// MCF3M Unit 1 worksheets — Quadratic Expressions & Equations.
// Examples carry full step-by-step solutions and TikZ graphs (\eplot, marked roots).
const r = String.raw;
const U = "1: Quadratic Expressions and Equations";

export default [
  {
    code: "1.1", unit: U, title: "Expanding & Simplifying Quadratic Expressions",
    intro: r`Expanding removes brackets; collect like terms into standard form $ax^2+bx+c$.`,
    ideas: [r`Distribute and FOIL: $(x+p)(x+q)=x^2+(p+q)x+pq$.`, r`Special products: $(a\pm b)^2=a^2\pm2ab+b^2$ and $(a-b)(a+b)=a^2-b^2$.`, r`Write the result in standard form.`],
    examples: [
      { t: "Distribute", body: r`Expand $3(x+4)$.\soln Multiply each term inside the bracket by $3$: \\ $3\cdot x+3\cdot4=3x+12$.` },
      { t: "Monomial times binomial", body: r`Expand $2x(x-5)$.\soln Distribute $2x$ to each term: \\ $2x\cdot x-2x\cdot5=2x^2-10x$.` },
      { t: "FOIL", body: r`Expand $(x+2)(x+3)$.\soln FOIL — First, Outer, Inner, Last: \\ $x^2+3x+2x+6$. \\ Collect like terms: $x^2+5x+6$. \\ The factored and expanded forms are the same parabola, with x-intercepts $-2$ and $-3$:` + r`\eplot{-5}{1}{-3}{8}{\addplot[exblue,very thick,domain=-4.7:0.7]{x^2+5*x+6};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-2,0) (-3,0)};}` },
      { t: "Perfect square", body: r`Expand $(x+5)^2$.\soln Write it out and FOIL: \\ $(x+5)(x+5)=x^2+5x+5x+25$. \\ Collect: $x^2+10x+25$. \\ The middle term is $2\cdot5\cdot x=10x$ — so it is not $x^2+25$.` },
      { t: "Difference of squares", body: r`Expand $(x-4)(x+4)$.\soln The outer and inner terms cancel: \\ $x^2+4x-4x-16=x^2-16$.` },
      { t: "General binomials", body: r`Expand $(2x-3)(x+5)$.\soln FOIL, watching the coefficient: \\ $2x^2+10x-3x-15$. \\ Collect: $2x^2+7x-15$.` },
      { t: "Square a binomial", body: r`Expand $(3x+2)^2$.\soln Square the binomial: \\ $(3x)^2+2(3x)(2)+(2)^2$ \\ $=9x^2+12x+4$.` },
      { t: "Collect like terms", body: r`Simplify $2x(x+1)+x(x-3)$.\soln Distribute each product: \\ $2x^2+2x+x^2-3x$. \\ Collect like terms: $3x^2-x$.` },
      { t: "Negative constant", body: r`Expand $(x-6)(x+2)$.\soln FOIL: \\ $x^2+2x-6x-12=x^2-4x-12$. \\ This parabola has x-intercepts $6$ and $-2$ and vertex $(2,-16)$:` + r`\eplot{-4}{8}{-18}{10}{\addplot[exblue,very thick,domain=-3:7]{x^2-4*x-12};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(6,0) (-2,0)};}` },
    ],
    questions: [
      { ask: r`Expand $5(x-2)$.` },
      { ask: r`Expand $x(3x+4)$.` },
      { ask: r`Expand $(x+4)(x+5)$.` },
      { ask: r`Expand $(x-7)^2$.` },
      { ask: r`Expand $(x-3)(x+3)$.` },
      { ask: r`Expand $(2x+1)(x+3)$.` },
      { ask: r`Expand $(3x-2)^2$.` },
      { ask: r`Expand $-2(x^2-3x+1)$.` },
      { ask: r`Expand $(x+5)(x-2)$.` },
      { ask: r`Expand $x(x+2)+3(x+2)$.` },
      { ask: r`Expand $(4x-1)(4x+1)$.` },
      { ask: r`Expand $2(x+3)^2$.` },
      { ask: r`Expand and simplify $(x+2)(x+3)-(x+1)(x-1)$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$5x-10$`, r`$3x^2+4x$`, r`$x^2+9x+20$`, r`$x^2-14x+49$`, r`$x^2-9$`, r`$2x^2+7x+3$`, r`$9x^2-12x+4$`, r`$-2x^2+6x-2$`, r`$x^2+3x-10$`, r`$x^2+5x+6$`, r`$16x^2-1$`, r`$2x^2+12x+18$`, r`$5x+7$`],
  },
  {
    code: "1.2", unit: U, title: "Factoring Quadratic Expressions",
    intro: r`Factoring reverses expanding. Look for a common factor first, then a pattern.`,
    ideas: [r`Pull out the GCF first.`, r`$x^2+bx+c=(x+p)(x+q)$ with $p+q=b,\ pq=c$; use decomposition for $ax^2+bx+c$.`, r`Special: $a^2-b^2=(a-b)(a+b)$ and $a^2\pm2ab+b^2=(a\pm b)^2$.`],
    examples: [
      { t: "Common factor", body: r`Factor $6x^2+9x$.\soln The GCF of $6x^2$ and $9x$ is $3x$: \\ $3x(2x+3)$. \\ Check: $3x\cdot2x+3x\cdot3=6x^2+9x$. \checkmark` },
      { t: "Simple trinomial", body: r`Factor $x^2+7x+12$.\soln Find two numbers with product $12$ and sum $7$: $3$ and $4$. \\ $(x+3)(x+4)$.` },
      { t: "Negative constant", body: r`Factor $x^2-x-6$.\soln Product $-6$, sum $-1$: $-3$ and $2$. \\ $(x-3)(x+2)$.` },
      { t: "Leading coefficient", body: r`Factor $2x^2+7x+3$.\soln Decomposition: $a\cdot c=6$; two numbers with product $6$, sum $7$ are $6,1$. \\ Split: $2x^2+6x+x+3$. \\ Group: $2x(x+3)+1(x+3)=(2x+1)(x+3)$.` },
      { t: "Difference of squares", body: r`Factor $x^2-25$.\soln Both terms are perfect squares: $x^2-5^2$. \\ $(x-5)(x+5)$. \\ The graph crosses the x-axis at $x=\pm5$:` + r`\eplot{-8}{8}{-28}{12}{\addplot[exblue,very thick,domain=-6:6]{x^2-25};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(5,0) (-5,0)};}` },
      { t: "Perfect square", body: r`Factor $x^2-10x+25$.\soln First and last are squares ($x^2$, $5^2$); the middle is $2\cdot5\cdot x=10x$. \\ $(x-5)^2$.` },
      { t: "Decomposition", body: r`Factor $3x^2+13x-10$.\soln $a\cdot c=-30$; product $-30$, sum $13$ are $15,-2$. \\ $3x^2+15x-2x-10=3x(x+5)-2(x+5)=(3x-2)(x+5)$.` },
      { t: "Perfect square (ax)", body: r`Factor $9x^2+24x+16$.\soln $(3x)^2$, $(4)^2$, middle $2\cdot3x\cdot4=24x$. \\ $(3x+4)^2$.` },
      { t: "Difference of squares (ax)", body: r`Factor $4x^2-9$.\soln $(2x)^2-(3)^2$. \\ $(2x-3)(2x+3)$.` },
    ],
    questions: [
      { ask: r`Factor $4x^2+8x$.` },
      { ask: r`Factor $x^2+9x+20$.` },
      { ask: r`Factor $x^2-2x-15$.` },
      { ask: r`Factor $x^2-36$.` },
      { ask: r`Factor $x^2+6x+9$.` },
      { ask: r`Factor $2x^2+5x+2$.` },
      { ask: r`Factor $3x^2-10x+3$.` },
      { ask: r`Factor $x^2-11x+30$.` },
      { ask: r`Factor $5x^2-20$.` },
      { ask: r`Factor $x^2+4x-21$.` },
      { ask: r`Factor $16x^2-25$.` },
      { ask: r`Factor $6x^2+x-2$.` },
      { ask: r`Factor fully $2x^2-18$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$4x(x+2)$`, r`$(x+4)(x+5)$`, r`$(x-5)(x+3)$`, r`$(x-6)(x+6)$`, r`$(x+3)^2$`, r`$(2x+1)(x+2)$`, r`$(3x-1)(x-3)$`, r`$(x-5)(x-6)$`, r`$5(x-2)(x+2)$`, r`$(x+7)(x-3)$`, r`$(4x-5)(4x+5)$`, r`$(3x+2)(2x-1)$`, r`$2(x-3)(x+3)$`],
  },
  {
    code: "1.3", unit: U, title: "Solving Quadratic Equations by Factoring",
    intro: r`Solve $ax^2+bx+c=0$ by factoring and the zero product property; the roots are the x-intercepts.`,
    ideas: [r`Rearrange so one side is $0$.`, r`Factor, then set each factor to $0$.`, r`Solutions are where the parabola meets the x-axis.`],
    examples: [
      { t: "Simple trinomial", body: r`Solve $x^2-5x+6=0$.\soln Factor: $(x-2)(x-3)=0$. \\ Zero product property: $x-2=0$ or $x-3=0$. \\ $x=2$ or $x=3$ — the x-intercepts of the parabola:` + r`\eplot{-1}{6}{-2}{8}{\addplot[exblue,very thick,domain=0:5]{x^2-5*x+6};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(2,0) (3,0)};}` },
      { t: "Difference of squares", body: r`Solve $x^2-9=0$.\soln $(x-3)(x+3)=0$. \\ $x=3$ or $x=-3$, i.e. $x=\pm3$.` },
      { t: "Negative constant", body: r`Solve $x^2+2x-8=0$.\soln Factor $(x+4)(x-2)=0$. \\ $x=-4$ or $x=2$.` },
      { t: "Leading coefficient", body: r`Solve $2x^2-7x+3=0$.\soln Factor $(2x-1)(x-3)=0$. \\ $2x-1=0\Rightarrow x=\tfrac12$; $\ x-3=0\Rightarrow x=3$.` },
      { t: "Common factor", body: r`Solve $x^2-6x=0$.\soln Common factor $x$: $x(x-6)=0$. \\ $x=0$ or $x=6$. The parabola passes through the origin and $(6,0)$:` + r`\eplot{-2}{8}{-12}{8}{\addplot[exblue,very thick,domain=-1:7]{x^2-6*x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,0) (6,0)};}` },
      { t: "Both negative", body: r`Solve $x^2+7x+10=0$.\soln $(x+2)(x+5)=0$. \\ $x=-2$ or $x=-5$.` },
      { t: "Mixed signs", body: r`Solve $x^2-x-12=0$.\soln Product $-12$, sum $-1$: $-4$ and $3$. $(x-4)(x+3)=0$. \\ $x=4$ or $x=-3$.` },
      { t: "Decomposition", body: r`Solve $3x^2-5x-2=0$.\soln $a\cdot c=-6$: $-6,1$. $3x^2-6x+x-2=(3x+1)(x-2)=0$. \\ $x=-\tfrac13$ or $x=2$.` },
      { t: "Larger squares", body: r`Solve $x^2-49=0$.\soln $(x-7)(x+7)=0$. \\ $x=\pm7$.` },
    ],
    questions: [
      { ask: r`Solve $x^2-7x+10=0$.` },
      { ask: r`Solve $x^2-16=0$.` },
      { ask: r`Solve $x^2+5x+6=0$.` },
      { ask: r`Solve $x^2-3x-10=0$.` },
      { ask: r`Solve $2x^2-3x-2=0$.` },
      { ask: r`Solve $x^2-8x=0$.` },
      { ask: r`Solve $x^2+x-20=0$.` },
      { ask: r`Solve $x^2-25=0$.` },
      { ask: r`Solve $3x^2+5x-2=0$.` },
      { ask: r`Solve $x^2-10x+24=0$.` },
      { ask: r`Solve $4x^2-9=0$.` },
      { ask: r`Solve $x^2+2x-15=0$.` },
      { ask: r`Solve $2x^2-x-6=0$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$x=2,5$`, r`$x=\pm4$`, r`$x=-2,-3$`, r`$x=5,-2$`, r`$x=2,-\tfrac12$`, r`$x=0,8$`, r`$x=4,-5$`, r`$x=\pm5$`, r`$x=\tfrac13,-2$`, r`$x=4,6$`, r`$x=\pm\tfrac32$`, r`$x=3,-5$`, r`$x=2,-\tfrac32$`],
  },
  {
    code: "1.4", unit: U, title: "The Quadratic Formula & the Discriminant",
    intro: r`Use $x=\dfrac{-b\pm\sqrt{b^2-4ac}}{2a}$; the discriminant $b^2-4ac$ gives the number of real roots.`,
    ideas: [r`The formula solves any quadratic.`, r`Discriminant: $>0$ two roots, $=0$ one, $<0$ none.`, r`Use the formula when the quadratic will not factor over the integers.`],
    examples: [
      { t: "Apply the formula", body: r`Solve $x^2-4x+1=0$.\soln Here $a=1,\ b=-4,\ c=1$. \\ $x=\dfrac{4\pm\sqrt{16-4}}{2}=\dfrac{4\pm\sqrt{12}}{2}$. \\ Since $\sqrt{12}=2\sqrt3$: $\ x=2\pm\sqrt3$.` },
      { t: "Leading coefficient", body: r`Solve $2x^2+3x-2=0$.\soln $a=2,\ b=3,\ c=-2$; discriminant $=9+16=25$. \\ $x=\dfrac{-3\pm5}{4}=\tfrac12$ or $-2$.` },
      { t: "No real roots", body: r`How many real roots has $x^2+2x+5=0$?\soln Discriminant $=4-20=-16<0$. \\ No real roots — the parabola never reaches the x-axis:` + r`\eplot{-6}{4}{-1}{12}{\addplot[exblue,very thick,domain=-5:3]{x^2+2*x+5};}` },
      { t: "One (double) root", body: r`How many real roots has $x^2-6x+9=0$?\soln Discriminant $=36-36=0$ — one (double) root. \\ $(x-3)^2=0\Rightarrow x=3$, where the vertex touches the axis:` + r`\eplot{-1}{7}{-1}{10}{\addplot[exblue,very thick,domain=0:6]{x^2-6*x+9};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(3,0)};}` },
      { t: "Irrational roots", body: r`Solve $x^2+x-1=0$.\soln $a=1,\ b=1,\ c=-1$. \\ $x=\dfrac{-1\pm\sqrt{1+4}}{2}=\dfrac{-1\pm\sqrt5}{2}$.` },
      { t: "Irrational roots", body: r`Solve $x^2-2x-1=0$.\soln $x=\dfrac{2\pm\sqrt{4+4}}{2}=\dfrac{2\pm2\sqrt2}{2}=1\pm\sqrt2$.` },
      { t: "Irrational roots", body: r`Solve $x^2-6x+7=0$.\soln $x=\dfrac{6\pm\sqrt{36-28}}{2}=\dfrac{6\pm2\sqrt2}{2}=3\pm\sqrt2$.` },
      { t: "Discriminant", body: r`Find the discriminant of $3x^2-5x+1$.\soln $b^2-4ac=25-12=13$. \\ Since $13>0$, there are two real roots.` },
      { t: "Simplify the root", body: r`Solve $2x^2-4x+1=0$.\soln $x=\dfrac{4\pm\sqrt{16-8}}{4}=\dfrac{4\pm2\sqrt2}{4}=\dfrac{2\pm\sqrt2}{2}$. \\ Two x-intercepts near $0.29$ and $1.71$:` + r`\eplot{-1}{4}{-2}{6}{\addplot[exblue,very thick,domain=-0.3:2.3]{2*x^2-4*x+1};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0.29,0) (1.71,0)};}` },
    ],
    questions: [
      { ask: r`Solve $x^2-2x-1=0$.` },
      { ask: r`Find the discriminant of $x^2-4x+4$.` },
      { ask: r`Solve $3x^2-5x-2=0$.` },
      { ask: r`How many real roots has $2x^2+x+3=0$?` },
      { ask: r`Solve $x^2-6x+7=0$.` },
      { ask: r`Find the discriminant of $x^2+x+1$.` },
      { ask: r`Solve $x^2+4x+2=0$.` },
      { ask: r`How many real roots has $x^2-10x+25=0$?` },
      { ask: r`Solve $2x^2-3x-1=0$.` },
      { ask: r`Find the discriminant of $5x^2-2x-1$.` },
      { ask: r`Solve $x^2-8x+13=0$.` },
      { ask: r`How many real roots has $4x^2-12x+9=0$?` },
      { ask: r`For what value of $k$ does $x^2-6x+k=0$ have exactly one root?`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$x=1\pm\sqrt2$`, r`$0$`, r`$x=2,-\tfrac13$`, r`none ($D<0$)`, r`$x=3\pm\sqrt2$`, r`$-3$`, r`$x=-2\pm\sqrt2$`, r`one ($D=0$)`, r`$x=\dfrac{3\pm\sqrt{17}}{4}$`, r`$24$`, r`$x=4\pm\sqrt3$`, r`one ($D=0$)`, r`$k=9$`],
  },
  {
    code: "1.5", unit: U, title: "Roots and x-Intercepts",
    intro: r`The real roots of $ax^2+bx+c=0$ are the x-intercepts of $y=ax^2+bx+c$.`,
    ideas: [r`$D>0$ two x-intercepts, $D=0$ one, $D<0$ none.`, r`A double root means the vertex sits on the x-axis.`, r`Factoring and graphing agree because both find where $y=0$.`],
    examples: [
      { t: "Two intercepts", body: r`Find the x-intercepts of $y=x^2-4x+3$.\soln Set $y=0$ and factor: $(x-1)(x-3)=0$. \\ $x=1$ and $x=3$:` + r`\eplot{-1}{6}{-2}{8}{\addplot[exblue,very thick,domain=0:5]{x^2-4*x+3};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(1,0) (3,0)};}` },
      { t: "One intercept", body: r`How many x-intercepts has $y=x^2-6x+9$?\soln $(x-3)^2$ — a double root; discriminant $=0$. \\ One x-intercept, at $x=3$.` },
      { t: "No intercepts", body: r`How many x-intercepts has $y=x^2+1$?\soln Discriminant $=0-4=-4<0$. \\ None — the parabola sits entirely above the x-axis:` + r`\eplot{-4}{4}{-1}{10}{\addplot[exblue,very thick,domain=-3:3]{x^2+1};}` },
      { t: "Count from D", body: r`How many x-intercepts has $y=2x^2-3x-5$?\soln Discriminant $=9+40=49>0$. \\ Two x-intercepts.` },
      { t: "Application — profit", body: r`Profit (in $\$1000$s) is $P=-5x^2+550x-5000$, where $x$ is advertising (in $\$1000$s). Where is $P=0$?\soln Factor out $-5$: $-5(x^2-110x+1000)$. \\ Factor: $-5(x-10)(x-100)=0$. \\ $x=10$ or $x=100$ (thousand dollars).` },
      { t: "Factor to intercepts", body: r`Find the x-intercepts of $y=x^2-x-6$.\soln $(x-3)(x+2)=0$. \\ $x=3$ and $x=-2$.` },
      { t: "Difference of squares", body: r`Find the x-intercepts of $y=x^2-9$.\soln $(x-3)(x+3)=0$. \\ $x=\pm3$.` },
      { t: "No intercepts", body: r`How many x-intercepts has $y=x^2-2x+5$?\soln Discriminant $=4-20=-16<0$. \\ None.` },
      { t: "Double root", body: r`How many x-intercepts has $y=4x^2-12x+9$?\soln $(2x-3)^2$, discriminant $=0$. \\ One, at $x=\tfrac32$:` + r`\eplot{-1}{4}{-1}{10}{\addplot[exblue,very thick,domain=0:3]{4*x^2-12*x+9};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(1.5,0)};}` },
    ],
    questions: [
      { ask: r`Find the x-intercepts of $y=x^2-5x+6$.` },
      { ask: r`How many x-intercepts has $y=x^2+4$?` },
      { ask: r`How many x-intercepts has $y=x^2-6x+9$?` },
      { ask: r`Find the x-intercepts of $y=x^2-16$.` },
      { ask: r`How many x-intercepts has $y=x^2+x-12$?` },
      { ask: r`Find the x-intercepts of $y=x^2+2x-8$.` },
      { ask: r`How many x-intercepts has $y=3x^2+2x+1$?` },
      { ask: r`Find the x-intercepts of $y=2x^2-5x-3$.` },
      { ask: r`How many x-intercepts has $y=x^2-10x+25$?` },
      { ask: r`Find the x-intercepts of $y=x^2-2x-3$.` },
      { ask: r`How many x-intercepts has $y=x^2-4x+5$?` },
      { ask: r`A profit model is $P=-2x^2+12x-10$. Where is $P=0$?` },
      { ask: r`A parabola's vertex sits on the x-axis. What is its discriminant?`, challenge: true, ws: "2.6cm" },
    ],
    answers: [r`$x=2,3$`, r`none`, r`one ($x=3$)`, r`$x=\pm4$`, r`two`, r`$x=-4,2$`, r`none`, r`$x=3,-\tfrac12$`, r`one ($x=5$)`, r`$x=3,-1$`, r`none`, r`$x=1,5$`, r`$0$`],
  },
];
