// MCF3M Unit 2 worksheets — Quadratic Functions.
// Examples: full step-by-step solutions with TikZ parabola graphs (\eplot).
const r = String.raw;
const U = "2: Quadratic Functions";

export default [
  {
    code: "2.1", unit: U, title: "Functions, Function Notation, Domain & Range",
    intro: r`A function gives one output per input; $f(x)$ is the output at $x$. State the domain and range.`,
    ideas: [r`Vertical-line test: a function meets any vertical line at most once.`, r`Evaluate by substituting for every $x$.`, r`A quadratic has domain all reals; its range starts (or ends) at the vertex.`],
    examples: [
      { t: "Function or not", body: r`Is $\{(1,2),(2,4),(3,6)\}$ a function?\soln Check each input: $1\to2$, $2\to4$, $3\to6$. \\ Every input has exactly one output, so \textbf{yes}.` },
      { t: "Evaluate", body: r`For $f(x)=2x^2+3x-1$, find $f(2)$.\soln Substitute $x=2$: \\ $2(2)^2+3(2)-1=8+6-1=13$.` },
      { t: "Negative input", body: r`Find $f(-1)$ for the same $f$.\soln Substitute $x=-1$: \\ $2(-1)^2+3(-1)-1=2-3-1=-2$.` },
      { t: "Domain & range", body: r`State the domain and range of $f(x)=x^2+1$.\soln Any $x$ is allowed, so the domain is all real numbers. \\ The vertex $(0,1)$ is the lowest point, so the range is $y\ge1$:` + r`\eplot{-3}{3}{-1}{8}{\addplot[exblue,very thick,domain=-2.6:2.6]{x^2+1};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,1)};}` },
      { t: "Application", body: r`Revenue is $r(s)=-10s^2+1500s$. Find $r(60)$.\soln Substitute $s=60$: \\ $-10(60)^2+1500(60)=-36000+90000=\$54\,000$.` },
      { t: "Evaluate", body: r`For $f(x)=x^2-4$, find $f(3)$.\soln $f(3)=(3)^2-4=9-4=5$.` },
      { t: "Solve", body: r`For $f(x)=5-2x$, solve $f(x)=1$.\soln Set $5-2x=1$: \\ $-2x=-4\Rightarrow x=2$.` },
      { t: "Range", body: r`State the range of $y=-x^2+5$.\soln The graph opens down with vertex $(0,5)$ as the highest point. \\ Range: $y\le5$:` + r`\eplot{-4}{4}{-4}{7}{\addplot[exblue,very thick,domain=-3:3]{-x^2+5};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,5)};}` },
      { t: "Not a function", body: r`Is $x=y^2$ a function?\soln Solve for $y$: $y=\pm\sqrt{x}$, so $x=4$ gives $y=2$ \emph{and} $y=-2$. \\ One input, two outputs — \textbf{not} a function.` },
    ],
    questions: [
      { ask: r`For $f(x)=3x-2$, find $f(5)$.` },
      { ask: r`For $f(x)=x^2+1$, find $f(4)$.` },
      { ask: r`Is $\{(2,1),(3,1),(4,1)\}$ a function?` },
      { ask: r`State the range of $y=x^2-3$.` },
      { ask: r`For $f(x)=x^2-2x$, find $f(5)$.` },
      { ask: r`State the domain of $y=2x+1$.` },
      { ask: r`For $f(x)=4-x^2$, find $f(2)$.` },
      { ask: r`For $f(x)=2x-6$, solve $f(x)=0$.` },
      { ask: r`State the range of $y=-x^2+2$.` },
      { ask: r`Is $x=y^2$ a function?` },
      { ask: r`For $f(x)=x^2-5x$, find $f(-2)$.` },
      { ask: r`State the range of $y=(x-1)^2+2$.` },
      { ask: r`Revenue $r(s)=-10s^2+1500s$. Find $r(75)$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$13$`, r`$17$`, r`yes`, r`$y\ge-3$`, r`$15$`, r`all reals`, r`$0$`, r`$x=3$`, r`$y\le2$`, r`no`, r`$14$`, r`$y\ge2$`, r`$\$56\,250$`],
  },
  {
    code: "2.2", unit: U, title: "Transformations & Vertex Form",
    intro: r`Vertex form $a(x-h)^2+k$ has vertex $(h,k)$; $a$ stretches/reflects, $h$ shifts horizontally, $k$ vertically.`,
    ideas: [r`$a$: stretch by $|a|$; reflect if $a<0$.`, r`$h$: horizontal shift (opposite to the sign). $k$: vertical shift.`, r`Vertex is $(h,k)$.`],
    examples: [
      { t: "Read the vertex", body: r`State the vertex of $y=(x-3)^2+2$.\soln In $a(x-h)^2+k$, $h=3$ and $k=2$. \\ Vertex $(3,2)$ — shifted right 3 and up 2:` + r`\eplot{-1}{7}{-1}{10}{\addplot[exblue,very thick,domain=0.5:5.5]{(x-3)^2+2};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(3,2)};}` },
      { t: "Describe", body: r`Describe $y=-2(x+1)^2+5$ from $y=x^2$.\soln $a=-2$: reflect in the x-axis and stretch by 2. \\ $h=-1$: left 1. $k=5$: up 5.` },
      { t: "Negative h", body: r`State the vertex of $y=(x+4)^2-2$.\soln $h=-4$, $k=-2$: vertex $(-4,-2)$.` },
      { t: "Direction & max", body: r`For $y=-(x-2)^2+3$, state the direction and max.\soln $a=-1<0$, so it opens down; the vertex $(2,3)$ is the highest point. \\ Maximum value $3$:` + r`\eplot{-2}{6}{-6}{5}{\addplot[exblue,very thick,domain=-0.5:4.5]{-(x-2)^2+3};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(2,3)};}` },
      { t: "Write the equation", body: r`Write $y=x^2$ shifted right 5 and down 4.\soln Right 5 gives $h=5$; down 4 gives $k=-4$. \\ $y=(x-5)^2-4$.` },
      { t: "Read the vertex", body: r`State the vertex of $y=(x-1)^2-7$.\soln $h=1$, $k=-7$: vertex $(1,-7)$.` },
      { t: "Stretch & shift", body: r`Describe $y=3(x-2)^2$ from $y=x^2$.\soln $a=3$: stretch by 3. $h=2$: right 2.` },
      { t: "Vertex & direction", body: r`State the vertex and direction of $y=-2(x+3)^2+1$.\soln $h=-3$, $k=1$: vertex $(-3,1)$; $a=-2<0$ opens down.` },
      { t: "Min value", body: r`State the min of $y=(x-4)^2+6$.\soln $a=1>0$ opens up, so the vertex $(4,6)$ is the lowest point. \\ Minimum value $6$.` },
    ],
    questions: [
      { ask: r`State the vertex of $y=(x-2)^2+5$.` },
      { ask: r`State the vertex of $y=(x+1)^2-3$.` },
      { ask: r`Describe $y=-(x-4)^2$ from $y=x^2$.` },
      { ask: r`Write $y=x^2$ shifted left 3 and up 2.` },
      { ask: r`State the max or min value of $y=(x-5)^2+1$.` },
      { ask: r`State the vertex of $y=-2(x-1)^2+8$.` },
      { ask: r`Does $y=-3(x+2)^2-1$ open up or down?` },
      { ask: r`Describe $y=2(x+5)^2-4$ from $y=x^2$.` },
      { ask: r`State the vertex of $y=4(x-3)^2$.` },
      { ask: r`State the max value of $y=-(x+1)^2+10$.` },
      { ask: r`Write $y=x^2$ reflected in the x-axis and up 6.` },
      { ask: r`State the stretch factor of $y=5(x-2)^2+1$.` },
      { ask: r`A parabola has vertex $(2,-3)$ and passes through $(0,5)$. Find $a$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$(2,5)$`, r`$(-1,-3)$`, r`reflect, right 4`, r`$y=(x+3)^2+2$`, r`min 1`, r`$(1,8)$`, r`down`, r`stretch 2, left 5, down 4`, r`$(3,0)$`, r`10`, r`$y=-x^2+6$`, r`$5$`, r`$a=2$`],
  },
  {
    code: "2.3", unit: U, title: "Completing the Square",
    intro: r`Completing the square turns $ax^2+bx+c$ into vertex form $a(x-h)^2+k$.`,
    ideas: [r`Add the square of half the $x$-coefficient (and subtract it).`, r`If $a\ne1$, factor $a$ from the $x^2$ and $x$ terms first.`, r`Vertex is $(h,k)$.`],
    examples: [
      { t: "Basic", body: r`Complete the square: $x^2+6x+5$.\soln Half of $6$ is $3$; $3^2=9$: \\ $x^2+6x+9-9+5=(x+3)^2-4$. \\ Vertex $(-3,-4)$:` + r`\eplot{-7}{1}{-6}{8}{\addplot[exblue,very thick,domain=-6.5:0.5]{x^2+6*x+5};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-3,-4)};}` },
      { t: "Negative middle", body: r`Complete the square: $x^2-4x+1$.\soln Half of $-4$ is $-2$; $(-2)^2=4$: \\ $x^2-4x+4-4+1=(x-2)^2-3$.` },
      { t: "Larger constant", body: r`Complete the square: $x^2+8x+10$.\soln Half of $8$ is $4$; $4^2=16$: \\ $(x+4)^2-16+10=(x+4)^2-6$.` },
      { t: "Leading coefficient", body: r`Complete the square: $2x^2-12x+5$.\soln Factor 2 from the $x$-terms: $2(x^2-6x)+5$. \\ Inside: $x^2-6x=(x-3)^2-9$. \\ $2((x-3)^2-9)+5=2(x-3)^2-13$. Vertex $(3,-13)$.` },
      { t: "Vertex to standard", body: r`Expand $(x-1)^2+4$.\soln $(x-1)^2=x^2-2x+1$, so \\ $x^2-2x+1+4=x^2-2x+5$.` },
      { t: "Negative constant", body: r`Complete the square: $x^2+2x-3$.\soln Half of $2$ is $1$: \\ $(x+1)^2-1-3=(x+1)^2-4$.` },
      { t: "No constant", body: r`Complete the square: $x^2-10x$.\soln Half of $-10$ is $-5$; $25$: \\ $(x-5)^2-25$.` },
      { t: "Leading coefficient", body: r`Complete the square: $2x^2+8x+3$.\soln $2(x^2+4x)+3=2((x+2)^2-4)+3=2(x+2)^2-5$.` },
      { t: "Find the vertex", body: r`Find the vertex of $y=x^2-6x+5$.\soln $x^2-6x+9-9+5=(x-3)^2-4$. \\ Vertex $(3,-4)$:` + r`\eplot{-1}{7}{-6}{8}{\addplot[exblue,very thick,domain=-0.5:6.5]{x^2-6*x+5};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(3,-4)};}` },
    ],
    questions: [
      { ask: r`Complete the square: $x^2+4x+1$.` },
      { ask: r`Complete the square: $x^2-2x-5$.` },
      { ask: r`Find the vertex of $y=x^2+6x+5$.` },
      { ask: r`Complete the square: $x^2-8x+10$.` },
      { ask: r`Complete the square: $2x^2-8x+3$.` },
      { ask: r`Write $(x+3)^2-2$ in standard form.` },
      { ask: r`Complete the square: $x^2+10x$.` },
      { ask: r`Find the vertex of $y=x^2-4x+1$.` },
      { ask: r`Complete the square: $3x^2-6x+1$.` },
      { ask: r`State the minimum of $y=x^2+6x+5$.` },
      { ask: r`Complete the square: $x^2-12x+40$.` },
      { ask: r`Write $2(x-1)^2+3$ in standard form.` },
      { ask: r`Complete the square for $y=-x^2+4x+1$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$(x+2)^2-3$`, r`$(x-1)^2-6$`, r`$(-3,-4)$`, r`$(x-4)^2-6$`, r`$2(x-2)^2-5$`, r`$x^2+6x+7$`, r`$(x+5)^2-25$`, r`$(2,-3)$`, r`$3(x-1)^2-2$`, r`$-4$`, r`$(x-6)^2+4$`, r`$2x^2-4x+5$`, r`$-(x-2)^2+5$`],
  },
  {
    code: "2.4", unit: U, title: "Factored Form & Graphing",
    intro: r`In factored form $a(x-r)(x-s)$ the x-intercepts are $r,s$; the axis is $x=\dfrac{r+s}{2}$.`,
    ideas: [r`Set each factor to $0$ for the x-intercepts.`, r`The axis of symmetry is midway between them; substitute it back for the vertex.`, r`The y-intercept is found by setting $x=0$.`],
    examples: [
      { t: "Intercepts & axis", body: r`For $y=(x-1)(x-5)$, find the x-intercepts and axis.\soln Set each factor to $0$: $x=1$ and $x=5$. \\ Axis of symmetry: $x=\dfrac{1+5}{2}=3$:` + r`\eplot{-1}{7}{-6}{8}{\addplot[exblue,very thick,domain=0:6]{x^2-6*x+5};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(1,0) (5,0) (3,-4)};}` },
      { t: "Vertex", body: r`Find the vertex of $y=(x-1)(x-5)$.\soln Axis $x=3$. Substitute: $y=(3-1)(3-5)=(2)(-2)=-4$. \\ Vertex $(3,-4)$.` },
      { t: "Factor first", body: r`Find the x-intercepts of $y=x^2-2x-3$.\soln Factor: $(x-3)(x+1)$. \\ $x=3$ and $x=-1$; axis $x=1$.` },
      { t: "Leading coefficient", body: r`For $y=2(x+2)(x-4)$, find the x-intercepts and vertex.\soln Intercepts $x=-2,4$; axis $x=1$. \\ $y=2(1+2)(1-4)=2(3)(-3)=-18$. Vertex $(1,-18)$:` + r`\eplot{-4}{6}{-20}{12}{\addplot[exblue,very thick,domain=-3:5]{2*x^2-4*x-16};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-2,0) (4,0) (1,-18)};}` },
      { t: "y-intercept", body: r`Find the y-intercept of $y=(x-1)(x-5)$.\soln Set $x=0$: $(0-1)(0-5)=(-1)(-5)=5$. \\ y-intercept $(0,5)$.` },
      { t: "Intercepts & axis", body: r`For $y=(x+2)(x-6)$, find the intercepts and axis.\soln $x=-2,6$; axis $x=\dfrac{-2+6}{2}=2$.` },
      { t: "Vertex", body: r`Find the vertex of $y=(x-2)(x-8)$.\soln Axis $x=5$; $y=(5-2)(5-8)=(3)(-3)=-9$. Vertex $(5,-9)$.` },
      { t: "Difference of squares", body: r`Find the x-intercepts and axis of $y=x^2-9$.\soln $(x-3)(x+3)=0$: $x=\pm3$; axis $x=0$.` },
      { t: "y-intercept", body: r`Find the y-intercept of $y=(x-3)(x+4)$.\soln Set $x=0$: $(-3)(4)=-12$. y-intercept $(0,-12)$.` },
    ],
    questions: [
      { ask: r`Find the x-intercepts of $y=(x-2)(x-6)$.` },
      { ask: r`Find the axis of symmetry of $y=(x-2)(x-6)$.` },
      { ask: r`Find the vertex of $y=(x-2)(x-6)$.` },
      { ask: r`Find the y-intercept of $y=(x+1)(x-5)$.` },
      { ask: r`Find the x-intercepts of $y=x^2+x-12$.` },
      { ask: r`Find the axis of symmetry of $y=x^2+x-12$.` },
      { ask: r`Find the x-intercepts of $y=3(x-1)(x+3)$.` },
      { ask: r`Find the y-intercept of $y=(x-4)(x-2)$.` },
      { ask: r`Find the vertex of $y=(x+1)(x-7)$.` },
      { ask: r`Find the x-intercepts of $y=x^2-16$.` },
      { ask: r`Find the axis of symmetry of $y=(x-3)(x+5)$.` },
      { ask: r`Find the y-intercept of $y=2(x-1)(x-3)$.` },
      { ask: r`A parabola has x-intercepts 2 and 6 and passes through $(4,-8)$. Find $a$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$x=2,6$`, r`$x=4$`, r`$(4,-4)$`, r`$(0,-5)$`, r`$x=3,-4$`, r`$x=-\tfrac12$`, r`$x=1,-3$`, r`$(0,8)$`, r`$(3,-16)$`, r`$x=\pm4$`, r`$x=-1$`, r`$(0,6)$`, r`$a=2$`],
  },
  {
    code: "2.5", unit: U, title: "Maximum/Minimum Problems & Applications",
    intro: r`The vertex gives the maximum (if $a<0$) or minimum (if $a>0$). Find it with $x=-\dfrac{b}{2a}$.`,
    ideas: [r`$a>0$ gives a minimum; $a<0$ gives a maximum.`, r`The max/min is the $y$-value of the vertex.`, r`Set up a quadratic model, then find the vertex.`],
    examples: [
      { t: "Read a max", body: r`Find the maximum of $y=-(x-3)^2+9$.\soln $a=-1<0$ opens down; the vertex $(3,9)$ is the highest point. \\ Maximum value $9$ at $x=3$:` + r`\eplot{-1}{7}{-2}{11}{\addplot[exblue,very thick,domain=0:6]{-(x-3)^2+9};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(3,9)};}` },
      { t: "Find a min", body: r`Find the minimum of $y=x^2-6x+5$.\soln Vertex $x=-\dfrac{-6}{2}=3$; $y=9-18+5=-4$. \\ Minimum value $-4$:` + r`\eplot{-1}{7}{-6}{8}{\addplot[exblue,very thick,domain=-0.5:6.5]{x^2-6*x+5};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(3,-4)};}` },
      { t: "Max height", body: r`A ball's height is $h=-5t^2+20t$. Find the maximum height.\soln Vertex $t=-\dfrac{20}{2(-5)}=2$; $h=-5(4)+40=20$. \\ Maximum height $20$ m at $t=2$ s:` + r`\eplot{-0.5}{4.5}{-2}{24}{\addplot[exblue,very thick,domain=0:4]{-5*x^2+20*x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(2,20)};}` },
      { t: "Max profit", body: r`Profit is $P=-2x^2+12x-10$. Find the maximum profit.\soln Vertex $x=-\dfrac{12}{2(-2)}=3$; $P=-2(9)+36-10=8$. \\ Maximum profit $8$.` },
      { t: "Max area", body: r`A rectangle has perimeter 20 m. What dimensions give the maximum area?\soln Width $w$, length $10-w$; $A=w(10-w)=10w-w^2$. \\ Vertex $w=5$, so $5\times5$, area $25$ m\textsuperscript{2}.` },
      { t: "Read a max", body: r`Find the maximum of $y=-(x-2)^2+7$.\soln Vertex $(2,7)$, opens down: maximum $7$.` },
      { t: "Find a min", body: r`Find the minimum of $y=x^2-4x+1$.\soln Vertex $x=2$; $y=4-8+1=-3$. Minimum $-3$.` },
      { t: "Max height", body: r`$h=-5t^2+30t$. Find the maximum height.\soln $t=-\dfrac{30}{2(-5)}=3$; $h=-45+90=45$ m.` },
      { t: "Find a min", body: r`Find the minimum of $y=2x^2-8x+1$.\soln $x=-\dfrac{-8}{2(2)}=2$; $y=8-16+1=-7$. Minimum $-7$.` },
    ],
    questions: [
      { ask: r`Find the maximum of $y=-(x-1)^2+4$.` },
      { ask: r`Find the minimum of $y=x^2-2x+5$.` },
      { ask: r`A ball $h=-5t^2+10t$. Find the maximum height.` },
      { ask: r`Profit $P=-x^2+8x-7$. Find the maximum profit.` },
      { ask: r`Find the minimum of $y=x^2+4x+1$.` },
      { ask: r`A rectangle has perimeter 24 m. Find the maximum area.` },
      { ask: r`Find the maximum of $y=-2(x-3)^2+5$.` },
      { ask: r`Find the minimum of $y=3x^2-12x+2$.` },
      { ask: r`A ball $h=-5t^2+40t$. Find the maximum height.` },
      { ask: r`Find the minimum of $y=x^2-10x+30$.` },
      { ask: r`A rectangle's area is $A=w(20-w)$. Find the maximum area.` },
      { ask: r`Find the maximum of $y=-(x+2)^2+12$.` },
      { ask: r`A rectangular pen against a wall uses 60 m of fencing on three sides. Find the maximum area.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$4$`, r`$4$`, r`$5$ m (at $t=1$)`, r`$9$ (at $x=4$)`, r`$-3$`, r`$36$ m\textsuperscript{2} ($6\times6$)`, r`$5$`, r`$-10$ (at $x=2$)`, r`$80$ m (at $t=4$)`, r`$5$`, r`$100$ (at $w=10$)`, r`$12$`, r`$450$ m\textsuperscript{2} ($15\times30$)`],
  },
];
