// MCF3M Unit 3 worksheets — Exponential Functions.
// Examples: full step-by-step solutions with TikZ exponential curves (\eplot).
const r = String.raw;
const U = "3: Exponential Functions";

export default [
  {
    code: "3.1", unit: U, title: "Exponent Laws & Rational Exponents",
    intro: r`Exponent laws combine powers; extend them to zero, negative, and rational exponents.`,
    ideas: [r`Product $x^m x^n=x^{m+n}$; quotient $\dfrac{x^m}{x^n}=x^{m-n}$; power $(x^m)^n=x^{mn}$.`, r`$x^0=1$ and $x^{-n}=\dfrac{1}{x^n}$.`, r`$x^{m/n}=\left(\sqrt[n]{x}\right)^m$ — denominator is the root.`],
    examples: [
      { t: "Product", body: r`Simplify $x^5\cdot x^3$.\soln Product law — add the exponents: \\ $x^{5+3}=x^8$.` },
      { t: "Power of a power", body: r`Simplify $(x^4)^3$.\soln Multiply the exponents: \\ $x^{4\cdot3}=x^{12}$.` },
      { t: "Quotient", body: r`Simplify $\dfrac{x^9}{x^4}$.\soln Subtract the exponents: \\ $x^{9-4}=x^5$.` },
      { t: "Negative exponent", body: r`Evaluate $2^{-3}$.\soln A negative exponent means the reciprocal: \\ $\dfrac{1}{2^3}=\dfrac18$.` },
      { t: "Rational exponent", body: r`Evaluate $27^{2/3}$.\soln Root first, then power: \\ $\left(\sqrt[3]{27}\right)^2=3^2=9$.` },
      { t: "Power of a product", body: r`Simplify $(2x^3)^2$.\soln The exponent reaches both factors: \\ $2^2\cdot x^{3\cdot2}=4x^6$.` },
      { t: "Rational exponent", body: r`Evaluate $16^{3/4}$.\soln $\left(\sqrt[4]{16}\right)^3=2^3=8$.` },
      { t: "Zero exponent", body: r`Evaluate $x^0$ (for $x\ne0$).\soln From the quotient law $\dfrac{x^n}{x^n}=x^{0}$, and anything over itself is $1$. \\ So $x^0=1$.` },
      { t: "Negative rational", body: r`Evaluate $\left(\tfrac12\right)^{-2}$.\soln Reciprocal then square: $2^2=4$. \\ Bases $>1$ grow, bases between 0 and 1 decay:` + r`\eplot{-3}{3}{-1}{9}{\addplot[exblue,very thick,domain=-3:3]{2^x};\addplot[qorange,very thick,domain=-3:3]{0.5^x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,1)};}` },
    ],
    questions: [
      { ask: r`Simplify $x^6\cdot x^2$.` },
      { ask: r`Simplify $(x^3)^2$.` },
      { ask: r`Simplify $\dfrac{y^8}{y^3}$.` },
      { ask: r`Evaluate $5^{-2}$.` },
      { ask: r`Evaluate $16^{1/2}$.` },
      { ask: r`Evaluate $8^{1/3}$.` },
      { ask: r`Simplify $(3x^2)^3$.` },
      { ask: r`Simplify $\dfrac{x^{10}}{x^{7}}$.` },
      { ask: r`Evaluate $27^{1/3}$.` },
      { ask: r`Evaluate $4^{3/2}$.` },
      { ask: r`Evaluate $2^{-4}$.` },
      { ask: r`Simplify $(x^2 y^3)^2$.` },
      { ask: r`Simplify $\dfrac{x^{1/2}\cdot x^{3/2}}{x}$.`, challenge: true, ws: "2.6cm" },
    ],
    answers: [r`$x^8$`, r`$x^6$`, r`$y^5$`, r`$\dfrac{1}{25}$`, r`$4$`, r`$2$`, r`$27x^6$`, r`$x^3$`, r`$3$`, r`$8$`, r`$\dfrac{1}{16}$`, r`$x^4 y^6$`, r`$x$`],
  },
  {
    code: "3.2", unit: U, title: "Exponential Functions & Their Graphs",
    intro: r`$y=a\cdot b^x$ has y-intercept $(0,a)$, horizontal asymptote $y=0$, domain all reals, and range $y>0$.`,
    ideas: [r`$b>1$ grows; $0<b<1$ decays; a larger base is steeper.`, r`The y-intercept is $a$ (since $b^0=1$).`, r`A vertical shift $+c$ moves the asymptote to $y=c$.`],
    examples: [
      { t: "Evaluate", body: r`For $f(x)=2^x$, find $f(3)$.\soln $2^3=8$.` },
      { t: "y-intercept", body: r`State the y-intercept of $y=3\cdot2^x$.\soln At $x=0$, $2^0=1$, so $y=3(1)=3$. \\ y-intercept $(0,3)$.` },
      { t: "Growth or decay", body: r`Is $y=\left(\tfrac12\right)^x$ growth or decay?\soln The base is between 0 and 1, so the curve falls — decay:` + r`\eplot{-3}{3}{-1}{9}{\addplot[exblue,very thick,domain=-3:3]{0.5^x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,1)};}` },
      { t: "Asymptote", body: r`State the horizontal asymptote of $y=2^x$.\soln As $x\to-\infty$, $2^x\to0$ but never reaches it. \\ Asymptote $y=0$:` + r`\eplot{-4}{3}{-1}{9}{\addplot[exblue,very thick,domain=-4:3]{2^x};}` },
      { t: "Shifted asymptote", body: r`State the horizontal asymptote of $y=2^x+3$.\soln The $+3$ lifts the whole graph up 3. \\ Asymptote $y=3$ (dashed):` + r`\eplot{-4}{3}{-1}{11}{\addplot[red,dashed,domain=-4:3]{3};\addplot[exblue,very thick,domain=-4:3]{2^x+3};}` },
      { t: "Compare bases", body: r`Which grows faster, $y=2^x$ or $y=5^x$?\soln Both pass $(0,1)$; the larger base climbs faster. \\ $5^x$ grows faster.` },
      { t: "Domain & range", body: r`State the domain and range of $y=2^x$.\soln Any $x$ is allowed; outputs stay positive. \\ Domain all reals; range $y>0$.` },
      { t: "Negative input", body: r`Find $2^x$ at $x=-1$.\soln $2^{-1}=\dfrac12$.` },
      { t: "y-intercept", body: r`State the y-intercept of $y=5\cdot2^x$.\soln At $x=0$: $5\cdot1=5$. y-intercept $(0,5)$.` },
    ],
    questions: [
      { ask: r`Find $2^x$ at $x=4$.` },
      { ask: r`State the y-intercept of $y=4\cdot3^x$.` },
      { ask: r`Is $y=0.8^x$ growth or decay?` },
      { ask: r`State the asymptote of $y=3^x-2$.` },
      { ask: r`State the domain of $y=2^x$.` },
      { ask: r`State the range of $y=2^x$.` },
      { ask: r`Find $3^x$ at $x=2$.` },
      { ask: r`State the y-intercept of $y=2^x$.` },
      { ask: r`Is $y=2^x$ growth or decay?` },
      { ask: r`State the asymptote of $y=2^x+7$.` },
      { ask: r`Which is steeper, $2^x$ or $10^x$?` },
      { ask: r`Find $\left(\tfrac13\right)^x$ at $x=2$.` },
      { ask: r`A function $y=a\cdot b^x$ passes $(0,5)$ and $(1,15)$. Find $b$.`, challenge: true, ws: "2.6cm" },
    ],
    answers: [r`$16$`, r`$(0,4)$`, r`decay`, r`$y=-2$`, r`all reals`, r`$y>0$`, r`$9$`, r`$(0,1)$`, r`growth`, r`$y=7$`, r`$10^x$`, r`$\dfrac19$`, r`$b=3$`],
  },
  {
    code: "3.3", unit: U, title: "Exponential Growth & Decay Applications",
    intro: r`Model with $y=a\cdot b^t$: $a$ is the initial amount, $b=1+r$ for growth or $1-r$ for decay; half-life uses $\left(\tfrac12\right)^{t/h}$.`,
    ideas: [r`Growth factor $1+r$; decay factor $1-r$.`, r`Doubling: $b=2$. Half-life $h$: $b=\tfrac12$ over each period.`, r`Compound interest $A=P(1+i)^n$ is exponential.`],
    examples: [
      { t: "Doubling", body: r`$P=200(2)^t$. Find $P$ after 3 years.\soln $P=200(2)^3=200(8)=1600$. \\ Doubling has the shape of $y=2^x$ (each step multiplies by 2):` + r`\eplot{-1}{4}{-1}{9}{\addplot[exblue,very thick,domain=-1:3.2]{2^x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,1) (1,2) (2,4) (3,8)};}` },
      { t: "Half-life", body: r`80 g halves every 5 years. How much after 10 years?\soln Number of half-lives: $10\div5=2$. \\ $80\left(\tfrac12\right)^2=80\cdot\tfrac14=20$ g. \\ The fraction remaining follows $y=\left(\tfrac12\right)^x$:` + r`\eplot{-0.5}{5}{-0.5}{4}{\addplot[exblue,very thick,domain=0:5]{0.5^x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,1) (1,0.5) (2,0.25)};}` },
      { t: "Growth factor", body: r`A town grows $8\%$ per year. State the growth factor.\soln $b=1+0.08=1.08$.` },
      { t: "Decay factor", body: r`A car loses $15\%$ of its value each year. State the decay factor.\soln $b=1-0.15=0.85$.` },
      { t: "Compound interest", body: r`\$1000 grows at $5\%$/year for 2 years. Find its value.\soln $A=1000(1.05)^2=1000(1.1025)\approx\$1102.50$.` },
      { t: "Doubling", body: r`$P=200(2)^t$ after 4 years.\soln $200(2)^4=200(16)=3200$.` },
      { t: "Half-life", body: r`100 g halves every 3 h. How much after 9 h?\soln $9\div3=3$ half-lives: $100\left(\tfrac12\right)^3=12.5$ g.` },
      { t: "Growth factor", body: r`Growth of $5\%$ per year.\soln $b=1.05$.` },
      { t: "Compound interest", body: r`\$500 at $4\%$/year for 3 years.\soln $500(1.04)^3\approx\$562.43$.` },
    ],
    questions: [
      { ask: r`State the growth factor for $+10\%$ per year.` },
      { ask: r`State the decay factor for $-20\%$ per year.` },
      { ask: r`For $P=200(2)^t$, find $P$ after 2 years.` },
      { ask: r`80 g halves every 5 years. How much after 15 years?` },
      { ask: r`\$1000 at $5\%$/year for 3 years. Find the value.` },
      { ask: r`State the doubling factor.` },
      { ask: r`State the decay factor for $-5\%$ per year.` },
      { ask: r`100 g halves every 4 h. How much after 8 h?` },
      { ask: r`State the growth factor for $+12\%$ per year.` },
      { ask: r`\$2000 at $4\%$/year for 5 years. Find the value.` },
      { ask: r`For $P=50(3)^t$, find $P$ after 2 years.` },
      { ask: r`How much of 64 g remains after one half-life?` },
      { ask: r`A population triples every 4 h. Write the model with $t$ in hours.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$1.10$`, r`$0.80$`, r`$800$`, r`$10$ g`, r`$\approx\$1157.63$`, r`$2$`, r`$0.95$`, r`$25$ g`, r`$1.12$`, r`$\approx\$2433.31$`, r`$450$`, r`$32$ g`, r`$y=a\cdot3^{t/4}$`],
  },
];
