// MCF3M Unit 5 worksheets — Trigonometry.
// Examples: full step-by-step solutions with TikZ triangle figures (\rtri, \gtri).
const r = String.raw;
const U = "5: Trigonometry";

export default [
  {
    code: "5.1", unit: U, title: "Primary Trigonometric Ratios & Right Triangles",
    intro: r`SOH CAH TOA links an angle to two sides: $\sin\theta=\frac{\text{opp}}{\text{hyp}}$, $\cos\theta=\frac{\text{adj}}{\text{hyp}}$, $\tan\theta=\frac{\text{opp}}{\text{adj}}$.`,
    ideas: [r`Name the sides relative to the angle.`, r`Find a side: pick a ratio and multiply.`, r`Find an angle: use $\sin^{-1},\cos^{-1},\tan^{-1}$.`],
    examples: [
      { t: "A ratio", body: r`Opposite $=3$, hypotenuse $=5$. Find $\sin\theta$.\soln $\sin\theta=\dfrac{\text{opp}}{\text{hyp}}=\dfrac35=0.6$.` + r`\rtri{4}{3}{$3$}{$4$}{$5$}` },
      { t: "Find a side", body: r`Hypotenuse $=10$, angle $=30^\circ$. Find the opposite side.\soln $\sin30^\circ=\dfrac{\text{opp}}{10}\Rightarrow \text{opp}=10\sin30^\circ=10(0.5)=5$.` },
      { t: "Find a side", body: r`Adjacent $=8$, angle $=40^\circ$. Find the opposite side.\soln $\tan40^\circ=\dfrac{\text{opp}}{8}\Rightarrow \text{opp}=8\tan40^\circ\approx6.71$.` },
      { t: "Find an angle", body: r`Opposite $=3$, adjacent $=4$. Find $\theta$.\soln $\tan\theta=\dfrac34\Rightarrow\theta=\tan^{-1}(0.75)\approx36.9^\circ$.` + r`\rtri{4}{3}{$3$}{$4$}{$5$}` },
      { t: "Ladder", body: r`A 10 m ladder leans at $60^\circ$. How high does it reach?\soln height $=10\sin60^\circ\approx8.66$ m.` },
      { t: "Cosine ratio", body: r`Adjacent $=4$, hypotenuse $=5$. Find $\cos\theta$.\soln $\cos\theta=\dfrac45=0.8$.` },
      { t: "Find a side", body: r`Hypotenuse $=20$, angle $=30^\circ$. Find the opposite side.\soln $20\sin30^\circ=20(0.5)=10$.` },
      { t: "Find an angle", body: r`Opposite $=7$, hypotenuse $=10$. Find $\theta$.\soln $\sin\theta=\dfrac{7}{10}=0.7\Rightarrow\theta=\sin^{-1}(0.7)\approx44.4^\circ$.` },
      { t: "Ladder", body: r`An 8 m ladder leans at $70^\circ$. How high does it reach?\soln $8\sin70^\circ\approx7.52$ m.` },
    ],
    questions: [
      { ask: r`Adjacent $=6$, hypotenuse $=10$. Find $\cos\theta$.` },
      { ask: r`Hypotenuse $=12$, angle $=30^\circ$. Find the opposite side.` },
      { ask: r`Adjacent $=10$, angle $=45^\circ$. Find the opposite side.` },
      { ask: r`Opposite $=5$, adjacent $=12$. Find $\tan\theta$.` },
      { ask: r`Opposite $=6$, adjacent $=8$. Find $\theta$.` },
      { ask: r`A 6 m ladder at $60^\circ$. How high does it reach?` },
      { ask: r`Hypotenuse $=8$, angle $=60^\circ$. Find the opposite side.` },
      { ask: r`Opposite $=9$, hypotenuse $=15$. Find $\sin\theta$.` },
      { ask: r`If $\sin\theta=0.5$, find $\theta$.` },
      { ask: r`Adjacent $=5$, angle $=50^\circ$. Find the opposite side.` },
      { ask: r`Adjacent $=4$, hypotenuse $=8$. Find $\theta$.` },
      { ask: r`Hypotenuse $=10$, angle $=40^\circ$. Find the opposite side.` },
      { ask: r`A kite string is 50 m long at $65^\circ$ to the ground. Find the kite's height.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$0.6$`, r`$6$`, r`$10$`, r`$\tfrac{5}{12}\approx0.42$`, r`$\approx36.9^\circ$`, r`$\approx5.20$ m`, r`$\approx6.93$`, r`$0.6$`, r`$30^\circ$`, r`$\approx5.96$`, r`$60^\circ$`, r`$\approx6.43$`, r`$\approx45.3$ m`],
  },
  {
    code: "5.2", unit: U, title: "Two Right Triangles in 2-D",
    intro: r`Two right triangles often share a side; write a ratio in each, then combine the equations.`,
    ideas: [r`Identify the shared side (height or base).`, r`Elevation looks up, depression looks down; they are equal across parallels.`, r`One equation per triangle, then subtract or substitute.`],
    examples: [
      { t: "Helicopter & trucks", body: r`Helicopter 500 m up; depressions $60^\circ$, $20^\circ$ to two trucks ahead.\soln Each truck's distance from the point below: $\dfrac{500}{\tan60^\circ}\approx288.7$ and $\dfrac{500}{\tan20^\circ}\approx1373.7$. \\ Apart $=1373.7-288.7\approx1085$ m.` },
      { t: "Pole on a building", body: r`From 50 m, elevations $30^\circ$ (base) and $40^\circ$ (top).\soln Top height $50\tan40^\circ\approx41.95$; base height $50\tan30^\circ\approx28.87$. \\ Pole $=41.95-28.87\approx13.1$ m.` },
      { t: "Two buoys", body: r`From a 40 m cliff, depressions $50^\circ$, $30^\circ$.\soln $\dfrac{40}{\tan30^\circ}\approx69.28$ and $\dfrac{40}{\tan50^\circ}\approx33.56$. \\ Apart $\approx35.7$ m.` },
      { t: "Walking to a hill", body: r`Elevation $20^\circ$ from A; 100 m closer it is $35^\circ$. Find the height $h$.\soln Each triangle: distance $=h\cot\theta$. \\ $h\cot20^\circ-h\cot35^\circ=100\Rightarrow h(2.747-1.428)=100$. \\ $h\approx75.8$ m.` },
      { t: "Approaching a tower", body: r`Elevation $45^\circ$, then $60^\circ$ from 20 m closer.\soln $h(\cot45^\circ-\cot60^\circ)=20\Rightarrow h(1-0.5774)=20$. \\ $h\approx47.3$ m.` },
      { t: "One-triangle warm-up", body: r`From 40 m, elevation to a roof is $35^\circ$. Find its height.\soln height $=40\tan35^\circ\approx28.0$ m.` + r`\rtri{5}{3.5}{$h$}{$40$ m}{}` },
      { t: "Boat", body: r`From a 60 m cliff, depression to a boat is $25^\circ$.\soln distance $=\dfrac{60}{\tan25^\circ}\approx128.7$ m.` },
      { t: "Pole", body: r`From 30 m, elevations $25^\circ$, $40^\circ$.\soln $30(\tan40^\circ-\tan25^\circ)\approx25.17-13.99\approx11.2$ m.` },
      { t: "Two trucks", body: r`From 300 m up, depressions $45^\circ$, $30^\circ$.\soln $\dfrac{300}{\tan30^\circ}-\dfrac{300}{\tan45^\circ}\approx519.6-300\approx219.6$ m.` },
    ],
    questions: [
      { ask: r`From 50 m away, the elevation to a roof is $40^\circ$. Find its height.` },
      { ask: r`From an 80 m cliff, the depression to a boat is $30^\circ$. Find its distance.` },
      { ask: r`From 40 m, elevations to a pole's base and top are $30^\circ$ and $45^\circ$. Find the pole.` },
      { ask: r`Elevation $25^\circ$ from A; 60 m closer it is $40^\circ$. Find the height.` },
      { ask: r`Elevation $30^\circ$, then $45^\circ$ from 50 m closer. Find the height.` },
      { ask: r`From 500 m up, two trucks have depressions $60^\circ$ and $30^\circ$. How far apart?` },
      { ask: r`From 60 m, elevations $28^\circ$ and $38^\circ$ to a flagpole's base and top. Find the pole.` },
      { ask: r`From 45 m, the elevation to a building top is $50^\circ$. Find its height.` },
      { ask: r`From a 100 m tower, the depression to a car is $20^\circ$. Find its distance.` },
      { ask: r`From a 50 m cliff, depressions to two buoys are $45^\circ$ and $30^\circ$. How far apart?` },
      { ask: r`Elevation $15^\circ$ from A; 80 m closer it is $30^\circ$. Find the height.` },
      { ask: r`From 25 m, the elevation to a roof is $60^\circ$. Find its height.` },
      { ask: r`A helicopter 400 m up sees two cars at depressions $50^\circ$ and $25^\circ$. How far apart?`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$\approx41.95$ m`, r`$\approx138.6$ m`, r`$\approx16.9$ m`, r`$\approx63.0$ m`, r`$\approx68.3$ m`, r`$\approx577.4$ m`, r`$\approx15.0$ m`, r`$\approx53.6$ m`, r`$\approx274.7$ m`, r`$\approx36.6$ m`, r`$\approx40.0$ m`, r`$\approx43.3$ m`, r`$\approx522.2$ m`],
  },
  {
    code: "5.3", unit: U, title: "The Sine Law",
    intro: r`Sine law: $\dfrac{a}{\sin A}=\dfrac{b}{\sin B}=\dfrac{c}{\sin C}$ — pair a side with its opposite angle.`,
    ideas: [r`Use it when you have a side and the angle across from it.`, r`Cross-multiply to find a side or an angle.`, r`Angles sum to $180^\circ$ to get a third angle.`],
    examples: [
      { t: "Find a side", body: r`$A=40^\circ,\ a=10,\ B=60^\circ$. Find $b$.\soln $\dfrac{b}{\sin60^\circ}=\dfrac{10}{\sin40^\circ}\Rightarrow b=\dfrac{10\sin60^\circ}{\sin40^\circ}\approx13.5$.` + r`\gtri{$40^\circ$}{$60^\circ$}{$C$}{$10$}{$b$}{$c$}` },
      { t: "Third angle first", body: r`$A=50^\circ,\ B=70^\circ,\ a=8$. Find $b$.\soln $b=\dfrac{8\sin70^\circ}{\sin50^\circ}\approx9.81$.` },
      { t: "Find an angle", body: r`$a=8,\ A=50^\circ,\ b=6$. Find $B$.\soln $\dfrac{\sin B}{6}=\dfrac{\sin50^\circ}{8}\Rightarrow\sin B=\dfrac{6\sin50^\circ}{8}\approx0.5745$. \\ $B=\sin^{-1}(0.5745)\approx35.1^\circ$.` + r`\gtri{$50^\circ$}{$B$}{$C$}{$8$}{$6$}{$c$}` },
      { t: "Two angles given", body: r`$A=45^\circ,\ B=60^\circ,\ a=12$. Find $c$.\soln Third angle $C=180^\circ-45^\circ-60^\circ=75^\circ$. \\ $c=\dfrac{12\sin75^\circ}{\sin45^\circ}\approx16.4$.` },
      { t: "Set it up", body: r`$A=35^\circ,\ a=9,\ b=7$. Write the equation for $B$.\soln $\dfrac{\sin B}{7}=\dfrac{\sin35^\circ}{9}\Rightarrow\sin B=\dfrac{7\sin35^\circ}{9}$.` },
      { t: "Find a side", body: r`$A=30^\circ,\ a=5,\ B=80^\circ$. Find $b$.\soln $b=\dfrac{5\sin80^\circ}{\sin30^\circ}\approx9.85$.` },
      { t: "Find a side", body: r`$A=60^\circ,\ a=10,\ B=40^\circ$. Find $b$.\soln $b=\dfrac{10\sin40^\circ}{\sin60^\circ}\approx7.42$.` },
      { t: "Find an angle", body: r`$a=10,\ A=70^\circ,\ b=8$. Find $B$.\soln $\sin B=\dfrac{8\sin70^\circ}{10}\approx0.7518\Rightarrow B\approx48.8^\circ$.` },
      { t: "Third angle", body: r`$A=40^\circ,\ B=75^\circ$. Find $C$.\soln $C=180^\circ-40^\circ-75^\circ=65^\circ$.` },
    ],
    questions: [
      { ask: r`$A=40^\circ,\ a=10,\ B=60^\circ$. Find $b$.` },
      { ask: r`$A=50^\circ,\ B=70^\circ,\ a=8$. Find $b$.` },
      { ask: r`$a=8,\ A=50^\circ,\ b=6$. Find $B$.` },
      { ask: r`$A=45^\circ,\ B=60^\circ,\ a=12$. Find $c$.` },
      { ask: r`If $A=40^\circ$ and $B=75^\circ$, find $C$.` },
      { ask: r`$A=30^\circ,\ a=5,\ B=80^\circ$. Find $b$.` },
      { ask: r`$A=60^\circ,\ a=10,\ B=40^\circ$. Find $b$.` },
      { ask: r`$a=10,\ A=70^\circ,\ b=8$. Find $B$.` },
      { ask: r`When is the sine law the right tool?` },
      { ask: r`$A=55^\circ,\ a=14,\ B=65^\circ$. Find $b$.` },
      { ask: r`If $A=50^\circ$ and $C=60^\circ$, find $B$.` },
      { ask: r`$a=12,\ A=80^\circ,\ b=9$. Find $B$.` },
      { ask: r`$A=35^\circ,\ a=9,\ b=7$. Find $B$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\approx13.5$`, r`$\approx9.81$`, r`$\approx35.1^\circ$`, r`$\approx16.4$`, r`$65^\circ$`, r`$\approx9.85$`, r`$\approx7.42$`, r`$\approx48.8^\circ$`, r`a side and its opposite angle`, r`$\approx15.5$`, r`$70^\circ$`, r`$\approx47.6^\circ$`, r`$\approx26.5^\circ$`],
  },
  {
    code: "5.4", unit: U, title: "The Cosine Law",
    intro: r`Cosine law: $c^2=a^2+b^2-2ab\cos C$ (find a side); $\cos C=\dfrac{a^2+b^2-c^2}{2ab}$ (find an angle).`,
    ideas: [r`Use for SAS (find a side) or SSS (find an angle).`, r`At $C=90^\circ$ it reduces to Pythagoras.`, r`The largest angle is opposite the longest side.`],
    examples: [
      { t: "Find a side (SAS)", body: r`$a=5,\ b=7,\ C=60^\circ$. Find $c$.\soln $c^2=5^2+7^2-2(5)(7)\cos60^\circ=25+49-70(0.5)=39$. \\ $c=\sqrt{39}\approx6.24$.` + r`\gtri{$A$}{$B$}{$60^\circ$}{$5$}{$7$}{$c$}` },
      { t: "Right angle", body: r`$a=8,\ b=6,\ C=90^\circ$. Find $c$.\soln $\cos90^\circ=0$, so $c^2=64+36=100$. \\ $c=10$.` },
      { t: "Find an angle (SSS)", body: r`Sides $6,8,10$; angle opposite $10$.\soln $\cos C=\dfrac{6^2+8^2-10^2}{2(6)(8)}=\dfrac{0}{96}=0$. \\ $C=\cos^{-1}(0)=90^\circ$.` },
      { t: "SAS", body: r`$a=7,\ b=9,\ C=50^\circ$. Find $c$.\soln $c^2=49+81-126\cos50^\circ\approx130-81.0=49.0$. \\ $c\approx7.0$.` },
      { t: "Largest angle (SSS)", body: r`Sides $5,6,7$; largest angle (opposite $7$).\soln $\cos C=\dfrac{25+36-49}{2(5)(6)}=\dfrac{12}{60}=0.2$. \\ $C\approx78.5^\circ$.` + r`\gtri{$A$}{$B$}{$C$}{$5$}{$6$}{$7$}` },
      { t: "Right angle", body: r`$a=4,\ b=5,\ C=90^\circ$. Find $c$.\soln $c=\sqrt{16+25}=\sqrt{41}\approx6.40$.` },
      { t: "SAS", body: r`$a=9,\ b=12,\ C=80^\circ$. Find $c$.\soln $c^2=81+144-216\cos80^\circ\approx187.5$. \\ $c\approx13.7$.` },
      { t: "Find an angle (SSS)", body: r`Sides $7,8,9$; angle opposite $9$.\soln $\cos C=\dfrac{49+64-81}{2(7)(8)}=\dfrac{32}{112}\approx0.286$. \\ $C\approx73.4^\circ$.` },
      { t: "SAS", body: r`$a=10,\ b=6,\ C=40^\circ$. Find $c$.\soln $c^2=100+36-120\cos40^\circ\approx44.1$. \\ $c\approx6.64$.` },
    ],
    questions: [
      { ask: r`$a=5,\ b=7,\ C=60^\circ$. Find $c$.` },
      { ask: r`$a=4,\ b=5,\ C=90^\circ$. Find $c$.` },
      { ask: r`Sides $6,8,10$. Find the largest angle.` },
      { ask: r`$a=9,\ b=12,\ C=80^\circ$. Find $c$.` },
      { ask: r`When should you use the cosine law?` },
      { ask: r`$a=6,\ b=8,\ C=45^\circ$. Find $c$.` },
      { ask: r`Sides $5,6,7$. Find the largest angle.` },
      { ask: r`$a=8,\ b=8,\ C=60^\circ$. Find $c$.` },
      { ask: r`Sides $7,8,9$. Find the angle opposite $9$.` },
      { ask: r`$a=10,\ b=7,\ C=55^\circ$. Find $c$.` },
      { ask: r`Sides $4,5,6$. Find the angle opposite $6$.` },
      { ask: r`$a=12,\ b=15,\ C=35^\circ$. Find $c$.` },
      { ask: r`A triangle has sides $9,10,11$. Find the largest angle.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\approx6.24$`, r`$\approx6.40$`, r`$90^\circ$`, r`$\approx13.7$`, r`SAS or SSS`, r`$\approx5.67$`, r`$\approx78.5^\circ$`, r`$8$`, r`$\approx73.4^\circ$`, r`$\approx8.29$`, r`$\approx82.8^\circ$`, r`$\approx8.61$`, r`$\approx70.5^\circ$`],
  },
];
