// MCF3M Unit 6 worksheets — Sine Functions.
// Examples: full step-by-step solutions with TikZ sine curves (\splot, degrees on x).
const r = String.raw;
const U = "6: Sine Functions";

export default [
  {
    code: "6.1", unit: U, title: "Periodic Functions & the Sine Function",
    intro: r`A periodic function repeats at regular intervals; the sine function $f(x)=\sin x$ has period $360^\circ$.`,
    ideas: [r`Cycle: one complete repeat; period: the length of one cycle.`, r`Amplitude $=\dfrac{\max-\min}{2}$.`, r`Midline $=\dfrac{\max+\min}{2}$.`],
    examples: [
      { t: "Period", body: r`A wave repeats every $360^\circ$. State its period.\soln One full cycle spans $360^\circ$, so the period is $360^\circ$. The parent sine wave:` + r`\splot{-1.5}{1.5}{\addplot[exblue,very thick,domain=0:360]{sin(x)};}` },
      { t: "Amplitude", body: r`Max $5$, min $1$. Find the amplitude.\soln $\dfrac{\max-\min}{2}=\dfrac{5-1}{2}=2$.` },
      { t: "Midline", body: r`Max $5$, min $1$. Find the midline.\soln $\dfrac{\max+\min}{2}=\dfrac{5+1}{2}=3$, so $y=3$.` },
      { t: "Function?", body: r`Is $y=\sin x$ a function?\soln Each angle gives exactly one sine value, so \textbf{yes}.` },
      { t: "Parent period", body: r`Period of $y=\sin x$?\soln The sine ratio repeats once per full turn: $360^\circ$.` },
      { t: "Amplitude", body: r`Max $7$, min $1$. Find the amplitude.\soln $\dfrac{7-1}{2}=3$.` },
      { t: "Midline", body: r`Max $7$, min $1$. Find the midline.\soln $\dfrac{7+1}{2}=4$, so $y=4$.` },
      { t: "Maximum", body: r`Maximum of $y=\sin x$?\soln The peak of the parent sine curve is $1$.` },
      { t: "Minimum", body: r`Minimum of $y=\sin x$?\soln The trough of the parent sine curve is $-1$.` },
    ],
    questions: [
      { ask: r`Amplitude if max $=10$, min $=2$.` },
      { ask: r`Midline if max $=10$, min $=2$.` },
      { ask: r`State the period of $y=\sin x$.` },
      { ask: r`State the maximum of $y=\sin x$.` },
      { ask: r`State the minimum of $y=\sin x$.` },
      { ask: r`Amplitude if max $=8$, min $=0$.` },
      { ask: r`Midline if max $=8$, min $=0$.` },
      { ask: r`Amplitude if max $=3$, min $=-3$.` },
      { ask: r`Midline if max $=3$, min $=-3$.` },
      { ask: r`Is a repeating temperature graph periodic?` },
      { ask: r`A cycle lasts 12 h. State the period.` },
      { ask: r`Amplitude if max $=9$, min $=3$.` },
      { ask: r`A wave has midline $y=5$ and amplitude $4$. Find its max and min.`, challenge: true, ws: "2.6cm" },
    ],
    answers: [r`$4$`, r`$y=6$`, r`$360^\circ$`, r`$1$`, r`$-1$`, r`$4$`, r`$y=4$`, r`$3$`, r`$y=0$`, r`yes`, r`$12$ h`, r`$3$`, r`max $9$, min $1$`],
  },
  {
    code: "6.2", unit: U, title: "Graphing f(x) = sin x",
    intro: r`The parent sine graph has five key points: $(0,0),(90,1),(180,0),(270,-1),(360,0)$.`,
    ideas: [r`Amplitude $1$, period $360^\circ$, midline $y=0$.`, r`Max at $90^\circ$, min at $270^\circ$.`, r`Zeros at $0^\circ,180^\circ,360^\circ$.`],
    examples: [
      { t: "Key value", body: r`$\sin0^\circ$.\soln The curve starts on the midline: $0$.` },
      { t: "Peak", body: r`$\sin90^\circ$.\soln The maximum of the curve: $1$.` },
      { t: "Zero", body: r`$\sin180^\circ$.\soln A zero crossing: $0$.` },
      { t: "Trough", body: r`$\sin270^\circ$.\soln The minimum of the curve: $-1$.` },
      { t: "Five key points", body: r`List one cycle's key points.\soln $(0,0),(90,1),(180,0),(270,-1),(360,0)$ — they split the cycle into quarters:` + r`\splot{-1.5}{1.5}{\addplot[exblue,very thick,domain=0:360]{sin(x)};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,0) (90,1) (180,0) (270,-1) (360,0)};}` },
      { t: "Full cycle", body: r`$\sin360^\circ$.\soln Back to the start: $0$.` },
      { t: "Maximum", body: r`Where is $y=\sin x$ maximum on $[0^\circ,360^\circ]$?\soln At the peak, $x=90^\circ$.` },
      { t: "Range", body: r`Range of $y=\sin x$.\soln The curve stays between $-1$ and $1$: $[-1,1]$.` },
      { t: "Period", body: r`Period of $y=\sin x$.\soln One cycle spans $360^\circ$.` },
    ],
    questions: [
      { ask: r`Find $\sin90^\circ$.` },
      { ask: r`Find $\sin180^\circ$.` },
      { ask: r`Find $\sin270^\circ$.` },
      { ask: r`Find $\sin0^\circ$.` },
      { ask: r`Where is $y=\sin x$ maximum on $[0^\circ,360^\circ]$?` },
      { ask: r`Where is $y=\sin x$ minimum on $[0^\circ,360^\circ]$?` },
      { ask: r`State the zeros of $y=\sin x$ on $[0^\circ,360^\circ]$.` },
      { ask: r`State the range of $y=\sin x$.` },
      { ask: r`State the period of $y=\sin x$.` },
      { ask: r`State the amplitude of $y=\sin x$.` },
      { ask: r`State the midline of $y=\sin x$.` },
      { ask: r`How many key points are in one cycle?` },
      { ask: r`Use the pattern to find $\sin450^\circ$.`, challenge: true, ws: "2.6cm" },
    ],
    answers: [r`$1$`, r`$0$`, r`$-1$`, r`$0$`, r`$90^\circ$`, r`$270^\circ$`, r`$0^\circ,180^\circ,360^\circ$`, r`$[-1,1]$`, r`$360^\circ$`, r`$1$`, r`$y=0$`, r`$5$`, r`$1$`],
  },
  {
    code: "6.3", unit: U, title: "Transformations of Sine Functions",
    intro: r`$y=a\sin\!\big(k(x-d)\big)+c$: $a$ amplitude, period $=\dfrac{360^\circ}{k}$, $d$ phase shift, $c$ midline.`,
    ideas: [r`$a$: amplitude $|a|$ (reflect if $a<0$).`, r`Period $=\dfrac{360^\circ}{k}$; $(x-d)$ shifts right by $d$.`, r`Max $=c+|a|$, min $=c-|a|$.`],
    examples: [
      { t: "Amplitude", body: r`Amplitude of $y=3\sin x$.\soln $|a|=3$ — the curve reaches $\pm3$ (compared with $\pm1$):` + r`\splot{-3.5}{3.5}{\addplot[qorange,very thick,domain=0:360]{sin(x)};\addplot[exblue,very thick,domain=0:360]{3*sin(x)};}` },
      { t: "Period", body: r`Period of $y=\sin(2x)$.\soln Period $=\dfrac{360^\circ}{2}=180^\circ$ — two cycles fit in $360^\circ$:` + r`\splot{-1.5}{1.5}{\addplot[exblue,very thick,domain=0:360]{sin(2*x)};}` },
      { t: "Midline", body: r`Midline of $y=\sin x+2$.\soln The $+2$ lifts the whole wave; midline $y=2$:` + r`\splot{-1}{4}{\addplot[red,dashed,domain=0:360]{2};\addplot[exblue,very thick,domain=0:360]{sin(x)+2};}` },
      { t: "Max & min", body: r`Max and min of $y=2\sin x+1$.\soln Midline $1$, amplitude $2$: max $=1+2=3$, min $=1-2=-1$.` },
      { t: "Full description", body: r`Describe $y=3\sin\!\big(2(x-30^\circ)\big)+1$.\soln $a=3$ (amplitude 3), $k=2$ (period $180^\circ$), $d=30^\circ$ (right $30^\circ$), $c=1$ (midline $y=1$).` },
      { t: "Amplitude", body: r`Amplitude of $y=5\sin x$.\soln $|a|=5$.` },
      { t: "Period", body: r`Period of $y=\sin(3x)$.\soln $\dfrac{360^\circ}{3}=120^\circ$.` },
      { t: "Midline", body: r`Midline of $y=\sin x-4$.\soln $c=-4$, so $y=-4$.` },
      { t: "Period", body: r`Period of $y=\sin\!\big(\tfrac12 x\big)$.\soln $\dfrac{360^\circ}{1/2}=720^\circ$.` },
    ],
    questions: [
      { ask: r`Amplitude of $y=4\sin x$.` },
      { ask: r`Period of $y=\sin(2x)$.` },
      { ask: r`Midline of $y=\sin x+3$.` },
      { ask: r`Maximum of $y=2\sin x+1$.` },
      { ask: r`Minimum of $y=2\sin x+1$.` },
      { ask: r`Period of $y=\sin(4x)$.` },
      { ask: r`Amplitude of $y=-2\sin x$.` },
      { ask: r`Period of $y=\sin(\tfrac12 x)$.` },
      { ask: r`Phase shift of $y=\sin(x-45^\circ)$.` },
      { ask: r`Maximum of $y=3\sin x+2$.` },
      { ask: r`Midline of $y=5\sin x-1$.` },
      { ask: r`Phase shift of $y=\sin(x+60^\circ)$.` },
      { ask: r`Write a sine function with amplitude $4$, period $180^\circ$, midline $y=2$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$4$`, r`$180^\circ$`, r`$y=3$`, r`$3$`, r`$-1$`, r`$90^\circ$`, r`$2$`, r`$720^\circ$`, r`right $45^\circ$`, r`$5$`, r`$y=-1$`, r`left $60^\circ$`, r`$y=4\sin(2x)+2$`],
  },
  {
    code: "6.4", unit: U, title: "Sinusoidal Applications",
    intro: r`Model with $h=a\sin(kt)+c$: amplitude $a$, midline $c$, period $=$ one cycle; max $=c+a$, min $=c-a$.`,
    ideas: [r`Amplitude $=$ radius or half the range.`, r`Midline $=$ the centre value.`, r`Period $=$ time for one full cycle.`],
    examples: [
      { t: "Max height", body: r`Wheel: radius 10 m, centre 12 m. Max height?\soln Max $=$ midline $+$ amplitude $=12+10=22$ m. A wheel's height is sinusoidal:` + r`\splot{-1}{3}{\addplot[exblue,very thick,domain=0:360]{sin(x)+1};\addplot[red,dashed,domain=0:360]{1};}` },
      { t: "Min height", body: r`Same wheel: min height?\soln Min $=12-10=2$ m.` },
      { t: "Tide", body: r`Tide rises to 6 m, falls to 2 m.\soln Amplitude $=\dfrac{6-2}{2}=2$ m; midline $=\dfrac{6+2}{2}=4$ m.` },
      { t: "Period", body: r`One rotation takes 60 s. Period?\soln One full cycle $=$ one rotation $=60$ s.` },
      { t: "Daylight", body: r`Daylight 16 h (max) to 8 h (min).\soln Amplitude $=\dfrac{16-8}{2}=4$ h; midline $=\dfrac{16+8}{2}=12$ h.` },
      { t: "Max height", body: r`Wheel: radius 8 m, centre 10 m. Max height?\soln $10+8=18$ m.` },
      { t: "Tide amplitude", body: r`Tide rises to 5 m, falls to 1 m. Amplitude?\soln $\dfrac{5-1}{2}=2$ m.` },
      { t: "Tide midline", body: r`Same tide: midline?\soln $\dfrac{5+1}{2}=3$ m.` },
      { t: "Period", body: r`One rotation takes 40 s. Period?\soln $40$ s.` },
    ],
    questions: [
      { ask: r`Wheel: radius 10 m, centre 12 m. Max height?` },
      { ask: r`Wheel: radius 10 m, centre 12 m. Min height?` },
      { ask: r`Tide rises to 6 m, falls to 2 m. Amplitude?` },
      { ask: r`Same tide: midline?` },
      { ask: r`One rotation takes 30 s. Period?` },
      { ask: r`Wheel: radius 8 m, centre 10 m. Max height?` },
      { ask: r`Daylight ranges 16 h to 8 h. Amplitude?` },
      { ask: r`Daylight ranges 16 h to 8 h. Midline?` },
      { ask: r`A wheel has radius 15 m. Amplitude?` },
      { ask: r`Wheel: radius 8 m, centre 10 m. Min height?` },
      { ask: r`A model $h=5\sin(kt)+20$. Maximum?` },
      { ask: r`Tide rises to 7 m, falls to 1 m. Amplitude?` },
      { ask: r`A wheel: radius 9 m, centre 11 m, rotation 50 s. State $a$, $c$, and the period.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$22$ m`, r`$2$ m`, r`$2$ m`, r`$4$ m`, r`$30$ s`, r`$18$ m`, r`$4$ h`, r`$12$ h`, r`$15$ m`, r`$2$ m`, r`$25$`, r`$3$ m`, r`$a=9$, $c=11$, period $50$ s`],
  },
];
