// MPM2D Unit 1 — Linear Systems: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "./helpers.mjs";

// ── 1.1 Review of Linear Relations ───────────────────────────
function g11() {
  const q = [];
  // EASY
  q.push(mc("easy", "What is the slope of $y=2x+3$?", ["$2$", "$3$", "$-2$", "$1/2$"], 0));
  q.push(mc("easy", "What is the $y$-intercept of $y=2x+3$?", ["$(0,3)$", "$(3,0)$", "$(0,2)$", "$(0,-3)$"], 0));
  q.push(mc("easy", "Find the slope of the line through $(0,0)$ and $(2,4)$.", ["$2$", "$1/2$", "$4$", "$-2$"], 0));
  q.push(mc("easy", "What is the slope of $y=-x+5$?", ["$-1$", "$1$", "$5$", "$-5$"], 0));
  q.push(mc("easy", "Find the $x$-intercept of $y=2x-4$.", ["$2$", "$-4$", "$4$", "$-2$"], 0));
  q.push(mc("easy", "Which equation is in slope-intercept form?", ["$y=mx+b$", "$Ax+By=C$", "$y-y_1=m(x-x_1)$", "$x=a$"], 0));
  q.push(ms("easy", "Which lines have slope $3$?", ["$y=3x+1$", "$y=3x-2$", "$y=2x+3$", "$y=-3x$"], [0, 1]));
  q.push(ms("easy", "Which lines pass through the origin?", ["$y=2x$", "$y=x+1$", "$y=-3x$", "$y=4$"], [0, 2]));
  q.push(ms("easy", "Which relations are linear?", ["$y=2x+1$", "$y=x^2$", "$y=-x$", "$y=3$"], [0, 2, 3]));
  q.push(ms("easy", "Which lines have the same slope as $y=x/2$?", ["$y=0.5x+3$", "$y=x/2-1$", "$y=2x$", "$y=-x/2$"], [0, 1]));
  q.push(tf("easy", "The slope of a horizontal line is $0$.", true));
  q.push(tf("easy", "A vertical line has an undefined slope.", true));
  q.push(tf("easy", "The line $y=-2x+1$ has $y$-intercept $-2$.", false, "The $y$-intercept is $1$."));
  q.push(fill("easy", "The slope of $y=4x-7$ is ___.", ["4"]));
  q.push(fill("easy", "The $y$-intercept of $y=-3x+6$ is ___ (a number).", ["6"]));
  q.push(fill("easy", "The line with slope $5$ and $y$-intercept $2$ is $y=$ ___.", ["5x+2", "5x + 2"]));
  q.push(num("easy", "Find the slope of the line through $(1,2)$ and $(3,8)$.", 3, 0));
  q.push(num("easy", "Find the $x$-intercept of $y=3x-9$.", 3, 0));
  q.push(num("easy", "Evaluate $y=2x+1$ at $x=4$.", 9, 0));
  q.push(match("easy", "Match each equation form to its name.", ["$y=mx+b$", "$Ax+By=C$", "$y-y_1=m(x-x_1)$"], ["slope-intercept", "standard", "point-slope"], [0, 1, 2]));
  // MEDIUM
  q.push(mc("medium", "Find the slope through $(-2,3)$ and $(4,-9)$.", ["$-2$", "$2$", "$-1/2$", "$-3$"], 0));
  q.push(mc("medium", "Rewrite $2x+y=5$ in slope-intercept form.", ["$y=-2x+5$", "$y=2x+5$", "$y=-2x-5$", "$y=5-2x^2$"], 0));
  q.push(mc("medium", "Find the equation with slope $3$ through $(0,-1)$.", ["$y=3x-1$", "$y=3x+1$", "$y=-x+3$", "$y=-3x-1$"], 0));
  q.push(mc("medium", "What is the slope of any line parallel to $y=4x-2$?", ["$4$", "$-4$", "$-1/4$", "$1/4$"], 0));
  q.push(mc("medium", "What is the slope of any line perpendicular to $y=2x$?", ["$-1/2$", "$2$", "$1/2$", "$-2$"], 0));
  q.push(mc("medium", "Find the $x$-intercept of $3x+2y=12$.", ["$4$", "$6$", "$3$", "$2$"], 0));
  q.push(ms("medium", "Which lines are parallel to $y=2x+1$?", ["$y=2x-3$", "$y=2x$", "$y=-2x$", "$y=x/2$"], [0, 1]));
  q.push(ms("medium", "Which lines pass through $(1,3)$?", ["$y=2x+1$", "$y=3x$", "$y=x+1$", "$y=-x+4$"], [0, 1, 3]));
  q.push(ms("medium", "Which lines have slope $-3/2$?", ["$y=-1.5x+2$", "$y=-3x/2$", "$3x+2y=6$", "$y=1.5x$"], [0, 1, 2]));
  q.push(ms("medium", "For $y=x/2-4$, which are true?", ["slope $1/2$", "$y$-intercept $-4$", "$x$-intercept $8$", "passes $(0,-4)$"], [0, 1, 2, 3]));
  q.push(tf("medium", "Parallel lines have equal slopes.", true));
  q.push(tf("medium", "Perpendicular slopes multiply to $1$.", false, "They multiply to $-1$."));
  q.push(tf("medium", "$2x+y=5$ has slope $-2$.", true));
  q.push(fill("medium", "Rewrite $4x-2y=6$ as $y=$ ___.", ["2x-3", "2x - 3"]));
  q.push(fill("medium", "The line with slope $-2$ through $(3,1)$ is $y=$ ___.", ["-2x+7", "-2x + 7"]));
  q.push(fill("medium", "The slope perpendicular to $2/3$ is ___.", ["-3/2", "-1.5"]));
  q.push(num("medium", "Find the slope through $(2,-1)$ and $(5,8)$.", 3, 0));
  q.push(num("medium", "Find the $y$-intercept of $4x+2y=10$.", 5, 0));
  q.push(num("medium", "Find the $x$-intercept of $y=-2x+8$.", 4, 0));
  q.push(match("medium", "Match each equation to its slope.", ["$y=3x-2$", "$y=-x+5$", "$2x-y=4$"], ["$3$", "$-1$", "$2$"], [0, 1, 2]));
  // HARD
  q.push(mc("hard", "Find the equation of the line through $(1,2)$ and $(4,11)$.", ["$y=3x-1$", "$y=3x+1$", "$y=2x$", "$y=x+1$"], 0));
  q.push(mc("hard", "Find the line parallel to $2x+3y=6$ through $(3,1)$.", ["$y=-2x/3+3$", "$y=-2x/3-3$", "$y=3x/2+1$", "$y=-2x+7$"], 0));
  q.push(mc("hard", "Find the line perpendicular to $y=x/2-3$ through $(2,5)$.", ["$y=-2x+9$", "$y=2x+1$", "$y=-2x-9$", "$y=x/2+4$"], 0));
  q.push(mc("hard", "For which $k$ are $y=kx+1$ and $y=3x-2$ parallel?", ["$3$", "$-3$", "$1/3$", "$-1/3$"], 0));
  q.push(mc("hard", "Find the $x$-intercept of the line through $(0,4)$ with slope $-2$.", ["$2$", "$4$", "$-2$", "$8$"], 0));
  q.push(mc("hard", "Find the slope of $3x-4y=12$.", ["$3/4$", "$-3/4$", "$3$", "$-4/3$"], 0));
  q.push(ms("hard", "Which lines are perpendicular to $y=3x/4$?", ["$y=-4x/3$", "$4x+3y=6$", "$y=3x/4$", "$y=4x/3$"], [0, 1]));
  q.push(ms("hard", "For the line through $(2,-1)$ and $(-2,7)$, which are true?", ["slope $-2$", "$y=-2x+3$", "$y$-intercept $3$", "passes $(0,3)$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which lines pass through $(-1,4)$?", ["$y=-3x+1$", "$y=x+5$", "$2x+y=3$", "$y=4$"], [0, 1, 3]));
  q.push(tf("hard", "The lines $y=2x+1$ and $x+2y=4$ are perpendicular.", true, "Slopes $2$ and $-1/2$."));
  q.push(tf("hard", "A line with undefined slope can be written as $y=mx+b$.", false, "It is $x=$ constant."));
  q.push(tf("hard", "Parallel lines can never share a $y$-intercept.", false, "If they do, they are the same line."));
  q.push(fill("hard", "The line perpendicular to $y=-x/3+2$ through the origin is $y=$ ___.", ["3x"]));
  q.push(fill("hard", "The line through $(2,5)$ and $(4,5)$ is $y=$ ___.", ["5"]));
  q.push(fill("hard", "Rewrite $5x-2y=10$ in slope-intercept form: $y=$ ___.", ["5/2x-5", "2.5x-5"]));
  q.push(num("hard", "Find the slope through $(-3,4)$ and $(2,-6)$.", -2, 0));
  q.push(num("hard", "If $y=kx-3$ passes through $(2,7)$, find $k$.", 5, 0));
  q.push(num("hard", "If $y=2x+b$ passes through $(3,1)$, find $b$.", -5, 0));
  q.push(order("hard", "Order the steps to graph a line from $y=mx+b$.", ["Plot the $y$-intercept $b$", "Use the slope as rise over run", "Plot a second point", "Draw the line through them"]));
  q.push(match("hard", "Match each description to its equation.", ["slope $2$ through origin", "horizontal through $(0,3)$", "vertical through $(4,0)$"], ["$y=2x$", "$y=3$", "$x=4$"], [0, 1, 2]));
  return q;
}

// ── 1.2 Solving Linear Systems by Graphing ───────────────────
function g12() {
  const q = [];
  q.push(mc("hard", "For $y=kx+2$ and $y=3x+2$ to be the same line, $k=$", ["$3$", "$2$", "$-3$", "$0$"], 0));
  q.push(mc("easy", "The solution of a system is the point that:", ["lies on both lines", "lies on one line", "is the $y$-intercept", "is the origin"], 0));
  q.push(mc("easy", "Where do $y=x$ and $y=2$ intersect?", ["$(2,2)$", "$(0,2)$", "$(2,0)$", "$(1,1)$"], 0));
  q.push(mc("easy", "Two lines that never meet are:", ["parallel", "perpendicular", "equal", "intersecting"], 0));
  q.push(mc("easy", "If two lines cross at one point, the system has:", ["one solution", "no solution", "infinitely many", "two solutions"], 0));
  q.push(mc("easy", "Where does $y=x+1$ meet $y=-x+5$?", ["$(2,3)$", "$(3,2)$", "$(1,2)$", "$(0,1)$"], 0));
  q.push(mc("easy", "The point $(2,1)$ is a solution if it:", ["satisfies both equations", "satisfies one equation", "is on the $x$-axis", "has $x=y$"], 0));
  q.push(ms("easy", "Which describe a system with no solution?", ["parallel lines", "equal slopes, different intercepts", "the same line", "intersecting lines"], [0, 1]));
  q.push(ms("easy", "Which points are solutions of $y=2x$?", ["$(1,2)$", "$(2,4)$", "$(1,3)$", "$(0,0)$"], [0, 1, 3]));
  q.push(ms("easy", "Which systems have exactly one solution?", ["different slopes", "$y=x$ and $y=-x$", "parallel lines", "the same line"], [0, 1]));
  q.push(ms("easy", "For $y=x-1$ and $y=-x+3$, which are true?", ["they intersect", "solution $(2,1)$", "slopes differ", "they are parallel"], [0, 1, 2]));
  q.push(tf("easy", "Two straight lines can have exactly two solutions.", false));
  q.push(tf("easy", "The solution to a system is where the graphs intersect.", true));
  q.push(tf("easy", "Parallel lines give a system with no solution.", true));
  q.push(fill("easy", "$y=x$ and $y=4$ intersect at $x=$ ___.", ["4"]));
  q.push(fill("easy", "$y=2x$ and $y=6$ intersect at $x=$ ___.", ["3"]));
  q.push(fill("easy", "Two lines with the same equation have ___ solutions.", ["infinitely many", "infinite"]));
  q.push(num("easy", "At what $x$ do $y=x+2$ and $y=2x$ meet?", 2, 0));
  q.push(num("easy", "At what $x$ do $y=3x$ and $y=x+4$ meet?", 2, 0));
  q.push(num("easy", "At what $y$ do $y=5$ and $y=2x+1$ meet?", 5, 0));
  q.push(match("easy", "Match each system type to its number of solutions.", ["intersecting lines", "parallel lines", "the same line"], ["one", "none", "infinite"], [0, 1, 2]));
  q.push(mc("medium", "Solve by graphing: $y=2x-3$, $y=-x+3$.", ["$(2,1)$", "$(1,2)$", "$(3,0)$", "$(0,3)$"], 0));
  q.push(mc("medium", "Solve: $x+y=4$, $y=2x-2$.", ["$(2,2)$", "$(1,3)$", "$(2,0)$", "$(0,4)$"], 0));
  q.push(mc("medium", "Solve: $2x+y=5$, $x-y=1$.", ["$(2,1)$", "$(1,2)$", "$(3,2)$", "$(2,3)$"], 0));
  q.push(mc("medium", "$y=2x+1$ and $y=2x-3$ have:", ["no solution", "one solution", "infinitely many", "two"], 0));
  q.push(mc("medium", "$y=x+2$ and $2x-2y=-4$ have:", ["infinitely many", "none", "one", "two"], 0));
  q.push(mc("medium", "Solve: $y=-2x+5$, $y=x-1$.", ["$(2,1)$", "$(1,2)$", "$(2,-1)$", "$(-1,2)$"], 0));
  q.push(ms("medium", "Which systems have no solution?", ["$y=3x+1$, $y=3x-2$", "$y=2x$, $y=2x+5$", "$y=x$, $y=-x$", "$y=x+1$, $y=x+1$"], [0, 1]));
  q.push(ms("medium", "For $y=x+1$, $y=-x+5$ (solution $(2,3)$), which are true?", ["$(2,3)$ is on both", "$2+1=3$", "$-2+5=3$", "$x=3$"], [0, 1, 2]));
  q.push(ms("medium", "Which systems have infinitely many solutions?", ["$y=x+2$, $2y=2x+4$", "$y=2x$, $4x-2y=0$", "$y=x$, $y=x+1$", "$y=3x$, $y=3x$"], [0, 1, 3]));
  q.push(ms("medium", "Which methods solve a linear system?", ["graphing", "substitution", "elimination", "guessing only"], [0, 1, 2]));
  q.push(tf("medium", "If two lines have different slopes they intersect exactly once.", true));
  q.push(tf("medium", "$y=2x+1$ and $y=2x+1$ are the same line.", true));
  q.push(tf("medium", "Graphing always gives exact non-integer solutions.", false, "Graphing is approximate for non-integers."));
  q.push(fill("medium", "Solve $y=x+1$, $y=-x+7$: the solution is ___.", ["(3,4)", "3,4"]));
  q.push(fill("medium", "Solve $y=2x$, $y=x+3$: the solution is ___.", ["(3,6)", "3,6"]));
  q.push(fill("medium", "$y=4$ and $y=2x-2$ meet at the point ___.", ["(3,4)", "3,4"]));
  q.push(num("medium", "Solve $y=x-2$, $y=-x+4$: find $x$.", 3, 0));
  q.push(num("medium", "Solve $y=2x+1$, $y=-x-2$: find $x$.", -1, 0));
  q.push(num("medium", "Solve $y=3x$, $y=x+8$: find $x$.", 4, 0));
  q.push(match("medium", "Match each system to its solution.", ["$y=x,\\ y=2$", "$y=2x,\\ y=4$", "$y=x+1,\\ y=5$"], ["$(2,2)$", "$(2,4)$", "$(4,5)$"], [0, 1, 2]));
  q.push(mc("hard", "Solve: $3x-2y=6$, $y=3x/2-3$.", ["infinitely many", "one", "none", "$(2,0)$"], 0));
  q.push(mc("hard", "Solve by graphing: $2x+y=3$, $x-y=3$.", ["$(2,-1)$", "$(-1,2)$", "$(2,1)$", "$(1,2)$"], 0));
  q.push(mc("hard", "Gym A: $C=5v$; Gym B: $C=3v+4$. Equal cost at $v=$", ["$2$", "$4$", "$1$", "$3$"], 0));
  q.push(mc("hard", "Taxi A: $C=2d+3$; Taxi B: $C=5d$. Equal at $d=$", ["$1$", "$2$", "$3$", "$0$"], 0));
  q.push(mc("hard", "For $y=kx+2$ and $y=3x-1$ to have no solution, $k=$", ["$3$", "$-3$", "$2$", "$-1$"], 0));
  q.push(ms("hard", "Which systems are inconsistent (no solution)?", ["$x+y=2$, $x+y=5$", "$y=x$, $y=x+1$", "$y=2x$, $y=2x$", "$2x+2y=4$, $x+y=5$"], [0, 1, 3]));
  q.push(ms("hard", "For the solution $(2,1)$, which lines could belong to the system?", ["$y=x-1$", "$x+y=3$", "$y=2x-3$", "$y=x+1$"], [0, 1, 2]));
  q.push(ms("hard", "Which are true for parallel-line systems?", ["equal slopes", "different intercepts", "no intersection", "infinitely many solutions"], [0, 1, 2]));
  q.push(tf("hard", "A consistent system has at least one solution.", true));
  q.push(tf("hard", "Coincident lines have infinitely many solutions.", true));
  q.push(tf("hard", "Two lines with slopes $2$ and $-2$ are parallel.", false));
  q.push(fill("hard", "Solve $2x+y=5$, $x-y=1$: the solution is ___.", ["(2,1)", "2,1"]));
  q.push(fill("hard", "Cost models $C=4n$ and $C=2n+6$ are equal at $n=$ ___.", ["3"]));
  q.push(fill("hard", "For $y=2x+b$ and $y=2x+5$ to be the same line, $b=$ ___.", ["5"]));
  q.push(num("hard", "Solve $3x-y=2$, $x+y=6$: find $x$.", 2, 0));
  q.push(num("hard", "Two plans: $C=10+2x$ and $C=4x$. Equal at $x=$ ___.", 5, 0));
  q.push(num("hard", "Solve $y=x+4$, $y=3x$: find $y$.", 6, 0));
  q.push(order("hard", "Order the steps to solve a system by graphing.", ["Write each line in $y=mx+b$", "Graph both lines", "Find the intersection point", "Check it in both equations"]));
  q.push(match("hard", "Match each system to its number of solutions.", ["$y=2x+1,\\ y=2x-3$", "$y=x,\\ y=-x+4$", "$y=x+2,\\ 2y=2x+4$"], ["none", "one", "infinite"], [0, 1, 2]));
  return q;
}

// ── 1.3 Solving by Substitution ──────────────────────────────
function g13() {
  const q = [];
  q.push(mc("medium", "Solve $x+y=6$, $y=2x$.", ["$(2,4)$", "$(4,2)$", "$(3,3)$", "$(2,2)$"], 0));
  q.push(num("hard", "Solve $x+y=7$, $2x+4y=22$: find $x$.", 3, 0));
  q.push(mc("easy", "First step of substitution for $y=2x$, $x+y=9$:", ["replace $y$ with $2x$", "add the equations", "graph them", "divide by 2"], 0));
  q.push(mc("easy", "Solve $y=2x$, $x+y=9$.", ["$(3,6)$", "$(6,3)$", "$(9,0)$", "$(3,3)$"], 0));
  q.push(mc("easy", "Solve $y=x+1$, $2x+y=7$.", ["$(2,3)$", "$(3,2)$", "$(1,2)$", "$(2,2)$"], 0));
  q.push(mc("easy", "Solve $x=2y$, $3x-y=10$.", ["$(4,2)$", "$(2,4)$", "$(2,1)$", "$(4,1)$"], 0));
  q.push(mc("easy", "After substituting, a true statement like $2=2$ means:", ["infinitely many solutions", "no solution", "one solution", "an error"], 0));
  q.push(mc("easy", "After substituting, a false statement like $0=3$ means:", ["no solution", "infinitely many", "one", "two"], 0));
  q.push(ms("easy", "Which equations are easiest to isolate a variable from?", ["$y=2x$", "$x+y=5$", "$2x+3y=7$", "$x=y-1$"], [0, 1, 3]));
  q.push(ms("easy", "Solve $y=x+1$, $2x+y=7$. Which are true?", ["$x=2$", "$y=3$", "solution $(2,3)$", "$x=3$"], [0, 1, 2]));
  q.push(ms("easy", "Which are valid first isolations of $x+2y=8$?", ["$x=8-2y$", "$2y=8-x$", "$y=(8-x)/2$", "$x=8+2y$"], [0, 1, 2]));
  q.push(ms("easy", "Substitution works best when:", ["a variable is already isolated", "a coefficient is $1$", "both terms are $x^2$", "never"], [0, 1]));
  q.push(tf("easy", "Substitution replaces one variable with an expression.", true));
  q.push(tf("easy", "You should substitute into the same equation you isolated from.", false, "Substitute into the OTHER equation."));
  q.push(tf("easy", "Solving $y=2x$, $x+y=9$ gives $x=3$.", true));
  q.push(fill("easy", "Solve $y=3x$, $x+y=8$: $x=$ ___.", ["2"]));
  q.push(fill("easy", "Solve $y=x-3$, $x+y=7$: $x=$ ___.", ["5"]));
  q.push(fill("easy", "Solve $x=2y$, $3x-y=10$: $y=$ ___.", ["2"]));
  q.push(num("easy", "Solve $2x+y=5$, $y=x-1$: find $x$.", 2, 0));
  q.push(num("easy", "Solve $x-y=3$, $2x+y=9$: find $x$.", 4, 0));
  q.push(num("easy", "Solve $y=2x+1$, $3x+y=11$: find $x$.", 2, 0));
  q.push(match("easy", "Match each system to its solution.", ["$y=3x,\\ x+y=8$", "$y=x-3,\\ x+y=7$", "$x=2y,\\ 3x-y=10$"], ["$(2,6)$", "$(5,2)$", "$(4,2)$"], [0, 1, 2]));
  q.push(mc("medium", "Solve $x+y=5$, $2x-y=4$.", ["$(3,2)$", "$(2,3)$", "$(3,-2)$", "$(1,4)$"], 0));
  q.push(mc("medium", "Solve $2x+y=7$, $3x-2y=0$.", ["$(2,3)$", "$(3,2)$", "$(2,1)$", "$(1,5)$"], 0));
  q.push(mc("medium", "Solve $y=4-x$, $2x+2y=8$.", ["infinitely many", "one $(2,2)$", "none", "$(0,4)$"], 0));
  q.push(mc("medium", "Solve $y=2x$, $4x-2y=3$.", ["no solution", "$(0,0)$", "infinitely many", "$(1,2)$"], 0));
  q.push(mc("medium", "Two numbers sum $20$, differ $4$. The larger is:", ["$12$", "$8$", "$16$", "$10$"], 0));
  q.push(mc("medium", "Isolate $y$ from $3x-y=7$:", ["$y=3x-7$", "$y=7-3x$", "$x=7-y$", "$y=3x+7$"], 0));
  q.push(ms("medium", "Solve $x-3y=1$, $2x+y=9$. Which are true?", ["$x=4$", "$y=1$", "solution $(4,1)$", "$x=1$"], [0, 1, 2]));
  q.push(ms("medium", "Which systems have no solution?", ["$y=2x$, $4x-2y=3$", "$y=3x+2$, $6x-2y=1$", "$y=x$, $y=x$", "$y=x+1$, $y=2x$"], [0, 1]));
  q.push(ms("medium", "Which are correct isolations?", ["$x+2y=8\\Rightarrow x=8-2y$", "$2x-y=4\\Rightarrow y=2x-4$", "$x-y=3\\Rightarrow x=3+y$", "$x+y=5\\Rightarrow y=5+x$"], [0, 1, 2]));
  q.push(tf("medium", "A system can be solved by substitution or elimination.", true));
  q.push(tf("medium", "If substitution gives $5=5$, there is exactly one solution.", false, "Infinitely many."));
  q.push(tf("medium", "Solving $2x+y=5$, $y=x-1$ gives $(2,1)$.", true));
  q.push(fill("medium", "Solve $x+y=10$, $y=x+2$: solution ___.", ["(4,6)", "4,6"]));
  q.push(fill("medium", "Solve $3x-y=7$, $y=x+1$: solution ___.", ["(4,5)", "4,5"]));
  q.push(fill("medium", "Two numbers sum $30$, one twice the other: the numbers are ___.", ["20 and 10", "20,10", "10 and 20", "10,20"]));
  q.push(num("medium", "Solve $x+2y=8$, $x=y+2$: find $y$.", 2, 0));
  q.push(num("medium", "Solve $y=2x+1$, $3x+y=11$: find $y$.", 5, 0));
  q.push(num("medium", "Solve $y=2x$, $x+y=18$: find $x$.", 6, 0));
  q.push(match("medium", "Match each system to its number of solutions.", ["$y=2x,\\ 4x-2y=3$", "$y=4-x,\\ 2x+2y=8$", "$y=x+1,\\ y=3x-1$"], ["none", "infinite", "one"], [0, 1, 2]));
  q.push(mc("hard", "A jar of $12$ dimes and quarters is worth \\$2.10. Number of quarters:", ["$6$", "$5$", "$7$", "$8$"], 0));
  q.push(mc("hard", "Solve $3x+2y=16$, $x=2y$.", ["$(4,2)$", "$(2,4)$", "$(4,1)$", "$(2,2)$"], 0));
  q.push(mc("hard", "Solve $x+y=7$, $2x+4y=22$.", ["$(3,4)$", "$(4,3)$", "$(3,3)$", "$(5,2)$"], 0));
  q.push(mc("hard", "A test has $20$ questions worth $1$ or $3$ marks, total $46$. Number of 3-mark questions:", ["$13$", "$7$", "$10$", "$6$"], 0));
  q.push(mc("hard", "Solve $4x-y=10$, $y=2x$.", ["$(5,10)$", "$(10,5)$", "$(5,5)$", "$(2,4)$"], 0));
  q.push(ms("hard", "For $x-3y=1$, $2x+y=9$ (solution $(4,1)$), which are true?", ["$x=4$", "$y=1$", "$4-3(1)=1$", "$2(4)+1=9$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which word problems form a linear system?", ["sum and difference of two numbers", "ticket sales at two prices", "area of a single square", "coin counts and total value"], [0, 1, 3]));
  q.push(ms("hard", "Which are valid steps for $2x+y=7$, $3x-2y=0$?", ["isolate $y=7-2x$", "substitute into $3x-2y=0$", "get $7x=14$", "$x=2$"], [0, 1, 2, 3]));
  q.push(tf("hard", "Substitution is ideal when one equation has an isolated variable.", true));
  q.push(tf("hard", "A coin problem can be modelled with two equations.", true));
  q.push(tf("hard", "If a substitution yields $x=2.5$, the system has no solution.", false, "Non-integer solutions are valid."));
  q.push(fill("hard", "Solve $x-3y=1$, $2x+y=9$: solution ___.", ["(4,1)", "4,1"]));
  q.push(fill("hard", "$d+q=20$, $0.10d+0.25q=3.65$: number of quarters ___.", ["11"]));
  q.push(fill("hard", "Two numbers differ by $4$, sum $50$: the larger is ___.", ["27"]));
  q.push(num("hard", "Solve $x+y=12$, $2x+4y=34$: find $y$.", 5, 0));
  q.push(num("hard", "Adult \\$10, child \\$6; $200$ tickets, \\$1640. Find the number of adults.", 110, 0));
  q.push(num("hard", "Solve $3x-2y=4$, $x=2y$: find $x$.", 2, 0));
  q.push(order("hard", "Order the substitution steps.", ["Isolate a variable in one equation", "Substitute into the other equation", "Solve for the remaining variable", "Back-substitute to find the other"]));
  q.push(match("hard", "Match each system to its solution.", ["$x+y=7,\\ 2x+4y=22$", "$y=2x,\\ 4x-y=10$", "$x+2y=8,\\ x=y+2$"], ["$(3,4)$", "$(5,10)$", "$(4,2)$"], [0, 1, 2]));
  return q;
}

// ── 1.4 Solving by Elimination ───────────────────────────────
function g14() {
  const q = [];
  q.push(mc("medium", "Solve $x-y=1$, $x+y=7$.", ["$(4,3)$", "$(3,4)$", "$(4,-3)$", "$(1,7)$"], 0));
  q.push(num("hard", "Solve $5x+2y=16$, $3x+2y=12$: find $y$.", 3, 0));
  q.push(mc("easy", "To eliminate by adding, a variable's coefficients should be:", ["opposites", "equal", "both positive", "both 1"], 0));
  q.push(mc("easy", "Solve $x+y=10$, $x-y=4$.", ["$(7,3)$", "$(3,7)$", "$(5,5)$", "$(6,4)$"], 0));
  q.push(mc("easy", "Solve $2x+y=7$, $x-y=2$.", ["$(3,1)$", "$(1,3)$", "$(3,-1)$", "$(2,3)$"], 0));
  q.push(mc("easy", "Adding $x+y=10$ and $x-y=4$ gives:", ["$2x=14$", "$2y=14$", "$2x=6$", "$x=14$"], 0));
  q.push(mc("easy", "Solve $3x+2y=12$, $3x-2y=0$.", ["$(2,3)$", "$(3,2)$", "$(2,1)$", "$(4,0)$"], 0));
  q.push(mc("easy", "When coefficients are equal, you should:", ["subtract", "add", "multiply", "divide"], 0));
  q.push(ms("easy", "Which pairs are eliminated by adding directly?", ["$2x$ and $-2x$", "$y$ and $-y$", "$3x$ and $3x$", "$5y$ and $-5y$"], [0, 1, 3]));
  q.push(ms("easy", "Solve $x+y=10$, $x-y=4$. Which are true?", ["$x=7$", "$y=3$", "solution $(7,3)$", "$x=3$"], [0, 1, 2]));
  q.push(ms("easy", "Which steps help eliminate a variable?", ["multiply an equation by a constant", "add or subtract the equations", "line up like terms", "change the variables"], [0, 1, 2]));
  q.push(ms("easy", "To solve $2x+y=5$, $x+3y=10$ you could:", ["multiply the 1st by 3", "subtract the equations", "multiply the 2nd by 2", "add directly"], [0, 1, 2]));
  q.push(tf("easy", "Elimination removes one variable by adding or subtracting.", true));
  q.push(tf("easy", "You may multiply an equation by a number to set up elimination.", true));
  q.push(tf("easy", "Adding $2x+y=5$ and $2x-y=1$ eliminates $x$.", false, "It eliminates $y$."));
  q.push(fill("easy", "Solve $x+y=8$, $x-y=2$: $x=$ ___.", ["5"]));
  q.push(fill("easy", "Solve $x+2y=7$, $x-2y=1$: $x=$ ___.", ["4"]));
  q.push(fill("easy", "Solve $3x+y=10$, $x+y=4$: $x=$ ___.", ["3"]));
  q.push(num("easy", "Solve $2x+3y=12$, $2x-y=4$: find $y$.", 2, 0));
  q.push(num("easy", "Solve $3x+2y=7$, $5x+2y=11$: find $x$.", 2, 0));
  q.push(num("easy", "Solve $2x+5y=1$, $3x-5y=14$: find $x$.", 3, 0));
  q.push(match("easy", "Match each coefficient pair to the operation that eliminates it.", ["$3x$ and $3x$", "$2y$ and $-2y$", "$5x$ and $-5x$"], ["subtract", "add", "add"], [0, 1, 2]));
  q.push(mc("medium", "Solve $2x+y=5$, $x+3y=10$.", ["$(1,3)$", "$(3,1)$", "$(2,2)$", "$(1,2)$"], 0));
  q.push(mc("medium", "Solve $2x+3y=7$, $3x+2y=8$.", ["$(2,1)$", "$(1,2)$", "$(2,2)$", "$(3,1)$"], 0));
  q.push(mc("medium", "Solve $4x-2y=2$, $2x-y=1$.", ["infinitely many", "one", "none", "$(1,1)$"], 0));
  q.push(mc("medium", "Solve $x+y=3$, $2x+2y=8$.", ["no solution", "one", "infinitely many", "$(1,2)$"], 0));
  q.push(mc("medium", "Solve $x+3y=9$, $2x+y=8$.", ["$(3,2)$", "$(2,3)$", "$(3,3)$", "$(1,2)$"], 0));
  q.push(mc("medium", "From $2a+3c=31$, $a+2c=18$, the child price $c$ is:", ["$5$", "$8$", "$6$", "$4$"], 0));
  q.push(ms("medium", "Solve $2x+3y=7$, $3x+2y=8$. Which are true?", ["$x=2$", "$y=1$", "solution $(2,1)$", "$x=1$"], [0, 1, 2]));
  q.push(ms("medium", "Which systems have infinitely many solutions?", ["$4x-2y=2$, $2x-y=1$", "$x+y=3$, $2x+2y=6$", "$x+y=3$, $2x+2y=8$", "$y=x$, $y=x$"], [0, 1, 3]));
  q.push(ms("medium", "To solve $2x+3y=7$, $3x+2y=8$ by elimination, you can:", ["multiply 1st by 3 and 2nd by 2", "make $6x$ in both", "subtract to remove $x$", "add to remove $y$"], [0, 1, 2]));
  q.push(tf("medium", "If subtracting gives $0=2$, the system has no solution.", true));
  q.push(tf("medium", "Elimination and substitution give the same solution.", true));
  q.push(tf("medium", "Multiplying only one side of an equation is valid.", false, "Multiply the whole equation."));
  q.push(fill("medium", "Solve $x+3y=9$, $2x+y=8$: solution ___.", ["(3,2)", "3,2"]));
  q.push(fill("medium", "Solve $3x+2y=7$, $5x+2y=11$: solution ___.", ["(2,0.5)", "2,0.5", "(2,1/2)"]));
  q.push(fill("medium", "Three pens + 2 erasers \\$13; 1 pen + 2 erasers \\$7. Pen costs \\$___.", ["3"]));
  q.push(num("medium", "Solve $2x+5y=1$, $3x-5y=14$: find $y$.", -1, 0));
  q.push(num("medium", "Solve $4x+3y=10$, $2x+y=4$: find $y$.", 2, 0));
  q.push(num("medium", "Solve $x+y=8$, $x-y=2$: find $y$.", 3, 0));
  q.push(match("medium", "Match each system to its solution.", ["$x+y=10,\\ x-y=4$", "$2x+y=7,\\ x-y=2$", "$3x+2y=12,\\ 3x-2y=0$"], ["$(7,3)$", "$(3,1)$", "$(2,3)$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $3x+4y=5$, $2x+3y=4$.", ["$(-1,2)$", "$(1,2)$", "$(2,-1)$", "$(-1,-2)$"], 0));
  q.push(mc("hard", "Solve $5x+2y=16$, $3x+2y=12$.", ["$(2,3)$", "$(3,2)$", "$(2,2)$", "$(4,3)$"], 0));
  q.push(mc("hard", "From $2a+3c=31$, $a+2c=18$, the adult price $a$ is:", ["$8$", "$5$", "$10$", "$6$"], 0));
  q.push(mc("hard", "Solve $4x+3y=10$, $2x+y=4$.", ["$(1,2)$", "$(2,1)$", "$(1,1)$", "$(2,2)$"], 0));
  q.push(mc("hard", "Solve $7x+2y=24$, $3x+2y=12$.", ["$(3,1.5)$", "$(3,2)$", "$(2,3)$", "$(1.5,3)$"], 0));
  q.push(ms("hard", "For $3x+4y=5$, $2x+3y=4$ (solution $(-1,2)$), which are true?", ["$x=-1$", "$y=2$", "$3(-1)+4(2)=5$", "$2(-1)+3(2)=4$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which require multiplying BOTH equations before elimination?", ["$2x+3y=7$, $3x+2y=8$", "$x+y=4$, $x-y=2$", "$3x+4y=5$, $2x+3y=4$", "$2x+y=5$, $x+3y=10$"], [0, 2]));
  q.push(ms("hard", "Which are inconsistent systems?", ["$x+y=3$, $x+y=7$", "$2x+2y=4$, $x+y=5$", "$x+y=3$, $2x+2y=6$", "$3x=6$, $3x=9$"], [0, 1, 3]));
  q.push(tf("hard", "A $2\\times2$ linear system has at most one solution unless the lines coincide.", true));
  q.push(tf("hard", "Elimination can solve systems where no variable is pre-isolated.", true));
  q.push(tf("hard", "If both variables cancel and you get a true statement, there is no solution.", false, "Infinitely many."));
  q.push(fill("hard", "Solve $3x+4y=5$, $2x+3y=4$: solution ___.", ["(-1,2)", "-1,2"]));
  q.push(fill("hard", "Solve $5x+2y=16$, $3x+2y=12$: solution ___.", ["(2,3)", "2,3"]));
  q.push(fill("hard", "A test: $x+y=20$ questions, $x+3y=46$ marks: number of 3-mark questions ___.", ["13"]));
  q.push(num("hard", "Solve $3x+4y=5$, $2x+3y=4$: find $x$.", -1, 0));
  q.push(num("hard", "Solve $4x+3y=10$, $2x+y=4$: find $x$.", 1, 0));
  q.push(num("hard", "Solve $2x+3y=12$, $2x-y=4$: find $x$.", 3, 0));
  q.push(order("hard", "Order the elimination steps.", ["Line up like terms in both equations", "Multiply to match a variable's coefficients", "Add or subtract to eliminate it", "Solve and back-substitute"]));
  q.push(match("hard", "Match each system to its number of solutions.", ["$x+y=3,\\ 2x+2y=8$", "$4x-2y=2,\\ 2x-y=1$", "$x+3y=9,\\ 2x+y=8$"], ["none", "infinite", "one"], [0, 1, 2]));
  return q;
}

// ── 1.5 Solving Problems with Linear Systems ─────────────────
function g15() {
  const q = [];
  q.push(mc("medium", "Two numbers sum $18$ and differ $2$. The larger is:", ["$10$", "$8$", "$9$", "$12$"], 0));
  q.push(num("hard", "Two numbers sum $50$; the larger is $8$ more than the smaller. Find the larger.", 29, 0));
  q.push(mc("easy", "Two numbers sum $25$, differ $7$. The larger is:", ["$16$", "$9$", "$18$", "$12$"], 0));
  q.push(mc("easy", "If $x+y=20$ and $x-y=4$, then $x=$", ["$12$", "$8$", "$10$", "$16$"], 0));
  q.push(mc("easy", "Adult \\$10, child \\$6, $200$ tickets, \\$1640. One equation is $a+c=200$; the other is:", ["$10a+6c=1640$", "$6a+10c=1640$", "$a+c=1640$", "$10a=6c$"], 0));
  q.push(mc("easy", "'The sum of two numbers is 30' becomes:", ["$x+y=30$", "$xy=30$", "$x-y=30$", "$x/y=30$"], 0));
  q.push(mc("easy", "'Length is 3 more than width' becomes:", ["$l=w+3$", "$l=3w$", "$w=l+3$", "$l+w=3$"], 0));
  q.push(mc("easy", "'One number is twice the other' becomes:", ["$x=2y$", "$x=y+2$", "$x+2=y$", "$2x=2y$"], 0));
  q.push(ms("easy", "Good variable choices for a ticket problem:", ["$a=$ adults", "$c=$ children", "$a=$ total money", "$x=$ everything"], [0, 1]));
  q.push(ms("easy", "Which phrases mean addition?", ["sum", "total", "increased by", "difference"], [0, 1, 2]));
  q.push(ms("easy", "For 'two numbers sum 25, differ 7', which equations?", ["$x+y=25$", "$x-y=7$", "$xy=25$", "$x+y=7$"], [0, 1]));
  q.push(ms("easy", "Which are linear-system word problems?", ["mixing two solutions", "two ticket prices", "area of one square", "coin counts and value"], [0, 1, 3]));
  q.push(tf("easy", "You should define variables before writing equations.", true));
  q.push(tf("easy", "'Difference' usually means subtraction.", true));
  q.push(tf("easy", "A problem with two unknowns needs only one equation.", false));
  q.push(fill("easy", "Two numbers sum $40$, differ $6$: the larger is ___.", ["23"]));
  q.push(fill("easy", "If $x=2y$ and $x+y=30$, then $y=$ ___.", ["10"]));
  q.push(fill("easy", "Perimeter $=26$ and $l=w+3$. Then $w=$ ___.", ["5"]));
  q.push(num("easy", "Two numbers sum $25$, differ $7$. Find the smaller.", 9, 0));
  q.push(num("easy", "Adult \\$10, child \\$6, $200$ tickets, \\$1640. Find the number of adults.", 110, 0));
  q.push(num("easy", "Rectangle length twice the width, perimeter $36$. Find the width.", 6, 0));
  q.push(match("easy", "Match each phrase to its equation (numbers $x,y$).", ["sum is 12", "one is twice the other", "differ by 4"], ["$x+y=12$", "$x=2y$", "$x-y=4$"], [0, 1, 2]));
  q.push(mc("medium", "A box of $20$ dimes and quarters is worth \\$3.65. Number of quarters:", ["$11$", "$9$", "$10$", "$13$"], 0));
  q.push(mc("medium", "From $2b+3f=12$, $3b+f=11$, the burger price $b$ is:", ["$3$", "$2$", "$4$", "$5$"], 0));
  q.push(mc("medium", "Mix 40% and 70% to get $30$ L of 50%. Litres of 70%:", ["$10$", "$20$", "$15$", "$5$"], 0));
  q.push(mc("medium", "Maria is $4\\times$ her son; in 5 years $3\\times$. Son's age:", ["$10$", "$8$", "$12$", "$5$"], 0));
  q.push(mc("medium", "A canoe goes $12$ km down in 2 h, up in 3 h. Canoe speed (km/h):", ["$5$", "$1$", "$6$", "$4$"], 0));
  q.push(mc("medium", "Sum is $50$; the larger is $8$ more than the smaller. The larger is:", ["$29$", "$21$", "$25$", "$30$"], 0));
  q.push(ms("medium", "For 'a+c=200, 10a+6c=1640' (a=110, c=90), which are true?", ["$a=110$", "$c=90$", "$a+c=200$", "$a=90$"], [0, 1, 2]));
  q.push(ms("medium", "For a mixture forming $x+y=30$, $0.4x+0.7y=15$, which are true?", ["total volume 30", "concentration equation", "$x=$ litres of 40%", "$y=$ litres of 70%"], [0, 1, 2, 3]));
  q.push(ms("medium", "Which answers should usually be rejected in context?", ["negative length", "negative number of people", "fractional count of tickets", "a positive length"], [0, 1, 2]));
  q.push(tf("medium", "Mixture problems balance total amount and total content.", true));
  q.push(tf("medium", "Upstream speed equals boat speed minus current.", true));
  q.push(tf("medium", "Every answer the algebra gives must be accepted in context.", false));
  q.push(fill("medium", "Coffee \\$3, muffin \\$2 from '3c+2m=13, c+2m=7'. Coffee = \\$___.", ["3"]));
  q.push(fill("medium", "Father $3\\times$ daughter; in 10 years $2\\times$. Daughter's age ___.", ["10"]));
  q.push(fill("medium", "Plane: $600$ km with wind in 2 h, against in 3 h. Plane speed ___ km/h.", ["250"]));
  q.push(num("medium", "Two numbers sum $40$, differ $6$. Find the smaller.", 17, 0));
  q.push(num("medium", "A box of $25$ dimes and nickels is worth \\$1.85. Find the number of dimes.", 12, 0));
  q.push(num("medium", "Complementary angles, one $30^\\circ$ larger. Find the larger angle.", 60, 0));
  q.push(match("medium", "Match each scenario to its key equation.", ["mixture of two liquids", "ticket counts", "difference of two numbers"], ["total amount", "total count", "difference"], [0, 1, 2]));
  q.push(mc("hard", "\\$5000 split at 3% and 5% earns \\$210. Amount at 5%:", ["\\$3000", "\\$2000", "\\$2500", "\\$1500"], 0));
  q.push(mc("hard", "A theatre: $500$ people, \\$12 and \\$8, total \\$5200. Number of adults:", ["$300$", "$200$", "$250$", "$350$"], 0));
  q.push(mc("hard", "Two trains $400$ km apart move toward each other at 60 and 40 km/h. They meet after (h):", ["$4$", "$5$", "$6$", "$10$"], 0));
  q.push(mc("hard", "A boat: $30$ km down in 2 h, $30$ km up in 5 h. The current (km/h):", ["$4.5$", "$1.5$", "$3$", "$6$"], 0));
  q.push(mc("hard", "Mix 20% and 50% to get $60$ L of 30%. Litres of 20%:", ["$40$", "$20$", "$30$", "$45$"], 0));
  q.push(ms("hard", "For \\$5000 ($x$ at 3%, $y$ at 5%, \\$210 interest), which are true?", ["$x+y=5000$", "$0.03x+0.05y=210$", "$y=3000$", "$x=2000$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which require two equations to solve?", ["two prices and two purchases", "one unknown only", "mixture of two concentrations", "speed with and against a current"], [0, 2, 3]));
  q.push(ms("hard", "Good context checks include:", ["counts are whole numbers", "lengths are positive", "times are non-negative", "ignore the units"], [0, 1, 2]));
  q.push(tf("hard", "Interest problems can be modelled with a linear system.", true));
  q.push(tf("hard", "With/against-current problems give boat speed and current.", true));
  q.push(tf("hard", "A negative number of tickets is an acceptable answer.", false));
  q.push(fill("hard", "Theatre: $a+s=500$, $12a+8s=5200$. Number of adults ___.", ["300"]));
  q.push(fill("hard", "\\$5000 at 3% and 5% earns \\$210. Amount at 3% = \\$___.", ["2000"]));
  q.push(fill("hard", "Two numbers: sum 50, larger 8 more than smaller. The smaller is ___.", ["21"]));
  q.push(num("hard", "Mix 20% and 50% for $60$ L of 30%. Litres of 50% = ___.", 20, 0));
  q.push(num("hard", "Theatre \\$12 and \\$8, $500$ people, \\$5200. Number of students = ___.", 200, 0));
  q.push(num("hard", "Trains $400$ km apart, 60 and 40 km/h toward each other. Hours to meet = ___.", 4, 0));
  q.push(order("hard", "Order the steps to solve a word problem with a system.", ["Define two variables", "Write two equations", "Solve the system", "State and check the answer"]));
  q.push(match("hard", "Match each problem to its equations.", ["sum and difference", "two prices, two purchases", "mixture of concentrations"], ["$x+y$ and $x-y$", "two cost equations", "total and content"], [0, 1, 2]));
  return q;
}

// ── 1.6 Number of Solutions ──────────────────────────────────
function g16() {
  const q = [];
  q.push(mc("medium", "$y=4x-1$ and $y=4x-1$ have:", ["infinitely many", "one", "none", "two"], 0));
  q.push(num("hard", "Find $k$ so $kx+2y=8$ and $3x+y=5$ have no solution.", 6, 0));
  q.push(mc("easy", "Different slopes means the system has:", ["one solution", "no solution", "infinitely many", "two"], 0));
  q.push(mc("easy", "Same slope but different intercepts means:", ["no solution", "one", "infinitely many", "two"], 0));
  q.push(mc("easy", "Same slope and same intercept means:", ["infinitely many", "one", "none", "two"], 0));
  q.push(mc("easy", "$y=2x+1$ and $y=3x-2$ have:", ["one solution", "none", "infinitely many", "two"], 0));
  q.push(mc("easy", "$y=2x+1$ and $y=2x-4$ have:", ["no solution", "one", "infinitely many", "two"], 0));
  q.push(mc("easy", "$y=2x+1$ and $4x-2y=-2$ have:", ["infinitely many", "one", "none", "two"], 0));
  q.push(ms("easy", "Which guarantee exactly one solution?", ["different slopes", "slopes 2 and 3", "slopes 2 and 2", "slopes $-1$ and $1$"], [0, 1, 3]));
  q.push(ms("easy", "Which describe parallel (no-solution) systems?", ["equal slopes", "different intercepts", "same line", "different slopes"], [0, 1]));
  q.push(ms("easy", "Which pairs are the same line?", ["$y=x+2$, $2y=2x+4$", "$y=2x$, $4x-2y=0$", "$y=x$, $y=x+1$", "$y=3x$, $y=3x$"], [0, 1, 3]));
  q.push(ms("easy", "How can you find the number of solutions?", ["compare slopes", "compare intercepts", "graph the lines", "guess randomly"], [0, 1, 2]));
  q.push(tf("easy", "Two lines with different slopes always intersect once.", true));
  q.push(tf("easy", "Parallel lines have the same slope.", true));
  q.push(tf("easy", "Coincident lines have no solution.", false, "They have infinitely many."));
  q.push(fill("easy", "$y=3x-1$ and $y=3x+4$ have ___ solutions.", ["no", "0", "zero"]));
  q.push(fill("easy", "$y=x+2$ and $2y=2x+4$ have ___ solutions.", ["infinitely many", "infinite"]));
  q.push(fill("easy", "$y=2x$ and $y=3x$ have ___ solution(s).", ["one", "1"]));
  q.push(num("easy", "The slope of $y=5x-2$ is ___.", 5, 0));
  q.push(num("easy", "The slope of $3x-y=4$ (as $y=mx+b$) is ___.", 3, 0));
  q.push(num("easy", "The slope of $2x+y=5$ (as $y=mx+b$) is ___.", -2, 0));
  q.push(match("easy", "Match each pair to its number of solutions.", ["different slopes", "same slope, different intercept", "the same line"], ["one", "none", "infinite"], [0, 1, 2]));
  q.push(mc("medium", "$2x+3y=6$ and $4x+6y=12$ have:", ["infinitely many", "one", "none", "two"], 0));
  q.push(mc("medium", "$2x+3y=6$ and $4x+6y=7$ have:", ["no solution", "one", "infinitely many", "two"], 0));
  q.push(mc("medium", "$x-y=1$ and $x+y=5$ have:", ["one", "none", "infinitely many", "two"], 0));
  q.push(mc("medium", "For no solution, $y=kx+2$ and $y=3x-1$ need $k=$", ["$3$", "$-3$", "$2$", "$0$"], 0));
  q.push(mc("medium", "$y=kx+4$ and $y=2x+4$ have infinitely many when $k=$", ["$2$", "$-2$", "$4$", "$0$"], 0));
  q.push(mc("medium", "Lines with slopes $2$ and $-1/2$:", ["intersect once", "are parallel", "coincide", "never meet"], 0));
  q.push(ms("medium", "Which systems have infinitely many solutions?", ["$2x+3y=6$, $4x+6y=12$", "$x+y=2$, $2x+2y=4$", "$x+y=2$, $2x+2y=5$", "$y=x$, $y=x$"], [0, 1, 3]));
  q.push(ms("medium", "Which systems have no solution?", ["$y=2x+1$, $y=2x-3$", "$5x+2y=10$, $5x+2y=4$", "$x-y=1$, $x+y=5$", "$x+y=3$, $2x+2y=10$"], [0, 1, 3]));
  q.push(ms("medium", "To compare $a_1x+b_1y=c_1$ and $a_2x+b_2y=c_2$, check ratios:", ["$a_1/a_2$", "$b_1/b_2$", "$c_1/c_2$", "the colours"], [0, 1, 2]));
  q.push(tf("medium", "$y=3x-1$ and $6x-2y=2$ are the same line.", true));
  q.push(tf("medium", "Equal slope but different intercept means infinitely many.", false, "That is no solution."));
  q.push(tf("medium", "If $a_1/a_2=b_1/b_2=c_1/c_2$ the lines coincide.", true));
  q.push(fill("medium", "$y=2x+1$ and $y=2x+5$ have ___ solutions.", ["no", "0", "zero"]));
  q.push(fill("medium", "For $y=kx-3$ parallel to $y=5x+1$, $k=$ ___.", ["5"]));
  q.push(fill("medium", "$3x-y=2$ and $x+y=6$ have ___ solution(s).", ["one", "1"]));
  q.push(num("medium", "Find $k$ so $y=kx+4$ and $y=2x+4$ coincide.", 2, 0));
  q.push(num("medium", "Find $k$ so $y=kx+1$ is parallel to $y=4x-5$.", 4, 0));
  q.push(num("medium", "The slope of $4x+6y=12$ (as a decimal, 2 dp) is ___.", -0.67, 0.02));
  q.push(match("medium", "Match each system to its number of solutions.", ["$2x+3y=6,\\ 4x+6y=12$", "$2x+3y=6,\\ 4x+6y=7$", "$x-y=1,\\ x+y=5$"], ["infinite", "none", "one"], [0, 1, 2]));
  q.push(mc("hard", "$kx+3y=6$ and $2x+y=4$ have no solution when $k=$", ["$6$", "$3$", "$2$", "$-6$"], 0));
  q.push(mc("hard", "$2x+ky=4$ and $x+2y=3$ have one solution unless $k=$", ["$4$", "$2$", "$-4$", "$0$"], 0));
  q.push(mc("hard", "For infinitely many, $6x+2y=8$ and $3x+y=$", ["$4$", "$8$", "$2$", "$1$"], 0));
  q.push(mc("hard", "Lines with $a_1/a_2=b_1/b_2\\ne c_1/c_2$ are:", ["parallel (no solution)", "coincident", "intersecting", "perpendicular"], 0));
  q.push(mc("hard", "If a system reduces to $0=0$, it has:", ["infinitely many", "one", "none", "two"], 0));
  q.push(ms("hard", "Which $k$ make $y=kx+1$ and $y=3x-2$ NOT parallel?", ["$k=2$", "$k=4$", "$k=3$", "$k=0$"], [0, 1, 3]));
  q.push(ms("hard", "Which are true of coincident lines?", ["same slope", "same intercept", "infinitely many solutions", "all ratios equal"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which give no solution for $a_1x+b_1y=c_1$, $a_2x+b_2y=c_2$?", ["$a_1/a_2=b_1/b_2$", "$\\ne c_1/c_2$", "equal slopes", "different intercepts"], [0, 1, 2, 3]));
  q.push(tf("hard", "A system with a unique solution has lines of different slopes.", true));
  q.push(tf("hard", "$kx+3y=6$ and $2x+y=4$ are parallel when $k=6$.", true));
  q.push(tf("hard", "Changing only the constant in one equation can turn coincident lines into parallel ones.", true));
  q.push(fill("hard", "$kx+3y=6$ and $2x+y=4$ have no solution when $k=$ ___.", ["6"]));
  q.push(fill("hard", "$6x+2y=8$ and $3x+y=c$ coincide when $c=$ ___.", ["4"]));
  q.push(fill("hard", "If a system gives $0=5$, it has ___ solutions.", ["no", "0", "zero"]));
  q.push(num("hard", "Find $k$ so $kx+3y=6$ and $2x+y=4$ are parallel.", 6, 0));
  q.push(num("hard", "Find $c$ so $4x+2y=10$ and $2x+y=c$ coincide.", 5, 0));
  q.push(num("hard", "Find $k$ so $y=kx-1$ and $y=7x+2$ are parallel.", 7, 0));
  q.push(order("hard", "Order the steps to classify a system.", ["Write both lines in $y=mx+b$", "Compare the slopes", "If equal, compare the intercepts", "State one / none / infinite"]));
  q.push(match("hard", "Match each condition to the number of solutions.", ["slopes differ", "slopes equal, intercepts differ", "slopes and intercepts equal"], ["one", "none", "infinite"], [0, 1, 2]));
  return q;
}

export default [
  { code: "1.1", gen: g11 },
  { code: "1.2", gen: g12 },
  { code: "1.3", gen: g13 },
  { code: "1.4", gen: g14 },
  { code: "1.5", gen: g15 },
  { code: "1.6", gen: g16 },
];
