// MPM2D Unit 2 — Analytic Geometry: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "./helpers.mjs";

// ── 2.1 Midpoint of a Line Segment ───────────────────────────
function g21() {
  const q = [];
  q.push(mc("easy", "Find the midpoint of $(2,4)$ and $(6,10)$.", ["$(4,7)$", "$(8,14)$", "$(4,6)$", "$(2,3)$"], 0));
  q.push(mc("easy", "The midpoint formula is:", ["$\\left(\\frac{x_1+x_2}{2},\\frac{y_1+y_2}{2}\\right)$", "$(x_2-x_1,\\,y_2-y_1)$", "$(x_1x_2,\\,y_1y_2)$", "$\\left(\\frac{x_1-x_2}{2},\\frac{y_1-y_2}{2}\\right)$"], 0));
  q.push(mc("easy", "Find the midpoint of $(0,0)$ and $(8,6)$.", ["$(4,3)$", "$(8,6)$", "$(2,3)$", "$(4,6)$"], 0));
  q.push(mc("easy", "Find the midpoint of $(-2,4)$ and $(2,-4)$.", ["$(0,0)$", "$(0,4)$", "$(2,0)$", "$(-2,0)$"], 0));
  q.push(mc("easy", "The midpoint of a diameter is the circle's:", ["centre", "radius", "circumference", "tangent"], 0));
  q.push(mc("easy", "Find the midpoint of $(1,1)$ and $(5,5)$.", ["$(3,3)$", "$(6,6)$", "$(2,2)$", "$(4,4)$"], 0));
  q.push(ms("easy", "Which equal the midpoint of $(0,0)$ and $(4,8)$?", ["$(2,4)$", "the average of the coordinates", "$(4/2,\\,8/2)$", "$(4,4)$"], [0, 1, 2]));
  q.push(ms("easy", "Which statements about midpoints are true?", ["average the $x$'s", "average the $y$'s", "it lies on the segment", "it is an endpoint"], [0, 1, 2]));
  q.push(ms("easy", "Which give a midpoint with integer coordinates?", ["$(0,0),(4,6)$", "$(0,0),(2,2)$", "$(2,2),(3,4)$", "$(-2,-2),(2,2)$"], [0, 1, 3]));
  q.push(ms("easy", "To find a missing endpoint from midpoint $M$ and endpoint $A$:", ["$B=2M-A$", "double $M$, subtract $A$", "$B=(2M_x-A_x,\\,2M_y-A_y)$", "$B=M-A$"], [0, 1, 2]));
  q.push(tf("easy", "The midpoint is the average of the endpoints' coordinates.", true));
  q.push(tf("easy", "The midpoint of $(0,0)$ and $(6,0)$ is $(3,0)$.", true));
  q.push(tf("easy", "The midpoint always has integer coordinates.", false));
  q.push(fill("easy", "The midpoint of $(2,2)$ and $(8,6)$ is ___.", ["(5,4)", "5,4"]));
  q.push(fill("easy", "The midpoint of $(-4,0)$ and $(4,0)$ is ___.", ["(0,0)", "0,0"]));
  q.push(fill("easy", "The midpoint of $(1,3)$ and $(3,7)$ is ___.", ["(2,5)", "2,5"]));
  q.push(num("easy", "The $x$-coordinate of the midpoint of $(2,5)$ and $(8,5)$ is ___.", 5, 0));
  q.push(num("easy", "The $y$-coordinate of the midpoint of $(1,2)$ and $(1,10)$ is ___.", 6, 0));
  q.push(num("easy", "Midpoint $(3,4)$, one endpoint $(1,2)$: the other endpoint's $x$ is ___.", 5, 0));
  q.push(match("easy", "Match each pair to its midpoint.", ["$(0,0),(4,4)$", "$(0,0),(2,8)$", "$(2,2),(6,2)$"], ["$(2,2)$", "$(1,4)$", "$(4,2)$"], [0, 1, 2]));
  q.push(mc("medium", "Find the midpoint of $(-3,5)$ and $(7,-1)$.", ["$(2,2)$", "$(2,3)$", "$(5,2)$", "$(-5,3)$"], 0));
  q.push(mc("medium", "$M=(3,4)$ is a midpoint and one endpoint is $(1,2)$. The other is:", ["$(5,6)$", "$(2,3)$", "$(4,6)$", "$(2,2)$"], 0));
  q.push(mc("medium", "Centre of the circle with diameter $(2,3)$ to $(8,11)$:", ["$(5,7)$", "$(6,8)$", "$(3,4)$", "$(10,14)$"], 0));
  q.push(mc("medium", "Find the midpoint of $(1,2)$ and $(4,5)$.", ["$(2.5,3.5)$", "$(3,4)$", "$(2,3)$", "$(5,7)$"], 0));
  q.push(mc("medium", "Find the midpoint of $(-5,-2)$ and $(3,8)$.", ["$(-1,3)$", "$(1,3)$", "$(-1,5)$", "$(-4,3)$"], 0));
  q.push(mc("medium", "The midpoint of $A(x_1,y_1)$ and the origin is:", ["$(x_1/2,\\,y_1/2)$", "$(x_1,y_1)$", "$(2x_1,2y_1)$", "$(0,0)$"], 0));
  q.push(ms("medium", "Which segments have midpoint $(2,2)$?", ["$(0,0),(4,4)$", "$(1,1),(3,3)$", "$(0,4),(4,0)$", "$(2,0),(2,2)$"], [0, 1, 2]));
  q.push(ms("medium", "For endpoints $(a,b)$ and $(c,d)$, the midpoint:", ["is $\\left(\\frac{a+c}{2},\\frac{b+d}{2}\\right)$", "is on the segment", "is equidistant from both", "equals $(a,b)$"], [0, 1, 2]));
  q.push(ms("medium", "For $M=(0,0)$, $A=(3,-4)$, the other endpoint $B$:", ["$=(-3,4)$", "$=2M-A$", "$=(-A_x,-A_y)$", "$=(3,-4)$"], [0, 1, 2]));
  q.push(ms("medium", "For $(0,0)$ and $(6,8)$, which are true?", ["midpoint $(3,4)$", "midpoint is equidistant from both", "it is $5$ from each endpoint", "midpoint $(6,8)$"], [0, 1, 2]));
  q.push(tf("medium", "The midpoint of $(-2,-2)$ and $(2,2)$ is the origin.", true));
  q.push(tf("medium", "Given a midpoint and one endpoint you can find the other.", true));
  q.push(tf("medium", "The midpoint of $(1,1)$ and $(2,2)$ has integer coordinates.", false));
  q.push(fill("medium", "Midpoint $(2,5)$, endpoint $(-1,3)$: the other endpoint is ___.", ["(5,7)", "5,7"]));
  q.push(fill("medium", "The midpoint of $(0.5,2)$ and $(3.5,6)$ is ___.", ["(2,4)", "2,4"]));
  q.push(fill("medium", "Centre of the circle with diameter $(-6,2)$ to $(4,8)$ is ___.", ["(-1,5)", "-1,5"]));
  q.push(num("medium", "The $x$-coordinate of the midpoint of $(2,-1)$ and $(8,5)$ is ___.", 5, 0));
  q.push(num("medium", "Midpoint $(4,1)$, endpoint $(1,-2)$: the other endpoint's $y$ is ___.", 4, 0));
  q.push(num("medium", "The $y$-coordinate of the midpoint of $(-7,-3)$ and $(-1,5)$ is ___.", 1, 0));
  q.push(match("medium", "Match each pair to its midpoint.", ["$(-3,5),(7,-1)$", "$(1,2),(4,5)$", "$(-5,-2),(3,8)$"], ["$(2,2)$", "$(2.5,3.5)$", "$(-1,3)$"], [0, 1, 2]));
  q.push(mc("hard", "Triangle $A(-2,1),B(4,3),C(0,-5)$: the midpoint of $AB$ is:", ["$(1,2)$", "$(2,2)$", "$(1,1)$", "$(3,4)$"], 0));
  q.push(mc("hard", "Same triangle: the midpoint of the segment joining the midpoints of $AB$ and $AC$ is:", ["$(0,0)$", "$(1,2)$", "$(-1,-2)$", "$(0,-1)$"], 0));
  q.push(mc("hard", "$M=(2,3)$ is the midpoint of $A(a,1)$ and $B(6,5)$. Find $a$.", ["$-2$", "$4$", "$2$", "$8$"], 0));
  q.push(mc("hard", "The midpoints of the sides of triangle $(0,0),(6,0),(0,8)$ are:", ["$(3,0),(3,4),(0,4)$", "$(6,0),(0,8),(0,0)$", "$(2,0),(0,2),(2,2)$", "all $(3,4)$"], 0));
  q.push(mc("hard", "A segment from $(1,2)$ has midpoint $(4,6)$. Its other endpoint is:", ["$(7,10)$", "$(2.5,4)$", "$(5,8)$", "$(3,4)$"], 0));
  q.push(ms("hard", "For midpoint of $(2,3),(8,11)=(5,7)$, which are true?", ["$x$ is the average of $2,8$", "$y$ is the average of $3,11$", "it is the centre if these are diameter ends", "midpoint is $(10,14)$"], [0, 1, 2]));
  q.push(ms("hard", "Given $M$ and endpoint $A$, the other endpoint $B$ satisfies:", ["$B_x=2M_x-A_x$", "$B_y=2M_y-A_y$", "$M$ is the midpoint of $AB$", "$B=A$"], [0, 1, 2]));
  q.push(ms("hard", "The segment joining the midpoints of two sides of a triangle:", ["is parallel to the third side", "is half its length", "is a midsegment", "is longer than the third side"], [0, 1, 2]));
  q.push(ms("hard", "Which segments share the midpoint $(0,0)$?", ["$(-3,4),(3,-4)$", "$(-1,-1),(1,1)$", "$(2,2),(-2,-2)$", "$(0,0),(1,1)$"], [0, 1, 2]));
  q.push(tf("hard", "The point dividing a segment in half is unique.", true));
  q.push(tf("hard", "The midpoint of a vertical segment has the same $x$ as both endpoints.", true));
  q.push(tf("hard", "Two different segments can never share the same midpoint.", false));
  q.push(fill("hard", "$M=(3,1)$ is the midpoint of $A(1,-2)$ and $B$. Find $B$.", ["(5,4)", "5,4"]));
  q.push(fill("hard", "The midpoint of $(2.5,-1.5)$ and $(3.5,4.5)$ is ___.", ["(3,1.5)", "3,1.5"]));
  q.push(fill("hard", "If $(k,4)$ is the midpoint of $(2,2)$ and $(8,6)$, then $k=$ ___.", ["5"]));
  q.push(num("hard", "$M=(4,1)$, $P=(1,-2)$: the other endpoint's $x$ is ___.", 7, 0));
  q.push(num("hard", "The $x$-coordinate of the midpoint of $(0,0)$ and $(10,10)$ is ___.", 5, 0));
  q.push(num("hard", "If the midpoint of $(a,3)$ and $(7,3)$ is $(5,3)$, find $a$.", 3, 0));
  q.push(order("hard", "Order the steps to find a missing endpoint from the midpoint.", ["Write the midpoint formula for each coordinate", "Substitute the known midpoint and endpoint", "Solve $2M_x-A_x$ for the missing $x$", "Solve $2M_y-A_y$ for the missing $y$"]));
  q.push(match("hard", "Triangle $A(0,0),B(6,0),C(0,8)$: match each midpoint.", ["midpoint of $AB$", "midpoint of $AC$", "midpoint of $BC$"], ["$(3,0)$", "$(0,4)$", "$(3,4)$"], [0, 1, 2]));
  return q;
}

// ── 2.2 Length of a Line Segment ─────────────────────────────
function g22() {
  const q = [];
  q.push(mc("easy", "The distance between two points is:", ["$\\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}$", "$(x_2-x_1)+(y_2-y_1)$", "$\\sqrt{x_2x_1+y_2y_1}$", "$(x_2-x_1)^2+(y_2-y_1)^2$"], 0));
  q.push(mc("easy", "Distance from $(0,0)$ to $(3,4)$:", ["$5$", "$7$", "$1$", "$25$"], 0));
  q.push(mc("easy", "Distance from $(0,0)$ to $(6,8)$:", ["$10$", "$14$", "$48$", "$2$"], 0));
  q.push(mc("easy", "Distance from $(1,2)$ to $(4,6)$:", ["$5$", "$7$", "$25$", "$3$"], 0));
  q.push(mc("easy", "Length of the horizontal segment $(2,3)$ to $(7,3)$:", ["$5$", "$4$", "$10$", "$3$"], 0));
  q.push(mc("easy", "Length of the vertical segment $(1,2)$ to $(1,9)$:", ["$7$", "$8$", "$11$", "$3$"], 0));
  q.push(ms("easy", "Which equal the distance from $(0,0)$ to $(3,4)$?", ["$5$", "$\\sqrt{9+16}$", "$\\sqrt{25}$", "$7$"], [0, 1, 2]));
  q.push(ms("easy", "Distance is always:", ["non-negative", "a length", "found with the Pythagorean theorem", "sometimes negative"], [0, 1, 2]));
  q.push(ms("easy", "Which pairs are $5$ apart?", ["$(0,0),(3,4)$", "$(0,0),(5,0)$", "$(1,1),(4,5)$", "$(0,0),(2,2)$"], [0, 1, 2]));
  q.push(ms("easy", "To find a segment's length you:", ["subtract the $x$'s", "subtract the $y$'s", "square, add, square-root", "multiply the coordinates"], [0, 1, 2]));
  q.push(tf("easy", "Distance can be negative.", false));
  q.push(tf("easy", "The order of subtraction does not change the distance.", true));
  q.push(tf("easy", "A horizontal segment's length is the difference in $x$-coordinates.", true));
  q.push(fill("easy", "Distance from $(0,0)$ to $(8,6)$ is ___.", ["10"]));
  q.push(fill("easy", "Distance from $(2,3)$ to $(2,9)$ is ___.", ["6"]));
  q.push(fill("easy", "Distance from $(-1,0)$ to $(4,0)$ is ___.", ["5"]));
  q.push(num("easy", "Distance from $(0,0)$ to $(5,12)$ = ___.", 13, 0));
  q.push(num("easy", "Distance from $(1,1)$ to $(4,5)$ = ___.", 5, 0));
  q.push(num("easy", "Distance from $(-2,1)$ to $(2,4)$ = ___.", 5, 0));
  q.push(match("easy", "Match each pair to its distance.", ["$(0,0),(3,4)$", "$(0,0),(6,8)$", "$(0,0),(5,12)$"], ["$5$", "$10$", "$13$"], [0, 1, 2]));
  q.push(mc("medium", "Distance from $(-2,1)$ to $(2,4)$:", ["$5$", "$7$", "$\\sqrt{7}$", "$25$"], 0));
  q.push(mc("medium", "Distance from $(1,1)$ to $(4,3)$ (exact):", ["$\\sqrt{13}$", "$5$", "$\\sqrt{5}$", "$13$"], 0));
  q.push(mc("medium", "Simplify the distance from $(-3,2)$ to $(1,-2)$:", ["$4\\sqrt{2}$", "$\\sqrt{32}$ unsimplified", "$8$", "$4$"], 0));
  q.push(mc("medium", "Perimeter of triangle $(0,0),(4,0),(4,3)$:", ["$12$", "$7$", "$10$", "$24$"], 0));
  q.push(mc("medium", "Which is closer to the origin?", ["$(1,1)$", "$(3,4)$", "they are equal", "cannot tell"], 0));
  q.push(mc("medium", "Distance from $(2,5)$ to $(2,-3)$:", ["$8$", "$2$", "$\\sqrt{8}$", "$10$"], 0));
  q.push(ms("medium", "Which equal $\\sqrt{32}$?", ["$4\\sqrt{2}$", "$\\sqrt{16\\cdot2}$", "$\\approx5.66$", "$16$"], [0, 1, 2]));
  q.push(ms("medium", "For the distance formula, which steps are correct?", ["square the $x$-difference", "square the $y$-difference", "add them", "take the square root"], [0, 1, 2, 3]));
  q.push(ms("medium", "Which triangles are isosceles by side length?", ["$(1,1),(5,1),(3,5)$", "$(0,0),(4,0),(2,3)$", "$(0,0),(6,0),(3,4)$", "$(0,0),(3,0),(0,4)$"], [0, 1, 2]));
  q.push(ms("medium", "The distance from $(0,0)$ to $(a,0)$ is:", ["$|a|$", "$a$ if $a>0$", "always non-negative", "$a^2$"], [0, 1, 2]));
  q.push(tf("medium", "$\\sqrt{50}=5\\sqrt{2}$.", true));
  q.push(tf("medium", "Distance from $(3,4)$ to $(0,0)$ equals distance from $(0,0)$ to $(3,4)$.", true));
  q.push(tf("medium", "A triangle with sides $3,4,5$ is isosceles.", false));
  q.push(fill("medium", "Distance from $(0,0)$ to $(9,12)$ is ___.", ["15"]));
  q.push(fill("medium", "Distance from $(2,1)$ to $(5,5)$ is ___.", ["5"]));
  q.push(fill("medium", "Simplify: distance from $(0,0)$ to $(2,2)$ is ___.", ["2√2", "2\\sqrt{2}", "2sqrt2"]));
  q.push(num("medium", "Distance from $(-5,4)$ to $(7,-1)$ = ___.", 13, 0));
  q.push(num("medium", "Perimeter of triangle $(0,0),(6,0),(0,8)$ = ___.", 24, 0));
  q.push(num("medium", "Distance from $(3,-2)$ to $(3,6)$ = ___.", 8, 0));
  q.push(match("medium", "Match each pair to its exact distance.", ["$(1,1),(4,3)$", "$(0,0),(2,2)$", "$(-3,2),(1,-2)$"], ["$\\sqrt{13}$", "$2\\sqrt{2}$", "$4\\sqrt{2}$"], [0, 1, 2]));
  q.push(mc("hard", "Is triangle $(2,1),(5,1),(2,5)$ right-angled?", ["yes (3-4-5)", "no", "only isosceles", "equilateral"], 0));
  q.push(mc("hard", "The point on the $x$-axis equidistant from $(1,2)$ and $(5,4)$:", ["$(4.5,0)$", "$(3,0)$", "$(4,0)$", "$(2,0)$"], 0));
  q.push(mc("hard", "Each side of the rhombus $(0,0),(4,2),(2,6),(-2,4)$ has length:", ["$\\sqrt{20}$", "$\\sqrt{16}$", "$5$", "$\\sqrt{10}$"], 0));
  q.push(mc("hard", "Which point is farthest from the origin?", ["$(6,8)$", "$(5,5)$", "$(0,9)$", "$(7,1)$"], 0));
  q.push(mc("hard", "Distance between the midpoints of $(0,0),(4,0)$ and of $(0,0),(0,6)$:", ["$\\sqrt{13}$", "$5$", "$\\sqrt{5}$", "$13$"], 0));
  q.push(ms("hard", "For triangle $(1,1),(5,1),(3,5)$, which are true?", ["$AB=4$", "$AC=\\sqrt{20}$", "$BC=\\sqrt{20}$", "it is isosceles"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which sets of three points are collinear?", ["$(0,0),(1,1),(2,2)$", "$(0,0),(2,4),(1,2)$", "$(0,0),(1,2),(2,3)$", "$(1,1),(2,2),(3,3)$"], [0, 1, 3]));
  q.push(ms("hard", "Which confirm a right angle at $B(4,1)$ for $A(1,1),C(4,5)$?", ["$AB$ is horizontal", "$BC$ is vertical", "they are perpendicular", "angle $B=90^\\circ$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which are valid uses of the distance formula?", ["find a segment's length", "check if isosceles", "find a perimeter", "find a slope"], [0, 1, 2]));
  q.push(tf("hard", "If all three sides are equal, the triangle is equilateral.", true));
  q.push(tf("hard", "$(0,0),(3,0),(0,4)$ form a right triangle.", true));
  q.push(tf("hard", "Two points $5$ apart must form a horizontal segment.", false));
  q.push(fill("hard", "The point on the $x$-axis equidistant from $(0,3)$ and $(6,1)$ is $(x,0)$; $x=$ ___.", ["7/3", "2.33", "2.333"]));
  q.push(fill("hard", "The longest side of triangle $(0,0),(6,0),(0,8)$ has length ___.", ["10"]));
  q.push(fill("hard", "A square with vertices $(0,0),(3,0),(3,3),(0,3)$ has side length ___.", ["3"]));
  q.push(num("hard", "Distance from $(-5,4)$ to $(7,-1)$ = ___.", 13, 0));
  q.push(num("hard", "Perimeter of triangle $(0,0),(3,0),(0,4)$ = ___.", 12, 0));
  q.push(num("hard", "Distance from $(0,0)$ to $(20,21)$ = ___.", 29, 0));
  q.push(order("hard", "Order the steps of the distance formula.", ["Find the difference in $x$", "Find the difference in $y$", "Square each and add", "Take the square root"]));
  q.push(match("hard", "Match each triangle to its type (by side lengths).", ["$(0,0),(3,0),(0,4)$", "$(0,0),(6,0),(3,4)$", "$(2,1),(5,1),(2,5)$"], ["right (3-4-5)", "isosceles", "right triangle"], [0, 1, 2]));
  return q;
}

// ── 2.3 Equation of a Circle (centre at the origin) ──────────
function g23() {
  const q = [];
  q.push(mc("easy", "The equation of a circle centred at the origin with radius $r$ is:", ["$x^2+y^2=r^2$", "$x^2+y^2=r$", "$x+y=r$", "$x^2-y^2=r^2$"], 0));
  q.push(mc("easy", "Circle with radius $5$ (centre origin):", ["$x^2+y^2=25$", "$x^2+y^2=5$", "$x^2+y^2=10$", "$x+y=5$"], 0));
  q.push(mc("easy", "The radius of $x^2+y^2=49$:", ["$7$", "$49$", "$24.5$", "$14$"], 0));
  q.push(mc("easy", "Circle with radius $3$:", ["$x^2+y^2=9$", "$x^2+y^2=3$", "$x^2+y^2=6$", "$x^2+y^2=27$"], 0));
  q.push(mc("easy", "Is $(3,4)$ on $x^2+y^2=25$?", ["yes", "no", "only if $r=4$", "cannot tell"], 0));
  q.push(mc("easy", "The radius of $x^2+y^2=36$:", ["$6$", "$18$", "$36$", "$9$"], 0));
  q.push(ms("easy", "Which points lie on $x^2+y^2=25$?", ["$(3,4)$", "$(5,0)$", "$(0,-5)$", "$(2,2)$"], [0, 1, 2]));
  q.push(ms("easy", "Which are circles centred at the origin?", ["$x^2+y^2=16$", "$x^2+y^2=1$", "$y=x^2$", "$x^2+y^2=100$"], [0, 1, 3]));
  q.push(ms("easy", "For $x^2+y^2=r^2$, which are true?", ["centre is the origin", "radius is $r$", "passes $(\\pm r,0)$", "centre is $(r,r)$"], [0, 1, 2]));
  q.push(ms("easy", "Which have radius $10$?", ["$x^2+y^2=100$", "passes $(6,8)$", "passes $(10,0)$", "$x^2+y^2=10$"], [0, 1, 2]));
  q.push(tf("easy", "The circle $x^2+y^2=16$ has radius $4$.", true));
  q.push(tf("easy", "$(0,0)$ is the centre of $x^2+y^2=9$.", true));
  q.push(tf("easy", "The radius of $x^2+y^2=20$ is $20$.", false, "It is $\\sqrt{20}$."));
  q.push(fill("easy", "Circle centre origin, radius $6$: $x^2+y^2=$ ___.", ["36"]));
  q.push(fill("easy", "The radius of $x^2+y^2=81$ is ___.", ["9"]));
  q.push(fill("easy", "Circle through $(0,7)$, centre origin: $x^2+y^2=$ ___.", ["49"]));
  q.push(num("easy", "The radius of $x^2+y^2=144$ = ___.", 12, 0));
  q.push(num("easy", "For a circle through $(3,4)$ (centre origin), $r^2=$ ___.", 25, 0));
  q.push(num("easy", "For a circle through $(6,8)$ (centre origin), the radius = ___.", 10, 0));
  q.push(match("easy", "Match each radius to its equation.", ["$r=5$", "$r=6$", "$r=10$"], ["$x^2+y^2=25$", "$x^2+y^2=36$", "$x^2+y^2=100$"], [0, 1, 2]));
  q.push(mc("medium", "Circle through $(-6,8)$, centre origin:", ["$x^2+y^2=100$", "$x^2+y^2=10$", "$x^2+y^2=14$", "$x^2+y^2=48$"], 0));
  q.push(mc("medium", "Is $(2,3)$ inside, on, or outside $x^2+y^2=16$?", ["inside", "on", "outside", "cannot tell"], 0));
  q.push(mc("medium", "Is $(3,4)$ inside, on, or outside $x^2+y^2=20$?", ["outside", "on", "inside", "none"], 0));
  q.push(mc("medium", "The radius of $x^2+y^2=50$ (exact):", ["$5\\sqrt{2}$", "$25$", "$\\sqrt{50}$ unsimplified", "$50$"], 0));
  q.push(mc("medium", "On $x^2+y^2=100$, the $y$-values where $x=6$:", ["$\\pm8$", "$8$", "$\\pm6$", "$\\pm10$"], 0));
  q.push(mc("medium", "Circle with diameter endpoints $(0,-5),(0,5)$:", ["$x^2+y^2=25$", "$x^2+y^2=5$", "$x^2+y^2=10$", "$x^2+y^2=100$"], 0));
  q.push(ms("medium", "Which points lie on $x^2+y^2=100$?", ["$(6,8)$", "$(0,10)$", "$(-8,6)$", "$(5,5)$"], [0, 1, 2]));
  q.push(ms("medium", "Which points are inside $x^2+y^2=25$?", ["$(1,2)$", "$(3,3)$", "$(0,0)$", "$(4,4)$"], [0, 1, 2]));
  q.push(ms("medium", "For $x^2+y^2=49$:", ["radius $7$", "passes $(7,0)$", "passes $(0,-7)$", "centre $(7,0)$"], [0, 1, 2]));
  q.push(ms("medium", "Which equal radius $\\sqrt{20}$?", ["$2\\sqrt{5}$", "from $x^2+y^2=20$", "$\\approx4.47$", "$20$"], [0, 1, 2]));
  q.push(tf("medium", "A point with $x^2+y^2<r^2$ is inside the circle.", true));
  q.push(tf("medium", "$(5,12)$ lies on $x^2+y^2=169$.", true));
  q.push(tf("medium", "The radius of $x^2+y^2=50$ is $25$.", false));
  q.push(fill("medium", "Circle through $(8,6)$, centre origin: $x^2+y^2=$ ___.", ["100"]));
  q.push(fill("medium", "On $x^2+y^2=25$, if $x=3$ then $y=$ ___.", ["±4", "4 or -4", "\\pm4"]));
  q.push(fill("medium", "The radius of $x^2+y^2=2$ (exact) is ___.", ["√2", "\\sqrt{2}", "sqrt2"]));
  q.push(num("medium", "For a circle through $(-7,0)$, $r^2=$ ___.", 49, 0));
  q.push(num("medium", "On $x^2+y^2=169$, if $x=5$ then the positive $y=$ ___.", 12, 0));
  q.push(num("medium", "The radius of $x^2+y^2=64$ = ___.", 8, 0));
  q.push(match("medium", "Match each point to its position relative to $x^2+y^2=25$.", ["$(1,2)$", "$(3,4)$", "$(5,1)$"], ["inside", "on", "outside"], [0, 1, 2]));
  q.push(mc("hard", "Circle through $(5,12)$, centre origin:", ["$x^2+y^2=169$", "$x^2+y^2=17$", "$x^2+y^2=119$", "$x^2+y^2=13$"], 0));
  q.push(mc("hard", "Does $(-13,0)$ lie on $x^2+y^2=169$?", ["yes", "no", "only if $r=13$ changes", "it is inside"], 0));
  q.push(mc("hard", "Circle through the midpoint of $(6,0),(0,8)$, centre origin:", ["$x^2+y^2=25$", "$x^2+y^2=100$", "$x^2+y^2=50$", "$x^2+y^2=5$"], 0));
  q.push(mc("hard", "Where does $x^2+y^2=25$ cross the $x$-axis?", ["$(\\pm5,0)$", "$(0,\\pm5)$", "$(5,5)$", "$(\\pm25,0)$"], 0));
  q.push(mc("hard", "A circle (centre origin) passes through $(9,40)$. Its radius is:", ["$41$", "$49$", "$\\sqrt{49}$", "$1681$"], 0));
  q.push(ms("hard", "For $x^2+y^2=169$, which points lie on it?", ["$(13,0)$", "$(0,-13)$", "$(12,5)$", "$(5,5)$"], [0, 1, 2]));
  q.push(ms("hard", "For $x^2+y^2=r^2$, which are true?", ["$r=\\sqrt{r^2}$", "symmetric about both axes", "centre at the origin", "it opens upward"], [0, 1, 2]));
  q.push(ms("hard", "Which points are outside $x^2+y^2=100$?", ["$(8,8)$", "$(9,5)$", "$(6,8)$", "$(0,11)$"], [0, 1, 3]));
  q.push(ms("hard", "Which describe the same circle as $x^2+y^2=36$?", ["radius $6$", "passes $(6,0)$", "$x^2+y^2-36=0$", "radius $36$"], [0, 1, 2]));
  q.push(tf("hard", "Since $9^2+40^2=41^2$, the point $(9,40)$ lies on $x^2+y^2=1681$.", true));
  q.push(tf("hard", "The graph of $x^2+y^2=0$ is a single point.", true));
  q.push(tf("hard", "Every circle centred at the origin passes through the origin.", false));
  q.push(fill("hard", "Circle through $(9,40)$, centre origin: $x^2+y^2=$ ___.", ["1681"]));
  q.push(fill("hard", "On $x^2+y^2=100$, if $x=6$ the two $y$-values are ___.", ["±8", "8 and -8", "\\pm8"]));
  q.push(fill("hard", "The radius of a circle through $(20,21)$, centre origin, is ___.", ["29"]));
  q.push(num("hard", "The radius of a circle through $(5,12)$, centre origin, = ___.", 13, 0));
  q.push(num("hard", "For $x^2+y^2=169$, if $y=12$ the positive $x=$ ___.", 5, 0));
  q.push(num("hard", "$r^2$ for a circle through $(9,40)$ = ___.", 1681, 0));
  q.push(order("hard", "Order the steps to write a circle (centre origin) through a point.", ["Take the point's coordinates", "Compute $x^2+y^2$ to get $r^2$", "Write $x^2+y^2=r^2$", "State $r=\\sqrt{r^2}$"]));
  q.push(match("hard", "Match each point on a circle to the circle's radius.", ["$(3,4)$", "$(6,8)$", "$(5,12)$"], ["$5$", "$10$", "$13$"], [0, 1, 2]));
  return q;
}

// ── 2.4 Medians, Right Bisectors & Altitudes ─────────────────
function g24() {
  const q = [];
  q.push(mc("easy", "A median goes from a vertex to:", ["the midpoint of the opposite side", "the opposite vertex", "the centroid only", "a right angle"], 0));
  q.push(mc("easy", "A right bisector passes through a side's midpoint at:", ["$90^\\circ$", "$45^\\circ$", "$0^\\circ$", "the vertex"], 0));
  q.push(mc("easy", "An altitude is:", ["a perpendicular from a vertex to the opposite side", "a median", "a midpoint", "the longest side"], 0));
  q.push(mc("easy", "The median from $A$ to side $BC$ first needs:", ["the midpoint of $BC$", "the slope of $A$", "the length of $AB$", "the centroid"], 0));
  q.push(mc("easy", "The right bisector of a horizontal segment is:", ["vertical", "horizontal", "slanted", "the segment itself"], 0));
  q.push(mc("easy", "The slope perpendicular to a line of slope $2$ is:", ["$-1/2$", "$2$", "$1/2$", "$-2$"], 0));
  q.push(ms("easy", "Which require the midpoint of a side?", ["median", "right bisector", "altitude", "none"], [0, 1]));
  q.push(ms("easy", "Which require a perpendicular (negative-reciprocal) slope?", ["right bisector", "altitude", "median", "midpoint"], [0, 1]));
  q.push(ms("easy", "The midpoint of $(2,4),(6,8)$ is:", ["$(4,6)$", "the average of the coordinates", "$\\left(\\frac{2+6}{2},\\frac{4+8}{2}\\right)$", "$(8,12)$"], [0, 1, 2]));
  q.push(ms("easy", "For a horizontal side, the altitude or right bisector is:", ["vertical", "$x=$ a constant", "perpendicular to the side", "horizontal"], [0, 1, 2]));
  q.push(tf("easy", "A median connects a vertex to the midpoint of the opposite side.", true));
  q.push(tf("easy", "A right bisector is perpendicular to the side it bisects.", true));
  q.push(tf("easy", "An altitude is always horizontal.", false));
  q.push(fill("easy", "The midpoint of $(4,2),(2,6)$ is ___.", ["(3,4)", "3,4"]));
  q.push(fill("easy", "The slope perpendicular to slope $3$ is ___.", ["-1/3", "-0.333"]));
  q.push(fill("easy", "The right bisector of a vertical segment is ___ (horizontal/vertical).", ["horizontal"]));
  q.push(num("easy", "The slope of $BC$ with $B(0,0),C(4,2)$ (decimal) is ___.", 0.5, 0));
  q.push(num("easy", "The midpoint of $(0,0),(6,0)$ has $x$-coordinate ___.", 3, 0));
  q.push(num("easy", "The slope perpendicular to slope $1/4$ is ___.", -4, 0));
  q.push(match("easy", "Match each line to its definition.", ["median", "right bisector", "altitude"], ["vertex to opposite midpoint", "perpendicular through a side's midpoint", "perpendicular from a vertex to the opposite side"], [0, 1, 2]));
  q.push(mc("medium", "Median from $A(0,0)$, $B(4,2),C(2,6)$ (midpoint $BC=(3,4)$):", ["$y=4x/3$", "$y=3x/4$", "$y=x$", "$y=4x$"], 0));
  q.push(mc("medium", "Right bisector of $A(1,2),B(5,6)$:", ["$y=-x+7$", "$y=x+1$", "$y=-x-7$", "$y=x-7$"], 0));
  q.push(mc("medium", "Altitude from $A(0,5)$ to $BC$ ($B(-2,1),C(4,1)$):", ["$x=0$", "$y=0$", "$y=5$", "$x=5$"], 0));
  q.push(mc("medium", "Altitude from $A(1,6)$ to $BC$ ($B(0,0),C(4,2)$):", ["$y=-2x+8$", "$y=2x+4$", "$y=-2x-8$", "$y=x/2$"], 0));
  q.push(mc("medium", "Right bisector of $A(-2,1),B(4,3)$:", ["$y=-3x+5$", "$y=3x-1$", "$y=-3x-5$", "$y=x/3$"], 0));
  q.push(mc("medium", "Median from $A(2,1)$, $B(6,3),C(0,5)$:", ["$y=3x-5$", "$y=3x+5$", "$y=x-5$", "$y=-3x+5$"], 0));
  q.push(ms("medium", "To find a median you need:", ["the vertex", "the opposite side's midpoint", "the line through them", "a perpendicular slope"], [0, 1, 2]));
  q.push(ms("medium", "To find an altitude you need:", ["the opposite side's slope", "its negative reciprocal", "the vertex", "the midpoint of that side"], [0, 1, 2]));
  q.push(ms("medium", "For the horizontal segment $(0,2),(6,2)$, the right bisector is:", ["$x=3$", "a vertical line", "through $(3,2)$", "$y=3$"], [0, 1, 2]));
  q.push(ms("medium", "For the altitude from $A$ to a horizontal side $BC$:", ["it is vertical", "$x=A_x$", "perpendicular to $BC$", "slope $0$"], [0, 1, 2]));
  q.push(tf("medium", "The median's equation passes through the vertex and the opposite midpoint.", true));
  q.push(tf("medium", "An altitude uses the negative reciprocal of the opposite side's slope.", true));
  q.push(tf("medium", "The right bisector passes through a vertex.", false));
  q.push(fill("medium", "The midpoint of $BC$ with $B(6,3),C(0,5)$ is ___.", ["(3,4)", "3,4"]));
  q.push(fill("medium", "The right bisector of the segment $(2,-1)$ to $(2,5)$ is $y=$ ___.", ["2"]));
  q.push(fill("medium", "The altitude from $A(0,5)$ to horizontal $BC$ ($y=1$) is $x=$ ___.", ["0"]));
  q.push(num("medium", "The midpoint of $BC$ with $B(8,2),C(2,2)$ has $x$-coordinate ___.", 5, 0));
  q.push(num("medium", "The slope of $BC$ with $B(0,0),C(2,4)$ (decimal) is ___.", 2, 0));
  q.push(num("medium", "The slope perpendicular to $BC$ ($B(0,0),C(2,4)$) is ___ (decimal).", -0.5, 0));
  q.push(match("medium", "Match each cevian to what you compute first.", ["median from $A$", "altitude from $A$", "right bisector of $AB$"], ["the opposite side's midpoint", "the opposite side's slope", "the midpoint of $AB$"], [0, 1, 2]));
  q.push(mc("hard", "Right bisector of $A(2,3),B(8,7)$: its $y$-intercept is:", ["$12.5$", "$5$", "$-3/2$", "$7$"], 0));
  q.push(mc("hard", "Altitude from $A(0,0)$ to $BC$ ($B(2,4),C(6,0)$):", ["$y=x$", "$y=-x$", "$y=x+1$", "$y=-x+6$"], 0));
  q.push(mc("hard", "Length of the median from $C(1,6)$ in $A(-2,0),B(4,0),C(1,6)$:", ["$6$", "$3$", "$\\sqrt{37}$", "$12$"], 0));
  q.push(mc("hard", "Right bisector of $A(0,0),B(6,4)$:", ["$y=-2x/3+4$", "$y=2x/3-4$", "$y=-3x/2+2$", "$y=2x/3$"], 0));
  q.push(mc("hard", "For $\\triangle PQR$, $P(-2,2),Q(4,2),R(1,7)$, the median from $R$ is:", ["$x=1$", "$y=1$", "$x=7$", "$y=7$"], 0));
  q.push(ms("hard", "For $P(-2,2),Q(4,2),R(1,7)$, which are true?", ["midpoint $PQ=(1,2)$", "median from $R$ is $x=1$", "$PQ$ is horizontal", "altitude from $R$ is $x=1$"], [0, 1, 2, 3]));
  q.push(ms("hard", "To find a right bisector you need:", ["the segment's midpoint", "the segment's slope", "the negative-reciprocal slope", "point-slope form"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which lines can be vertical ($x=$ const)?", ["altitude to a horizontal side", "right bisector of a horizontal segment", "median to any side", "altitude to a vertical side"], [0, 1]));
  q.push(ms("hard", "Which require a perpendicular-slope step?", ["right bisector", "altitude", "median", "centroid"], [0, 1]));
  q.push(tf("hard", "In an isosceles triangle the median and altitude from the apex can coincide.", true));
  q.push(tf("hard", "A right bisector need not pass through any vertex.", true));
  q.push(tf("hard", "The altitude from a vertex always passes through the opposite midpoint.", false));
  q.push(fill("hard", "The right bisector of $A(2,3),B(8,7)$ has $y$-intercept ___.", ["12.5", "25/2"]));
  q.push(fill("hard", "The median from $A(0,0)$ to midpoint $(3,4)$ is $y=$ ___.", ["4x/3", "(4/3)x", "4/3x"]));
  q.push(fill("hard", "The altitude from $A(0,0)$ to $BC$ (slope $-1$) is $y=$ ___.", ["x"]));
  q.push(num("hard", "Length of the median from $C(1,6)$ to midpoint of $AB$ ($A(-2,0),B(4,0)$) = ___.", 6, 0));
  q.push(num("hard", "The right bisector of $A(0,0),B(6,4)$ passes through the midpoint; its $x$-coordinate is ___.", 3, 0));
  q.push(num("hard", "The slope of the altitude to a side of slope $1/2$ is ___ (decimal).", -2, 0));
  q.push(order("hard", "Order the steps to find a right bisector of $AB$.", ["Find the midpoint of $AB$", "Find the slope of $AB$", "Take the negative reciprocal", "Use point-slope through the midpoint"]));
  q.push(match("hard", "For $A(0,0),B(4,2),C(2,6)$, match each item to its value.", ["median from $A$", "midpoint of $BC$", "slope of $BC$"], ["$y=4x/3$", "$(3,4)$", "$-2$"], [0, 1, 2]));
  return q;
}

// ── 2.5 Verifying Geometric Properties ───────────────────────
function g25() {
  const q = [];
  q.push(mc("easy", "Parallel sides have:", ["equal slopes", "opposite slopes", "negative-reciprocal slopes", "zero slopes"], 0));
  q.push(mc("easy", "Perpendicular sides have slopes that multiply to:", ["$-1$", "$1$", "$0$", "$2$"], 0));
  q.push(mc("easy", "To prove a triangle isosceles, show:", ["two sides are equal", "all angles equal", "one right angle", "parallel sides"], 0));
  q.push(mc("easy", "A rectangle is a parallelogram with:", ["a right angle", "only equal diagonals", "no right angles", "curved sides"], 0));
  q.push(mc("easy", "To show two segments are parallel, compare their:", ["slopes", "lengths", "midpoints", "colours"], 0));
  q.push(mc("easy", "A square has:", ["4 equal sides and right angles", "only equal sides", "only right angles", "2 equal sides"], 0));
  q.push(ms("easy", "Which tools verify geometric properties?", ["slope", "length (distance)", "midpoint", "temperature"], [0, 1, 2]));
  q.push(ms("easy", "To prove a parallelogram, show:", ["both pairs of opposite sides parallel", "diagonals bisect each other", "all four sides equal", "only one pair parallel"], [0, 1]));
  q.push(ms("easy", "Equal slopes mean lines are:", ["parallel", "or the same line", "not perpendicular (unless $0$/undefined)", "always perpendicular"], [0, 1, 2]));
  q.push(ms("easy", "A right angle can be shown by:", ["slopes multiplying to $-1$", "one horizontal and one vertical side", "perpendicular sides", "equal sides"], [0, 1, 2]));
  q.push(tf("easy", "Parallel lines have equal slopes.", true));
  q.push(tf("easy", "A rhombus has four equal sides.", true));
  q.push(tf("easy", "Equal diagonals alone prove a square.", false));
  q.push(fill("easy", "Slopes $2$ and $-1/2$ mean the lines are ___ (parallel/perpendicular).", ["perpendicular"]));
  q.push(fill("easy", "If two sides both have slope $3$, they are ___.", ["parallel"]));
  q.push(fill("easy", "A triangle with two equal sides is ___.", ["isosceles"]));
  q.push(num("easy", "The slope of the side from $(0,0)$ to $(4,2)$ (decimal) = ___.", 0.5, 0));
  q.push(num("easy", "The length of the side from $(0,0)$ to $(3,4)$ = ___.", 5, 0));
  q.push(num("easy", "The product of two perpendicular slopes = ___.", -1, 0));
  q.push(match("easy", "Match each property to its test.", ["parallel", "perpendicular", "isosceles"], ["equal slopes", "slopes multiply to $-1$", "two equal sides"], [0, 1, 2]));
  q.push(mc("medium", "Triangle $A(1,1),B(4,1),C(4,5)$ has a right angle at:", ["$B$", "$A$", "$C$", "none"], 0));
  q.push(mc("medium", "Triangle $(0,0),(6,0),(3,4)$ is:", ["isosceles", "scalene", "equilateral", "right"], 0));
  q.push(mc("medium", "Quadrilateral $(0,0),(4,0),(5,3),(1,3)$ is a:", ["parallelogram", "square", "trapezoid only", "kite"], 0));
  q.push(mc("medium", "To show diagonals bisect each other, show their ___ are equal:", ["midpoints", "lengths", "slopes", "endpoints"], 0));
  q.push(mc("medium", "A triangle with sides $3,4,5$ is:", ["right scalene", "isosceles", "equilateral", "obtuse"], 0));
  q.push(mc("medium", "If $AB\\parallel DC$ and $AD\\parallel BC$, the shape is a:", ["parallelogram", "trapezoid", "kite", "triangle"], 0));
  q.push(ms("medium", "For $(0,0),(4,0),(5,3),(1,3)$, which are true?", ["$AB\\parallel DC$ (slope $0$)", "$AD\\parallel BC$ (slope $3$)", "it is a parallelogram", "all sides equal"], [0, 1, 2]));
  q.push(ms("medium", "Which prove a right angle?", ["slopes $2$ and $-1/2$", "horizontal and vertical sides", "product of slopes $=-1$", "equal lengths"], [0, 1, 2]));
  q.push(ms("medium", "Which are isosceles triangles?", ["$(0,0),(6,0),(3,4)$", "$(1,1),(5,1),(3,5)$", "$(0,0),(3,0),(0,4)$", "$(2,1),(5,1),(2,5)$"], [0, 1]));
  q.push(ms("medium", "Diagonals bisecting each other prove:", ["a parallelogram", "midpoints coincide", "not necessarily a rectangle", "a triangle"], [0, 1, 2]));
  q.push(tf("medium", "A parallelogram with a right angle is a rectangle.", true));
  q.push(tf("medium", "The slope of a vertical side is undefined.", true));
  q.push(tf("medium", "A scalene triangle has two equal sides.", false));
  q.push(fill("medium", "Slopes $1/2$ and $-2$: the sides are ___.", ["perpendicular"]));
  q.push(fill("medium", "Triangle $(0,0),(6,0),(3,4)$: each of the two equal sides has length ___.", ["5"]));
  q.push(fill("medium", "The midpoint of the diagonal from $(0,0)$ to $(6,4)$ is ___.", ["(3,2)", "3,2"]));
  q.push(num("medium", "The slope of the side $(1,1)$ to $(4,7)$ (decimal) = ___.", 2, 0));
  q.push(num("medium", "The length of the side $(0,0)$ to $(5,12)$ = ___.", 13, 0));
  q.push(num("medium", "The product of slopes $3$ and $-1/3$ = ___.", -1, 0));
  q.push(match("medium", "Match each figure to its classification.", ["$(0,0),(6,0),(3,4)$", "$(2,1),(5,1),(2,5)$", "$(0,0),(4,0),(4,4),(0,4)$"], ["isosceles triangle", "right triangle", "square"], [0, 1, 2]));
  q.push(mc("hard", "$ABCD$ with $A(1,2),B(5,4),C(3,8),D(-1,6)$ is a:", ["rectangle", "square", "rhombus", "trapezoid"], 0));
  q.push(mc("hard", "Triangle $A(0,0),B(2,4),C(6,2)$ has a right angle at:", ["$B$", "$A$", "$C$", "none"], 0));
  q.push(mc("hard", "$(0,0),(4,2),(6,6),(2,4)$ is a:", ["rhombus", "rectangle", "square", "trapezoid"], 0));
  q.push(mc("hard", "Midpoints of the diagonals of $(0,0),(4,1),(6,5),(2,4)$:", ["coincide (parallelogram)", "differ", "are $(3,3)$", "are not equal"], 0));
  q.push(mc("hard", "Triangle $(1,1),(4,1),(1,5)$ is:", ["right", "equilateral", "isosceles only", "obtuse"], 0));
  q.push(ms("hard", "For $A(1,2),B(5,4),C(3,8),D(-1,6)$, which are true?", ["$AB\\parallel DC$ (slope $1/2$)", "$AD\\parallel BC$ (slope $-2$)", "$AB\\perp AD$", "it is a rectangle"], [0, 1, 2, 3]));
  q.push(ms("hard", "To prove a square, you show:", ["all sides equal", "a right angle", "it is a parallelogram", "diagonals equal and perpendicular"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which confirm a rhombus?", ["four equal sides", "opposite sides parallel", "not necessarily right angles", "all angles $90^\\circ$"], [0, 1, 2]));
  q.push(ms("hard", "A midsegment of a triangle:", ["is parallel to the third side", "is half its length", "joins two midpoints", "equals the third side"], [0, 1, 2]));
  q.push(tf("hard", "A rectangle's diagonals are equal.", true));
  q.push(tf("hard", "A parallelogram with perpendicular diagonals is a rhombus.", true));
  q.push(tf("hard", "Proving two sides equal proves a square.", false));
  q.push(fill("hard", "For $A(1,2),B(5,4),C(3,8),D(-1,6)$, the slope of $AB$ = ___.", ["1/2", "0.5"]));
  q.push(fill("hard", "The midsegment joining midpoints of $AC,BC$ in $A(0,0),B(8,0),C(2,6)$ has length ___.", ["4"]));
  q.push(fill("hard", "A parallelogram with a $90^\\circ$ angle is a ___.", ["rectangle"]));
  q.push(num("hard", "Perpendicular check: $1/2 \\times$ ___ $=-1$.", -2, 0));
  q.push(num("hard", "Each side of rhombus $(0,0),(4,2),(6,6),(2,4)$ has length $\\sqrt{\\,?\\,}$ — enter the number under the root.", 20, 0));
  q.push(num("hard", "The midsegment length (half of a base of $8$) = ___.", 4, 0));
  q.push(order("hard", "Order the steps to prove a quadrilateral is a parallelogram.", ["Find the slope of each side", "Check opposite sides have equal slopes", "Conclude both pairs are parallel", "State it is a parallelogram"]));
  q.push(match("hard", "Match each quadrilateral to its name.", ["opposite sides parallel", "parallelogram + right angle", "all sides equal + right angle"], ["parallelogram", "rectangle", "square"], [0, 1, 2]));
  return q;
}

// ── 2.6 Problems Involving Lines & Line Segments ─────────────
function g26() {
  const q = [];
  q.push(mc("easy", "The centroid of a triangle is the average of:", ["the three vertices", "two vertices", "the midpoints only", "the longest side"], 0));
  q.push(mc("easy", "A point on the right bisector of $AB$ is:", ["equidistant from $A$ and $B$", "closer to $A$", "on segment $AB$", "the midpoint only"], 0));
  q.push(mc("easy", "Centroid of $(0,0),(6,0),(3,9)$:", ["$(3,3)$", "$(9,9)$", "$(3,9)$", "$(2,3)$"], 0));
  q.push(mc("easy", "The line through $(1,2)$ parallel to $y=3x$ has slope:", ["$3$", "$-3$", "$1/3$", "$-1/3$"], 0));
  q.push(mc("easy", "To find where two lines meet, you:", ["solve them as a system", "add their slopes", "average them", "find midpoints"], 0));
  q.push(mc("easy", "The centroid divides each median in the ratio:", ["$2:1$", "$1:1$", "$3:1$", "$1:2$"], 0));
  q.push(ms("easy", "Which can coordinate geometry find?", ["a centroid", "the intersection of two lines", "the length of a median", "the weather"], [0, 1, 2]));
  q.push(ms("easy", "The line through $(0,4)$ perpendicular to $y=x/2$ has:", ["slope $-2$", "$y$-intercept $4$", "equation $y=-2x+4$", "slope $1/2$"], [0, 1, 2]));
  q.push(ms("easy", "A point equidistant from $A$ and $B$ lies on:", ["the right bisector of $AB$", "the perpendicular bisector", "a line $\\perp AB$ through its midpoint", "segment $AB$"], [0, 1, 2]));
  q.push(ms("easy", "The centroid formula uses:", ["sum of $x$'s over $3$", "sum of $y$'s over $3$", "all three vertices", "only one vertex"], [0, 1, 2]));
  q.push(tf("easy", "The centroid is the average of the three vertices.", true));
  q.push(tf("easy", "Parallel lines in a problem share a slope.", true));
  q.push(tf("easy", "The intersection of two lines is found by averaging them.", false));
  q.push(fill("easy", "Centroid of $(0,0),(9,0),(3,6)$ is ___.", ["(4,2)", "4,2"]));
  q.push(fill("easy", "The line through $(2,-1)$ parallel to $y=3x+4$ is $y=$ ___.", ["3x-7", "3x - 7"]));
  q.push(fill("easy", "The intersection of $y=2x-1$ and $y=-x+5$ is ___.", ["(2,3)", "2,3"]));
  q.push(num("easy", "Centroid of $(0,0),(6,0),(3,9)$: its $x$-coordinate is ___.", 3, 0));
  q.push(num("easy", "The $x$-coordinate where $y=2x-1$ meets $y=-x+5$ is ___.", 2, 0));
  q.push(num("easy", "The slope of a line parallel to $y=4x-2$ is ___.", 4, 0));
  q.push(match("easy", "Match each task to its tool.", ["intersection of two lines", "equidistant point", "centre of a triangle"], ["solve a system", "right bisector", "centroid"], [0, 1, 2]));
  q.push(mc("medium", "Line through $(1,2)$ parallel to $2x+y=5$:", ["$y=-2x+4$", "$y=2x$", "$y=-2x-4$", "$y=x/2$"], 0));
  q.push(mc("medium", "Line through $(0,4)$ perpendicular to $y=x/2-2$:", ["$y=-2x+4$", "$y=2x+4$", "$y=x/2+4$", "$y=-x/2$"], 0));
  q.push(mc("medium", "Perpendicular bisector of $A(2,3),B(8,7)$ has $y$-intercept:", ["$12.5$", "$5$", "$-3/2$", "$7$"], 0));
  q.push(mc("medium", "Point on the $x$-axis equidistant from $(1,2),(5,4)$:", ["$(4.5,0)$", "$(3,0)$", "$(4,0)$", "$(2,0)$"], 0));
  q.push(mc("medium", "Where do $y=2x-1$ and $y=-x+5$ meet?", ["$(2,3)$", "$(3,2)$", "$(1,1)$", "$(2,2)$"], 0));
  q.push(mc("medium", "Centroid of $(0,0),(6,0),(0,8)$:", ["$(2,8/3)$", "$(3,4)$", "$(2,3)$", "$(0,0)$"], 0));
  q.push(ms("medium", "For the centroid of $(0,0),(6,0),(0,8)$:", ["$x=2$", "$y=8/3$", "it averages the vertices", "it is $(3,4)$"], [0, 1, 2]));
  q.push(ms("medium", "The right bisector of $AB$:", ["passes through the midpoint of $AB$", "is perpendicular to $AB$", "is equidistant from $A,B$", "passes through vertex $A$"], [0, 1, 2]));
  q.push(ms("medium", "Line through $(1,2)$ parallel to $2x+y=5$:", ["has slope $-2$", "is $y=-2x+4$", "passes through $(1,2)$", "has slope $2$"], [0, 1, 2]));
  q.push(ms("medium", "To find a point on an axis equidistant from two points:", ["set the distances equal", "use $(x,0)$ for the $x$-axis", "solve for $x$", "use only the midpoint"], [0, 1, 2]));
  q.push(tf("medium", "A line parallel to $2x+y=5$ has slope $-2$.", true));
  q.push(tf("medium", "The perpendicular bisector is equidistant from the segment's endpoints.", true));
  q.push(tf("medium", "The centroid is always a vertex of the triangle.", false));
  q.push(fill("medium", "Centroid of $(0,0),(9,0),(3,6)$ is ___.", ["(4,2)", "4,2"]));
  q.push(fill("medium", "Line through $(0,4)$ perpendicular to $y=x/2$ is $y=$ ___.", ["-2x+4", "-2x + 4"]));
  q.push(fill("medium", "$y=2x-1$ meets $y=-x+5$ at ___.", ["(2,3)", "2,3"]));
  q.push(num("medium", "Point on the $x$-axis equidistant from $(0,3),(6,1)$: its $x$-coordinate (2 dp) ___.", 2.33, 0.02));
  q.push(num("medium", "Length of the median from $C(4,6)$ to midpoint of $AB$ ($A(0,0),B(8,0)$) = ___.", 6, 0));
  q.push(num("medium", "Centroid of $(0,0),(6,0),(3,9)$: its $y$-coordinate = ___.", 3, 0));
  q.push(match("medium", "Match each problem to its first step.", ["line parallel to a given line", "equidistant point on an axis", "centroid"], ["copy the slope", "set distances equal", "average the vertices"], [0, 1, 2]));
  q.push(mc("hard", "Line perpendicular to $3x+y=6$ through its $y$-intercept $(0,6)$:", ["$y=x/3+6$", "$y=-3x+6$", "$y=3x+6$", "$y=-x/3+6$"], 0));
  q.push(mc("hard", "Point on the $x$-axis equidistant from $(1,2),(5,4)$:", ["$(4.5,0)$", "$(3,0)$", "$(4,0)$", "$(2,0)$"], 0));
  q.push(mc("hard", "Centroid of $(-3,0),(3,0),(0,9)$:", ["$(0,3)$", "$(0,9)$", "$(0,0)$", "$(3,3)$"], 0));
  q.push(mc("hard", "Median from $C(0,8)$ to midpoint of $AB$ ($A(0,0),B(6,0)$):", ["$y=-8x/3+8$", "$y=8x/3+8$", "$y=-3x/8+8$", "$y=-8x/3$"], 0));
  q.push(mc("hard", "Is $(3,2)$ on the right bisector of $A(1,0),B(5,4)$?", ["yes, it is equidistant", "no", "only to $A$", "only to $B$"], 0));
  q.push(ms("hard", "For triangle $(0,0),(6,0),(0,8)$:", ["perimeter $24$", "$BC=10$", "centroid $(2,8/3)$", "right angle at the origin"], [0, 1, 2, 3]));
  q.push(ms("hard", "The perpendicular bisector of $A,B$ consists of points:", ["equidistant from $A$ and $B$", "on a line $\\perp AB$", "through the midpoint of $AB$", "equal to $A$"], [0, 1, 2]));
  q.push(ms("hard", "To find the circumcentre you could intersect:", ["two right bisectors", "the right bisectors of two sides", "perpendicular bisectors", "two medians"], [0, 1, 2]));
  q.push(ms("hard", "Which are true of the centroid?", ["the average of the 3 vertices", "the intersection of the medians", "divides medians $2:1$", "a midpoint of a side"], [0, 1, 2]));
  q.push(tf("hard", "The circumcentre is equidistant from all three vertices.", true));
  q.push(tf("hard", "The intersection of the medians is the centroid.", true));
  q.push(tf("hard", "The centroid is equidistant from all three vertices.", false));
  q.push(fill("hard", "Line through $(0,6)$ perpendicular to $3x+y=6$ is $y=$ ___.", ["x/3+6", "(1/3)x+6"]));
  q.push(fill("hard", "Centroid of $(-3,0),(3,0),(0,9)$ is ___.", ["(0,3)", "0,3"]));
  q.push(fill("hard", "Point on the $y$-axis equidistant from $(3,0),(-1,4)$ is $(0,y)$; $y=$ ___.", ["1"]));
  q.push(num("hard", "Perimeter of triangle $(0,0),(6,0),(0,8)$ = ___.", 24, 0));
  q.push(num("hard", "Point on the $x$-axis equidistant from $(0,3),(6,1)$: $x$ (2 dp) = ___.", 2.33, 0.02));
  q.push(num("hard", "Centroid of $(-3,0),(3,0),(0,9)$: its $y$-coordinate = ___.", 3, 0));
  q.push(order("hard", "Order the steps to find a point on the $x$-axis equidistant from $A$ and $B$.", ["Let the point be $(x,0)$", "Set distance to $A$ equal to distance to $B$", "Square both sides and simplify", "Solve for $x$"]));
  q.push(match("hard", "Match each centre to its definition.", ["centroid", "circumcentre", "intersection of two lines"], ["average of the vertices", "equidistant from the vertices", "solve a system"], [0, 1, 2]));
  return q;
}

export default [
  { code: "2.1", gen: g21 },
  { code: "2.2", gen: g22 },
  { code: "2.3", gen: g23 },
  { code: "2.4", gen: g24 },
  { code: "2.5", gen: g25 },
  { code: "2.6", gen: g26 },
];
