// MPM2D Unit 4 — Quadratic Relations: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "./helpers.mjs";

// ── 4.1 Introducing Quadratic Relations ──────────────────────
function g41() {
  const q = [];
  q.push(mc("easy", "A quadratic relation has degree:", ["$2$", "$1$", "$3$", "$0$"], 0));
  q.push(mc("easy", "The graph of a quadratic is a:", ["parabola", "line", "circle", "point"], 0));
  q.push(mc("easy", "Which is quadratic?", ["$y=x^2-3$", "$y=2x+1$", "$y=5$", "$y=1/x$"], 0));
  q.push(mc("easy", "The base parabola is:", ["$y=x^2$", "$y=x$", "$y=2x$", "$y=x^3$"], 0));
  q.push(mc("easy", "If $f(x)=x^2$, then $f(3)=$", ["$9$", "$6$", "$3$", "$27$"], 0));
  q.push(mc("easy", "For a quadratic, the ___ differences are constant:", ["second", "first", "third", "zero"], 0));
  q.push(ms("easy", "Which are quadratic?", ["$y=x^2-7$", "$y=-3x^2$", "$y=4x+1$", "$y=x^3$"], [0, 1]));
  q.push(ms("easy", "Which are true of $y=x^2$?", ["vertex $(0,0)$", "opens up", "it is a parabola", "it is a straight line"], [0, 1, 2]));
  q.push(ms("easy", "For a quadratic relation:", ["degree $2$", "second differences constant", "graph is a parabola", "first differences constant"], [0, 1, 2]));
  q.push(ms("easy", "Which open downward?", ["$y=-x^2$", "$y=-2x^2+1$", "$y=x^2$", "$y=3x^2$"], [0, 1]));
  q.push(tf("easy", "The graph of a quadratic relation is a parabola.", true));
  q.push(tf("easy", "$y=2x+5$ is a quadratic relation.", false));
  q.push(tf("easy", "For $y=x^2$, the second differences are constant.", true));
  q.push(fill("easy", "The graph of $y=x^2$ is called a ___.", ["parabola"]));
  q.push(fill("easy", "If $f(x)=x^2-1$, then $f(2)=$ ___.", ["3"]));
  q.push(fill("easy", "The base quadratic is $y=$ ___.", ["x^2", "x²"]));
  q.push(num("easy", "If $f(x)=x^2-2x-3$, find $f(4)$.", 5, 0));
  q.push(num("easy", "If $f(x)=2x^2$, find $f(3)$.", 18, 0));
  q.push(num("easy", "A relation $y=ax^2$ has constant second difference $6$; find $a$.", 3, 0));
  q.push(match("easy", "Match each relation to its type.", ["$y=x^2+1$", "$y=2x-3$", "$y=-x^2$"], ["quadratic (opens up)", "linear", "quadratic (opens down)"], [0, 1, 2]));
  q.push(mc("medium", "By second differences, $x:0,1,2,3$, $y:1,3,7,13$ is:", ["quadratic", "linear", "cubic", "none"], 0));
  q.push(mc("medium", "The constant second difference of $y=ax^2$ equals:", ["$2a$", "$a$", "$a^2$", "$4a$"], 0));
  q.push(mc("medium", "If $f(x)=2x^2-x+1$, then $f(-2)=$", ["$11$", "$7$", "$9$", "$5$"], 0));
  q.push(mc("medium", "A ball: $h=-5t^2+20t$; at $t=1$, $h=$", ["$15$", "$20$", "$25$", "$5$"], 0));
  q.push(mc("medium", "$y=3x^2$ compared to $y=x^2$ is:", ["narrower", "wider", "the same", "shifted up"], 0));
  q.push(mc("medium", "$y=-x^2+4$ opens:", ["down", "up", "left", "right"], 0));
  q.push(ms("medium", "Which are quadratic relations?", ["$y=x^2-7$", "$y=4x+1$", "$y=-3x^2$", "$y=x^3+2$"], [0, 2]));
  q.push(ms("medium", "For $y=x^2$, which points are on it?", ["$(1,1)$", "$(2,4)$", "$(-3,9)$", "$(2,5)$"], [0, 1, 2]));
  q.push(ms("medium", "The relation $y=-2x^2$:", ["opens down", "is quadratic", "is narrower than $y=-x^2$", "is linear"], [0, 1, 2]));
  q.push(ms("medium", "Second differences:", ["constant for quadratics", "equal $2a$ for $y=ax^2$", "zero for linear", "constant for cubics"], [0, 1, 2]));
  q.push(tf("medium", "A larger $|a|$ makes a parabola narrower.", true));
  q.push(tf("medium", "The second differences of a linear relation are $0$.", true));
  q.push(tf("medium", "$y=-x^2$ opens upward.", false));
  q.push(fill("medium", "The constant second difference of $y=ax^2$ is ___ (in terms of $a$).", ["2a"]));
  q.push(fill("medium", "For $h=-5t^2+20t$, $h(2)=$ ___.", ["20"]));
  q.push(fill("medium", "$y=5x^2$ is ___ than $y=x^2$ (narrower/wider).", ["narrower"]));
  q.push(num("medium", "A relation $y=ax^2$ has second difference $8$; find $a$.", 4, 0));
  q.push(num("medium", "If $f(x)=-2x^2+4x$, find $f(-1)$.", -6, 0));
  q.push(num("medium", "For $h=-5t^2+30t$, find $h(2)$.", 40, 0));
  q.push(match("medium", "Match each relation to how it compares to $y=x^2$.", ["$y=2x^2$", "$y=\\tfrac{1}{2}x^2$", "$y=-x^2$"], ["narrower", "wider", "opens down"], [0, 1, 2]));
  q.push(mc("hard", "A relation $y=ax^2$ has second difference $10$; then $y(4)=$", ["$80$", "$40$", "$100$", "$20$"], 0));
  q.push(mc("hard", "If $f(x)=x^2-4x+1$, then $f(5)=$", ["$6$", "$1$", "$11$", "$21$"], 0));
  q.push(mc("hard", "The first differences of $y=x^2$ for $x=0,1,2,3$ are:", ["$1,3,5$", "$2,2,2$", "$0,1,4$", "$1,2,3$"], 0));
  q.push(mc("hard", "A ball $h=-5t^2+40t$ reaches the ground ($h=0$) at $t=$", ["$8$", "$4$", "$40$", "$0$"], 0));
  q.push(mc("hard", "The vertex of $y=x^2$ is at:", ["$(0,0)$", "$(1,1)$", "$(0,1)$", "$(1,0)$"], 0));
  q.push(ms("hard", "For $y=ax^2$ with second difference $6$:", ["$a=3$", "$y=3x^2$", "$y(2)=12$", "$a=6$"], [0, 1, 2]));
  q.push(ms("hard", "Which relations are quadratic?", ["$y=x^2$", "$y=(x-1)^2$", "$y=x^2+3x$", "$y=2x+1$"], [0, 1, 2]));
  q.push(ms("hard", "For the height $h=-5t^2+20t$:", ["opens down", "maximum at $t=2$", "$h(0)=0$", "linear"], [0, 1, 2]));
  q.push(ms("hard", "Properties of $y=x^2$:", ["vertex $(0,0)$", "symmetric about $x=0$", "minimum $0$", "opens down"], [0, 1, 2]));
  q.push(tf("hard", "A quadratic relation can be identified by constant second differences.", true));
  q.push(tf("hard", "The vertex of $y=x^2$ is its minimum point.", true));
  q.push(tf("hard", "Every parabola has constant first differences.", false));
  q.push(fill("hard", "If $f(x)=x^2-2x-3$, then $f(4)=$ ___.", ["5"]));
  q.push(fill("hard", "A relation $y=ax^2$ with second difference $10$ has $a=$ ___.", ["5"]));
  q.push(fill("hard", "For $h=-5t^2+40t$, the ball lands at $t=$ ___ s.", ["8"]));
  q.push(num("hard", "If $f(x)=3x^2-2$, find $f(0)$.", -2, 0));
  q.push(num("hard", "A relation $y=ax^2$ has second difference $12$; find $a$.", 6, 0));
  q.push(num("hard", "If $f(x)=x^2+x$, find $f(-3)$.", 6, 0));
  q.push(order("hard", "Order the steps to confirm a table is quadratic.", ["Compute the first differences", "Compute the second differences", "Check they are constant", "Conclude it is quadratic"]));
  q.push(match("hard", "Match each relation to its second difference.", ["$y=x^2$", "$y=2x^2$", "$y=5x^2$"], ["$2$", "$4$", "$10$"], [0, 1, 2]));
  return q;
}

// ── 4.2 Key Features of a Parabola ───────────────────────────
function g42() {
  const q = [];
  q.push(mc("easy", "The turning point of a parabola is the:", ["vertex", "zero", "intercept", "axis"], 0));
  q.push(mc("easy", "The axis of symmetry of $y=(x-2)^2+3$ is:", ["$x=2$", "$x=-2$", "$x=3$", "$y=2$"], 0));
  q.push(mc("easy", "The vertex of $y=(x-1)^2+4$ is:", ["$(1,4)$", "$(-1,4)$", "$(1,-4)$", "$(4,1)$"], 0));
  q.push(mc("easy", "The zeros of $y=x^2-9$ are:", ["$\\pm3$", "$\\pm9$", "$3$", "$0$"], 0));
  q.push(mc("easy", "The $y$-intercept of $y=x^2-2x-3$ is:", ["$-3$", "$3$", "$-2$", "$0$"], 0));
  q.push(mc("easy", "If $a>0$, the vertex is a:", ["minimum", "maximum", "zero", "intercept"], 0));
  q.push(ms("easy", "Features of a parabola include:", ["vertex", "axis of symmetry", "zeros", "slope"], [0, 1, 2]));
  q.push(ms("easy", "For $y=-(x-2)^2+9$:", ["vertex $(2,9)$", "maximum $9$", "opens down", "axis $x=2$"], [0, 1, 2, 3]));
  q.push(ms("easy", "The zeros are where:", ["$y=0$", "the graph meets the $x$-axis", "the $x$-intercepts are", "$x=0$"], [0, 1, 2]));
  q.push(ms("easy", "The $y$-intercept is where:", ["$x=0$", "the graph meets the $y$-axis", "you set $x=0$", "$y=0$"], [0, 1, 2]));
  q.push(tf("easy", "The axis of symmetry passes through the vertex.", true));
  q.push(tf("easy", "A parabola with $a<0$ has a maximum.", true));
  q.push(tf("easy", "The $y$-intercept is found by setting $y=0$.", false));
  q.push(fill("easy", "The vertex of $y=(x-3)^2-4$ is ___.", ["(3,-4)", "3,-4"]));
  q.push(fill("easy", "The zeros of $y=x^2-16$ are ___.", ["±4", "4 and -4", "\\pm4"]));
  q.push(fill("easy", "The $y$-intercept of $y=2x^2+5x-7$ is ___.", ["-7"]));
  q.push(num("easy", "A parabola has zeros $1$ and $5$; its axis of symmetry is $x=$ ___.", 3, 0));
  q.push(num("easy", "The minimum value of $y=(x-2)^2+5$ is ___.", 5, 0));
  q.push(num("easy", "The $y$-intercept of $y=x^2-2x-3$ is ___.", -3, 0));
  q.push(match("easy", "Match each feature to its meaning.", ["vertex", "axis of symmetry", "zero"], ["the turning point", "line through the vertex", "an $x$-intercept"], [0, 1, 2]));
  q.push(mc("medium", "The vertex of $y=x^2-6x+5$ is:", ["$(3,-4)$", "$(3,4)$", "$(-3,-4)$", "$(6,5)$"], 0));
  q.push(mc("medium", "The maximum of $y=-2(x-1)^2+8$ is:", ["$8$", "$1$", "$-8$", "$2$"], 0));
  q.push(mc("medium", "A parabola with zeros $-2$ and $6$ has axis:", ["$x=2$", "$x=4$", "$x=-4$", "$x=8$"], 0));
  q.push(mc("medium", "The vertex of $y=x^2-8x+12$ is:", ["$(4,-4)$", "$(4,4)$", "$(8,12)$", "$(-4,-4)$"], 0));
  q.push(mc("medium", "The zeros of $y=x^2-2x-8$ are:", ["$4,-2$", "$-4,2$", "$2,8$", "$1,8$"], 0));
  q.push(mc("medium", "The minimum value of $y=3(x-2)^2-4$ is:", ["$-4$", "$2$", "$-2$", "$4$"], 0));
  q.push(ms("medium", "For $y=-(x+1)^2+9$:", ["vertex $(-1,9)$", "opens down", "maximum $9$", "axis $x=-1$"], [0, 1, 2, 3]));
  q.push(ms("medium", "For $y=x^2-4x-5$:", ["vertex $(2,-9)$", "zeros $5,-1$", "$y$-intercept $-5$", "opens up"], [0, 1, 2, 3]));
  q.push(ms("medium", "Which give the axis of symmetry?", ["midpoint of the zeros", "$x=h$ in vertex form", "$x=-b/(2a)$", "the $y$-intercept"], [0, 1, 2]));
  q.push(ms("medium", "A parabola opening up has:", ["a minimum", "range $y\\ge k$", "vertex at the bottom", "a maximum"], [0, 1, 2]));
  q.push(tf("medium", "The axis of symmetry is the midpoint of the two zeros.", true));
  q.push(tf("medium", "$y=-(x-2)^2+9$ has a maximum of $9$.", true));
  q.push(tf("medium", "The vertex of $y=x^2-6x+5$ is $(3,4)$.", false));
  q.push(fill("medium", "The vertex of $y=x^2-8x+12$ is ___.", ["(4,-4)", "4,-4"]));
  q.push(fill("medium", "The zeros of $y=x^2-2x-8$ are ___.", ["4 and -2", "4,-2", "-2,4"]));
  q.push(fill("medium", "A parabola with zeros $-2,6$ has axis $x=$ ___.", ["2"]));
  q.push(num("medium", "The minimum value of $y=3(x-2)^2-4$ is ___.", -4, 0));
  q.push(num("medium", "The axis of symmetry of $y=x^2-6x+5$ is $x=$ ___.", 3, 0));
  q.push(num("medium", "The $y$-coordinate of the vertex of $y=x^2-8x+12$ is ___.", -4, 0));
  q.push(match("medium", "Match each parabola to its vertex.", ["$y=(x-1)^2+2$", "$y=-(x+3)^2+5$", "$y=x^2-6x+5$"], ["$(1,2)$", "$(-3,5)$", "$(3,-4)$"], [0, 1, 2]));
  q.push(mc("hard", "For $y=x^2-4x-5$, the vertex is:", ["$(2,-9)$", "$(2,9)$", "$(-2,-9)$", "$(4,-5)$"], 0));
  q.push(mc("hard", "A parabola has axis $x=4$ and one zero $x=1$; the other zero is:", ["$7$", "$-2$", "$3$", "$5$"], 0));
  q.push(mc("hard", "$y=-x^2+6x-5$ has a:", ["maximum of $4$", "minimum of $4$", "maximum of $5$", "minimum of $-5$"], 0));
  q.push(mc("hard", "The vertex of $y=2x^2-8x+1$ is:", ["$(2,-7)$", "$(2,7)$", "$(-2,-7)$", "$(4,1)$"], 0));
  q.push(mc("hard", "For $y=(x-3)(x+1)$, the vertex is:", ["$(1,-4)$", "$(1,4)$", "$(-1,-4)$", "$(3,-1)$"], 0));
  q.push(ms("hard", "For $y=x^2-4x-5$:", ["vertex $(2,-9)$", "zeros $5,-1$", "$y$-intercept $-5$", "opens up"], [0, 1, 2, 3]));
  q.push(ms("hard", "To find a vertex from standard form:", ["AOS $x=-b/(2a)$", "substitute to get $y$", "or complete the square", "use the $y$-intercept"], [0, 1, 2]));
  q.push(ms("hard", "A parabola with a maximum has:", ["$a<0$", "vertex at the top", "range $y\\le k$", "opens up"], [0, 1, 2]));
  q.push(ms("hard", "The zeros and AOS:", ["AOS is the midpoint of the zeros", "zeros symmetric about the AOS", "sum of zeros $=2h$", "zeros equal the $y$-intercept"], [0, 1, 2]));
  q.push(tf("hard", "The vertex's $x$ equals $-b/(2a)$ for $y=ax^2+bx+c$.", true));
  q.push(tf("hard", "If a parabola has no real zeros, it does not cross the $x$-axis.", true));
  q.push(tf("hard", "The maximum of $y=-2(x-1)^2+8$ is at $x=8$.", false));
  q.push(fill("hard", "The vertex of $y=x^2-4x-5$ is ___.", ["(2,-9)", "2,-9"]));
  q.push(fill("hard", "Given axis $x=3$ and one zero $1$, the other zero is ___.", ["5"]));
  q.push(fill("hard", "The maximum value of $y=-x^2+6x-5$ is ___.", ["4"]));
  q.push(num("hard", "For $y=x^2-6x+8$, the $y$-coordinate of the vertex is ___.", -1, 0));
  q.push(num("hard", "A parabola has zeros $2$ and $8$; its axis of symmetry is $x=$ ___.", 5, 0));
  q.push(num("hard", "The $y$-intercept of $y=(x-3)(x+1)$ is ___.", -3, 0));
  q.push(order("hard", "Order the steps to find a vertex from standard form.", ["Find AOS $x=-b/(2a)$", "Substitute that $x$", "Compute $y$", "Write the vertex $(x,y)$"]));
  q.push(match("hard", "Match each parabola to its vertex.", ["$y=x^2-6x+5$", "$y=x^2-4x-5$", "$y=x^2-8x+12$"], ["$(3,-4)$", "$(2,-9)$", "$(4,-4)$"], [0, 1, 2]));
  return q;
}

// ── 4.3 Transformations & Vertex Form ────────────────────────
function g43() {
  const q = [];
  q.push(mc("easy", "In $y=a(x-h)^2+k$, the vertex is:", ["$(h,k)$", "$(-h,k)$", "$(h,-k)$", "$(k,h)$"], 0));
  q.push(mc("easy", "$y=(x-3)^2+2$ shifts $y=x^2$:", ["right 3, up 2", "left 3, up 2", "right 3, down 2", "up 3, right 2"], 0));
  q.push(mc("easy", "$y=x^2+5$ shifts $y=x^2$:", ["up 5", "down 5", "right 5", "left 5"], 0));
  q.push(mc("easy", "$y=(x+4)^2$ shifts $y=x^2$:", ["left 4", "right 4", "up 4", "down 4"], 0));
  q.push(mc("easy", "$y=-x^2$ is $y=x^2$:", ["reflected (opens down)", "shifted up", "narrower", "wider"], 0));
  q.push(mc("easy", "The vertex of $y=2(x-1)^2-3$ is:", ["$(1,-3)$", "$(-1,-3)$", "$(1,3)$", "$(2,-3)$"], 0));
  q.push(ms("easy", "In $y=a(x-h)^2+k$:", ["$h$ shifts horizontally", "$k$ shifts vertically", "vertex is $(h,k)$", "$a$ shifts up"], [0, 1, 2]));
  q.push(ms("easy", "$y=(x-2)^2+3$:", ["right 2", "up 3", "vertex $(2,3)$", "opens down"], [0, 1, 2]));
  q.push(ms("easy", "Which open downward?", ["$y=-x^2$", "$y=-2(x-1)^2$", "$y=x^2$", "$y=-(x+3)^2+1$"], [0, 1, 3]));
  q.push(ms("easy", "The vertex of $y=(x+1)^2-5$:", ["$(-1,-5)$", "$h=-1$", "$k=-5$", "$(1,-5)$"], [0, 1, 2]));
  q.push(tf("easy", "$y=a(x-h)^2+k$ has vertex $(h,k)$.", true));
  q.push(tf("easy", "$k>0$ shifts the parabola up.", true));
  q.push(tf("easy", "$y=(x-3)^2$ shifts $y=x^2$ left by 3.", false));
  q.push(fill("easy", "The vertex of $y=(x-2)^2-3$ is ___.", ["(2,-3)", "2,-3"]));
  q.push(fill("easy", "$y=(x+4)^2-5$ shifts $y=x^2$ left ___ and down 5.", ["4"]));
  q.push(fill("easy", "The equation with vertex $(2,-3)$, $a=1$ is $y=$ ___.", ["(x-2)^2-3", "(x-2)²-3"]));
  q.push(num("easy", "The $x$-coordinate of the vertex of $y=2(x-5)^2+1$ is ___.", 5, 0));
  q.push(num("easy", "The vertical shift $k$ in $y=(x-1)^2+7$ is ___.", 7, 0));
  q.push(num("easy", "In $y=a(x-1)^2+2$ through $(3,10)$, find $a$.", 2, 0));
  q.push(match("easy", "Match each equation to its vertex.", ["$y=(x-3)^2+2$", "$y=(x+1)^2-5$", "$y=2(x-1)^2-3$"], ["$(3,2)$", "$(-1,-5)$", "$(1,-3)$"], [0, 1, 2]));
  q.push(mc("medium", "Describe $y=-(x-2)^2+3$:", ["reflect, right 2, up 3", "right 2, up 3", "reflect, left 2, up 3", "reflect, right 2, down 3"], 0));
  q.push(mc("medium", "Describe $y=3x^2-4$:", ["stretch by 3, down 4", "compression, down 4", "stretch by 3, up 4", "stretch by 3, left 4"], 0));
  q.push(mc("medium", "The vertex of $y=2(x-3)^2-7$ is:", ["$(3,-7)$", "$(-3,-7)$", "$(3,7)$", "$(2,-7)$"], 0));
  q.push(mc("medium", "Equation with vertex $(-2,1)$, $a=-1$:", ["$y=-(x+2)^2+1$", "$y=-(x-2)^2+1$", "$y=(x+2)^2-1$", "$y=-(x+2)^2-1$"], 0));
  q.push(mc("medium", "$y=\\tfrac{1}{4}(x+1)^2$ is:", ["a compression, left 1", "a stretch, left 1", "a compression, right 1", "a stretch, right 1"], 0));
  q.push(mc("medium", "A parabola vertex $(0,0)$ through $(2,12)$ has $a=$", ["$3$", "$6$", "$12$", "$2$"], 0));
  q.push(ms("medium", "For $y=-3(x-2)^2+5$:", ["vertex $(2,5)$", "opens down", "stretch by 3", "axis $x=2$"], [0, 1, 2, 3]));
  q.push(ms("medium", "The equation with vertex $(4,-2)$ opening up, $a=3$:", ["$y=3(x-4)^2-2$", "stretch by 3", "vertex $(4,-2)$", "opens up"], [0, 1, 2, 3]));
  q.push(ms("medium", "Which describe $y=(x+4)^2-5$?", ["left 4", "down 5", "vertex $(-4,-5)$", "stretch"], [0, 1, 2]));
  q.push(ms("medium", "To find $a$ from a point:", ["substitute the point", "solve for $a$", "you need the vertex too", "ignore the vertex"], [0, 1, 2]));
  q.push(tf("medium", "$y=-2(x-1)^2+4$ opens downward.", true));
  q.push(tf("medium", "$y=\\tfrac{1}{2}x^2$ is wider than $y=x^2$.", true));
  q.push(tf("medium", "$y=3x^2-4$ is a vertical compression.", false));
  q.push(fill("medium", "The vertex of $y=2(x-3)^2-7$ is ___.", ["(3,-7)", "3,-7"]));
  q.push(fill("medium", "The equation with vertex $(0,5)$, $a=1$: $y=$ ___.", ["x^2+5", "x²+5"]));
  q.push(fill("medium", "A parabola vertex $(-1,3)$ through $(1,11)$ has $a=$ ___.", ["2"]));
  q.push(num("medium", "For a parabola vertex $(0,0)$ through $(2,12)$, find $a$.", 3, 0));
  q.push(num("medium", "The vertical shift $k$ in $y=-2(x+3)^2+6$ is ___.", 6, 0));
  q.push(num("medium", "In $y=a(x-2)^2-1$ through $(0,7)$, find $a$.", 2, 0));
  q.push(match("medium", "Match each equation to its transformation of $y=x^2$.", ["$y=(x-5)^2+1$", "$y=-(x-2)^2+3$", "$y=3x^2-4$"], ["right 5, up 1", "reflect, right 2, up 3", "stretch 3, down 4"], [0, 1, 2]));
  q.push(mc("hard", "A parabola vertex $(1,2)$ through $(3,10)$:", ["$y=2(x-1)^2+2$", "$y=(x-1)^2+2$", "$y=2(x+1)^2+2$", "$y=4(x-1)^2+2$"], 0));
  q.push(mc("hard", "A parabola vertex $(2,-1)$ through $(0,7)$ has $a=$", ["$2$", "$4$", "$-2$", "$1$"], 0));
  q.push(mc("hard", "Vertex $(-1,3)$ through $(1,11)$:", ["$y=2(x+1)^2+3$", "$y=2(x-1)^2+3$", "$y=(x+1)^2+3$", "$y=-2(x+1)^2+3$"], 0));
  q.push(mc("hard", "The $y$-intercept of $y=2(x-2)^2-1$ is:", ["$7$", "$-1$", "$2$", "$3$"], 0));
  q.push(mc("hard", "Convert vertex $(3,-4)$, $a=1$ to standard form:", ["$x^2-6x+5$", "$x^2+6x+5$", "$x^2-6x-4$", "$x^2-3x-4$"], 0));
  q.push(ms("hard", "For vertex $(1,2)$ through $(3,10)$:", ["$10=a(2)^2+2$", "$a=2$", "$y=2(x-1)^2+2$", "$a=4$"], [0, 1, 2]));
  q.push(ms("hard", "The transformations in $y=-2(x-1)^2+4$:", ["reflect", "right 1", "up 4", "stretch by 2"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which need a point besides the vertex to find $a$?", ["any parabola with $a\\ne1$", "when $a$ is unknown", "to pin the width", "never"], [0, 1, 2]));
  q.push(ms("hard", "For $y=-\\tfrac{1}{2}(x+3)^2+6$:", ["vertex $(-3,6)$", "opens down", "compression by $1/2$", "axis $x=-3$"], [0, 1, 2, 3]));
  q.push(tf("hard", "To find $a$, substitute a known point into vertex form.", true));
  q.push(tf("hard", "$y=2(x-2)^2-1$ has $y$-intercept $7$.", true));
  q.push(tf("hard", "A parabola's vertex form needs only the vertex to find $a$.", false));
  q.push(fill("hard", "A parabola vertex $(2,-1)$ through $(0,7)$ has $a=$ ___.", ["2"]));
  q.push(fill("hard", "Convert $y=(x-3)^2-4$ to standard form: $y=$ ___.", ["x^2-6x+5", "x²-6x+5"]));
  q.push(fill("hard", "The $y$-intercept of $y=2(x-2)^2-1$ is ___.", ["7"]));
  q.push(num("hard", "Vertex $(1,2)$ through $(3,10)$: find $a$.", 2, 0));
  q.push(num("hard", "Vertex $(-1,3)$ through $(1,11)$: find $a$.", 2, 0));
  q.push(num("hard", "The $y$-intercept of $y=3(x-1)^2-2$ is ___.", 1, 0));
  q.push(order("hard", "Order the steps to find $a$ in vertex form.", ["Write $y=a(x-h)^2+k$ with the vertex", "Substitute the extra point", "Solve for $a$", "Write the final equation"]));
  q.push(match("hard", "Match each parabola to its $a$-value.", ["vertex $(1,2)$ thru $(3,10)$", "vertex $(0,0)$ thru $(2,12)$", "vertex $(2,-1)$ thru $(0,7)$"], ["$2$", "$3$", "$2$"], [0, 1, 2]));
  return q;
}

// ── 4.4 Graphing from Vertex Form ────────────────────────────
function g44() {
  const q = [];
  q.push(mc("easy", "To graph $y=a(x-h)^2+k$, first plot the:", ["vertex $(h,k)$", "$y$-intercept", "zeros", "origin"], 0));
  q.push(mc("easy", "The vertex of $y=(x-2)^2-1$ is:", ["$(2,-1)$", "$(-2,-1)$", "$(2,1)$", "$(1,2)$"], 0));
  q.push(mc("easy", "$y=(x+1)^2-4$ opens:", ["up", "down", "left", "right"], 0));
  q.push(mc("easy", "The range of $y=(x-1)^2+3$ is:", ["$y\\ge3$", "$y\\le3$", "$y\\ge1$", "all reals"], 0));
  q.push(mc("easy", "The vertex of $y=-(x+1)^2+4$ is:", ["$(-1,4)$", "$(1,4)$", "$(-1,-4)$", "$(4,-1)$"], 0));
  q.push(mc("easy", "A parabola opening up has range:", ["$y\\ge k$", "$y\\le k$", "$y\\ge h$", "all reals"], 0));
  q.push(ms("easy", "To graph from vertex form:", ["plot the vertex", "use the step pattern", "draw the axis of symmetry", "find zeros if needed"], [0, 1, 2, 3]));
  q.push(ms("easy", "For $y=2(x-1)^2-3$:", ["vertex $(1,-3)$", "opens up", "narrow (step $2,8$)", "opens down"], [0, 1, 2]));
  q.push(ms("easy", "The range of $y=-(x-4)^2+6$:", ["$y\\le6$", "maximum $6$", "opens down", "$y\\ge6$"], [0, 1, 2]));
  q.push(ms("easy", "Which open downward?", ["$y=-(x-2)^2+3$", "$y=-2(x+1)^2$", "$y=(x-1)^2$", "$y=-(x+3)^2+5$"], [0, 1, 3]));
  q.push(tf("easy", "The vertex is the first point to plot.", true));
  q.push(tf("easy", "$y=2(x-1)^2+3$ has minimum value $3$.", true));
  q.push(tf("easy", "$y=-(x-3)^2+5$ has a minimum.", false));
  q.push(fill("easy", "The vertex of $y=(x-1)^2-4$ is ___.", ["(1,-4)", "1,-4"]));
  q.push(fill("easy", "The range of $y=2(x-1)^2+3$ is $y\\ge$ ___.", ["3"]));
  q.push(fill("easy", "The $x$-intercepts of $y=(x-2)^2-9$ are ___.", ["5 and -1", "5,-1", "-1,5"]));
  q.push(num("easy", "The $x$-coordinate of the vertex of $y=(x-2)^2-1$ is ___.", 2, 0));
  q.push(num("easy", "The minimum value of $y=3(x+1)^2-2$ is ___.", -2, 0));
  q.push(num("easy", "The positive $x$-intercept of $y=(x-1)^2-16$ is ___.", 5, 0));
  q.push(match("easy", "Match each parabola to its vertex.", ["$y=(x-2)^2-1$", "$y=-(x+1)^2+4$", "$y=2(x-1)^2-3$"], ["$(2,-1)$", "$(-1,4)$", "$(1,-3)$"], [0, 1, 2]));
  q.push(mc("medium", "The $x$-intercepts of $y=(x-2)^2-9$:", ["$5,-1$", "$-5,1$", "$2,9$", "$1,5$"], 0));
  q.push(mc("medium", "The $x$-intercepts of $y=(x+1)^2-4$:", ["$1,-3$", "$-1,-3$", "$1,3$", "$3,-3$"], 0));
  q.push(mc("medium", "The range of $y=2(x-1)^2+3$:", ["$y\\ge3$", "$y\\le3$", "$y\\ge1$", "$y\\ge2$"], 0));
  q.push(mc("medium", "The vertex of $y=-(x-3)^2+5$:", ["$(3,5)$", "$(-3,5)$", "$(3,-5)$", "$(5,3)$"], 0));
  q.push(mc("medium", "Does $y=2(x+1)^2+5$ have $x$-intercepts?", ["no", "yes, two", "yes, one", "cannot tell"], 0));
  q.push(mc("medium", "The $y$-intercept of $y=(x-3)^2+1$:", ["$10$", "$1$", "$9$", "$3$"], 0));
  q.push(ms("medium", "For $y=(x+2)^2-9$:", ["vertex $(-2,-9)$", "opens up", "zeros $1,-5$", "range $y\\ge-9$"], [0, 1, 2, 3]));
  q.push(ms("medium", "For $y=-2(x-1)^2+2$:", ["vertex $(1,2)$", "opens down", "zeros $0,2$", "range $y\\le2$"], [0, 1, 2, 3]));
  q.push(ms("medium", "A parabola with vertex above the $x$-axis opening up:", ["has no real zeros", "has minimum $>0$", "stays above the axis", "crosses twice"], [0, 1, 2]));
  q.push(ms("medium", "The range depends on:", ["$k$", "whether it opens up or down", "the vertex's $y$-value", "the $y$-intercept"], [0, 1, 2]));
  q.push(tf("medium", "$y=2(x+1)^2+5$ has no $x$-intercepts.", true));
  q.push(tf("medium", "The range of $y=-(x-4)^2+6$ is $y\\le6$.", true));
  q.push(tf("medium", "The $y$-intercept of $y=(x-3)^2+1$ is $1$.", false));
  q.push(fill("medium", "The $x$-intercepts of $y=(x-1)^2-16$ are ___.", ["5 and -3", "5,-3", "-3,5"]));
  q.push(fill("medium", "The range of $y=-(x-2)^2+6$ is $y\\le$ ___.", ["6"]));
  q.push(fill("medium", "The $y$-intercept of $y=(x-3)^2+1$ is ___.", ["10"]));
  q.push(num("medium", "The positive $x$-intercept of $y=(x-2)^2-9$ is ___.", 5, 0));
  q.push(num("medium", "The minimum value of $y=2(x-1)^2+3$ is ___.", 3, 0));
  q.push(num("medium", "The $y$-intercept of $y=(x+1)^2-4$ is ___.", -3, 0));
  q.push(match("medium", "Match each parabola to its range.", ["$y=(x-1)^2+3$", "$y=-(x-2)^2+6$", "$y=2(x+1)^2-5$"], ["$y\\ge3$", "$y\\le6$", "$y\\ge-5$"], [0, 1, 2]));
  q.push(mc("hard", "The zeros of $y=-2(x+2)^2+8$:", ["$0,-4$", "$0,4$", "$2,-6$", "$-2,8$"], 0));
  q.push(mc("hard", "The range of $y=-\\tfrac{1}{3}(x-3)^2+4$:", ["$y\\le4$", "$y\\ge4$", "$y\\le3$", "$y\\ge-3$"], 0));
  q.push(mc("hard", "The $x$-intercepts of $y=2(x-1)^2-8$:", ["$3,-1$", "$-3,1$", "$1,8$", "$2,-2$"], 0));
  q.push(mc("hard", "A parabola vertex $(2,-9)$ opening up has zeros:", ["$-1,5$", "$1,-5$", "$2,9$", "$-2,9$"], 0));
  q.push(mc("hard", "$y=(x-2)^2-9$ in standard form is:", ["$x^2-4x-5$", "$x^2-4x+5$", "$x^2+4x-5$", "$x^2-9$"], 0));
  q.push(ms("hard", "For $y=-2(x+2)^2+8$:", ["vertex $(-2,8)$", "opens down", "zeros $0,-4$", "range $y\\le8$"], [0, 1, 2, 3]));
  q.push(ms("hard", "To find $x$-intercepts from vertex form:", ["set $y=0$", "isolate the squared term", "take $\\pm\\sqrt{}$", "solve for $x$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which have two real $x$-intercepts?", ["$y=(x-1)^2-4$", "$y=-2(x+2)^2+8$", "$y=2(x+1)^2+5$", "$y=(x-2)^2-9$"], [0, 1, 3]));
  q.push(ms("hard", "Range and direction:", ["opens up $\\Rightarrow y\\ge k$", "opens down $\\Rightarrow y\\le k$", "$k$ is the extreme value", "$h$ is the extreme value"], [0, 1, 2]));
  q.push(tf("hard", "To find zeros from vertex form, set $y=0$ and solve.", true));
  q.push(tf("hard", "$y=-2(x+2)^2+8$ has zeros $0$ and $-4$.", true));
  q.push(tf("hard", "$y=2(x+1)^2+5$ crosses the $x$-axis twice.", false));
  q.push(fill("hard", "The zeros of $y=(x+2)^2-9$ are ___.", ["1 and -5", "1,-5", "-5,1"]));
  q.push(fill("hard", "The range of $y=-2(x+2)^2+8$ is $y\\le$ ___.", ["8"]));
  q.push(fill("hard", "Convert $y=(x-2)^2-9$ to standard form: $y=$ ___.", ["x^2-4x-5", "x²-4x-5"]));
  q.push(num("hard", "The positive zero of $y=2(x-1)^2-8$ is ___.", 3, 0));
  q.push(num("hard", "The maximum value of $y=-2(x+2)^2+8$ is ___.", 8, 0));
  q.push(num("hard", "The $y$-intercept of $y=(x-2)^2-9$ is ___.", -5, 0));
  q.push(order("hard", "Order the steps to find $x$-intercepts from vertex form.", ["Set $y=0$", "Isolate the squared term", "Take $\\pm$ square root", "Solve for $x$"]));
  q.push(match("hard", "Match each parabola to its zeros.", ["$y=(x-2)^2-9$", "$y=(x+1)^2-4$", "$y=-2(x+2)^2+8$"], ["$-1,5$", "$-3,1$", "$-4,0$"], [0, 1, 2]));
  return q;
}

// ── 4.5 Factored Form & the Zeros ────────────────────────────
function g45() {
  const q = [];
  q.push(mc("easy", "The zeros of $y=(x-2)(x+3)$ are:", ["$2,-3$", "$-2,3$", "$2,3$", "$-2,-3$"], 0));
  q.push(mc("easy", "Factored form is:", ["$y=a(x-r)(x-s)$", "$y=ax^2+bx+c$", "$y=a(x-h)^2+k$", "$y=mx+b$"], 0));
  q.push(mc("easy", "The zeros of $y=(x-5)(x-1)$ are:", ["$5,1$", "$-5,-1$", "$5,-1$", "$1,-5$"], 0));
  q.push(mc("easy", "The axis of symmetry from zeros $r,s$ is $x=$", ["$\\tfrac{r+s}{2}$", "$r+s$", "$rs$", "$\\tfrac{r-s}{2}$"], 0));
  q.push(mc("easy", "A quadratic with zeros $-2,4$, $a=1$:", ["$(x+2)(x-4)$", "$(x-2)(x+4)$", "$(x+2)(x+4)$", "$(x-2)(x-4)$"], 0));
  q.push(mc("easy", "The zeros of $y=x(x-3)$ are:", ["$0,3$", "$0,-3$", "$3$", "$1,3$"], 0));
  q.push(ms("easy", "From $y=a(x-r)(x-s)$:", ["zeros are $r,s$", "AOS is the midpoint", "$a$ sets width/direction", "$r,s$ are $y$-intercepts"], [0, 1, 2]));
  q.push(ms("easy", "The zeros of $y=(x-2)(x+3)$:", ["$x=2$", "$x=-3$", "set each factor to $0$", "$x=3$"], [0, 1, 2]));
  q.push(ms("easy", "Which have a zero at $x=0$?", ["$y=x(x-3)$", "$y=x(x+5)$", "$y=(x-1)(x-2)$", "$y=2x(x-4)$"], [0, 1, 3]));
  q.push(ms("easy", "To build from zeros $r,s$:", ["write $(x-r)(x-s)$", "multiply by $a$", "check a point if $a\\ne1$", "add $r+s$"], [0, 1, 2]));
  q.push(tf("easy", "The zeros of $y=(x-2)(x+3)$ are $2$ and $-3$.", true));
  q.push(tf("easy", "The AOS is the midpoint of the two zeros.", true));
  q.push(tf("easy", "The zeros of $y=(x-5)(x-1)$ are $-5,-1$.", false));
  q.push(fill("easy", "The zeros of $y=(x-4)(x+1)$ are ___.", ["4 and -1", "4,-1", "-1,4"]));
  q.push(fill("easy", "A quadratic with zeros $3,-5$ ($a=1$) is $y=$ ___.", ["(x-3)(x+5)"]));
  q.push(fill("easy", "The AOS of $y=(x-6)(x-2)$ is $x=$ ___.", ["4"]));
  q.push(num("easy", "The axis of symmetry of $y=(x-1)(x-5)$ is $x=$ ___.", 3, 0));
  q.push(num("easy", "The non-zero zero of $y=x(x-3)$ is ___.", 3, 0));
  q.push(num("easy", "The product of the zeros of $y=(x-2)(x+3)$ is ___.", -6, 0));
  q.push(match("easy", "Match each factored form to its zeros.", ["$(x-2)(x+3)$", "$(x-5)(x-1)$", "$x(x+4)$"], ["$2,-3$", "$5,1$", "$0,-4$"], [0, 1, 2]));
  q.push(mc("medium", "The vertex of $y=2(x+1)(x-3)$:", ["$(1,-8)$", "$(1,8)$", "$(-1,-8)$", "$(2,-3)$"], 0));
  q.push(mc("medium", "Find the zeros of $y=x^2-x-6$:", ["$3,-2$", "$-3,2$", "$6,-1$", "$2,3$"], 0));
  q.push(mc("medium", "The vertex of $y=x^2-6x+8$:", ["$(3,-1)$", "$(3,1)$", "$(2,4)$", "$(6,8)$"], 0));
  q.push(mc("medium", "A parabola zeros $1,5$ through $(3,-4)$ has $a=$", ["$1$", "$2$", "$-1$", "$4$"], 0));
  q.push(mc("medium", "The zeros of $y=-(x+2)(x-4)$:", ["$-2,4$", "$2,-4$", "$-2,-4$", "$2,4$"], 0));
  q.push(mc("medium", "The $y$-intercept of $y=(x-2)(x-5)$:", ["$10$", "$-10$", "$7$", "$2$"], 0));
  q.push(ms("medium", "For $y=2(x+1)(x-3)$:", ["zeros $-1,3$", "AOS $x=1$", "vertex $(1,-8)$", "opens up"], [0, 1, 2, 3]));
  q.push(ms("medium", "For $y=x^2-6x+8=(x-2)(x-4)$:", ["zeros $2,4$", "AOS $x=3$", "vertex $(3,-1)$", "$y$-int $8$"], [0, 1, 2, 3]));
  q.push(ms("medium", "To find a vertex from factored form:", ["find the zeros", "average them for the AOS", "substitute the AOS for $y$", "use the $y$-intercept"], [0, 1, 2]));
  q.push(ms("medium", "Which open downward?", ["$y=-(x+2)(x-4)$", "$y=-2(x-1)(x-5)$", "$y=(x-1)(x-2)$", "$y=-x(x+3)$"], [0, 1, 3]));
  q.push(tf("medium", "The vertex's $x$ is the average of the zeros.", true));
  q.push(tf("medium", "$y=-(x+2)(x-4)$ opens downward.", true));
  q.push(tf("medium", "The $y$-intercept of $y=(x-2)(x-5)$ is $7$.", false));
  q.push(fill("medium", "The zeros of $y=x^2+2x-15$ are ___.", ["3 and -5", "3,-5", "-5,3"]));
  q.push(fill("medium", "The vertex of $y=x^2-4x-5$ is ___.", ["(2,-9)", "2,-9"]));
  q.push(fill("medium", "A quadratic zeros $0,6$ through $(1,-10)$ has $a=$ ___.", ["2"]));
  q.push(num("medium", "The $y$-coordinate of the vertex of $y=2(x+1)(x-3)$ is ___.", -8, 0));
  q.push(num("medium", "The $y$-intercept of $y=(x-2)(x-5)$ is ___.", 10, 0));
  q.push(num("medium", "The axis of symmetry of $y=(x-1)(x-5)$ is $x=$ ___.", 3, 0));
  q.push(match("medium", "Match each to its vertex.", ["$y=2(x+1)(x-3)$", "$y=x^2-6x+8$", "$y=x^2-4x-5$"], ["$(1,-8)$", "$(3,-1)$", "$(2,-9)$"], [0, 1, 2]));
  q.push(mc("hard", "A parabola $x$-intercepts $-3,5$, $y$-intercept $-30$ has $a=$", ["$2$", "$1$", "$-2$", "$3$"], 0));
  q.push(mc("hard", "The vertex of $y=-(x+2)(x-4)$:", ["$(1,9)$", "$(1,-9)$", "$(-1,9)$", "$(2,4)$"], 0));
  q.push(mc("hard", "A parabola zeros $1,5$ through $(3,-4)$:", ["$y=(x-1)(x-5)$", "$y=2(x-1)(x-5)$", "$y=-(x-1)(x-5)$", "$y=(x+1)(x+5)$"], 0));
  q.push(mc("hard", "Zeros $2,-2$, $y$-intercept $-8$:", ["$y=2(x-2)(x+2)$", "$y=(x-2)(x+2)$", "$y=-2(x-2)(x+2)$", "$y=2(x-2)(x-2)$"], 0));
  q.push(mc("hard", "A parabola $x$-intercepts $1,7$ through $(4,-9)$:", ["vertex $(4,-9)$", "vertex $(4,9)$", "$a=2$", "no real zeros"], 0));
  q.push(ms("hard", "For zeros $-3,5$ and $y$-intercept $-30$:", ["$y=a(x+3)(x-5)$", "$a(3)(-5)=-30$", "$a=2$", "$y=2(x+3)(x-5)$"], [0, 1, 2, 3]));
  q.push(ms("hard", "To find $a$ from intercepts and a point:", ["write factored form with the zeros", "substitute the point", "solve for $a$", "ignore the point"], [0, 1, 2]));
  q.push(ms("hard", "For $y=-(x+2)(x-4)$:", ["zeros $-2,4$", "AOS $x=1$", "vertex $(1,9)$", "opens down"], [0, 1, 2, 3]));
  q.push(ms("hard", "The $y$-intercept of $y=a(x-r)(x-s)$:", ["is found by $x=0$", "equals $a(-r)(-s)$", "equals $a\\,rs$", "equals $r+s$"], [0, 1, 2]));
  q.push(tf("hard", "The $y$-intercept of $y=2(x+3)(x-5)$ is $-30$.", true));
  q.push(tf("hard", "A parabola through its two zeros and one more point is fully determined.", true));
  q.push(tf("hard", "The vertex of $y=-(x+2)(x-4)$ is a minimum.", false));
  q.push(fill("hard", "A parabola $x$-intercepts $-3,5$, $y$-intercept $-30$ has $a=$ ___.", ["2"]));
  q.push(fill("hard", "The vertex of $y=-(x+2)(x-4)$ is ___.", ["(1,9)", "1,9"]));
  q.push(fill("hard", "A parabola zeros $2,-2$, $y$-intercept $-8$: $y=$ ___.", ["2(x-2)(x+2)"]));
  q.push(num("hard", "For zeros $1,5$ through $(3,-4)$, find $a$.", 1, 0));
  q.push(num("hard", "The $y$-coordinate of the vertex of $y=-(x+2)(x-4)$ is ___.", 9, 0));
  q.push(num("hard", "For $x$-intercepts $-3,5$ and $y$-intercept $-30$, find $a$.", 2, 0));
  q.push(order("hard", "Order the steps to find the equation from $x$-intercepts and a point.", ["Write $y=a(x-r)(x-s)$", "Substitute the extra point", "Solve for $a$", "Write the final equation"]));
  q.push(match("hard", "Match each parabola to its $a$-value.", ["zeros $1,5$ thru $(3,-4)$", "zeros $0,6$ thru $(1,-10)$", "x-int $-3,5$ y-int $-30$"], ["$1$", "$2$", "$2$"], [0, 1, 2]));
  return q;
}

// ── 4.6 Standard Form & Converting Between Forms ─────────────
function g46() {
  const q = [];
  q.push(mc("easy", "Standard form is:", ["$y=ax^2+bx+c$", "$y=a(x-h)^2+k$", "$y=a(x-r)(x-s)$", "$y=mx+b$"], 0));
  q.push(mc("easy", "The $y$-intercept of $y=ax^2+bx+c$ is:", ["$c$", "$a$", "$b$", "$0$"], 0));
  q.push(mc("easy", "The AOS of $y=ax^2+bx+c$ is $x=$", ["$-b/(2a)$", "$b/(2a)$", "$-b/a$", "$c/a$"], 0));
  q.push(mc("easy", "The $y$-intercept of $y=2x^2+3x-5$ is:", ["$-5$", "$3$", "$2$", "$5$"], 0));
  q.push(mc("easy", "Vertex form is:", ["$y=a(x-h)^2+k$", "$y=ax^2+bx+c$", "$y=a(x-r)(x-s)$", "$y=mx+b$"], 0));
  q.push(mc("easy", "Convert $y=(x+3)(x-1)$ to standard form:", ["$x^2+2x-3$", "$x^2-2x-3$", "$x^2+2x+3$", "$x^2-3$"], 0));
  q.push(ms("easy", "The three forms of a quadratic:", ["standard $ax^2+bx+c$", "vertex $a(x-h)^2+k$", "factored $a(x-r)(x-s)$", "linear $mx+b$"], [0, 1, 2]));
  q.push(ms("easy", "From standard form you can read:", ["the $y$-intercept $c$", "the AOS via $-b/(2a)$", "the leading coefficient $a$", "the zeros directly"], [0, 1, 2]));
  q.push(ms("easy", "To convert standard to vertex:", ["complete the square", "or find the vertex via the AOS", "keep $a$", "just drop $c$"], [0, 1, 2]));
  q.push(ms("easy", "To convert standard to factored:", ["factor the trinomial", "find the zeros", "check $a$", "add the terms"], [0, 1, 2]));
  q.push(tf("easy", "The $y$-intercept of $y=ax^2+bx+c$ is $c$.", true));
  q.push(tf("easy", "The AOS of $y=ax^2+bx+c$ is $x=-b/(2a)$.", true));
  q.push(tf("easy", "Standard form shows the vertex directly.", false));
  q.push(fill("easy", "The $y$-intercept of $y=3x^2-2x+7$ is ___.", ["7"]));
  q.push(fill("easy", "The AOS of $y=x^2-6x+5$ is $x=$ ___.", ["3"]));
  q.push(fill("easy", "Convert $y=(x-2)(x+6)$ to standard form: $y=$ ___.", ["x^2+4x-12", "x²+4x-12"]));
  q.push(num("easy", "The AOS of $y=2x^2-12x+7$ is $x=$ ___.", 3, 0));
  q.push(num("easy", "The $y$-intercept of $y=-3x^2+4x-1$ is ___.", -1, 0));
  q.push(num("easy", "The $y$-coordinate of the vertex of $y=x^2-6x+5$ is ___.", -4, 0));
  q.push(match("easy", "Match each form to what it reveals.", ["standard", "vertex", "factored"], ["the $y$-intercept", "the vertex", "the zeros"], [0, 1, 2]));
  q.push(mc("medium", "Convert $y=x^2-4x+1$ to vertex form:", ["$(x-2)^2-3$", "$(x-2)^2+3$", "$(x+2)^2-3$", "$(x-2)^2-5$"], 0));
  q.push(mc("medium", "Convert $y=x^2+6x+5$ to factored form:", ["$(x+1)(x+5)$", "$(x-1)(x-5)$", "$(x+1)(x-5)$", "$(x+5)(x+5)$"], 0));
  q.push(mc("medium", "Convert $y=(x-2)^2-9$ to standard form:", ["$x^2-4x-5$", "$x^2-4x+5$", "$x^2+4x-5$", "$x^2-9$"], 0));
  q.push(mc("medium", "The vertex of $y=x^2-8x+10$:", ["$(4,-6)$", "$(4,6)$", "$(8,10)$", "$(-4,-6)$"], 0));
  q.push(mc("medium", "The zeros of $y=x^2-x-12$:", ["$4,-3$", "$-4,3$", "$12,-1$", "$3,4$"], 0));
  q.push(mc("medium", "Convert $y=2x^2-8x+1$ to vertex form:", ["$2(x-2)^2-7$", "$2(x-2)^2+7$", "$2(x-2)^2-9$", "$(x-2)^2-7$"], 0));
  q.push(ms("medium", "To convert $y=x^2-4x+1$ to vertex form:", ["complete the square", "$(x^2-4x+4)-4+1$", "$(x-2)^2-3$", "factor it"], [0, 1, 2]));
  q.push(ms("medium", "For $y=x^2-8x+10$:", ["AOS $x=4$", "$y=-6$ at vertex", "vertex $(4,-6)$", "$y$-int $10$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Which equal $y=x^2+6x+5$?", ["$(x+1)(x+5)$", "$(x+3)^2-4$", "standard form", "$(x+5)(x+1)$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Converting standard to vertex when $a\\ne1$:", ["factor $a$ from the $x$-terms", "complete the square inside", "distribute $a$ back", "ignore $a$"], [0, 1, 2]));
  q.push(tf("medium", "$y=x^2-4x+1=(x-2)^2-3$.", true));
  q.push(tf("medium", "$y=2x^2-8x+1=2(x-2)^2-7$.", true));
  q.push(tf("medium", "$y=x^2+6x+5$ factors as $(x+1)(x+6)$.", false));
  q.push(fill("medium", "Convert $y=x^2-6x+4$ to vertex form: $y=$ ___.", ["(x-3)^2-5", "(x-3)²-5"]));
  q.push(fill("medium", "Convert $y=x^2+8x+15$ to factored form: $y=$ ___.", ["(x+3)(x+5)"]));
  q.push(fill("medium", "Convert $y=(x-3)^2-4$ to standard form: $y=$ ___.", ["x^2-6x+5", "x²-6x+5"]));
  q.push(num("medium", "The AOS of $y=2x^2-12x+7$ is $x=$ ___.", 3, 0));
  q.push(num("medium", "The $y$-coordinate of the vertex of $y=x^2-8x+10$ is ___.", -6, 0));
  q.push(num("medium", "The smaller zero of $y=x^2-x-12$ is ___.", -3, 0));
  q.push(match("medium", "Match each standard form to its vertex.", ["$y=x^2-6x+5$", "$y=x^2-8x+10$", "$y=x^2+4x+1$"], ["$(3,-4)$", "$(4,-6)$", "$(-2,-3)$"], [0, 1, 2]));
  q.push(mc("hard", "Convert $y=3x^2-12x+5$ to vertex form:", ["$3(x-2)^2-7$", "$3(x-2)^2+7$", "$3(x-2)^2-17$", "$(x-2)^2-7$"], 0));
  q.push(mc("hard", "The vertex of $y=2x^2+12x+5$:", ["$(-3,-13)$", "$(3,-13)$", "$(-3,13)$", "$(-6,5)$"], 0));
  q.push(mc("hard", "Does $y=x^2+2x+5$ have real zeros?", ["no", "yes, two", "yes, one", "cannot tell"], 0));
  q.push(mc("hard", "Convert $y=2x^2+12x+5$ to vertex form:", ["$2(x+3)^2-13$", "$2(x+3)^2+13$", "$2(x+3)^2-23$", "$(x+3)^2-13$"], 0));
  q.push(mc("hard", "For $y=2x^2-8x+3$, the vertex form is:", ["$2(x-2)^2-5$", "$2(x-2)^2+5$", "$2(x-2)^2-11$", "$(x-2)^2-5$"], 0));
  q.push(ms("hard", "For $y=3x^2-12x+5$:", ["AOS $x=2$", "vertex $(2,-7)$", "minimum $-7$", "$y$-int $5$"], [0, 1, 2, 3]));
  q.push(ms("hard", "To complete the square for $2x^2+12x+5$:", ["factor $2$ from $2x^2+12x$", "$2(x^2+6x)+5$", "$2((x+3)^2-9)+5$", "$2(x+3)^2-13$"], [0, 1, 2, 3]));
  q.push(ms("hard", "$y=x^2+2x+5$:", ["$D=4-20<0$", "no real zeros", "$=(x+1)^2+4$", "minimum $4$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which forms reveal the vertex?", ["vertex form directly", "standard via $-b/(2a)$", "completing the square", "factored directly"], [0, 1, 2]));
  q.push(tf("hard", "$y=3x^2-12x+5$ has vertex $(2,-7)$.", true));
  q.push(tf("hard", "$y=x^2+2x+5$ has no real zeros.", true));
  q.push(tf("hard", "Completing the square on $2x^2+12x+5$ gives $2(x+3)^2+5$.", false));
  q.push(fill("hard", "Convert $y=2x^2+12x+5$ to vertex form: $y=$ ___.", ["2(x+3)^2-13", "2(x+3)²-13"]));
  q.push(fill("hard", "The vertex of $y=2x^2-8x+3$ is ___.", ["(2,-5)", "2,-5"]));
  q.push(fill("hard", "The minimum value of $y=3x^2-12x+5$ is ___.", ["-7"]));
  q.push(num("hard", "The AOS of $y=3x^2-12x+5$ is $x=$ ___.", 2, 0));
  q.push(num("hard", "The minimum value of $y=2x^2-8x+3$ is ___.", -5, 0));
  q.push(num("hard", "The $y$-intercept of $y=2x^2-8x+3$ is ___.", 3, 0));
  q.push(order("hard", "Order the steps to complete the square for $ax^2+bx+c$ ($a\\ne1$).", ["Factor $a$ from the $x$-terms", "Add and subtract $(b/2a)^2$ inside", "Write the perfect square", "Distribute $a$ and simplify"]));
  q.push(match("hard", "Match each standard form to its vertex form.", ["$y=x^2-4x+1$", "$y=2x^2-8x+1$", "$y=3x^2-12x+5$"], ["$(x-2)^2-3$", "$2(x-2)^2-7$", "$3(x-2)^2-7$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "4.1", gen: g41 },
  { code: "4.2", gen: g42 },
  { code: "4.3", gen: g43 },
  { code: "4.4", gen: g44 },
  { code: "4.5", gen: g45 },
  { code: "4.6", gen: g46 },
];
