// MPM2D Unit 5 — Quadratic Equations: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "./helpers.mjs";

// ── 5.1 Solving Quadratic Equations by Factoring ─────────────
function g51() {
  const q = [];
  q.push(mc("easy", "Solve $x^2-5x+6=0$.", ["$2,3$", "$-2,-3$", "$1,6$", "$5,6$"], 0));
  q.push(mc("easy", "Zero product: if $PQ=0$ then:", ["$P=0$ or $Q=0$", "$P=Q$", "$P+Q=0$", "$P=0$ and $Q=0$"], 0));
  q.push(mc("easy", "Solve $x^2-9=0$.", ["$\\pm3$", "$\\pm9$", "$3$", "$0$"], 0));
  q.push(mc("easy", "Solve $x^2+x-12=0$.", ["$-4,3$", "$4,-3$", "$4,3$", "$-4,-3$"], 0));
  q.push(mc("easy", "Solve $x^2-4x=0$.", ["$0,4$", "$0,-4$", "$4$", "$2$"], 0));
  q.push(mc("easy", "Before factoring, set the equation equal to:", ["$0$", "$1$", "$x$", "$y$"], 0));
  q.push(ms("easy", "Solutions of $x^2-5x+6=0$:", ["$x=2$", "$x=3$", "factor $(x-2)(x-3)$", "$x=6$"], [0, 1, 2]));
  q.push(ms("easy", "Which are solved by factoring?", ["$x^2-9=0$", "$x^2-5x+6=0$", "$x^2-4x=0$", "$x=5$"], [0, 1, 2]));
  q.push(ms("easy", "The zero product property:", ["a factor is $0$", "at least one factor is $0$", "set each factor $=0$", "both must be nonzero"], [0, 1, 2]));
  q.push(ms("easy", "Solve $x^2-4x=0$:", ["$x(x-4)=0$", "$x=0$", "$x=4$", "$x=-4$"], [0, 1, 2]));
  q.push(tf("easy", "To solve by factoring, first set the equation to $0$.", true));
  q.push(tf("easy", "$x^2-9=0$ has solutions $\\pm3$.", true));
  q.push(tf("easy", "$(x-2)(x-3)=0$ means $x=2$ and $x=3$ at the same time.", false));
  q.push(fill("easy", "Solve $x^2-7x+10=0$: $x=$ ___.", ["2 and 5", "2,5", "5,2"]));
  q.push(fill("easy", "Solve $x^2-16=0$: $x=$ ___.", ["±4", "4,-4", "\\pm4"]));
  q.push(fill("easy", "Solve $x^2-5x=0$: $x=$ ___.", ["0 and 5", "0,5", "5,0"]));
  q.push(num("easy", "The positive solution of $x^2-9=0$ is ___.", 3, 0));
  q.push(num("easy", "The number of solutions of $x^2-6x+9=0$ is ___.", 1, 0));
  q.push(num("easy", "The nonzero solution of $x^2-4x=0$ is ___.", 4, 0));
  q.push(match("easy", "Match each equation to its solutions.", ["$x^2-5x+6=0$", "$x^2-9=0$", "$x^2-4x=0$"], ["$2,3$", "$\\pm3$", "$0,4$"], [0, 1, 2]));
  q.push(mc("medium", "Solve $2x^2+5x-3=0$.", ["$1/2,-3$", "$-1/2,3$", "$2,-3$", "$1/2,3$"], 0));
  q.push(mc("medium", "Solve $x^2=2x+8$.", ["$4,-2$", "$-4,2$", "$2,8$", "$4,2$"], 0));
  q.push(mc("medium", "Solve $3x^2=12x$.", ["$0,4$", "$0,-4$", "$4$", "$3,12$"], 0));
  q.push(mc("medium", "Solve $x^2-6x+9=0$.", ["$3$ (double)", "$3,-3$", "$9$", "$0,3$"], 0));
  q.push(mc("medium", "Solve $4x^2-9=0$.", ["$\\pm3/2$", "$\\pm9/4$", "$3/2$", "$\\pm2/3$"], 0));
  q.push(mc("medium", "Solve $3x^2+x-2=0$.", ["$2/3,-1$", "$-2/3,1$", "$3,-2$", "$2/3,1$"], 0));
  q.push(ms("medium", "Solving $2x^2+5x-3=0$:", ["factor $(2x-1)(x+3)$", "$x=1/2$", "$x=-3$", "$x=3$"], [0, 1, 2]));
  q.push(ms("medium", "Which have a double root?", ["$x^2-6x+9=0$", "$x^2+4x+4=0$", "$x^2-5x+6=0$", "$(x-2)^2=0$"], [0, 1, 3]));
  q.push(ms("medium", "To solve $x^2=2x+8$:", ["rearrange to $x^2-2x-8=0$", "factor $(x-4)(x+2)$", "$x=4$", "$x=-2$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Which need rearranging before factoring?", ["$x^2=2x+8$", "$3x^2=12x$", "$x^2-5x+6=0$", "$(x-1)(x+2)=4$"], [0, 1, 3]));
  q.push(tf("medium", "$2x^2+5x-3=(2x-1)(x+3)$.", true));
  q.push(tf("medium", "$3x^2=12x$ has solutions $0$ and $4$.", true));
  q.push(tf("medium", "$x^2-6x+9=0$ has two distinct solutions.", false));
  q.push(fill("medium", "Solve $2x^2-5x-3=0$: $x=$ ___.", ["3 and -1/2", "3,-1/2", "-1/2,3"]));
  q.push(fill("medium", "Solve $x^2-2x-15=0$: $x=$ ___.", ["5 and -3", "5,-3", "-3,5"]));
  q.push(fill("medium", "Solve $x^2=3x+4$: $x=$ ___.", ["4 and -1", "4,-1", "-1,4"]));
  q.push(num("medium", "The double root of $x^2-6x+9=0$ is ___.", 3, 0));
  q.push(num("medium", "The positive solution of $4x^2-9=0$ is ___.", 1.5, 0));
  q.push(num("medium", "The nonzero solution of $3x^2=12x$ is ___.", 4, 0));
  q.push(match("medium", "Match each equation to its solutions.", ["$2x^2+5x-3=0$", "$x^2=2x+8$", "$x^2-6x+9=0$"], ["$1/2,-3$", "$4,-2$", "$3$ (double)"], [0, 1, 2]));
  q.push(mc("hard", "Solve $(x-1)(x+2)=4$.", ["$-3,2$", "$3,-2$", "$1,-2$", "$4,-4$"], 0));
  q.push(mc("hard", "Solve $2x^2+x-15=0$.", ["$5/2,-3$", "$-5/2,3$", "$3,-5$", "$5/2,3$"], 0));
  q.push(mc("hard", "Solve $6x^2-7x-3=0$.", ["$3/2,-1/3$", "$-3/2,1/3$", "$3,-1$", "$2/3,-3$"], 0));
  q.push(mc("hard", "Solve $x^2-6x+9=0$; the number of distinct roots is:", ["one ($x=3$)", "two", "none", "three"], 0));
  q.push(mc("hard", "Solve $9x^2-1=0$.", ["$\\pm1/3$", "$\\pm1/9$", "$\\pm3$", "$1/3$"], 0));
  q.push(ms("hard", "Solving $(x-1)(x+2)=4$:", ["expand to $x^2+x-2=4$", "get $x^2+x-6=0$", "factor $(x+3)(x-2)$", "$x=-3,2$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which have no rational solutions by factoring?", ["$x^2+x+1=0$", "$x^2-2=0$", "$x^2-5x+6=0$", "$x^2+1=0$"], [0, 1, 3]));
  q.push(ms("hard", "Which equal $0$ at $x=3$?", ["$(x-3)(x+1)$", "$x^2-9$", "$x^2-6x+9$", "$(x+3)(x-1)$"], [0, 1, 2]));
  q.push(ms("hard", "Steps to solve by factoring:", ["set $=0$", "factor fully", "apply zero product", "solve each factor"], [0, 1, 2, 3]));
  q.push(tf("hard", "To solve $(x-1)(x+2)=4$ you must first expand and set it to $0$.", true));
  q.push(tf("hard", "$9x^2-1=0$ gives $x=\\pm1/3$.", true));
  q.push(tf("hard", "A product equal to $4$ means a factor equals $4$.", false));
  q.push(fill("hard", "Solve $(x+1)(x-2)=4$: $x=$ ___.", ["3 and -2", "3,-2", "-2,3"]));
  q.push(fill("hard", "Solve $2x^2+x-15=0$: $x=$ ___.", ["5/2 and -3", "5/2,-3", "-3,5/2"]));
  q.push(fill("hard", "Solve $6x^2-7x-3=0$: $x=$ ___.", ["3/2 and -1/3", "3/2,-1/3"]));
  q.push(num("hard", "The number of distinct real solutions of $x^2-6x+9=0$ is ___.", 1, 0));
  q.push(num("hard", "The positive solution of $9x^2-1=0$ (decimal) is ___.", 0.333, 0.01));
  q.push(num("hard", "The larger solution of $(x+1)(x-2)=4$ is ___.", 3, 0));
  q.push(order("hard", "Order the steps to solve a quadratic by factoring.", ["Set the equation to $0$", "Factor fully", "Set each factor to $0$", "Solve for $x$"]));
  q.push(match("hard", "Match each equation to its solutions.", ["$(x-1)(x+2)=4$", "$2x^2+x-15=0$", "$9x^2-1=0$"], ["$-3,2$", "$5/2,-3$", "$\\pm1/3$"], [0, 1, 2]));
  return q;
}

// ── 5.2 Completing the Square ────────────────────────────────
function g52() {
  const q = [];
  q.push(mc("easy", "To complete the square for $x^2+6x$, add:", ["$9$", "$6$", "$3$", "$36$"], 0));
  q.push(mc("easy", "$x^2+6x+9=$", ["$(x+3)^2$", "$(x+6)^2$", "$(x+9)^2$", "$(x-3)^2$"], 0));
  q.push(mc("easy", "To complete $x^2+bx$, add:", ["$(b/2)^2$", "$b/2$", "$b^2$", "$2b$"], 0));
  q.push(mc("easy", "$x^2-4x+4=$", ["$(x-2)^2$", "$(x+2)^2$", "$(x-4)^2$", "$(x-2)$"], 0));
  q.push(mc("easy", "Solve $(x-3)^2=4$.", ["$5,1$", "$7,-1$", "$3,4$", "$2,4$"], 0));
  q.push(mc("easy", "First step solving $x^2+6x+5=0$ by completing the square:", ["move 5: $x^2+6x=-5$", "factor", "graph", "divide"], 0));
  q.push(ms("easy", "Completing $x^2+8x$:", ["add $16$", "gives $(x+4)^2$", "$(8/2)^2=16$", "add $8$"], [0, 1, 2]));
  q.push(ms("easy", "Which are perfect-square trinomials?", ["$x^2+6x+9$", "$x^2-4x+4$", "$x^2+10x+25$", "$x^2+5x+6$"], [0, 1, 2]));
  q.push(ms("easy", "To solve by completing the square:", ["isolate the constant", "add $(b/2)^2$ to both sides", "write the square", "take $\\pm\\sqrt{}$"], [0, 1, 2, 3]));
  q.push(ms("easy", "$(x+3)^2=4$ gives:", ["$x+3=\\pm2$", "$x=-1$", "$x=-5$", "$x=1$"], [0, 1, 2]));
  q.push(tf("easy", "To complete the square for $x^2+bx$, add $(b/2)^2$.", true));
  q.push(tf("easy", "$x^2+6x+9=(x+3)^2$.", true));
  q.push(tf("easy", "Solving $(x-3)^2=4$ gives only $x=5$.", false));
  q.push(fill("easy", "To complete $x^2+10x$, add ___.", ["25"]));
  q.push(fill("easy", "$x^2-8x+16=$ ___.", ["(x-4)^2", "(x-4)²"]));
  q.push(fill("easy", "Solve $(x-2)^2=9$: $x=$ ___.", ["5 and -1", "5,-1", "-1,5"]));
  q.push(num("easy", "To complete $x^2+12x$, add ___.", 36, 0));
  q.push(num("easy", "Solve $(x+1)^2=16$: the positive solution is ___.", 3, 0));
  q.push(num("easy", "The number to complete $x^2-6x$ is ___.", 9, 0));
  q.push(match("easy", "Match each to the number that completes the square.", ["$x^2+6x$", "$x^2+10x$", "$x^2-4x$"], ["$9$", "$25$", "$4$"], [0, 1, 2]));
  q.push(mc("medium", "Solve $x^2+6x+5=0$.", ["$-1,-5$", "$1,5$", "$-1,5$", "$-6,5$"], 0));
  q.push(mc("medium", "Solve $x^2-4x-1=0$.", ["$2\\pm\\sqrt5$", "$2\\pm\\sqrt3$", "$-2\\pm\\sqrt5$", "$4\\pm\\sqrt5$"], 0));
  q.push(mc("medium", "Solve $x^2-8x+12=0$.", ["$6,2$", "$-6,-2$", "$6,-2$", "$4,3$"], 0));
  q.push(mc("medium", "Solve $x^2+2x-5=0$.", ["$-1\\pm\\sqrt6$", "$1\\pm\\sqrt6$", "$-1\\pm\\sqrt5$", "$-2\\pm\\sqrt6$"], 0));
  q.push(mc("medium", "Write $y=x^2+4x+1$ in vertex form:", ["$(x+2)^2-3$", "$(x+2)^2+3$", "$(x-2)^2-3$", "$(x+2)^2-5$"], 0));
  q.push(mc("medium", "Solve $2x^2-12x+10=0$.", ["$5,1$", "$-5,-1$", "$6,2$", "$5,-1$"], 0));
  q.push(ms("medium", "Solving $x^2+6x+5=0$:", ["$x^2+6x=-5$", "$(x+3)^2=4$", "$x=-1$", "$x=-5$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Which have irrational solutions?", ["$x^2-4x-1=0$", "$x^2+2x-5=0$", "$x^2-8x+12=0$", "$x^2-2x-2=0$"], [0, 1, 3]));
  q.push(ms("medium", "Completing the square stays balanced by:", ["adding to both sides", "forming a perfect square", "then square-rooting", "ignoring one side"], [0, 1, 2]));
  q.push(ms("medium", "$(x-2)^2=5$ gives:", ["$x-2=\\pm\\sqrt5$", "$x=2+\\sqrt5$", "$x=2-\\sqrt5$", "$x=5$"], [0, 1, 2]));
  q.push(tf("medium", "$x^2-4x-1=0$ has solutions $2\\pm\\sqrt5$.", true));
  q.push(tf("medium", "To solve $2x^2-12x+10=0$, divide by 2 first.", true));
  q.push(tf("medium", "$x^2+2x-5=0$ has rational solutions.", false));
  q.push(fill("medium", "Solve $x^2+8x+7=0$: $x=$ ___.", ["-1 and -7", "-1,-7", "-7,-1"]));
  q.push(fill("medium", "Solve $x^2-10x+21=0$: $x=$ ___.", ["7 and 3", "7,3", "3,7"]));
  q.push(fill("medium", "Write $y=x^2+6x+5$ in vertex form: $y=$ ___.", ["(x+3)^2-4", "(x+3)²-4"]));
  q.push(num("medium", "To complete the square for $x^2+8x+7=0$ (after moving 7), add ___.", 16, 0));
  q.push(num("medium", "The larger solution of $x^2-8x+12=0$ is ___.", 6, 0));
  q.push(num("medium", "In $(x+3)^2=k$ from $x^2+6x+2=0$, $k=$ ___.", 7, 0));
  q.push(match("medium", "Match each equation to its solutions.", ["$x^2+6x+5=0$", "$x^2-8x+12=0$", "$x^2-2x-2=0$"], ["$-1,-5$", "$6,2$", "$1\\pm\\sqrt3$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $x^2-6x+7=0$.", ["$3\\pm\\sqrt2$", "$3\\pm\\sqrt7$", "$-3\\pm\\sqrt2$", "$6\\pm\\sqrt2$"], 0));
  q.push(mc("hard", "Solve $x^2+10x+18=0$.", ["$-5\\pm\\sqrt7$", "$5\\pm\\sqrt7$", "$-5\\pm\\sqrt5$", "$-10\\pm\\sqrt7$"], 0));
  q.push(mc("hard", "Solve $3x^2-12x+9=0$ (divide first).", ["$3,1$", "$-3,-1$", "$3,-1$", "$4,3$"], 0));
  q.push(mc("hard", "Solve $x^2-2x-2=0$.", ["$1\\pm\\sqrt3$", "$-1\\pm\\sqrt3$", "$1\\pm\\sqrt2$", "$2\\pm\\sqrt3$"], 0));
  q.push(mc("hard", "Write $y=2x^2-8x+1$ in vertex form:", ["$2(x-2)^2-7$", "$2(x-2)^2+7$", "$2(x-2)^2-9$", "$(x-2)^2-7$"], 0));
  q.push(ms("hard", "Solving $x^2-6x+7=0$:", ["$x^2-6x=-7$", "$(x-3)^2=2$", "$x=3+\\sqrt2$", "$x=3-\\sqrt2$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which give two irrational roots?", ["$x^2-6x+7=0$", "$x^2+10x+18=0$", "$x^2-8x+12=0$", "$x^2-2x-2=0$"], [0, 1, 3]));
  q.push(ms("hard", "For $2x^2-12x+10=0$:", ["divide by $2$", "$x^2-6x+5=0$", "$(x-3)^2=4$", "$x=5,1$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Completing the square can:", ["solve any quadratic", "produce vertex form", "handle irrational roots", "only handle perfect factors"], [0, 1, 2]));
  q.push(tf("hard", "$x^2-6x+7=0$ has solutions $3\\pm\\sqrt2$.", true));
  q.push(tf("hard", "Completing the square works even when factoring fails.", true));
  q.push(tf("hard", "$3x^2-12x+9=0$ has irrational solutions.", false));
  q.push(fill("hard", "Solve $x^2-6x+7=0$: $x=$ ___.", ["3±√2", "3\\pm\\sqrt2", "3 + √2 and 3 - √2"]));
  q.push(fill("hard", "Solve $x^2+6x+2=0$: $x=$ ___.", ["-3±√7", "-3\\pm\\sqrt7"]));
  q.push(fill("hard", "Write $y=2x^2-8x+1$ in vertex form: $y=$ ___.", ["2(x-2)^2-7", "2(x-2)²-7"]));
  q.push(num("hard", "In $(x-3)^2=k$ from $x^2-6x+7=0$, $k=$ ___.", 2, 0));
  q.push(num("hard", "The larger solution of $3x^2-12x+9=0$ is ___.", 3, 0));
  q.push(num("hard", "To complete the square for $x^2+10x+18=0$ (after moving 18), add ___.", 25, 0));
  q.push(order("hard", "Order the steps to solve by completing the square.", ["Make the leading coefficient 1", "Move the constant to the right", "Add $(b/2)^2$ to both sides", "Take $\\pm$ square root and solve"]));
  q.push(match("hard", "Match each equation to its solutions.", ["$x^2-6x+7=0$", "$x^2+10x+18=0$", "$3x^2-12x+9=0$"], ["$3\\pm\\sqrt2$", "$-5\\pm\\sqrt7$", "$3,1$"], [0, 1, 2]));
  return q;
}

// ── 5.3 The Quadratic Formula ────────────────────────────────
function g53() {
  const q = [];
  q.push(mc("easy", "The quadratic formula is $x=$", ["$\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}$", "$\\frac{b\\pm\\sqrt{b^2-4ac}}{2a}$", "$\\frac{-b\\pm\\sqrt{b^2+4ac}}{2a}$", "$\\frac{-b\\pm\\sqrt{b^2-4ac}}{a}$"], 0));
  q.push(mc("easy", "For $x^2-5x+6=0$, $(a,b,c)=$", ["$(1,-5,6)$", "$(1,5,6)$", "$(-1,5,6)$", "$(1,-5,-6)$"], 0));
  q.push(mc("easy", "Solve $x^2-5x+6=0$ with the formula:", ["$3,2$", "$-3,-2$", "$1,6$", "$5,6$"], 0));
  q.push(mc("easy", "The discriminant is:", ["$b^2-4ac$", "$b^2+4ac$", "$-b/2a$", "$\\sqrt{b^2-4ac}$"], 0));
  q.push(mc("easy", "Solve $x^2+3x-10=0$.", ["$2,-5$", "$-2,5$", "$5,2$", "$-5,-2$"], 0));
  q.push(mc("easy", "In $2x^2-7x+3=0$, $a=$", ["$2$", "$-7$", "$3$", "$1$"], 0));
  q.push(ms("easy", "To use the formula you need:", ["$a$", "$b$", "$c$", "the vertex"], [0, 1, 2]));
  q.push(ms("easy", "For $x^2-5x+6=0$:", ["$a=1$", "$b=-5$", "$c=6$", "$b=5$"], [0, 1, 2]));
  q.push(ms("easy", "Which are solved by the quadratic formula?", ["$x^2-5x+6=0$", "$2x^2-7x+3=0$", "$x^2+3x-10=0$", "$2x+1=0$"], [0, 1, 2]));
  q.push(ms("easy", "The $\\pm$ in the formula gives:", ["two solutions usually", "one if the discriminant is $0$", "none if the discriminant is $<0$", "always three"], [0, 1, 2]));
  q.push(tf("easy", "The quadratic formula solves any quadratic.", true));
  q.push(tf("easy", "The discriminant is $b^2-4ac$.", true));
  q.push(tf("easy", "The formula uses $+b$ in the numerator.", false));
  q.push(fill("easy", "Solve $x^2-3x+2=0$: $x=$ ___.", ["1 and 2", "1,2", "2,1"]));
  q.push(fill("easy", "Solve $x^2+5x+6=0$: $x=$ ___.", ["-2 and -3", "-2,-3", "-3,-2"]));
  q.push(fill("easy", "For $3x^2-2x-1=0$, $(a,b,c)=$ ___.", ["3,-2,-1", "3, -2, -1"]));
  q.push(num("easy", "For $x^2-5x+6=0$, the discriminant is ___.", 1, 0));
  q.push(num("easy", "The larger solution of $x^2-5x+6=0$ is ___.", 3, 0));
  q.push(num("easy", "For $2x^2-7x+3=0$, $a\\cdot c=$ ___.", 6, 0));
  q.push(match("easy", "Match each equation to its $(a,b,c)$.", ["$x^2-5x+6=0$", "$2x^2-7x+3=0$", "$x^2+3x-10=0$"], ["$(1,-5,6)$", "$(2,-7,3)$", "$(1,3,-10)$"], [0, 1, 2]));
  q.push(mc("medium", "Solve $2x^2-7x+3=0$.", ["$3,1/2$", "$-3,1/2$", "$3,-1/2$", "$1/2,1/3$"], 0));
  q.push(mc("medium", "Solve $x^2-2x-1=0$.", ["$1\\pm\\sqrt2$", "$-1\\pm\\sqrt2$", "$2\\pm\\sqrt2$", "$1\\pm\\sqrt3$"], 0));
  q.push(mc("medium", "Solve $3x^2+5x-2=0$.", ["$1/3,-2$", "$-1/3,2$", "$3,-2$", "$1/3,2$"], 0));
  q.push(mc("medium", "Solve $x^2+4x+1=0$.", ["$-2\\pm\\sqrt3$", "$2\\pm\\sqrt3$", "$-2\\pm\\sqrt5$", "$-4\\pm\\sqrt3$"], 0));
  q.push(mc("medium", "Solve $x^2-6x+9=0$.", ["$3$", "$3,-3$", "$9$", "$0,3$"], 0));
  q.push(mc("medium", "The discriminant of $x^2-2x-1=0$ is:", ["$8$", "$4$", "$0$", "$-8$"], 0));
  q.push(ms("medium", "For $2x^2-7x+3=0$ via the formula:", ["$D=25$", "$\\sqrt{25}=5$", "$x=(7\\pm5)/4$", "$x=3$ or $1/2$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Which have irrational solutions?", ["$x^2-2x-1=0$", "$x^2+4x+1=0$", "$x^2-5x+6=0$", "$2x^2-7x+3=0$"], [0, 1]));
  q.push(ms("medium", "The number of solutions depends on:", ["the discriminant", "$b^2-4ac$", "its sign", "the constant $c$ alone"], [0, 1, 2]));
  q.push(ms("medium", "Solve $3x^2+5x-2=0$:", ["$D=49$", "$x=(-5\\pm7)/6$", "$x=1/3$", "$x=-2$"], [0, 1, 2, 3]));
  q.push(tf("medium", "$x^2-2x-1=0$ has solutions $1\\pm\\sqrt2$.", true));
  q.push(tf("medium", "$x^2-6x+9=0$ has one (double) solution.", true));
  q.push(tf("medium", "A negative discriminant gives two real solutions.", false));
  q.push(fill("medium", "Solve $2x^2-5x+2=0$: $x=$ ___.", ["2 and 1/2", "2,1/2", "1/2,2"]));
  q.push(fill("medium", "Solve $x^2-4x+2=0$: $x=$ ___.", ["2±√2", "2\\pm\\sqrt2"]));
  q.push(fill("medium", "Solve $x^2+x-1=0$: $x=$ ___.", ["(-1±√5)/2", "\\frac{-1\\pm\\sqrt5}{2}"]));
  q.push(num("medium", "The discriminant of $x^2-2x-1=0$ is ___.", 8, 0));
  q.push(num("medium", "The discriminant of $2x^2-7x+3=0$ is ___.", 25, 0));
  q.push(num("medium", "The larger solution of $2x^2-7x+3=0$ is ___.", 3, 0));
  q.push(match("medium", "Match each equation to its solutions.", ["$2x^2-7x+3=0$", "$x^2-2x-1=0$", "$3x^2+5x-2=0$"], ["$3,1/2$", "$1\\pm\\sqrt2$", "$1/3,-2$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $5x^2-3x-1=0$.", ["$\\frac{3\\pm\\sqrt{29}}{10}$", "$\\frac{-3\\pm\\sqrt{29}}{10}$", "$\\frac{3\\pm\\sqrt{11}}{10}$", "$\\frac{3\\pm\\sqrt{29}}{5}$"], 0));
  q.push(mc("hard", "Solve $2x^2+3x-1=0$.", ["$\\frac{-3\\pm\\sqrt{17}}{4}$", "$\\frac{3\\pm\\sqrt{17}}{4}$", "$\\frac{-3\\pm\\sqrt{1}}{4}$", "$\\frac{-3\\pm\\sqrt{17}}{2}$"], 0));
  q.push(mc("hard", "Solve $3x^2+4x-2=0$.", ["$\\frac{-2\\pm\\sqrt{10}}{3}$", "$\\frac{-4\\pm\\sqrt{10}}{3}$", "$\\frac{-2\\pm\\sqrt{10}}{6}$", "$\\frac{2\\pm\\sqrt{10}}{3}$"], 0));
  q.push(mc("hard", "Solve $4x^2-4x+1=0$.", ["$1/2$", "$\\pm1/2$", "$1/2,-1/2$", "$2$"], 0));
  q.push(mc("hard", "Solve $x^2-2x-5=0$.", ["$1\\pm\\sqrt6$", "$-1\\pm\\sqrt6$", "$1\\pm\\sqrt5$", "$2\\pm\\sqrt6$"], 0));
  q.push(ms("hard", "For $5x^2-3x-1=0$:", ["$a=5,b=-3,c=-1$", "$D=9+20=29$", "$x=\\frac{3\\pm\\sqrt{29}}{10}$", "$D=29$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which simplify to a nicer radical?", ["$x^2-2x-1=0\\Rightarrow1\\pm\\sqrt2$", "$x^2+4x+1=0\\Rightarrow-2\\pm\\sqrt3$", "$3x^2+4x-2=0\\Rightarrow\\frac{-2\\pm\\sqrt{10}}{3}$", "none simplify"], [0, 1, 2]));
  q.push(ms("hard", "A perfect-square discriminant means:", ["rational solutions", "the quadratic is factorable", "two nice roots", "irrational roots"], [0, 1, 2]));
  q.push(ms("hard", "The quadratic-formula steps:", ["identify $a,b,c$", "compute $b^2-4ac$", "substitute", "simplify"], [0, 1, 2, 3]));
  q.push(tf("hard", "$5x^2-3x-1=0$ has solutions $\\frac{3\\pm\\sqrt{29}}{10}$.", true));
  q.push(tf("hard", "$4x^2-4x+1=0$ has a double root $1/2$.", true));
  q.push(tf("hard", "$3x^2+4x-2=0$ has rational solutions.", false));
  q.push(fill("hard", "Solve $2x^2+3x-1=0$: $x=$ ___.", ["(-3±√17)/4", "\\frac{-3\\pm\\sqrt{17}}{4}"]));
  q.push(fill("hard", "Solve $x^2-2x-5=0$: $x=$ ___.", ["1±√6", "1\\pm\\sqrt6"]));
  q.push(fill("hard", "Solve $3x^2+4x-2=0$: $x=$ ___.", ["(-2±√10)/3", "\\frac{-2\\pm\\sqrt{10}}{3}"]));
  q.push(num("hard", "The discriminant of $5x^2-3x-1=0$ is ___.", 29, 0));
  q.push(num("hard", "The discriminant of $3x^2+4x-2=0$ is ___.", 40, 0));
  q.push(num("hard", "The double root of $4x^2-4x+1=0$ (decimal) is ___.", 0.5, 0));
  q.push(order("hard", "Order the quadratic-formula steps.", ["Identify $a$, $b$, $c$", "Compute $b^2-4ac$", "Substitute into the formula", "Simplify the radical"]));
  q.push(match("hard", "Match each equation to its solutions.", ["$5x^2-3x-1=0$", "$2x^2+3x-1=0$", "$x^2-2x-5=0$"], ["$\\frac{3\\pm\\sqrt{29}}{10}$", "$\\frac{-3\\pm\\sqrt{17}}{4}$", "$1\\pm\\sqrt6$"], [0, 1, 2]));
  return q;
}

// ── 5.4 The Discriminant & the Number of Roots ───────────────
function g54() {
  const q = [];
  q.push(mc("easy", "The discriminant is:", ["$b^2-4ac$", "$b^2+4ac$", "$-b/2a$", "$2a$"], 0));
  q.push(mc("easy", "If $D>0$:", ["two real roots", "one root", "no real roots", "three roots"], 0));
  q.push(mc("easy", "If $D=0$:", ["one (double) root", "two roots", "no roots", "four"], 0));
  q.push(mc("easy", "If $D<0$:", ["no real roots", "one root", "two roots", "infinite"], 0));
  q.push(mc("easy", "For $x^2-5x+6=0$, $D=$", ["$1$", "$-1$", "$49$", "$0$"], 0));
  q.push(mc("easy", "For $x^2-4x+4=0$, $D=$", ["$0$", "$16$", "$4$", "$-16$"], 0));
  q.push(ms("easy", "The discriminant tells you:", ["the number of real roots", "$D>0$ two roots", "$D=0$ one root", "the exact roots"], [0, 1, 2]));
  q.push(ms("easy", "Which have two real roots ($D>0$)?", ["$x^2-5x+6$", "$x^2-4x+1$", "$x^2+x+1$", "$x^2-4x+4$"], [0, 1]));
  q.push(ms("easy", "$D=0$ means:", ["one repeated root", "a perfect-square trinomial", "vertex on the $x$-axis", "two distinct roots"], [0, 1, 2]));
  q.push(ms("easy", "Which have no real roots?", ["$x^2+x+1=0$", "$x^2+4=0$", "$x^2-5x+6=0$", "$x^2+2x+5=0$"], [0, 1, 3]));
  q.push(tf("easy", "$D=b^2-4ac$.", true));
  q.push(tf("easy", "$D<0$ means no real roots.", true));
  q.push(tf("easy", "$D=0$ gives two distinct roots.", false));
  q.push(fill("easy", "For $x^2-6x+5=0$, $D=$ ___.", ["16"]));
  q.push(fill("easy", "For $x^2-4x+4=0$, $D=$ ___.", ["0"]));
  q.push(fill("easy", "If $D<0$, there are ___ real roots.", ["no", "0", "zero"]));
  q.push(num("easy", "For $x^2-5x+6=0$, $D=$ ___.", 1, 0));
  q.push(num("easy", "The number of real roots when $D=0$ is ___.", 1, 0));
  q.push(num("easy", "For $x^2+2x+5=0$, $D=$ ___.", -16, 0));
  q.push(match("easy", "Match each sign of $D$ to the number of real roots.", ["$D>0$", "$D=0$", "$D<0$"], ["two", "one", "none"], [0, 1, 2]));
  q.push(mc("medium", "Describe the roots of $2x^2-3x-5=0$ ($D=49$):", ["two rational", "two irrational", "one", "none"], 0));
  q.push(mc("medium", "Describe the roots of $x^2-2x-1=0$ ($D=8$):", ["two irrational", "two rational", "one", "none"], 0));
  q.push(mc("medium", "Find $k$ so $x^2+kx+9=0$ has one root:", ["$\\pm6$", "$6$", "$\\pm3$", "$9$"], 0));
  q.push(mc("medium", "Find $k$ so $x^2-4x+k=0$ has two real roots:", ["$k<4$", "$k>4$", "$k=4$", "$k<0$"], 0));
  q.push(mc("medium", "Find $k$ so $x^2+2x+k=0$ has no real roots:", ["$k>1$", "$k<1$", "$k=1$", "$k>0$"], 0));
  q.push(mc("medium", "How many real roots does $9x^2-12x+4=0$ have?", ["one", "two", "none", "three"], 0));
  q.push(ms("medium", "For $2x^2-3x-5=0$:", ["$D=49$", "a perfect square", "two rational roots", "factorable"], [0, 1, 2, 3]));
  q.push(ms("medium", "Which have exactly one real root?", ["$x^2-4x+4=0$", "$9x^2-12x+4=0$", "$x^2-5x+6=0$", "$(x-3)^2=0$"], [0, 1, 3]));
  q.push(ms("medium", "To find $k$ for one root, set:", ["$D=0$", "$b^2-4ac=0$", "solve for $k$", "$D>0$"], [0, 1, 2]));
  q.push(ms("medium", "Which have no real roots?", ["$x^2+x+1=0$", "$3x^2+x+1=0$", "$x^2-2x-2=0$", "$x^2+2x+5=0$"], [0, 1, 3]));
  q.push(tf("medium", "A perfect-square discriminant gives rational roots.", true));
  q.push(tf("medium", "$x^2-4x+4=0$ has one repeated root.", true));
  q.push(tf("medium", "$D=8$ gives rational roots.", false));
  q.push(fill("medium", "Find $k$ so $x^2+kx+4=0$ has one root: $k=$ ___.", ["±4", "4 and -4", "\\pm4"]));
  q.push(fill("medium", "Find $k$ so $x^2-6x+k=0$ has two roots: $k$ ___.", ["<9", "k<9"]));
  q.push(fill("medium", "Find $k$ so $x^2+4x+k=0$ has no roots: $k$ ___.", [">4", "k>4"]));
  q.push(num("medium", "For $2x^2-3x-5=0$, $D=$ ___.", 49, 0));
  q.push(num("medium", "The value of $k$ giving one root for $x^2-6x+k=0$ is ___.", 9, 0));
  q.push(num("medium", "For $x^2-2x-2=0$, $D=$ ___.", 12, 0));
  q.push(match("medium", "Match each equation to its root description.", ["$2x^2-3x-5=0$", "$x^2-2x-1=0$", "$x^2+x+1=0$"], ["two rational", "two irrational", "no real roots"], [0, 1, 2]));
  q.push(mc("hard", "Find $k$ so $2x^2+kx+8=0$ has one root:", ["$\\pm8$", "$8$", "$\\pm4$", "$16$"], 0));
  q.push(mc("hard", "Find $k$ so $kx^2-4x+1=0$ has one root:", ["$4$", "$2$", "$1$", "$16$"], 0));
  q.push(mc("hard", "For $x^2+kx+9=0$ to have two real roots:", ["$|k|>6$", "$|k|<6$", "$k=6$", "$k>0$"], 0));
  q.push(mc("hard", "The roots of $9x^2-6x+1=0$ are:", ["one root $1/3$", "two roots", "irrational", "none"], 0));
  q.push(mc("hard", "For $3x^2+kx+3=0$ to have no real roots:", ["$|k|<6$", "$|k|>6$", "$k=6$", "$k<0$"], 0));
  q.push(ms("hard", "For one real root you need:", ["$D=0$", "the vertex on the axis", "$b^2=4ac$", "$D>0$"], [0, 1, 2]));
  q.push(ms("hard", "Which have two distinct real roots?", ["$x^2-5x+6$", "$2x^2-3x-5$", "$x^2-2x-2$", "$x^2+x+1$"], [0, 1, 2]));
  q.push(ms("hard", "For $2x^2+kx+8=0$ to have one root:", ["$D=k^2-64$", "set $D=0$", "$k=\\pm8$", "$k=8$ only"], [0, 1, 2]));
  q.push(ms("hard", "The discriminant determines:", ["the number of real roots", "whether factorable (perfect square)", "rational vs irrational", "the vertex location"], [0, 1, 2]));
  q.push(tf("hard", "$2x^2+kx+8=0$ has one root when $k=\\pm8$.", true));
  q.push(tf("hard", "If $D$ is positive but not a perfect square, the roots are irrational.", true));
  q.push(tf("hard", "$kx^2-4x+1=0$ has one root when $k=2$.", false));
  q.push(fill("hard", "Find $k$ so $2x^2+kx+8=0$ has exactly one root: $k=$ ___.", ["±8", "8 and -8", "\\pm8"]));
  q.push(fill("hard", "Find $k$ so $kx^2-4x+1=0$ has one root: $k=$ ___.", ["4"]));
  q.push(fill("hard", "For $3x^2+kx+3=0$ to have no real roots: $|k|$ ___.", ["<6", "less than 6"]));
  q.push(num("hard", "For $2x^2+kx+8=0$ to have one root, $|k|=$ ___.", 8, 0));
  q.push(num("hard", "For $kx^2-4x+1=0$ to have one root, $k=$ ___.", 4, 0));
  q.push(num("hard", "The discriminant of $9x^2-6x+1=0$ is ___.", 0, 0));
  q.push(order("hard", "Order the steps to find $k$ for exactly one real root.", ["Write the discriminant $b^2-4ac$", "Set it equal to $0$", "Substitute the coefficients (with $k$)", "Solve for $k$"]));
  q.push(match("hard", "Match each condition to the discriminant requirement.", ["one real root", "two real roots", "no real roots"], ["$D=0$", "$D>0$", "$D<0$"], [0, 1, 2]));
  return q;
}

// ── 5.5 Quadratic Word Problems ──────────────────────────────
function g55() {
  const q = [];
  q.push(mc("easy", "A rectangle's length is $3$ more than its width, area $40$: the equation is $w(w+3)=$", ["$40$", "$3$", "$43$", "$120$"], 0));
  q.push(mc("easy", "Two consecutive integers with product $56$: $n(n+1)=$", ["$56$", "$57$", "$55$", "$112$"], 0));
  q.push(mc("easy", "Projectile $h=-5t^2+20t$ hits the ground when $h=$", ["$0$", "$20$", "$5$", "$-5$"], 0));
  q.push(mc("easy", "To solve a word problem, first:", ["define a variable", "graph it", "guess", "add the numbers"], 0));
  q.push(mc("easy", "'A number plus its square is $30$' becomes:", ["$x^2+x=30$", "$x^2-x=30$", "$2x=30$", "$x^2=30$"], 0));
  q.push(mc("easy", "After solving, you should reject:", ["impossible answers (e.g. negative length)", "the larger root always", "the smaller root", "nothing"], 0));
  q.push(ms("easy", "Quadratic word problems include:", ["areas", "projectiles", "consecutive integers", "linear pricing only"], [0, 1, 2]));
  q.push(ms("easy", "For 'length 3 more, area 40':", ["$w(w+3)=40$", "$w^2+3w-40=0$", "$(w+8)(w-5)=0$", "$w=5$"], [0, 1, 2, 3]));
  q.push(ms("easy", "A projectile lands when:", ["height $=0$", "$h=0$", "you solve $h(t)=0$", "at the vertex"], [0, 1, 2]));
  q.push(ms("easy", "Steps for a quadratic word problem:", ["define a variable", "write an equation", "solve", "check / reject"], [0, 1, 2, 3]));
  q.push(tf("easy", "A projectile is at ground level when its height is $0$.", true));
  q.push(tf("easy", "You may reject a negative length as a solution.", true));
  q.push(tf("easy", "Every algebraic solution must be accepted in context.", false));
  q.push(fill("easy", "Two consecutive integers with product $56$ are ___.", ["7 and 8", "7,8", "8,7"]));
  q.push(fill("easy", "A rectangle length 3 more than width, area 40: the width is ___.", ["5"]));
  q.push(fill("easy", "$h=-5t^2+20t$ lands at $t=$ ___ s (nonzero).", ["4"]));
  q.push(num("easy", "The width of a rectangle with $w(w+3)=40$ is ___.", 5, 0));
  q.push(num("easy", "The smaller of two consecutive integers with product $56$ is ___.", 7, 0));
  q.push(num("easy", "$h=-5t^2+20t$ hits the ground at $t=$ ___ s.", 4, 0));
  q.push(match("easy", "Match each problem to its equation.", ["length 3 more, area 40", "consecutive integers product 56", "projectile lands"], ["$w(w+3)=40$", "$n(n+1)=56$", "$h(t)=0$"], [0, 1, 2]));
  q.push(mc("medium", "A rectangle length $2$ more than width, area $35$: the width is", ["$5$", "$7$", "$6$", "$4$"], 0));
  q.push(mc("medium", "Two consecutive integers with product $72$:", ["$8,9$", "$7,8$", "$9,10$", "$6,12$"], 0));
  q.push(mc("medium", "$h=-5t^2+15t$ lands at $t=$", ["$3$", "$5$", "$15$", "$0$"], 0));
  q.push(mc("medium", "The maximum height of $h=-5t^2+20t$:", ["$20$", "$15$", "$25$", "$10$"], 0));
  q.push(mc("medium", "'A number plus its square is $30$':", ["$5$ or $-6$", "$5$ only", "$6$", "$-5$ or $6$"], 0));
  q.push(mc("medium", "A right triangle: legs differ by $7$, hypotenuse $17$. The legs are:", ["$8,15$", "$5,12$", "$9,12$", "$8,17$"], 0));
  q.push(ms("medium", "For 'length 2 more, area 35':", ["$w(w+2)=35$", "$w^2+2w-35=0$", "$(w+7)(w-5)=0$", "$w=5$"], [0, 1, 2, 3]));
  q.push(ms("medium", "For $h=-5t^2+20t$:", ["lands at $t=4$", "max at $t=2$", "max height 20", "linear"], [0, 1, 2]));
  q.push(ms("medium", "Which require rejecting a root?", ["a negative length", "a negative time", "a fractional count of people", "a positive dimension"], [0, 1, 2]));
  q.push(ms("medium", "For two numbers differ by 4, product 45:", ["$x(x+4)=45$", "$x^2+4x-45=0$", "$(x+9)(x-5)=0$", "$x=5$"], [0, 1, 2, 3]));
  q.push(tf("medium", "The maximum height of a projectile occurs at the vertex.", true));
  q.push(tf("medium", "$h=-5t^2+15t$ lands at $t=3$ s.", true));
  q.push(tf("medium", "A projectile's maximum height occurs when it lands.", false));
  q.push(fill("medium", "Two consecutive integers with product $72$ are ___.", ["8 and 9", "8,9", "9,8"]));
  q.push(fill("medium", "The maximum height of $h=-5t^2+20t$ is ___ m.", ["20"]));
  q.push(fill("medium", "Two numbers differ by 4 with product 45: the numbers are ___.", ["5 and 9", "5,9", "9,5"]));
  q.push(num("medium", "The width of a rectangle with $w(w+2)=35$ is ___.", 5, 0));
  q.push(num("medium", "$h=-5t^2+15t$ lands at $t=$ ___ s.", 3, 0));
  q.push(num("medium", "The longer leg of the right triangle (legs differ by 7, hyp 17) is ___.", 15, 0));
  q.push(match("medium", "Match each scenario to its answer.", ["length 2 more, area 35", "consec. integers product 72", "legs differ 7, hyp 17"], ["$w=5$", "8 and 9", "8 and 15"], [0, 1, 2]));
  q.push(mc("hard", "$h=-5t^2+25t+30$ lands at $t=$", ["$6$", "$5$", "$3$", "$7$"], 0));
  q.push(mc("hard", "The maximum height of $h=-5t^2+25t+30$:", ["$61.25$", "$30$", "$55$", "$45$"], 0));
  q.push(mc("hard", "A rectangle length $3\\times$ width, area $48$: the width is", ["$4$", "$8$", "$6$", "$3$"], 0));
  q.push(mc("hard", "A ball $h=-5t^2+20t+25$ lands at $t=$", ["$5$", "$4$", "$3$", "$25$"], 0));
  q.push(mc("hard", "Two consecutive even integers with product $48$:", ["$6,8$", "$8,10$", "$4,12$", "$6,12$"], 0));
  q.push(ms("hard", "For $h=-5t^2+25t+30$:", ["lands at $t=6$", "max at $t=2.5$", "$h(0)=30$", "opens up"], [0, 1, 2]));
  q.push(ms("hard", "Which model with a quadratic?", ["projectile motion", "rectangular area", "product of consecutive integers", "simple interest (linear)"], [0, 1, 2]));
  q.push(ms("hard", "For 'rectangle length $3\\times$ width, area 48':", ["$w(3w)=48$", "$3w^2=48$", "$w^2=16$", "$w=4$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Solving a projectile's landing time:", ["set $h=0$", "solve the quadratic", "reject negative $t$", "take the vertex time"], [0, 1, 2]));
  q.push(tf("hard", "$h=-5t^2+25t+30$ reaches maximum height at $t=2.5$ s.", true));
  q.push(tf("hard", "For area problems, the negative root is rejected.", true));
  q.push(tf("hard", "$h=-5t^2+20t+25$ lands at $t=4$ s.", false));
  q.push(fill("hard", "$h=-5t^2+25t+30$ lands at $t=$ ___ s.", ["6"]));
  q.push(fill("hard", "The maximum height of $h=-5t^2+25t+30$ is ___ m.", ["61.25"]));
  q.push(fill("hard", "A rectangle length $3\\times$ width, area 48: the dimensions are ___.", ["4 by 12", "4 and 12", "4x12", "4×12"]));
  q.push(num("hard", "$h=-5t^2+20t+25$ lands at $t=$ ___ s.", 5, 0));
  q.push(num("hard", "The width of a rectangle with $3w^2=48$ is ___.", 4, 0));
  q.push(num("hard", "The maximum height of $h=-5t^2+30t$ is ___ m.", 45, 0));
  q.push(order("hard", "Order the steps to solve a quadratic word problem.", ["Define a variable", "Write a quadratic equation", "Solve it", "Reject invalid roots and state the answer"]));
  q.push(match("hard", "Match each model to its result.", ["$h=-5t^2+25t+30$ lands", "rectangle $3w^2=48$", "consec. even product 48"], ["$t=6$ s", "$w=4$", "6 and 8"], [0, 1, 2]));
  return q;
}

// ── 5.6 Linear–Quadratic Systems ─────────────────────────────
function g56() {
  const q = [];
  q.push(mc("easy", "A line and a parabola can meet at:", ["0, 1, or 2 points", "exactly 1", "exactly 2", "3 points"], 0));
  q.push(mc("easy", "To solve, set the two expressions:", ["equal", "to zero only", "to the vertex", "to the slope"], 0));
  q.push(mc("easy", "Solve $y=x^2$, $y=x+2$.", ["$(2,4),(-1,1)$", "$(2,4)$", "$(-1,1)$", "none"], 0));
  q.push(mc("easy", "If the combined quadratic has $D=0$, the line is:", ["tangent", "a secant", "a miss", "vertical"], 0));
  q.push(mc("easy", "Solve $y=x^2$, $y=4$.", ["$(\\pm2,4)$", "$(2,4)$", "$(4,16)$", "$(0,4)$"], 0));
  q.push(mc("easy", "After substituting, you solve a:", ["quadratic equation", "linear equation", "system of 3", "cubic"], 0));
  q.push(ms("easy", "To solve a linear-quadratic system:", ["set them equal", "solve the quadratic", "find each $y$", "check the discriminant"], [0, 1, 2, 3]));
  q.push(ms("easy", "The number of intersections can be:", ["2 (secant)", "1 (tangent)", "0 (miss)", "4"], [0, 1, 2]));
  q.push(ms("easy", "For $y=x^2$, $y=x+2$:", ["$x^2=x+2$", "$x^2-x-2=0$", "$(x-2)(x+1)=0$", "$x=2,-1$"], [0, 1, 2, 3]));
  q.push(ms("easy", "The combined discriminant tells:", ["secant if $D>0$", "tangent if $D=0$", "miss if $D<0$", "the slope"], [0, 1, 2]));
  q.push(tf("easy", "A tangent line meets a parabola at exactly one point.", true));
  q.push(tf("easy", "Substitution turns the system into one quadratic.", true));
  q.push(tf("easy", "A line always crosses a parabola twice.", false));
  q.push(fill("easy", "Solve $y=x^2$, $y=x+6$: the $x$-values are ___.", ["3 and -2", "3,-2", "-2,3"]));
  q.push(fill("easy", "Solve $y=x^2$, $y=4$: $x=$ ___.", ["±2", "2 and -2", "\\pm2"]));
  q.push(fill("easy", "A $D=0$ combined equation means the line is ___ to the parabola.", ["tangent"]));
  q.push(num("easy", "The number of intersection points when $D=0$ is ___.", 1, 0));
  q.push(num("easy", "For $y=x^2$, $y=x+2$, the positive $x$-solution is ___.", 2, 0));
  q.push(num("easy", "For $y=x^2$, $y=9$, the positive $x$ is ___.", 3, 0));
  q.push(match("easy", "Match each discriminant to the line's relation.", ["$D>0$", "$D=0$", "$D<0$"], ["secant (2 points)", "tangent (1 point)", "misses (0 points)"], [0, 1, 2]));
  q.push(mc("medium", "Solve $y=x^2-2$, $y=x$.", ["$(2,2),(-1,-1)$", "$(2,2)$", "$(-1,-1)$", "none"], 0));
  q.push(mc("medium", "Solve $y=x^2$, $y=2x-1$.", ["$(1,1)$ tangent", "$(1,1),(-1,1)$", "none", "$(2,3)$"], 0));
  q.push(mc("medium", "Solve $y=x^2-4$, $y=x-2$.", ["$(2,0),(-1,-3)$", "$(2,0)$", "$(-1,-3)$", "none"], 0));
  q.push(mc("medium", "Solve $y=x^2+2$, $y=x-1$.", ["no intersection", "$(1,0)$", "two points", "$(-1,-2)$"], 0));
  q.push(mc("medium", "Solve $y=2x^2$, $y=x+1$.", ["$(1,2),(-1/2,1/2)$", "$(1,2)$", "$(-1/2,1/2)$", "none"], 0));
  q.push(mc("medium", "Solve $y=x^2-2x$, $y=3$.", ["$(3,3),(-1,3)$", "$(3,3)$", "$(-1,3)$", "none"], 0));
  q.push(ms("medium", "For $y=x^2$, $y=x+2$:", ["$x^2-x-2=0$", "$x=2,-1$", "points $(2,4),(-1,1)$", "tangent"], [0, 1, 2]));
  q.push(ms("medium", "Which systems have no intersection?", ["$y=x^2+2$, $y=x-1$", "$y=x^2+5$, $y=x$", "$y=x^2$, $y=4$", "$y=x^2$, $y=x+2$"], [0, 1]));
  q.push(ms("medium", "A tangent system:", ["$D=0$", "one solution", "perfect-square quadratic", "two solutions"], [0, 1, 2]));
  q.push(ms("medium", "To find each $y$:", ["substitute the $x$ back", "use either equation", "report $(x,y)$", "ignore $y$"], [0, 1, 2]));
  q.push(tf("medium", "$y=x^2$ and $y=2x-1$ are tangent at $(1,1)$.", true));
  q.push(tf("medium", "$y=x^2+2$ and $y=x-1$ have no intersection.", true));
  q.push(tf("medium", "Every linear-quadratic system has two solutions.", false));
  q.push(fill("medium", "Solve $y=x^2-4x$, $y=-3$: the points are ___.", ["(1,-3) and (3,-3)", "(1,-3),(3,-3)"]));
  q.push(fill("medium", "Solve $y=2x^2$, $y=x+3$: the $x$-values are ___.", ["3/2 and -1", "3/2,-1", "-1,3/2"]));
  q.push(fill("medium", "Solve $y=x^2-1$, $y=3x-3$: the $x$-values are ___.", ["1 and 2", "1,2", "2,1"]));
  q.push(num("medium", "For $y=x^2-2$, $y=x$, the positive $x$ is ___.", 2, 0));
  q.push(num("medium", "For $y=x^2+5$, $y=x$, the number of intersections is ___.", 0, 0));
  q.push(num("medium", "For $y=x^2-2x$, $y=3$, the larger $x$ is ___.", 3, 0));
  q.push(match("medium", "Match each system to its solution.", ["$y=x^2-2,\\ y=x$", "$y=x^2,\\ y=2x-1$", "$y=x^2+2,\\ y=x-1$"], ["$(2,2),(-1,-1)$", "$(1,1)$ tangent", "no intersection"], [0, 1, 2]));
  q.push(mc("hard", "For what $k$ is $y=kx$ tangent to $y=x^2+2$?", ["$\\pm2\\sqrt2$", "$\\pm2$", "$\\pm\\sqrt2$", "$2$"], 0));
  q.push(mc("hard", "Solve $y=x^2-3x+2$, $y=x-1$.", ["$(1,0),(3,2)$", "$(1,0)$", "$(3,2)$", "none"], 0));
  q.push(mc("hard", "Solve $y=-x^2+4$, $y=x+2$.", ["$(-2,0),(1,3)$", "$(-2,0)$", "$(1,3)$", "none"], 0));
  q.push(mc("hard", "For what $k$ does $y=x+k$ touch $y=x^2$ once?", ["$-1/4$", "$1/4$", "$0$", "$-1$"], 0));
  q.push(mc("hard", "Solve $y=x^2+3x$, $y=-2$.", ["$(-1,-2),(-2,-2)$", "$(-1,-2)$", "$(-2,-2)$", "none"], 0));
  q.push(ms("hard", "For $y=kx$ tangent to $y=x^2+2$:", ["$x^2-kx+2=0$", "$D=k^2-8$", "set $D=0$", "$k=\\pm2\\sqrt2$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which systems are tangent (one solution)?", ["$y=x^2$, $y=2x-1$", "$y=x^2+x$, $y=-x-1$", "$y=x^2$, $y=x+2$", "$y=x^2-2x+1$, $y=0$"], [0, 1, 3]));
  q.push(ms("hard", "To classify intersections, use:", ["the combined quadratic's discriminant", "$D>0$ two", "$D=0$ one", "$D<0$ none"], [0, 1, 2, 3]));
  q.push(ms("hard", "For $y=x^2-3x+2$, $y=x-1$:", ["$x^2-4x+3=0$", "$(x-1)(x-3)=0$", "$x=1,3$", "points $(1,0),(3,2)$"], [0, 1, 2, 3]));
  q.push(tf("hard", "$y=kx$ is tangent to $y=x^2+2$ when $k=\\pm2\\sqrt2$.", true));
  q.push(tf("hard", "The combined equation's discriminant classifies the intersection.", true));
  q.push(tf("hard", "$y=x+k$ touches $y=x^2$ once when $k=1/4$.", false));
  q.push(fill("hard", "For $y=kx$ tangent to $y=x^2+2$, $k=$ ___.", ["±2√2", "\\pm2\\sqrt2", "2√2 and -2√2"]));
  q.push(fill("hard", "Solve $y=x^2-3x+2$, $y=x-1$: the points are ___.", ["(1,0) and (3,2)", "(1,0),(3,2)"]));
  q.push(fill("hard", "For $y=x+k$ to touch $y=x^2$ once, $k=$ ___.", ["-1/4", "-0.25"]));
  q.push(num("hard", "For $y=x^2$, $y=x+2$, the smaller $x$ is ___.", -1, 0));
  q.push(num("hard", "The number of intersections of $y=x^2+5$ and $y=x$ is ___.", 0, 0));
  q.push(num("hard", "For $y=x^2-3x+2$, $y=x-1$, the larger $x$ is ___.", 3, 0));
  q.push(order("hard", "Order the steps to solve a linear-quadratic system.", ["Set the two expressions equal", "Rearrange to a quadratic $=0$", "Solve for $x$", "Substitute back to find $y$"]));
  q.push(match("hard", "Match each system to its intersection count.", ["$y=x^2,\\ y=2x-1$", "$y=x^2,\\ y=x+2$", "$y=x^2+5,\\ y=x$"], ["one (tangent)", "two", "none"], [0, 1, 2]));
  return q;
}

export default [
  { code: "5.1", gen: g51 },
  { code: "5.2", gen: g52 },
  { code: "5.3", gen: g53 },
  { code: "5.4", gen: g54 },
  { code: "5.5", gen: g55 },
  { code: "5.6", gen: g56 },
];
