// MPM2D Unit 6 — Trigonometry of Right Triangles: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "./helpers.mjs";

// ── 6.1 Congruence & Similar Triangles ───────────────────────
function g61() {
  const q = [];
  q.push(mc("easy", "Similar triangles have:", ["equal angles, proportional sides", "equal sides only", "equal angles only", "nothing in common"], 0));
  q.push(mc("easy", "Congruent triangles have a scale factor of:", ["$1$", "$2$", "$0$", "any"], 0));
  q.push(mc("easy", "Two equal angles prove triangles similar by:", ["AA", "colour", "area", "perimeter"], 0));
  q.push(mc("easy", "If $\\triangle ABC\\sim\\triangle DEF$ with $AB=4$, $DE=8$, the scale factor ($D{:}A$) is:", ["$2$", "$1/2$", "$4$", "$8$"], 0));
  q.push(mc("easy", "Two triangles with angles $40^\\circ,60^\\circ,80^\\circ$ each are:", ["similar", "congruent only", "not similar", "right"], 0));
  q.push(mc("easy", "The symbol $\\sim$ means:", ["similar", "congruent", "equal", "parallel"], 0));
  q.push(ms("easy", "Similar triangles have:", ["equal corresponding angles", "proportional sides", "a constant scale factor", "equal areas"], [0, 1, 2]));
  q.push(ms("easy", "Ways to prove triangles similar:", ["AA", "SSS (proportional)", "SAS", "colour"], [0, 1, 2]));
  q.push(ms("easy", "If the sides are $3,4,5$ and $6,8,10$:", ["ratio $1{:}2$", "all ratios equal", "they are similar", "they are congruent"], [0, 1, 2]));
  q.push(ms("easy", "To find a missing side in similar triangles:", ["set up a proportion", "cross-multiply", "match corresponding sides", "add the sides"], [0, 1, 2]));
  q.push(tf("easy", "Similar triangles have proportional corresponding sides.", true));
  q.push(tf("easy", "Congruent triangles are similar with scale factor $1$.", true));
  q.push(tf("easy", "Similar triangles must have equal areas.", false));
  q.push(fill("easy", "Solve $\\frac{2}{5}=\\frac{8}{x}$: $x=$ ___.", ["20"]));
  q.push(fill("easy", "The scale factor from $3,4,5$ to $6,8,10$ is ___.", ["2"]));
  q.push(fill("easy", "Triangles with all corresponding angles equal are ___.", ["similar"]));
  q.push(num("easy", "Solve $\\frac{3}{4}=\\frac{x}{8}$: $x=$ ___.", 6, 0));
  q.push(num("easy", "The scale factor from $5,12,13$ to $10,24,26$ is ___.", 2, 0));
  q.push(num("easy", "Solve $\\frac{4}{6}=\\frac{x}{9}$: $x=$ ___.", 6, 0));
  q.push(match("easy", "Match each similarity test to its meaning.", ["AA", "SSS", "SAS"], ["two equal angles", "three proportional sides", "two sides and the included angle"], [0, 1, 2]));
  q.push(mc("medium", "$\\triangle ABC\\sim\\triangle DEF$, $AB=6$, $DE=9$, $DF=15$. Find $AC$.", ["$10$", "$12$", "$9$", "$15$"], 0));
  q.push(mc("medium", "Solve $\\frac{3}{7}=\\frac{12}{x}$:", ["$28$", "$21$", "$16$", "$36$"], 0));
  q.push(mc("medium", "A $1.5$ m person casts a $2$ m shadow; a tree casts $16$ m. Tree height:", ["$12$", "$10$", "$8$", "$24$"], 0));
  q.push(mc("medium", "Two similar triangles, ratio $2{:}3$, $AB=8$. Find $PQ$:", ["$12$", "$16$", "$6$", "$24$"], 0));
  q.push(mc("medium", "Scale factor from $4,7,9$ to $12,21,27$:", ["$3$", "$2$", "$4$", "$1/3$"], 0));
  q.push(mc("medium", "$\\triangle ABC\\sim\\triangle PQR$, ratio $3{:}5$, perimeter $ABC=24$. Perimeter $PQR$:", ["$40$", "$36$", "$30$", "$48$"], 0));
  q.push(ms("medium", "For $\\triangle ABC\\sim\\triangle DEF$, $AB=4$, $DE=6$:", ["corresponding sides proportional", "corresponding angles equal", "$\\frac{AB}{DE}=\\frac{2}{3}$", "areas equal"], [0, 1, 2]));
  q.push(ms("medium", "Which pairs are similar?", ["$3,4,5$ \\& $6,8,10$", "$5,12,13$ \\& $10,24,26$", "$2,3,4$ \\& $4,6,8$", "$3,4,5$ \\& $6,8,9$"], [0, 1, 2]));
  q.push(ms("medium", "Solving $\\frac{a}{b}=\\frac{c}{d}$:", ["cross-multiply $ad=bc$", "isolate the unknown", "match corresponding parts", "add the fractions"], [0, 1, 2]));
  q.push(ms("medium", "A shadow problem uses:", ["proportional heights and shadows", "similar triangles", "$\\frac{h_1}{s_1}=\\frac{h_2}{s_2}$", "the Pythagorean theorem only"], [0, 1, 2]));
  q.push(tf("medium", "All corresponding side ratios of similar triangles are equal.", true));
  q.push(tf("medium", "The perimeters of similar triangles share the scale factor.", true));
  q.push(tf("medium", "A scale factor of $1$ means the triangles are different sizes.", false));
  q.push(fill("medium", "$\\triangle ABC\\sim\\triangle DEF$, $AB=6$, $DE=9$, $DF=15$: $AC=$ ___.", ["10"]));
  q.push(fill("medium", "A $1.8$ m person casts $3$ m shadow; pole casts $25$ m. Pole height = ___ m.", ["15"]));
  q.push(fill("medium", "Solve $\\frac{x}{6}=\\frac{10}{4}$: $x=$ ___.", ["15"]));
  q.push(num("medium", "Solve $\\frac{3}{7}=\\frac{12}{x}$: $x=$ ___.", 28, 0));
  q.push(num("medium", "Two similar triangles have perimeters $12$ and $18$; the scale factor (larger:smaller) is ___.", 1.5, 0));
  q.push(num("medium", "A $3,4,5$ triangle is scaled so its longest side is $20$; the scale factor is ___.", 4, 0));
  q.push(match("medium", "Match each pair to its scale factor.", ["$3,4,5$ to $6,8,10$", "$4,7,9$ to $12,21,27$", "$5,12,13$ to $10,24,26$"], ["$2$", "$3$", "$2$"], [0, 1, 2]));
  q.push(mc("hard", "$\\triangle ABC\\sim\\triangle DEF$ ratio $4{:}7$, perimeter $DEF=42$. Perimeter $ABC$:", ["$24$", "$42$", "$28$", "$21$"], 0));
  q.push(mc("hard", "A $2$ m person's $2.5$ m shadow reaches a tree's shadow tip; person $12$ m from tree. Tree height:", ["$11.6$", "$12$", "$10$", "$14.5$"], 0));
  q.push(mc("hard", "Mirror method: eyes $1.6$ m, $2$ m from mirror, tree $6$ m beyond. Tree height:", ["$4.8$", "$6$", "$3.2$", "$9.6$"], 0));
  q.push(mc("hard", "Two similar triangles with scale factor $3$ have area ratio:", ["$9$", "$3$", "$6$", "$1/3$"], 0));
  q.push(mc("hard", "$\\triangle ABC\\sim\\triangle DEF$, ratio $3{:}5$, $AB=12$. Find $DE$:", ["$20$", "$15$", "$9$", "$36$"], 0));
  q.push(ms("hard", "For $\\triangle ABC\\sim\\triangle DEF$ ratio $4{:}7$:", ["perimeters ratio $4{:}7$", "each side $ABC=\\frac{4}{7}$ of $DEF$", "area ratio $16{:}49$", "sides ratio $7{:}4$"], [0, 1, 2]));
  q.push(ms("hard", "Which use similar triangles?", ["shadow heights", "mirror reflection", "map scales", "coin counts"], [0, 1, 2]));
  q.push(ms("hard", "If the scale factor is $k$:", ["sides scale by $k$", "perimeter scales by $k$", "area scales by $k^2$", "angles stay equal"], [0, 1, 2, 3]));
  q.push(ms("hard", "To find a tree's height by shadows:", ["$\\frac{h_{p}}{s_{p}}=\\frac{h_{t}}{s_{t}}$", "cross-multiply", "solve for $h_{t}$", "measure the angle"], [0, 1, 2]));
  q.push(tf("hard", "If the scale factor is $3$, the area ratio is $9$.", true));
  q.push(tf("hard", "Corresponding angles of similar triangles are equal.", true));
  q.push(tf("hard", "Doubling the sides doubles the area.", false));
  q.push(fill("hard", "$\\triangle ABC\\sim\\triangle DEF$ ratio $4{:}7$, perimeter $DEF=42$: perimeter $ABC=$ ___.", ["24"]));
  q.push(fill("hard", "A person $2$ m tall, $2.5$ m shadow, $12$ m from a tree (shadows align): tree height = ___ m.", ["11.6"]));
  q.push(fill("hard", "If the scale factor is $3$, the area scales by ___.", ["9"]));
  q.push(num("hard", "$\\triangle ABC\\sim\\triangle DEF$ ratio $4{:}7$, perimeter $DEF=42$: perimeter $ABC=$ ___.", 24, 0));
  q.push(num("hard", "Mirror method $\\frac{1.6}{2}=\\frac{h}{6}$: $h=$ ___.", 4.8, 0));
  q.push(num("hard", "If the scale factor is $5$, the area ratio is ___.", 25, 0));
  q.push(order("hard", "Order the steps to find a missing side with similar triangles.", ["Match corresponding sides", "Write a proportion", "Cross-multiply", "Solve for the unknown"]));
  q.push(match("hard", "Match each scale factor to its area ratio.", ["$2$", "$3$", "$4$"], ["$4$", "$9$", "$16$"], [0, 1, 2]));
  return q;
}

// ── 6.2 Solving Problems with Similar Triangles ──────────────
function g62() {
  const q = [];
  q.push(mc("easy", "A $1.8$ m person, $3$ m shadow; building $30$ m shadow. Height:", ["$18$", "$20$", "$15$", "$10$"], 0));
  q.push(mc("easy", "On a $1{:}50000$ map, $4$ cm apart; real distance:", ["$2$ km", "$200$ m", "$20$ km", "$2$ m"], 0));
  q.push(mc("easy", "A $1$ m stick, $1.5$ m shadow; pole $9$ m shadow. Pole height:", ["$6$", "$9$", "$4.5$", "$12$"], 0));
  q.push(mc("easy", "Shadow problems compare:", ["height to shadow", "area to volume", "slope to length", "angle to side"], 0));
  q.push(mc("easy", "A $1{:}20$ model is $22$ cm long. Real length:", ["$440$ cm", "$20$ cm", "$2.2$ cm", "$11$ cm"], 0));
  q.push(mc("easy", "To set up a shadow proportion:", ["$\\frac{h_1}{s_1}=\\frac{h_2}{s_2}$", "$h_1 s_1=h_2 s_2$", "$h_1+s_1=h_2+s_2$", "$h_1-s_1=h_2-s_2$"], 0));
  q.push(ms("easy", "Indirect measurement uses:", ["shadows", "mirrors", "maps / scales", "guessing"], [0, 1, 2]));
  q.push(ms("easy", "A map scale $1{:}50000$ means:", ["$1$ cm $=50000$ cm", "$1$ unit $=50000$ units", "the real distance is larger", "$1$ cm $=0.5$ km"], [0, 1, 2, 3]));
  q.push(ms("easy", "For a shadow problem you need:", ["a known height", "its shadow length", "the unknown's shadow", "the temperature"], [0, 1, 2]));
  q.push(ms("easy", "Solving the proportion:", ["cross-multiply", "isolate the unknown", "keep units consistent", "add the heights"], [0, 1, 2]));
  q.push(tf("easy", "Map scales use proportions (similar triangles).", true));
  q.push(tf("easy", "At the same time, a taller object casts a longer shadow.", true));
  q.push(tf("easy", "Shadow length and height are inversely proportional.", false));
  q.push(fill("easy", "A $1.8$ m person, $3$ m shadow; building $30$ m shadow: height = ___ m.", ["18"]));
  q.push(fill("easy", "Map $1{:}50000$, $4$ cm = ___ km.", ["2"]));
  q.push(fill("easy", "A $1$ m stick, $1.5$ m shadow; pole $9$ m shadow: pole = ___ m.", ["6"]));
  q.push(num("easy", "A $2$ m post, $3$ m shadow; tower $45$ m shadow: height = ___ m.", 30, 0));
  q.push(num("easy", "Map $1{:}25000$, $6$ cm = ___ km.", 1.5, 0));
  q.push(num("easy", "A $1{:}50$ model is $30$ cm tall; real height = ___ m.", 15, 0));
  q.push(match("easy", "Match each scenario to its answer.", ["$1.8$ m / $3$ m shadow, $30$ m shadow", "map $1{:}50000$, $4$ cm", "$1{:}20$ model, $22$ cm"], ["$18$ m", "$2$ km", "$440$ cm"], [0, 1, 2]));
  q.push(mc("medium", "A $1.5$ m person, $2.5$ m shadow; tree $20$ m shadow. Height:", ["$12$", "$10$", "$8$", "$15$"], 0));
  q.push(mc("medium", "Mirror: $\\frac{1.7}{1.5}=\\frac{h}{9}$. Tree height:", ["$10.2$", "$9$", "$8.5$", "$11.3$"], 0));
  q.push(mc("medium", "River width $\\frac{w}{40}=\\frac{15}{20}$:", ["$30$", "$20$", "$45$", "$60$"], 0));
  q.push(mc("medium", "Map $1{:}100000$, $7.5$ cm =", ["$7.5$ km", "$750$ m", "$75$ km", "$0.75$ km"], 0));
  q.push(mc("medium", "A $1{:}50$ model is $30$ cm; real height:", ["$15$ m", "$150$ cm", "$1.5$ m", "$3$ m"], 0));
  q.push(mc("medium", "A $2$ m post, $3$ m shadow; tower $45$ m shadow. Height:", ["$30$", "$40$", "$15$", "$60$"], 0));
  q.push(ms("medium", "To solve a shadow word problem:", ["define the proportion", "cross-multiply", "keep units consistent", "draw a diagram"], [0, 1, 2, 3]));
  q.push(ms("medium", "Which give $12$ m?", ["$\\frac{1.5}{2.5}=\\frac{h}{20}$", "$\\frac{1.8}{3}=\\frac{h}{20}$", "$\\frac{3}{5}=\\frac{h}{20}$", "$\\frac{2}{4}=\\frac{h}{20}$"], [0, 1, 2]));
  q.push(ms("medium", "Map-scale problems:", ["multiply map distance by the scale", "convert units", "$1{:}n$ means real $=n\\times$ map", "the real distance is smaller"], [0, 1, 2]));
  q.push(ms("medium", "The mirror method assumes:", ["similar triangles", "equal incidence/reflection angles", "proportional heights", "random heights"], [0, 1, 2]));
  q.push(tf("medium", "On a $1{:}25000$ map, $6$ cm represents $1.5$ km.", true));
  q.push(tf("medium", "The mirror method relies on similar triangles.", true));
  q.push(tf("medium", "A $1{:}50$ scale model is bigger than the real object.", false));
  q.push(fill("medium", "A $1.5$ m person, $2.5$ m shadow; tree $20$ m shadow: height = ___ m.", ["12"]));
  q.push(fill("medium", "River width $\\frac{w}{50}=\\frac{12}{30}$: $w=$ ___ m.", ["20"]));
  q.push(fill("medium", "Map $1{:}100000$, $7.5$ cm = ___ km.", ["7.5"]));
  q.push(num("medium", "A $1.6$ m person, $2$ m shadow; flagpole $14$ m shadow: height = ___ m.", 11.2, 0));
  q.push(num("medium", "River width $\\frac{w}{40}=\\frac{15}{20}$: $w=$ ___ m.", 30, 0));
  q.push(num("medium", "A $1{:}50$ model is $30$ cm tall; real height = ___ cm.", 1500, 0));
  q.push(match("medium", "Match each problem to its answer.", ["$1.5$ m / $2.5$ m, $20$ m shadow", "river $\\frac{w}{40}=\\frac{15}{20}$", "map $1{:}100000$, $7.5$ cm"], ["$12$ m", "$30$ m", "$7.5$ km"], [0, 1, 2]));
  q.push(mc("hard", "A $2$ m person, $2.5$ m shadow reaches a tree's shadow tip; person $12$ m from tree. Tree height:", ["$11.6$", "$12$", "$10$", "$14.5$"], 0));
  q.push(mc("hard", "A $1.8$ m person, $2.4$ m shadow, $15$ m from a tree (shadows align). Tree:", ["$13.05$", "$15$", "$11.6$", "$17.4$"], 0));
  q.push(mc("hard", "Two similar triangles have area ratio $9{:}16$. Side ratio:", ["$3{:}4$", "$9{:}16$", "$81{:}256$", "$3{:}16$"], 0));
  q.push(mc("hard", "A $5\\times7$ photo enlarged by factor $4$. New dimensions:", ["$20\\times28$", "$9\\times11$", "$1.25\\times1.75$", "$20\\times7$"], 0));
  q.push(mc("hard", "A flagpole's shadow is $14$ m when a $1.6$ m person's shadow is $2$ m. Height:", ["$11.2$", "$14$", "$8.75$", "$12$"], 0));
  q.push(ms("hard", "When shadows align at one point:", ["the tree's shadow $=$ person distance $+$ person's shadow", "set up one proportion", "use similar triangles", "measure the sun"], [0, 1, 2]));
  q.push(ms("hard", "Area and length scaling:", ["area ratio $=$ (side ratio)$^2$", "side ratio $=\\sqrt{\\text{area ratio}}$", "$9{:}16$ areas $\\to 3{:}4$ sides", "areas scale linearly"], [0, 1, 2]));
  q.push(ms("hard", "Map conversions:", ["multiply by the scale", "convert cm to km", "$1{:}n\\to$ real $=n\\times$ map", "divide by the scale"], [0, 1, 2]));
  q.push(ms("hard", "Indirect-measurement methods include:", ["shadows", "mirrors", "scale models / maps", "a stopwatch"], [0, 1, 2]));
  q.push(tf("hard", "Area ratio $9{:}16$ means side ratio $3{:}4$.", true));
  q.push(tf("hard", "Enlarging a $5\\times7$ photo by factor $4$ gives $20\\times28$.", true));
  q.push(tf("hard", "Area scales the same way as length.", false));
  q.push(fill("hard", "A $2$ m person, $2.5$ m shadow, $12$ m from tree (aligned): tree height = ___ m.", ["11.6"]));
  q.push(fill("hard", "Two similar triangles with area ratio $9{:}16$ have side ratio ___.", ["3:4", "3/4"]));
  q.push(fill("hard", "A $5\\times7$ photo enlarged $\\times4$ becomes ___.", ["20 by 28", "20×28", "20x28"]));
  q.push(num("hard", "A $1.8$ m person, $2.4$ m shadow, $15$ m from tree (aligned): tree height = ___ m.", 13.05, 0.05));
  q.push(num("hard", "Side ratio for area ratio $25{:}36$ is $5{:}$ ___.", 6, 0));
  q.push(num("hard", "Real length of a $1{:}50$ model $22$ cm long = ___ cm.", 1100, 0));
  q.push(order("hard", "Order the steps for a shadow problem with aligned shadow tips.", ["Find the total shadow length", "Set up the proportion height:shadow", "Cross-multiply", "Solve for the tree's height"]));
  q.push(match("hard", "Match each area ratio to its side ratio.", ["$9{:}16$", "$4{:}9$", "$25{:}36$"], ["$3{:}4$", "$2{:}3$", "$5{:}6$"], [0, 1, 2]));
  return q;
}

// ── 6.3 The Primary Trigonometric Ratios ─────────────────────
function g63() {
  const q = [];
  q.push(mc("easy", "SOH means $\\sin\\theta=$", ["$\\frac{opp}{hyp}$", "$\\frac{adj}{hyp}$", "$\\frac{opp}{adj}$", "$\\frac{hyp}{opp}$"], 0));
  q.push(mc("easy", "CAH means $\\cos\\theta=$", ["$\\frac{adj}{hyp}$", "$\\frac{opp}{hyp}$", "$\\frac{opp}{adj}$", "$\\frac{adj}{opp}$"], 0));
  q.push(mc("easy", "TOA means $\\tan\\theta=$", ["$\\frac{opp}{adj}$", "$\\frac{opp}{hyp}$", "$\\frac{adj}{hyp}$", "$\\frac{hyp}{opp}$"], 0));
  q.push(mc("easy", "In a $3$-$4$-$5$ triangle ($\\theta$ opp $3$), $\\sin\\theta=$", ["$3/5$", "$4/5$", "$3/4$", "$5/3$"], 0));
  q.push(mc("easy", "The hypotenuse is:", ["opposite the right angle", "the shortest side", "adjacent to $\\theta$", "the base"], 0));
  q.push(mc("easy", "If opp $=5$, hyp $=13$, then $\\sin\\theta=$", ["$5/13$", "$13/5$", "$12/13$", "$5/12$"], 0));
  q.push(ms("easy", "The primary ratios are:", ["sine", "cosine", "tangent", "secant"], [0, 1, 2]));
  q.push(ms("easy", "For a $3$-$4$-$5$ triangle ($\\theta$ opp $3$):", ["$\\sin\\theta=3/5$", "$\\cos\\theta=4/5$", "$\\tan\\theta=3/4$", "$\\sin\\theta=4/5$"], [0, 1, 2]));
  q.push(ms("easy", "Relative to $\\theta$, label the:", ["opposite", "adjacent", "hypotenuse", "diagonal"], [0, 1, 2]));
  q.push(ms("easy", "$\\tan\\theta$ uses:", ["the opposite", "the adjacent", "not the hypotenuse", "the hypotenuse"], [0, 1, 2]));
  q.push(tf("easy", "$\\sin\\theta=\\frac{opp}{hyp}$.", true));
  q.push(tf("easy", "The hypotenuse is opposite the right angle.", true));
  q.push(tf("easy", "$\\cos\\theta=\\frac{opp}{hyp}$.", false));
  q.push(fill("easy", "If opp $=5$, hyp $=13$, $\\sin\\theta=$ ___.", ["5/13"]));
  q.push(fill("easy", "If adj $=8$, hyp $=17$, $\\cos\\theta=$ ___.", ["8/17"]));
  q.push(fill("easy", "If opp $=7$, adj $=24$, $\\tan\\theta=$ ___.", ["7/24"]));
  q.push(num("easy", "For a $6$-$8$-$10$ triangle ($\\theta$ opp $6$), $\\sin\\theta$ as a decimal = ___.", 0.6, 0));
  q.push(num("easy", "For a $3$-$4$-$5$ triangle ($\\theta$ opp $4$), $\\cos\\theta$ as a decimal = ___.", 0.6, 0));
  q.push(num("easy", "For legs $3$ and $4$, the hypotenuse = ___.", 5, 0));
  q.push(match("easy", "Match each ratio to its definition.", ["$\\sin\\theta$", "$\\cos\\theta$", "$\\tan\\theta$"], ["$\\frac{opp}{hyp}$", "$\\frac{adj}{hyp}$", "$\\frac{opp}{adj}$"], [0, 1, 2]));
  q.push(mc("medium", "For $5$-$12$-$13$ ($\\theta$ opp $5$), $\\cos\\theta=$", ["$12/13$", "$5/13$", "$5/12$", "$13/12$"], 0));
  q.push(mc("medium", "For $5$-$12$-$13$ ($\\theta$ opp $5$), $\\tan\\theta=$", ["$5/12$", "$12/5$", "$5/13$", "$13/5$"], 0));
  q.push(mc("medium", "If $\\tan\\theta=3/4$, then $\\sin\\theta=$", ["$3/5$", "$4/5$", "$3/4$", "$5/3$"], 0));
  q.push(mc("medium", "Legs $3,4$: $\\sin\\theta$ ($\\theta$ opp $3$) =", ["$3/5$", "$4/5$", "$3/4$", "$5/4$"], 0));
  q.push(mc("medium", "opp $=7$, hyp $=25$: $\\cos\\theta=$ (find adj first)", ["$24/25$", "$7/25$", "$7/24$", "$25/24$"], 0));
  q.push(mc("medium", "For $8$-$15$-$17$ ($\\alpha$ opp $8$), $\\tan\\alpha=$", ["$8/15$", "$15/8$", "$8/17$", "$15/17$"], 0));
  q.push(ms("medium", "For $5$-$12$-$13$ ($\\theta$ opp $5$):", ["$\\sin\\theta=5/13$", "$\\cos\\theta=12/13$", "$\\tan\\theta=5/12$", "$\\sin\\theta=12/13$"], [0, 1, 2]));
  q.push(ms("medium", "If $\\sin\\theta=8/17$:", ["adj $=15$", "$\\cos\\theta=15/17$", "$\\tan\\theta=8/15$", "$\\cos\\theta=8/17$"], [0, 1, 2]));
  q.push(ms("medium", "Trig ratios depend on:", ["the angle", "not the triangle's size", "similar triangles share them", "the position on the page"], [0, 1, 2]));
  q.push(ms("medium", "For a $6$-$8$-$10$ triangle ($\\theta$ opp $6$):", ["$\\sin\\theta=3/5$", "$\\cos\\theta=4/5$", "$\\tan\\theta=3/4$", "$\\sin\\theta=4/5$"], [0, 1, 2]));
  q.push(tf("medium", "For $5$-$12$-$13$ ($\\theta$ opp $5$), $\\tan\\theta=5/12$.", true));
  q.push(tf("medium", "In a right triangle, if $\\sin\\theta=3/5$ then $\\cos\\theta=4/5$.", true));
  q.push(tf("medium", "Trig ratios change with the size of a similar triangle.", false));
  q.push(fill("medium", "For $5$-$12$-$13$ ($\\theta$ opp $5$), $\\cos\\theta=$ ___.", ["12/13"]));
  q.push(fill("medium", "For $7$-$24$-$25$ ($\\theta$ opp $7$), $\\tan\\theta=$ ___.", ["7/24"]));
  q.push(fill("medium", "If $\\sin\\theta=8/17$, $\\cos\\theta=$ ___.", ["15/17"]));
  q.push(num("medium", "For $8$-$15$-$17$ ($\\alpha$ opp $8$), $\\sin\\alpha$ (2 dp) = ___.", 0.47, 0.01));
  q.push(num("medium", "For $20$-$21$-$29$ ($\\theta$ opp $20$), $\\sin\\theta$ (2 dp) = ___.", 0.69, 0.01));
  q.push(num("medium", "If adj $=24$ and opp $=7$, the hypotenuse = ___.", 25, 0));
  q.push(match("medium", "Match each ratio ($5$-$12$-$13$, $\\theta$ opp $5$) to its value.", ["$\\sin\\theta$", "$\\cos\\theta$", "$\\tan\\theta$"], ["$5/13$", "$12/13$", "$5/12$"], [0, 1, 2]));
  q.push(mc("hard", "For $9$-$40$-$41$ ($\\alpha$ opp $9$), $\\cos\\alpha=$", ["$40/41$", "$9/41$", "$9/40$", "$41/40$"], 0));
  q.push(mc("hard", "If $\\cos\\theta=5/13$, then $\\tan\\theta=$", ["$12/5$", "$5/12$", "$12/13$", "$13/5$"], 0));
  q.push(mc("hard", "For $8$-$15$-$17$, the $\\tan$ of the two acute angles are:", ["$8/15$ and $15/8$", "$8/17$ and $15/17$", "$8/15$ and $17/15$", "$15/8$ and $17/8$"], 0));
  q.push(mc("hard", "If $\\tan\\theta=2$, then $\\sin\\theta=$", ["$\\frac{2}{\\sqrt5}$", "$\\frac{1}{\\sqrt5}$", "$\\frac{\\sqrt5}{2}$", "$\\frac{2}{3}$"], 0));
  q.push(mc("hard", "For $20$-$21$-$29$ ($\\theta$ opp $21$), $\\cos\\theta=$", ["$20/29$", "$21/29$", "$20/21$", "$29/20$"], 0));
  q.push(ms("hard", "For $9$-$40$-$41$ ($\\alpha$ opp $9$):", ["$\\sin\\alpha=9/41$", "$\\cos\\alpha=40/41$", "$\\tan\\alpha=9/40$", "$\\sin\\alpha=40/41$"], [0, 1, 2]));
  q.push(ms("hard", "If $\\cos\\theta=5/13$:", ["opp $=12$", "$\\sin\\theta=12/13$", "$\\tan\\theta=12/5$", "$\\sin\\theta=5/13$"], [0, 1, 2]));
  q.push(ms("hard", "For the two acute angles, the ratios:", ["swap opp/adj", "$\\sin$ of one $=\\cos$ of the other", "the angles are complementary", "are identical"], [0, 1, 2]));
  q.push(ms("hard", "To find one ratio from another:", ["use the Pythagorean theorem for the third side", "then apply SOH CAH TOA", "keep it a right triangle", "measure the angle"], [0, 1, 2]));
  q.push(tf("hard", "In a right triangle, $\\sin$ of one acute angle equals $\\cos$ of the other.", true));
  q.push(tf("hard", "If $\\tan\\theta=2$, the opposite:adjacent ratio is $2{:}1$.", true));
  q.push(tf("hard", "$\\sin\\theta$ can exceed $1$ in a right triangle.", false));
  q.push(fill("hard", "For $9$-$40$-$41$ ($\\alpha$ opp $9$), $\\tan\\alpha=$ ___.", ["9/40"]));
  q.push(fill("hard", "If $\\cos\\theta=5/13$, $\\tan\\theta=$ ___.", ["12/5"]));
  q.push(fill("hard", "For $8$-$15$-$17$, $\\sin$ of the larger acute angle = ___.", ["15/17"]));
  q.push(num("hard", "For $9$-$40$-$41$ ($\\alpha$ opp $9$), $\\sin\\alpha$ (2 dp) = ___.", 0.22, 0.01));
  q.push(num("hard", "If $\\sin\\theta=0.6$, then $\\cos\\theta$ (right triangle, 1 dp) = ___.", 0.8, 0.05));
  q.push(num("hard", "For legs $20$ and $21$, the hypotenuse = ___.", 29, 0));
  q.push(order("hard", "Order the steps to find $\\sin\\theta$ from two given legs.", ["Find the hypotenuse with the Pythagorean theorem", "Identify the opposite side", "Write $\\sin\\theta=opp/hyp$", "Simplify"]));
  q.push(match("hard", "Match each ratio ($8$-$15$-$17$, $\\alpha$ opp $8$) to its value.", ["$\\sin\\alpha$", "$\\cos\\alpha$", "$\\tan\\alpha$"], ["$8/17$", "$15/17$", "$8/15$"], [0, 1, 2]));
  return q;
}

// ── 6.4 Finding Side Lengths ─────────────────────────────────
function g64() {
  const q = [];
  q.push(mc("easy", "To find the opposite from the hypotenuse:", ["opp $=$ hyp$\\cdot\\sin\\theta$", "opp $=$ hyp$\\cdot\\cos\\theta$", "opp $=$ hyp$/\\sin\\theta$", "opp $=$ adj$\\cdot\\tan\\theta$"], 0));
  q.push(mc("easy", "$10\\sin 30^\\circ=$", ["$5$", "$8.66$", "$10$", "$0.5$"], 0));
  q.push(mc("easy", "$20\\cos 60^\\circ=$", ["$10$", "$17.3$", "$20$", "$0.5$"], 0));
  q.push(mc("easy", "The calculator should be in:", ["degree mode", "radian mode", "gradian mode", "any mode"], 0));
  q.push(mc("easy", "To find the adjacent from the hypotenuse:", ["adj $=$ hyp$\\cdot\\cos\\theta$", "adj $=$ hyp$\\cdot\\sin\\theta$", "adj $=$ opp$\\cdot\\tan\\theta$", "adj $=$ hyp$/\\cos\\theta$"], 0));
  q.push(mc("easy", "opp $=$ adj$\\cdot\\tan\\theta$; if adj $=8$, $\\theta=45^\\circ$:", ["$8$", "$4$", "$11.3$", "$5.66$"], 0));
  q.push(ms("easy", "To find a side, choose the ratio linking:", ["the known angle", "the known side", "the unknown side", "the area"], [0, 1, 2]));
  q.push(ms("easy", "Correct formulas:", ["opp $=$ hyp$\\sin\\theta$", "adj $=$ hyp$\\cos\\theta$", "opp $=$ adj$\\tan\\theta$", "opp $=$ hyp$/\\cos\\theta$"], [0, 1, 2]));
  q.push(ms("easy", "Before computing:", ["set degree mode", "identify opp/adj/hyp", "choose the ratio", "round sensibly"], [0, 1, 2, 3]));
  q.push(ms("easy", "If the unknown is the hypotenuse:", ["hyp $=$ opp$/\\sin\\theta$", "hyp $=$ adj$/\\cos\\theta$", "divide", "multiply only"], [0, 1, 2]));
  q.push(tf("easy", "opp $=$ hyp$\\cdot\\sin\\theta$.", true));
  q.push(tf("easy", "Use degree mode for angles given in degrees.", true));
  q.push(tf("easy", "adj $=$ hyp$\\cdot\\sin\\theta$.", false));
  q.push(fill("easy", "$10\\sin 30^\\circ=$ ___.", ["5"]));
  q.push(fill("easy", "$20\\cos 60^\\circ=$ ___.", ["10"]));
  q.push(fill("easy", "$6/\\sin 30^\\circ=$ ___.", ["12"]));
  q.push(num("easy", "$12\\sin 30^\\circ=$ ___.", 6, 0));
  q.push(num("easy", "$16\\cos 60^\\circ=$ ___.", 8, 0));
  q.push(num("easy", "$8/\\sin 30^\\circ=$ ___.", 16, 0));
  q.push(match("easy", "Match each unknown to its formula.", ["opposite (from hyp)", "adjacent (from hyp)", "hypotenuse (from opp)"], ["hyp$\\cdot\\sin\\theta$", "hyp$\\cdot\\cos\\theta$", "opp$/\\sin\\theta$"], [0, 1, 2]));
  q.push(mc("medium", "$8\\tan 40^\\circ\\approx$", ["$6.7$", "$9.5$", "$5.1$", "$10$"], 0));
  q.push(mc("medium", "$12/\\cos 25^\\circ\\approx$", ["$13.2$", "$10.9$", "$12$", "$26.5$"], 0));
  q.push(mc("medium", "$14\\sin 35^\\circ\\approx$", ["$8.0$", "$11.5$", "$9.8$", "$5.7$"], 0));
  q.push(mc("medium", "$9\\tan 50^\\circ\\approx$", ["$10.7$", "$7.6$", "$11.7$", "$6.9$"], 0));
  q.push(mc("medium", "$10/\\cos 40^\\circ\\approx$", ["$13.1$", "$7.7$", "$13$", "$15.6$"], 0));
  q.push(mc("medium", "$25\\sin 52^\\circ\\approx$", ["$19.7$", "$15.4$", "$20.3$", "$12$"], 0));
  q.push(ms("medium", "To find the opposite from the adjacent:", ["opp $=$ adj$\\tan\\theta$", "use TOA", "multiply", "divide"], [0, 1, 2]));
  q.push(ms("medium", "Which give the hypotenuse?", ["hyp $=$ opp$/\\sin\\theta$", "hyp $=$ adj$/\\cos\\theta$", "divide the known side", "hyp $=$ opp$\\sin\\theta$"], [0, 1, 2]));
  q.push(ms("medium", "For adj $=14$, $\\theta=38^\\circ$, the opposite:", ["$14\\tan 38^\\circ$", "$\\approx10.9$", "use TOA", "$14/\\tan 38^\\circ$"], [0, 1, 2]));
  q.push(ms("medium", "Rounding trig sides:", ["1 decimal is common", "keep degree mode", "check reasonableness", "always round to integers"], [0, 1, 2]));
  q.push(tf("medium", "opp $=$ adj$\\cdot\\tan\\theta$.", true));
  q.push(tf("medium", "hyp $=$ opp$/\\sin\\theta$ when the opposite and angle are known.", true));
  q.push(tf("medium", "$8\\tan 40^\\circ$ is about $12$.", false));
  q.push(fill("medium", "$8\\tan 40^\\circ\\approx$ ___ (1 dp).", ["6.7"]));
  q.push(fill("medium", "$12/\\cos 25^\\circ\\approx$ ___ (1 dp).", ["13.2"]));
  q.push(fill("medium", "$14\\sin 35^\\circ\\approx$ ___ (1 dp).", ["8.0", "8"]));
  q.push(num("medium", "$25\\sin 52^\\circ\\approx$ ___ (1 dp).", 19.7, 0.1));
  q.push(num("medium", "$9/\\cos 33^\\circ\\approx$ ___ (1 dp).", 10.7, 0.1));
  q.push(num("medium", "$30\\cos 65^\\circ\\approx$ ___ (1 dp).", 12.7, 0.1));
  q.push(match("medium", "Match each computation to its value.", ["$10\\sin 35^\\circ$", "$20\\cos 60^\\circ$", "$8\\tan 40^\\circ$"], ["$\\approx5.7$", "$10$", "$\\approx6.7$"], [0, 1, 2]));
  q.push(mc("hard", "A right triangle hyp $=18$, $\\theta=28^\\circ$. The opposite leg $\\approx$", ["$8.5$", "$15.9$", "$9.6$", "$8.0$"], 0));
  q.push(mc("hard", "Same triangle ($18$, $28^\\circ$): the adjacent leg $\\approx$", ["$15.9$", "$8.5$", "$16$", "$9.0$"], 0));
  q.push(mc("hard", "$11/\\sin 42^\\circ\\approx$", ["$16.4$", "$7.4$", "$14.8$", "$16$"], 0));
  q.push(mc("hard", "A right triangle $\\theta=60^\\circ$, opp $=12$. The adjacent $\\approx$", ["$6.9$", "$20.8$", "$6$", "$10.4$"], 0));
  q.push(mc("hard", "$20\\tan 15^\\circ\\approx$", ["$5.4$", "$74.6$", "$5.2$", "$18.6$"], 0));
  q.push(ms("hard", "For hyp $=18$, $\\theta=28^\\circ$:", ["opp $\\approx8.5$", "adj $\\approx15.9$", "opp $=18\\sin 28^\\circ$", "adj $=18\\cos 28^\\circ$"], [0, 1, 2, 3]));
  q.push(ms("hard", "To find both legs from the hypotenuse and an angle:", ["opp $=$ hyp$\\sin\\theta$", "adj $=$ hyp$\\cos\\theta$", "use both ratios", "add them"], [0, 1, 2]));
  q.push(ms("hard", "If the unknown is in the denominator:", ["divide", "hyp $=$ opp$/\\sin\\theta$", "hyp $=$ adj$/\\cos\\theta$", "always multiply"], [0, 1, 2]));
  q.push(ms("hard", "Good practice:", ["draw and label", "degree mode", "pick the right ratio", "round at the end"], [0, 1, 2, 3]));
  q.push(tf("hard", "For hyp $=18$, $\\theta=28^\\circ$, the opposite $\\approx8.5$.", true));
  q.push(tf("hard", "hyp $=$ adj$/\\cos\\theta$ when the adjacent and angle are known.", true));
  q.push(tf("hard", "$20\\tan 15^\\circ$ is about $18.6$.", false));
  q.push(fill("hard", "For hyp $=18$, $\\theta=28^\\circ$, the opposite $\\approx$ ___ (1 dp).", ["8.5"]));
  q.push(fill("hard", "$11/\\sin 42^\\circ\\approx$ ___ (1 dp).", ["16.4"]));
  q.push(fill("hard", "For $\\theta=60^\\circ$, opp $=12$, the adjacent $\\approx$ ___ (1 dp).", ["6.9"]));
  q.push(num("hard", "For hyp $=22$, $\\theta=37^\\circ$, the opposite $\\approx$ ___ (1 dp).", 13.2, 0.1));
  q.push(num("hard", "For hyp $=22$, $\\theta=37^\\circ$, the adjacent $\\approx$ ___ (1 dp).", 17.6, 0.1));
  q.push(num("hard", "$10/\\cos 40^\\circ\\approx$ ___ (1 dp).", 13.1, 0.1));
  q.push(order("hard", "Order the steps to find an unknown side.", ["Label opp/adj/hyp relative to the angle", "Pick sin, cos, or tan", "Substitute the known values", "Solve (multiply or divide)"]));
  q.push(match("hard", "Match each (hyp $=20$, $\\theta=30^\\circ$) to its value.", ["opposite", "adjacent", "other acute angle"], ["$10$", "$\\approx17.3$", "$60^\\circ$"], [0, 1, 2]));
  return q;
}

// ── 6.5 Finding Angles ───────────────────────────────────────
function g65() {
  const q = [];
  q.push(mc("easy", "To find an angle from two sides, use:", ["inverse trig", "the Pythagorean theorem", "the slope", "the area"], 0));
  q.push(mc("easy", "If $\\sin\\theta=0.5$, then $\\theta=$", ["$30^\\circ$", "$60^\\circ$", "$45^\\circ$", "$90^\\circ$"], 0));
  q.push(mc("easy", "If $\\tan\\theta=1$, then $\\theta=$", ["$45^\\circ$", "$30^\\circ$", "$60^\\circ$", "$90^\\circ$"], 0));
  q.push(mc("easy", "$\\theta=\\sin^{-1}(opp/hyp)$ is the:", ["inverse sine", "sine", "cosine", "tangent"], 0));
  q.push(mc("easy", "If $\\cos\\theta=0.5$, then $\\theta=$", ["$60^\\circ$", "$30^\\circ$", "$45^\\circ$", "$90^\\circ$"], 0));
  q.push(mc("easy", "The calculator key for inverse sine is:", ["$\\sin^{-1}$", "$\\sin$", "$\\cos^{-1}$", "$\\tan$"], 0));
  q.push(ms("easy", "Inverse functions:", ["$\\sin^{-1}$", "$\\cos^{-1}$", "$\\tan^{-1}$", "$\\log$"], [0, 1, 2]));
  q.push(ms("easy", "To find $\\theta$:", ["pick the ratio of the known sides", "apply its inverse", "use degree mode", "add the sides"], [0, 1, 2]));
  q.push(ms("easy", "The two acute angles of a right triangle:", ["add to $90^\\circ$", "are complementary", "with $90^\\circ$ sum to $180^\\circ$", "are equal"], [0, 1, 2]));
  q.push(ms("easy", "If opp $=3$, hyp $=5$:", ["$\\sin\\theta=0.6$", "$\\theta=\\sin^{-1}(0.6)$", "$\\theta\\approx36.9^\\circ$", "$\\theta=0.6^\\circ$"], [0, 1, 2]));
  q.push(tf("easy", "$\\sin^{-1}(0.5)=30^\\circ$.", true));
  q.push(tf("easy", "The two acute angles of a right triangle add to $90^\\circ$.", true));
  q.push(tf("easy", "$\\tan^{-1}(1)=60^\\circ$.", false));
  q.push(fill("easy", "If $\\sin\\theta=0.5$, $\\theta=$ ___ (degrees).", ["30"]));
  q.push(fill("easy", "If $\\tan\\theta=1$, $\\theta=$ ___ (degrees).", ["45"]));
  q.push(fill("easy", "If $\\cos\\theta=0.5$, $\\theta=$ ___ (degrees).", ["60"]));
  q.push(num("easy", "$\\sin^{-1}(0.5)=$ ___ (degrees).", 30, 0));
  q.push(num("easy", "$\\tan^{-1}(1)=$ ___ (degrees).", 45, 0));
  q.push(num("easy", "If one acute angle is $30^\\circ$, the other is ___ (degrees).", 60, 0));
  q.push(match("easy", "Match each equation to the angle.", ["$\\sin\\theta=0.5$", "$\\cos\\theta=0.5$", "$\\tan\\theta=1$"], ["$30^\\circ$", "$60^\\circ$", "$45^\\circ$"], [0, 1, 2]));
  q.push(mc("medium", "$\\cos\\theta=0.6\\Rightarrow\\theta\\approx$", ["$53.1^\\circ$", "$36.9^\\circ$", "$60^\\circ$", "$45^\\circ$"], 0));
  q.push(mc("medium", "opp $=3$, hyp $=5\\Rightarrow\\theta\\approx$", ["$36.9^\\circ$", "$53.1^\\circ$", "$30^\\circ$", "$60^\\circ$"], 0));
  q.push(mc("medium", "opp $=4$, adj $=3\\Rightarrow\\theta\\approx$", ["$53.1^\\circ$", "$36.9^\\circ$", "$45^\\circ$", "$60^\\circ$"], 0));
  q.push(mc("medium", "adj $=5$, hyp $=13\\Rightarrow\\theta\\approx$", ["$67.4^\\circ$", "$22.6^\\circ$", "$60^\\circ$", "$30^\\circ$"], 0));
  q.push(mc("medium", "opp $=7$, adj $=24\\Rightarrow\\theta\\approx$", ["$16.3^\\circ$", "$73.7^\\circ$", "$20^\\circ$", "$45^\\circ$"], 0));
  q.push(mc("medium", "The acute angles of a $3$-$4$-$5$ triangle:", ["$36.9^\\circ$ and $53.1^\\circ$", "$30^\\circ$ and $60^\\circ$", "$45^\\circ$ and $45^\\circ$", "$40^\\circ$ and $50^\\circ$"], 0));
  q.push(ms("medium", "For opp $=3$, hyp $=5$:", ["$\\sin\\theta=0.6$", "$\\theta=\\sin^{-1}(0.6)$", "$\\theta\\approx36.9^\\circ$", "$\\theta\\approx53.1^\\circ$"], [0, 1, 2]));
  q.push(ms("medium", "For a $5$-$12$-$13$ triangle:", ["$\\tan^{-1}(5/12)\\approx22.6^\\circ$", "the other angle $\\approx67.4^\\circ$", "they sum to $90^\\circ$", "both $45^\\circ$"], [0, 1, 2]));
  q.push(ms("medium", "Choosing the inverse:", ["$\\sin^{-1}$ for opp \\& hyp", "$\\cos^{-1}$ for adj \\& hyp", "$\\tan^{-1}$ for opp \\& adj", "any always works"], [0, 1, 2]));
  q.push(ms("medium", "After finding one acute angle:", ["subtract from $90^\\circ$ for the other", "they are complementary", "check with the third ratio", "add $90^\\circ$"], [0, 1, 2]));
  q.push(tf("medium", "$\\cos^{-1}(0.6)\\approx53.1^\\circ$.", true));
  q.push(tf("medium", "The acute angles of a $3$-$4$-$5$ triangle are about $36.9^\\circ$ and $53.1^\\circ$.", true));
  q.push(tf("medium", "$\\tan^{-1}(4/3)\\approx36.9^\\circ$.", false));
  q.push(fill("medium", "opp $=3$, hyp $=5\\Rightarrow\\theta\\approx$ ___ (1 dp, degrees).", ["36.9"]));
  q.push(fill("medium", "opp $=4$, adj $=3\\Rightarrow\\theta\\approx$ ___ (1 dp, degrees).", ["53.1"]));
  q.push(fill("medium", "adj $=5$, hyp $=13\\Rightarrow\\theta\\approx$ ___ (1 dp, degrees).", ["67.4"]));
  q.push(num("medium", "$\\sin^{-1}(0.6)\\approx$ ___ (1 dp, degrees).", 36.9, 0.2));
  q.push(num("medium", "$\\tan^{-1}(4/3)\\approx$ ___ (1 dp, degrees).", 53.1, 0.2));
  q.push(num("medium", "$\\cos^{-1}(5/13)\\approx$ ___ (1 dp, degrees).", 67.4, 0.2));
  q.push(match("medium", "Match each ratio to its angle.", ["$\\sin\\theta=0.6$", "$\\tan\\theta=4/3$", "$\\cos\\theta=5/13$"], ["$\\approx36.9^\\circ$", "$\\approx53.1^\\circ$", "$\\approx67.4^\\circ$"], [0, 1, 2]));
  q.push(mc("hard", "The acute angles of an $8$-$15$-$17$ triangle:", ["$28.1^\\circ$ and $61.9^\\circ$", "$30^\\circ$ and $60^\\circ$", "$45^\\circ$ and $45^\\circ$", "$20^\\circ$ and $70^\\circ$"], 0));
  q.push(mc("hard", "opp $=9$, adj $=40\\Rightarrow\\theta\\approx$", ["$12.7^\\circ$", "$77.3^\\circ$", "$16.3^\\circ$", "$20^\\circ$"], 0));
  q.push(mc("hard", "A ramp rises $1$ m over a $5$ m run; the angle $\\approx$", ["$11.3^\\circ$", "$78.7^\\circ$", "$20^\\circ$", "$5^\\circ$"], 0));
  q.push(mc("hard", "opp $=12$, adj $=5\\Rightarrow\\theta\\approx$", ["$67.4^\\circ$", "$22.6^\\circ$", "$60^\\circ$", "$53.1^\\circ$"], 0));
  q.push(mc("hard", "$\\sin^{-1}(0.28)\\approx$", ["$16.3^\\circ$", "$73.7^\\circ$", "$28^\\circ$", "$20^\\circ$"], 0));
  q.push(ms("hard", "For $8$-$15$-$17$:", ["$\\tan^{-1}(8/15)\\approx28.1^\\circ$", "the other $\\approx61.9^\\circ$", "they sum to $90^\\circ$", "both $45^\\circ$"], [0, 1, 2]));
  q.push(ms("hard", "For a ramp rise $1$, run $5$:", ["$\\tan\\theta=1/5$", "$\\theta=\\tan^{-1}(0.2)$", "$\\approx11.3^\\circ$", "$\\theta=\\sin^{-1}(0.2)$"], [0, 1, 2]));
  q.push(ms("hard", "To find both acute angles:", ["find one with an inverse", "subtract from $90^\\circ$ for the other", "or use another ratio", "they are equal"], [0, 1, 2]));
  q.push(ms("hard", "Inverse trig requires:", ["the ratio of two sides", "degree mode", "picking the right function", "the area"], [0, 1, 2]));
  q.push(tf("hard", "The acute angles of an $8$-$15$-$17$ triangle are about $28.1^\\circ$ and $61.9^\\circ$.", true));
  q.push(tf("hard", "A ramp rising $1$ m over $5$ m has angle $\\approx11.3^\\circ$.", true));
  q.push(tf("hard", "$\\tan^{-1}(9/40)\\approx77.3^\\circ$.", false));
  q.push(fill("hard", "The smaller acute angle of $8$-$15$-$17\\approx$ ___ (1 dp, degrees).", ["28.1"]));
  q.push(fill("hard", "opp $=9$, adj $=40\\Rightarrow\\theta\\approx$ ___ (1 dp, degrees).", ["12.7"]));
  q.push(fill("hard", "A ramp rise $1$, run $5\\Rightarrow$ angle $\\approx$ ___ (1 dp, degrees).", ["11.3"]));
  q.push(num("hard", "$\\tan^{-1}(8/15)\\approx$ ___ (1 dp, degrees).", 28.1, 0.2));
  q.push(num("hard", "$\\cos^{-1}(0.8)\\approx$ ___ (1 dp, degrees).", 36.9, 0.2));
  q.push(num("hard", "The larger acute angle of $9$-$12$-$15\\approx$ ___ (1 dp, degrees).", 53.1, 0.2));
  q.push(order("hard", "Order the steps to find an angle from two sides.", ["Identify which two sides are known", "Choose $\\sin^{-1}$, $\\cos^{-1}$, or $\\tan^{-1}$", "Compute the ratio", "Apply the inverse function"]));
  q.push(match("hard", "Match each right triangle to its smaller acute angle.", ["$3$-$4$-$5$", "$5$-$12$-$13$", "$8$-$15$-$17$"], ["$\\approx36.9^\\circ$", "$\\approx22.6^\\circ$", "$\\approx28.1^\\circ$"], [0, 1, 2]));
  return q;
}

// ── 6.6 Solving Right Triangles & Applications ───────────────
function g66() {
  const q = [];
  q.push(mc("easy", "To \"solve\" a right triangle means to find:", ["all unknown sides and angles", "only the hypotenuse", "only one angle", "the area"], 0));
  q.push(mc("easy", "The angle of elevation is measured:", ["up from the horizontal", "down from the horizontal", "from the vertical", "at the top"], 0));
  q.push(mc("easy", "The angle of depression is measured:", ["down from the horizontal", "up from the horizontal", "from the ground", "at the base"], 0));
  q.push(mc("easy", "From $50$ m away, elevation $40^\\circ$ to a tower top; height $=$", ["$50\\tan 40^\\circ$", "$50\\sin 40^\\circ$", "$50/\\tan 40^\\circ$", "$50\\cos 40^\\circ$"], 0));
  q.push(mc("easy", "The two acute angles of a right triangle sum to:", ["$90^\\circ$", "$180^\\circ$", "$45^\\circ$", "$360^\\circ$"], 0));
  q.push(mc("easy", "A ladder against a wall forms a triangle with the:", ["ground and wall", "roof", "ceiling", "door"], 0));
  q.push(ms("easy", "Solving a right triangle uses:", ["SOH CAH TOA", "the Pythagorean theorem", "inverse trig", "the slope formula"], [0, 1, 2]));
  q.push(ms("easy", "Real applications include:", ["angle of elevation", "angle of depression", "ladders / ramps", "none"], [0, 1, 2]));
  q.push(ms("easy", "Before solving an application:", ["draw a diagram", "label the knowns", "mark the angle", "ignore units"], [0, 1, 2]));
  q.push(ms("easy", "The acute angles:", ["sum to $90^\\circ$", "are complementary", "one determines the other", "sum to $180^\\circ$"], [0, 1, 2]));
  q.push(tf("easy", "To solve a right triangle, find all sides and angles.", true));
  q.push(tf("easy", "The angle of elevation is measured up from the horizontal.", true));
  q.push(tf("easy", "The acute angles of a right triangle sum to $180^\\circ$.", false));
  q.push(fill("easy", "From $50$ m away, elevation $40^\\circ$: height $=50\\tan 40^\\circ\\approx$ ___ m (1 dp).", ["42.0", "42"]));
  q.push(fill("easy", "The two acute angles sum to ___ (degrees).", ["90"]));
  q.push(fill("easy", "If one acute angle is $35^\\circ$, the other is ___ (degrees).", ["55"]));
  q.push(num("easy", "$30\\tan 50^\\circ\\approx$ ___ m (1 dp).", 35.8, 0.1));
  q.push(num("easy", "If one acute angle is $25^\\circ$, the other is ___ (degrees).", 65, 0));
  q.push(num("easy", "A $5$ m slide at $30^\\circ$ reaches height $5\\sin 30^\\circ=$ ___ m.", 2.5, 0));
  q.push(match("easy", "Match each term to its meaning.", ["solve a triangle", "angle of elevation", "angle of depression"], ["find all sides \\& angles", "up from the horizontal", "down from the horizontal"], [0, 1, 2]));
  q.push(mc("medium", "Solve $\\theta=30^\\circ$, hyp $=10$: opp, adj, other angle:", ["$5,\\ 8.7,\\ 60^\\circ$", "$8.7,\\ 5,\\ 60^\\circ$", "$5,\\ 5,\\ 60^\\circ$", "$10,\\ 5,\\ 30^\\circ$"], 0));
  q.push(mc("medium", "From $30$ m, elevation $50^\\circ$ to a tree top; height $\\approx$", ["$35.8$", "$23.0$", "$19.3$", "$39.2$"], 0));
  q.push(mc("medium", "From an $80$ m cliff, depression $25^\\circ$ to a boat; distance $\\approx$", ["$171.6$", "$37.3$", "$85.9$", "$176$"], 0));
  q.push(mc("medium", "A $5$ m ladder, base $1.5$ m from the wall; angle with ground $\\approx$", ["$72.5^\\circ$", "$17.5^\\circ$", "$30^\\circ$", "$60^\\circ$"], 0));
  q.push(mc("medium", "A ramp rises $2$ m over a $10$ m run; angle $\\approx$", ["$11.3^\\circ$", "$78.7^\\circ$", "$20^\\circ$", "$5.7^\\circ$"], 0));
  q.push(mc("medium", "A kite string $60$ m at $50^\\circ$; height $\\approx$", ["$46.0$", "$38.6$", "$45$", "$51.4$"], 0));
  q.push(ms("medium", "To solve $\\theta=30^\\circ$, hyp $=10$:", ["opp $=10\\sin 30^\\circ=5$", "adj $=10\\cos 30^\\circ\\approx8.7$", "other angle $=60^\\circ$", "opp $=10$"], [0, 1, 2]));
  q.push(ms("medium", "Angle-of-elevation problems:", ["use tan with horizontal distance and height", "draw the triangle", "height $=$ distance$\\cdot\\tan\\theta$", "need radian mode"], [0, 1, 2]));
  q.push(ms("medium", "For a ladder:", ["the wall is vertical", "the ground is horizontal", "$\\cos\\theta=$ base/ladder", "the ladder is the opposite"], [0, 1, 2]));
  q.push(ms("medium", "Depression problems:", ["the angle is below the horizontal", "equal to the elevation from the boat", "use tan", "measured upward"], [0, 1, 2]));
  q.push(tf("medium", "From $50$ m away with elevation $40^\\circ$, the height is $50\\tan 40^\\circ$.", true));
  q.push(tf("medium", "The angle of depression equals the angle of elevation from the other point.", true));
  q.push(tf("medium", "The angle of elevation is measured downward from the horizontal.", false));
  q.push(fill("medium", "From $30$ m, elevation $50^\\circ$: height $\\approx$ ___ m (1 dp).", ["35.8"]));
  q.push(fill("medium", "A kite string $60$ m at $50^\\circ$: height $\\approx$ ___ m (1 dp).", ["46.0", "46"]));
  q.push(fill("medium", "A $4$ m ladder, base $1$ m from the wall: angle with ground $\\approx$ ___ (1 dp, degrees).", ["75.5"]));
  q.push(num("medium", "$100\\tan 35^\\circ\\approx$ ___ m (1 dp).", 70.0, 0.2));
  q.push(num("medium", "$60/\\tan 35^\\circ\\approx$ ___ m (1 dp).", 85.7, 0.2));
  q.push(num("medium", "A ramp rise $3$, run $12$: angle $\\approx$ ___ (1 dp, degrees).", 14.0, 0.2));
  q.push(match("medium", "Match each scenario to its calculation.", ["height from $50$ m, elev $40^\\circ$", "distance from $80$ m cliff, depr $25^\\circ$", "kite height, string $60$, angle $50^\\circ$"], ["$50\\tan 40^\\circ$", "$80/\\tan 25^\\circ$", "$60\\sin 50^\\circ$"], [0, 1, 2]));
  q.push(mc("hard", "From $50$ m, elevation $40^\\circ$ to a tower top; height $\\approx$", ["$42.0$", "$38.3$", "$59.6$", "$32.1$"], 0));
  q.push(mc("hard", "From an $80$ m cliff, depression $25^\\circ$ to a boat; distance from base $\\approx$", ["$171.6$", "$37.3$", "$85.9$", "$176.3$"], 0));
  q.push(mc("hard", "A $5$ m ladder, base $1.5$ m from the wall; height reached $\\approx$", ["$4.8$", "$4.6$", "$5.2$", "$4.0$"], 0));
  q.push(mc("hard", "A $12$ m flagpole; shadow when the sun's elevation is $58^\\circ\\approx$", ["$7.5$", "$19.2$", "$10.2$", "$6.4$"], 0));
  q.push(mc("hard", "A wire $10$ m anchored $4$ m from a pole's base; angle with ground $\\approx$", ["$66.4^\\circ$", "$23.6^\\circ$", "$60^\\circ$", "$21.8^\\circ$"], 0));
  q.push(ms("hard", "To solve $\\theta=40^\\circ$, hyp $=20$:", ["opp $=20\\sin 40^\\circ\\approx12.9$", "adj $\\approx15.3$", "other angle $=50^\\circ$", "opp $=20$"], [0, 1, 2]));
  q.push(ms("hard", "Elevation / depression:", ["both measured from the horizontal", "alternate angles are equal", "use tan with horizontal \\& vertical", "measured from the vertical"], [0, 1, 2]));
  q.push(ms("hard", "For a ladder length $L$, base $b$:", ["angle $=\\cos^{-1}(b/L)$", "height $=\\sqrt{L^2-b^2}$", "or height $=L\\sin(\\text{angle})$", "height $=L\\cdot b$"], [0, 1, 2]));
  q.push(ms("hard", "Two-step problems:", ["find one quantity first", "use it in the next step", "draw clear diagrams", "skip the diagram"], [0, 1, 2]));
  q.push(tf("hard", "From a $45$ m lighthouse, the distance to a boat at depression $20^\\circ$ is $45/\\tan 20^\\circ$.", true));
  q.push(tf("hard", "A $5$ m ladder $1.5$ m from a wall reaches about $4.8$ m up.", true));
  q.push(tf("hard", "The shadow of a $12$ m pole at elevation $58^\\circ$ is $12\\tan 58^\\circ$.", false));
  q.push(fill("hard", "From $50$ m, elevation $40^\\circ$: tower height $\\approx$ ___ m (1 dp).", ["42.0", "42"]));
  q.push(fill("hard", "From an $80$ m cliff, depression $25^\\circ$: boat distance $\\approx$ ___ m (1 dp).", ["171.6"]));
  q.push(fill("hard", "A wire $10$ m, base $4$ m: angle with ground $\\approx$ ___ (1 dp, degrees).", ["66.4"]));
  q.push(num("hard", "A $15$ m pole's shadow at sun elevation $62^\\circ\\approx$ ___ m (1 dp).", 8.0, 0.2));
  q.push(num("hard", "A slide $5$ m at $30^\\circ$: its height $=$ ___ m.", 2.5, 0));
  q.push(num("hard", "From $120$ m away, elevation $28^\\circ$ to a building top: height $\\approx$ ___ m (1 dp).", 63.8, 0.3));
  q.push(order("hard", "Order the steps to solve an angle-of-elevation problem.", ["Draw and label the right triangle", "Identify the known side and angle", "Choose the correct ratio", "Solve for the unknown"]));
  q.push(match("hard", "Match each application to its formula.", ["tower height, $50$ m away, elev $40^\\circ$", "boat distance, $80$ m cliff, depr $25^\\circ$", "ladder angle, $5$ m, base $1.5$ m"], ["$50\\tan 40^\\circ$", "$80/\\tan 25^\\circ$", "$\\cos^{-1}(1.5/5)$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "6.1", gen: g61 },
  { code: "6.2", gen: g62 },
  { code: "6.3", gen: g63 },
  { code: "6.4", gen: g64 },
  { code: "6.5", gen: g65 },
  { code: "6.6", gen: g66 },
];
