// MPM2D Unit 7 — The Sine & Cosine Laws: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "./helpers.mjs";

// ── 7.1 The Sine Law ─────────────────────────────────────────
function g71() {
  const q = [];
  q.push(mc("easy", "The sine law is:", ["$\\frac{a}{\\sin A}=\\frac{b}{\\sin B}=\\frac{c}{\\sin C}$", "$a^2=b^2+c^2$", "$\\frac{a}{b}=\\frac{c}{d}$", "$a=b\\sin C$"], 0));
  q.push(mc("easy", "In the sine law, side $a$ is opposite:", ["angle $A$", "angle $B$", "angle $C$", "the right angle"], 0));
  q.push(mc("easy", "Use the sine law when you know:", ["a side and its opposite angle", "two sides and the included angle only", "three sides only", "nothing"], 0));
  q.push(mc("easy", "If $A+B=110^\\circ$, then $C=$", ["$70^\\circ$", "$110^\\circ$", "$180^\\circ$", "$90^\\circ$"], 0));
  q.push(mc("easy", "The sine law pairs a side with:", ["its opposite angle", "an adjacent angle", "the hypotenuse", "the largest angle"], 0));
  q.push(mc("easy", "To find a side, the sine law puts:", ["sides on top", "angles on top", "everything equal to 1", "sides in the denominator"], 0));
  q.push(ms("easy", "The sine law applies to:", ["AAS", "ASA", "SSA", "SAS"], [0, 1, 2]));
  q.push(ms("easy", "Each side pairs with:", ["its opposite angle", "$a$ with $A$", "$b$ with $B$", "an adjacent side"], [0, 1, 2]));
  q.push(ms("easy", "To find a missing angle, the sine law uses:", ["angles on top", "$\\frac{\\sin A}{a}=\\frac{\\sin B}{b}$", "then inverse sine", "sides on top"], [0, 1, 2]));
  q.push(ms("easy", "Angles of a triangle:", ["sum to $180^\\circ$", "let you find the third", "$A+B+C=180^\\circ$", "sum to $90^\\circ$"], [0, 1, 2]));
  q.push(tf("easy", "The sine law relates sides to their opposite angles.", true));
  q.push(tf("easy", "Side $a$ is opposite angle $A$.", true));
  q.push(tf("easy", "The sine law needs a right angle.", false));
  q.push(fill("easy", "If $A=40^\\circ$ and $B=70^\\circ$, then $C=$ ___ (degrees).", ["70"]));
  q.push(fill("easy", "The sine law: $\\frac{a}{\\sin A}=\\frac{b}{\\sin B}=\\frac{c}{\\sin\\,?}$. The missing angle is ___.", ["C"]));
  q.push(fill("easy", "Side $b$ is opposite angle ___.", ["B"]));
  q.push(num("easy", "If $A=50^\\circ$, $B=60^\\circ$, then $C=$ ___ (degrees).", 70, 0));
  q.push(num("easy", "If $A=90^\\circ$, $B=30^\\circ$, then $C=$ ___ (degrees).", 60, 0));
  q.push(num("easy", "If two angles are $45^\\circ$ and $65^\\circ$, the third is ___ (degrees).", 70, 0));
  q.push(match("easy", "Match each side to its opposite angle.", ["$a$", "$b$", "$c$"], ["$A$", "$B$", "$C$"], [0, 1, 2]));
  q.push(mc("medium", "$A=40^\\circ$, $B=60^\\circ$, $b=10$. Find $a$:", ["$\\approx7.4$", "$\\approx13.5$", "$\\approx10$", "$\\approx8.7$"], 0));
  q.push(mc("medium", "$A=50^\\circ$, $a=8$, $B=70^\\circ$. Find $b$:", ["$\\approx9.8$", "$\\approx6.5$", "$\\approx8$", "$\\approx10.4$"], 0));
  q.push(mc("medium", "$a=7$, $A=40^\\circ$, $b=10$. Find $B$:", ["$\\approx66.6^\\circ$", "$\\approx23.4^\\circ$", "$\\approx40^\\circ$", "$\\approx90^\\circ$"], 0));
  q.push(mc("medium", "$A=45^\\circ$, $B=65^\\circ$, $c=12$. Find $a$:", ["$\\approx9.0$", "$\\approx12$", "$\\approx7.4$", "$\\approx13.5$"], 0));
  q.push(mc("medium", "$B=30^\\circ$, $A=80^\\circ$, $a=15$. Find $b$:", ["$\\approx7.6$", "$\\approx14.8$", "$\\approx15$", "$\\approx9.5$"], 0));
  q.push(mc("medium", "$a=12$, $A=70^\\circ$, $c=9$. Find $C$:", ["$\\approx44.8^\\circ$", "$\\approx70^\\circ$", "$\\approx55^\\circ$", "$\\approx30^\\circ$"], 0));
  q.push(ms("medium", "For $A=40^\\circ$, $B=60^\\circ$, $b=10$ (find $a$):", ["$\\frac{a}{\\sin 40^\\circ}=\\frac{10}{\\sin 60^\\circ}$", "$a=\\frac{10\\sin 40^\\circ}{\\sin 60^\\circ}$", "$a\\approx7.4$", "$a=10$"], [0, 1, 2]));
  q.push(ms("medium", "To find an angle with the sine law:", ["flip to angles on top", "$\\sin B=\\frac{b\\sin A}{a}$", "then apply $\\sin^{-1}$", "sides on top"], [0, 1, 2]));
  q.push(ms("medium", "For an ASA problem:", ["find the third angle first", "then use the sine law", "$A+B+C=180^\\circ$", "use the cosine law"], [0, 1, 2]));
  q.push(ms("medium", "Which fit the sine law?", ["$A,B,a$", "$A,a,b$", "$A,B,c$", "$a,b,c$"], [0, 1, 2]));
  q.push(tf("medium", "$\\frac{a}{\\sin A}=\\frac{b}{\\sin B}$ can be flipped to find an angle.", true));
  q.push(tf("medium", "For ASA, find the third angle, then use the sine law.", true));
  q.push(tf("medium", "The sine law can find a side directly from SSS.", false));
  q.push(fill("medium", "$A=50^\\circ$, $B=60^\\circ$, $b=12$: $a\\approx$ ___ (1 dp).", ["10.6"]));
  q.push(fill("medium", "$A=40^\\circ$, $a=9$, $B=75^\\circ$: $b\\approx$ ___ (1 dp).", ["13.5"]));
  q.push(fill("medium", "$a=8$, $A=35^\\circ$, $b=11$: $B\\approx$ ___ (1 dp, degrees).", ["52.1"]));
  q.push(num("medium", "$A=40^\\circ$, $B=60^\\circ$, $b=10$: $a\\approx$ ___ (1 dp).", 7.4, 0.1));
  q.push(num("medium", "$B=45^\\circ$, $A=80^\\circ$, $a=15$: $b\\approx$ ___ (1 dp).", 10.8, 0.1));
  q.push(num("medium", "$a=14$, $A=70^\\circ$, $c=10$: $C\\approx$ ___ (1 dp, degrees).", 42.2, 0.3));
  q.push(match("medium", "Match each given info to what the sine law finds.", ["$A,B,b$", "$a,A,b$", "$A,B,c$ (ASA)"], ["a side", "an angle", "third angle then a side"], [0, 1, 2]));
  q.push(mc("hard", "$A=35^\\circ$, $B=85^\\circ$, $a=20$. Find $b$ (1 dp):", ["$\\approx34.7$", "$\\approx30.2$", "$\\approx20$", "$\\approx11.6$"], 0));
  q.push(mc("hard", "$A=42^\\circ$, $B=78^\\circ$, $a=16$. Find $b$ (1 dp):", ["$\\approx23.4$", "$\\approx20.7$", "$\\approx16$", "$\\approx10.7$"], 0));
  q.push(mc("hard", "$a=10$, $A=45^\\circ$, $b=12$. Find $B$ (1 dp):", ["$\\approx58.0^\\circ$", "$\\approx32.0^\\circ$", "$\\approx45^\\circ$", "$\\approx70^\\circ$"], 0));
  q.push(mc("hard", "$A=48^\\circ$, $B=62^\\circ$, $a=20$. Find $b$ (1 dp):", ["$\\approx23.8$", "$\\approx18.7$", "$\\approx20$", "$\\approx16.4$"], 0));
  q.push(mc("hard", "$A=40^\\circ$, $C=85^\\circ$, $a=12$. Find $c$ (1 dp):", ["$\\approx18.6$", "$\\approx12$", "$\\approx9.8$", "$\\approx15.2$"], 0));
  q.push(ms("hard", "For $A=35^\\circ$, $B=85^\\circ$, $a=20$:", ["$C=60^\\circ$", "$b=\\frac{20\\sin 85^\\circ}{\\sin 35^\\circ}$", "$b\\approx34.7$", "$c\\approx30.2$"], [0, 1, 2, 3]));
  q.push(ms("hard", "The ambiguous case (SSA) can give:", ["zero triangles", "one triangle", "two triangles", "always three"], [0, 1, 2]));
  q.push(ms("hard", "To solve $A=48^\\circ$, $B=62^\\circ$, $a=20$:", ["sine law for $b$", "$\\frac{b}{\\sin 62^\\circ}=\\frac{20}{\\sin 48^\\circ}$", "$b\\approx23.8$", "cosine law"], [0, 1, 2]));
  q.push(ms("hard", "After finding one part:", ["use $A+B+C=180^\\circ$", "find the remaining angle", "sine law for more sides", "stop early"], [0, 1, 2]));
  q.push(tf("hard", "$A=35^\\circ$, $B=85^\\circ$, $a=20$ gives $b\\approx34.7$.", true));
  q.push(tf("hard", "The SSA case can produce two valid triangles.", true));
  q.push(tf("hard", "$a=10$, $A=45^\\circ$, $b=12$ gives $B\\approx32^\\circ$.", false));
  q.push(fill("hard", "$A=42^\\circ$, $B=78^\\circ$, $a=16$: $b\\approx$ ___ (1 dp).", ["23.4"]));
  q.push(fill("hard", "$A=40^\\circ$, $C=85^\\circ$, $a=12$: $c\\approx$ ___ (1 dp).", ["18.6"]));
  q.push(fill("hard", "$a=10$, $A=45^\\circ$, $b=12$: $B\\approx$ ___ (1 dp, degrees).", ["58.0", "58"]));
  q.push(num("hard", "$A=35^\\circ$, $B=85^\\circ$, $a=20$: $b\\approx$ ___ (1 dp).", 34.7, 0.2));
  q.push(num("hard", "$A=35^\\circ$, $B=85^\\circ$, $a=20$: $c\\approx$ ___ (1 dp).", 30.2, 0.2));
  q.push(num("hard", "$A=48^\\circ$, $B=62^\\circ$, $a=20$: $b\\approx$ ___ (1 dp).", 23.8, 0.2));
  q.push(order("hard", "Order the steps to solve an ASA triangle.", ["Find the third angle ($180^\\circ-A-B$)", "Pick a known side-angle pair", "Apply the sine law", "Solve for the unknown side"]));
  q.push(match("hard", "Match each problem to its answer.", ["$A=42^\\circ,B=78^\\circ,a=16$: $b$", "$A=40^\\circ,C=85^\\circ,a=12$: $c$", "$a=10,A=45^\\circ,b=12$: $B$"], ["$\\approx23.4$", "$\\approx18.6$", "$\\approx58.0^\\circ$"], [0, 1, 2]));
  return q;
}

// ── 7.2 The Cosine Law ───────────────────────────────────────
function g72() {
  const q = [];
  q.push(mc("easy", "The cosine law is:", ["$c^2=a^2+b^2-2ab\\cos C$", "$\\frac{a}{\\sin A}=\\frac{b}{\\sin B}$", "$c^2=a^2+b^2$", "$c=a+b$"], 0));
  q.push(mc("easy", "Use the cosine law for SAS to find:", ["the third side", "an angle from a side", "nothing", "the area"], 0));
  q.push(mc("easy", "The cosine law generalizes:", ["the Pythagorean theorem", "the sine law", "the slope", "the midpoint"], 0));
  q.push(mc("easy", "If $C=90^\\circ$, the cosine law becomes:", ["$c^2=a^2+b^2$", "$c^2=a^2-b^2$", "$c=a+b$", "$c^2=2ab$"], 0));
  q.push(mc("easy", "To find an angle from three sides, use:", ["$\\cos C=\\frac{a^2+b^2-c^2}{2ab}$", "$\\cos C=\\frac{c^2}{2ab}$", "$\\cos C=a^2+b^2$", "$\\cos C=\\frac{2ab}{c^2}$"], 0));
  q.push(mc("easy", "The angle $C$ and the side it finds are:", ["opposite each other", "adjacent", "equal", "the largest"], 0));
  q.push(ms("easy", "The cosine law is used for:", ["SAS (find a side)", "SSS (find an angle)", "two sides + included angle", "AAS"], [0, 1, 2]));
  q.push(ms("easy", "It generalizes:", ["the Pythagorean theorem", "when $C=90^\\circ$, $c^2=a^2+b^2$", "right-triangle ideas", "the slope formula"], [0, 1, 2]));
  q.push(ms("easy", "In $c^2=a^2+b^2-2ab\\cos C$, the angle $C$ is:", ["opposite side $c$", "the included angle of $a,b$", "the angle being used", "angle $A$"], [0, 1, 2]));
  q.push(ms("easy", "A negative cosine indicates:", ["an obtuse angle", "an angle $>90^\\circ$", "$\\cos C<0$", "an acute angle"], [0, 1, 2]));
  q.push(tf("easy", "The cosine law generalizes the Pythagorean theorem.", true));
  q.push(tf("easy", "For SSS you can find any angle with the cosine law.", true));
  q.push(tf("easy", "The cosine law needs a right angle.", false));
  q.push(fill("easy", "The cosine law: $c^2=a^2+b^2-2ab\\cos\\,?$. The angle is ___.", ["C"]));
  q.push(fill("easy", "If $C=90^\\circ$, then $c^2=a^2+$ ___.", ["b^2", "b²"]));
  q.push(fill("easy", "To find angle $C$ from sides: $\\cos C=\\frac{a^2+b^2-c^2}{\\,?\\,}$. The denominator is ___.", ["2ab"]));
  q.push(num("easy", "With $a=5$, $b=7$, $C=60^\\circ$: $c^2=25+49-70\\cos 60^\\circ=$ ___.", 39, 0));
  q.push(num("easy", "If $a=3$, $b=4$, $C=90^\\circ$: $c=$ ___.", 5, 0));
  q.push(num("easy", "$\\cos C=\\frac{25+36-49}{60}=$ ___ (decimal).", 0.2, 0));
  q.push(match("easy", "Match each case to its cosine-law use.", ["SAS", "SSS", "right angle"], ["find the third side", "find an angle", "$c^2=a^2+b^2$"], [0, 1, 2]));
  q.push(mc("medium", "$a=5$, $b=7$, $C=60^\\circ$. Find $c$ (1 dp):", ["$\\approx6.2$", "$\\approx8.9$", "$\\approx6.0$", "$\\approx7.0$"], 0));
  q.push(mc("medium", "$a=8$, $b=6$, $C=40^\\circ$. Find $c$ (1 dp):", ["$\\approx5.1$", "$\\approx9.4$", "$\\approx10$", "$\\approx2.0$"], 0));
  q.push(mc("medium", "SSS $a=5$, $b=6$, $c=7$. Find $C$ (1 dp):", ["$\\approx78.5^\\circ$", "$\\approx60^\\circ$", "$\\approx90^\\circ$", "$\\approx101.5^\\circ$"], 0));
  q.push(mc("medium", "The largest angle of a $4$-$5$-$6$ triangle (1 dp):", ["$\\approx82.8^\\circ$", "$\\approx55.8^\\circ$", "$\\approx41.4^\\circ$", "$\\approx90^\\circ$"], 0));
  q.push(mc("medium", "$a=10$, $b=12$, $C=100^\\circ$. Find $c$ (1 dp):", ["$\\approx16.9$", "$\\approx14.2$", "$\\approx12$", "$\\approx22$"], 0));
  q.push(mc("medium", "Find $A$ in $a=7$, $b=8$, $c=9$ (1 dp):", ["$\\approx48.2^\\circ$", "$\\approx58.8^\\circ$", "$\\approx73.0^\\circ$", "$\\approx60^\\circ$"], 0));
  q.push(ms("medium", "For SAS $a=5$, $b=7$, $C=60^\\circ$:", ["$c^2=25+49-70\\cos 60^\\circ$", "$c^2=39$", "$c\\approx6.2$", "$c=12$"], [0, 1, 2]));
  q.push(ms("medium", "For SSS find an angle:", ["$\\cos C=\\frac{a^2+b^2-c^2}{2ab}$", "then $\\cos^{-1}$", "the largest angle faces the largest side", "use the sine law first"], [0, 1, 2]));
  q.push(ms("medium", "A negative $\\cos$ value means:", ["an obtuse angle", "an angle $>90^\\circ$", "the largest side is opposite it", "acute"], [0, 1, 2]));
  q.push(ms("medium", "Which need the cosine law?", ["$a,b,C$ (SAS)", "$a,b,c$ (SSS)", "$A,B,a$", "$b,c,A$ (SAS)"], [0, 1, 3]));
  q.push(tf("medium", "For a $4$-$5$-$6$ triangle, the largest angle is opposite the side $6$.", true));
  q.push(tf("medium", "$a=5$, $b=7$, $C=60^\\circ$ gives $c\\approx6.2$.", true));
  q.push(tf("medium", "The cosine law cannot find an angle from three sides.", false));
  q.push(fill("medium", "$a=6$, $b=9$, $C=50^\\circ$: $c\\approx$ ___ (1 dp).", ["6.9"]));
  q.push(fill("medium", "SSS $a=4$, $b=5$, $c=6$: $C\\approx$ ___ (1 dp, degrees).", ["82.8"]));
  q.push(fill("medium", "Find $A$ in $a=6$, $b=8$, $c=10$: $A\\approx$ ___ (1 dp, degrees).", ["36.9"]));
  q.push(num("medium", "$a=5$, $b=7$, $C=60^\\circ$: $c\\approx$ ___ (1 dp).", 6.2, 0.1));
  q.push(num("medium", "The largest angle of a $4$-$5$-$6$ triangle $\\approx$ ___ (1 dp, degrees).", 82.8, 0.3));
  q.push(num("medium", "$a=10$, $b=12$, $C=100^\\circ$: $c\\approx$ ___ (1 dp).", 16.9, 0.2));
  q.push(match("medium", "Match each problem to its answer.", ["$a=5,b=7,C=60^\\circ$: $c$", "SSS $5,6,7$: $C$", "$a=6,b=8,c=10$: $A$"], ["$\\approx6.2$", "$\\approx78.5^\\circ$", "$\\approx36.9^\\circ$"], [0, 1, 2]));
  q.push(mc("hard", "$a=11$, $b=13$, $C=72^\\circ$. Find $c$ (1 dp):", ["$\\approx14.2$", "$\\approx12.0$", "$\\approx16.0$", "$\\approx10.5$"], 0));
  q.push(mc("hard", "The largest angle of an $8$-$11$-$15$ triangle (1 dp):", ["$\\approx103.1^\\circ$", "$\\approx76.9^\\circ$", "$\\approx90^\\circ$", "$\\approx120^\\circ$"], 0));
  q.push(mc("hard", "The largest angle of a $9$-$12$-$15$ triangle:", ["$90^\\circ$", "$82.8^\\circ$", "$78.5^\\circ$", "$60^\\circ$"], 0));
  q.push(mc("hard", "The smallest angle of a $6$-$8$-$9$ triangle (1 dp):", ["$\\approx40.8^\\circ$", "$\\approx49.2^\\circ$", "$\\approx60^\\circ$", "$\\approx30^\\circ$"], 0));
  q.push(mc("hard", "The largest angle of a $3$-$5$-$7$ triangle:", ["$120^\\circ$", "$60^\\circ$", "$90^\\circ$", "$135^\\circ$"], 0));
  q.push(ms("hard", "For an $8$-$11$-$15$ triangle:", ["largest angle is opposite $15$", "$\\cos\\theta=\\frac{64+121-225}{176}$", "$\\cos\\theta\\approx-0.227$", "$\\theta\\approx103.1^\\circ$"], [0, 1, 2, 3]));
  q.push(ms("hard", "The largest angle:", ["is opposite the largest side", "may be obtuse", "has $\\cos<0$ if obtuse", "is opposite the shortest side"], [0, 1, 2]));
  q.push(ms("hard", "A $9$-$12$-$15$ triangle:", ["$\\cos$ of the largest angle $=0$", "the largest angle is $90^\\circ$", "it is a right triangle", "it is obtuse"], [0, 1, 2]));
  q.push(ms("hard", "To find an angle (SSS):", ["pick the side opposite", "use $\\cos\\theta=\\frac{a^2+b^2-c^2}{2ab}$", "then apply $\\cos^{-1}$", "use the sine law"], [0, 1, 2]));
  q.push(tf("hard", "The largest angle of an $8$-$11$-$15$ triangle is about $103.1^\\circ$.", true));
  q.push(tf("hard", "A $3$-$5$-$7$ triangle has a $120^\\circ$ angle.", true));
  q.push(tf("hard", "A $9$-$12$-$15$ triangle is obtuse.", false));
  q.push(fill("hard", "$a=11$, $b=13$, $C=72^\\circ$: $c\\approx$ ___ (1 dp).", ["14.2"]));
  q.push(fill("hard", "The largest angle of an $8$-$11$-$15$ triangle $\\approx$ ___ (1 dp, degrees).", ["103.1"]));
  q.push(fill("hard", "The largest angle of a $3$-$5$-$7$ triangle = ___ (degrees).", ["120"]));
  q.push(num("hard", "$a=11$, $b=13$, $C=72^\\circ$: $c\\approx$ ___ (1 dp).", 14.2, 0.2));
  q.push(num("hard", "The largest angle of a $3$-$5$-$7$ triangle = ___ (degrees).", 120, 0));
  q.push(num("hard", "The smallest angle of a $6$-$8$-$9$ triangle $\\approx$ ___ (1 dp, degrees).", 40.8, 0.3));
  q.push(order("hard", "Order the steps to find an angle (SSS) with the cosine law.", ["Identify the side opposite the wanted angle", "Write $\\cos\\theta=\\frac{a^2+b^2-c^2}{2ab}$", "Compute the value", "Apply $\\cos^{-1}$"]));
  q.push(match("hard", "Match each triangle to its largest angle.", ["$3$-$5$-$7$", "$9$-$12$-$15$", "$4$-$5$-$6$"], ["$120^\\circ$", "$90^\\circ$", "$\\approx82.8^\\circ$"], [0, 1, 2]));
  return q;
}

// ── 7.3 Choosing the Right Law ───────────────────────────────
function g73() {
  const q = [];
  q.push(mc("easy", "Given $A$, $B$, $a$, use:", ["the sine law", "the cosine law", "the Pythagorean theorem", "neither"], 0));
  q.push(mc("easy", "Given $a$, $b$, $C$ (SAS), use:", ["the cosine law", "the sine law", "the slope", "the area"], 0));
  q.push(mc("easy", "Given $a$, $b$, $c$ (SSS), use:", ["the cosine law", "the sine law", "SOH CAH TOA", "neither"], 0));
  q.push(mc("easy", "Given $A$, $a$, $b$ (SSA), use:", ["the sine law", "the cosine law", "the Pythagorean theorem", "the area"], 0));
  q.push(mc("easy", "For a right triangle, the simplest tool is:", ["SOH CAH TOA", "the cosine law", "the sine law", "the midpoint"], 0));
  q.push(mc("easy", "After finding one part, the easiest law for the rest is often:", ["the sine law", "the cosine law again", "the area", "neither"], 0));
  q.push(ms("easy", "The sine law fits:", ["AAS", "ASA", "SSA", "SAS"], [0, 1, 2]));
  q.push(ms("easy", "The cosine law fits:", ["SAS", "SSS", "a side from two sides + angle", "AAS"], [0, 1, 2]));
  q.push(ms("easy", "To choose a law:", ["check what is given", "match to AAS/ASA/SSA or SAS/SSS", "sine for a side + opposite angle", "guess"], [0, 1, 2]));
  q.push(ms("easy", "Right triangles can also use:", ["SOH CAH TOA", "the Pythagorean theorem", "inverse trig", "the sine/cosine laws too"], [0, 1, 2, 3]));
  q.push(tf("easy", "SSS calls for the cosine law.", true));
  q.push(tf("easy", "A side with its opposite angle calls for the sine law.", true));
  q.push(tf("easy", "SAS calls for the sine law.", false));
  q.push(fill("easy", "Given $a$, $b$, $C$, use the ___ law.", ["cosine"]));
  q.push(fill("easy", "Given $A$, $B$, $a$, use the ___ law.", ["sine"]));
  q.push(fill("easy", "Given $a$, $b$, $c$, use the ___ law.", ["cosine"]));
  q.push(num("easy", "SAS $a=6$, $b=8$, $C=60^\\circ$: $c^2=36+64-96\\cos 60^\\circ=$ ___.", 52, 0));
  q.push(num("easy", "$A=40^\\circ$, $B=60^\\circ$, $a=10$: $b=\\frac{10\\sin 60^\\circ}{\\sin 40^\\circ}\\approx$ ___ (1 dp).", 13.5, 0.1));
  q.push(num("easy", "The largest angle of a $5$-$6$-$7$ triangle $\\approx$ ___ (1 dp, degrees).", 78.5, 0.3));
  q.push(match("easy", "Match each given info to its law.", ["$A,B,a$", "$a,b,C$", "$a,b,c$"], ["sine law", "cosine law", "cosine law"], [0, 1, 2]));
  q.push(mc("medium", "Which law for $b$, $c$, $A$?", ["cosine", "sine", "Pythagorean", "neither"], 0));
  q.push(mc("medium", "Solve $a=7$, $b=9$, $C=55^\\circ$ for $c$ (1 dp):", ["$\\approx7.6$", "$\\approx10.3$", "$\\approx5.2$", "$\\approx12$"], 0));
  q.push(mc("medium", "Solve $A=35^\\circ$, $B=70^\\circ$, $a=12$ for $b$ (1 dp):", ["$\\approx19.7$", "$\\approx6.5$", "$\\approx12$", "$\\approx9.0$"], 0));
  q.push(mc("medium", "The largest angle of a $4$-$6$-$8$ triangle (1 dp):", ["$\\approx104.5^\\circ$", "$\\approx75.5^\\circ$", "$\\approx90^\\circ$", "$\\approx120^\\circ$"], 0));
  q.push(mc("medium", "Solve $A=50^\\circ$, $a=12$, $b=9$ for $B$ (1 dp):", ["$\\approx35.1^\\circ$", "$\\approx54.9^\\circ$", "$\\approx40^\\circ$", "$\\approx60^\\circ$"], 0));
  q.push(mc("medium", "Given ASA $A=30^\\circ$, $B=70^\\circ$, $c=10$: which law (after $C=80^\\circ$)?", ["sine", "cosine", "Pythagorean", "neither"], 0));
  q.push(ms("medium", "The sine-law cases:", ["AAS", "ASA", "SSA", "SAS"], [0, 1, 2]));
  q.push(ms("medium", "The cosine-law cases:", ["SAS", "SSS", "a side from two sides + included angle", "ASA"], [0, 1, 2]));
  q.push(ms("medium", "To solve $a=7$, $b=9$, $C=55^\\circ$:", ["it is SAS", "cosine law for $c$", "$c^2=130-126\\cos 55^\\circ$", "sine law"], [0, 1, 2]));
  q.push(ms("medium", "To solve $A=50^\\circ$, $a=12$, $b=9$:", ["it is SSA", "sine law for $B$", "$\\sin B=\\frac{9\\sin 50^\\circ}{12}$", "cosine law"], [0, 1, 2]));
  q.push(tf("medium", "SAS uses the cosine law to find the third side.", true));
  q.push(tf("medium", "After finding the third angle of an ASA triangle, the sine law finds the sides.", true));
  q.push(tf("medium", "SSS uses the sine law to find an angle.", false));
  q.push(fill("medium", "Given $a=9$, $b=7$, $C=110^\\circ$, use the ___ law.", ["cosine"]));
  q.push(fill("medium", "Given $A=40^\\circ$, $B=60^\\circ$, $a=10$, use the ___ law.", ["sine"]));
  q.push(fill("medium", "Solve $a=7$, $b=9$, $C=55^\\circ$: $c\\approx$ ___ (1 dp).", ["7.6"]));
  q.push(num("medium", "Solve $a=7$, $b=9$, $C=55^\\circ$: $c\\approx$ ___ (1 dp).", 7.6, 0.2));
  q.push(num("medium", "Solve $A=35^\\circ$, $B=70^\\circ$, $a=12$: $b\\approx$ ___ (1 dp).", 19.7, 0.2));
  q.push(num("medium", "The largest angle of a $4$-$6$-$8$ triangle $\\approx$ ___ (1 dp, degrees).", 104.5, 0.3));
  q.push(match("medium", "Match each given info to its law.", ["$b,c,A$ (SAS)", "$A,B,a$ (AAS)", "$a,b,c$ (SSS)"], ["cosine", "sine", "cosine"], [0, 1, 2]));
  q.push(mc("hard", "A triangle has $a=14$, $b=9$, $A=65^\\circ$. Find $B$ (1 dp):", ["$\\approx35.6^\\circ$", "$\\approx54.4^\\circ$", "$\\approx65^\\circ$", "$\\approx25^\\circ$"], 0));
  q.push(mc("hard", "Solve $a=9$, $b=7$, $C=110^\\circ$ for $c$ (1 dp):", ["$\\approx13.2$", "$\\approx11.5$", "$\\approx10.0$", "$\\approx16$"], 0));
  q.push(mc("hard", "Given $a=8$, $c=5$, $B=95^\\circ$, find $b$ (1 dp):", ["$\\approx9.8$", "$\\approx7.2$", "$\\approx12$", "$\\approx5.0$"], 0));
  q.push(mc("hard", "The largest angle of a $5$-$6$-$7$ triangle (1 dp):", ["$\\approx78.5^\\circ$", "$\\approx57.1^\\circ$", "$\\approx90^\\circ$", "$\\approx101.5^\\circ$"], 0));
  q.push(mc("hard", "Solve $A=30^\\circ$, $B=70^\\circ$, $c=10$ for $a$ ($C=80^\\circ$, 1 dp):", ["$\\approx5.1$", "$\\approx10$", "$\\approx7.7$", "$\\approx9.4$"], 0));
  q.push(ms("hard", "For $a=14$, $b=9$, $A=65^\\circ$:", ["it is SSA", "sine law", "$\\sin B=\\frac{9\\sin 65^\\circ}{14}$", "$B\\approx35.6^\\circ$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Two-step solving:", ["choose the first law from the given info", "find one unknown", "then often the sine law", "ignore the angle sum"], [0, 1, 2]));
  q.push(ms("hard", "Which require the cosine law first?", ["SAS", "SSS", "$a,b,C$", "$A,B,a$"], [0, 1, 2]));
  q.push(ms("hard", "Which require the sine law?", ["AAS", "ASA", "SSA", "SSS"], [0, 1, 2]));
  q.push(tf("hard", "For $a=14$, $b=9$, $A=65^\\circ$, the sine law gives $B\\approx35.6^\\circ$.", true));
  q.push(tf("hard", "SAS and SSS both use the cosine law.", true));
  q.push(tf("hard", "$a=9$, $b=7$, $C=110^\\circ$ gives $c\\approx11.5$.", false));
  q.push(fill("hard", "Given $a=8$, $c=5$, $B=95^\\circ$, use the ___ law to find $b$.", ["cosine"]));
  q.push(fill("hard", "Solve $a=9$, $b=7$, $C=110^\\circ$: $c\\approx$ ___ (1 dp).", ["13.2"]));
  q.push(fill("hard", "Solve $a=14$, $b=9$, $A=65^\\circ$: $B\\approx$ ___ (1 dp, degrees).", ["35.6"]));
  q.push(num("hard", "Solve $a=9$, $b=7$, $C=110^\\circ$: $c\\approx$ ___ (1 dp).", 13.2, 0.2));
  q.push(num("hard", "Given $a=8$, $c=5$, $B=95^\\circ$: $b\\approx$ ___ (1 dp).", 9.8, 0.2));
  q.push(num("hard", "Solve $a=14$, $b=9$, $A=65^\\circ$: $B\\approx$ ___ (1 dp, degrees).", 35.6, 0.3));
  q.push(order("hard", "Order the steps to choose and apply a law.", ["Identify what is given (AAS/ASA/SSA or SAS/SSS)", "Choose the sine or cosine law", "Set up the equation", "Solve for the unknown"]));
  q.push(match("hard", "Match each given info to its law.", ["$a,b,C$", "$a,b,c$", "$A,a,b$"], ["cosine", "cosine", "sine"], [0, 1, 2]));
  return q;
}

// ── 7.4 Applications of the Sine & Cosine Laws ───────────────
function g74() {
  const q = [];
  q.push(mc("easy", "Two roads leave a point $70^\\circ$ apart, $5$ km and $8$ km. The distance between their ends uses:", ["the cosine law", "the sine law", "SOH CAH TOA", "the midpoint"], 0));
  q.push(mc("easy", "A triangular field with three known sides — find an angle with:", ["the cosine law", "the sine law", "the area", "the slope"], 0));
  q.push(mc("easy", "To model a real triangle, first:", ["draw and label it", "guess", "measure the area", "ignore the angles"], 0));
  q.push(mc("easy", "Bearings and directions become the triangle's:", ["angles", "areas", "midpoints", "slopes"], 0));
  q.push(mc("easy", "Two ships leave port at an angle; their distance apart uses:", ["the cosine law (SAS)", "the sine law (AAS)", "the Pythagorean theorem only", "neither"], 0));
  q.push(mc("easy", "A surveying baseline with two angles to a point uses:", ["the sine law", "the cosine law", "the area", "the slope"], 0));
  q.push(ms("easy", "Real triangle problems include:", ["surveying", "navigation", "design / structures", "coin counting"], [0, 1, 2]));
  q.push(ms("easy", "To solve an application:", ["sketch the triangle", "label the knowns", "choose a law", "state units"], [0, 1, 2, 3]));
  q.push(ms("easy", "SAS situations (cosine law):", ["two roads + the angle between", "two sides + included angle", "two ships + course angle", "three angles"], [0, 1, 2]));
  q.push(ms("easy", "The sine law fits:", ["a side with its opposite angle", "baseline + two angles", "AAS / ASA", "SSS"], [0, 1, 2]));
  q.push(tf("easy", "Many real problems form non-right triangles needing the sine/cosine laws.", true));
  q.push(tf("easy", "You should state the final answer with units.", true));
  q.push(tf("easy", "The cosine law only works on right triangles.", false));
  q.push(fill("easy", "Two roads $70^\\circ$ apart, $5$ and $8$ km: use the ___ law.", ["cosine"]));
  q.push(fill("easy", "Three known sides of a field: use the ___ law to find an angle.", ["cosine"]));
  q.push(fill("easy", "A baseline with two angles to a point: use the ___ law.", ["sine"]));
  q.push(num("easy", "Two roads $70^\\circ$ apart, $5$ and $8$ km: $c^2=25+64-80\\cos 70^\\circ\\approx$ ___ (1 dp).", 61.6, 0.3));
  q.push(num("easy", "A triangle sides $7$, $9$, included $80^\\circ$: third side $\\approx$ ___ (1 dp).", 10.4, 0.2));
  q.push(num("easy", "Field sides $40,60,50$: angle between $40$ and $60\\approx$ ___ (1 dp, degrees).", 55.8, 0.3));
  q.push(match("easy", "Match each situation to its law.", ["two sides + angle between", "three known sides", "baseline + two angles"], ["cosine law", "cosine law", "sine law"], [0, 1, 2]));
  q.push(mc("medium", "Two roads $70^\\circ$ apart, $5$ and $8$ km. Ends are ___ km apart (1 dp):", ["$\\approx7.9$", "$\\approx9.4$", "$\\approx6.2$", "$\\approx13$"], 0));
  q.push(mc("medium", "Two ships $65^\\circ$ apart sail $30$ and $45$ km. Distance apart (1 dp):", ["$\\approx42.2$", "$\\approx53.5$", "$\\approx38.0$", "$\\approx75$"], 0));
  q.push(mc("medium", "A field $40$, $60$, $50$ m. Angle between $40$ and $60$ (1 dp):", ["$\\approx55.8^\\circ$", "$\\approx90^\\circ$", "$\\approx34.2^\\circ$", "$\\approx60^\\circ$"], 0));
  q.push(mc("medium", "From a $100$ m baseline, a point at $50^\\circ$ and $60^\\circ$. Distance from the first point (1 dp):", ["$\\approx92.2$", "$\\approx81.5$", "$\\approx100$", "$\\approx70$"], 0));
  q.push(mc("medium", "A triangle sides $7$ and $9$, included $80^\\circ$. Third side (1 dp):", ["$\\approx10.4$", "$\\approx8.2$", "$\\approx12$", "$\\approx5.6$"], 0));
  q.push(mc("medium", "A parallelogram sides $6$, $8$, angle $110^\\circ$. Longer diagonal (1 dp):", ["$\\approx11.5$", "$\\approx9.2$", "$\\approx14$", "$\\approx10$"], 0));
  q.push(ms("medium", "To solve a two-roads problem:", ["it is SAS", "cosine law", "$c^2=a^2+b^2-2ab\\cos\\theta$", "sine law"], [0, 1, 2]));
  q.push(ms("medium", "A baseline-survey problem:", ["find the third angle", "sine law", "$\\frac{d}{\\sin}=\\frac{baseline}{\\sin}$", "cosine law"], [0, 1, 2]));
  q.push(ms("medium", "Navigation problems:", ["use the angle between courses", "cosine law for distance", "draw the triangle", "ignore the angle"], [0, 1, 2]));
  q.push(ms("medium", "Good steps:", ["sketch", "label", "choose a law", "units in the answer"], [0, 1, 2, 3]));
  q.push(tf("medium", "Two roads $70^\\circ$ apart at $5$ and $8$ km end about $7.9$ km apart.", true));
  q.push(tf("medium", "Two ships $65^\\circ$ apart at $30$ and $45$ km are about $42.2$ km apart.", true));
  q.push(tf("medium", "Navigation distance problems (SAS) use the sine law.", false));
  q.push(fill("medium", "Two roads $70^\\circ$ apart, $5$ and $8$ km: ends $\\approx$ ___ km (1 dp).", ["7.9"]));
  q.push(fill("medium", "A field $40,60,50$: angle between $40$ and $60\\approx$ ___ (1 dp, degrees).", ["55.8"]));
  q.push(fill("medium", "A triangle sides $7,9$, included $80^\\circ$: third side $\\approx$ ___ (1 dp).", ["10.4"]));
  q.push(num("medium", "Two ships $65^\\circ$ apart, $30$ and $45$ km: distance $\\approx$ ___ km (1 dp).", 42.2, 0.3));
  q.push(num("medium", "From a $100$ m baseline, point at $50^\\circ$ and $60^\\circ$: distance from first $\\approx$ ___ m (1 dp).", 92.2, 0.5));
  q.push(num("medium", "A parallelogram $6$, $8$, angle $110^\\circ$: longer diagonal $\\approx$ ___ (1 dp).", 11.5, 0.2));
  q.push(match("medium", "Match each problem to its answer.", ["two roads $70^\\circ$, $5$ \\& $8$ km", "field $40,60,50$: angle", "two ships $65^\\circ$, $30$ \\& $45$ km"], ["$\\approx7.9$ km", "$\\approx55.8^\\circ$", "$\\approx42.2$ km"], [0, 1, 2]));
  q.push(mc("hard", "A plane flies $200$ km, turns $30^\\circ$, flies $150$ km. Distance from start (1 dp):", ["$\\approx338.3$", "$\\approx250$", "$\\approx111.8$", "$\\approx400$"], 0));
  q.push(mc("hard", "A triangular plot sides $10$, $14$, $18$ m. Largest angle (1 dp):", ["$\\approx95.7^\\circ$", "$\\approx84.3^\\circ$", "$\\approx90^\\circ$", "$\\approx120^\\circ$"], 0));
  q.push(mc("hard", "A boat sails $12$ km, turns to an interior angle $100^\\circ$, sails $18$ km. Distance from start (1 dp):", ["$\\approx23.3$", "$\\approx20.1$", "$\\approx30$", "$\\approx15.5$"], 0));
  q.push(mc("hard", "From two points $80$ m apart, a landmark at $55^\\circ$ and $65^\\circ$. Distance from the first (1 dp):", ["$\\approx83.7$", "$\\approx72.5$", "$\\approx80$", "$\\approx90$"], 0));
  q.push(mc("hard", "A triangle sides $12$, $15$, included $95^\\circ$. Third side (1 dp):", ["$\\approx20.0$", "$\\approx17.4$", "$\\approx12$", "$\\approx27$"], 0));
  q.push(ms("hard", "For the plane problem:", ["interior angle $=150^\\circ$", "cosine law", "$c^2=200^2+150^2-2(200)(150)\\cos 150^\\circ$", "$c\\approx338.3$"], [0, 1, 2, 3]));
  q.push(ms("hard", "A garden with two sides + the included angle:", ["it is SAS", "cosine law for the third side", "then sine law for an angle", "sine law first"], [0, 1, 2]));
  q.push(ms("hard", "Largest-angle problems (SSS):", ["opposite the longest side", "cosine law", "$\\cos<0$ if obtuse", "sine law"], [0, 1, 2]));
  q.push(ms("hard", "Surveying with a baseline:", ["sine law", "find the third angle", "$\\frac{d}{\\sin}=\\frac{b}{\\sin}$", "cosine law"], [0, 1, 2]));
  q.push(tf("hard", "A plane flying $200$ km then $150$ km after a $30^\\circ$ turn is about $338$ km from the start.", true));
  q.push(tf("hard", "A $10$-$14$-$18$ m plot has its largest angle ($\\approx95.7^\\circ$) opposite the $18$ m side.", true));
  q.push(tf("hard", "A triangle with sides $12$, $15$ and included angle $95^\\circ$ has a third side of about $12$.", false));
  q.push(fill("hard", "A plane $200$ km, turn $30^\\circ$, $150$ km: distance from start $\\approx$ ___ km (1 dp).", ["338.3"]));
  q.push(fill("hard", "A $10$-$14$-$18$ m plot: largest angle $\\approx$ ___ (1 dp, degrees).", ["95.7"]));
  q.push(fill("hard", "A triangle sides $12$, $15$, included $95^\\circ$: third side $\\approx$ ___ (1 dp).", ["20.0", "20"]));
  q.push(num("hard", "A boat $12$ km, interior angle $100^\\circ$, $18$ km: distance from start $\\approx$ ___ km (1 dp).", 23.3, 0.3));
  q.push(num("hard", "From an $80$ m baseline, landmark at $55^\\circ$ and $65^\\circ$: distance from first $\\approx$ ___ m (1 dp).", 83.7, 0.5));
  q.push(num("hard", "A garden two sides $25$, $30$, angle $95^\\circ$: third side $\\approx$ ___ m (1 dp).", 40.7, 0.4));
  q.push(order("hard", "Order the steps to solve a navigation problem.", ["Sketch and label the triangle", "Find the interior angle", "Apply the cosine law", "Compute the distance"]));
  q.push(match("hard", "Match each application to its answer.", ["plane $200$,$150$, turn $30^\\circ$", "plot $10,14,18$: largest angle", "triangle $12,15$, incl $95^\\circ$: 3rd side"], ["$\\approx338.3$ km", "$\\approx95.7^\\circ$", "$\\approx20.0$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "7.1", gen: g71 },
  { code: "7.2", gen: g72 },
  { code: "7.3", gen: g73 },
  { code: "7.4", gen: g74 },
];
