// MBF3C Unit 5 — Data Management: question bank (60 per topic). Authored fresh.
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 5.1 Collecting & Displaying Data ─────────────────────────
function g51() {
  const q = [];
  q.push(mc("easy", "A population is:", ["everyone of interest", "the part surveyed", "a graph", "the average"], 0));
  q.push(mc("easy", "A sample is:", ["the part surveyed", "everyone of interest", "a circle graph", "the mode"], 0));
  q.push(mc("easy", "Choosing every k-th member is:", ["systematic", "simple random", "stratified", "biased"], 0));
  q.push(mc("easy", "Best graph for parts of a whole:", ["circle", "bar", "scatter", "histogram"], 0));
  q.push(mc("easy", "Best graph to compare categories:", ["bar", "circle", "scatter", "line"], 0));
  q.push(mc("easy", "25% of 360° is:", ["90°", "25°", "36°", "180°"], 0));
  q.push(ms("easy", "Sampling methods include:", ["simple random", "systematic", "stratified", "biased"], [0, 1, 2]));
  q.push(ms("easy", "A biased sample:", ["is not representative", "over- or under-represents groups", "can mislead", "is always random"], [0, 1, 2]));
  q.push(ms("easy", "Choosing a graph:", ["bar ↔ categories", "circle ↔ parts of a whole", "scatter ↔ relationship", "circle ↔ relationship"], [0, 1, 2]));
  q.push(ms("easy", "Population vs sample:", ["population = all", "sample = part", "sample ⊂ population", "sample > population"], [0, 1, 2]));
  q.push(tf("easy", "A sample is smaller than the population.", true));
  q.push(tf("easy", "Systematic sampling picks every k-th member.", true));
  q.push(tf("easy", "A circle graph is best for a relationship between two variables.", false));
  q.push(fill("easy", "25% on a circle graph is how many degrees?", ["90", "90°"]));
  q.push(fill("easy", "Picking every 10th name is ___ sampling.", ["systematic"]));
  q.push(fill("easy", "A graph for parts of a whole.", ["circle", "circle graph", "pie"]));
  q.push(num("easy", "Circle-graph angle for 25%.", 90, 0));
  q.push(num("easy", "Circle-graph angle for 50%.", 180, 0));
  q.push(num("easy", "Circle-graph angle for 10%.", 36, 0));
  q.push(match("easy", "Match each goal to its graph.", ["compare categories", "parts of a whole", "relationship of two variables"], ["bar", "circle", "scatter"], [0, 1, 2]));
  q.push(mc("medium", "Circle-graph angle for 40%:", ["144°", "40°", "104°", "160°"], 0));
  q.push(mc("medium", "Surveying only at a hockey game is:", ["biased", "random", "stratified", "systematic"], 0));
  q.push(mc("medium", "Sampling each grade in proportion to its size is:", ["stratified", "systematic", "random", "biased"], 0));
  q.push(mc("medium", "Best graph for the distribution of test scores:", ["histogram", "circle", "bar", "scatter"], 0));
  q.push(mc("medium", "Circle-graph angle for 30%:", ["108°", "30°", "120°", "90°"], 0));
  q.push(mc("medium", "Drawing names from a hat is:", ["simple random", "systematic", "stratified", "biased"], 0));
  q.push(ms("medium", "Stratified sampling:", ["splits into groups", "samples each in proportion", "is representative", "ignores groups"], [0, 1, 2]));
  q.push(ms("medium", "Circle-graph angle:", ["percent × 360°", "40% → 144°", "decimal × 360°", "percent × 180°"], [0, 1, 2]));
  q.push(ms("medium", "Avoiding bias:", ["sample broadly", "select randomly", "stay representative", "survey one group"], [0, 1, 2]));
  q.push(ms("medium", "Data types:", ["categorical vs numerical", "discrete vs continuous", "number of pets is discrete", "height is discrete"], [0, 1, 2]));
  q.push(tf("medium", "40% corresponds to 144° on a circle graph.", true));
  q.push(tf("medium", "Surveying at a hockey game about favourite sport is biased.", true));
  q.push(tf("medium", "Stratified sampling ignores subgroups.", false));
  q.push(fill("medium", "Circle-graph angle for 40%.", ["144", "144°"]));
  q.push(fill("medium", "Sampling each grade in proportion is ___.", ["stratified"]));
  q.push(fill("medium", "Best graph for a distribution of grouped numbers.", ["histogram"]));
  q.push(num("medium", "Circle-graph angle for 40%.", 144, 0));
  q.push(num("medium", "Circle-graph angle for 75%.", 270, 0));
  q.push(num("medium", "Circle-graph angle for 20%.", 72, 0));
  q.push(match("medium", "Match each to its description.", ["40% on a circle", "every k-th member", "by group, in proportion"], ["144°", "systematic", "stratified"], [0, 1, 2]));
  q.push(mc("hard", "90° on a circle graph represents what percent?", ["25%", "90%", "50%", "36%"], 0));
  q.push(mc("hard", "Number of pets is which type of data?", ["discrete", "continuous", "categorical", "neither"], 0));
  q.push(mc("hard", "Which is continuous data?", ["height", "number of cars", "colour", "shoe count"], 0));
  q.push(mc("hard", "A category fills 108°. What percent is it?", ["30%", "108%", "60%", "36%"], 0));
  q.push(mc("hard", "An online-only poll mainly risks:", ["bias", "too much randomness", "too large a sample", "no problem"], 0));
  q.push(ms("hard", "From angle to percent:", ["divide the angle by 360", "90° → 25%", "the reverse of percent × 360", "angle × 360"], [0, 1, 2]));
  q.push(ms("hard", "Discrete vs continuous:", ["discrete is counted", "continuous is measured", "pets discrete", "height continuous"], [0, 1, 2, 3]));
  q.push(ms("hard", "Sources of bias:", ["a non-representative sample", "leading questions", "limited access", "a random sample"], [0, 1, 2]));
  q.push(ms("hard", "Choosing a display:", ["match the data type", "categories → bar", "two variables → scatter", "always circle"], [0, 1, 2]));
  q.push(tf("hard", "90° on a circle graph represents 25% of the data.", true));
  q.push(tf("hard", "Height is continuous data.", true));
  q.push(tf("hard", "Number of pets is continuous data.", false));
  q.push(fill("hard", "90° on a circle graph is what percent?", ["25%", "25"]));
  q.push(fill("hard", "Number of pets is ___ data.", ["discrete"]));
  q.push(fill("hard", "An online-only poll risks ___.", ["bias"]));
  q.push(num("hard", "Percent represented by 90° on a circle graph.", 25, 0));
  q.push(num("hard", "Percent represented by 180°.", 50, 0));
  q.push(num("hard", "Percent represented by 72°.", 20, 0));
  q.push(order("hard", "Order the steps to draw a 25% sector on a circle graph.", ["Write the fraction 0.25", "Multiply by 360°", "0.25 × 360 = 90°", "Draw a 90° sector"]));
  q.push(match("hard", "Match each angle to its percent.", ["90°", "180°", "72°"], ["25%", "50%", "20%"], [0, 1, 2]));
  return q;
}

// ── 5.2 Central Tendency & Spread ────────────────────────────
function g52() {
  const q = [];
  q.push(mc("easy", "The mean is:", ["sum ÷ count", "the middle value", "the most frequent", "max − min"], 0));
  q.push(mc("easy", "The median is:", ["the middle value", "sum ÷ count", "the most frequent", "the range"], 0));
  q.push(mc("easy", "The mode is:", ["the most frequent", "the middle", "the average", "the range"], 0));
  q.push(mc("easy", "The range is:", ["max − min", "sum ÷ count", "the middle", "the mode"], 0));
  q.push(mc("easy", "Mean of 2, 4, 6:", ["4", "6", "12", "2"], 0));
  q.push(mc("easy", "Mode of 3, 3, 5, 7:", ["3", "5", "7", "18"], 0));
  q.push(ms("easy", "Measures of centre:", ["mean", "median", "mode", "range"], [0, 1, 2]));
  q.push(ms("easy", "Measures of spread:", ["range", "standard deviation", "how scattered the data is", "the mean"], [0, 1, 2]));
  q.push(ms("easy", "The median:", ["is the middle when ordered", "averages the two middles if even", "resists outliers", "is the most frequent"], [0, 1, 2]));
  q.push(ms("easy", "The mean:", ["is sum ÷ count", "uses every value", "is affected by outliers", "is the middle value"], [0, 1, 2]));
  q.push(tf("easy", "The mean is the sum divided by the count.", true));
  q.push(tf("easy", "The mode is the middle value.", false));
  q.push(tf("easy", "Range = max − min.", true));
  q.push(fill("easy", "Mean of 4, 8, 6, 10, 2.", ["6"]));
  q.push(fill("easy", "Range of 5, 5, 7, 9, 9, 9, 12.", ["7"]));
  q.push(fill("easy", "Mode of 5, 5, 7, 9, 9, 9, 12.", ["9"]));
  q.push(num("easy", "Mean of 4, 8, 6, 10, 2.", 6, 0));
  q.push(num("easy", "Range of 5, 5, 7, 9, 9, 9, 12.", 7, 0));
  q.push(num("easy", "Mode of 9, 9, 9, 5, 7.", 9, 0));
  q.push(match("easy", "Match each definition.", ["sum ÷ count", "the middle", "the most frequent"], ["mean", "median", "mode"], [0, 1, 2]));
  q.push(mc("medium", "Median of 3, 7, 8, 12:", ["7.5", "8", "7", "10"], 0));
  q.push(mc("medium", "Mean of 10, 12, 14, 16, 18:", ["14", "12", "16", "70"], 0));
  q.push(mc("medium", "Median of 2, 5, 9, 11, 14, 20:", ["10", "9", "11", "12.5"], 0));
  q.push(mc("medium", "An outlier most affects the:", ["mean", "median", "mode", "minimum"], 0));
  q.push(mc("medium", "Mode and range of 4, 4, 4, 7, 9, 9, 15:", ["mode 4, range 11", "mode 9, range 7", "mode 4, range 7", "mode 7, range 11"], 0));
  q.push(mc("medium", "Mean of 3, 7, 7, 9, 14:", ["8", "7", "9", "40"], 0));
  q.push(ms("medium", "Median of an even-sized list:", ["average the two middles", "order the data first", "e.g. (7+8)/2", "take just one middle"], [0, 1, 2]));
  q.push(ms("medium", "Outliers:", ["pull the mean", "barely move the median", "make the median more typical", "pull the median"], [0, 1, 2]));
  q.push(ms("medium", "Choosing a measure:", ["categorical → mode", "skewed → median", "symmetric → mean", "always mean"], [0, 1, 2]));
  q.push(ms("medium", "The range:", ["is max − min", "measures spread", "ignores the middle values", "is a centre"], [0, 1, 2]));
  q.push(tf("medium", "The median of 3, 7, 8, 12 is 7.5.", true));
  q.push(tf("medium", "An outlier pulls the mean more than the median.", true));
  q.push(tf("medium", "For skewed incomes the mean is the best measure.", false));
  q.push(fill("medium", "Median of 3, 7, 8, 12.", ["7.5"]));
  q.push(fill("medium", "Mean of 10, 12, 14, 16, 18.", ["14"]));
  q.push(fill("medium", "Best centre for 'favourite colour'.", ["mode"]));
  q.push(num("medium", "Median of 3, 7, 8, 12.", 7.5, 0.01));
  q.push(num("medium", "Mean of 10, 12, 14, 16, 18.", 14, 0));
  q.push(num("medium", "Median of 2, 5, 9, 11, 14, 20.", 10, 0));
  q.push(match("medium", "Match each to its value.", ["median 3,7,8,12", "mean 10..18", "centre for categorical"], ["7.5", "14", "mode"], [0, 1, 2]));
  q.push(mc("hard", "Mean of 2, 3, 4, 5, 100:", ["22.8", "4", "5", "28.5"], 0));
  q.push(mc("hard", "Median of 2, 3, 4, 5, 100:", ["4", "22.8", "5", "3"], 0));
  q.push(mc("hard", "For 2, 3, 4, 5, 100, which is more typical?", ["median", "mean", "mode", "range"], 0));
  q.push(mc("hard", "Adding the value 200 to a data set will make the mean:", ["increase", "decrease", "stay the same", "double"], 0));
  q.push(mc("hard", "Two sets share a mean but have different ranges. This means they have:", ["different spread", "the same data", "no outliers", "identical graphs"], 0));
  q.push(ms("hard", "Mean vs median with an outlier:", ["mean = 22.8", "median = 4", "the median is more typical", "the mean is more typical"], [0, 1, 2]));
  q.push(ms("hard", "Effect of outliers:", ["they distort the mean", "the median resists them", "use the median for skewed data", "the median distorts"], [0, 1, 2]));
  q.push(ms("hard", "Comparing spread:", ["range shows spread", "same mean ≠ same spread", "a larger range = more scattered", "range is a centre"], [0, 1, 2]));
  q.push(ms("hard", "Standard deviation:", ["typical distance from the mean", "larger = more spread", "is a spread measure", "is a centre"], [0, 1, 2]));
  q.push(tf("hard", "For 2, 3, 4, 5, 100 the median (4) is more typical than the mean.", true));
  q.push(tf("hard", "Two sets can share a mean but differ in spread.", true));
  q.push(tf("hard", "Adding a large outlier leaves the mean unchanged.", false));
  q.push(fill("hard", "Median of 2, 3, 4, 5, 100.", ["4"]));
  q.push(fill("hard", "Mean of 2, 3, 4, 5, 100.", ["22.8"]));
  q.push(fill("hard", "The measure that resists outliers.", ["median"]));
  q.push(num("hard", "Mean of 2, 3, 4, 5, 100.", 22.8, 0.1));
  q.push(num("hard", "Median of 2, 3, 4, 5, 100.", 4, 0));
  q.push(num("hard", "Range of 2, 3, 4, 5, 100.", 98, 0));
  q.push(order("hard", "Order the steps to find the median of 12, 3, 8, 7.", ["Order: 3, 7, 8, 12", "Even count → two middles 7, 8", "Average: (7+8)/2", "Median = 7.5"]));
  q.push(match("hard", "Match each to its value (data 2,3,4,5,100).", ["mean", "median", "range"], ["22.8", "4", "98"], [0, 1, 2]));
  return q;
}

// ── 5.3 Probability ──────────────────────────────────────────
function g53() {
  const q = [];
  q.push(mc("easy", "Theoretical probability is:", ["favourable ÷ total", "successes ÷ trials", "total ÷ favourable", "1 − P"], 0));
  q.push(mc("easy", "P(rolling a 4 on a die):", ["1/6", "1/4", "1/2", "4/6"], 0));
  q.push(mc("easy", "Probabilities range from:", ["0 to 1", "−1 to 1", "1 to 6", "0 to 100"], 0));
  q.push(mc("easy", "P(even number on a die):", ["1/2", "1/3", "1/6", "2/3"], 0));
  q.push(mc("easy", "P(a certain event):", ["1", "0", "0.5", "100"], 0));
  q.push(mc("easy", "P(an impossible event):", ["0", "1", "0.5", "−1"], 0));
  q.push(ms("easy", "Theoretical probability:", ["favourable ÷ total", "assumes equally likely outcomes", "e.g. P(4)=1/6", "successes ÷ trials"], [0, 1, 2]));
  q.push(ms("easy", "The probability scale:", ["0 means impossible", "1 means certain", "values lie between 0 and 1", "values can exceed 1"], [0, 1, 2]));
  q.push(ms("easy", "A fair die:", ["has 6 outcomes", "each has P=1/6", "P(even)=1/2", "each has P=1/2"], [0, 1, 2]));
  q.push(ms("easy", "The complement rule:", ["P(not A)=1−P(A)", "probabilities sum to 1", "is a useful shortcut", "P(not A)=P(A)"], [0, 1, 2]));
  q.push(tf("easy", "P of rolling a 4 is 1/6.", true));
  q.push(tf("easy", "A probability can be greater than 1.", false));
  q.push(tf("easy", "P(even on a die) = 1/2.", true));
  q.push(fill("easy", "P of rolling a 4 on a die.", ["1/6"]));
  q.push(fill("easy", "P of an even number on a die.", ["1/2"]));
  q.push(fill("easy", "P of a certain event.", ["1"]));
  q.push(num("easy", "P of rolling a 4 on a die (decimal, 3 dp).", 0.167, 0.01));
  q.push(num("easy", "Number of outcomes when rolling a die.", 6, 0));
  q.push(num("easy", "P of an even number on a die (decimal).", 0.5, 0.01));
  q.push(match("easy", "Match each to its probability.", ["a 4 on a die", "an even number", "a certain event"], ["1/6", "1/2", "1"], [0, 1, 2]));
  q.push(mc("medium", "P(not rolling a 4):", ["5/6", "1/6", "4/6", "1"], 0));
  q.push(mc("medium", "P(red card from a deck):", ["1/2", "1/4", "13/52", "1/13"], 0));
  q.push(mc("medium", "P(number less than 3 on a die):", ["1/3", "1/2", "2/3", "1/6"], 0));
  q.push(mc("medium", "If P(rain) = 0.3, then P(no rain) =", ["0.7", "0.3", "1", "0.5"], 0));
  q.push(mc("medium", "30 heads in 50 flips: experimental P(heads):", ["0.6", "0.5", "0.3", "0.05"], 0));
  q.push(mc("medium", "P(two heads in a row):", ["1/4", "1/2", "1", "1/8"], 0));
  q.push(ms("medium", "The complement:", ["P(not 4)=1−1/6", "= 5/6", "is 1−P(A)", "= 1/6"], [0, 1, 2]));
  q.push(ms("medium", "Experimental probability:", ["successes ÷ trials", "30/50 = 0.6", "comes from data", "always equals theoretical"], [0, 1, 2]));
  q.push(ms("medium", "Independent events:", ["multiply", "P(A)×P(B)", "heads & heads = 1/4", "add them"], [0, 1, 2]));
  q.push(ms("medium", "A standard deck:", ["has 52 cards", "26 are red", "P(red)=1/2", "13 are red"], [0, 1, 2]));
  q.push(tf("medium", "P(not rolling a 4) = 5/6.", true));
  q.push(tf("medium", "For independent events you multiply the probabilities.", true));
  q.push(tf("medium", "Experimental probability always equals theoretical.", false));
  q.push(fill("medium", "P of not rolling a 4.", ["5/6"]));
  q.push(fill("medium", "P of two heads in a row.", ["1/4"]));
  q.push(fill("medium", "P(no rain) if P(rain) = 0.3.", ["0.7"]));
  q.push(num("medium", "Experimental P from 30 heads in 50 flips.", 0.6, 0.01));
  q.push(num("medium", "P of two heads in a row (decimal).", 0.25, 0.01));
  q.push(num("medium", "P(no rain) if P(rain) = 0.3.", 0.7, 0.01));
  q.push(match("medium", "Match each to its probability.", ["not a 4", "two heads", "a red card"], ["5/6", "1/4", "1/2"], [0, 1, 2]));
  q.push(mc("hard", "P(a 6 then another 6):", ["1/36", "1/12", "1/6", "2/6"], 0));
  q.push(mc("hard", "A bag has 3 red and 7 blue. P(red):", ["3/10", "7/10", "3/7", "1/3"], 0));
  q.push(mc("hard", "P(heads then a 3 on a die):", ["1/12", "1/8", "1/6", "1/2"], 0));
  q.push(mc("hard", "P(two even numbers in a row):", ["1/4", "1/2", "1/3", "1/6"], 0));
  q.push(mc("hard", "With replacement, P(red then red) from 4 red of 11:", ["16/121", "4/11", "8/22", "16/22"], 0));
  q.push(ms("hard", "Compound independent events:", ["P(A and B)=P(A)P(B)", "6 then 6 = 1/36", "needs independence", "just add"], [0, 1, 2]));
  q.push(ms("hard", "Drawing with replacement:", ["probabilities stay the same", "multiply across draws", "P(red,red)=P(red)²", "subtract one each time"], [0, 1, 2]));
  q.push(ms("hard", "Mixed events (coin & die):", ["P(H)×P(3)", "= 1/2 × 1/6", "= 1/12", "= 1/8"], [0, 1, 2]));
  q.push(ms("hard", "With many trials:", ["experimental → theoretical", "law of large numbers", "closer with more trials", "always exact"], [0, 1, 2]));
  q.push(tf("hard", "P(a 6 then another 6) = 1/36.", true));
  q.push(tf("hard", "P(two even numbers in a row) = 1/4.", true));
  q.push(tf("hard", "P(heads then a 3) = 1/8.", false));
  q.push(fill("hard", "P of rolling a 6 then a 6.", ["1/36"]));
  q.push(fill("hard", "P(red) from 3 red, 7 blue.", ["3/10"]));
  q.push(fill("hard", "P of two even rolls in a row.", ["1/4"]));
  q.push(num("hard", "P(6 then 6) — the denominator of the fraction 1/?.", 36, 0));
  q.push(num("hard", "P of two heads (decimal).", 0.25, 0.01));
  q.push(num("hard", "P(red) from 3 red, 7 blue (decimal).", 0.3, 0.01));
  q.push(order("hard", "Order the steps to find P(a 6 then a 6).", ["P(6) = 1/6", "Independent → multiply", "1/6 × 1/6", "= 1/36"]));
  q.push(match("hard", "Match each to its probability.", ["6 then 6", "red from 3r/7b", "two evens"], ["1/36", "3/10", "1/4"], [0, 1, 2]));
  return q;
}

export default [
  { code: "5.1", gen: g51 },
  { code: "5.2", gen: g52 },
  { code: "5.3", gen: g53 },
];
