// MCR3U Unit 1 — Characteristics of Functions: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 1.1 Functions, Relations & Function Notation ─────────────
function g11() {
  const q = [];
  q.push(mc("easy", "Evaluate $f(x)=2x+3$ at $x=4$.", ["$11$", "$14$", "$10$", "$7$"], 0));
  q.push(mc("easy", "Evaluate $f(x)=x^2-1$ at $x=3$.", ["$8$", "$5$", "$9$", "$10$"], 0));
  q.push(mc("easy", "Evaluate $f(x)=5-2x$ at $x=1$.", ["$3$", "$7$", "$-3$", "$2$"], 0));
  q.push(mc("easy", "Which is a function?", ["$y=2x+1$", "$x=y^2$", "a circle", "$x=3$"], 0));
  q.push(mc("easy", "$f(x)$ means:", ["the output at $x$", "$f$ times $x$", "the input", "the slope"], 0));
  q.push(mc("easy", "Evaluate $f(x)=x^2$ at $x=-3$.", ["$9$", "$-9$", "$6$", "$-6$"], 0));
  q.push(ms("easy", "Which are functions?", ["$y=3x$", "$y=x^2$", "$x=y^2$", "$y=|x|$"], [0, 1, 3]));
  q.push(ms("easy", "For $f(x)=x^2-4$:", ["$f(2)=0$", "$f(0)=-4$", "$f(3)=5$", "$f(1)=4$"], [0, 1, 2]));
  q.push(ms("easy", "The vertical-line test:", ["checks if it is a function", "a vertical line meets it once", "fails for $x=y^2$", "tests the range"], [0, 1, 2]));
  q.push(ms("easy", "Function notation facts:", ["$f(x)$ is the output", "substitute for $x$", "it is not multiplication", "means $f\\cdot x$"], [0, 1, 2]));
  q.push(tf("easy", "$f(x)=2x$ means double the input.", true));
  q.push(tf("easy", "$x=y^2$ is a function.", false));
  q.push(tf("easy", "$f(3)=4$ for $f(x)=x+1$.", true));
  q.push(fill("easy", "Evaluate $f(x)=3x-2$ at $x=5$.", ["13"]));
  q.push(fill("easy", "Evaluate $f(x)=x^2+1$ at $x=4$.", ["17"]));
  q.push(fill("easy", "Evaluate $f(x)=10-x$ at $x=6$.", ["4"]));
  q.push(num("easy", "$f(x)=2x^2$ at $x=3$.", 18, 0));
  q.push(num("easy", "$f(x)=4x-7$ at $x=2$.", 1, 0));
  q.push(num("easy", "$f(x)=x^2-2x$ at $x=5$.", 15, 0));
  q.push(match("easy", "Match each $f$ to $f(2)$.", ["$f(x)=x+3$", "$f(x)=2x$", "$f(x)=x^2$"], ["$5$", "$4$", "$4$"], [0, 1, 2]));
  q.push(mc("medium", "$f(x)=2x^2+3x-1$ at $x=2$.", ["$13$", "$9$", "$7$", "$15$"], 0));
  q.push(mc("medium", "$f(x)=2x^2+3x-1$ at $x=-1$.", ["$-2$", "$0$", "$4$", "$-4$"], 0));
  q.push(mc("medium", "$f(x)=\\dfrac{x+1}{x-1}$ at $x=3$.", ["$2$", "$1$", "$\\tfrac12$", "$4$"], 0));
  q.push(mc("medium", "If $f(x)=x^2$, then $f(a)=$", ["$a^2$", "$2a$", "$ax$", "$a$"], 0));
  q.push(mc("medium", "$f(x)=\\sqrt{x}+1$ at $x=9$.", ["$4$", "$10$", "$3$", "$8$"], 0));
  q.push(mc("medium", "$f(x)=3-x^2$ at $x=-2$.", ["$-1$", "$7$", "$1$", "$-7$"], 0));
  q.push(ms("medium", "For $f(x)=2x+1$:", ["$f(0)=1$", "$f(3)=7$", "$f(-1)=-1$", "$f(2)=6$"], [0, 1, 2]));
  q.push(ms("medium", "Which equal $9$ for $f(x)=x^2$?", ["$f(3)$", "$f(-3)$", "$f(9)$", "$|f(3)|$"], [0, 1, 3]));
  q.push(ms("medium", "Evaluating $f(x)=2x^2+3x-1$ at $x=2$:", ["$2(4)=8$", "$3(2)=6$", "$8+6-1=13$", "result $9$"], [0, 1, 2]));
  q.push(ms("medium", "A relation is a function if:", ["each input maps to one output", "it passes the vertical-line test", "it is one-to-one or many-to-one", "it is one-to-many"], [0, 1, 2]));
  q.push(tf("medium", "$f(-1)=-2$ for $f(x)=2x^2+3x-1$.", true));
  q.push(tf("medium", "$f(x)=x^2$ gives $f(-3)=f(3)$.", true));
  q.push(tf("medium", "$f(x)=\\dfrac{1}{x}$ is defined at $x=0$.", false));
  q.push(fill("medium", "$f(x)=2x^2+3x-1$ at $x=2$.", ["13"]));
  q.push(fill("medium", "$f(x)=x^2-5x$ at $x=-2$.", ["14"]));
  q.push(fill("medium", "$f(x)=\\sqrt{x-1}$ at $x=10$.", ["3"]));
  q.push(num("medium", "$f(x)=2x^2+3x-1$ at $x=-1$.", -2, 0));
  q.push(num("medium", "$f(x)=x^2-2x+4$ at $x=3$.", 7, 0));
  q.push(num("medium", "$f(x)=\\dfrac{12}{x}$ at $x=4$.", 3, 0));
  q.push(match("medium", "Match each $f$ to $f(-1)$.", ["$f(x)=x^2$", "$f(x)=2x+1$", "$f(x)=x^3$"], ["$1$", "$-1$", "$-1$"], [0, 1, 2]));
  q.push(mc("hard", "$f(x)=x^2-3x$; find $f(a+1)$.", ["$a^2-a-2$", "$a^2-3a$", "$a^2+a$", "$a^2-2$"], 0));
  q.push(mc("hard", "$f(x)=2x-5$; solve $f(x)=11$.", ["$8$", "$3$", "$13$", "$6$"], 0));
  q.push(mc("hard", "$f(x)=x^2$; $f(x)=49$ gives $x=$", ["$\\pm7$", "$7$", "$24.5$", "$\\pm49$"], 0));
  q.push(mc("hard", "If $f(2)=7$ and $f(x)=ax+1$, then $a=$", ["$3$", "$2$", "$4$", "$\\tfrac72$"], 0));
  q.push(mc("hard", "$f(g(x))$ with $f(x)=x+1,\\ g(x)=2x$:", ["$2x+1$", "$2x+2$", "$2(x+1)$", "$x+2$"], 0));
  q.push(ms("hard", "For $f(x)=x^2-3x$:", ["$f(0)=0$", "$f(3)=0$", "$f(1)=-2$", "$f(2)=2$"], [0, 1, 2]));
  q.push(ms("hard", "Solving $f(x)=11$ for $f(x)=2x-5$:", ["$2x=16$", "$x=8$", "check $f(8)=11$", "$x=3$"], [0, 1, 2]));
  q.push(ms("hard", "Which give $x=\\pm7$?", ["$x^2=49$", "$f(x)=49$ for $f=x^2$", "$|x|=7$", "$x=49$"], [0, 1, 2]));
  q.push(ms("hard", "Composition $f(g(x))$:", ["substitute $g$ into $f$", "inner function first", "order matters", "it is multiplication"], [0, 1, 2]));
  q.push(tf("hard", "$f(x)=x^2-3x$ gives $f(a+1)=a^2-a-2$.", true));
  q.push(tf("hard", "Solving $2x-5=11$ gives $x=8$.", true));
  q.push(tf("hard", "$f(g(x))=g(f(x))$ always.", false));
  q.push(fill("hard", "$f(x)=x^2-3x$; $f(4)=$", ["4"]));
  q.push(fill("hard", "$f(x)=2x-5$; solve $f(x)=11$: $x=$", ["8"]));
  q.push(fill("hard", "$f(x)=x+1,\\ g(x)=2x$; $f(g(3))=$", ["7"]));
  q.push(num("hard", "$f(x)=x^2-3x$ at $x=5$.", 10, 0));
  q.push(num("hard", "Solve $3x-1=14$.", 5, 0));
  q.push(num("hard", "$f(g(2))$ with $f(x)=x+1,\\ g(x)=2x$.", 5, 0));
  q.push(order("hard", "Order the steps to evaluate $f(g(2))$ for $f(x)=x+1,\\ g(x)=2x$.", ["Find $g(2)=4$", "Substitute into $f$", "$f(4)=4+1$", "Result $5$"]));
  q.push(match("hard", "Match each to its result ($f(x)=x^2-3x$).", ["$f(0)$", "$f(3)$", "$f(4)$"], ["$0$", "$0$", "$4$"], [0, 1, 2]));
  return q;
}

// ── 1.2 Domain and Range ─────────────────────────────────────
function g12() {
  const q = [];
  q.push(mc("easy", "Domain of $f(x)=\\sqrt{x-2}$.", ["$x\\ge2$", "$x>2$", "$x\\le2$", "all reals"], 0));
  q.push(mc("easy", "Domain of $f(x)=\\dfrac{1}{x-3}$.", ["$x\\ne3$", "$x\\ge3$", "$x\\ne0$", "all reals"], 0));
  q.push(mc("easy", "Range of $f(x)=x^2$.", ["$y\\ge0$", "$y>0$", "all reals", "$y\\le0$"], 0));
  q.push(mc("easy", "Domain of $f(x)=x^2+1$.", ["all reals", "$x\\ge0$", "$x\\ne0$", "$x\\ge1$"], 0));
  q.push(mc("easy", "Range of $f(x)=x^2+3$.", ["$y\\ge3$", "$y\\ge0$", "$y>3$", "all reals"], 0));
  q.push(mc("easy", "Domain of $f(x)=\\sqrt{x}$.", ["$x\\ge0$", "$x>0$", "all reals", "$x\\le0$"], 0));
  q.push(ms("easy", "Restrictions to watch:", ["denominator $\\ne0$", "radicand $\\ge0$", "context limits", "numerator $\\ne0$"], [0, 1, 2]));
  q.push(ms("easy", "Which have domain all reals?", ["$x^2$", "$2x+1$", "$\\sqrt{x}$", "$x^3$"], [0, 1, 3]));
  q.push(ms("easy", "For $\\sqrt{x-2}$:", ["need $x-2\\ge0$", "domain $x\\ge2$", "range $y\\ge0$", "domain all reals"], [0, 1, 2]));
  q.push(ms("easy", "Range facts:", ["the set of outputs", "$x^2$ gives $y\\ge0$", "read it from a graph", "the set of inputs"], [0, 1, 2]));
  q.push(tf("easy", "$\\sqrt{x}$ has domain $x\\ge0$.", true));
  q.push(tf("easy", "$\\dfrac{1}{x}$ is defined at $x=0$.", false));
  q.push(tf("easy", "The range of $x^2$ is $y\\ge0$.", true));
  q.push(fill("easy", "Domain of $\\sqrt{x-5}$ (write like x>=5).", ["x>=5", "x \\ge 5", "x≥5"]));
  q.push(fill("easy", "Domain of $\\dfrac{1}{x+2}$ (write like x!=-2).", ["x!=-2", "x \\ne -2", "x≠-2"]));
  q.push(fill("easy", "Range of $x^2-4$ (write like y>=-4).", ["y>=-4", "y \\ge -4", "y≥-4"]));
  q.push(num("easy", "Smallest $x$ in the domain of $\\sqrt{x-7}$.", 7, 0));
  q.push(num("easy", "Value excluded from the domain of $\\dfrac{1}{x-9}$.", 9, 0));
  q.push(num("easy", "Minimum $y$ (range) of $x^2+6$.", 6, 0));
  q.push(match("easy", "Match each function to its domain.", ["$\\sqrt{x-2}$", "$\\dfrac{1}{x-3}$", "$x^2$"], ["$x\\ge2$", "$x\\ne3$", "all reals"], [0, 1, 2]));
  q.push(mc("medium", "Domain of $\\dfrac{1}{x^2-9}$.", ["$x\\ne\\pm3$", "$x\\ne3$", "$x\\ne9$", "all reals"], 0));
  q.push(mc("medium", "Range of $f(x)=-x^2+5$.", ["$y\\le5$", "$y\\ge5$", "$y\\le0$", "all reals"], 0));
  q.push(mc("medium", "Domain of $\\sqrt{2x-6}$.", ["$x\\ge3$", "$x\\ge6$", "$x\\ge-3$", "all reals"], 0));
  q.push(mc("medium", "Range of $f(x)=(x-2)^2+1$.", ["$y\\ge1$", "$y\\ge2$", "$y\\ge0$", "$y\\le1$"], 0));
  q.push(mc("medium", "Domain of $\\dfrac{x}{x^2-4}$.", ["$x\\ne\\pm2$", "$x\\ne2$", "$x\\ne4$", "all reals"], 0));
  q.push(mc("medium", "Range of $f(x)=\\sqrt{x}+3$.", ["$y\\ge3$", "$y\\ge0$", "$y>3$", "all reals"], 0));
  q.push(ms("medium", "For $-x^2+5$:", ["opens down", "maximum $5$", "range $y\\le5$", "range $y\\ge5$"], [0, 1, 2]));
  q.push(ms("medium", "Which exclude $x=2$?", ["$\\dfrac{1}{x-2}$", "$\\dfrac{x}{x^2-4}$", "$\\dfrac{1}{x+2}$", "$\\sqrt{x-2}$"], [0, 1]));
  q.push(ms("medium", "Domain of $\\sqrt{2x-6}$:", ["$2x-6\\ge0$", "$x\\ge3$", "includes $x=3$", "$x\\ge6$"], [0, 1, 2]));
  q.push(ms("medium", "Range from $(x-h)^2+k$:", ["min is $k$", "$y\\ge k$ if opens up", "$y\\le k$ if opens down", "range all reals"], [0, 1, 2]));
  q.push(tf("medium", "$\\dfrac{1}{x^2-9}$ excludes $x=\\pm3$.", true));
  q.push(tf("medium", "$(x-2)^2+1$ has range $y\\ge1$.", true));
  q.push(tf("medium", "$\\sqrt{2x-6}$ has domain $x\\ge6$.", false));
  q.push(fill("medium", "Domain of $\\sqrt{2x-6}$ (x>=).", ["x>=3", "x \\ge 3", "x≥3"]));
  q.push(fill("medium", "Range of $(x-2)^2+1$ (y>=).", ["y>=1", "y \\ge 1", "y≥1"]));
  q.push(fill("medium", "Range of $-x^2+5$ (y<=).", ["y<=5", "y \\le 5", "y≤5"]));
  q.push(num("medium", "Smallest $x$ in the domain of $\\sqrt{2x-6}$.", 3, 0));
  q.push(num("medium", "Minimum $y$ of $(x-2)^2+1$.", 1, 0));
  q.push(num("medium", "Maximum $y$ of $-x^2+5$.", 5, 0));
  q.push(match("medium", "Match each to its range.", ["$x^2+1$", "$-x^2+5$", "$(x-2)^2$"], ["$y\\ge1$", "$y\\le5$", "$y\\ge0$"], [0, 1, 2]));
  q.push(mc("hard", "Domain of $\\dfrac{\\sqrt{x-1}}{x-4}$.", ["$x\\ge1,\\ x\\ne4$", "$x\\ge1$", "$x\\ne4$", "$x>4$"], 0));
  q.push(mc("hard", "Range of $f(x)=2-\\sqrt{x}$.", ["$y\\le2$", "$y\\ge2$", "$y\\le0$", "all reals"], 0));
  q.push(mc("hard", "Domain of $\\dfrac{1}{\\sqrt{x-3}}$.", ["$x>3$", "$x\\ge3$", "$x\\ne3$", "$x>0$"], 0));
  q.push(mc("hard", "Range of $f(x)=\\dfrac{1}{x}$.", ["$y\\ne0$", "$y>0$", "all reals", "$y\\ge0$"], 0));
  q.push(mc("hard", "Domain of $f(x)=\\sqrt{9-x^2}$.", ["$-3\\le x\\le3$", "$x\\ge3$", "$x\\le3$", "all reals"], 0));
  q.push(ms("hard", "For $\\dfrac{\\sqrt{x-1}}{x-4}$:", ["need $x-1\\ge0$", "need $x\\ne4$", "domain $x\\ge1,\\ x\\ne4$", "domain all reals"], [0, 1, 2]));
  q.push(ms("hard", "Which have a maximum (not a minimum)?", ["$-x^2+5$", "$2-\\sqrt{x}$", "$x^2+1$", "$-x^2$"], [0, 1, 3]));
  q.push(ms("hard", "For $\\sqrt{9-x^2}$:", ["need $9-x^2\\ge0$", "$-3\\le x\\le3$", "range $0\\le y\\le3$", "domain all reals"], [0, 1, 2]));
  q.push(ms("hard", "Combining restrictions:", ["take the intersection", "both conditions must hold", "root and denominator together", "take the union"], [0, 1, 2]));
  q.push(tf("hard", "$\\dfrac{1}{\\sqrt{x-3}}$ needs $x>3$ (strict).", true));
  q.push(tf("hard", "$f(x)=2-\\sqrt{x}$ has range $y\\le2$.", true));
  q.push(tf("hard", "$\\sqrt{9-x^2}$ has domain all reals.", false));
  q.push(fill("hard", "Domain of $\\dfrac{1}{\\sqrt{x-3}}$ (x>).", ["x>3", "x > 3"]));
  q.push(fill("hard", "Largest $x$ in the domain of $\\sqrt{9-x^2}$.", ["3"]));
  q.push(fill("hard", "Range of $2-\\sqrt{x}$ (y<=).", ["y<=2", "y \\le 2", "y≤2"]));
  q.push(num("hard", "Smallest $x$ in the domain of $\\dfrac{\\sqrt{x-1}}{x-4}$.", 1, 0));
  q.push(num("hard", "The excluded value in $\\dfrac{\\sqrt{x-1}}{x-4}$.", 4, 0));
  q.push(num("hard", "Maximum $y$ of $\\sqrt{9-x^2}$.", 3, 0));
  q.push(order("hard", "Order the steps to find the domain of $\\dfrac{\\sqrt{x-1}}{x-4}$.", ["Radicand $\\ge0$: $x\\ge1$", "Denominator $\\ne0$: $x\\ne4$", "Combine: $x\\ge1,\\ x\\ne4$", "State the domain"]));
  q.push(match("hard", "Match each to its domain.", ["$\\sqrt{9-x^2}$", "$\\dfrac{1}{\\sqrt{x-3}}$", "$\\dfrac{1}{x-5}$"], ["$-3\\le x\\le3$", "$x>3$", "$x\\ne5$"], [0, 1, 2]));
  return q;
}

// ── 1.3 Inverse Functions ────────────────────────────────────
function g13() {
  const q = [];
  q.push(mc("easy", "Inverse of $f(x)=x+5$.", ["$x-5$", "$5-x$", "$\\tfrac{x}{5}$", "$x+5$"], 0));
  q.push(mc("easy", "Inverse of $f(x)=2x$.", ["$\\dfrac{x}{2}$", "$2x$", "$x-2$", "$\\dfrac{2}{x}$"], 0));
  q.push(mc("easy", "Inverse of $f(x)=x-3$.", ["$x+3$", "$3-x$", "$\\dfrac{x}{3}$", "$x-3$"], 0));
  q.push(mc("easy", "To find an inverse you:", ["swap $x$ and $y$, then solve", "take the reciprocal", "negate", "square"], 0));
  q.push(mc("easy", "An inverse reflects in the line:", ["$y=x$", "the $x$-axis", "the $y$-axis", "$y=0$"], 0));
  q.push(mc("easy", "Inverse of $f(x)=5x$.", ["$\\dfrac{x}{5}$", "$5x$", "$x-5$", "$\\dfrac{5}{x}$"], 0));
  q.push(ms("easy", "Steps to find an inverse:", ["write $y=f(x)$", "swap $x$ and $y$", "solve for $y$", "take the reciprocal"], [0, 1, 2]));
  q.push(ms("easy", "True about inverses:", ["reflect over $y=x$", "domain and range swap", "they undo the function", "equal the reciprocal"], [0, 1, 2]));
  q.push(ms("easy", "Which are correct inverses?", ["$x+5\\to x-5$", "$2x\\to \\tfrac{x}{2}$", "$x-3\\to x+3$", "$3x\\to \\tfrac{3}{x}$"], [0, 1, 2]));
  q.push(ms("easy", "The inverse of $f$ is a function when:", ["$f$ is one-to-one", "$f$ passes the horizontal-line test", "$f(x)=2x+1$", "$f(x)=x^2$"], [0, 1, 2]));
  q.push(tf("easy", "The inverse of $f(x)=x+5$ is $x-5$.", true));
  q.push(tf("easy", "The inverse is the reciprocal of $f$.", false));
  q.push(tf("easy", "Domain and range swap for an inverse.", true));
  q.push(fill("easy", "Inverse of $f(x)=x+8$.", ["x-8", "x - 8"]));
  q.push(fill("easy", "Inverse of $f(x)=3x$.", ["x/3", "\\dfrac{x}{3}", "x÷3"]));
  q.push(fill("easy", "Inverse of $f(x)=x-10$.", ["x+10", "x + 10"]));
  q.push(num("easy", "For $f(x)=2x+3$, find $f^{-1}(7)$.", 2, 0));
  q.push(num("easy", "For $f(x)=x-4$, find $f^{-1}(10)$.", 14, 0));
  q.push(num("easy", "For $f(x)=5x$, find $f^{-1}(20)$.", 4, 0));
  q.push(match("easy", "Match each $f$ to its inverse.", ["$x+5$", "$2x$", "$x-3$"], ["$x-5$", "$\\tfrac{x}{2}$", "$x+3$"], [0, 1, 2]));
  q.push(mc("medium", "Inverse of $f(x)=2x+3$.", ["$\\dfrac{x-3}{2}$", "$\\dfrac{x+3}{2}$", "$2x-3$", "$\\dfrac{x}{2}+3$"], 0));
  q.push(mc("medium", "Inverse of $f(x)=3x-6$.", ["$\\dfrac{x+6}{3}$", "$\\dfrac{x-6}{3}$", "$3x+6$", "$\\dfrac{x}{3}-6$"], 0));
  q.push(mc("medium", "Inverse of $f(x)=\\dfrac{x}{2}+1$.", ["$2x-2$", "$2(x+1)$", "$\\dfrac{x-1}{2}$", "$2x+2$"], 0));
  q.push(mc("medium", "Inverse of $f(x)=4x-1$.", ["$\\dfrac{x+1}{4}$", "$\\dfrac{x-1}{4}$", "$4x+1$", "$\\dfrac{x}{4}+1$"], 0));
  q.push(mc("medium", "Is the inverse of $f(x)=x^2$ (all reals) a function?", ["No", "Yes", "only the $x\\ge0$ part is", "always"], 0));
  q.push(mc("medium", "Inverse of $f(x)=-x+4$.", ["$4-x$", "$x-4$", "$-x-4$", "$x+4$"], 0));
  q.push(ms("medium", "Finding the inverse of $2x+3$:", ["$y=2x+3$", "swap: $x=2y+3$", "solve $y=\\tfrac{x-3}{2}$", "$y=2x-3$"], [0, 1, 2]));
  q.push(ms("medium", "Which need a domain restriction for a function inverse?", ["$x^2$", "$x^4$", "$(x-1)^2$", "$2x+1$"], [0, 1, 2]));
  q.push(ms("medium", "Checking an inverse:", ["$f(f^{-1}(x))=x$", "compose them", "should return $x$", "multiply them"], [0, 1, 2]));
  q.push(ms("medium", "For $f(x)=3x-6$:", ["inverse $\\tfrac{x+6}{3}$", "domain all reals", "$f^{-1}(0)=2$", "inverse $3x+6$"], [0, 1, 2]));
  q.push(tf("medium", "The inverse of $2x+3$ is $\\tfrac{x-3}{2}$.", true));
  q.push(tf("medium", "$f(x)=x^2$ (all reals) has a function inverse.", false));
  q.push(tf("medium", "$f(f^{-1}(x))=x$.", true));
  q.push(fill("medium", "Inverse of $f(x)=2x-1$.", ["(x+1)/2", "\\dfrac{x+1}{2}"]));
  q.push(fill("medium", "Inverse of $f(x)=3x+9$.", ["(x-9)/3", "\\dfrac{x-9}{3}"]));
  q.push(fill("medium", "$f^{-1}(x)$ for $f(x)=\\dfrac{x}{4}$.", ["4x"]));
  q.push(num("medium", "$f(x)=2x+3$; $f^{-1}(9)=$", 3, 0));
  q.push(num("medium", "$f(x)=3x-6$; $f^{-1}(0)=$", 2, 0));
  q.push(num("medium", "$f(x)=4x-1$; $f^{-1}(7)=$", 2, 0));
  q.push(match("medium", "Match each $f$ to its inverse.", ["$2x+3$", "$3x-6$", "$4x-1$"], ["$\\dfrac{x-3}{2}$", "$\\dfrac{x+6}{3}$", "$\\dfrac{x+1}{4}$"], [0, 1, 2]));
  q.push(mc("hard", "Inverse of $f(x)=\\dfrac{2x+1}{3}$.", ["$\\dfrac{3x-1}{2}$", "$\\dfrac{3x+1}{2}$", "$\\dfrac{2x-1}{3}$", "$3x-1$"], 0));
  q.push(mc("hard", "Inverse of $f(x)=x^2,\\ x\\ge0$.", ["$\\sqrt{x}$", "$\\pm\\sqrt{x}$", "$x^2$", "$-\\sqrt{x}$"], 0));
  q.push(mc("hard", "Inverse of $f(x)=\\dfrac{1}{x}$.", ["$\\dfrac{1}{x}$", "$x$", "$-x$", "$x^2$"], 0));
  q.push(mc("hard", "If $f^{-1}(x)=2x-4$, then $f(x)=$", ["$\\dfrac{x+4}{2}$", "$\\dfrac{x-4}{2}$", "$2x+4$", "$\\dfrac{x}{2}+4$"], 0));
  q.push(mc("hard", "Inverse of $f(x)=(x-1)^2,\\ x\\ge1$.", ["$1+\\sqrt{x}$", "$\\sqrt{x}-1$", "$1-\\sqrt{x}$", "$\\sqrt{x-1}$"], 0));
  q.push(ms("hard", "For $f(x)=\\dfrac{2x+1}{3}$:", ["swap: $x=\\tfrac{2y+1}{3}$", "solve $3x=2y+1$", "inverse $\\tfrac{3x-1}{2}$", "inverse $\\tfrac{2x-1}{3}$"], [0, 1, 2]));
  q.push(ms("hard", "Which are self-inverse ($f^{-1}=f$)?", ["$\\dfrac{1}{x}$", "$-x$", "$x$", "$2x$"], [0, 1, 2]));
  q.push(ms("hard", "To invert $x^2$:", ["restrict the domain", "take $\\sqrt{}$", "choose a branch", "leave it as is"], [0, 1, 2]));
  q.push(ms("hard", "Given $f^{-1}$, to recover $f$:", ["invert again", "swap and solve", "$f=(f^{-1})^{-1}$", "take the reciprocal"], [0, 1, 2]));
  q.push(tf("hard", "$f(x)=\\dfrac1x$ is its own inverse.", true));
  q.push(tf("hard", "The inverse of $x^2$ ($x\\ge0$) is $\\sqrt{x}$.", true));
  q.push(tf("hard", "$(x-1)^2$ for all $x$ has a function inverse.", false));
  q.push(fill("hard", "Inverse of $f(x)=\\dfrac{2x+1}{3}$.", ["(3x-1)/2", "\\dfrac{3x-1}{2}"]));
  q.push(fill("hard", "If $f^{-1}(x)=2x-4$, then $f(x)=$", ["(x+4)/2", "\\dfrac{x+4}{2}"]));
  q.push(fill("hard", "Inverse of $f(x)=x^2,\\ x\\ge0$.", ["sqrt(x)", "\\sqrt{x}", "√x"]));
  q.push(num("hard", "$f(x)=\\dfrac{2x+1}{3}$; $f^{-1}(3)=$", 4, 0));
  q.push(num("hard", "$f(x)=x^2,\\ x\\ge0$; $f^{-1}(25)=$", 5, 0));
  q.push(num("hard", "$f^{-1}(x)=2x-4$; find $f(6)$.", 5, 0));
  q.push(order("hard", "Order the steps to find the inverse of $f(x)=\\dfrac{2x+1}{3}$.", ["Write $y=\\dfrac{2x+1}{3}$", "Swap: $x=\\dfrac{2y+1}{3}$", "Solve: $3x=2y+1$", "$y=\\dfrac{3x-1}{2}$"]));
  q.push(match("hard", "Match each $f$ to its inverse.", ["$\\dfrac{1}{x}$", "$x^2\\ (x\\ge0)$", "$-x$"], ["$\\dfrac{1}{x}$", "$\\sqrt{x}$", "$-x$"], [0, 1, 2]));
  return q;
}

// ── 1.4 Transformations of Functions ─────────────────────────
function g14() {
  const q = [];
  q.push(mc("easy", "$y=(x-3)^2$ shifts $x^2$:", ["right 3", "left 3", "up 3", "down 3"], 0));
  q.push(mc("easy", "$y=x^2+4$ shifts:", ["up 4", "down 4", "right 4", "left 4"], 0));
  q.push(mc("easy", "$y=-x^2$ is a:", ["reflection in the $x$-axis", "shift up", "stretch", "shift right"], 0));
  q.push(mc("easy", "$y=2x^2$ is a:", ["vertical stretch by 2", "shift up 2", "reflection", "shift right 2"], 0));
  q.push(mc("easy", "Vertex of $y=(x-2)^2+5$:", ["$(2,5)$", "$(-2,5)$", "$(2,-5)$", "$(5,2)$"], 0));
  q.push(mc("easy", "$y=(x+1)^2$ shifts:", ["left 1", "right 1", "up 1", "down 1"], 0));
  q.push(ms("easy", "In $y=a\\,f(k(x-d))+c$:", ["$a$ vertical stretch", "$d$ horizontal shift", "$c$ vertical shift", "$a$ horizontal shift"], [0, 1, 2]));
  q.push(ms("easy", "$y=-2(x-3)^2+1$:", ["reflect", "stretch by 2", "right 3, up 1", "left 3"], [0, 1, 2]));
  q.push(ms("easy", "Vertical shifts:", ["$+c$ up", "$-c$ down", "change $y$", "change $x$"], [0, 1, 2]));
  q.push(ms("easy", "Reflections:", ["$a<0$ over the $x$-axis", "$k<0$ over the $y$-axis", "flip the graph", "shift it"], [0, 1, 2]));
  q.push(tf("easy", "$y=(x-3)^2$ shifts right 3.", true));
  q.push(tf("easy", "$y=x^2-5$ shifts up 5.", false));
  q.push(tf("easy", "$y=-x^2$ opens down.", true));
  q.push(fill("easy", "Vertex of $y=(x-4)^2+2$.", ["(4,2)", "4,2"]));
  q.push(fill("easy", "$y=(x+6)^2$ shifts (left/right and amount).", ["left 6", "left6"]));
  q.push(fill("easy", "Vertex of $y=(x+1)^2-3$.", ["(-1,-3)", "-1,-3"]));
  q.push(num("easy", "In $y=(x-7)^2$, the $x$-coordinate of the vertex.", 7, 0));
  q.push(num("easy", "In $y=x^2+9$, the $y$-coordinate of the vertex.", 9, 0));
  q.push(num("easy", "Vertical stretch factor in $y=5x^2$.", 5, 0));
  q.push(match("easy", "Match each to its vertex.", ["$(x-2)^2+3$", "$(x+1)^2-5$", "$x^2+4$"], ["$(2,3)$", "$(-1,-5)$", "$(0,4)$"], [0, 1, 2]));
  q.push(mc("medium", "$y=-2(x-3)^2+1$ vertex:", ["$(3,1)$", "$(-3,1)$", "$(3,-1)$", "$(1,3)$"], 0));
  q.push(mc("medium", "$y=\\sqrt{x+4}-2$ shifts:", ["left 4, down 2", "right 4, up 2", "left 4, up 2", "right 4, down 2"], 0));
  q.push(mc("medium", "Range of $y=-2(x-3)^2+1$:", ["$y\\le1$", "$y\\ge1$", "$y\\le3$", "all reals"], 0));
  q.push(mc("medium", "$y=3(x-1)^2$ from $x^2$:", ["stretch 3, right 1", "stretch 3, left 1", "compress, right 1", "reflect, right 1"], 0));
  q.push(mc("medium", "$y=(x+2)^2-7$ vertex:", ["$(-2,-7)$", "$(2,-7)$", "$(-2,7)$", "$(2,7)$"], 0));
  q.push(mc("medium", "Which opens down?", ["$y=-3x^2$", "$y=3x^2$", "$y=x^2+1$", "$y=(x-2)^2$"], 0));
  q.push(ms("medium", "For $y=-2(x-3)^2+1$:", ["reflect over $x$-axis", "stretch by 2", "vertex $(3,1)$", "max value 1"], [0, 1, 2, 3]));
  q.push(ms("medium", "$y=\\sqrt{x+4}-2$:", ["left 4", "down 2", "from $\\sqrt{x}$", "right 4"], [0, 1, 2]));
  q.push(ms("medium", "Reading $a(x-h)^2+k$:", ["vertex $(h,k)$", "$a<0$ opens down", "$k$ is the max/min", "vertex $(-h,k)$"], [0, 1, 2]));
  q.push(ms("medium", "Order of transformations:", ["stretches and reflections first", "then shifts", "it matters for accuracy", "shifts first"], [0, 1, 2]));
  q.push(tf("medium", "$y=-2(x-3)^2+1$ has vertex $(3,1)$.", true));
  q.push(tf("medium", "$y=\\sqrt{x+4}$ shifts $\\sqrt{x}$ left 4.", true));
  q.push(tf("medium", "$y=2(x-3)^2$ shifts left 3.", false));
  q.push(fill("medium", "Vertex of $y=-2(x-3)^2+1$.", ["(3,1)", "3,1"]));
  q.push(fill("medium", "Range of $y=-2(x-3)^2+1$ (y<=).", ["y<=1", "y \\le 1", "y≤1"]));
  q.push(fill("medium", "Vertex of $y=(x+2)^2-7$.", ["(-2,-7)", "-2,-7"]));
  q.push(num("medium", "Maximum value of $y=-2(x-3)^2+1$.", 1, 0));
  q.push(num("medium", "$x$-coordinate of vertex of $y=3(x-5)^2+2$.", 5, 0));
  q.push(num("medium", "$y$-coordinate of vertex of $y=(x+1)^2-8$.", -8, 0));
  q.push(match("medium", "Match each to its vertex.", ["$-2(x-3)^2+1$", "$(x+2)^2-7$", "$3(x-5)^2+2$"], ["$(3,1)$", "$(-2,-7)$", "$(5,2)$"], [0, 1, 2]));
  q.push(mc("hard", "$y=2(x-1)^2-3$: which transformations of $x^2$?", ["stretch 2, right 1, down 3", "stretch 2, left 1, up 3", "compress, right 1", "reflect, down 3"], 0));
  q.push(mc("hard", "$(2,4)$ on $y=x^2$ maps to which point on $y=(x-3)^2$?", ["$(5,4)$", "$(-1,4)$", "$(2,7)$", "$(5,1)$"], 0));
  q.push(mc("hard", "$y=-(x+2)^2+5$ has:", ["max 5 at $x=-2$", "min 5", "max 5 at $x=2$", "min at $x=-2$"], 0));
  q.push(mc("hard", "$y=x^2$ stretched by 3 and shifted down 4:", ["$y=3x^2-4$", "$y=3(x-4)^2$", "$y=3x^2+4$", "$y=x^2-12$"], 0));
  q.push(mc("hard", "$y=\\sqrt{-x}$ is $\\sqrt{x}$ reflected in:", ["the $y$-axis", "the $x$-axis", "$y=x$", "the origin"], 0));
  q.push(ms("hard", "For $y=2(x-1)^2-3$:", ["stretch by 2", "right 1", "down 3", "vertex $(1,-3)$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Mapping points under $y=(x-3)^2$:", ["$x$-values shift $+3$", "$(2,4)\\to(5,4)$", "horizontal shift right", "$y$ changes"], [0, 1, 2]));
  q.push(ms("hard", "For $y=-(x+2)^2+5$:", ["opens down", "vertex $(-2,5)$", "max value 5", "min value 5"], [0, 1, 2]));
  q.push(ms("hard", "Combining transformations:", ["reflect/stretch before shifting", "$a,k$ act on $y$", "$d$ acts on $x$", "order never matters"], [0, 1, 2]));
  q.push(tf("hard", "$y=-(x+2)^2+5$ has maximum 5.", true));
  q.push(tf("hard", "$y=\\sqrt{-x}$ reflects $\\sqrt{x}$ in the $y$-axis.", true));
  q.push(tf("hard", "A vertical stretch moves the vertex's $x$-coordinate.", false));
  q.push(fill("hard", "Vertex of $y=2(x-1)^2-3$.", ["(1,-3)", "1,-3"]));
  q.push(fill("hard", "Equation: $x^2$ stretched by 3, down 4.", ["3x^2-4", "3x²-4"]));
  q.push(fill("hard", "Maximum value of $y=-(x+2)^2+5$.", ["5"]));
  q.push(num("hard", "$y$-coordinate of vertex of $y=2(x-1)^2-3$.", -3, 0));
  q.push(num("hard", "New $x$ of the point $(2,4)$ under $y=(x-3)^2$.", 5, 0));
  q.push(num("hard", "Stretch factor in $y=4(x-2)^2$.", 4, 0));
  q.push(order("hard", "Order the transformations to graph $y=-2(x-3)^2+1$ from $x^2$.", ["Stretch vertically by 2", "Reflect in the $x$-axis", "Shift right 3", "Shift up 1"]));
  q.push(match("hard", "Match each to its vertex.", ["$2(x-1)^2-3$", "$-(x+2)^2+5$", "$4(x-2)^2$"], ["$(1,-3)$", "$(-2,5)$", "$(2,0)$"], [0, 1, 2]));
  return q;
}

// ── 1.5 Quadratic Functions: Zeros, Max & Min ────────────────
function g15() {
  const q = [];
  q.push(mc("easy", "Vertex of $y=(x-3)^2-4$:", ["$(3,-4)$", "$(-3,-4)$", "$(3,4)$", "$(4,3)$"], 0));
  q.push(mc("easy", "Minimum value of $y=(x-3)^2-4$:", ["$-4$", "$3$", "$4$", "$0$"], 0));
  q.push(mc("easy", "Zeros of $y=(x-2)(x+5)$:", ["$2,-5$", "$-2,5$", "$2,5$", "$-2,-5$"], 0));
  q.push(mc("easy", "Axis of symmetry of $y=(x-1)^2$:", ["$x=1$", "$x=-1$", "$x=0$", "$y=1$"], 0));
  q.push(mc("easy", "Does $y=x^2-4$ open up or down?", ["up", "down", "neither", "sideways"], 0));
  q.push(mc("easy", "Zeros of $y=x^2-9$:", ["$\\pm3$", "$\\pm9$", "$3$", "$0$"], 0));
  q.push(ms("easy", "From $y=(x-3)^2-4$:", ["vertex $(3,-4)$", "minimum $-4$", "opens up", "maximum $-4$"], [0, 1, 2]));
  q.push(ms("easy", "Zeros from factors:", ["$(x-2)\\to x=2$", "$(x+5)\\to x=-5$", "set each factor $=0$", "add them"], [0, 1, 2]));
  q.push(ms("easy", "The vertex is the:", ["max or min", "turning point", "point on the axis of symmetry", "$y$-intercept"], [0, 1, 2]));
  q.push(ms("easy", "Which open up?", ["$x^2$", "$2x^2$", "$x^2-5$", "$-x^2$"], [0, 1, 2]));
  q.push(tf("easy", "$y=(x-3)^2-4$ has minimum $-4$.", true));
  q.push(tf("easy", "$y=x^2-9$ has zeros $\\pm3$.", true));
  q.push(tf("easy", "$y=-x^2$ has a minimum.", false));
  q.push(fill("easy", "Vertex of $y=(x-5)^2+2$.", ["(5,2)", "5,2"]));
  q.push(fill("easy", "Zeros of $y=(x-4)(x+1)$.", ["4,-1", "-1,4"]));
  q.push(fill("easy", "Axis of symmetry of $y=(x-6)^2$.", ["x=6", "6"]));
  q.push(num("easy", "Minimum value of $y=(x-3)^2-4$.", -4, 0));
  q.push(num("easy", "Larger zero of $y=x^2-9$.", 3, 0));
  q.push(num("easy", "$x$-coordinate of vertex of $y=(x-7)^2+1$.", 7, 0));
  q.push(match("easy", "Match each to its vertex.", ["$(x-3)^2-4$", "$(x+2)^2+1$", "$x^2-5$"], ["$(3,-4)$", "$(-2,1)$", "$(0,-5)$"], [0, 1, 2]));
  q.push(mc("medium", "Complete the square: $x^2-6x+5=$", ["$(x-3)^2-4$", "$(x-3)^2+4$", "$(x+3)^2-4$", "$(x-6)^2+5$"], 0));
  q.push(mc("medium", "Vertex of $y=x^2+4x+1$:", ["$(-2,-3)$", "$(2,-3)$", "$(-2,3)$", "$(4,1)$"], 0));
  q.push(mc("medium", "Zeros of $y=x^2-6x+5$:", ["$1,5$", "$-1,-5$", "$2,3$", "$0,5$"], 0));
  q.push(mc("medium", "Minimum of $y=x^2-2x+5$:", ["$4$", "$5$", "$1$", "$-1$"], 0));
  q.push(mc("medium", "Maximum of $y=-x^2+6x-5$:", ["$4$", "$-5$", "$6$", "$3$"], 0));
  q.push(mc("medium", "Axis of symmetry of $y=x^2-8x+1$:", ["$x=4$", "$x=8$", "$x=-4$", "$x=1$"], 0));
  q.push(ms("medium", "Completing the square for $x^2-6x+5$:", ["half of $-6$ is $-3$", "$(x-3)^2$", "$-9+5=-4$", "$(x-3)^2-4$"], [0, 1, 2, 3]));
  q.push(ms("medium", "From $y=x^2-6x+5$:", ["vertex $(3,-4)$", "zeros $1,5$", "axis $x=3$", "opens down"], [0, 1, 2]));
  q.push(ms("medium", "Max/min:", ["$a>0$ gives a minimum", "$a<0$ gives a maximum", "it is at the vertex", "it is at the $y$-intercept"], [0, 1, 2]));
  q.push(ms("medium", "Finding zeros:", ["set $y=0$", "factor or use the formula", "they are the $x$-intercepts", "set $x=0$"], [0, 1, 2]));
  q.push(tf("medium", "$x^2-6x+5=(x-3)^2-4$.", true));
  q.push(tf("medium", "$y=x^2+4x+1$ has vertex $(-2,-3)$.", true));
  q.push(tf("medium", "$y=x^2-2x+5$ has a maximum.", false));
  q.push(fill("medium", "Vertex of $y=x^2-6x+5$.", ["(3,-4)", "3,-4"]));
  q.push(fill("medium", "Complete the square: $x^2+8x+10=$", ["(x+4)^2-6", "(x+4)²-6"]));
  q.push(fill("medium", "Minimum of $y=x^2-2x+5$.", ["4"]));
  q.push(num("medium", "Minimum value of $y=x^2-6x+5$.", -4, 0));
  q.push(num("medium", "Larger zero of $y=x^2-6x+5$.", 5, 0));
  q.push(num("medium", "Axis of symmetry $x=$ of $y=x^2-8x+1$.", 4, 0));
  q.push(match("medium", "Match each to its vertex.", ["$x^2-6x+5$", "$x^2+4x+1$", "$x^2-2x+5$"], ["$(3,-4)$", "$(-2,-3)$", "$(1,4)$"], [0, 1, 2]));
  q.push(mc("hard", "$x$-coordinate of the vertex of $y=2x^2-8x+3$:", ["$2$", "$4$", "$-2$", "$8$"], 0));
  q.push(mc("hard", "Minimum value of $y=2x^2-8x+3$:", ["$-5$", "$3$", "$2$", "$-3$"], 0));
  q.push(mc("hard", "Zeros of $y=x^2-4x+1$ (exact):", ["$2\\pm\\sqrt3$", "$2\\pm\\sqrt5$", "$4\\pm\\sqrt3$", "$-2\\pm\\sqrt3$"], 0));
  q.push(mc("hard", "A parabola has vertex $(2,-1)$ and passes through $(0,3)$. Its $a$ is:", ["$1$", "$2$", "$-1$", "$4$"], 0));
  q.push(mc("hard", "Number of zeros of $y=x^2+x+1$:", ["$0$", "$1$", "$2$", "$3$"], 0));
  q.push(ms("hard", "For $y=2x^2-8x+3$:", ["axis $x=2$", "vertex $(2,-5)$", "opens up", "minimum $-5$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which have two real zeros?", ["$x^2-4$", "$x^2-4x+1$", "$x^2+1$", "$x^2-2x-3$"], [0, 1, 3]));
  q.push(ms("hard", "Vertex from $ax^2+bx+c$:", ["$x=-\\dfrac{b}{2a}$", "substitute to get $y$", "that point is the vertex", "$x=\\dfrac{b}{2a}$"], [0, 1, 2]));
  q.push(ms("hard", "The discriminant $b^2-4ac$:", ["$>0$ two zeros", "$=0$ one zero", "$<0$ no real zeros", "$>0$ none"], [0, 1, 2]));
  q.push(tf("hard", "$y=2x^2-8x+3$ has minimum $-5$.", true));
  q.push(tf("hard", "$y=x^2+x+1$ has no real zeros.", true));
  q.push(tf("hard", "The vertex $x$ of $y=ax^2+bx+c$ is $\\dfrac{b}{2a}$.", false));
  q.push(fill("hard", "Vertex $x$ of $y=2x^2-8x+3$.", ["2"]));
  q.push(fill("hard", "Minimum value of $y=2x^2-8x+3$.", ["-5"]));
  q.push(fill("hard", "Discriminant of $x^2-4x+1$.", ["12"]));
  q.push(num("hard", "$x$-coordinate of vertex of $y=3x^2-12x+5$.", 2, 0));
  q.push(num("hard", "Discriminant of $y=x^2+x+1$.", -3, 0));
  q.push(num("hard", "For vertex $(2,-1)$ through $(0,3)$, the value of $a$.", 1, 0));
  q.push(order("hard", "Order the steps to find the vertex of $y=2x^2-8x+3$.", ["Find $x=-\\dfrac{b}{2a}=2$", "Substitute $x=2$", "$y=2(4)-16+3=-5$", "Vertex $(2,-5)$"]));
  q.push(match("hard", "Match each to its number of real zeros.", ["$x^2-4$", "$x^2+1$", "$x^2-6x+9$"], ["$2$", "$0$", "$1$"], [0, 1, 2]));
  return q;
}

// ── 1.6 Solving Quadratics & Linear–Quadratic Systems ────────
function g16() {
  const q = [];
  q.push(mc("easy", "Solve $x^2-5x+6=0$.", ["$2,3$", "$-2,-3$", "$1,6$", "$5,6$"], 0));
  q.push(mc("easy", "Solve $x^2-9=0$.", ["$\\pm3$", "$\\pm9$", "$3$", "$9$"], 0));
  q.push(mc("easy", "Solve $(x-4)(x+1)=0$.", ["$4,-1$", "$-4,1$", "$4,1$", "$-4,-1$"], 0));
  q.push(mc("easy", "Solve $x^2=16$.", ["$\\pm4$", "$4$", "$8$", "$\\pm8$"], 0));
  q.push(mc("easy", "The quadratic formula is $x=$", ["$\\dfrac{-b\\pm\\sqrt{b^2-4ac}}{2a}$", "$\\dfrac{b\\pm\\sqrt{b^2-4ac}}{2a}$", "$\\dfrac{-b\\pm\\sqrt{b^2+4ac}}{2a}$", "$-\\dfrac{b}{2a}$"], 0));
  q.push(mc("easy", "Solve $x^2+2x-8=0$.", ["$2,-4$", "$-2,4$", "$2,4$", "$-2,-4$"], 0));
  q.push(ms("easy", "Solving $x^2-5x+6=0$:", ["factor $(x-2)(x-3)$", "set each $=0$", "$x=2,3$", "$x=5,6$"], [0, 1, 2]));
  q.push(ms("easy", "Which factor to $(x-2)(x+3)$?", ["$x^2+x-6$", "zeros $2,-3$", "$x^2+x-6=0$", "$x^2-6$"], [0, 1, 2]));
  q.push(ms("easy", "To solve $x^2=16$:", ["$x=\\pm\\sqrt{16}$", "$x=\\pm4$", "two solutions", "$x=4$ only"], [0, 1, 2]));
  q.push(ms("easy", "Methods to solve a quadratic:", ["factoring", "the quadratic formula", "graphing", "none"], [0, 1, 2]));
  q.push(tf("easy", "$x^2-5x+6=0$ has solutions $2,3$.", true));
  q.push(tf("easy", "$x^2=16$ has only $x=4$.", false));
  q.push(tf("easy", "Factoring is one way to solve a quadratic.", true));
  q.push(fill("easy", "Solve $x^2-7x+10=0$.", ["2,5", "5,2"]));
  q.push(fill("easy", "Solve $x^2-25=0$.", ["±5", "5,-5", "-5,5"]));
  q.push(fill("easy", "Solve $x^2+x-6=0$.", ["2,-3", "-3,2"]));
  q.push(num("easy", "Larger solution of $x^2-5x+6=0$.", 3, 0));
  q.push(num("easy", "Positive solution of $x^2-49=0$.", 7, 0));
  q.push(num("easy", "Larger solution of $x^2+2x-8=0$.", 2, 0));
  q.push(match("easy", "Match each equation to its solutions.", ["$x^2-9=0$", "$x^2-5x+6=0$", "$(x-4)(x+1)=0$"], ["$\\pm3$", "$2,3$", "$4,-1$"], [0, 1, 2]));
  q.push(mc("medium", "Solve $x^2-4x+1=0$ (exact).", ["$2\\pm\\sqrt3$", "$2\\pm\\sqrt5$", "$4\\pm\\sqrt3$", "$1\\pm\\sqrt3$"], 0));
  q.push(mc("medium", "Where do $y=x^2-2$ and $y=x$ meet?", ["$(2,2),(-1,-1)$", "$(2,2)$", "$(1,1)$", "nowhere"], 0));
  q.push(mc("medium", "Solve $2x^2-7x+3=0$.", ["$3,\\tfrac12$", "$-3,-\\tfrac12$", "$3,2$", "$\\tfrac13,2$"], 0));
  q.push(mc("medium", "Solve $x^2-6x+9=0$.", ["$3$ (double)", "$\\pm3$", "$3,-3$", "no solution"], 0));
  q.push(mc("medium", "Discriminant of $x^2+2x+5$:", ["$-16$", "$16$", "$24$", "$-4$"], 0));
  q.push(mc("medium", "Solve $x^2+4x=0$.", ["$0,-4$", "$0,4$", "$-4$", "$4$"], 0));
  q.push(ms("medium", "Quadratic formula on $x^2-4x+1$:", ["$a=1,b=-4,c=1$", "discriminant $12$", "$x=\\dfrac{4\\pm\\sqrt{12}}{2}$", "$x=2\\pm\\sqrt3$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Solving a linear–quadratic system:", ["set the expressions equal", "solve the quadratic", "substitute back for $y$", "subtract only"], [0, 1, 2]));
  q.push(ms("medium", "Which have a double root?", ["$x^2-6x+9$", "$(x-3)^2=0$", "discriminant $=0$", "$x^2-9$"], [0, 1, 2]));
  q.push(ms("medium", "The discriminant tells:", ["the number of real roots", "$>0$ two", "$<0$ none", "the vertex"], [0, 1, 2]));
  q.push(tf("medium", "$x^2-4x+1=0$ gives $x=2\\pm\\sqrt3$.", true));
  q.push(tf("medium", "$x^2-6x+9=0$ has a double root $x=3$.", true));
  q.push(tf("medium", "$y=x^2-2$ and $y=x$ never meet.", false));
  q.push(fill("medium", "Solutions of $x^2-4x+1=0$.", ["2±√3", "2 ± \\sqrt3", "2+√3,2-√3"]));
  q.push(fill("medium", "Solve $x^2+4x=0$.", ["0,-4", "-4,0"]));
  q.push(fill("medium", "Solve $2x^2-7x+3=0$.", ["3,1/2", "3,0.5"]));
  q.push(num("medium", "Discriminant of $x^2+2x+5$.", -16, 0));
  q.push(num("medium", "Double root of $x^2-6x+9=0$.", 3, 0));
  q.push(num("medium", "Positive $x$ at the intersection of $y=x^2-2$ and $y=x$.", 2, 0));
  q.push(match("medium", "Match each equation to its solutions.", ["$x^2-6x+9=0$", "$x^2-4x+1=0$", "$x^2+4x=0$"], ["$3$", "$2\\pm\\sqrt3$", "$0,-4$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $3x^2-5x-2=0$.", ["$2,-\\tfrac13$", "$-2,\\tfrac13$", "$2,\\tfrac13$", "$-2,-\\tfrac13$"], 0));
  q.push(mc("hard", "For what $k$ does $x^2-6x+k=0$ have one solution?", ["$9$", "$6$", "$3$", "$36$"], 0));
  q.push(mc("hard", "Where does $y=2x+1$ meet $y=x^2+1$?", ["$(0,1),(2,5)$", "$(1,3)$", "nowhere", "$(2,5)$"], 0));
  q.push(mc("hard", "Solve $x^2+x-1=0$ (exact).", ["$\\dfrac{-1\\pm\\sqrt5}{2}$", "$\\dfrac{1\\pm\\sqrt5}{2}$", "$-1\\pm\\sqrt5$", "$\\dfrac{-1\\pm\\sqrt3}{2}$"], 0));
  q.push(mc("hard", "$x^2-kx+4=0$ has two distinct roots when:", ["$k^2>16$", "$k^2<16$", "$k=4$", "$k>4$"], 0));
  q.push(ms("hard", "Solving $3x^2-5x-2=0$:", ["$ac=-6$", "factor $(3x+1)(x-2)$", "$x=2,-\\tfrac13$", "$x=2,\\tfrac13$"], [0, 1, 2]));
  q.push(ms("hard", "Linear–quadratic intersections can have:", ["0 points", "1 point (tangent)", "2 points", "infinitely many"], [0, 1, 2]));
  q.push(ms("hard", "Discriminant conditions:", ["two roots if $>0$", "one if $=0$", "none if $<0$", "two if $<0$"], [0, 1, 2]));
  q.push(ms("hard", "For $y=2x+1$ and $y=x^2+1$:", ["set $x^2+1=2x+1$", "$x^2-2x=0$", "$x=0,2$", "$x=1$"], [0, 1, 2]));
  q.push(tf("hard", "$x^2-6x+k=0$ has one solution when $k=9$.", true));
  q.push(tf("hard", "$3x^2-5x-2=0$ has solutions $2$ and $-\\tfrac13$.", true));
  q.push(tf("hard", "A line always meets a parabola in two points.", false));
  q.push(fill("hard", "Solve $3x^2-5x-2=0$.", ["2,-1/3", "2,-0.333"]));
  q.push(fill("hard", "$k$ for which $x^2-6x+k=0$ has a double root.", ["9"]));
  q.push(fill("hard", "Solutions of $x^2+x-1=0$.", ["(-1±√5)/2", "\\dfrac{-1\\pm\\sqrt5}{2}"]));
  q.push(num("hard", "Value of $k$ for one solution of $x^2-6x+k=0$.", 9, 0));
  q.push(num("hard", "Number of intersection points of $y=2x+1$ and $y=x^2+1$.", 2, 0));
  q.push(num("hard", "Larger solution of $3x^2-5x-2=0$.", 2, 0));
  q.push(order("hard", "Order the steps to solve the system $y=x^2+1,\\ y=2x+1$.", ["Set equal: $x^2+1=2x+1$", "Simplify: $x^2-2x=0$", "Factor: $x(x-2)=0$", "$x=0,2$"]));
  q.push(match("hard", "Match each equation to its number of real roots.", ["$x^2-6x+9=0$", "$x^2+2x+5=0$", "$x^2-5x+6=0$"], ["$1$", "$0$", "$2$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "1.1", gen: g11 },
  { code: "1.2", gen: g12 },
  { code: "1.3", gen: g13 },
  { code: "1.4", gen: g14 },
  { code: "1.5", gen: g15 },
  { code: "1.6", gen: g16 },
];
