// MCR3U Unit 2 — Equivalent Algebraic Expressions: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 2.1 Adding & Multiplying Polynomials ─────────────────────
function g21() {
  const q = [];
  q.push(mc("easy", "$(2x+3)+(x-5)$ =", ["$3x-2$", "$3x+8$", "$x-2$", "$2x-2$"], 0));
  q.push(mc("easy", "$(3x^2-x)+(x^2+4x)$ =", ["$4x^2+3x$", "$4x^2-3x$", "$2x^2+3x$", "$4x^2+5x$"], 0));
  q.push(mc("easy", "$2(x+4)$ =", ["$2x+8$", "$2x+4$", "$x+8$", "$2x+6$"], 0));
  q.push(mc("easy", "$x\\cdot x$ =", ["$x^2$", "$2x$", "$x$", "$2x^2$"], 0));
  q.push(mc("easy", "$(x+2)(x+3)$ =", ["$x^2+5x+6$", "$x^2+6x+5$", "$x^2+6$", "$x^2+5x+5$"], 0));
  q.push(mc("easy", "$3x\\cdot 2x$ =", ["$6x^2$", "$5x^2$", "$6x$", "$5x$"], 0));
  q.push(ms("easy", "Like terms:", ["$3x$ and $5x$", "$2x^2$ and $-x^2$", "$4$ and $7$", "$x$ and $x^2$"], [0, 1, 2]));
  q.push(ms("easy", "$(x+2)(x+3)$ expands using:", ["distribute each term", "FOIL", "result $x^2+5x+6$", "adding the binomials"], [0, 1, 2]));
  q.push(ms("easy", "Adding polynomials:", ["combine like terms", "keep $x^2$ with $x^2$", "$3x^2+x^2=4x^2$", "multiply them"], [0, 1, 2]));
  q.push(ms("easy", "$2(x+4)$:", ["distribute the 2", "$2x+8$", "each term times 2", "$2x+4$"], [0, 1, 2]));
  q.push(tf("easy", "$3x+5x=8x$.", true));
  q.push(tf("easy", "$x\\cdot x=2x$.", false));
  q.push(tf("easy", "$(x+2)(x+3)=x^2+5x+6$.", true));
  q.push(fill("easy", "Expand $(x+1)(x+4)$.", ["x^2+5x+4", "x²+5x+4"]));
  q.push(fill("easy", "Simplify $(2x+1)+(3x-4)$.", ["5x-3"]));
  q.push(fill("easy", "Expand $3(2x-5)$.", ["6x-15"]));
  q.push(num("easy", "Coefficient of $x$ in $(x+2)(x+3)$.", 5, 0));
  q.push(num("easy", "Constant term in $(x+2)(x+3)$.", 6, 0));
  q.push(num("easy", "Coefficient of $(4x)(3x)$.", 12, 0));
  q.push(match("easy", "Match each product.", ["$x\\cdot x$", "$2x\\cdot3x$", "$(x)(4)$"], ["$x^2$", "$6x^2$", "$4x$"], [0, 1, 2]));
  q.push(mc("medium", "$(x+5)(x-2)$ =", ["$x^2+3x-10$", "$x^2-3x-10$", "$x^2+3x+10$", "$x^2-7x-10$"], 0));
  q.push(mc("medium", "$(2x-3)(x+4)$ =", ["$2x^2+5x-12$", "$2x^2-5x-12$", "$2x^2+5x+12$", "$2x^2+11x-12$"], 0));
  q.push(mc("medium", "$(x+3)^2$ =", ["$x^2+6x+9$", "$x^2+9$", "$x^2+3x+9$", "$x^2+6x+6$"], 0));
  q.push(mc("medium", "$(x-4)(x+4)$ =", ["$x^2-16$", "$x^2+16$", "$x^2-8x-16$", "$x^2-8$"], 0));
  q.push(mc("medium", "$-2(3x-5)$ =", ["$-6x+10$", "$-6x-10$", "$6x+10$", "$-6x-5$"], 0));
  q.push(mc("medium", "$(x+2)(x^2-3)$ =", ["$x^3+2x^2-3x-6$", "$x^3-3x-6$", "$x^3+2x^2-6$", "$x^3-6$"], 0));
  q.push(ms("medium", "$(x+3)^2$:", ["$=(x+3)(x+3)$", "$x^2+6x+9$", "a perfect square", "$x^2+9$"], [0, 1, 2]));
  q.push(ms("medium", "$(x-4)(x+4)$:", ["difference of squares", "$x^2-16$", "middle terms cancel", "$x^2+16$"], [0, 1, 2]));
  q.push(ms("medium", "Expanding $(2x-3)(x+4)$:", ["$2x^2$", "$8x-3x=5x$", "$-12$", "$2x^2+5x-12$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Distributing $-2(3x-5)$:", ["$-6x$", "$+10$", "the sign flips", "$-6x-10$"], [0, 1, 2]));
  q.push(tf("medium", "$(x+3)^2=x^2+9$.", false));
  q.push(tf("medium", "$(x-4)(x+4)=x^2-16$.", true));
  q.push(tf("medium", "$(2x-3)(x+4)=2x^2+5x-12$.", true));
  q.push(fill("medium", "Expand $(x+5)(x-2)$.", ["x^2+3x-10", "x²+3x-10"]));
  q.push(fill("medium", "Expand $(x-3)^2$.", ["x^2-6x+9", "x²-6x+9"]));
  q.push(fill("medium", "Expand $(x+6)(x-6)$.", ["x^2-36", "x²-36"]));
  q.push(num("medium", "Coefficient of $x$ in $(2x-3)(x+4)$.", 5, 0));
  q.push(num("medium", "Constant in $(x+5)(x-2)$.", -10, 0));
  q.push(num("medium", "Coefficient of $x$ in $(x+3)^2$.", 6, 0));
  q.push(match("medium", "Match each expansion.", ["$(x+3)^2$", "$(x-4)(x+4)$", "$(x+5)(x-2)$"], ["$x^2+6x+9$", "$x^2-16$", "$x^2+3x-10$"], [0, 1, 2]));
  q.push(mc("hard", "$(x+2)(x^2-3x+1)$ =", ["$x^3-x^2-5x+2$", "$x^3-x^2+5x+2$", "$x^3+x^2-5x+2$", "$x^3-5x+2$"], 0));
  q.push(mc("hard", "$(2x-1)^2$ =", ["$4x^2-4x+1$", "$4x^2+1$", "$2x^2-4x+1$", "$4x^2-2x+1$"], 0));
  q.push(mc("hard", "$(x+1)(x-1)(x+2)$ =", ["$x^3+2x^2-x-2$", "$x^3-2$", "$x^3+2x^2+x-2$", "$x^3-x-2$"], 0));
  q.push(mc("hard", "Simplify $(x+3)^2-(x-3)^2$.", ["$12x$", "$0$", "$18$", "$6x$"], 0));
  q.push(mc("hard", "$3(x-2)^2$ =", ["$3x^2-12x+12$", "$3x^2-4x+4$", "$3x^2-12x+4$", "$3x^2-6x+12$"], 0));
  q.push(ms("hard", "Expanding $(2x-1)^2$:", ["$4x^2$", "$-4x$", "$+1$", "$4x^2-4x+1$"], [0, 1, 2, 3]));
  q.push(ms("hard", "$(x+1)(x-1)(x+2)$:", ["first $(x^2-1)$", "then $\\times(x+2)$", "$x^3+2x^2-x-2$", "$x^3-2$"], [0, 1, 2]));
  q.push(ms("hard", "$(x+3)^2-(x-3)^2$:", ["expand both", "$=12x$", "the $x^2$ and $9$ cancel", "$=0$"], [0, 1, 2]));
  q.push(ms("hard", "Multiplying three factors:", ["multiply two first", "then the third", "stay organized", "all at once"], [0, 1, 2]));
  q.push(tf("hard", "$(2x-1)^2=4x^2-4x+1$.", true));
  q.push(tf("hard", "$(x+3)^2-(x-3)^2=12x$.", true));
  q.push(tf("hard", "$(x+1)(x-1)(x+2)=x^3-2$.", false));
  q.push(fill("hard", "Expand $(2x-1)^2$.", ["4x^2-4x+1", "4x²-4x+1"]));
  q.push(fill("hard", "Simplify $(x+3)^2-(x-3)^2$.", ["12x"]));
  q.push(fill("hard", "Expand $3(x-2)^2$.", ["3x^2-12x+12", "3x²-12x+12"]));
  q.push(num("hard", "Coefficient of $x$ in $(2x-1)^2$.", -4, 0));
  q.push(num("hard", "Coefficient of $x^2$ in $(x+1)(x-1)(x+2)$.", 2, 0));
  q.push(num("hard", "Value of $(x+3)^2-(x-3)^2$ at $x=5$.", 60, 0));
  q.push(order("hard", "Order the steps to expand $(x+1)(x-1)(x+2)$.", ["Multiply $(x+1)(x-1)=x^2-1$", "Multiply by $(x+2)$", "Collect like terms", "$x^3+2x^2-x-2$"]));
  q.push(match("hard", "Match each expansion.", ["$(2x-1)^2$", "$3(x-2)^2$", "$(x+3)^2-(x-3)^2$"], ["$4x^2-4x+1$", "$3x^2-12x+12$", "$12x$"], [0, 1, 2]));
  return q;
}

// ── 2.2 Factoring Polynomials ────────────────────────────────
function g22() {
  const q = [];
  q.push(mc("easy", "Factor $x^2+5x+6$.", ["$(x+2)(x+3)$", "$(x+1)(x+6)$", "$(x-2)(x-3)$", "$(x+5)(x+6)$"], 0));
  q.push(mc("easy", "Factor $x^2-9$.", ["$(x-3)(x+3)$", "$(x-9)(x+1)$", "$(x-3)^2$", "$(x+3)^2$"], 0));
  q.push(mc("easy", "Common factor of $4x+8$.", ["$4$", "$2$", "$x$", "$8$"], 0));
  q.push(mc("easy", "Factor $x^2-x-6$.", ["$(x-3)(x+2)$", "$(x+3)(x-2)$", "$(x-6)(x+1)$", "$(x-3)(x-2)$"], 0));
  q.push(mc("easy", "Factor $2x+6$.", ["$2(x+3)$", "$2(x+6)$", "$x(2+6)$", "$6(x+1)$"], 0));
  q.push(mc("easy", "Factor $x^2+7x+12$.", ["$(x+3)(x+4)$", "$(x+2)(x+6)$", "$(x+1)(x+12)$", "$(x+3)(x+5)$"], 0));
  q.push(ms("easy", "To factor $x^2+5x+6$:", ["find two numbers multiplying to 6", "summing to 5", "$2$ and $3$", "product 5, sum 6"], [0, 1, 2]));
  q.push(ms("easy", "Difference of squares:", ["$a^2-b^2=(a-b)(a+b)$", "$x^2-9=(x-3)(x+3)$", "has two terms", "$a^2+b^2$"], [0, 1, 2]));
  q.push(ms("easy", "Common factoring:", ["take out the GCF", "$4x+8=4(x+2)$", "reverse distribution", "add the terms"], [0, 1, 2]));
  q.push(ms("easy", "Which factor over the integers?", ["$x^2-9$", "$x^2+5x+6$", "$x^2-x-6$", "$x^2+1$"], [0, 1, 2]));
  q.push(tf("easy", "$x^2-9=(x-3)(x+3)$.", true));
  q.push(tf("easy", "$x^2+9=(x+3)^2$.", false));
  q.push(tf("easy", "$4x+8=4(x+2)$.", true));
  q.push(fill("easy", "Factor $x^2+8x+15$.", ["(x+3)(x+5)", "(x+5)(x+3)"]));
  q.push(fill("easy", "Factor $x^2-16$.", ["(x-4)(x+4)", "(x+4)(x-4)"]));
  q.push(fill("easy", "Factor $5x+10$.", ["5(x+2)"]));
  q.push(num("easy", "In $x^2+5x+6=(x+a)(x+b)$, the value $a+b$.", 5, 0));
  q.push(num("easy", "In $x^2-9=(x-a)(x+a)$, the value $a$.", 3, 0));
  q.push(num("easy", "GCF of $6x+9$.", 3, 0));
  q.push(match("easy", "Match each to its factors.", ["$x^2-9$", "$x^2+5x+6$", "$x^2-x-6$"], ["$(x-3)(x+3)$", "$(x+2)(x+3)$", "$(x-3)(x+2)$"], [0, 1, 2]));
  q.push(mc("medium", "Factor $2x^2+7x+3$.", ["$(2x+1)(x+3)$", "$(2x+3)(x+1)$", "$(2x+1)(x-3)$", "$(x+1)(x+3)$"], 0));
  q.push(mc("medium", "Factor $3x^2-12$.", ["$3(x-2)(x+2)$", "$3(x^2-4)$ only", "$(3x-6)(x+2)$", "$3(x-4)(x+1)$"], 0));
  q.push(mc("medium", "Factor $x^2-10x+25$.", ["$(x-5)^2$", "$(x+5)^2$", "$(x-5)(x+5)$", "$(x-25)(x-1)$"], 0));
  q.push(mc("medium", "Factor $6x^2-x-2$.", ["$(3x-2)(2x+1)$", "$(3x+2)(2x-1)$", "$(6x-1)(x+2)$", "$(3x-1)(2x+2)$"], 0));
  q.push(mc("medium", "Factor $x^3-x$.", ["$x(x-1)(x+1)$", "$x(x^2-1)$ only", "$x^2(x-1)$", "$(x-1)(x+1)$"], 0));
  q.push(mc("medium", "Factor $4x^2-9$.", ["$(2x-3)(2x+3)$", "$(4x-3)(x+3)$", "$(2x-9)(2x+1)$", "$(2x-3)^2$"], 0));
  q.push(ms("medium", "Factoring $2x^2+7x+3$:", ["$ac=6$", "split $7x=6x+x$", "factor by grouping", "$(2x+1)(x+3)$"], [0, 1, 2, 3]));
  q.push(ms("medium", "$3x^2-12$:", ["common factor 3", "then difference of squares", "$3(x-2)(x+2)$", "cannot be factored"], [0, 1, 2]));
  q.push(ms("medium", "Perfect-square trinomials:", ["$x^2-10x+25=(x-5)^2$", "first and last are squares", "middle $=2ab$", "$x^2+25$"], [0, 1, 2]));
  q.push(ms("medium", "Always factor first:", ["the GCF", "before other methods", "$3x^2-12=3(x^2-4)$", "the largest term only"], [0, 1, 2]));
  q.push(tf("medium", "$x^2-10x+25=(x-5)^2$.", true));
  q.push(tf("medium", "$3x^2-12=3(x-2)(x+2)$.", true));
  q.push(tf("medium", "$4x^2-9=(2x-3)^2$.", false));
  q.push(fill("medium", "Factor $2x^2+7x+3$.", ["(2x+1)(x+3)", "(x+3)(2x+1)"]));
  q.push(fill("medium", "Factor $x^2-10x+25$.", ["(x-5)^2", "(x-5)(x-5)"]));
  q.push(fill("medium", "Factor $4x^2-9$.", ["(2x-3)(2x+3)", "(2x+3)(2x-3)"]));
  q.push(num("medium", "In $2x^2+7x+3$, the product $ac$.", 6, 0));
  q.push(num("medium", "GCF to remove from $3x^2-12$.", 3, 0));
  q.push(num("medium", "Repeated root of $(x-5)^2$.", 5, 0));
  q.push(match("medium", "Match each to its factors.", ["$x^2-10x+25$", "$4x^2-9$", "$2x^2+7x+3$"], ["$(x-5)^2$", "$(2x-3)(2x+3)$", "$(2x+1)(x+3)$"], [0, 1, 2]));
  q.push(mc("hard", "Factor $x^3-8$.", ["$(x-2)(x^2+2x+4)$", "$(x-2)^3$", "$(x-2)(x^2-2x+4)$", "$(x+2)(x^2-2x+4)$"], 0));
  q.push(mc("hard", "Factor $x^3+27$.", ["$(x+3)(x^2-3x+9)$", "$(x+3)^3$", "$(x+3)(x^2+3x+9)$", "$(x-3)(x^2+3x+9)$"], 0));
  q.push(mc("hard", "Factor $x^4-16$ (first step).", ["$(x^2-4)(x^2+4)$", "$(x-2)^4$", "$(x^2-4)^2$", "$(x-4)(x+4)$"], 0));
  q.push(mc("hard", "Factor $x^4-16$ fully.", ["$(x-2)(x+2)(x^2+4)$", "$(x^2-4)(x^2+4)$", "$(x-2)^2(x+2)^2$", "$(x-4)(x+4)$"], 0));
  q.push(mc("hard", "Factor $6x^2+11x-10$.", ["$(3x-2)(2x+5)$", "$(3x+2)(2x-5)$", "$(6x-5)(x+2)$", "$(2x-2)(3x+5)$"], 0));
  q.push(ms("hard", "Sum/difference of cubes:", ["$a^3-b^3=(a-b)(a^2+ab+b^2)$", "$a^3+b^3=(a+b)(a^2-ab+b^2)$", "$x^3-8=(x-2)(x^2+2x+4)$", "$x^3-8=(x-2)^3$"], [0, 1, 2]));
  q.push(ms("hard", "Factoring $x^4-16$:", ["difference of squares twice", "$(x^2-4)(x^2+4)$", "then $(x-2)(x+2)$", "$x^2+4$ factors over the reals"], [0, 1, 2]));
  q.push(ms("hard", "Decomposing $6x^2+11x-10$:", ["$ac=-60$", "$15$ and $-4$", "group", "$(3x-2)(2x+5)$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Factor fully means:", ["until no further factoring", "over the integers", "check each factor", "stop at the first step"], [0, 1, 2]));
  q.push(tf("hard", "$x^3-8=(x-2)(x^2+2x+4)$.", true));
  q.push(tf("hard", "$x^4-16$ factors fully to $(x-2)(x+2)(x^2+4)$.", true));
  q.push(tf("hard", "$x^2+4$ factors over the real numbers.", false));
  q.push(fill("hard", "Factor $x^3-8$.", ["(x-2)(x^2+2x+4)", "(x-2)(x²+2x+4)"]));
  q.push(fill("hard", "Factor $x^3+27$.", ["(x+3)(x^2-3x+9)", "(x+3)(x²-3x+9)"]));
  q.push(fill("hard", "Factor fully $x^4-16$.", ["(x-2)(x+2)(x^2+4)", "(x-2)(x+2)(x²+4)"]));
  q.push(num("hard", "In $6x^2+11x-10$, the product $ac$.", -60, 0));
  q.push(num("hard", "Real $a$ with $x^3-8=(x-a)(\\dots)$.", 2, 0));
  q.push(num("hard", "Number of linear real factors of $x^4-16$.", 2, 0));
  q.push(order("hard", "Order the steps to factor $x^4-16$ fully.", ["Difference of squares: $(x^2-4)(x^2+4)$", "Factor $x^2-4=(x-2)(x+2)$", "$x^2+4$ stays", "$(x-2)(x+2)(x^2+4)$"]));
  q.push(match("hard", "Match each to its factored form.", ["$x^3-8$", "$x^3+27$", "$x^4-16$"], ["$(x-2)(x^2+2x+4)$", "$(x+3)(x^2-3x+9)$", "$(x-2)(x+2)(x^2+4)$"], [0, 1, 2]));
  return q;
}

// ── 2.3 Simplifying Rational Expressions ─────────────────────
function g23() {
  const q = [];
  q.push(mc("easy", "Simplify $\\dfrac{2x}{4}$.", ["$\\dfrac{x}{2}$", "$2x$", "$\\dfrac{x}{4}$", "$\\dfrac{1}{2}$"], 0));
  q.push(mc("easy", "Simplify $\\dfrac{x^2}{x}$.", ["$x$", "$x^2$", "$1$", "$x^3$"], 0));
  q.push(mc("easy", "Simplify $\\dfrac{6x^2}{3x}$.", ["$2x$", "$2$", "$3x$", "$2x^2$"], 0));
  q.push(mc("easy", "$\\dfrac{x+2}{x+2}$ =", ["$1$", "$0$", "$x+2$", "$2$"], 0));
  q.push(mc("easy", "Restriction on $\\dfrac{1}{x-3}$.", ["$x\\ne3$", "$x\\ne0$", "$x\\ne-3$", "none"], 0));
  q.push(mc("easy", "Simplify $\\dfrac{4x}{8x}$.", ["$\\dfrac12$", "$\\dfrac{x}{2}$", "$2$", "$4$"], 0));
  q.push(ms("easy", "Simplifying rationals:", ["factor first", "cancel common factors", "state restrictions", "cancel terms"], [0, 1, 2]));
  q.push(ms("easy", "Restrictions:", ["denominator $\\ne0$", "find where it is $0$", "exclude those $x$", "numerator $\\ne0$"], [0, 1, 2]));
  q.push(ms("easy", "$\\dfrac{6x^2}{3x}$:", ["$=2x$", "divide the coefficients", "subtract exponents", "$=2$"], [0, 1, 2]));
  q.push(ms("easy", "Cancelling:", ["only common factors", "not terms", "$\\dfrac{x^2}{x}=x$", "any number"], [0, 1, 2]));
  q.push(tf("easy", "$\\dfrac{x^2}{x}=x$ for $x\\ne0$.", true));
  q.push(tf("easy", "$\\dfrac{x+2}{2}=x$.", false));
  q.push(tf("easy", "$\\dfrac{1}{x-3}$ needs $x\\ne3$.", true));
  q.push(fill("easy", "Simplify $\\dfrac{10x}{5}$.", ["2x"]));
  q.push(fill("easy", "Simplify $\\dfrac{x^3}{x}$.", ["x^2", "x²"]));
  q.push(fill("easy", "Restriction on $\\dfrac{5}{x+4}$.", ["x!=-4", "x \\ne -4", "x≠-4"]));
  q.push(num("easy", "$\\dfrac{9x^2}{3x}$ at $x=2$.", 6, 0));
  q.push(num("easy", "Excluded value of $\\dfrac{1}{x-7}$.", 7, 0));
  q.push(num("easy", "$\\dfrac{8x}{4x}$ as a number.", 2, 0));
  q.push(match("easy", "Match each to its simplest form.", ["$\\dfrac{2x}{4}$", "$\\dfrac{x^2}{x}$", "$\\dfrac{6x^2}{3x}$"], ["$\\dfrac{x}{2}$", "$x$", "$2x$"], [0, 1, 2]));
  q.push(mc("medium", "Simplify $\\dfrac{x^2-9}{x-3}$.", ["$x+3$", "$x-3$", "$x+9$", "$x^2$"], 0));
  q.push(mc("medium", "Simplify $\\dfrac{x^2+5x+6}{x+2}$.", ["$x+3$", "$x+2$", "$x+6$", "$x-3$"], 0));
  q.push(mc("medium", "Simplify $\\dfrac{x^2-x}{x}$.", ["$x-1$", "$x+1$", "$-1$", "$x$"], 0));
  q.push(mc("medium", "Restriction(s) on $\\dfrac{x^2-9}{x-3}$.", ["$x\\ne3$", "$x\\ne\\pm3$", "$x\\ne-3$", "none"], 0));
  q.push(mc("medium", "Simplify $\\dfrac{2x^2-8}{x-2}$.", ["$2(x+2)$", "$2(x-2)$", "$x+2$", "$2x+8$"], 0));
  q.push(mc("medium", "Simplify $\\dfrac{x^2-4}{x^2+4x+4}$.", ["$\\dfrac{x-2}{x+2}$", "$\\dfrac{x+2}{x-2}$", "$1$", "$\\dfrac{x-2}{x+4}$"], 0));
  q.push(ms("medium", "Simplifying $\\dfrac{x^2-9}{x-3}$:", ["factor numerator", "$(x-3)(x+3)$", "cancel $(x-3)$", "$=x+3$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Restrictions come from:", ["the original denominator", "$x-3\\ne0$", "$x\\ne3$", "the simplified form"], [0, 1, 2]));
  q.push(ms("medium", "$\\dfrac{x^2-4}{x^2+4x+4}$:", ["$(x-2)(x+2)$ over $(x+2)^2$", "cancel one $(x+2)$", "$\\dfrac{x-2}{x+2}$", "cancel $x^2$"], [0, 1, 2]));
  q.push(ms("medium", "Factor both parts:", ["numerator and denominator", "then cancel", "find restrictions", "add them"], [0, 1, 2]));
  q.push(tf("medium", "$\\dfrac{x^2-9}{x-3}=x+3$, $x\\ne3$.", true));
  q.push(tf("medium", "You may cancel the $x^2$ in $\\dfrac{x^2-4}{x^2+4x+4}$.", false));
  q.push(tf("medium", "$\\dfrac{x^2-x}{x}=x-1$.", true));
  q.push(fill("medium", "Simplify $\\dfrac{x^2-9}{x-3}$.", ["x+3"]));
  q.push(fill("medium", "Simplify $\\dfrac{x^2+5x+6}{x+2}$.", ["x+3"]));
  q.push(fill("medium", "Simplify $\\dfrac{2x^2-8}{x-2}$.", ["2(x+2)", "2x+4"]));
  q.push(num("medium", "$\\dfrac{x^2-9}{x-3}$ at $x=10$.", 13, 0));
  q.push(num("medium", "Excluded value of $\\dfrac{x^2-9}{x-3}$.", 3, 0));
  q.push(num("medium", "$\\dfrac{x^2-x}{x}$ at $x=5$.", 4, 0));
  q.push(match("medium", "Match each to its simplest form.", ["$\\dfrac{x^2-9}{x-3}$", "$\\dfrac{x^2-x}{x}$", "$\\dfrac{2x^2-8}{x-2}$"], ["$x+3$", "$x-1$", "$2(x+2)$"], [0, 1, 2]));
  q.push(mc("hard", "Multiply $\\dfrac{x^2-4}{x}\\cdot\\dfrac{x}{x+2}$.", ["$x-2$", "$x+2$", "$\\dfrac{x-2}{x}$", "$x^2-4$"], 0));
  q.push(mc("hard", "Divide $\\dfrac{x^2-1}{x}\\div\\dfrac{x-1}{x}$.", ["$x+1$", "$x-1$", "$\\dfrac{1}{x+1}$", "$x^2$"], 0));
  q.push(mc("hard", "Simplify $\\dfrac{x^2-5x+6}{x^2-9}$.", ["$\\dfrac{x-2}{x+3}$", "$\\dfrac{x-3}{x+3}$", "$\\dfrac{x-2}{x-3}$", "$1$"], 0));
  q.push(mc("hard", "Restrictions on $\\dfrac{x^2-5x+6}{x^2-9}$.", ["$x\\ne\\pm3$", "$x\\ne3$", "$x\\ne-3$", "$x\\ne2,3$"], 0));
  q.push(mc("hard", "Simplify $\\dfrac{2x^2+5x-3}{x^2-9}$.", ["$\\dfrac{2x-1}{x-3}$", "$\\dfrac{2x-1}{x+3}$", "$\\dfrac{2x+1}{x-3}$", "$1$"], 0));
  q.push(ms("hard", "Multiplying rationals:", ["factor everything", "cancel across", "multiply what remains", "add numerators"], [0, 1, 2]));
  q.push(ms("hard", "Dividing rationals:", ["multiply by the reciprocal", "flip the divisor", "then simplify", "subtract"], [0, 1, 2]));
  q.push(ms("hard", "$\\dfrac{x^2-5x+6}{x^2-9}$:", ["$(x-2)(x-3)$ on top", "$(x-3)(x+3)$ on bottom", "cancel $(x-3)$", "$\\dfrac{x-2}{x+3}$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Restrictions include:", ["zeros of every denominator", "factors that were cancelled", "$x\\ne\\pm3$", "only the final denominator"], [0, 1, 2]));
  q.push(tf("hard", "$\\dfrac{x^2-1}{x}\\div\\dfrac{x-1}{x}=x+1$.", true));
  q.push(tf("hard", "$\\dfrac{x^2-5x+6}{x^2-9}=\\dfrac{x-2}{x+3}$.", true));
  q.push(tf("hard", "When dividing, multiply by the reciprocal of the first fraction.", false));
  q.push(fill("hard", "Simplify $\\dfrac{x^2-5x+6}{x^2-9}$.", ["(x-2)/(x+3)", "\\dfrac{x-2}{x+3}"]));
  q.push(fill("hard", "$\\dfrac{x^2-4}{x}\\cdot\\dfrac{x}{x+2}=$", ["x-2"]));
  q.push(fill("hard", "$\\dfrac{x^2-1}{x}\\div\\dfrac{x-1}{x}=$", ["x+1"]));
  q.push(num("hard", "$\\dfrac{x^2-5x+6}{x^2-9}$ at $x=5$ (decimal).", 0.375, 0.01));
  q.push(num("hard", "Number of restrictions on $\\dfrac{x^2-5x+6}{x^2-9}$.", 2, 0));
  q.push(num("hard", "$\\dfrac{x^2-4}{x}\\cdot\\dfrac{x}{x+2}$ at $x=10$.", 8, 0));
  q.push(order("hard", "Order the steps to simplify $\\dfrac{x^2-5x+6}{x^2-9}$.", ["Factor top: $(x-2)(x-3)$", "Factor bottom: $(x-3)(x+3)$", "Cancel $(x-3)$", "$\\dfrac{x-2}{x+3}$"]));
  q.push(match("hard", "Match each to its result.", ["$\\dfrac{x^2-4}{x}\\cdot\\dfrac{x}{x+2}$", "$\\dfrac{x^2-1}{x}\\div\\dfrac{x-1}{x}$", "$\\dfrac{x^2-5x+6}{x^2-9}$"], ["$x-2$", "$x+1$", "$\\dfrac{x-2}{x+3}$"], [0, 1, 2]));
  return q;
}

// ── 2.4 Adding & Subtracting Rational Expressions ────────────
function g24() {
  const q = [];
  q.push(mc("easy", "$\\dfrac{1}{x}+\\dfrac{2}{x}$ =", ["$\\dfrac{3}{x}$", "$\\dfrac{2}{x}$", "$\\dfrac{3}{2x}$", "$\\dfrac{3}{x^2}$"], 0));
  q.push(mc("easy", "$\\dfrac{3}{x}-\\dfrac{1}{x}$ =", ["$\\dfrac{2}{x}$", "$\\dfrac{4}{x}$", "$\\dfrac{2}{x^2}$", "$2$"], 0));
  q.push(mc("easy", "LCD of $\\dfrac{1}{2}$ and $\\dfrac{1}{3}$.", ["$6$", "$5$", "$2$", "$3$"], 0));
  q.push(mc("easy", "$\\dfrac{x}{4}+\\dfrac{x}{4}$ =", ["$\\dfrac{x}{2}$", "$\\dfrac{2x}{8}$", "$\\dfrac{x}{4}$", "$\\dfrac{x}{8}$"], 0));
  q.push(mc("easy", "LCD of $\\dfrac{1}{x}$ and $\\dfrac{1}{x^2}$.", ["$x^2$", "$x$", "$x^3$", "$1$"], 0));
  q.push(mc("easy", "$\\dfrac{2}{5}+\\dfrac{1}{5}$ =", ["$\\dfrac{3}{5}$", "$\\dfrac{3}{10}$", "$\\dfrac{2}{5}$", "$\\dfrac{3}{25}$"], 0));
  q.push(ms("easy", "Adding fractions:", ["need a common denominator", "add the numerators", "keep the denominator", "add denominators"], [0, 1, 2]));
  q.push(ms("easy", "With the same denominator:", ["just add the tops", "$\\dfrac1x+\\dfrac2x=\\dfrac3x$", "denominator unchanged", "add the bottoms"], [0, 1, 2]));
  q.push(ms("easy", "Finding the LCD:", ["use each factor", "highest power of each", "$x$ and $x^2$ give $x^2$", "always multiply"], [0, 1, 2]));
  q.push(ms("easy", "Subtracting:", ["common denominator first", "subtract numerators", "watch the signs", "subtract denominators"], [0, 1, 2]));
  q.push(tf("easy", "$\\dfrac1x+\\dfrac2x=\\dfrac3x$.", true));
  q.push(tf("easy", "$\\dfrac1x+\\dfrac1y=\\dfrac{1}{x+y}$.", false));
  q.push(tf("easy", "The LCD of $\\dfrac1x,\\dfrac1{x^2}$ is $x^2$.", true));
  q.push(fill("easy", "$\\dfrac{2}{x}+\\dfrac{3}{x}$ =", ["5/x", "\\dfrac{5}{x}"]));
  q.push(fill("easy", "$\\dfrac{5}{x}-\\dfrac{2}{x}$ =", ["3/x", "\\dfrac{3}{x}"]));
  q.push(fill("easy", "LCD of $\\dfrac{1}{6}$ and $\\dfrac{1}{4}$.", ["12"]));
  q.push(num("easy", "$\\dfrac{1}{x}+\\dfrac{2}{x}$ at $x=3$.", 1, 0));
  q.push(num("easy", "$x^2$ at $x=3$ (LCD of $\\dfrac1x,\\dfrac1{x^2}$).", 9, 0));
  q.push(num("easy", "$\\dfrac{3}{x}-\\dfrac{1}{x}$ at $x=4$ (decimal).", 0.5, 0.01));
  q.push(match("easy", "Match each result.", ["$\\dfrac1x+\\dfrac2x$", "$\\dfrac3x-\\dfrac1x$", "$\\dfrac{x}{4}+\\dfrac{x}{4}$"], ["$\\dfrac3x$", "$\\dfrac2x$", "$\\dfrac{x}{2}$"], [0, 1, 2]));
  q.push(mc("medium", "$\\dfrac{1}{x}+\\dfrac{1}{x+1}$ =", ["$\\dfrac{2x+1}{x(x+1)}$", "$\\dfrac{2}{2x+1}$", "$\\dfrac{1}{2x+1}$", "$\\dfrac{2x+1}{x+1}$"], 0));
  q.push(mc("medium", "$\\dfrac{2}{x}-\\dfrac{1}{x+2}$ =", ["$\\dfrac{x+4}{x(x+2)}$", "$\\dfrac{1}{x+2}$", "$\\dfrac{x-4}{x(x+2)}$", "$\\dfrac{3}{x+2}$"], 0));
  q.push(mc("medium", "$\\dfrac{3}{x}+\\dfrac{2}{x^2}$ =", ["$\\dfrac{3x+2}{x^2}$", "$\\dfrac{5}{x^2}$", "$\\dfrac{5}{x^3}$", "$\\dfrac{3x+2}{x^3}$"], 0));
  q.push(mc("medium", "LCD of $\\dfrac{1}{x-1}$ and $\\dfrac{1}{x+1}$.", ["$(x-1)(x+1)$", "$x^2$", "$x-1$", "$x+1$"], 0));
  q.push(mc("medium", "$\\dfrac{x}{x+1}+\\dfrac{1}{x+1}$ =", ["$1$", "$x$", "$\\dfrac{x}{x+1}$", "$x+1$"], 0));
  q.push(mc("medium", "$\\dfrac{1}{x-2}-\\dfrac{1}{x}$ =", ["$\\dfrac{2}{x(x-2)}$", "$\\dfrac{1}{x(x-2)}$", "$\\dfrac{-2}{x(x-2)}$", "$0$"], 0));
  q.push(ms("medium", "Adding $\\dfrac1x+\\dfrac1{x+1}$:", ["LCD $x(x+1)$", "$\\dfrac{(x+1)+x}{x(x+1)}$", "$\\dfrac{2x+1}{x(x+1)}$", "add denominators"], [0, 1, 2]));
  q.push(ms("medium", "LCD when denominators differ:", ["multiply the distinct factors", "$(x-1)(x+1)$", "rewrite each fraction", "just pick one"], [0, 1, 2]));
  q.push(ms("medium", "$\\dfrac{2}{x}-\\dfrac{1}{x+2}$:", ["LCD $x(x+2)$", "numerator $2(x+2)-x$", "$=x+4$", "$\\dfrac{x+4}{x(x+2)}$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Sign care when subtracting:", ["distribute the minus sign", "to every term", "avoid sign errors", "ignore signs"], [0, 1, 2]));
  q.push(tf("medium", "$\\dfrac1x+\\dfrac1{x+1}=\\dfrac{2x+1}{x(x+1)}$.", true));
  q.push(tf("medium", "$\\dfrac{x}{x+1}+\\dfrac{1}{x+1}=1$.", true));
  q.push(tf("medium", "The LCD of $\\dfrac1{x-1},\\dfrac1{x+1}$ is $x^2-1$.", true));
  q.push(fill("medium", "$\\dfrac1x+\\dfrac1{x+1}$ =", ["(2x+1)/(x(x+1))", "\\dfrac{2x+1}{x(x+1)}"]));
  q.push(fill("medium", "$\\dfrac{x}{x+1}+\\dfrac{1}{x+1}$ =", ["1"]));
  q.push(fill("medium", "$\\dfrac{1}{x-2}-\\dfrac{1}{x}$ =", ["2/(x(x-2))", "\\dfrac{2}{x(x-2)}"]));
  q.push(num("medium", "$\\dfrac1x+\\dfrac1{x+1}$ at $x=2$ (decimal).", 0.833, 0.01));
  q.push(num("medium", "$\\dfrac{x}{x+1}+\\dfrac1{x+1}$ at $x=9$.", 1, 0));
  q.push(num("medium", "$\\dfrac{1}{x-2}-\\dfrac{1}{x}$ at $x=4$ (decimal).", 0.25, 0.01));
  q.push(match("medium", "Match each result.", ["$\\dfrac1x+\\dfrac1{x+1}$", "$\\dfrac{x}{x+1}+\\dfrac{1}{x+1}$", "$\\dfrac1{x-2}-\\dfrac1x$"], ["$\\dfrac{2x+1}{x(x+1)}$", "$1$", "$\\dfrac{2}{x(x-2)}$"], [0, 1, 2]));
  q.push(mc("hard", "$\\dfrac{1}{x-1}+\\dfrac{1}{x+1}$ =", ["$\\dfrac{2x}{x^2-1}$", "$\\dfrac{2}{x^2-1}$", "$\\dfrac{2x}{x+1}$", "$\\dfrac{1}{x^2-1}$"], 0));
  q.push(mc("hard", "$\\dfrac{x}{x-2}-\\dfrac{2}{x-2}$ =", ["$1$", "$x-2$", "$\\dfrac{x}{x-2}$", "$\\dfrac{x+2}{x-2}$"], 0));
  q.push(mc("hard", "$\\dfrac{3}{x-1}-\\dfrac{2}{x+1}$ =", ["$\\dfrac{x+5}{x^2-1}$", "$\\dfrac{1}{x^2-1}$", "$\\dfrac{x-5}{x^2-1}$", "$\\dfrac{5}{x^2-1}$"], 0));
  q.push(mc("hard", "The LCD of $\\dfrac{1}{x}+\\dfrac{1}{x+1}+\\dfrac{1}{x+2}$ is:", ["$x(x+1)(x+2)$", "$x^3$", "$x+3$", "$(x+1)$"], 0));
  q.push(mc("hard", "$\\dfrac{2x}{x^2-1}-\\dfrac{1}{x-1}$ =", ["$\\dfrac{1}{x+1}$", "$\\dfrac{2x-1}{x^2-1}$", "$\\dfrac{1}{x-1}$", "$\\dfrac{x}{x^2-1}$"], 0));
  q.push(ms("hard", "$\\dfrac{1}{x-1}+\\dfrac{1}{x+1}$:", ["LCD $(x-1)(x+1)$", "numerator $2x$", "$\\dfrac{2x}{x^2-1}$", "add denominators"], [0, 1, 2]));
  q.push(ms("hard", "$\\dfrac{3}{x-1}-\\dfrac{2}{x+1}$:", ["LCD $x^2-1$", "$3(x+1)-2(x-1)$", "$=x+5$", "$\\dfrac{x+5}{x^2-1}$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Recognising a common factor:", ["$x^2-1=(x-1)(x+1)$", "helps find the LCD", "rewrite each fraction", "ignore it"], [0, 1, 2]));
  q.push(ms("hard", "Simplify after combining:", ["factor the result", "cancel if possible", "state restrictions", "never simplify"], [0, 1, 2]));
  q.push(tf("hard", "$\\dfrac{1}{x-1}+\\dfrac{1}{x+1}=\\dfrac{2x}{x^2-1}$.", true));
  q.push(tf("hard", "$\\dfrac{2x}{x^2-1}-\\dfrac{1}{x-1}=\\dfrac{1}{x+1}$.", true));
  q.push(tf("hard", "$\\dfrac{x}{x-2}-\\dfrac{2}{x-2}=x$.", false));
  q.push(fill("hard", "$\\dfrac1{x-1}+\\dfrac1{x+1}$ =", ["2x/(x^2-1)", "\\dfrac{2x}{x^2-1}"]));
  q.push(fill("hard", "$\\dfrac{3}{x-1}-\\dfrac{2}{x+1}$ =", ["(x+5)/(x^2-1)", "\\dfrac{x+5}{x^2-1}"]));
  q.push(fill("hard", "$\\dfrac{x}{x-2}-\\dfrac{2}{x-2}$ =", ["1"]));
  q.push(num("hard", "$\\dfrac1{x-1}+\\dfrac1{x+1}$ at $x=3$ (decimal).", 0.75, 0.01));
  q.push(num("hard", "$\\dfrac{3}{x-1}-\\dfrac2{x+1}$ at $x=2$ (decimal).", 2.333, 0.01));
  q.push(num("hard", "$\\dfrac{2x}{x^2-1}-\\dfrac1{x-1}$ at $x=3$ (decimal).", 0.25, 0.01));
  q.push(order("hard", "Order the steps to add $\\dfrac{1}{x-1}+\\dfrac{1}{x+1}$.", ["LCD is $(x-1)(x+1)$", "Rewrite: $\\dfrac{(x+1)+(x-1)}{(x-1)(x+1)}$", "Numerator $2x$", "$\\dfrac{2x}{x^2-1}$"]));
  q.push(match("hard", "Match each result.", ["$\\dfrac1{x-1}+\\dfrac1{x+1}$", "$\\dfrac3{x-1}-\\dfrac2{x+1}$", "$\\dfrac{x}{x-2}-\\dfrac2{x-2}$"], ["$\\dfrac{2x}{x^2-1}$", "$\\dfrac{x+5}{x^2-1}$", "$1$"], [0, 1, 2]));
  return q;
}

// ── 2.5 Radicals & Equivalent Expressions ────────────────────
function g25() {
  const q = [];
  q.push(mc("easy", "$\\sqrt{16}$ =", ["$4$", "$8$", "$2$", "$16$"], 0));
  q.push(mc("easy", "$\\sqrt{9}\\cdot\\sqrt{4}$ =", ["$6$", "$13$", "$36$", "$5$"], 0));
  q.push(mc("easy", "Simplify $\\sqrt{8}$.", ["$2\\sqrt2$", "$4\\sqrt2$", "$2\\sqrt4$", "$\\sqrt8$"], 0));
  q.push(mc("easy", "$\\sqrt{25}$ =", ["$5$", "$\\pm5$", "$12.5$", "$625$"], 0));
  q.push(mc("easy", "$3\\sqrt2+2\\sqrt2$ =", ["$5\\sqrt2$", "$5\\sqrt4$", "$6\\sqrt2$", "$5$"], 0));
  q.push(mc("easy", "$\\sqrt{x^2}$ (for $x\\ge0$) =", ["$x$", "$x^2$", "$2x$", "$\\sqrt x$"], 0));
  q.push(ms("easy", "Simplifying $\\sqrt8$:", ["$\\sqrt{4\\cdot2}$", "$2\\sqrt2$", "find perfect-square factors", "$8\\sqrt1$"], [0, 1, 2]));
  q.push(ms("easy", "Like radicals:", ["$3\\sqrt2$ and $2\\sqrt2$", "add the coefficients", "$=5\\sqrt2$", "$\\sqrt2+\\sqrt3$"], [0, 1, 2]));
  q.push(ms("easy", "Product rule:", ["$\\sqrt a\\cdot\\sqrt b=\\sqrt{ab}$", "$\\sqrt9\\cdot\\sqrt4=6$", "$\\sqrt{36}=6$", "$\\sqrt a+\\sqrt b$"], [0, 1, 2]));
  q.push(ms("easy", "Perfect squares:", ["$4,9,16,25$", "$\\sqrt{16}=4$", "help simplify radicals", "$2,3,5$"], [0, 1, 2]));
  q.push(tf("easy", "$\\sqrt{16}=4$.", true));
  q.push(tf("easy", "$\\sqrt2+\\sqrt2=\\sqrt4$.", false));
  q.push(tf("easy", "$\\sqrt8=2\\sqrt2$.", true));
  q.push(fill("easy", "Simplify $\\sqrt{12}$.", ["2√3", "2\\sqrt3", "2 sqrt 3"]));
  q.push(fill("easy", "$\\sqrt{49}$ =", ["7"]));
  q.push(fill("easy", "$4\\sqrt3+\\sqrt3$ =", ["5√3", "5\\sqrt3"]));
  q.push(num("easy", "$\\sqrt{36}$.", 6, 0));
  q.push(num("easy", "$\\sqrt{9}\\cdot\\sqrt{16}$.", 12, 0));
  q.push(num("easy", "$\\sqrt{100}$.", 10, 0));
  q.push(match("easy", "Match each radical.", ["$\\sqrt{16}$", "$\\sqrt8$", "$\\sqrt{49}$"], ["$4$", "$2\\sqrt2$", "$7$"], [0, 1, 2]));
  q.push(mc("medium", "Simplify $\\sqrt{50}$.", ["$5\\sqrt2$", "$25\\sqrt2$", "$2\\sqrt5$", "$5\\sqrt5$"], 0));
  q.push(mc("medium", "$\\sqrt{18}+\\sqrt{2}$ =", ["$4\\sqrt2$", "$\\sqrt{20}$", "$3\\sqrt2$", "$2\\sqrt5$"], 0));
  q.push(mc("medium", "$\\sqrt{3}\\cdot\\sqrt{12}$ =", ["$6$", "$\\sqrt{15}$", "$36$", "$3\\sqrt{12}$"], 0));
  q.push(mc("medium", "Rationalize $\\dfrac{1}{\\sqrt2}$.", ["$\\dfrac{\\sqrt2}{2}$", "$\\sqrt2$", "$\\dfrac{2}{\\sqrt2}$", "$\\dfrac{1}{2}$"], 0));
  q.push(mc("medium", "$(\\sqrt5)^2$ =", ["$5$", "$\\sqrt{25}$", "$25$", "$\\sqrt5$"], 0));
  q.push(mc("medium", "Simplify $2\\sqrt{12}$.", ["$4\\sqrt3$", "$2\\sqrt3$", "$4\\sqrt6$", "$12\\sqrt2$"], 0));
  q.push(ms("medium", "$\\sqrt{50}=5\\sqrt2$ because:", ["$50=25\\cdot2$", "$\\sqrt{25}=5$", "factor out the square", "$50=2\\cdot25$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Combining radicals:", ["only like radicals add", "$\\sqrt{18}=3\\sqrt2$", "$3\\sqrt2+\\sqrt2=4\\sqrt2$", "$\\sqrt2+\\sqrt3=\\sqrt5$"], [0, 1, 2]));
  q.push(ms("medium", "Rationalizing $\\dfrac1{\\sqrt2}$:", ["multiply by $\\dfrac{\\sqrt2}{\\sqrt2}$", "$=\\dfrac{\\sqrt2}{2}$", "removes the root from the denominator", "leave it as is"], [0, 1, 2]));
  q.push(ms("medium", "$\\sqrt3\\cdot\\sqrt{12}$:", ["$=\\sqrt{36}$", "$=6$", "product rule", "$=\\sqrt{15}$"], [0, 1, 2]));
  q.push(tf("medium", "$\\sqrt{50}=5\\sqrt2$.", true));
  q.push(tf("medium", "$\\sqrt2+\\sqrt3=\\sqrt5$.", false));
  q.push(tf("medium", "$\\dfrac1{\\sqrt2}=\\dfrac{\\sqrt2}{2}$.", true));
  q.push(fill("medium", "Simplify $\\sqrt{50}$.", ["5√2", "5\\sqrt2"]));
  q.push(fill("medium", "$\\sqrt{18}+\\sqrt2$ =", ["4√2", "4\\sqrt2"]));
  q.push(fill("medium", "Rationalize $\\dfrac{1}{\\sqrt3}$.", ["√3/3", "\\dfrac{\\sqrt3}{3}"]));
  q.push(num("medium", "$\\sqrt3\\cdot\\sqrt{12}$.", 6, 0));
  q.push(num("medium", "$(\\sqrt7)^2$.", 7, 0));
  q.push(num("medium", "$\\sqrt{18}\\cdot\\sqrt2$.", 6, 0));
  q.push(match("medium", "Match each simplified radical.", ["$\\sqrt{50}$", "$\\sqrt{18}$", "$\\sqrt{12}$"], ["$5\\sqrt2$", "$3\\sqrt2$", "$2\\sqrt3$"], [0, 1, 2]));
  q.push(mc("hard", "Expand $(\\sqrt3+1)(\\sqrt3-1)$.", ["$2$", "$\\sqrt3$", "$4$", "$3$"], 0));
  q.push(mc("hard", "Expand $(\\sqrt5+2)^2$.", ["$9+4\\sqrt5$", "$9$", "$5+4\\sqrt5$", "$7+4\\sqrt5$"], 0));
  q.push(mc("hard", "Rationalize $\\dfrac{1}{\\sqrt3-1}$.", ["$\\dfrac{\\sqrt3+1}{2}$", "$\\sqrt3+1$", "$\\dfrac{\\sqrt3-1}{2}$", "$\\dfrac{1}{2}$"], 0));
  q.push(mc("hard", "Simplify $\\sqrt{75}-\\sqrt{12}$.", ["$3\\sqrt3$", "$\\sqrt{63}$", "$5\\sqrt3$", "$\\sqrt3$"], 0));
  q.push(mc("hard", "$\\dfrac{\\sqrt{18}}{\\sqrt2}$ =", ["$3$", "$\\sqrt{15}$", "$9$", "$\\sqrt{16}$"], 0));
  q.push(ms("hard", "$(\\sqrt3+1)(\\sqrt3-1)$:", ["difference of squares", "$(\\sqrt3)^2-1^2$", "$3-1=2$", "$=\\sqrt3$"], [0, 1, 2]));
  q.push(ms("hard", "$(\\sqrt5+2)^2$:", ["$5+4\\sqrt5+4$", "$9+4\\sqrt5$", "square the binomial", "$=9$"], [0, 1, 2]));
  q.push(ms("hard", "Rationalizing with a conjugate:", ["multiply by the conjugate", "$\\sqrt3-1$ uses $\\sqrt3+1$", "denominator becomes $2$", "square it"], [0, 1, 2]));
  q.push(ms("hard", "$\\sqrt{75}-\\sqrt{12}$:", ["$5\\sqrt3-2\\sqrt3$", "$=3\\sqrt3$", "both reduce to $\\sqrt3$", "$=\\sqrt{63}$"], [0, 1, 2]));
  q.push(tf("hard", "$(\\sqrt3+1)(\\sqrt3-1)=2$.", true));
  q.push(tf("hard", "$\\sqrt{75}-\\sqrt{12}=3\\sqrt3$.", true));
  q.push(tf("hard", "$(\\sqrt5+2)^2=9$.", false));
  q.push(fill("hard", "Expand $(\\sqrt3+1)(\\sqrt3-1)$.", ["2"]));
  q.push(fill("hard", "Simplify $\\sqrt{75}-\\sqrt{12}$.", ["3√3", "3\\sqrt3"]));
  q.push(fill("hard", "Rationalize $\\dfrac{1}{\\sqrt3-1}$.", ["(√3+1)/2", "\\dfrac{\\sqrt3+1}{2}"]));
  q.push(num("hard", "Value of $(\\sqrt3+1)(\\sqrt3-1)$.", 2, 0));
  q.push(num("hard", "$\\dfrac{\\sqrt{18}}{\\sqrt2}$.", 3, 0));
  q.push(num("hard", "Value of $(\\sqrt5+2)^2-4\\sqrt5$.", 9, 0));
  q.push(order("hard", "Order the steps to rationalize $\\dfrac{1}{\\sqrt3-1}$.", ["Multiply by $\\dfrac{\\sqrt3+1}{\\sqrt3+1}$", "Denominator $(\\sqrt3)^2-1=2$", "Numerator $\\sqrt3+1$", "$\\dfrac{\\sqrt3+1}{2}$"]));
  q.push(match("hard", "Match each to its value/form.", ["$(\\sqrt3+1)(\\sqrt3-1)$", "$\\sqrt{75}-\\sqrt{12}$", "$\\dfrac{\\sqrt{18}}{\\sqrt2}$"], ["$2$", "$3\\sqrt3$", "$3$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "2.1", gen: g21 },
  { code: "2.2", gen: g22 },
  { code: "2.3", gen: g23 },
  { code: "2.4", gen: g24 },
  { code: "2.5", gen: g25 },
];
