// MCR3U Unit 3 — Exponential Functions: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 3.1 Exponent Laws & Rational Exponents ───────────────────
function g31() {
  const q = [];
  q.push(mc("easy", "$x^3\\cdot x^4$ =", ["$x^7$", "$x^{12}$", "$x^1$", "$x^{34}$"], 0));
  q.push(mc("easy", "$\\dfrac{x^5}{x^2}$ =", ["$x^3$", "$x^7$", "$x^{2.5}$", "$x^{10}$"], 0));
  q.push(mc("easy", "$(x^2)^3$ =", ["$x^6$", "$x^5$", "$x^8$", "$x^9$"], 0));
  q.push(mc("easy", "$x^0$ =", ["$1$", "$0$", "$x$", "undefined"], 0));
  q.push(mc("easy", "$2^3$ =", ["$8$", "$6$", "$9$", "$5$"], 0));
  q.push(mc("easy", "$x^{-1}$ =", ["$\\dfrac1x$", "$-x$", "$x$", "$0$"], 0));
  q.push(ms("easy", "Product law:", ["$x^a x^b=x^{a+b}$", "add the exponents", "$x^3x^4=x^7$", "multiply the exponents"], [0, 1, 2]));
  q.push(ms("easy", "Quotient law:", ["$\\dfrac{x^a}{x^b}=x^{a-b}$", "subtract the exponents", "$\\dfrac{x^5}{x^2}=x^3$", "add the exponents"], [0, 1, 2]));
  q.push(ms("easy", "Power of a power:", ["$(x^a)^b=x^{ab}$", "multiply the exponents", "$(x^2)^3=x^6$", "add the exponents"], [0, 1, 2]));
  q.push(ms("easy", "Zero & negative exponents:", ["$x^0=1$", "$x^{-1}=\\dfrac1x$", "$x^{-n}=\\dfrac1{x^n}$", "$x^0=0$"], [0, 1, 2]));
  q.push(tf("easy", "$x^3\\cdot x^4=x^7$.", true));
  q.push(tf("easy", "$(x^2)^3=x^5$.", false));
  q.push(tf("easy", "$x^0=1$ for $x\\ne0$.", true));
  q.push(fill("easy", "Simplify $x^2\\cdot x^6$.", ["x^8", "x⁸"]));
  q.push(fill("easy", "Simplify $(x^3)^2$.", ["x^6", "x⁶"]));
  q.push(fill("easy", "Simplify $\\dfrac{x^7}{x^3}$.", ["x^4", "x⁴"]));
  q.push(num("easy", "$2^4$.", 16, 0));
  q.push(num("easy", "$5^2$.", 25, 0));
  q.push(num("easy", "$3^3$.", 27, 0));
  q.push(match("easy", "Match each.", ["$x^2\\cdot x^3$", "$(x^2)^4$", "$\\dfrac{x^6}{x^2}$"], ["$x^5$", "$x^8$", "$x^4$"], [0, 1, 2]));
  q.push(mc("medium", "$16^{1/2}$ =", ["$4$", "$8$", "$2$", "$32$"], 0));
  q.push(mc("medium", "$8^{1/3}$ =", ["$2$", "$4$", "$3$", "$8$"], 0));
  q.push(mc("medium", "$x^{1/2}$ means:", ["$\\sqrt x$", "$\\dfrac x2$", "$2x$", "$x^2$"], 0));
  q.push(mc("medium", "$27^{2/3}$ =", ["$9$", "$18$", "$6$", "$3$"], 0));
  q.push(mc("medium", "$4^{-2}$ =", ["$\\dfrac{1}{16}$", "$-16$", "$16$", "$-8$"], 0));
  q.push(mc("medium", "$\\left(\\dfrac{x^2}{y}\\right)^3$ =", ["$\\dfrac{x^6}{y^3}$", "$\\dfrac{x^5}{y^3}$", "$\\dfrac{x^6}{y}$", "$\\dfrac{x^8}{y^3}$"], 0));
  q.push(ms("medium", "Rational exponents:", ["$x^{1/2}=\\sqrt x$", "$x^{m/n}=\\sqrt[n]{x^m}$", "$8^{1/3}=2$", "$x^{1/2}=2x$"], [0, 1, 2]));
  q.push(ms("medium", "$27^{2/3}$:", ["$=(27^{1/3})^2$", "$=3^2$", "$=9$", "$=18$"], [0, 1, 2]));
  q.push(ms("medium", "Negative exponents:", ["$4^{-2}=\\dfrac1{4^2}$", "$=\\dfrac1{16}$", "reciprocal then power", "$=-16$"], [0, 1, 2]));
  q.push(ms("medium", "Power of a quotient:", ["$\\left(\\dfrac ab\\right)^n=\\dfrac{a^n}{b^n}$", "apply to each part", "$\\left(\\dfrac{x^2}{y}\\right)^3=\\dfrac{x^6}{y^3}$", "only the top"], [0, 1, 2]));
  q.push(tf("medium", "$8^{1/3}=2$.", true));
  q.push(tf("medium", "$27^{2/3}=9$.", true));
  q.push(tf("medium", "$4^{-2}=-16$.", false));
  q.push(fill("medium", "Evaluate $16^{1/2}$.", ["4"]));
  q.push(fill("medium", "Evaluate $8^{2/3}$.", ["4"]));
  q.push(fill("medium", "Evaluate $4^{-2}$.", ["1/16", "0.0625"]));
  q.push(num("medium", "$25^{1/2}$.", 5, 0));
  q.push(num("medium", "$27^{1/3}$.", 3, 0));
  q.push(num("medium", "$16^{3/4}$.", 8, 0));
  q.push(match("medium", "Match each value.", ["$16^{1/2}$", "$8^{1/3}$", "$27^{2/3}$"], ["$4$", "$2$", "$9$"], [0, 1, 2]));
  q.push(mc("hard", "Simplify $\\dfrac{x^{1/2}\\cdot x^{3/2}}{x}$.", ["$x$", "$x^2$", "$1$", "$x^{1/2}$"], 0));
  q.push(mc("hard", "$(x^{2/3})^{3}$ =", ["$x^2$", "$x^{9}$", "$x^{2/9}$", "$x^{11/3}$"], 0));
  q.push(mc("hard", "Simplify $\\left(\\dfrac{8x^3}{27}\\right)^{1/3}$.", ["$\\dfrac{2x}{3}$", "$\\dfrac{8x}{27}$", "$\\dfrac{2x^3}{3}$", "$\\dfrac{2}{3}x^3$"], 0));
  q.push(mc("hard", "$32^{2/5}$ =", ["$4$", "$8$", "$16$", "$2$"], 0));
  q.push(mc("hard", "Simplify $\\dfrac{a^{-2}b^3}{a^{-4}b}$.", ["$a^2b^2$", "$a^{-6}b^2$", "$a^2b^4$", "$b^2$"], 0));
  q.push(ms("hard", "$\\dfrac{x^{1/2}\\cdot x^{3/2}}{x}$:", ["add: $x^{2}$", "divide: $x^{2-1}$", "$=x$", "$=x^2$"], [0, 1, 2]));
  q.push(ms("hard", "$32^{2/5}$:", ["$=(32^{1/5})^2$", "$32^{1/5}=2$", "$=4$", "$=16$"], [0, 1, 2]));
  q.push(ms("hard", "Simplifying $\\dfrac{a^{-2}b^3}{a^{-4}b}$:", ["$a^{-2-(-4)}=a^2$", "$b^{3-1}=b^2$", "$=a^2b^2$", "$=b^2$"], [0, 1, 2]));
  q.push(ms("hard", "Combining the laws:", ["use all the laws", "convert roots to exponents", "simplify step by step", "guess"], [0, 1, 2]));
  q.push(tf("hard", "$32^{2/5}=4$.", true));
  q.push(tf("hard", "$\\left(\\dfrac{8x^3}{27}\\right)^{1/3}=\\dfrac{2x}{3}$.", true));
  q.push(tf("hard", "$(x^{2/3})^3=x^{2/9}$.", false));
  q.push(fill("hard", "Simplify $(x^{2/3})^3$.", ["x^2", "x²"]));
  q.push(fill("hard", "Evaluate $32^{2/5}$.", ["4"]));
  q.push(fill("hard", "Simplify $\\dfrac{a^{-2}b^3}{a^{-4}b}$.", ["a^2b^2", "a²b²"]));
  q.push(num("hard", "$32^{2/5}$.", 4, 0));
  q.push(num("hard", "$\\dfrac{x^{1/2}\\cdot x^{3/2}}{x}$ at $x=7$.", 7, 0));
  q.push(num("hard", "$64^{2/3}$.", 16, 0));
  q.push(order("hard", "Order the steps to evaluate $27^{2/3}$.", ["Take the cube root: $27^{1/3}=3$", "Square it: $3^2$", "$=9$", "State the result"]));
  q.push(match("hard", "Match each value.", ["$32^{2/5}$", "$64^{2/3}$", "$16^{3/4}$"], ["$4$", "$16$", "$8$"], [0, 1, 2]));
  return q;
}

// ── 3.2 Exponential Functions & Their Graphs ─────────────────
function g32() {
  const q = [];
  q.push(mc("easy", "$f(x)=2^x$ at $x=3$.", ["$8$", "$6$", "$9$", "$5$"], 0));
  q.push(mc("easy", "$f(x)=2^x$ at $x=0$.", ["$1$", "$0$", "$2$", "undefined"], 0));
  q.push(mc("easy", "The base of $y=3^x$ is:", ["$3$", "$x$", "$1$", "$0$"], 0));
  q.push(mc("easy", "$y=2^x$ for large $x$:", ["grows", "shrinks to 0", "stays constant", "is negative"], 0));
  q.push(mc("easy", "$y=2^x$ at $x=-1$.", ["$\\dfrac12$", "$-2$", "$2$", "$0$"], 0));
  q.push(mc("easy", "The $y$-intercept of $y=b^x$ is:", ["$1$", "$0$", "$b$", "$x$"], 0));
  q.push(ms("easy", "For $y=2^x$:", ["passes $(0,1)$", "increasing", "always positive", "passes $(0,0)$"], [0, 1, 2]));
  q.push(ms("easy", "Exponential functions:", ["variable in the exponent", "base $>0$", "e.g. $y=2^x$", "variable in the base"], [0, 1, 2]));
  q.push(ms("easy", "Asymptote of $y=2^x$:", ["$y=0$", "horizontal", "the graph approaches it", "$x=0$"], [0, 1, 2]));
  q.push(ms("easy", "Growth vs decay:", ["$b>1$ grows", "$0<b<1$ decays", "depends on the base", "$b<0$"], [0, 1, 2]));
  q.push(tf("easy", "$2^0=1$.", true));
  q.push(tf("easy", "$y=2^x$ can be negative.", false));
  q.push(tf("easy", "$y=2^x$ passes through $(0,1)$.", true));
  q.push(fill("easy", "$2^x$ at $x=4$.", ["16"]));
  q.push(fill("easy", "$3^x$ at $x=2$.", ["9"]));
  q.push(fill("easy", "$5^x$ at $x=0$.", ["1"]));
  q.push(num("easy", "$2^5$.", 32, 0));
  q.push(num("easy", "$10^2$.", 100, 0));
  q.push(num("easy", "$2^x$ at $x=6$.", 64, 0));
  q.push(match("easy", "Match each value.", ["$2^3$", "$3^2$", "$2^0$"], ["$8$", "$9$", "$1$"], [0, 1, 2]));
  q.push(mc("medium", "$y=\\left(\\dfrac12\\right)^x$ is:", ["decay", "growth", "linear", "constant"], 0));
  q.push(mc("medium", "Horizontal asymptote of $y=2^x+3$:", ["$y=3$", "$y=0$", "$y=2$", "$x=3$"], 0));
  q.push(mc("medium", "$y$-intercept of $y=3\\cdot2^x$:", ["$3$", "$1$", "$6$", "$2$"], 0));
  q.push(mc("medium", "$y=2^x$ vs $y=5^x$: which grows faster?", ["$5^x$", "$2^x$", "same", "neither"], 0));
  q.push(mc("medium", "$f(x)=4^x$ at $x=1/2$.", ["$2$", "$4$", "$16$", "$8$"], 0));
  q.push(mc("medium", "As $x\\to-\\infty$, $y=2^x\\to$", ["$0$", "$\\infty$", "$1$", "$-\\infty$"], 0));
  q.push(ms("medium", "Decay functions:", ["$0<b<1$", "$y=(1/2)^x$", "decreasing", "$b>1$"], [0, 1, 2]));
  q.push(ms("medium", "The graph of $y=2^x+3$:", ["shifts up 3", "asymptote $y=3$", "$y$-intercept 4", "asymptote $y=0$"], [0, 1, 2]));
  q.push(ms("medium", "Comparing $2^x$ and $5^x$:", ["both pass $(0,1)$", "$5^x$ is steeper", "larger base grows faster", "$2^x$ is steeper"], [0, 1, 2]));
  q.push(ms("medium", "Domain & range of $y=2^x$:", ["domain all reals", "range $y>0$", "never zero", "range all reals"], [0, 1, 2]));
  q.push(tf("medium", "$y=(1/2)^x$ is exponential decay.", true));
  q.push(tf("medium", "$y=2^x+3$ has asymptote $y=3$.", true));
  q.push(tf("medium", "$y=2^x$ has range all real numbers.", false));
  q.push(fill("medium", "$y$-intercept of $y=3\\cdot2^x$.", ["3"]));
  q.push(fill("medium", "Horizontal asymptote of $y=2^x-5$.", ["y=-5", "-5"]));
  q.push(fill("medium", "$4^{1/2}$.", ["2"]));
  q.push(num("medium", "$y$-intercept of $y=5\\cdot2^x$.", 5, 0));
  q.push(num("medium", "$9^{1/2}$.", 3, 0));
  q.push(num("medium", "Asymptote $y=$ of $y=2^x+7$.", 7, 0));
  q.push(match("medium", "Match each to its asymptote.", ["$2^x$", "$2^x+3$", "$2^x-5$"], ["$y=0$", "$y=3$", "$y=-5$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $2^x=32$.", ["$5$", "$16$", "$6$", "$4$"], 0));
  q.push(mc("hard", "Solve $3^x=\\dfrac19$.", ["$-2$", "$2$", "$-3$", "$3$"], 0));
  q.push(mc("hard", "If $y=a\\cdot b^x$ passes $(0,5)$ and $(1,15)$, then $b=$", ["$3$", "$5$", "$15$", "$10$"], 0));
  q.push(mc("hard", "Solve $2^{x+1}=16$.", ["$3$", "$4$", "$8$", "$15$"], 0));
  q.push(mc("hard", "$y=2^x$ and $y=8$ meet at $x=$", ["$3$", "$4$", "$2$", "$16$"], 0));
  q.push(ms("hard", "Solving $2^x=32$:", ["write $32=2^5$", "equate exponents", "$x=5$", "$x=16$"], [0, 1, 2]));
  q.push(ms("hard", "For $y=a\\cdot b^x$ through $(0,5),(1,15)$:", ["$a=5$", "$5b=15$", "$b=3$", "$b=15$"], [0, 1, 2]));
  q.push(ms("hard", "Solving $3^x=1/9$:", ["$1/9=3^{-2}$", "$x=-2$", "negative exponent", "$x=2$"], [0, 1, 2]));
  q.push(ms("hard", "Exponential equations (same base):", ["rewrite with one base", "equate exponents", "solve", "add the bases"], [0, 1, 2]));
  q.push(tf("hard", "$2^x=32$ gives $x=5$.", true));
  q.push(tf("hard", "$3^x=1/9$ gives $x=-2$.", true));
  q.push(tf("hard", "$2^{x+1}=16$ gives $x=4$.", false));
  q.push(fill("hard", "Solve $2^x=64$.", ["6"]));
  q.push(fill("hard", "Solve $3^x=27$.", ["3"]));
  q.push(fill("hard", "Solve $2^{x+1}=16$.", ["3"]));
  q.push(num("hard", "Solve $2^x=128$.", 7, 0));
  q.push(num("hard", "Solve $5^x=125$.", 3, 0));
  q.push(num("hard", "Solve $2^{x-1}=8$.", 4, 0));
  q.push(order("hard", "Order the steps to solve $2^x=32$.", ["Write $32=2^5$", "So $2^x=2^5$", "Equate exponents", "$x=5$"]));
  q.push(match("hard", "Match each equation to its solution.", ["$2^x=32$", "$3^x=\\dfrac19$", "$2^{x+1}=16$"], ["$5$", "$-2$", "$3$"], [0, 1, 2]));
  return q;
}

// ── 3.3 Transformations of Exponential Functions ─────────────
function g33() {
  const q = [];
  q.push(mc("easy", "$y=2^x+3$ shifts:", ["up 3", "down 3", "right 3", "left 3"], 0));
  q.push(mc("easy", "$y=2^{x-1}$ shifts:", ["right 1", "left 1", "up 1", "down 1"], 0));
  q.push(mc("easy", "$y=-2^x$ is:", ["a reflection in the $x$-axis", "a shift up", "a stretch", "a shift right"], 0));
  q.push(mc("easy", "$y=2^x-4$ has asymptote:", ["$y=-4$", "$y=4$", "$y=0$", "$x=-4$"], 0));
  q.push(mc("easy", "$y=3\\cdot2^x$ is a:", ["vertical stretch by 3", "shift up 3", "reflection", "shift right 3"], 0));
  q.push(mc("easy", "$y=2^{x+2}$ shifts:", ["left 2", "right 2", "up 2", "down 2"], 0));
  q.push(ms("easy", "In $y=a\\cdot b^{(x-d)}+c$:", ["$c$ vertical shift", "$d$ horizontal shift", "$a$ stretch/reflect", "$c$ horizontal shift"], [0, 1, 2]));
  q.push(ms("easy", "$y=2^x-4$:", ["shifts down 4", "asymptote $y=-4$", "from $y=2^x$", "asymptote $y=0$"], [0, 1, 2]));
  q.push(ms("easy", "Reflections:", ["$y=-2^x$ over the $x$-axis", "$y=2^{-x}$ over the $y$-axis", "flip the graph", "shift it"], [0, 1, 2]));
  q.push(ms("easy", "The asymptote moves with:", ["the vertical shift $c$", "to $y=c$", "not with horizontal shifts", "the base"], [0, 1, 2]));
  q.push(tf("easy", "$y=2^x+3$ shifts up 3.", true));
  q.push(tf("easy", "$y=2^{x-1}$ shifts left 1.", false));
  q.push(tf("easy", "$y=2^x-4$ has asymptote $y=-4$.", true));
  q.push(fill("easy", "Asymptote of $y=2^x+5$.", ["y=5", "5"]));
  q.push(fill("easy", "$y=2^{x-3}$ shifts (direction & amount).", ["right 3", "right3"]));
  q.push(fill("easy", "Asymptote of $y=2^x-2$.", ["y=-2", "-2"]));
  q.push(num("easy", "Asymptote $y=$ of $y=2^x+6$.", 6, 0));
  q.push(num("easy", "$y$-intercept of $y=2^x+3$.", 4, 0));
  q.push(num("easy", "Asymptote $y=$ of $y=3\\cdot2^x-1$.", -1, 0));
  q.push(match("easy", "Match each to its asymptote.", ["$2^x+3$", "$2^x-4$", "$2^x+1$"], ["$y=3$", "$y=-4$", "$y=1$"], [0, 1, 2]));
  q.push(mc("medium", "$y=2^{x-1}+3$: asymptote and shift.", ["$y=3$, right 1", "$y=1$, right 3", "$y=3$, left 1", "$y=-3$"], 0));
  q.push(mc("medium", "$y=-2^x+5$ has asymptote:", ["$y=5$", "$y=-5$", "$y=0$", "$y=2$"], 0));
  q.push(mc("medium", "$y=2^{-x}$ is $2^x$ reflected in:", ["the $y$-axis", "the $x$-axis", "$y=x$", "the origin"], 0));
  q.push(mc("medium", "$y$-intercept of $y=2^{x}+3$:", ["$4$", "$3$", "$1$", "$5$"], 0));
  q.push(mc("medium", "$y=4\\cdot2^x$ can be written as:", ["$2^{x+2}$", "$2^{x+4}$", "$8^x$", "$2^{4x}$"], 0));
  q.push(mc("medium", "$y=2^x$ stretched vertically by 3 then up 1:", ["$y=3\\cdot2^x+1$", "$y=2^{3x}+1$", "$y=3\\cdot2^{x+1}$", "$y=2^x+4$"], 0));
  q.push(ms("medium", "For $y=2^{x-1}+3$:", ["right 1", "up 3", "asymptote $y=3$", "left 1"], [0, 1, 2]));
  q.push(ms("medium", "$y=-2^x+5$:", ["reflect over the $x$-axis", "up 5", "asymptote $y=5$", "asymptote $y=-5$"], [0, 1, 2]));
  q.push(ms("medium", "Combining transformations:", ["stretch/reflect first", "then shift", "asymptote from $c$", "order never matters"], [0, 1, 2]));
  q.push(ms("medium", "$y=2^{-x}$:", ["reflection over the $y$-axis", "decay", "$=(1/2)^x$", "growth"], [0, 1, 2]));
  q.push(tf("medium", "$y=2^{x-1}+3$ has asymptote $y=3$.", true));
  q.push(tf("medium", "$y=2^{-x}=(1/2)^x$.", true));
  q.push(tf("medium", "$y=-2^x+5$ has asymptote $y=-5$.", false));
  q.push(fill("medium", "Asymptote of $y=2^{x-1}+3$.", ["y=3", "3"]));
  q.push(fill("medium", "$y$-intercept of $y=2^x+3$.", ["4"]));
  q.push(fill("medium", "Rewrite $y=2^{-x}$ with a fractional base.", ["(1/2)^x", "(0.5)^x"]));
  q.push(num("medium", "Asymptote $y=$ of $y=2^{x+2}-3$.", -3, 0));
  q.push(num("medium", "$y$-intercept of $y=2^x+10$.", 11, 0));
  q.push(num("medium", "Asymptote $y=$ of $y=-2^x+8$.", 8, 0));
  q.push(match("medium", "Match each to its asymptote.", ["$2^{x-1}+3$", "$-2^x+5$", "$2^{x+2}-3$"], ["$y=3$", "$y=5$", "$y=-3$"], [0, 1, 2]));
  q.push(mc("hard", "Describe $y=-3\\cdot2^{x-1}+4$ fully.", ["reflect, stretch 3, right 1, up 4", "stretch 3, left 1, up 4", "reflect, right 1, down 4", "stretch 3, up 4 only"], 0));
  q.push(mc("hard", "Asymptote of $y=-3\\cdot2^{x-1}+4$.", ["$y=4$", "$y=-4$", "$y=0$", "$y=1$"], 0));
  q.push(mc("hard", "$y$-intercept of $y=2^{x}+3$ minus that of $y=2^x-1$:", ["$4$", "$2$", "$0$", "$1$"], 0));
  q.push(mc("hard", "The point $(0,1)$ on $y=2^x$ moves to which point on $y=2^x+5$?", ["$(0,6)$", "$(0,5)$", "$(5,1)$", "$(0,1)$"], 0));
  q.push(mc("hard", "$y=2^{x}$ reflected over the $x$-axis then up 6 is:", ["$y=-2^x+6$", "$y=2^{-x}+6$", "$y=-2^x-6$", "$y=2^x+6$"], 0));
  q.push(ms("hard", "For $y=-3\\cdot2^{x-1}+4$:", ["$a=-3$ reflect & stretch", "$d=1$ right", "$c=4$ up", "asymptote $y=4$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Finding the asymptote:", ["it is $y=c$", "here $y=4$", "comes from the vertical shift", "is $y=0$ always"], [0, 1, 2]));
  q.push(ms("hard", "Mapping a point:", ["apply each transformation", "$(0,1)\\to(0,6)$ for $+5$", "track the $y$-changes", "$x$ never matters"], [0, 1, 2]));
  q.push(ms("hard", "Reflect over the $x$-axis:", ["multiply $y$ by $-1$", "$y=-2^x$", "flips up/down", "over the $y$-axis"], [0, 1, 2]));
  q.push(tf("hard", "$y=-3\\cdot2^{x-1}+4$ has asymptote $y=4$.", true));
  q.push(tf("hard", "Reflecting $y=2^x$ over the $x$-axis gives $y=-2^x$.", true));
  q.push(tf("hard", "The asymptote of $y=-3\\cdot2^{x-1}+4$ is $y=0$.", false));
  q.push(fill("hard", "Asymptote of $y=-3\\cdot2^{x-1}+4$.", ["y=4", "4"]));
  q.push(fill("hard", "Image of $(0,1)$ on $y=2^x$ under a $+5$ shift.", ["(0,6)", "0,6"]));
  q.push(fill("hard", "Equation: $y=2^x$ reflected over the $x$-axis, up 6.", ["-2^x+6", "y=-2^x+6"]));
  q.push(num("hard", "Asymptote $y=$ of $y=-3\\cdot2^{x-1}+4$.", 4, 0));
  q.push(num("hard", "$y$-coordinate of the image of $(0,1)$ under a $+5$ shift.", 6, 0));
  q.push(num("hard", "$y$-intercept of $y=-2^x+6$.", 5, 0));
  q.push(order("hard", "Order the transformations to graph $y=-3\\cdot2^{x-1}+4$.", ["Stretch vertically by 3", "Reflect in the $x$-axis", "Shift right 1", "Shift up 4"]));
  q.push(match("hard", "Match each to its asymptote.", ["$-3\\cdot2^{x-1}+4$", "$2^{x+2}-3$", "$-2^x+5$"], ["$y=4$", "$y=-3$", "$y=5$"], [0, 1, 2]));
  return q;
}

// ── 3.4 Applications: Growth, Decay & Compound Interest ──────
function g34() {
  const q = [];
  q.push(mc("easy", "Doubling each year is modeled by:", ["$y=a\\cdot2^x$", "$y=2x$", "$y=x^2$", "$y=a+2x$"], 0));
  q.push(mc("easy", "Half-life uses base:", ["$\\dfrac12$", "$2$", "$1$", "$10$"], 0));
  q.push(mc("easy", "Compound interest: $A=$", ["$P(1+i)^n$", "$Prt$", "$P+rn$", "$P(1+rn)$"], 0));
  q.push(mc("easy", "After 3 doublings, a population is multiplied by:", ["$8$", "$6$", "$3$", "$9$"], 0));
  q.push(mc("easy", "Growth factor for $+10\\%$ per year:", ["$1.10$", "$0.10$", "$10$", "$1.01$"], 0));
  q.push(mc("easy", "Decay factor for $-20\\%$ per year:", ["$0.80$", "$1.20$", "$0.20$", "$-0.20$"], 0));
  q.push(ms("easy", "Growth models:", ["$y=a\\cdot b^x$", "$b>1$ growth", "$b<1$ decay", "linear"], [0, 1, 2]));
  q.push(ms("easy", "Compound interest:", ["$A=P(1+i)^n$", "exponential", "$i$ is the rate per period", "simple"], [0, 1, 2]));
  q.push(ms("easy", "A growth factor:", ["$1+r$", "$1.10$ for $+10\\%$", "multiplies each period", "$r$ alone"], [0, 1, 2]));
  q.push(ms("easy", "Half-life:", ["base $1/2$", "the amount halves", "$y=a(1/2)^{t/h}$", "base 2"], [0, 1, 2]));
  q.push(tf("easy", "A growth factor of 1.10 means $+10\\%$ per period.", true));
  q.push(tf("easy", "Half-life uses base 2.", false));
  q.push(tf("easy", "$A=P(1+i)^n$ is compound interest.", true));
  q.push(fill("easy", "Growth factor for $+5\\%$ per year.", ["1.05"]));
  q.push(fill("easy", "Decay factor for $-10\\%$ per year.", ["0.90", "0.9"]));
  q.push(fill("easy", "After 2 doublings, multiply by.", ["4"]));
  q.push(num("easy", "$1000$ doubled 3 times.", 8000, 0));
  q.push(num("easy", "Growth factor for $+25\\%$ (decimal).", 1.25, 0.001));
  q.push(num("easy", "After 4 doublings, the multiplier.", 16, 0));
  q.push(match("easy", "Match each to its factor.", ["$+10\\%$/yr", "$-20\\%$/yr", "$+5\\%$/yr"], ["$1.10$", "$0.80$", "$1.05$"], [0, 1, 2]));
  q.push(mc("medium", "$1000$ at $5\\%$/yr compounded annually for 2 yr:", ["$\\approx1102.50$", "$1100$", "$1050$", "$1010$"], 0));
  q.push(mc("medium", "$P=200(2)^t$ ($t$ in years). After 3 yr:", ["$1600$", "$1200$", "$600$", "$800$"], 0));
  q.push(mc("medium", "A sample halves every 5 yr. After 10 yr, fraction left:", ["$\\dfrac14$", "$\\dfrac12$", "$\\dfrac18$", "$0$"], 0));
  q.push(mc("medium", "$V=5000(0.9)^t$. After 1 yr:", ["$4500$", "$4900$", "$5500$", "$450$"], 0));
  q.push(mc("medium", "$+8\\%$/yr growth factor:", ["$1.08$", "$0.92$", "$8$", "$1.8$"], 0));
  q.push(mc("medium", "$A=P(1.05)^{10}$ models:", ["$5\\%$/yr for 10 yr", "$10\\%$/yr for 5 yr", "simple interest", "decay"], 0));
  q.push(ms("medium", "Compound interest $1000$ at $5\\%$ for 2 yr:", ["$1000(1.05)^2$", "$=1102.50$", "exponential", "$1000(1+0.10)$"], [0, 1, 2]));
  q.push(ms("medium", "Half-life problems:", ["count the periods", "$10/5=2$ half-lives", "$(1/2)^2=1/4$", "subtract"], [0, 1, 2]));
  q.push(ms("medium", "Decay $V=5000(0.9)^t$:", ["$10\\%$ loss per year", "factor 0.9", "$t$ in years", "growth"], [0, 1, 2]));
  q.push(ms("medium", "Building a model:", ["$y=a\\cdot b^t$", "$a$ initial amount", "$b$ factor", "ignore the initial"], [0, 1, 2]));
  q.push(tf("medium", "$1000$ at $5\\%$ compounded annually for 2 yr is about $1102.50$.", true));
  q.push(tf("medium", "Halving every 5 yr leaves $1/4$ after 10 yr.", true));
  q.push(tf("medium", "A $+8\\%$ growth factor is $0.92$.", false));
  q.push(fill("medium", "$200(2)^t$ at $t=3$.", ["1600"]));
  q.push(fill("medium", "Fraction left after 2 half-lives.", ["1/4", "0.25"]));
  q.push(fill("medium", "Growth factor for $+8\\%$/yr.", ["1.08"]));
  q.push(num("medium", "$1000(1.05)^2$ (to cents).", 1102.50, 0.5));
  q.push(num("medium", "$200\\cdot2^3$.", 1600, 0));
  q.push(num("medium", "$5000(0.9)^1$.", 4500, 0));
  q.push(match("medium", "Match each model to its meaning.", ["$P(1.05)^n$", "$P(0.9)^n$", "$P(2)^n$"], ["$+5\\%$/period", "$-10\\%$/period", "doubling"], [0, 1, 2]));
  q.push(mc("hard", "A culture triples every 4 h ($t$ in hours):", ["$y=a\\cdot3^{t/4}$", "$y=a\\cdot3^{4t}$", "$y=a\\cdot4^{t/3}$", "$y=a+3t$"], 0));
  q.push(mc("hard", "$2000$ at $6\\%$/yr compounded monthly for 1 yr: $A=$", ["$2000(1.005)^{12}$", "$2000(1.06)^{12}$", "$2000(1.5)^{12}$", "$2000(1.06)$"], 0));
  q.push(mc("hard", "A drug halves every 6 h. After 18 h, fraction left:", ["$\\dfrac18$", "$\\dfrac14$", "$\\dfrac16$", "$\\dfrac12$"], 0));
  q.push(mc("hard", "$500(1.04)^t=1000$ asks for:", ["the doubling time", "the rate", "the principal", "nothing"], 0));
  q.push(mc("hard", "How many doublings until $100$ exceeds $1000$?", ["$4$", "$3$", "$10$", "$5$"], 0));
  q.push(ms("hard", "Tripling every 4 h:", ["base 3", "exponent $t/4$", "$y=a\\cdot3^{t/4}$", "base 4"], [0, 1, 2]));
  q.push(ms("hard", "Monthly compounding for $6\\%$/yr:", ["$i=0.06/12=0.005$", "$n=12$", "$A=P(1.005)^{12}$", "$i=0.06$"], [0, 1, 2]));
  q.push(ms("hard", "Half-life after 18 h with a 6-h half-life:", ["$18/6=3$", "$(1/2)^3$", "$=1/8$", "$=1/3$"], [0, 1, 2]));
  q.push(ms("hard", "Doublings to pass 1000 from 100:", ["need $\\times10$", "$2^3=8$ too small", "$2^4=16$ works", "$2^3$ works"], [0, 1, 2]));
  q.push(tf("hard", "$6\\%$/yr compounded monthly uses $i=0.005$.", true));
  q.push(tf("hard", "A drug with a 6-h half-life leaves $1/8$ after 18 h.", true));
  q.push(tf("hard", "Tripling every 4 h is $y=a\\cdot3^{4t}$.", false));
  q.push(fill("hard", "Monthly rate $i$ for $6\\%$/yr compounded monthly.", ["0.005"]));
  q.push(fill("hard", "Fraction left after 3 half-lives.", ["1/8", "0.125"]));
  q.push(fill("hard", "Doublings for $100$ to exceed $1000$.", ["4"]));
  q.push(num("hard", "Number of half-lives in 18 h with a 6-h half-life.", 3, 0));
  q.push(num("hard", "$i$ (decimal) for $6\\%$/yr compounded monthly.", 0.005, 0.0001));
  q.push(num("hard", "Doublings for $100$ to exceed $1000$.", 4, 0));
  q.push(order("hard", "Order the steps for $2000$ at $6\\%$/yr compounded monthly for 1 yr.", ["$i=0.06/12=0.005$", "$n=12$", "$A=2000(1.005)^{12}$", "$A\\approx2123.36$"]));
  q.push(match("hard", "Match each scenario to its model.", ["triples every 4 h", "halves every 6 h", "$6\\%$/yr monthly"], ["$a\\cdot3^{t/4}$", "$a(1/2)^{t/6}$", "$P(1.005)^{n}$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "3.1", gen: g31 },
  { code: "3.2", gen: g32 },
  { code: "3.3", gen: g33 },
  { code: "3.4", gen: g34 },
];
