// MCR3U Unit 4 — Trigonometry: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 4.1 Trigonometric Ratios & Special Angles ────────────────
function g41() {
  const q = [];
  q.push(mc("easy", "In a right triangle, $\\sin\\theta=$", ["$\\dfrac{\\text{opp}}{\\text{hyp}}$", "$\\dfrac{\\text{adj}}{\\text{hyp}}$", "$\\dfrac{\\text{opp}}{\\text{adj}}$", "$\\dfrac{\\text{hyp}}{\\text{opp}}$"], 0));
  q.push(mc("easy", "$\\cos\\theta=$", ["$\\dfrac{\\text{adj}}{\\text{hyp}}$", "$\\dfrac{\\text{opp}}{\\text{hyp}}$", "$\\dfrac{\\text{opp}}{\\text{adj}}$", "$\\dfrac{\\text{hyp}}{\\text{adj}}$"], 0));
  q.push(mc("easy", "$\\tan\\theta=$", ["$\\dfrac{\\text{opp}}{\\text{adj}}$", "$\\dfrac{\\text{adj}}{\\text{opp}}$", "$\\dfrac{\\text{opp}}{\\text{hyp}}$", "$\\dfrac{\\text{hyp}}{\\text{adj}}$"], 0));
  q.push(mc("easy", "$\\sin30°=$", ["$\\dfrac12$", "$\\dfrac{\\sqrt3}2$", "$1$", "$\\dfrac{\\sqrt2}2$"], 0));
  q.push(mc("easy", "$\\cos60°=$", ["$\\dfrac12$", "$\\dfrac{\\sqrt3}2$", "$1$", "$0$"], 0));
  q.push(mc("easy", "$\\tan45°=$", ["$1$", "$0$", "$\\dfrac12$", "$\\sqrt3$"], 0));
  q.push(ms("easy", "SOH CAH TOA:", ["$\\sin=$ opp/hyp", "$\\cos=$ adj/hyp", "$\\tan=$ opp/adj", "$\\sin=$ adj/hyp"], [0, 1, 2]));
  q.push(ms("easy", "Special angles:", ["$30°,45°,60°$", "have exact values", "come from special triangles", "$33°$"], [0, 1, 2]));
  q.push(ms("easy", "$\\sin30°$:", ["$=\\dfrac12$", "from the 30-60-90 triangle", "is exact", "$=\\dfrac{\\sqrt3}2$"], [0, 1, 2]));
  q.push(ms("easy", "The hypotenuse:", ["is the longest side", "is opposite the right angle", "is in the denominator of sin/cos", "is the shortest"], [0, 1, 2]));
  q.push(tf("easy", "$\\sin\\theta=\\dfrac{\\text{opp}}{\\text{hyp}}$.", true));
  q.push(tf("easy", "$\\tan45°=0$.", false));
  q.push(tf("easy", "$\\cos60°=\\dfrac12$.", true));
  q.push(fill("easy", "$\\sin30°$ (decimal).", ["0.5", "1/2"]));
  q.push(fill("easy", "$\\tan45°$.", ["1"]));
  q.push(fill("easy", "$\\cos0°$.", ["1"]));
  q.push(num("easy", "$\\tan45°$.", 1, 0));
  q.push(num("easy", "$\\sin90°$.", 1, 0));
  q.push(num("easy", "$\\cos90°$.", 0, 0));
  q.push(match("easy", "Match each special value.", ["$\\sin30°$", "$\\cos60°$", "$\\tan45°$"], ["$\\dfrac12$", "$\\dfrac12$", "$1$"], [0, 1, 2]));
  q.push(mc("medium", "$\\sin45°=$", ["$\\dfrac{\\sqrt2}2$", "$\\dfrac12$", "$\\dfrac{\\sqrt3}2$", "$1$"], 0));
  q.push(mc("medium", "$\\cos30°=$", ["$\\dfrac{\\sqrt3}2$", "$\\dfrac12$", "$\\dfrac{\\sqrt2}2$", "$1$"], 0));
  q.push(mc("medium", "$\\tan60°=$", ["$\\sqrt3$", "$1$", "$\\dfrac1{\\sqrt3}$", "$\\dfrac{\\sqrt3}2$"], 0));
  q.push(mc("medium", "opp $=3$, hyp $=5$. $\\sin\\theta=$", ["$\\dfrac35$", "$\\dfrac45$", "$\\dfrac34$", "$\\dfrac53$"], 0));
  q.push(mc("medium", "opp $=3$, adj $=4$. $\\tan\\theta=$", ["$\\dfrac34$", "$\\dfrac43$", "$\\dfrac35$", "$\\dfrac45$"], 0));
  q.push(mc("medium", "If $\\sin\\theta=\\dfrac12$, then $\\theta=$", ["$30°$", "$45°$", "$60°$", "$90°$"], 0));
  q.push(ms("medium", "The 45-45-90 triangle:", ["legs are equal", "$\\sin45°=\\cos45°$", "$=\\dfrac{\\sqrt2}2$", "$\\tan45°=\\sqrt3$"], [0, 1, 2]));
  q.push(ms("medium", "The 30-60-90 triangle:", ["sides $1,\\sqrt3,2$", "$\\sin30°=\\dfrac12$", "$\\cos30°=\\dfrac{\\sqrt3}2$", "all sides equal"], [0, 1, 2]));
  q.push(ms("medium", "Finding $\\sin\\theta$ with opp 3, hyp 5:", ["$=\\dfrac35$", "opp over hyp", "$=0.6$", "$=\\dfrac45$"], [0, 1, 2]));
  q.push(ms("medium", "Inverse trig:", ["$\\theta=\\sin^{-1}(\\dots)$", "finds the angle", "$\\sin^{-1}(0.5)=30°$", "is the reciprocal"], [0, 1, 2]));
  q.push(tf("medium", "$\\sin45°=\\dfrac{\\sqrt2}2$.", true));
  q.push(tf("medium", "$\\tan60°=\\sqrt3$.", true));
  q.push(tf("medium", "$\\cos30°=\\dfrac12$.", false));
  q.push(fill("medium", "$\\cos30°$ (exact).", ["√3/2", "\\dfrac{\\sqrt3}2"]));
  q.push(fill("medium", "$\\tan60°$.", ["√3", "\\sqrt3"]));
  q.push(fill("medium", "$\\sin\\theta$ if opp $=6$, hyp $=10$.", ["3/5", "0.6"]));
  q.push(num("medium", "$\\sin\\theta$ (decimal) for opp $=3$, hyp $=5$.", 0.6, 0.01));
  q.push(num("medium", "$\\theta$ in degrees if $\\tan\\theta=1$.", 45, 0));
  q.push(num("medium", "$\\theta$ in degrees if $\\sin\\theta=1$.", 90, 0));
  q.push(match("medium", "Match each value.", ["$\\sin45°$", "$\\cos30°$", "$\\tan60°$"], ["$\\dfrac{\\sqrt2}2$", "$\\dfrac{\\sqrt3}2$", "$\\sqrt3$"], [0, 1, 2]));
  q.push(mc("hard", "adj $=5$, angle $=60°$. Find opp.", ["$5\\sqrt3$", "$5$", "$\\dfrac5{\\sqrt3}$", "$10$"], 0));
  q.push(mc("hard", "hyp $=10$, angle $=30°$. Find opp.", ["$5$", "$10\\sqrt3$", "$5\\sqrt3$", "$20$"], 0));
  q.push(mc("hard", "opp $=7$, adj $=7$. Find $\\theta$.", ["$45°$", "$30°$", "$60°$", "$90°$"], 0));
  q.push(mc("hard", "Exact value of $\\sin60°\\cos30°$.", ["$\\dfrac34$", "$\\dfrac12$", "$\\dfrac{\\sqrt3}4$", "$1$"], 0));
  q.push(mc("hard", "A 10 m ladder at $60°$ to the ground reaches height:", ["$5\\sqrt3$ m", "$5$ m", "$10\\sqrt3$ m", "$10$ m"], 0));
  q.push(ms("hard", "Finding opp with adj $=5$, $60°$:", ["$\\tan60°=\\dfrac{\\text{opp}}5$", "$\\text{opp}=5\\tan60°$", "$=5\\sqrt3$", "$=5$"], [0, 1, 2]));
  q.push(ms("hard", "Solving right triangles:", ["pick the right ratio", "use known + unknown sides", "use SOH CAH TOA", "ignore the angle"], [0, 1, 2]));
  q.push(ms("hard", "$\\sin60°\\cos30°$:", ["$\\dfrac{\\sqrt3}2\\cdot\\dfrac{\\sqrt3}2$", "$=\\dfrac34$", "an exact value", "$=\\dfrac12$"], [0, 1, 2]));
  q.push(ms("hard", "Word problems:", ["draw a diagram", "label the sides", "choose a ratio", "skip the diagram"], [0, 1, 2]));
  q.push(tf("hard", "With hyp $=10$ and angle $30°$, the opposite side is 5.", true));
  q.push(tf("hard", "$\\sin60°\\cos30°=\\dfrac34$.", true));
  q.push(tf("hard", "A 10 m ladder at $60°$ reaches 10 m up.", false));
  q.push(fill("hard", "Opp side if adj $=5$, angle $60°$ (exact).", ["5√3", "5\\sqrt3"]));
  q.push(fill("hard", "Value of $\\sin60°\\cos30°$.", ["3/4", "0.75"]));
  q.push(fill("hard", "$\\theta$ if opp $=$ adj.", ["45", "45°"]));
  q.push(num("hard", "Opp side if hyp $=10$, angle $30°$.", 5, 0));
  q.push(num("hard", "Height reached by a 10 m ladder at $30°$.", 5, 0));
  q.push(num("hard", "$\\theta$ in degrees if opp $=$ adj.", 45, 0));
  q.push(order("hard", "Order the steps to find the height a 10 m ladder reaches at $60°$.", ["Use $\\sin60°=\\dfrac{h}{10}$", "$h=10\\sin60°$", "$=10\\cdot\\dfrac{\\sqrt3}2$", "$=5\\sqrt3$"]));
  q.push(match("hard", "Match each to its value.", ["$\\sin60°\\cos30°$", "$\\sin30°$", "$\\tan45°$"], ["$\\dfrac34$", "$\\dfrac12$", "$1$"], [0, 1, 2]));
  return q;
}

// ── 4.2 Angles 0°–360° & the CAST Rule ───────────────────────
function g42() {
  const q = [];
  q.push(mc("easy", "The CAST rule shows where each ratio is:", ["positive", "negative", "zero", "undefined"], 0));
  q.push(mc("easy", "In quadrant I, which ratios are positive?", ["all", "only sin", "only cos", "only tan"], 0));
  q.push(mc("easy", "In quadrant II, the positive ratio is:", ["sin", "cos", "tan", "none"], 0));
  q.push(mc("easy", "In quadrant III, the positive ratio is:", ["tan", "sin", "cos", "all"], 0));
  q.push(mc("easy", "In quadrant IV, the positive ratio is:", ["cos", "sin", "tan", "all"], 0));
  q.push(mc("easy", "$90°$ lies along which axis direction?", ["positive $y$", "positive $x$", "negative $y$", "negative $x$"], 0));
  q.push(ms("easy", "CAST (from QIV counterclockwise):", ["C: cos positive (QIV)", "A: all positive (QI)", "S: sin positive (QII)", "T: tan positive (QIII)"], [0, 1, 2, 3]));
  q.push(ms("easy", "Quadrant I:", ["all ratios positive", "$0°$ to $90°$", "sin, cos, tan $>0$", "only sin positive"], [0, 1, 2]));
  q.push(ms("easy", "Reference angle:", ["acute angle to the $x$-axis", "helps find values", "always positive", "to the $y$-axis"], [0, 1, 2]));
  q.push(ms("easy", "Signs in QII:", ["sin positive", "cos negative", "tan negative", "all positive"], [0, 1, 2]));
  q.push(tf("easy", "In quadrant II, sine is positive.", true));
  q.push(tf("easy", "In quadrant III, cosine is positive.", false));
  q.push(tf("easy", "In quadrant IV, cosine is positive.", true));
  q.push(fill("easy", "Quadrant where ALL ratios are positive.", ["I", "1", "QI"]));
  q.push(fill("easy", "The only positive ratio in QII.", ["sin", "sine"]));
  q.push(fill("easy", "The only positive ratio in QIII.", ["tan", "tangent"]));
  q.push(num("easy", "Number of quadrants.", 4, 0));
  q.push(num("easy", "Degrees in one full rotation.", 360, 0));
  q.push(num("easy", "Reference angle for $150°$ (degrees).", 30, 0));
  q.push(match("easy", "Match each quadrant to its positive ratio(s).", ["QI", "QII", "QIV"], ["all", "sin", "cos"], [0, 1, 2]));
  q.push(mc("medium", "Reference angle for $210°$.", ["$30°$", "$60°$", "$210°$", "$150°$"], 0));
  q.push(mc("medium", "Reference angle for $135°$.", ["$45°$", "$35°$", "$135°$", "$55°$"], 0));
  q.push(mc("medium", "$\\sin150°=$", ["$\\dfrac12$", "$-\\dfrac12$", "$\\dfrac{\\sqrt3}2$", "$-\\dfrac{\\sqrt3}2$"], 0));
  q.push(mc("medium", "$\\cos120°=$", ["$-\\dfrac12$", "$\\dfrac12$", "$\\dfrac{\\sqrt3}2$", "$-\\dfrac{\\sqrt3}2$"], 0));
  q.push(mc("medium", "$\\tan225°=$", ["$1$", "$-1$", "$\\sqrt3$", "$0$"], 0));
  q.push(mc("medium", "In which quadrant is $300°$?", ["IV", "III", "II", "I"], 0));
  q.push(ms("medium", "Finding $\\sin150°$:", ["QII", "reference angle $30°$", "sin positive", "$=\\dfrac12$"], [0, 1, 2, 3]));
  q.push(ms("medium", "$\\cos120°$:", ["QII", "cos negative", "reference $60°$", "$=-\\dfrac12$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Reference angles:", ["$180°-\\theta$ in QII", "$\\theta-180°$ in QIII", "$360°-\\theta$ in QIV", "always $\\theta$"], [0, 1, 2]));
  q.push(ms("medium", "Quadrant of $300°$:", ["QIV", "between $270°$ and $360°$", "cos positive", "QI"], [0, 1, 2]));
  q.push(tf("medium", "The reference angle for $210°$ is $30°$.", true));
  q.push(tf("medium", "$\\cos120°=-\\dfrac12$.", true));
  q.push(tf("medium", "$\\sin150°=-\\dfrac12$.", false));
  q.push(fill("medium", "Reference angle for $210°$ (degrees).", ["30"]));
  q.push(fill("medium", "$\\sin150°$ (exact).", ["1/2", "0.5"]));
  q.push(fill("medium", "Quadrant of $300°$.", ["IV", "4", "QIV"]));
  q.push(num("medium", "Reference angle for $135°$.", 45, 0));
  q.push(num("medium", "Reference angle for $300°$.", 60, 0));
  q.push(num("medium", "Reference angle for $225°$.", 45, 0));
  q.push(match("medium", "Match each angle to its value.", ["$\\sin150°$", "$\\cos120°$", "$\\tan225°$"], ["$\\dfrac12$", "$-\\dfrac12$", "$1$"], [0, 1, 2]));
  q.push(mc("hard", "If $\\sin\\theta=\\dfrac12$ on $[0°,360°]$, $\\theta=$", ["$30°$ or $150°$", "$30°$ only", "$150°$ only", "$30°$ or $210°$"], 0));
  q.push(mc("hard", "If $\\cos\\theta=-\\dfrac12$, $\\theta=$", ["$120°$ or $240°$", "$60°$ or $120°$", "$120°$ only", "$240°$ only"], 0));
  q.push(mc("hard", "If $\\tan\\theta=1$ on $[0°,360°]$, $\\theta=$", ["$45°$ or $225°$", "$45°$ only", "$135°$ or $315°$", "$45°$ or $135°$"], 0));
  q.push(mc("hard", "$\\sin\\theta<0$ and $\\cos\\theta>0$: which quadrant?", ["IV", "III", "II", "I"], 0));
  q.push(mc("hard", "If $\\sin\\theta=-\\dfrac{\\sqrt3}2$, $\\theta=$", ["$240°$ or $300°$", "$60°$ or $120°$", "$240°$ only", "$120°$ or $240°$"], 0));
  q.push(ms("hard", "Solving $\\sin\\theta=\\dfrac12$ on $[0°,360°]$:", ["sin positive in QI, QII", "$\\theta=30°$", "$\\theta=150°$", "only one solution"], [0, 1, 2]));
  q.push(ms("hard", "$\\cos\\theta=-\\dfrac12$:", ["cos negative in QII, QIII", "$\\theta=120°$", "$\\theta=240°$", "reference angle $60°$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Determining a quadrant from signs:", ["use CAST", "$\\sin<0,\\cos>0$ → QIV", "check each ratio", "ignore signs"], [0, 1, 2]));
  q.push(ms("hard", "Two solutions arise because:", ["a ratio is positive in two quadrants", "of the period of sine/cosine", "we look over $360°$", "there is only one"], [0, 1, 2]));
  q.push(tf("hard", "$\\sin\\theta=\\dfrac12$ has two solutions in $[0°,360°]$.", true));
  q.push(tf("hard", "$\\sin\\theta<0$ and $\\cos\\theta>0$ means QIV.", true));
  q.push(tf("hard", "$\\cos\\theta=-\\dfrac12$ gives $\\theta=60°$.", false));
  q.push(fill("hard", "The two solutions of $\\sin\\theta=\\dfrac12$ in $[0°,360°]$.", ["30,150", "30°,150°"]));
  q.push(fill("hard", "The two solutions of $\\cos\\theta=-\\dfrac12$.", ["120,240", "120°,240°"]));
  q.push(fill("hard", "Quadrant with $\\sin<0,\\cos>0$.", ["IV", "4", "QIV"]));
  q.push(num("hard", "Smaller solution of $\\sin\\theta=\\dfrac12$ (degrees).", 30, 0));
  q.push(num("hard", "Larger solution of $\\sin\\theta=\\dfrac12$ (degrees).", 150, 0));
  q.push(num("hard", "Smaller solution of $\\tan\\theta=1$ (degrees).", 45, 0));
  q.push(order("hard", "Order the steps to solve $\\cos\\theta=-\\dfrac12$ on $[0°,360°]$.", ["Reference angle $60°$", "Cosine negative in QII and QIII", "$\\theta=180°-60°=120°$", "$\\theta=180°+60°=240°$"]));
  q.push(match("hard", "Match each equation to its solutions in $[0°,360°]$.", ["$\\sin\\theta=\\dfrac12$", "$\\cos\\theta=-\\dfrac12$", "$\\tan\\theta=1$"], ["$30°,150°$", "$120°,240°$", "$45°,225°$"], [0, 1, 2]));
  return q;
}

// ── 4.3 Reciprocal Ratios & Trigonometric Identities ─────────
function g43() {
  const q = [];
  q.push(mc("easy", "$\\csc\\theta=$", ["$\\dfrac1{\\sin\\theta}$", "$\\dfrac1{\\cos\\theta}$", "$\\dfrac1{\\tan\\theta}$", "$\\sin\\theta$"], 0));
  q.push(mc("easy", "$\\sec\\theta=$", ["$\\dfrac1{\\cos\\theta}$", "$\\dfrac1{\\sin\\theta}$", "$\\dfrac1{\\tan\\theta}$", "$\\cos\\theta$"], 0));
  q.push(mc("easy", "$\\cot\\theta=$", ["$\\dfrac1{\\tan\\theta}$", "$\\dfrac1{\\sin\\theta}$", "$\\dfrac1{\\cos\\theta}$", "$\\tan\\theta$"], 0));
  q.push(mc("easy", "$\\tan\\theta=$", ["$\\dfrac{\\sin\\theta}{\\cos\\theta}$", "$\\dfrac{\\cos\\theta}{\\sin\\theta}$", "$\\sin\\theta\\cos\\theta$", "$\\dfrac1{\\sin\\theta}$"], 0));
  q.push(mc("easy", "The Pythagorean identity:", ["$\\sin^2\\theta+\\cos^2\\theta=1$", "$\\sin\\theta+\\cos\\theta=1$", "$\\sin^2-\\cos^2=1$", "$\\tan^2=1$"], 0));
  q.push(mc("easy", "If $\\sin\\theta=\\dfrac12$, $\\csc\\theta=$", ["$2$", "$\\dfrac12$", "$1$", "$\\dfrac{\\sqrt3}2$"], 0));
  q.push(ms("easy", "Reciprocal ratios:", ["$\\csc=1/\\sin$", "$\\sec=1/\\cos$", "$\\cot=1/\\tan$", "$\\csc=1/\\cos$"], [0, 1, 2]));
  q.push(ms("easy", "Quotient identity:", ["$\\tan=\\dfrac{\\sin}{\\cos}$", "$\\cot=\\dfrac{\\cos}{\\sin}$", "relates the ratios", "$\\tan=\\sin\\cos$"], [0, 1, 2]));
  q.push(ms("easy", "Pythagorean identity:", ["$\\sin^2+\\cos^2=1$", "always true", "fundamental", "$\\sin+\\cos=1$"], [0, 1, 2]));
  q.push(ms("easy", "Using $\\sin\\theta=\\dfrac12$:", ["$\\csc\\theta=2$", "reciprocal", "flip the fraction", "$\\csc\\theta=\\dfrac12$"], [0, 1, 2]));
  q.push(tf("easy", "$\\csc\\theta=\\dfrac1{\\sin\\theta}$.", true));
  q.push(tf("easy", "$\\tan\\theta=\\dfrac{\\cos\\theta}{\\sin\\theta}$.", false));
  q.push(tf("easy", "$\\sin^2\\theta+\\cos^2\\theta=1$.", true));
  q.push(fill("easy", "$\\csc\\theta$ if $\\sin\\theta=\\dfrac13$.", ["3"]));
  q.push(fill("easy", "$\\sec\\theta$ if $\\cos\\theta=\\dfrac14$.", ["4"]));
  q.push(fill("easy", "The Pythagorean identity (right side).", ["1"]));
  q.push(num("easy", "$\\csc\\theta$ if $\\sin\\theta=0.5$.", 2, 0));
  q.push(num("easy", "$\\sec\\theta$ if $\\cos\\theta=0.2$.", 5, 0));
  q.push(num("easy", "$\\cot\\theta$ if $\\tan\\theta=4$.", 0.25, 0.01));
  q.push(match("easy", "Match each reciprocal.", ["$\\csc\\theta$", "$\\sec\\theta$", "$\\cot\\theta$"], ["$\\dfrac1{\\sin\\theta}$", "$\\dfrac1{\\cos\\theta}$", "$\\dfrac1{\\tan\\theta}$"], [0, 1, 2]));
  q.push(mc("medium", "If $\\cos\\theta=\\dfrac35$ (QI), $\\sin\\theta=$", ["$\\dfrac45$", "$\\dfrac35$", "$\\dfrac34$", "$\\dfrac53$"], 0));
  q.push(mc("medium", "If $\\sin\\theta=\\dfrac35$ (QI), $\\tan\\theta=$", ["$\\dfrac34$", "$\\dfrac43$", "$\\dfrac35$", "$\\dfrac45$"], 0));
  q.push(mc("medium", "Simplify $\\dfrac{\\sin\\theta}{\\cos\\theta}$.", ["$\\tan\\theta$", "$\\cot\\theta$", "$1$", "$\\sec\\theta$"], 0));
  q.push(mc("medium", "Simplify $\\sin^2\\theta+\\cos^2\\theta$.", ["$1$", "$0$", "$2$", "$\\tan\\theta$"], 0));
  q.push(mc("medium", "$1-\\cos^2\\theta=$", ["$\\sin^2\\theta$", "$\\cos^2\\theta$", "$1$", "$\\tan^2\\theta$"], 0));
  q.push(mc("medium", "$\\sin\\theta\\csc\\theta=$", ["$1$", "$\\sin^2\\theta$", "$0$", "$\\tan\\theta$"], 0));
  q.push(ms("medium", "From $\\cos\\theta=\\dfrac35$ in QI:", ["use $\\sin^2+\\cos^2=1$", "$\\sin^2=1-\\dfrac9{25}$", "$\\sin=\\dfrac45$", "$\\sin=\\dfrac35$"], [0, 1, 2]));
  q.push(ms("medium", "Simplifying with identities:", ["$\\dfrac{\\sin}{\\cos}=\\tan$", "$\\sin^2+\\cos^2=1$", "$1-\\cos^2=\\sin^2$", "$\\sin+\\cos=1$"], [0, 1, 2]));
  q.push(ms("medium", "Reciprocal products:", ["$\\sin\\csc=1$", "$\\cos\\sec=1$", "$\\tan\\cot=1$", "$\\sin\\sec=1$"], [0, 1, 2]));
  q.push(ms("medium", "Proving identities:", ["work one side", "use known identities", "simplify to the other side", "change the equation"], [0, 1, 2]));
  q.push(tf("medium", "If $\\cos\\theta=\\dfrac35$ in QI then $\\sin\\theta=\\dfrac45$.", true));
  q.push(tf("medium", "$1-\\cos^2\\theta=\\sin^2\\theta$.", true));
  q.push(tf("medium", "$\\sin\\theta\\csc\\theta=0$.", false));
  q.push(fill("medium", "$\\sin\\theta$ if $\\cos\\theta=\\dfrac35$ (QI).", ["4/5", "0.8"]));
  q.push(fill("medium", "Simplify $\\dfrac{\\sin\\theta}{\\cos\\theta}$.", ["tan θ", "tanθ", "\\tan\\theta"]));
  q.push(fill("medium", "Simplify $1-\\cos^2\\theta$.", ["sin^2 θ", "\\sin^2\\theta", "sin²θ"]));
  q.push(num("medium", "$\\sin\\theta$ (decimal) if $\\cos\\theta=0.6$ (QI).", 0.8, 0.01));
  q.push(num("medium", "$\\tan\\theta$ if $\\sin\\theta=0.6,\\cos\\theta=0.8$.", 0.75, 0.01));
  q.push(num("medium", "Value of $\\sin\\theta\\csc\\theta$.", 1, 0));
  q.push(match("medium", "Match each to its simplification.", ["$\\dfrac{\\sin\\theta}{\\cos\\theta}$", "$\\sin^2\\theta+\\cos^2\\theta$", "$\\sin\\theta\\csc\\theta$"], ["$\\tan\\theta$", "$1$", "$1$"], [0, 1, 2]));
  q.push(mc("hard", "Simplify $\\dfrac{1-\\cos^2\\theta}{\\sin\\theta}$.", ["$\\sin\\theta$", "$\\cos\\theta$", "$\\tan\\theta$", "$1$"], 0));
  q.push(mc("hard", "Simplify $\\tan\\theta\\cos\\theta$.", ["$\\sin\\theta$", "$\\cos\\theta$", "$1$", "$\\sec\\theta$"], 0));
  q.push(mc("hard", "Simplify $\\dfrac{\\cos\\theta}{\\cot\\theta}$.", ["$\\sin\\theta$", "$\\cos\\theta$", "$\\tan\\theta$", "$1$"], 0));
  q.push(mc("hard", "If $\\tan\\theta=\\dfrac34$ (QI), $\\sin\\theta=$", ["$\\dfrac35$", "$\\dfrac45$", "$\\dfrac34$", "$\\dfrac53$"], 0));
  q.push(mc("hard", "Simplify $\\sec^2\\theta-\\tan^2\\theta$.", ["$1$", "$0$", "$\\sin^2\\theta$", "$\\sec\\theta$"], 0));
  q.push(ms("hard", "Simplifying $\\dfrac{1-\\cos^2\\theta}{\\sin\\theta}$:", ["$1-\\cos^2=\\sin^2$", "$\\dfrac{\\sin^2}{\\sin}$", "$=\\sin\\theta$", "$=\\cos\\theta$"], [0, 1, 2]));
  q.push(ms("hard", "$\\tan\\theta\\cos\\theta$:", ["$\\dfrac{\\sin}{\\cos}\\cdot\\cos$", "$=\\sin\\theta$", "cos cancels", "$=1$"], [0, 1, 2]));
  q.push(ms("hard", "From $\\tan\\theta=\\dfrac34$ (QI):", ["a 3-4-5 triangle", "$\\sin=\\dfrac35$", "$\\cos=\\dfrac45$", "$\\sin=\\dfrac45$"], [0, 1, 2]));
  q.push(ms("hard", "$\\sec^2-\\tan^2$:", ["$=1$", "a Pythagorean identity", "from $\\sin^2+\\cos^2=1$", "$=0$"], [0, 1, 2]));
  q.push(tf("hard", "$\\dfrac{1-\\cos^2\\theta}{\\sin\\theta}=\\sin\\theta$.", true));
  q.push(tf("hard", "$\\sec^2\\theta-\\tan^2\\theta=1$.", true));
  q.push(tf("hard", "$\\tan\\theta\\cos\\theta=\\cos\\theta$.", false));
  q.push(fill("hard", "Simplify $\\tan\\theta\\cos\\theta$.", ["sin θ", "\\sin\\theta", "sinθ"]));
  q.push(fill("hard", "Simplify $\\sec^2\\theta-\\tan^2\\theta$.", ["1"]));
  q.push(fill("hard", "$\\sin\\theta$ if $\\tan\\theta=\\dfrac34$ (QI).", ["3/5", "0.6"]));
  q.push(num("hard", "Value of $\\sec^2\\theta-\\tan^2\\theta$.", 1, 0));
  q.push(num("hard", "$\\sin\\theta$ (decimal) if $\\tan\\theta=0.75$ (QI).", 0.6, 0.01));
  q.push(num("hard", "$\\dfrac{1-\\cos^2\\theta}{\\sin\\theta}$ if $\\sin\\theta=0.5$.", 0.5, 0.01));
  q.push(order("hard", "Order the steps to simplify $\\dfrac{1-\\cos^2\\theta}{\\sin\\theta}$.", ["Use $1-\\cos^2\\theta=\\sin^2\\theta$", "Rewrite as $\\dfrac{\\sin^2\\theta}{\\sin\\theta}$", "Cancel one $\\sin\\theta$", "$=\\sin\\theta$"]));
  q.push(match("hard", "Match each to its simplification.", ["$\\tan\\theta\\cos\\theta$", "$\\sec^2\\theta-\\tan^2\\theta$", "$\\dfrac{\\cos\\theta}{\\cot\\theta}$"], ["$\\sin\\theta$", "$1$", "$\\sin\\theta$"], [0, 1, 2]));
  return q;
}

// ── 4.4 The Sine Law & Cosine Law ────────────────────────────
function g44() {
  const q = [];
  q.push(mc("easy", "The sine law:", ["$\\dfrac{a}{\\sin A}=\\dfrac{b}{\\sin B}$", "$a^2=b^2+c^2$", "$a=b+c$", "$\\sin A=\\dfrac ab$"], 0));
  q.push(mc("easy", "The cosine law:", ["$c^2=a^2+b^2-2ab\\cos C$", "$c=a+b$", "$\\dfrac{a}{\\sin A}=\\dfrac{b}{\\sin B}$", "$c^2=a^2+b^2$"], 0));
  q.push(mc("easy", "Use the cosine law when you know:", ["two sides and the included angle", "three angles", "one side only", "nothing"], 0));
  q.push(mc("easy", "Use the sine law when you know:", ["an angle and its opposite side", "three sides only", "two sides and the included angle", "nothing"], 0));
  q.push(mc("easy", "In any triangle, the angles sum to:", ["$180°$", "$360°$", "$90°$", "$270°$"], 0));
  q.push(mc("easy", "The largest angle is opposite the:", ["longest side", "shortest side", "hypotenuse", "smallest angle"], 0));
  q.push(ms("easy", "Sine law:", ["$\\dfrac a{\\sin A}=\\dfrac b{\\sin B}=\\dfrac c{\\sin C}$", "relates sides & opposite angles", "needs a matched pair", "$a^2+b^2=c^2$"], [0, 1, 2]));
  q.push(ms("easy", "Cosine law:", ["$c^2=a^2+b^2-2ab\\cos C$", "generalizes Pythagoras", "for SAS or SSS", "only right triangles"], [0, 1, 2]));
  q.push(ms("easy", "Choosing a law:", ["SAS → cosine law", "SSS → cosine law", "matched pair → sine law", "always sine law"], [0, 1, 2]));
  q.push(ms("easy", "Angle sum:", ["$A+B+C=180°$", "find the third angle", "useful in the sine law", "$=360°$"], [0, 1, 2]));
  q.push(tf("easy", "The cosine law generalizes the Pythagorean theorem.", true));
  q.push(tf("easy", "The sine law needs three sides and no angles.", false));
  q.push(tf("easy", "Triangle angles sum to $180°$.", true));
  q.push(fill("easy", "Third angle if two are $50°$ and $60°$.", ["70", "70°"]));
  q.push(fill("easy", "Law for SSS (three sides).", ["cosine", "cosine law"]));
  q.push(fill("easy", "Law for a known angle-side pair plus another angle.", ["sine", "sine law"]));
  q.push(num("easy", "Third angle (degrees) if two are $40°$, $75°$.", 65, 0));
  q.push(num("easy", "Sum of triangle angles (degrees).", 180, 0));
  q.push(num("easy", "Third angle if two are $90°$, $30°$.", 60, 0));
  q.push(match("easy", "Match each case to a law.", ["SAS", "SSS", "matched pair"], ["cosine law", "cosine law", "sine law"], [0, 1, 2]));
  q.push(mc("medium", "$A=40°$, $a=10$, $B=60°$. Sine-law setup for $b$:", ["$\\dfrac{b}{\\sin60°}=\\dfrac{10}{\\sin40°}$", "$b=10+60$", "$b^2=10^2$", "$\\dfrac{b}{10}=40$"], 0));
  q.push(mc("medium", "Cosine law for $c$ with $a=5,b=7,C=60°$:", ["$c^2=25+49-70\\cos60°$", "$c=5+7$", "$c^2=25+49$", "$c=\\sqrt{12}$"], 0));
  q.push(mc("medium", "With $\\cos60°=\\dfrac12$, $c^2=25+49-2(5)(7)\\cos60°=$", ["$39$", "$74$", "$109$", "$35$"], 0));
  q.push(mc("medium", "To find an angle given three sides, use:", ["the cosine law", "the sine law only", "Pythagoras", "the angle sum only"], 0));
  q.push(mc("medium", "If $a=8,b=6,C=90°$, then $c=$", ["$10$", "$14$", "$2$", "$\\sqrt{28}$"], 0));
  q.push(mc("medium", "The ambiguous case can occur with:", ["the sine law", "the cosine law", "SSS", "SAS"], 0));
  q.push(ms("medium", "Setting up the sine law:", ["match each side with its opposite angle", "$\\dfrac{a}{\\sin A}=\\dfrac{b}{\\sin B}$", "cross-multiply", "add the sides"], [0, 1, 2]));
  q.push(ms("medium", "Cosine law with $a=5,b=7,C=60°$:", ["$c^2=25+49-2(5)(7)(0.5)$", "$=39$", "$c=\\sqrt{39}$", "$c=12$"], [0, 1, 2]));
  q.push(ms("medium", "Finding an angle (SSS):", ["rearrange the cosine law", "$\\cos C=\\dfrac{a^2+b^2-c^2}{2ab}$", "use $\\cos^{-1}$", "use the sine law first"], [0, 1, 2]));
  q.push(ms("medium", "Angle sum helps:", ["find a third angle", "then apply the sine law", "$A+B+C=180°$", "replace the cosine law"], [0, 1, 2]));
  q.push(tf("medium", "With $a=5,b=7,C=60°$, $c^2=39$.", true));
  q.push(tf("medium", "To find an angle from three sides, use the cosine law.", true));
  q.push(tf("medium", "The cosine law has an ambiguous case.", false));
  q.push(fill("medium", "$c^2$ if $a=5,b=7,C=60°$.", ["39"]));
  q.push(fill("medium", "$c$ if $a=8,b=6,C=90°$.", ["10"]));
  q.push(fill("medium", "Law to find an angle from three sides.", ["cosine", "cosine law"]));
  q.push(num("medium", "$c^2$ for $a=5,b=7,C=60°$.", 39, 0));
  q.push(num("medium", "$c$ for $a=8,b=6,C=90°$.", 10, 0));
  q.push(num("medium", "Third angle (degrees) if $A=40°,B=60°$.", 80, 0));
  q.push(match("medium", "Match each case to a law.", ["find a side, matched pair", "find a side, SAS", "find an angle, SSS"], ["sine law", "cosine law", "cosine law"], [0, 1, 2]));
  q.push(mc("hard", "$a=5,b=7,C=60°$. $c\\approx$", ["$6.24$", "$12$", "$8.6$", "$5$"], 0));
  q.push(mc("hard", "Sides $a=6,b=8,c=10$. The largest angle is opposite:", ["$c$", "$a$", "$b$", "none"], 0));
  q.push(mc("hard", "For $a=6,b=8,c=10$, $\\cos C=\\dfrac{36+64-100}{2(6)(8)}=$", ["$0$", "$1$", "$-1$", "$0.5$"], 0));
  q.push(mc("hard", "Triangle $A=30°,a=5,b=8$: number of triangles (ambiguous case).", ["2", "1", "0", "3"], 0));
  q.push(mc("hard", "$a=10,A=90°,B=30°$. Then $b=$", ["$5$", "$10$", "$\\dfrac{10}{\\sqrt3}$", "$20$"], 0));
  q.push(ms("hard", "Computing $c$ for $a=5,b=7,C=60°$:", ["$c^2=39$", "$c=\\sqrt{39}$", "$\\approx6.24$", "$c=12$"], [0, 1, 2]));
  q.push(ms("hard", "For $a=6,b=8,c=10$:", ["$\\cos C=0$", "$C=90°$", "a right triangle", "$C=60°$"], [0, 1, 2]));
  q.push(ms("hard", "The ambiguous (SSA) case:", ["uses the sine law", "can give 0, 1, or 2 triangles", "compare $a$ with $b\\sin A$", "never happens"], [0, 1, 2]));
  q.push(ms("hard", "Solving fully:", ["find all sides and angles", "use both laws as needed", "angles sum to $180°$", "stop after one side"], [0, 1, 2]));
  q.push(tf("hard", "For $a=5,b=7,C=60°$, $c\\approx6.24$.", true));
  q.push(tf("hard", "A triangle with sides $6,8,10$ is right-angled.", true));
  q.push(tf("hard", "The cosine law gives the ambiguous case.", false));
  q.push(fill("hard", "$c$ (to 2 dp) for $a=5,b=7,C=60°$.", ["6.24"]));
  q.push(fill("hard", "The angle $C$ for sides $6,8,10$ (degrees).", ["90", "90°"]));
  q.push(fill("hard", "$b$ if $a=10,A=90°,B=30°$.", ["5"]));
  q.push(num("hard", "$c$ (2 dp) for $a=5,b=7,C=60°$.", 6.24, 0.05));
  q.push(num("hard", "$\\cos C$ for sides $6,8,10$.", 0, 0.001));
  q.push(num("hard", "Number of triangles for $A=30°,a=5,b=8$.", 2, 0));
  q.push(order("hard", "Order the steps to find $c$ for $a=5,b=7,C=60°$.", ["Write $c^2=a^2+b^2-2ab\\cos C$", "Substitute: $25+49-70(0.5)$", "$c^2=39$", "$c\\approx6.24$"]));
  q.push(match("hard", "Match each to its result.", ["$c$ for $a=5,b=7,C=60°$", "$C$ for sides $6,8,10$", "$b$ for $a=10,A=90°,B=30°$"], ["$\\approx6.24$", "$90°$", "$5$"], [0, 1, 2]));
  return q;
}

// ── 4.5 Trigonometry in 3-D Problems ─────────────────────────
function g45() {
  const q = [];
  q.push(mc("easy", "To solve a 3-D problem, first:", ["identify right triangles", "guess", "ignore the diagram", "use only the sine law"], 0));
  q.push(mc("easy", "An angle of elevation is measured from:", ["the horizontal, looking up", "the vertical", "straight down", "the ground only"], 0));
  q.push(mc("easy", "An angle of depression is measured:", ["from the horizontal, looking down", "straight up", "from the vertical", "along the ground"], 0));
  q.push(mc("easy", "A vertical pole makes what angle with level ground?", ["$90°$", "$45°$", "$60°$", "$30°$"], 0));
  q.push(mc("easy", "In 3-D, we often break the figure into:", ["2-D right triangles", "circles", "squares", "nothing"], 0));
  q.push(mc("easy", "Pythagoras for a box's diagonal uses:", ["all three dimensions", "two only", "one only", "none"], 0));
  q.push(ms("easy", "Strategy for 3-D:", ["find right triangles", "work plane by plane", "label everything", "do it all at once"], [0, 1, 2]));
  q.push(ms("easy", "Elevation/depression:", ["measured from the horizontal", "elevation looks up", "depression looks down", "from the vertical"], [0, 1, 2]));
  q.push(ms("easy", "Tools:", ["SOH CAH TOA", "Pythagoras", "the sine/cosine law", "none"], [0, 1, 2]));
  q.push(ms("easy", "Common 3-D setups:", ["a pole and two observers", "a box diagonal", "a pyramid", "a circle only"], [0, 1, 2]));
  q.push(tf("easy", "Angle of elevation is measured up from the horizontal.", true));
  q.push(tf("easy", "3-D problems can't use 2-D triangles.", false));
  q.push(tf("easy", "A vertical pole meets level ground at $90°$.", true));
  q.push(fill("easy", "Angle a vertical pole makes with the ground (degrees).", ["90", "90°"]));
  q.push(fill("easy", "Shapes we reduce 3-D problems to.", ["right triangles", "triangles"]));
  q.push(fill("easy", "Angle measured downward from the horizontal.", ["depression", "angle of depression"]));
  q.push(num("easy", "Angle (degrees) between a vertical wall and the floor.", 90, 0));
  q.push(num("easy", "Number of dimensions in a box-diagonal calculation.", 3, 0));
  q.push(num("easy", "Non-right angles' sum in a right triangle (degrees).", 90, 0));
  q.push(match("easy", "Match each term.", ["elevation", "depression", "vertical pole to ground"], ["look up", "look down", "$90°$"], [0, 1, 2]));
  q.push(mc("medium", "A 10 m pole; angle of elevation $45°$. Distance to base:", ["$10$ m", "$5$ m", "$10\\sqrt2$ m", "$20$ m"], 0));
  q.push(mc("medium", "From 20 m away, a tower's top has elevation $30°$. Height:", ["$20\\tan30°$", "$20\\sin30°$", "$20\\cos30°$", "$\\dfrac{20}{\\tan30°}$"], 0));
  q.push(mc("medium", "A box $3\\times4\\times12$: the base diagonal is:", ["$5$", "$7$", "$12$", "$13$"], 0));
  q.push(mc("medium", "The angle of depression from a cliff equals:", ["the angle of elevation to the cliff", "its complement", "$90°$", "zero"], 0));
  q.push(mc("medium", "To find a slant height in a pyramid, use:", ["a right triangle", "the sine law only", "a circle", "nothing"], 0));
  q.push(mc("medium", "From 30 m, elevation $60°$: height $=30\\tan60°=$", ["$30\\sqrt3$", "$30$", "$15\\sqrt3$", "$60$"], 0));
  q.push(ms("medium", "Pole with $45°$ elevation:", ["$\\tan45°=\\dfrac{10}{d}$", "$d=10$", "a right triangle", "$d=5$"], [0, 1, 2]));
  q.push(ms("medium", "Box diagonals:", ["base diagonal first", "then the space diagonal", "two Pythagoras steps", "one step"], [0, 1, 2]));
  q.push(ms("medium", "Elevation vs depression:", ["alternate angles are equal", "depression = elevation across", "parallel horizontals", "they differ"], [0, 1, 2]));
  q.push(ms("medium", "Setting up:", ["draw the 2-D triangle", "label opp/adj/hyp", "pick a ratio", "skip labels"], [0, 1, 2]));
  q.push(tf("medium", "For a 10 m pole with $45°$ elevation, the base is 10 m away.", true));
  q.push(tf("medium", "A $3\\times4$ base has diagonal 5.", true));
  q.push(tf("medium", "The angle of depression is always $90°$.", false));
  q.push(fill("medium", "Distance to a 10 m pole at $45°$ elevation.", ["10", "10 m"]));
  q.push(fill("medium", "Base diagonal of a $3\\times4$ rectangle.", ["5"]));
  q.push(fill("medium", "Height $=20\\tan30°$ for a tower 20 m away, $30°$ elevation (form).", ["20tan30", "20\\tan30°"]));
  q.push(num("medium", "Distance to base of a 10 m pole at $45°$ elevation.", 10, 0));
  q.push(num("medium", "Diagonal of a $3\\times4$ rectangle.", 5, 0));
  q.push(num("medium", "Height (decimal) of a tower from 30 m at $45°$ elevation.", 30, 0));
  q.push(match("medium", "Match each to its value.", ["$45°$ elevation, 10 m pole: distance", "$3\\times4$ base diagonal", "wall-to-floor angle"], ["$10$", "$5$", "$90°$"], [0, 1, 2]));
  q.push(mc("hard", "A box $3\\times4\\times12$: the space (longest) diagonal is:", ["$13$", "$12$", "$5$", "$19$"], 0));
  q.push(mc("hard", "Two observers 100 m apart see a balloon between them at $45°$ each. Balloon height:", ["$50$ m", "$100$ m", "$50\\sqrt2$ m", "$25$ m"], 0));
  q.push(mc("hard", "From a 50 m tower, depression to a car is $30°$. Distance from base:", ["$50\\sqrt3$ m", "$50$ m", "$\\dfrac{50}{\\sqrt3}$ m", "$25$ m"], 0));
  q.push(mc("hard", "A pyramid: base $6\\times6$, height 4. Slant height to a base-edge midpoint:", ["$5$", "$4$", "$6$", "$\\sqrt{52}$"], 0));
  q.push(mc("hard", "The space diagonal of a cube with side 2:", ["$2\\sqrt3$", "$2$", "$2\\sqrt2$", "$6$"], 0));
  q.push(ms("hard", "Space diagonal of a box:", ["base diagonal $=\\sqrt{a^2+b^2}$", "then $\\sqrt{(\\text{base})^2+c^2}$", "for $3,4,12$ gives $13$", "just $c$"], [0, 1, 2]));
  q.push(ms("hard", "Tower depression problem:", ["depression = elevation", "$\\tan30°=\\dfrac{50}{d}$", "$d=50\\sqrt3$", "$d=50$"], [0, 1, 2]));
  q.push(ms("hard", "Pyramid slant height:", ["right triangle: height & half-base", "$\\sqrt{4^2+3^2}=5$", "find the right triangle", "use a circle"], [0, 1, 2]));
  q.push(ms("hard", "Multi-step 3-D:", ["one triangle at a time", "carry exact values", "combine the results", "one big formula"], [0, 1, 2]));
  q.push(tf("hard", "The space diagonal of a $3\\times4\\times12$ box is 13.", true));
  q.push(tf("hard", "The space diagonal of a cube of side 2 is $2\\sqrt3$.", true));
  q.push(tf("hard", "A $6\\times6$ base, height-4 pyramid has slant height 4.", false));
  q.push(fill("hard", "Space diagonal of a $3\\times4\\times12$ box.", ["13"]));
  q.push(fill("hard", "Distance from base for a 50 m tower, $30°$ depression (exact).", ["50√3", "50\\sqrt3"]));
  q.push(fill("hard", "Slant height of a $6\\times6$ base, height-4 pyramid.", ["5"]));
  q.push(num("hard", "Space diagonal of a $3\\times4\\times12$ box.", 13, 0));
  q.push(num("hard", "Space diagonal of a cube of side 2 (decimal).", 3.46, 0.05));
  q.push(num("hard", "Slant height of a $6\\times6$ base, height-4 pyramid.", 5, 0));
  q.push(order("hard", "Order the steps to find the space diagonal of a $3\\times4\\times12$ box.", ["Base diagonal $=\\sqrt{3^2+4^2}=5$", "Space diagonal $=\\sqrt{5^2+12^2}$", "$=\\sqrt{169}$", "$=13$"]));
  q.push(match("hard", "Match each to its value.", ["$3\\times4\\times12$ space diagonal", "cube side 2 space diagonal", "$6\\times6$ base, h=4 slant height"], ["$13$", "$2\\sqrt3$", "$5$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "4.1", gen: g41 },
  { code: "4.2", gen: g42 },
  { code: "4.3", gen: g43 },
  { code: "4.4", gen: g44 },
  { code: "4.5", gen: g45 },
];
