// MCR3U Unit 5 — Sinusoidal Functions: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 5.1 Periodic Functions & Their Properties ────────────────
function g51() {
  const q = [];
  q.push(mc("easy", "A periodic function:", ["repeats at regular intervals", "never repeats", "is linear", "is constant"], 0));
  q.push(mc("easy", "The period is:", ["the length of one cycle", "the height", "the midline", "the maximum"], 0));
  q.push(mc("easy", "The amplitude is:", ["half the distance between max and min", "the period", "the midline", "the maximum"], 0));
  q.push(mc("easy", "Midline of a function with max 5, min 1:", ["$y=3$", "$y=2$", "$y=5$", "$y=1$"], 0));
  q.push(mc("easy", "Period of $\\sin x$ (degrees):", ["$360°$", "$180°$", "$90°$", "$720°$"], 0));
  q.push(mc("easy", "Maximum of $\\sin x$:", ["$1$", "$0$", "$-1$", "$360$"], 0));
  q.push(ms("easy", "Key features:", ["amplitude", "period", "midline", "slope"], [0, 1, 2]));
  q.push(ms("easy", "Amplitude:", ["$\\dfrac{\\max-\\min}2$", "half the range", "always positive", "$\\max-\\min$"], [0, 1, 2]));
  q.push(ms("easy", "Period:", ["one full cycle", "repeats after it", "$\\sin x$: $360°$", "the height"], [0, 1, 2]));
  q.push(ms("easy", "Midline:", ["$y=\\dfrac{\\max+\\min}2$", "the centre line", "halfway between max and min", "the top"], [0, 1, 2]));
  q.push(tf("easy", "The period is the length of one cycle.", true));
  q.push(tf("easy", "Amplitude is the distance from max to min.", false));
  q.push(tf("easy", "$\\sin x$ has period $360°$.", true));
  q.push(fill("easy", "Amplitude if max $=7$, min $=1$.", ["3"]));
  q.push(fill("easy", "Midline if max $=7$, min $=1$.", ["y=4", "4"]));
  q.push(fill("easy", "Period of $\\cos x$ in degrees.", ["360", "360°"]));
  q.push(num("easy", "Amplitude if max $=10$, min $=2$.", 4, 0));
  q.push(num("easy", "Midline value if max $=10$, min $=2$.", 6, 0));
  q.push(num("easy", "Period of $\\sin x$ in degrees.", 360, 0));
  q.push(match("easy", "Match each term.", ["amplitude", "period", "midline"], ["half (max−min)", "one cycle length", "centre line"], [0, 1, 2]));
  q.push(mc("medium", "$y=3\\sin x$: amplitude.", ["$3$", "$1$", "$6$", "$\\dfrac13$"], 0));
  q.push(mc("medium", "$y=\\sin x+2$: midline.", ["$y=2$", "$y=0$", "$y=3$", "$y=1$"], 0));
  q.push(mc("medium", "Max of $y=2\\sin x+1$.", ["$3$", "$2$", "$1$", "$-1$"], 0));
  q.push(mc("medium", "Min of $y=2\\sin x+1$.", ["$-1$", "$1$", "$0$", "$3$"], 0));
  q.push(mc("medium", "Period of $y=\\sin(2x)$ (degrees).", ["$180°$", "$360°$", "$720°$", "$90°$"], 0));
  q.push(mc("medium", "Amplitude of $y=-4\\cos x$.", ["$4$", "$-4$", "$8$", "$1$"], 0));
  q.push(ms("medium", "For $y=2\\sin x+1$:", ["amplitude 2", "midline $y=1$", "max 3", "min -1"], [0, 1, 2, 3]));
  q.push(ms("medium", "Changing the period:", ["$y=\\sin(kx)$", "period $=\\dfrac{360°}{k}$", "$k=2$ → $180°$", "period unchanged"], [0, 1, 2]));
  q.push(ms("medium", "Amplitude is $|a|$:", ["always positive", "$y=-4\\cos x$ → 4", "reflection if $a<0$", "equals $a$ with sign"], [0, 1, 2]));
  q.push(ms("medium", "Vertical shift:", ["moves the midline", "$+c$ up", "$-c$ down", "changes amplitude"], [0, 1, 2]));
  q.push(tf("medium", "$y=3\\sin x$ has amplitude 3.", true));
  q.push(tf("medium", "$y=\\sin(2x)$ has period $180°$.", true));
  q.push(tf("medium", "$y=-4\\cos x$ has amplitude $-4$.", false));
  q.push(fill("medium", "Amplitude of $y=5\\sin x$.", ["5"]));
  q.push(fill("medium", "Period of $y=\\sin(3x)$ in degrees.", ["120", "120°"]));
  q.push(fill("medium", "Midline of $y=\\cos x-3$.", ["y=-3", "-3"]));
  q.push(num("medium", "Max of $y=2\\sin x+1$.", 3, 0));
  q.push(num("medium", "Period of $y=\\sin(2x)$ in degrees.", 180, 0));
  q.push(num("medium", "Amplitude of $y=-4\\cos x$.", 4, 0));
  q.push(match("medium", "Match each to its amplitude.", ["$3\\sin x$", "$-4\\cos x$", "$\\tfrac12\\sin x$"], ["$3$", "$4$", "$\\tfrac12$"], [0, 1, 2]));
  q.push(mc("hard", "$y=3\\sin(2x)+1$: amplitude, period, midline.", ["$3$, $180°$, $y=1$", "$3$, $360°$, $y=1$", "$2$, $180°$, $y=3$", "$3$, $90°$, $y=1$"], 0));
  q.push(mc("hard", "Max of $y=3\\sin(2x)+1$.", ["$4$", "$3$", "$2$", "$1$"], 0));
  q.push(mc("hard", "Min of $y=3\\sin(2x)+1$.", ["$-2$", "$1$", "$-1$", "$-4$"], 0));
  q.push(mc("hard", "A function with max 9, min 3: amplitude and midline.", ["$3$, $y=6$", "$6$, $y=6$", "$3$, $y=3$", "$6$, $y=3$"], 0));
  q.push(mc("hard", "$y=\\sin(kx)$ has period $90°$. Then $k=$", ["$4$", "$2$", "$90$", "$\\dfrac14$"], 0));
  q.push(ms("hard", "For $y=3\\sin(2x)+1$:", ["amplitude 3", "period $180°$", "midline $y=1$", "max 4"], [0, 1, 2, 3]));
  q.push(ms("hard", "From max 9, min 3:", ["amplitude $=\\dfrac{9-3}2=3$", "midline $=\\dfrac{9+3}2=6$", "range 6", "amplitude 6"], [0, 1, 2]));
  q.push(ms("hard", "Period from $k$:", ["period $=\\dfrac{360°}{k}$", "$90°$ → $k=4$", "larger $k$, shorter period", "$k$ doesn't matter"], [0, 1, 2]));
  q.push(ms("hard", "Combining features:", ["max $=$ midline $+$ amplitude", "min $=$ midline $-$ amplitude", "both are needed", "ignore midline"], [0, 1, 2]));
  q.push(tf("hard", "$y=3\\sin(2x)+1$ has period $180°$.", true));
  q.push(tf("hard", "A function with max 9, min 3 has amplitude 3.", true));
  q.push(tf("hard", "$y=3\\sin(2x)+1$ has maximum 3.", false));
  q.push(fill("hard", "Period of $y=\\sin(4x)$ in degrees.", ["90", "90°"]));
  q.push(fill("hard", "Amplitude of a curve with max 9, min 3.", ["3"]));
  q.push(fill("hard", "Midline of a curve with max 9, min 3.", ["y=6", "6"]));
  q.push(num("hard", "Max of $y=3\\sin(2x)+1$.", 4, 0));
  q.push(num("hard", "Min of $y=3\\sin(2x)+1$.", -2, 0));
  q.push(num("hard", "$k$ if $y=\\sin(kx)$ has period $90°$.", 4, 0));
  q.push(order("hard", "Order the steps to find the max of $y=3\\sin(2x)+1$.", ["Amplitude $=3$", "Midline $=1$", "Max $=$ midline $+$ amplitude", "$=4$"]));
  q.push(match("hard", "Match each property of $y=3\\sin(2x)+1$.", ["amplitude", "period", "midline"], ["$3$", "$180°$", "$y=1$"], [0, 1, 2]));
  return q;
}

// ── 5.2 Graphing Sine & Cosine ───────────────────────────────
function g52() {
  const q = [];
  q.push(mc("easy", "$\\sin0°=$", ["$0$", "$1$", "$-1$", "$\\dfrac12$"], 0));
  q.push(mc("easy", "$\\cos0°=$", ["$1$", "$0$", "$-1$", "$\\dfrac12$"], 0));
  q.push(mc("easy", "$\\sin90°=$", ["$1$", "$0$", "$-1$", "$\\dfrac12$"], 0));
  q.push(mc("easy", "$\\cos90°=$", ["$0$", "$1$", "$-1$", "$\\dfrac12$"], 0));
  q.push(mc("easy", "$\\sin180°=$", ["$0$", "$1$", "$-1$", "$\\dfrac12$"], 0));
  q.push(mc("easy", "The graph of $y=\\sin x$ at $x=0$ is at:", ["$0$", "$1$", "$-1$", "the midline going down"], 0));
  q.push(ms("easy", "Sine key points ($0°,90°,180°,270°$):", ["$0,1,0,-1$", "starts at 0", "peak at $90°$", "starts at 1"], [0, 1, 2]));
  q.push(ms("easy", "Cosine key points:", ["$1,0,-1,0$", "starts at 1", "peak at $0°$", "starts at 0"], [0, 1, 2]));
  q.push(ms("easy", "Both curves:", ["range $[-1,1]$", "period $360°$", "wave shapes", "range $[0,1]$"], [0, 1, 2]));
  q.push(ms("easy", "Cosine vs sine:", ["cosine leads by $90°$", "$\\cos x=\\sin(x+90°)$", "same shape, shifted", "they are identical"], [0, 1, 2]));
  q.push(tf("easy", "$\\sin0°=0$.", true));
  q.push(tf("easy", "$\\cos0°=0$.", false));
  q.push(tf("easy", "$\\cos90°=0$.", true));
  q.push(fill("easy", "$\\sin90°$.", ["1"]));
  q.push(fill("easy", "$\\cos180°$.", ["-1"]));
  q.push(fill("easy", "$\\sin270°$.", ["-1"]));
  q.push(num("easy", "$\\sin0°$.", 0, 0));
  q.push(num("easy", "$\\cos0°$.", 1, 0));
  q.push(num("easy", "$\\sin180°$.", 0, 0));
  q.push(match("easy", "Match each value.", ["$\\sin90°$", "$\\cos0°$", "$\\sin180°$"], ["$1$", "$1$", "$0$"], [0, 1, 2]));
  q.push(mc("medium", "$y=\\cos x$ at $x=180°$.", ["$-1$", "$1$", "$0$", "$\\dfrac12$"], 0));
  q.push(mc("medium", "Where is $y=\\sin x$ maximum on $[0°,360°]$?", ["$90°$", "$0°$", "$180°$", "$270°$"], 0));
  q.push(mc("medium", "Where is $y=\\cos x$ minimum on $[0°,360°]$?", ["$180°$", "$0°$", "$90°$", "$360°$"], 0));
  q.push(mc("medium", "$y=\\sin x=0$ at:", ["$0°,180°,360°$", "$90°$", "$270°$", "$45°$"], 0));
  q.push(mc("medium", "The five key points of one sine cycle divide it into:", ["quarters", "halves", "thirds", "fifths"], 0));
  q.push(mc("medium", "$y=2\\cos x$ has maximum value:", ["$2$", "$1$", "$-2$", "$0$"], 0));
  q.push(ms("medium", "Graphing $y=\\sin x$:", ["plot key points", "$0,90,180,270,360$", "values $0,1,0,-1,0$", "random points"], [0, 1, 2]));
  q.push(ms("medium", "Graphing $y=\\cos x$:", ["starts at the max", "$1,0,-1,0,1$", "peak at $0°$", "starts at 0"], [0, 1, 2]));
  q.push(ms("medium", "Reading a graph:", ["amplitude from the height", "period from one cycle", "midline from the centre", "slope"], [0, 1, 2]));
  q.push(ms("medium", "Zeros of $\\sin x$:", ["$0°,180°,360°$", "every $180°$", "on the midline", "at the peaks"], [0, 1, 2]));
  q.push(tf("medium", "$y=\\sin x$ is maximum at $90°$.", true));
  q.push(tf("medium", "$y=\\cos x$ is minimum at $180°$.", true));
  q.push(tf("medium", "$y=\\sin x=0$ at $90°$.", false));
  q.push(fill("medium", "$x$ where $y=\\sin x$ is max on $[0°,360°]$.", ["90", "90°"]));
  q.push(fill("medium", "$\\cos180°$.", ["-1"]));
  q.push(fill("medium", "Number of key points in one sine cycle.", ["5"]));
  q.push(num("medium", "$x$ (degrees) of the first max of $y=\\sin x$.", 90, 0));
  q.push(num("medium", "$x$ (degrees) of the min of $y=\\cos x$ on $[0,360]$.", 180, 0));
  q.push(num("medium", "Max value of $y=2\\cos x$.", 2, 0));
  q.push(match("medium", "Match each.", ["max of $\\sin x$ at", "min of $\\cos x$ at", "zeros of $\\sin x$"], ["$90°$", "$180°$", "$0°,180°,360°$"], [0, 1, 2]));
  q.push(mc("hard", "$y=\\sin(2x)$ completes how many cycles on $[0°,360°]$?", ["$2$", "$1$", "$\\dfrac12$", "$4$"], 0));
  q.push(mc("hard", "First zero of $y=\\sin x$ after $x=0$:", ["$180°$", "$90°$", "$360°$", "$270°$"], 0));
  q.push(mc("hard", "$y=\\cos(2x)$ has period:", ["$180°$", "$360°$", "$90°$", "$720°$"], 0));
  q.push(mc("hard", "$y=3\\sin x$ at $x=90°$.", ["$3$", "$1$", "$0$", "$-3$"], 0));
  q.push(mc("hard", "$y=\\sin x+\\cos x$ at $x=0°$.", ["$1$", "$0$", "$2$", "$-1$"], 0));
  q.push(ms("hard", "$y=\\sin(2x)$ on $[0°,360°]$:", ["period $180°$", "two cycles", "compressed horizontally", "one cycle"], [0, 1, 2]));
  q.push(ms("hard", "Evaluating points:", ["substitute $x$", "$y=3\\sin90°=3$", "amplitude scales the value", "ignore amplitude"], [0, 1, 2]));
  q.push(ms("hard", "$y=\\cos(2x)$:", ["period $\\dfrac{360°}{2}=180°$", "horizontal compression", "two cycles in $360°$", "period $720°$"], [0, 1, 2]));
  q.push(ms("hard", "Sketching accurately:", ["use the new period", "mark quarter points", "scale by the amplitude", "ignore the period"], [0, 1, 2]));
  q.push(tf("hard", "$y=\\sin(2x)$ completes 2 cycles on $[0°,360°]$.", true));
  q.push(tf("hard", "$y=\\cos(2x)$ has period $180°$.", true));
  q.push(tf("hard", "$y=3\\sin x$ at $90°$ equals 1.", false));
  q.push(fill("hard", "Number of cycles of $y=\\sin(2x)$ on $[0°,360°]$.", ["2"]));
  q.push(fill("hard", "Period of $y=\\cos(2x)$ in degrees.", ["180", "180°"]));
  q.push(fill("hard", "$y=3\\sin x$ at $x=90°$.", ["3"]));
  q.push(num("hard", "Cycles of $y=\\sin(2x)$ on $[0°,360°]$.", 2, 0));
  q.push(num("hard", "Period of $y=\\cos(3x)$ in degrees.", 120, 0));
  q.push(num("hard", "$y=\\sin x+\\cos x$ at $x=0°$.", 1, 0));
  q.push(order("hard", "Order the steps to graph $y=\\sin(2x)$ on $[0°,360°]$.", ["Find the period $=180°$", "Mark quarter points every $45°$", "Plot $0,1,0,-1,0$", "Repeat for the second cycle"]));
  q.push(match("hard", "Match each function to its period.", ["$\\sin(2x)$", "$\\cos(3x)$", "$\\sin x$"], ["$180°$", "$120°$", "$360°$"], [0, 1, 2]));
  return q;
}

// ── 5.3 Transformations of Sinusoidal Functions ──────────────
function g53() {
  const q = [];
  q.push(mc("easy", "In $y=a\\sin(k(x-d))+c$, $a$ controls:", ["amplitude", "period", "phase shift", "midline"], 0));
  q.push(mc("easy", "$c$ controls:", ["the midline", "the amplitude", "the period", "the phase"], 0));
  q.push(mc("easy", "$y=\\sin x+4$ shifts:", ["up 4", "down 4", "right 4", "left 4"], 0));
  q.push(mc("easy", "$y=2\\sin x$ has amplitude:", ["$2$", "$1$", "$4$", "$\\dfrac12$"], 0));
  q.push(mc("easy", "$k$ affects the:", ["period", "amplitude", "midline", "none"], 0));
  q.push(mc("easy", "$d$ is the:", ["phase (horizontal) shift", "amplitude", "midline", "period"], 0));
  q.push(ms("easy", "The parameters:", ["$a$ amplitude", "$k$ period", "$c$ midline", "$a$ midline"], [0, 1, 2]));
  q.push(ms("easy", "$y=\\sin x+4$:", ["midline $y=4$", "shift up 4", "amplitude 1", "amplitude 4"], [0, 1, 2]));
  q.push(ms("easy", "Amplitude:", ["$|a|$", "$y=2\\sin x$ → 2", "stretches vertically", "equals the period"], [0, 1, 2]));
  q.push(ms("easy", "Horizontal shift:", ["$d$", "$y=\\sin(x-30°)$ right $30°$", "the phase shift", "is vertical"], [0, 1, 2]));
  q.push(tf("easy", "In $y=2\\sin x$, the amplitude is 2.", true));
  q.push(tf("easy", "$c$ controls the amplitude.", false));
  q.push(tf("easy", "$y=\\sin x+4$ has midline $y=4$.", true));
  q.push(fill("easy", "Amplitude of $y=5\\sin x$.", ["5"]));
  q.push(fill("easy", "Midline of $y=\\sin x-2$.", ["y=-2", "-2"]));
  q.push(fill("easy", "Direction of shift for $y=\\sin(x-20°)$.", ["right", "right 20°"]));
  q.push(num("easy", "Amplitude of $y=3\\sin x$.", 3, 0));
  q.push(num("easy", "Midline value of $y=\\sin x+7$.", 7, 0));
  q.push(num("easy", "Amplitude of $y=\\tfrac12\\cos x$ (decimal).", 0.5, 0.01));
  q.push(match("easy", "Match each parameter to what it controls.", ["$a$", "$k$", "$c$"], ["amplitude", "period", "midline"], [0, 1, 2]));
  q.push(mc("medium", "Period of $y=\\sin(2x)$ (degrees).", ["$180°$", "$360°$", "$90°$", "$720°$"], 0));
  q.push(mc("medium", "$y=\\sin(x-30°)$ is shifted:", ["right $30°$", "left $30°$", "up 30", "down 30"], 0));
  q.push(mc("medium", "$y=2\\sin x+3$: max value.", ["$5$", "$3$", "$2$", "$1$"], 0));
  q.push(mc("medium", "$y=\\cos x+2$ has midline:", ["$y=2$", "$y=0$", "$y=3$", "$y=1$"], 0));
  q.push(mc("medium", "Period of $y=\\cos(3x)$.", ["$120°$", "$360°$", "$180°$", "$90°$"], 0));
  q.push(mc("medium", "$y=-\\sin x$ is $\\sin x$:", ["reflected over the $x$-axis", "shifted up", "stretched", "shifted right"], 0));
  q.push(ms("medium", "For $y=2\\sin x+3$:", ["amplitude 2", "midline $y=3$", "max 5", "min 1"], [0, 1, 2, 3]));
  q.push(ms("medium", "Period change:", ["$\\dfrac{360°}{k}$", "$k=2$ → $180°$", "horizontal compression", "no change"], [0, 1, 2]));
  q.push(ms("medium", "Phase shift:", ["$y=\\sin(x-30°)$ right $30°$", "$d$ controls it", "opposite sign moves it", "always left"], [0, 1, 2]));
  q.push(ms("medium", "Reflection:", ["$a<0$ flips over the $x$-axis", "$y=-\\sin x$", "amplitude $|a|$", "shifts up"], [0, 1, 2]));
  q.push(tf("medium", "$y=\\sin(2x)$ has period $180°$.", true));
  q.push(tf("medium", "$y=\\sin(x-30°)$ shifts right $30°$.", true));
  q.push(tf("medium", "$y=2\\sin x+3$ has minimum 3.", false));
  q.push(fill("medium", "Period of $y=\\sin(2x)$ in degrees.", ["180", "180°"]));
  q.push(fill("medium", "Max of $y=2\\sin x+3$.", ["5"]));
  q.push(fill("medium", "Midline of $y=\\cos x+2$.", ["y=2", "2"]));
  q.push(num("medium", "Period of $y=\\cos(3x)$ in degrees.", 120, 0));
  q.push(num("medium", "Max of $y=2\\sin x+3$.", 5, 0));
  q.push(num("medium", "Min of $y=2\\sin x+3$.", 1, 0));
  q.push(match("medium", "Match each function to its period.", ["$\\sin(2x)$", "$\\cos(3x)$", "$\\sin(\\tfrac12 x)$"], ["$180°$", "$120°$", "$720°$"], [0, 1, 2]));
  q.push(mc("hard", "$y=3\\sin(2(x-45°))+1$: amplitude, period, phase, midline.", ["$3$, $180°$, right $45°$, $y=1$", "$3$, $360°$, left $45°$, $y=1$", "$2$, $180°$, right $45°$, $y=3$", "$3$, $90°$, right $45°$, $y=1$"], 0));
  q.push(mc("hard", "Max of $y=3\\sin(2(x-45°))+1$.", ["$4$", "$3$", "$1$", "$2$"], 0));
  q.push(mc("hard", "A sinusoid with amplitude 5, midline $y=2$, period $180°$ (sine):", ["$y=5\\sin(2x)+2$", "$y=2\\sin(5x)+5$", "$y=5\\sin(x)+2$", "$y=5\\sin(180x)+2$"], 0));
  q.push(mc("hard", "Phase shift of $y=\\cos(x+60°)$.", ["left $60°$", "right $60°$", "up 60", "down 60"], 0));
  q.push(mc("hard", "Period of $y=\\sin(\\tfrac12 x)$.", ["$720°$", "$180°$", "$360°$", "$90°$"], 0));
  q.push(ms("hard", "For $y=3\\sin(2(x-45°))+1$:", ["amplitude 3", "period $180°$", "phase right $45°$", "midline $y=1$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Building an equation:", ["$a=$ amplitude", "$k=\\dfrac{360°}{\\text{period}}$", "$c=$ midline", "$d=$ phase"], [0, 1, 2, 3]));
  q.push(ms("hard", "Period & $k$:", ["period $=\\dfrac{360°}{k}$", "$k=\\tfrac12$ → $720°$", "smaller $k$, longer period", "$k$ irrelevant"], [0, 1, 2]));
  q.push(ms("hard", "Phase direction:", ["$(x-d)$ shifts right", "$(x+d)$ shifts left", "opposite to the sign", "always right"], [0, 1, 2]));
  q.push(tf("hard", "$y=3\\sin(2(x-45°))+1$ has period $180°$.", true));
  q.push(tf("hard", "$y=\\cos(x+60°)$ shifts left $60°$.", true));
  q.push(tf("hard", "$y=\\sin(\\tfrac12 x)$ has period $180°$.", false));
  q.push(fill("hard", "Period of $y=\\sin(\\tfrac12 x)$ in degrees.", ["720", "720°"]));
  q.push(fill("hard", "Max of $y=3\\sin(2(x-45°))+1$.", ["4"]));
  q.push(fill("hard", "$k$ for a period of $180°$.", ["2"]));
  q.push(num("hard", "Max of $y=3\\sin(2(x-45°))+1$.", 4, 0));
  q.push(num("hard", "Period of $y=\\sin(\\tfrac12 x)$ in degrees.", 720, 0));
  q.push(num("hard", "$k$ for a period of $90°$.", 4, 0));
  q.push(order("hard", "Order the steps to write a sine curve with amplitude 5, period $180°$, midline $y=2$.", ["$a=5$", "$k=\\dfrac{360°}{180°}=2$", "$c=2$", "$y=5\\sin(2x)+2$"]));
  q.push(match("hard", "Match each property of $y=3\\sin(2(x-45°))+1$.", ["amplitude", "period", "phase shift"], ["$3$", "$180°$", "right $45°$"], [0, 1, 2]));
  return q;
}

// ── 5.4 Sinusoidal Applications ──────────────────────────────
function g54() {
  const q = [];
  q.push(mc("easy", "A Ferris wheel's height over time is modeled by a:", ["sinusoidal function", "linear function", "quadratic", "constant"], 0));
  q.push(mc("easy", "The midline of a Ferris-wheel model represents:", ["the centre height of the wheel", "the top", "the ground", "the speed"], 0));
  q.push(mc("easy", "The amplitude of a Ferris-wheel model is:", ["the radius", "the diameter", "the centre height", "the period"], 0));
  q.push(mc("easy", "The period represents:", ["time for one full rotation", "the radius", "the height", "the speed"], 0));
  q.push(mc("easy", "Tides can be modeled with:", ["a sinusoidal function", "a line", "a parabola", "none"], 0));
  q.push(mc("easy", "The maximum height equals:", ["midline + amplitude", "midline − amplitude", "amplitude only", "the period"], 0));
  q.push(ms("easy", "Ferris-wheel model:", ["amplitude = radius", "midline = centre height", "period = one rotation", "amplitude = diameter"], [0, 1, 2]));
  q.push(ms("easy", "Real sinusoids:", ["tides", "Ferris wheels", "daylight hours", "straight roads"], [0, 1, 2]));
  q.push(ms("easy", "Max/min:", ["max = midline + amplitude", "min = midline − amplitude", "amplitude is the radius", "ignore midline"], [0, 1, 2]));
  q.push(ms("easy", "Reading the model:", ["period = repeat time", "amplitude = swing", "midline = average", "slope"], [0, 1, 2]));
  q.push(tf("easy", "A Ferris wheel's height is sinusoidal.", true));
  q.push(tf("easy", "The amplitude equals the diameter.", false));
  q.push(tf("easy", "Tides can be modeled sinusoidally.", true));
  q.push(fill("easy", "Max height if midline 10, amplitude 4.", ["14"]));
  q.push(fill("easy", "Min height if midline 10, amplitude 4.", ["6"]));
  q.push(fill("easy", "Amplitude if the wheel radius is 8.", ["8"]));
  q.push(num("easy", "Max height: midline 12, amplitude 5.", 17, 0));
  q.push(num("easy", "Min height: midline 12, amplitude 5.", 7, 0));
  q.push(num("easy", "Amplitude if max $=20$, min $=4$.", 8, 0));
  q.push(match("easy", "Match each part of a Ferris-wheel model.", ["amplitude", "midline", "period"], ["radius", "centre height", "one rotation"], [0, 1, 2]));
  q.push(mc("medium", "Ferris wheel: radius 10 m, centre 12 m high. Max height:", ["$22$ m", "$12$ m", "$2$ m", "$10$ m"], 0));
  q.push(mc("medium", "Same wheel: min height.", ["$2$ m", "$12$ m", "$22$ m", "$0$ m"], 0));
  q.push(mc("medium", "One rotation takes 60 s. The period is:", ["$60$ s", "$30$ s", "$120$ s", "$1$ s"], 0));
  q.push(mc("medium", "Amplitude of a tide from 6 m high to 2 m low:", ["$2$ m", "$4$ m", "$8$ m", "$6$ m"], 0));
  q.push(mc("medium", "Midline of that tide:", ["$4$ m", "$2$ m", "$6$ m", "$8$ m"], 0));
  q.push(mc("medium", "A model $h=10\\sin(\\dots)+12$. The midline is:", ["$12$", "$10$", "$22$", "$2$"], 0));
  q.push(ms("medium", "Ferris wheel (r=10, centre 12):", ["amplitude 10", "midline 12", "max 22", "min 2"], [0, 1, 2, 3]));
  q.push(ms("medium", "Tide 6 m to 2 m:", ["amplitude $\\dfrac{6-2}2=2$", "midline $\\dfrac{6+2}2=4$", "range 4", "amplitude 4"], [0, 1, 2]));
  q.push(ms("medium", "Period from rotation time:", ["= time for one cycle", "60 s rotation → period 60 s", "appears as $k$", "is the radius"], [0, 1, 2]));
  q.push(ms("medium", "From a model $h=a\\sin+c$:", ["$a$ amplitude", "$c$ midline", "max $=c+a$", "$c$ amplitude"], [0, 1, 2]));
  q.push(tf("medium", "A wheel with radius 10, centre 12 reaches max height 22 m.", true));
  q.push(tf("medium", "A tide from 6 m to 2 m has amplitude 2 m.", true));
  q.push(tf("medium", "A 60 s rotation gives a period of 30 s.", false));
  q.push(fill("medium", "Max height: radius 10, centre 12.", ["22", "22 m"]));
  q.push(fill("medium", "Min height: radius 10, centre 12.", ["2", "2 m"]));
  q.push(fill("medium", "Amplitude of a tide 6 m high to 2 m low.", ["2", "2 m"]));
  q.push(num("medium", "Max height (m): radius 10, centre 12.", 22, 0));
  q.push(num("medium", "Min height (m): radius 10, centre 12.", 2, 0));
  q.push(num("medium", "Amplitude (m) of a tide from 6 m to 2 m.", 2, 0));
  q.push(match("medium", "Match each to its value (r=10, centre 12).", ["amplitude", "midline", "max height"], ["$10$", "$12$", "$22$"], [0, 1, 2]));
  q.push(mc("hard", "Ferris wheel radius 8 m, centre 10 m, one rotation 40 s. Model $h=$", ["$8\\sin(\\tfrac{360°}{40}t)+10$", "$10\\sin(8t)+8$", "$8\\sin(40t)+10$", "$8\\sin t+10$"], 0));
  q.push(mc("hard", "Max height of that wheel.", ["$18$ m", "$10$ m", "$8$ m", "$2$ m"], 0));
  q.push(mc("hard", "Its period.", ["$40$ s", "$8$ s", "$10$ s", "$20$ s"], 0));
  q.push(mc("hard", "A tide: high 5 m, low 1 m. Amplitude and midline.", ["$2$ m, $3$ m", "$4$ m, $3$ m", "$2$ m, $4$ m", "$4$ m, $2$ m"], 0));
  q.push(mc("hard", "Daylight ranges 16 h (max) to 8 h (min). The amplitude is:", ["$4$ h", "$8$ h", "$12$ h", "$2$ h"], 0));
  q.push(ms("hard", "Building $h=a\\sin(kt)+c$ (r=8, centre 10, 40 s):", ["$a=8$", "$c=10$", "$k=\\dfrac{360°}{40}$", "$a=10$"], [0, 1, 2]));
  q.push(ms("hard", "Max/min of the wheel:", ["max $=10+8=18$", "min $=10-8=2$", "amplitude 8", "max 28"], [0, 1, 2]));
  q.push(ms("hard", "Tide (5 m to 1 m):", ["amplitude 2", "midline 3", "range 4", "amplitude 4"], [0, 1, 2]));
  q.push(ms("hard", "Daylight 16 h to 8 h:", ["amplitude $\\dfrac{16-8}2=4$", "midline 12", "models the year", "amplitude 8"], [0, 1, 2]));
  q.push(tf("hard", "A wheel radius 8, centre 10 reaches 18 m at the top.", true));
  q.push(tf("hard", "A tide from 5 m to 1 m has amplitude 2 m.", true));
  q.push(tf("hard", "Daylight from 16 h to 8 h has amplitude 8 h.", false));
  q.push(fill("hard", "Max height: radius 8, centre 10.", ["18", "18 m"]));
  q.push(fill("hard", "Amplitude of a tide 5 m to 1 m.", ["2", "2 m"]));
  q.push(fill("hard", "Amplitude of daylight 16 h to 8 h.", ["4", "4 h"]));
  q.push(num("hard", "Max height (m): radius 8, centre 10.", 18, 0));
  q.push(num("hard", "Period (s) if one rotation takes 40 s.", 40, 0));
  q.push(num("hard", "Midline (h) of daylight ranging 16 h to 8 h.", 12, 0));
  q.push(order("hard", "Order the steps to model a Ferris wheel (r=8, centre 10, 40 s rotation).", ["Amplitude $a=8$", "Midline $c=10$", "$k=\\dfrac{360°}{40}=9°$/s", "$h=8\\sin(9t)+10$"]));
  q.push(match("hard", "Match each to its value (r=8, centre 10, 40 s).", ["amplitude", "midline", "period"], ["$8$", "$10$", "$40$ s"], [0, 1, 2]));
  return q;
}

export default [
  { code: "5.1", gen: g51 },
  { code: "5.2", gen: g52 },
  { code: "5.3", gen: g53 },
  { code: "5.4", gen: g54 },
];
