// MBF3C Unit 1 worksheets — Quadratic Relations.
// Examples: full step-by-step solutions with TikZ parabola graphs (\eplot).
const r = String.raw;
const U = "1: Quadratic Relations";

export default [
  {
    code: "1.1", unit: U, title: "Expanding & Factoring Quadratics",
    intro: r`Expanding removes brackets; factoring reverses it. Move between the two forms of a quadratic.`,
    ideas: [r`Distribute and FOIL: $(x+p)(x+q)=x^2+(p+q)x+pq$.`, r`Special products: $(a\pm b)^2$ and $(a-b)(a+b)=a^2-b^2$.`, r`Factor: common factor first, then two numbers with product $c$, sum $b$.`],
    examples: [
      { t: "Distribute", body: r`Expand $3(x+4)$.\soln Multiply each term by 3: $3x+12$.` },
      { t: "FOIL", body: r`Expand $(x+2)(x+3)$.\soln First, Outer, Inner, Last: $x^2+3x+2x+6=x^2+5x+6$ — the factored and expanded forms are the same parabola (x-intercepts $-2,-3$):` + r`\eplot{-7}{2}{-3}{8}{\addplot[exblue,very thick,domain=-6.2:0.8]{x^2+5*x+6};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-2,0) (-3,0)};}` },
      { t: "Perfect square", body: r`Expand $(x+5)^2$.\soln $x^2+2(5)x+25=x^2+10x+25$ (not $x^2+25$).` },
      { t: "Difference of squares", body: r`Expand $(x-4)(x+4)$.\soln Middle terms cancel: $x^2-16$.` },
      { t: "Factor a trinomial", body: r`Factor $x^2+7x+12$.\soln Product $12$, sum $7$: $3$ and $4$. $(x+3)(x+4)$:` + r`\eplot{-7}{1}{-3}{8}{\addplot[exblue,very thick,domain=-6.2:0.2]{x^2+7*x+12};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-3,0) (-4,0)};}` },
      { t: "Common factor", body: r`Factor $2x^2+8x$.\soln GCF $2x$: $2x(x+4)$.` },
      { t: "Mixed signs", body: r`Factor $x^2-x-6$.\soln Product $-6$, sum $-1$: $-3,2$. $(x-3)(x+2)$.` },
      { t: "Binomial product", body: r`Expand $(2x+1)(x+3)$.\soln $2x^2+6x+x+3=2x^2+7x+3$.` },
      { t: "Difference of squares", body: r`Factor $x^2-9$.\soln $(x-3)(x+3)$.` },
    ],
    questions: [
      { ask: r`Expand $5(x-2)$.` },
      { ask: r`Expand $x(3x+4)$.` },
      { ask: r`Expand $(x+4)(x+5)$.` },
      { ask: r`Expand $(x-3)^2$.` },
      { ask: r`Expand $(x-6)(x+6)$.` },
      { ask: r`Factor $x^2+8x+15$.` },
      { ask: r`Factor $x^2-2x-15$.` },
      { ask: r`Factor $4x^2+8x$.` },
      { ask: r`Factor $x^2-7x+10$.` },
      { ask: r`Factor $x^2-25$.` },
      { ask: r`Expand $(2x+3)(x-1)$.` },
      { ask: r`Factor $x^2+6x+9$.` },
      { ask: r`Expand $(x+2)(x^2-3x+1)$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$5x-10$`, r`$3x^2+4x$`, r`$x^2+9x+20$`, r`$x^2-6x+9$`, r`$x^2-36$`, r`$(x+3)(x+5)$`, r`$(x-5)(x+3)$`, r`$4x(x+2)$`, r`$(x-2)(x-5)$`, r`$(x-5)(x+5)$`, r`$2x^2+x-3$`, r`$(x+3)^2$`, r`$x^3-x^2-5x+2$`],
  },
  {
    code: "1.2", unit: U, title: "Quadratic Relations & Their Graphs",
    intro: r`Vertex form $y=a(x-h)^2+k$ has vertex $(h,k)$; $a$ stretches/reflects, $h$ shifts horizontally, $k$ vertically.`,
    ideas: [r`$a$: stretch by $|a|$; reflect if $a<0$.`, r`$h$: horizontal shift (opposite to the sign). $k$: vertical shift.`, r`Standard form comes from expanding vertex form.`],
    examples: [
      { t: "Read the vertex", body: r`Vertex of $y=(x-3)^2+2$.\soln $h=3,\ k=2$: vertex $(3,2)$:` + r`\eplot{-1}{7}{-1}{10}{\addplot[exblue,very thick,domain=0.5:5.5]{(x-3)^2+2};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(3,2)};}` },
      { t: "Describe", body: r`Describe $y=-2(x+1)^2+5$ from $y=x^2$.\soln $a=-2$ reflect and stretch 2; $h=-1$ left 1; $k=5$ up 5.` },
      { t: "Vertex to standard", body: r`Expand $y=(x-1)^2+4$.\soln $x^2-2x+1+4=x^2-2x+5$.` },
      { t: "Direction & max", body: r`For $y=-(x-2)^2+3$, state the direction and max.\soln $a<0$ opens down; vertex $(2,3)$: maximum 3:` + r`\eplot{-2}{6}{-6}{5}{\addplot[exblue,very thick,domain=-0.5:4.5]{-(x-2)^2+3};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(2,3)};}` },
      { t: "Write the equation", body: r`Write $y=x^2$ shifted right 3 and down 2.\soln $h=3,\ k=-2$: $y=(x-3)^2-2$.` },
      { t: "Negative h", body: r`Vertex of $y=(x+4)^2-2$.\soln $(-4,-2)$.` },
      { t: "Direction", body: r`Does $y=3(x-1)^2$ open up or down?\soln $a=3>0$: up.` },
      { t: "Max value", body: r`Max value of $y=-(x-5)^2+8$.\soln Vertex $(5,8)$, opens down: $8$.` },
      { t: "Standard form", body: r`Write $y=(x+2)^2-7$ in standard form.\soln $x^2+4x+4-7=x^2+4x-3$.` },
    ],
    questions: [
      { ask: r`State the vertex of $y=(x-2)^2+5$.` },
      { ask: r`State the vertex of $y=(x+1)^2-3$.` },
      { ask: r`Describe $y=-(x-4)^2$ from $y=x^2$.` },
      { ask: r`Write $y=x^2$ shifted left 3 and up 2.` },
      { ask: r`Max or min value of $y=(x-5)^2+1$?` },
      { ask: r`Expand $y=(x-2)^2+1$ to standard form.` },
      { ask: r`Does $y=-3(x+2)^2-1$ open up or down?` },
      { ask: r`State the vertex of $y=4(x-3)^2$.` },
      { ask: r`State the max value of $y=-(x+1)^2+10$.` },
      { ask: r`Write $y=x^2$ reflected and up 6.` },
      { ask: r`State the stretch factor of $y=5(x-2)^2+1$.` },
      { ask: r`Expand $y=(x+3)^2-2$ to standard form.` },
      { ask: r`A parabola has vertex $(2,-3)$ and passes through $(0,5)$. Find $a$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$(2,5)$`, r`$(-1,-3)$`, r`reflect, right 4`, r`$y=(x+3)^2+2$`, r`min 1`, r`$y=x^2-4x+5$`, r`down`, r`$(3,0)$`, r`10`, r`$y=-x^2+6$`, r`$5$`, r`$y=x^2+6x+7$`, r`$a=2$`],
  },
  {
    code: "1.3", unit: U, title: "Solving Quadratic Equations",
    intro: r`Solve $ax^2+bx+c=0$ by factoring and the zero product property; the solutions are the x-intercepts.`,
    ideas: [r`Rearrange so one side is $0$.`, r`Factor (common factor first), then set each factor to $0$.`, r`Solutions are where the parabola meets the x-axis.`],
    examples: [
      { t: "Trinomial", body: r`Solve $x^2-5x+6=0$.\soln $(x-2)(x-3)=0\Rightarrow x=2$ or $x=3$ — the x-intercepts:` + r`\eplot{-1}{6}{-2}{8}{\addplot[exblue,very thick,domain=0:5]{x^2-5*x+6};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(2,0) (3,0)};}` },
      { t: "Difference of squares", body: r`Solve $x^2-9=0$.\soln $(x-3)(x+3)=0\Rightarrow x=\pm3$.` },
      { t: "Negative constant", body: r`Solve $x^2+2x-8=0$.\soln $(x+4)(x-2)=0\Rightarrow x=-4,2$.` },
      { t: "Common factor", body: r`Solve $x^2-6x=0$.\soln $x(x-6)=0\Rightarrow x=0$ or $x=6$:` + r`\eplot{-2}{8}{-12}{8}{\addplot[exblue,very thick,domain=-1:7]{x^2-6*x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,0) (6,0)};}` },
      { t: "Break-even", body: r`Profit (in $\$1000$s) is $P=x^2-7x+10$. Where is $P=0$?\soln $(x-2)(x-5)=0\Rightarrow x=2$ or $x=5$.` },
      { t: "Trinomial", body: r`Solve $x^2-7x+10=0$.\soln $(x-2)(x-5)=0\Rightarrow x=2,5$.` },
      { t: "Mixed signs", body: r`Solve $x^2-x-12=0$.\soln $(x-4)(x+3)=0\Rightarrow x=4,-3$.` },
      { t: "Both negative", body: r`Solve $x^2+5x+6=0$.\soln $(x+2)(x+3)=0\Rightarrow x=-2,-3$.` },
      { t: "Larger squares", body: r`Solve $x^2-16=0$.\soln $(x-4)(x+4)=0\Rightarrow x=\pm4$.` },
    ],
    questions: [
      { ask: r`Solve $x^2-7x+10=0$.` },
      { ask: r`Solve $x^2-16=0$.` },
      { ask: r`Solve $x^2+5x+6=0$.` },
      { ask: r`Solve $x^2-3x-10=0$.` },
      { ask: r`Solve $x^2-8x=0$.` },
      { ask: r`Solve $x^2+x-20=0$.` },
      { ask: r`Solve $x^2-25=0$.` },
      { ask: r`Solve $x^2-10x+24=0$.` },
      { ask: r`Solve $x^2+2x-15=0$.` },
      { ask: r`Solve $x^2-4x=0$.` },
      { ask: r`Solve $x^2-x-6=0$.` },
      { ask: r`A profit relation $P=x^2-9x+20$; find the break-even values.` },
      { ask: r`Solve $x^2-2x-3=0$ and state the x-intercepts of $y=x^2-2x-3$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$x=2,5$`, r`$x=\pm4$`, r`$x=-2,-3$`, r`$x=5,-2$`, r`$x=0,8$`, r`$x=4,-5$`, r`$x=\pm5$`, r`$x=4,6$`, r`$x=3,-5$`, r`$x=0,4$`, r`$x=3,-2$`, r`$x=4,5$`, r`$x=3,-1$`],
  },
  {
    code: "1.4", unit: U, title: "Quadratic Models & Applications",
    intro: r`The vertex gives the maximum (if $a<0$) or minimum (if $a>0$); the x-intercepts give break-even or landing times.`,
    ideas: [r`$a>0$ minimum; $a<0$ maximum, at the vertex.`, r`Find the vertex with $x=-\dfrac{b}{2a}$, then substitute.`, r`Set the relation to $0$ for break-even / landing.`],
    examples: [
      { t: "Read a max", body: r`Find the maximum of $y=-(x-3)^2+9$.\soln Vertex $(3,9)$, opens down: maximum 9 at $x=3$:` + r`\eplot{-1}{7}{-2}{11}{\addplot[exblue,very thick,domain=0:6]{-(x-3)^2+9};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(3,9)};}` },
      { t: "Max height", body: r`A ball: $h=-5t^2+20t$. Max height?\soln $t=-\dfrac{20}{2(-5)}=2$; $h=-20+40=20$ m:` + r`\eplot{-0.5}{4.5}{-2}{24}{\addplot[exblue,very thick,domain=0:4]{-5*x^2+20*x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(2,20)};}` },
      { t: "When it lands", body: r`Same ball: when does it hit the ground?\soln $-5t(t-4)=0\Rightarrow t=0$ or $t=4$ s.` },
      { t: "Max profit", body: r`Profit $P=-2x^2+12x-10$. Max profit?\soln $x=3$; $P=-18+36-10=8$.` },
      { t: "Max area", body: r`Perimeter 20 m rectangle. Max area?\soln $A=w(10-w)$, vertex $w=5$: $5\times5$, area 25 m\textsuperscript{2}.` },
      { t: "Find a min", body: r`Min of $y=x^2-6x+5$.\soln $x=3$; $y=9-18+5=-4$.` },
      { t: "Max height", body: r`$h=-5t^2+30t$. Max height?\soln $t=3$; $h=45$ m.` },
      { t: "Break-even", body: r`$P=x^2-8x+12$. Break-even values?\soln $(x-2)(x-6)=0\Rightarrow x=2,6$.` },
      { t: "Max area", body: r`Perimeter 24 m rectangle. Max area?\soln $6\times6=36$ m\textsuperscript{2}.` },
    ],
    questions: [
      { ask: r`Find the maximum of $y=-(x-1)^2+4$.` },
      { ask: r`Find the minimum of $y=x^2-2x+5$.` },
      { ask: r`A ball $h=-5t^2+10t$. Find the maximum height.` },
      { ask: r`Profit $P=-x^2+8x-7$. Find the maximum profit.` },
      { ask: r`When does $h=-5t^2+20t$ hit the ground?` },
      { ask: r`A rectangle has perimeter 16 m. Find the maximum area.` },
      { ask: r`Find the maximum of $y=-2(x-3)^2+5$.` },
      { ask: r`Find the minimum of $y=x^2-4x+1$.` },
      { ask: r`A ball $h=-5t^2+40t$. Find the maximum height.` },
      { ask: r`$P=x^2-9x+20$. Find the break-even values.` },
      { ask: r`A model $h=-5t^2+25t$. When does it land?` },
      { ask: r`Find the maximum of $y=-(x+2)^2+12$.` },
      { ask: r`A rectangular pen against a wall uses 60 m of fencing on three sides. Find the maximum area.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$4$`, r`$4$`, r`$5$ m (at $t=1$)`, r`$9$ (at $x=4$)`, r`$t=4$ s`, r`$16$ m\textsuperscript{2} ($4\times4$)`, r`$5$`, r`$-3$ (at $x=2$)`, r`$80$ m (at $t=4$)`, r`$x=4,5$`, r`$t=5$ s`, r`$12$`, r`$450$ m\textsuperscript{2} ($15\times30$)`],
  },
];
