// MBF3C Unit 2 worksheets — Exponential Relations.
// Examples: full step-by-step solutions with TikZ exponential curves (\eplot).
const r = String.raw;
const U = "2: Exponential Relations";

export default [
  {
    code: "2.1", unit: U, title: "Exponent Laws",
    intro: r`Exponent laws combine powers, including zero and negative exponents.`,
    ideas: [r`Product $x^m x^n=x^{m+n}$; quotient $\dfrac{x^m}{x^n}=x^{m-n}$; power $(x^m)^n=x^{mn}$.`, r`$x^0=1$ and $x^{-n}=\dfrac{1}{x^n}$.`, r`A negative exponent means reciprocal, not a negative number.`],
    examples: [
      { t: "Product", body: r`Simplify $x^5\cdot x^3$.\soln Add the exponents: $x^{5+3}=x^8$.` },
      { t: "Quotient", body: r`Simplify $\dfrac{x^9}{x^4}$.\soln Subtract the exponents: $x^{9-4}=x^5$.` },
      { t: "Power of a power", body: r`Simplify $(x^4)^3$.\soln Multiply the exponents: $x^{4\cdot3}=x^{12}$.` },
      { t: "Power of a product", body: r`Simplify $(2x^3)^2$.\soln The exponent reaches both factors: $2^2 x^{6}=4x^6$.` },
      { t: "Zero exponent", body: r`Evaluate $5^0$.\soln Any non-zero base to the power 0 is $1$.` },
      { t: "Negative exponent", body: r`Evaluate $2^{-3}$.\soln Reciprocal: $\dfrac{1}{2^3}=\dfrac18$.` },
      { t: "Negative exponent", body: r`Evaluate $5^{-2}$.\soln $\dfrac{1}{5^2}=\dfrac{1}{25}$.` },
      { t: "Combine laws", body: r`Simplify $x^{-3}\cdot x^{7}$.\soln Add exponents: $x^{-3+7}=x^4$.` },
      { t: "Growth vs decay", body: r`Sketch the shapes of $y=2^x$ and $y=0.5^x$.\soln Base $>1$ grows; base $<1$ decays; both pass $(0,1)$:` + r`\eplot{-3}{3}{-1}{9}{\addplot[exblue,very thick,domain=-3:3]{2^x};\addplot[qorange,very thick,domain=-3:3]{0.5^x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,1)};}` },
    ],
    questions: [
      { ask: r`Simplify $x^6\cdot x^2$.` },
      { ask: r`Simplify $(x^3)^2$.` },
      { ask: r`Simplify $\dfrac{y^8}{y^3}$.` },
      { ask: r`Evaluate $4^0$.` },
      { ask: r`Evaluate $3^{-2}$.` },
      { ask: r`Simplify $(3x^2)^3$.` },
      { ask: r`Simplify $\dfrac{x^{10}}{x^{7}}$.` },
      { ask: r`Evaluate $2^{-4}$.` },
      { ask: r`Simplify $(2x^3y)^2$.` },
      { ask: r`Simplify $x^{-3}\cdot x^{7}$.` },
      { ask: r`Evaluate $10^{-1}$.` },
      { ask: r`Simplify $\left(\dfrac{x^6}{x^2}\right)^2$.` },
      { ask: r`Simplify $\dfrac{(2x^2)^3}{4x^3}$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$x^8$`, r`$x^6$`, r`$y^5$`, r`$1$`, r`$\dfrac{1}{9}$`, r`$27x^6$`, r`$x^3$`, r`$\dfrac{1}{16}$`, r`$4x^6y^2$`, r`$x^4$`, r`$\dfrac{1}{10}$`, r`$x^8$`, r`$2x^3$`],
  },
  {
    code: "2.2", unit: U, title: "Exponential Relations & Graphs",
    intro: r`$y=a\cdot b^x$ has y-intercept $(0,a)$, horizontal asymptote $y=0$, domain all reals, and range $y>0$.`,
    ideas: [r`$b>1$ grows; $0<b<1$ decays; a larger base is steeper.`, r`The y-intercept is $a$ (since $b^0=1$).`, r`Exponential beats linear and quadratic for large $x$.`],
    examples: [
      { t: "Evaluate", body: r`For $y=2^x$, find the value at $x=3$.\soln $2^3=8$.` },
      { t: "y-intercept", body: r`State the y-intercept of $y=3\cdot2^x$.\soln At $x=0$, $2^0=1$, so $y=3$. y-intercept $(0,3)$.` },
      { t: "Growth or decay", body: r`Is $y=\left(\tfrac12\right)^x$ growth or decay?\soln Base between 0 and 1, so decay:` + r`\eplot{-3}{3}{-1}{9}{\addplot[exblue,very thick,domain=-3:3]{0.5^x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,1)};}` },
      { t: "Asymptote", body: r`State the horizontal asymptote of $y=2^x$.\soln As $x\to-\infty$, $2^x\to0$. Asymptote $y=0$:` + r`\eplot{-4}{3}{-1}{9}{\addplot[exblue,very thick,domain=-4:3]{2^x};}` },
      { t: "Distinguish relations", body: r`Which grows fastest for large $x$: $2x$, $x^2$, or $2^x$?\soln Multiplying beats adding or squaring eventually: $2^x$.` },
      { t: "Compare bases", body: r`Which grows faster, $2^x$ or $5^x$?\soln Both pass $(0,1)$; the larger base is steeper: $5^x$.` },
      { t: "Domain & range", body: r`Domain and range of $y=2^x$.\soln Any $x$; outputs positive. Domain all reals; range $y>0$.` },
      { t: "Negative input", body: r`Find $2^x$ at $x=-1$.\soln $2^{-1}=\dfrac12$.` },
      { t: "y-intercept", body: r`State the y-intercept of $y=5\cdot2^x$.\soln $5\cdot1=5$: $(0,5)$.` },
    ],
    questions: [
      { ask: r`Find $2^x$ at $x=4$.` },
      { ask: r`State the y-intercept of $y=4\cdot3^x$.` },
      { ask: r`Is $y=0.8^x$ growth or decay?` },
      { ask: r`State the asymptote of $y=2^x$.` },
      { ask: r`State the domain of $y=2^x$.` },
      { ask: r`State the range of $y=2^x$.` },
      { ask: r`Find $3^x$ at $x=2$.` },
      { ask: r`State the y-intercept of $y=2^x$.` },
      { ask: r`Is $y=2^x$ growth or decay?` },
      { ask: r`Which is steeper, $2^x$ or $10^x$?` },
      { ask: r`Find $\left(\tfrac13\right)^x$ at $x=2$.` },
      { ask: r`Which grows fastest for large $x$: $3x$, $x^2$, or $3^x$?` },
      { ask: r`A relation $y=a\cdot b^x$ passes $(0,5)$ and $(1,15)$. Find $b$.`, challenge: true, ws: "2.6cm" },
    ],
    answers: [r`$16$`, r`$(0,4)$`, r`decay`, r`$y=0$`, r`all reals`, r`$y>0$`, r`$9$`, r`$(0,1)$`, r`growth`, r`$10^x$`, r`$\dfrac19$`, r`$3^x$`, r`$b=3$`],
  },
  {
    code: "2.3", unit: U, title: "Exponential Growth & Decay Applications",
    intro: r`Model with $y=a\cdot b^t$: $a$ is the initial amount, $b=1+r$ for growth or $1-r$ for decay; half-life uses $\left(\tfrac12\right)^{t/h}$.`,
    ideas: [r`Growth factor $1+r$; decay factor $1-r$.`, r`Doubling: $b=2$. Half-life $h$: $b=\tfrac12$ over each period.`, r`Compound interest $A=P(1+i)^n$ is exponential.`],
    examples: [
      { t: "Doubling", body: r`$P=200(2)^t$. Find $P$ after 3 years.\soln $200(2)^3=200(8)=1600$. Doubling has the shape of $y=2^x$:` + r`\eplot{-1}{4}{-1}{9}{\addplot[exblue,very thick,domain=-1:3.2]{2^x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,1) (1,2) (2,4) (3,8)};}` },
      { t: "Half-life", body: r`80 g halves every 5 years. How much after 10 years?\soln $10\div5=2$ half-lives: $80\left(\tfrac12\right)^2=20$ g.` },
      { t: "Growth factor", body: r`A town grows $8\%$ per year. State the growth factor.\soln $b=1+0.08=1.08$.` },
      { t: "Decay factor", body: r`A car loses $15\%$ each year. State the decay factor.\soln $b=1-0.15=0.85$.` },
      { t: "Bouncing ball", body: r`Height after $n$ bounces: $h=100(0.6)^n$ cm. Find $h$ after 3 bounces.\soln $100(0.6)^3=100(0.216)=21.6$ cm.` },
      { t: "Compound interest", body: r`\$1000 grows at $5\%$/year for 2 years.\soln $1000(1.05)^2\approx\$1102.50$.` },
      { t: "Doubling", body: r`$P=200(2)^t$ after 4 years.\soln $200(16)=3200$.` },
      { t: "Half-life", body: r`100 g halves every 3 h. After 9 h?\soln $9\div3=3$: $100\left(\tfrac12\right)^3=12.5$ g.` },
      { t: "Growth factor", body: r`Growth of $5\%$ per year.\soln $b=1.05$.` },
    ],
    questions: [
      { ask: r`State the growth factor for $+10\%$ per year.` },
      { ask: r`State the decay factor for $-20\%$ per year.` },
      { ask: r`For $P=200(2)^t$, find $P$ after 2 years.` },
      { ask: r`80 g halves every 5 years. How much after 15 years?` },
      { ask: r`\$1000 at $5\%$/year for 3 years. Find the value.` },
      { ask: r`State the doubling factor.` },
      { ask: r`State the decay factor for $-5\%$ per year.` },
      { ask: r`100 g halves every 4 h. How much after 8 h?` },
      { ask: r`For $h=100(0.6)^n$, find the height after 2 bounces.` },
      { ask: r`For $P=50(3)^t$, find $P$ after 2 years.` },
      { ask: r`State the growth factor for $+12\%$ per year.` },
      { ask: r`How much of 64 g remains after one half-life?` },
      { ask: r`A population triples every 4 h. Write the model with $t$ in hours.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$1.10$`, r`$0.80$`, r`$800$`, r`$10$ g`, r`$\approx\$1157.63$`, r`$2$`, r`$0.95$`, r`$25$ g`, r`$36$ cm`, r`$450$`, r`$1.12$`, r`$32$ g`, r`$y=a\cdot3^{t/4}$`],
  },
];
