// MBF3C Unit 4 worksheets — Geometry & Trigonometry.
// Figures: \rtri (cone slant height), \eplot (optimization parabola), \gtri (sine/cosine law).
const r = String.raw;
const U = "4: Geometry and Trigonometry";

export default [
  {
    code: "4.1", unit: U, title: "Surface Area & Volume",
    intro: r`Volume measures the space inside; surface area measures the outside. Prisms and cylinders multiply base by height; cones and pyramids take a third; spheres have their own formulas.`,
    ideas: [r`Cylinder: $V=\pi r^2 h$, $SA=2\pi r^2+2\pi r h$.`, r`Cone: $V=\tfrac13\pi r^2 h$, $SA=\pi r^2+\pi r\ell$. Sphere: $V=\tfrac43\pi r^3$, $SA=4\pi r^2$.`, r`Composite solids: add (or subtract) the pieces.`],
    examples: [
      { t: "Cylinder volume", body: r`A can has $r=5$ cm, $h=12$ cm.\soln $V=\pi r^2 h=\pi(25)(12)=300\pi\approx942.5$ cm³.` },
      { t: "Cylinder surface area", body: r`Surface area of the same can.\soln $SA=2\pi r^2+2\pi rh=50\pi+120\pi=170\pi\approx534.1$ cm².` },
      { t: "Cone (slant height first)", body: r`A cone has $r=6$, $h=8$. Find its surface area.\soln Slant $\ell=\sqrt{r^2+h^2}=\sqrt{36+64}=10$, then $SA=\pi r^2+\pi r\ell=36\pi+60\pi=96\pi\approx301.6$.` + r`\rtri{6}{8}{$h=8$}{$r=6$}{$\ell=10$}` },
      { t: "Sphere volume", body: r`Volume of a sphere with $r=6$.\soln $V=\tfrac43\pi(216)=288\pi\approx904.8$.` },
      { t: "Work backwards", body: r`A sphere has volume $36\pi$. Find $r$.\soln $\tfrac43\pi r^3=36\pi\Rightarrow r^3=27\Rightarrow r=3$.` },
      { t: "Composite solid", body: r`A silo: cylinder ($r=3,h=10$) topped by a cone ($r=3,h=4$).\soln $V=\pi(9)(10)+\tfrac13\pi(9)(4)=90\pi+12\pi=102\pi\approx320.4$.` },
      { t: "Rectangular prism", body: r`Volume of a $4\times3\times2$ cm box.\soln $V=lwh=4\cdot3\cdot2=24$ cm³.` },
      { t: "Cone volume", body: r`Volume of a cone with $r=3$, $h=4$.\soln $V=\tfrac13\pi(9)(4)=12\pi\approx37.7$.` },
      { t: "Cube — reverse", body: r`A cube has volume $125$ cm³. Find its side.\soln $s=\sqrt[3]{125}=5$ cm.` },
    ],
    questions: [
      { ask: r`Volume of a cylinder with $r=3$, $h=10$?` },
      { ask: r`Surface area of a cylinder with $r=2$, $h=7$?` },
      { ask: r`Volume of a sphere with $r=3$?` },
      { ask: r`A cone has $r=3$, $h=4$; find its slant height, then its surface area.`, ws: "2.6cm" },
      { ask: r`Volume of a $5\times4\times3$ cm box?` },
      { ask: r`Volume of a cone with $r=6$, $h=10$?` },
      { ask: r`Surface area of a sphere with $r=5$?` },
      { ask: r`A cube has volume $64$ cm³; find its side.` },
      { ask: r`Volume of a cylinder with $r=4$, $h=9$?` },
      { ask: r`A sphere has volume $\tfrac{32}{3}\pi$; find its radius.` },
      { ask: r`A triangular prism has base area $15$ cm² and length $8$ cm; find its volume.` },
      { ask: r`Volume of a hemisphere with $r=3$? (half a sphere)` },
      { ask: r`A grain bin is a cylinder ($r=2,h=6$) with a cone lid ($r=2,h=3$). Find the total volume.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$90\pi\approx282.7$`, r`$2\pi(4)+2\pi(2)(7)=36\pi\approx113.1$`, r`$36\pi\approx113.1$`, r`$\ell=5$; $SA=9\pi+15\pi=24\pi\approx75.4$`, r`$60$ cm³`, r`$120\pi\approx377.0$`, r`$100\pi\approx314.2$`, r`$4$ cm`, r`$144\pi\approx452.4$`, r`$r=2$`, r`$120$ cm³`, r`$\tfrac23\pi(27)=18\pi\approx56.5$`, r`$24\pi+4\pi=28\pi\approx88.0$`],
  },
  {
    code: "4.2", unit: U, title: "2-D Design & Optimization",
    intro: r`Designers trade off perimeter and area. The most area for a fixed perimeter (and the least perimeter for a fixed area) is a square.`,
    ideas: [r`Rectangle: $A=lw$, $P=2l+2w$.`, r`Max area for fixed perimeter $\Rightarrow$ a square.`, r`Composite figures: add the pieces, subtract any holes. Net $\to$ surface area: total all faces.`],
    examples: [
      { t: "Area and perimeter", body: r`A rectangle is $8$ m by $5$ m.\soln $A=8\times5=40$ m²; $P=2(8)+2(5)=26$ m.` },
      { t: "Maximum area", body: r`$40$ m of fencing for a rectangle. Maximize the area.\soln One side $x$, the other $20-x$, so $A=x(20-x)$; the parabola peaks at $x=10$, giving $10\times10=100$ m².` + r`\eplot{0}{20}{0}{120}{\addplot[exblue,very thick,domain=0:20]{x*(20-x)};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(10,100)};}` },
      { t: "Least perimeter", body: r`A garden of area $36$ m²: least fencing (whole numbers)?\soln $1{\times}36\,(P{=}74)$, $4{\times}9\,(P{=}26)$, $6{\times}6\,(P{=}24)$: the $6\times6$ square wins, $P=24$ m.` },
      { t: "Composite (subtract a hole)", body: r`A $10\times6$ m yard has a circular pond, $r=2$ m. Find the grass area.\soln $60-\pi(2)^2=60-4\pi\approx47.4$ m².` },
      { t: "Surface area from a net", body: r`A closed $4\times3\times2$ cm box.\soln $SA=2(lw+lh+wh)=2(12+8+6)=52$ cm².` },
      { t: "Maximum area", body: r`$60$ m of fencing. Maximize the rectangular area.\soln $A=x(30-x)$, peak at $x=15$: $15\times15=225$ m².` },
      { t: "Least perimeter", body: r`Area $16$ m², whole-number rectangle, least fencing?\soln $4\times4$, $P=16$ m.` },
      { t: "Composite (add pieces)", body: r`An L-shape: a $6\times4$ rectangle plus a $3\times2$ rectangle. Total area?\soln $24+6=30$ units².` },
      { t: "Net surface area", body: r`Surface area of a closed $5\times4\times3$ box.\soln $2(20+15+12)=94$ cm².` },
    ],
    questions: [
      { ask: r`Area and perimeter of a $12\times5$ rectangle?` },
      { ask: r`With $60$ m of fencing, what rectangle gives the most area?` },
      { ask: r`Whole-number rectangle of area $16$ m² with the least perimeter?` },
      { ask: r`An $8\times8$ m patio loses a $2\times3$ m planter. Paved area?` },
      { ask: r`Surface area of a closed $5\times4\times3$ box?` },
      { ask: r`With $24$ m of fencing, find the maximum rectangular area.` },
      { ask: r`A $9\times9$ m yard has a circular flowerbed, $r=3$ m. Grass area?` },
      { ask: r`Area of an L-shape: a $5\times3$ plus a $2\times2$ rectangle?` },
      { ask: r`Whole-number rectangle of area $24$ m² with the least perimeter?` },
      { ask: r`Surface area of a cube with side $4$ cm?` },
      { ask: r`A $10\times8$ rectangle has a $4\times3$ rectangle cut out. Remaining area?` },
      { ask: r`Maximum area with $100$ m of fencing?` },
      { ask: r`You have $20$ m of fencing for a pen against a wall (only 3 sides fenced). What dimensions maximize the area?`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$A=60$, $P=34$`, r`$15\times15$, $225$ m²`, r`$4\times4$, $P=16$`, r`$64-6=58$ m²`, r`$94$ cm²`, r`$6\times6=36$ m²`, r`$81-9\pi\approx52.7$ m²`, r`$15+4=19$ units²`, r`$4\times6$, $P=20$`, r`$6(16)=96$ cm²`, r`$80-12=68$`, r`$25\times25=625$ m²`, r`width $5$, length $10$ ($A=x(20-2x)$, max at $x=5$): $50$ m²`],
  },
  {
    code: "4.3", unit: U, title: "The Sine Law",
    intro: r`The sine law solves any triangle where a side is paired with its opposite angle: $\dfrac{a}{\sin A}=\dfrac{b}{\sin B}=\dfrac{c}{\sin C}$.`,
    ideas: [r`$\dfrac{a}{\sin A}=\dfrac{b}{\sin B}=\dfrac{c}{\sin C}$.`, r`Use it with a side and its opposite angle, plus one more piece.`, r`Angles sum to $180^\circ$.`],
    examples: [
      { t: "Find a side", body: r`$A=40^\circ,\ a=10,\ B=60^\circ$. Find $b$.\soln $b=\dfrac{a\sin B}{\sin A}=\dfrac{10\sin60^\circ}{\sin40^\circ}\approx13.5$.` + r`\gtri{$40^\circ$}{$60^\circ$}{$C$}{$10$}{$b$}{$c$}` },
      { t: "Find an angle", body: r`$a=8,\ A=50^\circ,\ b=6$. Find $B$.\soln $\sin B=\dfrac{b\sin A}{a}=\dfrac{6\sin50^\circ}{8}\approx0.5745$, so $B=\sin^{-1}(0.5745)\approx35.1^\circ$.` + r`\gtri{$50^\circ$}{$B$}{$C$}{$8$}{$6$}{$c$}` },
      { t: "Third angle first", body: r`$A=45^\circ,\ B=60^\circ,\ a=12$. Find $c$.\soln $C=75^\circ$; $c=\dfrac{12\sin75^\circ}{\sin45^\circ}\approx16.4$.` },
      { t: "Two angles", body: r`$A=40^\circ,\ B=75^\circ$. Find $C$.\soln $C=180^\circ-40^\circ-75^\circ=65^\circ$.` },
      { t: "Find a side", body: r`$A=30^\circ,\ a=5,\ B=80^\circ$. Find $b$.\soln $b=\dfrac{5\sin80^\circ}{\sin30^\circ}\approx9.85$.` },
      { t: "Find an angle", body: r`$a=10,\ A=70^\circ,\ b=8$. Find $B$.\soln $\sin B=\dfrac{8\sin70^\circ}{10}\approx0.7518\Rightarrow B\approx48.8^\circ$.` },
      { t: "Application", body: r`From two points $50$ m apart, the angles to a tree are $70^\circ$ and $60^\circ$ (tree angle $50^\circ$). Distance from the first point?\soln $d=\dfrac{50\sin60^\circ}{\sin50^\circ}\approx56.5$ m.` },
      { t: "Find a side", body: r`$A=60^\circ,\ a=10,\ B=40^\circ$. Find $b$.\soln $b=\dfrac{10\sin40^\circ}{\sin60^\circ}\approx7.42$.` },
      { t: "Set it up", body: r`For $A=35^\circ,\ a=9,\ b=7$, write the equation for $B$.\soln $\dfrac{\sin B}{7}=\dfrac{\sin35^\circ}{9}\Rightarrow\sin B=\dfrac{7\sin35^\circ}{9}$.` },
    ],
    questions: [
      { ask: r`$A=30^\circ,\ a=5,\ B=80^\circ$. Find $b$.`, ws: "2.2cm" },
      { ask: r`If $A=40^\circ$ and $B=75^\circ$, find $C$.` },
      { ask: r`$A=60^\circ,\ a=10,\ B=40^\circ$. Find $b$.`, ws: "2.2cm" },
      { ask: r`$a=10,\ A=70^\circ,\ b=8$. Find $B$.`, ws: "2.2cm" },
      { ask: r`$A=50^\circ,\ B=70^\circ,\ a=8$. Find $b$.`, ws: "2.2cm" },
      { ask: r`If $B=55^\circ$ and $C=65^\circ$, find $A$.` },
      { ask: r`$A=35^\circ,\ a=12,\ C=80^\circ$. Find $c$.`, ws: "2.2cm" },
      { ask: r`$a=9,\ A=40^\circ,\ b=7$. Find $B$.`, ws: "2.2cm" },
      { ask: r`When is the sine law the right tool?` },
      { ask: r`$A=25^\circ,\ a=6,\ B=100^\circ$. Find $b$.`, ws: "2.2cm" },
      { ask: r`$A=48^\circ,\ B=61^\circ,\ a=15$. Find $b$.`, ws: "2.2cm" },
      { ask: r`Find $C$ if $A=33^\circ$ and $B=92^\circ$.` },
      { ask: r`A surveyor at points $80$ m apart measures angles $65^\circ$ and $72^\circ$ to a rock; the rock angle is $43^\circ$. Find the distance from the second point to the rock.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\approx9.85$`, r`$65^\circ$`, r`$\approx7.42$`, r`$\approx48.8^\circ$`, r`$\approx9.81$`, r`$60^\circ$`, r`$\approx20.6$`, r`$\approx30.0^\circ$`, r`a side with its opposite angle`, r`$\approx13.98$`, r`$\approx17.66$`, r`$55^\circ$`, r`$\dfrac{80\sin65^\circ}{\sin43^\circ}\approx106.3$ m`],
  },
  {
    code: "4.4", unit: U, title: "The Cosine Law",
    intro: r`The cosine law solves SAS and SSS triangles: $c^2=a^2+b^2-2ab\cos C$ — Pythagoras plus a correction for the angle.`,
    ideas: [r`Find a side (SAS): $c^2=a^2+b^2-2ab\cos C$.`, r`Find an angle (SSS): $\cos C=\dfrac{a^2+b^2-c^2}{2ab}$.`, r`When $C=90^\circ$ it becomes $c^2=a^2+b^2$.`],
    examples: [
      { t: "Find a side (SAS)", body: r`$a=7,\ b=9,\ C=50^\circ$. Find $c$.\soln $c^2=49+81-2(7)(9)\cos50^\circ\approx130-80.99=49.0\Rightarrow c\approx7.0$.` + r`\gtri{$A$}{$B$}{$50^\circ$}{$7$}{$9$}{$c$}` },
      { t: "Find an angle (SSS)", body: r`$a=5,\ b=6,\ c=7$. Find $C$.\soln $\cos C=\dfrac{25+36-49}{2(5)(6)}=\dfrac{12}{60}=0.2\Rightarrow C\approx78.5^\circ$.` + r`\gtri{$A$}{$B$}{$C$}{$5$}{$6$}{$7$}` },
      { t: "Largest angle", body: r`Sides $4,5,6$; find the largest angle (opposite $6$).\soln $\cos C=\dfrac{16+25-36}{2(4)(5)}=\dfrac{5}{40}=0.125\Rightarrow C\approx82.8^\circ$.` },
      { t: "Choose the law", body: r`Given $a=8,\ c=11,\ B=35^\circ$, which law finds $b$?\soln Two sides and the angle between them (SAS): the cosine law, $b^2=8^2+11^2-2(8)(11)\cos35^\circ$.` },
      { t: "Application (two roads)", body: r`Roads leave a town at $60^\circ$; cars drive $40$ km and $30$ km. Distance apart?\soln $d^2=1600+900-2400\cos60^\circ=1300\Rightarrow d=\sqrt{1300}\approx36.1$ km.` },
      { t: "Find a side (SAS)", body: r`$a=6,\ b=8,\ C=60^\circ$. Find $c$.\soln $c^2=36+64-96(0.5)=52\Rightarrow c\approx7.21$.` },
      { t: "Find an angle (SSS)", body: r`$a=4,\ b=5,\ c=6$. Find the angle opposite $6$.\soln $\cos C=\dfrac{16+25-36}{40}=0.125\Rightarrow C\approx82.8^\circ$.` },
      { t: "Find a side (SAS)", body: r`$a=10,\ b=7,\ C=45^\circ$. Find $c$.\soln $c^2=100+49-140\cos45^\circ\approx49.0\Rightarrow c\approx7.0$.` },
      { t: "Why a correction", body: r`Why is the cosine law "Pythagoras with a correction"?\soln The $-2ab\cos C$ term is $0$ when $C=90^\circ$, leaving $c^2=a^2+b^2$.` },
    ],
    questions: [
      { ask: r`$a=6,\ b=8,\ C=60^\circ$. Find $c$.`, ws: "2.4cm" },
      { ask: r`$a=4,\ b=5,\ c=6$. Find the angle opposite $c$.`, ws: "2.4cm" },
      { ask: r`Which law: you know all three sides and want an angle?` },
      { ask: r`$a=10,\ b=7,\ C=45^\circ$. Find $c$.`, ws: "2.4cm" },
      { ask: r`Sides $5,6,7$: find the largest angle.`, ws: "2.4cm" },
      { ask: r`$a=9,\ b=12,\ C=80^\circ$. Find $c$.`, ws: "2.4cm" },
      { ask: r`$a=7,\ b=8,\ c=9$. Find the angle opposite $9$.`, ws: "2.4cm" },
      { ask: r`Which law: SAS (two sides + included angle)?` },
      { ask: r`$a=5,\ b=5,\ C=90^\circ$. Find $c$ (check against Pythagoras).`, ws: "2.4cm" },
      { ask: r`$a=11,\ b=13,\ C=72^\circ$. Find $c$.`, ws: "2.4cm" },
      { ask: r`$a=6,\ b=7,\ c=8$. Find the angle opposite $6$.`, ws: "2.4cm" },
      { ask: r`Two planes leave an airport at $110^\circ$; they fly $200$ km and $250$ km. How far apart?`, ws: "2.6cm" },
      { ask: r`A triangular lot has sides $40$ m, $55$ m, $70$ m. Find its largest interior angle.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$c^2=52\Rightarrow\approx7.21$`, r`$\approx82.8^\circ$`, r`cosine law (SSS)`, r`$\approx7.0$`, r`$\approx78.5^\circ$`, r`$\approx13.7$`, r`$\approx73.4^\circ$`, r`cosine law`, r`$c=\sqrt{50}\approx7.07$ ($=\sqrt{a^2+b^2}$)`, r`$\approx14.3$`, r`$\approx46.6^\circ$`, r`$\approx369$ km`, r`$\cos C=\dfrac{40^2+55^2-70^2}{2(40)(55)}\approx-0.073\Rightarrow C\approx94.2^\circ$`],
  },
];
