// MAP4C Unit 1 worksheets — Mathematical Models.
// Full \soln solutions; 9 worked examples + 13 questions + answer key each.
const r = String.raw;
const U = "1: Mathematical Models";

export default [
  {
    code: "1.1", unit: U, title: "Exponent Laws & Rational Exponents",
    intro: r`Same-base powers combine by adding, subtracting, or multiplying exponents. A negative exponent is a reciprocal ($a^{-n}=\tfrac{1}{a^n}$); a rational exponent is a root ($a^{m/n}=\sqrt[n]{a^m}$).`,
    ideas: [r`Product/quotient/power laws (same base).`, r`$a^0=1$, $a^{-n}=\dfrac{1}{a^n}$.`, r`$a^{m/n}=\left(\sqrt[n]{a}\right)^m$ — root first.`],
    examples: [
      { t: "Combine like bases", body: r`Simplify $\dfrac{x^5\cdot x^2}{x^3}$.\soln $\dfrac{x^7}{x^3}=x^4$.` },
      { t: "Power of a product", body: r`Simplify $(2x^3)^4\cdot x^{-5}$.\soln $16x^{12}\cdot x^{-5}=16x^7$.` },
      { t: "Evaluate a rational power", body: r`Evaluate $27^{2/3}$.\soln $(\sqrt[3]{27})^2=3^2=9$.` },
      { t: "Negative rational power", body: r`Evaluate $16^{-3/4}$.\soln $\dfrac{1}{(\sqrt[4]{16})^3}=\dfrac{1}{2^3}=\dfrac18$.` },
      { t: "Negative exponents, variables", body: r`Simplify with positive exponents: $(4x^{-2}y^5)^{-1}$.\soln $4^{-1}x^2y^{-5}=\dfrac{x^2}{4y^5}$.` },
      { t: "Fifth root power", body: r`Evaluate $32^{3/5}$.\soln $(\sqrt[5]{32})^3=2^3=8$.` },
      { t: "Quotient with variables", body: r`Simplify $\dfrac{6a^5b^2}{2a^2b^5}$.\soln $3a^{3}b^{-3}=\dfrac{3a^3}{b^3}$.` },
      { t: "A growth factor", body: r`Write $(1.05)^2\cdot(1.05)^3$ as one power and state what it models.\soln $(1.05)^5$ — five years of $5\%$ annual growth.` },
      { t: "Mixed evaluation", body: r`Evaluate $8^{2/3}\cdot 9^{-1/2}$.\soln $4\cdot\tfrac13=\tfrac43$.` },
    ],
    questions: [
      { ask: r`Simplify $(3x^4)^2$.` },
      { ask: r`Evaluate $25^{3/2}$.` },
      { ask: r`Simplify $\dfrac{a^7}{a^3}$.` },
      { ask: r`Evaluate $16^{-1/2}$.` },
      { ask: r`Simplify $(2a^2b)^3$.` },
      { ask: r`Evaluate $81^{3/4}$.` },
      { ask: r`Evaluate $\left(\tfrac18\right)^{-2/3}$.` },
      { ask: r`Simplify $(x^{1/3})^6$.` },
      { ask: r`Evaluate $\left(\tfrac{8}{27}\right)^{-2/3}$.` },
      { ask: r`Simplify $(2x^3)^2(3xy^2)$.` },
      { ask: r`Evaluate $32^{-2/5}$.` },
      { ask: r`Simplify $\dfrac{(2a^2b^{-1})^3}{4a^{-1}b^2}$ with positive exponents.`, challenge: true, ws: "3cm" },
      { ask: r`Evaluate $100^{1/2}\cdot 27^{1/3}$.` },
    ],
    answers: [r`$9x^8$`, r`$125$`, r`$a^4$`, r`$\tfrac14$`, r`$8a^6b^3$`, r`$27$`, r`$4$`, r`$x^2$`, r`$\tfrac94$`, r`$12x^7y^2$`, r`$\tfrac14$`, r`$\dfrac{2a^7}{b^5}$`, r`$30$`],
  },
  {
    code: "1.2", unit: U, title: "Solving Exponential Equations by Common Bases",
    intro: r`If both sides can be written as powers of the same base, the exponents must be equal. Watch for hidden powers: $8=2^3$, $27=3^3$, $\tfrac14=2^{-2}$.`,
    ideas: [r`Rewrite each side to a common base.`, r`Equate exponents and solve.`, r`Distribute a power over an exponent expression.`],
    examples: [
      { t: "Single power", body: r`Solve $2^{x}=32$.\soln $2^x=2^5\Rightarrow x=5$.` },
      { t: "Rewrite one side", body: r`Solve $9^{x}=27$.\soln $3^{2x}=3^3\Rightarrow x=\tfrac32$.` },
      { t: "Exponent expression", body: r`Solve $8^{\,x-1}=16$.\soln $2^{3(x-1)}=2^4\Rightarrow 3x-3=4\Rightarrow x=\tfrac73$.` },
      { t: "Fractional base", body: r`Solve $\left(\tfrac14\right)^{x}=8$.\soln $2^{-2x}=2^3\Rightarrow x=-\tfrac32$.` },
      { t: "Powers both sides", body: r`Solve $4^{\,x+1}=8^{\,x-1}$.\soln $2^{2x+2}=2^{3x-3}\Rightarrow 2x+2=3x-3\Rightarrow x=5$.` },
      { t: "Base 5", body: r`Solve $25^{x}=125$.\soln $5^{2x}=5^3\Rightarrow x=\tfrac32$.` },
      { t: "Negative solution", body: r`Solve $\left(\tfrac19\right)^{x}=27$.\soln $3^{-2x}=3^3\Rightarrow x=-\tfrac32$.` },
      { t: "Coefficient in exponent", body: r`Solve $2^{3x}=32$.\soln $2^{3x}=2^5\Rightarrow x=\tfrac53$.` },
      { t: "Both sides powers", body: r`Solve $27^{\,x-1}=9^{\,2x+1}$.\soln $3^{3x-3}=3^{4x+2}\Rightarrow 3x-3=4x+2\Rightarrow x=-5$.` },
    ],
    questions: [
      { ask: r`Solve $3^{x}=81$.` },
      { ask: r`Solve $2^{x}=64$.` },
      { ask: r`Solve $9^{x}=27$.` },
      { ask: r`Solve $\left(\tfrac12\right)^{x}=16$.` },
      { ask: r`Solve $4^{\,x-1}=64$.` },
      { ask: r`Solve $25^{x}=5$.` },
      { ask: r`Solve $8^{x}=32$.` },
      { ask: r`Solve $\left(\tfrac13\right)^{x}=81$.` },
      { ask: r`Solve $2^{2x}=128$.` },
      { ask: r`Solve $16^{x}=8$.` },
      { ask: r`Solve $4^{\,x+1}=16^{\,x}$.` },
      { ask: r`Solve $27^{x}=9$.` },
      { ask: r`Solve $8^{\,x+1}=4^{\,2x-1}$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$x=4$`, r`$x=6$`, r`$x=\tfrac32$`, r`$x=-4$`, r`$x=4$`, r`$x=\tfrac12$`, r`$x=\tfrac53$`, r`$x=-4$`, r`$x=\tfrac72$`, r`$x=\tfrac34$`, r`$2x+2=4x\Rightarrow x=1$`, r`$x=\tfrac23$`, r`$3x+3=4x-2\Rightarrow x=5$`],
  },
  {
    code: "1.3", unit: U, title: "Solving Exponential Equations Graphically",
    intro: r`When no common base works, solve $b^{x}=k$ with a graph or table: the solution is where $y=b^{x}$ reaches $k$. Bracket it between two $x$-values, then zoom in.`,
    ideas: [r`Graph $y=b^x$ and $y=k$; read the intersection.`, r`Trap the solution, then refine with a table.`, r`Report an estimate to the required decimals.`],
    examples: [
      { t: "Read a clean solution", body: r`Use $y=2^{x}$ to solve $2^{x}=8$.\soln The curve reaches $8$ at $x=3$.` },
      { t: "Bracket a solution", body: r`Between which integers is the solution of $3^{x}=5$?\soln $3^1=3$, $3^2=9$, so $1<x<2$.` },
      { t: "Zoom in", body: r`Estimate the solution of $3^{x}=5$ to one decimal.\soln $3^{1.4}\approx4.66$, $3^{1.5}\approx5.20$, so $x\approx1.5$ (closer to $1.46$).` },
      { t: "Interest question", body: r`When does $1.05^{x}=1.276$?\soln $1.05^{5}\approx1.276$, so $x=5$ years.` },
      { t: "Decay to half", body: r`A drug follows $R=0.8^{t}$. Estimate when half remains, $0.8^{t}=0.5$.\soln $0.8^{3}\approx0.512$, $0.8^{4}\approx0.410$; $0.8^{3.1}\approx0.50$, so $t\approx3.1$ h.` },
      { t: "Two curves", body: r`$y=2^{x}$ and $y=3x+4$. Where are they equal for $x>0$?\soln At $x=4$: $2^4=16$ and $3(4)+4=16$; equal at $x=4$.` },
      { t: "Doubling time", body: r`When does $1.08^{x}=2$?\soln $1.08^{9}\approx2.0$, so about $9$ years.` },
      { t: "Estimate to a decimal", body: r`Estimate the solution of $2^{x}=10$.\soln $2^3=8$, $2^4=16$; $2^{3.3}\approx9.85$, so $x\approx3.3$.` },
      { t: "Growth target", body: r`When does $200(1.06)^{t}=1000$? (So $1.06^{t}=5$.)\soln $1.06^{27}\approx4.82$, $1.06^{28}\approx5.11$, so $t\approx27.6$ years.` },
    ],
    questions: [
      { ask: r`Use $y=2^{x}$ to solve $2^{x}=16$.` },
      { ask: r`Between which two integers is the solution of $2^{x}=20$?` },
      { ask: r`Between which two integers is the solution of $3^{x}=40$?` },
      { ask: r`Estimate the solution of $3^{x}=20$ to one decimal.` },
      { ask: r`When does $1.05^{x}=1.216$ (nearest year)?` },
      { ask: r`Estimate when $0.9^{t}=0.5$ (a $10\%$/step decay).` },
      { ask: r`Solve $10^{x}=1000$.` },
      { ask: r`Between which integers is the solution of $5^{x}=100$?` },
      { ask: r`When does $1.04^{t}=2$ (nearest year)?` },
      { ask: r`Estimate the solution of $2^{x}=50$ to one decimal.` },
      { ask: r`A $\$500$ deposit grows by $1.06^{t}$. When does it reach $\$800$? ($1.06^{t}=1.6$.)` },
      { ask: r`Solve $4^{x}=64$ (a clean case).` },
      { ask: r`Estimate when a $\$1000$ investment at $6\%$/yr triples: $1.06^{t}=3$.`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`$x=4$`, r`between $4$ and $5$`, r`between $3$ and $4$`, r`$x\approx2.7$`, r`about $4$ years`, r`about $6.6$ steps`, r`$x=3$`, r`between $2$ and $3$`, r`about $18$ years`, r`$x\approx5.6$`, r`about $8$ years ($1.06^{8}\approx1.59$)`, r`$x=3$`, r`about $18.9$ years ($1.06^{19}\approx3.03$)`],
  },
  {
    code: "1.4", unit: U, title: "Exponential Growth & Decay Applications",
    intro: r`Model constant-percentage change with $A=A_0\,b^{t}$: growth $b=1+r$, decay $b=1-r$. Half-life uses $\left(\tfrac12\right)^{t/h}$; compound interest is $A=P(1+i)^n$.`,
    ideas: [r`Growth/decay factor $b=1\pm r$.`, r`Half-life / doubling models.`, r`Compound interest $A=P(1+i)^n$.`],
    examples: [
      { t: "Population growth", body: r`A town of $5000$ grows $3\%$/yr. Find the population after $10$ years.\soln $5000(1.03)^{10}\approx6720$.` },
      { t: "Half-life", body: r`An $80$ mg sample has a $6$-hour half-life. Find the amount after $18$ h.\soln $80\left(\tfrac12\right)^{18/6}=80\left(\tfrac12\right)^{3}=10$ mg.` },
      { t: "Depreciation", body: r`A $\$30\,000$ car loses $12\%$/yr. Value after $4$ years?\soln $30\,000(0.88)^{4}\approx\$17\,990$.` },
      { t: "Compound interest", body: r`$\$2000$ at $4\%$/yr compounded annually, $5$ years.\soln $2000(1.04)^{5}\approx\$2433.31$.` },
      { t: "Doubling time (table)", body: r`At $6\%$/yr, when does an investment double?\soln $1.06^{11}\approx1.90$, $1.06^{12}\approx2.01$; about $11.9$ years.` },
      { t: "Growth value", body: r`$800(1.02)^{t}$; find the amount after $15$ years.\soln $\approx1077$.` },
      { t: "Half-life count", body: r`$60$ mg, half-life $4$ h; amount after $12$ h.\soln $60\left(\tfrac12\right)^{3}=7.5$ mg.` },
      { t: "Decay to a fraction", body: r`$A=A_0(0.85)^{t}$; when is $25\%$ left?\soln $0.85^{8}\approx0.272$, $0.85^{9}\approx0.232$; about $8.5$ years.` },
      { t: "Interest amount", body: r`$\$1500$ at $5\%$/yr, $4$ years.\soln $1500(1.05)^{4}\approx\$1823.26$.` },
    ],
    questions: [
      { ask: r`$\$1000$ at $5\%$/yr compounded annually for $3$ years — find the amount.` },
      { ask: r`A $40$ mg sample, half-life $5$ h — amount after $15$ h?` },
      { ask: r`A population $600(1.03)^{t}$ — find it after $10$ years.` },
      { ask: r`A bacteria count of $200$ doubles every $3$ h — count after $9$ h?` },
      { ask: r`\$5000 at $6\%$/yr for $2$ years — amount?` },
      { ask: r`A $100$ mg sample, half-life $3$ h — amount after $9$ h?` },
      { ask: r`A \$20\,000 machine depreciates $10\%$/yr — value after $3$ years?` },
      { ask: r`A colony $50(1.1)^{t}$ — value after $5$ h?` },
      { ask: r`A $200$ mg dose, half-life $8$ h — amount after $24$ h?` },
      { ask: r`\$3000 at $7\%$/yr for $5$ years — amount?` },
      { ask: r`At $8\%$/yr, estimate the doubling time (table).` },
      { ask: r`A substance decays $15\%$/yr — estimate when $50\%$ is left.` },
      { ask: r`Write the model for a $\$2000$ investment at $6\%$/yr compounded monthly, and find its value after $2$ years.`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`$1000(1.05)^3\approx\$1157.63$`, r`$40\left(\tfrac12\right)^3=5$ mg`, r`$600(1.03)^{10}\approx807$`, r`$200\cdot2^{3}=1600$`, r`$5000(1.06)^2\approx\$5618$`, r`$100\left(\tfrac12\right)^3=12.5$ mg`, r`$20000(0.9)^3\approx\$14\,580$`, r`$50(1.1)^5\approx80.5$`, r`$200\left(\tfrac12\right)^3=25$ mg`, r`$3000(1.07)^5\approx\$4207.66$`, r`about $9.0$ years`, r`about $4.3$ years ($0.85^{4.3}\approx0.50$)`, r`$A=2000(1.005)^{n}$; at $n=24$: $\approx\$2254.32$`],
  },
  {
    code: "1.5", unit: U, title: "Interpreting Graphs & Describing Trends",
    intro: r`Read a graph to describe how two quantities relate, identify the trend, and make predictions — always with correct units and stated assumptions.`,
    ideas: [r`Describe direction: rise, fall, level, reverse.`, r`Trend $=$ overall direction; extrapolate to predict.`, r`Note maxima, minima, and intercepts.`],
    examples: [
      { t: "Distance–time", body: r`A distance–time graph is a straight line from $(0,0)$ to $(2,120)$ (km, h). Describe it.\soln Constant speed; rate $=\tfrac{120}{2}=60$ km/h.` },
      { t: "Levelling off", body: r`A cooling graph falls fast then flattens. Describe the trend.\soln Decreasing, then levelling toward room temperature (exponential decay to a limit).` },
      { t: "Linear prediction", body: r`Sales (\$000) are $20,24,28,32$ for years $1$–$4$. Predict year $6$.\soln Rises \$4000/yr (linear): year $5\to36$, year $6\to40$; assuming the trend continues.` },
      { t: "Reading a maximum", body: r`A profit graph peaks at $(50,900)$. Interpret the peak.\soln Maximum profit \$900 at $50$ units; profit falls beyond that.` },
      { t: "Exponential trend", body: r`Users are $10,20,40,80$ over four months. Predict month $5$.\soln Doubling (exponential): $160$.` },
      { t: "Rate direction", body: r`A temperature graph falls and flattens. Is the size of the rate increasing or decreasing?\soln Decreasing — the drop slows.` },
      { t: "Cautious extrapolation", body: r`A world-record-time graph trends down but flattens. Why is a $2100$ prediction risky?\soln Improvements shrink; extending far ahead may give impossible times.` },
      { t: "Intercept meaning", body: r`A cost graph crosses the vertical axis at \$20. What does that represent?\soln A fixed starting cost (base fee) when usage is $0$.` },
      { t: "Compare two graphs", body: r`Graph A is a straight line; graph B curves upward. Compare their trends.\soln A: constant rate; B: increasing rate (accelerating).` },
    ],
    questions: [
      { ask: r`A graph rises then stays flat. Describe the trend.` },
      { ask: r`A distance–time line goes $(0,0)$ to $(4,200)$. Find the speed with units.` },
      { ask: r`Sales are $10,20,40,80$ over four years. Predict year $5$ and name the pattern.` },
      { ask: r`A graph falls and flattens. Is the size of the rate of change increasing or decreasing?` },
      { ask: r`A profit graph peaks at $(30,450)$. What does the peak mean?` },
      { ask: r`Sales rise by \$5000 each year from \$25\,000. Predict after $3$ more years.` },
      { ask: r`Why should a prediction far beyond the data be treated with caution?` },
      { ask: r`A cost graph crosses the vertical axis at \$15. Interpret it.` },
      { ask: r`A population graph bends toward a ceiling. What does the ceiling suggest?` },
      { ask: r`Data $3,6,12,24$. Linear or exponential trend?` },
      { ask: r`A graph is horizontal at $y=50$. What is its rate of change?` },
      { ask: r`Name two things a good graph description should include.` },
      { ask: r`App users climb steeply, then bend toward $1\,000\,000$. Predict cautiously and explain why linear extrapolation of the steep part fails.`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`increases, then constant`, r`$200/4=50$ km/h`, r`$160$, exponential (doubling)`, r`decreasing`, r`maximum value $450$ at $30$`, r`$25\,000+3(5000)=\$40\,000$`, r`the trend may not continue (limits, new factors)`, r`a fixed starting cost of \$15`, r`a saturation limit (maximum size)`, r`exponential (constant ratio $2$)`, r`zero`, r`direction/trend, quantities with units, special points`, r`growth slows near the ceiling, so linear extrapolation over-predicts; approaches the $1\,000\,000$ limit`],
  },
  {
    code: "1.6", unit: U, title: "Rate of Change from Graphs & Tables",
    intro: r`Rate of change $=\dfrac{\text{change in output}}{\text{change in input}}$ — the slope, with units \emph{output per input}. Equal first differences mean a constant rate; a curve means a changing rate.`,
    ideas: [r`Rate $=\dfrac{\Delta\text{output}}{\Delta\text{input}}$, with units.`, r`Constant (line) vs changing (curve).`, r`Zero rate $=$ horizontal graph.`],
    examples: [
      { t: "Rate from two points", body: r`A car travels $90$ km in $1.5$ h at steady speed. Find the rate.\soln $\dfrac{90}{1.5}=60$ km/h.` },
      { t: "Units of a rate", body: r`Earnings go \$0 to \$180 over $12$ h. State the rate.\soln $\dfrac{180}{12}=\$15$/h.` },
      { t: "Constant (table)", body: r`Outputs $2,5,8,11$ at $x=0,1,2,3$. Constant rate?\soln First differences $3,3,3$ — constant rate $3$ (linear).` },
      { t: "Changing (table)", body: r`Outputs $3,6,12,24$. Describe the rate.\soln Differences $3,6,12$ — changing; constant ratio $2$ (exponential).` },
      { t: "Compare graphs", body: r`Car A's graph is a line; car B's curves up. Compare rates.\soln A constant speed; B increasing speed (accelerating).` },
      { t: "Fill rate", body: r`A tank fills $40$ L in $8$ min. Find the rate.\soln $40/8=5$ L/min.` },
      { t: "Quadratic differences", body: r`Outputs $1,4,9,16$. Constant rate?\soln Differences $3,5,7$ — changing (quadratic).` },
      { t: "Zero rate", body: r`A graph sits at $y=25$ for all $x$. Rate of change?\soln Zero — no change in output.` },
      { t: "Interpret intercept", body: r`A plan costs \$20 plus \$0.10/min. Rate and meaning of \$20?\soln Rate \$0.10/min; \$20 is the fixed base fee.` },
    ],
    questions: [
      { ask: r`A tank fills $60$ L in $10$ min. Rate with units?` },
      { ask: r`Outputs $4,7,10,13$ at $x=0,1,2,3$. Constant or changing?` },
      { ask: r`Outputs $1,4,9,16$. Constant or changing rate?` },
      { ask: r`A horizontal graph at $y=30$. Rate of change?` },
      { ask: r`A car goes $150$ km in $2.5$ h. Speed with units?` },
      { ask: r`Outputs $2,6,18,54$. Constant, changing (quadratic), or exponential?` },
      { ask: r`Earnings \$0 to \$225 over $15$ h. Rate?` },
      { ask: r`Outputs $5,9,13,17$. Rate of change?` },
      { ask: r`A curve steepens as $x$ increases. Constant or changing rate?` },
      { ask: r`A phone plan: \$30 base plus \$0.05/min. What is the rate of change of cost?` },
      { ask: r`In that plan, what does the \$30 represent?` },
      { ask: r`Outputs $0,3,8,15$. Constant, quadratic, or exponential rate?` },
      { ask: r`A pool drains from $200$ L to $50$ L in $30$ min. Find the rate of change (with sign and units).`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$6$ L/min`, r`constant (linear)`, r`changing (quadratic)`, r`zero`, r`$60$ km/h`, r`exponential (ratio $3$)`, r`\$15/h`, r`constant, $4$ per step`, r`changing`, r`\$0.05/min`, r`a fixed base fee`, r`changing (quadratic; second differences $2$)`, r`$\dfrac{50-200}{30}=-5$ L/min`],
  },
  {
    code: "1.7", unit: U, title: "Choosing a Model: Linear, Quadratic, or Exponential",
    intro: r`Constant first differences signal a linear model; constant second differences a quadratic; a constant ratio an exponential. A constant \emph{amount} of change is linear; a constant \emph{percentage} is exponential.`,
    ideas: [r`Linear: constant first difference.`, r`Quadratic: constant second difference.`, r`Exponential: constant ratio.`],
    examples: [
      { t: "Spot linear", body: r`$y=7,10,13,16$ at $x=0,1,2,3$. Which model?\soln First differences $3$ — linear, $y=3x+7$.` },
      { t: "Spot exponential", body: r`$y=5,10,20,40$. Which model?\soln Ratio $2$ — exponential, $y=5\cdot2^{x}$.` },
      { t: "Spot quadratic", body: r`$y=1,4,9,16$. Which model?\soln First differences $3,5,7$; second differences $2$ — quadratic ($y=x^2$).` },
      { t: "From a description", body: r`Account A adds \$100/month; account B grows $4\%$/month. Which is which?\soln A linear (constant amount), B exponential (constant percent).` },
      { t: "Build the model", body: r`A colony is $3$ at $x=0$ and triples each step. Write the model; predict $x=4$.\soln $y=3\cdot3^{x}$; $y=3\cdot81=243$.` },
      { t: "Decay model", body: r`Data start at $100$ and drop $20\%$ each step. Write the model.\soln Ratio $0.8$: $y=100(0.8)^{x}$.` },
      { t: "Linear model", body: r`$y=2,6,10,14$. Write the model.\soln First differences $4$: $y=4x+2$.` },
      { t: "Quadratic build", body: r`$y=5,8,13,20,29$. Identify and give the equation.\soln Second differences $2$ — quadratic; $y=x^2+2x+5$.` },
      { t: "Compare growth", body: r`A adds \$50/week from \$0; B doubles from \$1/week. Which is larger after $10$ weeks?\soln A $=\$500$; B $=2^{10}=\$1024$ — B (exponential) wins.` },
    ],
    questions: [
      { ask: r`$y=2,6,10,14$ at $x=0,1,2,3$. Which model?` },
      { ask: r`$y=2,6,18,54$. Which model?` },
      { ask: r`$y=0,3,8,15$. Linear, quadratic, or exponential?` },
      { ask: r`Write the model: starts at $100$, drops $20\%$ each step.` },
      { ask: r`$y=1,3,9,27$. Which model, and its equation?` },
      { ask: r`$y=3,7,11,15$. Model and equation?` },
      { ask: r`A savings account grows $5\%$/month. Linear or exponential?` },
      { ask: r`A phone plan adds \$40/month. Linear or exponential?` },
      { ask: r`$y=1,4,9,16,25$. Model?` },
      { ask: r`Write the model: starts at $2$, triples each step.` },
      { ask: r`Constant amount per step vs constant percent per step — which is which?` },
      { ask: r`$y=4,4.8,5.76,6.912$. Linear or exponential? (Give the ratio.)` },
      { ask: r`$y=6,9,14,21,30$. Identify the model and give its equation.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`linear, $y=4x+2$`, r`exponential, $y=2\cdot3^{x}$`, r`quadratic (2nd diff $2$)`, r`$y=100(0.8)^{x}$`, r`exponential, $y=3^{x}$`, r`linear, $y=4x+3$`, r`exponential`, r`linear`, r`quadratic, $y=(x+1)^2$`, r`$y=2\cdot3^{x}$`, r`amount $=$ linear; percent $=$ exponential`, r`exponential, ratio $1.2$`, r`quadratic; $y=x^2+2x+6$`],
  },
  {
    code: "1.8", unit: U, title: "Powers, Roots & Working with Formulas",
    intro: r`Undo a power with a root: $x^{n}=a\Rightarrow x=\sqrt[n]{a}$ (even $n$ gives $\pm$). Rearrange formulas by undoing operations in reverse; keep only positive roots for measurements.`,
    ideas: [r`$x^{n}=a\Rightarrow x=\sqrt[n]{a}$; even $n$ gives $\pm$.`, r`Isolate, then take the matching root.`, r`Physical lengths use the positive root.`],
    examples: [
      { t: "Cube root", body: r`Solve $x^{3}=64$.\soln $x=\sqrt[3]{64}=4$.` },
      { t: "Even power", body: r`Solve $x^{2}=49$.\soln $x=\pm7$.` },
      { t: "Radius of a sphere", body: r`$V=\tfrac43\pi r^{3}=1000$. Find $r$.\soln $r^3=\dfrac{3(1000)}{4\pi}\approx238.7$, so $r\approx6.2$ cm.` },
      { t: "Rearrange for a radius", body: r`Solve $A=\pi r^{2}$ for $r$.\soln $r=\sqrt{\dfrac{A}{\pi}}$ (positive).` },
      { t: "Formula as a relation", body: r`In $A=P(1+i)^n$ with $P,i$ fixed, what relation is $A$ vs $n$?\soln Exponential (the variable is in the exponent).` },
      { t: "Side of a cube", body: r`$V=s^3=216$. Find $s$.\soln $s=\sqrt[3]{216}=6$.` },
      { t: "Rearrange a box", body: r`Solve $V=lwh$ for $h$.\soln $h=\dfrac{V}{lw}$.` },
      { t: "Square root of an area", body: r`A square has area $200$ cm$^2$. Find its side (1 dp).\soln $s=\sqrt{200}\approx14.1$ cm.` },
      { t: "Fifth power", body: r`Solve $x^{5}=32$.\soln $x=\sqrt[5]{32}=2$.` },
    ],
    questions: [
      { ask: r`Solve $x^{3}=125$.` },
      { ask: r`Solve $x^{2}=81$.` },
      { ask: r`A cube has volume $27$ cm$^3$. Find the side.` },
      { ask: r`Solve $V=lwh$ for $l$.` },
      { ask: r`A square has area $144$ cm$^2$. Find its side.` },
      { ask: r`Solve $x^{2}=100$.` },
      { ask: r`Solve $A=s^2$ for $s$ (positive).` },
      { ask: r`Solve $x^{3}=8$.` },
      { ask: r`A sphere has $V=\tfrac43\pi r^3=113.1$. Find $r$.` },
      { ask: r`Solve $C=2\pi r$ for $r$.` },
      { ask: r`Solve $x^{4}=16$.` },
      { ask: r`In $A=P(1+i)^n$ with $i,n$ fixed, what relation is $A$ vs $P$?` },
      { ask: r`A square patio has area $500$ cm$^2$. Find its side to one decimal, and explain why only the positive root is used.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$x=5$`, r`$x=\pm9$`, r`$3$ cm`, r`$l=\dfrac{V}{wh}$`, r`$12$ cm`, r`$x=\pm10$`, r`$s=\sqrt{A}$`, r`$x=2$`, r`$r=3$`, r`$r=\dfrac{C}{2\pi}$`, r`$x=\pm2$`, r`linear`, r`$s=\sqrt{500}\approx22.4$ cm; a length cannot be negative`],
  },
];
