// MAP4C Unit 3 worksheets — Geometry & Trigonometry.
// Full \soln solutions; 9 worked examples + 13 questions + answer key each.
const r = String.raw;
const U = "3: Geometry & Trigonometry";

export default [
  {
    code: "3.1", unit: U, title: "Unit Conversion (Metric & Imperial)",
    intro: r`Metric units scale by tens ($1$ m $=100$ cm, $1$ km $=1000$ m). Bridge to imperial with $1$ in $=2.54$ cm, $1$ ft $\approx0.305$ m, $1$ mi $\approx1.609$ km. Multiply by a ratio equal to $1$ so the old unit cancels.`,
    ideas: [r`Metric conversions by powers of ten.`, r`Metric $\leftrightarrow$ imperial bridges.`, r`Cancel the unwanted unit.`],
    examples: [
      { t: "Within metric", body: r`Convert $250$ cm to metres.\soln $250\times\dfrac{1\text{ m}}{100\text{ cm}}=2.5$ m.` },
      { t: "km to m", body: r`Convert $5$ km to metres.\soln $5\times1000=5000$ m.` },
      { t: "Inches to cm", body: r`Convert $12$ in to cm.\soln $12\times2.54=30.48$ cm.` },
      { t: "Feet to metres", body: r`Convert $10$ ft to metres.\soln $10\times0.3048\approx3.05$ m.` },
      { t: "km to miles", body: r`Convert $100$ km to miles.\soln $\dfrac{100}{1.609}\approx62.15$ miles.` },
      { t: "Miles to km", body: r`Convert $3$ miles to km.\soln $3\times1.609\approx4.83$ km.` },
      { t: "Feet to cm", body: r`Convert $6$ ft to cm.\soln $6\times30.48=182.88$ cm.` },
      { t: "Gallons to litres", body: r`Convert $10$ US gallons to litres.\soln $10\times3.785=37.85$ L.` },
      { t: "Kilograms to pounds", body: r`Convert $5$ kg to pounds.\soln $5\times2.205\approx11.03$ lb.` },
    ],
    questions: [
      { ask: r`Convert $3.5$ m to cm.` },
      { ask: r`Convert $8$ ft to inches.` },
      { ask: r`Convert $20$ in to cm.` },
      { ask: r`Convert $2$ miles to km.` },
      { ask: r`Convert $15$ in to cm.` },
      { ask: r`Convert $50$ km to miles.` },
      { ask: r`Convert $4$ km to metres.` },
      { ask: r`Convert $3$ kg to pounds (to 2 decimals).` },
      { ask: r`Convert $2$ US gallons to litres.` },
      { ask: r`Convert $250$ cm to metres.` },
      { ask: r`Convert $6$ ft to metres (to 2 decimals).` },
      { ask: r`Convert $100$ cm to inches (to 2 decimals).` },
      { ask: r`A room is $12$ ft long. How many metres is that, to 2 decimals?`, challenge: true, ws: "2.6cm" },
    ],
    answers: [r`$350$ cm`, r`$96$ in`, r`$50.8$ cm`, r`$\approx3.22$ km`, r`$38.1$ cm`, r`$\approx31.08$ mi`, r`$4000$ m`, r`$\approx6.62$ lb`, r`$7.57$ L`, r`$2.5$ m`, r`$\approx1.83$ m`, r`$100/2.54\approx39.37$ in`, r`$12\times0.3048\approx3.66$ m`],
  },
  {
    code: "3.2", unit: U, title: "Areas of Composite Shapes",
    intro: r`Decompose a region into rectangles ($lw$), triangles ($\tfrac12bh$), and circles ($\pi r^2$), then add the pieces or subtract a cut-out. A semicircle is $\tfrac12\pi r^2$.`,
    ideas: [r`Rectangle $lw$, triangle $\tfrac12bh$, circle $\pi r^2$.`, r`Add attached parts; subtract holes.`, r`Use the radius (half the diameter).`],
    examples: [
      { t: "Rectangle", body: r`Area of an $8\times5$ rectangle.\soln $40$.` },
      { t: "Triangle", body: r`Area of a triangle, base $10$, height $6$.\soln $\tfrac12(10)(6)=30$.` },
      { t: "Circle", body: r`Area of a circle of radius $4$.\soln $16\pi\approx50.27$.` },
      { t: "L-shape (subtract)", body: r`A $10\times8$ rectangle with a $4\times3$ corner removed.\soln $80-12=68$.` },
      { t: "Rectangle + semicircle", body: r`A $12\times6$ rectangle capped by a semicircle of radius $3$.\soln $72+\tfrac12\pi(3)^2\approx72+14.14=86.14$.` },
      { t: "Larger triangle", body: r`Area of a triangle, base $14$, height $9$.\soln $\tfrac12(14)(9)=63$.` },
      { t: "Ring (annulus)", body: r`Area between circles of radius $8$ and $5$.\soln $\pi(64-25)=39\pi\approx122.52$.` },
      { t: "Circle, radius 6", body: r`Area of a circle of radius $6$.\soln $36\pi\approx113.1$.` },
      { t: "Rectangle + semicircle end", body: r`A $14\times8$ rectangle with a semicircle of radius $4$ on one end.\soln $112+\tfrac12\pi(4)^2\approx112+25.13=137.13$.` },
    ],
    questions: [
      { ask: r`Area of a $15\times9$ rectangle.` },
      { ask: r`Area of a triangle, base $12$, height $7$.` },
      { ask: r`Area of a circle of radius $5$ (2 decimals).` },
      { ask: r`Area between circles of radius $6$ and $4$ (2 decimals).` },
      { ask: r`L-shape: $12\times10$ with a $5\times4$ corner removed.` },
      { ask: r`Area of a circle of radius $6$ (2 decimals).` },
      { ask: r`A $10\times6$ rectangle with a semicircle of radius $3$ on one end (2 decimals).` },
      { ask: r`Area of a triangle, base $14$, height $9$.` },
      { ask: r`Area of a trapezoid, parallel sides $6$ and $10$, height $5$.` },
      { ask: r`Area of a $20\times12$ rectangle with two semicircles of radius $6$ on the short ends (2 decimals).` },
      { ask: r`Area of a semicircle of radius $8$ (2 decimals).` },
      { ask: r`Area of a square of side $7$ with an inscribed circle removed (2 decimals).` },
      { ask: r`A patio is a $14\times8$ rectangle with a semicircle of radius $4$ on one end. Find its area to 2 decimals.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$135$`, r`$42$`, r`$25\pi\approx78.54$`, r`$20\pi\approx62.83$`, r`$120-20=100$`, r`$36\pi\approx113.10$`, r`$60+\tfrac12\pi(9)\approx74.14$`, r`$63$`, r`$\tfrac12(6+10)(5)=40$`, r`$240+\pi(6)^2\approx353.10$`, r`$\tfrac12\pi(64)\approx100.53$`, r`$49-12.25\pi\approx10.52$`, r`$112+\tfrac12\pi(16)\approx137.13$`],
  },
  {
    code: "3.3", unit: U, title: "Surface Area & Volume of Composite Figures",
    intro: r`Prism/cylinder volume $=(\text{base area})\times h$; box $V=lwh$, cylinder $V=\pi r^2h$. Surface area: box $2(lw+lh+wh)$, closed cylinder $2\pi r^2+2\pi rh$. Add joined solids; subtract a drilled hole.`,
    ideas: [r`Box $V=lwh$, cylinder $V=\pi r^2h$.`, r`Box $SA=2(lw+lh+wh)$; cylinder $2\pi r^2+2\pi rh$.`, r`Add parts; subtract a hole.`],
    examples: [
      { t: "A box", body: r`Volume and surface area of a $4\times5\times6$ box.\soln $V=120$; $SA=2(20+24+30)=148$.` },
      { t: "A cylinder", body: r`Cylinder radius $3$, height $10$.\soln $V=90\pi\approx282.74$; $SA=18\pi+60\pi=78\pi\approx245.04$.` },
      { t: "A tank", body: r`Volume of a tank, radius $5$, height $8$.\soln $200\pi\approx628.32$.` },
      { t: "Drilled block (subtract)", body: r`A $10\times8\times6$ block with a cylindrical hole of radius $2$ through the height $6$.\soln $480-\pi(4)(6)=480-24\pi\approx404.60$.` },
      { t: "Triangular prism", body: r`Prism with triangular cross-section (base $6$, height $4$), length $10$.\soln $\tfrac12(6)(4)\times10=120$.` },
      { t: "Larger cylinder", body: r`Cylinder radius $4$, height $10$.\soln $V=160\pi\approx502.65$; $SA=32\pi+80\pi=112\pi\approx351.86$.` },
      { t: "A large tank", body: r`Volume of a tank, radius $6$, height $12$.\soln $432\pi\approx1357.17$.` },
      { t: "A box (SA)", body: r`Surface area of a $5\times6\times7$ box.\soln $2(30+35+42)=214$.` },
      { t: "Drilled block 2", body: r`A $12\times8\times5$ block with a cylindrical hole of radius $2$ through the height $5$.\soln $480-\pi(4)(5)=480-20\pi\approx417.17$.` },
    ],
    questions: [
      { ask: r`Surface area of a cube of side $5$.` },
      { ask: r`Volume of a $3\times4\times10$ prism.` },
      { ask: r`Volume of a cylinder, radius $4$, height $9$ (2 decimals).` },
      { ask: r`Surface area of a closed cylinder, radius $5$, height $8$ (2 decimals).` },
      { ask: r`Volume of a $5\times6\times7$ box.` },
      { ask: r`Surface area of a $4\times5\times6$ box.` },
      { ask: r`Volume of a cylinder, radius $6$, height $12$ (2 decimals).` },
      { ask: r`Volume of a $10\times8\times6$ block minus a cylindrical hole (radius $2$, through height $6$) (2 decimals).` },
      { ask: r`Volume of a triangular prism: cross-section base $8$, height $5$, length $12$.` },
      { ask: r`Volume of a cylinder, radius $3$, height $10$ (2 decimals).` },
      { ask: r`Surface area of a cube of side $8$.` },
      { ask: r`Volume of a $5\times6\times7$ box.` },
      { ask: r`A $12\times8\times5$ box has a cylindrical hole (radius $2$) through its height $5$. Find the remaining volume to 2 decimals.`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`$150$`, r`$120$`, r`$144\pi\approx452.39$`, r`$130\pi\approx408.41$`, r`$210$`, r`$148$`, r`$432\pi\approx1357.17$`, r`$480-24\pi\approx404.60$`, r`$\tfrac12(8)(5)\times12=240$`, r`$90\pi\approx282.74$`, r`$384$`, r`$210$`, r`$480-20\pi\approx417.17$`],
  },
  {
    code: "3.4", unit: U, title: "Optimizing Perimeter & Area (2-D)",
    intro: r`For a fixed perimeter, the maximum-area rectangle is a square; for a fixed area, the minimum-perimeter rectangle is a square. With one side a free wall, the best pen is a $1{:}2$ rectangle. Reduce to one variable, then use a table.`,
    ideas: [r`Fixed perimeter $\Rightarrow$ max area is a square.`, r`Fixed area $\Rightarrow$ min perimeter is a square.`, r`Against a wall $\Rightarrow$ best is $1{:}2$.`],
    examples: [
      { t: "Max area, fixed perimeter", body: r`Perimeter $24$ ($l+w=12$). Which dimensions maximize area?\soln Table: $4\times8=32$, $5\times7=35$, $6\times6=36$; the $6\times6$ square gives $36$.` },
      { t: "Min perimeter, fixed area", body: r`Area $36$. Which dimensions minimize the perimeter?\soln $4\times9\Rightarrow26$, $6\times6\Rightarrow24$; the square, $24$.` },
      { t: "A garden", body: r`$48$ m of fence for a rectangle. Max area?\soln $l+w=24$; square $12\times12$ gives $144$ m$^2$.` },
      { t: "Pen against a wall", body: r`$30$ m of fence for three sides ($2x+y=30$). Max area?\soln $A=x(30-2x)$; peak at $x=7.5,\ y=15$, area $112.5$ m$^2$.` },
      { t: "Why it matters", body: r`Two $36$ m$^2$ gardens: $6\times6$ and $3\times12$. Which needs less fence?\soln $6\times6\Rightarrow24$; $3\times12\Rightarrow30$; the square saves $6$ m.` },
      { t: "Fixed perimeter 32", body: r`Perimeter $32$. Max-area rectangle?\soln Square $8\times8$, area $64$.` },
      { t: "Fixed area 64", body: r`Area $64$. Min-perimeter rectangle?\soln Square $8\times8$, perimeter $32$.` },
      { t: "Fence 20", body: r`$20$ m of fence for a rectangle. Max area?\soln $l+w=10$; square $5\times5$, area $25$.` },
      { t: "Pen against a wall 2", body: r`$40$ m of fence for three sides. Max area?\soln $2x+y=40$; $x=10,\ y=20$, area $200$ m$^2$.` },
    ],
    questions: [
      { ask: r`Perimeter $40$ — which rectangle has the greatest area?` },
      { ask: r`Area $64$ — which rectangle has the least perimeter?` },
      { ask: r`With $20$ m of fence, the greatest rectangular area?` },
      { ask: r`A pen against a wall uses $20$ m for three sides. Best area?` },
      { ask: r`Perimeter $36$ — max-area rectangle?` },
      { ask: r`Area $100$ — min-perimeter rectangle?` },
      { ask: r`With $60$ m of fence, greatest rectangular area?` },
      { ask: r`A pen against a wall uses $24$ m for three sides. Best area?` },
      { ask: r`Perimeter $28$ — max-area rectangle?` },
      { ask: r`Which shape maximizes area for a fixed perimeter?` },
      { ask: r`Why is a pen against a wall best as a $1{:}2$ rectangle?` },
      { ask: r`Area $81$ — min-perimeter rectangle?` },
      { ask: r`A pen against a wall uses $36$ m of fence for three sides. Find the dimensions and maximum area.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`square $10\times10$, area $100$`, r`square $8\times8$, perimeter $32$`, r`$5\times5=25$ m$^2$`, r`$x=5,\ y=10$, area $50$ m$^2$`, r`square $9\times9$, area $81$`, r`square $10\times10$, perimeter $40$`, r`$15\times15=225$ m$^2$`, r`$x=6,\ y=12$, area $72$ m$^2$`, r`square $7\times7$, area $49$`, r`a square`, r`the free wall replaces one fenced side, shifting the optimum to $y=2x$`, r`square $9\times9$, perimeter $36$`, r`$2x+y=36$: $x=9,\ y=18$, area $162$ m$^2$`],
  },
  {
    code: "3.5", unit: U, title: "Optimizing Surface Area & Volume (3-D)",
    intro: r`For a fixed volume, the least-surface-area rectangular prism is a cube; a cylinder is best when $h=2r$. Use a table of dimensions with the right volume and read the minimum surface area.`,
    ideas: [r`Fixed volume $\Rightarrow$ least surface area is a cube.`, r`Cylinder best when $h=2r$.`, r`Least surface area $=$ least material.`],
    examples: [
      { t: "Least material for a volume", body: r`A box holds $64$ cm$^3$. Among $2\times2\times16$, $2\times4\times8$, $4\times4\times4$, which uses the least material?\soln $SA$: $136$, $112$, $96$; the cube $4\times4\times4$ ($96$).` },
      { t: "Confirm the cube", body: r`Verify the cube's surface area above.\soln $6(4\times4)=96$ cm$^2$.` },
      { t: "A different volume", body: r`Least-material box for $27$ cm$^3$, and its surface area?\soln Cube $3\times3\times3$; $SA=6(9)=54$ cm$^2$.` },
      { t: "Why it matters", body: r`A $64$ cm$^3$ product ships as $2\times4\times8$ or a cube. Cardboard saved by the cube?\soln $112-96=16$ cm$^2$ per box.` },
      { t: "The cylinder rule", body: r`For a fixed volume, what shape of cylinder uses the least material?\soln Height equals diameter, $h=2r$ (a \emph{square} cylinder).` },
      { t: "Cube for 125", body: r`Least-material box for $125$ cm$^3$.\soln Cube $5\times5\times5$; $SA=6(25)=150$ cm$^2$.` },
      { t: "Cube for 216", body: r`Least-material box for $216$ cm$^3$.\soln Cube $6\times6\times6$; $SA=6(36)=216$ cm$^2$.` },
      { t: "A long box", body: r`Surface area of a $2\times2\times8$ box (volume $32$).\soln $2(4+16+16)=72$ cm$^2$.` },
      { t: "Compare shapes", body: r`For $32$ cm$^3$: compare $2\times2\times8$ with $2\times4\times4$.\soln $2\times2\times8\Rightarrow72$; $2\times4\times4\Rightarrow2(8+8+16)=64$ — the more cube-like box uses less.` },
    ],
    questions: [
      { ask: r`Least-material box for $8$ cm$^3$ — dimensions and surface area?` },
      { ask: r`Surface area of a $5\times5\times5$ cube.` },
      { ask: r`Least-material box for $1000$ cm$^3$ — dimensions?` },
      { ask: r`Surface area of that $10$-cm cube.` },
      { ask: r`Least-material box for $27$ cm$^3$ — surface area?` },
      { ask: r`Surface area of a $6\times6\times6$ cube.` },
      { ask: r`Which uses less material for $64$ cm$^3$: $4\times4\times4$ or $2\times4\times8$?` },
      { ask: r`What shape of cylinder uses the least material for a fixed volume?` },
      { ask: r`Surface area of a $1\times2\times8$ box.` },
      { ask: r`Least-material box for $216$ cm$^3$ — dimensions?` },
      { ask: r`Why does a cube minimize material?` },
      { ask: r`Surface area of a $3\times3\times3$ cube.` },
      { ask: r`Compare the surface area of a $1\times1\times64$ box with the cube for the same $64$ cm$^3$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`cube $2\times2\times2$, $SA=24$`, r`$150$`, r`cube $10\times10\times10$`, r`$600$`, r`cube $3\times3\times3$, $SA=54$`, r`$216$`, r`the cube $4\times4\times4$ ($96$ vs $112$)`, r`one with $h=2r$`, r`$2(2+8+16)=52$`, r`cube $6\times6\times6$`, r`it is the most balanced shape, so faces are smallest for the volume`, r`$54$`, r`$1\times1\times64\Rightarrow SA=258$; cube $=96$ — the long box uses $162$ more`],
  },
  {
    code: "3.6", unit: U, title: "Right-Triangle Trigonometry",
    intro: r`In a right triangle: $\sin=\tfrac{\text{opp}}{\text{hyp}}$, $\cos=\tfrac{\text{adj}}{\text{hyp}}$, $\tan=\tfrac{\text{opp}}{\text{adj}}$ (SOH-CAH-TOA). Find a side with a ratio; find an angle with an inverse ratio.`,
    ideas: [r`SOH-CAH-TOA.`, r`Side: set up a ratio and solve.`, r`Angle: use $\sin^{-1},\cos^{-1},\tan^{-1}$.`],
    examples: [
      { t: "Find the opposite", body: r`Hypotenuse $10$, angle $30^\circ$. Find the opposite side.\soln $10\sin30^\circ=10(0.5)=5$.` },
      { t: "Find the hypotenuse", body: r`Opposite $8$ to a $40^\circ$ angle. Find the hypotenuse.\soln $\dfrac{8}{\sin40^\circ}\approx12.45$.` },
      { t: "Find an angle", body: r`Opposite $5$, adjacent $12$. Find the angle.\soln $\tan^{-1}\!\left(\tfrac{5}{12}\right)\approx22.6^\circ$.` },
      { t: "Angle of elevation", body: r`From $20$ m away, the elevation to a building top is $55^\circ$. Find the height.\soln $20\tan55^\circ\approx28.56$ m.` },
      { t: "Find the adjacent", body: r`A $15$-m ramp makes $25^\circ$ with the ground. Horizontal reach?\soln $15\cos25^\circ\approx13.59$ m.` },
      { t: "Opposite side", body: r`Hypotenuse $15$, angle $30^\circ$. Find the opposite side.\soln $15\sin30^\circ=7.5$.` },
      { t: "Find angle 2", body: r`Opposite $9$, adjacent $12$. Find the angle.\soln $\tan^{-1}\!\left(\tfrac{9}{12}\right)\approx36.87^\circ$.` },
      { t: "Height 2", body: r`From $30$ m, elevation $50^\circ$ to a tower top. Height?\soln $30\tan50^\circ\approx35.75$ m.` },
      { t: "Adjacent 2", body: r`Hypotenuse $12$, angle $40^\circ$. Find the adjacent side.\soln $12\cos40^\circ\approx9.19$.` },
    ],
    questions: [
      { ask: r`Hypotenuse $12$, angle $35^\circ$ — find the opposite side.` },
      { ask: r`Hypotenuse $20$, angle $40^\circ$ — find the adjacent side.` },
      { ask: r`Opposite $7$, adjacent $24$ — find the angle.` },
      { ask: r`Opposite $10$ to a $30^\circ$ angle — find the hypotenuse.` },
      { ask: r`Hypotenuse $18$, angle $42^\circ$ — find the opposite side.` },
      { ask: r`Hypotenuse $25$, angle $38^\circ$ — find the adjacent side.` },
      { ask: r`Opposite $8$, adjacent $15$ — find the angle.` },
      { ask: r`Opposite $12$ to a $40^\circ$ angle — find the hypotenuse.` },
      { ask: r`From $30$ m, elevation $50^\circ$ to a roof — find its height.` },
      { ask: r`A $15$-m ramp at $25^\circ$ — find the horizontal reach.` },
      { ask: r`Hypotenuse $10$, angle $30^\circ$ — find the opposite side.` },
      { ask: r`Opposite $5$, adjacent $12$ — find the angle.` },
      { ask: r`From the top of a $50$-m cliff, the angle of depression to a boat is $25^\circ$. How far is the boat from the base?`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`$12\sin35^\circ\approx6.88$`, r`$20\cos40^\circ\approx15.32$`, r`$\tan^{-1}(7/24)\approx16.26^\circ$`, r`$\tfrac{10}{\sin30^\circ}=20$`, r`$18\sin42^\circ\approx12.04$`, r`$25\cos38^\circ\approx19.70$`, r`$\tan^{-1}(8/15)\approx28.07^\circ$`, r`$\tfrac{12}{\sin40^\circ}\approx18.67$`, r`$30\tan50^\circ\approx35.75$ m`, r`$15\cos25^\circ\approx13.59$ m`, r`$10\sin30^\circ=5$`, r`$\tan^{-1}(5/12)\approx22.62^\circ$`, r`$\tfrac{50}{\tan25^\circ}\approx107.23$ m`],
  },
  {
    code: "3.7", unit: U, title: "The Sine Law & the Cosine Law",
    intro: r`Sine law $\dfrac{a}{\sin A}=\dfrac{b}{\sin B}=\dfrac{c}{\sin C}$ (matched side–angle pair); cosine law $a^2=b^2+c^2-2bc\cos A$ (SAS or SSS). An obtuse angle has a negative cosine.`,
    ideas: [r`Sine law: matched pair.`, r`Cosine law: SAS or SSS.`, r`Obtuse angle $\Rightarrow$ negative cosine.`],
    examples: [
      { t: "Sine law, side", body: r`$A=40^\circ$, $B=60^\circ$, $a=10$. Find $b$.\soln $b=\dfrac{10\sin60^\circ}{\sin40^\circ}\approx13.47$.` },
      { t: "Sine law, angle", body: r`$a=8$, $b=6$, $A=50^\circ$. Find $B$.\soln $\sin B=\dfrac{6\sin50^\circ}{8}\approx0.5745\Rightarrow B\approx35.1^\circ$.` },
      { t: "Cosine law, side", body: r`$b=7$, $c=9$, included $A=60^\circ$. Find $a$.\soln $a^2=49+81-2(63)\cos60^\circ=67\Rightarrow a\approx8.19$.` },
      { t: "Cosine law, angle", body: r`Sides $6,8,10$. Find the largest angle (opposite $10$).\soln $\cos C=\dfrac{36+64-100}{2(48)}=0\Rightarrow C=90^\circ$.` },
      { t: "Obtuse triangle", body: r`$b=5$, $c=8$, $A=120^\circ$. Find $a$.\soln $a^2=25+64-80\cos120^\circ=129\Rightarrow a\approx11.36$.` },
      { t: "Sine law, side 2", body: r`$A=40^\circ$, $B=70^\circ$, $a=10$. Find $b$.\soln $b=\dfrac{10\sin70^\circ}{\sin40^\circ}\approx14.62$.` },
      { t: "Cosine law, side 2", body: r`$b=8$, $c=10$, $A=50^\circ$. Find $a$.\soln $a=\sqrt{64+100-160\cos50^\circ}\approx7.82$.` },
      { t: "Largest angle", body: r`Sides $7,9,12$. Find the largest angle (opposite $12$).\soln $\cos C=\dfrac{49+81-144}{2(63)}\approx-0.111\Rightarrow C\approx96.4^\circ$.` },
      { t: "Two roads", body: r`Two roads leave a town at $75^\circ$; cars go $9$ km and $6$ km. Distance apart?\soln $\sqrt{81+36-108\cos75^\circ}\approx9.44$ km.` },
    ],
    questions: [
      { ask: r`$A=45^\circ$, $a=14$, $B=60^\circ$ — find $b$.` },
      { ask: r`$b=12$, $c=15$, included $A=50^\circ$ — find $a$.` },
      { ask: r`Sides $5,6,7$ — find the largest angle (opposite $7$).` },
      { ask: r`$a=9$, $A=40^\circ$, $b=7$ — find $B$.` },
      { ask: r`$b=7$, $c=9$, included $A=60^\circ$ — find $a$.` },
      { ask: r`Sides $4,5,6$ — find the smallest angle (opposite $4$).` },
      { ask: r`$A=40^\circ$, $B=70^\circ$, $a=10$ — find $b$.` },
      { ask: r`$b=5$, $c=8$, included $A=120^\circ$ — find $a$.` },
      { ask: r`When do you use the cosine law?` },
      { ask: r`$a=8$, $b=6$, $A=50^\circ$ — find $B$.` },
      { ask: r`What is special about an obtuse angle's cosine?` },
      { ask: r`Sides $6,8,10$ — find the largest angle.` },
      { ask: r`A surveyor sees points $B$ ($250$ m) and $C$ ($310$ m) with $\angle BAC=68^\circ$. Find $BC$.`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`$\dfrac{14\sin60^\circ}{\sin45^\circ}\approx17.15$`, r`$\sqrt{144+225-360\cos50^\circ}\approx11.72$`, r`$\cos C=\tfrac{25+36-49}{60}=0.2\Rightarrow78.46^\circ$`, r`$\sin B=\tfrac{7\sin40^\circ}{9}\Rightarrow B\approx30.0^\circ$`, r`$\sqrt{67}\approx8.19$`, r`$\cos A=\tfrac{25+36-16}{60}=0.75\Rightarrow41.41^\circ$`, r`$\approx14.62$`, r`$\sqrt{129}\approx11.36$`, r`with SAS (two sides + included angle) or SSS (three sides)`, r`$B\approx35.1^\circ$`, r`it is negative`, r`$90^\circ$ (opposite $10$)`, r`$BC=\sqrt{250^2+310^2-2(250)(310)\cos68^\circ}\approx317$ m`],
  },
];
