// MAP4C Unit 4 worksheets — Data Management.
// Full \soln solutions; 9 worked examples + 13 questions + answer key each.
const r = String.raw;
const U = "4: Data Management";

export default [
  {
    code: "4.1", unit: U, title: "One-Variable Statistics & Displaying Data",
    intro: r`Summarize data with the mean (average), median (middle value in order), mode (most frequent), and range (highest $-$ lowest). Bar/circle graphs suit categories; histograms suit numeric intervals.`,
    ideas: [r`Mean, median, mode.`, r`Range $=$ highest $-$ lowest.`, r`Choose the graph to match the data type.`],
    examples: [
      { t: "The mean", body: r`Find the mean of $12, 15, 15, 18, 20$.\soln $\dfrac{80}{5}=16$.` },
      { t: "Median (odd)", body: r`Find the median of $7, 3, 9, 5, 11$.\soln Order $3,5,7,9,11$; middle $=7$.` },
      { t: "Median (even)", body: r`Find the median of $4, 8, 10, 14$.\soln Average the middles: $\dfrac{8+10}{2}=9$.` },
      { t: "Mode and range", body: r`For $5, 8, 8, 8, 10, 12$, find the mode and range.\soln Mode $8$; range $12-5=7$.` },
      { t: "Choosing a graph", body: r`Which graph suits (a) favourite sports, (b) test-score distribution?\soln (a) bar/circle; (b) histogram.` },
      { t: "Mean of five", body: r`Find the mean of $3, 6, 9, 12, 15$.\soln $\dfrac{45}{5}=9$.` },
      { t: "Median of six", body: r`Find the median of $2, 4, 6, 8, 10, 12$.\soln $\dfrac{6+8}{2}=7$.` },
      { t: "Mode", body: r`Find the mode of $4, 4, 7, 9, 9, 9$.\soln $9$ (three times).` },
      { t: "Outlier effect", body: r`For $4, 5, 6, 7, 100$, find the mean and median.\soln Mean $\dfrac{122}{5}=24.4$; median $6$ — the median is more typical.` },
    ],
    questions: [
      { ask: r`Mean of $3, 6, 9, 12, 15$.` },
      { ask: r`Median of $2, 4, 6, 8, 10, 12$.` },
      { ask: r`Mode of $4, 4, 7, 9, 9, 9$.` },
      { ask: r`Range of $45, 12, 33, 28$.` },
      { ask: r`Mean of $10, 20, 30, 40$.` },
      { ask: r`Median of $6, 2, 8, 4, 10$.` },
      { ask: r`Range of $5, 8, 12, 20, 3$.` },
      { ask: r`Mode of $2, 3, 3, 5, 3, 7$.` },
      { ask: r`Which graph suits categories: a histogram or a bar graph?` },
      { ask: r`Mean of $8, 8, 10, 14$.` },
      { ask: r`Median of $3, 7, 1, 9, 5$.` },
      { ask: r`For $4, 5, 6, 7, 100$, which better represents a typical value — mean or median?` },
      { ask: r`A data set is $10, 12, 12, 14, 52$. Find the mean and median, and say which better represents a typical value.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$9$`, r`$7$`, r`$9$`, r`$45-12=33$`, r`$25$`, r`$6$`, r`$20-3=17$`, r`$3$`, r`a bar graph`, r`$\tfrac{40}{4}=10$`, r`$5$`, r`the median ($6$)`, r`mean $\tfrac{100}{5}=20$; median $12$; the median (the $52$ is an outlier)`],
  },
  {
    code: "4.2", unit: U, title: "Sampling, Bias & the Misuse of Statistics",
    intro: r`The population is everyone of interest; a sample is the part studied. A good sample is random, representative, and large enough. Bias makes a sample misrepresent the population.`,
    ideas: [r`Population vs sample.`, r`Good sample: random, representative, large enough.`, r`Watch for bias and misleading graphs.`],
    examples: [
      { t: "Population vs sample", body: r`A school has $1200$ students; $100$ are surveyed. Identify each.\soln Population $=1200$; sample $=100$.` },
      { t: "A biased sample", body: r`Surveying only the band class about the whole school's music taste. Good sample?\soln Biased — not representative.` },
      { t: "A leading question", body: r`\emph{Don't you agree our great cafeteria should stay open later?} Why biased?\soln The wording pushes toward \emph{yes} — response bias.` },
      { t: "A tiny sample", body: r`An ad claims \emph{$80\%$ preferred Brand X} from $5$ people. The concern?\soln $80\%$ is only $4$ of $5$ — far too few.` },
      { t: "A better design", body: r`How would you fairly sample the school's lunch preference?\soln Randomly select across all grades, with a large, varied group and neutral questions.` },
      { t: "Naming both", body: r`A city has $50\,000$ voters; a poll asks $800$. Name each.\soln Population $50\,000$; sample $800$.` },
      { t: "Bias check", body: r`Surveying shoppers only at a luxury store about spending. Biased?\soln Yes — not representative of all shoppers.` },
      { t: "Good-sample feature", body: r`Name one feature of a good sample.\soln Random (or representative, or large enough).` },
      { t: "Misleading graph", body: r`A graph's vertical axis starts at $90$, so $92\to96$ looks huge. What is this?\soln A misleading (truncated) scale.` },
    ],
    questions: [
      { ask: r`A city has $50\,000$ voters; a poll asks $800$. Name the population and sample.` },
      { ask: r`Surveying only shoppers at a luxury store about spending — biased or not?` },
      { ask: r`Name one feature of a good sample.` },
      { ask: r`Why is \emph{9 out of 10 dentists} weak if only $10$ were asked?` },
      { ask: r`In a school of $1500$, $120$ are surveyed. What is the sample size?` },
      { ask: r`Is surveying your friends a random sample of the school?` },
      { ask: r`Give one reason we sample instead of surveying everyone.` },
      { ask: r`A survey asks \emph{Isn't our new park wonderful?} What kind of bias is this?` },
      { ask: r`A graph starts its axis at $50$ instead of $0$. What is the risk?` },
      { ask: r`Population or sample: all voters in a city?` },
      { ask: r`Population or sample: the $800$ people polled?` },
      { ask: r`Why can a percentage from a tiny sample be unreliable?` },
      { ask: r`A poll of $10$ people at a hockey game finds $90\%$ support a new arena. Give two reasons this may not represent the whole city.`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`population $50\,000$; sample $800$`, r`biased (not representative)`, r`random, representative, or large enough`, r`the sample is too small to generalize`, r`$120$`, r`no — friends are not random`, r`time, cost, or practicality`, r`response bias (a leading question)`, r`it can exaggerate small differences`, r`population`, r`sample`, r`it may not represent the whole population`, r`tiny sample ($10$); and hockey fans are not representative of all residents`],
  },
  {
    code: "4.3", unit: U, title: "Two-Variable Data & Scatter Plots",
    intro: r`A scatter plot graphs paired data $(x,y)$: the independent variable (input) on the horizontal axis, the dependent variable (output) on the vertical. The shape of the cloud shows whether the two are related.`,
    ideas: [r`Independent on $x$, dependent on $y$.`, r`Upward, downward, or no pattern.`, r`Show separate points, not a line.`],
    examples: [
      { t: "Choosing the axes", body: r`Hours studied affects test score. Which is independent?\soln Hours studied (the input) — horizontal axis.` },
      { t: "Upward trend", body: r`$(1,55),(2,60),(3,68),(4,75),(5,82)$ (hours vs score). Describe the pattern.\soln As hours rise, score rises — a positive (upward) pattern.` },
      { t: "Downward trend", body: r`$(0,100),(2,80),(4,65),(6,45)$ (hours used vs battery). Describe it.\soln As use rises, battery falls — a negative pattern.` },
      { t: "No pattern", body: r`Shoe size vs math mark gives a scattered cloud. What does it mean?\soln No relationship.` },
      { t: "Reading a point", body: r`On a height–weight plot, a point is $(170,68)$. Interpret it.\soln A person $170$ cm tall weighing $68$ kg.` },
      { t: "Cause vs effect", body: r`Temperature affects ice-cream sales. Which variable is dependent?\soln Sales (the outcome) — vertical axis.` },
      { t: "Positive pattern", body: r`$(1,3),(2,5),(3,7),(4,9)$. Describe the trend.\soln Steady rise — positive.` },
      { t: "Negative pattern", body: r`$(1,20),(2,16),(3,12),(4,8)$. Describe the trend.\soln Steady fall — negative.` },
      { t: "Strength", body: r`Two study–score plots: one tight along a line, one widely scattered. What differs?\soln The strength — the first is strong, the second weak.` },
    ],
    questions: [
      { ask: r`Temperature affects ice-cream sales. Which variable is independent?` },
      { ask: r`$(1,3),(2,5),(3,7),(4,9)$ — describe the trend.` },
      { ask: r`$(1,20),(2,16),(3,12),(4,8)$ — describe the trend.` },
      { ask: r`Where does the dependent variable go?` },
      { ask: r`A shapeless cloud of points shows what relationship?` },
      { ask: r`Should scatter-plot points be joined with a line?` },
      { ask: r`Hours of exercise vs resting heart rate trends downward. What kind of pattern?` },
      { ask: r`On a plot, a point is $(15, 40)$. If $x$ is age and $y$ is height (in), interpret it.` },
      { ask: r`In "rainfall affects crop yield," which is the dependent variable?` },
      { ask: r`$(2,10),(4,14),(6,18)$ — positive or negative pattern?` },
      { ask: r`A tight, line-like cloud shows a strong or weak relationship?` },
      { ask: r`Which axis is the independent variable on?` },
      { ask: r`A scatter plot of study hours vs score is tight along a rising line for one class but scattered for another. What differs about the relationship?`, challenge: true, ws: "3cm" },
    ],
    answers: [r`temperature`, r`positive (upward)`, r`negative (downward)`, r`the vertical ($y$) axis`, r`no relationship`, r`no — show separate points`, r`negative`, r`a $15$-year-old who is $40$ in tall`, r`crop yield`, r`positive`, r`strong`, r`the horizontal ($x$) axis`, r`the strength — one is strong, the other weak`],
  },
  {
    code: "4.4", unit: U, title: "Correlation, Trends & the Line of Best Fit",
    intro: r`Correlation has a direction (positive/negative/none) and strength (tight line $=$ strong). The line of best fit $y=mx+b$ (from technology) predicts a $y$ from an $x$; interpolate within the data, not far beyond it.`,
    ideas: [r`Direction and strength.`, r`Line of best fit $y=mx+b$.`, r`Interpolate (safe) vs extrapolate (risky).`],
    examples: [
      { t: "Naming a correlation", body: r`Temperature vs ice-cream sales trends clearly upward. Describe the correlation.\soln Strong positive.` },
      { t: "A weak negative", body: r`Hours of TV vs test score trends down but loosely. Describe it.\soln Weak negative.` },
      { t: "Predict from the line", body: r`Line $y=2x+3$ (score vs hours). Predict at $10$ hours.\soln $2(10)+3=23$.` },
      { t: "Interpolate vs extrapolate", body: r`Data covers $0$–$8$ hours. Safer prediction: at $5$ or at $40$ hours?\soln At $5$ (inside the data) — interpolation is reliable.` },
      { t: "Correlation not cause", body: r`Ice-cream sales and drownings rise together. Does ice cream cause drownings?\soln No — hot weather (a hidden variable) drives both.` },
      { t: "Predict again", body: r`Line $y=1.5x+2$. Predict at $x=8$.\soln $1.5(8)+2=14$.` },
      { t: "Strong negative", body: r`Points trend downward in a tight line. Describe the correlation.\soln Strong negative.` },
      { t: "No correlation", body: r`A scattered cloud with no trend. Correlation?\soln None.` },
      { t: "Unrealistic prediction", body: r`Line $y=8x+40$ (score). Predict at $12$ hours; comment.\soln $136$ — impossible ($>100$), so the extrapolation is unreliable.` },
    ],
    questions: [
      { ask: r`Points trend downward in a tight line. Describe the correlation.` },
      { ask: r`Line $y=1.5x+2$. Predict $y$ at $x=8$.` },
      { ask: r`Is predicting inside the data range interpolation or extrapolation?` },
      { ask: r`A scattered cloud with no trend has what correlation?` },
      { ask: r`Line $y=3x+5$. Predict $y$ at $x=6$.` },
      { ask: r`Points rise loosely. Describe the correlation.` },
      { ask: r`Does correlation prove causation?` },
      { ask: r`Line $y=5x+10$. Predict $y$ at $x=4$.` },
      { ask: r`Which is riskier: interpolation or extrapolation?` },
      { ask: r`Ice-cream sales and drownings both rise in summer. Name the hidden variable.` },
      { ask: r`A tight upward cloud shows what correlation?` },
      { ask: r`Line $y=2x+1$. Predict $y$ at $x=7$.` },
      { ask: r`Data on $1$–$6$ hours gives $y=8x+40$ (score). The prediction at $12$ hours is $136$. Why is it unreliable?`, challenge: true, ws: "3cm" },
    ],
    answers: [r`strong negative`, r`$1.5(8)+2=14$`, r`interpolation`, r`no correlation`, r`$3(6)+5=23$`, r`weak positive`, r`no`, r`$5(4)+10=30$`, r`extrapolation`, r`hot weather (temperature)`, r`strong positive`, r`$2(7)+1=15$`, r`$12$ hours is far outside the data (extrapolation) and $136>100$ is impossible`],
  },
  {
    code: "4.5", unit: U, title: "Probability & Making Decisions",
    intro: r`For equally likely outcomes, $P(\text{event})=\dfrac{\text{favourable}}{\text{total}}$, from $0$ to $1$. Experimental probability comes from trials and approaches the theoretical value over many trials.`,
    ideas: [r`$P=\dfrac{\text{favourable}}{\text{total}}$.`, r`Experimental $\to$ theoretical over many trials.`, r`Two dice: $36$ outcomes.`],
    examples: [
      { t: "A single die", body: r`Probability of rolling an even number.\soln $\dfrac{3}{6}=\dfrac12$.` },
      { t: "Two dice", body: r`Probability the sum is $7$.\soln $6$ ways out of $36$: $\dfrac{6}{36}=\dfrac16$.` },
      { t: "A card", body: r`Probability of drawing a heart from $52$ cards.\soln $\dfrac{13}{52}=\dfrac14$.` },
      { t: "Experimental vs theoretical", body: r`A coin lands heads $12$ times in $20$ flips. Compare.\soln Experimental $\dfrac{12}{20}=0.6$; theoretical $0.5$ — closer with more flips.` },
      { t: "A decision", body: r`A game costs $\$2$; you win $\$10$ with probability $\tfrac16$. Worth playing?\soln Expected win $\tfrac16(10)\approx\$1.67<\$2$ — a long-run loss.` },
      { t: "Rolling a specific number", body: r`Probability of rolling a $5$.\soln $\dfrac16$.` },
      { t: "A red card", body: r`Probability of drawing a red card.\soln $\dfrac{26}{52}=\dfrac12$.` },
      { t: "Complement", body: r`Probability of NOT rolling a $6$.\soln $1-\tfrac16=\tfrac56$.` },
      { t: "Two dice sum 8", body: r`Probability the sum is $8$.\soln $(2,6),(3,5),(4,4),(5,3),(6,2)=5$ ways: $\dfrac{5}{36}$.` },
    ],
    questions: [
      { ask: r`Probability of rolling a $5$ on a fair die.` },
      { ask: r`Probability of drawing a red card from $52$ cards.` },
      { ask: r`Probability of NOT rolling a $6$.` },
      { ask: r`Two dice: probability the sum is $8$.` },
      { ask: r`Probability of rolling an odd number on a die.` },
      { ask: r`Probability of drawing a spade from $52$ cards.` },
      { ask: r`Two dice: probability the sum is $2$.` },
      { ask: r`A coin lands heads $14$ times in $20$ flips. Experimental probability?` },
      { ask: r`Two dice: probability the sum is $5$.` },
      { ask: r`Probability of drawing a face card (J, Q, K) from $52$ cards.` },
      { ask: r`Two dice: probability the sum is at least $10$.` },
      { ask: r`As trials increase, experimental probability approaches what?` },
      { ask: r`A spinner has $3$ equal colours. It lands on red $18$ times in $60$ spins. Find the experimental probability and compare it to the theoretical value.`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`$\tfrac16$`, r`$\tfrac{26}{52}=\tfrac12$`, r`$\tfrac56$`, r`$\tfrac{5}{36}$`, r`$\tfrac36=\tfrac12$`, r`$\tfrac{13}{52}=\tfrac14$`, r`$\tfrac{1}{36}$`, r`$\tfrac{14}{20}=0.7$`, r`$\tfrac{4}{36}=\tfrac19$`, r`$\tfrac{12}{52}=\tfrac{3}{13}$`, r`$\tfrac{6}{36}=\tfrac16$ (sums $10,11,12$)`, r`the theoretical probability`, r`experimental $\tfrac{18}{60}=0.3$; theoretical $\tfrac13\approx0.333$ — close, approaching $\tfrac13$`],
  },
];
