// MCV4U Unit 1 worksheets — Rates of Change & Limits. Full \soln solutions + TikZ figures.
const r = String.raw;
const U = "1: Rates of Change and Limits";

export default [
  {
    code: "1.1", unit: U, title: "Average & Instantaneous Rate of Change",
    intro: r`Average rate $=\dfrac{f(b)-f(a)}{b-a}$ (secant slope); instantaneous rate $=\displaystyle\lim_{h\to0}\dfrac{f(a+h)-f(a)}{h}$ (tangent slope).`,
    ideas: [r`Average rate over $[a,b]$: $\dfrac{f(b)-f(a)}{b-a}$.`, r`Difference quotient: $\dfrac{f(x+h)-f(x)}{h}$ — the secant slope for spacing $h$.`, r`Let $h\to0$ to get the instantaneous (tangent) rate.`],
    examples: [
      { t: "Average rate (secant)", body: r`Average rate of change of $f(x)=x^2+1$ on $[1,3]$.\soln $\dfrac{f(3)-f(1)}{3-1}=\dfrac{10-2}{2}=4$. The secant through $(1,1)$ and $(3,9)$ has slope $4$:` + r`\eplot{-1}{4}{-2}{12}{\addplot[exblue,very thick,domain=-1.4:3.4]{x^2};\addplot[qorange,thick,domain=0:4]{4*x-3};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(1,1) (3,9)};}` },
      { t: "Average rate", body: r`Average rate of change of $f(x)=x^2$ on $[2,4]$.\soln $\dfrac{16-4}{2}=6$.` },
      { t: "Difference quotient", body: r`Simplify the difference quotient of $f(x)=x^2$ at a general $x$.\soln $\dfrac{(x+h)^2-x^2}{h}=\dfrac{2xh+h^2}{h}=2x+h$ (limit $2x$).` },
      { t: "Instantaneous via a limit", body: r`Instantaneous rate of $f(x)=x^2$ at $x=2$.\soln $\displaystyle\lim_{h\to0}\dfrac{(2+h)^2-4}{h}=\lim_{h\to0}(4+h)=4$.` },
      { t: "Instantaneous", body: r`Instantaneous rate of $f(x)=3x^2$ at $x=2$.\soln Slope function $6x\Rightarrow 6(2)=12$.` },
      { t: "Velocity", body: r`For $s(t)=t^2$, find the instantaneous velocity at $t=4$.\soln $v=2t\Rightarrow 2(4)=8$.` },
      { t: "Average rate (cubic)", body: r`Average rate of change of $f(x)=x^3$ on $[1,2]$.\soln $\dfrac{8-1}{1}=7$.` },
      { t: "Velocity from a model", body: r`A ball's height is $h(t)=20t-5t^2$. Find its instantaneous velocity at $t=1$.\soln $\displaystyle\lim_{h\to0}\dfrac{20(1+h)-5(1+h)^2-15}{h}=\lim_{h\to0}(10-5h)=10$ m/s.` },
      { t: "Difference quotient", body: r`Simplify the difference quotient of $f(x)=2x^2$ at $x=1$.\soln $\dfrac{2(1+h)^2-2}{h}=4+2h$ (limit $4$).` },
    ],
    questions: [
      { ask: r`Average rate of change of $f(x)=x^2-3$ on $[2,5]$?` },
      { ask: r`Average rate of change of $f(x)=x^2$ on $[0,4]$?` },
      { ask: r`Simplify the difference quotient of $f(x)=x^2$ at $x=3$.` },
      { ask: r`Instantaneous rate of $f(x)=x^2$ at $x=5$?` },
      { ask: r`Instantaneous rate of $f(x)=4x^2$ at $x=1$?` },
      { ask: r`For $s(t)=t^2$, the instantaneous velocity at $t=6$?` },
      { ask: r`Average rate of change of $f(x)=x^3$ on $[0,2]$?` },
      { ask: r`Simplify $\dfrac{3(2+h)^2-12}{h}$.` },
      { ask: r`A ball's height is $h(t)=30t-5t^2$; instantaneous velocity at $t=2$?` },
      { ask: r`Average rate of change of $f(x)=2x+1$ on $[1,4]$?` },
      { ask: r`Instantaneous rate of $f(x)=x^2$ at $x=-3$?` },
      { ask: r`For $s(t)=t^2+t$, instantaneous velocity at $t=1$?` },
      { ask: r`A population is $P(t)=100+t^2$; find its instantaneous rate of growth at $t=5$ using the limit.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\tfrac{22-1}{3}=7$`, r`$4$`, r`$6+h$ (limit $6$)`, r`$10$`, r`$8$`, r`$12$`, r`$\tfrac{8-0}{2}=4$`, r`$12+3h$ (limit $12$)`, r`$10$ m/s`, r`$2$`, r`$-6$`, r`$3$`, r`$\lim_{h\to0}(10+h)=10$`],
  },
  {
    code: "1.2", unit: U, title: "The Limit of a Function",
    intro: r`$\displaystyle\lim_{x\to a}f(x)=L$ is the value $f$ approaches near $a$. Substitute when continuous; for $\tfrac00$ factor or rationalize first.`,
    ideas: [r`Direct substitution when continuous.`, r`$\tfrac00$ indeterminate $\Rightarrow$ factor / rationalize, then substitute.`, r`One-sided limits must agree; at infinity, divide by the highest power.`],
    examples: [
      { t: "Direct substitution", body: r`$\displaystyle\lim_{x\to3}(2x+1)$.\soln Continuous; substitute: $2(3)+1=7$.` },
      { t: "Factor out 0/0", body: r`$\displaystyle\lim_{x\to2}\dfrac{x^2-4}{x-2}$.\soln $\tfrac00$; factor $\dfrac{(x-2)(x+2)}{x-2}=x+2\to4$. The graph is $y=x+2$ with a hole at $(2,4)$:` + r`\eplot{-1}{5}{-1}{7}{\addplot[exblue,very thick,domain=-1:1.9]{x+2};\addplot[exblue,very thick,domain=2.1:5]{x+2};\addplot[red,only marks,mark=o,mark size=2.4pt] coordinates {(2,4)};}` },
      { t: "Rationalize 0/0", body: r`$\displaystyle\lim_{x\to0}\dfrac{\sqrt{x+9}-3}{x}$.\soln Multiply by the conjugate: $\dfrac{x}{x(\sqrt{x+9}+3)}=\dfrac1{\sqrt{x+9}+3}\to\dfrac16$.` },
      { t: "One-sided (DNE)", body: r`$\displaystyle\lim_{x\to0}\dfrac{|x|}{x}$.\soln Right limit $=1$, left limit $=-1$; they differ, so the limit does not exist.` },
      { t: "Limit at infinity", body: r`$\displaystyle\lim_{x\to\infty}\dfrac{3x^2-x}{x^2+5}$.\soln Divide by $x^2$: $\dfrac{3-1/x}{1+5/x^2}\to3$.` },
      { t: "Direct substitution", body: r`$\displaystyle\lim_{x\to4}(x^2-1)$.\soln $16-1=15$.` },
      { t: "Factor", body: r`$\displaystyle\lim_{x\to3}\dfrac{x^2-9}{x-3}$.\soln $x+3\to6$.` },
      { t: "At infinity", body: r`$\displaystyle\lim_{x\to\infty}\dfrac{5x-2}{x+1}$.\soln Ratio of leading coefficients $\to5$.` },
      { t: "Factor", body: r`$\displaystyle\lim_{x\to1}\dfrac{x^2+x-2}{x-1}$.\soln $\dfrac{(x+2)(x-1)}{x-1}=x+2\to3$.` },
    ],
    questions: [
      { ask: r`$\displaystyle\lim_{x\to5}(3x-2)$?` },
      { ask: r`$\displaystyle\lim_{x\to2}\dfrac{x^2-4}{x-2}$?` },
      { ask: r`$\displaystyle\lim_{x\to\infty}\dfrac{4x-1}{2x+3}$?` },
      { ask: r`$\displaystyle\lim_{x\to1}\dfrac{x^2-1}{x-1}$?` },
      { ask: r`Does $\displaystyle\lim_{x\to0}\dfrac1x$ exist?` },
      { ask: r`$\displaystyle\lim_{x\to-2}\dfrac{x^2-4}{x+2}$?` },
      { ask: r`$\displaystyle\lim_{x\to\infty}\dfrac{2x^2+1}{x^2-3}$?` },
      { ask: r`$\displaystyle\lim_{x\to0}\dfrac{\sqrt{x+4}-2}{x}$?` },
      { ask: r`$\displaystyle\lim_{x\to3}(x^2-2x)$?` },
      { ask: r`$\displaystyle\lim_{x\to4}\dfrac{x^2-16}{x-4}$?` },
      { ask: r`$\displaystyle\lim_{x\to\infty}\dfrac{x+5}{x^2+1}$?` },
      { ask: r`$\displaystyle\lim_{x\to2}\dfrac{x^2+x-6}{x-2}$?` },
      { ask: r`$\displaystyle\lim_{x\to0}\dfrac{\sqrt{x+1}-1}{x}$ (rationalize).`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$13$`, r`$4$`, r`$2$`, r`$2$`, r`no ($\pm\infty$)`, r`$-4$`, r`$2$`, r`$\tfrac14$`, r`$3$`, r`$8$`, r`$0$`, r`$5$`, r`$\tfrac12$`],
  },
  {
    code: "1.3", unit: U, title: "Continuity & Limit Laws",
    intro: r`Continuous at $a$: $f(a)$ defined, the limit exists, and they are equal. Discontinuities are removable, jump, or infinite.`,
    ideas: [r`Three conditions: $f(a)$ defined, limit exists, $\lim=f(a)$.`, r`Removable (hole), jump (one-sided differ), infinite (asymptote).`, r`Limit laws split sums, products and quotients.`],
    examples: [
      { t: "Verify continuity", body: r`Is $f(x)=x^2+1$ continuous at $x=2$?\soln $f(2)=5$ and $\lim_{x\to2}(x^2+1)=5$; equal, so yes.` },
      { t: "Removable", body: r`Classify the discontinuity of $\dfrac{x^2-4}{x-2}$ at $x=2$.\soln $f(2)$ undefined but the limit is $4$: removable (a hole).` },
      { t: "Infinite", body: r`Classify the discontinuity of $\dfrac1{x-3}$ at $x=3$.\soln One-sided limits are $\pm\infty$: infinite (vertical asymptote):` + r`\eplot{-1}{7}{-6}{6}{\addplot[exblue,very thick,domain=-1:2.82,samples=120]{1/(x-3)};\addplot[exblue,very thick,domain=3.18:7,samples=120]{1/(x-3)};\draw[dashed,gray] (axis cs:3,-6)--(axis cs:3,6);}` },
      { t: "Jump", body: r`For $f(x)=\begin{cases}x,&x<1\\x+2,&x\ge1\end{cases}$, what happens at $x=1$?\soln Left limit $1$, right limit $3$: a jump discontinuity.` },
      { t: "Make it continuous", body: r`Find $k$ so $f(x)=\begin{cases}x^2,&x\le2\\kx,&x>2\end{cases}$ is continuous at $2$.\soln $2^2=2k\Rightarrow k=2$.` },
      { t: "Where discontinuous", body: r`Where is $\dfrac1{x^2-9}$ discontinuous?\soln $x^2-9=0\Rightarrow x=3,-3$.` },
      { t: "Removable", body: r`Classify $\dfrac{x^2-1}{x-1}$ at $x=1$.\soln Removable (hole at $(1,2)$).` },
      { t: "Limit laws", body: r`$\displaystyle\lim_{x\to2}(3x^2-x)$.\soln $3(4)-2=10$.` },
      { t: "Domain & continuity", body: r`Where is $\sqrt{x}$ continuous?\soln On its domain $x\ge0$.` },
    ],
    questions: [
      { ask: r`Is $\dfrac{x+1}{x-2}$ continuous at $x=2$?` },
      { ask: r`Classify the discontinuity of $\dfrac{x^2-1}{x-1}$ at $x=1$.` },
      { ask: r`$\displaystyle\lim_{x\to3}(2x^2-x)$?` },
      { ask: r`Find $k$: $\begin{cases}3x,&x<1\\x+k,&x\ge1\end{cases}$ continuous at $1$.` },
      { ask: r`Where is $\dfrac1{x^2-4}$ discontinuous?` },
      { ask: r`Classify the discontinuity of $\dfrac1{x+5}$ at $x=-5$.` },
      { ask: r`Is $f(x)=x^3-2x$ continuous at $x=0$?` },
      { ask: r`$\displaystyle\lim_{x\to1}(4x^2+2x)$?` },
      { ask: r`Find $k$: $\begin{cases}x^2,&x\le3\\kx,&x>3\end{cases}$ continuous at $3$.` },
      { ask: r`Where is $\dfrac{x}{x^2-x}$ discontinuous?` },
      { ask: r`Classify the discontinuity of $\dfrac{x^2-9}{x-3}$ at $x=3$.` },
      { ask: r`State the three conditions for continuity at $a$.` },
      { ask: r`For $\begin{cases}x^2+1,&x<2\\ax+1,&x\ge2\end{cases}$, find $a$ making it continuous at $2$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`no (infinite)`, r`removable`, r`$15$`, r`$k=2$`, r`$x=\pm2$`, r`infinite`, r`yes`, r`$6$`, r`$k=3$`, r`$x=0,1$`, r`removable`, r`$f(a)$ defined, limit exists, equal`, r`$5=2a+1\Rightarrow a=2$`],
  },
  {
    code: "1.4", unit: U, title: "The Derivative from First Principles",
    intro: r`$f'(x)=\displaystyle\lim_{h\to0}\dfrac{f(x+h)-f(x)}{h}$. Expand, simplify to cancel $h$, then let $h\to0$.`,
    ideas: [r`$f'(x)=\displaystyle\lim_{h\to0}\dfrac{f(x+h)-f(x)}{h}$.`, r`Combine fractions / rationalize so $h$ cancels.`, r`Tangent line at $a$: $y-f(a)=f'(a)(x-a)$.`],
    examples: [
      { t: "Polynomial", body: r`Differentiate $f(x)=x^2$ from first principles.\soln $\dfrac{(x+h)^2-x^2}{h}=2x+h\to f'(x)=2x$.` },
      { t: "Polynomial", body: r`Differentiate $f(x)=3x^2-x$ from first principles.\soln Numerator $=6xh+3h^2-h$; divide by $h$ and let $h\to0$: $f'(x)=6x-1$.` },
      { t: "Reciprocal", body: r`Differentiate $f(x)=\dfrac1x$ from first principles.\soln $\dfrac{\frac1{x+h}-\frac1x}{h}=\dfrac{-1}{x(x+h)}\to f'(x)=-\dfrac1{x^2}$.` },
      { t: "Tangent line", body: r`Find the tangent to $y=x^2$ at $x=3$.\soln $f'(3)=6$, point $(3,9)$: $y=6x-9$:` + r`\eplot{-1}{5}{-2}{12}{\addplot[exblue,very thick,domain=-1.4:3.4]{x^2};\addplot[qorange,thick,domain=1.2:5]{6*x-9};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(3,9)};}` },
      { t: "Radical", body: r`Differentiate $f(x)=\sqrt{x}$ from first principles.\soln Rationalize: $\dfrac{1}{\sqrt{x+h}+\sqrt{x}}\to f'(x)=\dfrac1{2\sqrt{x}}$.` },
      { t: "Polynomial", body: r`Differentiate $f(x)=x^2+5x$ from first principles.\soln $\dfrac{(x+h)^2+5(x+h)-(x^2+5x)}{h}=2x+5+h\to 2x+5$.` },
      { t: "Polynomial", body: r`Differentiate $f(x)=2x^2$ from first principles.\soln $\dfrac{2(x+h)^2-2x^2}{h}=4x+2h\to4x$.` },
      { t: "Tangent line", body: r`Find the tangent to $y=x^2$ at $x=1$.\soln $f'(1)=2$, point $(1,1)$: $y=2x-1$.` },
      { t: "Linear", body: r`Differentiate $f(x)=5x-3$ from first principles.\soln $\dfrac{5(x+h)-3-(5x-3)}{h}=5\to f'(x)=5$.` },
    ],
    questions: [
      { ask: r`Differentiate $f(x)=x^2$ from first principles.` },
      { ask: r`Differentiate $f(x)=x^2+5x$ from first principles.` },
      { ask: r`Differentiate $f(x)=2x^2$ from first principles.` },
      { ask: r`Find the tangent to $y=x^2$ at $x=1$.` },
      { ask: r`Differentiate $f(x)=5x-3$ from first principles.` },
      { ask: r`Differentiate $f(x)=4x^2-x$ from first principles.` },
      { ask: r`Differentiate $f(x)=\dfrac1x$ from first principles.` },
      { ask: r`Find the tangent to $y=x^2$ at $x=2$.` },
      { ask: r`Differentiate $f(x)=x^2-3x$ from first principles.` },
      { ask: r`Differentiate $f(x)=7$ from first principles.` },
      { ask: r`Find the tangent to $y=x^2$ at $x=-1$.` },
      { ask: r`Differentiate $f(x)=3x^2$ from first principles.` },
      { ask: r`Differentiate $f(x)=\sqrt{x}$ from first principles (rationalize).`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$2x$`, r`$2x+5$`, r`$4x$`, r`$y=2x-1$`, r`$5$`, r`$8x-1$`, r`$-\tfrac1{x^2}$`, r`$y=4x-4$`, r`$2x-3$`, r`$0$`, r`$y=-2x-1$`, r`$6x$`, r`$\tfrac1{2\sqrt{x}}$`],
  },
];
