// MCV4U Unit 2 worksheets — Derivative Rules. Full \soln + f/f' figures.
const r = String.raw;
const U = "2: Derivative Rules";

export default [
  {
    code: "2.1", unit: U, title: "Power, Constant & Sum Rules",
    intro: r`$\dfrac{d}{dx}x^n=nx^{n-1}$, with the constant-multiple and sum/difference rules, differentiates any polynomial. Rewrite radicals and reciprocals as powers first.`,
    ideas: [r`Power: $\dfrac{d}{dx}x^n=nx^{n-1}$; constant: $\dfrac{d}{dx}c=0$.`, r`Constant multiple and sum/difference rules.`, r`Rewrite $\sqrt{x}=x^{1/2}$, $\dfrac1{x^k}=x^{-k}$.`],
    examples: [
      { t: "Power rule", body: r`Differentiate $f(x)=x^5$.\soln $f'(x)=5x^4$.` },
      { t: "Whole polynomial", body: r`Differentiate $f(x)=3x^4-2x^2+7$.\soln $f'(x)=12x^3-4x$ (the constant vanishes). $f$ and $f'$ for $x^3-3x$ illustrate the idea — $f'$ is zero at the turning points:` + r`\eplot{-3}{3}{-6}{6}{\addplot[exblue,very thick,domain=-2.2:2.2]{x^3-3*x};\addplot[qorange,very thick,domain=-1.7:1.7]{3*x^2-3};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-1,0) (1,0)};}` },
      { t: "Negative & fractional", body: r`Differentiate $f(x)=\sqrt{x}+\dfrac1{x^2}$.\soln $x^{1/2}+x^{-2}\Rightarrow \tfrac12x^{-1/2}-2x^{-3}=\dfrac1{2\sqrt{x}}-\dfrac2{x^3}$.` },
      { t: "Slope at a point", body: r`Slope of the tangent to $f(x)=x^3-3x$ at $x=2$.\soln $f'(x)=3x^2-3\Rightarrow f'(2)=9$.` },
      { t: "Horizontal tangent", body: r`Where does $f(x)=x^3-3x$ have a horizontal tangent?\soln $3x^2-3=0\Rightarrow x=\pm1$.` },
      { t: "Power rule", body: r`Differentiate $f(x)=x^7$.\soln $7x^6$.` },
      { t: "Polynomial", body: r`Differentiate $f(x)=4x^3-6x^2+x-9$.\soln $12x^2-12x+1$.` },
      { t: "Reciprocal power", body: r`Differentiate $f(x)=\dfrac1{x^3}$.\soln $x^{-3}\to-3x^{-4}=-\dfrac3{x^4}$.` },
      { t: "Evaluate a derivative", body: r`Find $f'(1)$ for $f(x)=x^4-2x$.\soln $f'(x)=4x^3-2\Rightarrow f'(1)=2$.` },
    ],
    questions: [
      { ask: r`Differentiate $f(x)=x^9$.` },
      { ask: r`Differentiate $f(x)=2x^5-3x^3+4$.` },
      { ask: r`Differentiate $f(x)=\dfrac1{x^2}$.` },
      { ask: r`Differentiate $f(x)=\sqrt{x}$.` },
      { ask: r`Find $f'(2)$ for $f(x)=x^3-x$.` },
      { ask: r`Where does $f(x)=x^2-6x$ have a horizontal tangent?` },
      { ask: r`Differentiate $f(x)=5x^4-x$.` },
      { ask: r`Differentiate $f(x)=x^{1/3}$.` },
      { ask: r`Find $f'(0)$ for $f(x)=x^3+2x+1$.` },
      { ask: r`Differentiate $f(x)=\dfrac3{x}$.` },
      { ask: r`Where is the tangent to $f(x)=x^3-12x$ horizontal?` },
      { ask: r`Differentiate $f(x)=6\sqrt{x}$.` },
      { ask: r`Find the equation of the tangent to $f(x)=x^2-2x$ at $x=3$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$9x^8$`, r`$10x^4-9x^2$`, r`$-\tfrac2{x^3}$`, r`$\tfrac1{2\sqrt{x}}$`, r`$3(4)-1=11$`, r`$x=3$`, r`$20x^3-1$`, r`$\tfrac13x^{-2/3}$`, r`$2$`, r`$-\tfrac3{x^2}$`, r`$x=\pm2$`, r`$\tfrac3{\sqrt{x}}$`, r`$f'(3)=4$, point $(3,3)$: $y=4x-9$`],
  },
  {
    code: "2.2", unit: U, title: "Product & Quotient Rules",
    intro: r`Product: $(fg)'=f'g+fg'$. Quotient: $\left(\dfrac fg\right)'=\dfrac{f'g-fg'}{g^2}$ — top derivative first.`,
    ideas: [r`$(fg)'=f'g+fg'$ (not $f'g'$).`, r`$\left(\dfrac fg\right)'=\dfrac{f'g-fg'}{g^2}$.`, r`If expanding is easy, expand and use the power rule.`],
    examples: [
      { t: "Product rule", body: r`Differentiate $f(x)=x^2(x+1)$.\soln $2x(x+1)+x^2(1)=3x^2+2x$ (check: $x^3+x^2\to3x^2+2x$).` },
      { t: "Two factors", body: r`Differentiate $f(x)=(2x+1)(x^2-3)$.\soln $2(x^2-3)+(2x+1)(2x)=6x^2+2x-6$.` },
      { t: "Quotient rule", body: r`Differentiate $f(x)=\dfrac{x+1}{x-1}$.\soln $\dfrac{(x-1)-(x+1)}{(x-1)^2}=\dfrac{-2}{(x-1)^2}$.` },
      { t: "Polynomial over linear", body: r`Differentiate $f(x)=\dfrac{x^2}{x+1}$.\soln $\dfrac{2x(x+1)-x^2}{(x+1)^2}=\dfrac{x^2+2x}{(x+1)^2}$.` },
      { t: "From a table", body: r`Given $f(2)=3,f'(2)=1,g(2)=4,g'(2)=-2$, find $(fg)'(2)$.\soln $(1)(4)+(3)(-2)=-2$.` },
      { t: "Product rule", body: r`Differentiate $f(x)=x^3(x-2)$.\soln $3x^2(x-2)+x^3=4x^3-6x^2$.` },
      { t: "Two factors", body: r`Differentiate $f(x)=(x+2)(x^2+1)$.\soln $(x^2+1)+(x+2)(2x)=3x^2+4x+1$.` },
      { t: "Quotient rule", body: r`Differentiate $f(x)=\dfrac{x}{x+2}$.\soln $\dfrac{(x+2)-x}{(x+2)^2}=\dfrac{2}{(x+2)^2}$.` },
      { t: "Quotient rule", body: r`Differentiate $f(x)=\dfrac{x-1}{x+1}$.\soln $\dfrac{(x+1)-(x-1)}{(x+1)^2}=\dfrac{2}{(x+1)^2}$.` },
    ],
    questions: [
      { ask: r`Differentiate $f(x)=x^2(x-3)$.` },
      { ask: r`Differentiate $f(x)=(3x-1)(x+2)$.` },
      { ask: r`Differentiate $f(x)=\dfrac{x+2}{x-2}$.` },
      { ask: r`Differentiate $f(x)=\dfrac{x^2}{x-1}$.` },
      { ask: r`With $f(1)=2,f'(1)=3,g(1)=5,g'(1)=-1$, find $(fg)'(1)$.` },
      { ask: r`Differentiate $f(x)=x^4(2x+1)$.` },
      { ask: r`Differentiate $f(x)=(x^2+1)(x-4)$.` },
      { ask: r`Differentiate $f(x)=\dfrac{2x}{x+3}$.` },
      { ask: r`Differentiate $f(x)=\dfrac{1}{x^2+1}$ (quotient rule).` },
      { ask: r`Differentiate $f(x)=x(x^2-5)$.` },
      { ask: r`With $f(0)=1,f'(0)=2,g(0)=3,g'(0)=4$, find $\left(\tfrac fg\right)'(0)$.` },
      { ask: r`Differentiate $f(x)=(x-1)(x+1)$ two ways (rule and expansion).` },
      { ask: r`Find the tangent to $f(x)=\dfrac{x}{x+1}$ at $x=1$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$3x^2-6x$`, r`$6x+5$`, r`$\dfrac{-4}{(x-2)^2}$`, r`$\dfrac{x^2-2x}{(x-1)^2}$`, r`$(3)(5)+(2)(-1)=13$`, r`$10x^4+4x^3$`, r`$3x^2-8x+1$`, r`$\dfrac{6}{(x+3)^2}$`, r`$\dfrac{-2x}{(x^2+1)^2}$`, r`$3x^2-5$`, r`$\dfrac{(2)(3)-(1)(4)}{9}=\tfrac29$`, r`both give $2x$`, r`$f'(1)=\tfrac14$, point $(1,\tfrac12)$: $y=\tfrac14x+\tfrac14$`],
  },
  {
    code: "2.3", unit: U, title: "The Chain Rule",
    intro: r`$\dfrac{d}{dx}f(g(x))=f'(g(x))\cdot g'(x)$ — derivative of the outside (inside untouched) times the derivative of the inside.`,
    ideas: [r`Chain rule: $f'(g(x))\cdot g'(x)$.`, r`Power of a function: $\dfrac{d}{dx}[g(x)]^n=n[g(x)]^{n-1}g'(x)$.`, r`Don't forget the inner derivative $g'(x)$.`],
    examples: [
      { t: "Power of a function", body: r`Differentiate $f(x)=(x^2+1)^3$.\soln $3(x^2+1)^2\cdot2x=6x(x^2+1)^2$.` },
      { t: "Radical", body: r`Differentiate $f(x)=\sqrt{x^2+1}$.\soln $\tfrac12(x^2+1)^{-1/2}\cdot2x=\dfrac{x}{\sqrt{x^2+1}}$.` },
      { t: "Linear inside", body: r`Differentiate $f(x)=(3x-2)^5$.\soln $5(3x-2)^4\cdot3=15(3x-2)^4$.` },
      { t: "Cubic inside", body: r`Differentiate $f(x)=(x^3+x)^4$.\soln $4(x^3+x)^3(3x^2+1)$.` },
      { t: "Chain inside a product", body: r`Differentiate $f(x)=x(2x+1)^3$.\soln $(2x+1)^3+x\cdot3(2x+1)^2\cdot2=(2x+1)^2(8x+1)$.` },
      { t: "Power of a function", body: r`Differentiate $f(x)=(x^2-4)^3$.\soln $6x(x^2-4)^2$.` },
      { t: "Linear inside", body: r`Differentiate $f(x)=(5x+1)^4$.\soln $20(5x+1)^3$.` },
      { t: "Radical", body: r`Differentiate $f(x)=\sqrt{2x+1}$.\soln $\dfrac1{\sqrt{2x+1}}$.` },
      { t: "Reciprocal power", body: r`Differentiate $f(x)=\dfrac1{(x+1)^2}$.\soln $(x+1)^{-2}\to-2(x+1)^{-3}=\dfrac{-2}{(x+1)^3}$.` },
    ],
    questions: [
      { ask: r`Differentiate $f(x)=(x^2+3)^4$.` },
      { ask: r`Differentiate $f(x)=(4x-1)^3$.` },
      { ask: r`Differentiate $f(x)=\sqrt{x^2+9}$.` },
      { ask: r`Differentiate $f(x)=(x^3-x)^5$.` },
      { ask: r`Differentiate $f(x)=\dfrac1{(2x+1)^2}$.` },
      { ask: r`Differentiate $f(x)=(1-x^2)^4$.` },
      { ask: r`Differentiate $f(x)=\sqrt{3x-2}$.` },
      { ask: r`Differentiate $f(x)=(x^2+x+1)^3$.` },
      { ask: r`Differentiate $f(x)=x^2(x+1)^3$.` },
      { ask: r`Differentiate $f(x)=(2x+5)^6$.` },
      { ask: r`Differentiate $f(x)=\dfrac{1}{\sqrt{x+4}}$.` },
      { ask: r`Differentiate $f(x)=(x^2-1)^{1/2}$.` },
      { ask: r`Differentiate $f(x)=\dfrac{(x+1)^2}{x}$ (chain + quotient).`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$8x(x^2+3)^3$`, r`$12(4x-1)^2$`, r`$\dfrac{x}{\sqrt{x^2+9}}$`, r`$5(x^3-x)^4(3x^2-1)$`, r`$\dfrac{-4}{(2x+1)^3}$`, r`$-8x(1-x^2)^3$`, r`$\dfrac3{2\sqrt{3x-2}}$`, r`$3(x^2+x+1)^2(2x+1)$`, r`$2x(x+1)^3+3x^2(x+1)^2$`, r`$12(2x+5)^5$`, r`$-\tfrac12(x+4)^{-3/2}$`, r`$\dfrac{x}{\sqrt{x^2-1}}$`, r`$\dfrac{2x(x+1)\cdot x-(x+1)^2}{x^2}=\dfrac{(x+1)(x-1)}{x^2}$`],
  },
  {
    code: "2.4", unit: U, title: "Rational, Radical & Higher-Order Derivatives",
    intro: r`Rewrite as powers; differentiate again for $f''$; use implicit differentiation when $y$ is tangled with $x$.`,
    ideas: [r`Rewrite: $\dfrac1{x^k}=x^{-k}$, $\sqrt[n]{x^m}=x^{m/n}$.`, r`Second derivative $f''=(f')'$.`, r`Implicit: differentiate both sides, attach $\tfrac{dy}{dx}$ to every $y$.`],
    examples: [
      { t: "Rational via powers", body: r`Differentiate $f(x)=\dfrac1{x^2}$.\soln $x^{-2}\to-2x^{-3}=-\dfrac2{x^3}$.` },
      { t: "Radical via powers", body: r`Differentiate $f(x)=\sqrt[3]{x^2}$.\soln $x^{2/3}\to\tfrac23x^{-1/3}=\dfrac2{3\sqrt[3]{x}}$.` },
      { t: "Second derivative", body: r`Find $f''(x)$ for $f(x)=x^4$.\soln $f'=4x^3,\ f''=12x^2$. For $x^3$: $f,f',f''$ are $x^3,3x^2,6x$ — each the slope of the previous:` + r`\eplot{-2.5}{2.5}{-8}{8}{\addplot[exblue,very thick,domain=-2:2]{x^3};\addplot[qorange,very thick,domain=-1.6:1.6]{3*x^2};\addplot[red,very thick,domain=-1.3:1.3]{6*x};}` },
      { t: "Second derivative", body: r`Find $f''(x)$ for $f(x)=x^3-3x$ and $f''(1)$.\soln $f'=3x^2-3,\ f''=6x,\ f''(1)=6$.` },
      { t: "Implicit differentiation", body: r`Find $\dfrac{dy}{dx}$ for $x^2+y^2=25$.\soln $2x+2yy'=0\Rightarrow y'=-\dfrac xy$.` },
      { t: "Rational via powers", body: r`Differentiate $f(x)=\dfrac1{x^4}$.\soln $x^{-4}\to-4x^{-5}=-\dfrac4{x^5}$.` },
      { t: "Radical via powers", body: r`Differentiate $f(x)=x^{3/2}$.\soln $\tfrac32x^{1/2}$.` },
      { t: "Second derivative", body: r`Find $f''(x)$ for $f(x)=2x^3-x^2$.\soln $f'=6x^2-2x,\ f''=12x-2$.` },
      { t: "Implicit differentiation", body: r`Find $\dfrac{dy}{dx}$ for $xy=4$.\soln Product rule: $y+xy'=0\Rightarrow y'=-\dfrac yx$.` },
    ],
    questions: [
      { ask: r`Differentiate $f(x)=\dfrac1{x^5}$.` },
      { ask: r`Differentiate $f(x)=\sqrt[3]{x}$.` },
      { ask: r`Find $f''(x)$ for $f(x)=x^5$.` },
      { ask: r`Find $f''(x)$ for $f(x)=x^4-2x^2$.` },
      { ask: r`Find $\dfrac{dy}{dx}$ for $x^2+y^2=9$.` },
      { ask: r`Differentiate $f(x)=x^{5/2}$.` },
      { ask: r`Find $f''(1)$ for $f(x)=x^3$.` },
      { ask: r`Find $f''(x)$ for $f(x)=3x^4$.` },
      { ask: r`Find $\dfrac{dy}{dx}$ for $x^2-y^2=1$.` },
      { ask: r`Differentiate $f(x)=\dfrac2{x^3}$.` },
      { ask: r`Find $f''(x)$ for $f(x)=x^3-6x^2+2x$.` },
      { ask: r`Find $\dfrac{dy}{dx}$ for $xy=10$.` },
      { ask: r`Find $\dfrac{dy}{dx}$ for $x^2+xy+y^2=7$ (product rule on $xy$).`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$-\tfrac5{x^6}$`, r`$\tfrac13x^{-2/3}$`, r`$f''=20x^3$`, r`$f''=12x^2-4$`, r`$-\tfrac xy$`, r`$\tfrac52x^{3/2}$`, r`$f''=6x\Rightarrow6$`, r`$f''=36x^2$`, r`$\tfrac xy$`, r`$-\tfrac6{x^4}$`, r`$f''=6x-12$`, r`$-\tfrac yx$`, r`$2x+y+xy'+2yy'=0\Rightarrow y'=-\dfrac{2x+y}{x+2y}$`],
  },
];
