// MCV4U Unit 4 worksheets — Curve Sketching. Full \soln + f/f'/f'' figures.
const r = String.raw;
const U = "4: Curve Sketching";

const ffp = r`\eplot{-3}{3}{-6}{6}{\addplot[exblue,very thick,domain=-2.2:2.2]{x^3-3*x};\addplot[qorange,very thick,domain=-1.7:1.7]{3*x^2-3};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-1,2) (1,-2)};}`;
const fpp = r`\eplot{-2.5}{2.5}{-8}{8}{\addplot[exblue,very thick,domain=-2:2]{x^3};\addplot[qorange,very thick,domain=-1.3:1.3]{6*x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,0)};}`;
const cubic2 = r`\eplot{-1.5}{4}{-6}{4}{\addplot[exblue,very thick,domain=-1:3.3]{x^3-3*x^2};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,0) (2,-4) (1,-2)};}`;
const sketch = r`\eplot{-3}{3}{-4}{4}{\addplot[exblue,very thick,domain=-2.1:2.1]{x^3-3*x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-1,2) (1,-2) (0,0)};}`;

export default [
  {
    code: "4.1", unit: U, title: "Increasing/Decreasing & the First Derivative Test",
    intro: r`$f$ increases where $f'>0$ and decreases where $f'<0$. Critical numbers ($f'=0$ or undefined) are classified by how $f'$ changes sign.`,
    ideas: [r`Increasing: $f'>0$; decreasing: $f'<0$.`, r`Critical numbers: $f'=0$ or undefined.`, r`1st-derivative test: $+\to-$ max, $-\to+$ min, no change ⇒ neither.`],
    examples: [
      { t: "Intervals", body: r`Where is $f(x)=x^2-4x$ increasing/decreasing?\soln $f'=2x-4$; decreasing on $(-\infty,2)$, increasing on $(2,\infty)$.` },
      { t: "Critical numbers", body: r`Critical numbers of $f(x)=x^3-3x$.\soln $3x^2-3=0\Rightarrow x=\pm1$. $f$ rises where $f'>0$, falls where $f'<0$:` + ffp },
      { t: "Classify", body: r`Classify the critical points of $f(x)=x^3-3x$.\soln $x=-1$: $+\to-$, local max $(-1,2)$; $x=1$: $-\to+$, local min $(1,-2)$.` },
      { t: "Neither", body: r`Classify the critical point of $f(x)=x^3$.\soln $f'=3x^2=0$ at $0$, but no sign change ⇒ neither (inflection).` },
      { t: "Several", body: r`Find and classify the critical points of $f(x)=x^4-2x^2$.\soln $4x(x-1)(x+1)=0\Rightarrow x=0,\pm1$; signs $-,+,-,+$: min at $\pm1$ ($-1$), max at $0$ ($0$).` },
      { t: "Intervals", body: r`Where is $f(x)=x^2-6x$ decreasing?\soln $2x-6<0\Rightarrow x<3$.` },
      { t: "Critical numbers", body: r`Critical numbers of $f(x)=x^3-12x$.\soln $3x^2-12=0\Rightarrow x=\pm2$.` },
      { t: "Always increasing", body: r`Is $f(x)=x^3+x$ ever decreasing?\soln $f'=3x^2+1>0$ always — never decreasing.` },
      { t: "Classify", body: r`Classify the critical point of $f(x)=x^2-4x$.\soln $x=2$: $-\to+$, local min.` },
    ],
    questions: [
      { ask: r`Where is $f(x)=x^2-6x$ increasing?` },
      { ask: r`Critical numbers of $f(x)=x^3-12x$?` },
      { ask: r`Classify the critical points of $f(x)=x^2-4x$.` },
      { ask: r`Is $f(x)=x^3+x$ ever decreasing?` },
      { ask: r`Critical numbers of $f(x)=x^4-2x^2$?` },
      { ask: r`Where is $f(x)=x^2+2x$ decreasing?` },
      { ask: r`Critical numbers of $f(x)=x^3-3x^2$?` },
      { ask: r`At a critical number $f'$ goes $-\to+$. What is it?` },
      { ask: r`Classify the critical point of $f(x)=x^3$.` },
      { ask: r`Where is $f(x)=x^3-3x$ increasing?` },
      { ask: r`Is $f(x)=-x^2$ increasing or decreasing for $x>0$?` },
      { ask: r`Local max value of $f(x)=x^3-3x$?` },
      { ask: r`Find and classify all critical points of $f(x)=x^3-6x^2+9x$.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$x>3$`, r`$x=\pm2$`, r`local min at $x=2$`, r`no ($f'=3x^2+1>0$)`, r`$0,\pm1$`, r`$x<-1$`, r`$0,2$`, r`local min`, r`neither (inflection)`, r`$|x|>1$`, r`decreasing`, r`$2$ (at $x=-1$)`, r`$f'=3x^2-12x+9=3(x-1)(x-3)$: max $(1,4)$, min $(3,0)$`],
  },
  {
    code: "4.2", unit: U, title: "Concavity & the Second Derivative",
    intro: r`$f''>0$ concave up, $f''<0$ concave down; inflection where $f''$ changes sign. 2nd-derivative test: $f''(c)>0$ min, $f''(c)<0$ max.`,
    ideas: [r`Concave up: $f''>0$; down: $f''<0$.`, r`Inflection: $f''$ changes sign.`, r`2nd-derivative test classifies critical points.`],
    examples: [
      { t: "Always concave up", body: r`Concavity of $f(x)=x^2$.\soln $f''=2>0$: concave up everywhere.` },
      { t: "Switches", body: r`Concavity of $f(x)=x^3$.\soln $f''=6x$: down for $x<0$, up for $x>0$, inflection at $(0,0)$:` + fpp },
      { t: "2nd-derivative test", body: r`Classify the critical point of $f(x)=x^2-4x$.\soln $f'=2x-4=0\Rightarrow x=2$; $f''=2>0$: local min.` },
      { t: "Inflection", body: r`Inflection point of $f(x)=x^3-3x^2$.\soln $f''=6x-6=0\Rightarrow x=1$; $f(1)=-2$: $(1,-2)$.` },
      { t: "Classify all", body: r`Use $f''$ on $f(x)=x^4-2x^2$.\soln $f''=12x^2-4$; $f''(0)=-4$ (max), $f''(\pm1)=8$ (min).` },
      { t: "Concave down", body: r`Concavity of $f(x)=-x^2$.\soln $f''=-2<0$: concave down everywhere.` },
      { t: "Concave up where", body: r`Where is $f(x)=x^3$ concave up?\soln $6x>0\Rightarrow x>0$.` },
      { t: "2nd-derivative test", body: r`Classify the critical point of $f(x)=x^2+6x$.\soln $x=-3$; $f''=2>0$: local min.` },
      { t: "Inflection", body: r`Inflection point of $f(x)=x^3-6x^2$.\soln $f''=6x-12=0\Rightarrow x=2$; $f(2)=-16$: $(2,-16)$.` },
    ],
    questions: [
      { ask: r`Concavity of $f(x)=-x^2$?` },
      { ask: r`Where is $f(x)=x^3$ concave up?` },
      { ask: r`Use the 2nd-derivative test on $f(x)=x^2+6x$.` },
      { ask: r`Inflection point of $f(x)=x^3-6x^2$?` },
      { ask: r`At a critical point $f''(c)<0$. What is it?` },
      { ask: r`Concavity of $f(x)=x^2+1$?` },
      { ask: r`Inflection point of $f(x)=x^3$?` },
      { ask: r`Use $f''$ to classify $x=0$ for $f(x)=x^4-2x^2$.` },
      { ask: r`Where is $f(x)=x^3-3x^2$ concave down?` },
      { ask: r`$f''(2)>0$ and $f'(2)=0$: classify $x=2$.` },
      { ask: r`Concavity of $f(x)=x^3$ at $x=-1$?` },
      { ask: r`Inflection point of $f(x)=x^3-3x$?` },
      { ask: r`Find the intervals of concavity and the inflection point of $f(x)=x^3-3x^2+1$.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`concave down everywhere`, r`$x>0$`, r`min at $x=-3$`, r`$(2,-16)$`, r`local max`, r`concave up`, r`$(0,0)$`, r`max ($f''=-4<0$)`, r`$x<1$`, r`local min`, r`concave down`, r`$(0,0)$`, r`$f''=6x-6$: down on $x<1$, up on $x>1$, inflection $(1,-1)$`],
  },
  {
    code: "4.3", unit: U, title: "Critical, Inflection & End Behaviour",
    intro: r`Gather all features before sketching: domain, intercepts, asymptotes, extrema (from $f'$), inflection/concavity (from $f''$), and end behaviour.`,
    ideas: [r`From $f'$: increase/decrease and extrema.`, r`From $f''$: concavity and inflection.`, r`From $f$: domain, intercepts, asymptotes, end behaviour.`],
    examples: [
      { t: "List features", body: r`Key features of $f(x)=x^3-3x^2$.\soln Max $(0,0)$, min $(2,-4)$, inflection $(1,-2)$, ends down–up:` + cubic2 },
      { t: "Read f from f'", body: r`$f'>0$ on $(-\infty,1)$, $f'<0$ on $(1,\infty)$. Describe $f$ near $x=1$.\soln $+\to-$ ⇒ local max at $x=1$.` },
      { t: "Classify from f''", body: r`$f'(2)=0$ and $f''(2)=-3$. Classify $x=2$.\soln $f''<0$ ⇒ local maximum.` },
      { t: "Rational asymptotes", body: r`Asymptotes of $f(x)=\dfrac{x}{x-2}$.\soln VA $x=2$; equal degrees ⇒ HA $y=1$.` },
      { t: "Inflection, not extremum", body: r`Inflection of $f(x)=x^3+1$; why no extremum?\soln $f''=6x=0\Rightarrow(0,1)$ inflection; $f'=3x^2\ge0$ ⇒ no max/min.` },
      { t: "Critical numbers", body: r`Critical numbers of $f(x)=x^3-3x^2$.\soln $3x^2-6x=0\Rightarrow x=0,2$.` },
      { t: "Classify from f''", body: r`$f'(3)=0,\ f''(3)>0$. Classify $x=3$.\soln Local minimum.` },
      { t: "Inflection", body: r`Inflection of $f(x)=x^3-3x^2$.\soln $(1,-2)$.` },
      { t: "End behaviour", body: r`End behaviour of $f(x)=-x^3+2x$.\soln Odd, $a<0$: up–down.` },
    ],
    questions: [
      { ask: r`Critical numbers of $f(x)=x^3-3x^2$?` },
      { ask: r`If $f'(3)=0$ and $f''(3)>0$, classify $x=3$.` },
      { ask: r`Inflection point of $f(x)=x^3-3x^2$?` },
      { ask: r`Asymptotes of $f(x)=\dfrac1{x-3}$?` },
      { ask: r`End behaviour of $f(x)=-x^3+2x$?` },
      { ask: r`Local extrema of $f(x)=x^3-3x$?` },
      { ask: r`Asymptotes of $f(x)=\dfrac{x}{x-2}$?` },
      { ask: r`If $f'(1)=0$ and $f''(1)<0$, classify $x=1$.` },
      { ask: r`Inflection point of $f(x)=x^3$?` },
      { ask: r`End behaviour of $f(x)=x^4-1$?` },
      { ask: r`Where is $f(x)=x^3-3x^2$ increasing?` },
      { ask: r`Does $f(x)=x^3+1$ have a local extremum?` },
      { ask: r`List every key feature of $f(x)=x^3-3x$ (intercepts, extrema, inflection, ends).`, challenge: true, ws: "4cm" },
    ],
    answers: [r`$x=0,2$`, r`local min`, r`$(1,-2)$`, r`VA $x=3$, HA $y=0$`, r`up–down`, r`max $(-1,2)$, min $(1,-2)$`, r`VA $x=2$, HA $y=1$`, r`local max`, r`$(0,0)$`, r`up–up`, r`$x<0$ or $x>2$`, r`no (inflection at $(0,1)$)`, r`x-int $0,\pm\sqrt3$; max $(-1,2)$; min $(1,-2)$; inflection $(0,0)$; ends down–up`],
  },
  {
    code: "4.4", unit: U, title: "Full Curve Sketching",
    intro: r`Run the checklist: domain/symmetry, intercepts, asymptotes, $f'$ (extrema), $f''$ (concavity/inflection), end behaviour — then sketch.`,
    ideas: [r`Domain, symmetry, intercepts first.`, r`$f'$ → extrema; $f''$ → inflection/concavity.`, r`Finish with end behaviour and a consistent sketch.`],
    examples: [
      { t: "Cubic", body: r`Sketch $f(x)=x^3-3x$.\soln x-ints $0,\pm\sqrt3$; max $(-1,2)$, min $(1,-2)$; inflection $(0,0)$; ends down–up:` + sketch },
      { t: "Quartic (even)", body: r`Sketch $f(x)=x^4-2x^2$.\soln Even; x-ints $0,\pm\sqrt2$; max $(0,0)$, mins $(\pm1,-1)$; inflections at $x=\pm\tfrac1{\sqrt3}$; ends up–up (a "W").` },
      { t: "Cubic", body: r`Sketch $f(x)=x^3-3x^2$.\soln x-ints $0,3$; max $(0,0)$, min $(2,-4)$; inflection $(1,-2)$; ends down–up.` },
      { t: "From clues", body: r`$f'>0$ on $(-\infty,0)\cup(2,\infty)$, $f'<0$ on $(0,2)$, $f''>0$ on $(1,\infty)$.\soln Max at $0$, min at $2$, inflection at $1$ — a cubic shape.` },
      { t: "Match f to f'", body: r`$f$ has a max at $-1$, min at $1$. What is $f'$?\soln $f'=0$ at $\pm1$, $+$ outside, $-$ inside: an upward parabola (e.g. $3x^2-3$).` },
      { t: "Intercepts", body: r`x-intercepts of $f(x)=x^3-3x$.\soln $x(x^2-3)=0\Rightarrow 0,\pm\sqrt3$.` },
      { t: "Symmetry", body: r`Is $f(x)=x^4-2x^2$ even or odd?\soln Even (only even powers).` },
      { t: "Extrema", body: r`Local extrema of $f(x)=x^3-3x^2$.\soln Max $(0,0)$, min $(2,-4)$.` },
      { t: "Always increasing", body: r`If $f'>0$ everywhere, what does the curve do?\soln Always increasing — no extrema.` },
    ],
    questions: [
      { ask: r`x-intercepts of $f(x)=x^3-3x$?` },
      { ask: r`Local extrema of $f(x)=x^3-3x^2$?` },
      { ask: r`Inflection point of $f(x)=x^3-3x$?` },
      { ask: r`Is $f(x)=x^4-2x^2$ even or odd?` },
      { ask: r`If $f'>0$ everywhere, what does the graph do?` },
      { ask: r`y-intercept of $f(x)=x^3-3x+2$?` },
      { ask: r`Local extrema of $f(x)=x^3-3x$?` },
      { ask: r`End behaviour of $f(x)=x^4-2x^2$?` },
      { ask: r`Inflection point of $f(x)=x^3-3x^2$?` },
      { ask: r`If $f$ has a min at $2$, what does $f'$ do at $2$?` },
      { ask: r`x-intercepts of $f(x)=x^4-2x^2$?` },
      { ask: r`Is $f(x)=x^3-3x$ even, odd, or neither?` },
      { ask: r`Do a full sketch analysis of $f(x)=x^3-3x^2$ (intercepts, extrema, inflection, ends).`, challenge: true, ws: "4cm" },
    ],
    answers: [r`$0,\pm\sqrt3$`, r`max $(0,0)$, min $(2,-4)$`, r`$(0,0)$`, r`even`, r`always increasing`, r`$(0,2)$`, r`max $(-1,2)$, min $(1,-2)$`, r`up–up`, r`$(1,-2)$`, r`$f'=0$, changing $-\to+$`, r`$0,\pm\sqrt2$`, r`odd`, r`x-ints $0,3$; max $(0,0)$, min $(2,-4)$; inflection $(1,-2)$; ends down–up`],
  },
];
