// MCV4U Unit 5 worksheets — Applications of Derivatives.
const r = String.raw;
const U = "5: Applications of Derivatives";

export default [
  {
    code: "5.1", unit: U, title: "Optimization",
    intro: r`Write the quantity to optimize, reduce it to one variable using the constraint, solve $Q'=0$, and verify.`,
    ideas: [r`Define a variable; write $Q$.`, r`Use the constraint to make $Q$ one-variable; state the domain.`, r`Solve $Q'=0$; verify with the 1st/2nd derivative test.`],
    examples: [
      { t: "Max area, fixed perimeter", body: r`A pen uses 40 m of fence. Maximize the area.\soln $A=x(20-x)$; $A'=20-2x=0\Rightarrow x=10$; $A''=-2<0$. Square $10\times10$, area $100$ m²:` + r`\eplot{0}{20}{0}{120}{\addplot[exblue,very thick,domain=0:20]{x*(20-x)};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(10,100)};}` },
      { t: "Wall on one side", body: r`Only 3 sides fenced with 20 m. Maximize the area.\soln $A=x(20-2x)$; $A'=20-4x=0\Rightarrow x=5$, length $10$; area $50$ m².` },
      { t: "Minimize a sum", body: r`For $x>0$, minimize $f(x)=x+\dfrac{16}{x}$.\soln $f'=1-\dfrac{16}{x^2}=0\Rightarrow x=4$; $f''>0$; min value $8$.` },
      { t: "Max-volume open box", body: r`Cut side-$x$ squares from a $12\times12$ sheet; fold into an open box. Maximize the volume.\soln $V=x(12-2x)^2$; $V'=(12-2x)(12-6x)=0\Rightarrow x=2$; $V=128$ cm³.` },
      { t: "Maximum profit", body: r`Maximize $P(x)=-2x^2+40x-100$.\soln $P'=-4x+40=0\Rightarrow x=10$; $P(10)=100$.` },
      { t: "Max product", body: r`Two positive numbers sum to 12. Maximize the product.\soln $P=x(12-x)$; $P'=12-2x=0\Rightarrow x=6$; product $36$.` },
      { t: "Max area", body: r`Maximize the area of a rectangle with 60 m of fence.\soln $15\times15$, area $225$ m².` },
      { t: "Minimize a sum", body: r`For $x>0$, minimize $f(x)=x+\dfrac{9}{x}$.\soln $1-\dfrac9{x^2}=0\Rightarrow x=3$; min value $6$.` },
      { t: "Maximum value", body: r`Maximize $P(x)=-x^2+10x$.\soln $P'=-2x+10=0\Rightarrow x=5$; $P(5)=25$.` },
    ],
    questions: [
      { ask: r`Two positive numbers sum to 20. Maximize the product.` },
      { ask: r`Maximize the area of a rectangle with 80 m of fence.` },
      { ask: r`For $x>0$, minimize $f(x)=x+\dfrac{25}{x}$.` },
      { ask: r`Maximize $P(x)=-x^2+8x$.` },
      { ask: r`A 3-sided pen uses 40 m of fence. Maximize the area.` },
      { ask: r`Two positive numbers sum to 30. Maximize the product.` },
      { ask: r`For $x>0$, minimize $f(x)=x+\dfrac{4}{x}$.` },
      { ask: r`Maximize $P(x)=-3x^2+30x$.` },
      { ask: r`Cut side-$x$ squares from a $6\times6$ sheet for an open box. Find $x$ that maximizes the volume.`, ws: "2.4cm" },
      { ask: r`Maximize the area of a rectangle with 100 m of fence.` },
      { ask: r`For $x>0$, minimize $f(x)=x+\dfrac1{x}$.` },
      { ask: r`Maximize $P(x)=-2x^2+12x-5$.` },
      { ask: r`A farmer has 240 m of fence to make two identical adjacent rectangular pens (so three lengths of fence run one way). Maximize the total area.`, challenge: true, ws: "4cm" },
    ],
    answers: [r`$10,10$; product $100$`, r`$20\times20$, $400$ m²`, r`$x=5$; min $10$`, r`$x=4$; $P=16$`, r`$10\times20$, $200$ m²`, r`$15,15$; product $225$`, r`$x=2$; min $4$`, r`$x=5$; $P=75$`, r`$x=1$; $V=16$`, r`$25\times25$, $625$ m²`, r`$x=1$; min $2$`, r`$x=3$; $P=13$`, r`width $x$, $3x+2L=240$; $A=x\cdot\tfrac{240-3x}{2}$, $x=40$, $A=2400$ m²`],
  },
  {
    code: "5.2", unit: U, title: "Related Rates",
    intro: r`Write an equation relating the quantities, differentiate both sides with respect to $t$, then substitute the instant and solve for the unknown rate.`,
    ideas: [r`Identify known/unknown rates.`, r`Relate the quantities; differentiate w.r.t. $t$ (chain rule).`, r`Substitute the instant's values; solve.`],
    examples: [
      { t: "Expanding circle", body: r`$\dfrac{dr}{dt}=2$ cm/s. Find $\dfrac{dA}{dt}$ at $r=5$.\soln $A=\pi r^2\Rightarrow\dfrac{dA}{dt}=2\pi r\dfrac{dr}{dt}=2\pi(5)(2)=20\pi\approx62.8$ cm²/s.` },
      { t: "Sliding ladder", body: r`A 13 m ladder's base slides out at 2 m/s. Find the top's rate when the base is 5 m out.\soln $x^2+y^2=169$, $y=12$; $2xx'+2yy'=0\Rightarrow y'=-\dfrac{5(2)}{12}=-\dfrac56$ m/s.` + r`\rtri{5}{12}{$y$}{$x$}{$13$}` },
      { t: "Inflating balloon", body: r`$\dfrac{dV}{dt}=100$ cm³/s. Find $\dfrac{dr}{dt}$ at $r=5$.\soln $V=\tfrac43\pi r^3\Rightarrow\dfrac{dV}{dt}=4\pi r^2\dfrac{dr}{dt}$; $100=4\pi(25)\dfrac{dr}{dt}\Rightarrow\dfrac{dr}{dt}=\dfrac1\pi$ cm/s.` },
      { t: "Growing square", body: r`A square's side grows at 3 cm/s. Find $\dfrac{dA}{dt}$ at $s=10$.\soln $A=s^2\Rightarrow 2s\dfrac{ds}{dt}=2(10)(3)=60$ cm²/s.` },
      { t: "Two cars", body: r`Car A north at 60, car B east at 80 km/h from a point. Find the rate the distance grows after 1 h.\soln $D=100$; $2DD'=2aa'+2bb'\Rightarrow D'=\dfrac{60(60)+80(80)}{100}=100$ km/h.` },
      { t: "Expanding circle", body: r`$\dfrac{dr}{dt}=3$ cm/s. Find $\dfrac{dA}{dt}$ at $r=4$.\soln $2\pi(4)(3)=24\pi$ cm²/s.` },
      { t: "Growing square", body: r`Side grows at 2 cm/s. Find $\dfrac{dA}{dt}$ at $s=6$.\soln $2(6)(2)=24$ cm²/s.` },
      { t: "Inflating balloon", body: r`$\dfrac{dV}{dt}=36\pi$ cm³/s. Find $\dfrac{dr}{dt}$ at $r=3$.\soln $36\pi=4\pi(9)\dfrac{dr}{dt}\Rightarrow\dfrac{dr}{dt}=1$ cm/s.` },
      { t: "Sliding ladder", body: r`A 10 m ladder's base slides out at 1 m/s. Find the top's rate at base $=6$ m.\soln $y=8$; $y'=-\dfrac{6(1)}{8}=-\dfrac34$ m/s.` },
    ],
    questions: [
      { ask: r`A circle's radius grows at 5 cm/s. Find $\dfrac{dA}{dt}$ at $r=2$.` },
      { ask: r`A square's side grows at 4 cm/s. Find $\dfrac{dA}{dt}$ at $s=5$.` },
      { ask: r`A balloon fills at $\dfrac{dV}{dt}=48\pi$ cm³/s. Find $\dfrac{dr}{dt}$ at $r=2$.` },
      { ask: r`A 25 m ladder's base slides out at 3 m/s. Find the top's rate at base $=7$ m.`, ws: "2.4cm" },
      { ask: r`A circle's radius grows at 1 cm/s. Find $\dfrac{dA}{dt}$ at $r=10$.` },
      { ask: r`What's the first step after writing the relating equation?` },
      { ask: r`A square's area grows; side grows at 2 cm/s. Find $\dfrac{dA}{dt}$ at $s=8$.` },
      { ask: r`A balloon fills at $\dfrac{dV}{dt}=4\pi$ cm³/s. Find $\dfrac{dr}{dt}$ at $r=1$.` },
      { ask: r`Two cars: N at 30, E at 40 km/h. Rate the distance grows after 1 h?`, ws: "2.4cm" },
      { ask: r`A 5 m ladder's base slides out at 1 m/s. Find the top's rate at base $=3$ m.`, ws: "2.4cm" },
      { ask: r`What does a negative rate of change indicate?` },
      { ask: r`A circle's area grows at $20\pi$ cm²/s. Find $\dfrac{dr}{dt}$ at $r=5$ (use $\tfrac{dA}{dt}=2\pi r\tfrac{dr}{dt}$).` },
      { ask: r`Water fills a cylinder (radius 3) so the volume grows at $18\pi$ cm³/s. How fast is the height rising? ($V=\pi r^2 h$)`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$20\pi$ cm²/s`, r`$40$ cm²/s`, r`$48\pi=4\pi(4)\tfrac{dr}{dt}\Rightarrow3$ cm/s`, r`$y=24$; $-\tfrac{7(3)}{24}=-\tfrac78$ m/s`, r`$20\pi$ cm²/s`, r`differentiate w.r.t. $t$`, r`$32$ cm²/s`, r`$4\pi=4\pi\tfrac{dr}{dt}\Rightarrow1$ cm/s`, r`$D=50$; $\tfrac{30^2+40^2}{50}=50$ km/h`, r`$y=4$; $-\tfrac{3(1)}{4}=-\tfrac34$ m/s`, r`the quantity is decreasing`, r`$20\pi=2\pi(5)\tfrac{dr}{dt}\Rightarrow2$ cm/s`, r`$18\pi=9\pi\tfrac{dh}{dt}\Rightarrow\tfrac{dh}{dt}=2$ cm/s`],
  },
  {
    code: "5.3", unit: U, title: "Kinematics: Velocity & Acceleration",
    intro: r`$v=s'$, $a=v'=s''$, speed $=|v|$. At rest when $v=0$; speeding up when $v,a$ share a sign.`,
    ideas: [r`$v(t)=s'(t)$, $a(t)=s''(t)$.`, r`At rest: $v=0$; direction: sign of $v$.`, r`Speeding up: $v,a$ same sign; slowing: opposite.`],
    examples: [
      { t: "v and a", body: r`For $s(t)=t^2-4t$, find $v$ and $a$.\soln $v=2t-4$, $a=2$. Velocity is the slope of position; at rest at the lowest point ($t=2$):` + r`\eplot{-1}{5}{-5}{6}{\addplot[exblue,very thick,domain=0:4.5]{x^2-4*x};\addplot[qorange,very thick,domain=0:4.5]{2*x-4};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(2,-4)};}` },
      { t: "At rest", body: r`When is $s(t)=t^2-4t$ at rest?\soln $v=2t-4=0\Rightarrow t=2$ s.` },
      { t: "Multiple rest times", body: r`When is $s(t)=t^3-6t^2+9t$ at rest?\soln $v=3t^2-12t+9=3(t-1)(t-3)=0\Rightarrow t=1,3$.` },
      { t: "Direction & accel", body: r`Describe the motion of $s(t)=t^3-6t^2+9t$ at $t=0$.\soln $v(0)=9>0$ (moving right); $a=6t-12$, $a(0)=-12<0$ (decelerating).` },
      { t: "Speeding up?", body: r`Is $s(t)=t^3-6t^2+9t$ speeding up at $t=4$?\soln $v(4)=9>0$, $a(4)=12>0$; same sign ⇒ speeding up.` },
      { t: "Velocity", body: r`For $s(t)=t^2-6t$, find $v(t)$.\soln $2t-6$.` },
      { t: "At rest", body: r`When is $s(t)=t^2-6t$ at rest?\soln $2t-6=0\Rightarrow t=3$.` },
      { t: "Acceleration", body: r`For $s(t)=t^3-3t^2$, find $a(t)$.\soln $v=3t^2-6t$, $a=6t-6$.` },
      { t: "Max height", body: r`A projectile has $h(t)=-5t^2+20t$. When is it highest?\soln $v=-10t+20=0\Rightarrow t=2$ s.` },
    ],
    questions: [
      { ask: r`For $s(t)=t^2-6t$, find $v(t)$.` },
      { ask: r`When is $s(t)=t^2-6t$ at rest?` },
      { ask: r`For $s(t)=t^3-3t^2$, find $a(t)$.` },
      { ask: r`A projectile has $h(t)=-5t^2+30t$. When is it highest?` },
      { ask: r`If $v>0$ and $a<0$, is the object speeding up or slowing down?` },
      { ask: r`For $s(t)=2t^2-8t$, find $v(t)$ and $a(t)$.` },
      { ask: r`When is $s(t)=t^3-6t^2+9t$ at rest?` },
      { ask: r`For $s(t)=t^3-3t^2$, when is the object at rest?` },
      { ask: r`At $t=0$, $s(t)=t^3-6t^2+9t$: which direction is it moving?` },
      { ask: r`Speed of $s(t)=t^2-4t$ at $t=0$?` },
      { ask: r`If $v<0$ and $a<0$, is the object speeding up or slowing down?` },
      { ask: r`Acceleration of $s(t)=t^2-4t$ (constant)?` },
      { ask: r`For $s(t)=t^3-6t^2+9t$, determine whether it is speeding up or slowing down at $t=2$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$2t-6$`, r`$t=3$`, r`$a=6t-6$`, r`$v=-10t+30=0\Rightarrow t=3$ s`, r`slowing down`, r`$v=4t-8$, $a=4$`, r`$t=1,3$`, r`$v=3t^2-6t=0\Rightarrow t=0,2$`, r`right ($v(0)=9>0$)`, r`$|v(0)|=|-4|=4$`, r`speeding up`, r`$2$`, r`$v(2)=-3<0$, $a(2)=0$ — at an instant of zero acceleration (neither)`],
  },
];
