// MCV4U Unit 7 worksheets — Lines & Planes.
const r = String.raw;
const U = "7: Lines and Planes";

export default [
  {
    code: "7.1", unit: U, title: "Equations of Lines",
    intro: r`A line needs a point and a direction vector $\vec d$. Vector: $\vec r=\vec r_0+t\vec d$; parametric: $x=x_0+ta,\dots$; symmetric: $\tfrac{x-x_0}{a}=\tfrac{y-y_0}{b}$.`,
    ideas: [r`Vector: $\vec r=\vec r_0+t\vec d$.`, r`Parametric: $x=x_0+ta,\ y=y_0+tb\ (,z=z_0+tc)$.`, r`Direction through two points: $\vec d=B-A$.`],
    examples: [
      { t: "Vector equation", body: r`Line through $(1,2)$ with direction $(3,4)$.\soln $\vec r=(1,2)+t(3,4)$.` },
      { t: "Parametric", body: r`Parametric form of that line.\soln $x=1+3t,\ y=2+4t$.` },
      { t: "Through two points", body: r`Vector equation through $A(1,0,2),B(4,6,8)$.\soln $\vec d=B-A=(3,6,6)$; $\vec r=(1,0,2)+t(3,6,6)$.` },
      { t: "Symmetric", body: r`Symmetric equation through $(1,2)$ with direction $(3,4)$.\soln $\dfrac{x-1}{3}=\dfrac{y-2}{4}$.` },
      { t: "Point on the line?", body: r`Is $(4,6)$ on $\vec r=(1,2)+t(3,4)$?\soln $4=1+3t\Rightarrow t=1$; $2+4(1)=6$ ✓: yes.` },
      { t: "Vector equation", body: r`Line through $(0,1)$ with direction $(2,5)$.\soln $\vec r=(0,1)+t(2,5)$.` },
      { t: "Parametric", body: r`Parametric form of $\vec r=(3,-1)+t(1,2)$.\soln $x=3+t,\ y=-1+2t$.` },
      { t: "Direction vector", body: r`Direction through $A(2,1,0),B(5,7,6)$.\soln $(3,6,6)$.` },
      { t: "Point on the line?", body: r`Is $(7,11)$ on $\vec r=(1,2)+t(3,3)$?\soln $7=1+3t\Rightarrow t=2$; $2+3(2)=8\ne11$: no.` },
    ],
    questions: [
      { ask: r`Vector equation through $(0,1)$ with direction $(2,5)$.` },
      { ask: r`Parametric form of $\vec r=(3,-1)+t(1,2)$.` },
      { ask: r`Direction vector through $A(2,1,0),B(5,7,6)$.` },
      { ask: r`Symmetric equation through $(0,0)$ with direction $(1,3)$.` },
      { ask: r`Is $(7,11)$ on $\vec r=(1,2)+t(3,3)$?` },
      { ask: r`Vector equation through $(2,3)$ with direction $(1,-1)$.` },
      { ask: r`Parametric form through $(1,1,1)$ with direction $(2,0,3)$.` },
      { ask: r`Direction vector through $A(0,0,0),B(3,4,12)$.` },
      { ask: r`Is $(5,8)$ on $\vec r=(1,2)+t(2,3)$?` },
      { ask: r`Symmetric equation through $(2,1)$ with direction $(4,2)$.` },
      { ask: r`Vector equation of the $x$-axis.` },
      { ask: r`Is $(2,4,6)$ on $\vec r=(0,0,0)+t(1,2,3)$?` },
      { ask: r`Write the line through $A(1,2,3)$ and $B(4,8,9)$ in vector and parametric form.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$\vec r=(0,1)+t(2,5)$`, r`$x=3+t,\ y=-1+2t$`, r`$(3,6,6)$`, r`$\dfrac{x}{1}=\dfrac{y}{3}$`, r`no`, r`$\vec r=(2,3)+t(1,-1)$`, r`$x=1+2t,\ y=1,\ z=1+3t$`, r`$(3,4,12)$`, r`$5=1+2t\Rightarrow t=2$; $2+6=8=8$ ✓ yes`, r`$\dfrac{x-2}{4}=\dfrac{y-1}{2}$`, r`$\vec r=(0,0,0)+t(1,0,0)$`, r`$t=2$ throughout ✓ yes`, r`$\vec d=(3,6,6)$; $\vec r=(1,2,3)+t(3,6,6)$; $x=1+3t,y=2+6t,z=3+6t$`],
  },
  {
    code: "7.2", unit: U, title: "Equations of Planes",
    intro: r`A plane needs a point and a normal $\vec n=(A,B,C)$. Scalar: $Ax+By+Cz=D$ (the coefficients are the normal). Get a normal from two directions via the cross product.`,
    ideas: [r`Scalar: $Ax+By+Cz=D$, normal $(A,B,C)$.`, r`$A(x-x_0)+B(y-y_0)+C(z-z_0)=0$.`, r`Normal from directions: $\vec n=\vec u\times\vec v$.`],
    examples: [
      { t: "From point & normal", body: r`Plane through $(1,2,3)$ with normal $(2,1,-1)$.\soln $2(x-1)+(y-2)-(z-3)=0\Rightarrow 2x+y-z=1$.` },
      { t: "Read the normal", body: r`Normal of $2x+y-z=5$.\soln $(2,1,-1)$.` },
      { t: "Point on the plane?", body: r`Is $(1,1,1)$ on $2x+y-z=2$?\soln $2+1-1=2$ ✓: yes.` },
      { t: "Normal from directions", body: r`Plane contains $\vec u=(1,0,0),\vec v=(0,1,0)$. Find a normal.\soln $\vec n=\vec u\times\vec v=(0,0,1)$.` },
      { t: "Through three points", body: r`Plane through $A(0,0,0),B(1,0,0),C(0,1,0)$.\soln $\vec{AB}\times\vec{AC}=(0,0,1)$; equation $z=0$.` },
      { t: "From point & normal", body: r`Plane through $(0,0,0)$ with normal $(1,2,3)$.\soln $x+2y+3z=0$.` },
      { t: "Read the normal", body: r`Normal of $3x-y+4z=7$.\soln $(3,-1,4)$.` },
      { t: "Point on the plane?", body: r`Is $(2,0,1)$ on $x+y+z=3$?\soln $2+0+1=3$ ✓: yes.` },
      { t: "Vertical plane", body: r`Plane through $(2,0,0)$ with normal $(1,0,0)$.\soln $x-2=0\Rightarrow x=2$.` },
    ],
    questions: [
      { ask: r`Scalar equation through $(0,0,0)$ with normal $(1,2,3)$.` },
      { ask: r`Normal vector of $3x-y+4z=7$.` },
      { ask: r`Is $(2,0,1)$ on $x+y+z=3$?` },
      { ask: r`Normal of the plane containing $(1,0,0)$ and $(0,0,1)$.` },
      { ask: r`Scalar equation through $(2,0,0)$ with normal $(1,0,0)$.` },
      { ask: r`Scalar equation through $(1,1,1)$ with normal $(1,1,1)$.` },
      { ask: r`Normal vector of $x-2y+5z=0$.` },
      { ask: r`Is $(0,3,0)$ on $2x+y-z=3$?` },
      { ask: r`Equation of the plane $z=0$'s normal.` },
      { ask: r`Scalar equation through $(0,0,4)$ with normal $(0,0,1)$.` },
      { ask: r`Normal of the plane through $A(0,0,0),B(2,0,0),C(0,3,0)$.` },
      { ask: r`Is $(1,2,3)$ on $x+y+z=6$?` },
      { ask: r`Find the scalar equation of the plane through $A(1,0,0),B(0,1,0),C(0,0,1)$.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$x+2y+3z=0$`, r`$(3,-1,4)$`, r`yes ($3=3$)`, r`$(0,-1,0)$`, r`$x=2$`, r`$x+y+z=3$`, r`$(1,-2,5)$`, r`yes ($3=3$)`, r`$(0,0,1)$`, r`$z=4$`, r`$(0,0,6)$ or $(0,0,1)$`, r`yes ($6=6$)`, r`$\vec n=\vec{AB}\times\vec{AC}=(1,1,1)$; $x+y+z=1$`],
  },
  {
    code: "7.3", unit: U, title: "Intersections of Lines & Planes",
    intro: r`Line–plane: substitute the line into the plane and solve for $t$. Compare directions/normals to detect parallel, skew, or coincident.`,
    ideas: [r`Line–plane: substitute $x,y,z$; solve for $t$; back-substitute.`, r`Line $\parallel$ plane when $\vec d\cdot\vec n=0$.`, r`Planes $\parallel$ when normals are parallel.`],
    examples: [
      { t: "Line meets a plane", body: r`Where does $\vec r=(1,0,0)+t(0,0,1)$ meet $z=5$?\soln $z=t=5$; $(1,0,5)$.` },
      { t: "Substitute into the plane", body: r`Where does $x=t,y=t,z=t$ meet $x+y+z=6$?\soln $3t=6\Rightarrow t=2$; $(2,2,2)$.` },
      { t: "Line parallel to a plane", body: r`Is $\vec r=(0,0,1)+t(1,1,0)$ parallel to $z=5$?\soln $\vec d\cdot\vec n=(1,1,0)\cdot(0,0,1)=0$ and $(0,0,1)$ not on $z=5$: parallel.` },
      { t: "Parallel lines", body: r`Are $\vec r=(0,0)+t(2,4)$ and $\vec r=(1,1)+s(1,2)$ parallel?\soln $(2,4)=2(1,2)$: yes.` },
      { t: "Parallel planes", body: r`Are $2x+y-z=1$ and $4x+2y-2z=9$ parallel?\soln Normals $(2,1,-1)$ and $2(2,1,-1)$; equations not multiples ⇒ parallel \& distinct.` },
      { t: "Line meets a plane", body: r`Where does $x=t,y=2t,z=0$ meet $z=0$?\soln Every point — the line lies in the plane.` },
      { t: "Substitute", body: r`Where does $x=t,y=t,z=t$ meet $x+y+z=9$?\soln $3t=9\Rightarrow t=3$; $(3,3,3)$.` },
      { t: "Line crosses a plane", body: r`Is direction $(1,1,1)$ parallel to $x+y+z=4$?\soln $\vec d\cdot\vec n=3\ne0$: no, it crosses.` },
      { t: "Simple plane", body: r`Where does $\vec r=(0,0,0)+t(1,0,0)$ meet $x=4$?\soln $t=4$; $(4,0,0)$.` },
    ],
    questions: [
      { ask: r`Where does $x=t,y=t,z=t$ meet $x+y+z=9$?` },
      { ask: r`Are the planes $x+y+z=1$ and $2x+2y+2z=5$ parallel?` },
      { ask: r`Is the line with direction $(1,1,1)$ parallel to $x+y+z=4$?` },
      { ask: r`Where does $\vec r=(0,0,0)+t(1,0,0)$ meet $x=4$?` },
      { ask: r`Are $\vec r=(0,0)+t(2,4)$ and $\vec r=(1,1)+s(1,2)$ parallel?` },
      { ask: r`Where does $x=t,y=0,z=0$ meet $x=7$?` },
      { ask: r`Are the planes $x-y+z=0$ and $2x-2y+2z=3$ parallel?` },
      { ask: r`Is direction $(1,0,0)$ parallel to the plane $y=5$?` },
      { ask: r`Where does $x=2t,y=t,z=t$ meet $x+y+z=8$?` },
      { ask: r`Are $\vec r=(0,0)+t(1,2)$ and $\vec r=(0,0)+s(2,1)$ parallel?` },
      { ask: r`Where does $\vec r=(0,0,1)+t(0,0,1)$ meet $z=10$?` },
      { ask: r`Two planes have normals $(1,2,3)$ and $(2,4,6)$. Parallel?` },
      { ask: r`Find where the line $x=1+t,\ y=2+t,\ z=3+t$ meets the plane $x+y+z=12$.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$(3,3,3)$`, r`parallel and distinct`, r`no ($\vec d\cdot\vec n=3$)`, r`$(4,0,0)$`, r`yes`, r`$(7,0,0)$`, r`parallel and distinct`, r`yes ($\vec d\cdot\vec n=0$, $(1,0,0)$)`, r`$4t=8\Rightarrow t=2$: $(4,2,2)$`, r`no (not scalar multiples)`, r`$(0,0,10)$`, r`yes (normals are multiples)`, r`$(1+t)+(2+t)+(3+t)=12\Rightarrow 6+3t=12\Rightarrow t=2$: $(3,4,5)$`],
  },
];
