// FTCE Unit 1 — Algebra. Question bank, ~26 curated questions per topic
// (skewed medium/hard for certification level). Answers verified by hand.
import { mc, tf, num, fill } from "./helpers.mjs";
const R = String.raw;

// ── 1.1 Polynomial Operations ────────────────────────────────
const g11 = () => [
  mc("easy", R`Degree of $-4x^5+2x^3-7$?`, [R`$3$`, R`$5$`, R`$-4$`, R`$7$`], 1),
  mc("easy", R`Leading coefficient of $-4x^5+2x^3-7$?`, [R`$5$`, R`$-4$`, R`$2$`, R`$-7$`], 1),
  fill("easy", R`A polynomial with three terms is called a ___.`, ["trinomial"]),
  mc("easy", R`$(3x^2-2x+5)+(x^2+4x-1)=$`, [R`$4x^2+2x+4$`, R`$2x^2+2x+4$`, R`$4x^2-2x+4$`, R`$4x^2+2x+6$`], 0),
  mc("easy", R`$(4x^2-x+1)-(x^2+3x-4)=$`, [R`$3x^2-4x+5$`, R`$3x^2+2x-3$`, R`$3x^2-4x-3$`, R`$5x^2-4x+5$`], 0),
  mc("easy", R`$(x-5)(x+5)=$`, [R`$x^2-25$`, R`$x^2+25$`, R`$x^2-10x+25$`, R`$x^2-5$`], 0),
  mc("easy", R`$3x^2\cdot 4x^3=$`, [R`$12x^5$`, R`$12x^6$`, R`$7x^5$`, R`$12x^{5}y$`], 0),
  num("easy", R`Evaluate $P(x)=2x^3-x+5$ at $x=1$.`, 6, 0),
  mc("medium", R`$(2x+1)(x^2-3x+2)=$`, [R`$2x^3-5x^2+x+2$`, R`$2x^3-5x^2-x+2$`, R`$2x^3+5x^2+x+2$`, R`$2x^3-6x^2+2$`], 0),
  mc("medium", R`$(x-3)^2=$`, [R`$x^2-6x+9$`, R`$x^2+9$`, R`$x^2-9$`, R`$x^2-3x+9$`], 0),
  mc("medium", R`$(x+2)^3=$`, [R`$x^3+6x^2+12x+8$`, R`$x^3+8$`, R`$x^3+6x^2+8$`, R`$x^3+2x^2+4x+8$`], 0),
  mc("medium", R`$(2x-3)(x^2+x-4)=$`, [R`$2x^3-x^2-11x+12$`, R`$2x^3+x^2-11x+12$`, R`$2x^3-x^2-5x+12$`, R`$2x^3-x^2-11x-12$`], 0),
  mc("medium", R`Divide: $\dfrac{x^3-1}{x-1}=$`, [R`$x^2+x+1$`, R`$x^2-x+1$`, R`$x^2+1$`, R`$x^2-1$`], 0),
  mc("medium", R`$\dfrac{15x^3-10x^2+5x}{5x}=$`, [R`$3x^2-2x+1$`, R`$3x^2-2x$`, R`$3x^3-2x^2+x$`, R`$3x^2-10x^2+1$`], 0),
  num("medium", R`Degree of the product $(x^2+1)(x^3-x)$?`, 5, 0),
  fill("medium", R`Fill in: $\deg(fg)=\deg f\ \_\_\_\ \deg g$ (operation).`, ["+", "plus", "add"]),
  num("hard", R`Find the remainder when $2x^3-3x^2+4x-1$ is divided by $x-2$.`, 11, 0),
  mc("hard", R`The quotient of $(2x^3-3x^2+4x-1)\div(x-2)$ is`, [R`$2x^2+x+6$`, R`$2x^2-x+6$`, R`$2x^2+x-6$`, R`$2x^2+7x$`], 0),
  mc("hard", R`$(3x^2-1)^2-(3x^2+1)^2=$`, [R`$-12x^2$`, R`$12x^2$`, R`$0$`, R`$-2$`], 0),
  mc("hard", R`Divide: $\dfrac{x^4-16}{x-2}=$`, [R`$x^3+2x^2+4x+8$`, R`$x^3-2x^2+4x-8$`, R`$x^3+8$`, R`$x^3+2x^2+8$`], 0),
  tf("hard", R`$(a+b)^2=a^2+b^2$ for all real $a,b$.`, false),
  mc("hard", R`By the Remainder Theorem, the remainder of $P(x)\div(x-3)$ equals`, [R`$P(3)$`, R`$P(-3)$`, R`$P(0)$`, R`$3P(1)$`], 0),
  num("hard", R`If $P(x)=x^3-2x^2+x+4$, the remainder of $P(x)\div(x+1)$ is $P(-1)=$ ___.`, 0, 0),
  mc("hard", R`$(x^2+x+1)(x-1)=$`, [R`$x^3-1$`, R`$x^3+1$`, R`$x^3-x-1$`, R`$x^3+x^2-1$`], 0),
  mc("medium", R`$-2x(3x^2-4x+1)=$`, [R`$-6x^3+8x^2-2x$`, R`$-6x^3-8x^2-2x$`, R`$6x^3-8x^2+2x$`, R`$-6x^3+8x^2+2x$`], 0),
  tf("medium", R`Polynomial long division stops when the remainder's degree is below the divisor's.`, true),
];

// ── 1.2 Factoring ────────────────────────────────────────────
const g12 = () => [
  mc("easy", R`Factor $x^2-9$.`, [R`$(x-3)(x+3)$`, R`$(x-3)^2$`, R`$(x+3)^2$`, R`$(x-9)(x+1)$`], 0),
  mc("easy", R`Factor $x^2+8x+15$.`, [R`$(x+3)(x+5)$`, R`$(x+1)(x+15)$`, R`$(x-3)(x-5)$`, R`$(x+4)(x+4)$`], 0),
  mc("easy", R`Factor $x^2-x-12$.`, [R`$(x-4)(x+3)$`, R`$(x+4)(x-3)$`, R`$(x-6)(x+2)$`, R`$(x-12)(x+1)$`], 0),
  fill("easy", R`The GCF of $12x^3$ and $18x^2$ is ___.`, ["6x^2", "6x²"]),
  mc("easy", R`Factor $x^2-6x+9$.`, [R`$(x-3)^2$`, R`$(x+3)^2$`, R`$(x-3)(x+3)$`, R`$(x-9)(x+1)$`], 0),
  tf("easy", R`$x^2+9$ factors over the real numbers.`, false),
  mc("medium", R`Factor $6x^2+7x-3$.`, [R`$(2x+3)(3x-1)$`, R`$(2x-3)(3x+1)$`, R`$(6x-1)(x+3)$`, R`$(2x+1)(3x-3)$`], 0),
  mc("medium", R`Factor $2x^2+5x-3$.`, [R`$(2x-1)(x+3)$`, R`$(2x+1)(x-3)$`, R`$(2x-3)(x+1)$`, R`$(x-1)(2x+3)$`], 0),
  mc("medium", R`Factor $x^3-27$.`, [R`$(x-3)(x^2+3x+9)$`, R`$(x-3)(x^2-3x+9)$`, R`$(x-3)^3$`, R`$(x-3)(x^2+9)$`], 0),
  mc("medium", R`Factor $8x^3+27$.`, [R`$(2x+3)(4x^2-6x+9)$`, R`$(2x+3)(4x^2+6x+9)$`, R`$(2x+3)^3$`, R`$(2x+3)(4x^2-9)$`], 0),
  mc("medium", R`Factor $12x^3y-18x^2y^2$.`, [R`$6x^2y(2x-3y)$`, R`$6xy(2x^2-3xy)$`, R`$6x^2y(2x-3)$`, R`$3x^2y(4x-6y)$`], 0),
  mc("medium", R`Factor $9x^2-24x+16$.`, [R`$(3x-4)^2$`, R`$(3x+4)^2$`, R`$(3x-4)(3x+4)$`, R`$(9x-4)(x-4)$`], 0),
  fill("medium", R`Factor completely: $3x^2-27=$ ___.`, ["3(x-3)(x+3)"]),
  mc("hard", R`Factor $2x^4-32$ completely.`, [R`$2(x-2)(x+2)(x^2+4)$`, R`$2(x^2-4)(x^2+4)$`, R`$(x-2)(x+2)(2x^2+8)$`, R`$2(x^2-16)$`], 0),
  mc("hard", R`Factor $x^3+2x^2-9x-18$ by grouping.`, [R`$(x+2)(x-3)(x+3)$`, R`$(x+2)(x^2-9)$`, R`$(x-2)(x-3)(x+3)$`, R`$(x+2)(x-3)^2$`], 0),
  mc("hard", R`Factor $x^4-1$.`, [R`$(x-1)(x+1)(x^2+1)$`, R`$(x^2-1)^2$`, R`$(x-1)^2(x+1)^2$`, R`$(x-1)(x^3+1)$`], 0),
  mc("hard", R`Factor $4x^2+12x+9$.`, [R`$(2x+3)^2$`, R`$(2x-3)^2$`, R`$(4x+3)(x+3)$`, R`$(2x+3)(2x-3)$`], 0),
  mc("hard", R`Factor $6x^2-x-2$.`, [R`$(3x-2)(2x+1)$`, R`$(3x+2)(2x-1)$`, R`$(6x-1)(x+2)$`, R`$(3x-1)(2x+2)$`], 0),
  tf("hard", R`$a^3-b^3=(a-b)(a^2+ab+b^2)$.`, true),
  mc("hard", R`Factor $x^2-5$ over the reals.`, [R`$(x-\sqrt5)(x+\sqrt5)$`, R`prime (does not factor)`, R`$(x-5)(x+1)$`, R`$(x-\sqrt5)^2$`], 0),
  mc("medium", R`Factor $x^2+10x+25$.`, [R`$(x+5)^2$`, R`$(x-5)^2$`, R`$(x+5)(x-5)$`, R`$(x+25)(x+1)$`], 0),
  mc("medium", R`Factor $3x^2+11x+6$.`, [R`$(3x+2)(x+3)$`, R`$(3x+6)(x+1)$`, R`$(3x+3)(x+2)$`, R`$(x+2)(3x+3)$`], 0),
  fill("easy", R`Always factor out the ___ first.`, ["GCF", "greatest common factor"]),
  mc("easy", R`Factor $x^2+7x+12$.`, [R`$(x+3)(x+4)$`, R`$(x+2)(x+6)$`, R`$(x+1)(x+12)$`, R`$(x-3)(x-4)$`], 0),
  tf("medium", R`$25-x^2=(5-x)(5+x)$.`, true),
];

// ── 1.3 Rational Expressions ─────────────────────────────────
const g13 = () => [
  mc("easy", R`Simplify $\dfrac{x^2-4}{x^2-x-6}$.`, [R`$\dfrac{x-2}{x-3}$`, R`$\dfrac{x+2}{x+3}$`, R`$\dfrac{x-2}{x+3}$`, R`$\dfrac{x+2}{x-3}$`], 0),
  mc("easy", R`Simplify $\dfrac{x^2-1}{x^2+2x+1}$.`, [R`$\dfrac{x-1}{x+1}$`, R`$\dfrac{x+1}{x-1}$`, R`$x-1$`, R`$\dfrac{x-1}{x-1}$`], 0),
  fill("easy", R`Restrictions on $\dfrac{3}{x^2-4}$: $x\ne$ ___ (list both).`, ["2, -2", "-2, 2", "±2", "2 and -2"]),
  mc("easy", R`Simplify $\dfrac{x-2}{2-x}$.`, [R`$-1$`, R`$1$`, R`$x-2$`, R`$0$`], 0),
  mc("medium", R`$\dfrac{x}{x+1}\cdot\dfrac{x^2-1}{x^2}=$`, [R`$\dfrac{x-1}{x}$`, R`$\dfrac{x+1}{x}$`, R`$\dfrac{x-1}{x+1}$`, R`$x-1$`], 0),
  mc("medium", R`$\dfrac{1}{x}+\dfrac{1}{x+1}=$`, [R`$\dfrac{2x+1}{x(x+1)}$`, R`$\dfrac{2}{2x+1}$`, R`$\dfrac{1}{2x+1}$`, R`$\dfrac{2x+1}{x^2+x}$`], 0),
  mc("medium", R`$\dfrac{2}{x-3}-\dfrac{1}{x+2}=$`, [R`$\dfrac{x+7}{(x-3)(x+2)}$`, R`$\dfrac{1}{(x-3)(x+2)}$`, R`$\dfrac{x-7}{(x-3)(x+2)}$`, R`$\dfrac{3x+1}{(x-3)(x+2)}$`], 0),
  mc("medium", R`$\dfrac{6}{x^2}\div\dfrac{3}{x}=$`, [R`$\dfrac{2}{x}$`, R`$\dfrac{2}{x^2}$`, R`$\dfrac{18}{x^3}$`, R`$2x$`], 0),
  mc("medium", R`Add $\dfrac{2}{x}+\dfrac{3}{x^2}$.`, [R`$\dfrac{2x+3}{x^2}$`, R`$\dfrac{5}{x^2}$`, R`$\dfrac{5}{x^3}$`, R`$\dfrac{6}{x^3}$`], 0),
  mc("hard", R`Simplify the complex fraction $\dfrac{\frac{1}{x}-\frac{1}{y}}{\frac{1}{x}+\frac{1}{y}}$.`, [R`$\dfrac{y-x}{y+x}$`, R`$\dfrac{x-y}{x+y}$`, R`$\dfrac{y+x}{y-x}$`, R`$1$`], 0),
  mc("hard", R`Simplify $\dfrac{1-\frac{1}{x}}{1-\frac{1}{x^2}}$.`, [R`$\dfrac{x}{x+1}$`, R`$\dfrac{x}{x-1}$`, R`$\dfrac{x-1}{x}$`, R`$\dfrac{x+1}{x}$`], 0),
  mc("hard", R`$\dfrac{x^2-9}{x+2}\div\dfrac{x-3}{x^2-4}=$`, [R`$(x+3)(x-2)$`, R`$(x-3)(x+2)$`, R`$\dfrac{x+3}{x-2}$`, R`$(x+3)(x+2)$`], 0),
  tf("medium", R`Restrictions must be read from the original expression, not the simplified one.`, true),
  fill("medium", R`To add rational expressions you first find the ___.`, ["LCD", "least common denominator", "common denominator"]),
  tf("easy", R`$\dfrac{x^2}{x}=x$ only when $x\ne 0$.`, true),
  mc("medium", R`$\dfrac{x+3}{x}\cdot\dfrac{x^2}{x^2-9}=$`, [R`$\dfrac{x}{x-3}$`, R`$\dfrac{x}{x+3}$`, R`$\dfrac{x^2}{x-3}$`, R`$\dfrac{1}{x-3}$`], 0),
  mc("hard", R`Restrictions on $\dfrac{x+1}{x^2-x-6}$: $x\ne$`, [R`$3,\ -2$`, R`$-3,\ 2$`, R`$-1$`, R`$6,\ 1$`], 0),
  mc("medium", R`$\dfrac{x^2-16}{x-4}=$ (simplified)`, [R`$x+4$`, R`$x-4$`, R`$x^2-4$`, R`$\dfrac{1}{x+4}$`], 0),
  mc("hard", R`$\dfrac{a}{a-b}+\dfrac{b}{b-a}=$`, [R`$1$`, R`$0$`, R`$-1$`, R`$\dfrac{a+b}{a-b}$`], 0),
  num("easy", R`Value excluded from $\dfrac{5}{x-7}$: $x=$ ___.`, 7, 0),
  mc("medium", R`$\dfrac{3x}{x^2-1}-\dfrac{3}{x^2-1}=$`, [R`$\dfrac{3}{x+1}$`, R`$\dfrac{3}{x-1}$`, R`$\dfrac{3x-3}{x-1}$`, R`$3$`], 0),
  tf("hard", R`$\dfrac{a-b}{b-a}=-1$ for $a\ne b$.`, true),
  mc("easy", R`Simplify $\dfrac{6x^2}{2x}$.`, [R`$3x$`, R`$3x^2$`, R`$4x$`, R`$3$`], 0),
  mc("medium", R`$\dfrac{x^2+5x+6}{x+2}=$`, [R`$x+3$`, R`$x+2$`, R`$x-3$`, R`$\dfrac{x+3}{x+2}$`], 0),
];

// ── 1.4 Linear & Radical Equations ───────────────────────────
const g14 = () => [
  num("easy", R`Solve $3x-7=2x+5$.`, 12, 0),
  num("easy", R`Solve $5x+3=2x-9$.`, -4, 0),
  num("easy", R`Solve $\dfrac{x}{2}+\dfrac{x}{3}=5$.`, 6, 0),
  num("easy", R`Solve $\sqrt{x+3}=4$.`, 13, 0),
  num("easy", R`Solve $x-8=-3$.`, 5, 0),
  num("medium", R`Solve $2(x-3)=4x+2$.`, -4, 0),
  num("medium", R`Solve $\dfrac{x}{4}-\dfrac{x}{6}=1$.`, 12, 0),
  num("medium", R`Solve $\dfrac{2}{x}=\dfrac{5}{x+3}$.`, 2, 0),
  num("medium", R`Solve $\dfrac{3}{x-1}=\dfrac{2}{x}$.`, -2, 0),
  num("medium", R`Solve $\sqrt{x-2}=3$.`, 11, 0),
  num("medium", R`Solve $\dfrac{x}{2}+3=\dfrac{x}{5}+9$.`, 20, 0),
  num("hard", R`Solve $\sqrt{2x+1}=x-1$ (real solution, checked).`, 4, 0),
  num("hard", R`Solve $\sqrt{3x+1}=x-1$ (checked).`, 5, 0),
  tf("hard", R`Squaring both sides of a radical equation can introduce extraneous roots.`, true),
  tf("medium", R`$2(x+1)=2x+2$ is true for all real $x$ (an identity).`, true),
  mc("easy", R`First step to solve $\dfrac{x}{3}=6$?`, [R`Multiply both sides by 3`, R`Divide by 3`, R`Subtract 3`, R`Add 3`], 0),
  mc("medium", R`How many solutions does $x+5=x+2$ have?`, [R`none`, R`one`, R`infinitely many`, R`two`], 0),
  num("hard", R`Solve $\sqrt{x}+\sqrt{x+5}=5$.`, 4, 0),
  mc("hard", R`Solving $\sqrt{x+4}=x-2$, which value is extraneous?`, [R`$x=0$`, R`$x=5$`, R`neither`, R`both`], 0),
  num("easy", R`Solve $4x=-12$.`, -3, 0),
  num("medium", R`Solve $\dfrac{2x-1}{3}=5$.`, 8, 0),
  num("medium", R`Solve $3(x+2)=2(x+5)$.`, 4, 0),
  fill("medium", R`An equation true for NO value of $x$ is called a ___.`, ["contradiction"]),
  num("hard", R`Solve $\dfrac{1}{x}+\dfrac{1}{2x}=\dfrac{3}{4}$.`, 2, 0),
  num("easy", R`Solve $x+11=4$.`, -7, 0),
];

// ── 1.5 Lines: Slope & Forms ─────────────────────────────────
const g15 = () => [
  num("easy", R`Slope through $(1,2)$ and $(5,10)$?`, 2, 0),
  num("easy", R`Slope through $(-1,2)$ and $(3,10)$?`, 2, 0),
  mc("easy", R`Slope of $y=3x-5$?`, [R`$3$`, R`$-5$`, R`$-3$`, R`$5$`], 0),
  mc("easy", R`$y$-intercept of $2x+3y=12$?`, [R`$(0,4)$`, R`$(6,0)$`, R`$(0,12)$`, R`$(0,-4)$`], 0),
  mc("easy", R`Slope of a horizontal line?`, [R`$0$`, R`undefined`, R`$1$`, R`$-1$`], 0),
  mc("easy", R`Slope of a vertical line?`, [R`undefined`, R`$0$`, R`$1$`, R`$-1$`], 0),
  mc("medium", R`Slope of $5x-2y=8$?`, [R`$\tfrac{5}{2}$`, R`$-\tfrac{5}{2}$`, R`$5$`, R`$\tfrac{2}{5}$`], 0),
  mc("medium", R`Perpendicular to slope $\tfrac{2}{3}$ is`, [R`$-\tfrac{3}{2}$`, R`$\tfrac{3}{2}$`, R`$-\tfrac{2}{3}$`, R`$\tfrac{2}{3}$`], 0),
  mc("medium", R`Point-slope $y-3=2(x-1)$ in slope-intercept form:`, [R`$y=2x+1$`, R`$y=2x-1$`, R`$y=2x+5$`, R`$y=2x+3$`], 0),
  mc("medium", R`Line through $(0,4)$ with slope $-3$:`, [R`$y=-3x+4$`, R`$y=-3x-4$`, R`$y=3x+4$`, R`$y=4x-3$`], 0),
  mc("medium", R`$y=2x+1$ and $y=-\tfrac12 x$ are`, [R`perpendicular`, R`parallel`, R`the same line`, R`neither`], 0),
  mc("medium", R`$x$-intercept of $3x-4y=12$?`, [R`$(4,0)$`, R`$(0,-3)$`, R`$(3,0)$`, R`$(12,0)$`], 0),
  mc("hard", R`Standard form of the line through $(1,4)$ and $(3,10)$:`, [R`$3x-y=-1$`, R`$3x-y=1$`, R`$x-3y=-1$`, R`$3x+y=13$`], 0),
  mc("hard", R`Line through $(2,-1)$ perpendicular to $2x+y=7$:`, [R`$y=\tfrac12 x-2$`, R`$y=-2x+3$`, R`$y=\tfrac12 x+2$`, R`$y=2x-5$`], 0),
  mc("hard", R`$2x+3y=6$ and $4x+6y=1$ are`, [R`parallel`, R`perpendicular`, R`the same line`, R`intersecting once`], 0),
  mc("medium", R`Line through $(2,3)$ and $(2,-5)$ is`, [R`vertical, $x=2$`, R`horizontal, $y=2$`, R`slope $0$`, R`$y=2x$`], 0),
  mc("medium", R`Parallel to $y=4x-1$ through $(0,3)$:`, [R`$y=4x+3$`, R`$y=-\tfrac14 x+3$`, R`$y=4x-3$`, R`$y=3x+4$`], 0),
  num("medium", R`For $y=mx+b$ through $(0,-2)$ and $(4,6)$, find $m$.`, 2, 0),
  tf("easy", R`Perpendicular slopes multiply to $-1$.`, true),
  num("hard", R`Line $3x+ky=6$ has slope $-\tfrac34$. Find $k$.`, 4, 0),
  mc("medium", R`Which line passes through the origin?`, [R`$y=5x$`, R`$y=5x+1$`, R`$x+y=2$`, R`$y=3$`], 0),
  num("easy", R`$y$-intercept of $y=-7x+9$?`, 9, 0),
  mc("hard", R`Distance from $(0,0)$ to the line $x=y$: is the origin ON the line?`, [R`yes`, R`no`, R`only if shifted`, R`undefined`], 0),
  mc("medium", R`Slope of line parallel to $y=-2x+7$?`, [R`$-2$`, R`$\tfrac12$`, R`$2$`, R`$7$`], 0),
  tf("medium", R`A line with slope $0$ is horizontal.`, true),
];

// ── 1.6 Systems of Linear Equations ──────────────────────────
const g16 = () => [
  mc("easy", R`Solve $\begin{cases}x+y=7\\x-y=1\end{cases}$.`, [R`$(4,3)$`, R`$(3,4)$`, R`$(5,2)$`, R`$(4,4)$`], 0),
  mc("easy", R`Solve $\begin{cases}x+y=5\\x-y=3\end{cases}$.`, [R`$(4,1)$`, R`$(1,4)$`, R`$(3,2)$`, R`$(2,3)$`], 0),
  mc("easy", R`Solve $\begin{cases}2x+y=7\\x-y=2\end{cases}$.`, [R`$(3,1)$`, R`$(1,3)$`, R`$(2,3)$`, R`$(3,2)$`], 0),
  mc("easy", R`Solve by substitution $\begin{cases}y=2x\\3x+y=10\end{cases}$.`, [R`$(2,4)$`, R`$(4,2)$`, R`$(1,2)$`, R`$(2,2)$`], 0),
  mc("medium", R`Classify $\begin{cases}2x+3y=6\\4x+6y=7\end{cases}$.`, [R`inconsistent (no solution)`, R`dependent`, R`one solution`, R`homogeneous`], 0),
  mc("medium", R`Classify $\begin{cases}x-2y=3\\2x-4y=6\end{cases}$.`, [R`dependent (infinitely many)`, R`inconsistent`, R`one solution`, R`no real solution`], 0),
  mc("medium", R`Solve $\begin{cases}y=x-1\\2x+y=8\end{cases}$.`, [R`$(3,2)$`, R`$(2,3)$`, R`$(3,3)$`, R`$(1,0)$`], 0),
  mc("medium", R`Solve $\begin{cases}2x+3y=7\\3x-y=5\end{cases}$.`, [R`$(2,1)$`, R`$(1,2)$`, R`$(2,-1)$`, R`$(3,1)$`], 0),
  mc("medium", R`Solve $\begin{cases}3x+2y=12\\x-y=1\end{cases}$.`, [R`$(\tfrac{14}{5},\tfrac{9}{5})$`, R`$(2,1)$`, R`$(3,2)$`, R`$(4,3)$`], 0),
  mc("hard", R`Solve $\begin{cases}x+y+z=6\\x-y+z=2\\2x+y-z=1\end{cases}$.`, [R`$(1,2,3)$`, R`$(3,2,1)$`, R`$(2,2,2)$`, R`$(1,3,2)$`], 0),
  mc("hard", R`Solve $\begin{cases}x+y=3\\y+z=5\\x+z=4\end{cases}$.`, [R`$(1,2,3)$`, R`$(2,1,3)$`, R`$(3,2,1)$`, R`$(1,3,2)$`], 0),
  mc("medium", R`The homogeneous system $\begin{cases}2x+3y=0\\x-y=0\end{cases}$ has solution`, [R`$(0,0)$ only`, R`infinitely many`, R`no solution`, R`$(1,1)$`], 0),
  num("hard", R`For what $k$ is $\begin{cases}2x+3y=5\\4x+6y=k\end{cases}$ dependent?`, 10, 0),
  mc("medium", R`Classify $\begin{cases}x+y=1\\x+y=4\end{cases}$.`, [R`inconsistent`, R`dependent`, R`one solution`, R`trivial`], 0),
  tf("easy", R`Two lines that intersect once give a system with exactly one solution.`, true),
  tf("medium", R`Parallel lines correspond to an inconsistent system.`, true),
  tf("medium", R`Every homogeneous linear system has at least the trivial solution.`, true),
  mc("medium", R`Best method when one equation is already solved for a variable:`, [R`substitution`, R`elimination`, R`graphing`, R`matrices`], 0),
  mc("hard", R`$\begin{cases}x+2y=5\\3x+6y=15\end{cases}$ has how many solutions?`, [R`infinitely many`, R`one`, R`none`, R`two`], 0),
  num("medium", R`In the solution of $\begin{cases}x+y=10\\x-y=4\end{cases}$, find $x$.`, 7, 0),
  mc("easy", R`Graphically, the solution of a $2\times2$ system is`, [R`the intersection point`, R`the $y$-intercepts`, R`the slopes`, R`the origin`], 0),
  mc("hard", R`Solve $\begin{cases}2x-y=3\\4x-2y=6\end{cases}$.`, [R`infinitely many solutions`, R`$(3,3)$`, R`no solution`, R`$(1,-1)$`], 0),
  num("medium", R`In $\begin{cases}3x+y=10\\x+y=4\end{cases}$, find $x$.`, 3, 0),
  mc("medium", R`Adding $\begin{cases}x+y=6\\x-y=2\end{cases}$ eliminates`, [R`$y$`, R`$x$`, R`both`, R`neither`], 0),
];

// ── 1.7 Quadratic Equations ──────────────────────────────────
const g17 = () => [
  mc("easy", R`Solve $x^2-5x+6=0$.`, [R`$x=2,3$`, R`$x=-2,-3$`, R`$x=1,6$`, R`$x=2,-3$`], 0),
  mc("easy", R`Solve $x^2=49$.`, [R`$x=\pm 7$`, R`$x=7$`, R`$x=\pm 49$`, R`$x=\pm\sqrt7$`], 0),
  mc("easy", R`Solve $x^2+2x-8=0$.`, [R`$x=-4,2$`, R`$x=4,-2$`, R`$x=-4,-2$`, R`$x=8,-1$`], 0),
  mc("easy", R`Solve $x^2-7x+12=0$.`, [R`$x=3,4$`, R`$x=-3,-4$`, R`$x=2,6$`, R`$x=1,12$`], 0),
  mc("easy", R`Solve $x^2-6x+9=0$.`, [R`$x=3$ (double)`, R`$x=\pm 3$`, R`$x=-3$`, R`$x=3,6$`], 0),
  mc("medium", R`Solve $2x^2-5x+2=0$.`, [R`$x=\tfrac12,2$`, R`$x=-\tfrac12,-2$`, R`$x=1,2$`, R`$x=2,5$`], 0),
  mc("medium", R`Solve $2x^2+3x-2=0$.`, [R`$x=\tfrac12,-2$`, R`$x=-\tfrac12,2$`, R`$x=1,-2$`, R`$x=2,-1$`], 0),
  mc("medium", R`Solve $x^2+4x-1=0$.`, [R`$x=-2\pm\sqrt5$`, R`$x=2\pm\sqrt5$`, R`$x=-2\pm\sqrt3$`, R`$x=-4\pm\sqrt5$`], 0),
  num("medium", R`Discriminant of $x^2+x+1$?`, -3, 0),
  num("medium", R`Discriminant of $2x^2-3x+5$?`, -31, 0),
  mc("medium", R`If the discriminant is $0$, the quadratic has`, [R`one real (double) root`, R`two real roots`, R`two complex roots`, R`no roots`], 0),
  mc("hard", R`Solve $x^2-4x+13=0$.`, [R`$x=2\pm 3i$`, R`$x=2\pm 3$`, R`$x=-2\pm 3i$`, R`$x=4\pm 3i$`], 0),
  mc("hard", R`Solve $3x^2-2x+1=0$.`, [R`$x=\dfrac{1\pm i\sqrt2}{3}$`, R`$x=\dfrac{2\pm i\sqrt2}{3}$`, R`$x=\dfrac{1\pm\sqrt2}{3}$`, R`$x=\dfrac{-1\pm i\sqrt2}{3}$`], 0),
  num("hard", R`Sum of the roots of $x^2-5x+6=0$?`, 5, 0),
  num("hard", R`Product of the roots of $x^2-5x+6=0$?`, 6, 0),
  mc("hard", R`For $x^2+kx+9=0$ to have a double root, $k=$`, [R`$\pm 6$`, R`$6$`, R`$9$`, R`$3$`], 0),
  fill("medium", R`The quadratic formula: $x=\dfrac{-b\pm\sqrt{b^2-4ac}}{\_\_}$ (denominator).`, ["2a"]),
  mc("medium", R`A positive discriminant means`, [R`two distinct real roots`, R`one root`, R`two complex roots`, R`no roots`], 0),
  mc("easy", R`Solve $x^2-9=0$.`, [R`$x=\pm 3$`, R`$x=3$`, R`$x=\pm 9$`, R`$x=9$`], 0),
  mc("medium", R`Solve $x^2+x-12=0$.`, [R`$x=3,-4$`, R`$x=-3,4$`, R`$x=2,-6$`, R`$x=12,-1$`], 0),
  tf("hard", R`Completing the square on $ax^2+bx+c=0$ yields the quadratic formula.`, true),
  mc("hard", R`The roots of $x^2-2x+5=0$ are`, [R`$1\pm 2i$`, R`$1\pm 2$`, R`$-1\pm 2i$`, R`$2\pm i$`], 0),
  num("medium", R`Discriminant of $x^2-4x+4$?`, 0, 0),
  mc("easy", R`Zero-product property: if $(x-2)(x+5)=0$ then`, [R`$x=2$ or $x=-5$`, R`$x=-2$ or $x=5$`, R`$x=2$ and $x=5$`, R`$x=10$`], 0),
];

// ── 1.8 Absolute Value & Inequalities ────────────────────────
const g18 = () => [
  mc("easy", R`Solve $|x-3|=5$.`, [R`$x=8,-2$`, R`$x=8,2$`, R`$x=-8,2$`, R`$x=2$`], 0),
  mc("easy", R`Solve $|x|=6$.`, [R`$x=\pm 6$`, R`$x=6$`, R`$x=-6$`, R`no solution`], 0),
  mc("easy", R`Solve $|x+2|=5$.`, [R`$x=3,-7$`, R`$x=-3,7$`, R`$x=3,7$`, R`$x=-7$`], 0),
  mc("easy", R`Solve $2x-1<7$.`, [R`$x<4$`, R`$x>4$`, R`$x<3$`, R`$x<8$`], 0),
  mc("easy", R`Solve $3x+1>10$.`, [R`$x>3$`, R`$x<3$`, R`$x>\tfrac{11}{3}$`, R`$x>9$`], 0),
  mc("medium", R`Solve $-2x<8$.`, [R`$x>-4$`, R`$x<-4$`, R`$x>4$`, R`$x<4$`], 0),
  mc("medium", R`Solve $|x|<3$.`, [R`$-3<x<3$`, R`$x<3$`, R`$x<-3$ or $x>3$`, R`$x>3$`], 0),
  mc("medium", R`Solve $|x|\ge 4$.`, [R`$x\le -4$ or $x\ge 4$`, R`$-4\le x\le 4$`, R`$x\ge 4$`, R`$x\le -4$`], 0),
  mc("medium", R`Solve $|2x-1|\le 7$.`, [R`$-3\le x\le 4$`, R`$-4\le x\le 3$`, R`$x\le 4$`, R`$-3<x<4$`], 0),
  mc("medium", R`Solve $|2x-1|>5$.`, [R`$x>3$ or $x<-2$`, R`$-2<x<3$`, R`$x>3$`, R`$x<-2$`], 0),
  mc("medium", R`Solve $-3\le 2x+1<5$.`, [R`$-2\le x<2$`, R`$-2<x\le 2$`, R`$-1\le x<2$`, R`$-2\le x\le 2$`], 0),
  mc("hard", R`Solve $|3x+2|>4$.`, [R`$x>\tfrac23$ or $x<-2$`, R`$-2<x<\tfrac23$`, R`$x>\tfrac23$`, R`$x<-2$`], 0),
  mc("hard", R`$|x-4|<2$ describes`, [R`points within $2$ of $4$: $2<x<6$`, R`$x<2$`, R`$x>6$`, R`$-2<x<2$`], 0),
  tf("easy", R`$|x|<a$ (with $a>0$) is equivalent to $-a<x<a$.`, true),
  tf("medium", R`Multiplying an inequality by a negative reverses it.`, true),
  tf("easy", R`$|x|=-3$ has no solution.`, true),
  mc("medium", R`Solve $1\le x+2\le 6$.`, [R`$-1\le x\le 4$`, R`$1\le x\le 4$`, R`$-1\le x\le 6$`, R`$3\le x\le 8$`], 0),
  mc("hard", R`Solution of $x+1<3$ OR $2x-1>7$:`, [R`$x<2$ or $x>4$`, R`$2<x<4$`, R`$x<2$`, R`$x>4$`], 0),
  mc("medium", R`Interval notation for $-3\le x<5$:`, [R`$[-3,5)$`, R`$(-3,5)$`, R`$[-3,5]$`, R`$(-3,5]$`], 0),
  mc("easy", R`Solve $x/2\ge 3$.`, [R`$x\ge 6$`, R`$x\le 6$`, R`$x\ge 1.5$`, R`$x\ge 3$`], 0),
  num("medium", R`The largest integer satisfying $2x+1<10$ is ___.`, 4, 0),
  mc("hard", R`Solve $|5-2x|=3$.`, [R`$x=1,4$`, R`$x=-1,4$`, R`$x=1,-4$`, R`$x=4$`], 0),
  mc("medium", R`Solve $4-x>1$.`, [R`$x<3$`, R`$x>3$`, R`$x<5$`, R`$x>-3$`], 0),
  tf("hard", R`$|X|>a$ (with $a>0$) means $X<-a$ or $X>a$.`, true),
];

// ── 1.9 Ratios, Proportions & Variation ──────────────────────
const g19 = () => [
  num("easy", R`Solve $\dfrac{3}{4}=\dfrac{x}{20}$.`, 15, 0),
  num("easy", R`Solve $\dfrac{5}{8}=\dfrac{x}{40}$.`, 25, 0),
  num("easy", R`Solve $\dfrac{2}{x}=\dfrac{6}{9}$.`, 3, 0),
  num("medium", R`$y=kx$; $y=12$ at $x=3$. Find $y$ at $x=7$.`, 28, 0),
  num("medium", R`$y=kx$; $y=10$ at $x=2$. Find $y$ at $x=5$.`, 25, 0),
  num("medium", R`$y=\dfrac{k}{x}$; $y=6$ at $x=4$. Find $y$ at $x=8$.`, 3, 0),
  num("medium", R`$y=\dfrac{k}{x}$; $y=9$ at $x=2$. Find $y$ at $x=6$.`, 3, 0),
  num("hard", R`$z=kxy^2$; $z=96$ at $x=3,y=2$. Find $z$ at $x=2,y=5$.`, 400, 0),
  num("hard", R`$z=kxy$; $z=30$ at $x=2,y=3$. Find $z$ at $x=4,y=5$.`, 100, 0),
  mc("easy", R`'$y$ varies inversely as the square of $x$' is`, [R`$y=\dfrac{k}{x^2}$`, R`$y=kx^2$`, R`$y=\dfrac{k}{x}$`, R`$y=kx$`], 0),
  mc("easy", R`'$z$ varies jointly as $x$ and $y$' is`, [R`$z=kxy$`, R`$z=\dfrac{k}{xy}$`, R`$z=k(x+y)$`, R`$z=kx+y$`], 0),
  mc("medium", R`In direct variation, if $x$ doubles then $y$`, [R`doubles`, R`halves`, R`is unchanged`, R`quadruples`], 0),
  mc("medium", R`In inverse variation, if $x$ doubles then $y$`, [R`is halved`, R`doubles`, R`is unchanged`, R`quadruples`], 0),
  num("medium", R`Map scale $1\,\text{cm}:15\,\text{km}$. Distance for $8$ cm (km)?`, 120, 0),
  num("hard", R`Current $I$ varies inversely as $R$; $I=4$ at $R=6$. Find $I$ at $R=8$.`, 3, 0),
  tf("easy", R`A proportion $\tfrac{a}{b}=\tfrac{c}{d}$ is equivalent to $ad=bc$.`, true),
  num("medium", R`Solve $\dfrac{x}{6}=\dfrac{10}{15}$.`, 4, 0),
  num("medium", R`$y$ varies directly as $x$; $y=21$ at $x=3$. Find $k$.`, 7, 0),
  num("hard", R`$w=\dfrac{k}{x^2}$; $w=2$ at $x=3$. Find $w$ at $x=1$.`, 18, 0),
  mc("medium", R`If $y=kx$ and the graph passes through the origin, that indicates`, [R`direct variation`, R`inverse variation`, R`joint variation`, R`no variation`], 0),
  num("easy", R`Solve $\dfrac{4}{5}=\dfrac{12}{x}$.`, 15, 0),
  num("hard", R`$A$ varies jointly as $b$ and $h$; $A=24$ at $b=6,h=2$. Find $A$ at $b=5,h=4$.`, 40, 0),
  mc("easy", R`A ratio of $3:4$ is the same as`, [R`$\tfrac{3}{4}$`, R`$\tfrac{4}{3}$`, R`$7$`, R`$12$`], 0),
  num("medium", R`Two gears in ratio $2:3$; if the small turns $60$ times, the large turns ___.`, 40, 0),
];

// ── 1.10 Algebraic Word Problems ─────────────────────────────
const g110 = () => [
  num("easy", R`Five less than twice a number is $17$. Find the number.`, 11, 0),
  num("easy", R`Three more than half a number is $11$. Find the number.`, 16, 0),
  num("medium", R`Two numbers sum to $30$ and differ by $8$. The larger is ___.`, 19, 0),
  num("medium", R`Two numbers differ by $5$ and sum to $21$. The larger is ___.`, 13, 0),
  num("medium", R`Three consecutive integers sum to $51$. The middle one is ___.`, 17, 0),
  num("medium", R`A rectangle's length is $3$ more than its width; perimeter $34$. The width is ___.`, 7, 0),
  num("medium", R`A rectangle's length is twice its width; perimeter $36$. The width is ___.`, 6, 0),
  num("hard", R`Train A at $60$ km/h; $2$ h later B at $80$ km/h same route. B catches A after ___ h (of B's travel).`, 6, 0),
  num("hard", R`How many litres of $20\%$ acid added to $10$ L of $50\%$ acid gives $30\%$?`, 20, 0),
  num("hard", R`How much water added to $10$ L of $40\%$ acid gives $25\%$? (litres)`, 6, 0),
  num("medium", R`A finishes a job in $4$ h, B in $4$ h. Together they take ___ h.`, 2, 0),
  num("hard", R`A in $4$ h, B in $6$ h. Together they take ___ h (enter as $a/b$→ compute; answer $2.4$).`, 2.4, 0.01),
  num("easy", R`Travel $175$ km at $50$ km/h takes ___ h.`, 3.5, 0.01),
  num("medium", R`\$1200 split so one part is twice the other. The smaller part is \$___.`, 400, 0),
  num("medium", R`A number is $\tfrac13$ of another; they sum to $24$. The smaller is ___.`, 6, 0),
  num("hard", R`The tens digit of a two-digit number is $2$ more than the units; the digits sum to $10$. The number is ___.`, 64, 0),
  num("medium", R`Tickets: $8$ adult, $5$ child; $20$ sold for \$130. Adults sold: ___.`, 10, 0),
  num("hard", R`A boat goes $30$ km downstream in $2$ h and returns in $3$ h. Boat speed in still water (km/h): ___.`, 12.5, 0.1),
  num("medium", R`Perimeter of a square is $48$. Its area is ___.`, 144, 0),
  num("easy", R`If $3x=21$, then $x=$ ___.`, 7, 0),
  num("medium", R`The sum of a number and its double is $27$. The number is ___.`, 9, 0),
  num("hard", R`\$5000 is split into two accounts; one earns $4\%$, the other $6\%$; total interest \$260. Amount at $6\%$ is \$___.`, 3000, 0),
  num("medium", R`A phone plan costs \$30 plus \$0.10/min. For \$45, minutes used: ___.`, 150, 0),
  num("easy", R`Twice a number decreased by $3$ equals $11$. The number is ___.`, 7, 0),
];

export default [
  { code: "1.1", gen: g11 }, { code: "1.2", gen: g12 }, { code: "1.3", gen: g13 },
  { code: "1.4", gen: g14 }, { code: "1.5", gen: g15 }, { code: "1.6", gen: g16 },
  { code: "1.7", gen: g17 }, { code: "1.8", gen: g18 }, { code: "1.9", gen: g19 },
  { code: "1.10", gen: g110 },
];
