// FTCE Unit 2 — Functions. ~24 curated questions per topic. Answers verified.
import { mc, tf, num, fill } from "./helpers.mjs";
const R = String.raw;

// ── 2.1 Functions: Domain & Range ────────────────────────────
const g21 = () => [
  num("easy", R`For $f(x)=3x-5$, find $f(4)$.`, 7, 0),
  num("easy", R`For $f(x)=x^2+1$, find $f(-3)$.`, 10, 0),
  num("easy", R`For $f(x)=7x^2+3$, find $f(2)$.`, 31, 0),
  num("medium", R`For $f(x)=2x^2-x$, find $f(3)$.`, 15, 0),
  num("easy", R`For $f(x)=|x-3|$, find $f(-1)$.`, 4, 0),
  mc("easy", R`Domain of $f(x)=\dfrac{1}{x+2}$.`, [R`$x\ne -2$`, R`$x\ne 2$`, R`all reals`, R`$x>0$`], 0),
  mc("easy", R`Domain of $\sqrt{x-5}$.`, [R`$x\ge 5$`, R`$x\le 5$`, R`$x>5$`, R`all reals`], 0),
  mc("medium", R`Domain of $\dfrac{x}{x^2-9}$.`, [R`$x\ne \pm 3$`, R`$x\ne 3$`, R`$x\ne 9$`, R`all reals`], 0),
  mc("medium", R`Domain of $y=\sqrt{-x+1}$.`, [R`$x\le 1$`, R`$x\ge 1$`, R`$x\le -1$`, R`all reals`], 0),
  mc("hard", R`Domain of $\dfrac{\sqrt{x}}{x-2}$.`, [R`$[0,2)\cup(2,\infty)$`, R`$x\ge 0$`, R`$x\ne 2$`, R`$(0,\infty)$`], 0),
  mc("hard", R`Domain of $\dfrac{x+1}{(x-1)(x+4)}$.`, [R`$x\ne 1,-4$`, R`$x\ne -1,4$`, R`$x\ne 1$`, R`all reals`], 0),
  mc("easy", R`Range of $f(x)=x^2$.`, [R`$y\ge 0$`, R`$y\le 0$`, R`all reals`, R`$y>0$`], 0),
  mc("medium", R`Range of $f(x)=-x^2+3$.`, [R`$y\le 3$`, R`$y\ge 3$`, R`$y\le 0$`, R`all reals`], 0),
  mc("medium", R`Range of $f(x)=x^2-4$.`, [R`$y\ge -4$`, R`$y\ge 4$`, R`$y\le -4$`, R`all reals`], 0),
  mc("easy", R`Range of $f(x)=|x|$.`, [R`$y\ge 0$`, R`$y\le 0$`, R`all reals`, R`$y>0$`], 0),
  mc("medium", R`Domain of $\dfrac{5}{x^2+1}$.`, [R`all reals`, R`$x\ne 1$`, R`$x\ne \pm 1$`, R`$x>0$`], 0),
  mc("hard", R`Range of $f(x)=-2(x-1)^2+5$.`, [R`$y\le 5$`, R`$y\ge 5$`, R`$y\le 1$`, R`all reals`], 0),
  mc("easy", R`Does a vertical line represent a function?`, [R`no`, R`yes`, R`only if steep`, R`sometimes`], 0),
  tf("easy", R`The vertical-line test identifies whether a graph is a function.`, true),
  mc("medium", R`Domain of $\sqrt{3-x}$.`, [R`$x\le 3$`, R`$x\ge 3$`, R`$x\le -3$`, R`all reals`], 0),
  mc("medium", R`Range of $\sqrt{x}$.`, [R`$y\ge 0$`, R`all reals`, R`$y\le 0$`, R`$y>0$`], 0),
  num("hard", R`For $f(x)=x^2-1$, find $f(4)$.`, 15, 0),
  tf("medium", R`The range of an upward parabola is bounded below.`, true),
  mc("hard", R`Excluded values of $f(x)=\dfrac{1}{x^2-x-6}$.`, [R`$x=3,-2$`, R`$x=-3,2$`, R`$x=6,-1$`, R`none`], 0),
];

// ── 2.2 Function Arithmetic & Composition ────────────────────
const g22 = () => [
  num("easy", R`$f(x)=x+1$, $g(x)=x^2$: find $(f+g)(2)$.`, 7, 0),
  mc("easy", R`$f(x)=2x$, $g(x)=x-3$: $(fg)(x)=$`, [R`$2x^2-6x$`, R`$2x-6$`, R`$2x^2-3$`, R`$2x^2+6x$`], 0),
  mc("easy", R`$f(x)=3x$, $g(x)=x+1$: $(f\circ g)(x)=$`, [R`$3x+3$`, R`$3x+1$`, R`$x+3$`, R`$3x$`], 0),
  mc("easy", R`$f(x)=x^2$, $g(x)=x-4$: $(g\circ f)(x)=$`, [R`$x^2-4$`, R`$(x-4)^2$`, R`$x^2-16$`, R`$x-4$`], 0),
  mc("medium", R`$f(x)=x^2$, $g(x)=\sqrt{x}$: $(f\circ g)(x)$ for $x\ge0$ is`, [R`$x$`, R`$x^2$`, R`$\sqrt{x}$`, R`$x\sqrt x$`], 0),
  mc("easy", R`$f(x)=x-5$, $g(x)=x+5$: $(f\circ g)(x)=$`, [R`$x$`, R`$x+10$`, R`$x-10$`, R`$2x$`], 0),
  tf("easy", R`In general $f\circ g=g\circ f$.`, false),
  mc("medium", R`$f(x)=2x+1$: $(f\circ f)(x)=$`, [R`$4x+3$`, R`$4x+1$`, R`$2x+2$`, R`$4x^2+1$`], 0),
  num("medium", R`$f(x)=7x^2+3$, $g(x)=2x-9$: find $g(f(2))$.`, 53, 0),
  mc("medium", R`$f(x)=x^2$, $g(x)=2x-1$: $(f+g)(x)=$`, [R`$x^2+2x-1$`, R`$x^2+2x+1$`, R`$x^2-2x-1$`, R`$2x^2-1$`], 0),
  mc("medium", R`$f(x)=x^2$, $g(x)=x-1$: $(f-g)(x)=$`, [R`$x^2-x+1$`, R`$x^2-x-1$`, R`$x^2+x-1$`, R`$x^2-1$`], 0),
  num("medium", R`$f(x)=x^2$, $g(x)=x-1$: find $(f\circ g)(3)$.`, 4, 0),
  mc("hard", R`$f(x)=\tfrac1x$, $g(x)=x-2$: domain of $(f\circ g)$`, [R`$x\ne 2$`, R`$x\ne 0$`, R`all reals`, R`$x\ne -2$`], 0),
  mc("medium", R`$f(x)=\sqrt{x}$, $g(x)=x+4$: $(f\circ g)(x)=$`, [R`$\sqrt{x+4}$`, R`$\sqrt{x}+4$`, R`$x+4$`, R`$\sqrt{x}+2$`], 0),
  num("easy", R`$f(x)=x+1$, $g(x)=2x$: find $(f\circ g)(0)$.`, 1, 0),
  mc("easy", R`In $(f\circ g)(x)$, which function acts first?`, [R`$g$`, R`$f$`, R`both at once`, R`neither`], 0),
  num("medium", R`$f(x)=x^2$, $g(x)=3x-1$: find $f(g(1))$.`, 4, 0),
  mc("medium", R`The domain of $(f/g)(x)$ excludes`, [R`zeros of $g$`, R`zeros of $f$`, R`negatives`, R`nothing`], 0),
  mc("hard", R`$f(x)=\sqrt{x}$, $g(x)=x^2$: $(g\circ f)(x)$ for $x\ge0$ is`, [R`$x$`, R`$x^2$`, R`$\sqrt x$`, R`$x^4$`], 0),
  num("hard", R`$f(x)=x+2$: find $(f\circ f\circ f)(1)$.`, 7, 0),
  mc("hard", R`$f(x)=3x-1$, $g(x)=\dfrac{x+1}{3}$: $(f\circ g)(x)=$`, [R`$x$`, R`$3x-1$`, R`$\tfrac{x+1}{3}$`, R`$9x$`], 0),
  tf("medium", R`Composing a function with its inverse returns $x$.`, true),
  num("easy", R`$f(x)=x$, $g(x)=x+1$: find $(fg)(2)$.`, 6, 0),
  mc("hard", R`$f(x)=x^2+1$, $g(x)=x-1$: $(f\circ g)(x)=$`, [R`$x^2-2x+2$`, R`$x^2+1$`, R`$x^2-2x$`, R`$(x-1)^2$`], 0),
];

// ── 2.3 Inverse Functions ────────────────────────────────────
const g23 = () => [
  mc("easy", R`Inverse of $f(x)=x+7$.`, [R`$x-7$`, R`$7-x$`, R`$\tfrac{x}{7}$`, R`$7x$`], 0),
  mc("easy", R`Inverse of $f(x)=3x$.`, [R`$\tfrac{x}{3}$`, R`$3x$`, R`$x-3$`, R`$\tfrac{3}{x}$`], 0),
  mc("easy", R`Inverse of $f(x)=x-4$.`, [R`$x+4$`, R`$4-x$`, R`$4x$`, R`$\tfrac{x}{4}$`], 0),
  mc("medium", R`Inverse of $f(x)=\dfrac{x-1}{2}$.`, [R`$2x+1$`, R`$2x-1$`, R`$\tfrac{x+1}{2}$`, R`$\tfrac{2}{x-1}$`], 0),
  mc("medium", R`Inverse of $f(x)=2x+3$.`, [R`$\dfrac{x-3}{2}$`, R`$\dfrac{x+3}{2}$`, R`$2x-3$`, R`$\dfrac{1}{2x+3}$`], 0),
  mc("medium", R`Inverse of $f(x)=x^3$.`, [R`$\sqrt[3]{x}$`, R`$\tfrac{1}{x^3}$`, R`$x^{1/3}$ only for $x>0$`, R`$3x$`], 0),
  mc("hard", R`Inverse of $f(x)=\dfrac{x+1}{x-2}$.`, [R`$\dfrac{2x+1}{x-1}$`, R`$\dfrac{x-1}{2x+1}$`, R`$\dfrac{x-2}{x+1}$`, R`$\dfrac{2x-1}{x+1}$`], 0),
  mc("hard", R`Inverse of $f(x)=x^3+1$.`, [R`$\sqrt[3]{x-1}$`, R`$\sqrt[3]{x}-1$`, R`$\sqrt[3]{x+1}$`, R`$(x-1)^3$`], 0),
  mc("easy", R`$f$ and $f^{-1}$ are reflections across`, [R`$y=x$`, R`the $x$-axis`, R`the $y$-axis`, R`the origin`], 0),
  mc("easy", R`Does $f(x)=x^2$ over all reals have an inverse?`, [R`no`, R`yes`, R`only for $x<0$`, R`always`], 0),
  tf("easy", R`$f^{-1}(x)$ equals $\dfrac{1}{f(x)}$.`, false),
  mc("medium", R`Which functions have inverses?`, [R`one-to-one functions`, R`even functions`, R`all functions`, R`periodic functions`], 0),
  tf("medium", R`The domain and range interchange between $f$ and $f^{-1}$.`, true),
  mc("medium", R`Inverse of $f(x)=\tfrac{x}{5}$.`, [R`$5x$`, R`$\tfrac{5}{x}$`, R`$x-5$`, R`$\tfrac{x}{5}$`], 0),
  mc("medium", R`Inverse of $f(x)=4x-8$.`, [R`$\dfrac{x+8}{4}$`, R`$\dfrac{x-8}{4}$`, R`$4x+8$`, R`$\dfrac{8-x}{4}$`], 0),
  num("medium", R`If $f(3)=7$, then $f^{-1}(7)=$ ___.`, 3, 0),
  num("medium", R`For $f(x)=2x$, find $f^{-1}(10)$.`, 5, 0),
  tf("easy", R`$f\big(f^{-1}(x)\big)=x$ for $x$ in the range of $f$.`, true),
  mc("medium", R`The horizontal-line test checks whether a function`, [R`is one-to-one (invertible)`, R`is even`, R`is continuous`, R`has a maximum`], 0),
  mc("hard", R`To make $f(x)=x^2$ invertible, restrict to`, [R`$x\ge 0$`, R`$x\le 0$ only`, R`$x\ne 0$`, R`$0\le x\le 1$`], 0),
  mc("hard", R`Inverse of $f(x)=\dfrac{2x+1}{3}$.`, [R`$\dfrac{3x-1}{2}$`, R`$\dfrac{3x+1}{2}$`, R`$\dfrac{2x-1}{3}$`, R`$\dfrac{3}{2x+1}$`], 0),
  tf("medium", R`A function must be one-to-one to have an inverse function.`, true),
  mc("easy", R`Inverse of $f(x)=-x$.`, [R`$-x$`, R`$x$`, R`$\tfrac1x$`, R`$-\tfrac1x$`], 0),
  mc("medium", R`Inverse of $f(x)=2x-6$.`, [R`$\dfrac{x+6}{2}$`, R`$\dfrac{x-6}{2}$`, R`$2x+6$`, R`$\dfrac{6-x}{2}$`], 0),
];

// ── 2.4 Exponential & Logarithmic Functions ──────────────────
const g24 = () => [
  num("easy", R`Evaluate $\log_2 16$.`, 4, 0),
  num("easy", R`Evaluate $\log_3 9$.`, 2, 0),
  num("easy", R`Evaluate $\log_5 125$.`, 3, 0),
  num("easy", R`Evaluate $\log_{10} 1000$.`, 3, 0),
  num("easy", R`Evaluate $\log_4 16$.`, 2, 0),
  num("easy", R`Evaluate $\log_b 1$.`, 0, 0),
  num("medium", R`Evaluate $\log_2 8+\log_2 4$.`, 5, 0),
  num("medium", R`Solve $\log_2 x=5$.`, 32, 0),
  num("medium", R`Evaluate $\log_2 64$.`, 6, 0),
  num("medium", R`Solve $\log_x 64=3$.`, 4, 0),
  num("hard", R`Solve $\log_3(x-1)=4$.`, 82, 0),
  num("medium", R`Evaluate $\log_9 3$ (decimal).`, 0.5, 0.01),
  mc("medium", R`Evaluate $\log_2\!\tfrac18$.`, [R`$-3$`, R`$3$`, R`$-\tfrac13$`, R`$\tfrac18$`], 0),
  mc("easy", R`Write $2^5=32$ in logarithmic form.`, [R`$\log_2 32=5$`, R`$\log_5 32=2$`, R`$\log_{32} 2=5$`, R`$\log_2 5=32$`], 0),
  mc("medium", R`Expand $\log\!\dfrac{x^2 y}{z}$.`, [R`$2\log x+\log y-\log z$`, R`$2\log x-\log y+\log z$`, R`$\log(2x)+\log y-\log z$`, R`$2\log x\cdot\log y-\log z$`], 0),
  mc("hard", R`Condense $2\log a+\log b-3\log c$.`, [R`$\log\dfrac{a^2 b}{c^3}$`, R`$\log\dfrac{a^2}{bc^3}$`, R`$\log(a^2 b c^3)$`, R`$\log\dfrac{2ab}{3c}$`], 0),
  mc("easy", R`Range of $y=b^x$ (with $b>0,b\ne1$).`, [R`$y>0$`, R`all reals`, R`$y\ge 0$`, R`$y<0$`], 0),
  mc("easy", R`Domain of $y=\log x$.`, [R`$x>0$`, R`$x\ge 0$`, R`all reals`, R`$x\ne 0$`], 0),
  mc("easy", R`$y=b^x$ passes through`, [R`$(0,1)$`, R`$(1,0)$`, R`$(0,0)$`, R`$(1,1)$`], 0),
  mc("medium", R`Horizontal asymptote of $y=b^x$.`, [R`$y=0$`, R`$x=0$`, R`$y=1$`, R`none`], 0),
  tf("hard", R`$\log_b(M+N)=\log_b M+\log_b N$.`, false),
  mc("medium", R`Solve $2^x=8$.`, [R`$x=3$`, R`$x=4$`, R`$x=2$`, R`$x=\tfrac83$`], 0),
  num("easy", R`Evaluate $\log_7 1$.`, 0, 0),
  tf("medium", R`A logarithm is the inverse of an exponential with the same base.`, true),
];

// ── 2.5 Properties of Functions ──────────────────────────────
const g25 = () => [
  mc("easy", R`$f(x)=x^2$ is`, [R`even`, R`odd`, R`neither`, R`both`], 0),
  mc("easy", R`$f(x)=x^3$ is`, [R`odd`, R`even`, R`neither`, R`both`], 0),
  mc("easy", R`$f(x)=x^2+1$ is`, [R`even`, R`odd`, R`neither`, R`both`], 0),
  mc("easy", R`$f(x)=x^3-x$ is`, [R`odd`, R`even`, R`neither`, R`both`], 0),
  mc("easy", R`$f(x)=|x|$ is`, [R`even`, R`odd`, R`neither`, R`both`], 0),
  mc("medium", R`$f(x)=x^2+x$ is`, [R`neither`, R`even`, R`odd`, R`both`], 0),
  mc("medium", R`$f(x)=x^4-3x^2$ is`, [R`even`, R`odd`, R`neither`, R`both`], 0),
  mc("medium", R`$f(x)=x^3+x$ is`, [R`odd`, R`even`, R`neither`, R`both`], 0),
  mc("medium", R`$f(x)=x^3+x^2$ is`, [R`neither`, R`even`, R`odd`, R`both`], 0),
  mc("easy", R`Zeros of $f(x)=x^2-9$.`, [R`$x=\pm 3$`, R`$x=9$`, R`$x=3$`, R`$x=\pm 9$`], 0),
  mc("medium", R`Zeros of $f(x)=x^2-5x+6$.`, [R`$x=2,3$`, R`$x=-2,-3$`, R`$x=1,6$`, R`$x=5,6$`], 0),
  mc("hard", R`Zeros of $f(x)=x^3-4x$.`, [R`$x=0,\pm 2$`, R`$x=\pm 2$`, R`$x=0,4$`, R`$x=\pm 4$`], 0),
  mc("easy", R`Period of $\cos x$.`, [R`$2\pi$`, R`$\pi$`, R`$\tfrac{\pi}{2}$`, R`$4\pi$`], 0),
  mc("medium", R`Period of $\sin(2x)$.`, [R`$\pi$`, R`$2\pi$`, R`$\tfrac{\pi}{2}$`, R`$4\pi$`], 0),
  mc("hard", R`Period of $\cos(3x)$.`, [R`$\tfrac{2\pi}{3}$`, R`$3\pi$`, R`$2\pi$`, R`$\tfrac{\pi}{3}$`], 0),
  mc("easy", R`A one-to-one function passes the`, [R`horizontal-line test`, R`vertical-line test`, R`ratio test`, R`slope test`], 0),
  tf("easy", R`An even function is symmetric about the $y$-axis.`, true),
  tf("easy", R`An odd function is symmetric about the origin.`, true),
  mc("medium", R`$f(-x)=-f(x)$ defines an`, [R`odd function`, R`even function`, R`inverse`, R`identity`], 0),
  mc("medium", R`$f(-x)=f(x)$ defines an`, [R`even function`, R`odd function`, R`one-to-one function`, R`periodic function`], 0),
  num("easy", R`How many real zeros does $f(x)=x^2-4$ have?`, 2, 0),
  mc("medium", R`Is $f(x)=x^2$ one-to-one over all reals?`, [R`no`, R`yes`, R`only for $x=0$`, R`always`], 0),
  mc("medium", R`Is $f(x)=x^3$ one-to-one over all reals?`, [R`yes`, R`no`, R`only for $x>0$`, R`never`], 0),
  mc("easy", R`An $x$-intercept of a function is also called a`, [R`zero (root)`, R`vertex`, R`asymptote`, R`maximum`], 0),
];

// ── 2.6 Graphing, Symmetry & Asymptotes ──────────────────────
const g26 = () => [
  mc("easy", R`Vertical asymptote of $\dfrac{1}{x-3}$.`, [R`$x=3$`, R`$x=-3$`, R`$y=3$`, R`$x=0$`], 0),
  mc("easy", R`Vertical asymptote of $\dfrac{1}{x+4}$.`, [R`$x=-4$`, R`$x=4$`, R`$y=-4$`, R`$x=0$`], 0),
  mc("medium", R`Horizontal asymptote of $\dfrac{2x}{x+1}$.`, [R`$y=2$`, R`$y=0$`, R`$y=1$`, R`none`], 0),
  mc("medium", R`Horizontal asymptote of $\dfrac{3x}{x-2}$.`, [R`$y=3$`, R`$y=0$`, R`$y=-2$`, R`none`], 0),
  mc("medium", R`Horizontal asymptote of $\dfrac{x}{x^2+1}$.`, [R`$y=0$`, R`$y=1$`, R`none`, R`$y=x$`], 0),
  mc("medium", R`Horizontal asymptote of $\dfrac{5}{x^2+1}$.`, [R`$y=0$`, R`$y=5$`, R`none`, R`$y=1$`], 0),
  mc("medium", R`$y$-intercept of $f(x)=\dfrac{x-1}{x+2}$.`, [R`$(0,-\tfrac12)$`, R`$(0,\tfrac12)$`, R`$(0,-1)$`, R`$(0,2)$`], 0),
  mc("easy", R`$y=x^2$ is symmetric about the`, [R`$y$-axis`, R`origin`, R`$x$-axis`, R`line $y=x$`], 0),
  mc("easy", R`$y=\dfrac1x$ is symmetric about the`, [R`origin`, R`$y$-axis`, R`$x$-axis`, R`line $y=x$`], 0),
  mc("hard", R`Vertical asymptotes of $\dfrac{x+1}{x^2-4}$.`, [R`$x=\pm 2$`, R`$x=2$`, R`$x=\pm 1$`, R`$x=4$`], 0),
  mc("medium", R`$x$-intercept of $f(x)=\dfrac{x-5}{x+1}$.`, [R`$(5,0)$`, R`$(-1,0)$`, R`$(0,-5)$`, R`$(0,5)$`], 0),
  mc("easy", R`$y=x^3$ is symmetric about the`, [R`origin`, R`$y$-axis`, R`$x$-axis`, R`line $y=x$`], 0),
  mc("easy", R`$y=x^4$ is symmetric about the`, [R`$y$-axis`, R`origin`, R`$x$-axis`, R`line $y=-x$`], 0),
  tf("medium", R`A vertical asymptote requires the numerator to be nonzero there.`, true),
  mc("hard", R`Horizontal asymptote of $\dfrac{x^2+1}{x}$.`, [R`none (numerator degree larger)`, R`$y=0$`, R`$y=1$`, R`$y=x$`], 0),
  mc("medium", R`$y$-intercept of $f(x)=\dfrac{x-2}{x+4}$.`, [R`$(0,-\tfrac12)$`, R`$(0,\tfrac12)$`, R`$(0,2)$`, R`$(0,-2)$`], 0),
  mc("medium", R`$x$-intercept of $f(x)=\dfrac{2x-6}{x+1}$.`, [R`$(3,0)$`, R`$(-1,0)$`, R`$(0,-6)$`, R`$(6,0)$`], 0),
  mc("hard", R`Horizontal asymptote of $\dfrac{6x^2}{3x^2+1}$.`, [R`$y=2$`, R`$y=0$`, R`$y=6$`, R`none`], 0),
  mc("hard", R`Vertical asymptotes of $\dfrac{x}{x^2-x-6}$.`, [R`$x=3,-2$`, R`$x=-3,2$`, R`$x=6,-1$`, R`$x=0$`], 0),
  tf("medium", R`$x$-axis symmetry means the relation is not a function.`, true),
  mc("easy", R`$y=x^2+1$ is symmetric about the`, [R`$y$-axis`, R`origin`, R`$x$-axis`, R`line $y=x$`], 0),
  mc("medium", R`Which of these is odd: $x^3,\ x^2,\ |x|,\ x^2+1$?`, [R`$x^3$`, R`$x^2$`, R`$|x|$`, R`$x^2+1$`], 0),
  num("medium", R`Number of vertical asymptotes of $\dfrac{1}{(x-1)(x+2)}$.`, 2, 0),
  mc("medium", R`Horizontal asymptote of $\dfrac{3x+1}{x-5}$.`, [R`$y=3$`, R`$y=0$`, R`$y=-5$`, R`none`], 0),
];

export default [
  { code: "2.1", gen: g21 }, { code: "2.2", gen: g22 }, { code: "2.3", gen: g23 },
  { code: "2.4", gen: g24 }, { code: "2.5", gen: g25 }, { code: "2.6", gen: g26 },
];
