// FTCE Unit 3 — Geometry. ~24 curated questions per topic. Answers verified.
import { mc, tf, num, fill } from "./helpers.mjs";
const R = String.raw;

// ── 3.1 Angles & Angle Relationships ─────────────────────────
const g31 = () => [
  num("easy", R`Complement of $20^\circ$? (degrees)`, 70, 0),
  num("easy", R`Complement of $35^\circ$?`, 55, 0),
  num("easy", R`Supplement of $45^\circ$?`, 135, 0),
  num("easy", R`Supplement of $110^\circ$?`, 70, 0),
  num("easy", R`Vertical angle of $72^\circ$?`, 72, 0),
  num("easy", R`Linear pair with $130^\circ$?`, 50, 0),
  num("easy", R`Measure of a right angle?`, 90, 0),
  mc("easy", R`An angle of $120^\circ$ is`, [R`obtuse`, R`acute`, R`right`, R`straight`], 0),
  mc("easy", R`An angle of $30^\circ$ is`, [R`acute`, R`obtuse`, R`right`, R`reflex`], 0),
  num("medium", R`Two complementary angles: one is twice the other. The smaller is ___ degrees.`, 30, 0),
  num("medium", R`Two supplementary angles: one is three times the other. The smaller is ___ degrees.`, 45, 0),
  num("medium", R`Corresponding angle to $55^\circ$ (parallel lines)?`, 55, 0),
  num("medium", R`Co-interior angle to $70^\circ$ (parallel lines)?`, 110, 0),
  num("medium", R`Alternate interior angle to $65^\circ$?`, 65, 0),
  num("hard", R`An angle is $20^\circ$ more than its complement. The angle is ___ degrees.`, 55, 0),
  num("hard", R`An angle is $40^\circ$ less than its supplement. The angle is ___ degrees.`, 70, 0),
  tf("easy", R`Complementary angles sum to $90^\circ$.`, true),
  tf("easy", R`Supplementary angles sum to $180^\circ$.`, true),
  tf("medium", R`A linear pair is always supplementary.`, true),
  tf("medium", R`Vertical angles are supplementary.`, false),
  num("medium", R`Two complementary angles in ratio $1:4$: the larger is ___ degrees.`, 72, 0),
  num("hard", R`Three angles on a straight line are $x$, $2x$, $3x$. Find $x$ (degrees).`, 30, 0),
  mc("medium", R`Same-side interior angles on parallel lines are`, [R`supplementary`, R`equal`, R`complementary`, R`vertical`], 0),
  num("easy", R`Supplement of $90^\circ$?`, 90, 0),
];

// ── 3.2 Proof: Congruent Segments, Angles & Perpendiculars ───
const g32 = () => [
  num("easy", R`$M$ midpoint of $\overline{AB}$, $AB=12$. Find $AM$.`, 6, 0),
  num("easy", R`$M$ midpoint of $\overline{AB}$, $AB=20$. Find $AM$.`, 10, 0),
  num("medium", R`A bisector splits a $100^\circ$ angle into ___ degrees each.`, 50, 0),
  num("medium", R`A ray bisects an $80^\circ$ angle; each part is ___ degrees.`, 40, 0),
  num("easy", R`Perpendicular lines meet at ___ degrees.`, 90, 0),
  fill("easy", R`A segment congruent to itself illustrates the ___ property.`, ["reflexive"]),
  fill("medium", R`A perpendicular bisector passes through the ___ of the segment.`, ["midpoint"]),
  fill("medium", R`If $AM=MB$ then $M$ is the ___ of $\overline{AB}$.`, ["midpoint"]),
  fill("medium", R`Distance from a point to a line is measured along the ___.`, ["perpendicular"]),
  tf("easy", R`A midpoint divides a segment into two congruent parts.`, true),
  tf("medium", R`Every point on the perpendicular bisector of $\overline{AB}$ is equidistant from $A$ and $B$.`, true),
  tf("medium", R`An angle bisector creates two congruent angles.`, true),
  mc("medium", R`Two angles that form a linear pair and are congruent each measure`, [R`$90^\circ$`, R`$45^\circ$`, R`$60^\circ$`, R`$180^\circ$`], 0),
  mc("easy", R`If $M$ bisects $\overline{AB}$ and $AB=16$, then $MB=$`, [R`$8$`, R`$16$`, R`$4$`, R`$32$`], 0),
  mc("medium", R`Angles supplementary to the same angle are`, [R`congruent`, R`complementary`, R`vertical`, R`perpendicular`], 0),
  num("medium", R`$M$ midpoint of $\overline{AB}$, $AM=7$. Find $AB$.`, 14, 0),
  num("hard", R`$B$ is between $A$ and $C$; $AB=5$, $BC=9$. Find $AC$.`, 14, 0),
  num("hard", R`$\overrightarrow{OB}$ bisects $\angle AOC=68^\circ$. Find $\angle AOB$ (degrees).`, 34, 0),
  fill("hard", R`Two angles complementary to the same angle are ___.`, ["congruent", "equal"]),
  tf("easy", R`Perpendicular lines form four right angles.`, true),
  mc("hard", R`In a proof, "shared side" is justified by the`, [R`reflexive property`, R`transitive property`, R`symmetric property`, R`substitution`], 0),
  num("medium", R`A bisector splits a $150^\circ$ angle into ___ degrees each.`, 75, 0),
  tf("medium", R`If two segments are each congruent to a third, they are congruent to each other (transitive).`, true),
  num("easy", R`A right angle bisected gives ___ degrees each.`, 45, 0),
];

// ── 3.3 Triangles & Classification ───────────────────────────
const g33 = () => [
  num("easy", R`Third angle if two are $50^\circ$ and $60^\circ$?`, 70, 0),
  num("easy", R`Third angle if two are $45^\circ$ and $45^\circ$?`, 90, 0),
  num("easy", R`Each angle of an equilateral triangle?`, 60, 0),
  num("medium", R`Base angle of an isosceles triangle with vertex $40^\circ$?`, 70, 0),
  num("medium", R`Base angle of an isosceles triangle with vertex $100^\circ$?`, 40, 0),
  num("medium", R`Exterior angle with remote interiors $30^\circ$ and $80^\circ$?`, 110, 0),
  num("medium", R`Exterior angle with remote interiors $40^\circ$ and $55^\circ$?`, 95, 0),
  mc("easy", R`A triangle with a $90^\circ$ angle is`, [R`right`, R`acute`, R`obtuse`, R`equiangular`], 0),
  mc("easy", R`A triangle with sides $5,5,8$ is`, [R`isosceles`, R`scalene`, R`equilateral`, R`right`], 0),
  mc("medium", R`A triangle with sides $6,8,10$ is`, [R`right`, R`acute`, R`obtuse`, R`equilateral`], 0),
  tf("easy", R`Do sides $3,4,5$ form a right triangle?`, true),
  tf("medium", R`Can sides $2,3,6$ form a triangle?`, false),
  tf("medium", R`Can sides $4,4,10$ form a triangle?`, false),
  tf("easy", R`The interior angles of a triangle sum to $180^\circ$.`, true),
  mc("medium", R`The longest side of a triangle is opposite the`, [R`largest angle`, R`smallest angle`, R`right angle`, R`vertex`], 0),
  num("hard", R`Angles in ratio $2:3:4$: the largest is ___ degrees.`, 80, 0),
  num("hard", R`A right triangle has one acute angle $37^\circ$; the other acute angle is ___ degrees.`, 53, 0),
  mc("medium", R`Sides $7,7,7$ form a(n)`, [R`equilateral triangle`, R`isosceles-only triangle`, R`scalene triangle`, R`right triangle`], 0),
  num("medium", R`Two angles of a triangle are $x$ and $x$; the third is $80^\circ$. Find $x$.`, 50, 0),
  tf("medium", R`Do sides $5,12,13$ form a right triangle?`, true),
  mc("hard", R`A triangle with sides $5,6,10$ (since $5^2+6^2<10^2$) is`, [R`obtuse`, R`acute`, R`right`, R`impossible`], 0),
  num("easy", R`Third angle if two are $30^\circ$ and $90^\circ$?`, 60, 0),
  mc("easy", R`A triangle with all sides different is`, [R`scalene`, R`isosceles`, R`equilateral`, R`equiangular`], 0),
  num("hard", R`Exterior angle of $115^\circ$; one remote interior is $70^\circ$. The other is ___ degrees.`, 45, 0),
];

// ── 3.4 Similar Triangles & Polygons ─────────────────────────
const g34 = () => [
  num("easy", R`Similar: $3,4,5\sim 6,8,x$. Find $x$.`, 10, 0),
  num("easy", R`Similar: $2,3,4\sim 4,6,x$. Find $x$.`, 8, 0),
  num("medium", R`Similar: $6,8,10\sim 9,12,x$. Find $x$.`, 15, 0),
  mc("easy", R`Scale factor $1:3$ gives area ratio`, [R`$1:9$`, R`$1:3$`, R`$1:6$`, R`$3:1$`], 0),
  mc("medium", R`Scale factor $2:5$ gives area ratio`, [R`$4:25$`, R`$2:5$`, R`$8:125$`, R`$4:10$`], 0),
  mc("medium", R`Area ratio $9:16$ gives side ratio`, [R`$3:4$`, R`$9:16$`, R`$81:256$`, R`$3:16$`], 0),
  mc("medium", R`Area ratio $4:25$ gives side ratio`, [R`$2:5$`, R`$4:25$`, R`$16:625$`, R`$2:25$`], 0),
  num("medium", R`A $6$-ft person casts a $4$-ft shadow; a tree casts $20$ ft. Tree height (ft)?`, 30, 0),
  num("medium", R`A $5$-ft person casts a $3$-ft shadow; a pole casts $12$ ft. Pole height (ft)?`, 20, 0),
  fill("easy", R`The ratio of perimeters of similar figures equals the ratio of ___.`, ["sides", "corresponding sides"]),
  num("easy", R`AA similarity requires how many pairs of equal angles?`, 2, 0),
  tf("easy", R`Corresponding angles of similar figures are equal.`, true),
  tf("medium", R`Corresponding sides of similar figures are proportional.`, true),
  num("hard", R`Similar triangles areas $12$ and $48$: side ratio is $1:$ ___.`, 2, 0),
  num("medium", R`Scale $1:50$; a $2$-cm model wall is ___ cm in reality.`, 100, 0),
  mc("medium", R`Which is NOT a triangle-similarity criterion?`, [R`SSA`, R`AA`, R`SSS`, R`SAS`], 0),
  num("hard", R`Two similar polygons have perimeters $18$ and $30$; the side of the first is $6$, the corresponding side of the second is ___.`, 10, 0),
  num("medium", R`Similar: $4,6\sim 10,x$ (corresponding). Find $x$.`, 15, 0),
  tf("medium", R`All squares are similar.`, true),
  tf("hard", R`All rectangles are similar.`, false),
  num("hard", R`A map scale is $1\,\text{cm}:8\,\text{km}$. A $5.5$-cm distance is ___ km.`, 44, 0),
  num("easy", R`Similar: $1,2,3\sim 2,4,x$. Find $x$.`, 6, 0),
  mc("medium", R`If two triangles are similar with ratio $3:1$, the larger area is ___ times the smaller.`, [R`$9$`, R`$3$`, R`$6$`, R`$27$`], 0),
  num("medium", R`A $10$-m flagpole casts a $4$-m shadow; a nearby person casts a $0.8$-m shadow. Person height (m)?`, 2, 0),
];

// ── 3.5 Regular Polygons, Area & Perimeter ───────────────────
const g35 = () => [
  num("easy", R`Sum of interior angles of a quadrilateral (degrees)?`, 360, 0),
  num("easy", R`Sum of interior angles of a pentagon?`, 540, 0),
  num("medium", R`Sum of interior angles of a hexagon?`, 720, 0),
  num("easy", R`Each interior angle of a regular pentagon?`, 108, 0),
  num("medium", R`Each interior angle of a regular hexagon?`, 120, 0),
  num("medium", R`Each interior angle of a regular octagon?`, 135, 0),
  num("easy", R`Each exterior angle of a regular hexagon?`, 60, 0),
  num("medium", R`Each exterior angle of a regular octagon?`, 45, 0),
  num("medium", R`Each exterior angle of a regular decagon?`, 36, 0),
  num("medium", R`Number of sides if each exterior angle is $30^\circ$?`, 12, 0),
  num("hard", R`Number of sides if each exterior angle is $24^\circ$?`, 15, 0),
  num("hard", R`Number of sides if each interior angle is $150^\circ$?`, 12, 0),
  num("easy", R`Area of a triangle with base $10$, height $6$?`, 30, 0),
  num("easy", R`Area of a parallelogram with base $7$, height $4$?`, 28, 0),
  num("medium", R`Area of a trapezoid with bases $8,14$ and height $6$?`, 66, 0),
  num("medium", R`Area of a trapezoid with bases $6,10$ and height $4$?`, 32, 0),
  mc("easy", R`Area of a circle with radius $3$?`, [R`$9\pi$`, R`$6\pi$`, R`$3\pi$`, R`$9$`], 0),
  num("medium", R`Area of a regular polygon with apothem $5$ and perimeter $30$?`, 75, 0),
  num("hard", R`Area of a regular polygon with apothem $4$ and perimeter $20$?`, 40, 0),
  num("hard", R`Sum of interior angles of a decagon?`, 1440, 0),
  tf("easy", R`Each exterior angle of a regular $n$-gon is $360^\circ/n$.`, true),
  num("medium", R`Perimeter of a regular pentagon with side $8$?`, 40, 0),
  num("easy", R`Area of a rectangle $5\times 9$?`, 45, 0),
  num("hard", R`A regular polygon's interior angle is $140^\circ$; number of sides?`, 9, 0),
];

// ── 3.6 Quadrilaterals ───────────────────────────────────────
const g36 = () => [
  fill("easy", R`Opposite angles of a parallelogram are ___.`, ["equal", "congruent"]),
  fill("easy", R`Diagonals of a rectangle are ___.`, ["equal", "congruent"]),
  fill("medium", R`Diagonals of a rhombus are ___.`, ["perpendicular"]),
  num("medium", R`Area of a rhombus with diagonals $6$ and $8$?`, 24, 0),
  num("medium", R`Area of a rhombus with diagonals $10$ and $12$?`, 60, 0),
  num("easy", R`Trapezoid midsegment with bases $10$ and $16$?`, 13, 0),
  num("easy", R`Trapezoid midsegment with bases $8$ and $12$?`, 10, 0),
  num("easy", R`Sum of the angles of any quadrilateral (degrees)?`, 360, 0),
  num("medium", R`Diagonal of a $5\times12$ rectangle?`, 13, 0),
  num("medium", R`Diagonal of a $6\times8$ rectangle?`, 10, 0),
  num("easy", R`Area of a parallelogram with base $9$, height $5$?`, 45, 0),
  num("medium", R`One angle of a parallelogram is $70^\circ$; an adjacent angle is ___ degrees.`, 110, 0),
  mc("easy", R`A square is a special`, [R`rhombus and rectangle`, R`trapezoid`, R`kite only`, R`scalene quadrilateral`], 0),
  tf("easy", R`Diagonals of a parallelogram bisect each other.`, true),
  tf("medium", R`Every rectangle is a parallelogram.`, true),
  tf("medium", R`Every parallelogram is a rectangle.`, false),
  num("hard", R`A rhombus has area $48$ and one diagonal $8$; the other diagonal is ___.`, 12, 0),
  num("hard", R`A square has diagonal $10$; its area is ___.`, 50, 0),
  num("medium", R`Area of a square with side $7$?`, 49, 0),
  mc("medium", R`A trapezoid has exactly ___ pair(s) of parallel sides.`, [R`one`, R`two`, R`zero`, R`three`], 0),
  num("medium", R`Perimeter of a rhombus with side $9$?`, 36, 0),
  tf("easy", R`Opposite sides of a parallelogram are equal.`, true),
  num("hard", R`A parallelogram has base $12$ and area $84$; its height is ___.`, 7, 0),
  num("medium", R`A rectangle has length $10$ and area $70$; its width is ___.`, 7, 0),
];

// ── 3.7 Circles ──────────────────────────────────────────────
const g37 = () => [
  mc("easy", R`Circumference of a circle with radius $5$?`, [R`$10\pi$`, R`$5\pi$`, R`$25\pi$`, R`$20\pi$`], 0),
  mc("easy", R`Circumference of a circle with diameter $10$?`, [R`$10\pi$`, R`$5\pi$`, R`$100\pi$`, R`$20\pi$`], 0),
  mc("easy", R`Area of a circle with radius $4$?`, [R`$16\pi$`, R`$8\pi$`, R`$4\pi$`, R`$16$`], 0),
  mc("medium", R`Area of a circle with radius $7$?`, [R`$49\pi$`, R`$14\pi$`, R`$7\pi$`, R`$49$`], 0),
  num("easy", R`Inscribed angle intercepting an $80^\circ$ arc (degrees)?`, 40, 0),
  num("medium", R`Inscribed angle intercepting a $100^\circ$ arc?`, 50, 0),
  num("easy", R`Central angle for a $45^\circ$ arc?`, 45, 0),
  num("easy", R`Angle inscribed in a semicircle (degrees)?`, 90, 0),
  num("easy", R`Diameter if the radius is $9$?`, 18, 0),
  num("medium", R`Radius if the diameter is $22$?`, 11, 0),
  mc("medium", R`Arc length of a $90^\circ$ sector with radius $6$?`, [R`$3\pi$`, R`$6\pi$`, R`$9\pi$`, R`$\tfrac{3\pi}{2}$`], 0),
  mc("medium", R`Arc length of a $180^\circ$ sector with radius $4$?`, [R`$4\pi$`, R`$8\pi$`, R`$2\pi$`, R`$16\pi$`], 0),
  mc("medium", R`Area of a $60^\circ$ sector with radius $6$?`, [R`$6\pi$`, R`$12\pi$`, R`$36\pi$`, R`$3\pi$`], 0),
  mc("hard", R`Area of a $90^\circ$ sector with radius $8$?`, [R`$16\pi$`, R`$64\pi$`, R`$8\pi$`, R`$32\pi$`], 0),
  num("easy", R`A tangent meets the radius at ___ degrees.`, 90, 0),
  tf("easy", R`A central angle equals its intercepted arc.`, true),
  tf("medium", R`An inscribed angle is half its intercepted arc.`, true),
  mc("medium", R`A $72^\circ$ central angle is what fraction of the full circle?`, [R`$\tfrac15$`, R`$\tfrac14$`, R`$\tfrac13$`, R`$\tfrac{72}{100}$`], 0),
  num("hard", R`Two inscribed angles intercept the same arc of $50^\circ$; each is ___ degrees.`, 25, 0),
  mc("hard", R`Circumference of a circle with area $16\pi$?`, [R`$8\pi$`, R`$16\pi$`, R`$4\pi$`, R`$32\pi$`], 0),
  num("medium", R`Radius of a circle with circumference $12\pi$?`, 6, 0),
  num("hard", R`Radius of a circle with area $25\pi$?`, 5, 0),
  tf("medium", R`A chord is a segment joining two points on a circle.`, true),
  mc("easy", R`The longest chord of a circle is the`, [R`diameter`, R`radius`, R`tangent`, R`secant`], 0),
];

// ── 3.8 Volume & Surface Area of Solids ──────────────────────
const g38 = () => [
  mc("easy", R`Volume of a cylinder with $r=3$, $h=10$?`, [R`$90\pi$`, R`$30\pi$`, R`$300\pi$`, R`$9\pi$`], 0),
  mc("easy", R`Volume of a cylinder with $r=2$, $h=5$?`, [R`$20\pi$`, R`$10\pi$`, R`$40\pi$`, R`$4\pi$`], 0),
  num("easy", R`Volume of a $2\times3\times4$ box?`, 24, 0),
  num("easy", R`Volume of a $3\times4\times5$ box?`, 60, 0),
  mc("medium", R`Volume of a cone with $r=3$, $h=4$?`, [R`$12\pi$`, R`$36\pi$`, R`$4\pi$`, R`$48\pi$`], 0),
  mc("medium", R`Volume of a cone with $r=6$, $h=10$?`, [R`$120\pi$`, R`$360\pi$`, R`$60\pi$`, R`$40\pi$`], 0),
  mc("medium", R`Volume of a sphere with $r=3$?`, [R`$36\pi$`, R`$27\pi$`, R`$12\pi$`, R`$9\pi$`], 0),
  mc("hard", R`Volume of a sphere with $r=6$?`, [R`$288\pi$`, R`$144\pi$`, R`$216\pi$`, R`$48\pi$`], 0),
  num("easy", R`Surface area of a cube with edge $4$?`, 96, 0),
  num("easy", R`Surface area of a cube with edge $5$?`, 150, 0),
  num("easy", R`Volume of a cube with edge $3$?`, 27, 0),
  num("medium", R`Slant height of a cone with $r=6$, $h=8$?`, 10, 0),
  num("medium", R`Slant height of a cone with $r=3$, $h=4$?`, 5, 0),
  mc("medium", R`Surface area of a sphere with $r=5$?`, [R`$100\pi$`, R`$25\pi$`, R`$500\pi$`, R`$20\pi$`], 0),
  mc("hard", R`Total surface area of a cone with $r=3$, $\ell=5$?`, [R`$24\pi$`, R`$15\pi$`, R`$9\pi$`, R`$30\pi$`], 0),
  num("easy", R`Volume of a cube with edge $2$?`, 8, 0),
  tf("medium", R`A cone's volume is one-third of a cylinder with the same base and height.`, true),
  num("hard", R`A sphere has surface area $144\pi$; its radius is ___.`, 6, 0),
  mc("medium", R`Lateral surface area of a cylinder with $r=2$, $h=5$?`, [R`$20\pi$`, R`$10\pi$`, R`$28\pi$`, R`$40\pi$`], 0),
  num("medium", R`Volume of a rectangular prism $6\times2\times3$?`, 36, 0),
  tf("easy", R`Surface area scales with the square of a length.`, true),
  tf("medium", R`Volume scales with the cube of a length.`, true),
  num("hard", R`Volume of a cylinder with $r=5$, $h=4$ (coefficient of $\pi$)?`, 100, 0),
  num("medium", R`Surface area of a cube with edge $10$?`, 600, 0),
];

// ── 3.9 Coordinate Geometry ──────────────────────────────────
const g39 = () => [
  num("easy", R`Distance between $(0,0)$ and $(3,4)$?`, 5, 0),
  num("easy", R`Distance between $(0,0)$ and $(6,8)$?`, 10, 0),
  num("easy", R`Distance between $(0,0)$ and $(5,12)$?`, 13, 0),
  num("medium", R`Distance between $(1,2)$ and $(4,6)$?`, 5, 0),
  num("easy", R`Distance between $(2,3)$ and $(2,8)$?`, 5, 0),
  mc("easy", R`Midpoint of $(1,1)$ and $(5,7)$?`, [R`$(3,4)$`, R`$(2,3)$`, R`$(6,8)$`, R`$(4,6)$`], 0),
  mc("easy", R`Midpoint of $(2,4)$ and $(6,10)$?`, [R`$(4,7)$`, R`$(8,14)$`, R`$(4,6)$`, R`$(3,5)$`], 0),
  mc("medium", R`Midpoint of $(-2,4)$ and $(6,-2)$?`, [R`$(2,1)$`, R`$(4,2)$`, R`$(2,2)$`, R`$(-4,6)$`], 0),
  mc("easy", R`Midpoint of $(0,0)$ and $(10,0)$?`, [R`$(5,0)$`, R`$(10,0)$`, R`$(0,5)$`, R`$(5,5)$`], 0),
  num("medium", R`Slope through $(0,0)$ and $(2,6)$?`, 3, 0),
  num("medium", R`Slope through $(1,1)$ and $(4,7)$?`, 2, 0),
  num("medium", R`Distance from $(0,0)$ to $3x+4y-10=0$?`, 2, 0),
  mc("hard", R`Distance from $(2,4)$ to $2x+y-3=0$?`, [R`$\sqrt5$`, R`$5$`, R`$\tfrac{5}{2}$`, R`$1$`], 0),
  tf("medium", R`$(0,0),(4,0),(0,3)$ form a right triangle.`, true),
  num("hard", R`Perimeter of the triangle $(0,0),(6,0),(0,8)$?`, 24, 0),
  num("medium", R`Distance between $(-3,0)$ and $(0,4)$?`, 5, 0),
  mc("medium", R`Midpoint of $(3,-1)$ and $(7,5)$?`, [R`$(5,2)$`, R`$(10,4)$`, R`$(4,3)$`, R`$(5,3)$`], 0),
  num("hard", R`Midpoint of $\overline{AB}$ is $(4,3)$ and $A=(1,1)$; the $x$-coordinate of $B$ is ___.`, 7, 0),
  num("medium", R`Distance between $(1,1)$ and $(1,10)$?`, 9, 0),
  tf("easy", R`The distance formula comes from the Pythagorean theorem.`, true),
  mc("medium", R`Slope of the line through $(2,5)$ and $(2,-3)$ is`, [R`undefined`, R`$0$`, R`$1$`, R`$8$`], 0),
  num("hard", R`Distance from $(1,2)$ to $3x-4y+2=0$?`, 0.6, 0.01),
  num("easy", R`Distance between $(0,0)$ and $(8,6)$?`, 10, 0),
  mc("medium", R`The midpoint formula averages the`, [R`coordinates`, R`slopes`, R`distances`, R`intercepts`], 0),
];

// ── 3.10 Conic Sections ──────────────────────────────────────
const g310 = () => [
  mc("easy", R`Vertex of $y=x^2-4x+3$?`, [R`$(2,-1)$`, R`$(-2,-1)$`, R`$(2,3)$`, R`$(4,3)$`], 0),
  mc("medium", R`Vertex of $y=x^2-6x+5$? (axis $x=3$)`, [R`$(3,-4)$`, R`$(3,5)$`, R`$(-3,-4)$`, R`$(6,5)$`], 0),
  mc("medium", R`Vertex of $y=x^2+2x$?`, [R`$(-1,-1)$`, R`$(1,-1)$`, R`$(-1,0)$`, R`$(0,0)$`], 0),
  num("easy", R`Axis of symmetry of $y=x^2-6x+5$? ($x=$ ___)`, 3, 0),
  num("medium", R`Axis of symmetry of $y=x^2-8x+12$?`, 4, 0),
  mc("easy", R`Center of $(x-2)^2+(y+3)^2=25$?`, [R`$(2,-3)$`, R`$(-2,3)$`, R`$(2,3)$`, R`$(-2,-3)$`], 0),
  mc("easy", R`Center of $(x+1)^2+(y-2)^2=9$?`, [R`$(-1,2)$`, R`$(1,-2)$`, R`$(1,2)$`, R`$(-1,-2)$`], 0),
  num("easy", R`Radius of $x^2+y^2=49$?`, 7, 0),
  num("medium", R`Radius of $(x-2)^2+(y+3)^2=25$?`, 5, 0),
  mc("easy", R`Radius of $x^2+y^2=16$?`, [R`$4$`, R`$16$`, R`$8$`, R`$2$`], 0),
  mc("medium", R`$x$-intercepts of $\dfrac{x^2}{9}+\dfrac{y^2}{4}=1$?`, [R`$(\pm3,0)$`, R`$(\pm9,0)$`, R`$(\pm2,0)$`, R`$(0,\pm3)$`], 0),
  mc("medium", R`$x$-intercepts of $\dfrac{x^2}{25}+\dfrac{y^2}{16}=1$?`, [R`$(\pm5,0)$`, R`$(\pm4,0)$`, R`$(\pm25,0)$`, R`$(0,\pm5)$`], 0),
  mc("hard", R`Asymptotes of $\dfrac{x^2}{4}-\dfrac{y^2}{9}=1$?`, [R`$y=\pm\tfrac32 x$`, R`$y=\pm\tfrac23 x$`, R`$y=\pm\tfrac94 x$`, R`$y=\pm x$`], 0),
  mc("hard", R`Asymptotes of $\dfrac{x^2}{9}-\dfrac{y^2}{16}=1$?`, [R`$y=\pm\tfrac43 x$`, R`$y=\pm\tfrac34 x$`, R`$y=\pm\tfrac{16}{9}x$`, R`$y=\pm x$`], 0),
  mc("easy", R`$y=-2x^2+1$ opens`, [R`down`, R`up`, R`left`, R`right`], 0),
  tf("medium", R`$\dfrac{x^2}{4}+\dfrac{y^2}{4}=1$ is a circle of radius $2$.`, true),
  mc("medium", R`The equation of a circle centered at $(0,0)$ with radius $3$ is`, [R`$x^2+y^2=9$`, R`$x^2+y^2=3$`, R`$x^2+y^2=6$`, R`$\tfrac{x^2}{9}+\tfrac{y^2}{9}=3$`], 0),
  mc("medium", R`A minus sign between the squared terms indicates a(n)`, [R`hyperbola`, R`ellipse`, R`circle`, R`parabola`], 0),
  mc("easy", R`$y=x^2$ is a`, [R`parabola`, R`circle`, R`ellipse`, R`hyperbola`], 0),
  num("hard", R`Vertex $y$-value of $y=2x^2-8x+5$? (at $x=2$)`, -3, 0),
  mc("hard", R`Equation of the circle with center $(2,-3)$, radius $5$?`, [R`$(x-2)^2+(y+3)^2=25$`, R`$(x+2)^2+(y-3)^2=25$`, R`$(x-2)^2+(y+3)^2=5$`, R`$(x-2)^2+(y-3)^2=25$`], 0),
  mc("medium", R`$y$-intercepts of $\dfrac{x^2}{16}+\dfrac{y^2}{9}=1$?`, [R`$(0,\pm3)$`, R`$(0,\pm4)$`, R`$(\pm3,0)$`, R`$(0,\pm9)$`], 0),
  tf("easy", R`An ellipse with $a=b$ is a circle.`, true),
  mc("medium", R`The graph of $x=y^2$ is a parabola opening`, [R`right`, R`up`, R`down`, R`left`], 0),
];

export default [
  { code: "3.1", gen: g31 }, { code: "3.2", gen: g32 }, { code: "3.3", gen: g33 },
  { code: "3.4", gen: g34 }, { code: "3.5", gen: g35 }, { code: "3.6", gen: g36 },
  { code: "3.7", gen: g37 }, { code: "3.8", gen: g38 }, { code: "3.9", gen: g39 },
  { code: "3.10", gen: g310 },
];
