// FTCE Unit 4 — Trigonometry. ~24 curated questions per topic. Answers verified.
import { mc, tf, num, fill } from "./helpers.mjs";
const R = String.raw;

// ── 4.1 Six Trig Functions & Right Triangles ─────────────────
const g41 = () => [
  mc("easy", R`Evaluate $\sin 30^\circ$.`, [R`$\tfrac12$`, R`$\tfrac{\sqrt3}{2}$`, R`$\tfrac{\sqrt2}{2}$`, R`$1$`], 0),
  mc("easy", R`Evaluate $\cos 60^\circ$.`, [R`$\tfrac12$`, R`$\tfrac{\sqrt3}{2}$`, R`$1$`, R`$0$`], 0),
  mc("easy", R`Evaluate $\cos 30^\circ$.`, [R`$\tfrac{\sqrt3}{2}$`, R`$\tfrac12$`, R`$\tfrac{\sqrt2}{2}$`, R`$1$`], 0),
  mc("easy", R`Evaluate $\sin 60^\circ$.`, [R`$\tfrac{\sqrt3}{2}$`, R`$\tfrac12$`, R`$\tfrac{\sqrt2}{2}$`, R`$\sqrt3$`], 0),
  mc("easy", R`Evaluate $\tan 45^\circ$.`, [R`$1$`, R`$0$`, R`$\sqrt3$`, R`$\tfrac{\sqrt3}{3}$`], 0),
  mc("easy", R`Evaluate $\sin 45^\circ$.`, [R`$\tfrac{\sqrt2}{2}$`, R`$\tfrac12$`, R`$\tfrac{\sqrt3}{2}$`, R`$1$`], 0),
  mc("medium", R`Evaluate $\tan 60^\circ$.`, [R`$\sqrt3$`, R`$\tfrac{\sqrt3}{3}$`, R`$1$`, R`$\tfrac12$`], 0),
  mc("medium", R`Evaluate $\tan 30^\circ$.`, [R`$\tfrac{\sqrt3}{3}$`, R`$\sqrt3$`, R`$1$`, R`$\tfrac12$`], 0),
  fill("easy", R`$\sin=\dfrac{\text{opp}}{\_\_}$`, ["hyp", "hypotenuse"]),
  fill("easy", R`$\cos=\dfrac{\text{adj}}{\_\_}$`, ["hyp", "hypotenuse"]),
  fill("easy", R`$\tan=\dfrac{\text{opp}}{\_\_}$`, ["adj", "adjacent"]),
  mc("easy", R`$\csc=\dfrac1{?}$`, [R`$\sin$`, R`$\cos$`, R`$\tan$`, R`$\cot$`], 0),
  mc("easy", R`$\sec=\dfrac1{?}$`, [R`$\cos$`, R`$\sin$`, R`$\tan$`, R`$\csc$`], 0),
  mc("medium", R`In a $3$-$4$-$5$ triangle, $\sin$ of the angle opposite $3$?`, [R`$\tfrac35$`, R`$\tfrac45$`, R`$\tfrac34$`, R`$\tfrac53$`], 0),
  mc("medium", R`In a $3$-$4$-$5$ triangle, $\cos$ of the angle adjacent to $4$?`, [R`$\tfrac45$`, R`$\tfrac35$`, R`$\tfrac34$`, R`$\tfrac54$`], 0),
  mc("medium", R`In a $3$-$4$-$5$ triangle, $\tan$ of the angle opposite $3$?`, [R`$\tfrac34$`, R`$\tfrac43$`, R`$\tfrac35$`, R`$\tfrac45$`], 0),
  mc("medium", R`Evaluate $\sec 60^\circ$.`, [R`$2$`, R`$\tfrac12$`, R`$\tfrac{2\sqrt3}{3}$`, R`$1$`], 0),
  mc("medium", R`Evaluate $\csc 30^\circ$.`, [R`$2$`, R`$\tfrac12$`, R`$\sqrt3$`, R`$1$`], 0),
  mc("easy", R`Evaluate $\cot 45^\circ$.`, [R`$1$`, R`$0$`, R`$\sqrt3$`, R`undefined`], 0),
  num("medium", R`If $\sin\theta=\tfrac35$ ($\theta$ acute), $\cos\theta$ as a decimal is ___.`, 0.8, 0.01),
  mc("hard", R`The side ratios of a $30$-$60$-$90$ triangle are`, [R`$1:\sqrt3:2$`, R`$1:1:\sqrt2$`, R`$3:4:5$`, R`$1:2:3$`], 0),
  mc("hard", R`The side ratios of a $45$-$45$-$90$ triangle are`, [R`$1:1:\sqrt2$`, R`$1:\sqrt3:2$`, R`$1:2:\sqrt5$`, R`$1:1:2$`], 0),
  num("medium", R`Hypotenuse of a right triangle with legs $6$ and $8$?`, 10, 0),
  num("hard", R`If $\cos\theta=\tfrac{7}{25}$ ($\theta$ acute), $\sin\theta=\tfrac{?}{25}$. Enter the numerator.`, 24, 0),
];

// ── 4.2 Unit Circle, Radians & Quadrant Signs ────────────────
const g42 = () => [
  mc("easy", R`Convert $60^\circ$ to radians.`, [R`$\tfrac{\pi}{3}$`, R`$\tfrac{\pi}{6}$`, R`$\tfrac{\pi}{2}$`, R`$\tfrac{\pi}{4}$`], 0),
  mc("easy", R`Convert $45^\circ$ to radians.`, [R`$\tfrac{\pi}{4}$`, R`$\tfrac{\pi}{3}$`, R`$\tfrac{\pi}{6}$`, R`$\tfrac{\pi}{2}$`], 0),
  mc("easy", R`Convert $30^\circ$ to radians.`, [R`$\tfrac{\pi}{6}$`, R`$\tfrac{\pi}{3}$`, R`$\tfrac{\pi}{4}$`, R`$\tfrac{\pi}{2}$`], 0),
  mc("easy", R`Convert $90^\circ$ to radians.`, [R`$\tfrac{\pi}{2}$`, R`$\pi$`, R`$\tfrac{\pi}{4}$`, R`$2\pi$`], 0),
  mc("medium", R`Convert $\tfrac{3\pi}{4}$ to degrees.`, [R`$135^\circ$`, R`$45^\circ$`, R`$120^\circ$`, R`$150^\circ$`], 0),
  mc("easy", R`Convert $\tfrac{\pi}{6}$ to degrees.`, [R`$30^\circ$`, R`$60^\circ$`, R`$45^\circ$`, R`$15^\circ$`], 0),
  mc("medium", R`Convert $\tfrac{5\pi}{6}$ to degrees.`, [R`$150^\circ$`, R`$120^\circ$`, R`$135^\circ$`, R`$100^\circ$`], 0),
  num("easy", R`Evaluate $\cos 0$.`, 1, 0),
  num("easy", R`Evaluate $\sin 0$.`, 0, 0),
  num("easy", R`Evaluate $\sin\tfrac{\pi}{2}$.`, 1, 0),
  num("medium", R`Evaluate $\cos\tfrac{\pi}{2}$.`, 0, 0),
  mc("medium", R`Evaluate $\cos\pi$.`, [R`$-1$`, R`$1$`, R`$0$`, R`$\tfrac12$`], 0),
  mc("medium", R`Reference angle of $210^\circ$?`, [R`$30^\circ$`, R`$60^\circ$`, R`$45^\circ$`, R`$210^\circ$`], 0),
  mc("medium", R`Reference angle of $150^\circ$?`, [R`$30^\circ$`, R`$60^\circ$`, R`$45^\circ$`, R`$15^\circ$`], 0),
  mc("hard", R`Reference angle of $225^\circ$?`, [R`$45^\circ$`, R`$30^\circ$`, R`$60^\circ$`, R`$135^\circ$`], 0),
  mc("medium", R`Sign of $\cos\theta$ in Quadrant II?`, [R`negative`, R`positive`, R`zero`, R`undefined`], 0),
  mc("medium", R`Sign of $\tan\theta$ in Quadrant III?`, [R`positive`, R`negative`, R`zero`, R`undefined`], 0),
  mc("medium", R`In which quadrant is $\sin<0$ and $\cos>0$?`, [R`IV`, R`II`, R`III`, R`I`], 0),
  mc("easy", R`In which quadrant are all six functions positive?`, [R`I`, R`II`, R`III`, R`IV`], 0),
  num("easy", R`$2\pi$ radians equals how many degrees?`, 360, 0),
  mc("medium", R`Unit-circle coordinates at $0^\circ$?`, [R`$(1,0)$`, R`$(0,1)$`, R`$(-1,0)$`, R`$(0,-1)$`], 0),
  mc("medium", R`Unit-circle coordinates at $90^\circ$?`, [R`$(0,1)$`, R`$(1,0)$`, R`$(0,-1)$`, R`$(-1,0)$`], 0),
  tf("easy", R`A full circle measures $2\pi$ radians.`, true),
  mc("hard", R`Which function is positive in Quadrant II (besides its reciprocal)?`, [R`$\sin$`, R`$\cos$`, R`$\tan$`, R`$\cot$`], 0),
];

// ── 4.3 Trigonometric Identities ─────────────────────────────
const g43 = () => [
  mc("easy", R`Simplify $\sin^2\theta+\cos^2\theta$.`, [R`$1$`, R`$0$`, R`$2$`, R`$\tan^2\theta$`], 0),
  mc("easy", R`Simplify $1+\tan^2\theta$.`, [R`$\sec^2\theta$`, R`$\csc^2\theta$`, R`$1$`, R`$\cot^2\theta$`], 0),
  mc("medium", R`Simplify $1+\cot^2\theta$.`, [R`$\csc^2\theta$`, R`$\sec^2\theta$`, R`$\tan^2\theta$`, R`$1$`], 0),
  mc("medium", R`Simplify $\sec^2\theta-\tan^2\theta$.`, [R`$1$`, R`$0$`, R`$\sec^2\theta$`, R`$\tan^2\theta$`], 0),
  mc("medium", R`Simplify $\csc^2\theta-\cot^2\theta$.`, [R`$1$`, R`$0$`, R`$\csc^2\theta$`, R`$-1$`], 0),
  mc("easy", R`$\tan\theta$ equals`, [R`$\tfrac{\sin\theta}{\cos\theta}$`, R`$\tfrac{\cos\theta}{\sin\theta}$`, R`$\sin\theta\cos\theta$`, R`$\tfrac1{\sin\theta}$`], 0),
  mc("medium", R`$\cot\theta$ equals`, [R`$\tfrac{\cos\theta}{\sin\theta}$`, R`$\tfrac{\sin\theta}{\cos\theta}$`, R`$\tfrac1{\cos\theta}$`, R`$\sin\theta\cos\theta$`], 0),
  mc("easy", R`The reciprocal of $\cos\theta$ is`, [R`$\sec\theta$`, R`$\csc\theta$`, R`$\cot\theta$`, R`$\sin\theta$`], 0),
  mc("easy", R`The reciprocal of $\sin\theta$ is`, [R`$\csc\theta$`, R`$\sec\theta$`, R`$\cot\theta$`, R`$\cos\theta$`], 0),
  mc("medium", R`Simplify $\sin\theta\cot\theta$.`, [R`$\cos\theta$`, R`$\sin\theta$`, R`$1$`, R`$\tan\theta$`], 0),
  mc("medium", R`Simplify $\cos\theta\tan\theta$.`, [R`$\sin\theta$`, R`$\cos\theta$`, R`$1$`, R`$\cot\theta$`], 0),
  mc("easy", R`Simplify $\cos\theta\sec\theta$.`, [R`$1$`, R`$\cos^2\theta$`, R`$\sec^2\theta$`, R`$0$`], 0),
  mc("easy", R`Simplify $\sin\theta\csc\theta$.`, [R`$1$`, R`$0$`, R`$\sin^2\theta$`, R`$\csc^2\theta$`], 0),
  num("medium", R`If $\cos\theta=0.6$, find $\sin^2\theta$.`, 0.64, 0.01),
  mc("medium", R`If $\sin\theta=\tfrac35$ ($\theta$ in QI), $\cos\theta=$`, [R`$\tfrac45$`, R`$-\tfrac45$`, R`$\tfrac34$`, R`$\tfrac53$`], 0),
  num("medium", R`If $\sin\theta=0.8$, find $\cos^2\theta$.`, 0.36, 0.01),
  mc("medium", R`Simplify $\tan\theta\cos\theta$.`, [R`$\sin\theta$`, R`$\cos\theta$`, R`$1$`, R`$\tan\theta$`], 0),
  tf("easy", R`$\sin^2\theta=1-\cos^2\theta$.`, true),
  mc("medium", R`Simplify $1-\cos^2\theta$.`, [R`$\sin^2\theta$`, R`$\cos^2\theta$`, R`$1$`, R`$\tan^2\theta$`], 0),
  mc("hard", R`Simplify $\dfrac{\sec\theta}{\csc\theta}$.`, [R`$\tan\theta$`, R`$\cot\theta$`, R`$1$`, R`$\sin\theta$`], 0),
  mc("hard", R`If $\cos\theta=\tfrac{5}{13}$ ($\theta$ in QI), $\sin\theta=$`, [R`$\tfrac{12}{13}$`, R`$\tfrac{5}{12}$`, R`$\tfrac{13}{12}$`, R`$-\tfrac{12}{13}$`], 0),
  mc("medium", R`Simplify $\cot\theta\tan\theta$.`, [R`$1$`, R`$0$`, R`$\cot^2\theta$`, R`$\tan^2\theta$`], 0),
  num("medium", R`If $\sin\theta=0.6$ ($\theta$ acute), $\cos\theta=$ ___.`, 0.8, 0.01),
  tf("medium", R`$\sec^2\theta=1+\tan^2\theta$.`, true),
];

// ── 4.4 Sum, Difference & Multiple-Angle Formulas ────────────
const g44 = () => [
  mc("easy", R`Formula for $\sin 2A$.`, [R`$2\sin A\cos A$`, R`$\sin^2 A-\cos^2 A$`, R`$2\cos^2 A-1$`, R`$\sin A\cos A$`], 0),
  mc("medium", R`Formula for $\cos(A+B)$.`, [R`$\cos A\cos B-\sin A\sin B$`, R`$\cos A\cos B+\sin A\sin B$`, R`$\sin A\cos B+\cos A\sin B$`, R`$\cos A\sin B-\sin A\cos B$`], 0),
  mc("medium", R`Formula for $\sin(A+B)$.`, [R`$\sin A\cos B+\cos A\sin B$`, R`$\sin A\cos B-\cos A\sin B$`, R`$\cos A\cos B-\sin A\sin B$`, R`$2\sin A\cos B$`], 0),
  mc("medium", R`Formula for $\cos(A-B)$.`, [R`$\cos A\cos B+\sin A\sin B$`, R`$\cos A\cos B-\sin A\sin B$`, R`$\sin A\cos B-\cos A\sin B$`, R`$\sin A\sin B-\cos A\cos B$`], 0),
  mc("medium", R`Formula for $\sin(A-B)$.`, [R`$\sin A\cos B-\cos A\sin B$`, R`$\sin A\cos B+\cos A\sin B$`, R`$\cos A\cos B+\sin A\sin B$`, R`$\cos A\sin B-\sin A\cos B$`], 0),
  mc("medium", R`If $\sin A=\tfrac35$, $\cos A=\tfrac45$, then $\sin 2A=$`, [R`$\tfrac{24}{25}$`, R`$\tfrac{7}{25}$`, R`$\tfrac{12}{25}$`, R`$\tfrac{6}{5}$`], 0),
  mc("medium", R`If $\sin A=\tfrac35$, then $\cos 2A=$`, [R`$\tfrac{7}{25}$`, R`$\tfrac{24}{25}$`, R`$-\tfrac{7}{25}$`, R`$\tfrac{16}{25}$`], 0),
  mc("medium", R`$\cos 2A$ equals`, [R`$2\cos^2 A-1$`, R`$2\sin^2 A-1$`, R`$2\sin A\cos A$`, R`$1+2\cos^2 A$`], 0),
  mc("hard", R`Formula for $\tan 2A$.`, [R`$\dfrac{2\tan A}{1-\tan^2 A}$`, R`$\dfrac{2\tan A}{1+\tan^2 A}$`, R`$\dfrac{\tan A}{1-\tan^2 A}$`, R`$2\tan A$`], 0),
  mc("hard", R`Exact value of $\cos 75^\circ$.`, [R`$\dfrac{\sqrt6-\sqrt2}{4}$`, R`$\dfrac{\sqrt6+\sqrt2}{4}$`, R`$\dfrac{\sqrt2-\sqrt6}{4}$`, R`$\dfrac{\sqrt3-1}{2}$`], 0),
  mc("hard", R`Exact value of $\sin 75^\circ$.`, [R`$\dfrac{\sqrt6+\sqrt2}{4}$`, R`$\dfrac{\sqrt6-\sqrt2}{4}$`, R`$\dfrac{\sqrt2-\sqrt6}{4}$`, R`$\dfrac{\sqrt3+1}{2}$`], 0),
  num("medium", R`If $\sin A=0.6$, $\cos A=0.8$, then $\sin 2A=$ ___ (decimal).`, 0.96, 0.01),
  num("medium", R`If $\sin A=\tfrac35$, then $\cos 2A=$ ___ (decimal).`, 0.28, 0.01),
  mc("medium", R`Using $\cos 2A=\cos^2A-\sin^2A$ with $A=30^\circ$, $\cos 60^\circ=$`, [R`$\tfrac12$`, R`$\tfrac{\sqrt3}{2}$`, R`$0$`, R`$1$`], 0),
  mc("hard", R`Half-angle: $\sin\tfrac{A}{2}=$`, [R`$\pm\sqrt{\tfrac{1-\cos A}{2}}$`, R`$\pm\sqrt{\tfrac{1+\cos A}{2}}$`, R`$2\sin A\cos A$`, R`$\tfrac{1-\cos A}{2}$`], 0),
  mc("medium", R`$2\sin 30^\circ\cos 30^\circ$ equals`, [R`$\tfrac{\sqrt3}{2}$`, R`$\tfrac12$`, R`$1$`, R`$\tfrac{\sqrt2}{2}$`], 0),
  tf("medium", R`$\cos 2A=1-2\sin^2 A$.`, true),
  mc("hard", R`If $\tan A=1$, then $\tan 2A$ is`, [R`undefined`, R`$1$`, R`$2$`, R`$0$`], 0),
  mc("medium", R`$2\sin A\cos A$ equals`, [R`$\sin 2A$`, R`$\cos 2A$`, R`$\tan 2A$`, R`$\sin^2 A$`], 0),
  mc("easy", R`In $\cos(A+B)$, the middle sign is`, [R`minus`, R`plus`, R`times`, R`divide`], 0),
  mc("easy", R`In $\cos(A-B)$, the middle sign is`, [R`plus`, R`minus`, R`times`, R`divide`], 0),
  mc("hard", R`If $\cos A=\tfrac45$, $\sin A=\tfrac35$, then $\cos 2A=2\cos^2A-1=$`, [R`$\tfrac{7}{25}$`, R`$\tfrac{24}{25}$`, R`$-\tfrac{7}{25}$`, R`$\tfrac{16}{25}$`], 0),
  mc("medium", R`$\sin(A-B)=\sin A\cos B\ \_\ \cos A\sin B$; the sign is`, [R`minus`, R`plus`, R`times`, R`divide`], 0),
  tf("easy", R`$\sin 2A=2\sin A\cos A$.`, true),
];

// ── 4.5 Graphs of Sine & Cosine ──────────────────────────────
const g45 = () => [
  num("easy", R`Amplitude of $y=5\sin x$?`, 5, 0),
  num("easy", R`Amplitude of $y=-2\sin x$?`, 2, 0),
  num("easy", R`Amplitude of $y=3\sin(2x)$?`, 3, 0),
  num("easy", R`Amplitude of $y=-4\cos x$?`, 4, 0),
  num("easy", R`Amplitude of $y=\sin x$?`, 1, 0),
  mc("easy", R`Period of $y=\sin(3x)$?`, [R`$\tfrac{2\pi}{3}$`, R`$3\pi$`, R`$2\pi$`, R`$\tfrac{\pi}{3}$`], 0),
  mc("medium", R`Period of $y=\sin(2x)$?`, [R`$\pi$`, R`$2\pi$`, R`$\tfrac{\pi}{2}$`, R`$4\pi$`], 0),
  mc("medium", R`Period of $y=\cos\tfrac{x}{2}$?`, [R`$4\pi$`, R`$2\pi$`, R`$\pi$`, R`$\tfrac{\pi}{2}$`], 0),
  mc("medium", R`Period of $y=\sin(4x)$?`, [R`$\tfrac{\pi}{2}$`, R`$4\pi$`, R`$2\pi$`, R`$\pi$`], 0),
  mc("easy", R`Period of $y=\cos x$?`, [R`$2\pi$`, R`$\pi$`, R`$\tfrac{\pi}{2}$`, R`$4\pi$`], 0),
  num("easy", R`Maximum of $y=2\cos x$?`, 2, 0),
  num("easy", R`Maximum of $y=3\sin x+1$?`, 4, 0),
  num("medium", R`Maximum of $y=2\sin x+3$?`, 5, 0),
  num("medium", R`Minimum of $y=2\sin x+3$?`, 1, 0),
  num("medium", R`Minimum of $y=4\sin x-2$?`, -6, 0),
  mc("easy", R`Midline of $y=\cos x-1$?`, [R`$y=-1$`, R`$y=1$`, R`$y=0$`, R`$y=-2$`], 0),
  mc("easy", R`Midline of $y=\sin x+2$?`, [R`$y=2$`, R`$y=0$`, R`$y=-2$`, R`$y=1$`], 0),
  num("hard", R`For $y=3\cos(2x)-1$, the maximum is ___.`, 2, 0),
  num("hard", R`For $y=3\cos(2x)-1$, the minimum is ___.`, -4, 0),
  mc("hard", R`For $y=3\cos(2x)-1$, the period is`, [R`$\pi$`, R`$2\pi$`, R`$\tfrac{\pi}{2}$`, R`$6\pi$`], 0),
  num("medium", R`A sinusoid has max $8$ and min $2$; its amplitude is ___.`, 3, 0),
  num("medium", R`A sinusoid has max $8$ and min $2$; its midline is $y=$ ___.`, 5, 0),
  mc("easy", R`A cosine graph starts (at $x=0$) at its`, [R`maximum`, R`midline`, R`minimum`, R`$x$-intercept`], 0),
  mc("medium", R`A sine graph $y=\sin x$ starts (at $x=0$) at its`, [R`midline`, R`maximum`, R`minimum`, R`asymptote`], 0),
];

// ── 4.6 Inverse Trigonometric Functions ──────────────────────
const g46 = () => [
  mc("easy", R`Evaluate $\arcsin\tfrac12$.`, [R`$\tfrac{\pi}{6}$`, R`$\tfrac{\pi}{3}$`, R`$\tfrac{\pi}{4}$`, R`$\tfrac{\pi}{2}$`], 0),
  mc("easy", R`Evaluate $\arccos 0$.`, [R`$\tfrac{\pi}{2}$`, R`$0$`, R`$\pi$`, R`$\tfrac{\pi}{4}$`], 0),
  mc("easy", R`Evaluate $\arctan 1$.`, [R`$\tfrac{\pi}{4}$`, R`$\tfrac{\pi}{3}$`, R`$\tfrac{\pi}{6}$`, R`$\tfrac{\pi}{2}$`], 0),
  mc("easy", R`Evaluate $\arcsin 1$.`, [R`$\tfrac{\pi}{2}$`, R`$0$`, R`$\pi$`, R`$1$`], 0),
  mc("medium", R`Evaluate $\arccos(-1)$.`, [R`$\pi$`, R`$0$`, R`$\tfrac{\pi}{2}$`, R`$-\pi$`], 0),
  mc("easy", R`Evaluate $\arcsin 0$.`, [R`$0$`, R`$\tfrac{\pi}{2}$`, R`$\pi$`, R`$1$`], 0),
  mc("easy", R`Evaluate $\arctan 0$.`, [R`$0$`, R`$\tfrac{\pi}{4}$`, R`$\tfrac{\pi}{2}$`, R`$1$`], 0),
  mc("easy", R`Evaluate $\arccos 1$.`, [R`$0$`, R`$\tfrac{\pi}{2}$`, R`$\pi$`, R`$1$`], 0),
  mc("medium", R`Evaluate $\arcsin\left(-\tfrac12\right)$.`, [R`$-\tfrac{\pi}{6}$`, R`$\tfrac{\pi}{6}$`, R`$-\tfrac{\pi}{3}$`, R`$\tfrac{5\pi}{6}$`], 0),
  mc("medium", R`Evaluate $\arctan\sqrt3$.`, [R`$\tfrac{\pi}{3}$`, R`$\tfrac{\pi}{6}$`, R`$\tfrac{\pi}{4}$`, R`$\tfrac{\pi}{2}$`], 0),
  mc("medium", R`Range of $\arcsin$.`, [R`$[-\tfrac{\pi}{2},\tfrac{\pi}{2}]$`, R`$[0,\pi]$`, R`$(-\tfrac{\pi}{2},\tfrac{\pi}{2})$`, R`$[0,2\pi]$`], 0),
  mc("medium", R`Range of $\arccos$.`, [R`$[0,\pi]$`, R`$[-\tfrac{\pi}{2},\tfrac{\pi}{2}]$`, R`$(-\tfrac{\pi}{2},\tfrac{\pi}{2})$`, R`$[0,2\pi]$`], 0),
  num("easy", R`Evaluate $\sin(\arcsin 0.7)$.`, 0.7, 0.01),
  num("easy", R`Evaluate $\cos(\arccos 0.4)$.`, 0.4, 0.01),
  mc("medium", R`Evaluate $\arcsin\tfrac{\sqrt2}{2}$.`, [R`$\tfrac{\pi}{4}$`, R`$\tfrac{\pi}{3}$`, R`$\tfrac{\pi}{6}$`, R`$\tfrac{\pi}{2}$`], 0),
  mc("medium", R`Evaluate $\arccos\tfrac12$.`, [R`$\tfrac{\pi}{3}$`, R`$\tfrac{\pi}{6}$`, R`$\tfrac{\pi}{4}$`, R`$\tfrac{2\pi}{3}$`], 0),
  mc("hard", R`Evaluate $\arctan(-1)$.`, [R`$-\tfrac{\pi}{4}$`, R`$\tfrac{\pi}{4}$`, R`$\tfrac{3\pi}{4}$`, R`$-\tfrac{\pi}{2}$`], 0),
  num("medium", R`Evaluate $\tan(\arctan 4)$.`, 4, 0),
  mc("hard", R`Evaluate $\cos\left(\arcsin\tfrac35\right)$.`, [R`$\tfrac45$`, R`$\tfrac35$`, R`$\tfrac34$`, R`$\tfrac53$`], 0),
  mc("medium", R`Evaluate $\arccos\tfrac{\sqrt3}{2}$.`, [R`$\tfrac{\pi}{6}$`, R`$\tfrac{\pi}{3}$`, R`$\tfrac{\pi}{4}$`, R`$\tfrac{5\pi}{6}$`], 0),
  tf("easy", R`$\arcsin$ and $\sin$ are inverses on the restricted domain.`, true),
  num("hard", R`Evaluate $\arcsin(\sin\pi)$.`, 0, 0),
  num("easy", R`Evaluate $\sin(\arcsin 0.9)$.`, 0.9, 0.01),
  mc("easy", R`$\arctan 1$ in radians is`, [R`$\tfrac{\pi}{4}$`, R`$45$`, R`$\tfrac{\pi}{2}$`, R`$1$`], 0),
];

export default [
  { code: "4.1", gen: g41 }, { code: "4.2", gen: g42 }, { code: "4.3", gen: g43 },
  { code: "4.4", gen: g44 }, { code: "4.5", gen: g45 }, { code: "4.6", gen: g46 },
];
