// FTCE Unit 5 — Statistics. ~24 curated questions per topic. Answers verified.
import { mc, tf, num, fill } from "./helpers.mjs";
const R = String.raw;

// ── 5.1 Displaying Data ──────────────────────────────────────
const g51 = () => [
  mc("easy", R`Which display shows a relationship between two variables?`, [R`scatterplot`, R`pie chart`, R`bar chart`, R`stem-and-leaf`], 0),
  mc("easy", R`Which plot shows the five-number summary?`, [R`box-and-whisker`, R`histogram`, R`pie chart`, R`line graph`], 0),
  mc("easy", R`A circle graph is also called a`, [R`pie chart`, R`histogram`, R`box plot`, R`scatterplot`], 0),
  mc("medium", R`Which display best shows the frequency of numeric classes?`, [R`histogram`, R`pie chart`, R`scatterplot`, R`stem-and-leaf`], 0),
  num("easy", R`Relative frequency of a class with $6$ out of $30$? (decimal)`, 0.2, 0.001),
  num("medium", R`Relative frequency of a class with $8$ out of $40$? (decimal)`, 0.2, 0.001),
  num("medium", R`Relative frequency of a class with $9$ out of $36$? (decimal)`, 0.25, 0.001),
  num("easy", R`In a stem-and-leaf plot, stem $4$ leaf $2$ represents?`, 42, 0),
  num("medium", R`In a stem-and-leaf plot, stem $7$ leaf $9$ represents?`, 79, 0),
  num("easy", R`Central angle for $50\%$ of a pie chart (degrees)?`, 180, 0),
  num("medium", R`Central angle for $25\%$ of a pie chart (degrees)?`, 90, 0),
  num("hard", R`Central angle for $10\%$ of a pie chart (degrees)?`, 36, 0),
  mc("easy", R`Points trending downward indicate ___ correlation.`, [R`negative`, R`positive`, R`no`, R`perfect`], 0),
  mc("easy", R`Points trending upward indicate ___ correlation.`, [R`positive`, R`negative`, R`no`, R`zero`], 0),
  mc("medium", R`A scatterplot with points scattered randomly shows`, [R`no correlation`, R`strong positive`, R`strong negative`, R`perfect`], 0),
  fill("medium", R`A frequency table groups data into ___.`, ["classes", "intervals", "bins"]),
  tf("easy", R`A stem-and-leaf plot preserves the individual data values.`, true),
  tf("medium", R`A histogram is used for categorical data.`, false),
  mc("medium", R`Which shows parts of a whole best?`, [R`pie chart`, R`scatterplot`, R`box plot`, R`stem-and-leaf`], 0),
  num("hard", R`A pie slice measures $72^\circ$; what percent of the data is it?`, 20, 0),
  num("medium", R`A class has count $12$ of total $48$; relative frequency (decimal)?`, 0.25, 0.001),
  mc("easy", R`Bar charts are best for ___ data.`, [R`categorical`, R`continuous`, R`paired`, R`time-series only`], 0),
  tf("easy", R`A scatterplot can reveal a positive, negative, or no correlation.`, true),
  num("hard", R`If $30\%$ of a pie chart is one category, its angle is ___ degrees.`, 108, 0),
];

// ── 5.2 Measures of Central Tendency ─────────────────────────
const g52 = () => [
  num("easy", R`Mean of $2,4,6$?`, 4, 0),
  num("easy", R`Mean of $10,20,30$?`, 20, 0),
  num("easy", R`Mean of $5,10,15$?`, 10, 0),
  num("medium", R`Mean of $4,8,6,10,12$?`, 8, 0),
  num("medium", R`Mean of $90,85,80$?`, 85, 0),
  num("easy", R`Mean of $7$ and $13$?`, 10, 0),
  num("easy", R`Median of $3,5,9$?`, 5, 0),
  num("easy", R`Median of $2,4,6,8$?`, 5, 0),
  num("medium", R`Median of $1,3,5,7,9$?`, 5, 0),
  num("medium", R`Median of $3,8,8,10,20$?`, 8, 0),
  num("hard", R`Median of $6,20,7,3,18,4,8,14$? (decimal)`, 7.5, 0.01),
  num("easy", R`Mode of $1,2,2,3,4$?`, 2, 0),
  num("medium", R`Mode of $4,4,7,9,9,9$?`, 9, 0),
  num("medium", R`Median of $5,5,5,5$?`, 5, 0),
  num("easy", R`Mean of $10,20,30,40$?`, 25, 0),
  tf("easy", R`The mean is affected by outliers.`, true),
  tf("medium", R`The median is resistant to outliers.`, true),
  mc("medium", R`In a right-skewed distribution,`, [R`mean $>$ median`, R`mean $<$ median`, R`mean $=$ median`, R`no mode exists`], 0),
  num("hard", R`Scores $82,90,78,x$ have mean $85$. Find $x$.`, 90, 0),
  num("hard", R`Grouped data: midpoints $15,25,35$, frequencies $4,10,6$. Estimated mean?`, 26, 0.1),
  fill("easy", R`The most frequent value is the ___.`, ["mode"]),
  num("medium", R`Mean of $3,3,3,3,12$?`, 4.8, 0.01),
  num("medium", R`Median of $12,4,8,20,16$?`, 12, 0),
  mc("easy", R`Which measure uses the sum of all values?`, [R`mean`, R`median`, R`mode`, R`range`], 0),
];

// ── 5.3 Measures of Variability ──────────────────────────────
const g53 = () => [
  num("easy", R`Range of $3,7,2,9,5$?`, 7, 0),
  num("easy", R`Range of $4,10,6,2$?`, 8, 0),
  num("easy", R`Range of $15,20,25$?`, 10, 0),
  num("medium", R`Range of $-3,4,10,1$?`, 13, 0),
  fill("easy", R`$\text{IQR}=Q_3-\ ?$`, ["Q1", "Q_1"]),
  num("medium", R`IQR of $1,2,3,4,5,6,7,8$?`, 4, 0),
  num("hard", R`IQR of $2,4,5,7,8,10,12,14$?`, 6, 0),
  num("easy", R`Standard deviation of $3,3,3$?`, 0, 0),
  num("easy", R`Standard deviation of $5,5,5,5$?`, 0, 0),
  num("medium", R`Population variance of $2,4,6,8$?`, 5, 0),
  num("hard", R`Population standard deviation of $2,4,6,8$? (decimal)`, 2.24, 0.02),
  num("medium", R`Population variance of $1,3,5$? (mean $3$)`, 2.667, 0.02),
  fill("easy", R`Standard deviation is the square root of the ___.`, ["variance"]),
  mc("medium", R`Which is resistant to outliers?`, [R`IQR`, R`range`, R`mean`, R`sum`], 0),
  mc("easy", R`A larger standard deviation means`, [R`more spread`, R`less spread`, R`no spread`, R`a larger mean`], 0),
  num("medium", R`In a normal distribution, about what percent is within $1$ SD of the mean?`, 68, 0),
  num("hard", R`In a normal distribution, about what percent is within $2$ SD of the mean?`, 95, 0),
  tf("easy", R`Range $=\max-\min$.`, true),
  tf("medium", R`A sample variance divides the sum of squared deviations by $n-1$.`, true),
  num("medium", R`Range of a data set with min $12$ and max $47$?`, 35, 0),
  num("hard", R`Data $10,10,10,10$ has standard deviation ___.`, 0, 0),
  mc("medium", R`The middle $50\%$ of the data is measured by the`, [R`IQR`, R`range`, R`mode`, R`mean`], 0),
  num("medium", R`$Q_1=20$, $Q_3=35$; the IQR is ___.`, 15, 0),
  tf("hard", R`If all data values are equal, both the range and the standard deviation are $0$.`, true),
];

// ── 5.4 Percentiles & Position ───────────────────────────────
const g54 = () => [
  mc("easy", R`The median is which percentile?`, [R`50th`, R`25th`, R`75th`, R`100th`], 0),
  mc("easy", R`$Q_1$ is which percentile?`, [R`25th`, R`50th`, R`75th`, R`10th`], 0),
  mc("easy", R`$Q_3$ is which percentile?`, [R`75th`, R`50th`, R`25th`, R`90th`], 0),
  num("easy", R`z-score of $80$ with mean $70$, SD $5$?`, 2, 0),
  num("easy", R`z-score of $90$ with mean $80$, SD $10$?`, 1, 0),
  num("medium", R`z-score of $60$ with mean $70$, SD $5$?`, -2, 0),
  num("medium", R`z-score of $85$ with mean $75$, SD $5$?`, 2, 0),
  num("medium", R`z-score of $54$ with mean $70$, SD $8$?`, -2, 0),
  num("easy", R`z-score of a value equal to the mean?`, 0, 0),
  num("easy", R`How many values are in a five-number summary?`, 5, 0),
  num("medium", R`In $2,4,6,8,10,12$, the median is ___.`, 7, 0),
  num("medium", R`In $2,4,6,8,10,12$, $Q_1$ is ___.`, 4, 0),
  num("medium", R`In $2,4,6,8,10,12$, $Q_3$ is ___.`, 10, 0),
  num("medium", R`The $90$th percentile means ___ percent scored below.`, 90, 0),
  fill("medium", R`A z-score gives position in units of ___.`, ["standard deviation", "standard deviations", "SD"]),
  tf("easy", R`A positive z-score means the value is above the mean.`, true),
  tf("medium", R`A z-score of $-1$ means the value is one SD below the mean.`, true),
  num("hard", R`If a value has z-score $1.5$ with mean $50$, SD $4$, the value is ___.`, 56, 0),
  num("hard", R`If a value has z-score $-2$ with mean $100$, SD $15$, the value is ___.`, 70, 0),
  mc("medium", R`Outliers are often flagged beyond`, [R`$Q_3+1.5\cdot\text{IQR}$`, R`$Q_3+\text{IQR}$`, R`the mean $+1$ SD`, R`the median`], 0),
  mc("easy", R`A score at the $50$th percentile equals the`, [R`median`, R`mean`, R`mode`, R`maximum`], 0),
  num("medium", R`In $3,5,7,9,11,13$, the median is ___.`, 8, 0),
  tf("medium", R`The five-number summary is the basis of a box plot.`, true),
  num("hard", R`A test score of $88$ has mean $76$ and SD $6$; its z-score is ___.`, 2, 0),
];

// ── 5.5 Regression, Sampling & Experimental Design ───────────
const g55 = () => [
  num("easy", R`Best-fit $y=2x+3$; predict $y$ at $x=5$.`, 13, 0),
  num("easy", R`Best-fit $y=3x-1$; predict $y$ at $x=4$.`, 11, 0),
  num("medium", R`Best-fit $y=4x-2$; predict $y$ at $x=3$.`, 10, 0),
  num("medium", R`Best-fit $y=1.2x+30$; predict $y$ at $x=10$.`, 42, 0.01),
  mc("easy", R`The correlation coefficient $r$ ranges from`, [R`$-1$ to $1$`, R`$0$ to $1$`, R`$0$ to $100$`, R`$-\infty$ to $\infty$`], 0),
  mc("easy", R`$r=0$ indicates`, [R`no linear correlation`, R`perfect positive`, R`perfect negative`, R`strong positive`], 0),
  mc("medium", R`$r=0.9$ indicates`, [R`strong positive`, R`weak positive`, R`strong negative`, R`no`], 0),
  mc("medium", R`$r=-1$ indicates`, [R`perfect negative`, R`perfect positive`, R`no correlation`, R`weak negative`], 0),
  mc("easy", R`The group receiving no treatment is the`, [R`control group`, R`treatment group`, R`sample`, R`population`], 0),
  tf("easy", R`Correlation implies causation.`, false),
  mc("easy", R`Random sampling reduces`, [R`bias`, R`the mean`, R`variance to zero`, R`the sample size`], 0),
  mc("medium", R`A variable that distorts the treatment–outcome relationship is a`, [R`confounding variable`, R`dependent variable`, R`control`, R`parameter`], 0),
  mc("medium", R`The slope of a regression line is the average change in $y$ per unit`, [R`$x$`, R`$y$`, R`$r$`, R`time`], 0),
  tf("medium", R`Randomization helps balance confounding variables across groups.`, true),
  mc("medium", R`$r$ near $+1$ means a`, [R`strong positive linear relationship`, R`weak relationship`, R`strong negative`, R`curved relationship`], 0),
  mc("hard", R`Which sampling method is most likely to be unbiased?`, [R`simple random sample`, R`convenience sample`, R`voluntary response`, R`sampling only volunteers`], 0),
  num("hard", R`Best-fit $y=-2x+20$; predict $y$ at $x=6$.`, 8, 0),
  tf("easy", R`A representative sample allows inference about the population.`, true),
  mc("medium", R`Ice-cream sales and drownings both rise in summer; their correlation is likely due to`, [R`a confounder (hot weather)`, R`causation`, R`a sampling error`, R`no relationship`], 0),
  mc("easy", R`In an experiment, the imposed condition is the`, [R`treatment`, R`control`, R`bias`, R`parameter`], 0),
  num("medium", R`Best-fit $y=0.5x+2$; predict $y$ at $x=8$.`, 6, 0),
  tf("medium", R`A larger, well-chosen sample generally gives more reliable estimates.`, true),
  mc("hard", R`$r=-0.85$ describes a relationship that is`, [R`strong and negative`, R`weak and negative`, R`strong and positive`, R`nonexistent`], 0),
  mc("easy", R`The variable predicted by a regression line is the`, [R`response ($y$)`, R`explanatory ($x$)`, R`slope`, R`intercept`], 0),
];

export default [
  { code: "5.1", gen: g51 }, { code: "5.2", gen: g52 }, { code: "5.3", gen: g53 },
  { code: "5.4", gen: g54 }, { code: "5.5", gen: g55 },
];
