// FTCE Unit 6 — Probability. ~24 curated questions per topic. Answers verified.
import { mc, tf, num, fill } from "./helpers.mjs";
const R = String.raw;

// ── 6.1 Probability Basics & Properties ──────────────────────
const g61 = () => [
  mc("easy", R`$P(\text{rolling a }4)$ on a fair die?`, [R`$\tfrac16$`, R`$\tfrac14$`, R`$\tfrac13$`, R`$\tfrac12$`], 0),
  mc("easy", R`$P(\text{even})$ on a die?`, [R`$\tfrac12$`, R`$\tfrac13$`, R`$\tfrac16$`, R`$\tfrac23$`], 0),
  mc("easy", R`$P(\text{not }6)$ on a die?`, [R`$\tfrac56$`, R`$\tfrac16$`, R`$\tfrac12$`, R`$\tfrac23$`], 0),
  mc("easy", R`$P(\text{heart})$ from a deck?`, [R`$\tfrac14$`, R`$\tfrac{1}{13}$`, R`$\tfrac12$`, R`$\tfrac{1}{52}$`], 0),
  mc("medium", R`$P(\text{ace})$ from a deck?`, [R`$\tfrac{1}{13}$`, R`$\tfrac14$`, R`$\tfrac{1}{52}$`, R`$\tfrac{4}{13}$`], 0),
  mc("medium", R`$P(\text{face card})$ from a deck?`, [R`$\tfrac{3}{13}$`, R`$\tfrac{1}{13}$`, R`$\tfrac14$`, R`$\tfrac{12}{13}$`], 0),
  mc("easy", R`$P(\text{heads})$ on a coin?`, [R`$\tfrac12$`, R`$\tfrac14$`, R`$1$`, R`$\tfrac13$`], 0),
  num("easy", R`$P(\text{a certain event})$?`, 1, 0),
  num("easy", R`$P(\text{an impossible event})$?`, 0, 0),
  mc("easy", R`The range of any probability is`, [R`$0$ to $1$`, R`$-1$ to $1$`, R`$0$ to $100$`, R`$1$ to $10$`], 0),
  mc("easy", R`Bag: $3$ red, $2$ blue. $P(\text{red})$?`, [R`$\tfrac35$`, R`$\tfrac25$`, R`$\tfrac13$`, R`$\tfrac32$`], 0),
  mc("medium", R`Bag: $4$ red, $6$ green. $P(\text{green})$?`, [R`$\tfrac35$`, R`$\tfrac25$`, R`$\tfrac23$`, R`$\tfrac46$`], 0),
  mc("medium", R`$P(\text{red card})$ from a deck?`, [R`$\tfrac12$`, R`$\tfrac14$`, R`$\tfrac{1}{13}$`, R`$\tfrac{13}{52}$`], 0),
  num("medium", R`If $P(A)=0.3$, then $P(\text{not }A)=$ ___.`, 0.7, 0.001),
  num("medium", R`If $P(A)=0.35$, then $P(\text{not }A)=$ ___.`, 0.65, 0.001),
  mc("easy", R`The probabilities of all outcomes sum to`, [R`$1$`, R`$0$`, R`$100$`, R`the number of outcomes`], 0),
  mc("medium", R`$P(\text{rolling a }7)$ on a single die?`, [R`$0$`, R`$\tfrac17$`, R`$\tfrac16$`, R`$1$`], 0),
  mc("medium", R`$P(\text{a number}\le 6)$ on a die?`, [R`$1$`, R`$\tfrac56$`, R`$0$`, R`$\tfrac12$`], 0),
  fill("easy", R`$P(\text{not }A)=1-\ ?$`, ["P(A)"]),
  mc("medium", R`Probability estimated from observed data is`, [R`empirical`, R`classical`, R`subjective`, R`theoretical`], 0),
  num("medium", R`A spinner has $8$ equal sectors, $3$ shaded; $P(\text{shaded})$ as a decimal?`, 0.375, 0.001),
  mc("hard", R`Bag: $2$ red, $3$ blue, $5$ green. $P(\text{green})$?`, [R`$\tfrac12$`, R`$\tfrac13$`, R`$\tfrac15$`, R`$\tfrac25$`], 0),
  num("easy", R`$P(\text{tails})$ on a fair coin (decimal)?`, 0.5, 0.001),
  mc("hard", R`$P(\text{not an ace})$ from a deck?`, [R`$\tfrac{12}{13}$`, R`$\tfrac{1}{13}$`, R`$\tfrac{48}{52}$`, R`$\tfrac{4}{13}$`], 0),
];

// ── 6.2 Addition & Multiplication Rules ──────────────────────
const g62 = () => [
  num("easy", R`Mutually exclusive, $P=0.3$ and $0.4$: $P(A\text{ or }B)$?`, 0.7, 0.001),
  num("easy", R`Mutually exclusive, $P=0.2$ and $0.5$: $P(A\text{ or }B)$?`, 0.7, 0.001),
  mc("easy", R`Two coins: $P(\text{two heads})$?`, [R`$\tfrac14$`, R`$\tfrac12$`, R`$\tfrac13$`, R`$1$`], 0),
  mc("medium", R`Two dice: $P(\text{both }6)$?`, [R`$\tfrac{1}{36}$`, R`$\tfrac{1}{12}$`, R`$\tfrac16$`, R`$\tfrac{1}{6}$`], 0),
  fill("easy", R`$P(A\text{ or }B)=P(A)+P(B)-\ ?$`, ["P(A and B)"]),
  mc("medium", R`$P(\text{king or heart})$ from a deck?`, [R`$\tfrac{4}{13}$`, R`$\tfrac{17}{52}$`, R`$\tfrac{1}{13}$`, R`$\tfrac14$`], 0),
  mc("medium", R`$P(\text{red or king})$ from a deck?`, [R`$\tfrac{7}{13}$`, R`$\tfrac{30}{52}$`, R`$\tfrac12$`, R`$\tfrac{28}{52}$`], 0),
  mc("easy", R`If $A,B$ are independent, $P(B\mid A)=$`, [R`$P(B)$`, R`$P(A)$`, R`$0$`, R`$1$`], 0),
  mc("easy", R`Mutually exclusive events have $P(A\text{ and }B)=$`, [R`$0$`, R`$1$`, R`$P(A)P(B)$`, R`$0.5$`], 0),
  num("medium", R`Independent, $P(A)=0.5,\,P(B)=0.4$: $P(A\text{ and }B)$?`, 0.2, 0.001),
  num("medium", R`Independent, $P(A)=0.5,\,P(B)=0.6$: $P(A\text{ and }B)$?`, 0.3, 0.001),
  num("medium", R`Independent, $P(A)=0.6,\,P(B)=0.5$: $P(A\text{ and }B)$?`, 0.3, 0.001),
  mc("medium", R`Roll a die twice: $P(1\text{ then }2)$?`, [R`$\tfrac{1}{36}$`, R`$\tfrac{2}{36}$`, R`$\tfrac16$`, R`$\tfrac{1}{12}$`], 0),
  mc("hard", R`Draw $2$ cards without replacement: $P(\text{both aces})$?`, [R`$\tfrac{1}{221}$`, R`$\tfrac{1}{169}$`, R`$\tfrac{1}{16}$`, R`$\tfrac{1}{13}$`], 0),
  mc("medium", R`On a die, $P(\text{even or }5)$?`, [R`$\tfrac23$`, R`$\tfrac12$`, R`$\tfrac56$`, R`$\tfrac13$`], 0),
  mc("hard", R`Draw $2$ cards without replacement: $P(\text{both hearts})$?`, [R`$\tfrac{1}{17}$`, R`$\tfrac{1}{16}$`, R`$\tfrac14$`, R`$\tfrac{13}{52}$`], 0),
  tf("medium", R`For independent events, $P(A\text{ and }B)=P(A)\cdot P(B)$.`, true),
  mc("medium", R`$P(\text{three heads in a row})$?`, [R`$\tfrac18$`, R`$\tfrac14$`, R`$\tfrac16$`, R`$\tfrac{1}{3}$`], 0),
  mc("hard", R`The conditional probability $P(B\mid A)$ equals`, [R`$\dfrac{P(A\text{ and }B)}{P(A)}$`, R`$P(A)P(B)$`, R`$\dfrac{P(A)}{P(B)}$`, R`$P(A)+P(B)$`], 0),
  mc("medium", R`$P(\text{sum of two dice}=7)$?`, [R`$\tfrac16$`, R`$\tfrac{1}{12}$`, R`$\tfrac{1}{36}$`, R`$\tfrac17$`], 0),
  num("hard", R`$P(\text{doubles on two dice})$ as a decimal (to 3 dp)?`, 0.167, 0.002),
  tf("easy", R`$P(A\text{ or }B)=P(A)+P(B)$ only when the events are mutually exclusive.`, true),
  mc("hard", R`$P(A)=0.6,\,P(B)=0.5,\,P(A\text{ and }B)=0.3$. Are $A,B$ independent?`, [R`yes ($0.6\times0.5=0.3$)`, R`no`, R`cannot tell`, R`only if disjoint`], 0),
  mc("medium", R`Two events that cannot occur together are`, [R`mutually exclusive`, R`independent`, R`complementary only`, R`certain`], 0),
];

// ── 6.3 Counting: Permutations & Combinations ────────────────
const g63 = () => [
  num("easy", R`Evaluate $5!$.`, 120, 0),
  num("easy", R`Evaluate $4!$.`, 24, 0),
  num("easy", R`Evaluate $3!$.`, 6, 0),
  num("easy", R`Evaluate $0!$.`, 1, 0),
  num("medium", R`Evaluate $6!$.`, 720, 0),
  num("medium", R`Evaluate $P(5,2)$.`, 20, 0),
  num("medium", R`Evaluate $P(4,2)$.`, 12, 0),
  num("medium", R`Evaluate $P(6,2)$.`, 30, 0),
  num("hard", R`Evaluate $P(6,3)$.`, 120, 0),
  num("hard", R`Evaluate $P(8,3)$.`, 336, 0),
  num("easy", R`Evaluate $C(5,2)$.`, 10, 0),
  num("easy", R`Evaluate $C(6,2)$.`, 15, 0),
  num("medium", R`Evaluate $C(7,2)$.`, 21, 0),
  num("medium", R`Evaluate $C(8,2)$.`, 28, 0),
  num("medium", R`Evaluate $C(4,3)$.`, 4, 0),
  num("easy", R`Evaluate $C(10,1)$.`, 10, 0),
  num("easy", R`Evaluate $C(n,n)$.`, 1, 0),
  num("medium", R`Evaluate $C(6,3)$.`, 20, 0),
  num("easy", R`With $3$ shirts and $4$ pants, number of outfits?`, 12, 0),
  num("medium", R`With $4$ appetizers and $5$ mains, number of meals?`, 20, 0),
  num("hard", R`Number of $4$-digit PINs (digits may repeat)?`, 10000, 0),
  mc("easy", R`When order matters, use a`, [R`permutation`, R`combination`, R`factorial only`, R`ratio`], 0),
  mc("easy", R`When order does not matter, use a`, [R`combination`, R`permutation`, R`factorial only`, R`product`], 0),
  num("medium", R`Evaluate $C(52,1)$.`, 52, 0),
];

// ── 6.4 Applying Counting to Probability ─────────────────────
const g64 = () => [
  num("easy", R`Evaluate $C(5,2)\cdot C(4,3)$.`, 40, 0),
  num("easy", R`Number of committees of $2$ from $6$?`, 15, 0),
  num("easy", R`Ways to arrange $4$ books on a shelf?`, 24, 0),
  num("medium", R`Number of committees of $3$ from $8$?`, 56, 0),
  num("medium", R`Ways to choose $3$ from $7$?`, 35, 0),
  num("medium", R`Ways to line up $5$ people?`, 120, 0),
  num("medium", R`Ways to pick a president and VP from $8$ (order matters)?`, 56, 0),
  num("easy", R`Evaluate $C(6,3)$.`, 20, 0),
  mc("medium", R`Bag: $3$ red, $2$ blue. Draw $2$ (no replacement): $P(\text{both red})$?`, [R`$\tfrac{3}{10}$`, R`$\tfrac{3}{5}$`, R`$\tfrac{9}{25}$`, R`$\tfrac{1}{10}$`], 0),
  mc("hard", R`From $4$ red and $2$ white, choose $3$: $P(\text{all red})$?`, [R`$\tfrac15$`, R`$\tfrac25$`, R`$\tfrac{1}{20}$`, R`$\tfrac{4}{20}$`], 0),
  mc("hard", R`Draw $2$ cards (no replacement): $P(\text{both kings})$?`, [R`$\tfrac{1}{221}$`, R`$\tfrac{1}{169}$`, R`$\tfrac{1}{13}$`, R`$\tfrac{1}{16}$`], 0),
  num("medium", R`Choose $2$ men from $3$ AND $2$ women from $4$: $C(3,2)\cdot C(4,2)=$?`, 18, 0),
  num("hard", R`Number of $5$-card hands from a $52$-card deck? ($C(52,5)$)`, 2598960, 0),
  num("medium", R`Number of committees of $4$ from $10$?`, 210, 0),
  num("hard", R`Ways to arrange $3$ of $9$ runners on a podium? ($P(9,3)$)`, 504, 0),
  num("hard", R`Ways to choose $6$ numbers from $49$? ($C(49,6)$)`, 13983816, 0),
  num("easy", R`Ways to choose $2$ from $5$?`, 10, 0),
  mc("hard", R`Bag: $5$ red, $3$ blue. Draw $2$: $P(\text{both red})$?`, [R`$\tfrac{5}{14}$`, R`$\tfrac{25}{64}$`, R`$\tfrac57$`, R`$\tfrac{10}{56}$`], 0),
  num("medium", R`Handshakes among $6$ people ($C(6,2)$)?`, 15, 0),
  num("easy", R`Ways to seat $4$ people in a row?`, 24, 0),
  num("medium", R`Ways to choose $3$ pizza toppings from $8$?`, 56, 0),
  mc("hard", R`From $3$ blue, $3$ red, choose $3$: $P(\text{all blue})$?`, [R`$\tfrac{1}{20}$`, R`$\tfrac{1}{8}$`, R`$\tfrac{3}{20}$`, R`$\tfrac18$`], 0),
  num("medium", R`Ways to choose a $3$-person committee from $6$?`, 20, 0),
  num("hard", R`Choose $2$ from $5$ AND $1$ from $4$: $C(5,2)\cdot C(4,1)=$?`, 40, 0),
];

export default [
  { code: "6.1", gen: g61 }, { code: "6.2", gen: g62 }, { code: "6.3", gen: g63 },
  { code: "6.4", gen: g64 },
];
