// FTCE Unit 8 — Calculus. ~24 curated questions per topic. Answers verified.
import { mc, tf, num, fill } from "./helpers.mjs";
const R = String.raw;

// ── 8.1 Limits ───────────────────────────────────────────────
const g81 = () => [
  num("easy", R`$\lim_{x\to1}(3x+2)$?`, 5, 0),
  num("easy", R`$\lim_{x\to0}(x^2-4)$?`, -4, 0),
  num("easy", R`$\lim_{x\to5}(2x-3)$?`, 7, 0),
  num("easy", R`$\lim_{x\to0}(3x+7)$?`, 7, 0),
  num("medium", R`$\lim_{x\to2}\dfrac{x^2-4}{x-2}$?`, 4, 0),
  num("medium", R`$\lim_{x\to3}\dfrac{x^2-9}{x-3}$?`, 6, 0),
  num("medium", R`$\lim_{x\to1}\dfrac{x^2-1}{x-1}$?`, 2, 0),
  num("easy", R`$\lim_{x\to\infty}\dfrac5x$?`, 0, 0),
  num("easy", R`$\lim_{x\to\infty}\dfrac1x$?`, 0, 0),
  num("medium", R`$\lim_{x\to\infty}\dfrac{3x}{x+1}$?`, 3, 0),
  num("medium", R`$\lim_{x\to\infty}\dfrac{2x+1}{x-3}$?`, 2, 0),
  num("medium", R`$\lim_{x\to\infty}\dfrac{4x^2}{2x^2+1}$?`, 2, 0),
  num("hard", R`$\lim_{x\to\infty}\dfrac{5x^3}{x^3}$?`, 5, 0),
  num("medium", R`$\lim_{x\to\infty}\dfrac{x}{x^2+1}$?`, 0, 0),
  num("easy", R`$\lim_{x\to0}\dfrac{\sin x}{x}$?`, 1, 0),
  num("easy", R`$\lim_{x\to2}(x^2+1)$?`, 5, 0),
  num("easy", R`$\lim_{x\to4}(x+6)$?`, 10, 0),
  num("medium", R`$\lim_{x\to-1}(x^2+2x)$?`, -1, 0),
  num("medium", R`$\lim_{x\to2}(x^3)$?`, 8, 0),
  mc("easy", R`Direct substitution works when $f$ is`, [R`continuous at the point`, R`a polynomial only`, R`increasing`, R`positive`], 0),
  fill("medium", R`A $\tfrac00$ result is called an ___ form.`, ["indeterminate"]),
  tf("medium", R`For a limit to exist, the left- and right-hand limits must be equal.`, true),
  num("easy", R`$\lim_{x\to0}\cos x$?`, 1, 0),
  num("hard", R`$\lim_{x\to\infty}\dfrac{7}{x^2}$?`, 0, 0),
];

// ── 8.2 Continuity ───────────────────────────────────────────
const g82 = () => [
  tf("easy", R`Polynomials are continuous everywhere.`, true),
  mc("easy", R`Where is $f(x)=\dfrac1x$ discontinuous?`, [R`$x=0$`, R`$x=1$`, R`everywhere`, R`nowhere`], 0),
  mc("easy", R`The discontinuity at a vertical asymptote is`, [R`infinite`, R`removable`, R`jump`, R`none`], 0),
  mc("easy", R`A hole in a graph is a ___ discontinuity.`, [R`removable`, R`jump`, R`infinite`, R`essential`], 0),
  fill("easy", R`Continuity at $a$ requires $f(a)$ to be ___.`, ["defined"]),
  mc("medium", R`Where is $f(x)=\dfrac1{x-5}$ discontinuous?`, [R`$x=5$`, R`$x=-5$`, R`$x=0$`, R`nowhere`], 0),
  mc("easy", R`Is $\sqrt{x}$ continuous at $x=4$?`, [R`yes`, R`no`, R`only from the left`, R`undefined`], 0),
  mc("medium", R`If the left and right limits differ, the discontinuity is`, [R`jump`, R`removable`, R`infinite`, R`none`], 0),
  mc("medium", R`Classify the discontinuity of $\dfrac{x^2-1}{x-1}$ at $x=1$.`, [R`removable`, R`jump`, R`infinite`, R`none`], 0),
  num("easy", R`How many conditions must hold for continuity at a point?`, 3, 0),
  mc("medium", R`Where is $f(x)=\dfrac1{x-2}$ discontinuous?`, [R`$x=2$`, R`$x=-2$`, R`$x=0$`, R`nowhere`], 0),
  fill("medium", R`Rational functions are continuous except where the denominator is ___.`, ["zero", "0"]),
  mc("easy", R`Is $f(x)=x^2$ continuous at $x=3$?`, [R`yes`, R`no`, R`only from the right`, R`undefined`], 0),
  mc("hard", R`Where is $f(x)=\dfrac{x}{x^2-9}$ discontinuous?`, [R`$x=\pm3$`, R`$x=3$`, R`$x=9$`, R`nowhere`], 0),
  tf("medium", R`A jump discontinuity occurs when the one-sided limits differ.`, true),
  tf("easy", R`Every constant function is continuous.`, true),
  mc("medium", R`A removable discontinuity can be fixed by`, [R`redefining the point`, R`adding an asymptote`, R`differentiating`, R`nothing`], 0),
  mc("medium", R`Is $|x|$ continuous at $x=0$?`, [R`yes`, R`no`, R`only from the left`, R`undefined`], 0),
  mc("hard", R`$f(x)=\dfrac{x-2}{x-2}$ has a hole at`, [R`$x=2$`, R`$x=0$`, R`$x=1$`, R`nowhere`], 0),
  mc("medium", R`Is $e^x$ continuous everywhere?`, [R`yes`, R`no`, R`only for $x>0$`, R`only for $x<0$`], 0),
  mc("hard", R`A discontinuity where the denominator is $0$ but numerator is nonzero is`, [R`infinite`, R`removable`, R`jump`, R`none`], 0),
  tf("hard", R`$f(x)=\dfrac1{x^2+1}$ is continuous for all real $x$.`, true),
  fill("easy", R`A continuous graph has no breaks, holes, or ___.`, ["jumps"]),
  tf("medium", R`One condition for continuity is that $\lim_{x\to a}f(x)$ exists.`, true),
];

// ── 8.3 The Derivative ───────────────────────────────────────
const g83 = () => [
  mc("easy", R`Derivative of $f(x)=x^2$?`, [R`$2x$`, R`$x$`, R`$2$`, R`$x^2$`], 0),
  num("easy", R`Tangent slope to $f(x)=x^2$ at $x=2$?`, 4, 0),
  num("easy", R`Tangent slope to $f(x)=x^2$ at $x=1$?`, 2, 0),
  num("medium", R`Tangent slope to $f(x)=x^2$ at $x=3$?`, 6, 0),
  num("easy", R`Derivative of a constant?`, 0, 0),
  mc("medium", R`If $s(t)=t^3$, then $s'(t)=$`, [R`$3t^2$`, R`$t^2$`, R`$3t$`, R`$t^3$`], 0),
  fill("medium", R`$f'(x)$ gives the slope of the ___ line.`, ["tangent"]),
  mc("easy", R`The derivative is the limit of a`, [R`difference quotient`, R`sum`, R`product`, R`ratio of integers`], 0),
  num("medium", R`If $s(t)=t^2$, the velocity at $t=3$?`, 6, 0),
  num("easy", R`Derivative of $f(x)=3x$?`, 3, 0),
  num("easy", R`Derivative of $f(x)=x$?`, 1, 0),
  num("easy", R`Derivative of $f(x)=7$?`, 0, 0),
  fill("medium", R`In the definition, $\dfrac{f(x+h)-f(x)}{\_\_}$; the denominator is`, ["h"]),
  num("medium", R`For $f(x)=x^2$, find $f'(4)$.`, 8, 0),
  num("easy", R`Derivative of $f(x)=2x$?`, 2, 0),
  mc("easy", R`The instantaneous rate of change is the`, [R`derivative`, R`integral`, R`limit at infinity`, R`average`], 0),
  num("medium", R`Derivative of $f(x)=7x$?`, 7, 0),
  mc("medium", R`For $s(t)=t^2-2t$, $s'(t)=$`, [R`$2t-2$`, R`$2t$`, R`$t-2$`, R`$2t-2t$`], 0),
  num("hard", R`For $s(t)=t^2-2t$, the velocity at $t=3$?`, 4, 0),
  num("easy", R`Tangent slope to $f(x)=x^2$ at $x=0$?`, 0, 0),
  mc("medium", R`$\dfrac{dy}{dx}$ denotes the`, [R`derivative`, R`integral`, R`limit`, R`slope of a secant`], 0),
  mc("easy", R`Derivative of $f(x)=-x$?`, [R`$-1$`, R`$1$`, R`$0$`, R`$-x$`], 0),
  mc("medium", R`Velocity is the derivative of`, [R`position`, R`acceleration`, R`time`, R`distance squared`], 0),
  tf("easy", R`The derivative measures the slope of the tangent line.`, true),
];

// ── 8.4 Differentiation Rules ────────────────────────────────
const g84 = () => [
  mc("easy", R`$\dfrac{d}{dx}x^7=$`, [R`$7x^6$`, R`$6x^7$`, R`$7x^7$`, R`$x^6$`], 0),
  mc("easy", R`$\dfrac{d}{dx}(x^3-4x)=$`, [R`$3x^2-4$`, R`$3x^2-4x$`, R`$x^2-4$`, R`$3x-4$`], 0),
  mc("easy", R`$\dfrac{d}{dx}(5x^2)=$`, [R`$10x$`, R`$5x$`, R`$10x^2$`, R`$25x$`], 0),
  mc("easy", R`$\dfrac{d}{dx}x^5=$`, [R`$5x^4$`, R`$4x^5$`, R`$5x^5$`, R`$x^4$`], 0),
  mc("medium", R`$\dfrac{d}{dx}(3x^4-2x+1)=$`, [R`$12x^3-2$`, R`$12x^3-2x$`, R`$7x^3-2$`, R`$12x^3-1$`], 0),
  mc("medium", R`$\dfrac{d}{dx}(2x+1)^4=$`, [R`$8(2x+1)^3$`, R`$4(2x+1)^3$`, R`$8(2x+1)^4$`, R`$(2x+1)^3$`], 0),
  mc("medium", R`$\dfrac{d}{dx}(x^2+3)^5=$`, [R`$10x(x^2+3)^4$`, R`$5(x^2+3)^4$`, R`$10(x^2+3)^4$`, R`$5x(x^2+3)^4$`], 0),
  mc("hard", R`$\dfrac{d}{dx}(5x-1)^3=$`, [R`$15(5x-1)^2$`, R`$3(5x-1)^2$`, R`$5(5x-1)^2$`, R`$15(5x-1)^3$`], 0),
  mc("easy", R`The product rule $(fg)'=$`, [R`$f'g+fg'$`, R`$f'g-fg'$`, R`$f'g'$`, R`$\tfrac{f'}{g'}$`], 0),
  mc("medium", R`The quotient rule $\left(\tfrac{f}{g}\right)'=$`, [R`$\dfrac{f'g-fg'}{g^2}$`, R`$\dfrac{f'g+fg'}{g^2}$`, R`$\dfrac{f'}{g'}$`, R`$\dfrac{fg'-f'g}{g^2}$`], 0),
  mc("medium", R`$\dfrac{d}{dx}x^{1/2}=$`, [R`$\tfrac12 x^{-1/2}$`, R`$\tfrac12 x^{1/2}$`, R`$2x^{-1/2}$`, R`$x^{-1/2}$`], 0),
  mc("easy", R`$\dfrac{d}{dx}(7)=$`, [R`$0$`, R`$7$`, R`$1$`, R`$7x$`], 0),
  mc("medium", R`$\dfrac{d}{dx}(2x^3)=$`, [R`$6x^2$`, R`$2x^2$`, R`$6x^3$`, R`$3x^2$`], 0),
  mc("easy", R`$\dfrac{d}{dx}x^{10}=$`, [R`$10x^9$`, R`$9x^{10}$`, R`$10x^{10}$`, R`$x^9$`], 0),
  mc("medium", R`$\dfrac{d}{dx}(3x^2+2x)=$`, [R`$6x+2$`, R`$6x+2x$`, R`$3x+2$`, R`$6x$`], 0),
  mc("hard", R`$\dfrac{d}{dx}(x-1)^2=$`, [R`$2(x-1)$`, R`$(x-1)$`, R`$2(x-1)^2$`, R`$2x$`], 0),
  mc("medium", R`Simplify then differentiate $x^2\cdot x^3$:`, [R`$5x^4$`, R`$6x^5$`, R`$x^5$`, R`$5x^5$`], 0),
  mc("hard", R`The chain rule $\dfrac{d}{dx}f(g(x))=$`, [R`$f'(g(x))g'(x)$`, R`$f'(g(x))$`, R`$f'(x)g'(x)$`, R`$f(g'(x))$`], 0),
  mc("medium", R`$\dfrac{d}{dx}(4x)=$`, [R`$4$`, R`$4x$`, R`$1$`, R`$x$`], 0),
  mc("medium", R`$\dfrac{d}{dx}(x^2+1)=$`, [R`$2x$`, R`$2x+1$`, R`$x^2$`, R`$2$`], 0),
  mc("hard", R`$\dfrac{d}{dx}x^{-1}=$`, [R`$-x^{-2}$`, R`$x^{-2}$`, R`$-x^{-1}$`, R`$-1$`], 0),
  mc("hard", R`$\dfrac{d}{dx}(2x)^5=$`, [R`$160x^4$`, R`$10x^4$`, R`$32x^4$`, R`$80x^4$`], 0),
  tf("easy", R`The derivative of a sum is the sum of the derivatives.`, true),
  mc("medium", R`$\dfrac{d}{dx}(6x^{1/3})=$`, [R`$2x^{-2/3}$`, R`$6x^{-2/3}$`, R`$2x^{2/3}$`, R`$x^{-2/3}$`], 0),
];

// ── 8.5 Derivatives of Exp, Log & Trig ───────────────────────
const g85 = () => [
  mc("easy", R`$\dfrac{d}{dx}e^x=$`, [R`$e^x$`, R`$xe^{x-1}$`, R`$e$`, R`$\tfrac1x$`], 0),
  mc("easy", R`$\dfrac{d}{dx}\sin x=$`, [R`$\cos x$`, R`$-\cos x$`, R`$-\sin x$`, R`$\sec^2 x$`], 0),
  mc("easy", R`$\dfrac{d}{dx}\cos x=$`, [R`$-\sin x$`, R`$\sin x$`, R`$\cos x$`, R`$-\cos x$`], 0),
  mc("easy", R`$\dfrac{d}{dx}\ln x=$`, [R`$\dfrac1x$`, R`$\ln x$`, R`$x$`, R`$-\dfrac1{x^2}$`], 0),
  mc("medium", R`$\dfrac{d}{dx}\tan x=$`, [R`$\sec^2 x$`, R`$\csc^2 x$`, R`$-\sec^2 x$`, R`$\cot x$`], 0),
  mc("medium", R`$\dfrac{d}{dx}e^{3x}=$`, [R`$3e^{3x}$`, R`$e^{3x}$`, R`$3e^x$`, R`$e^{3}$`], 0),
  mc("medium", R`$\dfrac{d}{dx}\sin(2x)=$`, [R`$2\cos(2x)$`, R`$\cos(2x)$`, R`$2\cos x$`, R`$-2\cos(2x)$`], 0),
  mc("medium", R`$\dfrac{d}{dx}\ln(x^2)=$`, [R`$\dfrac2x$`, R`$\dfrac1{x^2}$`, R`$\dfrac1x$`, R`$2x$`], 0),
  mc("medium", R`$\dfrac{d}{dx}e^{2x}=$`, [R`$2e^{2x}$`, R`$e^{2x}$`, R`$2e^x$`, R`$2x e^{2x}$`], 0),
  mc("hard", R`$\dfrac{d}{dx}\cos(3x)=$`, [R`$-3\sin(3x)$`, R`$3\sin(3x)$`, R`$-\sin(3x)$`, R`$-3\cos(3x)$`], 0),
  num("medium", R`$\dfrac{d}{dx}e^x$ evaluated at $x=0$?`, 1, 0),
  mc("easy", R`$\dfrac{d}{dx}(2e^x)=$`, [R`$2e^x$`, R`$e^x$`, R`$2xe^x$`, R`$2e$`], 0),
  num("medium", R`$\dfrac{d}{dx}\sin x$ evaluated at $x=0$?`, 1, 0),
  mc("hard", R`$\dfrac{d}{dx}\ln(2x)=$`, [R`$\dfrac1x$`, R`$\dfrac2x$`, R`$\dfrac1{2x}$`, R`$2$`], 0),
  mc("hard", R`$\dfrac{d}{dx}e^{-x}=$`, [R`$-e^{-x}$`, R`$e^{-x}$`, R`$-e^x$`, R`$xe^{-x}$`], 0),
  mc("hard", R`$\dfrac{d}{dx}a^x=$`, [R`$a^x\ln a$`, R`$a^x$`, R`$x a^{x-1}$`, R`$a\ln x$`], 0),
  mc("medium", R`$\dfrac{d}{dx}(5\sin x)=$`, [R`$5\cos x$`, R`$5\sin x$`, R`$-5\cos x$`, R`$\cos x$`], 0),
  mc("medium", R`$\dfrac{d}{dx}(\sin x+\cos x)=$`, [R`$\cos x-\sin x$`, R`$\cos x+\sin x$`, R`$-\cos x-\sin x$`, R`$\sin x-\cos x$`], 0),
  mc("hard", R`$\dfrac{d}{dx}\ln(3x+1)=$`, [R`$\dfrac{3}{3x+1}$`, R`$\dfrac{1}{3x+1}$`, R`$\dfrac{3}{x}$`, R`$3\ln(3x+1)$`], 0),
  num("medium", R`$\dfrac{d}{dx}\cos x$ evaluated at $x=0$?`, 0, 0),
  mc("hard", R`$\dfrac{d}{dx}\sin(x^2)=$`, [R`$2x\cos(x^2)$`, R`$\cos(x^2)$`, R`$2x\sin(x^2)$`, R`$\cos(2x)$`], 0),
  mc("hard", R`$\dfrac{d}{dx}e^{x^2}=$`, [R`$2xe^{x^2}$`, R`$e^{x^2}$`, R`$2e^{x^2}$`, R`$x^2e^{x^2-1}$`], 0),
  tf("easy", R`$e^x$ is its own derivative.`, true),
  tf("medium", R`$\dfrac{d}{dx}\tan x=\sec^2 x$.`, true),
];

// ── 8.6 Applications of the Derivative ───────────────────────
const g86 = () => [
  num("easy", R`Critical point of $f(x)=x^2-6x$? ($x=$)`, 3, 0),
  num("easy", R`Critical point of $f(x)=x^2-8x$? ($x=$)`, 4, 0),
  mc("easy", R`$f''>0$ means the graph is concave`, [R`up`, R`down`, R`flat`, R`linear`], 0),
  mc("easy", R`$f'>0$ means the function is`, [R`increasing`, R`decreasing`, R`constant`, R`concave up`], 0),
  mc("easy", R`$f'<0$ means the function is`, [R`decreasing`, R`increasing`, R`constant`, R`concave down`], 0),
  num("medium", R`$f(x)=x^2-4x$ has a minimum at $x=$ ?`, 2, 0),
  mc("medium", R`At a local maximum, $f'$ changes from $+$ to`, [R`$-$`, R`$+$`, R`$0$`, R`undefined`], 0),
  mc("medium", R`$f''(c)<0$ indicates a local`, [R`maximum`, R`minimum`, R`inflection`, R`asymptote`], 0),
  mc("easy", R`Critical points occur where $f'=$`, [R`$0$ (or undefined)`, R`$1$`, R`$f$`, R`$\infty$`], 0),
  num("medium", R`$f(x)=x^3$ has an inflection point at $x=$ ?`, 0, 0),
  num("medium", R`Minimum value of $f(x)=x^2-4x+3$?`, -1, 0),
  num("medium", R`$f(x)=-x^2+4x$ has a maximum at $x=$ ?`, 2, 0),
  num("hard", R`Maximum value of $f(x)=-x^2+4x$?`, 4, 0),
  mc("medium", R`$f''(c)>0$ indicates a local`, [R`minimum`, R`maximum`, R`inflection`, R`asymptote`], 0),
  mc("medium", R`Concave down corresponds to $f''$`, [R`$<0$`, R`$>0$`, R`$=0$`, R`$=1$`], 0),
  tf("easy", R`A parabola's vertex is a critical point.`, true),
  num("hard", R`One critical point of $f(x)=x^3-3x$ (the positive one, $x=$)?`, 1, 0),
  num("hard", R`Critical points of $f(x)=x^3-12x$ are $x=\pm$ ?`, 2, 0),
  mc("medium", R`$f''=0$ may indicate an`, [R`inflection point`, R`absolute max`, R`asymptote`, R`hole`], 0),
  mc("medium", R`On a closed interval, absolute extrema occur at critical points or`, [R`endpoints`, R`inflection points`, R`asymptotes`, R`the origin`], 0),
  tf("easy", R`$f(x)=x^2$ is concave up everywhere.`, true),
  mc("medium", R`At a local minimum, $f'$ changes from $-$ to`, [R`$+$`, R`$-$`, R`$0$`, R`undefined`], 0),
  mc("easy", R`The second derivative measures`, [R`concavity`, R`slope`, R`area`, R`position`], 0),
  num("hard", R`$f(x)=6x-x^2$ has a maximum at $x=$ ?`, 3, 0),
];

// ── 8.7 Antiderivatives & the Definite Integral ──────────────
const g87 = () => [
  mc("easy", R`$\displaystyle\int x^3\,dx=$`, [R`$\tfrac{x^4}{4}+C$`, R`$3x^2+C$`, R`$\tfrac{x^4}{3}+C$`, R`$4x^3+C$`], 0),
  mc("easy", R`$\displaystyle\int 2\,dx=$`, [R`$2x+C$`, R`$2+C$`, R`$x^2+C$`, R`$0$`], 0),
  mc("easy", R`$\displaystyle\int x^2\,dx=$`, [R`$\tfrac{x^3}{3}+C$`, R`$2x+C$`, R`$\tfrac{x^3}{2}+C$`, R`$3x^2+C$`], 0),
  mc("medium", R`$\displaystyle\int(2x+1)\,dx=$`, [R`$x^2+x+C$`, R`$2x^2+x+C$`, R`$x^2+1+C$`, R`$2+C$`], 0),
  num("easy", R`$\displaystyle\int_0^1 x\,dx$? (decimal)`, 0.5, 0.001),
  num("medium", R`$\displaystyle\int_1^2 2x\,dx$?`, 3, 0),
  num("medium", R`$\displaystyle\int_1^3 2x\,dx$?`, 8, 0),
  num("easy", R`$\displaystyle\int_0^2 x\,dx$?`, 2, 0),
  num("easy", R`$\displaystyle\int_0^3 2\,dx$?`, 6, 0),
  num("medium", R`$\displaystyle\int_0^1 x^2\,dx$? (decimal, 3 dp)`, 0.333, 0.005),
  mc("easy", R`$\displaystyle\int\cos x\,dx=$`, [R`$\sin x+C$`, R`$-\sin x+C$`, R`$\cos x+C$`, R`$-\cos x+C$`], 0),
  mc("easy", R`$\displaystyle\int\dfrac1x\,dx=$`, [R`$\ln|x|+C$`, R`$-\tfrac1{x^2}+C$`, R`$\tfrac1x+C$`, R`$x+C$`], 0),
  mc("easy", R`$\displaystyle\int e^x\,dx=$`, [R`$e^x+C$`, R`$xe^x+C$`, R`$\tfrac{e^x}{x}+C$`, R`$e^{x+1}+C$`], 0),
  mc("medium", R`$\displaystyle\int\sin x\,dx=$`, [R`$-\cos x+C$`, R`$\cos x+C$`, R`$\sin x+C$`, R`$-\sin x+C$`], 0),
  mc("easy", R`$\displaystyle\int x\,dx=$`, [R`$\tfrac{x^2}{2}+C$`, R`$x^2+C$`, R`$1+C$`, R`$\tfrac{x^2}{1}+C$`], 0),
  mc("medium", R`$\displaystyle\int x^4\,dx=$`, [R`$\tfrac{x^5}{5}+C$`, R`$4x^3+C$`, R`$\tfrac{x^5}{4}+C$`, R`$5x^4+C$`], 0),
  fill("easy", R`The constant of integration is written as ___.`, ["+C", "C"]),
  mc("medium", R`The Fundamental Theorem: $\displaystyle\int_a^b f\,dx=F(b)-$`, [R`$F(a)$`, R`$F(0)$`, R`$f(a)$`, R`$F(b)$`], 0),
  num("hard", R`$\displaystyle\int_0^{\pi}\sin x\,dx$?`, 2, 0),
  mc("easy", R`$\displaystyle\int 3\,dx=$`, [R`$3x+C$`, R`$3+C$`, R`$\tfrac{x^2}{3}+C$`, R`$0$`], 0),
  mc("medium", R`$\displaystyle\int(x^2+x)\,dx=$`, [R`$\tfrac{x^3}{3}+\tfrac{x^2}{2}+C$`, R`$2x+1+C$`, R`$\tfrac{x^3}{3}+x+C$`, R`$x^3+x^2+C$`], 0),
  num("medium", R`$\displaystyle\int_2^4 1\,dx$?`, 2, 0),
  tf("medium", R`A definite integral gives the net signed area.`, true),
  num("hard", R`$\displaystyle\int_0^2 3x^2\,dx$?`, 8, 0),
];

// ── 8.8 Applications of Integration ──────────────────────────
const g88 = () => [
  num("medium", R`Area under $y=x^2$ from $0$ to $2$? (decimal, 3 dp)`, 2.667, 0.01),
  num("easy", R`Area under $y=3x^2$ from $0$ to $1$?`, 1, 0),
  num("medium", R`Area under $y=x^2$ from $0$ to $3$?`, 9, 0),
  num("easy", R`Area under $y=2x$ from $0$ to $4$?`, 16, 0),
  num("easy", R`Area under $y=4$ from $0$ to $5$?`, 20, 0),
  num("medium", R`Area under $y=6$ from $0$ to $3$?`, 18, 0),
  num("hard", R`Area between $y=x$ and $y=x^2$ on $[0,1]$? (decimal, 3 dp)`, 0.167, 0.005),
  mc("medium", R`The disk-method volume formula is`, [R`$V=\pi\int R^2\,dx$`, R`$V=\int R\,dx$`, R`$V=2\pi\int R\,dx$`, R`$V=\pi\int R\,dx$`], 0),
  mc("easy", R`Area between two curves integrates top minus`, [R`bottom`, R`left`, R`right`, R`zero`], 0),
  num("medium", R`$\displaystyle\int_0^1 x^2\,dx$? (decimal, 3 dp)`, 0.333, 0.005),
  mc("medium", R`Volume rotating $y=1$ on $[0,2]$ about the $x$-axis?`, [R`$2\pi$`, R`$4\pi$`, R`$\pi$`, R`$2$`], 0),
  mc("medium", R`Volume rotating $y=2$ on $[0,3]$ about the $x$-axis?`, [R`$12\pi$`, R`$6\pi$`, R`$24\pi$`, R`$4\pi$`], 0),
  num("medium", R`Area under $y=x$ from $0$ to $4$?`, 8, 0),
  mc("hard", R`Area between $y=4$ and $y=x^2$ from $-2$ to $2$?`, [R`$\tfrac{32}{3}$`, R`$16$`, R`$\tfrac{16}{3}$`, R`$8$`], 0),
  mc("medium", R`The shell method uses`, [R`$2\pi\int(\text{radius})(\text{height})\,dx$`, R`$\pi\int R^2\,dx$`, R`$\int R\,dx$`, R`$2\pi\int R^2\,dx$`], 0),
  num("hard", R`Area under $y=x^3$ from $0$ to $2$?`, 4, 0),
  num("hard", R`Volume rotating $y=3$ on $[0,1]$ about the $x$-axis (coefficient of $\pi$)?`, 9, 0),
  mc("medium", R`For total (not net) area, the integrand should be`, [R`non-negative`, R`negative`, R`zero`, R`linear`], 0),
  num("medium", R`$\displaystyle\int_0^2 2x\,dx$?`, 4, 0),
  mc("medium", R`When curves cross, the area limits are the`, [R`intersection points`, R`endpoints of the axes`, R`intercepts`, R`asymptotes`], 0),
  num("hard", R`Area under $y=x^2$ from $1$ to $2$? (decimal, 3 dp)`, 2.333, 0.01),
  tf("medium", R`A net signed area can be negative.`, true),
  mc("hard", R`Between $y=x$ and $y=x^2$ on $[0,1]$, the top curve is`, [R`$y=x$`, R`$y=x^2$`, R`both`, R`neither`], 0),
  num("easy", R`Area under $y=5$ from $0$ to $4$?`, 20, 0),
];

export default [
  { code: "8.1", gen: g81 }, { code: "8.2", gen: g82 }, { code: "8.3", gen: g83 },
  { code: "8.4", gen: g84 }, { code: "8.5", gen: g85 }, { code: "8.6", gen: g86 },
  { code: "8.7", gen: g87 }, { code: "8.8", gen: g88 },
];
