// MFM2P remaining worksheets: 5.1, 5.4, 7.5.
const r = String.raw;
const U5 = r`5: Similar Triangles \& Trigonometry`;

export default [
{
  code: "5.1", unit: U5, title: r`Ratio, Proportion \& Scale`,
  intro: r`A ratio compares quantities; a proportion sets two ratios equal; a scale shrinks or enlarges by a constant factor.`,
  ideas: [
    r`Simplify a ratio like a fraction: $12:18=2:3$.`,
    r`Solve a proportion by cross-multiplying.`,
    r`A scale $1:n$ means $1$ drawing unit $=n$ real units; real $=$ drawing $\times n$.`,
    r`Ratios power similar triangles (proportional sides).`,
  ],
  examples: [
    { t: "Simplify a ratio", body: r`Simplify $12:18$.\soln Divide both by $6$: $2:3$.` },
    { t: "Solve a proportion", body: r`Solve $\dfrac34=\dfrac{x}{12}$.\soln Cross-multiply: $4x=36$, $x=9$.` },
    { t: "Scale drawing", body: r`On a $1:50$ plan a wall is $4$ cm. Find the real length.\soln $4\times50=200$ cm $=2$ m.` },
    { t: "Recipe ratio", body: r`Flour : sugar $=3:1$. With $9$ cups flour, how much sugar?\soln $\dfrac31=\dfrac{9}{s}\Rightarrow s=3$ cups.` },
    { t: "Map scale", body: r`A $1:100000$ map: two towns are $7.5$ cm apart. Real distance?\soln $7.5\times100000=750000$ cm $=7.5$ km.` },
    { t: "Simplify", body: r`Simplify $20:35$.\soln Divide by $5$: $4:7$.` },
    { t: "Solve a proportion", body: r`Solve $\dfrac58=\dfrac{x}{24}$.\soln $8x=120$, $x=15$.` },
    { t: "Model scale", body: r`A $1:25$ model car is $18$ cm. Real length?\soln $18\times25=450$ cm.` },
    { t: "Map scale (harder)", body: r`A $1:50000$ map: two points are $6$ cm apart. Real distance in km?\soln $6\times50000=300000$ cm $=3$ km.` },
  ],
  questions: [
    { ask: r`Simplify $15:25$.`, ws: "1.8cm" },
    { ask: r`Solve $\dfrac{3}{7}=\dfrac{12}{x}$.`, ws: "2.0cm" },
    { ask: r`On a $1:50$ plan a wall is $6$ cm; find the real length.`, ws: "2.0cm" },
    { ask: r`Paint mixes blue : white $=2:5$. With $10$ L blue, how much white?`, ws: "2.2cm" },
    { ask: r`A $1:100000$ map: $5$ cm apart. Real distance in km?`, ws: "2.0cm" },
    { ask: r`Simplify $24:36$.`, ws: "1.8cm" },
    { ask: r`Solve $\dfrac{x}{6}=\dfrac{10}{4}$.`, ws: "2.0cm" },
    { ask: r`A $1:40$ model is $20$ cm; find the real length.`, ws: "2.0cm" },
    { ask: r`A recipe is sugar : flour $=2:3$; with $6$ cups sugar, how much flour?`, ws: "2.2cm" },
    { ask: r`Solve $\dfrac{4}{9}=\dfrac{x}{27}$.`, ws: "2.0cm" },
    { ask: r`A $1:25000$ map: $8$ cm apart. Real distance in km?`, ws: "2.2cm" },
    { ask: r`Simplify $18:30$.`, ws: "1.8cm" },
    { ask: r`A $1:50000$ map: $6$ cm apart. Real distance in km?`, ws: "2.2cm", challenge: true },
  ],
  answers: [r`$3:5$.`, r`$3x=84\Rightarrow x=28$.`, r`$6\times50=300$ cm $=3$ m.`, r`$25$ L.`, r`$5$ km.`, r`$2:3$.`, r`$4x=60\Rightarrow x=15$.`, r`$800$ cm $=8$ m.`, r`$9$ cups.`, r`$9x=108\Rightarrow x=12$.`, r`$8\times25000=200000$ cm $=2$ km.`, r`$3:5$.`, r`$3$ km.`],
},
{
  code: "5.4", unit: U5, title: "The Pythagorean Theorem",
  intro: r`In a right triangle, $a^2+b^2=c^2$ where $c$ is the hypotenuse (opposite the right angle).`,
  ideas: [
    r`Hypotenuse: $c=\sqrt{a^2+b^2}$.`,
    r`Leg: $a=\sqrt{c^2-b^2}$.`,
    r`Only right triangles; $c$ is the longest side.`,
    r`Common triples: 3-4-5, 5-12-13, 8-15-17.`,
  ],
  examples: [
    { t: "Find the hypotenuse", body: r`Legs $3$ and $4$. Find $c$.\soln $c=\sqrt{9+16}=\sqrt{25}=5$.
\plot{-1}{6}{-1}{5}{\addplot[exblue,very thick]coordinates{(0,0)(4,0)(4,3)(0,0)};\addplot[mark=*,only marks,black]coordinates{(0,0)(4,0)(4,3)};}` },
    { t: "Bigger triangle", body: r`Legs $6$ and $8$. Find $c$.\soln $\sqrt{36+64}=\sqrt{100}=10$.` },
    { t: "Find a leg", body: r`Hypotenuse $13$, leg $5$. Find the other leg.\soln $\sqrt{169-25}=\sqrt{144}=12$.` },
    { t: "Decimal answer", body: r`Legs $5$ and $7$. Find $c$ (1 dp).\soln $\sqrt{25+49}=\sqrt{74}\approx8.6$.` },
    { t: "Ladder", body: r`A $5$ m ladder's base is $3$ m from a wall. How high does it reach?\soln $\sqrt{25-9}=\sqrt{16}=4$ m.` },
    { t: "Triple", body: r`Legs $8$ and $15$. Find $c$.\soln $\sqrt{64+225}=\sqrt{289}=17$.` },
    { t: "Scaled triple", body: r`Legs $9$ and $12$. Find $c$.\soln $\sqrt{81+144}=\sqrt{225}=15$.` },
    { t: "Find a leg", body: r`Hypotenuse $25$, leg $7$. Find the other leg.\soln $\sqrt{625-49}=\sqrt{576}=24$.` },
    { t: "TV diagonal (harder)", body: r`A TV is $40$ in wide and $30$ in tall. Find the diagonal.\soln $\sqrt{1600+900}=\sqrt{2500}=50$ in.` },
  ],
  questions: [
    { ask: r`Legs $8$ and $15$; find $c$.`, ws: "2.0cm" },
    { ask: r`Legs $9$ and $12$; find $c$.`, ws: "2.0cm" },
    { ask: r`Hypotenuse $25$, leg $7$; find the other leg.`, ws: "2.2cm" },
    { ask: r`Legs $2$ and $6$; find $c$ (1 dp).`, ws: "2.0cm" },
    { ask: r`Legs $5$ and $12$; find $c$.`, ws: "2.0cm" },
    { ask: r`Hypotenuse $17$, leg $8$; find the other leg.`, ws: "2.2cm" },
    { ask: r`A $10$ m ladder's base is $6$ m from a wall; how high does it reach?`, ws: "2.4cm" },
    { ask: r`Legs $7$ and $24$; find $c$.`, ws: "2.0cm" },
    { ask: r`Legs $1$ and $1$; find $c$ (1 dp).`, ws: "2.0cm" },
    { ask: r`A rectangle is $9$ m by $12$ m; find the diagonal.`, ws: "2.2cm" },
    { ask: r`Hypotenuse $13$, leg $12$; find the other leg.`, ws: "2.2cm" },
    { ask: r`Legs $3$ and $4$; find $c$.`, ws: "1.8cm" },
    { ask: r`A TV is $40$ in by $30$ in; find the diagonal.`, ws: "2.4cm", challenge: true },
  ],
  answers: [r`$\sqrt{289}=17$.`, r`$\sqrt{225}=15$.`, r`$\sqrt{576}=24$.`, r`$\sqrt{40}\approx6.3$.`, r`$\sqrt{169}=13$.`, r`$\sqrt{225}=15$.`, r`$\sqrt{64}=8$ m.`, r`$\sqrt{625}=25$.`, r`$\sqrt{2}\approx1.4$.`, r`$\sqrt{225}=15$ m.`, r`$\sqrt{25}=5$.`, r`$5$.`, r`$\sqrt{2500}=50$ in.`],
},
{
  code: "7.5", unit: "7: Quadratic Relations", title: "Interpreting Quadratic Graphs in Context",
  intro: r`Parabolas model thrown objects, profit, and arches: the vertex is a max/min, the zeros are where the quantity is $0$, the $y$-intercept is the starting value.`,
  ideas: [
    r`Vertex: the maximum or minimum (e.g. greatest height, greatest profit).`,
    r`Zeros: where the quantity is $0$ (landing time, break-even).`,
    r`$y$-intercept: the value at the start ($x=0$).`,
    r`Reject impossible answers (e.g. a negative time).`,
  ],
  examples: [
    { t: "Projectile", body: r`$h=-5t^2+20t$. Find the maximum height and the landing time.\soln Vertex $t=2$: $h=20$. Zeros: $t=0,4$. Max $20$ m at $2$ s; lands at $4$ s.
\plot{0}{5}{-2}{22}{\addplot[exblue,very thick,domain=0:4,samples=40]{-5*x^2+20*x};\addplot[mark=*,only marks,black]coordinates{(2,20)(4,0)};}` },
    { t: "Profit (break-even)", body: r`$P=-x^2+10x-16$. Find the break-even points and the maximum profit.\soln Zeros $x=2,8$; vertex $x=5$, $P=9$.
\plot{0}{9}{-3}{10}{\addplot[exblue,very thick,domain=1.5:8.5,samples=40]{-x^2+10*x-16};\addplot[mark=*,only marks,black]coordinates{(5,9)(2,0)(8,0)};}` },
    { t: "Read the vertex", body: r`A ball's path is $y=-(x-3)^2+9$. Greatest height and where?\soln Vertex $(3,9)$: max $9$ at $x=3$.` },
    { t: "Starting value", body: r`$h=-5t^2+10t+15$. From what height was it released?\soln At $t=0$, $h=15$ m.` },
    { t: "Landing time", body: r`$h=-5t^2+10t+15$. Find the landing time.\soln $t^2-2t-3=0\Rightarrow(t-3)(t+1)=0\Rightarrow t=3$ s.
\plot{0}{4}{-2}{22}{\addplot[exblue,very thick,domain=0:3,samples=40]{-5*x^2+10*x+15};\addplot[mark=*,only marks,black]coordinates{(0,15)(3,0)};}` },
    { t: "Landing time", body: r`$h=-5t^2+30t$. When does it land?\soln $-5t(t-6)=0\Rightarrow t=6$ s.` },
    { t: "Maximum height", body: r`$h=-5t^2+30t$. Find the maximum height.\soln Vertex $t=3$: $h=45$ m.` },
    { t: "Zeros from vertex form", body: r`$y=(x-4)^2-9$. Find the zeros.\soln $(x-4)^2=9\Rightarrow x=1,7$.` },
    { t: "Full projectile (harder)", body: r`$h=-5t^2+20t+25$. Find the max height and the landing time.\soln Vertex $t=2$: $h=45$. Land: $t^2-4t-5=0\Rightarrow t=5$ s.` },
  ],
  questions: [
    { ask: r`$h=-5t^2+30t$. When does it land?`, ws: "2.2cm" },
    { ask: r`$h=-5t^2+30t$. Find the maximum height.`, ws: "2.2cm" },
    { ask: r`$y=(x-4)^2-9$. Find the zeros.`, ws: "2.2cm" },
    { ask: r`$P=-(x-5)^2+12$. Find the maximum profit and where.`, ws: "2.2cm" },
    { ask: r`$h=-5t^2+20t$. Find the landing time.`, ws: "2.2cm" },
    { ask: r`$h=-5t^2+20t$. Find the maximum height.`, ws: "2.2cm" },
    { ask: r`$y=-(x-2)^2+16$. State the vertex and the maximum.`, ws: "2.2cm" },
    { ask: r`$h=-5t^2+10t+15$. From what height was it released?`, ws: "2.2cm" },
    { ask: r`$h=-5t^2+10t+15$. Find the landing time.`, ws: "2.4cm" },
    { ask: r`$P=-x^2+8x-12$. Find the break-even points.`, ws: "2.4cm" },
    { ask: r`$P=-x^2+8x-12$. Find the maximum profit.`, ws: "2.4cm" },
    { ask: r`$y=(x-3)^2-4$. Find the zeros.`, ws: "2.2cm" },
    { ask: r`$h=-5t^2+20t+25$. Find the max height and the landing time.`, ws: "2.6cm", challenge: true },
  ],
  answers: [r`$-5t(t-6)=0\Rightarrow t=6$ s.`, r`Vertex $t=3$: $45$ m.`, r`$x=1,7$.`, r`Vertex $(5,12)$: $12$ at $x=5$.`, r`$t=0,4\Rightarrow$ lands at $4$ s.`, r`Vertex $t=2$: $20$ m.`, r`Vertex $(2,16)$: max $16$.`, r`$15$ m.`, r`$t^2-2t-3=0\Rightarrow t=3$ s.`, r`$(x-2)(x-6)=0\Rightarrow x=2,6$.`, r`Vertex $x=4$: $P=4$.`, r`$x=1,5$.`, r`Vertex $t=2$: $45$ m; lands at $t=5$ s.`],
},
];
