// MFM2P Unit 1 — Algebra & Solving Equations worksheets (1.1–1.6).
const r = String.raw;
const U = r`1: Algebra \& Solving Equations`;

export default [
{
  code: "1.1", unit: U, title: r`Review of Expressions \& Integers`,
  intro: r`Algebra rests on confident integer arithmetic and careful evaluation.`,
  ideas: [
    r`Adding: same signs add and keep the sign; different signs subtract and keep the larger size's sign.`,
    r`Subtracting means adding the opposite: $a-(-b)=a+b$.`,
    r`Multiplying/dividing: same signs give positive, different signs give negative.`,
    r`Substitute negatives in brackets, then follow BEDMAS (brackets, exponents, $\times\div$, $+-$).`,
  ],
  examples: [
    { t: "Adding integers", body: r`Evaluate $-3+7-5$.\soln $-3+7=4$, then $4-5=-1$.` },
    { t: "Subtracting a negative", body: r`Evaluate $4-(-6)$.\soln Add the opposite: $4+6=10$.` },
    { t: "Multiplying", body: r`Evaluate $(-4)(3)$.\soln Different signs $\Rightarrow$ negative: $-12$.` },
    { t: "Dividing", body: r`Evaluate $-20\div(-5)$.\soln Same signs $\Rightarrow$ positive: $4$.` },
    { t: "Evaluate by substitution", body: r`Evaluate $2x^2-3x$ at $x=-2$.\soln $2(-2)^2-3(-2)=2(4)+6=14$.` },
    { t: "Order of operations", body: r`Evaluate $5+2\times3^2-4$.\soln $3^2=9$; $2\times9=18$; $5+18-4=19$.` },
    { t: "Two variables", body: r`Evaluate $\dfrac{a-b}{c}$ at $a=7,\ b=-3,\ c=2$.\soln $\dfrac{7-(-3)}{2}=\dfrac{10}{2}=5$.` },
    { t: "Sign and exponent", body: r`Evaluate $-3^2$ and $(-3)^2$.\soln $-3^2=-(9)=-9$; $(-3)^2=9$.` },
    { t: "Putting it together", body: r`Evaluate $\dfrac{2a+b}{a-b}$ at $a=4,\ b=-2$.\soln $\dfrac{8-2}{4+2}=\dfrac{6}{6}=1$.` },
  ],
  questions: [
    { ask: r`Evaluate $-8+3-(-2)$.`, ws: "1.8cm" },
    { ask: r`Evaluate $(-6)(-4)$.`, ws: "1.8cm" },
    { ask: r`Evaluate $-18\div3$.`, ws: "1.8cm" },
    { ask: r`Evaluate $3x-x^2$ at $x=-1$.`, ws: "2.0cm" },
    { ask: r`Evaluate $12-3\times2+4$.`, ws: "1.8cm" },
    { ask: r`Evaluate $-5^2$.`, ws: "1.8cm" },
    { ask: r`Evaluate $(-5)^2$.`, ws: "1.8cm" },
    { ask: r`Evaluate $2x^2+1$ at $x=-3$.`, ws: "2.0cm" },
    { ask: r`Evaluate $\dfrac{a+b}{2}$ at $a=7,\ b=-1$.`, ws: "2.0cm" },
    { ask: r`Evaluate $4-(-3)-8$.`, ws: "1.8cm" },
    { ask: r`Evaluate $(-2)^3$.`, ws: "1.8cm" },
    { ask: r`Evaluate $10-2(3-7)$.`, ws: "2.0cm" },
    { ask: r`Evaluate $\dfrac{2a+b}{a-b}$ at $a=4,\ b=-2$.`, ws: "2.4cm", challenge: true },
  ],
  answers: [r`$-3$.`, r`$24$.`, r`$-6$.`, r`$3(-1)-1=-4$.`, r`$12-6+4=10$.`, r`$-25$.`, r`$25$.`, r`$18+1=19$.`, r`$3$.`, r`$-1$.`, r`$-8$.`, r`$10-2(-4)=18$.`, r`$\dfrac{6}{6}=1$.`],
},
{
  code: "1.2", unit: U, title: r`Like Terms \& the Distributive Property`,
  intro: r`Simplify before you solve: collect like terms and remove brackets.`,
  ideas: [
    r`Like terms have the same variable and power; combine only their coefficients.`,
    r`Distributive property: $a(b+c)=ab+ac$ — multiply every term inside.`,
    r`A negative in front flips every sign inside the brackets.`,
    r`Expand brackets first, then collect like terms.`,
  ],
  examples: [
    { t: "Collect like terms", body: r`Simplify $4x+7-2x+3$.\soln $(4x-2x)+(7+3)=2x+10$.` },
    { t: "Distribute", body: r`Expand $3(x+4)$.\soln $3x+12$.` },
    { t: "Negative factor", body: r`Expand $-2(2x-5)$.\soln $-4x+10$.` },
    { t: "Expand then collect", body: r`Simplify $2(x+3)+4x$.\soln $2x+6+4x=6x+6$.` },
    { t: "Two brackets", body: r`Simplify $3(x-1)-2(x+4)$.\soln $3x-3-2x-8=x-11$.` },
    { t: "Monomial times binomial", body: r`Expand $x(x+5)$.\soln $x^2+5x$.` },
    { t: "Two variables", body: r`Simplify $5a-3b+2a+b$.\soln $7a-2b$.` },
    { t: "Distribute a negative one", body: r`Expand $-(x-6)$.\soln $-x+6$.` },
    { t: "Putting it together", body: r`Simplify $2(3x-1)-4(x-2)$.\soln $6x-2-4x+8=2x+6$.` },
  ],
  questions: [
    { ask: r`Simplify $5x+2-3x+6$.`, ws: "1.8cm" },
    { ask: r`Expand $4(2x-3)$.`, ws: "1.8cm" },
    { ask: r`Expand $-3(x+5)$.`, ws: "1.8cm" },
    { ask: r`Simplify $3(x+2)+5x$.`, ws: "2.0cm" },
    { ask: r`Simplify $4(x-1)-2(x+3)$.`, ws: "2.2cm" },
    { ask: r`Expand $x(2x-3)$.`, ws: "1.8cm" },
    { ask: r`Simplify $6a+2b-a-5b$.`, ws: "2.0cm" },
    { ask: r`Expand $-(2x-7)$.`, ws: "1.8cm" },
    { ask: r`Simplify $2(x+4)-3x$.`, ws: "2.0cm" },
    { ask: r`Expand $5(3x+2)$.`, ws: "1.8cm" },
    { ask: r`Simplify $-2(x-3)+4(x+1)$.`, ws: "2.2cm" },
    { ask: r`Write a simplified expression for the perimeter of a rectangle with length $x+5$ and width $3$.`, ws: "2.2cm" },
    { ask: r`Simplify $3(2x-1)-2(3x-4)$.`, ws: "2.4cm", challenge: true },
  ],
  answers: [r`$2x+8$.`, r`$8x-12$.`, r`$-3x-15$.`, r`$8x+6$.`, r`$2x-10$.`, r`$2x^2-3x$.`, r`$5a-3b$.`, r`$-2x+7$.`, r`$-x+8$.`, r`$15x+10$.`, r`$2x+10$.`, r`$2(x+5)+2(3)=2x+16$.`, r`$6x-3-6x+8=5$.`],
},
{
  code: "1.3", unit: U, title: r`Solving One- \& Two-Step Equations`,
  intro: r`Solve an equation by isolating the variable with inverse operations.`,
  ideas: [
    r`Undo $+$ with $-$, and $\times$ with $\div$ — do the same to both sides.`,
    r`Two-step: undo addition/subtraction first, then multiplication/division.`,
    r`Check by substituting your answer back into the original equation.`,
    r`If the variable is negative ($-x=k$), multiply both sides by $-1$.`,
  ],
  examples: [
    { t: "One step (add)", body: r`Solve $x+5=12$.\soln Subtract $5$: $x=7$.` },
    { t: "One step (multiply)", body: r`Solve $3x=21$.\soln Divide by $3$: $x=7$.` },
    { t: "Subtraction", body: r`Solve $x-4=-2$.\soln Add $4$: $x=2$.` },
    { t: "Two steps", body: r`Solve $2x+1=9$.\soln $2x=8$, then $x=4$.` },
    { t: "Division", body: r`Solve $\dfrac{x}{4}=3$.\soln Multiply by $4$: $x=12$.` },
    { t: "Negative variable", body: r`Solve $5-x=2$.\soln $-x=-3$, so $x=3$.` },
    { t: "Two steps again", body: r`Solve $3x-2=10$.\soln $3x=12$, then $x=4$.` },
    { t: "Two-step with fraction", body: r`Solve $\dfrac{x}{2}+1=5$.\soln $\dfrac{x}{2}=4$, then $x=8$.` },
    { t: "Negative coefficient", body: r`Solve $7-2x=1$.\soln $-2x=-6$, so $x=3$.` },
  ],
  questions: [
    { ask: r`Solve $x-7=2$.`, ws: "1.8cm" },
    { ask: r`Solve $4x=20$.`, ws: "1.8cm" },
    { ask: r`Solve $x+9=4$.`, ws: "1.8cm" },
    { ask: r`Solve $2x-5=11$.`, ws: "2.0cm" },
    { ask: r`Solve $\dfrac{x}{3}=4$.`, ws: "1.8cm" },
    { ask: r`Solve $3x+2=17$.`, ws: "2.0cm" },
    { ask: r`Solve $8-x=3$.`, ws: "2.0cm" },
    { ask: r`Solve $\dfrac{x}{2}-1=4$.`, ws: "2.0cm" },
    { ask: r`Solve $5x=-15$.`, ws: "1.8cm" },
    { ask: r`Solve $2x+7=1$.`, ws: "2.0cm" },
    { ask: r`A taxi charges $3$ dollars plus $2$ dollars per km. Write and solve an equation for a $15$-dollar fare.`, ws: "2.6cm" },
    { ask: r`Solve $\dfrac{x}{5}+2=6$.`, ws: "2.0cm" },
    { ask: r`Solve $9-3x=0$.`, ws: "2.0cm", challenge: true },
  ],
  answers: [r`$x=9$.`, r`$x=5$.`, r`$x=-5$.`, r`$x=8$.`, r`$x=12$.`, r`$x=5$.`, r`$x=5$.`, r`$x=10$.`, r`$x=-3$.`, r`$x=-3$.`, r`$2d+3=15\Rightarrow d=6$ km.`, r`$x=20$.`, r`$x=3$.`],
},
{
  code: "1.4", unit: U, title: r`Solving Multi-Step Equations`,
  intro: r`Expand, collect, gather the variable on one side, then isolate it.`,
  ideas: [
    r`Expand any brackets first.`,
    r`Collect like terms on each side.`,
    r`Move the variable to one side, numbers to the other.`,
    r`Divide to isolate the variable, then check.`,
  ],
  examples: [
    { t: "Variables both sides", body: r`Solve $2x+3=x+8$.\soln Subtract $x$: $x+3=8$, so $x=5$.` },
    { t: "Brackets", body: r`Solve $3(x-2)=12$.\soln $3x-6=12$, $3x=18$, $x=6$.` },
    { t: "Both sides + collect", body: r`Solve $4x-7=2x+5$.\soln $2x=12$, $x=6$.` },
    { t: "A fraction", body: r`Solve $\dfrac{x}{3}-2=4$.\soln $\dfrac{x}{3}=6$, $x=18$.` },
    { t: "Brackets both sides", body: r`Solve $2(x+1)=3(x-2)$.\soln $2x+2=3x-6$, $8=x$.` },
    { t: "Collect first", body: r`Solve $5x-3=2x+9$.\soln $3x=12$, $x=4$.` },
    { t: "Expand then solve", body: r`Solve $2(x+4)=14$.\soln $2x+8=14$, $x=3$.` },
    { t: "Both sides", body: r`Solve $6x-5=4x+7$.\soln $2x=12$, $x=6$.` },
    { t: "Brackets both sides (harder)", body: r`Solve $3(x-1)=2(x+4)$.\soln $3x-3=2x+8$, $x=11$.` },
  ],
  questions: [
    { ask: r`Solve $3x+2=x+10$.`, ws: "2.2cm" },
    { ask: r`Solve $2(x-3)=8$.`, ws: "2.0cm" },
    { ask: r`Solve $5x-4=3x+6$.`, ws: "2.2cm" },
    { ask: r`Solve $\dfrac{x}{2}+3=7$.`, ws: "2.0cm" },
    { ask: r`Solve $3(x+1)=2x+9$.`, ws: "2.2cm" },
    { ask: r`Solve $7x-2=4x+13$.`, ws: "2.2cm" },
    { ask: r`Solve $4(x-2)=12$.`, ws: "2.0cm" },
    { ask: r`Solve $2x+9=5x-3$.`, ws: "2.2cm" },
    { ask: r`Solve $\dfrac{x}{4}-1=2$.`, ws: "2.0cm" },
    { ask: r`Solve $5(x-1)=3(x+3)$.`, ws: "2.4cm" },
    { ask: r`One number is $x$, another is $2x-5$; together they are $40$. Find $x$.`, ws: "2.4cm" },
    { ask: r`Solve $2(2x+1)=3(x+4)$.`, ws: "2.4cm" },
    { ask: r`Solve $4(x+2)-3=2(x+7)$.`, ws: "2.6cm", challenge: true },
  ],
  answers: [r`$2x=8\Rightarrow x=4$.`, r`$2x-6=8\Rightarrow x=7$.`, r`$2x=10\Rightarrow x=5$.`, r`$x=8$.`, r`$3x+3=2x+9\Rightarrow x=6$.`, r`$3x=15\Rightarrow x=5$.`, r`$4x-8=12\Rightarrow x=5$.`, r`$12=3x\Rightarrow x=4$.`, r`$\dfrac{x}{4}=3\Rightarrow x=12$.`, r`$5x-5=3x+9\Rightarrow x=7$.`, r`$3x-5=40\Rightarrow x=15$.`, r`$4x+2=3x+12\Rightarrow x=10$.`, r`$4x+5=2x+14\Rightarrow x=4.5$.`],
},
{
  code: "1.5", unit: U, title: "Rearranging Formulas",
  intro: r`Solve a formula for any of its variables using inverse operations.`,
  ideas: [
    r`Treat the wanted variable as the unknown; isolate it.`,
    r`Do the same operation to both sides.`,
    r`Undo the outermost operation on the target variable first.`,
    r`The answer is often a fraction — that's fine.`,
  ],
  examples: [
    { t: "Area of a rectangle", body: r`Solve $A=lw$ for $w$.\soln Divide by $l$: $w=\dfrac{A}{l}$.` },
    { t: "Perimeter", body: r`Solve $P=2(l+w)$ for $w$.\soln $\dfrac{P}{2}=l+w$, so $w=\dfrac{P}{2}-l$.` },
    { t: "Circumference", body: r`Solve $C=2\pi r$ for $r$.\soln $r=\dfrac{C}{2\pi}$.` },
    { t: "Distance", body: r`Solve $d=vt$ for $t$.\soln $t=\dfrac{d}{v}$.` },
    { t: "Line equation", body: r`Solve $y=mx+b$ for $x$.\soln $y-b=mx$, so $x=\dfrac{y-b}{m}$.` },
    { t: "Triangle area", body: r`Solve $A=\tfrac12 bh$ for $h$.\soln Multiply by $2$, divide by $b$: $h=\dfrac{2A}{b}$.` },
    { t: "Square perimeter", body: r`Solve $P=4s$ for $s$.\soln $s=\dfrac{P}{4}$.` },
    { t: "Force", body: r`Solve $F=ma$ for $a$.\soln $a=\dfrac{F}{m}$.` },
    { t: "Motion (harder)", body: r`Solve $v=u+at$ for $t$.\soln $v-u=at$, so $t=\dfrac{v-u}{a}$.` },
  ],
  questions: [
    { ask: r`Solve $A=lw$ for $l$.`, ws: "2.0cm" },
    { ask: r`Solve $d=vt$ for $v$.`, ws: "2.0cm" },
    { ask: r`Solve $P=4s$ for $s$.`, ws: "1.8cm" },
    { ask: r`Solve $y=mx+b$ for $b$.`, ws: "2.0cm" },
    { ask: r`Solve $A=\tfrac12 bh$ for $b$.`, ws: "2.2cm" },
    { ask: r`Solve $C=2\pi r$ for $r$.`, ws: "2.0cm" },
    { ask: r`Solve $P=2(l+w)$ for $l$.`, ws: "2.4cm" },
    { ask: r`Solve $F=ma$ for $m$.`, ws: "2.0cm" },
    { ask: r`Solve $V=lwh$ for $h$.`, ws: "2.0cm" },
    { ask: r`Solve $y=mx+b$ for $m$.`, ws: "2.0cm" },
    { ask: r`For $A=\tfrac12 bh$, find $h$ when $A=24$ and $b=6$.`, ws: "2.4cm" },
    { ask: r`Solve $2x+3y=12$ for $y$.`, ws: "2.2cm" },
    { ask: r`Solve $v=u+at$ for $a$.`, ws: "2.4cm", challenge: true },
  ],
  answers: [r`$l=\dfrac{A}{w}$.`, r`$v=\dfrac{d}{t}$.`, r`$s=\dfrac{P}{4}$.`, r`$b=y-mx$.`, r`$b=\dfrac{2A}{h}$.`, r`$r=\dfrac{C}{2\pi}$.`, r`$l=\dfrac{P}{2}-w$.`, r`$m=\dfrac{F}{a}$.`, r`$h=\dfrac{V}{lw}$.`, r`$m=\dfrac{y-b}{x}$.`, r`$h=\dfrac{2(24)}{6}=8$.`, r`$y=\dfrac{12-2x}{3}$.`, r`$a=\dfrac{v-u}{t}$.`],
},
{
  code: "1.6", unit: U, title: "Modelling with Equations",
  intro: r`Turn a situation into an equation, solve it, and answer in context.`,
  ideas: [
    r`Define a variable for the unknown.`,
    r`Write an equation from the words.`,
    r`Solve it, then answer in a sentence and check.`,
    r`Cost models are linear: $C=(\text{rate})x+(\text{fixed fee})$.`,
  ],
  examples: [
    { t: "Number problem", body: r`Five more than twice a number is $17$. Find it.\soln $2x+5=17\Rightarrow x=6$.` },
    { t: "Perimeter", body: r`A rectangle's length is $3$ m more than its width; perimeter $26$ m. Find the width.\soln $2(w+3)+2w=26\Rightarrow w=5$ m.` },
    { t: "Cost model", body: r`A plumber charges $50$ dollars plus $40$ dollars/hour. How long is a $210$-dollar job?\soln $40x+50=210\Rightarrow x=4$ h.` },
    { t: "Consecutive integers", body: r`Three consecutive integers sum to $48$. Find them.\soln $3x+3=48\Rightarrow x=15$: $15,16,17$.` },
    { t: "Comparing plans", body: r`Plan A: $5$ dollars/visit. Plan B: $3$ dollars/visit plus $4$ dollars. When equal?\soln $5x=3x+4\Rightarrow x=2$ visits.` },
    { t: "Less than", body: r`Seven less than three times a number is $11$. Find it.\soln $3x-7=11\Rightarrow x=6$.` },
    { t: "Taxi", body: r`A taxi charges $3$ dollars plus $2$ dollars/km. What distance costs $15$ dollars?\soln $2d+3=15\Rightarrow d=6$ km.` },
    { t: "Rectangle (length twice width)", body: r`Length is twice the width; perimeter $36$. Find the dimensions.\soln $2(2w)+2w=36\Rightarrow w=6$, length $12$.` },
    { t: "Two gyms (harder)", body: r`Gym A: $8$ dollars/visit. Gym B: $5$ dollars/visit plus $12$ dollars. When equal?\soln $8x=5x+12\Rightarrow x=4$ visits.` },
  ],
  questions: [
    { ask: r`Four more than triple a number is $19$. Find the number.`, ws: "2.2cm" },
    { ask: r`Two consecutive integers sum to $35$. Find them.`, ws: "2.2cm" },
    { ask: r`A taxi charges $4$ dollars plus $2$ dollars/km. What distance costs $20$ dollars?`, ws: "2.4cm" },
    { ask: r`A rectangle's length is $5$ more than its width; perimeter $34$. Find the width.`, ws: "2.4cm" },
    { ask: r`A printer costs $60$ dollars plus $0.10$ dollars/page. How many pages cost $80$ dollars?`, ws: "2.4cm" },
    { ask: r`A number doubled then increased by $7$ is $25$. Find it.`, ws: "2.2cm" },
    { ask: r`Three consecutive integers sum to $72$. Find them.`, ws: "2.4cm" },
    { ask: r`Gym A: $6$ dollars/visit. Gym B: $4$ dollars/visit plus $10$ dollars. When equal?`, ws: "2.4cm" },
    { ask: r`A rectangle's length is three times its width; perimeter $32$. Find the dimensions.`, ws: "2.4cm" },
    { ask: r`Seven more than half a number is $12$. Find the number.`, ws: "2.2cm" },
    { ask: r`A phone plan is $15$ dollars plus $0.05$ dollars/min. How many minutes cost $20$ dollars?`, ws: "2.4cm" },
    { ask: r`Two numbers: one is $x$, the other $3x$; together $48$. Find both.`, ws: "2.4cm" },
    { ask: r`A plumber charges $45$ dollars plus $35$ dollars/hour. How long is a $220$-dollar job?`, ws: "2.6cm", challenge: true },
  ],
  answers: [r`$3x+4=19\Rightarrow x=5$.`, r`$2x+1=35\Rightarrow 17,18$.`, r`$2d+4=20\Rightarrow d=8$ km.`, r`$2(w+5)+2w=34\Rightarrow w=6$.`, r`$0.10p+60=80\Rightarrow p=200$.`, r`$2x+7=25\Rightarrow x=9$.`, r`$3x+3=72\Rightarrow 23,24,25$.`, r`$6x=4x+10\Rightarrow x=5$.`, r`$8w=32\Rightarrow w=4$, length $12$.`, r`$\tfrac{x}{2}+7=12\Rightarrow x=10$.`, r`$0.05m+15=20\Rightarrow m=100$.`, r`$4x=48\Rightarrow x=12$: $12$ and $36$.`, r`$35h+45=220\Rightarrow h=5$.`],
},
];
