// MFM2P Unit 2 — Linear Relations worksheets (2.1–2.6).
const r = String.raw;
const U = "2: Linear Relations";

export default [
{
  code: "2.1", unit: U, title: r`Rate of Change \& Slope`,
  intro: r`Slope measures a constant rate of change: $m=\dfrac{\text{rise}}{\text{run}}=\dfrac{y_2-y_1}{x_2-x_1}$.`,
  ideas: [
    r`Subtract the $y$'s over the $x$'s, in the same order.`,
    r`Positive rises, negative falls, $0$ is horizontal, vertical is undefined.`,
    r`From a table with even $x$-steps: $m=\dfrac{\Delta y}{\Delta x}$.`,
    r`Slope has units in context (e.g. cm/hour).`,
  ],
  examples: [
    { t: "Slope from two points", body: r`Find the slope through $(1,2)$ and $(4,8)$.\soln $m=\dfrac{8-2}{4-1}=2$.
\plot{-1}{6}{-1}{10}{\addplot[exblue,very thick,domain=-0.5:5,samples=2]{2*x};\addplot[mark=*,only marks,black]coordinates{(1,2)(4,8)};}` },
    { t: "Negative slope", body: r`Find the slope through $(-2,5)$ and $(2,-3)$.\soln $m=\dfrac{-3-5}{2-(-2)}=\dfrac{-8}{4}=-2$.` },
    { t: "From a table", body: r`$x:0,1,2,3$, $y:1,4,7,10$. Find the rate of change.\soln Each $\Delta x=1$ gives $\Delta y=3$, so $m=3$.` },
    { t: "Horizontal line", body: r`Find the slope through $(1,4)$ and $(5,4)$.\soln $m=\dfrac{0}{4}=0$ (horizontal).` },
    { t: "A rate in context", body: r`A candle burns from $20$ cm to $8$ cm in $4$ h. Find the rate.\soln $\dfrac{8-20}{4}=-3$ cm/h.` },
    { t: "Through the origin", body: r`Find the slope through $(0,1)$ and $(3,7)$.\soln $m=\dfrac{7-1}{3-0}=2$.
\plot{-1}{5}{-1}{9}{\addplot[exblue,very thick,domain=-0.5:4,samples=2]{2*x+1};\addplot[mark=*,only marks,black]coordinates{(0,1)(3,7)};}` },
    { t: "Vertical line", body: r`Find the slope through $(3,2)$ and $(3,9)$.\soln Run $=0$, so the slope is undefined.` },
    { t: "Filling a pool", body: r`A pool fills from $30$ L to $150$ L in $8$ min. Find the rate.\soln $\dfrac{150-30}{8}=15$ L/min.` },
    { t: "Fractional slope (harder)", body: r`Find the slope through $(-4,3)$ and $(2,0)$.\soln $m=\dfrac{0-3}{2-(-4)}=\dfrac{-3}{6}=-\tfrac12$.
\plot{-5}{4}{-2}{5}{\addplot[exblue,very thick,domain=-5:4,samples=2]{-0.5*x+1};\addplot[mark=*,only marks,black]coordinates{(-4,3)(2,0)};}` },
  ],
  questions: [
    { ask: r`Slope through $(0,1)$ and $(3,7)$.`, ws: "2.0cm" },
    { ask: r`Slope through $(2,5)$ and $(6,1)$.`, ws: "2.0cm" },
    { ask: r`From the table $x:0,1,2$, $y:5,8,11$, find the slope.`, ws: "2.0cm" },
    { ask: r`Slope through $(3,2)$ and $(3,9)$.`, ws: "2.0cm" },
    { ask: r`Slope through $(-1,-1)$ and $(2,5)$.`, ws: "2.0cm" },
    { ask: r`Slope through $(1,4)$ and $(6,4)$.`, ws: "1.8cm" },
    { ask: r`A car travels $240$ km in $3$ h. Find the rate (with units).`, ws: "2.2cm" },
    { ask: r`Slope through $(-2,1)$ and $(4,-2)$.`, ws: "2.2cm" },
    { ask: r`From $x:0,2,4$, $y:1,7,13$, find the rate of change.`, ws: "2.0cm" },
    { ask: r`A tank drains from $100$ L to $20$ L in $4$ min. Find the rate.`, ws: "2.2cm" },
    { ask: r`Slope through $(0,0)$ and $(5,2)$.`, ws: "2.0cm" },
    { ask: r`Slope through $(-3,4)$ and $(1,-4)$.`, ws: "2.2cm" },
    { ask: r`A pool fills $30$ L to $150$ L in $8$ min. Find the rate.`, ws: "2.4cm", challenge: true },
  ],
  answers: [r`$2$.`, r`$\dfrac{1-5}{6-2}=-1$.`, r`$3$.`, r`undefined (vertical).`, r`$\dfrac{6}{3}=2$.`, r`$0$.`, r`$80$ km/h.`, r`$\dfrac{-3}{6}=-\tfrac12$.`, r`$3$.`, r`$-20$ L/min.`, r`$\tfrac25$.`, r`$\dfrac{-8}{4}=-2$.`, r`$15$ L/min.`],
},
{
  code: "2.2", unit: U, title: r`Direct \& Partial Variation`,
  intro: r`Direct variation $y=kx$ passes through the origin; partial variation $y=mx+b$ has a starting value.`,
  ideas: [
    r`Direct: $y=kx$, constant of variation $k=\dfrac{y}{x}$, graph through $(0,0)$.`,
    r`Partial: $y=mx+b$, initial value $b$ plus rate $m$.`,
    r`A fixed fee plus a per-unit rate is partial variation.`,
    r`Find $k$ from one point; find a partial model from the fixed value and rate.`,
  ],
  examples: [
    { t: "Identify (direct)", body: r`Is $y=4x$ direct or partial?\soln No constant term $\Rightarrow$ direct, $k=4$.` },
    { t: "Identify (partial)", body: r`Is $y=3x+5$ direct or partial?\soln Starting value $5\neq0\Rightarrow$ partial.
\plot{-3}{3}{-2}{12}{\addplot[exblue,very thick,domain=-3:2.3,samples=2]{3*x+5};\addplot[mark=*,only marks,black]coordinates{(0,5)};}` },
    { t: "Find k", body: r`$y$ varies directly with $x$; $y=12$ when $x=3$. Find $k$ and the equation.\soln $k=\dfrac{12}{3}=4$, so $y=4x$.` },
    { t: "Write a partial model", body: r`A gym charges $20$ dollars to join plus $5$ dollars/visit. Write the equation.\soln $C=5v+20$.` },
    { t: "Direct vs partial graph", body: r`Compare $y=2x$ and $y=x+10$ at $x=5$.\soln $2(5)=10$ vs $5+10=15$ — direct is cheaper here.
\plot{-1}{12}{-1}{22}{\addplot[exblue,very thick,domain=0:11,samples=2]{2*x};\addplot[qorange,very thick,domain=0:11,samples=2]{x+10};\addplot[mark=*,only marks,black]coordinates{(10,20)};}` },
    { t: "Cost as direct variation", body: r`Cost varies directly with litres: $25$ dollars for $10$ L. Find the cost of $16$ L.\soln $k=2.5$; $C=2.5(16)=40$ dollars.` },
    { t: "Read a partial model", body: r`For $C=4n+8$, state the fixed cost and the rate.\soln Fixed $8$, rate $4$ per unit.` },
    { t: "Through the origin?", body: r`Does $y=2x-1$ pass through the origin?\soln At $x=0$, $y=-1\neq0$ — no (partial).` },
    { t: "Build and use (harder)", body: r`A printer costs $60$ dollars plus $0.10$ dollars/page. Find the cost of $300$ pages.\soln $C=0.10(300)+60=90$ dollars.` },
  ],
  questions: [
    { ask: r`Is $y=7x$ direct or partial?`, ws: "1.8cm" },
    { ask: r`Is $y=2x-1$ direct or partial?`, ws: "1.8cm" },
    { ask: r`$y$ varies directly with $x$; $y=20$ at $x=4$. Find $k$.`, ws: "2.0cm" },
    { ask: r`A printer costs $60$ dollars plus $0.10$ dollars/page. Write the equation.`, ws: "2.2cm" },
    { ask: r`For $C=4n+8$, find $C$ at $n=6$.`, ws: "2.0cm" },
    { ask: r`Write the equation: direct variation with $k=3$.`, ws: "1.8cm" },
    { ask: r`A gym: $15$ dollars join plus $4$ dollars/visit. Write the model.`, ws: "2.0cm" },
    { ask: r`$y$ varies directly with $x$; $y=18$ at $x=6$. Write the equation.`, ws: "2.0cm" },
    { ask: r`State the fixed cost and rate for $C=2.5x+12$.`, ws: "2.0cm" },
    { ask: r`Cost varies directly with mass: $9$ dollars for $3$ kg. Find the cost of $7$ kg.`, ws: "2.2cm" },
    { ask: r`Is the graph of $y=5x$ through the origin? Explain.`, ws: "2.0cm" },
    { ask: r`A taxi: $3$ dollars plus $2$ dollars/km. Find the cost of $8$ km.`, ws: "2.2cm" },
    { ask: r`Compare $C=3x$ and $C=2x+6$: find where they cost the same.`, ws: "2.4cm", challenge: true },
  ],
  answers: [r`direct ($k=7$).`, r`partial (initial $-1$).`, r`$k=5$.`, r`$C=0.10p+60$.`, r`$C=32$ dollars.`, r`$y=3x$.`, r`$C=4v+15$.`, r`$y=3x$.`, r`fixed $12$, rate $2.5$.`, r`$k=3$; $C=21$ dollars.`, r`Yes — no constant term, so it passes through $(0,0)$.`, r`$C=19$ dollars.`, r`$3x=2x+6\Rightarrow x=6$.`],
},
{
  code: "2.3", unit: U, title: "Slope-Intercept Form (y = mx + b)",
  intro: r`In $y=mx+b$, $m$ is the slope and $b$ is the $y$-intercept — read them straight off.`,
  ideas: [
    r`$m$ = steepness/direction; $b$ = where the line crosses the $y$-axis.`,
    r`To write a line, place the slope as $m$ and the intercept as $b$.`,
    r`From standard form, isolate $y$ (divide every term).`,
    r`In context, $m$ is the rate and $b$ is the fixed/initial value.`,
  ],
  examples: [
    { t: "Read m and b", body: r`State the slope and $y$-intercept of $y=-3x+5$.\soln $m=-3$, $b=5$.` },
    { t: "Build from words", body: r`Slope $4$, $y$-intercept $-2$. Write the equation.\soln $y=4x-2$.` },
    { t: "From standard form", body: r`Write $2x+y=5$ as $y=mx+b$.\soln $y=-2x+5$ (slope $-2$, $b=5$).
\plot{-2}{5}{-3}{7}{\addplot[exblue,very thick,domain=-0.5:4,samples=2]{-2*x+5};\addplot[mark=*,only marks,black]coordinates{(0,5)};}` },
    { t: "Divide to isolate y", body: r`Write $4x-2y=6$ as $y=mx+b$.\soln $-2y=-4x+6$, so $y=2x-3$.` },
    { t: "Interpret in context", body: r`A plan is $C=0.10t+15$. What do $0.10$ and $15$ mean?\soln $0.10$ = cost per minute; $15$ = fixed monthly fee.` },
    { t: "Negative intercept", body: r`Write the line with slope $\tfrac12$ and $y$-intercept $-4$.\soln $y=\tfrac12x-4$.` },
    { t: "From standard (divide)", body: r`Write $6x-3y=9$ as $y=mx+b$.\soln $-3y=-6x+9$, so $y=2x-3$.` },
    { t: "Find y at a value", body: r`For $y=2x-4$, find $y$ at $x=3$.\soln $y=2(3)-4=2$.` },
    { t: "Read a graph (harder)", body: r`A line crosses $(0,4)$ and falls $1$ for every $2$ across. Write it.\soln $m=-\tfrac12$, $b=4$: $y=-\tfrac12x+4$.
\plot{-2}{8}{-2}{6}{\addplot[exblue,very thick,domain=-1:8,samples=2]{-0.5*x+4};\addplot[mark=*,only marks,black]coordinates{(0,4)(8,0)};}` },
  ],
  questions: [
    { ask: r`Slope and $y$-intercept of $y=5x-1$.`, ws: "1.8cm" },
    { ask: r`Write the line with slope $-2$, $y$-intercept $3$.`, ws: "1.8cm" },
    { ask: r`Write $3x+y=7$ as $y=mx+b$.`, ws: "2.0cm" },
    { ask: r`Write $6x-3y=9$ as $y=mx+b$.`, ws: "2.0cm" },
    { ask: r`Slope and $y$-intercept of $y=-x+6$.`, ws: "1.8cm" },
    { ask: r`Write the line with slope $\tfrac13$, $y$-intercept $-2$.`, ws: "1.8cm" },
    { ask: r`Write $4x-2y=8$ as $y=mx+b$.`, ws: "2.0cm" },
    { ask: r`For $y=3x-5$, find $y$ at $x=4$.`, ws: "2.0cm" },
    { ask: r`A plan is $C=0.05t+20$. State the rate and fixed fee.`, ws: "2.0cm" },
    { ask: r`Write the line with slope $0$, $y$-intercept $5$.`, ws: "1.8cm" },
    { ask: r`Write $x+2y=6$ as $y=mx+b$.`, ws: "2.0cm" },
    { ask: r`A line has slope $2$ through $(0,-4)$; write it and find $y$ at $x=3$.`, ws: "2.4cm" },
    { ask: r`Write $5x-2y=10$ as $y=mx+b$.`, ws: "2.2cm", challenge: true },
  ],
  answers: [r`$m=5$, $b=-1$.`, r`$y=-2x+3$.`, r`$y=-3x+7$.`, r`$y=2x-3$.`, r`$m=-1$, $b=6$.`, r`$y=\tfrac13x-2$.`, r`$y=2x-4$.`, r`$y=7$.`, r`rate $0.05$/min, fixed $20$.`, r`$y=5$.`, r`$y=-\tfrac12x+3$.`, r`$y=2x-4$; at $x=3$, $y=2$.`, r`$y=\tfrac52x-5$.`],
},
{
  code: "2.4", unit: U, title: "Graphing Lines",
  intro: r`Graph from $y=mx+b$ (plot $b$, step the slope) or from intercepts.`,
  ideas: [
    r`From $y=mx+b$: plot $(0,b)$, then step $\dfrac{\text{rise}}{\text{run}}$.`,
    r`From $Ax+By=C$: find both intercepts and join them.`,
    r`Horizontal $y=k$; vertical $x=a$.`,
    r`Two points are enough to draw a line.`,
  ],
  examples: [
    { t: "From slope-intercept", body: r`Graph $y=2x-3$.\soln Start at $(0,-3)$, up $2$/right $1$.
\plot{-2}{5}{-5}{6}{\addplot[exblue,very thick,domain=-0.5:4,samples=2]{2*x-3};\addplot[mark=*,only marks,black]coordinates{(0,-3)(1,-1)};}` },
    { t: "Negative slope", body: r`Graph $y=-x+4$.\soln Start at $(0,4)$, down $1$/right $1$.
\plot{-2}{6}{-2}{6}{\addplot[exblue,very thick,domain=-1:5,samples=2]{-x+4};\addplot[mark=*,only marks,black]coordinates{(0,4)(4,0)};}` },
    { t: "Using intercepts", body: r`Graph $2x+3y=6$.\soln $x=0\Rightarrow y=2$; $y=0\Rightarrow x=3$.
\plot{-2}{5}{-2}{4}{\addplot[exblue,very thick,domain=-0.5:4,samples=2]{-2/3*x+2};\addplot[mark=*,only marks,black]coordinates{(0,2)(3,0)};}` },
    { t: r`Horizontal \& vertical`, body: r`Describe $y=3$ and $x=-2$.\soln $y=3$ is horizontal; $x=-2$ is vertical.` },
    { t: "Fractional slope", body: r`Graph $y=\tfrac23x-1$.\soln Start at $(0,-1)$, up $2$/right $3$.` },
    { t: "From a table", body: r`Graph the line through $(0,1)$ and $(2,5)$.\soln Slope $2$, $b=1$: $y=2x+1$.` },
    { t: "Intercepts of standard form", body: r`Find the intercepts of $3x-4y=12$.\soln $(4,0)$ and $(0,-3)$.` },
    { t: "Negative intercept", body: r`Graph $y=-2x+1$.\soln Start at $(0,1)$, down $2$/right $1$.` },
    { t: "Both intercepts (harder)", body: r`Graph $x-2y=4$ using intercepts.\soln $(4,0)$ and $(0,-2)$.
\plot{-2}{6}{-4}{3}{\addplot[exblue,very thick,domain=-1:6,samples=2]{0.5*x-2};\addplot[mark=*,only marks,black]coordinates{(4,0)(0,-2)};}` },
  ],
  questions: [
    { ask: r`Graph $y=x+2$.`, grid: true },
    { ask: r`Graph $y=-2x+1$.`, grid: true },
    { ask: r`Find the intercepts of $x+2y=4$.`, ws: "2.0cm" },
    { ask: r`Graph $y=\tfrac12x-1$.`, grid: true },
    { ask: r`What kind of line is $y=-1$?`, ws: "1.8cm" },
    { ask: r`Graph $2x+y=4$.`, grid: true },
    { ask: r`Find the intercepts of $3x-4y=12$.`, ws: "2.0cm" },
    { ask: r`Graph $y=-x+3$.`, grid: true },
    { ask: r`Name two points on $y=3x-2$.`, ws: "2.0cm" },
    { ask: r`What kind of line is $x=4$?`, ws: "1.8cm" },
    { ask: r`Graph the line through $(0,-2)$ and $(3,1)$.`, grid: true },
    { ask: r`Find the intercepts of $2x+5y=10$.`, ws: "2.0cm" },
    { ask: r`Graph $3x-2y=6$ using intercepts.`, grid: true, challenge: true },
  ],
  answers: [r`$(0,2),(1,3)$.`, r`$(0,1),(1,-1)$.`, r`$(0,2),(4,0)$.`, r`$(0,-1),(2,0)$.`, r`horizontal.`, r`$(0,4),(2,0)$.`, r`$(4,0),(0,-3)$.`, r`$(0,3),(3,0)$.`, r`$(0,-2),(1,1)$.`, r`vertical.`, r`slope $1$: $y=x-2$.`, r`$(5,0),(0,2)$.`, r`$(2,0),(0,-3)$.`],
},
{
  code: "2.5", unit: U, title: "Writing Equations of Lines",
  intro: r`From a slope and a point, two points, or a graph, write $y=mx+b$.`,
  ideas: [
    r`From slope + point: substitute into $y=mx+b$ to find $b$.`,
    r`From two points: find the slope first, then $b$.`,
    r`If the point is on the $y$-axis, its $y$ is $b$.`,
    r`Check: both given points should satisfy your equation.`,
  ],
  examples: [
    { t: "Slope + intercept point", body: r`Slope $4$ through $(0,-2)$.\soln $b=-2$: $y=4x-2$.` },
    { t: "Slope + point", body: r`Slope $-2$ through $(3,1)$.\soln $1=-2(3)+b\Rightarrow b=7$: $y=-2x+7$.
\plot{-1}{6}{-3}{8}{\addplot[exblue,very thick,domain=-0.5:5.5,samples=2]{-2*x+7};\addplot[mark=*,only marks,black]coordinates{(3,1)};}` },
    { t: "Two points", body: r`Through $(1,2)$ and $(3,8)$.\soln $m=3$; $2=3+b\Rightarrow b=-1$: $y=3x-1$.` },
    { t: "From a graph", body: r`A line crosses $(0,4)$ and falls $1$ per $2$ across.\soln $m=-\tfrac12$, $b=4$: $y=-\tfrac12x+4$.` },
    { t: "Context model", body: r`A candle is $20$ cm and burns $3$ cm/h. Write $h$ vs $t$.\soln $h=-3t+20$.` },
    { t: "Two points (negative slope)", body: r`Through $(-1,2)$ and $(2,-7)$.\soln $m=\dfrac{-7-2}{2-(-1)}=-3$; $2=-3(-1)+b\Rightarrow b=-1$: $y=-3x-1$.` },
    { t: "Horizontal", body: r`Through $(1,4)$ and $(3,4)$.\soln Slope $0$: $y=4$.` },
    { t: "Slope + point (fraction)", body: r`Slope $\tfrac23$ through $(3,0)$.\soln $0=\tfrac23(3)+b\Rightarrow b=-2$: $y=\tfrac23x-2$.` },
    { t: "Two points (harder)", body: r`Through $(2,5)$ and $(6,13)$.\soln $m=2$; $5=2(2)+b\Rightarrow b=1$: $y=2x+1$.
\plot{-1}{7}{-1}{14}{\addplot[exblue,very thick,domain=-0.5:6.3,samples=2]{2*x+1};\addplot[mark=*,only marks,black]coordinates{(2,5)(6,13)};}` },
  ],
  questions: [
    { ask: r`Slope $3$ through $(0,5)$.`, ws: "1.8cm" },
    { ask: r`Slope $-1$ through $(2,3)$.`, ws: "2.0cm" },
    { ask: r`Through $(0,1)$ and $(2,7)$.`, ws: "2.0cm" },
    { ask: r`Through $(1,4)$ and $(3,4)$.`, ws: "2.0cm" },
    { ask: r`Slope $\tfrac12$ through $(4,1)$.`, ws: "2.0cm" },
    { ask: r`Through $(-2,1)$ and $(2,9)$.`, ws: "2.2cm" },
    { ask: r`Slope $-3$ through $(0,-2)$.`, ws: "1.8cm" },
    { ask: r`Through $(1,-1)$ and $(4,8)$.`, ws: "2.2cm" },
    { ask: r`A tank starts at $50$ L and drains $5$ L/min. Write $V$ vs $t$.`, ws: "2.2cm" },
    { ask: r`Slope $2$ through $(-1,-3)$.`, ws: "2.0cm" },
    { ask: r`Through $(0,-2)$ and $(5,8)$.`, ws: "2.2cm" },
    { ask: r`A candle is $24$ cm, burns $4$ cm/h. Write $h$ vs $t$.`, ws: "2.2cm" },
    { ask: r`Through $(-1,2)$ and $(2,-7)$.`, ws: "2.4cm", challenge: true },
  ],
  answers: [r`$y=3x+5$.`, r`$y=-x+5$.`, r`$y=3x+1$.`, r`$y=4$.`, r`$y=\tfrac12x-1$.`, r`$m=2$: $y=2x+5$.`, r`$y=-3x-2$.`, r`$m=3$: $y=3x-4$.`, r`$V=-5t+50$.`, r`$y=2x-1$.`, r`$m=2$: $y=2x-2$.`, r`$h=-4t+24$.`, r`$y=-3x-1$.`],
},
{
  code: "2.6", unit: U, title: "Interpreting Linear Models",
  intro: r`A line models cost, distance, or volume. Read slope and intercept in context, then predict.`,
  ideas: [
    r`Slope = the rate of change (per-unit amount).`,
    r`Intercept = the starting/fixed value at $x=0$.`,
    r`Predict an output: substitute the input.`,
    r`Predict an input: set the model equal to the output and solve.`,
  ],
  examples: [
    { t: "Read the model", body: r`A pool drains by $V=-20t+500$. What do $-20$ and $500$ mean?\soln Drains $20$ L/min; starts at $500$ L.
\plot{-2}{28}{-50}{550}{\addplot[exblue,very thick,domain=0:25,samples=2]{-20*x+500};\addplot[mark=*,only marks,black]coordinates{(0,500)(25,0)};}` },
    { t: "Predict an output", body: r`For $C=2d+3$, find the cost of a $10$ km trip.\soln $C=2(10)+3=23$ dollars.` },
    { t: "Predict an input", body: r`For $C=2d+3$, how far for $15$ dollars?\soln $2d+3=15\Rightarrow d=6$ km.` },
    { t: "Interpret the intercept", body: r`For $C=0.05t+20$, what is the cost at $0$ minutes?\soln $C=20$ dollars — the fixed fee.` },
    { t: "Compare two models", body: r`Plan A: $C=0.10t+10$; Plan B: $C=0.05t+20$. Cheaper at $100$ min?\soln A: $20$; B: $25$ — Plan A.` },
    { t: "When is it empty?", body: r`For $V=-5t+60$, when is $V=0$?\soln $5t=60\Rightarrow t=12$.` },
    { t: "Rate with units", body: r`A candle: $h=-3t+20$. What does $-3$ mean?\soln It burns $3$ cm per hour.` },
    { t: "Starting value", body: r`For $h=-5t+25$, what is the starting height?\soln At $t=0$, $h=25$.` },
    { t: "Break-even (harder)", body: r`Plan A: $C=0.10t+10$; Plan B: $C=0.05t+20$. When equal?\soln $0.10t+10=0.05t+20\Rightarrow t=200$ min.` },
  ],
  questions: [
    { ask: r`For $C=3h+25$, state the fixed fee and the rate.`, ws: "2.0cm" },
    { ask: r`For $C=3h+25$, find $C$ at $h=4$.`, ws: "2.0cm" },
    { ask: r`For $C=3h+25$, find $h$ when $C=49$.`, ws: "2.0cm" },
    { ask: r`For $V=-5t+60$, what does $-5$ mean?`, ws: "2.0cm" },
    { ask: r`For $V=-5t+60$, when is $V=0$?`, ws: "2.0cm" },
    { ask: r`A taxi $C=2d+5$: find the cost of $12$ km.`, ws: "2.0cm" },
    { ask: r`A taxi $C=2d+5$: how far for $25$ dollars?`, ws: "2.0cm" },
    { ask: r`For $h=-4t+32$, find the starting height.`, ws: "2.0cm" },
    { ask: r`For $h=-4t+32$, when does it reach $0$?`, ws: "2.0cm" },
    { ask: r`Plan A: $0.20t+5$; Plan B: $0.10t+15$. Cheaper at $50$ units?`, ws: "2.2cm" },
    { ask: r`A pool drains $V=-25t+400$: when is it empty?`, ws: "2.2cm" },
    { ask: r`For $C=1.5x+8$, interpret $1.5$ and $8$.`, ws: "2.2cm" },
    { ask: r`Plan A: $0.20t+5$; Plan B: $0.10t+15$. When equal?`, ws: "2.4cm", challenge: true },
  ],
  answers: [r`fixed $25$, rate $3$.`, r`$C=37$ dollars.`, r`$3h=24\Rightarrow h=8$.`, r`decreasing $5$ per unit time.`, r`$t=12$.`, r`$C=29$ dollars.`, r`$2d+5=25\Rightarrow d=10$ km.`, r`$32$.`, r`$4t=32\Rightarrow t=8$.`, r`A: $15$, B: $20$ — Plan A.`, r`$25t=400\Rightarrow t=16$.`, r`rate $1.5$/unit, fixed fee $8$.`, r`$0.20t+5=0.10t+15\Rightarrow t=100$.`],
},
];
