// MFM2P Unit 4 — Measurement worksheets (4.1–4.6).
const r = String.raw;
const U = "4: Measurement";

export default [
{
  code: "4.1", unit: U, title: r`Measurement Systems \& Unit Conversion`,
  intro: r`Applied math uses metric (powers of ten) and imperial units; convert within and between them.`,
  ideas: [
    r`Metric: $1$ m $=100$ cm, $1$ km $=1000$ m, $1$ L $=1000$ mL.`,
    r`Imperial: $1$ ft $=12$ in, $1$ yd $=3$ ft, $1$ lb $=16$ oz.`,
    r`Between: $1$ in $=2.54$ cm, $1$ mile $\approx1.6$ km, $1$ kg $\approx2.2$ lb.`,
    r`Going to a larger unit, divide; to a smaller unit, multiply.`,
  ],
  examples: [
    { t: "Metre to cm", body: r`Convert $3.5$ m to cm.\soln $3.5\times100=350$ cm.` },
    { t: "mL to L", body: r`Convert $2500$ mL to L.\soln $2500\div1000=2.5$ L.` },
    { t: "Feet to inches", body: r`Convert $5$ ft to inches.\soln $5\times12=60$ in.` },
    { t: "Inches to cm", body: r`Convert $10$ in to cm.\soln $10\times2.54=25.4$ cm.` },
    { t: "km to miles", body: r`Convert $8$ km to miles.\soln $8\div1.6=5$ miles.` },
    { t: "km to m", body: r`Convert $4.2$ km to m.\soln $4.2\times1000=4200$ m.` },
    { t: "Yards to feet", body: r`Convert $3$ yd to feet.\soln $3\times3=9$ ft.` },
    { t: "kg to pounds", body: r`Convert $5$ kg to pounds.\soln $5\times2.2=11$ lb.` },
    { t: "Miles to km (harder)", body: r`Convert $12$ miles to km.\soln $12\times1.6=19.2$ km.` },
  ],
  questions: [
    { ask: r`Convert $2.7$ m to cm.`, ws: "1.8cm" },
    { ask: r`Convert $3500$ mL to L.`, ws: "1.8cm" },
    { ask: r`Convert $4$ ft to inches.`, ws: "1.8cm" },
    { ask: r`Convert $6$ in to cm.`, ws: "1.8cm" },
    { ask: r`Convert $16$ km to miles.`, ws: "1.8cm" },
    { ask: r`Convert $5.5$ km to m.`, ws: "1.8cm" },
    { ask: r`Convert $4$ yd to feet.`, ws: "1.8cm" },
    { ask: r`Convert $10$ kg to pounds.`, ws: "1.8cm" },
    { ask: r`Convert $250$ cm to m.`, ws: "1.8cm" },
    { ask: r`Convert $3$ L to mL.`, ws: "1.8cm" },
    { ask: r`A board is $8$ ft long; convert to inches.`, ws: "2.0cm" },
    { ask: r`A road is $20$ miles; about how many km?`, ws: "2.0cm" },
    { ask: r`A recipe needs $3$ cups; about how many mL (1 cup $\approx250$ mL)?`, ws: "2.2cm", challenge: true },
  ],
  answers: [r`$270$ cm.`, r`$3.5$ L.`, r`$48$ in.`, r`$15.24$ cm.`, r`$10$ miles.`, r`$5500$ m.`, r`$12$ ft.`, r`$22$ lb.`, r`$2.5$ m.`, r`$3000$ mL.`, r`$96$ in.`, r`$\approx32$ km.`, r`$\approx750$ mL.`],
},
{
  code: "4.2", unit: U, title: r`Surface Area of Prisms \& Cylinders`,
  intro: r`Surface area is the total area of all faces.`,
  ideas: [
    r`Rectangular prism: $SA=2(lw+lh+wh)$.`,
    r`Cylinder: $SA=2\pi r^2+2\pi rh$ (two circles + the wrap).`,
    r`Triangular prism: $SA=(\text{perimeter})\times\text{length}+2\times\text{triangle area}$.`,
    r`Use the radius (not the diameter); area units are squared.`,
  ],
  examples: [
    { t: "Rectangular prism", body: r`$SA$ of a $4\times3\times2$ box.\soln $2(12+8+6)=52$ units$^2$.` },
    { t: "Cube", body: r`$SA$ of a cube, side $5$.\soln $6\times25=150$ units$^2$.` },
    { t: "Cylinder", body: r`$SA$ of a cylinder $r=3,\ h=10$.\soln $2\pi(9)+2\pi(3)(10)=78\pi\approx245.0$.` },
    { t: "Triangular prism", body: r`Triangle legs $3,4$ (hyp $5$), length $10$.\soln Lateral $(3+4+5)(10)=120$; ends $2(\tfrac12\cdot3\cdot4)=12$. Total $132$.` },
    { t: "Open-top box", body: r`$SA$ of a $4\times4\times3$ box with no top.\soln Base $16$ + $4$ sides $4(12)=48$. Total $64$.` },
    { t: "Smaller cube", body: r`$SA$ of a cube, side $4$.\soln $6\times16=96$ units$^2$.` },
    { t: "Cylinder (exact)", body: r`$SA$ of a cylinder $r=2,\ h=5$.\soln $8\pi+20\pi=28\pi\approx88.0$.` },
    { t: "Lateral area", body: r`Lateral area of a cylinder $r=3,\ h=7$.\soln $2\pi(3)(7)=42\pi$.` },
    { t: "Triangular prism (harder)", body: r`Triangle base $6$, height $4$ (equal sides $5$), length $12$.\soln Lateral $(6+5+5)(12)=192$; ends $2(\tfrac12\cdot6\cdot4)=24$. Total $216$.` },
  ],
  questions: [
    { ask: r`$SA$ of a $5\times2\times3$ prism.`, ws: "2.0cm" },
    { ask: r`$SA$ of a cube, side $4$.`, ws: "1.8cm" },
    { ask: r`$SA$ of a cylinder $r=2,\ h=5$ (exact).`, ws: "2.2cm" },
    { ask: r`Lateral area of a cylinder $r=3,\ h=7$ (exact).`, ws: "2.0cm" },
    { ask: r`$SA$ of a $6\times4\times2$ box.`, ws: "2.0cm" },
    { ask: r`$SA$ of a cube, side $6$.`, ws: "1.8cm" },
    { ask: r`$SA$ of a cylinder $r=5,\ h=4$ (1 dp).`, ws: "2.2cm" },
    { ask: r`$SA$ of a triangular prism: triangle legs $3,4$, length $8$.`, ws: "2.4cm" },
    { ask: r`A can has $r=4$ cm, $h=12$ cm; find the label (lateral) area (1 dp).`, ws: "2.2cm" },
    { ask: r`$SA$ of an open-top box $5\times5\times4$.`, ws: "2.2cm" },
    { ask: r`$SA$ of a cube, side $10$.`, ws: "1.8cm" },
    { ask: r`A gift box $20\times15\times10$ cm; find the wrapping (SA).`, ws: "2.4cm" },
    { ask: r`$SA$ of a triangular prism: triangle base $6$, height $4$ (sides $5,5$), length $12$.`, ws: "2.6cm", challenge: true },
  ],
  answers: [r`$2(10+15+6)=62$.`, r`$96$.`, r`$8\pi+20\pi=28\pi\approx88.0$.`, r`$42\pi$.`, r`$2(24+12+8)=88$.`, r`$216$.`, r`$50\pi+40\pi=90\pi\approx282.7$.`, r`$(3+4+5)(8)+12=108$.`, r`$2\pi(4)(12)=96\pi\approx301.6$.`, r`$25+4(20)=105$.`, r`$600$.`, r`$2(300+200+150)=1300$ cm$^2$.`, r`$192+24=216$.`],
},
{
  code: "4.3", unit: U, title: r`Volume of Prisms \& Cylinders`,
  intro: r`Volume is the space inside: $V=(\text{base area})\times\text{height}$.`,
  ideas: [
    r`Rectangular prism: $V=lwh$.`,
    r`Cylinder: $V=\pi r^2h$.`,
    r`Triangular prism: $V=(\text{triangle area})\times\text{length}$.`,
    r`Volume units are cubic; use the radius for cylinders.`,
  ],
  examples: [
    { t: "Rectangular prism", body: r`$V$ of a $4\times3\times2$ box.\soln $4\times3\times2=24$ units$^3$.` },
    { t: "Cube", body: r`$V$ of a cube, side $5$.\soln $5^3=125$ units$^3$.` },
    { t: "Cylinder", body: r`$V$ of a cylinder $r=3,\ h=10$.\soln $\pi(9)(10)=90\pi\approx282.7$.` },
    { t: "Triangular prism", body: r`Triangle area $6$, length $10$.\soln $6\times10=60$ units$^3$.` },
    { t: "Water tank", body: r`Cylinder $r=2$ m, $h=5$ m.\soln $\pi(4)(5)=20\pi\approx62.8$ m$^3$.` },
    { t: "Box", body: r`$V$ of a $6\times2\times3$ prism.\soln $36$ units$^3$.` },
    { t: "Smaller cube", body: r`$V$ of a cube, side $4$.\soln $64$ units$^3$.` },
    { t: "Cylinder (exact)", body: r`$V$ of a cylinder $r=5,\ h=4$.\soln $\pi(25)(4)=100\pi\approx314.2$.` },
    { t: "Find a height (harder)", body: r`A cylinder holds $48\pi$ cm$^3$ with $r=4$. Find $h$.\soln $\pi(16)h=48\pi\Rightarrow h=3$ cm.` },
  ],
  questions: [
    { ask: r`$V$ of a $5\times3\times2$ prism.`, ws: "1.8cm" },
    { ask: r`$V$ of a cube, side $4$.`, ws: "1.8cm" },
    { ask: r`$V$ of a cylinder $r=3,\ h=10$ (1 dp).`, ws: "2.2cm" },
    { ask: r`$V$ of a triangular prism: triangle area $10$, length $7$.`, ws: "2.0cm" },
    { ask: r`$V$ of a $6\times2\times3$ box.`, ws: "1.8cm" },
    { ask: r`$V$ of a cube, side $6$.`, ws: "1.8cm" },
    { ask: r`$V$ of a cylinder $r=5,\ h=4$ (exact).`, ws: "2.0cm" },
    { ask: r`$V$ of a cylinder $r=2,\ h=9$ (1 dp).`, ws: "2.0cm" },
    { ask: r`A tank $r=2$ m, $h=5$ m; find the volume (1 dp).`, ws: "2.2cm" },
    { ask: r`How many litres in a $30\times20\times10$ cm box (1 L $=1000$ cm$^3$)?`, ws: "2.2cm" },
    { ask: r`$V$ of a triangular prism: triangle base $8$, height $3$, length $10$.`, ws: "2.2cm" },
    { ask: r`A cylinder holds $100\pi$ cm$^3$ with $r=5$; find $h$.`, ws: "2.2cm" },
    { ask: r`A cylinder holds $48\pi$ cm$^3$ with $r=4$; find $h$.`, ws: "2.4cm", challenge: true },
  ],
  answers: [r`$30$.`, r`$64$.`, r`$90\pi\approx282.7$.`, r`$70$.`, r`$36$.`, r`$216$.`, r`$100\pi$.`, r`$36\pi\approx113.1$.`, r`$20\pi\approx62.8$ m$^3$.`, r`$6000$ cm$^3=6$ L.`, r`$(\tfrac12\cdot8\cdot3)(10)=120$.`, r`$\pi(25)h=100\pi\Rightarrow h=4$.`, r`$h=3$ cm.`],
},
{
  code: "4.4", unit: U, title: r`Pyramids \& Cones`,
  intro: r`Pyramids and cones taper to a point, so their volume is one-third of the matching prism or cylinder.`,
  ideas: [
    r`Volume: $V=\tfrac13(\text{base area})h$; cone $V=\tfrac13\pi r^2h$.`,
    r`Cone surface area: $SA=\pi r^2+\pi r s$ ($s=$ slant height).`,
    r`Square pyramid $SA=\text{base}+\tfrac12(\text{perimeter})s$.`,
    r`Slant height: $s=\sqrt{r^2+h^2}$.`,
  ],
  examples: [
    { t: "Cone volume", body: r`$V$ of a cone $r=3,\ h=4$.\soln $\tfrac13\pi(9)(4)=12\pi\approx37.7$.` },
    { t: "Pyramid volume", body: r`Square pyramid base $6\times6$, height $10$.\soln $\tfrac13(36)(10)=120$.` },
    { t: "Slant height", body: r`Cone $r=3,\ h=4$. Find $s$.\soln $s=\sqrt{9+16}=5$.` },
    { t: "Cone surface area", body: r`Cone $r=3,\ s=5$.\soln $\pi(9)+\pi(3)(5)=24\pi\approx75.4$.` },
    { t: "Pyramid surface area", body: r`Square pyramid base $6$, slant $5$.\soln $36+\tfrac12(24)(5)=96$.` },
    { t: "Bigger cone", body: r`$V$ of a cone $r=6,\ h=10$.\soln $\tfrac13\pi(36)(10)=120\pi\approx377.0$.` },
    { t: "Pyramid volume", body: r`Square pyramid base $4\times4$, height $9$.\soln $\tfrac13(16)(9)=48$.` },
    { t: "Slant height", body: r`Cone $r=6,\ h=8$. Find $s$.\soln $\sqrt{36+64}=10$.` },
    { t: "Total surface area (harder)", body: r`Cone $r=3,\ h=4$. Find the total $SA$.\soln $s=5$; $SA=9\pi+15\pi=24\pi\approx75.4$.` },
  ],
  questions: [
    { ask: r`$V$ of a cone $r=6,\ h=10$ (exact).`, ws: "2.0cm" },
    { ask: r`$V$ of a square pyramid base $4\times4$, height $9$.`, ws: "2.0cm" },
    { ask: r`Slant height of a cone $r=6,\ h=8$.`, ws: "2.0cm" },
    { ask: r`$SA$ of a cone $r=5,\ s=13$ (exact).`, ws: "2.0cm" },
    { ask: r`$V$ of a cone $r=3,\ h=4$ (1 dp).`, ws: "2.0cm" },
    { ask: r`$V$ of a square pyramid base $6\times6$, height $10$.`, ws: "2.0cm" },
    { ask: r`Slant height of a cone $r=3,\ h=4$.`, ws: "2.0cm" },
    { ask: r`$SA$ of a square pyramid base $6$, slant $5$.`, ws: "2.2cm" },
    { ask: r`$V$ of a cone $r=2,\ h=6$ (exact).`, ws: "2.0cm" },
    { ask: r`$SA$ of a cone $r=3,\ s=5$ (exact).`, ws: "2.0cm" },
    { ask: r`An ice-cream cone $r=3,\ h=8$; find its volume (1 dp).`, ws: "2.2cm" },
    { ask: r`A pyramid roof base $6\times6$, slant $5$; find the lateral area to shingle.`, ws: "2.4cm" },
    { ask: r`A cone $r=6,\ h=8$; find its total surface area (exact).`, ws: "2.6cm", challenge: true },
  ],
  answers: [r`$120\pi\approx377.0$.`, r`$48$.`, r`$10$.`, r`$25\pi+65\pi=90\pi$.`, r`$12\pi\approx37.7$.`, r`$120$.`, r`$5$.`, r`$36+60=96$.`, r`$8\pi\approx25.1$.`, r`$9\pi+15\pi=24\pi$.`, r`$\tfrac13\pi(9)(8)=24\pi\approx75.4$.`, r`$\tfrac12(24)(5)=60$.`, r`$s=10$; $36\pi+60\pi=96\pi$.`],
},
{
  code: "4.5", unit: U, title: "Spheres",
  intro: r`A sphere has volume $V=\tfrac43\pi r^3$ and surface area $SA=4\pi r^2$.`,
  ideas: [
    r`Volume: $V=\tfrac43\pi r^3$.`,
    r`Surface area: $SA=4\pi r^2$.`,
    r`Hemisphere volume is half a sphere's; given a diameter, halve it for $r$.`,
    r`Find $r$ from $SA$: divide by $4\pi$, then square-root.`,
  ],
  examples: [
    { t: "Volume", body: r`$V$ of a sphere $r=3$.\soln $\tfrac43\pi(27)=36\pi\approx113.1$.` },
    { t: "Surface area", body: r`$SA$ of a sphere $r=3$.\soln $4\pi(9)=36\pi\approx113.1$.` },
    { t: "Larger sphere", body: r`$V$ of a sphere $r=6$.\soln $\tfrac43\pi(216)=288\pi\approx904.8$.` },
    { t: "From diameter", body: r`$SA$ of a ball with diameter $10$.\soln $r=5$: $4\pi(25)=100\pi\approx314.2$.` },
    { t: "Hemisphere", body: r`Volume of a hemisphere $r=3$.\soln $\tfrac12(36\pi)=18\pi\approx56.5$.` },
    { t: "Small sphere", body: r`$V$ of a sphere $r=2$.\soln $\tfrac43\pi(8)=\tfrac{32}{3}\pi\approx33.5$.` },
    { t: "Surface area", body: r`$SA$ of a sphere $r=5$.\soln $4\pi(25)=100\pi\approx314.2$.` },
    { t: "From diameter", body: r`$SA$ of a sphere with diameter $8$.\soln $r=4$: $64\pi\approx201.1$.` },
    { t: "Find the radius (harder)", body: r`A sphere has $SA=36\pi$. Find $r$.\soln $4\pi r^2=36\pi\Rightarrow r^2=9\Rightarrow r=3$.` },
  ],
  questions: [
    { ask: r`$V$ of a sphere $r=2$ (exact).`, ws: "2.0cm" },
    { ask: r`$SA$ of a sphere $r=5$ (exact).`, ws: "1.8cm" },
    { ask: r`$SA$ of a sphere with diameter $8$.`, ws: "2.0cm" },
    { ask: r`$V$ of a hemisphere $r=6$ (exact).`, ws: "2.0cm" },
    { ask: r`$V$ of a sphere $r=3$ (1 dp).`, ws: "2.0cm" },
    { ask: r`$SA$ of a sphere $r=3$ (1 dp).`, ws: "2.0cm" },
    { ask: r`$V$ of a sphere $r=6$ (exact).`, ws: "2.0cm" },
    { ask: r`$SA$ of a ball with diameter $10$.`, ws: "2.0cm" },
    { ask: r`$V$ of a hemisphere $r=3$ (exact).`, ws: "2.0cm" },
    { ask: r`A basketball has $r=12$ cm; find its volume (1 dp).`, ws: "2.2cm" },
    { ask: r`$SA$ of a sphere $r=10$ (exact).`, ws: "1.8cm" },
    { ask: r`A sphere has $SA=64\pi$; find $r$.`, ws: "2.2cm" },
    { ask: r`A sphere has $SA=36\pi$; find $r$.`, ws: "2.2cm", challenge: true },
  ],
  answers: [r`$\tfrac{32}{3}\pi\approx33.5$.`, r`$100\pi\approx314.2$.`, r`$64\pi\approx201.1$.`, r`$144\pi$.`, r`$36\pi\approx113.1$.`, r`$36\pi\approx113.1$.`, r`$288\pi$.`, r`$100\pi$.`, r`$18\pi$.`, r`$\tfrac43\pi(1728)=2304\pi\approx7238.2$.`, r`$400\pi$.`, r`$4\pi r^2=64\pi\Rightarrow r=4$.`, r`$r=3$.`],
},
{
  code: "4.6", unit: U, title: r`Composite Figures \& Measurement Problems`,
  intro: r`Break a composite figure into simple solids, then add (or subtract) their measurements.`,
  ideas: [
    r`Identify the simple solids (prism, cylinder, cone, hemisphere).`,
    r`Add the parts; subtract a hollowed-out part.`,
    r`For surface area, count only exposed faces (drop hidden joins).`,
    r`Keep $\pi$ exact until the end, then round if asked.`,
  ],
  examples: [
    { t: "Silo (cylinder + hemisphere)", body: r`Cylinder $r=3,\ h=10$ topped by a hemisphere $r=3$.\soln $90\pi+18\pi=108\pi\approx339.3$.` },
    { t: "House (box + roof)", body: r`Box $6\times4\times3$ + triangular-prism roof (triangle base $6$, height $2$, length $4$).\soln $72+\tfrac12(6)(2)(4)=72+24=96$.` },
    { t: "Pipe (subtract a hole)", body: r`Cylinder $R=5$ with a hole $r=3$, length $10$.\soln $250\pi-90\pi=160\pi\approx502.7$.` },
    { t: "Cone + scoop", body: r`Cone $r=3,\ h=8$ with a hemisphere $r=3$.\soln $24\pi+18\pi=42\pi\approx131.9$.` },
    { t: "Painting (surface area)", body: r`A cube side $4$ on the ground (no bottom painted).\soln $5(16)=80$ units$^2$.` },
    { t: "Box + pyramid", body: r`Box $5\times5\times2$ + pyramid (base $5\times5$, height $6$).\soln $50+\tfrac13(25)(6)=50+50=100$.` },
    { t: "Washer", body: r`Disc $R=4$ with hole $r=2$, thickness $1$.\soln $16\pi-4\pi=12\pi$.` },
    { t: "Drilled cube", body: r`Cube side $3$ with a $1\times1\times3$ hole.\soln $27-3=24$ units$^3$.` },
    { t: "Silo with cone top (harder)", body: r`Cylinder $r=4,\ h=12$ + cone top $r=4,\ h=3$.\soln $192\pi+16\pi=208\pi\approx653.5$.` },
  ],
  questions: [
    { ask: r`Cylinder $r=2,\ h=6$ + hemisphere $r=2$ (exact).`, ws: "2.2cm" },
    { ask: r`Box $5\times5\times2$ + pyramid (base $5\times5$, height $6$).`, ws: "2.2cm" },
    { ask: r`A washer: disc $R=4$ with hole $r=2$, thickness $1$ (exact).`, ws: "2.2cm" },
    { ask: r`A cube side $3$ with a $1\times1\times3$ hole; find the remaining volume.`, ws: "2.2cm" },
    { ask: r`Cylinder $r=3,\ h=10$ + hemisphere $r=3$ (exact).`, ws: "2.2cm" },
    { ask: r`Cone $r=3,\ h=8$ + hemisphere $r=3$ (exact).`, ws: "2.2cm" },
    { ask: r`Painted area of a cube side $5$ resting on the ground.`, ws: "2.0cm" },
    { ask: r`A pipe: cylinder $R=5$ minus hole $r=3$, length $10$ (exact).`, ws: "2.4cm" },
    { ask: r`Box $4\times4\times3$ + pyramid (base $4\times4$, height $6$).`, ws: "2.2cm" },
    { ask: r`A drilled cube side $4$ with a $1\times1\times4$ hole.`, ws: "2.2cm" },
    { ask: r`Cylinder $r=2,\ h=5$ + cone top $r=2,\ h=3$ (exact).`, ws: "2.4cm" },
    { ask: r`A silo: cylinder $r=4,\ h=12$ + cone top $r=4,\ h=3$ (exact).`, ws: "2.4cm" },
    { ask: r`A grain bin: cylinder $r=3,\ h=8$ + cone top $r=3,\ h=4$ (exact).`, ws: "2.6cm", challenge: true },
  ],
  answers: [r`$24\pi+\tfrac{16}{3}\pi=\tfrac{88}{3}\pi\approx92.2$.`, r`$50+50=100$.`, r`$16\pi-4\pi=12\pi$.`, r`$27-3=24$.`, r`$90\pi+18\pi=108\pi$.`, r`$24\pi+18\pi=42\pi$.`, r`$5(25)=125$.`, r`$250\pi-90\pi=160\pi$.`, r`$48+32=80$.`, r`$64-4=60$.`, r`$20\pi+4\pi=24\pi$.`, r`$192\pi+16\pi=208\pi$.`, r`$72\pi+12\pi=84\pi\approx263.9$.`],
},
];
