// MFM2P Unit 1 — Algebra & Solving Equations: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 1.1 Review of Expressions & Integers ─────────────────────
function g11() {
  const q = [];
  q.push(mc("easy", "Evaluate $-3+7-5$.", ["$-1$", "$1$", "$-15$", "$9$"], 0));
  q.push(mc("easy", "Evaluate $4-(-6)$.", ["$10$", "$-2$", "$-10$", "$2$"], 0));
  q.push(mc("easy", "Evaluate $(-4)(3)$.", ["$-12$", "$12$", "$-7$", "$7$"], 0));
  q.push(mc("easy", "Evaluate $-20\\div(-5)$.", ["$4$", "$-4$", "$-25$", "$15$"], 0));
  q.push(mc("easy", "Evaluate $2x^2-3x$ at $x=-2$.", ["$14$", "$2$", "$-2$", "$-14$"], 0));
  q.push(mc("easy", "Evaluate $5+2\\times3^2-4$.", ["$19$", "$25$", "$45$", "$13$"], 0));
  q.push(ms("easy", "Which equal $-3+7$?", ["$4$", "$7-3$", "$-(3-7)$", "$-10$"], [0, 1, 2]));
  q.push(ms("easy", "Which are negative?", ["$(-2)(3)$", "$-5+2$", "$(-4)(-1)$", "$10-3$"], [0, 1]));
  q.push(ms("easy", "For $2x^2-3x$ at $x=-2$:", ["$2(-2)^2=8$", "$-3(-2)=6$", "sum is $14$", "answer $-14$"], [0, 1, 2]));
  q.push(ms("easy", "The order of operations:", ["brackets first", "then exponents", "then $\\times$ and $\\div$", "then $+$ and $-$"], [0, 1, 2, 3]));
  q.push(tf("easy", "$-3-(-5)=2$.", true));
  q.push(tf("easy", "$(-2)^2=4$.", true));
  q.push(tf("easy", "$-3^2=9$.", false, "It is $-9$."));
  q.push(fill("easy", "Evaluate $-8+3-(-2)$.", ["-3"]));
  q.push(fill("easy", "Evaluate $(-6)(-4)$.", ["24"]));
  q.push(fill("easy", "Evaluate $12-3\\times2+4$.", ["10"]));
  q.push(num("easy", "Evaluate $-7+12-5$.", 0, 0));
  q.push(num("easy", "Evaluate $2x^2+1$ at $x=-3$.", 19, 0));
  q.push(num("easy", "Evaluate $10-2(3-7)$.", 18, 0));
  q.push(match("easy", "Match each expression to its value.", ["$-3+7$", "$(-4)(3)$", "$4-(-6)$"], ["$4$", "$-12$", "$10$"], [0, 1, 2]));
  q.push(mc("medium", "Evaluate $\\dfrac{a-b}{c}$ at $a=7,\\ b=-3,\\ c=2$.", ["$5$", "$2$", "$-5$", "$10$"], 0));
  q.push(mc("medium", "Evaluate $3x-x^2$ at $x=-1$.", ["$-4$", "$-2$", "$4$", "$2$"], 0));
  q.push(mc("medium", "Evaluate $(-2)^3$.", ["$-8$", "$8$", "$-6$", "$6$"], 0));
  q.push(mc("medium", "Evaluate $-5^2$.", ["$-25$", "$25$", "$-10$", "$10$"], 0));
  q.push(mc("medium", "Evaluate $20\\div(-4)+3$.", ["$-2$", "$-8$", "$2$", "$8$"], 0));
  q.push(mc("medium", "Evaluate $2(3)^2-5(3)+1$.", ["$4$", "$10$", "$-2$", "$13$"], 0));
  q.push(ms("medium", "Which equal $9$?", ["$(-3)^2$", "$-(-9)$", "$3^2$", "$-3^2$"], [0, 1, 2]));
  q.push(ms("medium", "Which are true?", ["$-6+4=-2$", "$-6-4=-10$", "$(-2)(-3)=6$", "$-8\\div2=4$"], [0, 1, 2]));
  q.push(ms("medium", "Evaluating $2x^2$ at $x=-3$:", ["$(-3)^2=9$", "$2\\times9=18$", "answer $18$", "answer $-18$"], [0, 1, 2]));
  q.push(ms("medium", "For $\\dfrac{a-b}{c}$ ($a=7,b=-3,c=2$):", ["substitute first", "$a-b=10$", "divide by $c$", "answer $5$"], [0, 1, 2, 3]));
  q.push(tf("medium", "$(-2)^3=-8$.", true));
  q.push(tf("medium", "$-4-3=-7$.", true));
  q.push(tf("medium", "$\\dfrac{-10}{-2}=-5$.", false));
  q.push(fill("medium", "Evaluate $3x-x^2$ at $x=-1$.", ["-4"]));
  q.push(fill("medium", "Evaluate $-5^2$.", ["-25"]));
  q.push(fill("medium", "Evaluate $(-2)^3$.", ["-8"]));
  q.push(num("medium", "Evaluate $\\dfrac{a-b}{c}$ at $a=7,\\ b=-3,\\ c=2$.", 5, 0));
  q.push(num("medium", "Evaluate $20\\div(-4)+3$.", -2, 0));
  q.push(num("medium", "Evaluate $2(3)^2-5(3)+1$.", 4, 0));
  q.push(match("medium", "Match each to its value.", ["$-5^2$", "$(-5)^2$", "$(-2)^3$"], ["$-25$", "$25$", "$-8$"], [0, 1, 2]));
  q.push(mc("hard", "Evaluate $\\dfrac{2a+b}{a-b}$ at $a=4,\\ b=-2$.", ["$1$", "$-1$", "$3$", "$0$"], 0));
  q.push(mc("hard", "Evaluate $-2^4$.", ["$-16$", "$16$", "$-8$", "$8$"], 0));
  q.push(mc("hard", "Evaluate $(-1)^{10}$.", ["$1$", "$-1$", "$10$", "$-10$"], 0));
  q.push(mc("hard", "Evaluate $3-2[4-(6-9)]$.", ["$-11$", "$11$", "$-3$", "$5$"], 0));
  q.push(mc("hard", "Evaluate $\\dfrac{(-3)^2-1}{-4}$.", ["$-2$", "$2$", "$-\\tfrac12$", "$8$"], 0));
  q.push(ms("hard", "Which equal $-8$?", ["$(-2)^3$", "$-2^3$", "$-(8)$", "$2^3$"], [0, 1, 2]));
  q.push(ms("hard", "Which are correct?", ["$-3-(-7)=4$", "$(-4)(-2)(-1)=-8$", "$\\dfrac{-12}{4}=-3$", "$-2^2=4$"], [0, 1, 2]));
  q.push(ms("hard", "For $\\dfrac{2a+b}{a-b}$ at $a=4,b=-2$:", ["$2a+b=6$", "$a-b=6$", "quotient $1$", "answer $-1$"], [0, 1, 2]));
  q.push(ms("hard", "Evaluating with BEDMAS:", ["brackets inside-out", "exponents next", "left-to-right for $\\times\\div$", "left-to-right for $+-$"], [0, 1, 2, 3]));
  q.push(tf("hard", "$-2^4=-16$.", true));
  q.push(tf("hard", "$(-2)^4=16$.", true));
  q.push(tf("hard", "$-2^4=16$.", false));
  q.push(fill("hard", "Evaluate $\\dfrac{2a+b}{a-b}$ at $a=4,\\ b=-2$.", ["1"]));
  q.push(fill("hard", "Evaluate $-2^4$.", ["-16"]));
  q.push(fill("hard", "Evaluate $3-2[4-(6-9)]$.", ["-11"]));
  q.push(num("hard", "Evaluate $(-1)^{10}$.", 1, 0));
  q.push(num("hard", "Evaluate $\\dfrac{(-3)^2-1}{-4}$.", -2, 0));
  q.push(num("hard", "Evaluate $4-(-3)-8$.", -1, 0));
  q.push(order("hard", "Order the BEDMAS steps for $5+2\\times3^2-4$.", ["Exponent: $3^2=9$", "Multiply: $2\\times9=18$", "Add: $5+18=23$", "Subtract: $23-4=19$"]));
  q.push(match("hard", "Match each to its value.", ["$-2^4$", "$(-2)^4$", "$(-1)^{10}$"], ["$-16$", "$16$", "$1$"], [0, 1, 2]));
  return q;
}

// ── 1.2 Like Terms & the Distributive Property ───────────────
function g12() {
  const q = [];
  q.push(mc("easy", "Simplify $4x+7-2x+3$.", ["$2x+10$", "$2x+4$", "$6x+10$", "$2x+21$"], 0));
  q.push(mc("easy", "Expand $3(x+4)$.", ["$3x+12$", "$3x+4$", "$x+12$", "$3x+7$"], 0));
  q.push(mc("easy", "Expand $-2(2x-5)$.", ["$-4x+10$", "$-4x-10$", "$-4x-5$", "$4x-10$"], 0));
  q.push(mc("easy", "Simplify $5a+2a$.", ["$7a$", "$10a$", "$7a^2$", "$7$"], 0));
  q.push(mc("easy", "Expand $x(x+5)$.", ["$x^2+5x$", "$x^2+5$", "$2x+5$", "$x^2$"], 0));
  q.push(mc("easy", "Simplify $8x-3x$.", ["$5x$", "$11x$", "$5x^2$", "$24x$"], 0));
  q.push(ms("easy", "Which are like terms?", ["$3x$ and $5x$", "$2y$ and $-y$", "$3x$ and $3x^2$", "$4$ and $-7$"], [0, 1, 3]));
  q.push(ms("easy", "Which equal $3(x+4)$?", ["$3x+12$", "$3\\cdot x+3\\cdot4$", "$3x+4$", "$12+3x$"], [0, 1, 3]));
  q.push(ms("easy", "Simplify $2(x+3)+4x$:", ["expand to $2x+6$", "add $4x$", "result $6x+6$", "result $6x+3$"], [0, 1, 2]));
  q.push(ms("easy", "The distributive property:", ["multiplies each inside term", "$a(b+c)=ab+ac$", "works with subtraction too", "multiplies only the first term"], [0, 1, 2]));
  q.push(tf("easy", "$3x$ and $5x$ are like terms.", true));
  q.push(tf("easy", "$-(x-6)=-x+6$.", true));
  q.push(tf("easy", "$2(x+3)=2x+3$.", false));
  q.push(fill("easy", "Simplify $5x+2-3x+6$.", ["2x+8", "2x + 8"]));
  q.push(fill("easy", "Expand $4(2x-3)$.", ["8x-12", "8x - 12"]));
  q.push(fill("easy", "Expand $-(2x-7)$.", ["-2x+7", "-2x + 7"]));
  q.push(num("easy", "In $3(x+4)=3x+c$, find $c$.", 12, 0));
  q.push(num("easy", "The coefficient of $x$ in $2(x+3)+4x$ is ___.", 6, 0));
  q.push(num("easy", "Simplify $6a-a$; the coefficient is ___.", 5, 0));
  q.push(match("easy", "Match each to its simplified form.", ["$3(x+2)$", "$4x+x$", "$-2(x-1)$"], ["$3x+6$", "$5x$", "$-2x+2$"], [0, 1, 2]));
  q.push(mc("medium", "Simplify $3(x-1)-2(x+4)$.", ["$x-11$", "$x-5$", "$5x-11$", "$x+11$"], 0));
  q.push(mc("medium", "Simplify $2(3x-1)-4(x-2)$.", ["$2x+6$", "$2x-6$", "$10x-10$", "$2x+10$"], 0));
  q.push(mc("medium", "Expand $-3(2x-5)$.", ["$-6x+15$", "$-6x-15$", "$-6x-5$", "$6x-15$"], 0));
  q.push(mc("medium", "Simplify $5a-3b+2a+b$.", ["$7a-2b$", "$7a-4b$", "$3a-2b$", "$7a+2b$"], 0));
  q.push(mc("medium", "Expand $2x(3x-4)$.", ["$6x^2-8x$", "$6x^2-4$", "$5x^2-8x$", "$6x-8$"], 0));
  q.push(mc("medium", "Simplify $4(x+2)-3x$.", ["$x+8$", "$x+2$", "$7x+8$", "$x+6$"], 0));
  q.push(ms("medium", "Simplify $3(x-1)-2(x+4)$:", ["$3x-3$", "$-2x-8$", "collect to $x-11$", "result $x+11$"], [0, 1, 2]));
  q.push(ms("medium", "Which simplify to $2x+6$?", ["$2(x+3)$", "$4(x+2)-2x-2$", "$2x+6+0$", "$x+6$"], [0, 1, 2]));
  q.push(ms("medium", "Expanding $2x(3x-4)$:", ["$2x\\cdot3x=6x^2$", "$2x\\cdot(-4)=-8x$", "result $6x^2-8x$", "result $6x-8$"], [0, 1, 2]));
  q.push(ms("medium", "A negative in front of brackets:", ["flips every sign", "$-(x-6)=-x+6$", "$-2(x+3)=-2x-6$", "leaves signs unchanged"], [0, 1, 2]));
  q.push(tf("medium", "$3(x-1)-2(x+4)=x-11$.", true));
  q.push(tf("medium", "$2x(3x-4)=6x^2-8x$.", true));
  q.push(tf("medium", "$-3(2x-5)=-6x-15$.", false));
  q.push(fill("medium", "Simplify $2(3x-1)-4(x-2)$.", ["2x+6", "2x + 6"]));
  q.push(fill("medium", "Expand $5(3x+2)$.", ["15x+10", "15x + 10"]));
  q.push(fill("medium", "Simplify $-2(x-3)+4(x+1)$.", ["2x+10", "2x + 10"]));
  q.push(num("medium", "The constant term in $3(x-1)-2(x+4)$ is ___.", -11, 0));
  q.push(num("medium", "The coefficient of $x^2$ in $2x(3x-4)$ is ___.", 6, 0));
  q.push(num("medium", "The coefficient of $x$ in $4(x+2)-3x$ is ___.", 1, 0));
  q.push(match("medium", "Match each to its simplified form.", ["$3(x-1)-2(x+4)$", "$2x(3x-4)$", "$5(3x+2)$"], ["$x-11$", "$6x^2-8x$", "$15x+10$"], [0, 1, 2]));
  q.push(mc("hard", "Simplify $2(x+3)-3(2x-1)+x$.", ["$-3x+9$", "$-3x+3$", "$3x+9$", "$-3x-9$"], 0));
  q.push(mc("hard", "Expand $(x+2)(x+3)$.", ["$x^2+5x+6$", "$x^2+6x+5$", "$x^2+6$", "$x^2+5x+5$"], 0));
  q.push(mc("hard", "Simplify $4x-[3-2(x-1)]$.", ["$6x-5$", "$2x-5$", "$6x-1$", "$2x-1$"], 0));
  q.push(mc("hard", "Expand $-2x(x-3)+x^2$.", ["$-x^2+6x$", "$-3x^2+6x$", "$-x^2-6x$", "$x^2+6x$"], 0));
  q.push(mc("hard", "Simplify $3(2x-1)-(x-4)$.", ["$5x+1$", "$5x-7$", "$5x-1$", "$7x+1$"], 0));
  q.push(ms("hard", "For $2(x+3)-3(2x-1)+x$:", ["$2x+6$", "$-6x+3$", "the $+x$", "collect to $-3x+9$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which equal $x^2+5x+6$?", ["$(x+2)(x+3)$", "$(x+3)(x+2)$", "$x^2+6$", "the FOIL of $(x+2)(x+3)$"], [0, 1, 3]));
  q.push(ms("hard", "Which are fully simplified?", ["$-3x+9$", "$2x+6$", "$3x-2x$", "$5x+1$"], [0, 1, 3]));
  q.push(ms("hard", "Steps to simplify nested brackets:", ["work innermost first", "distribute", "collect like terms", "ignore the signs"], [0, 1, 2]));
  q.push(tf("hard", "$(x+2)(x+3)=x^2+5x+6$.", true));
  q.push(tf("hard", "$4x-[3-2(x-1)]=6x-5$.", true));
  q.push(tf("hard", "$-2x(x-3)=-2x^2-6x$.", false));
  q.push(fill("hard", "Simplify $2(x+3)-3(2x-1)+x$.", ["-3x+9", "-3x + 9"]));
  q.push(fill("hard", "Expand $(x+2)(x+3)$.", ["x^2+5x+6", "x²+5x+6"]));
  q.push(fill("hard", "Simplify $3(2x-1)-(x-4)$.", ["5x+1", "5x + 1"]));
  q.push(num("hard", "The coefficient of $x$ in $2(x+3)-3(2x-1)+x$ is ___.", -3, 0));
  q.push(num("hard", "The constant term of $(x+2)(x+3)$ is ___.", 6, 0));
  q.push(num("hard", "The coefficient of $x$ in $3(2x-1)-(x-4)$ is ___.", 5, 0));
  q.push(order("hard", "Order the steps to simplify $-2x(x-3)+x^2$.", ["Distribute: $-2x^2+6x$", "Add $x^2$", "Collect: $-x^2+6x$", "Write the result"]));
  q.push(match("hard", "Match each to its simplified form.", ["$2(x+3)-3(2x-1)+x$", "$(x+2)(x+3)$", "$-2x(x-3)+x^2$"], ["$-3x+9$", "$x^2+5x+6$", "$-x^2+6x$"], [0, 1, 2]));
  return q;
}

// ── 1.3 Solving One- & Two-Step Equations ────────────────────
function g13() {
  const q = [];
  q.push(mc("easy", "Solve $x+5=12$.", ["$7$", "$17$", "$-7$", "$5$"], 0));
  q.push(mc("easy", "Solve $3x=21$.", ["$7$", "$18$", "$24$", "$63$"], 0));
  q.push(mc("easy", "Solve $x-4=-2$.", ["$2$", "$-6$", "$6$", "$-2$"], 0));
  q.push(mc("easy", "Solve $2x+1=9$.", ["$4$", "$5$", "$3$", "$8$"], 0));
  q.push(mc("easy", "Solve $\\dfrac{x}{4}=3$.", ["$12$", "$7$", "$\\tfrac34$", "$1$"], 0));
  q.push(mc("easy", "To solve $2x+1=9$, first:", ["subtract $1$", "divide by $2$", "add $1$", "multiply by $2$"], 0));
  q.push(ms("easy", "Which check $x=4$ in $2x+1=9$?", ["$2(4)+1=9$", "$8+1=9$", "$x=4$ works", "$x=5$"], [0, 1, 2]));
  q.push(ms("easy", "Which equations have $x=5$?", ["$x+2=7$", "$3x=15$", "$x-1=4$", "$2x=8$"], [0, 1, 2]));
  q.push(ms("easy", "To isolate $x$:", ["use inverse operations", "do the same to both sides", "check by substituting", "change only one side"], [0, 1, 2]));
  q.push(ms("easy", "Which are one-step equations?", ["$x+3=8$", "$5x=20$", "$2x+1=7$", "$\\dfrac{x}{2}=4$"], [0, 1, 3]));
  q.push(tf("easy", "To undo $+5$, subtract $5$.", true));
  q.push(tf("easy", "Solving $3x=21$ gives $x=7$.", true));
  q.push(tf("easy", "Solving $x-4=-2$ gives $x=-6$.", false));
  q.push(fill("easy", "Solve $x-7=2$.", ["9"]));
  q.push(fill("easy", "Solve $4x=20$.", ["5"]));
  q.push(fill("easy", "Solve $\\dfrac{x}{3}=4$.", ["12"]));
  q.push(num("easy", "Solve $2x-5=11$.", 8, 0));
  q.push(num("easy", "Solve $x+9=4$.", -5, 0));
  q.push(num("easy", "Solve $3x+2=17$.", 5, 0));
  q.push(match("easy", "Match each equation to its solution.", ["$x+5=12$", "$3x=21$", "$\\dfrac{x}{4}=3$"], ["$7$", "$7$", "$12$"], [0, 1, 2]));
  q.push(mc("medium", "Solve $5-x=2$.", ["$3$", "$-3$", "$7$", "$-7$"], 0));
  q.push(mc("medium", "Solve $\\dfrac{x}{2}+1=5$.", ["$8$", "$12$", "$3$", "$10$"], 0));
  q.push(mc("medium", "Solve $7-2x=1$.", ["$3$", "$-3$", "$4$", "$-4$"], 0));
  q.push(mc("medium", "Solve $3x-2=10$.", ["$4$", "$6$", "$\\tfrac83$", "$12$"], 0));
  q.push(mc("medium", "Solve $2x+7=1$.", ["$-3$", "$3$", "$-4$", "$4$"], 0));
  q.push(mc("medium", "A taxi: $2d+3=15$. The distance is:", ["$6$", "$9$", "$7.5$", "$12$"], 0));
  q.push(ms("medium", "Solving $7-2x=1$:", ["subtract $7$", "$-2x=-6$", "divide by $-2$", "$x=3$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Which have $x=4$?", ["$2x=8$", "$x+1=5$", "$3x-2=10$", "$x-1=4$"], [0, 1, 2]));
  q.push(ms("medium", "The two-step strategy:", ["undo $+/-$ first", "then $\\times/\\div$", "check the answer", "always divide first"], [0, 1, 2]));
  q.push(ms("medium", "Which are two-step equations?", ["$2x+1=9$", "$\\dfrac{x}{2}-1=4$", "$3x=12$", "$x-4=2$"], [0, 1]));
  q.push(tf("medium", "Solving $5-x=2$ gives $x=3$.", true));
  q.push(tf("medium", "Solving $\\dfrac{x}{2}+1=5$ gives $x=8$.", true));
  q.push(tf("medium", "Solving $2x+7=1$ gives $x=3$.", false));
  q.push(fill("medium", "Solve $3x-2=10$.", ["4"]));
  q.push(fill("medium", "Solve $\\dfrac{x}{2}-1=4$.", ["10"]));
  q.push(fill("medium", "Solve $5x=-15$.", ["-3"]));
  q.push(num("medium", "Solve $2x+1=9$.", 4, 0));
  q.push(num("medium", "Solve $7-2x=1$.", 3, 0));
  q.push(num("medium", "Solve $\\dfrac{x}{5}+2=6$.", 20, 0));
  q.push(match("medium", "Match each equation to its solution.", ["$5-x=2$", "$3x-2=10$", "$2x+7=1$"], ["$3$", "$4$", "$-3$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $\\dfrac{x}{3}-2=4$.", ["$18$", "$6$", "$2$", "$9$"], 0));
  q.push(mc("hard", "Solve $9-3x=0$.", ["$3$", "$-3$", "$0$", "$9$"], 0));
  q.push(mc("hard", "Solve $\\dfrac{2x}{3}=8$.", ["$12$", "$16$", "$\\tfrac{16}{3}$", "$4$"], 0));
  q.push(mc("hard", "Solve $4-\\dfrac{x}{2}=1$.", ["$6$", "$-6$", "$10$", "$3$"], 0));
  q.push(mc("hard", "Solve $-3x+5=-7$.", ["$4$", "$-4$", "$\\tfrac23$", "$12$"], 0));
  q.push(ms("hard", "Solving $\\dfrac{x}{3}-2=4$:", ["add $2$", "$\\dfrac{x}{3}=6$", "multiply by $3$", "$x=18$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which equations have a negative solution?", ["$x+5=2$", "$2x=-6$", "$x-1=4$", "$3x+9=0$"], [0, 1, 3]));
  q.push(ms("hard", "Which steps solve $\\dfrac{2x}{3}=8$?", ["multiply both sides by $3$", "$2x=24$", "divide by $2$", "$x=12$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Checking a solution means:", ["substitute it back", "both sides should match", "catches sign errors", "is optional and pointless"], [0, 1, 2]));
  q.push(tf("hard", "Solving $\\dfrac{x}{3}-2=4$ gives $x=18$.", true));
  q.push(tf("hard", "Solving $9-3x=0$ gives $x=3$.", true));
  q.push(tf("hard", "Solving $\\dfrac{2x}{3}=8$ gives $x=16$.", false));
  q.push(fill("hard", "Solve $\\dfrac{x}{3}-2=4$.", ["18"]));
  q.push(fill("hard", "Solve $-3x+5=-7$.", ["4"]));
  q.push(fill("hard", "Solve $4-\\dfrac{x}{2}=1$.", ["6"]));
  q.push(num("hard", "Solve $9-3x=0$.", 3, 0));
  q.push(num("hard", "Solve $\\dfrac{2x}{3}=8$.", 12, 0));
  q.push(num("hard", "Solve $2x+7=1$.", -3, 0));
  q.push(order("hard", "Order the steps to solve $2x+1=9$.", ["Subtract $1$ from both sides", "Get $2x=8$", "Divide both sides by $2$", "Get $x=4$"]));
  q.push(match("hard", "Match each equation to its solution.", ["$\\dfrac{x}{3}-2=4$", "$9-3x=0$", "$-3x+5=-7$"], ["$18$", "$3$", "$4$"], [0, 1, 2]));
  return q;
}

// ── 1.4 Solving Multi-Step Equations ─────────────────────────
function g14() {
  const q = [];
  q.push(mc("easy", "Solve $2x+3=x+8$.", ["$5$", "$11$", "$-5$", "$3$"], 0));
  q.push(mc("easy", "Solve $3(x-2)=12$.", ["$6$", "$2$", "$4$", "$10$"], 0));
  q.push(mc("easy", "Solve $4x-7=2x+5$.", ["$6$", "$1$", "$-6$", "$2$"], 0));
  q.push(mc("easy", "Solve $5x-3=2x+9$.", ["$4$", "$2$", "$6$", "$3$"], 0));
  q.push(mc("easy", "Solve $2(x+4)=14$.", ["$3$", "$5$", "$7$", "$1$"], 0));
  q.push(mc("easy", "First step for $3(x-2)=12$:", ["expand the brackets", "divide by $x$", "subtract $x$", "add $12$"], 0));
  q.push(ms("easy", "Solving $2x+3=x+8$:", ["subtract $x$", "$x+3=8$", "$x=5$", "$x=11$"], [0, 1, 2]));
  q.push(ms("easy", "Which are multi-step equations?", ["$2x+3=x+8$", "$3(x-2)=12$", "$x+1=5$", "$4x-7=2x+5$"], [0, 1, 3]));
  q.push(ms("easy", "The plan for a multi-step equation:", ["expand brackets", "collect like terms", "gather the variable on one side", "guess"], [0, 1, 2]));
  q.push(ms("easy", "Which have $x=6$?", ["$3(x-2)=12$", "$4x-7=2x+5$", "$x+1=7$", "$2x=10$"], [0, 1, 2]));
  q.push(tf("easy", "Expand brackets before collecting like terms.", true));
  q.push(tf("easy", "Solving $2(x+4)=14$ gives $x=3$.", true));
  q.push(tf("easy", "Solving $4x-7=2x+5$ gives $x=-6$.", false));
  q.push(fill("easy", "Solve $3x+2=x+10$.", ["4"]));
  q.push(fill("easy", "Solve $2(x-3)=8$.", ["7"]));
  q.push(fill("easy", "Solve $5x-4=3x+6$.", ["5"]));
  q.push(num("easy", "Solve $2x+3=x+8$.", 5, 0));
  q.push(num("easy", "Solve $3(x-2)=12$.", 6, 0));
  q.push(num("easy", "Solve $2(x+4)=14$.", 3, 0));
  q.push(match("easy", "Match each equation to its solution.", ["$2x+3=x+8$", "$3(x-2)=12$", "$2(x+4)=14$"], ["$5$", "$6$", "$3$"], [0, 1, 2]));
  q.push(mc("medium", "Solve $2(x+1)=3(x-2)$.", ["$8$", "$-8$", "$1$", "$4$"], 0));
  q.push(mc("medium", "Solve $\\dfrac{x}{3}-2=4$.", ["$18$", "$6$", "$2$", "$9$"], 0));
  q.push(mc("medium", "Solve $6x-5=4x+7$.", ["$6$", "$1$", "$-6$", "$2$"], 0));
  q.push(mc("medium", "Solve $3(x-1)=2(x+4)$.", ["$11$", "$5$", "$-11$", "$7$"], 0));
  q.push(mc("medium", "Solve $\\dfrac{x}{2}+3=7$.", ["$8$", "$20$", "$2$", "$5$"], 0));
  q.push(mc("medium", "Solve $4(x+2)=12$.", ["$1$", "$5$", "$2$", "$4$"], 0));
  q.push(ms("medium", "Solving $2(x+1)=3(x-2)$:", ["expand $2x+2=3x-6$", "subtract $2x$", "$8=x$", "$x=-8$"], [0, 1, 2]));
  q.push(ms("medium", "Which equal $x=6$?", ["$6x-5=4x+7$", "$3(x-2)=12$", "$\\dfrac{x}{2}=3$", "$2x=12$"], [0, 1, 3]));
  q.push(ms("medium", "To clear a fraction:", ["multiply the whole equation by the denominator", "$\\dfrac{x}{3}=6\\Rightarrow x=18$", "keeps both sides equal", "ignore it"], [0, 1, 2]));
  q.push(ms("medium", "For $3(x-1)=2(x+4)$:", ["$3x-3=2x+8$", "subtract $2x$", "add $3$", "$x=11$"], [0, 1, 2, 3]));
  q.push(tf("medium", "Solving $2(x+1)=3(x-2)$ gives $x=8$.", true));
  q.push(tf("medium", "Solving $\\dfrac{x}{2}+3=7$ gives $x=8$.", true));
  q.push(tf("medium", "Solving $3(x-1)=2(x+4)$ gives $x=5$.", false));
  q.push(fill("medium", "Solve $7x-2=4x+13$.", ["5"]));
  q.push(fill("medium", "Solve $5(x-1)=3(x+3)$.", ["7"]));
  q.push(fill("medium", "Solve $\\dfrac{x}{4}-1=2$.", ["12"]));
  q.push(num("medium", "Solve $2(x+1)=3(x-2)$.", 8, 0));
  q.push(num("medium", "Solve $3(x-1)=2(x+4)$.", 11, 0));
  q.push(num("medium", "Solve $6x-5=4x+7$.", 6, 0));
  q.push(match("medium", "Match each equation to its solution.", ["$2(x+1)=3(x-2)$", "$3(x-1)=2(x+4)$", "$5(x-1)=3(x+3)$"], ["$8$", "$11$", "$7$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $2(2x+1)=3(x+4)$.", ["$10$", "$5$", "$-10$", "$2$"], 0));
  q.push(mc("hard", "Solve $4(x+2)-3=2(x+7)$.", ["$4.5$", "$4$", "$9$", "$3$"], 0));
  q.push(mc("hard", "Solve $\\dfrac{x+1}{2}=4$.", ["$7$", "$9$", "$3$", "$8$"], 0));
  q.push(mc("hard", "Solve $3-2(x-1)=x-4$.", ["$3$", "$-3$", "$1$", "$9$"], 0));
  q.push(mc("hard", "Solve $5(x-2)=2x+5$.", ["$5$", "$3$", "$-5$", "$1$"], 0));
  q.push(ms("hard", "Solving $2(2x+1)=3(x+4)$:", ["$4x+2=3x+12$", "subtract $3x$", "$x+2=12$", "$x=10$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which need brackets expanded first?", ["$2(2x+1)=3(x+4)$", "$3-2(x-1)=x-4$", "$2x=10$", "$5(x-2)=2x+5$"], [0, 1, 3]));
  q.push(ms("hard", "If variables cancel:", ["a true statement means infinitely many", "a false statement means no solution", "happens when both sides are identical/parallel", "always one solution"], [0, 1, 2]));
  q.push(ms("hard", "For $\\dfrac{x+1}{2}=4$:", ["multiply by $2$", "$x+1=8$", "subtract $1$", "$x=7$"], [0, 1, 2, 3]));
  q.push(tf("hard", "Solving $2(2x+1)=3(x+4)$ gives $x=10$.", true));
  q.push(tf("hard", "Solving $\\dfrac{x+1}{2}=4$ gives $x=7$.", true));
  q.push(tf("hard", "Solving $5(x-2)=2x+5$ gives $x=3$.", false));
  q.push(fill("hard", "Solve $2(2x+1)=3(x+4)$.", ["10"]));
  q.push(fill("hard", "Solve $\\dfrac{x+1}{2}=4$.", ["7"]));
  q.push(fill("hard", "Solve $5(x-2)=2x+5$.", ["5"]));
  q.push(num("hard", "Solve $3-2(x-1)=x-4$.", 3, 0));
  q.push(num("hard", "Solve $4(x+2)-3=2(x+7)$.", 4.5, 0));
  q.push(num("hard", "Solve $5(x-2)=2x+5$.", 5, 0));
  q.push(order("hard", "Order the steps to solve $3(x-1)=2(x+4)$.", ["Expand: $3x-3=2x+8$", "Subtract $2x$: $x-3=8$", "Add $3$", "$x=11$"]));
  q.push(match("hard", "Match each equation to its solution.", ["$2(2x+1)=3(x+4)$", "$\\dfrac{x+1}{2}=4$", "$5(x-2)=2x+5$"], ["$10$", "$7$", "$5$"], [0, 1, 2]));
  return q;
}

// ── 1.5 Rearranging Formulas ─────────────────────────────────
function g15() {
  const q = [];
  q.push(mc("easy", "Solve $A=lw$ for $w$.", ["$w=\\dfrac{A}{l}$", "$w=Al$", "$w=A-l$", "$w=\\dfrac{l}{A}$"], 0));
  q.push(mc("easy", "Solve $d=vt$ for $t$.", ["$t=\\dfrac{d}{v}$", "$t=dv$", "$t=\\dfrac{v}{d}$", "$t=d-v$"], 0));
  q.push(mc("easy", "Solve $P=4s$ for $s$.", ["$s=\\dfrac{P}{4}$", "$s=4P$", "$s=P-4$", "$s=\\dfrac{4}{P}$"], 0));
  q.push(mc("easy", "Solve $y=mx+b$ for $b$.", ["$b=y-mx$", "$b=y+mx$", "$b=\\dfrac{y}{mx}$", "$b=mx-y$"], 0));
  q.push(mc("easy", "Solve $C=2\\pi r$ for $r$.", ["$r=\\dfrac{C}{2\\pi}$", "$r=2\\pi C$", "$r=\\dfrac{2\\pi}{C}$", "$r=C-2\\pi$"], 0));
  q.push(mc("easy", "Rearranging a formula uses:", ["the same inverse operations as solving", "guessing", "only addition", "factoring"], 0));
  q.push(ms("easy", "To solve $A=lw$ for $w$:", ["divide both sides by $l$", "$w=\\dfrac{A}{l}$", "treat $w$ as the unknown", "multiply by $l$"], [0, 1, 2]));
  q.push(ms("easy", "Correct rearrangements:", ["$d=vt\\Rightarrow t=\\dfrac{d}{v}$", "$P=4s\\Rightarrow s=\\dfrac{P}{4}$", "$F=ma\\Rightarrow a=\\dfrac{F}{m}$", "$A=lw\\Rightarrow w=Al$"], [0, 1, 2]));
  q.push(ms("easy", "When rearranging:", ["do the same to both sides", "isolate the wanted variable", "the answer may be a fraction", "you can divide one side only"], [0, 1, 2]));
  q.push(ms("easy", "Which formulas give $r=\\dfrac{C}{2\\pi}$?", ["$C=2\\pi r$ for $r$", "circumference solved for radius", "$r=\\dfrac{C}{2\\pi}$", "$C=\\pi r^2$ for $r$"], [0, 1, 2]));
  q.push(tf("easy", "Rearranging is like solving, but with letters.", true));
  q.push(tf("easy", "$A=lw$ solved for $w$ is $w=\\dfrac{A}{l}$.", true));
  q.push(tf("easy", "$d=vt$ solved for $t$ is $t=dv$.", false));
  q.push(fill("easy", "Solve $A=lw$ for $l$.", ["A/w", "\\dfrac{A}{w}", "A÷w"]));
  q.push(fill("easy", "Solve $P=4s$ for $s$.", ["P/4", "\\dfrac{P}{4}"]));
  q.push(fill("easy", "Solve $F=ma$ for $a$.", ["F/m", "\\dfrac{F}{m}"]));
  q.push(num("easy", "For $A=lw$ with $A=20,\\ l=4$, find $w$.", 5, 0));
  q.push(num("easy", "For $d=vt$ with $d=120,\\ v=40$, find $t$.", 3, 0));
  q.push(num("easy", "For $P=4s$ with $P=24$, find $s$.", 6, 0));
  q.push(match("easy", "Match each formula (solved for the bold variable) to its result.", ["$A=lw$ for $w$", "$d=vt$ for $t$", "$P=4s$ for $s$"], ["$\\dfrac{A}{l}$", "$\\dfrac{d}{v}$", "$\\dfrac{P}{4}$"], [0, 1, 2]));
  q.push(mc("medium", "Solve $P=2(l+w)$ for $w$.", ["$w=\\dfrac{P}{2}-l$", "$w=P-2l$", "$w=\\dfrac{P-l}{2}$", "$w=2P-l$"], 0));
  q.push(mc("medium", "Solve $y=mx+b$ for $x$.", ["$x=\\dfrac{y-b}{m}$", "$x=\\dfrac{y}{m}-b$", "$x=y-b-m$", "$x=\\dfrac{y+b}{m}$"], 0));
  q.push(mc("medium", "Solve $A=\\tfrac12 bh$ for $h$.", ["$h=\\dfrac{2A}{b}$", "$h=\\dfrac{A}{2b}$", "$h=2Ab$", "$h=\\dfrac{b}{2A}$"], 0));
  q.push(mc("medium", "Solve $V=lwh$ for $h$.", ["$h=\\dfrac{V}{lw}$", "$h=Vlw$", "$h=\\dfrac{lw}{V}$", "$h=V-lw$"], 0));
  q.push(mc("medium", "Solve $2x+3y=12$ for $y$.", ["$y=\\dfrac{12-2x}{3}$", "$y=12-2x$", "$y=\\dfrac{12}{3}-2x$", "$y=\\dfrac{2x-12}{3}$"], 0));
  q.push(mc("medium", "Solve $v=u+at$ for $t$.", ["$t=\\dfrac{v-u}{a}$", "$t=\\dfrac{v}{a}-u$", "$t=v-u-a$", "$t=\\dfrac{v+u}{a}$"], 0));
  q.push(ms("medium", "Solving $P=2(l+w)$ for $w$:", ["divide by $2$", "$\\dfrac{P}{2}=l+w$", "subtract $l$", "$w=\\dfrac{P}{2}-l$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Correct rearrangements:", ["$A=\\tfrac12 bh\\Rightarrow h=\\dfrac{2A}{b}$", "$V=lwh\\Rightarrow h=\\dfrac{V}{lw}$", "$y=mx+b\\Rightarrow x=\\dfrac{y-b}{m}$", "$P=2(l+w)\\Rightarrow w=P-2l$"], [0, 1, 2]));
  q.push(ms("medium", "To isolate $h$ in $A=\\tfrac12 bh$:", ["multiply both sides by $2$", "divide by $b$", "$h=\\dfrac{2A}{b}$", "subtract $b$"], [0, 1, 2]));
  q.push(ms("medium", "For $2x+3y=12$ solved for $y$:", ["subtract $2x$", "$3y=12-2x$", "divide by $3$", "$y=\\dfrac{12-2x}{3}$"], [0, 1, 2, 3]));
  q.push(tf("medium", "$P=2(l+w)$ for $w$ is $w=\\dfrac{P}{2}-l$.", true));
  q.push(tf("medium", "$A=\\tfrac12 bh$ for $h$ is $h=\\dfrac{2A}{b}$.", true));
  q.push(tf("medium", "$y=mx+b$ for $x$ is $x=y-b-m$.", false));
  q.push(fill("medium", "Solve $P=2(l+w)$ for $l$.", ["P/2-w", "\\dfrac{P}{2}-w"]));
  q.push(fill("medium", "Solve $A=\\tfrac12 bh$ for $b$.", ["2A/h", "\\dfrac{2A}{h}"]));
  q.push(fill("medium", "Solve $y=mx+b$ for $m$.", ["(y-b)/x", "\\dfrac{y-b}{x}"]));
  q.push(num("medium", "For $A=\\tfrac12 bh$ with $A=24,\\ b=6$, find $h$.", 8, 0));
  q.push(num("medium", "For $V=lwh$ with $V=60,\\ l=5,\\ w=3$, find $h$.", 4, 0));
  q.push(num("medium", "For $C=40h+50$ with $C=250$, find $h$.", 5, 0));
  q.push(match("medium", "Match each formula (solved for the variable) to its result.", ["$A=\\tfrac12 bh$ for $h$", "$V=lwh$ for $h$", "$v=u+at$ for $t$"], ["$\\dfrac{2A}{b}$", "$\\dfrac{V}{lw}$", "$\\dfrac{v-u}{a}$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $S=\\dfrac{a}{1-r}$ for $r$.", ["$r=1-\\dfrac{a}{S}$", "$r=\\dfrac{a}{S}-1$", "$r=\\dfrac{S-a}{S}$", "both A and C"], 3));
  q.push(mc("hard", "Solve $A=P(1+rt)$ for $t$.", ["$t=\\dfrac{A-P}{Pr}$", "$t=\\dfrac{A}{Pr}-1$", "$t=\\dfrac{A-P}{r}$", "$t=\\dfrac{A}{P}-r$"], 0));
  q.push(mc("hard", "Solve $\\dfrac{x}{a}+\\dfrac{y}{b}=1$ for $y$.", ["$y=b\\left(1-\\dfrac{x}{a}\\right)$", "$y=1-\\dfrac{x}{a}$", "$y=\\dfrac{b}{1-x/a}$", "$y=ab-x$"], 0));
  q.push(mc("hard", "Solve $P=2l+2w$ for $w$.", ["$w=\\dfrac{P-2l}{2}$", "$w=P-2l$", "$w=\\dfrac{P}{2}-2l$", "$w=2P-l$"], 0));
  q.push(mc("hard", "Solve $C=\\tfrac59(F-32)$ for $F$.", ["$F=\\tfrac95C+32$", "$F=\\tfrac59C+32$", "$F=\\tfrac95(C-32)$", "$F=\\tfrac95C-32$"], 0));
  q.push(ms("hard", "Solving $A=P(1+rt)$ for $t$:", ["divide by $P$: $\\dfrac{A}{P}=1+rt$", "subtract $1$", "divide by $r$", "$t=\\dfrac{A-P}{Pr}$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which require dividing by a bracket or factoring it out?", ["$P=2(l+w)$ for $w$", "$A=P(1+rt)$ for $t$", "$d=vt$ for $t$", "$C=\\tfrac59(F-32)$ for $F$"], [0, 1, 3]));
  q.push(ms("hard", "Good practice when rearranging:", ["undo the outermost operation first", "keep both sides balanced", "answers can be fractions", "drop the variable you want"], [0, 1, 2]));
  q.push(ms("hard", "For $C=\\tfrac59(F-32)$ solved for $F$:", ["multiply by $\\tfrac95$", "$\\tfrac95C=F-32$", "add $32$", "$F=\\tfrac95C+32$"], [0, 1, 2, 3]));
  q.push(tf("hard", "$A=P(1+rt)$ for $t$ is $t=\\dfrac{A-P}{Pr}$.", true));
  q.push(tf("hard", "$P=2l+2w$ for $w$ is $w=\\dfrac{P-2l}{2}$.", true));
  q.push(tf("hard", "$C=\\tfrac59(F-32)$ for $F$ is $F=\\tfrac59C+32$.", false));
  q.push(fill("hard", "Solve $P=2l+2w$ for $w$.", ["(P-2l)/2", "\\dfrac{P-2l}{2}"]));
  q.push(fill("hard", "Solve $v=u+at$ for $a$.", ["(v-u)/t", "\\dfrac{v-u}{t}"]));
  q.push(fill("hard", "Solve $A=P(1+rt)$ for $t$.", ["(A-P)/(Pr)", "\\dfrac{A-P}{Pr}"]));
  q.push(num("hard", "For $A=P(1+rt)$ with $A=120,\\ P=100,\\ r=0.05$, find $t$.", 4, 0));
  q.push(num("hard", "For $C=\\tfrac59(F-32)$ with $F=212$, find $C$.", 100, 0));
  q.push(num("hard", "For $v=u+at$ with $v=20,\\ u=4,\\ t=8$, find $a$.", 2, 0));
  q.push(order("hard", "Order the steps to solve $A=P(1+rt)$ for $t$.", ["Divide both sides by $P$", "Subtract $1$", "Divide by $r$", "Write $t=\\dfrac{A-P}{Pr}$"]));
  q.push(match("hard", "Match each formula (solved for the variable) to its result.", ["$P=2l+2w$ for $w$", "$v=u+at$ for $a$", "$A=P(1+rt)$ for $t$"], ["$\\dfrac{P-2l}{2}$", "$\\dfrac{v-u}{t}$", "$\\dfrac{A-P}{Pr}$"], [0, 1, 2]));
  return q;
}

// ── 1.6 Modelling with Equations ─────────────────────────────
function g16() {
  const q = [];
  q.push(mc("easy", "Five more than twice a number is $17$. The number is:", ["$6$", "$11$", "$7$", "$8$"], 0));
  q.push(mc("easy", "'Twice a number' is written:", ["$2x$", "$x+2$", "$x^2$", "$\\dfrac{x}{2}$"], 0));
  q.push(mc("easy", "Three consecutive integers can be written:", ["$x,\\ x+1,\\ x+2$", "$x,\\ 2x,\\ 3x$", "$x,\\ x+2,\\ x+4$", "$x,\\ x-1,\\ x-2$"], 0));
  q.push(mc("easy", "A taxi: $2d+3=15$. The distance is:", ["$6$", "$9$", "$7.5$", "$12$"], 0));
  q.push(mc("easy", "A cost model has the form:", ["$C=(\\text{rate})x+(\\text{fixed fee})$", "$C=x^2$", "$C=\\dfrac{1}{x}$", "$C=\\sqrt{x}$"], 0));
  q.push(mc("easy", "The first step in a word problem is:", ["define a variable", "guess", "graph it", "add the numbers"], 0));
  q.push(ms("easy", "Which phrases mean $+$?", ["sum", "more than", "increased by", "less than"], [0, 1, 2]));
  q.push(ms("easy", "For 'five more than twice a number is 17':", ["$2x+5=17$", "$2x=12$", "$x=6$", "$x=11$"], [0, 1, 2]));
  q.push(ms("easy", "Steps to model a problem:", ["define a variable", "write an equation", "solve", "answer in a sentence"], [0, 1, 2, 3]));
  q.push(ms("easy", "Which are linear cost models?", ["$C=2d+3$", "$C=5v+20$", "$C=0.10p+60$", "$C=x^2$"], [0, 1, 2]));
  q.push(tf("easy", "Define the variable before writing the equation.", true));
  q.push(tf("easy", "'Twice a number' is $2x$.", true));
  q.push(tf("easy", "A problem with two unknowns always needs only one equation.", false));
  q.push(fill("easy", "Seven less than three times a number is $11$. Find the number.", ["6"]));
  q.push(fill("easy", "A taxi charges $3$ dollars plus $2$ dollars/km. The cost of $5$ km is ___ dollars.", ["13"]));
  q.push(fill("easy", "Two consecutive integers sum to $35$. The smaller is ___.", ["17"]));
  q.push(num("easy", "Five more than twice a number is $17$. Find the number.", 6, 0));
  q.push(num("easy", "A taxi $2d+3=15$: find $d$.", 6, 0));
  q.push(num("easy", "Three consecutive integers sum to $48$; the smallest is ___.", 15, 0));
  q.push(match("easy", "Match each phrase to its expression.", ["twice a number", "five more than a number", "a number decreased by 3"], ["$2x$", "$x+5$", "$x-3$"], [0, 1, 2]));
  q.push(mc("medium", "A rectangle's length is $3$ more than its width; perimeter $26$. The width is:", ["$5$", "$8$", "$6.5$", "$10$"], 0));
  q.push(mc("medium", "A plumber charges $50$ dollars plus $40$ dollars/h. A $210$-dollar job takes:", ["$4$ h", "$5$ h", "$6$ h", "$3$ h"], 0));
  q.push(mc("medium", "Plan A: $5$ dollars/visit. Plan B: $3$ dollars/visit + $4$ dollars. Equal at:", ["$2$ visits", "$3$ visits", "$4$ visits", "$1$ visit"], 0));
  q.push(mc("medium", "A rectangle's length is twice its width; perimeter $36$. The width is:", ["$6$", "$9$", "$12$", "$4$"], 0));
  q.push(mc("medium", "Three consecutive integers sum to $72$. The middle one is:", ["$24$", "$23$", "$25$", "$36$"], 0));
  q.push(mc("medium", "A number doubled then increased by $7$ is $25$. The number is:", ["$9$", "$16$", "$11$", "$18$"], 0));
  q.push(ms("medium", "For 'length 3 more than width, perimeter 26':", ["$2(w+3)+2w=26$", "$4w+6=26$", "$w=5$", "$w=8$"], [0, 1, 2]));
  q.push(ms("medium", "For a plumber $40x+50=210$:", ["subtract $50$", "$40x=160$", "$x=4$", "$x=6$"], [0, 1, 2]));
  q.push(ms("medium", "Two plans 'cost the same' means:", ["set the expressions equal", "solve for the variable", "find the break-even point", "they never meet"], [0, 1, 2]));
  q.push(ms("medium", "Which model a real situation linearly?", ["taxi fare", "gym membership", "phone plan", "area of a square"], [0, 1, 2]));
  q.push(tf("medium", "Setting two cost expressions equal finds when they cost the same.", true));
  q.push(tf("medium", "For length twice the width with perimeter $36$, the width is $6$.", true));
  q.push(tf("medium", "Three consecutive integers summing to $72$ have middle $25$.", false));
  q.push(fill("medium", "A taxi $4$ dollars plus $2$ dollars/km. What distance costs $20$ dollars?", ["8"]));
  q.push(fill("medium", "Gym A $8$/visit; Gym B $5$/visit + $12$. When equal? (visits)", ["4"]));
  q.push(fill("medium", "A printer $60$ dollars + $0.10$ dollars/page. How many pages cost $80$ dollars?", ["200"]));
  q.push(num("medium", "A rectangle length $3$ more than width, perimeter $26$: the width.", 5, 0));
  q.push(num("medium", "A plumber $40x+50=210$: hours.", 4, 0));
  q.push(num("medium", "Plan A $5x$, Plan B $3x+4$: visits when equal.", 2, 0));
  q.push(match("medium", "Match each scenario to its equation.", ["taxi: 3 + 2/km, cost 15", "plumber: 50 + 40/h, cost 210", "two plans equal"], ["$2d+3=15$", "$40h+50=210$", "$5x=3x+4$"], [0, 1, 2]));
  q.push(mc("hard", "Two numbers: one is $x$, the other $2x-5$; together $40$. Then $x=$", ["$15$", "$20$", "$45$", "$9$"], 0));
  q.push(mc("hard", "A plumber charges $45$ dollars plus $35$ dollars/h. A $220$-dollar job takes:", ["$5$ h", "$6$ h", "$4$ h", "$7$ h"], 0));
  q.push(mc("hard", "A test has $20$ questions worth $1$ or $3$ marks, total $46$. The number of 3-mark questions is:", ["$13$", "$7$", "$10$", "$6$"], 0));
  q.push(mc("hard", "Two angles are complementary ($90^\\circ$) and one is $30^\\circ$ larger. The larger is:", ["$60^\\circ$", "$30^\\circ$", "$45^\\circ$", "$75^\\circ$"], 0));
  q.push(mc("hard", "A jar of $12$ dimes and quarters is worth $2.10$ dollars. The number of quarters is:", ["$6$", "$5$", "$7$", "$8$"], 0));
  q.push(ms("hard", "For 'one is $x$, other $2x-5$, together 40':", ["$x+(2x-5)=40$", "$3x-5=40$", "$3x=45$", "$x=15$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which become a linear equation in one variable?", ["sum and a relationship between two numbers", "a fixed fee plus a rate", "consecutive integers summing to a total", "the area of a circle"], [0, 1, 2]));
  q.push(ms("hard", "Good context checks:", ["counts are whole numbers", "lengths are positive", "answer the question in words", "ignore the units"], [0, 1, 2]));
  q.push(ms("hard", "For the $20$-question / $46$-mark test ($x$ one-mark, $y$ three-mark):", ["$x+y=20$", "$x+3y=46$", "subtract to get $2y=26$", "$y=13$"], [0, 1, 2, 3]));
  q.push(tf("hard", "'One is $x$, the other $2x-5$, together 40' gives $x=15$.", true));
  q.push(tf("hard", "A $45+35h=220$ job takes $5$ hours.", true));
  q.push(tf("hard", "Complementary angles where one is $30^\\circ$ larger are $60^\\circ$ and $40^\\circ$.", false));
  q.push(fill("hard", "One number is $x$, the other $2x-5$; together $40$. Find $x$.", ["15"]));
  q.push(fill("hard", "A plumber $35h+45=220$: hours.", ["5"]));
  q.push(fill("hard", "A test: $x+y=20$, $x+3y=46$. Number of 3-mark questions.", ["13"]));
  q.push(num("hard", "Two numbers, one $x$, other $2x-5$, sum $40$: find $x$.", 15, 0));
  q.push(num("hard", "Complementary angles, one $30^\\circ$ larger: the larger (degrees).", 60, 0));
  q.push(num("hard", "A jar of $12$ dimes and quarters worth $2.10$ dollars: number of quarters.", 6, 0));
  q.push(order("hard", "Order the steps to solve a word problem with an equation.", ["Define a variable", "Write an equation", "Solve it", "State and check the answer"]));
  q.push(match("hard", "Match each problem to its equation.", ["one $x$, other $2x-5$, sum 40", "plumber 45 + 35/h, cost 220", "20 Q, 46 marks (1 or 3 each)"], ["$3x-5=40$", "$35h+45=220$", "$x+3y=46$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "1.1", gen: g11 },
  { code: "1.2", gen: g12 },
  { code: "1.3", gen: g13 },
  { code: "1.4", gen: g14 },
  { code: "1.5", gen: g15 },
  { code: "1.6", gen: g16 },
];
