// MFM2P Unit 2 — Linear Relations: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 2.1 Rate of Change & Slope ───────────────────────────────
function g21() {
  const q = [];
  q.push(mc("easy", "What is the slope of $y=2x+3$?", ["$2$", "$3$", "$-2$", "$1/2$"], 0));
  q.push(mc("easy", "Slope through $(0,0)$ and $(2,4)$?", ["$2$", "$1/2$", "$4$", "$-2$"], 0));
  q.push(mc("easy", "Slope through $(1,2)$ and $(4,8)$?", ["$2$", "$3$", "$6$", "$1/2$"], 0));
  q.push(mc("easy", "The slope of a horizontal line is:", ["$0$", "undefined", "$1$", "positive"], 0));
  q.push(mc("easy", "Slope through $(-2,5)$ and $(2,-3)$?", ["$-2$", "$2$", "$-1/2$", "$-8$"], 0));
  q.push(mc("easy", "Slope is rise over:", ["run", "slope", "$y$", "$x^2$"], 0));
  q.push(ms("easy", "Which have slope $3$?", ["$y=3x+1$", "through $(0,0),(1,3)$", "$y=3x-2$", "$y=2x+3$"], [0, 1, 2]));
  q.push(ms("easy", "Which have slope $0$?", ["$y=4$", "through $(1,5),(6,5)$", "horizontal lines", "vertical lines"], [0, 1, 2]));
  q.push(ms("easy", "Slope measures:", ["a rate of change", "steepness", "direction (its sign)", "the $y$-intercept"], [0, 1, 2]));
  q.push(ms("easy", "From a table with even $x$-steps:", ["$m=\\Delta y/\\Delta x$", "it is constant for a line", "you need two rows", "$m=y_1$"], [0, 1, 2]));
  q.push(tf("easy", "A vertical line has an undefined slope.", true));
  q.push(tf("easy", "The slope through $(1,4)$ and $(5,4)$ is $0$.", true));
  q.push(tf("easy", "Slope is run over rise.", false));
  q.push(fill("easy", "Slope through $(1,2)$ and $(3,8)$.", ["3"]));
  q.push(fill("easy", "Slope through $(2,5)$ and $(6,1)$.", ["-1"]));
  q.push(fill("easy", "From $x:0,1,2$, $y:5,8,11$, the slope is ___.", ["3"]));
  q.push(num("easy", "Slope through $(0,1)$ and $(3,7)$.", 2, 0));
  q.push(num("easy", "Slope through $(-1,-1)$ and $(2,5)$.", 2, 0));
  q.push(num("easy", "A candle burns from $20$ cm to $8$ cm in $4$ h; the rate (signed) is ___ cm/h.", -3, 0));
  q.push(match("easy", "Match each pair to its slope.", ["$(0,0),(1,2)$", "$(0,0),(2,2)$", "$(1,4),(5,4)$"], ["$2$", "$1$", "$0$"], [0, 1, 2]));
  q.push(mc("medium", "Slope through $(-2,5)$ and $(2,-3)$?", ["$-2$", "$2$", "$-1/2$", "$8$"], 0));
  q.push(mc("medium", "Slope through $(3,2)$ and $(3,9)$?", ["undefined", "$0$", "$7$", "$3$"], 0));
  q.push(mc("medium", "A pool fills $30$ L to $150$ L in $8$ min. The rate is:", ["$15$ L/min", "$120$", "$18.75$", "$-15$"], 0));
  q.push(mc("medium", "Slope through $(-4,3)$ and $(2,0)$?", ["$-1/2$", "$1/2$", "$-2$", "$-3$"], 0));
  q.push(mc("medium", "Which slope is the steepest?", ["$m=3$", "$m=1$", "$m=-1$", "$m=0$"], 0));
  q.push(mc("medium", "A line that falls left to right has slope:", ["negative", "positive", "zero", "undefined"], 0));
  q.push(ms("medium", "Which pairs give slope $-2$?", ["$(0,0),(1,-2)$", "$(-2,5),(2,-3)$", "$(1,1),(2,-1)$", "$(0,0),(2,2)$"], [0, 1, 2]));
  q.push(ms("medium", "Which have an undefined slope?", ["$x=3$", "$(2,1),(2,7)$", "vertical lines", "$y=3$"], [0, 1, 2]));
  q.push(ms("medium", "For $x:0,2,4$, $y:1,7,13$:", ["$\\Delta y=6$ per $\\Delta x=2$", "$m=3$", "it is linear", "$m=6$"], [0, 1, 2]));
  q.push(ms("medium", "A rate of change in context:", ["has units", "e.g. km/h", "its sign shows increase/decrease", "is always positive"], [0, 1, 2]));
  q.push(tf("medium", "A larger $|m|$ is steeper.", true));
  q.push(tf("medium", "The slope through $(-4,3)$ and $(2,0)$ is $-1/2$.", true));
  q.push(tf("medium", "The slope of a vertical line is $0$.", false));
  q.push(fill("medium", "Slope through $(2,5)$ and $(6,1)$.", ["-1"]));
  q.push(fill("medium", "Slope through $(-2,1)$ and $(4,-2)$.", ["-1/2", "-0.5"]));
  q.push(fill("medium", "A car travels $240$ km in $3$ h; the rate is ___ km/h.", ["80"]));
  q.push(num("medium", "Slope through $(-2,5)$ and $(2,-3)$.", -2, 0));
  q.push(num("medium", "A tank drains $100$ L to $20$ L in $4$ min; the rate is ___ L/min.", -20, 0));
  q.push(num("medium", "Slope through $(0,0)$ and $(5,2)$ (decimal).", 0.4, 0));
  q.push(match("medium", "Match each pair to its slope.", ["$(-2,5),(2,-3)$", "$(-4,3),(2,0)$", "$(3,2),(3,9)$"], ["$-2$", "$-1/2$", "undefined"], [0, 1, 2]));
  q.push(mc("hard", "Points $(1,k)$ and $(3,11)$ have slope $4$. Find $k$.", ["$3$", "$7$", "$19$", "$5$"], 0));
  q.push(mc("hard", "A line has slope $2$; if $x$ increases by $5$, $y$ changes by:", ["$+10$", "$+2$", "$+5$", "$+7$"], 0));
  q.push(mc("hard", "Points $(a,3)$ and $(5,1)$ have slope $-1$. Find $a$.", ["$3$", "$7$", "$2$", "$-3$"], 0));
  q.push(mc("hard", "Points $(2,7)$ and $(6,7)$ lie on a line that is:", ["horizontal, slope $0$", "vertical", "slope $1$", "undefined"], 0));
  q.push(mc("hard", "A ramp rises $2$ over a run of $8$. Its slope is:", ["$1/4$", "$4$", "$2$", "$1/2$"], 0));
  q.push(ms("hard", "For slope through two points:", ["subtract $y$'s and $x$'s in the same order", "$\\dfrac{y_2-y_1}{x_2-x_1}$", "same value either order", "it is run over rise"], [0, 1, 2]));
  q.push(ms("hard", "Which give slope $0$?", ["$(1,4),(9,4)$", "$y=-2$", "$(0,3),(5,3)$", "$(2,1),(2,9)$"], [0, 1, 2]));
  q.push(ms("hard", "If $y$ decreases as $x$ increases:", ["the slope is negative", "the line falls", "$m<0$", "$m>0$"], [0, 1, 2]));
  q.push(ms("hard", "Rate-of-change applications:", ["speed $=$ distance/time", "cost per item", "temperature change per hour", "area of a rectangle"], [0, 1, 2]));
  q.push(tf("hard", "A line through $(2,5)$ and $(2,9)$ has an undefined slope.", true));
  q.push(tf("hard", "A line through $(1,4)$ and $(6,4)$ has slope $0$.", true));
  q.push(tf("hard", "If slope is $3$ and $x$ increases by $2$, $y$ increases by $5$.", false));
  q.push(fill("hard", "Points $(1,k),(3,11)$ have slope $4$; $k=$ ___.", ["3"]));
  q.push(fill("hard", "Points $(a,3),(5,1)$ have slope $-1$; $a=$ ___.", ["3"]));
  q.push(fill("hard", "A line slope $-3$; if $x$ increases by $4$, $y$ changes by ___.", ["-12"]));
  q.push(num("hard", "Slope through $(-3,4)$ and $(2,-6)$.", -2, 0));
  q.push(num("hard", "If $y=2x+1$, the slope is ___.", 2, 0));
  q.push(num("hard", "Slope through $(0,0)$ and $(4,10)$ (decimal).", 2.5, 0));
  q.push(order("hard", "Order the steps to find slope from two points.", ["Label $(x_1,y_1)$ and $(x_2,y_2)$", "Compute $y_2-y_1$", "Compute $x_2-x_1$", "Divide to get $m$"]));
  q.push(match("hard", "Match each description to its slope.", ["rises $3$ per $1$ across", "falls $1$ per $1$ across", "horizontal"], ["$3$", "$-1$", "$0$"], [0, 1, 2]));
  return q;
}

// ── 2.2 Direct & Partial Variation ───────────────────────────
function g22() {
  const q = [];
  q.push(mc("easy", "$y=4x$ is:", ["direct variation", "partial variation", "neither", "quadratic"], 0));
  q.push(mc("easy", "$y=3x+5$ is:", ["partial variation", "direct variation", "neither", "constant"], 0));
  q.push(mc("easy", "Direct variation passes through:", ["the origin", "$(0,5)$", "$(1,0)$", "$(0,1)$"], 0));
  q.push(mc("easy", "In $y=kx$, $k$ is the:", ["constant of variation", "$y$-intercept", "exponent", "fixed fee"], 0));
  q.push(mc("easy", "$y$ varies directly with $x$; $y=12$ at $x=3$. Then $k=$", ["$4$", "$36$", "$1/4$", "$9$"], 0));
  q.push(mc("easy", "Partial variation has the form:", ["$y=mx+b$", "$y=kx$", "$y=x^2$", "$x=a$"], 0));
  q.push(ms("easy", "Which are direct variation?", ["$y=2x$", "$y=-5x$", "$y=x+1$", "$y=3x+2$"], [0, 1]));
  q.push(ms("easy", "Which are partial variation?", ["$y=2x+1$", "$y=3x-4$", "$C=5v+20$", "$y=7x$"], [0, 1, 2]));
  q.push(ms("easy", "For $y=kx$:", ["it passes through the origin", "$k=y/x$", "it has a constant rate", "it has a fixed start value"], [0, 1, 2]));
  q.push(ms("easy", "A fixed fee plus a rate is:", ["partial variation", "$y=mx+b$", "e.g. a taxi fare", "direct variation"], [0, 1, 2]));
  q.push(tf("easy", "Direct variation passes through the origin.", true));
  q.push(tf("easy", "$y=3x+5$ is partial variation.", true));
  q.push(tf("easy", "$y=4x$ is partial variation.", false));
  q.push(fill("easy", "$y$ varies directly with $x$; $y=20$ at $x=4$. Then $k=$ ___.", ["5"]));
  q.push(fill("easy", "A gym charges $20$ dollars to join plus $5$ dollars/visit. Write $C=$ ___.", ["5v+20", "5x+20"]));
  q.push(fill("easy", "In $C=4n+8$, the fixed cost is ___.", ["8"]));
  q.push(num("easy", "$y$ varies directly; $y=18$ at $x=6$. Find $k$.", 3, 0));
  q.push(num("easy", "For $C=4n+8$ at $n=6$, find $C$.", 32, 0));
  q.push(num("easy", "Cost varies directly: $25$ dollars for $10$ L. Find the cost of $16$ L.", 40, 0));
  q.push(match("easy", "Match each equation to its type.", ["$y=4x$", "$y=3x+5$", "$y=-2x$"], ["direct", "partial", "direct"], [0, 1, 2]));
  q.push(mc("medium", "$y$ varies directly; $y=15$ at $x=5$. The equation is:", ["$y=3x$", "$y=5x$", "$y=15x$", "$y=x/3$"], 0));
  q.push(mc("medium", "A printer costs $60$ dollars plus $0.10$ dollars/page. $C=$", ["$0.10p+60$", "$60p+0.10$", "$0.10p$", "$60+p$"], 0));
  q.push(mc("medium", "For $C=2.5x+12$, the fixed cost is:", ["$12$", "$2.5$", "$14.5$", "$0$"], 0));
  q.push(mc("medium", "$C=2x$ vs $C=x+10$ at $x=5$: cheaper is:", ["$C=2x$ ($10$)", "$C=x+10$ ($15$)", "equal", "cannot tell"], 0));
  q.push(mc("medium", "$y=kx$ with $k=7$: at $x=4$, $y=$", ["$28$", "$11$", "$7/4$", "$4$"], 0));
  q.push(mc("medium", "A direct-variation graph is a line through the origin with slope:", ["$k$", "$b$", "$0$", "undefined"], 0));
  q.push(ms("medium", "For $y=3x+5$:", ["it is partial", "initial value $5$", "rate $3$", "through the origin"], [0, 1, 2]));
  q.push(ms("medium", "Which pass through the origin?", ["$y=2x$", "$y=-3x$", "$y=x$", "$y=x+1$"], [0, 1, 2]));
  q.push(ms("medium", "To write a partial model:", ["use the fixed value as $b$", "use the rate as $m$", "write $y=mx+b$", "find $k=y/x$"], [0, 1, 2]));
  q.push(ms("medium", "Which are real partial-variation models?", ["taxi: flat fee + per km", "gym: join fee + per visit", "phone: fee + per minute", "perimeter of a square"], [0, 1, 2]));
  q.push(tf("medium", "A direct-variation graph passes through the origin.", true));
  q.push(tf("medium", "In $C=2.5x+12$, the rate is $2.5$ per unit.", true));
  q.push(tf("medium", "In $C=4n+8$, the fixed cost is $4$.", false));
  q.push(fill("medium", "$y$ varies directly; $y=20$ at $x=4$. Write $y=$ ___.", ["5x"]));
  q.push(fill("medium", "Printer $60$ dollars $+ 0.10$ dollars/page, $300$ pages: cost ___ dollars.", ["90"]));
  q.push(fill("medium", "$C=4n+8$ at $n=6$: ___ dollars.", ["32"]));
  q.push(num("medium", "$y=kx$; $y=18$ at $x=6$. Find $y$ at $x=10$.", 30, 0));
  q.push(num("medium", "Cost varies directly: $9$ dollars for $3$ kg. Find the cost of $7$ kg.", 21, 0));
  q.push(num("medium", "$C=2x$ and $C=x+10$ are equal at $x=$ ___.", 10, 0));
  q.push(match("medium", "Match each model to its fixed cost.", ["$C=5v+20$", "$C=2.5x+12$", "$C=0.10p+60$"], ["$20$", "$12$", "$60$"], [0, 1, 2]));
  q.push(mc("hard", "$y$ varies directly; $y=21$ at $x=3$. Find $y$ at $x=8$.", ["$56$", "$24$", "$7$", "$48$"], 0));
  q.push(mc("hard", "$C=3x$ and $C=2x+6$ are equal at:", ["$x=6$", "$x=3$", "$x=2$", "$x=9$"], 0));
  q.push(mc("hard", "A line through the origin and $(4,10)$:", ["$y=2.5x$", "$y=10x$", "$y=0.4x$", "$y=4x$"], 0));
  q.push(mc("hard", "In direct variation, doubling $x$ doubles $y$ because:", ["it is proportional ($y/x=k$)", "$k$ changes", "$b\\ne0$", "it is partial"], 0));
  q.push(mc("hard", "Gym A is $8$ dollars/visit; Gym B is $5$ dollars/visit plus a join fee, equal at $4$ visits. The fee is:", ["$12$", "$8$", "$20$", "$3$"], 0));
  q.push(ms("hard", "For direct variation $y=kx$:", ["it is proportional", "through the origin", "$k=y/x$", "it has a fixed start"], [0, 1, 2]));
  q.push(ms("hard", "Which equal $y=3x$ (direct, $k=3$)?", ["through $(1,3)$", "through the origin", "$y/x=3$", "through $(0,3)$"], [0, 1, 2]));
  q.push(ms("hard", "Comparing two cost models:", ["set them equal for the break-even", "test a value on each side", "graph both", "they never cross"], [0, 1, 2]));
  q.push(ms("hard", "Partial vs direct:", ["partial has $b\\ne0$", "direct has $b=0$", "both are linear", "direct passes through the origin"], [0, 1, 2, 3]));
  q.push(tf("hard", "In direct variation, doubling $x$ doubles $y$.", true));
  q.push(tf("hard", "Two plans cost the same at their break-even point.", true));
  q.push(tf("hard", "A partial-variation graph passes through the origin.", false));
  q.push(fill("hard", "$y$ varies directly; $y=21$ at $x=3$. Find $y$ at $x=8$.", ["56"]));
  q.push(fill("hard", "$C=3x$ and $C=2x+6$ are equal at $x=$ ___.", ["6"]));
  q.push(fill("hard", "A line through the origin and $(4,10)$: $y=$ ___.", ["2.5x", "5/2x"]));
  q.push(num("hard", "$y$ varies directly; $y=21$ at $x=3$. Find $y$ at $x=8$.", 56, 0));
  q.push(num("hard", "$C=3x$ and $C=2x+6$ are equal at $x=$ ___.", 6, 0));
  q.push(num("hard", "Cost varies directly: $9$ dollars for $3$ kg. Find the cost of $7$ kg.", 21, 0));
  q.push(order("hard", "Order the steps to find a direct-variation equation from a point.", ["Write $y=kx$", "Substitute the point", "Solve for $k$", "Write the final $y=kx$"]));
  q.push(match("hard", "Match each scenario to its equation.", ["direct, $y=21$ at $x=3$", "gym: join $20$ + $5$/visit", "printer: $60$ + $0.10$/page"], ["$y=7x$", "$C=5v+20$", "$C=0.10p+60$"], [0, 1, 2]));
  return q;
}

// ── 2.3 Slope–Intercept Form ─────────────────────────────────
function g23() {
  const q = [];
  q.push(mc("easy", "State the slope and $y$-intercept of $y=-3x+5$.", ["slope $-3$, intercept $5$", "slope $5$, intercept $-3$", "slope $3$, intercept $5$", "slope $-3$, intercept $-5$"], 0));
  q.push(mc("easy", "Write the line with slope $4$ and $y$-intercept $-2$.", ["$y=4x-2$", "$y=-2x+4$", "$y=4x+2$", "$y=2x-4$"], 0));
  q.push(mc("easy", "In $y=mx+b$, $b$ is the:", ["$y$-intercept", "slope", "$x$-intercept", "origin"], 0));
  q.push(mc("easy", "The $y$-intercept of $y=2x-7$ is:", ["$-7$", "$2$", "$7$", "$0$"], 0));
  q.push(mc("easy", "Write $2x+y=5$ as $y=mx+b$.", ["$y=-2x+5$", "$y=2x+5$", "$y=-2x-5$", "$y=5x$"], 0));
  q.push(mc("easy", "In $y=mx+b$, $m$ is the:", ["slope", "$y$-intercept", "constant", "$x$"], 0));
  q.push(ms("easy", "For $y=5x-1$:", ["slope $5$", "$y$-intercept $-1$", "through $(0,-1)$", "slope $-1$"], [0, 1, 2]));
  q.push(ms("easy", "Which are in slope-intercept form?", ["$y=2x+3$", "$y=-x$", "$2x+y=4$", "$y=\\tfrac12x-1$"], [0, 1, 3]));
  q.push(ms("easy", "To write standard form as $y=mx+b$:", ["isolate $y$", "divide every term", "read $m$ and $b$", "multiply by $x$"], [0, 1, 2]));
  q.push(ms("easy", "The $y$-intercept is where:", ["$x=0$", "the line meets the $y$-axis", "$b$ in $y=mx+b$", "$y=0$"], [0, 1, 2]));
  q.push(tf("easy", "In $y=mx+b$, $m$ is the slope.", true));
  q.push(tf("easy", "$y=-2x+5$ has $y$-intercept $5$.", true));
  q.push(tf("easy", "In $y=mx+b$, $b$ is the slope.", false));
  q.push(fill("easy", "The slope of $y=4x-7$ is ___.", ["4"]));
  q.push(fill("easy", "The $y$-intercept of $y=-3x+6$ is ___.", ["6"]));
  q.push(fill("easy", "Write the line with slope $-2$, $y$-intercept $3$: $y=$ ___.", ["-2x+3", "-2x + 3"]));
  q.push(num("easy", "For $y=2x-4$, find $y$ at $x=3$.", 2, 0));
  q.push(num("easy", "The $y$-intercept of $4x+2y=10$ is ___.", 5, 0));
  q.push(num("easy", "The slope of $6x-3y=9$ is ___.", 2, 0));
  q.push(match("easy", "Match each line to its slope.", ["$y=3x-2$", "$y=-x+5$", "$y=\\tfrac12x$"], ["$3$", "$-1$", "$\\tfrac12$"], [0, 1, 2]));
  q.push(mc("medium", "Write $4x-2y=6$ as $y=mx+b$.", ["$y=2x-3$", "$y=-2x+3$", "$y=2x+3$", "$y=4x-6$"], 0));
  q.push(mc("medium", "Slope and $y$-intercept of $y=-x+6$:", ["slope $-1$, intercept $6$", "slope $1$, intercept $6$", "slope $-1$, intercept $-6$", "slope $6$"], 0));
  q.push(mc("medium", "Write the line with slope $1/3$ and $y$-intercept $-2$.", ["$y=\\tfrac13x-2$", "$y=-2x+\\tfrac13$", "$y=\\tfrac13x+2$", "$y=3x-2$"], 0));
  q.push(mc("medium", "Write $3x+y=7$ as $y=mx+b$.", ["$y=-3x+7$", "$y=3x+7$", "$y=-3x-7$", "$y=7x$"], 0));
  q.push(mc("medium", "In $C=0.10t+15$, the $0.10$ means:", ["cost per minute", "fixed fee", "total cost", "minutes"], 0));
  q.push(mc("medium", "Write $6x-3y=9$ as $y=mx+b$.", ["$y=2x-3$", "$y=-2x+3$", "$y=2x+3$", "$y=6x-9$"], 0));
  q.push(ms("medium", "For $y=-3x+5$:", ["slope $-3$", "$y$-intercept $5$", "it falls left to right", "through $(0,5)$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Which equal $y=2x-3$?", ["$4x-2y=6$", "$6x-3y=9$", "$2x-y=3$", "$y=-2x+3$"], [0, 1, 2]));
  q.push(ms("medium", "Reading a context model $C=mt+b$:", ["$m$ is the rate", "$b$ is the fixed fee", "at $t=0$, $C=b$", "$m$ is the total"], [0, 1, 2]));
  q.push(ms("medium", "To graph from $y=mx+b$:", ["plot $(0,b)$", "step the slope", "draw the line", "find $x^2$"], [0, 1, 2]));
  q.push(tf("medium", "$4x-2y=6$ becomes $y=2x-3$.", true));
  q.push(tf("medium", "The $y$-intercept of $y=2x-7$ is $-7$.", true));
  q.push(tf("medium", "To isolate $y$ you divide only the $x$-term.", false));
  q.push(fill("medium", "Write $4x-2y=6$: $y=$ ___.", ["2x-3", "2x - 3"]));
  q.push(fill("medium", "Write $3x+y=7$: $y=$ ___.", ["-3x+7", "-3x + 7"]));
  q.push(fill("medium", "The $y$-intercept of $5x+y=2$ is ___.", ["2"]));
  q.push(num("medium", "For $y=3x-5$, find $y$ at $x=4$.", 7, 0));
  q.push(num("medium", "The $y$-intercept of $6x-3y=9$ is ___.", -3, 0));
  q.push(num("medium", "The slope of $2x+y=5$ is ___.", -2, 0));
  q.push(match("medium", "Match each standard form to its $y=mx+b$.", ["$2x+y=5$", "$4x-2y=6$", "$x+2y=6$"], ["$y=-2x+5$", "$y=2x-3$", "$y=-\\tfrac12x+3$"], [0, 1, 2]));
  q.push(mc("hard", "Write $5x-2y=10$ as $y=mx+b$.", ["$y=\\tfrac52x-5$", "$y=-\\tfrac52x+5$", "$y=\\tfrac52x+5$", "$y=5x-10$"], 0));
  q.push(mc("hard", "A line slope $2$ through $(0,-4)$: $y$ at $x=3$ is:", ["$2$", "$-4$", "$6$", "$10$"], 0));
  q.push(mc("hard", "$y=2x+1$ and $y=2x-3$ are:", ["parallel", "perpendicular", "intersecting", "the same line"], 0));
  q.push(mc("hard", "The $x$-intercept of $y=-\\tfrac34x+2$ is:", ["$\\tfrac83$", "$2$", "$-\\tfrac34$", "$\\tfrac34$"], 0));
  q.push(mc("hard", "Convert $y=-\\tfrac12x+4$ to standard $Ax+By=C$ (integers).", ["$x+2y=8$", "$x-2y=4$", "$2x+y=8$", "$x+2y=4$"], 0));
  q.push(ms("hard", "For $y=\\tfrac52x-5$:", ["slope $5/2$", "$y$-intercept $-5$", "comes from $5x-2y=10$", "slope $-5$"], [0, 1, 2]));
  q.push(ms("hard", "Which are parallel to $y=2x+1$?", ["$y=2x-3$", "$4x-2y=6$", "$y=2x$", "$y=-2x$"], [0, 1, 2]));
  q.push(ms("hard", "To convert $y=mx+b$ to integer standard form:", ["clear fractions", "move the $x$-term across", "use integer coefficients", "keep a fraction"], [0, 1, 2]));
  q.push(ms("hard", "In $C=0.05t+20$:", ["rate $0.05$/min", "fixed fee $20$", "at $t=0$, $C=20$", "the total is always $20$"], [0, 1, 2]));
  q.push(tf("hard", "$5x-2y=10$ becomes $y=\\tfrac52x-5$.", true));
  q.push(tf("hard", "Lines with equal slope and different intercepts are parallel.", true));
  q.push(tf("hard", "$y=-\\tfrac12x+4$ has $x$-intercept $4$.", false));
  q.push(fill("hard", "Write $5x-2y=10$: $y=$ ___.", ["5/2x-5", "2.5x-5", "\\dfrac{5}{2}x-5"]));
  q.push(fill("hard", "The $x$-intercept of $y=2x-6$ is ___.", ["3"]));
  q.push(fill("hard", "A line slope $2$ through $(0,-4)$: $y=$ ___.", ["2x-4", "2x - 4"]));
  q.push(num("hard", "For $y=\\tfrac52x-5$, find $y$ at $x=4$.", 5, 0));
  q.push(num("hard", "The $x$-intercept of $y=-\\tfrac34x+2$ (2 dp).", 2.67, 0.02));
  q.push(num("hard", "The slope of $5x-2y=10$ (decimal).", 2.5, 0));
  q.push(order("hard", "Order the steps to write standard form as $y=mx+b$.", ["Isolate the $y$-term", "Divide every term by the $y$-coefficient", "Simplify", "Read off $m$ and $b$"]));
  q.push(match("hard", "Match each line to its $x$-intercept.", ["$y=2x-6$", "$y=-x+4$", "$y=\\tfrac12x-2$"], ["$3$", "$4$", "$4$"], [0, 1, 2]));
  return q;
}

// ── 2.4 Graphing Lines ───────────────────────────────────────
function g24() {
  const q = [];
  q.push(mc("easy", "To graph $y=mx+b$, start at:", ["$(0,b)$", "$(b,0)$", "the origin", "$(m,b)$"], 0));
  q.push(mc("easy", "For $y=2x-3$, the $y$-intercept point is:", ["$(0,-3)$", "$(0,3)$", "$(-3,0)$", "$(0,2)$"], 0));
  q.push(mc("easy", "The $x$-intercept of $2x+3y=6$ is:", ["$(3,0)$", "$(0,3)$", "$(2,0)$", "$(0,2)$"], 0));
  q.push(mc("easy", "$y=4$ is a:", ["horizontal line", "vertical line", "slanted line", "point"], 0));
  q.push(mc("easy", "$x=-2$ is a:", ["vertical line", "horizontal line", "slanted line", "point"], 0));
  q.push(mc("easy", "From $(0,b)$, the slope tells you:", ["how to step to a second point", "the intercept", "nothing", "the $x$-axis"], 0));
  q.push(ms("easy", "To graph $y=2x-3$:", ["plot $(0,-3)$", "up $2$, right $1$", "draw the line", "plot $(-3,0)$"], [0, 1, 2]));
  q.push(ms("easy", "Intercepts of $2x+3y=6$:", ["$(0,2)$", "$(3,0)$", "set $x=0$ then $y=0$", "$(2,3)$"], [0, 1, 2]));
  q.push(ms("easy", "Which are points on $y=x+2$?", ["$(0,2)$", "$(1,3)$", "$(2,4)$", "$(2,0)$"], [0, 1, 2]));
  q.push(ms("easy", "Horizontal and vertical lines:", ["$y=k$ is horizontal", "$x=a$ is vertical", "slope $0$ is horizontal", "$x=a$ is horizontal"], [0, 1, 2]));
  q.push(tf("easy", "Two points are enough to draw a line.", true));
  q.push(tf("easy", "$y=2x-3$ starts at $(0,-3)$.", true));
  q.push(tf("easy", "$y=3$ is a vertical line.", false));
  q.push(fill("easy", "The $y$-intercept of $y=2x-3$ is the point ___.", ["(0,-3)", "0,-3"]));
  q.push(fill("easy", "The $x$-intercept of $2x+3y=6$ is the point ___.", ["(3,0)", "3,0"]));
  q.push(fill("easy", "The intercepts of $x+2y=4$ are ___.", ["(4,0) and (0,2)", "(4,0),(0,2)", "(0,2),(4,0)"]));
  q.push(num("easy", "The $x$-intercept of $y=2x-6$ is ___.", 3, 0));
  q.push(num("easy", "The $y$-intercept of $3x+y=7$ is ___.", 7, 0));
  q.push(num("easy", "At $x=2$ on $y=3x-1$, $y=$ ___.", 5, 0));
  q.push(match("easy", "Match each line to its type.", ["$y=2x+1$", "$y=5$", "$x=-3$"], ["slanted", "horizontal", "vertical"], [0, 1, 2]));
  q.push(mc("medium", "A point on $y=-x+4$ is:", ["$(0,4)$", "$(4,4)$", "$(0,-4)$", "$(-4,0)$"], 0));
  q.push(mc("medium", "The $x$-intercept of $3x-4y=12$ is:", ["$(4,0)$", "$(0,4)$", "$(3,0)$", "$(0,-3)$"], 0));
  q.push(mc("medium", "The $y$-intercept of $3x-4y=12$ is:", ["$(0,-3)$", "$(0,3)$", "$(0,4)$", "$(0,-4)$"], 0));
  q.push(mc("medium", "To graph $y=\\tfrac23x-1$, from $(0,-1)$ step:", ["up $2$, right $3$", "up $3$, right $2$", "up $2$, right $1$", "down $2$, right $3$"], 0));
  q.push(mc("medium", "The line through $(0,5)$ and $(2,1)$ has slope:", ["$-2$", "$2$", "$-1$", "$3$"], 0));
  q.push(mc("medium", "For $y=-2x+1$, from $(0,1)$ step:", ["down $2$, right $1$", "up $2$, right $1$", "down $1$, right $2$", "up $1$"], 0));
  q.push(ms("medium", "Intercepts of $3x-4y=12$:", ["$(4,0)$", "$(0,-3)$", "set the other variable to $0$", "$(3,0)$"], [0, 1, 2]));
  q.push(ms("medium", "Two points on $y=-x+4$:", ["$(0,4)$", "$(4,0)$", "$(1,3)$", "$(0,-4)$"], [0, 1, 2]));
  q.push(ms("medium", "For $y=\\tfrac23x-1$:", ["start at $(0,-1)$", "rise $2$, run $3$", "through $(3,1)$", "through $(3,0)$"], [0, 1, 2]));
  q.push(ms("medium", "Best method per form:", ["intercepts for $Ax+By=C$", "slope-intercept for $y=mx+b$", "two points always work", "none of these work"], [0, 1, 2]));
  q.push(tf("medium", "$3x-4y=12$ has $x$-intercept $(4,0)$.", true));
  q.push(tf("medium", "The line through $(0,5),(2,1)$ has slope $-2$.", true));
  q.push(tf("medium", "$y=\\tfrac23x-1$ rises $3$ for every $2$ across.", false));
  q.push(fill("medium", "The intercepts of $3x-4y=12$ are ___.", ["(4,0) and (0,-3)", "(4,0),(0,-3)"]));
  q.push(fill("medium", "A point on $y=-x+4$ besides $(0,4)$ is ___.", ["(4,0)", "(1,3)"]));
  q.push(fill("medium", "The slope of the line through $(0,-2),(3,1)$ is ___.", ["1"]));
  q.push(num("medium", "The $x$-intercept of $3x-4y=12$ is ___.", 4, 0));
  q.push(num("medium", "The $y$-intercept of $3x-4y=12$ is ___.", -3, 0));
  q.push(num("medium", "At $x=3$ on $y=\\tfrac23x-1$, $y=$ ___.", 1, 0));
  q.push(match("medium", "Match each line to one intercept.", ["$2x+3y=6$", "$3x-4y=12$", "$x+2y=4$"], ["$(3,0)$", "$(4,0)$", "$(4,0)$"], [0, 1, 2]));
  q.push(mc("hard", "The line through $(0,5)$ and $(2,1)$ is:", ["$y=-2x+5$", "$y=2x+5$", "$y=-2x-5$", "$y=-x+5$"], 0));
  q.push(mc("hard", "Where does $y=2x-3$ cross the $x$-axis?", ["$(1.5,0)$", "$(0,-3)$", "$(3,0)$", "$(-1.5,0)$"], 0));
  q.push(mc("hard", "A line parallel to $y=2x-3$ through $(0,1)$ is:", ["$y=2x+1$", "$y=-2x+1$", "$y=\\tfrac12x+1$", "$y=2x-1$"], 0));
  q.push(mc("hard", "A vertical line through $(4,7)$ is:", ["$x=4$", "$y=7$", "$y=4$", "$x=7$"], 0));
  q.push(mc("hard", "The intercepts of $x+2y=4$ are:", ["$(4,0)$ and $(0,2)$", "$(0,4)$ and $(2,0)$", "$(4,0)$ and $(0,4)$", "$(2,0)$ and $(0,2)$"], 0));
  q.push(ms("hard", "For $3x-4y=12$:", ["$x$-intercept $(4,0)$", "$y$-intercept $(0,-3)$", "slope $3/4$", "passes the origin"], [0, 1, 2]));
  q.push(ms("hard", "Which graph as the same line?", ["$y=2x-3$", "$4x-2y=6$", "$6x-3y=9$", "$y=-2x+3$"], [0, 1, 2]));
  q.push(ms("hard", "To graph a vertical line $x=a$:", ["every point has $x=a$", "it is parallel to the $y$-axis", "its slope is undefined", "its slope is $0$"], [0, 1, 2]));
  q.push(ms("hard", "Steps to graph by intercepts:", ["set $x=0$ for the $y$-intercept", "set $y=0$ for the $x$-intercept", "plot both", "join them"], [0, 1, 2, 3]));
  q.push(tf("hard", "$x=4$ is a vertical line.", true));
  q.push(tf("hard", "$y=2x-3$ crosses the $x$-axis at $(1.5,0)$.", true));
  q.push(tf("hard", "$4x-2y=6$ and $y=2x-3$ are different lines.", false));
  q.push(fill("hard", "The line through $(0,5),(2,1)$: $y=$ ___.", ["-2x+5", "-2x + 5"]));
  q.push(fill("hard", "The $x$-intercept of $y=2x-3$ is ___.", ["1.5", "3/2"]));
  q.push(fill("hard", "A vertical line through $(4,7)$ is ___.", ["x=4"]));
  q.push(num("hard", "The $x$-intercept of $3x-4y=12$ is ___.", 4, 0));
  q.push(num("hard", "The $y$-intercept of $3x-4y=12$ is ___.", -3, 0));
  q.push(num("hard", "The slope of the line through $(0,5),(2,1)$ is ___.", -2, 0));
  q.push(order("hard", "Order the steps to graph $Ax+By=C$ by intercepts.", ["Set $x=0$, solve for $y$", "Set $y=0$, solve for $x$", "Plot both intercepts", "Draw the line"]));
  q.push(match("hard", "Match each line to its $x$-intercept.", ["$y=2x-6$", "$3x-4y=12$", "$x+2y=4$"], ["$(3,0)$", "$(4,0)$", "$(4,0)$"], [0, 1, 2]));
  return q;
}

// ── 2.5 Writing Equations of Lines ───────────────────────────
function g25() {
  const q = [];
  q.push(mc("easy", "Slope $3$ through $(0,5)$:", ["$y=3x+5$", "$y=5x+3$", "$y=3x-5$", "$y=3x$"], 0));
  q.push(mc("easy", "Slope $-2$ through $(3,1)$: the $y$-intercept $b$ is:", ["$7$", "$-5$", "$1$", "$5$"], 0));
  q.push(mc("easy", "Through $(1,2)$ and $(3,8)$, the slope is:", ["$3$", "$2$", "$6$", "$1/2$"], 0));
  q.push(mc("easy", "Through $(0,1)$ and $(2,7)$:", ["$y=3x+1$", "$y=3x-1$", "$y=2x+1$", "$y=x+1$"], 0));
  q.push(mc("easy", "If a point is on the $y$-axis, its $y$ is the:", ["$y$-intercept", "slope", "$x$-intercept", "origin"], 0));
  q.push(mc("easy", "To write a line from two points, first find:", ["the slope", "$b$", "the $x$-intercept", "nothing"], 0));
  q.push(ms("easy", "For slope $3$ through $(0,5)$:", ["$b=5$", "$y=3x+5$", "it passes $(0,5)$", "$b=3$"], [0, 1, 2]));
  q.push(ms("easy", "From $(1,2)$ and $(3,8)$:", ["slope $3$", "$y=3x-1$", "$b=-1$", "slope $2$"], [0, 1, 2]));
  q.push(ms("easy", "To write a line from slope + point:", ["use $y=mx+b$", "substitute to find $b$", "write the equation", "find $k=y/x$"], [0, 1, 2]));
  q.push(ms("easy", "Which pass through $(0,5)$?", ["$y=3x+5$", "$y=-x+5$", "$y=2x+5$", "$y=x-5$"], [0, 1, 2]));
  q.push(tf("easy", "From two points, find the slope first.", true));
  q.push(tf("easy", "Slope $3$ through $(0,5)$ is $y=3x+5$.", true));
  q.push(tf("easy", "If a point is on the $y$-axis, its $x$ is $b$.", false));
  q.push(fill("easy", "Slope $4$ through $(0,-2)$: $y=$ ___.", ["4x-2", "4x - 2"]));
  q.push(fill("easy", "Through $(1,1)$ and $(3,7)$: $y=$ ___.", ["3x-2", "3x - 2"]));
  q.push(fill("easy", "Through $(1,4)$ and $(3,4)$: $y=$ ___.", ["4"]));
  q.push(num("easy", "Slope $-2$ through $(3,1)$: find $b$.", 7, 0));
  q.push(num("easy", "Through $(1,2)$ and $(3,8)$: the slope.", 3, 0));
  q.push(num("easy", "Through $(0,1)$ and $(2,7)$: find $b$.", 1, 0));
  q.push(match("easy", "Match each to its equation.", ["slope $3$, $(0,5)$", "slope $-1$, $(0,2)$", "slope $2$, $(0,0)$"], ["$y=3x+5$", "$y=-x+2$", "$y=2x$"], [0, 1, 2]));
  q.push(mc("medium", "Slope $-2$ through $(3,1)$:", ["$y=-2x+7$", "$y=-2x-5$", "$y=-2x+1$", "$y=2x-7$"], 0));
  q.push(mc("medium", "Through $(1,2)$ and $(3,8)$:", ["$y=3x-1$", "$y=3x+1$", "$y=2x$", "$y=x+1$"], 0));
  q.push(mc("medium", "Through $(-2,1)$ and $(2,9)$:", ["$y=2x+5$", "$y=2x-5$", "$y=-2x+5$", "$y=4x+5$"], 0));
  q.push(mc("medium", "A candle is $20$ cm and burns $3$ cm/h. Height $h$ vs time $t$:", ["$h=-3t+20$", "$h=3t+20$", "$h=-3t-20$", "$h=20t-3$"], 0));
  q.push(mc("medium", "Through $(1,-1)$ and $(4,8)$:", ["$y=3x-4$", "$y=3x+4$", "$y=2x-3$", "$y=3x-1$"], 0));
  q.push(mc("medium", "Through $(-1,2)$ and $(2,-7)$:", ["$y=-3x-1$", "$y=-3x+1$", "$y=3x-1$", "$y=-x-1$"], 0));
  q.push(ms("medium", "Through $(1,2)$ and $(3,8)$:", ["slope $3$", "$1\\cdot3+b=2\\Rightarrow b=-1$", "$y=3x-1$", "slope $2$"], [0, 1, 2]));
  q.push(ms("medium", "Slope $-2$ through $(3,1)$:", ["$1=-2(3)+b$", "$b=7$", "$y=-2x+7$", "$b=-5$"], [0, 1, 2]));
  q.push(ms("medium", "Writing a real model:", ["the start value is $b$", "the rate is $m$", "$y=mt+b$", "ignore the start"], [0, 1, 2]));
  q.push(ms("medium", "Through $(1,4)$ and $(3,4)$:", ["slope $0$", "horizontal", "$y=4$", "slope $1$"], [0, 1, 2]));
  q.push(tf("medium", "Slope $-2$ through $(3,1)$ is $y=-2x+7$.", true));
  q.push(tf("medium", "A candle $20$ cm burning $3$ cm/h is $h=-3t+20$.", true));
  q.push(tf("medium", "Through $(1,2)$ and $(3,8)$ the equation is $y=3x+1$.", false));
  q.push(fill("medium", "Slope $-2$ through $(3,1)$: $y=$ ___.", ["-2x+7", "-2x + 7"]));
  q.push(fill("medium", "Through $(-2,1)$ and $(2,9)$: $y=$ ___.", ["2x+5", "2x + 5"]));
  q.push(fill("medium", "A tank starts at $50$ L and drains $5$ L/min: $V=$ ___.", ["-5t+50", "-5t + 50"]));
  q.push(num("medium", "Through $(1,-1)$ and $(4,8)$: the slope.", 3, 0));
  q.push(num("medium", "Through $(-1,2)$ and $(2,-7)$: find $b$.", -1, 0));
  q.push(num("medium", "Slope $2$ through $(-1,-3)$: find $b$.", -1, 0));
  q.push(match("medium", "Match each to its equation.", ["slope $-2$, $(3,1)$", "through $(1,2),(3,8)$", "through $(1,4),(3,4)$"], ["$y=-2x+7$", "$y=3x-1$", "$y=4$"], [0, 1, 2]));
  q.push(mc("hard", "Through $(2,5)$ and $(6,13)$:", ["$y=2x+1$", "$y=2x-1$", "$y=3x-1$", "$y=2x+5$"], 0));
  q.push(mc("hard", "Through $(-1,2)$ and $(2,-7)$:", ["$y=-3x-1$", "$y=-3x+1$", "$y=3x-1$", "$y=-x-1$"], 0));
  q.push(mc("hard", "A line parallel to $y=2x-3$ through $(1,4)$:", ["$y=2x+2$", "$y=2x-2$", "$y=-\\tfrac12x+4$", "$y=2x+4$"], 0));
  q.push(mc("hard", "The $x$-intercept of the line through $(0,6)$ with slope $-2$:", ["$3$", "$-3$", "$6$", "$12$"], 0));
  q.push(mc("hard", "Through $(0,-2)$ and $(5,8)$:", ["$y=2x-2$", "$y=2x+2$", "$y=\\tfrac12x-2$", "$y=-2x-2$"], 0));
  q.push(ms("hard", "Through $(2,5)$ and $(6,13)$:", ["slope $2$", "$b=1$", "$y=2x+1$", "slope $4$"], [0, 1, 2]));
  q.push(ms("hard", "Which pass through $(-1,2)$?", ["$y=-3x-1$", "$y=x+3$", "$y=2x+4$", "$y=x-3$"], [0, 1, 2]));
  q.push(ms("hard", "To find an $x$-intercept:", ["set $y=0$", "solve for $x$", "it is where the line meets the $x$-axis", "set $x=0$"], [0, 1, 2]));
  q.push(ms("hard", "A parallel line through a point:", ["same slope", "substitute the point to find $b$", "$y=mx+b$", "change the slope"], [0, 1, 2]));
  q.push(tf("hard", "Through $(2,5)$ and $(6,13)$ the line is $y=2x+1$.", true));
  q.push(tf("hard", "A line parallel to $y=2x-3$ through $(1,4)$ is $y=2x+2$.", true));
  q.push(tf("hard", "Through $(-1,2)$ and $(2,-7)$ the slope is $3$.", false));
  q.push(fill("hard", "Through $(2,5)$ and $(6,13)$: $y=$ ___.", ["2x+1", "2x + 1"]));
  q.push(fill("hard", "Through $(-1,2)$ and $(2,-7)$: $y=$ ___.", ["-3x-1", "-3x - 1"]));
  q.push(fill("hard", "Parallel to $y=2x-3$ through $(1,4)$: $y=$ ___.", ["2x+2", "2x + 2"]));
  q.push(num("hard", "Through $(2,5)$ and $(6,13)$: the slope.", 2, 0));
  q.push(num("hard", "Through $(0,-2)$ and $(5,8)$: the slope.", 2, 0));
  q.push(num("hard", "The $x$-intercept of the line through $(0,6)$ with slope $-2$.", 3, 0));
  q.push(order("hard", "Order the steps to write a line through two points.", ["Find the slope", "Substitute one point into $y=mx+b$", "Solve for $b$", "Write the equation"]));
  q.push(match("hard", "Match each to its equation.", ["through $(2,5),(6,13)$", "through $(-1,2),(2,-7)$", "parallel to $y=2x-3$ thru $(1,4)$"], ["$y=2x+1$", "$y=-3x-1$", "$y=2x+2$"], [0, 1, 2]));
  return q;
}

// ── 2.6 Interpreting Linear Models ───────────────────────────
function g26() {
  const q = [];
  q.push(mc("easy", "In $C=2d+3$, the rate is:", ["$2$", "$3$", "$5$", "$d$"], 0));
  q.push(mc("easy", "In $C=2d+3$, the fixed fee is:", ["$3$", "$2$", "$5$", "$0$"], 0));
  q.push(mc("easy", "To predict the cost at $d=10$:", ["substitute $d=10$", "solve for $d$", "graph it", "guess"], 0));
  q.push(mc("easy", "For $C=2d+3$ at $d=5$:", ["$13$", "$10$", "$8$", "$25$"], 0));
  q.push(mc("easy", "The intercept is the value when:", ["$x=0$", "$y=0$", "$x=1$", "slope $=0$"], 0));
  q.push(mc("easy", "A negative slope means the quantity is:", ["decreasing", "increasing", "constant", "zero"], 0));
  q.push(ms("easy", "In $C=2d+3$:", ["rate $2$/km", "fixed fee $3$", "at $d=0$, $C=3$", "the total is $3$"], [0, 1, 2]));
  q.push(ms("easy", "To predict an input from a model:", ["set the model equal to the output", "solve", "e.g. $2d+3=15$", "substitute the input"], [0, 1, 2]));
  q.push(ms("easy", "Slope in context:", ["a rate of change", "a per-unit amount", "has units", "the start value"], [0, 1, 2]));
  q.push(ms("easy", "Which are linear models?", ["$C=2d+3$", "$V=-5t+60$", "$h=-3t+20$", "$A=\\pi r^2$"], [0, 1, 2]));
  q.push(tf("easy", "In $C=2d+3$, the fixed fee is $3$.", true));
  q.push(tf("easy", "A negative slope means the quantity decreases.", true));
  q.push(tf("easy", "The intercept is the value when $y=0$.", false));
  q.push(fill("easy", "In $C=3h+25$, the fixed fee is ___.", ["25"]));
  q.push(fill("easy", "In $C=3h+25$, the rate is ___.", ["3"]));
  q.push(fill("easy", "For $C=3h+25$ at $h=4$: ___ dollars.", ["37"]));
  q.push(num("easy", "For $C=2d+3$ at $d=10$: ___ dollars.", 23, 0));
  q.push(num("easy", "For $C=3h+25$, find $h$ when $C=49$.", 8, 0));
  q.push(num("easy", "For $V=-5t+60$, find $V$ at $t=0$.", 60, 0));
  q.push(match("easy", "Match each part of $C=2d+3$ to its meaning.", ["the $2$", "the $3$", "at $d=0$"], ["rate per km", "fixed fee", "$C=3$"], [0, 1, 2]));
  q.push(mc("medium", "A pool $V=-20t+500$: the $-20$ means:", ["drains $20$ L/min", "fills $20$", "starts at $20$", "$500$ L"], 0));
  q.push(mc("medium", "$V=-20t+500$: when is it empty?", ["$t=25$", "$t=20$", "$t=500$", "never"], 0));
  q.push(mc("medium", "For $C=2d+3$, how far for $15$ dollars?", ["$6$ km", "$9$ km", "$7.5$ km", "$12$ km"], 0));
  q.push(mc("medium", "$C=0.05t+20$ at $t=0$:", ["$20$", "$0$", "$25$", "$0.05$"], 0));
  q.push(mc("medium", "Plan A $0.10t+10$, Plan B $0.05t+20$ at $t=100$: cheaper is:", ["A ($20$)", "B ($25$)", "equal", "cannot tell"], 0));
  q.push(mc("medium", "For $h=-5t+60$, when is $h=0$?", ["$t=12$", "$t=60$", "$t=5$", "$t=300$"], 0));
  q.push(ms("medium", "For $V=-20t+500$:", ["drains $20$ L/min", "starts at $500$ L", "empty at $t=25$", "fills up"], [0, 1, 2]));
  q.push(ms("medium", "To predict an input:", ["set the model $=$ output", "solve the equation", "e.g. $2d+3=15\\Rightarrow d=6$", "substitute the input as the output"], [0, 1, 2]));
  q.push(ms("medium", "Comparing two plans:", ["find the break-even", "test each side", "graph both", "they never cross"], [0, 1, 2]));
  q.push(ms("medium", "In a cost model:", ["slope $=$ rate", "intercept $=$ fixed fee", "predict by substitution", "intercept $=$ total"], [0, 1, 2]));
  q.push(tf("medium", "$V=-20t+500$ is empty at $t=25$.", true));
  q.push(tf("medium", "For $C=0.05t+20$ at $t=0$, $C=20$.", true));
  q.push(tf("medium", "In $C=2d+3$, doubling $d$ doubles $C$.", false));
  q.push(fill("medium", "$V=-5t+60$: when is $V=0$? $t=$ ___.", ["12"]));
  q.push(fill("medium", "$C=2d+3$: distance for $15$ dollars is ___ km.", ["6"]));
  q.push(fill("medium", "$C=3h+25$: find $h$ when $C=49$.", ["8"]));
  q.push(num("medium", "$V=-20t+500$ is empty at $t=$ ___.", 25, 0));
  q.push(num("medium", "$C=2d+3$ at $d=10$: ___ dollars.", 23, 0));
  q.push(num("medium", "$C=0.05t+20$ at $t=100$: ___ dollars.", 25, 0));
  q.push(match("medium", "Match each model to its slope's meaning.", ["$V=-20t+500$", "$C=2d+3$", "$h=-3t+20$"], ["drains $20$/min", "$2$ per km", "falls $3$ per hour"], [0, 1, 2]));
  q.push(mc("hard", "Plan A $0.10t+10$, Plan B $0.05t+20$ are equal at:", ["$t=200$", "$t=100$", "$t=50$", "$t=300$"], 0));
  q.push(mc("hard", "A pool $V=-25t+400$ is empty at:", ["$t=16$", "$t=25$", "$t=400$", "$t=10$"], 0));
  q.push(mc("hard", "For $C=1.5x+8$, the rate is:", ["$1.5$ per unit", "$8$", "$9.5$", "$0$"], 0));
  q.push(mc("hard", "A candle $h=-3t+20$ burns out at:", ["$t\\approx6.67$", "$t=20$", "$t=3$", "$t=60$"], 0));
  q.push(mc("hard", "$y=2x+5$ and $y=-x+20$ meet where?", ["$(5,15)$", "$(15,5)$", "$(3,11)$", "$(5,25)$"], 0));
  q.push(ms("hard", "For Plan A $0.10t+10$ vs B $0.05t+20$:", ["equal when $0.10t+10=0.05t+20$", "$t=200$", "A is cheaper before $200$", "B is cheaper before $200$"], [0, 1, 2]));
  q.push(ms("hard", "Interpreting $V=-25t+400$:", ["drains $25$/min", "starts at $400$ L", "empty at $16$ min", "fills"], [0, 1, 2]));
  q.push(ms("hard", "To find where two linear models meet:", ["set them equal", "solve for $x$", "substitute for $y$", "it is never possible"], [0, 1, 2]));
  q.push(ms("hard", "In $C=1.5x+8$:", ["rate $1.5$/unit", "fixed fee $8$", "at $x=0$, $C=8$", "the total is $8$"], [0, 1, 2]));
  q.push(tf("hard", "Plans $0.10t+10$ and $0.05t+20$ are equal at $t=200$.", true));
  q.push(tf("hard", "$V=-25t+400$ is empty at $t=16$.", true));
  q.push(tf("hard", "$C=1.5x+8$ has a fixed fee of $1.5$.", false));
  q.push(fill("hard", "Plans $0.10t+10$ and $0.05t+20$ are equal at $t=$ ___.", ["200"]));
  q.push(fill("hard", "$V=-25t+400$ is empty at $t=$ ___.", ["16"]));
  q.push(fill("hard", "$y=2x+5$ and $y=-x+20$ meet at ___.", ["(5,15)", "5,15"]));
  q.push(num("hard", "Plans $0.10t+10$, $0.05t+20$ equal at $t=$ ___.", 200, 0));
  q.push(num("hard", "$V=-25t+400$ empty at $t=$ ___.", 16, 0));
  q.push(num("hard", "$y=2x+5$, $y=-x+20$: the $x$ at intersection.", 5, 0));
  q.push(order("hard", "Order the steps to find when two cost models are equal.", ["Set the two expressions equal", "Collect the variable on one side", "Solve for the variable", "Interpret the break-even value"]));
  q.push(match("hard", "Match each model to its key value.", ["$V=-25t+400$ empty", "$0.10t+10=0.05t+20$", "$C=1.5x+8$ fixed fee"], ["$t=16$", "$t=200$", "$8$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "2.1", gen: g21 },
  { code: "2.2", gen: g22 },
  { code: "2.3", gen: g23 },
  { code: "2.4", gen: g24 },
  { code: "2.5", gen: g25 },
  { code: "2.6", gen: g26 },
];
