// MFM2P Unit 4 — Measurement: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 4.1 Measurement Systems & Unit Conversion ────────────────
function g41() {
  const q = [];
  q.push(mc("easy", "Convert $3.5$ m to cm.", ["$350$", "$0.035$", "$35$", "$3500$"], 0));
  q.push(mc("easy", "Convert $2500$ mL to L.", ["$2.5$", "$2500000$", "$25$", "$0.25$"], 0));
  q.push(mc("easy", "Convert $5$ ft to inches.", ["$60$", "$17$", "$15$", "$120$"], 0));
  q.push(mc("easy", "$1$ in equals how many cm?", ["$2.54$", "$1.6$", "$12$", "$2.2$"], 0));
  q.push(mc("easy", "To convert to a larger unit, you:", ["divide", "multiply", "add", "square"], 0));
  q.push(mc("easy", "Convert $8$ km to miles ($\\div1.6$).", ["$5$", "$12.8$", "$10$", "$4$"], 0));
  q.push(ms("easy", "Metric facts:", ["$1$ m $=100$ cm", "$1$ km $=1000$ m", "$1$ L $=1000$ mL", "$1$ ft $=12$ in"], [0, 1, 2]));
  q.push(ms("easy", "Imperial facts:", ["$1$ ft $=12$ in", "$1$ yd $=3$ ft", "$1$ lb $=16$ oz", "$1$ m $=100$ cm"], [0, 1, 2]));
  q.push(ms("easy", "Between systems:", ["$1$ in $=2.54$ cm", "$1$ mile $\\approx1.6$ km", "$1$ kg $\\approx2.2$ lb", "$1$ cm $=2.54$ in"], [0, 1, 2]));
  q.push(ms("easy", "Converting units:", ["to a smaller unit, multiply", "to a larger unit, divide", "keep units consistent", "always multiply"], [0, 1, 2]));
  q.push(tf("easy", "$1$ m $=100$ cm.", true));
  q.push(tf("easy", "$1$ ft $=12$ in.", true));
  q.push(tf("easy", "$1$ ft $=10$ in.", false));
  q.push(fill("easy", "Convert $3.5$ m to cm.", ["350"]));
  q.push(fill("easy", "Convert $2500$ mL to L.", ["2.5"]));
  q.push(fill("easy", "Convert $5$ ft to inches.", ["60"]));
  q.push(num("easy", "Convert $4.2$ km to m.", 4200, 0));
  q.push(num("easy", "Convert $3$ yd to feet.", 9, 0));
  q.push(num("easy", "Convert $5$ kg to pounds ($\\times2.2$).", 11, 0));
  q.push(match("easy", "Match each metric conversion.", ["$1$ m", "$1$ km", "$1$ L"], ["$100$ cm", "$1000$ m", "$1000$ mL"], [0, 1, 2]));
  q.push(mc("medium", "Convert $10$ in to cm.", ["$25.4$", "$3.94$", "$12$", "$20$"], 0));
  q.push(mc("medium", "Convert $12$ miles to km ($\\times1.6$).", ["$19.2$", "$7.5$", "$13.6$", "$120$"], 0));
  q.push(mc("medium", "Convert $350$ cm to m.", ["$3.5$", "$35000$", "$35$", "$0.35$"], 0));
  q.push(mc("medium", "Convert $3$ L to mL.", ["$3000$", "$0.003$", "$300$", "$30$"], 0));
  q.push(mc("medium", "Convert $10$ kg to lb.", ["$22$", "$4.5$", "$20$", "$12$"], 0));
  q.push(mc("medium", "A board $8$ ft long, in inches:", ["$96$", "$20$", "$0.67$", "$48$"], 0));
  q.push(ms("medium", "To convert miles and km:", ["$1$ mile $\\approx1.6$ km", "$\\times1.6$ to get km", "$\\div1.6$ to get miles", "$1$ mile $=10$ km"], [0, 1, 2]));
  q.push(ms("medium", "Which equal $2$ m?", ["$200$ cm", "$2000$ mm", "$0.002$ km", "$20$ cm"], [0, 1, 2]));
  q.push(ms("medium", "To convert kg to lb:", ["$\\times2.2$", "$1$ kg $\\approx2.2$ lb", "the number gets larger", "$\\div2.2$"], [0, 1, 2]));
  q.push(ms("medium", "Common conversion errors:", ["multiplying when you should divide", "mixing systems", "using the wrong factor", "using the right factor"], [0, 1, 2]));
  q.push(tf("medium", "$1$ in $=2.54$ cm.", true));
  q.push(tf("medium", "$1$ mile $\\approx1.6$ km.", true));
  q.push(tf("medium", "To convert cm to m, multiply by $100$.", false));
  q.push(fill("medium", "Convert $10$ in to cm.", ["25.4"]));
  q.push(fill("medium", "Convert $16$ km to miles.", ["10"]));
  q.push(fill("medium", "Convert $5.5$ km to m.", ["5500"]));
  q.push(num("medium", "Convert $8$ km to miles.", 5, 0));
  q.push(num("medium", "Convert $4$ yd to feet.", 12, 0));
  q.push(num("medium", "Convert $250$ cm to m.", 2.5, 0));
  q.push(match("medium", "Match each conversion factor.", ["in $\\to$ cm", "mile $\\to$ km", "kg $\\to$ lb"], ["$\\times2.54$", "$\\times1.6$", "$\\times2.2$"], [0, 1, 2]));
  q.push(mc("hard", "A recipe needs $3$ cups; in mL ($1$ cup $\\approx250$):", ["$750$", "$83$", "$3000$", "$250$"], 0));
  q.push(mc("hard", "A $6$ ft $2$ in person, in inches:", ["$74$", "$62$", "$8$", "$72$"], 0));
  q.push(mc("hard", "Convert $2.5$ m$^2$ to cm$^2$.", ["$25000$", "$250$", "$2500$", "$0.00025$"], 0));
  q.push(mc("hard", "A $5$ km run is about how many miles ($\\div1.6$)?", ["$\\approx3.1$", "$\\approx8$", "$\\approx5$", "$\\approx2$"], 0));
  q.push(mc("hard", "$90$ km/h is about how many mph ($\\div1.6$)?", ["$\\approx56$", "$\\approx144$", "$\\approx90$", "$\\approx45$"], 0));
  q.push(ms("hard", "For area conversions:", ["$1$ m$^2=10000$ cm$^2$", "$1$ cm$^2=100$ mm$^2$", "square the linear factor", "same factor as linear"], [0, 1, 2]));
  q.push(ms("hard", "Which equal $1.5$ m?", ["$150$ cm", "$1500$ mm", "$0.0015$ km", "$15$ cm"], [0, 1, 2]));
  q.push(ms("hard", "To convert a speed km/h $\\to$ mph:", ["$\\div1.6$", "since $1$ mile $\\approx1.6$ km", "the number gets smaller", "$\\times1.6$"], [0, 1, 2]));
  q.push(ms("hard", "Multi-step conversions:", ["chain the factors", "check the direction each step", "keep units", "drop the units"], [0, 1, 2]));
  q.push(tf("hard", "$1$ m$^2=10000$ cm$^2$.", true));
  q.push(tf("hard", "$6$ ft $2$ in $=74$ in.", true));
  q.push(tf("hard", "To convert m$^2$ to cm$^2$, multiply by $100$.", false));
  q.push(fill("hard", "A recipe $3$ cups in mL ($1$ cup $\\approx250$):", ["750"]));
  q.push(fill("hard", "$6$ ft $2$ in to inches:", ["74"]));
  q.push(fill("hard", "$2.5$ m$^2$ to cm$^2$:", ["25000"]));
  q.push(num("hard", "Convert $100$ in to cm ($\\times2.54$).", 254, 0));
  q.push(num("hard", "Convert a $20$-mile road to km ($\\times1.6$).", 32, 0));
  q.push(num("hard", "Convert $7.5$ km to m.", 7500, 0));
  q.push(order("hard", "Order the steps to convert $5$ ft $3$ in to cm.", ["Feet to inches: $5\\times12=60$", "Add the extra inches: $63$", "Multiply by $2.54$", "Result $\\approx160$ cm"]));
  q.push(match("hard", "Match each conversion to its result.", ["$3$ cups (mL)", "$6$ ft $2$ in (inches)", "$2.5$ m$^2$ (cm$^2$)"], ["$750$", "$74$", "$25000$"], [0, 1, 2]));
  return q;
}

// ── 4.2 Surface Area of Prisms & Cylinders ───────────────────
function g42() {
  const q = [];
  q.push(mc("easy", "SA of a $4\\times3\\times2$ box.", ["$52$", "$24$", "$26$", "$48$"], 0));
  q.push(mc("easy", "SA of a cube, side $5$.", ["$150$", "$125$", "$30$", "$25$"], 0));
  q.push(mc("easy", "The cylinder SA formula:", ["$2\\pi r^2+2\\pi rh$", "$\\pi r^2 h$", "$2\\pi r$", "$\\pi r^2$"], 0));
  q.push(mc("easy", "SA of a cube, side $4$.", ["$96$", "$64$", "$16$", "$48$"], 0));
  q.push(mc("easy", "A rectangular prism's SA uses:", ["$2(lw+lh+wh)$", "$lwh$", "$2\\pi rh$", "$6s$"], 0));
  q.push(mc("easy", "Surface area is measured in:", ["square units", "cubic units", "linear units", "no units"], 0));
  q.push(ms("easy", "For a $4\\times3\\times2$ box, SA:", ["$2(12)$ for the $lw$ faces", "$2(8)$ for $lh$", "$2(6)$ for $wh$", "total $52$"], [0, 1, 2, 3]));
  q.push(ms("easy", "Cylinder SA parts:", ["two circles $2\\pi r^2$", "the wrap $2\\pi rh$", "total $2\\pi r^2+2\\pi rh$", "$\\pi r^2 h$"], [0, 1, 2]));
  q.push(ms("easy", "Which are surface-area formulas?", ["$2(lw+lh+wh)$", "$6s^2$ (cube)", "$2\\pi r^2+2\\pi rh$", "$lwh$"], [0, 1, 2]));
  q.push(ms("easy", "SA facts:", ["measured in square units", "add all the faces", "use the radius for cylinders", "measured in cubic units"], [0, 1, 2]));
  q.push(tf("easy", "SA of a cube side $5$ is $150$.", true));
  q.push(tf("easy", "Cylinder SA is $2\\pi r^2+2\\pi rh$.", true));
  q.push(tf("easy", "SA is measured in cubic units.", false));
  q.push(fill("easy", "SA of a $4\\times3\\times2$ box.", ["52"]));
  q.push(fill("easy", "SA of a cube, side $5$.", ["150"]));
  q.push(fill("easy", "SA of a cube, side $4$.", ["96"]));
  q.push(num("easy", "SA of a $5\\times2\\times3$ box.", 62, 0));
  q.push(num("easy", "SA of a cube, side $6$.", 216, 0));
  q.push(num("easy", "SA of a cube, side $10$.", 600, 0));
  q.push(match("easy", "Match each solid to its SA formula.", ["rectangular prism", "cube", "cylinder"], ["$2(lw+lh+wh)$", "$6s^2$", "$2\\pi r^2+2\\pi rh$"], [0, 1, 2]));
  q.push(mc("medium", "SA of a cylinder $r=3,\\ h=10$ (1 dp).", ["$245.0$", "$282.7$", "$78$", "$188.5$"], 0));
  q.push(mc("medium", "SA of a cylinder $r=2,\\ h=5$ (exact).", ["$28\\pi$", "$20\\pi$", "$8\\pi$", "$48\\pi$"], 0));
  q.push(mc("medium", "Lateral area of a cylinder $r=3,\\ h=7$ (exact).", ["$42\\pi$", "$18\\pi$", "$60\\pi$", "$21\\pi$"], 0));
  q.push(mc("medium", "SA of an open-top box $4\\times4\\times3$.", ["$64$", "$80$", "$16$", "$112$"], 0));
  q.push(mc("medium", "SA of a triangular prism (legs $3,4$, hyp $5$, length $10$).", ["$132$", "$120$", "$144$", "$60$"], 0));
  q.push(mc("medium", "SA of a $6\\times4\\times2$ box.", ["$88$", "$48$", "$44$", "$96$"], 0));
  q.push(ms("medium", "For SA of a cylinder $r=3,\\ h=10$:", ["$2\\pi(9)=18\\pi$", "$2\\pi(3)(10)=60\\pi$", "total $78\\pi$", "$\\approx245$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Triangular-prism SA:", ["lateral $=$ (perimeter)(length)", "plus $2$ triangular ends", "legs $3,4\\to$ area $6$", "subtract the ends"], [0, 1, 2]));
  q.push(ms("medium", "Which need the radius (not diameter)?", ["cylinder SA", "cylinder volume", "circle area", "none"], [0, 1, 2]));
  q.push(ms("medium", "An open-top box:", ["omits the top face", "base $+$ $4$ sides", "less SA than a closed box", "includes the top"], [0, 1, 2]));
  q.push(tf("medium", "SA of a cylinder $r=2,\\ h=5$ is $28\\pi$.", true));
  q.push(tf("medium", "Lateral area of a cylinder is $2\\pi rh$.", true));
  q.push(tf("medium", "An open-top box includes the top face.", false));
  q.push(fill("medium", "SA of a cylinder $r=2,\\ h=5$ (exact, multiple of $\\pi$):", ["28"]));
  q.push(fill("medium", "Lateral area of a cylinder $r=3,\\ h=7$ (multiple of $\\pi$):", ["42"]));
  q.push(fill("medium", "SA of a triangular prism, legs $3,4$, length $10$:", ["132"]));
  q.push(num("medium", "SA of a cylinder $r=5,\\ h=4$ (1 dp).", 282.7, 0.2));
  q.push(num("medium", "SA of a $5\\times2\\times3$ box.", 62, 0));
  q.push(num("medium", "SA of an open-top box $4\\times4\\times3$.", 64, 0));
  q.push(match("medium", "Match each to its SA.", ["box $4\\times3\\times2$", "cube side $5$", "cylinder $r=2,h=5$"], ["$52$", "$150$", "$28\\pi$"], [0, 1, 2]));
  q.push(mc("hard", "SA of a triangular prism: base $6$, height $4$ (sides $5,5$), length $12$.", ["$216$", "$192$", "$240$", "$120$"], 0));
  q.push(mc("hard", "A can $r=4,\\ h=12$: its label (lateral) area (1 dp).", ["$301.6$", "$402.1$", "$96$", "$150.8$"], 0));
  q.push(mc("hard", "If a cylinder's radius doubles, each circular end becomes:", ["$4\\times$ as large", "$2\\times$", "the same", "half"], 0));
  q.push(mc("hard", "If a cube's side doubles, its SA becomes:", ["$4\\times$ larger", "$2\\times$", "$8\\times$", "the same"], 0));
  q.push(mc("hard", "SA of a gift box $20\\times15\\times10$.", ["$1300$", "$3000$", "$650$", "$900$"], 0));
  q.push(ms("hard", "For a triangular prism base $6$, height $4$ (sides $5,5$), length $12$:", ["triangle area $12$", "lateral $(6+5+5)(12)=192$", "ends $2(12)=24$", "total $216$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Scaling surface area:", ["side $\\times2\\to$ SA $\\times4$", "SA scales as length$^2$", "area is $2$-dimensional", "SA scales linearly"], [0, 1, 2]));
  q.push(ms("hard", "Which SA computations are correct?", ["cube side $4=96$", "cylinder $r=2,h=5=28\\pi$", "box $5\\times2\\times3=62$", "cube side $5=125$"], [0, 1, 2]));
  q.push(ms("hard", "Steps for a prism's SA:", ["find each face's area", "add them all", "for a cylinder use $2\\pi r^2+2\\pi rh$", "subtract a face"], [0, 1, 2]));
  q.push(tf("hard", "If a cube's side doubles, its SA becomes $4\\times$ larger.", true));
  q.push(tf("hard", "A can's label area is its lateral area $2\\pi rh$.", true));
  q.push(tf("hard", "A triangular prism's SA omits the two triangular ends.", false));
  q.push(fill("hard", "SA of a triangular prism base $6$, height $4$, sides $5,5$, length $12$:", ["216"]));
  q.push(fill("hard", "A can $r=4,\\ h=12$ lateral area (multiple of $\\pi$):", ["96"]));
  q.push(fill("hard", "SA of a gift box $20\\times15\\times10$:", ["1300"]));
  q.push(num("hard", "SA of a cylinder $r=3,\\ h=10$ (1 dp).", 245.0, 0.2));
  q.push(num("hard", "SA of a cube, side $7$.", 294, 0));
  q.push(num("hard", "SA of a $8\\times3\\times2$ box.", 92, 0));
  q.push(order("hard", "Order the steps to find a cylinder's surface area.", ["Find the two circle areas: $2\\pi r^2$", "Find the wrap: $2\\pi rh$", "Add them", "Round if asked"]));
  q.push(match("hard", "Match each to its SA.", ["cylinder $r=2,h=5$", "triangular prism (3,4,len10)", "cube side $6$"], ["$28\\pi$", "$132$", "$216$"], [0, 1, 2]));
  return q;
}

// ── 4.3 Volume of Prisms & Cylinders ─────────────────────────
function g43() {
  const q = [];
  q.push(mc("easy", "V of a $4\\times3\\times2$ box.", ["$24$", "$52$", "$9$", "$48$"], 0));
  q.push(mc("easy", "V of a cube, side $5$.", ["$125$", "$150$", "$15$", "$25$"], 0));
  q.push(mc("easy", "The cylinder volume formula:", ["$\\pi r^2 h$", "$2\\pi rh$", "$\\pi r^2$", "$lwh$"], 0));
  q.push(mc("easy", "V of a cube, side $4$.", ["$64$", "$96$", "$16$", "$48$"], 0));
  q.push(mc("easy", "The volume of any prism is:", ["base area $\\times$ height", "$2(lw+lh+wh)$", "perimeter $\\times$ height", "$\\pi r$"], 0));
  q.push(mc("easy", "Volume is measured in:", ["cubic units", "square units", "linear units", "no units"], 0));
  q.push(ms("easy", "For a $4\\times3\\times2$ box:", ["$4\\times3\\times2$", "$=24$", "cubic units", "$=52$"], [0, 1, 2]));
  q.push(ms("easy", "Volume formulas:", ["$lwh$ (box)", "$\\pi r^2 h$ (cylinder)", "(triangle area)(length)", "$2\\pi rh$"], [0, 1, 2]));
  q.push(ms("easy", "Volume facts:", ["measured in cubic units", "base area $\\times$ height", "use the radius for cylinders", "measured in square units"], [0, 1, 2]));
  q.push(ms("easy", "Which are prisms or cylinders?", ["rectangular box", "cylinder", "triangular prism", "sphere"], [0, 1, 2]));
  q.push(tf("easy", "V of a cube side $5$ is $125$.", true));
  q.push(tf("easy", "Cylinder volume is $\\pi r^2 h$.", true));
  q.push(tf("easy", "Volume is measured in square units.", false));
  q.push(fill("easy", "V of a $4\\times3\\times2$ box.", ["24"]));
  q.push(fill("easy", "V of a cube, side $5$.", ["125"]));
  q.push(fill("easy", "V of a cube, side $4$.", ["64"]));
  q.push(num("easy", "V of a $6\\times2\\times3$ box.", 36, 0));
  q.push(num("easy", "V of a cube, side $6$.", 216, 0));
  q.push(num("easy", "V of a triangular prism, triangle area $10$, length $7$.", 70, 0));
  q.push(match("easy", "Match each solid to its volume formula.", ["rectangular prism", "cube", "cylinder"], ["$lwh$", "$s^3$", "$\\pi r^2 h$"], [0, 1, 2]));
  q.push(mc("medium", "V of a cylinder $r=3,\\ h=10$ (1 dp).", ["$282.7$", "$245.0$", "$90$", "$94.2$"], 0));
  q.push(mc("medium", "V of a cylinder $r=5,\\ h=4$ (exact).", ["$100\\pi$", "$80\\pi$", "$20\\pi$", "$40\\pi$"], 0));
  q.push(mc("medium", "V of a tank $r=2,\\ h=5$ m (1 dp).", ["$62.8$", "$31.4$", "$20$", "$125.7$"], 0));
  q.push(mc("medium", "V of a triangular prism, area $6$, length $10$.", ["$60$", "$16$", "$120$", "$30$"], 0));
  q.push(mc("medium", "Litres in a $30\\times20\\times10$ cm box.", ["$6$", "$60$", "$0.6$", "$600$"], 0));
  q.push(mc("medium", "V of a $6\\times2\\times3$ box.", ["$36$", "$22$", "$11$", "$72$"], 0));
  q.push(ms("medium", "V of a cylinder $r=3,\\ h=10$:", ["$\\pi(9)(10)$", "$=90\\pi$", "$\\approx282.7$", "$=78\\pi$"], [0, 1, 2]));
  q.push(ms("medium", "Which equal $100\\pi$?", ["cylinder $r=5,h=4$", "$\\pi(25)(4)$", "$\\approx314.2$", "$\\pi(10)(10)$"], [0, 1, 2]));
  q.push(ms("medium", "Volume of a prism:", ["base area $\\times$ height", "works for any prism", "cylinder uses a $\\pi r^2$ base", "perimeter $\\times$ height"], [0, 1, 2]));
  q.push(ms("medium", "Unit facts:", ["$1$ L $=1000$ cm$^3$", "volume is cubic", "$1$ m$^3=1000$ L", "$1$ L $=100$ cm$^3$"], [0, 1, 2]));
  q.push(tf("medium", "V of a cylinder $r=5,\\ h=4$ is $100\\pi$.", true));
  q.push(tf("medium", "$1$ L $=1000$ cm$^3$.", true));
  q.push(tf("medium", "Volume is base area divided by height.", false));
  q.push(fill("medium", "V of a cylinder $r=5,\\ h=4$ (multiple of $\\pi$):", ["100"]));
  q.push(fill("medium", "Litres in a $30\\times20\\times10$ cm box.", ["6"]));
  q.push(fill("medium", "V of a triangular prism, area $6$, length $10$.", ["60"]));
  q.push(num("medium", "V of a cylinder $r=3,\\ h=10$ (1 dp).", 282.7, 0.2));
  q.push(num("medium", "V of a $6\\times2\\times3$ box.", 36, 0));
  q.push(num("medium", "V of a cube, side $4$.", 64, 0));
  q.push(match("medium", "Match each to its volume.", ["box $4\\times3\\times2$", "cube side $5$", "cylinder $r=5,h=4$"], ["$24$", "$125$", "$100\\pi$"], [0, 1, 2]));
  q.push(mc("hard", "A cylinder holds $48\\pi$ cm$^3$ with $r=4$; its height is:", ["$3$", "$4$", "$12$", "$6$"], 0));
  q.push(mc("hard", "A cylinder holds $100\\pi$ cm$^3$ with $r=5$; its height is:", ["$4$", "$5$", "$20$", "$2$"], 0));
  q.push(mc("hard", "If a cube's side doubles, its volume becomes:", ["$8\\times$ larger", "$2\\times$", "$4\\times$", "the same"], 0));
  q.push(mc("hard", "A box has volume $120$ and base $6\\times4$; its height is:", ["$5$", "$20$", "$4$", "$10$"], 0));
  q.push(mc("hard", "V of a cylinder $r=2,\\ h=9$ (exact).", ["$36\\pi$", "$18\\pi$", "$72\\pi$", "$36$"], 0));
  q.push(ms("hard", "To find a cylinder's height from its volume:", ["divide $V$ by the base area", "base area $=\\pi r^2$", "$h=V/(\\pi r^2)$", "multiply"], [0, 1, 2]));
  q.push(ms("hard", "Scaling volume:", ["side $\\times2\\to$ volume $\\times8$", "scales as length$^3$", "it is $3$-dimensional", "scales linearly"], [0, 1, 2]));
  q.push(ms("hard", "Which volumes are correct?", ["box $6\\times2\\times3=36$", "cube side $4=64$", "cylinder $r=5,h=4=100\\pi$", "cube side $3=9$"], [0, 1, 2]));
  q.push(ms("hard", "Steps to find a missing height:", ["compute the base area", "divide volume by base area", "keep units", "multiply volume by base"], [0, 1, 2]));
  q.push(tf("hard", "If a cube's side doubles, its volume becomes $8\\times$ larger.", true));
  q.push(tf("hard", "A cylinder $48\\pi$ cm$^3$ with $r=4$ has height $3$.", true));
  q.push(tf("hard", "A box of volume $120$ with base $6\\times4$ has height $10$.", false));
  q.push(fill("hard", "A cylinder holds $48\\pi$ cm$^3$ with $r=4$; height ___.", ["3"]));
  q.push(fill("hard", "A box volume $120$, base $6\\times4$; height ___.", ["5"]));
  q.push(fill("hard", "V of a cylinder $r=2,\\ h=9$ (multiple of $\\pi$):", ["36"]));
  q.push(num("hard", "A cylinder $100\\pi$ cm$^3$, $r=5$; its height.", 4, 0));
  q.push(num("hard", "V of a $5\\times3\\times2$ box.", 30, 0));
  q.push(num("hard", "Litres in a $50\\times20\\times10$ cm tank.", 10, 0));
  q.push(order("hard", "Order the steps to find a cylinder's height from its volume.", ["Write $V=\\pi r^2h$", "Compute the base area $\\pi r^2$", "Divide $V$ by the base area", "State $h$"]));
  q.push(match("hard", "Match each to its volume.", ["cylinder $r=5,h=4$", "cube side $4$", "cylinder $r=2,h=9$"], ["$100\\pi$", "$64$", "$36\\pi$"], [0, 1, 2]));
  return q;
}

// ── 4.4 Pyramids & Cones ─────────────────────────────────────
function g44() {
  const q = [];
  q.push(mc("easy", "The cone volume formula:", ["$\\tfrac13\\pi r^2 h$", "$\\pi r^2 h$", "$\\tfrac13\\pi r^2$", "$2\\pi rh$"], 0));
  q.push(mc("easy", "V of a cone $r=3,\\ h=4$ (exact).", ["$12\\pi$", "$36\\pi$", "$4\\pi$", "$24\\pi$"], 0));
  q.push(mc("easy", "The pyramid volume formula:", ["$\\tfrac13(\\text{base})h$", "$(\\text{base})h$", "$\\tfrac12 bh$", "$\\tfrac13\\pi r^2$"], 0));
  q.push(mc("easy", "The slant height of a cone:", ["$\\sqrt{r^2+h^2}$", "$r+h$", "$\\sqrt{r^2-h^2}$", "$rh$"], 0));
  q.push(mc("easy", "The slant of a cone $r=3,\\ h=4$:", ["$5$", "$7$", "$\\sqrt{7}$", "$1$"], 0));
  q.push(mc("easy", "A cone holds ___ of a cylinder's volume:", ["one-third", "one-half", "the same", "twice"], 0));
  q.push(ms("easy", "Volume formulas:", ["cone $\\tfrac13\\pi r^2h$", "pyramid $\\tfrac13(\\text{base})h$", "both have $\\tfrac13$", "cone $\\pi r^2 h$"], [0, 1, 2]));
  q.push(ms("easy", "For a cone $r=3,\\ h=4$:", ["slant $=\\sqrt{9+16}$", "slant $=5$", "V $=12\\pi$", "slant $=7$"], [0, 1, 2]));
  q.push(ms("easy", "Cone surface area:", ["$\\pi r^2+\\pi r s$", "uses the slant $s$", "base $+$ curved part", "$2\\pi rh$"], [0, 1, 2]));
  q.push(ms("easy", "Pyramid/cone facts:", ["one-third of the prism/cylinder", "they taper to a point", "SA uses the slant", "volume uses the slant"], [0, 1, 2]));
  q.push(tf("easy", "A cone's volume is one-third of a cylinder's.", true));
  q.push(tf("easy", "Slant height $s=\\sqrt{r^2+h^2}$.", true));
  q.push(tf("easy", "Cone SA uses the vertical height.", false));
  q.push(fill("easy", "V of a cone $r=3,\\ h=4$ (multiple of $\\pi$):", ["12"]));
  q.push(fill("easy", "The slant of a cone $r=3,\\ h=4$:", ["5"]));
  q.push(fill("easy", "V of a square pyramid, base $6\\times6$, height $10$.", ["120"]));
  q.push(num("easy", "V of a cone $r=6,\\ h=10$ as a multiple of $\\pi$.", 120, 0));
  q.push(num("easy", "The slant of a cone $r=6,\\ h=8$.", 10, 0));
  q.push(num("easy", "V of a square pyramid, base $4\\times4$, height $9$.", 48, 0));
  q.push(match("easy", "Match each to its volume.", ["cone $r=3,h=4$", "square pyramid base $6$, $h=10$", "cone $r=6,h=10$"], ["$12\\pi$", "$120$", "$120\\pi$"], [0, 1, 2]));
  q.push(mc("medium", "Cone SA $r=3,\\ s=5$ (exact).", ["$24\\pi$", "$9\\pi$", "$15\\pi$", "$45\\pi$"], 0));
  q.push(mc("medium", "Square pyramid SA, base $6$, slant $5$.", ["$96$", "$36$", "$60$", "$156$"], 0));
  q.push(mc("medium", "V of a cone $r=6,\\ h=10$ (1 dp).", ["$377.0$", "$1130.4$", "$120$", "$251.3$"], 0));
  q.push(mc("medium", "The slant of a cone $r=6,\\ h=8$.", ["$10$", "$14$", "$\\sqrt{28}$", "$48$"], 0));
  q.push(mc("medium", "V of a square pyramid, base $4\\times4$, height $9$.", ["$48$", "$144$", "$16$", "$108$"], 0));
  q.push(mc("medium", "V of a cone $r=2,\\ h=6$ (exact).", ["$8\\pi$", "$24\\pi$", "$4\\pi$", "$16\\pi$"], 0));
  q.push(ms("medium", "For cone SA $r=3,\\ s=5$:", ["base $\\pi(9)$", "curved $\\pi(3)(5)$", "total $24\\pi$", "$\\approx75.4$"], [0, 1, 2, 3]));
  q.push(ms("medium", "To find a cone's slant:", ["use $\\sqrt{r^2+h^2}$", "it is the Pythagorean theorem", "needed for SA", "it equals $h$"], [0, 1, 2]));
  q.push(ms("medium", "Square pyramid SA:", ["base $+$ lateral", "lateral $=\\tfrac12(\\text{perimeter})s$", "base $6$, slant $5\\to36+60$", "subtract the base"], [0, 1, 2]));
  q.push(ms("medium", "Which use the $\\tfrac13$ factor?", ["cone volume", "pyramid volume", "cylinder volume", "prism volume"], [0, 1]));
  q.push(tf("medium", "Cone SA $r=3,\\ s=5$ is $24\\pi$.", true));
  q.push(tf("medium", "A square pyramid base $6$, slant $5$ has SA $96$.", true));
  q.push(tf("medium", "V of a cone $r=6,\\ h=10$ is $120$ (forgetting $\\pi$).", false));
  q.push(fill("medium", "Cone SA $r=3,\\ s=5$ (multiple of $\\pi$):", ["24"]));
  q.push(fill("medium", "Square pyramid SA, base $6$, slant $5$:", ["96"]));
  q.push(fill("medium", "The slant of a cone $r=6,\\ h=8$:", ["10"]));
  q.push(num("medium", "V of a cone $r=6,\\ h=10$ (1 dp).", 377.0, 0.3));
  q.push(num("medium", "V of a square pyramid, base $6\\times6$, height $10$.", 120, 0));
  q.push(num("medium", "Cone SA $r=5,\\ s=13$ as a multiple of $\\pi$.", 90, 0));
  q.push(match("medium", "Match each to its value.", ["cone V $r=3,h=4$", "cone SA $r=3,s=5$", "pyramid V base $6$, $h=10$"], ["$12\\pi$", "$24\\pi$", "$120$"], [0, 1, 2]));
  q.push(mc("hard", "Cone $r=3,\\ h=4$: total SA (exact).", ["$24\\pi$", "$9\\pi$", "$21\\pi$", "$33\\pi$"], 0));
  q.push(mc("hard", "V of a cone $r=2,\\ h=6$ (exact).", ["$8\\pi$", "$24\\pi$", "$4\\pi$", "$16\\pi$"], 0));
  q.push(mc("hard", "Cone SA $r=5,\\ s=13$ (exact).", ["$90\\pi$", "$65\\pi$", "$25\\pi$", "$18\\pi$"], 0));
  q.push(mc("hard", "A pyramid roof base $6\\times6$, slant $5$: lateral area to shingle.", ["$60$", "$96$", "$36$", "$120$"], 0));
  q.push(mc("hard", "V of a square pyramid, base $10\\times10$, height $12$.", ["$400$", "$1200$", "$100$", "$120$"], 0));
  q.push(ms("hard", "For cone $r=3,\\ h=4$ total SA:", ["slant $s=5$", "base $9\\pi$", "curved $15\\pi$", "total $24\\pi$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which equal $90\\pi$?", ["cone SA $r=5,s=13$", "$25\\pi+65\\pi$", "$\\pi(25)+\\pi(5)(13)$", "$50\\pi$"], [0, 1, 2]));
  q.push(ms("hard", "Pyramid lateral area:", ["$\\tfrac12(\\text{perimeter})s$", "base $6$, slant $5\\to60$", "excludes the base", "includes the base"], [0, 1, 2]));
  q.push(ms("hard", "Cone vs cylinder:", ["the cone is $\\tfrac13$ the volume", "same radius and height", "cone $\\tfrac13\\pi r^2h$", "the cone is larger"], [0, 1, 2]));
  q.push(tf("hard", "Cone $r=3,\\ h=4$ has total SA $24\\pi$.", true));
  q.push(tf("hard", "A pyramid's lateral area excludes its base.", true));
  q.push(tf("hard", "V of a cone $r=2,\\ h=6$ is $24\\pi$.", false));
  q.push(fill("hard", "V of a cone $r=2,\\ h=6$ (multiple of $\\pi$):", ["8"]));
  q.push(fill("hard", "Cone SA $r=5,\\ s=13$ (multiple of $\\pi$):", ["90"]));
  q.push(fill("hard", "V of a square pyramid, base $10\\times10$, height $12$.", ["400"]));
  q.push(num("hard", "V of a cone $r=6,\\ h=10$ as a multiple of $\\pi$.", 120, 0));
  q.push(num("hard", "The slant of a cone $r=9,\\ h=12$.", 15, 0));
  q.push(num("hard", "V of a square pyramid, base $6\\times6$, height $10$.", 120, 0));
  q.push(order("hard", "Order the steps to find a cone's surface area.", ["Find the slant $s=\\sqrt{r^2+h^2}$", "Compute the base $\\pi r^2$", "Compute the curved part $\\pi r s$", "Add them"]));
  q.push(match("hard", "Match each to its value.", ["cone V $r=2,h=6$", "cone SA $r=5,s=13$", "pyramid V base $10$, $h=12$"], ["$8\\pi$", "$90\\pi$", "$400$"], [0, 1, 2]));
  return q;
}

// ── 4.5 Spheres ──────────────────────────────────────────────
function g45() {
  const q = [];
  q.push(mc("easy", "The sphere volume formula:", ["$\\tfrac43\\pi r^3$", "$4\\pi r^2$", "$\\tfrac13\\pi r^2h$", "$\\pi r^2$"], 0));
  q.push(mc("easy", "The sphere surface-area formula:", ["$4\\pi r^2$", "$\\tfrac43\\pi r^3$", "$2\\pi r$", "$\\pi r^2$"], 0));
  q.push(mc("easy", "V of a sphere $r=3$ (exact).", ["$36\\pi$", "$108\\pi$", "$12\\pi$", "$9\\pi$"], 0));
  q.push(mc("easy", "SA of a sphere $r=3$ (exact).", ["$36\\pi$", "$12\\pi$", "$108\\pi$", "$9\\pi$"], 0));
  q.push(mc("easy", "Given a diameter, you first:", ["halve it for $r$", "double it", "square it", "use it directly"], 0));
  q.push(mc("easy", "A hemisphere is:", ["half a sphere", "a quarter", "a whole sphere", "a cone"], 0));
  q.push(ms("easy", "Sphere formulas:", ["V $=\\tfrac43\\pi r^3$", "SA $=4\\pi r^2$", "V uses $r^3$", "SA uses $r^3$"], [0, 1, 2]));
  q.push(ms("easy", "For $r=3$:", ["V $=36\\pi$", "SA $=36\\pi$", "both are $36\\pi$ here", "V $=108\\pi$"], [0, 1, 2]));
  q.push(ms("easy", "Given a diameter $d$:", ["$r=d/2$", "then apply the formula", "e.g. $d=10\\to r=5$", "use $d$ as $r$"], [0, 1, 2]));
  q.push(ms("easy", "Sphere facts:", ["V uses $\\tfrac43\\pi r^3$", "SA uses $4\\pi r^2$", "a hemisphere is half", "V is squared"], [0, 1, 2]));
  q.push(tf("easy", "Sphere volume is $\\tfrac43\\pi r^3$.", true));
  q.push(tf("easy", "Sphere SA is $4\\pi r^2$.", true));
  q.push(tf("easy", "For a sphere, use the diameter as the radius.", false));
  q.push(fill("easy", "V of a sphere $r=3$ (multiple of $\\pi$):", ["36"]));
  q.push(fill("easy", "SA of a sphere $r=3$ (multiple of $\\pi$):", ["36"]));
  q.push(fill("easy", "SA of a sphere with diameter $10$ (multiple of $\\pi$):", ["100"]));
  q.push(num("easy", "V of a sphere $r=3$ (1 dp).", 113.1, 0.2));
  q.push(num("easy", "SA of a sphere $r=5$ as a multiple of $\\pi$.", 100, 0));
  q.push(num("easy", "V of a sphere $r=6$ as a multiple of $\\pi$.", 288, 0));
  q.push(match("easy", "Match each to its formula.", ["sphere volume", "sphere SA", "hemisphere volume"], ["$\\tfrac43\\pi r^3$", "$4\\pi r^2$", "$\\tfrac12\\cdot\\tfrac43\\pi r^3$"], [0, 1, 2]));
  q.push(mc("medium", "V of a sphere $r=6$ (exact).", ["$288\\pi$", "$144\\pi$", "$216\\pi$", "$24\\pi$"], 0));
  q.push(mc("medium", "SA of a sphere with diameter $8$ (exact).", ["$64\\pi$", "$256\\pi$", "$16\\pi$", "$32\\pi$"], 0));
  q.push(mc("medium", "V of a hemisphere $r=3$ (exact).", ["$18\\pi$", "$36\\pi$", "$9\\pi$", "$54\\pi$"], 0));
  q.push(mc("medium", "V of a sphere $r=2$ (exact).", ["$\\tfrac{32}{3}\\pi$", "$8\\pi$", "$\\tfrac{16}{3}\\pi$", "$32\\pi$"], 0));
  q.push(mc("medium", "SA of a sphere $r=5$ (1 dp).", ["$314.2$", "$523.6$", "$100$", "$78.5$"], 0));
  q.push(mc("medium", "If $r$ doubles, the volume becomes:", ["$8\\times$ larger", "$2\\times$", "$4\\times$", "the same"], 0));
  q.push(ms("medium", "For $r=6$:", ["V $=\\tfrac43\\pi(216)$", "$=288\\pi$", "$\\approx904.8$", "$=216\\pi$"], [0, 1, 2]));
  q.push(ms("medium", "Which are surface areas?", ["sphere $r=5\\to100\\pi$", "sphere $r=3\\to36\\pi$", "diameter $8\\to64\\pi$", "sphere $r=5\\to\\tfrac{500}{3}\\pi$"], [0, 1, 2]));
  q.push(ms("medium", "Hemisphere:", ["half a sphere's volume", "$\\tfrac12\\cdot\\tfrac43\\pi r^3$", "$r=3\\to18\\pi$", "equals a full sphere"], [0, 1, 2]));
  q.push(ms("medium", "Diameter problems:", ["halve to get $r$", "then apply the formula", "$d=8\\to r=4$", "use $d$ directly"], [0, 1, 2]));
  q.push(tf("medium", "V of a sphere $r=6$ is $288\\pi$.", true));
  q.push(tf("medium", "V of a hemisphere $r=3$ is $18\\pi$.", true));
  q.push(tf("medium", "If $r$ doubles, sphere volume doubles.", false));
  q.push(fill("medium", "V of a sphere $r=6$ (multiple of $\\pi$):", ["288"]));
  q.push(fill("medium", "SA of a sphere with diameter $8$ (multiple of $\\pi$):", ["64"]));
  q.push(fill("medium", "V of a hemisphere $r=3$ (multiple of $\\pi$):", ["18"]));
  q.push(num("medium", "SA of a sphere $r=5$ as a multiple of $\\pi$.", 100, 0));
  q.push(num("medium", "V of a sphere $r=3$ as a multiple of $\\pi$.", 36, 0));
  q.push(num("medium", "V of a sphere $r=6$ (1 dp).", 904.8, 0.3));
  q.push(match("medium", "Match each to its value.", ["V sphere $r=3$", "SA sphere $r=5$", "V hemisphere $r=3$"], ["$36\\pi$", "$100\\pi$", "$18\\pi$"], [0, 1, 2]));
  q.push(mc("hard", "A sphere has SA $36\\pi$; its radius is:", ["$3$", "$6$", "$9$", "$\\sqrt{6}$"], 0));
  q.push(mc("hard", "A sphere has SA $64\\pi$; its radius is:", ["$4$", "$8$", "$16$", "$2$"], 0));
  q.push(mc("hard", "V of a hemisphere $r=6$ (exact).", ["$144\\pi$", "$288\\pi$", "$72\\pi$", "$216\\pi$"], 0));
  q.push(mc("hard", "A basketball $r=12$ cm: its volume (1 dp).", ["$7238.2$", "$1809.6$", "$904.8$", "$2304$"], 0));
  q.push(mc("hard", "Two spheres have radii ratio $1:2$. Their volumes are in ratio:", ["$1:8$", "$1:2$", "$1:4$", "$1:6$"], 0));
  q.push(ms("hard", "To find $r$ from the SA:", ["$4\\pi r^2=$ SA", "divide by $4\\pi$", "take the square root", "multiply by $4\\pi$"], [0, 1, 2]));
  q.push(ms("hard", "Which equal $288\\pi$?", ["V sphere $r=6$", "$\\tfrac43\\pi(216)$", "$2\\times144\\pi$", "SA sphere $r=6$"], [0, 1, 2]));
  q.push(ms("hard", "Volume scaling:", ["radius $\\times2\\to$ V $\\times8$", "scales as $r^3$", "ratio $1:2\\to1:8$", "scales linearly"], [0, 1, 2]));
  q.push(ms("hard", "Hemisphere volume:", ["half the sphere", "$\\tfrac23\\pi r^3$", "$r=6\\to144\\pi$", "equals the sphere"], [0, 1, 2]));
  q.push(tf("hard", "A sphere with SA $36\\pi$ has radius $3$.", true));
  q.push(tf("hard", "Doubling the radius multiplies the volume by $8$.", true));
  q.push(tf("hard", "A sphere with SA $64\\pi$ has radius $8$.", false));
  q.push(fill("hard", "A sphere has SA $36\\pi$; $r=$ ___.", ["3"]));
  q.push(fill("hard", "A sphere has SA $64\\pi$; $r=$ ___.", ["4"]));
  q.push(fill("hard", "V of a hemisphere $r=6$ (multiple of $\\pi$):", ["144"]));
  q.push(num("hard", "SA of a sphere $r=10$ as a multiple of $\\pi$.", 400, 0));
  q.push(num("hard", "V of a sphere $r=6$ as a multiple of $\\pi$.", 288, 0));
  q.push(num("hard", "A sphere with SA $100\\pi$: its radius.", 5, 0));
  q.push(order("hard", "Order the steps to find a sphere's radius from its surface area.", ["Write $4\\pi r^2=$ SA", "Divide both sides by $4\\pi$", "Take the square root", "State $r$"]));
  q.push(match("hard", "Match each sphere to its radius (from SA).", ["SA $=36\\pi$", "SA $=64\\pi$", "SA $=100\\pi$"], ["$3$", "$4$", "$5$"], [0, 1, 2]));
  return q;
}

// ── 4.6 Composite Figures & Measurement Problems ─────────────
function g46() {
  const q = [];
  q.push(mc("easy", "To find a composite figure's volume:", ["break it into simple solids", "guess", "measure once", "use one formula"], 0));
  q.push(mc("easy", "A silo is a cylinder plus:", ["a hemisphere on top", "another cylinder only", "a cube", "nothing"], 0));
  q.push(mc("easy", "When there is a hole, you:", ["subtract its volume", "add it", "ignore it", "double it"], 0));
  q.push(mc("easy", "V of a cylinder ($r=3,h=10$) + hemisphere ($r=3$) (exact).", ["$108\\pi$", "$90\\pi$", "$126\\pi$", "$18\\pi$"], 0));
  q.push(mc("easy", "For composite surface area, count:", ["only exposed faces", "all faces twice", "hidden joins too", "no faces"], 0));
  q.push(mc("easy", "Keep $\\pi$:", ["exact until the end", "never", "round immediately", "drop it"], 0));
  q.push(ms("easy", "Strategy for composites:", ["identify simple solids", "compute each", "add (or subtract)", "use one formula"], [0, 1, 2]));
  q.push(ms("easy", "Which are composite solids?", ["silo (cylinder + hemisphere)", "ice-cream cone (cone + hemisphere)", "a pipe (cylinder $-$ hole)", "a plain cube"], [0, 1, 2]));
  q.push(ms("easy", "Subtracting a hole:", ["compute the outer volume", "subtract the hole's volume", "e.g. a pipe", "add the hole"], [0, 1, 2]));
  q.push(ms("easy", "Composite SA:", ["count exposed faces", "drop hidden joins", "a hemisphere-on-cylinder join isn't a surface", "count every face"], [0, 1, 2]));
  q.push(tf("easy", "To find a composite volume, break it into simple solids.", true));
  q.push(tf("easy", "A hole is subtracted from the volume.", true));
  q.push(tf("easy", "You count hidden joined faces in surface area.", false));
  q.push(fill("easy", "V of cylinder ($r=3,h=10$) + hemisphere ($r=3$) (multiple of $\\pi$):", ["108"]));
  q.push(fill("easy", "V of box $5\\times5\\times2$ + pyramid (base $5\\times5$, $h=6$):", ["100"]));
  q.push(fill("easy", "V of a cube side $3$ with a $1\\times1\\times3$ hole:", ["24"]));
  q.push(num("easy", "V of box $5\\times5\\times2$ + pyramid (base $5\\times5$, $h=6$).", 100, 0));
  q.push(num("easy", "V of a cube side $3$ minus a $1\\times1\\times3$ hole.", 24, 0));
  q.push(num("easy", "Painted area of a cube (side $5$) resting on the ground.", 125, 0));
  q.push(match("easy", "Match each composite to its parts.", ["silo", "ice-cream cone", "pipe"], ["cylinder + hemisphere", "cone + hemisphere", "cylinder $-$ hole"], [0, 1, 2]));
  q.push(mc("medium", "V of cylinder $r=3,h=10$ + hemisphere $r=3$ (exact).", ["$108\\pi$", "$90\\pi$", "$126\\pi$", "$54\\pi$"], 0));
  q.push(mc("medium", "V of cone $r=3,h=8$ + hemisphere $r=3$ (exact).", ["$42\\pi$", "$24\\pi$", "$60\\pi$", "$18\\pi$"], 0));
  q.push(mc("medium", "V of a pipe: cylinder $R=5$ $-$ hole $r=3$, length $10$ (exact).", ["$160\\pi$", "$250\\pi$", "$90\\pi$", "$340\\pi$"], 0));
  q.push(mc("medium", "V of box $5\\times5\\times2$ + pyramid (base $5\\times5$, $h=6$).", ["$100$", "$50$", "$150$", "$200$"], 0));
  q.push(mc("medium", "Painted area of a cube side $4$ on the ground.", ["$80$", "$96$", "$64$", "$48$"], 0));
  q.push(mc("medium", "V of cylinder $r=2,h=6$ + hemisphere $r=2$ (exact).", ["$\\tfrac{88}{3}\\pi$", "$24\\pi$", "$\\tfrac{16}{3}\\pi$", "$28\\pi$"], 0));
  q.push(ms("medium", "For a silo (cyl $r=3,h=10$ + hemisphere $r=3$):", ["cylinder $90\\pi$", "hemisphere $18\\pi$", "total $108\\pi$", "$\\approx339.3$"], [0, 1, 2, 3]));
  q.push(ms("medium", "For a pipe ($R=5$, hole $r=3$, length $10$):", ["outer $250\\pi$", "hole $90\\pi$", "material $160\\pi$", "add the hole"], [0, 1, 2]));
  q.push(ms("medium", "Composite volume:", ["add the combined parts", "subtract holes", "keep $\\pi$ exact", "always add"], [0, 1, 2]));
  q.push(ms("medium", "A cube on the ground:", ["$5$ faces painted", "the bottom is not painted", "painted area $5s^2$", "$6$ faces painted"], [0, 1, 2]));
  q.push(tf("medium", "A silo (cyl $r=3,h=10$ + hemisphere $r=3$) has volume $108\\pi$.", true));
  q.push(tf("medium", "A pipe's material volume $=$ outer $-$ hole.", true));
  q.push(tf("medium", "A cube resting on the ground has all $6$ faces painted.", false));
  q.push(fill("medium", "V of cylinder $r=3,h=10$ + hemisphere $r=3$ (multiple of $\\pi$):", ["108"]));
  q.push(fill("medium", "V of a pipe $R=5$ $-$ $r=3$, length $10$ (multiple of $\\pi$):", ["160"]));
  q.push(fill("medium", "Painted area of a cube side $4$ on the ground:", ["80"]));
  q.push(num("medium", "V of cone $r=3,h=8$ + hemisphere $r=3$ as a multiple of $\\pi$.", 42, 0));
  q.push(num("medium", "V of box $5\\times5\\times2$ + pyramid (base $5\\times5$, $h=6$).", 100, 0));
  q.push(num("medium", "V of a cube side $3$ minus a $1\\times1\\times3$ hole.", 24, 0));
  q.push(match("medium", "Match each composite to its volume.", ["silo cyl $r3h10$+hemi $r3$", "pipe $R5$$-$$r3$ len10", "cone $r3h8$+hemi $r3$"], ["$108\\pi$", "$160\\pi$", "$42\\pi$"], [0, 1, 2]));
  q.push(mc("hard", "V of a silo: cylinder $r=4,h=12$ + cone top $r=4,h=3$ (exact).", ["$208\\pi$", "$192\\pi$", "$224\\pi$", "$16\\pi$"], 0));
  q.push(mc("hard", "V of cone $r=3,h=8$ + hemisphere $r=3$ (1 dp).", ["$131.9$", "$75.4$", "$56.5$", "$113.1$"], 0));
  q.push(mc("hard", "A washer: disc $R=4$, hole $r=2$, thickness $1$ (exact).", ["$12\\pi$", "$16\\pi$", "$4\\pi$", "$20\\pi$"], 0));
  q.push(mc("hard", "A grain bin: cylinder $r=3,h=8$ + cone $r=3,h=4$ (exact).", ["$84\\pi$", "$72\\pi$", "$12\\pi$", "$96\\pi$"], 0));
  q.push(mc("hard", "V of a cube side $4$ with a $1\\times1\\times4$ hole.", ["$60$", "$64$", "$48$", "$56$"], 0));
  q.push(ms("hard", "For a silo (cyl $r=4,h=12$ + cone $r=4,h=3$):", ["cylinder $192\\pi$", "cone $16\\pi$", "total $208\\pi$", "subtract the cone"], [0, 1, 2]));
  q.push(ms("hard", "For a washer ($R=4$, hole $r=2$, thickness $1$):", ["outer $16\\pi$", "hole $4\\pi$", "material $12\\pi$", "add the hole"], [0, 1, 2]));
  q.push(ms("hard", "Composite strategy:", ["split into solids", "add or subtract", "keep $\\pi$ exact", "ignore hidden joins for SA"], [0, 1, 2, 3]));
  q.push(ms("hard", "Which require subtraction?", ["a pipe", "a drilled cube", "a washer", "a silo"], [0, 1, 2]));
  q.push(tf("hard", "A silo (cyl $r=4,h=12$ + cone $r=4,h=3$) has volume $208\\pi$.", true));
  q.push(tf("hard", "A washer's volume $=$ outer disc $-$ hole.", true));
  q.push(tf("hard", "A grain bin (cyl $r=3,h=8$ + cone $r=3,h=4$) has volume $96\\pi$.", false));
  q.push(fill("hard", "V of silo cyl $r=4,h=12$ + cone $r=4,h=3$ (multiple of $\\pi$):", ["208"]));
  q.push(fill("hard", "V of washer $R=4$, hole $r=2$, thickness $1$ (multiple of $\\pi$):", ["12"]));
  q.push(fill("hard", "V of a cube side $4$ with a $1\\times1\\times4$ hole:", ["60"]));
  q.push(num("hard", "V of grain bin cyl $r=3,h=8$ + cone $r=3,h=4$ as a multiple of $\\pi$.", 84, 0));
  q.push(num("hard", "V of a box $5\\times3\\times2$ + pyramid (base $5\\times3$, $h=6$).", 60, 0));
  q.push(num("hard", "Painted area of a cube side $5$ on the ground.", 125, 0));
  q.push(order("hard", "Order the steps for a composite figure's volume.", ["Identify the simple solids", "Compute each volume", "Add parts (subtract holes)", "State the total"]));
  q.push(match("hard", "Match each composite to its volume.", ["silo cyl $r4h12$+cone $r4h3$", "washer $R4$ hole $r2$ t1", "grain bin cyl $r3h8$+cone $r3h4$"], ["$208\\pi$", "$12\\pi$", "$84\\pi$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "4.1", gen: g41 },
  { code: "4.2", gen: g42 },
  { code: "4.3", gen: g43 },
  { code: "4.4", gen: g44 },
  { code: "4.5", gen: g45 },
  { code: "4.6", gen: g46 },
];
