export default {
  grade: "MTH1W",
  code: "1.1",
  title: "Number Sets & Their Subsets",
  intro: "Numbers are organized into sets — natural ($\\mathbb{N}$), whole ($\\mathbb{W}$), integers ($\\mathbb{Z}$), rational ($\\mathbb{Q}$), irrational, and real ($\\mathbb{R}$). This worksheet builds skill in classifying numbers and understanding how the sets nest: $\\mathbb{N}\\subset\\mathbb{W}\\subset\\mathbb{Z}\\subset\\mathbb{Q}\\subset\\mathbb{R}$.",
  lesson: [
    ["What is a number set?", "In math we sort numbers into groups called <b>sets</b> — a set is just a collection of numbers that share a property. The number sets fit <b>inside one another like nested boxes</b>, so one number usually belongs to several sets at the same time. The whole point of this topic is to look at a number and name every set it lives in."],
    ["The six sets you need to know", "<b>Natural, $\\mathbb{N}$</b> — the counting numbers: $1, 2, 3, 4, \\dots$ (no zero, no negatives, no fractions).<br><b>Whole, $\\mathbb{W}$</b> — the natural numbers <b>plus zero</b>: $0, 1, 2, 3, \\dots$<br><b>Integers, $\\mathbb{Z}$</b> — the whole numbers <b>and their negatives</b>: $\\dots, -3, -2, -1, 0, 1, 2, 3, \\dots$ (still no fractions or decimals).<br><b>Rational, $\\mathbb{Q}$</b> — any number you can write as a <b>fraction $\\dfrac{a}{b}$</b> of two integers (with $b\\ne 0$). This includes every integer, every fraction, every decimal that <b>ends</b> (like $0.75=\\tfrac34$), and every decimal that <b>repeats</b> (like $0.\\overline{3}=\\tfrac13$).<br><b>Irrational</b> — numbers that <b>cannot</b> be written as a fraction. Their decimals go on <b>forever with no repeating pattern</b>, for example $\\sqrt{2}=1.41421\\dots$ and $\\pi=3.14159\\dots$<br><b>Real, $\\mathbb{R}$</b> — <b>every number on the number line</b>: all the rationals and all the irrationals together."],
    ["How the sets nest", "Each set sits neatly inside the next larger one:<br>$\\mathbb{N}\\subset\\mathbb{W}\\subset\\mathbb{Z}\\subset\\mathbb{Q}\\subset\\mathbb{R}$<br>So a natural number like $5$ is <b>also</b> whole, an integer, rational, and real — you list them all. The only real numbers that are <b>not</b> rational are the irrationals; together the rationals and irrationals make up every real number."],
    ["A quick way to classify any number", "<b>Step 1 — Simplify first.</b> A number in disguise may be simpler than it looks: $\\sqrt{9}=3$ and $\\dfrac{6}{2}=3$ are really whole numbers, not roots or fractions.<br><b>Step 2 — Fraction or decimal?</b> If it is a fraction, or a decimal that <b>ends or repeats</b>, it is <b>rational</b>. If its decimal runs on forever with <b>no pattern</b>, it is <b>irrational</b>.<br><b>Step 3 — List every larger set.</b> Once you know the smallest set it fits, add every set above it in the chain."],
  ],
  examples: [
    ["Example 1: Classifying a counting number", "List every set that $7$ belongs to.", "$7$ is a positive counting number with no fraction or decimal part.<br>It is <b>natural, whole, integer, rational, and real</b>.<br>(Rational because $7 = \\dfrac{7}{1}$.)"],
    ["Example 2: A negative integer", "List every set that $-4$ belongs to.", "$-4$ is negative, so it is not natural and not whole.<br>It is an <b>integer, rational ($-4=\\dfrac{-4}{1}$), and real</b>."],
    ["Example 3: Zero", "List every set that $0$ belongs to.", "Using $\\mathbb{N}=\\{1,2,3,\\dots\\}$, zero is not natural.<br>$0$ is <b>whole, integer, rational, and real</b>."],
    ["Example 4: A fraction", "Classify $\\dfrac{3}{5}$.", "It is a ratio of two integers, so it is <b>rational</b> (and therefore <b>real</b>). It is not an integer."],
    ["Example 5: A non-perfect square root", "Classify $\\sqrt{2}$.", "$\\sqrt{2}=1.41421356\\dots$ never terminates or repeats, so it cannot be written as a fraction.<br>It is <b>irrational</b> (and <b>real</b>)."],
    ["Example 6: A terminating decimal", "Classify $0.75$.", "$0.75=\\dfrac{3}{4}$, a ratio of integers.<br>It is <b>rational</b> and <b>real</b>."],
    ["Example 7: A hidden perfect square", "Classify $\\sqrt{9}$.", "$\\sqrt{9}=3$ — a perfect square root simplifies to a whole number.<br>So $\\sqrt9$ is <b>natural, whole, integer, rational, and real</b> (not irrational!)."],
    ["Example 8: Subset reasoning", "True or false: every integer is a rational number.", "Any integer $n$ can be written $\\dfrac{n}{1}$, a ratio of integers.<br><b>True</b> — $\\mathbb{Z}\\subset\\mathbb{Q}$."],
    ["Example 9: Where do irrationals fit?", "Are irrational numbers part of the real numbers? Are they rational?", "Irrational numbers are <b>real</b> but <b>not rational</b> — they fill the gaps between rationals on the number line. $\\mathbb{Q}$ and the irrationals together make up $\\mathbb{R}$."],
  ],
  questions: [
    ["Problem 1: Classify a counting number", "List every set that $12$ belongs to.", "Natural, whole, integer, rational, real"],
    ["Problem 2: Negative integer", "List every set that $-9$ belongs to.", "Integer, rational, real"],
    ["Problem 3: Fraction", "Classify $\\dfrac{2}{7}$.", "Rational, real"],
    ["Problem 4: Root", "Classify $\\sqrt{5}$.", "Irrational, real"],
    ["Problem 5: Repeating decimal", "Classify $0.\\overline{3}$ (i.e. $0.333\\dots$).", "Rational, real $\\left(=\\tfrac{1}{3}\\right)$"],
    ["Problem 6: Hidden perfect square", "Classify $\\sqrt{16}$.", "$\\sqrt{16}=4$: natural, whole, integer, rational, real"],
    ["Problem 7: Negative decimal", "Classify $-2.5$.", "Rational, real"],
    ["Problem 8: Famous constant", "Classify $\\pi$.", "Irrational, real"],
    ["Problem 9: Subset true/false", "True or false: every whole number is an integer.", "True"],
    ["Problem 10: Subset true/false", "True or false: every rational number is an integer.", "False (e.g. $\\tfrac{1}{2}$)"],
    ["Problem 11: Natural or not?", "Using $\\mathbb{N}=\\{1,2,3,\\dots\\}$, is $0$ a natural number?", "No — $0$ is whole, not natural"],
    ["Problem 12: Name the set", "What name is given to numbers that cannot be written as a fraction of two integers?", "Irrational numbers"],
    ["Problem 13: Simplify then classify", "Simplify $\\sqrt{49}$ and classify the result.", "$7$ — natural, whole, integer, rational, real"],
  ],
};
