export default {
  grade: "MTH1W",
  code: "1.2",
  title: "Density, Infinity & Limit",
  intro: "The rational numbers are <i>dense</i>: between any two different numbers there is always another. This worksheet explores finding numbers between numbers, the idea of infinity, and how a sequence can approach a limiting value.",
  examples: [
    ["Example 1: A number between two fractions", "Find a number between $\\dfrac{1}{2}$ and $\\dfrac{3}{4}$.", "Take the average: $\\dfrac{\\frac12+\\frac34}{2} = \\dfrac{\\frac54}{2} = \\dfrac{5}{8}$.<br>Check: $0.5 < 0.625 < 0.75$ ✓"],
    ["Example 2: Between two decimals", "Find a number between $0.4$ and $0.5$.", "Any value in between works, e.g. $0.45$ (the midpoint)."],
    ["Example 3: Two numbers in a gap", "Find two numbers between $\\dfrac{1}{3}$ and $\\dfrac{2}{3}$.", "$\\dfrac13\\approx0.33$, $\\dfrac23\\approx0.67$. Two choices: $0.4$ and $0.5$."],
    ["Example 4: Is there a smallest positive number?", "Is there a smallest positive rational number?", "No. Whatever tiny number you pick, half of it is smaller and still positive — so there is <b>no smallest</b>. This is a consequence of density and infinity."],
    ["Example 5: Limit of a halving sequence", "What value does $1,\\ \\tfrac12,\\ \\tfrac14,\\ \\tfrac18,\\dots$ approach?", "Each term is half the previous one, getting closer and closer to but never reaching <b>$0$</b>. The limit is $0$."],
    ["Example 6: Limit approaching one", "What value does $\\dfrac12,\\ \\dfrac23,\\ \\dfrac34,\\ \\dfrac45,\\dots$ approach?", "The terms $\\dfrac{n}{n+1}$ creep upward toward but never reach <b>$1$</b>."],
    ["Example 7: A surprising equality", "What number does $0.999\\dots$ (repeating forever) equal?", "It equals exactly <b>$1$</b>. The endless 9s leave no gap between $0.999\\dots$ and $1$."],
    ["Example 8: Counting the in-between", "How many rational numbers are there between $0$ and $1$?", "<b>Infinitely many</b> — by density you can always find another between any two."],
    ["Example 9: Limit of a power", "What does $\\left(\\dfrac12\\right)^n$ approach as $n$ grows very large?", "$\\tfrac12,\\tfrac14,\\tfrac18,\\dots$ shrinks toward <b>$0$</b>."],
  ],
  questions: [
    ["Problem 1: Between two fractions", "Find a number between $\\dfrac{2}{5}$ and $\\dfrac{3}{5}$.", "$\\dfrac{1}{2}=0.5$"],
    ["Problem 2: Between two decimals", "Find a number between $0.7$ and $0.8$.", "$0.75$"],
    ["Problem 3: Midpoint", "Find the average of $\\dfrac{1}{4}$ and $\\dfrac{1}{2}$.", "$\\dfrac{3}{8}$"],
    ["Problem 4: Limit", "What does $1,\\ \\tfrac13,\\ \\tfrac19,\\ \\tfrac1{27},\\dots$ approach?", "$0$"],
    ["Problem 5: Limit", "What does $\\tfrac12,\\ \\tfrac34,\\ \\tfrac78,\\ \\tfrac{15}{16},\\dots$ approach?", "$1$"],
    ["Problem 6: Repeating decimal", "What does $0.4999\\dots$ equal?", "$0.5$"],
    ["Problem 7: How many?", "How many numbers are there between $0$ and $1$?", "Infinitely many"],
    ["Problem 8: Smallest?", "What is the smallest positive number?", "There is none"],
    ["Problem 9: Between", "Find a number between $0.99$ and $1$.", "$0.995$"],
    ["Problem 10: Limit of a power", "What does $\\left(\\dfrac13\\right)^n$ approach as $n\\to\\infty$?", "$0$"],
    ["Problem 11: Between eighths", "Find a number between $\\dfrac{5}{8}$ and $\\dfrac{3}{4}$.", "$\\dfrac{11}{16}$"],
    ["Problem 12: True/false", "True or false: between any two different rationals there is another rational.", "True"],
    ["Problem 13: Limit", "What does $\\dfrac{n}{n+1}$ approach as $n$ becomes very large?", "$1$"],
  ],
};
