export default {
  grade: "MTH1W",
  code: "1.3",
  title: "Powers & Scientific Notation",
  intro: "A power $a^n$ means the base $a$ multiplied by itself $n$ times. Scientific notation writes a number as $a\\times 10^n$ with $1\\le a<10$ — a compact way to handle very large and very small quantities.",
  examples: [
    ["Example 1: Evaluate a power", "Evaluate $2^5$.", "$2^5 = 2\\times2\\times2\\times2\\times2 = 32$."],
    ["Example 2: Power of ten", "Evaluate $10^4$.", "$10^4 = 10\\times10\\times10\\times10 = 10{,}000$ (a 1 followed by four zeros)."],
    ["Example 3: Large number to scientific notation", "Write $5400$ in scientific notation.", "Move the decimal so one non-zero digit is in front: $5400 = 5.4\\times 10^{3}$ (decimal moved 3 places left)."],
    ["Example 4: Small number to scientific notation", "Write $0.0072$ in scientific notation.", "$0.0072 = 7.2\\times 10^{-3}$ (decimal moved 3 places right ⇒ negative exponent)."],
    ["Example 5: Evaluate a power", "Evaluate $3^4$.", "$3^4 = 3\\times3\\times3\\times3 = 81$."],
    ["Example 6: Scientific notation to standard", "Write $6.1\\times 10^{5}$ in standard form.", "Move the decimal 5 places right: $610{,}000$."],
    ["Example 7: Small scientific notation to standard", "Write $2.3\\times 10^{-4}$ in standard form.", "Move the decimal 4 places left: $0.00023$."],
    ["Example 8: Negative base", "Evaluate $(-2)^3$.", "$(-2)(-2)(-2) = 4\\times(-2) = -8$. (Odd power of a negative ⇒ negative.)"],
    ["Example 9: Multiplying powers of ten", "Evaluate $(2\\times 10^{3})(4\\times 10^{2})$.", "Multiply the fronts and add the exponents: $2\\times4 = 8$, $10^{3+2}=10^{5}$.<br>$= 8\\times 10^{5} = 800{,}000$."],
  ],
  questions: [
    ["Problem 1: Evaluate", "Evaluate $2^6$.", "$64$"],
    ["Problem 2: Power of ten", "Evaluate $10^3$.", "$1000$"],
    ["Problem 3: Evaluate", "Evaluate $7^2$.", "$49$"],
    ["Problem 4: Negative base (even)", "Evaluate $(-3)^2$.", "$9$"],
    ["Problem 5: Negative base (odd)", "Evaluate $(-3)^3$.", "$-27$"],
    ["Problem 6: To scientific notation", "Write $4500$ in scientific notation.", "$4.5\\times 10^{3}$"],
    ["Problem 7: To scientific notation", "Write $0.00089$ in scientific notation.", "$8.9\\times 10^{-4}$"],
    ["Problem 8: To standard form", "Write $3.2\\times 10^{4}$ in standard form.", "$32{,}000$"],
    ["Problem 9: To standard form", "Write $5\\times 10^{-3}$ in standard form.", "$0.005$"],
    ["Problem 10: Multiply", "Evaluate $(3\\times 10^{2})(2\\times 10^{4})$.", "$6\\times 10^{6}$"],
    ["Problem 11: Zero exponent", "Evaluate $2^0$.", "$1$"],
    ["Problem 12: Evaluate", "Evaluate $5^3$.", "$125$"],
    ["Problem 13: Divide powers of ten", "Evaluate $\\dfrac{10^{6}}{10^{2}}$.", "$10^{4}=10{,}000$"],
  ],
};
