export default {
  grade: "MTH1W",
  code: "1.4",
  title: "Exponent Laws",
  intro: "The exponent laws let us simplify powers without expanding them: product rule $a^m\\cdot a^n=a^{m+n}$, quotient rule $\\dfrac{a^m}{a^n}=a^{m-n}$, power of a power $(a^m)^n=a^{mn}$, power of a product $(ab)^n=a^n b^n$, zero exponent $a^0=1$, and negative exponent $a^{-n}=\\dfrac{1}{a^n}$.",
  examples: [
    ["Example 1: Product rule", "Simplify $x^3\\cdot x^4$.", "Add the exponents: $x^{3+4} = x^{7}$."],
    ["Example 2: Quotient rule", "Simplify $\\dfrac{x^7}{x^2}$.", "Subtract the exponents: $x^{7-2} = x^{5}$."],
    ["Example 3: Power of a power", "Simplify $(x^2)^3$.", "Multiply the exponents: $x^{2\\times3} = x^{6}$."],
    ["Example 4: Power of a product", "Simplify $(2x)^3$.", "Apply the power to each factor: $2^3 x^3 = 8x^{3}$."],
    ["Example 5: Zero exponent", "Simplify $x^0$ (with $x\\ne 0$).", "Any non-zero base to the power $0$ is $1$: $x^0 = 1$."],
    ["Example 6: Negative exponent", "Simplify $x^{-2}$.", "A negative exponent means reciprocal: $x^{-2} = \\dfrac{1}{x^{2}}$."],
    ["Example 7: Combining variables", "Simplify $(x^3 y^2)(x\\, y^4)$.", "Add exponents on like bases: $x^{3+1}y^{2+4} = x^{4}y^{6}$."],
    ["Example 8: Coefficient with power of a power", "Simplify $(3x^2)^2$.", "$3^2 (x^2)^2 = 9x^{4}$."],
    ["Example 9: Equal powers", "Simplify $\\dfrac{a^5}{a^5}$.", "$a^{5-5} = a^0 = 1$."],
  ],
  questions: [
    ["Problem 1: Product rule", "Simplify $a^2\\cdot a^5$.", "$a^{7}$"],
    ["Problem 2: Quotient rule", "Simplify $\\dfrac{y^8}{y^3}$.", "$y^{5}$"],
    ["Problem 3: Power of a power", "Simplify $(m^4)^2$.", "$m^{8}$"],
    ["Problem 4: Power of a product", "Simplify $(3y)^2$.", "$9y^{2}$"],
    ["Problem 5: Coefficient + power", "Simplify $(2a^3)^3$.", "$8a^{9}$"],
    ["Problem 6: Negative exponent", "Simplify $x^{-3}$.", "$\\dfrac{1}{x^{3}}$"],
    ["Problem 7: Zero exponent", "Simplify $5x^0$ (with $x\\ne0$).", "$5$"],
    ["Problem 8: Combine variables", "Simplify $(x^2 y)(x^3 y^4)$.", "$x^{5}y^{5}$"],
    ["Problem 9: Equal powers", "Simplify $\\dfrac{p^6}{p^6}$.", "$1$"],
    ["Problem 10: Power of a product", "Simplify $(a^2 b^3)^2$.", "$a^{4}b^{6}$"],
    ["Problem 11: Numeric product", "Simplify $2^3\\cdot 2^2$.", "$2^{5}=32$"],
    ["Problem 12: Numeric quotient", "Simplify $\\dfrac{10^4}{10^1}$.", "$10^{3}=1000$"],
    ["Problem 13: Negative result", "Simplify $\\dfrac{x^5}{x^8}$.", "$x^{-3}=\\dfrac{1}{x^{3}}$"],
  ],
};
