export default {
  grade: "MTH1W",
  code: "1.4",
  title: "Integers in Context",
  intro: "This worksheet goes beyond simple integer arithmetic: order of operations with negative numbers and exponents, the difference between a negative base and a negative sign in front of a power, and substituting negative values into algebraic expressions.",
  examples: [
    ["Example 1: Negative base vs. negative sign", "Evaluate $-4^2$ and $(-4)^2$.", "$-4^2$ has no brackets, so only $4$ is squared, then negated: $-4^2=-16$.<br>$(-4)^2$ has brackets, so $-4$ is the base: $(-4)(-4)=16$."],
    ["Example 2: Sign prediction", "Without calculating, is $-(-3)^3$ positive or negative? Then evaluate.", "$(-3)^3$ is negative (odd exponent on a negative base); negating a negative gives a positive.<br>$(-3)^3=-27$, so $-(-27)=27$."],
    ["Example 3: Calculate a fraction of integers", "Evaluate $\\dfrac{-7(10)}{-14}$.", "Numerator: $-7\\times10=-70$.<br>$-70\\div-14=5$ (same signs give a positive quotient)."],
    ["Example 4: Order of operations with an exponent", "Evaluate $5(-2)^3$.", "Exponent first: $(-2)^3=-8$.<br>Then multiply: $5\\times(-8)=-40$."],
    ["Example 5: Nested brackets and an exponent", "Evaluate $\\left[-4(-1)^2\\right]^3$.", "Innermost exponent: $(-1)^2=1$.<br>Inside the brackets: $-4\\times1=-4$.<br>Outer exponent: $(-4)^3=-64$."],
    ["Example 6: A fraction with exponents top and bottom", "Evaluate $\\dfrac{(-4)^2-21}{-2^2}$.", "Numerator: $16-21=-5$.<br>Denominator: $-2^2=-4$.<br>$-5\\div-4=\\dfrac{5}{4}$."],
    ["Example 7: Substitution", "Evaluate $x^2+y^3$ when $x=-2$ and $y=-3$.", "Substitute with brackets: $(-2)^2+(-3)^3$.<br>$4+(-27)=-23$."],
    ["Example 8: Substitution with brackets", "Evaluate $x^2+\\left[4x-2(y-x)\\right]$ when $x=-2$ and $y=-3$.", "$y-x=(-3)-(-2)=-1$.<br>$4(-2)-2(-1)=-8+2=-6$.<br>$(-2)^2+(-6)=4-6=-2$."],
    ["Example 9: Substitution into a fraction", "Evaluate $\\dfrac{4(x+y^2)}{x^2}$ when $x=-2$ and $y=-3$.", "$y^2=9$, so $x+y^2=-2+9=7$; then $4(7)=28$.<br>$x^2=4$.<br>$28\\div4=7$."],
  ],
  questions: [
    ["Problem 1: Sign prediction", "Without calculating, is $-3^5$ positive or negative? Evaluate.", "$-243$"],
    ["Problem 2: Sign prediction", "Without calculating, is $(-3)^6$ positive or negative? Evaluate.", "$729$"],
    ["Problem 3: Sign prediction", "Evaluate $-(-5)^2$.", "$-25$"],
    ["Problem 4: Calculate", "Evaluate $\\dfrac{-8(9)}{-6}$.", "$12$"],
    ["Problem 5: Calculate", "Evaluate $\\dfrac{20}{-4(5)}$.", "$-1$"],
    ["Problem 6: Order of operations", "Evaluate $3(-4)^2$.", "$48$"],
    ["Problem 7: Nested brackets", "Evaluate $\\left[-3(-2)^2\\right]^2$.", "$144$"],
    ["Problem 8: Fraction with exponents", "Evaluate $\\dfrac{3^2-13}{-2^2}$.", "$1$"],
    ["Problem 9: Mixed operations", "Evaluate $-4^2-(-6+3^2)$.", "$-19$"],
    ["Problem 10: Substitution", "Evaluate $x^2+y^3$ when $x=-3$ and $y=-1$.", "$8$"],
    ["Problem 11: Substitution with brackets", "Evaluate $x^2+\\left[3x-2(y-x)\\right]$ when $x=-3$ and $y=-1$.", "$-4$"],
    ["Problem 12: Triple product", "Evaluate $(-2)\\times(-1)\\times(-4)$.", "$-8$"],
    ["Problem 13: Substitution into a fraction", "Evaluate $\\dfrac{6(x+y^2)}{x^2}$ when $x=-3$ and $y=-1$.", "$-\\dfrac{4}{3}$"],
  ],
};
