export default {
  grade: "MTH1W",
  code: "1.5",
  title: "Integers in Context",
  intro: "Integers — the positive and negative whole numbers and zero — model real situations like temperature, elevation, and money. This worksheet practises adding, subtracting, multiplying, and dividing integers, including word problems.",
  examples: [
    ["Example 1: Adding with different signs", "Evaluate $(-5) + 8$.", "Different signs ⇒ subtract and keep the sign of the larger size: $8 - 5 = 3$.<br>$(-5) + 8 = 3$."],
    ["Example 2: Adding two negatives", "Evaluate $(-3) + (-7)$.", "Same sign ⇒ add the sizes, keep the sign: $3 + 7 = 10$.<br>$(-3) + (-7) = -10$."],
    ["Example 3: Subtraction giving a negative", "Evaluate $6 - 10$.", "$6 - 10 = -(10 - 6) = -4$."],
    ["Example 4: Subtracting a negative", "Evaluate $(-4) - (-9)$.", "Subtracting a negative adds: $(-4) + 9 = 5$."],
    ["Example 5: Multiplying integers", "Evaluate $(-3) \\times 4$.", "Different signs ⇒ negative product: $(-3)\\times 4 = -12$."],
    ["Example 6: Product of two negatives", "Evaluate $(-6) \\times (-5)$.", "Same signs ⇒ positive product: $(-6)\\times(-5) = 30$."],
    ["Example 7: Dividing integers", "Evaluate $(-20) \\div 4$.", "Different signs ⇒ negative quotient: $(-20)\\div 4 = -5$."],
    ["Example 8: Temperature", "The temperature is $-8^{\\circ}$C and rises $5^{\\circ}$. What is the new temperature?", "Rising means add: $-8 + 5 = -3$.<br>New temperature $= -3^{\\circ}$C."],
    ["Example 9: Elevation", "A diver at $-15$ m descends $7$ m more. Find the new depth.", "Descending means going more negative: $-15 + (-7) = -22$.<br>New depth $= -22$ m."],
  ],
  questions: [
    ["Problem 1: Add", "Evaluate $(-7) + 12$.", "$5$"],
    ["Problem 2: Add negatives", "Evaluate $(-9) + (-4)$.", "$-13$"],
    ["Problem 3: Subtract", "Evaluate $3 - 11$.", "$-8$"],
    ["Problem 4: Subtract a negative", "Evaluate $(-5) - (-8)$.", "$3$"],
    ["Problem 5: Multiply", "Evaluate $(-6) \\times 7$.", "$-42$"],
    ["Problem 6: Multiply negatives", "Evaluate $(-8) \\times (-3)$.", "$24$"],
    ["Problem 7: Divide", "Evaluate $(-24) \\div 6$.", "$-4$"],
    ["Problem 8: Divide negatives", "Evaluate $(-36) \\div (-9)$.", "$4$"],
    ["Problem 9: Temperature", "The temperature is $-4^{\\circ}$C and drops $9^{\\circ}$. Find the new temperature.", "$-13^{\\circ}$C"],
    ["Problem 10: Money", "A bank balance of $-\\$20$ receives a $\\$50$ deposit. Find the balance.", "$\\$30$"],
    ["Problem 11: Elevation", "From an elevation of $-120$ m, a balloon rises $200$ m. Find the new elevation.", "$80$ m"],
    ["Problem 12: Triple product", "Evaluate $(-2) \\times (-3) \\times (-1)$.", "$-6$"],
    ["Problem 13: Mixed operations", "Evaluate $5 + (-12) - (-3)$.", "$-4$"],
  ],
};
