export default {
  grade: "MTH1W",
  code: "1.6",
  title: "Fractions & Unit Fractions",
  intro: "A fraction represents part of a whole; a <i>unit fraction</i> has numerator $1$. This worksheet practises simplifying fractions, finding equivalent fractions, converting between mixed and improper forms, and comparing fractions.",
  examples: [
    ["Example 1: Simplify", "Simplify $\\dfrac{6}{8}$.", "Divide top and bottom by the GCF $2$: $\\dfrac{6\\div2}{8\\div2} = \\dfrac{3}{4}$."],
    ["Example 2: Simplify", "Simplify $\\dfrac{10}{15}$.", "GCF is $5$: $\\dfrac{10\\div5}{15\\div5} = \\dfrac{2}{3}$."],
    ["Example 3: Equivalent fractions", "Is $\\dfrac{2}{3} = \\dfrac{4}{6}$?", "$\\dfrac{2}{3} = \\dfrac{2\\times2}{3\\times2} = \\dfrac{4}{6}$. Yes — they are equivalent."],
    ["Example 4: Comparing", "Which is larger, $\\dfrac{2}{3}$ or $\\dfrac{3}{4}$?", "Common denominator $12$: $\\dfrac{2}{3}=\\dfrac{8}{12}$, $\\dfrac{3}{4}=\\dfrac{9}{12}$.<br>$\\dfrac{3}{4}$ is larger."],
    ["Example 5: Unit fractions", "Write $\\dfrac{3}{4}$ as a sum of unit fractions.", "$\\dfrac{3}{4} = \\dfrac{1}{4}+\\dfrac{1}{4}+\\dfrac{1}{4}$."],
    ["Example 6: Improper to mixed", "Write $\\dfrac{7}{4}$ as a mixed number.", "$7\\div4 = 1$ remainder $3$, so $\\dfrac{7}{4} = 1\\dfrac{3}{4}$."],
    ["Example 7: Mixed to improper", "Write $2\\dfrac{1}{3}$ as an improper fraction.", "$2\\times3 + 1 = 7$, so $2\\dfrac{1}{3} = \\dfrac{7}{3}$."],
    ["Example 8: Build an equivalent", "Write $\\dfrac{2}{5}$ with denominator $20$.", "$20\\div5 = 4$, so multiply top and bottom by $4$: $\\dfrac{2}{5} = \\dfrac{8}{20}$."],
    ["Example 9: Compare to a half", "Which is larger, $\\dfrac{5}{8}$ or $\\dfrac{1}{2}$?", "$\\dfrac{1}{2}=\\dfrac{4}{8}$, and $\\dfrac{5}{8} > \\dfrac{4}{8}$.<br>$\\dfrac{5}{8}$ is larger."],
  ],
  questions: [
    ["Problem 1: Simplify", "Simplify $\\dfrac{9}{12}$.", "$\\dfrac{3}{4}$"],
    ["Problem 2: Simplify", "Simplify $\\dfrac{14}{21}$.", "$\\dfrac{2}{3}$"],
    ["Problem 3: Equivalent?", "Is $\\dfrac{3}{5} = \\dfrac{6}{10}$?", "Yes"],
    ["Problem 4: Compare", "Which is larger, $\\dfrac{3}{8}$ or $\\dfrac{1}{2}$?", "$\\dfrac{1}{2}$"],
    ["Problem 5: Unit fractions", "Write $\\dfrac{5}{6}$ as a sum of unit fractions.", "$\\dfrac{1}{6}+\\dfrac{1}{6}+\\dfrac{1}{6}+\\dfrac{1}{6}+\\dfrac{1}{6}$"],
    ["Problem 6: Improper to mixed", "Write $\\dfrac{11}{3}$ as a mixed number.", "$3\\dfrac{2}{3}$"],
    ["Problem 7: Mixed to improper", "Write $3\\dfrac{1}{4}$ as an improper fraction.", "$\\dfrac{13}{4}$"],
    ["Problem 8: Build equivalent", "Write $\\dfrac{3}{4}$ with denominator $12$.", "$\\dfrac{9}{12}$"],
    ["Problem 9: Compare", "Which is larger, $\\dfrac{2}{3}$ or $\\dfrac{5}{9}$?", "$\\dfrac{2}{3}$ $\\left(=\\tfrac{6}{9}\\right)$"],
    ["Problem 10: Simplify", "Simplify $\\dfrac{8}{24}$.", "$\\dfrac{1}{3}$"],
    ["Problem 11: Unit fraction", "Write the unit fraction with denominator $7$.", "$\\dfrac{1}{7}$"],
    ["Problem 12: Compare", "Which is larger, $\\dfrac{7}{10}$ or $\\dfrac{3}{4}$?", "$\\dfrac{3}{4}$ $\\left(\\tfrac{30}{40}>\\tfrac{28}{40}\\right)$"],
    ["Problem 13: Build equivalent", "Write $\\dfrac{4}{5}$ with denominator $25$.", "$\\dfrac{20}{25}$"],
  ],
};
