export default {
  grade: "MTH1W",
  code: "1.7",
  title: "Operations with Positive & Negative Fractions",
  intro: "This worksheet combines fraction skills with integer sign rules: add and subtract using a common denominator, multiply straight across, and divide by multiplying by the reciprocal — all while tracking positive and negative signs.",
  examples: [
    ["Example 1: Add fractions", "Evaluate $\\dfrac{1}{2} + \\dfrac{1}{3}$.", "Common denominator $6$: $\\dfrac{3}{6} + \\dfrac{2}{6} = \\dfrac{5}{6}$."],
    ["Example 2: Subtract fractions", "Evaluate $\\dfrac{3}{4} - \\dfrac{1}{6}$.", "Common denominator $12$: $\\dfrac{9}{12} - \\dfrac{2}{12} = \\dfrac{7}{12}$."],
    ["Example 3: Add with a negative", "Evaluate $-\\dfrac{1}{2} + \\dfrac{1}{4}$.", "$-\\dfrac{2}{4} + \\dfrac{1}{4} = -\\dfrac{1}{4}$."],
    ["Example 4: Multiply", "Evaluate $\\dfrac{2}{3} \\times \\dfrac{3}{5}$.", "Multiply across: $\\dfrac{6}{15} = \\dfrac{2}{5}$."],
    ["Example 5: Multiply with a negative", "Evaluate $-\\dfrac{3}{4} \\times \\dfrac{2}{9}$.", "$-\\dfrac{6}{36} = -\\dfrac{1}{6}$ (different signs ⇒ negative)."],
    ["Example 6: Divide", "Evaluate $\\dfrac{1}{2} \\div \\dfrac{3}{4}$.", "Multiply by the reciprocal: $\\dfrac{1}{2}\\times\\dfrac{4}{3} = \\dfrac{4}{6} = \\dfrac{2}{3}$."],
    ["Example 7: Divide with a negative", "Evaluate $-\\dfrac{5}{6} \\div \\dfrac{5}{12}$.", "$-\\dfrac{5}{6}\\times\\dfrac{12}{5} = -\\dfrac{60}{30} = -2$."],
    ["Example 8: Subtract negatives", "Evaluate $-\\dfrac{2}{3} - \\dfrac{1}{6}$.", "$-\\dfrac{4}{6} - \\dfrac{1}{6} = -\\dfrac{5}{6}$."],
    ["Example 9: Multiply signs", "Evaluate $\\dfrac{1}{2} \\times \\left(-\\dfrac{4}{5}\\right)$.", "$-\\dfrac{4}{10} = -\\dfrac{2}{5}$."],
  ],
  questions: [
    ["Problem 1: Add", "Evaluate $\\dfrac{1}{4} + \\dfrac{2}{3}$.", "$\\dfrac{11}{12}$"],
    ["Problem 2: Subtract", "Evaluate $\\dfrac{5}{6} - \\dfrac{1}{2}$.", "$\\dfrac{1}{3}$"],
    ["Problem 3: Add with negative", "Evaluate $-\\dfrac{2}{5} + \\dfrac{1}{2}$.", "$\\dfrac{1}{10}$"],
    ["Problem 4: Multiply", "Evaluate $\\dfrac{3}{8} \\times \\dfrac{4}{9}$.", "$\\dfrac{1}{6}$"],
    ["Problem 5: Multiply negative", "Evaluate $-\\dfrac{1}{3} \\times \\dfrac{6}{7}$.", "$-\\dfrac{2}{7}$"],
    ["Problem 6: Divide", "Evaluate $\\dfrac{2}{3} \\div \\dfrac{4}{9}$.", "$\\dfrac{3}{2}$"],
    ["Problem 7: Divide negative", "Evaluate $-\\dfrac{3}{4} \\div \\dfrac{1}{2}$.", "$-\\dfrac{3}{2}$"],
    ["Problem 8: Subtract", "Evaluate $-\\dfrac{1}{2} - \\dfrac{1}{3}$.", "$-\\dfrac{5}{6}$"],
    ["Problem 9: Multiply negative", "Evaluate $\\dfrac{5}{6} \\times \\left(-\\dfrac{3}{10}\\right)$.", "$-\\dfrac{1}{4}$"],
    ["Problem 10: Subtract", "Evaluate $\\dfrac{7}{8} - \\dfrac{3}{4}$.", "$\\dfrac{1}{8}$"],
    ["Problem 11: Add negatives", "Evaluate $-\\dfrac{2}{3} + \\left(-\\dfrac{1}{6}\\right)$.", "$-\\dfrac{5}{6}$"],
    ["Problem 12: Divide negative", "Evaluate $\\dfrac{4}{5} \\div \\left(-\\dfrac{2}{5}\\right)$.", "$-2$"],
    ["Problem 13: Three fractions", "Evaluate $\\dfrac{1}{2} + \\dfrac{1}{3} + \\dfrac{1}{6}$.", "$1$"],
  ],
};
