export default {
  grade: "MTH1W",
  code: "1.8",
  title: "Ratios, Rates, Percentages & Proportions",
  intro: "A ratio compares quantities, a rate compares quantities with different units (often a <i>unit rate</i>), a percentage is a ratio out of 100, and a proportion sets two ratios equal. This worksheet practises all four and solving with cross-multiplication.",
  examples: [
    ["Example 1: Simplify a ratio", "Simplify the ratio $12:18$.", "Divide both by the GCF $6$: $12:18 = 2:3$."],
    ["Example 2: Unit rate", "A bag of rice costs $\\$6$ for $3$ kg. Find the unit rate.", "$\\$6 \\div 3\\text{ kg} = \\$2$ per kg."],
    ["Example 3: Percent of a number", "Find $25\\%$ of $80$.", "$25\\% = 0.25$, so $0.25 \\times 80 = 20$."],
    ["Example 4: What percent", "$15$ is what percent of $60$?", "$\\dfrac{15}{60} = 0.25 = 25\\%$."],
    ["Example 5: Solve a proportion", "Solve $\\dfrac{x}{4} = \\dfrac{9}{12}$.", "Cross-multiply: $12x = 36$, so $x = 3$."],
    ["Example 6: Speed (rate)", "A car travels $240$ km in $4$ hours. Find its speed.", "$240 \\div 4 = 60$ km/h."],
    ["Example 7: Percent increase", "Increase $50$ by $20\\%$.", "$20\\%$ of $50$ is $10$, so $50 + 10 = 60$."],
    ["Example 8: Use a ratio", "Two amounts are in the ratio $3:5$. If the first is $12$, find the second.", "$12 \\div 3 = 4$, so the second is $5\\times 4 = 20$."],
    ["Example 9: What percent", "$15$ is what percent of $50$?", "$\\dfrac{15}{50} = 0.30 = 30\\%$."],
  ],
  questions: [
    ["Problem 1: Simplify a ratio", "Simplify $10:15$.", "$2:3$"],
    ["Problem 2: Unit price", "If $3$ items cost $\\$9$, find the price of one item.", "$\\$3$"],
    ["Problem 3: Percent of a number", "Find $30\\%$ of $90$.", "$27$"],
    ["Problem 4: What percent", "$12$ is what percent of $48$?", "$25\\%$"],
    ["Problem 5: Solve a proportion", "Solve $\\dfrac{x}{6} = \\dfrac{10}{15}$.", "$x = 4$"],
    ["Problem 6: Speed", "A train travels $180$ km in $3$ hours. Find its speed.", "$60$ km/h"],
    ["Problem 7: Percent increase", "Increase $40$ by $25\\%$.", "$50$"],
    ["Problem 8: Use a ratio", "Two amounts are in the ratio $2:7$. If the first is $8$, find the second.", "$28$"],
    ["Problem 9: What percent", "$18$ is what percent of $72$?", "$25\\%$"],
    ["Problem 10: Simplify a ratio", "Simplify $24:36$.", "$2:3$"],
    ["Problem 11: Percent of a number", "Find $40\\%$ of $150$.", "$60$"],
    ["Problem 12: Rate per hour", "A cyclist rides $9$ km in $45$ minutes. Find the rate in km/h.", "$12$ km/h"],
    ["Problem 13: Percent decrease", "Decrease $80$ by $15\\%$.", "$68$"],
  ],
};
