export default {
  grade: "MTH1W",
  code: "2.1",
  title: "From Words to Algebraic Expressions",
  intro: "Algebra begins with translation: turning a phrase in words into an expression using a variable. Watch the key words — <i>sum/more than</i> (+), <i>less than/difference</i> (−), <i>product/times/twice</i> (×), and <i>quotient/divided by</i> (÷).",
  examples: [
    ["Example 1: More than", "Write an expression for: $5$ more than a number $x$.", "“More than” means add: $x + 5$."],
    ["Example 2: Less than", "Write an expression for: $7$ less than a number $n$.", "“$7$ less than $n$” means $n - 7$ (the order flips!)."],
    ["Example 3: Twice", "Write an expression for: twice a number $y$.", "“Twice” means multiply by $2$: $2y$."],
    ["Example 4: Divided by", "Write an expression for: a number $x$ divided by $4$.", "$\\dfrac{x}{4}$."],
    ["Example 5: Sum", "Write an expression for: the sum of a number $x$ and $8$.", "$x + 8$."],
    ["Example 6: Two operations", "Write an expression for: $3$ more than twice a number $x$.", "Twice the number is $2x$; $3$ more is $2x + 3$."],
    ["Example 7: Product then subtract", "Write an expression for: the product of $5$ and a number $x$, decreased by $2$.", "$5x - 2$."],
    ["Example 8: Half then add", "Write an expression for: half of a number $x$, increased by $3$.", "$\\dfrac{x}{2} + 3$."],
    ["Example 9: Real context", "A taxi charges $\\$4$ plus $\\$2$ per kilometre. Write an expression for the cost of $d$ km.", "Variable cost $2d$ plus the fixed $\\$4$: $2d + 4$."],
  ],
  questions: [
    ["Problem 1: More than", "Write an expression: $8$ more than a number $x$.", "$x + 8$"],
    ["Problem 2: Less than", "Write an expression: $5$ less than a number $m$.", "$m - 5$"],
    ["Problem 3: Times", "Write an expression: three times a number $n$.", "$3n$"],
    ["Problem 4: Divided by", "Write an expression: a number $x$ divided by $6$.", "$\\dfrac{x}{6}$"],
    ["Problem 5: Sum", "Write an expression: the sum of a number $x$ and $12$.", "$x + 12$"],
    ["Problem 6: Two operations", "Write an expression: $4$ more than twice a number $x$.", "$2x + 4$"],
    ["Problem 7: Product then subtract", "Write an expression: the product of $6$ and a number $x$, decreased by $5$.", "$6x - 5$"],
    ["Problem 8: Half then add", "Write an expression: half of a number $x$, increased by $3$.", "$\\dfrac{x}{2} + 3$"],
    ["Problem 9: Times then add", "Write an expression: $7$ times a number $x$, plus $1$.", "$7x + 1$"],
    ["Problem 10: Difference", "Write an expression: the difference between a number $x$ and $10$.", "$x - 10$"],
    ["Problem 11: Two operations", "Write an expression: $5$ less than three times a number $x$.", "$3x - 5$"],
    ["Problem 12: Real context", "A phone plan costs $\\$30$ plus $\\$0.10$ per text $t$. Write the cost.", "$0.10t + 30$"],
    ["Problem 13: Geometry context", "A rectangle's width is $w$; its length is $5$ more than twice the width. Write the length.", "$2w + 5$"],
  ],
};
