export default {
  grade: "MTH1W",
  code: "2.2",
  title: "Equivalent Expressions",
  intro: "Two expressions are <i>equivalent</i> if they give the same value for every input. The distributive property, $a(b+c)=ab+ac$, lets us expand; common factoring reverses it. This worksheet builds both skills and checks for equivalence.",
  examples: [
    ["Example 1: Distribute", "Expand $3(x + 4)$.", "$3\\cdot x + 3\\cdot 4 = 3x + 12$."],
    ["Example 2: Distribute with subtraction", "Expand $2(x - 5)$.", "$2x - 10$."],
    ["Example 3: Distribute a negative", "Expand $-(x + 7)$.", "$-1(x + 7) = -x - 7$."],
    ["Example 4: Check equivalence", "Are $2(x+3)$ and $2x+6$ equivalent?", "Expand: $2(x+3) = 2x + 6$. Yes — equivalent."],
    ["Example 5: Coefficient inside", "Expand $4(2x + 1)$.", "$8x + 4$."],
    ["Example 6: Variable factor", "Expand $x(x + 3)$.", "$x\\cdot x + x\\cdot 3 = x^2 + 3x$."],
    ["Example 7: Common factoring", "Factor $6x + 9$.", "GCF is $3$: $6x + 9 = 3(2x + 3)$."],
    ["Example 8: Check equivalence", "Are $3x + 6$ and $3(x+3)$ equivalent?", "$3(x+3) = 3x + 9 \\ne 3x + 6$. No — not equivalent."],
    ["Example 9: Distribute a negative coefficient", "Expand $-2(3x - 4)$.", "$-6x + 8$ (the negative flips both signs)."],
  ],
  questions: [
    ["Problem 1: Distribute", "Expand $5(x + 2)$.", "$5x + 10$"],
    ["Problem 2: Distribute", "Expand $3(x - 6)$.", "$3x - 18$"],
    ["Problem 3: Distribute a negative", "Expand $-(2x + 5)$.", "$-2x - 5$"],
    ["Problem 4: Distribute", "Expand $4(3x + 2)$.", "$12x + 8$"],
    ["Problem 5: Distribute", "Expand $2(5x - 3)$.", "$10x - 6$"],
    ["Problem 6: Variable factor", "Expand $x(x + 6)$.", "$x^2 + 6x$"],
    ["Problem 7: Factor", "Factor $8x + 12$.", "$4(2x + 3)$"],
    ["Problem 8: Factor", "Factor $10x - 15$.", "$5(2x - 3)$"],
    ["Problem 9: Equivalent?", "Are $4(x+2)$ and $4x+8$ equivalent?", "Yes"],
    ["Problem 10: Equivalent?", "Are $2(x+5)$ and $2x+5$ equivalent?", "No $\\left(2(x+5)=2x+10\\right)$"],
    ["Problem 11: Distribute negative", "Expand $-3(2x - 1)$.", "$-6x + 3$"],
    ["Problem 12: Distribute", "Expand $6(2x + 3)$.", "$12x + 18$"],
    ["Problem 13: Factor", "Factor $9x + 6$.", "$3(3x + 2)$"],
  ],
};
