export default {
  grade: "MTH1W",
  code: "2.3",
  title: "Simplifying Expressions",
  intro: "To simplify, collect <i>like terms</i> — terms with the same variable and exponent. Combine their coefficients; constants combine separately. When brackets appear, distribute first, then collect like terms.",
  examples: [
    ["Example 1: Like terms", "Simplify $3x + 5x$.", "Add the coefficients: $(3+5)x = 8x$."],
    ["Example 2: Subtract like terms", "Simplify $7x - 2x$.", "$(7-2)x = 5x$."],
    ["Example 3: With a constant", "Simplify $4x + 3 + 2x$.", "Combine $x$-terms: $4x + 2x = 6x$; keep $+3$.<br>$6x + 3$."],
    ["Example 4: Two groups", "Simplify $5x + 2 - 3x + 4$.", "$x$-terms: $5x - 3x = 2x$; constants: $2 + 4 = 6$.<br>$2x + 6$."],
    ["Example 5: Two variables", "Simplify $2x + 3y + 4x - y$.", "$x$: $2x + 4x = 6x$; $y$: $3y - y = 2y$.<br>$6x + 2y$."],
    ["Example 6: Distribute then collect", "Simplify $2(x + 3) + 4x$.", "$2x + 6 + 4x = 6x + 6$."],
    ["Example 7: Distribute then collect", "Simplify $3(x - 2) + 5$.", "$3x - 6 + 5 = 3x - 1$."],
    ["Example 8: Collect", "Simplify $5a - 2 + 3a + 7$.", "$a$: $5a + 3a = 8a$; constants: $-2 + 7 = 5$.<br>$8a + 5$."],
    ["Example 9: Two brackets", "Simplify $4(x + 1) - 2(x - 3)$.", "$4x + 4 - 2x + 6 = 2x + 10$."],
  ],
  questions: [
    ["Problem 1: Like terms", "Simplify $6x + 2x$.", "$8x$"],
    ["Problem 2: Subtract", "Simplify $9x - 4x$.", "$5x$"],
    ["Problem 3: With constant", "Simplify $3x + 5 + 4x$.", "$7x + 5$"],
    ["Problem 4: Two groups", "Simplify $8x + 3 - 2x - 1$.", "$6x + 2$"],
    ["Problem 5: Two variables", "Simplify $5a + 2b + a - 3b$.", "$6a - b$"],
    ["Problem 6: Distribute then collect", "Simplify $3(x + 4) + 2x$.", "$5x + 12$"],
    ["Problem 7: Distribute then collect", "Simplify $4(x - 1) + 6$.", "$4x + 2$"],
    ["Problem 8: Collect", "Simplify $7y - 3 + 2y + 8$.", "$9y + 5$"],
    ["Problem 9: Two brackets", "Simplify $2(x + 5) + 3(x - 2)$.", "$5x + 4$"],
    ["Problem 10: Two variables", "Simplify $5x + 3y - 2x + y$.", "$3x + 4y$"],
    ["Problem 11: Distribute then collect", "Simplify $6(2x - 1) - 4x$.", "$8x - 6$"],
    ["Problem 12: Distribute a negative", "Simplify $10 - 3(x - 2)$.", "$16 - 3x$"],
    ["Problem 13: Squared terms", "Simplify $2a + 3a^2 - a + a^2$.", "$4a^2 + a$"],
  ],
};
