export default {
  grade: "MTH1W",
  code: "2.4",
  title: "Creating & Solving Equations",
  intro: "An equation states that two expressions are equal. Solve by using inverse operations to isolate the variable, doing the same thing to both sides. Always verify by substituting your answer back in.",
  examples: [
    ["Example 1: One step (add/subtract)", "Solve and verify: $x + 6 = 14$.", "$x = 14 - 6 = 8$.<br><b>Verify:</b> $8 + 6 = 14$ ✓"],
    ["Example 2: One step (multiply/divide)", "Solve and verify: $3x = 21$.", "$x = \\dfrac{21}{3} = 7$.<br><b>Verify:</b> $3\\times 7 = 21$ ✓"],
    ["Example 3: Two steps", "Solve and verify: $2x + 5 = 17$.", "$2x = 17 - 5 = 12$, so $x = 6$.<br><b>Verify:</b> $2(6)+5 = 17$ ✓"],
    ["Example 4: Two steps with a fraction", "Solve and verify: $\\dfrac{x}{4} - 1 = 2$.", "$\\dfrac{x}{4} = 3$, so $x = 12$.<br><b>Verify:</b> $\\dfrac{12}{4} - 1 = 2$ ✓"],
    ["Example 5: Variables on both sides", "Solve and verify: $5x - 3 = 2x + 9$.", "$5x - 2x = 9 + 3$, so $3x = 12$, $x = 4$.<br><b>Verify:</b> $5(4)-3 = 17 = 2(4)+9$ ✓"],
    ["Example 6: Build an equation", "A number tripled, plus $4$, is $19$. Find the number.", "$3x + 4 = 19 \\Rightarrow 3x = 15 \\Rightarrow x = 5$.<br><b>Verify:</b> $3(5)+4 = 19$ ✓"],
    ["Example 7: Bracket", "Solve and verify: $4(x - 2) = 12$.", "$x - 2 = 3$, so $x = 5$.<br><b>Verify:</b> $4(5-2) = 12$ ✓"],
    ["Example 8: Geometry equation", "A square has perimeter $28$ cm. Find the side length.", "$4s = 28 \\Rightarrow s = 7$.<br><b>Verify:</b> $4\\times 7 = 28$ ✓"],
    ["Example 9: Brackets, both sides", "Solve and verify: $2(x + 3) = x + 10$.", "$2x + 6 = x + 10 \\Rightarrow x = 4$.<br><b>Verify:</b> $2(4+3) = 14 = 4 + 10$ ✓"],
  ],
  questions: [
    ["Problem 1: One step", "Solve and verify: $x + 9 = 15$.", "$x = 6$"],
    ["Problem 2: One step", "Solve and verify: $4x = 32$.", "$x = 8$"],
    ["Problem 3: Two steps", "Solve and verify: $3x + 2 = 20$.", "$x = 6$"],
    ["Problem 4: Two steps (fraction)", "Solve and verify: $\\dfrac{x}{5} + 2 = 6$.", "$x = 20$"],
    ["Problem 5: Two steps", "Solve and verify: $5x - 4 = 16$.", "$x = 4$"],
    ["Problem 6: Both sides", "Solve and verify: $2x + 7 = x + 12$.", "$x = 5$"],
    ["Problem 7: Bracket", "Solve and verify: $3(x - 1) = 12$.", "$x = 5$"],
    ["Problem 8: Both sides", "Solve and verify: $6x - 5 = 2x + 11$.", "$x = 4$"],
    ["Problem 9: Build an equation", "A number doubled, minus $3$, is $11$. Find the number.", "$x = 7$ &nbsp;($2(7)-3=11$)"],
    ["Problem 10: Bracket", "Solve and verify: $4(x + 2) = 20$.", "$x = 3$"],
    ["Problem 11: Two steps (fraction)", "Solve and verify: $\\dfrac{x}{3} - 4 = 1$.", "$x = 15$"],
    ["Problem 12: Geometry", "A square has perimeter $36$ cm. Find the side length.", "$s = 9$ cm"],
    ["Problem 13: Both sides, brackets", "Solve and verify: $5(x - 2) = 3x + 4$.", "$x = 7$"],
  ],
};
