export default {
  grade: "MTH1W",
  code: "3.1",
  title: "Coding Algebraic Concepts",
  intro: "Algebra and code share the same ideas: a <i>variable</i> stores a value, the assignment arrow <code>←</code> puts a value into a variable, and <code>OUTPUT</code> reports a result. This worksheet practises tracing short programs by hand to find what they print.",
  examples: [
    ["Example 1: Assignment & output", "Trace and give the output:<div class='code'>x ← 5<br>y ← x + 3<br>OUTPUT y</div>", "$x$ holds $5$, so $y = 5 + 3 = 8$.<br><b>Output: 8</b>"],
    ["Example 2: Updating a variable", "Trace:<div class='code'>x ← 10<br>x ← x + 4<br>OUTPUT x</div>", "$x$ becomes $10 + 4 = 14$.<br><b>Output: 14</b>"],
    ["Example 3: Multiplying variables", "Trace:<div class='code'>a ← 6<br>b ← 2<br>OUTPUT a * b</div>", "$6 \\times 2 = 12$.<br><b>Output: 12</b>"],
    ["Example 4: An expression", "Trace:<div class='code'>x ← 7<br>y ← 2 * x − 1<br>OUTPUT y</div>", "$y = 2(7) - 1 = 13$.<br><b>Output: 13</b>"],
    ["Example 5: Squaring", "Trace:<div class='code'>p ← 3<br>q ← p * p<br>OUTPUT q</div>", "$q = 3\\times 3 = 9$.<br><b>Output: 9</b>"],
    ["Example 6: With input", "Trace with input $n = 4$:<div class='code'>INPUT n<br>m ← n / 2 + 5<br>OUTPUT m</div>", "$m = 4/2 + 5 = 2 + 5 = 7$.<br><b>Output: 7</b>"],
    ["Example 7: Swapping with a temp", "Trace:<div class='code'>x ← 8<br>y ← 3<br>t ← x<br>x ← y<br>y ← t<br>OUTPUT x, y</div>", "The temp $t$ holds the old $x$; after swapping, $x = 3$, $y = 8$.<br><b>Output: 3, 8</b>"],
    ["Example 8: Two updates", "Trace:<div class='code'>a ← 2<br>b ← 5<br>c ← a + b<br>c ← c * 2<br>OUTPUT c</div>", "$c = 7$, then $c = 7 \\times 2 = 14$.<br><b>Output: 14</b>"],
    ["Example 9: Accumulating", "Trace:<div class='code'>cost ← 0<br>cost ← cost + 12<br>cost ← cost + 8<br>OUTPUT cost</div>", "$0 \\to 12 \\to 20$.<br><b>Output: 20</b>"],
  ],
  questions: [
    ["Problem 1", "Trace:<div class='code'>x ← 4<br>y ← x + 9<br>OUTPUT y</div>", "13"],
    ["Problem 2", "Trace:<div class='code'>x ← 20<br>x ← x − 7<br>OUTPUT x</div>", "13"],
    ["Problem 3", "Trace:<div class='code'>a ← 5<br>b ← 3<br>OUTPUT a * b</div>", "15"],
    ["Problem 4", "Trace:<div class='code'>x ← 6<br>y ← 2 * x + 1<br>OUTPUT y</div>", "13"],
    ["Problem 5", "Trace:<div class='code'>p ← 4<br>q ← p * p<br>OUTPUT q</div>", "16"],
    ["Problem 6", "Trace with input $n = 10$:<div class='code'>INPUT n<br>m ← n / 2 + 3<br>OUTPUT m</div>", "8"],
    ["Problem 7", "Trace:<div class='code'>x ← 9<br>y ← 1<br>t ← x<br>x ← y<br>y ← t<br>OUTPUT x, y</div>", "1, 9"],
    ["Problem 8", "Trace:<div class='code'>a ← 3<br>b ← 4<br>c ← a + b<br>c ← c * 3<br>OUTPUT c</div>", "21"],
    ["Problem 9", "Trace:<div class='code'>total ← 0<br>total ← total + 15<br>total ← total + 5<br>OUTPUT total</div>", "20"],
    ["Problem 10", "Trace:<div class='code'>x ← 2<br>x ← x * x<br>x ← x * x<br>OUTPUT x</div>", "16"],
    ["Problem 11", "Trace:<div class='code'>a ← 12<br>b ← 4<br>OUTPUT a / b</div>", "3"],
    ["Problem 12", "Trace:<div class='code'>n ← 7<br>r ← n * 2 − 4<br>OUTPUT r</div>", "10"],
    ["Problem 13", "Trace:<div class='code'>x ← 5<br>y ← x + 2<br>z ← y + x<br>OUTPUT z</div>", "12"],
  ],
};
