export default {
  grade: "MTH1W",
  code: "3.2",
  title: "Building Code from Steps",
  intro: "This worksheet turns a description into pseudocode and traces programs that use <code>FOR</code> loops (repeat a number of times) and <code>IF … THEN … ELSE</code> decisions. <code>MOD</code> gives the remainder after division.",
  examples: [
    ["Example 1: Write code", "Write pseudocode: ask for a number and output double it.", "<div class='code'>INPUT n<br>d ← n * 2<br>OUTPUT d</div>"],
    ["Example 2: Write code", "Write pseudocode: output the sum of two inputs $a$ and $b$.", "<div class='code'>INPUT a<br>INPUT b<br>s ← a + b<br>OUTPUT s</div>"],
    ["Example 3: Trace a loop", "Trace:<div class='code'>s ← 0<br>FOR i FROM 1 TO 3<br>&nbsp;&nbsp;s ← s + i<br>OUTPUT s</div>", "$s$ adds $1, 2, 3$: $0\\to1\\to3\\to6$.<br><b>Output: 6</b>"],
    ["Example 4: Doubling loop", "Trace:<div class='code'>x ← 1<br>FOR i FROM 1 TO 4<br>&nbsp;&nbsp;x ← x * 2<br>OUTPUT x</div>", "$1\\to2\\to4\\to8\\to16$.<br><b>Output: 16</b>"],
    ["Example 5: A decision", "Trace:<div class='code'>n ← 7<br>IF n > 5 THEN OUTPUT \"big\" ELSE OUTPUT \"small\"</div>", "$7 > 5$ is true.<br><b>Output: big</b>"],
    ["Example 6: Even or odd", "Trace:<div class='code'>n ← 3<br>IF n MOD 2 = 0 THEN OUTPUT \"even\" ELSE OUTPUT \"odd\"</div>", "$3 \\bmod 2 = 1 \\ne 0$.<br><b>Output: odd</b>"],
    ["Example 7: Counting by 2s", "Trace:<div class='code'>c ← 0<br>FOR i FROM 1 TO 5<br>&nbsp;&nbsp;c ← c + 2<br>OUTPUT c</div>", "Adds $2$ five times: $c = 10$.<br><b>Output: 10</b>"],
    ["Example 8: Sum 1 to 5", "Trace:<div class='code'>s ← 0<br>FOR i FROM 1 TO 5<br>&nbsp;&nbsp;s ← s + i<br>OUTPUT s</div>", "$1+2+3+4+5 = 15$.<br><b>Output: 15</b>"],
    ["Example 9: Write code", "Write pseudocode: compute the area of a rectangle from inputs $L$ and $W$.", "<div class='code'>INPUT L<br>INPUT W<br>A ← L * W<br>OUTPUT A</div>"],
  ],
  questions: [
    ["Problem 1: Write code", "Write pseudocode: input a number and output it plus $10$.", "<div class='code'>INPUT n<br>r ← n + 10<br>OUTPUT r</div>"],
    ["Problem 2: Write code", "Write pseudocode: output the product of inputs $a$ and $b$.", "<div class='code'>INPUT a<br>INPUT b<br>p ← a * b<br>OUTPUT p</div>"],
    ["Problem 3: Trace", "Trace:<div class='code'>s ← 0<br>FOR i FROM 1 TO 4<br>&nbsp;&nbsp;s ← s + i<br>OUTPUT s</div>", "10"],
    ["Problem 4: Trace", "Trace:<div class='code'>x ← 1<br>FOR i FROM 1 TO 3<br>&nbsp;&nbsp;x ← x * 3<br>OUTPUT x</div>", "27"],
    ["Problem 5: Decision", "Trace:<div class='code'>n ← 10<br>IF n > 5 THEN OUTPUT \"big\" ELSE OUTPUT \"small\"</div>", "big"],
    ["Problem 6: Even/odd", "Trace:<div class='code'>n ← 8<br>IF n MOD 2 = 0 THEN OUTPUT \"even\" ELSE OUTPUT \"odd\"</div>", "even"],
    ["Problem 7: Counting", "Trace:<div class='code'>c ← 0<br>FOR i FROM 1 TO 6<br>&nbsp;&nbsp;c ← c + 5<br>OUTPUT c</div>", "30"],
    ["Problem 8: Sum", "Trace:<div class='code'>s ← 0<br>FOR i FROM 1 TO 6<br>&nbsp;&nbsp;s ← s + i<br>OUTPUT s</div>", "21"],
    ["Problem 9: Write code", "Write pseudocode: perimeter of a square from input $s$.", "<div class='code'>INPUT s<br>P ← 4 * s<br>OUTPUT P</div>"],
    ["Problem 10: Trace", "Trace:<div class='code'>p ← 1<br>FOR i FROM 1 TO 4<br>&nbsp;&nbsp;p ← p * 2<br>OUTPUT p</div>", "16"],
    ["Problem 11: Decision", "Trace:<div class='code'>n ← 4<br>IF n > 10 THEN OUTPUT \"yes\" ELSE OUTPUT \"no\"</div>", "no"],
    ["Problem 12: Counting down", "Trace:<div class='code'>k ← 10<br>FOR i FROM 1 TO 3<br>&nbsp;&nbsp;k ← k − 2<br>OUTPUT k</div>", "4"],
    ["Problem 13: Write code", "Write pseudocode: the average of two inputs $a$ and $b$.", "<div class='code'>INPUT a<br>INPUT b<br>avg ← (a + b) / 2<br>OUTPUT avg</div>"],
  ],
};
