export default {
  grade: "MTH1W",
  code: "3.3",
  title: "Reading, Predicting & Altering Code",
  intro: "Skilled coders read a program and predict its output before running it, then alter it to change behaviour. This worksheet practises careful tracing of loops and conditionals — track each variable line by line.",
  examples: [
    ["Example 1: Expression trace", "Predict the output:<div class='code'>x ← 2<br>y ← 3<br>z ← x * y + x<br>OUTPUT z</div>", "$z = 2(3) + 2 = 8$.<br><b>Output: 8</b>"],
    ["Example 2: Sum of squares", "Predict:<div class='code'>s ← 0<br>FOR i FROM 1 TO 4<br>&nbsp;&nbsp;s ← s + i * i<br>OUTPUT s</div>", "$1 + 4 + 9 + 16 = 30$.<br><b>Output: 30</b>"],
    ["Example 3: IF inside a loop", "Predict:<div class='code'>c ← 0<br>FOR i FROM 1 TO 5<br>&nbsp;&nbsp;IF i MOD 2 = 0 THEN c ← c + 1<br>OUTPUT c</div>", "Even $i$ are $2, 4$ ⇒ $c = 2$.<br><b>Output: 2</b>"],
    ["Example 4: Factorial", "Predict:<div class='code'>n ← 5<br>r ← 1<br>FOR i FROM 1 TO n<br>&nbsp;&nbsp;r ← r * i<br>OUTPUT r</div>", "$1\\cdot2\\cdot3\\cdot4\\cdot5 = 120$.<br><b>Output: 120</b>"],
    ["Example 5: Repeated add", "Predict:<div class='code'>total ← 0<br>FOR i FROM 1 TO 4<br>&nbsp;&nbsp;total ← total + 3<br>OUTPUT total</div>", "Adds $3$ four times ⇒ $12$.<br><b>Output: 12</b>"],
    ["Example 6: Nested decisions", "Predict:<div class='code'>x ← 10<br>IF x > 5 THEN x ← x − 2<br>IF x > 7 THEN OUTPUT \"A\" ELSE OUTPUT \"B\"</div>", "$x$ becomes $8$; $8 > 7$ ⇒ A.<br><b>Output: A</b>"],
    ["Example 7: Sum of a range", "Predict:<div class='code'>sum ← 0<br>FOR i FROM 2 TO 6<br>&nbsp;&nbsp;sum ← sum + i<br>OUTPUT sum</div>", "$2+3+4+5+6 = 20$.<br><b>Output: 20</b>"],
    ["Example 8: Fibonacci-style", "Predict:<div class='code'>a ← 1<br>b ← 1<br>FOR i FROM 1 TO 3<br>&nbsp;&nbsp;t ← a + b<br>&nbsp;&nbsp;a ← b<br>&nbsp;&nbsp;b ← t<br>OUTPUT b</div>", "$b: 1\\to2\\to3\\to5$.<br><b>Output: 5</b>"],
    ["Example 9: Alter the code", "The program below outputs the sum $1$ to $3$. What does it output if you change <code>TO 3</code> to <code>TO 5</code>?<div class='code'>s ← 0<br>FOR i FROM 1 TO 3<br>&nbsp;&nbsp;s ← s + i<br>OUTPUT s</div>", "Now it sums $1$ to $5$: $15$.<br><b>Output: 15</b>"],
  ],
  questions: [
    ["Problem 1", "Predict:<div class='code'>x ← 4<br>y ← 2<br>z ← x * y + y<br>OUTPUT z</div>", "10"],
    ["Problem 2", "Predict:<div class='code'>s ← 0<br>FOR i FROM 1 TO 3<br>&nbsp;&nbsp;s ← s + i * i<br>OUTPUT s</div>", "14"],
    ["Problem 3", "Predict:<div class='code'>c ← 0<br>FOR i FROM 1 TO 6<br>&nbsp;&nbsp;IF i MOD 2 = 0 THEN c ← c + 1<br>OUTPUT c</div>", "3"],
    ["Problem 4", "Predict:<div class='code'>n ← 4<br>r ← 1<br>FOR i FROM 1 TO n<br>&nbsp;&nbsp;r ← r * i<br>OUTPUT r</div>", "24"],
    ["Problem 5", "Predict:<div class='code'>total ← 0<br>FOR i FROM 1 TO 5<br>&nbsp;&nbsp;total ← total + 4<br>OUTPUT total</div>", "20"],
    ["Problem 6", "Predict:<div class='code'>x ← 9<br>IF x > 5 THEN x ← x + 1<br>IF x > 9 THEN OUTPUT \"A\" ELSE OUTPUT \"B\"</div>", "A"],
    ["Problem 7", "Predict:<div class='code'>sum ← 0<br>FOR i FROM 3 TO 7<br>&nbsp;&nbsp;sum ← sum + i<br>OUTPUT sum</div>", "25"],
    ["Problem 8", "Predict:<div class='code'>a ← 2<br>b ← 3<br>t ← a<br>a ← b<br>b ← t<br>OUTPUT a, b</div>", "3, 2"],
    ["Problem 9", "Predict:<div class='code'>count ← 0<br>FOR i FROM 1 TO 10<br>&nbsp;&nbsp;IF i MOD 5 = 0 THEN count ← count + 1<br>OUTPUT count</div>", "2"],
    ["Problem 10", "Predict:<div class='code'>p ← 1<br>FOR i FROM 1 TO 5<br>&nbsp;&nbsp;p ← p * 2<br>OUTPUT p</div>", "32"],
    ["Problem 11", "Predict:<div class='code'>x ← 20<br>FOR i FROM 1 TO 4<br>&nbsp;&nbsp;x ← x − 3<br>OUTPUT x</div>", "8"],
    ["Problem 12", "Predict:<div class='code'>s ← 0<br>FOR i FROM 1 TO 4<br>&nbsp;&nbsp;s ← s + 2 * i<br>OUTPUT s</div>", "20"],
    ["Problem 13", "The code sums $1$ to $n$. What is the output when $n = 10$?<div class='code'>s ← 0<br>FOR i FROM 1 TO n<br>&nbsp;&nbsp;s ← s + i<br>OUTPUT s</div>", "55"],
  ],
};
