export default {
  grade: "MTH1W",
  code: "4.1",
  title: "Linear vs Non-Linear Relations",
  intro: "A relation is <i>linear</i> if it has a constant rate of change — its graph is a straight line and its equation has degree $1$ (like $y = mx + b$). In a table, a linear relation has constant <i>first differences</i>. Anything with $x^2$, $\\sqrt{x}$, $\\frac{1}{x}$, etc. is non-linear.",
  examples: [
    ["Example 1: From an equation", "Is $y = 3x + 2$ linear?", "It has degree $1$ (no powers of $x$), so <b>yes — linear</b>."],
    ["Example 2: A squared term", "Is $y = x^2$ linear?", "The $x^2$ makes it <b>non-linear</b>."],
    ["Example 3: From a table", "Is this linear?  $x: 1,2,3$ → $y: 5,8,11$.", "First differences: $8-5=3$, $11-8=3$ — constant. <b>Yes — linear</b> (rate $3$)."],
    ["Example 4: Table, not linear", "Is this linear?  $x: 1,2,3$ → $y: 1,4,9$.", "Differences: $4-1=3$, $9-4=5$ — not constant. <b>No — non-linear</b>."],
    ["Example 5: A constant", "Is $y = 5$ linear?", "It is a horizontal line (constant rate $0$). <b>Yes — linear</b>."],
    ["Example 6: A reciprocal", "Is $y = \\dfrac{2}{x}$ linear?", "$x$ is in the denominator. <b>No — non-linear</b>."],
    ["Example 7: Rate of change", "What is the rate of change of $y = 4x - 1$?", "The coefficient of $x$: rate $= 4$ (constant ⇒ linear)."],
    ["Example 8: Table", "Is this linear?  $x: 0,1,2,3$ → $y: 2,5,8,11$.", "First differences all $3$. <b>Yes — linear</b>, rate $3$."],
    ["Example 9: A cube", "Is $y = x^3$ linear?", "The $x^3$ makes it <b>non-linear</b>."],
  ],
  questions: [
    ["Problem 1", "Is $y = 2x - 7$ linear?", "Yes"],
    ["Problem 2", "Is $y = x^2 + 1$ linear?", "No"],
    ["Problem 3", "Is this linear? $x:1,2,3 \\to y:4,7,10$.", "Yes (first difference $3$)"],
    ["Problem 4", "Is this linear? $x:1,2,3 \\to y:2,6,12$.", "No (differences $4, 6$)"],
    ["Problem 5", "Is $y = -3$ linear?", "Yes (horizontal)"],
    ["Problem 6", "Is $y = \\sqrt{x}$ linear?", "No"],
    ["Problem 7", "Are the $y$-values $3, 7, 11, 15$ linear?", "Yes (constant difference $4$)"],
    ["Problem 8", "Is $y = 10 - 2x$ linear?", "Yes"],
    ["Problem 9", "Is this linear? $x:0,1,2 \\to y:1,2,4$.", "No (differences $1, 2$)"],
    ["Problem 10", "Is $3x + 2y = 6$ linear?", "Yes"],
    ["Problem 11", "Is $y = \\dfrac{1}{x+1}$ linear?", "No"],
    ["Problem 12", "What is the rate of change of $y = 6x + 5$?", "$6$"],
    ["Problem 13", "Is this linear? $x:2,4,6 \\to y:5,9,13$.", "Yes (constant rate)"],
  ],
};
