export default {
  grade: "MTH1W",
  code: "4.2",
  title: "Representing Linear Relations",
  intro: "A linear relation can be shown four ways: in <i>words</i>, as a <i>table</i>, as an <i>equation</i> $y = mx + b$, and as a <i>graph</i>. Here $m$ is the slope (rate of change) and $b$ is the $y$-intercept (value when $x = 0$). This worksheet moves between these representations.",
  examples: [
    ["Example 1: Evaluate", "For $y = 2x + 3$, find $y$ when $x = 4$.", "$y = 2(4) + 3 = 11$."],
    ["Example 2: Build a table", "Make a table for $y = x + 5$ at $x = 0, 1, 2$.", "$y = 5, 6, 7$."],
    ["Example 3: Table to equation", "Find the equation: $x: 0,1,2 \\to y: 4,6,8$.", "Slope $= 2$, $y$-intercept $= 4$: $y = 2x + 4$."],
    ["Example 4: y-intercept", "What is the $y$-intercept of $y = 3x - 7$?", "$b = -7$ (the constant term)."],
    ["Example 5: Slope", "What is the slope of $y = -2x + 1$?", "$m = -2$."],
    ["Example 6: Words to equation", "Write the equation: start at $10$ and increase by $5$ each step.", "$y = 5x + 10$."],
    ["Example 7: Solve for x", "For $y = 4x$, find $x$ when $y = 20$.", "$20 = 4x \\Rightarrow x = 5$."],
    ["Example 8: Table to equation", "Find the equation: $x: 1,2,3 \\to y: 7,10,13$.", "Slope $= 3$; at $x = 1$, $y = 7 \\Rightarrow b = 4$: $y = 3x + 4$."],
    ["Example 9: Point on a line", "Find $y$ on $y = 3x - 1$ when $x = 2$.", "$y = 3(2) - 1 = 5$."],
  ],
  questions: [
    ["Problem 1", "For $y = 2x + 1$, find $y$ when $x = 5$.", "$11$"],
    ["Problem 2", "For $y = x - 4$, find $y$ when $x = 10$.", "$6$"],
    ["Problem 3", "Find the equation: $x:0,1,2 \\to y:3,7,11$.", "$y = 4x + 3$"],
    ["Problem 4", "What is the $y$-intercept of $y = 5x + 2$?", "$2$"],
    ["Problem 5", "What is the slope of $y = -4x + 9$?", "$-4$"],
    ["Problem 6", "Write the equation: start at $6$ and go up by $3$ each step.", "$y = 3x + 6$"],
    ["Problem 7", "For $y = 2x + 5$, find $x$ when $y = 15$.", "$x = 5$"],
    ["Problem 8", "Find the equation: $x:1,2,3 \\to y:5,8,11$.", "$y = 3x + 2$"],
    ["Problem 9", "Find $y$ on $y = 2x - 3$ when $x = 4$.", "$5$"],
    ["Problem 10", "For $y = -x + 8$, find $y$ when $x = 3$.", "$5$"],
    ["Problem 11", "What is the slope of $y = 7x$?", "$7$"],
    ["Problem 12", "What is the $y$-intercept of $y = -2x - 6$?", "$-6$"],
    ["Problem 13", "Find the equation: $x:0,2,4 \\to y:1,5,9$.", "$y = 2x + 1$"],
  ],
};
