export default {
  grade: "MTH1W",
  code: "4.3",
  title: "Comparing Lines",
  intro: "Two lines are compared by their <i>slope</i> (steepness — the bigger the absolute value, the steeper) and their <i>$y$-intercept</i> (where they cross the $y$-axis). Lines with equal slopes are parallel; identical equations (even after simplifying) are the same line.",
  examples: [
    ["Example 1: Steeper slope", "Which is steeper, $y = 2x$ or $y = 5x$?", "$5 > 2$, so $y = 5x$ is steeper."],
    ["Example 2: Steepness uses size", "Which is steeper, $y = 3x + 1$ or $y = -4x$?", "Compare $|3|$ and $|-4|$: $4 > 3$, so $y = -4x$ is steeper."],
    ["Example 3: Higher intercept", "Which has the higher $y$-intercept, $y = 2x + 3$ or $y = 2x + 7$?", "$7 > 3$, so $y = 2x + 7$."],
    ["Example 4: Parallel?", "Are $y = 3x + 1$ and $y = 3x - 2$ parallel?", "Same slope $3$ ⇒ <b>yes, parallel</b>."],
    ["Example 5: Same line?", "Are $y = 2x + 4$ and $2y = 4x + 8$ the same line?", "Divide the second by $2$: $y = 2x + 4$. <b>Yes — same line</b>."],
    ["Example 6: Rises faster", "Which rises faster, slope $\\tfrac{1}{2}$ or slope $3$?", "$3 > \\tfrac{1}{2}$, so slope $3$."],
    ["Example 7: Compare intercepts", "Which has the higher $y$-intercept, $y = x - 5$ or $y = x + 2$?", "$2 > -5$, so $y = x + 2$."],
    ["Example 8: Identical", "Are $y = 4x + 1$ and $y = 4x + 1$ the same line?", "Identical equations ⇒ <b>yes</b>."],
    ["Example 9: Steeper (negative)", "Which is steeper, slope $-2$ or slope $1$?", "$|-2| = 2 > 1$, so slope $-2$."],
  ],
  questions: [
    ["Problem 1", "Which is steeper, $y = x$ or $y = 6x$?", "$y = 6x$"],
    ["Problem 2", "Which is steeper, $y = 2x$ or $y = -3x$?", "$y = -3x$"],
    ["Problem 3", "Higher $y$-intercept: $y = x + 1$ or $y = x + 9$?", "$y = x + 9$"],
    ["Problem 4", "Are $y = 5x + 2$ and $y = 5x - 7$ parallel?", "Yes"],
    ["Problem 5", "Same line? $y = 3x + 2$ and $2y = 6x + 4$.", "Yes"],
    ["Problem 6", "Which rises faster, slope $\\tfrac{1}{3}$ or slope $2$?", "Slope $2$"],
    ["Problem 7", "Lower $y$-intercept: $y = x - 8$ or $y = x - 2$?", "$y = x - 8$"],
    ["Problem 8", "Which is steeper, slope $-5$ or slope $4$?", "Slope $-5$"],
    ["Problem 9", "Are $y = 2x + 1$ and $y = 3x + 1$ parallel?", "No"],
    ["Problem 10", "Higher $y$-intercept: $y = -x + 5$ or $y = -x + 1$?", "$y = -x + 5$"],
    ["Problem 11", "Which is steeper, $y = 0.5x$ or $y = 0.9x$?", "$y = 0.9x$"],
    ["Problem 12", "Do $y = 4x - 1$ and $y = 4x + 6$ have the same slope?", "Yes"],
    ["Problem 13", "Which passes through the origin, $y = 2x + 3$ or $y = 2x$?", "$y = 2x$"],
  ],
};
