export default {
  grade: "MTH1W",
  code: "4.4",
  title: "Graphing Special Lines",
  intro: "Some lines are special: a <i>horizontal</i> line $y = b$ has slope $0$; a <i>vertical</i> line $x = a$ has an undefined slope; and $y = x$ is the diagonal through the origin with slope $1$. This worksheet identifies and writes these lines.",
  examples: [
    ["Example 1: Horizontal slope", "What is the slope of $y = 5$?", "A horizontal line has slope $0$."],
    ["Example 2: Vertical slope", "What is the slope of $x = 3$?", "A vertical line has an <b>undefined</b> slope."],
    ["Example 3: The line y = x", "On $y = x$, find $y$ when $x = 4$.", "$y = x = 4$."],
    ["Example 4: Write a horizontal line", "Write the horizontal line through $(2, 7)$.", "Only the $y$-value matters: $y = 7$."],
    ["Example 5: Write a vertical line", "Write the vertical line through $(4, 1)$.", "Only the $x$-value matters: $x = 4$."],
    ["Example 6: Identify", "Is $y = -2$ horizontal or vertical?", "$y = $ constant ⇒ <b>horizontal</b>."],
    ["Example 7: Point on a vertical line", "Give a point on $x = 5$.", "Any point with $x = 5$, e.g. $(5, 3)$."],
    ["Example 8: y = x negative", "On $y = x$, find $y$ when $x = -3$.", "$y = -3$."],
    ["Example 9: Horizontal through origin level", "Write the horizontal line through $(0, -4)$.", "$y = -4$."],
  ],
  questions: [
    ["Problem 1", "What is the slope of $y = 8$?", "$0$"],
    ["Problem 2", "What is the slope of $x = -2$?", "Undefined"],
    ["Problem 3", "On $y = x$, find $y$ when $x = 6$.", "$6$"],
    ["Problem 4", "Write the horizontal line through $(3, 9)$.", "$y = 9$"],
    ["Problem 5", "Write the vertical line through $(5, 2)$.", "$x = 5$"],
    ["Problem 6", "Is $x = 7$ horizontal or vertical?", "Vertical"],
    ["Problem 7", "On $y = x$, find $y$ when $x = -5$.", "$-5$"],
    ["Problem 8", "Write the horizontal line through $(0, 3)$.", "$y = 3$"],
    ["Problem 9", "Write the vertical line through $(-1, 4)$.", "$x = -1$"],
    ["Problem 10", "What is the slope of $y = 0$?", "$0$"],
    ["Problem 11", "Write the equation of the $x$-axis.", "$y = 0$"],
    ["Problem 12", "Write the equation of the $y$-axis.", "$x = 0$"],
    ["Problem 13", "Write the horizontal line through $(6, -2)$.", "$y = -2$"],
  ],
};
