export default {
  grade: "MTH1W",
  code: "4.5",
  title: "Transformations of Lines",
  intro: "Changing $b$ in $y = mx + b$ <i>translates</i> the line up or down; changing $m$ tilts it (steeper, flatter, or reflected). This worksheet practises shifting lines vertically, changing their slope, and reflecting them in the $x$-axis (which flips the sign of the slope).",
  examples: [
    ["Example 1: Shift up", "Translate $y = 2x$ up $3$ units.", "Add $3$ to the constant: $y = 2x + 3$."],
    ["Example 2: Shift down", "Translate $y = x$ down $5$ units.", "$y = x - 5$."],
    ["Example 3: Make steeper", "Change $y = 3x$ to have slope $5$.", "$y = 5x$."],
    ["Example 4: Shift up", "Translate $y = 2x + 1$ up $4$ units.", "$y = 2x + 5$."],
    ["Example 5: Reflect in x-axis", "Reflect $y = 2x$ in the $x$-axis.", "Flip the slope's sign: $y = -2x$."],
    ["Example 6: Shift down", "Translate $y = x + 2$ down $6$ units.", "$y = x - 4$."],
    ["Example 7: Flatten", "Change $y = 4x$ to have slope $1$.", "$y = x$."],
    ["Example 8: Shift up", "Translate $y = -x + 3$ up $2$ units.", "$y = -x + 5$."],
    ["Example 9: Down to the origin", "Translate $y = 2x + 3$ down $3$ units.", "$y = 2x$ (now through the origin)."],
  ],
  questions: [
    ["Problem 1", "Translate $y = 3x$ up $2$ units.", "$y = 3x + 2$"],
    ["Problem 2", "Translate $y = x$ down $7$ units.", "$y = x - 7$"],
    ["Problem 3", "Change $y = 2x$ to have slope $6$.", "$y = 6x$"],
    ["Problem 4", "Translate $y = x + 5$ up $3$ units.", "$y = x + 8$"],
    ["Problem 5", "Reflect $y = 4x$ in the $x$-axis.", "$y = -4x$"],
    ["Problem 6", "Translate $y = 2x - 1$ down $4$ units.", "$y = 2x - 5$"],
    ["Problem 7", "Translate $y = -2x + 1$ up $5$ units.", "$y = -2x + 6$"],
    ["Problem 8", "Change $y = 5x$ to have slope $2$.", "$y = 2x$"],
    ["Problem 9", "Translate $y = x - 3$ up $3$ units.", "$y = x$"],
    ["Problem 10", "Reflect $y = -3x$ in the $x$-axis.", "$y = 3x$"],
    ["Problem 11", "Translate $y = 2x + 4$ down $4$ units.", "$y = 2x$"],
    ["Problem 12", "Translate $y = x + 1$ up $9$ units.", "$y = x + 10$"],
    ["Problem 13", "Change $y = 6x + 2$ to have slope $-6$, keeping the same $y$-intercept.", "$y = -6x + 2$"],
  ],
};
