export default {
  grade: "MTH1W",
  code: "4.6",
  title: "Finding the Equation of a Line",
  intro: "To find a line's equation $y = mx + b$: first find the slope $m = \\dfrac{y_2 - y_1}{x_2 - x_1}$, then substitute a known point to solve for $b$. Two points with the same $x$ give a vertical line ($x =$ constant).",
  examples: [
    ["Example 1: Slope from two points", "Find the slope through $(1,2)$ and $(3,8)$.", "$m = \\dfrac{8-2}{3-1} = \\dfrac{6}{2} = 3$."],
    ["Example 2: Slope from two points", "Find the slope through $(0,5)$ and $(2,9)$.", "$m = \\dfrac{9-5}{2-0} = 2$."],
    ["Example 3: From slope and intercept", "Write the line with slope $2$ and $y$-intercept $3$.", "$y = 2x + 3$."],
    ["Example 4: From intercept and slope", "Write the line through $(0,4)$ with slope $-1$.", "$b = 4$: $y = -x + 4$."],
    ["Example 5: Point and slope", "Write the line through $(1,5)$ with slope $2$.", "$5 = 2(1) + b \\Rightarrow b = 3$: $y = 2x + 3$."],
    ["Example 6: Vertical line", "Find the slope through $(2,3)$ and $(2,7)$.", "Same $x$ ⇒ slope <b>undefined</b>; the line is $x = 2$."],
    ["Example 7: Through the origin", "Write the line through $(0,0)$ with slope $4$.", "$y = 4x$."],
    ["Example 8: Two points", "Write the line through $(1,2)$ and $(4,11)$.", "$m = \\dfrac{11-2}{4-1} = 3$; $2 = 3(1)+b \\Rightarrow b=-1$: $y = 3x - 1$."],
    ["Example 9: Horizontal line", "Write the line through $(3,6)$ with slope $0$.", "$y = 6$."],
  ],
  questions: [
    ["Problem 1", "Find the slope through $(2,1)$ and $(4,7)$.", "$3$"],
    ["Problem 2", "Find the slope through $(0,2)$ and $(5,12)$.", "$2$"],
    ["Problem 3", "Write the line with slope $4$ and $y$-intercept $-1$.", "$y = 4x - 1$"],
    ["Problem 4", "Write the line through $(0,7)$ with slope $3$.", "$y = 3x + 7$"],
    ["Problem 5", "Write the line through $(2,9)$ with slope $2$.", "$y = 2x + 5$"],
    ["Problem 6", "Find the slope through $(3,5)$ and $(3,1)$.", "Undefined (line $x = 3$)"],
    ["Problem 7", "Write the line through the origin with slope $6$.", "$y = 6x$"],
    ["Problem 8", "Write the line through $(1,4)$ and $(3,10)$.", "$y = 3x + 1$"],
    ["Problem 9", "Write the line through $(5,2)$ with slope $0$.", "$y = 2$"],
    ["Problem 10", "Find the slope through $(1,1)$ and $(5,9)$.", "$2$"],
    ["Problem 11", "Write the line through $(0,-3)$ with slope $5$.", "$y = 5x - 3$"],
    ["Problem 12", "Write the line through $(2,1)$ with slope $-2$.", "$y = -2x + 5$"],
    ["Problem 13", "Write the line through $(1,2)$ and $(2,5)$.", "$y = 3x - 1$"],
  ],
};
