export default {
  grade: "MTH1W",
  code: "4.7",
  title: "General Form of a Line",
  intro: "The <i>general form</i> of a line is $Ax + By + C = 0$. To read its slope and intercepts, rearrange into $y = mx + b$. To find the $x$-intercept set $y = 0$; for the $y$-intercept set $x = 0$. This worksheet converts to general form and reads key features from it.",
  examples: [
    ["Example 1: To general form", "Write $y = 2x + 3$ in general form.", "Move all terms to one side: $2x - y + 3 = 0$."],
    ["Example 2: To general form", "Write $y = -x + 5$ in general form.", "$x + y - 5 = 0$."],
    ["Example 3: Slope from general form", "Find the slope of $2x + y - 6 = 0$.", "Solve for $y$: $y = -2x + 6$. Slope $= -2$."],
    ["Example 4: Read features", "For $x - y + 4 = 0$, find the slope and $y$-intercept.", "$y = x + 4$: slope $1$, $y$-intercept $4$."],
    ["Example 5: y-intercept", "Find the $y$-intercept of $3x + 2y - 12 = 0$.", "Set $x = 0$: $2y = 12 \\Rightarrow y = 6$."],
    ["Example 6: x-intercept", "Find the $x$-intercept of $2x + y - 8 = 0$.", "Set $y = 0$: $2x = 8 \\Rightarrow x = 4$."],
    ["Example 7: Clear fractions", "Write $y = \\tfrac{1}{2}x - 2$ in general form.", "Multiply by $2$: $2y = x - 4 \\Rightarrow x - 2y - 4 = 0$."],
    ["Example 8: Slope from general form", "Find the slope of $4x - 2y + 6 = 0$.", "$2y = 4x + 6 \\Rightarrow y = 2x + 3$. Slope $= 2$."],
    ["Example 9: Rearrange", "Write $3x + y = 7$ in general form.", "$3x + y - 7 = 0$."],
  ],
  questions: [
    ["Problem 1", "Write $y = 3x + 1$ in general form.", "$3x - y + 1 = 0$"],
    ["Problem 2", "Write $y = -2x + 4$ in general form.", "$2x + y - 4 = 0$"],
    ["Problem 3", "Find the slope of $x + y - 5 = 0$.", "$-1$"],
    ["Problem 4", "Find the slope of $2x - y + 3 = 0$.", "$2$"],
    ["Problem 5", "Find the $y$-intercept of $x + 2y - 8 = 0$.", "$4$"],
    ["Problem 6", "Find the $x$-intercept of $3x + y - 9 = 0$.", "$3$"],
    ["Problem 7", "Write $y = \\tfrac{1}{3}x + 2$ in general form.", "$x - 3y + 6 = 0$"],
    ["Problem 8", "Find the slope of $6x - 3y + 9 = 0$.", "$2$"],
    ["Problem 9", "Find the $y$-intercept of $4x + 2y - 10 = 0$.", "$5$"],
    ["Problem 10", "Find the $x$-intercept of $x - y - 4 = 0$.", "$4$"],
    ["Problem 11", "Write $y = 5x - 2$ in general form.", "$5x - y - 2 = 0$"],
    ["Problem 12", "Find the slope of $5x + y - 1 = 0$.", "$-5$"],
    ["Problem 13", "Write $y = -x - 3$ in general form.", "$x + y + 3 = 0$"],
  ],
};
