export default {
  grade: "MTH1W",
  code: "4.8",
  title: "General Form vs Slope-Intercept Form",
  intro: "The same line can be written in <i>general form</i> $Ax + By + C = 0$ or <i>slope-intercept form</i> $y = mx + b$. Slope-intercept is best for reading slope and intercept; general form is tidy with integer coefficients. This worksheet converts back and forth.",
  examples: [
    ["Example 1: General → slope-intercept", "Convert $2x + y - 6 = 0$ to slope-intercept form.", "$y = -2x + 6$."],
    ["Example 2: Slope-intercept → general", "Convert $y = 3x - 2$ to general form.", "$3x - y - 2 = 0$."],
    ["Example 3: With a fraction slope", "Convert $3x + 2y - 12 = 0$ to slope-intercept form.", "$2y = -3x + 12 \\Rightarrow y = -\\tfrac{3}{2}x + 6$."],
    ["Example 4: Clear a fraction", "Convert $y = \\tfrac{1}{2}x + 1$ to general form.", "Multiply by $2$: $2y = x + 2 \\Rightarrow x - 2y + 2 = 0$."],
    ["Example 5: Read features", "State the slope and $y$-intercept of $4x - y + 5 = 0$.", "$y = 4x + 5$: slope $4$, $y$-intercept $5$."],
    ["Example 6: General → slope-intercept", "Convert $x + 3y - 9 = 0$ to slope-intercept form.", "$3y = -x + 9 \\Rightarrow y = -\\tfrac{1}{3}x + 3$."],
    ["Example 7: Slope-intercept → general", "Convert $y = -2x + 7$ to general form.", "$2x + y - 7 = 0$."],
    ["Example 8: General → slope-intercept", "Convert $5x - y - 3 = 0$ to slope-intercept form.", "$y = 5x - 3$."],
    ["Example 9: Simplify first", "Convert $2x + 4y - 8 = 0$ to slope-intercept form.", "Divide by $2$: $x + 2y - 4 = 0 \\Rightarrow y = -\\tfrac{1}{2}x + 2$."],
  ],
  questions: [
    ["Problem 1", "Convert $3x + y - 9 = 0$ to slope-intercept form.", "$y = -3x + 9$"],
    ["Problem 2", "Convert $y = 2x - 5$ to general form.", "$2x - y - 5 = 0$"],
    ["Problem 3", "Convert $x + 2y - 6 = 0$ to slope-intercept form.", "$y = -\\tfrac{1}{2}x + 3$"],
    ["Problem 4", "Convert $y = 4x + 1$ to general form.", "$4x - y + 1 = 0$"],
    ["Problem 5", "State the slope and $y$-intercept of $5x - y + 2 = 0$.", "Slope $5$, $y$-intercept $2$"],
    ["Problem 6", "Convert $2x + 3y - 12 = 0$ to slope-intercept form.", "$y = -\\tfrac{2}{3}x + 4$"],
    ["Problem 7", "Convert $y = -x + 6$ to general form.", "$x + y - 6 = 0$"],
    ["Problem 8", "Convert $6x - 2y + 4 = 0$ to slope-intercept form.", "$y = 3x + 2$"],
    ["Problem 9", "Convert $y = \\tfrac{1}{4}x - 1$ to general form.", "$x - 4y - 4 = 0$"],
    ["Problem 10", "Convert $x - y - 7 = 0$ to slope-intercept form.", "$y = x - 7$"],
    ["Problem 11", "Convert $y = -3x$ to general form.", "$3x + y = 0$"],
    ["Problem 12", "Convert $4x + 8y - 16 = 0$ to slope-intercept form.", "$y = -\\tfrac{1}{2}x + 2$"],
    ["Problem 13", "State the slope and $y$-intercept of $2x - y + 6 = 0$.", "Slope $2$, $y$-intercept $6$"],
  ],
};
