export default {
  grade: "MTH1W",
  code: "4.9",
  title: "Parallel and Perpendicular Lines",
  intro: "Two lines are <i>parallel</i> when they have the same slope. They are <i>perpendicular</i> when their slopes are negative reciprocals — their product is $-1$ (e.g. $2$ and $-\\tfrac{1}{2}$). This worksheet identifies and builds parallel and perpendicular lines.",
  examples: [
    ["Example 1: Parallel slope", "What slope is parallel to $y = 3x + 1$?", "Same slope: $3$."],
    ["Example 2: Perpendicular slope", "What slope is perpendicular to $y = 2x$?", "Negative reciprocal of $2$: $-\\tfrac{1}{2}$."],
    ["Example 3: Parallel?", "Are $y = 2x + 1$ and $y = 2x - 5$ parallel?", "Same slope $2$ ⇒ <b>yes</b>."],
    ["Example 4: Perpendicular?", "Are $y = 3x$ and $y = -\\tfrac{1}{3}x$ perpendicular?", "$3 \\times \\left(-\\tfrac{1}{3}\\right) = -1$ ⇒ <b>yes</b>."],
    ["Example 5: Build a parallel line", "Write the line parallel to $y = 4x - 2$ through $(0,5)$.", "Same slope $4$, $b = 5$: $y = 4x + 5$."],
    ["Example 6: Perpendicular slope", "What slope is perpendicular to $y = -\\tfrac{1}{2}x$?", "Negative reciprocal of $-\\tfrac12$: $2$."],
    ["Example 7: Parallel?", "Are $y = 2x + 1$ and $y = -2x + 1$ parallel?", "Slopes $2$ and $-2$ differ ⇒ <b>no</b>."],
    ["Example 8: Perpendicular slope", "What slope is perpendicular to $y = 5x$?", "$-\\tfrac{1}{5}$."],
    ["Example 9: Build a perpendicular line", "Write the line perpendicular to $y = 2x + 3$ through the origin.", "Perpendicular slope $-\\tfrac12$, through $(0,0)$: $y = -\\tfrac{1}{2}x$."],
  ],
  questions: [
    ["Problem 1", "What slope is parallel to $y = 5x - 2$?", "$5$"],
    ["Problem 2", "What slope is perpendicular to $y = 3x$?", "$-\\tfrac{1}{3}$"],
    ["Problem 3", "Are $y = 4x + 1$ and $y = 4x - 9$ parallel?", "Yes"],
    ["Problem 4", "Are $y = 2x$ and $y = -\\tfrac{1}{2}x + 4$ perpendicular?", "Yes"],
    ["Problem 5", "Write the line parallel to $y = 2x + 3$ through $(0,7)$.", "$y = 2x + 7$"],
    ["Problem 6", "What slope is perpendicular to $y = -\\tfrac{1}{4}x$?", "$4$"],
    ["Problem 7", "Are $y = 3x$ and $y = -3x$ parallel?", "No"],
    ["Problem 8", "What slope is perpendicular to $y = 6x$?", "$-\\tfrac{1}{6}$"],
    ["Problem 9", "Write the line perpendicular to $y = 3x + 1$ through the origin.", "$y = -\\tfrac{1}{3}x$"],
    ["Problem 10", "What slope is parallel to $y = -2x + 5$?", "$-2$"],
    ["Problem 11", "Are $y = x$ and $y = -x$ perpendicular?", "Yes"],
    ["Problem 12", "Write the line parallel to $y = \\tfrac{1}{2}x - 1$ through $(0,4)$.", "$y = \\tfrac{1}{2}x + 4$"],
    ["Problem 13", "What slope is perpendicular to $y = \\tfrac{2}{3}x$?", "$-\\tfrac{3}{2}$"],
  ],
};
