export default {
  grade: "MTH1W",
  code: "5.1",
  title: "Geometry & Measurement Through History",
  intro: "Geometry grew from practical needs across many cultures — surveying land, building, and tracking the seasons. This worksheet reviews key people, ideas, and units from the history of geometry and measurement.",
  examples: [
    ["Example 1: A famous theorem", "Who is credited with the theorem relating the sides of a right triangle?", "<b>Pythagoras</b> — the Pythagorean theorem, $a^2 + b^2 = c^2$."],
    ["Example 2: Right angles with rope", "Egyptian surveyors used a knotted rope with sides in the ratio $3:4:5$ to form which angle?", "A <b>right angle</b> ($90^{\\circ}$)."],
    ["Example 3: Why 360°?", "Why does a circle have $360^{\\circ}$ and an hour $60$ minutes?", "From the <b>Babylonian base-60</b> (sexagesimal) number system."],
    ["Example 4: The Elements", "Who wrote <i>The Elements</i>, the foundational geometry text?", "<b>Euclid</b>."],
    ["Example 5: A Greek letter", "What Greek letter names the ratio of a circle's circumference to its diameter?", "$\\pi$ (pi)."],
    ["Example 6: Value of π", "What is $\\pi$ to two decimal places?", "$\\approx 3.14$."],
    ["Example 7: The Nile", "Why did ancient Egyptians re-measure land each year?", "The annual <b>flooding of the Nile</b> erased property boundaries."],
    ["Example 8: The metric system", "The modern metric (SI) system is built on powers of which number?", "<b>10</b>."],
    ["Example 9: Archimedes", "Which Greek mathematician estimated $\\pi$ and found the area of a circle?", "<b>Archimedes</b>."],
  ],
  questions: [
    ["Problem 1", "Name the theorem about the sides of a right triangle.", "Pythagorean theorem"],
    ["Problem 2", "Who wrote <i>The Elements</i>?", "Euclid"],
    ["Problem 3", "A $3$-$4$-$5$ knotted rope forms which angle?", "A right angle ($90^{\\circ}$)"],
    ["Problem 4", "Our $360^{\\circ}$ circle comes from which civilization's number system?", "Babylonian (base 60)"],
    ["Problem 5", "What symbol stands for circumference ÷ diameter?", "$\\pi$"],
    ["Problem 6", "What is $\\pi$ to two decimal places?", "$3.14$"],
    ["Problem 7", "The metric system uses powers of which number?", "$10$"],
    ["Problem 8", "Egyptian land surveyors were called rope-______.", "stretchers"],
    ["Problem 9", "Which mathematician approximated $\\pi$ and a circle's area?", "Archimedes"],
    ["Problem 10", "How many degrees are in a full circle?", "$360^{\\circ}$"],
    ["Problem 11", "How many degrees are in a right angle?", "$90^{\\circ}$"],
    ["Problem 12", "What is the name of the base-60 number system?", "Sexagesimal"],
    ["Problem 13", "The word “geometry” originally meant the measurement of what?", "The earth / land"],
  ],
};
