export default {
  grade: "MTH1W",
  code: "5.2",
  title: "Designs with Circle & Triangle Properties",
  intro: "Designs and constructions rely on two facts: the angles of any triangle add to $180^{\\circ}$, and a circle's diameter is twice its radius. This worksheet uses triangle angle sums, special triangles, straight-line angles, and circle parts.",
  examples: [
    ["Example 1: Triangle angle sum", "Two angles of a triangle are $50^{\\circ}$ and $60^{\\circ}$. Find the third.", "$180 - 50 - 60 = 70^{\\circ}$."],
    ["Example 2: Equilateral", "What is each angle of an equilateral triangle?", "$180 \\div 3 = 60^{\\circ}$."],
    ["Example 3: Right triangle", "A right triangle has a $90^{\\circ}$ angle and a $35^{\\circ}$ angle. Find the third.", "$180 - 90 - 35 = 55^{\\circ}$."],
    ["Example 4: Diameter", "A circle has radius $5$ cm. Find its diameter.", "$d = 2r = 10$ cm."],
    ["Example 5: Radius", "A circle has diameter $14$. Find its radius.", "$r = d \\div 2 = 7$."],
    ["Example 6: Isosceles", "An isosceles triangle has an apex angle of $40^{\\circ}$. Find each base angle.", "$(180 - 40) \\div 2 = 70^{\\circ}$."],
    ["Example 7: Inscribed angle", "A central angle is $80^{\\circ}$. What inscribed angle stands on the same arc?", "Inscribed $=$ half the central $= 40^{\\circ}$."],
    ["Example 8: Straight line", "Two angles on a straight line: one is $110^{\\circ}$. Find the other.", "$180 - 110 = 70^{\\circ}$."],
    ["Example 9: Angle sum fact", "What do the interior angles of a triangle add up to?", "$180^{\\circ}$."],
  ],
  questions: [
    ["Problem 1", "Two angles of a triangle are $45^{\\circ}$ and $55^{\\circ}$. Find the third.", "$80^{\\circ}$"],
    ["Problem 2", "Each angle of an equilateral triangle?", "$60^{\\circ}$"],
    ["Problem 3", "A right triangle has a $25^{\\circ}$ acute angle. Find the other acute angle.", "$65^{\\circ}$"],
    ["Problem 4", "Radius $9$ — find the diameter.", "$18$"],
    ["Problem 5", "Diameter $20$ — find the radius.", "$10$"],
    ["Problem 6", "Isosceles triangle, apex $50^{\\circ}$. Find each base angle.", "$65^{\\circ}$"],
    ["Problem 7", "Central angle $100^{\\circ}$ — find the inscribed angle on the same arc.", "$50^{\\circ}$"],
    ["Problem 8", "Angles on a straight line; one is $130^{\\circ}$. Find the other.", "$50^{\\circ}$"],
    ["Problem 9", "A triangle has angles $90^{\\circ}$ and $30^{\\circ}$. Find the third.", "$60^{\\circ}$"],
    ["Problem 10", "A regular (equilateral) triangle has side $6$. Find its perimeter.", "$18$"],
    ["Problem 11", "An isosceles triangle has base angles of $70^{\\circ}$ each. Find the apex angle.", "$40^{\\circ}$"],
    ["Problem 12", "Radius $2.5$ — find the diameter.", "$5$"],
    ["Problem 13", "Two angles of a triangle are $100^{\\circ}$ and $40^{\\circ}$. Find the third.", "$40^{\\circ}$"],
  ],
};
