export default {
  grade: "MTH1W",
  code: "5.4",
  title: "The Pythagorean Theorem",
  intro: "In a right triangle, the square of the hypotenuse (the side opposite the right angle) equals the sum of the squares of the two legs: $a^2 + b^2 = c^2$. Use it to find a missing side or to test whether a triangle has a right angle.",
  examples: [
    ["Example 1: Find the hypotenuse", "Legs $3$ and $4$. Find the hypotenuse.", "$c^2 = 3^2 + 4^2 = 9 + 16 = 25$, so $c = 5$."],
    ["Example 2: Find the hypotenuse", "Legs $6$ and $8$. Find the hypotenuse.", "$c^2 = 36 + 64 = 100$, so $c = 10$."],
    ["Example 3: Find a leg", "One leg is $5$, the hypotenuse is $13$. Find the other leg.", "$b^2 = 13^2 - 5^2 = 169 - 25 = 144$, so $b = 12$."],
    ["Example 4: Find the hypotenuse", "Legs $5$ and $12$. Find the hypotenuse.", "$c^2 = 25 + 144 = 169$, so $c = 13$."],
    ["Example 5: Find the hypotenuse", "Legs $8$ and $15$. Find the hypotenuse.", "$c^2 = 64 + 225 = 289$, so $c = 17$."],
    ["Example 6: Find a leg", "One leg is $9$, the hypotenuse is $15$. Find the other leg.", "$b^2 = 225 - 81 = 144$, so $b = 12$."],
    ["Example 7: Find the hypotenuse", "Legs $7$ and $24$. Find the hypotenuse.", "$c^2 = 49 + 576 = 625$, so $c = 25$."],
    ["Example 8: Test a triangle", "Is a triangle with sides $3, 4, 6$ a right triangle?", "$3^2 + 4^2 = 25$ but $6^2 = 36$. $25 \\ne 36$, so <b>no</b>."],
    ["Example 9: Find the hypotenuse", "Legs $9$ and $12$. Find the hypotenuse.", "$c^2 = 81 + 144 = 225$, so $c = 15$."],
  ],
  questions: [
    ["Problem 1", "Legs $3$ and $4$. Find the hypotenuse.", "$5$"],
    ["Problem 2", "Legs $6$ and $8$. Find the hypotenuse.", "$10$"],
    ["Problem 3", "Legs $5$ and $12$. Find the hypotenuse.", "$13$"],
    ["Problem 4", "Legs $8$ and $15$. Find the hypotenuse.", "$17$"],
    ["Problem 5", "Leg $5$, hypotenuse $13$. Find the other leg.", "$12$"],
    ["Problem 6", "Leg $9$, hypotenuse $15$. Find the other leg.", "$12$"],
    ["Problem 7", "Legs $7$ and $24$. Find the hypotenuse.", "$25$"],
    ["Problem 8", "Legs $20$ and $21$. Find the hypotenuse.", "$29$"],
    ["Problem 9", "Is $5, 12, 13$ a right triangle?", "Yes ($25+144=169$)"],
    ["Problem 10", "Is $2, 3, 4$ a right triangle?", "No ($4+9 \\ne 16$)"],
    ["Problem 11", "Legs $9$ and $12$. Find the hypotenuse.", "$15$"],
    ["Problem 12", "Leg $8$, hypotenuse $17$. Find the other leg.", "$15$"],
    ["Problem 13", "Legs $10$ and $24$. Find the hypotenuse.", "$26$"],
  ],
};
