export default {
  grade: "MTH1W",
  code: "5.5",
  title: "Changing Dimensions: Perimeter",
  intro: "Perimeter is the distance around a shape. It is one-dimensional, so when every length is scaled by a factor $k$, the perimeter scales by the same factor $k$. This worksheet finds perimeters and explores how they change under scaling.",
  examples: [
    ["Example 1: Square", "Find the perimeter of a square with side $5$.", "$P = 4 \\times 5 = 20$."],
    ["Example 2: Rectangle", "Find the perimeter of a $6 \\times 4$ rectangle.", "$P = 2(6 + 4) = 20$."],
    ["Example 3: Scaling", "If a square's side is doubled, by what factor does the perimeter change?", "Perimeter is 1-D, so it scales by the same factor: $2$."],
    ["Example 4: Find the side", "A square has perimeter $12$. Find the side length.", "$s = 12 \\div 4 = 3$."],
    ["Example 5: Scaling factor", "All sides of a shape are scaled by $3$. By what factor does the perimeter change?", "$3$."],
    ["Example 6: Triangle", "Find the perimeter of a triangle with sides $3, 4, 5$.", "$P = 3 + 4 + 5 = 12$."],
    ["Example 7: Apply scaling", "A side is scaled by $4$. The new perimeter is the old one times what?", "$\\times 4$."],
    ["Example 8: Scaled perimeter", "A square has perimeter $20$. Find the new perimeter after scaling by $2$.", "$20 \\times 2 = 40$."],
    ["Example 9: Equilateral", "Find the perimeter of an equilateral triangle with side $7$.", "$P = 3 \\times 7 = 21$."],
  ],
  questions: [
    ["Problem 1", "Find the perimeter of a square with side $8$.", "$32$"],
    ["Problem 2", "Find the perimeter of a $7 \\times 3$ rectangle.", "$20$"],
    ["Problem 3", "Find the perimeter of a triangle with sides $5, 6, 7$.", "$18$"],
    ["Problem 4", "A square has perimeter $24$. Find the side length.", "$6$"],
    ["Problem 5", "Sides are scaled by $5$. By what factor does the perimeter change?", "$5$"],
    ["Problem 6", "A square has perimeter $16$. Find its perimeter after scaling by $3$.", "$48$"],
    ["Problem 7", "Find the perimeter of an equilateral triangle with side $9$.", "$27$"],
    ["Problem 8", "A $10 \\times 2$ rectangle is scaled by $2$. Find the new perimeter.", "$48$"],
    ["Problem 9", "Find the perimeter of a square with side $12$.", "$48$"],
    ["Problem 10", "Perimeter scales by the same factor as which measurement?", "The side length ($k$)"],
    ["Problem 11", "Find the perimeter of a regular pentagon with side $4$.", "$20$"],
    ["Problem 12", "A square has perimeter $40$. Find the side length.", "$10$"],
    ["Problem 13", "All sides of a triangle are doubled. By what factor does the perimeter change?", "$2$"],
  ],
};
