export default {
  grade: "MTH1W",
  code: "5.6",
  title: "Changing Dimensions: Area",
  intro: "Area is two-dimensional, so when every length of a figure is scaled by a factor $k$, the area scales by $k^2$ — it grows much faster than the perimeter. This worksheet finds areas and explores how they change under scaling.",
  examples: [
    ["Example 1: Square", "Find the area of a square with side $5$.", "$A = 5^2 = 25$."],
    ["Example 2: Rectangle", "Find the area of a $6 \\times 4$ rectangle.", "$A = 6 \\times 4 = 24$."],
    ["Example 3: Scaling", "A square's side is doubled. By what factor does the area change?", "$k^2 = 2^2 = 4$."],
    ["Example 4: Scaling", "All sides are scaled by $3$. By what factor does the area change?", "$3^2 = 9$."],
    ["Example 5: Triangle", "Find the area of a triangle with base $6$ and height $4$.", "$A = \\tfrac{1}{2}(6)(4) = 12$."],
    ["Example 6: Find the side", "A square has area $36$. Find its side length.", "$s = \\sqrt{36} = 6$."],
    ["Example 7: Scaling factor", "All lengths are scaled by $5$. By what factor does the area change?", "$5^2 = 25$."],
    ["Example 8: Rectangle", "Find the area of an $8 \\times 3$ rectangle.", "$A = 24$."],
    ["Example 9: Scaling", "Lengths are scaled by $4$. By what factor does the area change?", "$4^2 = 16$."],
  ],
  questions: [
    ["Problem 1", "Find the area of a square with side $7$.", "$49$"],
    ["Problem 2", "Find the area of a $9 \\times 3$ rectangle.", "$27$"],
    ["Problem 3", "A square's side is doubled. By what factor does the area change?", "$4$"],
    ["Problem 4", "Sides are scaled by $4$. By what factor does the area change?", "$16$"],
    ["Problem 5", "Find the area of a triangle with base $10$ and height $6$.", "$30$"],
    ["Problem 6", "A square has area $64$. Find its side length.", "$8$"],
    ["Problem 7", "Lengths are scaled by $3$. By what factor does the area change?", "$9$"],
    ["Problem 8", "Find the area of a $5 \\times 4$ rectangle.", "$20$"],
    ["Problem 9", "Lengths are scaled by $6$. By what factor does the area change?", "$36$"],
    ["Problem 10", "Find the area of a square with side $11$.", "$121$"],
    ["Problem 11", "Find the area of a triangle with base $8$ and height $5$.", "$20$"],
    ["Problem 12", "Lengths are scaled by $10$. By what factor does the area change?", "$100$"],
    ["Problem 13", "A square has area $100$. Find its side length.", "$10$"],
  ],
};
