export default {
  grade: "MTH1W",
  code: "5.7",
  title: "Volume",
  intro: "Volume measures the space inside a solid, in cubic units. Key formulas: rectangular prism $V = l\\,w\\,h$, cube $V = s^3$, cylinder $V = \\pi r^2 h$. Volume is three-dimensional, so when every length scales by $k$, the volume scales by $k^3$.",
  examples: [
    ["Example 1: Prism", "Find the volume of a $5 \\times 4 \\times 3$ rectangular prism.", "$V = 5 \\times 4 \\times 3 = 60$."],
    ["Example 2: Cube", "Find the volume of a cube with edge $4$.", "$V = 4^3 = 64$."],
    ["Example 3: Cylinder", "Find the volume of a cylinder with $r = 3$, $h = 10$ (in terms of $\\pi$).", "$V = \\pi r^2 h = \\pi(9)(10) = 90\\pi$."],
    ["Example 4: Cube", "Find the volume of a cube with edge $5$.", "$V = 5^3 = 125$."],
    ["Example 5: Cylinder", "Find the volume of a cylinder with $r = 2$, $h = 5$ (in terms of $\\pi$).", "$V = \\pi(4)(5) = 20\\pi$."],
    ["Example 6: Prism", "Find the volume of a $2 \\times 3 \\times 4$ prism.", "$V = 24$."],
    ["Example 7: Scaling", "Every edge of a solid is tripled. By what factor does the volume change?", "$k^3 = 3^3 = 27$."],
    ["Example 8: Find the edge", "A cube has volume $27$. Find its edge length.", "$s = \\sqrt[3]{27} = 3$."],
    ["Example 9: Cylinder", "Find the volume of a cylinder with $r = 4$, $h = 10$ (in terms of $\\pi$).", "$V = \\pi(16)(10) = 160\\pi$."],
  ],
  questions: [
    ["Problem 1", "Find the volume of a $6 \\times 5 \\times 2$ prism.", "$60$"],
    ["Problem 2", "Find the volume of a cube with edge $3$.", "$27$"],
    ["Problem 3", "Cylinder $r = 5$, $h = 4$ (in terms of $\\pi$).", "$100\\pi$"],
    ["Problem 4", "Find the volume of a cube with edge $6$.", "$216$"],
    ["Problem 5", "Cylinder $r = 3$, $h = 10$ (in terms of $\\pi$).", "$90\\pi$"],
    ["Problem 6", "Find the volume of a $10 \\times 2 \\times 3$ prism.", "$60$"],
    ["Problem 7", "Every edge is doubled. By what factor does the volume change?", "$8$"],
    ["Problem 8", "A cube has volume $125$. Find its edge length.", "$5$"],
    ["Problem 9", "Cylinder $r = 2$, $h = 9$ (in terms of $\\pi$).", "$36\\pi$"],
    ["Problem 10", "Find the volume of a $4 \\times 4 \\times 4$ cube.", "$64$"],
    ["Problem 11", "Every edge is scaled by $4$. By what factor does the volume change?", "$64$"],
    ["Problem 12", "Find the volume of a cube with edge $10$.", "$1000$"],
    ["Problem 13", "Cylinder $r = 1$, $h = 10$ (in terms of $\\pi$).", "$10\\pi$"],
  ],
};
