export default {
  grade: "MTH1W",
  code: "5.8",
  title: "Surface Area",
  intro: "Surface area is the total area of the outside of a solid, in square units. Key formulas: cube $SA = 6s^2$, rectangular prism $SA = 2(lw + lh + wh)$, cylinder $SA = 2\\pi r^2 + 2\\pi r h$, sphere $SA = 4\\pi r^2$. Like all areas, surface area scales by $k^2$.",
  examples: [
    ["Example 1: Cube", "Find the surface area of a cube with edge $4$.", "$SA = 6s^2 = 6(16) = 96$."],
    ["Example 2: Prism", "Find the surface area of a $5 \\times 4 \\times 3$ prism.", "$SA = 2(20 + 15 + 12) = 2(47) = 94$."],
    ["Example 3: Cylinder", "Find the surface area of a cylinder with $r = 4$, $h = 9$ (in terms of $\\pi$).", "$2\\pi(16) + 2\\pi(4)(9) = 32\\pi + 72\\pi = 104\\pi$."],
    ["Example 4: Sphere", "Find the surface area of a sphere with $r = 3$ (in terms of $\\pi$).", "$SA = 4\\pi r^2 = 4\\pi(9) = 36\\pi$."],
    ["Example 5: Cube", "Find the surface area of a cube with edge $3$.", "$6(9) = 54$."],
    ["Example 6: Scaling", "Every edge of a cube is doubled. By what factor does the surface area change?", "$k^2 = 2^2 = 4$."],
    ["Example 7: Sphere", "Find the surface area of a sphere with $r = 5$ (in terms of $\\pi$).", "$4\\pi(25) = 100\\pi$."],
    ["Example 8: Prism", "Find the surface area of a $2 \\times 3 \\times 4$ prism.", "$2(6 + 8 + 12) = 2(26) = 52$."],
    ["Example 9: Cube", "Find the surface area of a cube with edge $5$.", "$6(25) = 150$."],
  ],
  questions: [
    ["Problem 1", "Find the surface area of a cube with edge $3$.", "$54$"],
    ["Problem 2", "Sphere $r = 5$ (in terms of $\\pi$).", "$100\\pi$"],
    ["Problem 3", "Find the surface area of a $2 \\times 3 \\times 4$ prism.", "$52$"],
    ["Problem 4", "Lengths are scaled by $3$. By what factor does the surface area change?", "$9$"],
    ["Problem 5", "Find the surface area of a cube with edge $4$.", "$96$"],
    ["Problem 6", "Cylinder $r = 3$, $h = 7$ (in terms of $\\pi$).", "$60\\pi$"],
    ["Problem 7", "Sphere $r = 3$ (in terms of $\\pi$).", "$36\\pi$"],
    ["Problem 8", "Find the surface area of a $5 \\times 4 \\times 3$ prism.", "$94$"],
    ["Problem 9", "Find the surface area of a cube with edge $6$.", "$216$"],
    ["Problem 10", "By what factor does surface area change when lengths are scaled by $2$?", "$4$"],
    ["Problem 11", "Sphere $r = 2$ (in terms of $\\pi$).", "$16\\pi$"],
    ["Problem 12", "Find the surface area of a cube with edge $10$.", "$600$"],
    ["Problem 13", "Find the surface area of a $1 \\times 2 \\times 3$ prism.", "$22$"],
  ],
};
