export default {
  grade: "MTH1W",
  code: "6.1",
  title: "Big Data & Its Implications",
  intro: "Big data is described by the “three V's” — <b>Volume</b> (how much), <b>Velocity</b> (how fast it arrives), and <b>Variety</b> (text, images, sensors…). Data sizes step up by about $1000$ ($1$ MB $=1000$ KB, $1$ GB $=1000$ MB). We also study sampling and the privacy risks of large data sets.",
  examples: [
    ["Example 1: GB to MB", "Convert $2$ GB to MB.", "$\\times 1000$: $2000$ MB."],
    ["Example 2: The three V's", "Name the three V's of big data.", "Volume, Velocity, Variety."],
    ["Example 3: Velocity", "A sensor takes $5$ readings per second. How many in one minute?", "$5 \\times 60 = 300$."],
    ["Example 4: Sampling bias", "Why is surveying only paying members biased?", "The sample isn't representative — non-paying users are left out."],
    ["Example 5: Daily data", "A site logs $1.2$ KB per visit and gets $50{,}000$ visits/day. How many MB per day?", "$1.2 \\times 50{,}000 = 60{,}000$ KB $= 60$ MB."],
    ["Example 6: TB to GB", "Convert $3$ TB to GB.", "$3000$ GB."],
    ["Example 7: Identify a V", "Which V refers to how fast data arrives?", "Velocity."],
    ["Example 8: Population", "The whole group you want to study is called the…", "Population."],
    ["Example 9: A risk", "Name one risk of large-scale personal data collection.", "Loss of privacy (also: misuse, security breaches)."],
  ],
  questions: [
    ["Problem 1", "Convert $4$ GB to MB.", "$4000$ MB"],
    ["Problem 2", "Name the three V's of big data.", "Volume, Velocity, Variety"],
    ["Problem 3", "A sensor takes $10$ readings/second. How many in one minute?", "$600$"],
    ["Problem 4", "Convert $5$ TB to GB.", "$5000$ GB"],
    ["Problem 5", "Which V refers to the amount of data?", "Volume"],
    ["Problem 6", "Which V refers to different forms (text, images, sensors)?", "Variety"],
    ["Problem 7", "Convert $2000$ MB to GB.", "$2$ GB"],
    ["Problem 8", "A smaller group chosen to represent the whole is a…", "Sample"],
    ["Problem 9", "The entire group being studied is the…", "Population"],
    ["Problem 10", "Name one risk of big data.", "Privacy / misuse / security"],
    ["Problem 11", "About how many bytes are in $1$ KB (using the $1000$ convention)?", "$1000$"],
    ["Problem 12", "A site logs $2$ KB/visit over $1000$ visits. How many MB?", "$2$ MB"],
    ["Problem 13", "Convert $6$ GB to MB.", "$6000$ MB"],
  ],
};
