export default {
  grade: "MTH1W",
  code: "6.3",
  title: "Scatter Plots & Correlation",
  intro: "A scatter plot shows pairs of values. <b>Correlation</b> describes whether they move together: <i>positive</i> (both rise), <i>negative</i> (one rises as the other falls), or <i>none</i>. A line of best fit $y = mx + b$ lets us predict. Remember: correlation does not prove causation.",
  examples: [
    ["Example 1: Positive", "Hours studied vs test score rise together. What correlation?", "Positive correlation."],
    ["Example 2: Negative", "Outside temperature vs heating cost. What correlation?", "Negative (warmer ⇒ lower cost)."],
    ["Example 3: Best-fit slope", "Find the slope of the best-fit line through $(0,2)$ and $(5,12)$.", "$m = \\dfrac{12-2}{5-0} = 2$."],
    ["Example 4: Predict", "Best-fit line $y = 3x + 5$. Predict the score for $x = 4$.", "$y = 3(4) + 5 = 17$."],
    ["Example 5: Causation trap", "Ice-cream sales and drownings are positively correlated. Does ice cream cause drowning?", "No — a lurking variable (hot weather) drives both."],
    ["Example 6: No correlation", "Points show no clear pattern. What correlation?", "No (zero) correlation."],
    ["Example 7: Negative", "As $x$ increases, $y$ decreases. What correlation?", "Negative."],
    ["Example 8: Best-fit slope", "Find the slope through $(1,3)$ and $(4,9)$.", "$m = \\dfrac{9-3}{4-1} = 2$."],
    ["Example 9: Predict", "Using $y = 2x + 1$, predict $y$ at $x = 6$.", "$y = 13$."],
  ],
  questions: [
    ["Problem 1", "As $x$ increases, $y$ increases. What correlation?", "Positive"],
    ["Problem 2", "As $x$ increases, $y$ decreases. What correlation?", "Negative"],
    ["Problem 3", "Points show no trend. What correlation?", "None"],
    ["Problem 4", "Slope of best fit through $(0,2)$ and $(5,12)$.", "$2$"],
    ["Problem 5", "Slope of best fit through $(1,3)$ and $(4,9)$.", "$2$"],
    ["Problem 6", "Using $y = 2x + 1$, predict $y$ at $x = 6$.", "$13$"],
    ["Problem 7", "Using $y = 3x + 5$, predict $y$ at $x = 4$.", "$17$"],
    ["Problem 8", "Does correlation prove causation?", "No"],
    ["Problem 9", "A hidden factor that influences both variables is called a…", "Lurking variable"],
    ["Problem 10", "Predicting within the data range is called…", "Interpolation"],
    ["Problem 11", "Predicting beyond the data range is called…", "Extrapolation"],
    ["Problem 12", "Using $y = 4x - 2$, predict $y$ at $x = 3$.", "$10$"],
    ["Problem 13", "Slope of best fit through $(2,5)$ and $(4,9)$.", "$2$"],
  ],
};
