export default {
  grade: "MTH1W",
  code: "6.4",
  title: "The Mathematical Modelling Process",
  intro: "A mathematical model is an equation that describes a real situation. Linear cost models look like $C = (\\text{rate})x + (\\text{fixed cost})$. Modelling is a cycle: understand → assume → build → test → interpret/revise. This worksheet reads, builds, and uses linear models.",
  examples: [
    ["Example 1: Read a model", "In $C = 15n + 40$, state the fixed cost and the cost per item.", "Fixed cost \\$40; \\$15 per item."],
    ["Example 2: Use a model", "Using $C = 15n + 40$, find the cost for $12$ items.", "$C = 15(12) + 40 = 220$."],
    ["Example 3: Build a model", "A taxi charges \\$3.50 plus \\$1.75/km. Write the cost for $d$ km.", "$C = 1.75d + 3.50$."],
    ["Example 4: The cycle", "List the stages of the modelling cycle in order.", "Understand → assume → build → test → interpret/revise."],
    ["Example 5: Solve a model", "A pool drains at $50$ L/min from $3000$ L: $V = 3000 - 50t$. When is it empty?", "$0 = 3000 - 50t \\Rightarrow t = 60$ minutes."],
    ["Example 6: Use a model", "Using $C = 0.10m + 25$, find the cost for $m = 300$.", "$C = 0.10(300) + 25 = 55$."],
    ["Example 7: First stage", "What is the first stage of modelling?", "Understand the problem."],
    ["Example 8: Interpret & predict", "For savings $S = 20w + 50$, interpret $20$ and $50$, then find $S$ at $w = 8$.", "$\\$20$ saved per week; \\$50 to start. $S = 20(8) + 50 = 210$."],
    ["Example 9: Why revise", "Why must a model be tested and sometimes revised?", "Assumptions may be wrong; testing against data shows where to improve."],
  ],
  questions: [
    ["Problem 1", "In $C = 15n + 40$, what is the fixed cost?", "\\$40"],
    ["Problem 2", "Using $C = 15n + 40$, find the cost for $12$ items.", "\\$220"],
    ["Problem 3", "A taxi charges \\$3.50 plus \\$1.75/km. Write the model for $d$ km.", "$C = 1.75d + 3.50$"],
    ["Problem 4", "Using $C = 0.10m + 25$, find the cost for $m = 300$.", "\\$55"],
    ["Problem 5", "What is the first stage of the modelling process?", "Understand the problem"],
    ["Problem 6", "For $S = 20w + 50$, find $S$ when $w = 8$.", "$210$"],
    ["Problem 7", "For $V = 3000 - 50t$, when is $V = 0$?", "$t = 60$"],
    ["Problem 8", "Using $C = 5n + 20$, find the cost for $n = 10$.", "$70$"],
    ["Problem 9", "In $y = mx + b$, what does $b$ represent in a model?", "The start / fixed value"],
    ["Problem 10", "In $y = mx + b$, what does $m$ represent in a model?", "The rate of change"],
    ["Problem 11", "Is modelling a one-time step or a repeating cycle?", "A cycle"],
    ["Problem 12", "Using $C = 2n + 8$, find the cost for $n = 6$.", "$20$"],
    ["Problem 13", "For savings $S = 10w + 30$, find $S$ at $w = 5$.", "$80$"],
  ],
};
