export default {
  grade: "MTH1W",
  code: "7.1",
  title: "Making Financial Decisions",
  intro: "Smart money choices come from comparing options with math: separating <b>fixed</b> costs (the same no matter what) from <b>variable</b> costs (grow with use), finding the <b>unit price</b>, and locating the <b>break-even point</b> where one option overtakes another.",
  examples: [
    ["Example 1: Build a cost model", "A phone plan is \\$30/month plus \\$0.05/text. Write the cost $C$ for $t$ texts.", "Fixed \\$30, variable \\$0.05 each: $C = 0.05t + 30$."],
    ["Example 2: Break-even", "Plan A: \\$40 flat. Plan B: \\$15 + \\$0.50/GB. For how many GB are they equal?", "$15 + 0.5g = 40 \\Rightarrow 0.5g = 25 \\Rightarrow g = 50$ GB."],
    ["Example 3: Unit price", "A $750$ mL juice costs \\$3.00; a $2$ L bottle costs \\$7.20. Which is the better deal?", "Small: $\\$3.00/0.75 = \\$4.00$/L. Large: $\\$7.20/2 = \\$3.60$/L. The $2$ L is better."],
    ["Example 4: Tax flips the winner", "Store A: \\$900, no tax. Store B: \\$820 + 13% tax. Which is cheaper?", "B $= 820 \\times 1.13 = \\$926.60 >$ \\$900. Store A is cheaper."],
    ["Example 5: One-year cost", "A gym charges \\$25 to join plus \\$18/month. Find the one-year total.", "$25 + 18(12) = 25 + 216 = \\$241$."],
    ["Example 6: Fixed or variable", "Is a flat \\$30 monthly fee a fixed or variable cost?", "Fixed (it doesn't change with use)."],
    ["Example 7: Unit rate", "You earn \\$60 for $5$ hours of work. Find the hourly rate.", "$\\$60 \\div 5 = \\$12$/hour."],
    ["Example 8: Use a model", "Using $C = 0.10m + 25$, find the cost for $m = 300$ minutes.", "$0.10(300) + 25 = \\$55$."],
    ["Example 9: Break-even", "Plan A: \\$50 flat. Plan B: \\$20 + \\$3/hour. For how many hours are they equal?", "$20 + 3h = 50 \\Rightarrow h = 10$."],
  ],
  questions: [
    ["Problem 1", "A phone plan is \\$30 plus \\$0.05/text. Write the cost model for $t$ texts.", "$C = 0.05t + 30$"],
    ["Problem 2", "A gym charges \\$25 to join plus \\$18/month. Find the one-year total.", "\\$241"],
    ["Problem 3", "Which is the better unit price: $500$ g for \\$4.00 or $1.2$ kg for \\$8.40?", "$1.2$ kg (\\$7/kg vs \\$8/kg)"],
    ["Problem 4", "Is a monthly subscription fee a fixed or variable cost?", "Fixed"],
    ["Problem 5", "You earn \\$60 for $5$ hours. Find the hourly rate.", "\\$12/hour"],
    ["Problem 6", "Solve the break-even: $20 + 3h = 50$.", "$h = 10$"],
    ["Problem 7", "Store A: \\$900, no tax. Store B: \\$820 + 13% tax. Which is cheaper?", "Store A (B $=$ \\$926.60)"],
    ["Problem 8", "Is \\$0.05 per text a fixed or variable cost?", "Variable"],
    ["Problem 9", "Using $C = 0.10m + 25$, find the cost for $m = 300$.", "\\$55"],
    ["Problem 10", "Solve the break-even: $15 + 0.5g = 40$.", "$g = 50$"],
    ["Problem 11", "Better deal: \\$3.00 for $750$ mL or \\$3.60 for $1$ L?", "$1$ L (\\$3.60/L vs \\$4.00/L)"],
    ["Problem 12", "In a cost model $C = rx + f$, what does $f$ represent?", "The fixed cost"],
    ["Problem 13", "Plan A: \\$40 flat. Plan B: \\$10 + \\$2/unit. Find the break-even number of units.", "$x = 15$"],
  ],
};
