export default {
  grade: "MTH1W",
  code: "7.3",
  title: "Interest & Borrowing",
  intro: "Interest is the price of money. <b>Simple interest</b> is earned on the original amount only: $I = Prt$ (and total $A = P + I$). <b>Compound interest</b> is earned on the growing balance: $A = P(1 + r)^n$. Compound always overtakes simple given enough time.",
  examples: [
    ["Example 1: Simple interest", "Find the simple interest on \\$2000 at 4%/year for $3$ years.", "$I = Prt = 2000 \\times 0.04 \\times 3 = \\$240$."],
    ["Example 2: Total owed", "A \\$1500 loan at 6% simple interest for $2$ years — total to repay?", "$I = 1500 \\times 0.06 \\times 2 = 180$; total $= 1500 + 180 = \\$1680$."],
    ["Example 3: Compound", "\\$1000 at 5% compounded annually for $3$ years.", "$A = 1000 \\times 1.05^3 = 1000 \\times 1.157625 = \\$1157.63$."],
    ["Example 4: Loan interest", "A \\$5000 loan at 8% simple interest. Interest after $4$ years?", "$5000 \\times 0.08 \\times 4 = \\$1600$."],
    ["Example 5: Simple vs compound", "Compare \\$1000 at 5% for $10$ years: simple vs compound.", "Simple: $1000(1 + 0.5) = \\$1500$. Compound: $1000 \\times 1.05^{10} \\approx \\$1628.89$."],
    ["Example 6: Simple interest", "Find the simple interest on \\$800 at 5%/year for $2$ years.", "$800 \\times 0.05 \\times 2 = \\$80$."],
    ["Example 7: Compound", "\\$2000 at 6% compounded annually for $5$ years (nearest cent).", "$2000 \\times 1.06^5 \\approx \\$2676.45$."],
    ["Example 8: Principal", "What is the principal?", "The original amount invested or borrowed."],
    ["Example 9: Which grows faster", "Over time, which grows faster — simple or compound interest?", "Compound."],
  ],
  questions: [
    ["Problem 1", "Simple interest on \\$800 at 5%/year for $2$ years?", "\\$80"],
    ["Problem 2", "Total to repay a \\$1200 loan at 10% simple interest for $3$ years?", "\\$1560"],
    ["Problem 3", "\\$2000 at 6% compounded annually for $5$ years (nearest cent)?", "\\$2676.45"],
    ["Problem 4", "Why can credit-card debt grow so fast?", "It compounds at a high rate"],
    ["Problem 5", "Simple interest on \\$5000 at 8%/year for $4$ years?", "\\$1600"],
    ["Problem 6", "\\$1000 at 5% compounded annually for $3$ years (nearest cent)?", "\\$1157.63"],
    ["Problem 7", "Write the simple interest formula.", "$I = Prt$"],
    ["Problem 8", "Write the compound amount formula.", "$A = P(1+r)^n$"],
    ["Problem 9", "Which grows faster over time?", "Compound"],
    ["Problem 10", "What is the original amount borrowed or invested called?", "The principal"],
    ["Problem 11", "Simple interest on \\$1000 at 5%/year for $10$ years?", "\\$500"],
    ["Problem 12", "Simple interest on \\$3000 at 4%/year for $6$ years?", "\\$720"],
    ["Problem 13", "\\$1000 at 10% compounded annually for $2$ years — final amount?", "\\$1210"],
  ],
};
