// MCR3U Unit 1 worksheets — Characteristics of Functions.
// Examples: full step-by-step solutions with TikZ graphs (\eplot).
const r = String.raw;
const U = "1: Characteristics of Functions";

export default [
  {
    code: "1.1", unit: U, title: "Functions, Relations & Function Notation",
    intro: r`A function gives exactly one output for each input; $f(x)$ is the output at $x$.`,
    ideas: [r`Vertical-line test: a vertical line may meet the graph only once.`, r`A function is one-to-one or many-to-one, never one-to-many.`, r`Evaluate by substituting for every $x$.`],
    examples: [
      { t: "Function or not", body: r`Is $x=y^2$ a function?\soln Solve for $y$: $y=\pm\sqrt{x}$. Then $x=4$ gives $y=2$ \emph{and} $y=-2$ — one input, two outputs. \\ \textbf{Not} a function.` },
      { t: "Evaluate", body: r`For $f(x)=2x^2+3x-1$, find $f(2)$.\soln Substitute $x=2$: $2(2)^2+3(2)-1=8+6-1=13$.` },
      { t: "Negative input", body: r`For $f(x)=2x^2+3x-1$, find $f(-1)$.\soln $2(-1)^2+3(-1)-1=2-3-1=-2$.` },
      { t: "From a set", body: r`Is $\{(1,2),(1,3)\}$ a function?\soln Input $1$ maps to both $2$ and $3$ — one-to-many, so \textbf{not} a function.` },
      { t: "Evaluate", body: r`For $f(x)=x^2-4$, find $f(3)$.\soln $(3)^2-4=9-4=5$.` },
      { t: "Evaluate", body: r`For $f(x)=5-2x$, find $f(4)$.\soln $5-2(4)=5-8=-3$.` },
      { t: "Vertical-line test", body: r`Is $y=3x+1$ a function?\soln A non-vertical line meets every vertical line once, so \textbf{yes}.` },
      { t: "Many-to-one", body: r`Is $f(x)=x^2$ a function even though $f(2)=f(-2)$?\soln Two inputs sharing one output (many-to-one) is allowed; it still passes the vertical-line test, so \textbf{yes}:` + r`\eplot{-3}{3}{-1}{8}{\addplot[exblue,very thick,domain=-2.6:2.6]{x^2};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(2,4) (-2,4)};}` },
      { t: "Solve", body: r`For $f(x)=2x-6$, solve $f(x)=0$.\soln $2x-6=0\Rightarrow x=3$.` },
    ],
    questions: [
      { ask: r`For $f(x)=x^2-4$, find $f(-2)$.` },
      { ask: r`For $f(x)=3x+1$, find $f(5)$.` },
      { ask: r`Is $\{(2,1),(3,1),(4,1)\}$ a function?` },
      { ask: r`For $f(x)=x^2+x$, find $f(-3)$.` },
      { ask: r`Does $y=x^2$ pass the vertical-line test?` },
      { ask: r`For $f(x)=2x-5$, find $f(0)$.` },
      { ask: r`For $f(x)=4-x^2$, find $f(2)$.` },
      { ask: r`Is $x=y^2$ a function?` },
      { ask: r`For $f(x)=5x$, solve $f(x)=20$.` },
      { ask: r`For $f(x)=x^2-1$, find $f(4)$.` },
      { ask: r`Is a one-to-many relation a function?` },
      { ask: r`For $f(x)=3x^2-2x$, find $f(1)$.` },
      { ask: r`For $f(x)=x^2-2x$, solve $f(x)=0$.`, challenge: true, ws: "2.6cm" },
    ],
    answers: [r`$0$`, r`$16$`, r`yes`, r`$6$`, r`yes`, r`$-5$`, r`$0$`, r`no`, r`$x=4$`, r`$15$`, r`no`, r`$1$`, r`$x=0,2$`],
  },
  {
    code: "1.2", unit: U, title: "Domain and Range",
    intro: r`The domain is all allowed inputs $x$; the range is all outputs $y$.`,
    ideas: [r`Denominators cannot be zero.`, r`Square roots need a non-negative radicand.`, r`A parabola's range starts at its vertex.`],
    examples: [
      { t: "Square-root domain", body: r`Domain of $\sqrt{x-2}$?\soln The radicand must be $\ge0$: $x-2\ge0\Rightarrow x\ge2$. The curve starts at $(2,0)$:` + r`\eplot{-1}{8}{-1}{4}{\addplot[exblue,very thick,domain=2:8]{sqrt(x-2)};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(2,0)};}` },
      { t: "Square-root range", body: r`Range of $\sqrt{x-2}$?\soln A square root is never negative, so outputs are $y\ge0$.` },
      { t: "Quadratic range", body: r`Range of $x^2+1$?\soln The vertex $(0,1)$ is the lowest point, so $y\ge1$:` + r`\eplot{-3}{3}{-1}{8}{\addplot[exblue,very thick,domain=-2.6:2.6]{x^2+1};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,1)};}` },
      { t: "Rational domain", body: r`Domain of $\dfrac{1}{x-3}$?\soln The denominator cannot be zero: $x-3\ne0\Rightarrow x\ne3$.` },
      { t: "Polynomial domain", body: r`Domain of $x^2-5$?\soln A polynomial is defined everywhere: all real numbers.` },
      { t: "Reflected range", body: r`Range of $-x^2$?\soln It opens down with vertex $(0,0)$ as the highest point: $y\le0$.` },
      { t: "Domain", body: r`Domain of $\sqrt{x+5}$?\soln $x+5\ge0\Rightarrow x\ge-5$.` },
      { t: "Rational domain", body: r`Domain of $\dfrac{1}{x+2}$?\soln $x+2\ne0\Rightarrow x\ne-2$.` },
      { t: "Range", body: r`Range of $x^2-3$?\soln Vertex $(0,-3)$ is the minimum, so $y\ge-3$.` },
    ],
    questions: [
      { ask: r`Domain of $\sqrt{x+5}$?` },
      { ask: r`Domain of $\dfrac{1}{x+2}$?` },
      { ask: r`Range of $x^2-3$?` },
      { ask: r`Range of $-x^2$?` },
      { ask: r`Domain of $\sqrt{2x-6}$?` },
      { ask: r`Domain of $x^2+1$?` },
      { ask: r`Range of $x^2+4$?` },
      { ask: r`Domain of $\dfrac{1}{x-1}$?` },
      { ask: r`Domain of $\sqrt{x-7}$?` },
      { ask: r`Range of $-x^2+2$?` },
      { ask: r`Domain of $3x-1$?` },
      { ask: r`Range of $\sqrt{x}$?` },
      { ask: r`State the domain and range of $\sqrt{x-1}+2$.`, challenge: true, ws: "2.6cm" },
    ],
    answers: [r`$x\ge-5$`, r`$x\ne-2$`, r`$y\ge-3$`, r`$y\le0$`, r`$x\ge3$`, r`all reals`, r`$y\ge4$`, r`$x\ne1$`, r`$x\ge7$`, r`$y\le2$`, r`all reals`, r`$y\ge0$`, r`domain $x\ge1$, range $y\ge2$`],
  },
  {
    code: "1.3", unit: U, title: "Inverse Functions",
    intro: r`The inverse $f^{-1}$ undoes $f$: swap $x$ and $y$, then solve. Its graph reflects over $y=x$.`,
    ideas: [r`Swap $x$ and $y$, solve for $y$.`, r`Domain and range swap.`, r`The inverse is a function only if $f$ is one-to-one.`],
    examples: [
      { t: "Linear inverse", body: r`Inverse of $f(x)=2x+3$?\soln Write $y=2x+3$, swap: $x=2y+3$, solve: $y=\dfrac{x-3}{2}$. \\ Each graph is the mirror image of the other across $y=x$:` + r`\eplot{-6}{6}{-6}{6}{\addplot[exblue,very thick,domain=-4:1.5]{2*x+3};\addplot[qorange,very thick,domain=-6:6]{(x-3)/2};\addplot[gray,dashed,domain=-6:6]{x};}` },
      { t: "Linear inverse", body: r`Inverse of $f(x)=3x-6$?\soln Swap and solve: $x=3y-6\Rightarrow y=\dfrac{x+6}{3}$.` },
      { t: "Not a function", body: r`Is the inverse of $f(x)=x^2$ a function?\soln Swapping gives $y=\pm\sqrt{x}$, which fails the vertical-line test. \\ No, unless the domain of $f$ is restricted.` },
      { t: "Check", body: r`Verify $f^{-1}$ for $f(x)=2x$.\soln $f^{-1}(x)=\tfrac{x}{2}$, so $f(f^{-1}(x))=2\cdot\tfrac{x}{2}=x$. \checkmark` },
      { t: "Swap domain/range", body: r`If $f$ has domain $x\ge0$, range $y\ge2$, what is the domain of $f^{-1}$?\soln Domain and range swap, so $f^{-1}$ has domain $x\ge2$.` },
      { t: "Linear inverse", body: r`Inverse of $f(x)=4x-8$?\soln $x=4y-8\Rightarrow y=\dfrac{x+8}{4}$.` },
      { t: "Linear inverse", body: r`Inverse of $f(x)=\dfrac{x}{2}+1$?\soln $x=\dfrac{y}{2}+1\Rightarrow y=2(x-1)=2x-2$.` },
      { t: "Linear inverse", body: r`Inverse of $f(x)=5x$?\soln $x=5y\Rightarrow y=\dfrac{x}{5}$.` },
      { t: "Reflection line", body: r`An inverse reflects in which line?\soln The line $y=x$.` },
    ],
    questions: [
      { ask: r`Find the inverse of $f(x)=4x-8$.` },
      { ask: r`Find the inverse of $f(x)=\dfrac{x}{2}+1$.` },
      { ask: r`Is the inverse of $f(x)=x^2$ (all reals) a function?` },
      { ask: r`An inverse is a reflection in which line?` },
      { ask: r`Find the inverse of $f(x)=5x$.` },
      { ask: r`Find the inverse of $f(x)=2x+3$.` },
      { ask: r`Find the inverse of $f(x)=3x-6$.` },
      { ask: r`Compute $f(f^{-1}(x))$ for $f(x)=2x$.` },
      { ask: r`Find the inverse of $f(x)=x-7$.` },
      { ask: r`Find the inverse of $f(x)=-x+4$.` },
      { ask: r`Find the inverse of $f(x)=\dfrac{x}{4}$.` },
      { ask: r`If $f$ has domain $x\ge0$, range $y\ge1$, state the domain of $f^{-1}$.` },
      { ask: r`Find the inverse of $f(x)=\dfrac{x+2}{3}$.`, challenge: true, ws: "2.6cm" },
    ],
    answers: [r`$\dfrac{x+8}{4}$`, r`$2x-2$`, r`no`, r`$y=x$`, r`$\dfrac{x}{5}$`, r`$\dfrac{x-3}{2}$`, r`$\dfrac{x+6}{3}$`, r`$x$`, r`$x+7$`, r`$4-x$`, r`$4x$`, r`$x\ge1$`, r`$3x-2$`],
  },
  {
    code: "1.4", unit: U, title: "Transformations of Functions",
    intro: r`Every transformed function has the form $g(x)=a\,f\big(k(x-d)\big)+c$.`,
    ideas: [r`$a$: vertical stretch/reflection. $c$: vertical shift.`, r`$d$: horizontal shift (opposite to the sign inside).`, r`Apply stretches/reflections first, then translations.`],
    examples: [
      { t: "Full description", body: r`Describe $y=-2(x-3)^2+1$ from $y=x^2$.\soln $a=-2$: reflect and stretch by 2. $d=3$: right 3. $c=1$: up 1. Vertex $(3,1)$, opens down:` + r`\eplot{-1}{7}{-8}{3}{\addplot[exblue,very thick,domain=0.7:5.3]{-2*(x-3)^2+1};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(3,1)};}` },
      { t: "Radical", body: r`Describe $y=\sqrt{x+4}-2$.\soln $d=-4$: left 4. $c=-2$: down 2.` },
      { t: "Reflection", body: r`Describe $y=-x^2$.\soln $a=-1$: a reflection in the $x$-axis (opens down).` },
      { t: "Stretch", body: r`Describe $y=3x^2$.\soln $a=3$: a vertical stretch by 3.` },
      { t: "Vertex from form", body: r`Vertex of $y=(x+1)^2-5$?\soln $h=-1$, $k=-5$: vertex $(-1,-5)$.` },
      { t: "Description", body: r`Describe $y=(x-2)^2+3$.\soln Right 2, up 3.` },
      { t: "Radical", body: r`Describe $y=\sqrt{x}-4$.\soln Down 4.` },
      { t: "Vertex", body: r`Vertex of $y=-(x-4)^2+2$?\soln $(4,2)$; $a<0$ so it opens down.` },
      { t: "Stretch + shift", body: r`Describe $y=2(x+1)^2$.\soln Stretch by 2, left 1.` },
    ],
    questions: [
      { ask: r`Describe $y=(x-2)^2+3$.` },
      { ask: r`Describe $y=\sqrt{x}-4$.` },
      { ask: r`State the vertex of $y=-(x-4)^2+2$.` },
      { ask: r`What does $a=-1$ do?` },
      { ask: r`Describe $y=2(x+1)^2$.` },
      { ask: r`State the vertex of $y=(x+1)^2-5$.` },
      { ask: r`Describe $y=-2(x-3)^2+1$.` },
      { ask: r`Write $y=x^2$ shifted right $4$ and down $2$.` },
      { ask: r`Describe $y=\sqrt{x+4}-2$.` },
      { ask: r`Does $y=-3(x+2)^2+4$ open up or down?` },
      { ask: r`State the vertex of $y=(x-5)^2+2$.` },
      { ask: r`What does $(x-3)$ inside do?` },
      { ask: r`Describe $y=-(x+1)^2+5$ fully.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`right $2$, up $3$`, r`down $4$`, r`$(4,2)$`, r`reflects in the $x$-axis`, r`stretch $2$, left $1$`, r`$(-1,-5)$`, r`stretch $2$, reflect, right $3$, up $1$`, r`$y=(x-4)^2-2$`, r`left $4$, down $2$`, r`down`, r`$(5,2)$`, r`shifts right $3$`, r`reflect in $x$-axis, left $1$, up $5$; vertex $(-1,5)$`],
  },
  {
    code: "1.5", unit: U, title: "Quadratic Functions: Zeros, Max & Min",
    intro: r`Vertex form $a(x-h)^2+k$ shows the vertex $(h,k)$; complete the square to find it.`,
    ideas: [r`Vertex is the max ($a<0$) or min ($a>0$).`, r`Zeros are where the parabola crosses the $x$-axis.`, r`Axis of symmetry: $x=h$.`],
    examples: [
      { t: "Complete the square", body: r`Vertex form of $x^2-6x+5$.\soln Half of $-6$ is $-3$; $(-3)^2=9$: $x^2-6x+9-9+5=(x-3)^2-4$. \\ Vertex $(3,-4)$; zeros $1$ and $5$:` + r`\eplot{-1}{7}{-6}{8}{\addplot[exblue,very thick,domain=-0.5:6.5]{x^2-6*x+5};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(1,0) (5,0) (3,-4)};}` },
      { t: "Minimum", body: r`Minimum of $x^2-6x+5$?\soln From $(x-3)^2-4$, the minimum value is $-4$.` },
      { t: "Zeros", body: r`Zeros of $x^2-6x+5$?\soln Factor $(x-1)(x-5)=0\Rightarrow x=1,5$.` },
      { t: "Another vertex", body: r`Vertex of $x^2+4x+1$?\soln $x^2+4x+4-4+1=(x+2)^2-3$; vertex $(-2,-3)$.` },
      { t: "Axis of symmetry", body: r`Axis of symmetry of $x^2-6x+5$?\soln It passes through the vertex: $x=3$.` },
      { t: "Vertex form given", body: r`Vertex of $y=(x-3)^2-4$?\soln Read off $(h,k)=(3,-4)$.` },
      { t: "Complete the square", body: r`Complete the square: $x^2+6x+5$.\soln Half of $6$ is $3$: $(x+3)^2-9+5=(x+3)^2-4$.` },
      { t: "Minimum", body: r`Minimum of $x^2-2x+5$?\soln $(x-1)^2-1+5=(x-1)^2+4$; minimum $4$.` },
      { t: "Maximum", body: r`Max of $y=-x^2+4$?\soln Opens down, vertex $(0,4)$: maximum $4$.` },
    ],
    questions: [
      { ask: r`State the vertex of $y=(x-5)^2+2$.` },
      { ask: r`Complete the square: $x^2+8x+10$.` },
      { ask: r`Find the minimum of $y=x^2-2x+5$.` },
      { ask: r`Does $y=-x^2+4$ have a max or min, and its value?` },
      { ask: r`Find the zeros of $y=x^2-9$.` },
      { ask: r`State the vertex of $x^2-6x+5$.` },
      { ask: r`State the axis of symmetry of $x^2-6x+5$.` },
      { ask: r`Find the zeros of $x^2-6x+5$.` },
      { ask: r`State the vertex of $x^2+4x+1$.` },
      { ask: r`Complete the square: $x^2-10x$.` },
      { ask: r`Find the minimum of $x^2+4x+7$.` },
      { ask: r`State the vertex of $y=-(x-2)^2+3$.` },
      { ask: r`Find the vertex, axis, min, and zeros of $x^2-4x+3$.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$(5,2)$`, r`$(x+4)^2-6$`, r`$4$`, r`max, $4$`, r`$\pm3$`, r`$(3,-4)$`, r`$x=3$`, r`$1,5$`, r`$(-2,-3)$`, r`$(x-5)^2-25$`, r`$3$`, r`$(2,3)$`, r`vertex $(2,-1)$, axis $x=2$, min $-1$, zeros $1,3$`],
  },
  {
    code: "1.6", unit: U, title: "Solving Quadratics & Linear-Quadratic Systems",
    intro: r`Solve quadratics by factoring or the formula $x=\dfrac{-b\pm\sqrt{b^2-4ac}}{2a}$.`,
    ideas: [r`Try factoring first; use the formula when it won't factor.`, r`Discriminant $b^2-4ac$: $>0$ two roots, $=0$ one, $<0$ none.`, r`A linear-quadratic system: set the expressions equal.`],
    examples: [
      { t: "Factor", body: r`Solve $x^2-5x+6=0$.\soln $(x-2)(x-3)=0\Rightarrow x=2$ or $x=3$.` },
      { t: "System", body: r`Where do $y=x^2-2$ and $y=x$ meet?\soln Set equal: $x^2-2=x\Rightarrow x^2-x-2=0\Rightarrow(x-2)(x+1)=0$. \\ $x=2,-1$, giving $(2,2)$ and $(-1,-1)$:` + r`\eplot{-3}{4}{-3}{6}{\addplot[exblue,very thick,domain=-2.5:3]{x^2-2};\addplot[qorange,very thick,domain=-3:4]{x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(2,2) (-1,-1)};}` },
      { t: "Factor", body: r`Solve $x^2+2x-8=0$.\soln $(x+4)(x-2)=0\Rightarrow x=-4,2$.` },
      { t: "Quadratic formula", body: r`Solve $x^2-4x+1=0$.\soln $x=\dfrac{4\pm\sqrt{16-4}}{2}=\dfrac{4\pm\sqrt{12}}{2}=2\pm\sqrt3$.` },
      { t: "Discriminant", body: r`How many real solutions has $x^2+x+1=0$?\soln $b^2-4ac=1-4=-3<0$: no real solutions.` },
      { t: "Factor", body: r`Solve $x^2-7x+10=0$.\soln $(x-2)(x-5)=0\Rightarrow x=2,5$.` },
      { t: "Factor", body: r`Solve $x^2-x-6=0$.\soln $(x-3)(x+2)=0\Rightarrow x=3,-2$.` },
      { t: "System", body: r`Where do $y=x^2$ and $y=x+2$ meet?\soln $x^2=x+2\Rightarrow x^2-x-2=0\Rightarrow(x-2)(x+1)=0$. \\ Points $(2,4)$ and $(-1,1)$:` + r`\eplot{-3}{4}{-2}{8}{\addplot[exblue,very thick,domain=-2.5:3]{x^2};\addplot[qorange,very thick,domain=-3:4]{x+2};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(2,4) (-1,1)};}` },
      { t: "Quadratic formula", body: r`Solve $x^2-2x-1=0$.\soln $x=\dfrac{2\pm\sqrt{4+4}}{2}=\dfrac{2\pm2\sqrt2}{2}=1\pm\sqrt2$.` },
    ],
    questions: [
      { ask: r`Solve $x^2-7x+10=0$.` },
      { ask: r`Solve $x^2-x-6=0$.` },
      { ask: r`Where do $y=x^2$ and $y=x+2$ meet?` },
      { ask: r`Solve $x^2-2x-1=0$ (quadratic formula).` },
      { ask: r`Solve $x^2+2x-15=0$.` },
      { ask: r`Solve $x^2-5x+6=0$.` },
      { ask: r`Solve $x^2-16=0$.` },
      { ask: r`How many real solutions has $x^2-6x+9=0$?` },
      { ask: r`Solve $x^2+5x+6=0$.` },
      { ask: r`Where do $y=x^2-2$ and $y=x$ meet?` },
      { ask: r`Solve $x^2-3x=0$.` },
      { ask: r`How many real solutions has $x^2+x+1=0$?` },
      { ask: r`Solve $2x^2-5x-3=0$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$x=2,5$`, r`$x=3,-2$`, r`$(2,4),(-1,1)$`, r`$1\pm\sqrt2$`, r`$x=-5,3$`, r`$x=2,3$`, r`$x=\pm4$`, r`one ($x=3$)`, r`$x=-2,-3$`, r`$(2,2),(-1,-1)$`, r`$x=0,3$`, r`none`, r`$x=-\tfrac12,3$`],
  },
];
