// MCR3U Unit 2 worksheets — Equivalent Algebraic Expressions.
// Examples: full step-by-step solutions; selected parabola graphs (\eplot).
const r = String.raw;
const U = "2: Equivalent Algebraic Expressions";

export default [
  {
    code: "2.1", unit: U, title: "Adding & Multiplying Polynomials",
    intro: "Polynomials are built from terms. Simplifying means collecting like terms and expanding products.",
    ideas: [
      r`Only \textbf{like terms} (same variable and exponent) can be combined.`,
      r`Distributive property: $a(b+c)=ab+ac$.`,
      r`FOIL for binomials: $(a+b)(c+d)=ac+ad+bc+bd$.`,
      r`Special products: $(a\pm b)^2=a^2\pm2ab+b^2$ and $(a+b)(a-b)=a^2-b^2$.`,
    ],
    examples: [
      { t: "Collect like terms", body: r`Simplify $5x-3+2x-8$.\soln Group like terms: $(5x+2x)+(-3-8)$. \\ $=7x-11$.` },
      { t: "Distribute", body: r`Expand $4(2x-3)$.\soln Multiply each term by 4: $4\cdot2x-4\cdot3=8x-12$.` },
      { t: "Distribute then collect", body: r`Simplify $2(x+3)+3(x-1)$.\soln Expand: $2x+6+3x-3$. \\ Collect: $5x+3$.` },
      { t: "Monomial times polynomial", body: r`Expand $3x(x^2-2x+4)$.\soln Distribute $3x$: $3x^3-6x^2+12x$.` },
      { t: "FOIL", body: r`Expand $(x+2)(x+5)$.\soln First, Outer, Inner, Last: $x^2+5x+2x+10$. \\ Collect: $x^2+7x+10$ — a parabola with x-intercepts $-2,-5$:` + r`\eplot{-7}{2}{-3}{8}{\addplot[exblue,very thick,domain=-6.2:0.8]{x^2+7*x+10};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-2,0) (-5,0)};}` },
      { t: "FOIL with a negative", body: r`Expand $(x-4)(x+3)$.\soln $x^2+3x-4x-12$. \\ Collect: $x^2-x-12$.` },
      { t: "Perfect square", body: r`Expand $(x+5)^2$.\soln $(x+5)(x+5)=x^2+2(5)x+25=x^2+10x+25$.` },
      { t: "Difference of squares", body: r`Expand $(x-6)(x+6)$.\soln The middle terms cancel: $x^2-36$.` },
      { t: "Combine products", body: r`Expand and simplify $(2x-1)(x+3)-(x^2-2)$.\soln Expand: $(2x^2+5x-3)-(x^2-2)$. \\ Distribute the minus: $2x^2+5x-3-x^2+2=x^2+5x-1$.` },
    ],
    questions: [
      { ask: r`Simplify $5x-3+2x-8$.` },
      { ask: r`Expand $-2(3x-4)$.` },
      { ask: r`Simplify $3(x+2)-4(x-1)$.` },
      { ask: r`Expand $2x(4x^2-x+3)$.` },
      { ask: r`Expand $(x+7)(x+2)$.` },
      { ask: r`Expand $(x-5)(x+4)$.` },
      { ask: r`Expand $(3x+2)(x-1)$.` },
      { ask: r`Expand $(x-3)^2$.` },
      { ask: r`Expand $(2x+5)^2$.` },
      { ask: r`Expand $(x-8)(x+8)$.` },
      { ask: r`Expand and simplify $(x+4)(x-2)+(x+1)^2$.`, ws: "3cm" },
      { ask: r`A rectangle has length $(2x+1)$ and width $(x+5)$. Write its area as a polynomial.`, ws: "3cm" },
      { ask: r`Expand $(x+2)(x^2-3x+1)$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$7x-11$`, r`$-6x+8$`, r`$-x+10$`, r`$8x^3-2x^2+6x$`, r`$x^2+9x+14$`, r`$x^2-x-20$`, r`$3x^2-x-2$`, r`$x^2-6x+9$`, r`$4x^2+20x+25$`, r`$x^2-64$`, r`$2x^2+4x-7$`, r`$2x^2+11x+5$`, r`$x^3-x^2-5x+2$`],
  },
  {
    code: "2.2", unit: U, title: "Factoring Polynomials",
    intro: "Factoring is expansion in reverse: rewrite a sum as a product.",
    ideas: [
      r`Always remove a \textbf{common factor} first.`,
      r`$x^2+bx+c$: find two numbers that multiply to $c$ and add to $b$.`,
      r`$ax^2+bx+c$: decomposition (split the middle term, then group).`,
      r`Patterns: $a^2-b^2=(a+b)(a-b)$ and $a^2\pm2ab+b^2=(a\pm b)^2$.`,
    ],
    examples: [
      { t: "Common factor", body: r`Factor $6x+9$.\soln The GCF is $3$: $3(2x+3)$.` },
      { t: "Common factor with a variable", body: r`Factor $4x^2-8x$.\soln The GCF is $4x$: $4x(x-2)$.` },
      { t: "Simple trinomial", body: r`Factor $x^2+8x+15$.\soln Two numbers with product $15$, sum $8$: $3$ and $5$. \\ $(x+3)(x+5)$ — the factors are the x-intercepts $-3,-5$:` + r`\eplot{-7}{1}{-3}{8}{\addplot[exblue,very thick,domain=-6.2:0.2]{x^2+8*x+15};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-3,0) (-5,0)};}` },
      { t: "Negative constant", body: r`Factor $x^2-5x-14$.\soln Product $-14$, sum $-5$: $-7$ and $2$. \\ $(x-7)(x+2)$.` },
      { t: "Negative middle", body: r`Factor $x^2-9x+20$.\soln Product $20$, sum $-9$: $-4$ and $-5$. \\ $(x-4)(x-5)$.` },
      { t: "Complex trinomial", body: r`Factor $2x^2+7x+3$.\soln $ac=6$; split $7x=6x+x$: $2x^2+6x+x+3$. \\ Group: $2x(x+3)+1(x+3)=(x+3)(2x+1)$.` },
      { t: "Complex trinomial", body: r`Factor $3x^2-10x-8$.\soln $ac=-24$; split $-12x+2x$: $3x^2-12x+2x-8$. \\ Group: $3x(x-4)+2(x-4)=(3x+2)(x-4)$.` },
      { t: "Difference of squares", body: r`Factor $25x^2-16$.\soln $(5x)^2-(4)^2=(5x-4)(5x+4)$.` },
      { t: "Factor fully", body: r`Factor $2x^2-50$.\soln Common factor 2: $2(x^2-25)$. \\ Difference of squares: $2(x-5)(x+5)$.` },
    ],
    questions: [
      { ask: r`Factor $10x-15$.` },
      { ask: r`Factor $6x^2+9x$.` },
      { ask: r`Factor $x^2+6x+8$.` },
      { ask: r`Factor $x^2+2x-15$.` },
      { ask: r`Factor $x^2-7x+10$.` },
      { ask: r`Factor $x^2-x-20$.` },
      { ask: r`Factor $2x^2+5x+2$.` },
      { ask: r`Factor $3x^2+8x+4$.` },
      { ask: r`Factor $x^2-49$.` },
      { ask: r`Factor $9x^2-1$.` },
      { ask: r`Factor $x^2-12x+36$.` },
      { ask: r`Factor fully $5x^2-20$.`, ws: "3cm" },
      { ask: r`Factor $6x^2-x-2$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$5(2x-3)$`, r`$3x(2x+3)$`, r`$(x+2)(x+4)$`, r`$(x+5)(x-3)$`, r`$(x-2)(x-5)$`, r`$(x-5)(x+4)$`, r`$(2x+1)(x+2)$`, r`$(3x+2)(x+2)$`, r`$(x-7)(x+7)$`, r`$(3x-1)(3x+1)$`, r`$(x-6)^2$`, r`$5(x-2)(x+2)$`, r`$(3x-2)(2x+1)$`],
  },
  {
    code: "2.3", unit: U, title: "Simplifying Rational Expressions",
    intro: "Treat algebraic fractions like number fractions: factor, cancel common factors, and state restrictions.",
    ideas: [
      r`Factor numerator and denominator, then cancel common \textbf{factors} (never terms in a sum).`,
      r`State restrictions: any value making an original denominator $0$.`,
      r`Multiply: cancel across, then multiply. Divide: multiply by the reciprocal.`,
    ],
    examples: [
      { t: "Cancel a monomial", body: r`Simplify $\dfrac{3x^2}{6x}$.\soln Divide coefficients and subtract exponents: $\dfrac{3}{6}x^{2-1}=\dfrac{x}{2},\ x\ne0$.` },
      { t: "Difference of squares", body: r`Simplify $\dfrac{x^2-9}{x-3}$.\soln Factor the top: $\dfrac{(x-3)(x+3)}{x-3}$. \\ Cancel $(x-3)$: $x+3,\ x\ne3$.` },
      { t: "Trinomial over binomial", body: r`Simplify $\dfrac{x^2+5x+6}{x+2}$.\soln $\dfrac{(x+2)(x+3)}{x+2}=x+3,\ x\ne-2$.` },
      { t: "Trinomial over trinomial", body: r`Simplify $\dfrac{x^2-x-6}{x^2-9}$.\soln Factor both: $\dfrac{(x-3)(x+2)}{(x-3)(x+3)}$. \\ Cancel $(x-3)$: $\dfrac{x+2}{x+3},\ x\ne\pm3$.` },
      { t: "Common factor", body: r`Simplify $\dfrac{2x+4}{x^2+2x}$.\soln $\dfrac{2(x+2)}{x(x+2)}=\dfrac{2}{x},\ x\ne0,-2$.` },
      { t: "Multiply", body: r`Simplify $\dfrac{x^2-4}{x}\cdot\dfrac{3}{x+2}$.\soln Factor and cancel across: $\dfrac{(x-2)(x+2)}{x}\cdot\dfrac{3}{x+2}=\dfrac{3(x-2)}{x},\ x\ne0,-2$.` },
      { t: "Multiply to 1", body: r`Simplify $\dfrac{x+1}{x-2}\cdot\dfrac{x-2}{x+1}$.\soln Everything cancels: $1,\ x\ne2,-1$.` },
      { t: "Divide", body: r`Simplify $\dfrac{x}{x+3}\div\dfrac{x^2}{x+3}$.\soln Multiply by the reciprocal: $\dfrac{x}{x+3}\cdot\dfrac{x+3}{x^2}=\dfrac{1}{x},\ x\ne-3,0$.` },
      { t: "Divide with factoring", body: r`Simplify $\dfrac{x^2-1}{x}\div\dfrac{x+1}{x}$.\soln $\dfrac{x^2-1}{x}\cdot\dfrac{x}{x+1}=\dfrac{(x-1)(x+1)}{x+1}=x-1,\ x\ne0,-1$.` },
    ],
    questions: [
      { ask: r`Simplify $\dfrac{4x^3}{8x}$ and state restrictions.` },
      { ask: r`Simplify $\dfrac{x^2-25}{x+5}$.` },
      { ask: r`Simplify $\dfrac{x^2+7x+12}{x+3}$.` },
      { ask: r`Simplify $\dfrac{x^2-4}{x^2-2x}$.` },
      { ask: r`Simplify $\dfrac{3x+12}{x^2+4x}$.` },
      { ask: r`Simplify $\dfrac{x^2-x-6}{x^2-9}$.` },
      { ask: r`Simplify $\dfrac{x^2-1}{x+2}\cdot\dfrac{x+2}{x-1}$.` },
      { ask: r`Simplify $\dfrac{x+3}{x}\cdot\dfrac{2x}{x+3}$.` },
      { ask: r`Simplify $\dfrac{x+2}{x-1}\div\dfrac{x+2}{x}$.` },
      { ask: r`Simplify $\dfrac{x^2}{x-4}\div\dfrac{x}{x-4}$.` },
      { ask: r`Simplify $\dfrac{2x^2-8}{x^2-4}$.`, ws: "3cm" },
      { ask: r`State the restrictions for $\dfrac{x+1}{x^2-x-6}$.` },
      { ask: r`Simplify $\dfrac{x^2-4}{x+3}\cdot\dfrac{x^2+6x+9}{x-2}$.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$\dfrac{x^2}{2},\ x\ne0$`, r`$x-5,\ x\ne-5$`, r`$x+4,\ x\ne-3$`, r`$\dfrac{x+2}{x},\ x\ne0,2$`, r`$\dfrac{3}{x},\ x\ne0,-4$`, r`$\dfrac{x+2}{x+3},\ x\ne\pm3$`, r`$x+1,\ x\ne-2,1$`, r`$2,\ x\ne0,-3$`, r`$\dfrac{x}{x-1},\ x\ne0,1,-2$`, r`$x,\ x\ne0,4$`, r`$2,\ x\ne\pm2$`, r`$x\ne3,-2$`, r`$(x+2)(x+3),\ x\ne-3,2$`],
  },
  {
    code: "2.4", unit: U, title: "Adding & Subtracting Rational Expressions",
    intro: "Find a common denominator, combine the numerators, then simplify and state restrictions.",
    ideas: [
      r`Factor denominators to find the \textbf{lowest common denominator (LCD)}.`,
      r`Rewrite each fraction over the LCD, then add/subtract numerators.`,
      r`When subtracting, bracket the whole numerator: $-(2x-1)=-2x+1$.`,
    ],
    examples: [
      { t: "Like denominators", body: r`Simplify $\dfrac{2}{x}+\dfrac{5}{x}$.\soln Same denominator — add the tops: $\dfrac{2+5}{x}=\dfrac{7}{x},\ x\ne0$.` },
      { t: "Numeric denominators", body: r`Simplify $\dfrac{x}{3}+\dfrac{x}{4}$.\soln LCD $=12$: $\dfrac{4x}{12}+\dfrac{3x}{12}=\dfrac{7x}{12}$.` },
      { t: "Subtract like denominators", body: r`Simplify $\dfrac{7}{x}-\dfrac{3}{x}$.\soln $\dfrac{7-3}{x}=\dfrac{4}{x},\ x\ne0$.` },
      { t: "Constant plus variable", body: r`Simplify $\dfrac{1}{2}+\dfrac{1}{x}$.\soln LCD $=2x$: $\dfrac{x}{2x}+\dfrac{2}{2x}=\dfrac{x+2}{2x},\ x\ne0$.` },
      { t: "Different variable denominators", body: r`Simplify $\dfrac{2}{x}+\dfrac{3}{x+1}$.\soln LCD $=x(x+1)$: $\dfrac{2(x+1)+3x}{x(x+1)}=\dfrac{5x+2}{x(x+1)},\ x\ne0,-1$.` },
      { t: "Subtraction", body: r`Simplify $\dfrac{x+3}{x}-\dfrac{2}{x}$.\soln $\dfrac{(x+3)-2}{x}=\dfrac{x+1}{x},\ x\ne0$.` },
      { t: "Subtraction to a constant", body: r`Simplify $\dfrac{3x+1}{x-2}-\dfrac{x+5}{x-2}$.\soln $\dfrac{(3x+1)-(x+5)}{x-2}=\dfrac{2x-4}{x-2}=\dfrac{2(x-2)}{x-2}=2,\ x\ne2$.` },
      { t: "Factor for the LCD", body: r`Simplify $\dfrac{1}{x-2}+\dfrac{1}{x^2-4}$.\soln $x^2-4=(x-2)(x+2)$, so LCD $=(x-2)(x+2)$: $\dfrac{(x+2)+1}{(x-2)(x+2)}=\dfrac{x+3}{(x-2)(x+2)},\ x\ne\pm2$.` },
      { t: "Two binomial denominators", body: r`Simplify $\dfrac{3}{x+1}-\dfrac{2}{x-1}$.\soln $\dfrac{3(x-1)-2(x+1)}{(x+1)(x-1)}=\dfrac{3x-3-2x-2}{(x+1)(x-1)}=\dfrac{x-5}{(x+1)(x-1)},\ x\ne\pm1$.` },
    ],
    questions: [
      { ask: r`Simplify $\dfrac{4}{x}+\dfrac{1}{x}$.` },
      { ask: r`Simplify $\dfrac{9}{x}-\dfrac{2}{x}$.` },
      { ask: r`Simplify $\dfrac{x}{2}+\dfrac{x}{5}$.` },
      { ask: r`Simplify $\dfrac{x}{4}-\dfrac{x}{6}$.` },
      { ask: r`Simplify $\dfrac{1}{3}+\dfrac{1}{x}$.` },
      { ask: r`Simplify $\dfrac{2}{x}+\dfrac{1}{x+2}$.`, ws: "3cm" },
      { ask: r`Simplify $\dfrac{5}{x-1}+\dfrac{3}{x-1}$.` },
      { ask: r`Simplify $\dfrac{2x+3}{x+4}-\dfrac{x-1}{x+4}$.` },
      { ask: r`Simplify $\dfrac{3}{x}-\dfrac{2}{x-3}$.`, ws: "3cm" },
      { ask: r`Simplify $\dfrac{1}{x+2}+\dfrac{1}{x^2-4}$.`, ws: "3cm" },
      { ask: r`Simplify $\dfrac{4}{x-1}-\dfrac{2}{x+1}$.`, ws: "3cm" },
      { ask: r`State the LCD of $\dfrac{1}{x+3}$ and $\dfrac{1}{x^2-9}$.` },
      { ask: r`Simplify $\dfrac{1}{x^2-x}+\dfrac{1}{x^2-1}$.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$\dfrac{5}{x},\ x\ne0$`, r`$\dfrac{7}{x},\ x\ne0$`, r`$\dfrac{7x}{10}$`, r`$\dfrac{x}{12}$`, r`$\dfrac{x+3}{3x},\ x\ne0$`, r`$\dfrac{3x+4}{x(x+2)},\ x\ne0,-2$`, r`$\dfrac{8}{x-1},\ x\ne1$`, r`$1,\ x\ne-4$`, r`$\dfrac{x-9}{x(x-3)},\ x\ne0,3$`, r`$\dfrac{x-1}{(x-2)(x+2)},\ x\ne\pm2$`, r`$\dfrac{2x+6}{(x-1)(x+1)},\ x\ne\pm1$`, r`$(x-3)(x+3)$`, r`$\dfrac{2x+1}{x(x-1)(x+1)},\ x\ne0,\pm1$`],
  },
  {
    code: "2.5", unit: U, title: "Radicals & Equivalent Expressions",
    intro: "Simplify radicals with the largest perfect-square factor, then add like radicals and multiply with the distributive property.",
    ideas: [
      r`$\sqrt{ab}=\sqrt{a}\cdot\sqrt{b}$; pull out the largest perfect square.`,
      r`Only \textbf{like radicals} (same value under the root) can be added or subtracted.`,
      r`Conjugates: $(a+\sqrt{b})(a-\sqrt{b})=a^2-b$.`,
    ],
    examples: [
      { t: "Simplify", body: r`Simplify $\sqrt{50}$.\soln Largest perfect-square factor: $\sqrt{25\cdot2}=\sqrt{25}\cdot\sqrt2=5\sqrt{2}$.` },
      { t: "Simplify", body: r`Simplify $\sqrt{72}$.\soln $\sqrt{36\cdot2}=6\sqrt{2}$.` },
      { t: "Add like radicals", body: r`Simplify $\sqrt{12}+\sqrt{27}$.\soln Simplify each: $2\sqrt{3}+3\sqrt{3}$. \\ Add like radicals: $5\sqrt{3}$.` },
      { t: "Subtract", body: r`Simplify $5\sqrt{2}-\sqrt{8}$.\soln $\sqrt8=2\sqrt2$, so $5\sqrt{2}-2\sqrt{2}=3\sqrt{2}$.` },
      { t: "Multiply roots", body: r`Simplify $\sqrt{3}\cdot\sqrt{6}$.\soln $\sqrt{18}=\sqrt{9\cdot2}=3\sqrt{2}$.` },
      { t: "Distribute", body: r`Simplify $\sqrt{2}(\sqrt{10}+\sqrt{2})$.\soln $\sqrt{20}+\sqrt4=2\sqrt{5}+2$.` },
      { t: "Square a radical", body: r`Evaluate $(2\sqrt{3})^2$.\soln $2^2\cdot(\sqrt3)^2=4\cdot3=12$.` },
      { t: "Conjugates", body: r`Expand $(3+\sqrt{2})(3-\sqrt{2})$.\soln Difference of squares: $9-2=7$.` },
      { t: "Verify equivalence", body: r`Is $\sqrt{8}+\sqrt{18}=5\sqrt{2}$?\soln $2\sqrt{2}+3\sqrt{2}=5\sqrt{2}$ — yes.` },
    ],
    questions: [
      { ask: r`Simplify $\sqrt{8}$.` },
      { ask: r`Simplify $\sqrt{45}$.` },
      { ask: r`Simplify $\sqrt{200}$.` },
      { ask: r`Simplify $\sqrt{18}+\sqrt{2}$.` },
      { ask: r`Simplify $2\sqrt{5}+\sqrt{20}$.` },
      { ask: r`Simplify $\sqrt{48}-\sqrt{12}$.` },
      { ask: r`Simplify $\sqrt{3}\cdot\sqrt{12}$.` },
      { ask: r`Simplify $\sqrt{2}(\sqrt{8}+\sqrt{2})$.`, ws: "3cm" },
      { ask: r`Evaluate $(\sqrt{6})^2$.` },
      { ask: r`Expand $(1+\sqrt{3})(1-\sqrt{3})$.` },
      { ask: r`Expand $(4+\sqrt{5})(4-\sqrt{5})$.` },
      { ask: r`Simplify $\sqrt{27}+\sqrt{75}-\sqrt{12}$.`, ws: "3cm" },
      { ask: r`Expand $(2+\sqrt{3})^2$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$2\sqrt{2}$`, r`$3\sqrt{5}$`, r`$10\sqrt{2}$`, r`$4\sqrt{2}$`, r`$4\sqrt{5}$`, r`$2\sqrt{3}$`, r`$6$`, r`$6$`, r`$6$`, r`$-2$`, r`$11$`, r`$6\sqrt{3}$`, r`$7+4\sqrt{3}$`],
  },
];
