// MCR3U Unit 2 worksheets — Equivalent Algebraic Expressions.
// Examples: full step-by-step solutions; selected parabola graphs (\eplot).
const r = String.raw;
const U = "2: Equivalent Algebraic Expressions";

export default [
  {
    code: "2.1", unit: U, title: "Adding & Multiplying Polynomials",
    intro: "Polynomials are built from terms. Simplifying means collecting like terms and expanding products.",
    ideas: [
      r`Only \textbf{like terms} (same variable and exponent) can be combined.`,
      r`Distributive property: $a(b+c)=ab+ac$.`,
      r`FOIL for binomials: $(a+b)(c+d)=ac+ad+bc+bd$.`,
      r`Special products: $(a\pm b)^2=a^2\pm2ab+b^2$ and $(a+b)(a-b)=a^2-b^2$.`,
    ],
    examples: [
      { t: "Collect like terms", body: r`Simplify $5x-3+2x-8$.\soln Group like terms: $(5x+2x)+(-3-8)$. \\ $=7x-11$.` },
      { t: "Distribute", body: r`Expand $4(2x-3)$.\soln Multiply each term by 4: $4\cdot2x-4\cdot3=8x-12$.` },
      { t: "Distribute then collect", body: r`Simplify $2(x+3)+3(x-1)$.\soln Expand: $2x+6+3x-3$. \\ Collect: $5x+3$.` },
      { t: "Monomial times polynomial", body: r`Expand $3x(x^2-2x+4)$.\soln Distribute $3x$: $3x^3-6x^2+12x$.` },
      { t: "FOIL", body: r`Expand $(x+2)(x+5)$.\soln First, Outer, Inner, Last: $x^2+5x+2x+10$. \\ Collect: $x^2+7x+10$ — a parabola with x-intercepts $-2,-5$:` + r`\eplot{-7}{2}{-3}{8}{\addplot[exblue,very thick,domain=-6.2:0.8]{x^2+7*x+10};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-2,0) (-5,0)};}` },
      { t: "FOIL with a negative", body: r`Expand $(x-4)(x+3)$.\soln $x^2+3x-4x-12$. \\ Collect: $x^2-x-12$.` },
      { t: "Perfect square", body: r`Expand $(x+5)^2$.\soln $(x+5)(x+5)=x^2+2(5)x+25=x^2+10x+25$.` },
      { t: "Difference of squares", body: r`Expand $(x-6)(x+6)$.\soln The middle terms cancel: $x^2-36$.` },
      { t: "Combine products", body: r`Expand and simplify $(2x-1)(x+3)-(x^2-2)$.\soln Expand: $(2x^2+5x-3)-(x^2-2)$. \\ Distribute the minus: $2x^2+5x-3-x^2+2=x^2+5x-1$.` },
    ],
    questions: [
      { ask: r`Simplify $5x-3+2x-8$.` },
      { ask: r`Expand $-2(3x-4)$.` },
      { ask: r`Simplify $3(x+2)-4(x-1)$.` },
      { ask: r`Expand $2x(4x^2-x+3)$.` },
      { ask: r`Expand $(x+7)(x+2)$.` },
      { ask: r`Expand $(x-5)(x+4)$.` },
      { ask: r`Expand $(3x+2)(x-1)$.` },
      { ask: r`Expand $(x-3)^2$.` },
      { ask: r`Expand $(2x+5)^2$.` },
      { ask: r`Expand $(x-8)(x+8)$.` },
      { ask: r`Expand and simplify $(x+4)(x-2)+(x+1)^2$.`, ws: "3cm" },
      { ask: r`A rectangle has length $(2x+1)$ and width $(x+5)$. Write its area as a polynomial.`, ws: "3cm" },
      { ask: r`Expand $(x+2)(x^2-3x+1)$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$7x-11$`, r`$-6x+8$`, r`$-x+10$`, r`$8x^3-2x^2+6x$`, r`$x^2+9x+14$`, r`$x^2-x-20$`, r`$3x^2-x-2$`, r`$x^2-6x+9$`, r`$4x^2+20x+25$`, r`$x^2-64$`, r`$2x^2+4x-7$`, r`$2x^2+11x+5$`, r`$x^3-x^2-5x+2$`],
  },
  {
    code: "2.2", unit: U, title: "Factoring Polynomials",
    intro: "Factoring is expansion in reverse: rewrite a sum as a product. Run one decision order every time, and always check by expanding.",
    ideas: [
      r`\textbf{Order:} common factor first $\rightarrow$ count the terms $\rightarrow$ factor again if a bracket still factors $\rightarrow$ check by expanding.`,
      r`$x^2+bx+c$: find two numbers that \textbf{multiply to $c$} and \textbf{add to $b$}.`,
      r`$ax^2+bx+c$ with $a\neq1$: find two numbers that \textbf{multiply to $ac$} and \textbf{add to $b$}, split the middle term, then group.`,
      r`Patterns: $a^2-b^2=(a+b)(a-b)$ and $a^2\pm2ab+b^2=(a\pm b)^2$. A sum of squares does not factor.`,
      r`If no pair of factors of $ac$ adds to $b$, the trinomial is \textbf{prime}.`,
    ],
    examples: [
      { t: "Common factor, then check the bracket", body: r`Factor fully $18x^3-24x^2+6x$.\soln \textbf{Step 1 --- the GCF.} $\gcd(18,24,6)=6$ and the lowest power of $x$ is $x^1$, so the GCF is $6x$. \\ \textbf{Step 2 --- divide each term:} $\tfrac{18x^3}{6x}=3x^2,\ \tfrac{-24x^2}{6x}=-4x,\ \tfrac{6x}{6x}=1$, so $6x(3x^2-4x+1)$. \\ \textbf{Step 3 --- look inside the bracket.} $3x^2-4x+1$ has $ac=3$; the pair $-1,-3$ multiplies to $3$ and adds to $-4$: $3x^2-3x-x+1=3x(x-1)-1(x-1)=(3x-1)(x-1)$. \\ \textbf{Check:} $6x(3x-1)(x-1)=6x(3x^2-4x+1)=18x^3-24x^2+6x$. \\ \textbf{Answer:} $6x(3x-1)(x-1)$.` },
      { t: "Trinomial with $a=1$", body: r`Factor $x^2+3x-28$.\soln \textbf{Need:} product $-28$, sum $+3$. One number is positive, one negative, and the larger one is positive.` + "\n" + r`\begin{center}\small\begin{tabular}{|l|c|c|c|}\hline Pair (product $-28$) & $-1,28$ & $-2,14$ & $-4,7$ \\ \hline Sum & $27$ & $12$ & $\mathbf{3}$ \\ \hline\end{tabular}\end{center}` + "\n" + r`The pair is $-4$ and $7$: $(x+7)(x-4)$. \\ \textbf{Check:} $x^2-4x+7x-28=x^2+3x-28$.` },
      { t: "$a\\neq1$: the five steps", body: r`Factor $3x^2+10x+8$.\soln \textbf{1. Clear the way:} no common factor. \\ \textbf{2. Find $ac$:} $3\times8=24$. \\ \textbf{3. Find the pair:} product $24$, sum $10$, all positive: $1,24\ (25)$; $2,12\ (14)$; $3,8\ (11)$; $\mathbf{4,6\ (10)}$. \\ \textbf{4. Split:} $3x^2+4x+6x+8$. \\ \textbf{5. Group:} $x(3x+4)+2(3x+4)$. Both groups give the same bracket, which confirms the split. $=(x+2)(3x+4)$. \\ \textbf{Check:} $(x+2)(3x+4)=3x^2+4x+6x+8=3x^2+10x+8$.` },
      { t: "$a\\neq1$: a negative middle term", body: r`Factor $5x^2-13x+6$.\soln \textbf{Find $ac$:} $30$. Product $+30$ and sum $-13$ means both numbers are \emph{negative}: $-1,-30\ (-31)$; $-2,-15\ (-17)$; $\mathbf{-3,-10\ (-13)}$. \\ \textbf{Split:} $5x^2-10x-3x+6$. \\ \textbf{Group:} $5x(x-2)-3(x-2)$. \emph{Sign trap:} the second group $-3x+6$ is written $-3(x-2)$, factoring out the $-3$ so the bracket matches. $=(5x-3)(x-2)$. \\ \textbf{Check:} $5x^2-10x-3x+6=5x^2-13x+6$.` },
      { t: "$a\\neq1$: a negative constant", body: r`Factor $4x^2+4x-15$.\soln \textbf{Find $ac$:} $4\times(-15)=-60$. Need product $-60$, sum $+4$: the larger number is positive, so look for two factors of $60$ whose \emph{difference} is $4$.` + "\n" + r`\begin{center}\small\begin{tabular}{|l|c|c|c|c|c|c|}\hline Factors of $60$ & $1,60$ & $2,30$ & $3,20$ & $4,15$ & $5,12$ & $6,10$ \\ \hline Difference & $59$ & $28$ & $17$ & $11$ & $7$ & $\mathbf{4}$ \\ \hline\end{tabular}\end{center}` + "\n" + r`The numbers are $+10$ and $-6$. \textbf{Split:} $4x^2+10x-6x-15$. \textbf{Group:} $2x(2x+5)-3(2x+5)=(2x-3)(2x+5)$. \\ \textbf{Check:} $4x^2+10x-6x-15=4x^2+4x-15$.` },
      { t: "Common factor first, then $a\\neq1$", body: r`Factor fully $18x^2+3x-6$.\soln \textbf{GCF:} all coefficients are multiples of $3$: $3(6x^2+x-2)$. \emph{This keeps $ac$ small:} $-12$ instead of $-108$. \\ \textbf{Inside:} $ac=6\times(-2)=-12$; product $-12$, sum $+1$: $1,12\ (11)$; $2,6\ (4)$; $\mathbf{3,4\ (1)}$, so $+4$ and $-3$. \\ \textbf{Split and group:} $6x^2+4x-3x-2=2x(3x+2)-1(3x+2)=(2x-1)(3x+2)$. \\ \textbf{Put the GCF back:} $3(2x-1)(3x+2)$. \\ \textbf{Check:} $(2x-1)(3x+2)=6x^2+x-2$, and $3(6x^2+x-2)=18x^2+3x-6$.` },
      { t: "A prime trinomial", body: r`Can $2x^2-3x+5$ be factored over the integers?\soln $ac=10$. Product $+10$, sum $-3$, so both numbers would be negative. \\ All pairs: $-1,-10\ (-11)$; $-2,-5\ (-7)$. \\ Neither sum is $-3$, so the trinomial is \textbf{prime} --- it cannot be factored over the integers. Listing \emph{every} pair is what proves it.` },
      { t: "Difference of squares and perfect square", body: r`Factor \textbf{(a)} $49x^2-36$ and \textbf{(b)} $16x^2+24x+9$.\soln \textbf{(a)} Two terms, subtracted, both squares: $(7x)^2-6^2=(7x+6)(7x-6)$. \\ \textbf{(b)} $16x^2=(4x)^2$, $9=3^2$, and $2(4x)(3)=24x$ matches the middle term, so it is a perfect square: $(4x+3)^2$. \\ \textbf{Check (b):} $(4x+3)^2=16x^2+24x+9$. (Decomposition agrees: $ac=144$, pair $12,12$.)` },
      { t: "A negative leading coefficient", body: r`Factor $-6x^2+x+15$.\soln \textbf{Step 1 --- make $a$ positive:} factor out $-1$: $-(6x^2-x-15)$. \\ \textbf{Step 2:} $ac=6\times(-15)=-90$; product $-90$, sum $-1$ (larger number negative): $1,90\ (89)$; $2,45\ (43)$; $3,30\ (27)$; $5,18\ (13)$; $6,15\ (9)$; $\mathbf{9,10\ (1)}$, so $-10$ and $+9$. \\ \textbf{Step 3:} $6x^2-10x+9x-15=2x(3x-5)+3(3x-5)=(2x+3)(3x-5)$. \\ \textbf{Step 4 --- restore the $-1$:} $-(2x+3)(3x-5)$. \\ \textbf{Check:} $(2x+3)(3x-5)=6x^2-x-15$, and its negative is $-6x^2+x+15$.` },
    ],
    questions: [
      { ask: r`Factor $15x^2-25x$.`, ws: "2.2cm" },
      { ask: r`Factor fully $14x^3+21x^2$.`, ws: "2.2cm" },
      { ask: r`Factor $x^2+11x+24$.`, ws: "2.6cm" },
      { ask: r`Factor $x^2-2x-35$. List the factor pairs of $35$ in a table.`, ws: "2.6cm" },
      { ask: r`Factor $2x^2+9x+10$. Show $ac$, the pair, the split and the grouping, then check.`, ws: "3.3cm" },
      { ask: r`Factor $7x^2-16x+4$. (Both numbers will be negative --- why?)`, ws: "3.3cm" },
      { ask: r`Factor $3x^2+x-10$. List the factor pairs of $ac$ to find the right pair.`, ws: "3.3cm" },
      { ask: r`Factor $6x^2-17x+5$. Watch the sign when you group.`, ws: "3.3cm" },
      { ask: r`Factor fully $20x^2+30x-20$.`, ws: "3.6cm" },
      { ask: r`Decide whether $4x^2+3x+2$ can be factored over the integers. Justify your answer.`, ws: "2.6cm" },
      { ask: r`Factor $64x^2-1$.`, ws: "2.2cm" },
      { ask: r`Factor $25x^2+20x+4$ and explain how you recognised the pattern.`, ws: "2.6cm" },
      { ask: r`Factor fully $24x^2-10x-4$, and check your answer by expanding.`, challenge: true, ws: "4.2cm" },
    ],
    answers: [
      r`$5x(3x-5)$`,
      r`$7x^2(2x+3)$`,
      r`$(x+3)(x+8)$`,
      r`$(x-7)(x+5)$; product $-35$, sum $-2$: pairs $1,-35$ and $5,-7$ (sum $-2$)`,
      r`$(2x+5)(x+2)$; $ac=20$, pair $4,5$: $2x^2+4x+5x+10=2x(x+2)+5(x+2)$`,
      r`$(7x-2)(x-2)$; $ac=28$, pair $-14,-2$ (product positive, sum negative): $7x^2-14x-2x+4=7x(x-2)-2(x-2)$`,
      r`$(3x-5)(x+2)$; $ac=-30$, pair $6,-5$: $3x^2+6x-5x-10=3x(x+2)-5(x+2)$`,
      r`$(3x-1)(2x-5)$; $ac=30$, pair $-15,-2$: $6x^2-15x-2x+5=3x(2x-5)-1(2x-5)$`,
      r`$10(2x-1)(x+2)$; GCF $10$, then $2x^2+3x-2$: $ac=-4$, pair $4,-1$: $2x^2+4x-x-2=2x(x+2)-1(x+2)$`,
      r`prime: $ac=8$, pairs $1,8\ (9)$ and $2,4\ (6)$; neither sums to $3$`,
      r`$(8x-1)(8x+1)$`,
      r`$(5x+2)^2$; $(5x)^2$, $2^2$, and $2(5x)(2)=20x$ matches the middle term`,
      r`$2(4x+1)(3x-2)$; GCF $2$, then $12x^2-5x-2$: $ac=-24$, pair $-8,3$: $12x^2-8x+3x-2=4x(3x-2)+1(3x-2)$; check $(4x+1)(3x-2)=12x^2-5x-2$`,
    ],
  },
  {
    code: "2.3", unit: U, title: "Simplifying Rational Expressions",
    intro: "Treat algebraic fractions like number fractions: factor, cancel common factors, and state restrictions.",
    ideas: [
      r`Factor numerator and denominator, then cancel common \textbf{factors} (never terms in a sum).`,
      r`State restrictions: any value making an original denominator $0$.`,
      r`Multiply: cancel across, then multiply. Divide: multiply by the reciprocal.`,
    ],
    examples: [
      { t: "Cancel a monomial", body: r`Simplify $\dfrac{3x^2}{6x}$.\soln Divide coefficients and subtract exponents: $\dfrac{3}{6}x^{2-1}=\dfrac{x}{2},\ x\ne0$.` },
      { t: "Difference of squares", body: r`Simplify $\dfrac{x^2-9}{x-3}$.\soln Factor the top: $\dfrac{(x-3)(x+3)}{x-3}$. \\ Cancel $(x-3)$: $x+3,\ x\ne3$.` },
      { t: "Trinomial over binomial", body: r`Simplify $\dfrac{x^2+5x+6}{x+2}$.\soln $\dfrac{(x+2)(x+3)}{x+2}=x+3,\ x\ne-2$.` },
      { t: "Trinomial over trinomial", body: r`Simplify $\dfrac{x^2-x-6}{x^2-9}$.\soln Factor both: $\dfrac{(x-3)(x+2)}{(x-3)(x+3)}$. \\ Cancel $(x-3)$: $\dfrac{x+2}{x+3},\ x\ne\pm3$.` },
      { t: "Common factor", body: r`Simplify $\dfrac{2x+4}{x^2+2x}$.\soln $\dfrac{2(x+2)}{x(x+2)}=\dfrac{2}{x},\ x\ne0,-2$.` },
      { t: "Multiply", body: r`Simplify $\dfrac{x^2-4}{x}\cdot\dfrac{3}{x+2}$.\soln Factor and cancel across: $\dfrac{(x-2)(x+2)}{x}\cdot\dfrac{3}{x+2}=\dfrac{3(x-2)}{x},\ x\ne0,-2$.` },
      { t: "Multiply to 1", body: r`Simplify $\dfrac{x+1}{x-2}\cdot\dfrac{x-2}{x+1}$.\soln Everything cancels: $1,\ x\ne2,-1$.` },
      { t: "Divide", body: r`Simplify $\dfrac{x}{x+3}\div\dfrac{x^2}{x+3}$.\soln Multiply by the reciprocal: $\dfrac{x}{x+3}\cdot\dfrac{x+3}{x^2}=\dfrac{1}{x},\ x\ne-3,0$.` },
      { t: "Divide with factoring", body: r`Simplify $\dfrac{x^2-1}{x}\div\dfrac{x+1}{x}$.\soln $\dfrac{x^2-1}{x}\cdot\dfrac{x}{x+1}=\dfrac{(x-1)(x+1)}{x+1}=x-1,\ x\ne0,-1$.` },
    ],
    questions: [
      { ask: r`Simplify $\dfrac{4x^3}{8x}$ and state restrictions.` },
      { ask: r`Simplify $\dfrac{x^2-25}{x+5}$.` },
      { ask: r`Simplify $\dfrac{x^2+7x+12}{x+3}$.` },
      { ask: r`Simplify $\dfrac{x^2-4}{x^2-2x}$.` },
      { ask: r`Simplify $\dfrac{3x+12}{x^2+4x}$.` },
      { ask: r`Simplify $\dfrac{x^2-x-6}{x^2-9}$.` },
      { ask: r`Simplify $\dfrac{x^2-1}{x+2}\cdot\dfrac{x+2}{x-1}$.` },
      { ask: r`Simplify $\dfrac{x+3}{x}\cdot\dfrac{2x}{x+3}$.` },
      { ask: r`Simplify $\dfrac{x+2}{x-1}\div\dfrac{x+2}{x}$.` },
      { ask: r`Simplify $\dfrac{x^2}{x-4}\div\dfrac{x}{x-4}$.` },
      { ask: r`Simplify $\dfrac{2x^2-8}{x^2-4}$.`, ws: "3cm" },
      { ask: r`State the restrictions for $\dfrac{x+1}{x^2-x-6}$.` },
      { ask: r`Simplify $\dfrac{x^2-4}{x+3}\cdot\dfrac{x^2+6x+9}{x-2}$.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$\dfrac{x^2}{2},\ x\ne0$`, r`$x-5,\ x\ne-5$`, r`$x+4,\ x\ne-3$`, r`$\dfrac{x+2}{x},\ x\ne0,2$`, r`$\dfrac{3}{x},\ x\ne0,-4$`, r`$\dfrac{x+2}{x+3},\ x\ne\pm3$`, r`$x+1,\ x\ne-2,1$`, r`$2,\ x\ne0,-3$`, r`$\dfrac{x}{x-1},\ x\ne0,1,-2$`, r`$x,\ x\ne0,4$`, r`$2,\ x\ne\pm2$`, r`$x\ne3,-2$`, r`$(x+2)(x+3),\ x\ne-3,2$`],
  },
  {
    code: "2.4", unit: U, title: "Adding & Subtracting Rational Expressions",
    intro: "Find a common denominator, combine the numerators, then simplify and state restrictions.",
    ideas: [
      r`Factor denominators to find the \textbf{lowest common denominator (LCD)}.`,
      r`Rewrite each fraction over the LCD, then add/subtract numerators.`,
      r`When subtracting, bracket the whole numerator: $-(2x-1)=-2x+1$.`,
    ],
    examples: [
      { t: "Like denominators", body: r`Simplify $\dfrac{2}{x}+\dfrac{5}{x}$.\soln Same denominator — add the tops: $\dfrac{2+5}{x}=\dfrac{7}{x},\ x\ne0$.` },
      { t: "Numeric denominators", body: r`Simplify $\dfrac{x}{3}+\dfrac{x}{4}$.\soln LCD $=12$: $\dfrac{4x}{12}+\dfrac{3x}{12}=\dfrac{7x}{12}$.` },
      { t: "Subtract like denominators", body: r`Simplify $\dfrac{7}{x}-\dfrac{3}{x}$.\soln $\dfrac{7-3}{x}=\dfrac{4}{x},\ x\ne0$.` },
      { t: "Constant plus variable", body: r`Simplify $\dfrac{1}{2}+\dfrac{1}{x}$.\soln LCD $=2x$: $\dfrac{x}{2x}+\dfrac{2}{2x}=\dfrac{x+2}{2x},\ x\ne0$.` },
      { t: "Different variable denominators", body: r`Simplify $\dfrac{2}{x}+\dfrac{3}{x+1}$.\soln LCD $=x(x+1)$: $\dfrac{2(x+1)+3x}{x(x+1)}=\dfrac{5x+2}{x(x+1)},\ x\ne0,-1$.` },
      { t: "Subtraction", body: r`Simplify $\dfrac{x+3}{x}-\dfrac{2}{x}$.\soln $\dfrac{(x+3)-2}{x}=\dfrac{x+1}{x},\ x\ne0$.` },
      { t: "Subtraction to a constant", body: r`Simplify $\dfrac{3x+1}{x-2}-\dfrac{x+5}{x-2}$.\soln $\dfrac{(3x+1)-(x+5)}{x-2}=\dfrac{2x-4}{x-2}=\dfrac{2(x-2)}{x-2}=2,\ x\ne2$.` },
      { t: "Factor for the LCD", body: r`Simplify $\dfrac{1}{x-2}+\dfrac{1}{x^2-4}$.\soln $x^2-4=(x-2)(x+2)$, so LCD $=(x-2)(x+2)$: $\dfrac{(x+2)+1}{(x-2)(x+2)}=\dfrac{x+3}{(x-2)(x+2)},\ x\ne\pm2$.` },
      { t: "Two binomial denominators", body: r`Simplify $\dfrac{3}{x+1}-\dfrac{2}{x-1}$.\soln $\dfrac{3(x-1)-2(x+1)}{(x+1)(x-1)}=\dfrac{3x-3-2x-2}{(x+1)(x-1)}=\dfrac{x-5}{(x+1)(x-1)},\ x\ne\pm1$.` },
    ],
    questions: [
      { ask: r`Simplify $\dfrac{4}{x}+\dfrac{1}{x}$.` },
      { ask: r`Simplify $\dfrac{9}{x}-\dfrac{2}{x}$.` },
      { ask: r`Simplify $\dfrac{x}{2}+\dfrac{x}{5}$.` },
      { ask: r`Simplify $\dfrac{x}{4}-\dfrac{x}{6}$.` },
      { ask: r`Simplify $\dfrac{1}{3}+\dfrac{1}{x}$.` },
      { ask: r`Simplify $\dfrac{2}{x}+\dfrac{1}{x+2}$.`, ws: "3cm" },
      { ask: r`Simplify $\dfrac{5}{x-1}+\dfrac{3}{x-1}$.` },
      { ask: r`Simplify $\dfrac{2x+3}{x+4}-\dfrac{x-1}{x+4}$.` },
      { ask: r`Simplify $\dfrac{3}{x}-\dfrac{2}{x-3}$.`, ws: "3cm" },
      { ask: r`Simplify $\dfrac{1}{x+2}+\dfrac{1}{x^2-4}$.`, ws: "3cm" },
      { ask: r`Simplify $\dfrac{4}{x-1}-\dfrac{2}{x+1}$.`, ws: "3cm" },
      { ask: r`State the LCD of $\dfrac{1}{x+3}$ and $\dfrac{1}{x^2-9}$.` },
      { ask: r`Simplify $\dfrac{1}{x^2-x}+\dfrac{1}{x^2-1}$.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$\dfrac{5}{x},\ x\ne0$`, r`$\dfrac{7}{x},\ x\ne0$`, r`$\dfrac{7x}{10}$`, r`$\dfrac{x}{12}$`, r`$\dfrac{x+3}{3x},\ x\ne0$`, r`$\dfrac{3x+4}{x(x+2)},\ x\ne0,-2$`, r`$\dfrac{8}{x-1},\ x\ne1$`, r`$1,\ x\ne-4$`, r`$\dfrac{x-9}{x(x-3)},\ x\ne0,3$`, r`$\dfrac{x-1}{(x-2)(x+2)},\ x\ne\pm2$`, r`$\dfrac{2x+6}{(x-1)(x+1)},\ x\ne\pm1$`, r`$(x-3)(x+3)$`, r`$\dfrac{2x+1}{x(x-1)(x+1)},\ x\ne0,\pm1$`],
  },
  {
    code: "2.5", unit: U, title: "Radicals & Equivalent Expressions",
    intro: "Simplify radicals with the largest perfect-square factor, then add like radicals and multiply with the distributive property.",
    ideas: [
      r`$\sqrt{ab}=\sqrt{a}\cdot\sqrt{b}$; pull out the largest perfect square.`,
      r`Only \textbf{like radicals} (same value under the root) can be added or subtracted.`,
      r`Conjugates: $(a+\sqrt{b})(a-\sqrt{b})=a^2-b$.`,
    ],
    examples: [
      { t: "Simplify", body: r`Simplify $\sqrt{50}$.\soln Largest perfect-square factor: $\sqrt{25\cdot2}=\sqrt{25}\cdot\sqrt2=5\sqrt{2}$.` },
      { t: "Simplify", body: r`Simplify $\sqrt{72}$.\soln $\sqrt{36\cdot2}=6\sqrt{2}$.` },
      { t: "Add like radicals", body: r`Simplify $\sqrt{12}+\sqrt{27}$.\soln Simplify each: $2\sqrt{3}+3\sqrt{3}$. \\ Add like radicals: $5\sqrt{3}$.` },
      { t: "Subtract", body: r`Simplify $5\sqrt{2}-\sqrt{8}$.\soln $\sqrt8=2\sqrt2$, so $5\sqrt{2}-2\sqrt{2}=3\sqrt{2}$.` },
      { t: "Multiply roots", body: r`Simplify $\sqrt{3}\cdot\sqrt{6}$.\soln $\sqrt{18}=\sqrt{9\cdot2}=3\sqrt{2}$.` },
      { t: "Distribute", body: r`Simplify $\sqrt{2}(\sqrt{10}+\sqrt{2})$.\soln $\sqrt{20}+\sqrt4=2\sqrt{5}+2$.` },
      { t: "Square a radical", body: r`Evaluate $(2\sqrt{3})^2$.\soln $2^2\cdot(\sqrt3)^2=4\cdot3=12$.` },
      { t: "Conjugates", body: r`Expand $(3+\sqrt{2})(3-\sqrt{2})$.\soln Difference of squares: $9-2=7$.` },
      { t: "Verify equivalence", body: r`Is $\sqrt{8}+\sqrt{18}=5\sqrt{2}$?\soln $2\sqrt{2}+3\sqrt{2}=5\sqrt{2}$ — yes.` },
    ],
    questions: [
      { ask: r`Simplify $\sqrt{8}$.` },
      { ask: r`Simplify $\sqrt{45}$.` },
      { ask: r`Simplify $\sqrt{200}$.` },
      { ask: r`Simplify $\sqrt{18}+\sqrt{2}$.` },
      { ask: r`Simplify $2\sqrt{5}+\sqrt{20}$.` },
      { ask: r`Simplify $\sqrt{48}-\sqrt{12}$.` },
      { ask: r`Simplify $\sqrt{3}\cdot\sqrt{12}$.` },
      { ask: r`Simplify $\sqrt{2}(\sqrt{8}+\sqrt{2})$.`, ws: "3cm" },
      { ask: r`Evaluate $(\sqrt{6})^2$.` },
      { ask: r`Expand $(1+\sqrt{3})(1-\sqrt{3})$.` },
      { ask: r`Expand $(4+\sqrt{5})(4-\sqrt{5})$.` },
      { ask: r`Simplify $\sqrt{27}+\sqrt{75}-\sqrt{12}$.`, ws: "3cm" },
      { ask: r`Expand $(2+\sqrt{3})^2$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$2\sqrt{2}$`, r`$3\sqrt{5}$`, r`$10\sqrt{2}$`, r`$4\sqrt{2}$`, r`$4\sqrt{5}$`, r`$2\sqrt{3}$`, r`$6$`, r`$6$`, r`$6$`, r`$-2$`, r`$11$`, r`$6\sqrt{3}$`, r`$7+4\sqrt{3}$`],
  },
];
