// MCR3U Unit 3 worksheets — Exponential Functions.
// Examples: full step-by-step solutions with TikZ exponential curves (\eplot).
const r = String.raw;
const U = "3: Exponential Functions";

export default [
  {
    code: "3.1", unit: U, title: "Exponent Laws & Rational Exponents",
    intro: "The exponent laws let you simplify powers, including negative and fractional exponents.",
    ideas: [
      r`Product $x^m x^n=x^{m+n}$; Quotient $\dfrac{x^m}{x^n}=x^{m-n}$; Power $(x^m)^n=x^{mn}$.`,
      r`$x^0=1$ and $x^{-n}=\dfrac{1}{x^n}$.`,
      r`$x^{1/n}=\sqrt[n]{x}$ and $x^{m/n}=\sqrt[n]{x^m}$.`,
    ],
    examples: [
      { t: "Product", body: r`Simplify $x^3\cdot x^6$.\soln Add the exponents: $x^{3+6}=x^{9}$.` },
      { t: "Power of a power", body: r`Simplify $(x^5)^2$.\soln Multiply the exponents: $x^{5\cdot2}=x^{10}$.` },
      { t: "Quotient", body: r`Simplify $\dfrac{x^8}{x^3}$.\soln Subtract the exponents: $x^{8-3}=x^{5}$.` },
      { t: "Power of a product", body: r`Simplify $(2x^3)^2$.\soln The exponent reaches both factors: $2^2 x^{6}=4x^{6}$.` },
      { t: "Zero exponent", body: r`Evaluate $4^0$.\soln Any non-zero base to the power $0$ is $1$.` },
      { t: "Negative exponent", body: r`Evaluate $2^{-4}$.\soln Reciprocal: $\dfrac{1}{2^4}=\dfrac{1}{16}$.` },
      { t: "Square root power", body: r`Evaluate $25^{1/2}$.\soln $25^{1/2}=\sqrt{25}=5$.` },
      { t: "Cube root power", body: r`Evaluate $8^{1/3}$.\soln $8^{1/3}=\sqrt[3]{8}=2$.` },
      { t: "Rational exponent", body: r`Evaluate $16^{3/4}$.\soln Root first, then power: $(\sqrt[4]{16})^3=2^3=8$.` },
    ],
    questions: [
      { ask: r`Simplify $x^2\cdot x^7$.` },
      { ask: r`Simplify $(x^4)^3$.` },
      { ask: r`Simplify $\dfrac{y^9}{y^5}$.` },
      { ask: r`Simplify $(3x^2)^3$.` },
      { ask: r`Evaluate $5^0$.` },
      { ask: r`Evaluate $3^{-2}$.` },
      { ask: r`Evaluate $100^{1/2}$.` },
      { ask: r`Evaluate $27^{1/3}$.` },
      { ask: r`Evaluate $32^{2/5}$.` },
      { ask: r`Simplify $(2x^3y)^2$.` },
      { ask: r`Simplify $x^{-3}\cdot x^{7}$.` },
      { ask: r`Simplify $\left(\dfrac{x^6}{x^2}\right)^2$.`, ws: "3cm" },
      { ask: r`Simplify $(8x^6)^{2/3}$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$x^9$`, r`$x^{12}$`, r`$y^4$`, r`$27x^6$`, r`$1$`, r`$\dfrac{1}{9}$`, r`$10$`, r`$3$`, r`$4$`, r`$4x^6y^2$`, r`$x^4$`, r`$x^8$`, r`$4x^4$`],
  },
  {
    code: "3.2", unit: U, title: "Exponential Functions & Their Graphs",
    intro: "Exponential functions $y=a\\,b^{x}$ grow or decay depending on the base.",
    ideas: [
      r`Growth if $b>1$; decay if $0<b<1$.`,
      r`$y$-intercept is $a$; horizontal asymptote $y=0$.`,
      r`Domain: all real numbers; range: $y>0$ (for $a>0$).`,
    ],
    examples: [
      { t: "Growth or decay", body: r`Classify $y=2\cdot3^{x}$.\soln The base $b=3>1$, so it is growth — the curve rises steeply (shape of $3^x$):` + r`\eplot{-3}{3}{-1}{9}{\addplot[exblue,very thick,domain=-3:2]{3^x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,1)};}` },
      { t: "Decay", body: r`Classify $y=(0.5)^{x}$.\soln The base is between 0 and 1, so it is decay — the curve falls toward $y=0$:` + r`\eplot{-3}{3}{-1}{9}{\addplot[exblue,very thick,domain=-3:3]{0.5^x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,1)};}` },
      { t: "y-intercept", body: r`Find the $y$-intercept of $y=5\cdot2^{x}$.\soln At $x=0$, $2^0=1$, so $y=5$.` },
      { t: "Evaluate", body: r`Evaluate $y=2^{x}$ at $x=4$.\soln $2^4=16$.` },
      { t: "Negative input", body: r`Evaluate $y=3^{x}$ at $x=-2$.\soln $3^{-2}=\dfrac{1}{9}$.` },
      { t: "Domain", body: r`State the domain of $y=2^{x}$.\soln Any $x$ works: all real numbers.` },
      { t: "Range", body: r`State the range of $y=2^{x}$.\soln Outputs stay positive: $y>0$.` },
      { t: "Compare", body: r`Which decays: $y=0.7^{x}$ or $y=4^{x}$?\soln $y=0.7^{x}$, because its base is $<1$.` },
      { t: "Write an equation", body: r`Write the exponential through $(0,3)$ with base $2$.\soln The $y$-intercept is $a=3$: $y=3\cdot2^{x}$.` },
    ],
    questions: [
      { ask: r`Growth or decay: $y=7^{x}$?` },
      { ask: r`Growth or decay: $y=(2/5)^{x}$?` },
      { ask: r`Find the $y$-intercept of $y=8\cdot3^{x}$.` },
      { ask: r`Evaluate $2^{x}$ at $x=7$.` },
      { ask: r`Evaluate $5^{x}$ at $x=-1$.` },
      { ask: r`State the asymptote of $y=2^{x}$.` },
      { ask: r`State the range of $y=4\cdot2^{x}$.` },
      { ask: r`State the domain of $y=10^{x}$.` },
      { ask: r`Write an exponential through $(0,6)$ with base $3$.` },
      { ask: r`Which is larger at $x=3$: $2^{x}$ or $3^{x}$?` },
      { ask: r`Evaluate $(1/2)^{x}$ at $x=3$.` },
      { ask: r`Find the $y$-intercept of $y=2\cdot5^{x}$.` },
      { ask: r`For $y=a\cdot2^{x}$ through $(0,5)$, find $a$ and then $y$ at $x=1$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`growth`, r`decay`, r`$8$`, r`$128$`, r`$\dfrac{1}{5}$`, r`$y=0$`, r`$y>0$`, r`all real numbers`, r`$y=6\cdot3^{x}$`, r`$3^{x}$ (27 vs 8)`, r`$\dfrac{1}{8}$`, r`$2$`, r`$a=5$, $y=10$`],
  },
  {
    code: "3.3", unit: U, title: "Transformations of Exponential Functions",
    intro: "Transform the parent $b^{x}$ with $y=a\\,b^{\\,k(x-d)}+c$; the shift $c$ moves the asymptote to $y=c$.",
    ideas: [
      r`$c$ shifts vertically and moves the asymptote to $y=c$.`,
      r`$d$ shifts horizontally; $a<0$ reflects in the $x$-axis.`,
      r`Domain stays all reals; range is $y>c$ (or $y<c$ if reflected).`,
    ],
    examples: [
      { t: "Vertical shift", body: r`Describe $y=2^{x}+3$.\soln The $+3$ lifts the graph up 3, so the asymptote moves to $y=3$ and the range is $y>3$:` + r`\eplot{-4}{3}{-1}{11}{\addplot[red,dashed,domain=-4:3]{3};\addplot[exblue,very thick,domain=-4:3]{2^x+3};}` },
      { t: "Horizontal shift", body: r`Describe $y=2^{x-2}$.\soln $(x-2)$ shifts the graph right 2.` },
      { t: "Reflection", body: r`Describe $y=-2^{x}$.\soln The leading $-$ reflects it in the $x$-axis, so the range becomes $y<0$:` + r`\eplot{-3}{3}{-9}{1}{\addplot[exblue,very thick,domain=-3:3]{-(2^x)};}` },
      { t: "Stretch", body: r`Describe $y=3\cdot2^{x}$.\soln A vertical stretch by 3; the $y$-intercept is $3$.` },
      { t: "Range from a shift", body: r`State the range of $y=2^{x}-5$.\soln Asymptote $y=-5$, so the range is $y>-5$.` },
      { t: "Left shift", body: r`Describe $y=2^{x+1}$.\soln $(x+1)$ shifts the graph left 1.` },
      { t: "Reflect in y-axis", body: r`Describe $y=2^{-x}$.\soln The $-x$ reflects it in the $y$-axis, turning growth into decay.` },
      { t: "Asymptote", body: r`State the asymptote of $y=5^{x}+2$.\soln The vertical shift $+2$ gives $y=2$.` },
      { t: "Range with reflection", body: r`State the range of $y=-3^{x}$.\soln Reflected below the axis: $y<0$.` },
    ],
    questions: [
      { ask: r`State the asymptote of $y=2^{x}+6$.` },
      { ask: r`Describe the shift in $y=3^{x-4}$.` },
      { ask: r`State the range of $y=2^{x}+2$.` },
      { ask: r`What does the negative do in $y=-4^{x}$?` },
      { ask: r`State the asymptote of $y=2^{x}-3$.` },
      { ask: r`Describe the shift in $y=2^{x+5}$.` },
      { ask: r`State the range of $y=2^{x}-1$.` },
      { ask: r`State the domain of $y=3^{x}+7$.` },
      { ask: r`Describe all transformations of $y=2^{x-1}+4$.`, ws: "3cm" },
      { ask: r`State the range of $y=-2^{x}$.` },
      { ask: r`Write $y=3^{x}$ shifted up $5$.` },
      { ask: r`Write $y=2^{x}$ shifted left $3$ and down $2$.` },
      { ask: r`State the asymptote, domain, and range of $y=-2^{x}+6$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$y=6$`, r`right $4$`, r`$y>2$`, r`reflects over the $x$-axis; range $y<0$`, r`$y=-3$`, r`left $5$`, r`$y>-1$`, r`all real numbers`, r`right $1$, up $4$ (asymptote $y=4$)`, r`$y<0$`, r`$y=3^{x}+5$`, r`$y=2^{x+3}-2$`, r`asymptote $y=6$, domain all reals, range $y<6$`],
  },
  {
    code: "3.4", unit: U, title: "Applications: Growth, Decay & Compound Interest",
    intro: "Exponential models describe anything multiplying by a fixed factor each period.",
    ideas: [
      r`Growth/decay: $A=A_0(1\pm r)^{t}$.`,
      r`Half-life / doubling: $A=A_0\left(\tfrac12\right)^{t/h}$ or $A_0\,(2)^{t/d}$.`,
      r`Compound interest: $A=P(1+i)^{n}$.`,
    ],
    examples: [
      { t: "Growth model", body: r`A town of $600$ grows $5\%$ per year.\soln Growth factor $1+0.05=1.05$: $P=600(1.05)^{t}$.` },
      { t: "Decay model", body: r`A $\$5000$ value falls $12\%$ per year.\soln Decay factor $1-0.12=0.88$: $V=5000(0.88)^{t}$.` },
      { t: "Compound interest", body: r`$\$1000$ at $8\%$ compounded annually for $3$ years.\soln $A=1000(1.08)^{3}=1000(1.259712)\approx\$1259.71$.` },
      { t: "Half-life", body: r`$40$ mg, half-life $10$ years; after $30$ years.\soln $30\div10=3$ half-lives: $40\left(\tfrac12\right)^{3}=40\cdot\tfrac18=5$ mg.` },
      { t: "Doubling", body: r`$50$ bacteria double every $2$ h; after $8$ h.\soln $8\div2=4$ doublings: $50\cdot2^{4}=50\cdot16=800$.` },
      { t: "Depreciation", body: r`A $\$30000$ asset drops $18\%$ per year; after $2$ years.\soln $30000(0.82)^{2}=30000(0.6724)\approx\$20172$.` },
      { t: "Population", body: r`$2000$ grows $3\%$ per year; after $5$ years.\soln $2000(1.03)^{5}\approx2000(1.159274)\approx2319$.` },
      { t: "Compound", body: r`$\$1500$ at $4\%$ compounded annually for $10$ years.\soln $1500(1.04)^{10}\approx\$2220.37$.` },
      { t: "Half-life amount", body: r`$200$ mg, half-life $4$ days; after $8$ days.\soln $8\div4=2$ half-lives: $200\left(\tfrac12\right)^{2}=50$ mg.` },
    ],
    questions: [
      { ask: r`Write the growth model: $900$ increasing $7\%$ per year.` },
      { ask: r`Write the decay model: $1500$ decreasing $10\%$ per year.` },
      { ask: r`$700$ grows $6\%$ per year; find the amount after $4$ years.`, ws: "3cm" },
      { ask: r`$\$2000$ at $5\%$ compounded annually for $3$ years; find the amount.`, ws: "3cm" },
      { ask: r`$80$ mg, half-life $5$ years; amount after $15$ years.` },
      { ask: r`$120$ bacteria double every $3$ h; count after $12$ h.` },
      { ask: r`A $\$28000$ car depreciates $15\%$ per year; value after $2$ years.`, ws: "3cm" },
      { ask: r`A population of $5000$ grows $2\%$ per year; after $6$ years.`, ws: "3cm" },
      { ask: r`$\$1000$ at $8\%$ compounded annually for $5$ years; find the amount.`, ws: "3cm" },
      { ask: r`$64$ mg, half-life $2$ days; amount after $10$ days.` },
      { ask: r`$\$3000$ invested at $6\%$ per year; amount after $4$ years.`, ws: "3cm" },
      { ask: r`Write a model for a quantity that halves every $6$ years, from $A_0$.` },
      { ask: r`$\$500$ at $6\%$ compounded monthly for $2$ years ($i=0.005$, $n=24$); find the amount.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$P=900(1.07)^{t}$`, r`$V=1500(0.90)^{t}$`, r`$\approx 883.78$`, r`$\approx \$2315.25$`, r`$10$ mg`, r`$1920$`, r`$\approx \$20230$`, r`$\approx 5631$`, r`$\approx \$1469.33$`, r`$2$ mg`, r`$\approx \$3787.43$`, r`$A=A_0\left(\tfrac12\right)^{t/6}$`, r`$\approx \$563.58$`],
  },
];
