// MCR3U Unit 4 worksheets — Trigonometric Functions.
// Examples: full step-by-step solutions with TikZ triangles (\rtri,\gtri) and sine curves (\splot).
const r = String.raw;
const U = "4: Trigonometric Functions";

export default [
  {
    code: "4.1", unit: U, title: "Trigonometric Ratios & Special Angles",
    intro: "Use SOH CAH TOA in right triangles and memorize the exact values of the special angles.",
    ideas: [
      r`$\sin\theta=\dfrac{\text{opp}}{\text{hyp}}$, $\cos\theta=\dfrac{\text{adj}}{\text{hyp}}$, $\tan\theta=\dfrac{\text{opp}}{\text{adj}}$.`,
      r`Special angles come from the $45^\circ$-$45^\circ$-$90^\circ$ ($1,1,\sqrt2$) and $30^\circ$-$60^\circ$-$90^\circ$ ($1,\sqrt3,2$) triangles.`,
      r`Set your calculator to DEGREE mode.`,
    ],
    examples: [
      { t: "Find a ratio", body: r`Opposite $3$, hypotenuse $5$. Find $\sin\theta$.\soln $\sin\theta=\dfrac{\text{opp}}{\text{hyp}}=\dfrac{3}{5}$.` + r`\rtri{4}{3}{$3$}{$4$}{$5$}` },
      { t: "Cosine", body: r`Adjacent $4$, hypotenuse $5$. Find $\cos\theta$.\soln $\cos\theta=\dfrac{\text{adj}}{\text{hyp}}=\dfrac{4}{5}$.` },
      { t: "Tangent", body: r`Opposite $3$, adjacent $4$. Find $\tan\theta$.\soln $\tan\theta=\dfrac{\text{opp}}{\text{adj}}=\dfrac{3}{4}$.` },
      { t: "Special angle", body: r`State $\sin30^\circ$.\soln From the $30$-$60$-$90$ triangle: $\dfrac12$.` },
      { t: "Special angle", body: r`State $\cos45^\circ$.\soln From the $45$-$45$-$90$ triangle: $\dfrac{\sqrt2}{2}$.` },
      { t: "Special angle", body: r`State $\tan60^\circ$.\soln $\dfrac{\sqrt3}{1}=\sqrt3$.` },
      { t: "Find a side", body: r`Hypotenuse $10$, angle $30^\circ$. Find the opposite side.\soln $\sin30^\circ=\dfrac{\text{opp}}{10}\Rightarrow\text{opp}=10\sin30^\circ=5$.` },
      { t: "Find a side", body: r`Hypotenuse $8$, angle $60^\circ$. Find the adjacent side.\soln $\cos60^\circ=\dfrac{\text{adj}}{8}\Rightarrow\text{adj}=8\cos60^\circ=4$.` },
      { t: "Find an angle", body: r`Opposite $5$, hypotenuse $10$. Find $\theta$.\soln $\sin\theta=\dfrac{5}{10}=\tfrac12\Rightarrow\theta=30^\circ$.` },
    ],
    questions: [
      { ask: r`State $\sin45^\circ$.` },
      { ask: r`State $\cos30^\circ$.` },
      { ask: r`State $\tan45^\circ$.` },
      { ask: r`State $\sin60^\circ$.` },
      { ask: r`State $\cos60^\circ$.` },
      { ask: r`State $\tan30^\circ$.` },
      { ask: r`Hypotenuse $12$, angle $30^\circ$: find the opposite side.` },
      { ask: r`Hypotenuse $10$, angle $60^\circ$: find the adjacent side.` },
      { ask: r`Opposite $6$, angle $30^\circ$: find the hypotenuse.` },
      { ask: r`Opposite $7$, adjacent $7$: find $\theta$.` },
      { ask: r`Opposite $1$, hypotenuse $2$: find $\theta$.` },
      { ask: r`Adjacent $5$, angle $45^\circ$: find the opposite side.` },
      { ask: r`A right triangle has legs $5$ and $12$. Find the smaller acute angle.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\tfrac{\sqrt2}{2}$`, r`$\tfrac{\sqrt3}{2}$`, r`$1$`, r`$\tfrac{\sqrt3}{2}$`, r`$\tfrac12$`, r`$\tfrac{1}{\sqrt3}$`, r`$6$`, r`$5$`, r`$12$`, r`$45^\circ$`, r`$30^\circ$`, r`$5$`, r`$\tan\theta=\tfrac{5}{12}\Rightarrow\theta\approx22.6^\circ$`],
  },
  {
    code: "4.2", unit: U, title: "Angles 0°–360° & the CAST Rule",
    intro: "Trig ratios take signs by quadrant (CAST), and most equations have two solutions in [0°, 360°].",
    ideas: [
      r`CAST (from Q4 counter-clockwise): Q1 all $+$, Q2 sin $+$, Q3 tan $+$, Q4 cos $+$.`,
      r`Reference angle: Q2 $180-\theta$, Q3 $\theta-180$, Q4 $360-\theta$.`,
      r`Find the ratio of the reference angle, then attach the CAST sign.`,
    ],
    examples: [
      { t: "Sign", body: r`Is $\sin150^\circ$ positive or negative?\soln $150^\circ$ is in Q2, where sine is positive.` },
      { t: "Sign", body: r`Is $\cos210^\circ$ positive or negative?\soln $210^\circ$ is in Q3, where only tangent is positive — so cosine is negative.` },
      { t: "Sign", body: r`Is $\tan300^\circ$ positive or negative?\soln $300^\circ$ is in Q4, where only cosine is positive — tangent is negative.` },
      { t: "Reference angle", body: r`Reference angle of $210^\circ$.\soln Q3: $\theta-180=210-180=30^\circ$.` },
      { t: "Reference angle", body: r`Reference angle of $300^\circ$.\soln Q4: $360-\theta=360-300=60^\circ$.` },
      { t: "Exact value", body: r`Evaluate $\cos120^\circ$.\soln Q2 (cos negative), reference $60^\circ$: $-\cos60^\circ=-\tfrac12$.` },
      { t: "Exact value", body: r`Evaluate $\sin240^\circ$.\soln Q3 (sin negative), reference $60^\circ$: $-\sin60^\circ=-\tfrac{\sqrt3}{2}$.` },
      { t: "Two solutions", body: r`Solve $\sin\theta=\tfrac12$ in $[0^\circ,360^\circ]$.\soln Sine is positive in Q1 and Q2; reference $30^\circ$. \\ $\theta=30^\circ$ and $180-30=150^\circ$:` + r`\splot{-1.5}{1.5}{\addplot[exblue,very thick,domain=0:360]{sin(x)};\addplot[qorange,dashed,domain=0:360]{0.5};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(30,0.5) (150,0.5)};}` },
      { t: "Two solutions", body: r`Solve $\cos\theta=-\tfrac{\sqrt3}{2}$.\soln Cosine is negative in Q2, Q3; reference $30^\circ$. \\ $\theta=150^\circ$ and $210^\circ$.` },
    ],
    questions: [
      { ask: r`Sign of $\sin300^\circ$?` },
      { ask: r`Sign of $\cos150^\circ$?` },
      { ask: r`Sign of $\tan120^\circ$?` },
      { ask: r`Reference angle of $135^\circ$?` },
      { ask: r`Reference angle of $225^\circ$?` },
      { ask: r`Evaluate $\cos240^\circ$.` },
      { ask: r`Evaluate $\sin150^\circ$.` },
      { ask: r`Evaluate $\tan225^\circ$.` },
      { ask: r`Solve $\cos\theta=\tfrac12$ in $[0^\circ,360^\circ]$.` },
      { ask: r`Solve $\sin\theta=-\tfrac12$ in $[0^\circ,360^\circ]$.` },
      { ask: r`Solve $\tan\theta=1$ in $[0^\circ,360^\circ]$.` },
      { ask: r`Evaluate $\sin270^\circ$.` },
      { ask: r`Solve $\cos\theta=-\tfrac12$ in $[0^\circ,360^\circ]$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`negative`, r`negative`, r`negative`, r`$45^\circ$`, r`$45^\circ$`, r`$-\tfrac12$`, r`$\tfrac12$`, r`$1$`, r`$60^\circ,300^\circ$`, r`$210^\circ,330^\circ$`, r`$45^\circ,225^\circ$`, r`$-1$`, r`$120^\circ,240^\circ$`],
  },
  {
    code: "4.3", unit: U, title: "Reciprocal Ratios & Trigonometric Identities",
    intro: "The reciprocal ratios and the Pythagorean and quotient identities let you simplify and prove.",
    ideas: [
      r`$\csc\theta=\dfrac{1}{\sin\theta}$, $\sec\theta=\dfrac{1}{\cos\theta}$, $\cot\theta=\dfrac{1}{\tan\theta}$.`,
      r`Quotient: $\tan\theta=\dfrac{\sin\theta}{\cos\theta}$. Pythagorean: $\sin^2\theta+\cos^2\theta=1$.`,
      r`To prove an identity, rewrite everything in sine and cosine.`,
    ],
    examples: [
      { t: "Reciprocal", body: r`$\sin\theta=\tfrac35$. Find $\csc\theta$.\soln $\csc\theta=\dfrac{1}{\sin\theta}=\tfrac53$.` },
      { t: "Reciprocal", body: r`$\cos\theta=\tfrac45$. Find $\sec\theta$.\soln $\sec\theta=\dfrac{1}{\cos\theta}=\tfrac54$.` },
      { t: "Reciprocal", body: r`$\tan\theta=2$. Find $\cot\theta$.\soln $\cot\theta=\dfrac{1}{\tan\theta}=\tfrac12$.` },
      { t: "Evaluate", body: r`Find $\sec60^\circ$.\soln $\dfrac{1}{\cos60^\circ}=\dfrac{1}{1/2}=2$.` },
      { t: "Evaluate", body: r`Find $\csc30^\circ$.\soln $\dfrac{1}{\sin30^\circ}=\dfrac{1}{1/2}=2$.` },
      { t: "Evaluate", body: r`Find $\cot45^\circ$.\soln $\dfrac{1}{\tan45^\circ}=\dfrac11=1$.` },
      { t: "Pythagorean", body: r`$\sin\theta=\tfrac35$, acute. Find $\cos\theta$.\soln $\cos^2\theta=1-\tfrac{9}{25}=\tfrac{16}{25}\Rightarrow\cos\theta=\tfrac45$ (a 3-4-5 triangle):` + r`\rtri{4}{3}{$3$}{$4$}{$5$}` },
      { t: "Pythagorean", body: r`$\cos\theta=\tfrac{5}{13}$, acute. Find $\sin\theta$.\soln $\sin^2\theta=1-\tfrac{25}{169}=\tfrac{144}{169}\Rightarrow\sin\theta=\tfrac{12}{13}$.` },
      { t: "Prove", body: r`Prove $\tan\theta\cos\theta=\sin\theta$.\soln $\tan\theta\cos\theta=\dfrac{\sin\theta}{\cos\theta}\cdot\cos\theta=\sin\theta$. \checkmark` },
    ],
    questions: [
      { ask: r`$\sin\theta=\tfrac12$: find $\csc\theta$.` },
      { ask: r`$\cos\theta=\tfrac13$: find $\sec\theta$.` },
      { ask: r`$\tan\theta=4$: find $\cot\theta$.` },
      { ask: r`Find $\sec45^\circ$.` },
      { ask: r`Find $\csc60^\circ$.` },
      { ask: r`Find $\cot30^\circ$.` },
      { ask: r`$\sin\theta=\tfrac{8}{17}$, acute: find $\cos\theta$.` },
      { ask: r`$\cos\theta=\tfrac{24}{25}$, acute: find $\sin\theta$.` },
      { ask: r`Simplify $\csc\theta\cdot\sin\theta$.` },
      { ask: r`Simplify $\dfrac{\cos\theta}{\sin\theta}$.` },
      { ask: r`Evaluate $\sec0^\circ$.` },
      { ask: r`Prove $\cot\theta\cdot\tan\theta=1$.`, ws: "2.6cm" },
      { ask: r`$\sin\theta=\tfrac23$, acute: find $\tan\theta$ exactly.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$2$`, r`$3$`, r`$\tfrac14$`, r`$\sqrt2$`, r`$\tfrac{2}{\sqrt3}$`, r`$\sqrt3$`, r`$\tfrac{15}{17}$`, r`$\tfrac{7}{25}$`, r`$1$`, r`$\cot\theta$`, r`$1$`, r`true (reciprocals multiply to $1$)`, r`$\cos\theta=\tfrac{\sqrt5}{3}$, $\tan\theta=\tfrac{2}{\sqrt5}$`],
  },
  {
    code: "4.4", unit: U, title: "The Sine Law & Cosine Law",
    intro: "Solve oblique triangles: sine law for a side–angle pair, cosine law for SAS or SSS.",
    ideas: [
      r`Sine law: $\dfrac{a}{\sin A}=\dfrac{b}{\sin B}=\dfrac{c}{\sin C}$.`,
      r`Cosine law: $c^2=a^2+b^2-2ab\cos C$.`,
      r`SSA is the ambiguous case — it may give two triangles.`,
    ],
    examples: [
      { t: "Sine law (side)", body: r`$A=40^\circ$, $B=60^\circ$, $a=10$. Find $b$.\soln $\dfrac{b}{\sin60^\circ}=\dfrac{10}{\sin40^\circ}\Rightarrow b=\dfrac{10\sin60^\circ}{\sin40^\circ}\approx13.5$.` + r`\gtri{$40^\circ$}{$60^\circ$}{$C$}{$10$}{$b$}{$c$}` },
      { t: "Sine law (angle)", body: r`$a=8$, $b=11$, $A=35^\circ$. Find $B$.\soln $\dfrac{\sin B}{11}=\dfrac{\sin35^\circ}{8}\Rightarrow\sin B=\dfrac{11\sin35^\circ}{8}\approx0.789$. \\ $B\approx52.1^\circ$.` },
      { t: "Cosine law (side)", body: r`$a=9$, $b=7$, $C=55^\circ$. Find $c$.\soln $c^2=81+49-2(9)(7)\cos55^\circ\approx130-72.3=57.7$. \\ $c\approx7.6$.` },
      { t: "Cosine law (angle)", body: r`$a=5$, $b=6$, $c=7$. Find $C$.\soln $\cos C=\dfrac{25+36-49}{2(5)(6)}=\dfrac{12}{60}=0.2\Rightarrow C\approx78.5^\circ$:` + r`\gtri{$A$}{$B$}{$C$}{$5$}{$6$}{$7$}` },
      { t: "ASA side", body: r`$A=50^\circ$, $B=70^\circ$, $a=12$. Find $b$.\soln $b=\dfrac{12\sin70^\circ}{\sin50^\circ}\approx14.7$.` },
      { t: "SAS side", body: r`$a=8$, $b=5$, $C=60^\circ$. Find $c$.\soln $c^2=64+25-80\cos60^\circ=89-40=49\Rightarrow c=7$.` },
      { t: "SSS angle", body: r`$a=4$, $b=5$, $c=6$. Find $C$.\soln $\cos C=\dfrac{16+25-36}{2(4)(5)}=\dfrac{5}{40}=0.125\Rightarrow C\approx82.8^\circ$.` },
      { t: "Choose the law", body: r`Given two angles and a side, which law?\soln A side with its opposite angle is available — use the sine law.` },
      { t: "Choose the law", body: r`Given three sides, which law?\soln No angle is known — use the cosine law.` },
    ],
    questions: [
      { ask: r`$A=50^\circ$, $B=70^\circ$, $a=12$. Find $b$.`, ws: "3cm" },
      { ask: r`$A=45^\circ$, $B=65^\circ$, $a=14$. Find $b$.`, ws: "3cm" },
      { ask: r`$a=9$, $b=7$, $C=55^\circ$. Find $c$.`, ws: "3cm" },
      { ask: r`$a=6$, $b=8$, $c=11$. Find the largest angle.`, ws: "3cm" },
      { ask: r`$a=8$, $b=11$, $A=35^\circ$. Find $B$.`, ws: "3cm" },
      { ask: r`$a=5$, $b=6$, $C=60^\circ$. Find $c$.`, ws: "3cm" },
      { ask: r`$a=4$, $b=5$, $c=6$. Find $C$.`, ws: "3cm" },
      { ask: r`Which law: two angles and a side?` },
      { ask: r`Which law: three sides?` },
      { ask: r`$a=7$, $b=10$, $C=45^\circ$. Find $c$.`, ws: "3cm" },
      { ask: r`$A=40^\circ$, $a=10$, $b=8$. Find $B$.`, ws: "3cm" },
      { ask: r`$a=12$, $b=15$, $c=9$. Find the largest angle.`, ws: "3cm" },
      { ask: r`$A=35^\circ$, $a=6$, $b=9$ (SSA). How many triangles are possible?`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\approx14.7$`, r`$\approx17.9$`, r`$\approx7.6$`, r`$C\approx102.6^\circ$`, r`$B\approx52.1^\circ$`, r`$\approx5.6$`, r`$C\approx82.8^\circ$`, r`sine law`, r`cosine law`, r`$\approx7.1$`, r`$B\approx31.0^\circ$`, r`$B=90^\circ$ (a $9$-$12$-$15$ right triangle)`, r`two triangles ($b\sin A\approx5.16<a<b$)`],
  },
  {
    code: "4.5", unit: U, title: "Trigonometry in 3-D Problems",
    intro: "Break a 3-D or multi-step problem into right and oblique triangles and solve them in turn.",
    ideas: [
      r`Draw and label a clear diagram first.`,
      r`Solve the triangle you can, then carry a shared side into the next.`,
      r`Angles of elevation and depression between two points are equal.`,
    ],
    examples: [
      { t: "Elevation", body: r`From $50$ m away the elevation to a tower top is $38^\circ$. Find the height.\soln $\tan38^\circ=\dfrac{h}{50}\Rightarrow h=50\tan38^\circ\approx39.1$ m.` + r`\rtri{5}{3.9}{$h$}{$50$ m}{}` },
      { t: "Ladder", body: r`A $6$ m ladder makes $70^\circ$ with the ground. How high does it reach?\soln $h=6\sin70^\circ\approx5.6$ m.` },
      { t: "Space diagonal", body: r`A box is $3\times4\times12$. Find the space diagonal.\soln Base diagonal $\sqrt{3^2+4^2}=5$; space diagonal $\sqrt{5^2+12^2}=\sqrt{169}=13$.` },
      { t: "Two paths", body: r`Two roads leave a point $65^\circ$ apart; cars travel $40$ km and $55$ km. Distance apart?\soln Cosine law: $d^2=40^2+55^2-2(40)(55)\cos65^\circ\approx2765\Rightarrow d\approx52.6$ km.` },
      { t: "Ramp angle", body: r`A ramp rises $2$ m over a $10$ m run. Find the angle.\soln $\tan\theta=\dfrac{2}{10}=0.2\Rightarrow\theta\approx11.3^\circ$.` },
      { t: "Wire", body: r`A $10$ m wire makes $55^\circ$ with the ground. Attachment height?\soln $h=10\sin55^\circ\approx8.2$ m.` },
      { t: "Elevation", body: r`From $80$ m away the elevation to a roof is $25^\circ$. Find the height.\soln $h=80\tan25^\circ\approx37.3$ m.` },
      { t: "Space diagonal", body: r`A box is $6\times8\times24$. Find the space diagonal.\soln Base $\sqrt{6^2+8^2}=10$; diagonal $\sqrt{10^2+24^2}=\sqrt{676}=26$.` },
      { t: "Two ships", body: r`Two ships leave port $48^\circ$ apart at $20$ km and $30$ km. Distance apart?\soln $d^2=400+900-2(20)(30)\cos48^\circ\approx497\Rightarrow d\approx22.3$ km.` },
    ],
    questions: [
      { ask: r`Elevation $30^\circ$ from $100$ m away. Find the height.`, ws: "3cm" },
      { ask: r`A $8$ m ladder at $60^\circ$. How high does it reach?` },
      { ask: r`Space diagonal of a $2\times3\times6$ box.`, ws: "3cm" },
      { ask: r`Two paths $50^\circ$ apart, $10$ km and $14$ km. Distance apart?`, ws: "3cm" },
      { ask: r`A ramp rises $1.5$ m over a $12$ m run. Find the angle.` },
      { ask: r`A $15$ m wire at $40^\circ$. Find the attachment height.` },
      { ask: r`Elevation $20^\circ$ from $200$ m away. Find the height.`, ws: "3cm" },
      { ask: r`Space diagonal of a $9\times12\times8$ box.`, ws: "3cm" },
      { ask: r`Two ships $60^\circ$ apart, both $25$ km out. Distance apart?`, ws: "3cm" },
      { ask: r`A kite string is $50$ m at $65^\circ$ elevation. Find the height.` },
      { ask: r`A guy wire runs to the top of a $12$ m pole from $5$ m away. Find its length.` },
      { ask: r`From $40$ m away the elevation to a building top is $55^\circ$. Find the height.`, ws: "3cm" },
      { ask: r`From two points $40$ m apart in line with a tower, the elevations are $28^\circ$ and $40^\circ$. Find the tower height.`, challenge: true, ws: "4cm" },
    ],
    answers: [r`$100\tan30^\circ\approx57.7$ m`, r`$8\sin60^\circ\approx6.9$ m`, r`$\sqrt{13+36}=7$`, r`$\approx10.8$ km`, r`$\theta\approx7.1^\circ$`, r`$15\sin40^\circ\approx9.6$ m`, r`$200\tan20^\circ\approx72.8$ m`, r`base $15$, diagonal $17$`, r`$25$ km`, r`$50\sin65^\circ\approx45.3$ m`, r`$\sqrt{144+25}=13$ m`, r`$40\tan55^\circ\approx57.1$ m`, r`$\approx58$ m`],
  },
];
