// MCR3U Unit 5 worksheets — Sinusoidal Functions.
// Examples: full step-by-step solutions with TikZ sine/cosine curves (\splot).
const r = String.raw;
const U = "5: Sinusoidal Functions";

export default [
  {
    code: "5.1", unit: U, title: "Periodic Functions & Their Properties",
    intro: "Periodic functions repeat. Read off the period, amplitude, and axis (midline).",
    ideas: [
      r`Period: the horizontal length of one cycle.`,
      r`Amplitude $=\dfrac{\text{max}-\text{min}}{2}$.`,
      r`Axis (midline) $=\dfrac{\text{max}+\text{min}}{2}$.`,
    ],
    examples: [
      { t: "Period", body: r`A graph repeats every $5$ units. State the period.\soln One full cycle spans $5$ units, so the period is $5$.` },
      { t: "Amplitude", body: r`Max $8$, min $2$. Find the amplitude.\soln $\dfrac{\text{max}-\text{min}}{2}=\dfrac{8-2}{2}=3$.` },
      { t: "Axis", body: r`Max $8$, min $2$. Find the axis.\soln $\dfrac{\text{max}+\text{min}}{2}=\dfrac{8+2}{2}=5$.` },
      { t: "Period of sine", body: r`State the period of $y=\sin x$.\soln The sine curve repeats once per full turn: $360^\circ$:` + r`\splot{-1.5}{1.5}{\addplot[exblue,very thick,domain=0:360]{sin(x)};}` },
      { t: "Max/min", body: r`State the max and min of $y=\sin x$.\soln The peak is $1$ and the trough is $-1$.` },
      { t: "Amplitude (negatives)", body: r`Max $10$, min $-2$. Amplitude?\soln $\dfrac{10-(-2)}{2}=\dfrac{12}{2}=6$.` },
      { t: "Axis (negatives)", body: r`Max $10$, min $-2$. Axis?\soln $\dfrac{10+(-2)}{2}=4$.` },
      { t: "Range", body: r`Amplitude $3$, axis $5$. Range?\soln From $5-3$ to $5+3$: $2$ to $8$.` },
      { t: "Cycle", body: r`What is one "cycle"?\soln One complete repeat of the pattern; its length is the period.` },
    ],
    questions: [
      { ask: r`A graph repeats every $7$ units. State the period.` },
      { ask: r`Max $9$, min $1$. Find the amplitude.` },
      { ask: r`Max $9$, min $1$. Find the axis.` },
      { ask: r`State the period of $y=\cos x$.` },
      { ask: r`State the maximum of $y=\sin x$.` },
      { ask: r`Max $12$, min $-4$. Find the amplitude.` },
      { ask: r`Max $12$, min $-4$. Find the axis.` },
      { ask: r`A wave repeats every $6$ s. State the period.` },
      { ask: r`Max $5$, min $-5$. Find the amplitude.` },
      { ask: r`Max $5$, min $-5$. Find the axis.` },
      { ask: r`Amplitude $4$, axis $10$. State the range.` },
      { ask: r`State the minimum of $y=\cos x$.` },
      { ask: r`A graph has axis $y=3$ and amplitude $7$. Find the max and min.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$7$`, r`$4$`, r`$5$`, r`$360^\circ$`, r`$1$`, r`$8$`, r`$4$`, r`$6$ s`, r`$5$`, r`$0$`, r`$6$ to $14$`, r`$-1$`, r`max $10$, min $-4$`],
  },
  {
    code: "5.2", unit: U, title: "Graphing Sine & Cosine",
    intro: "The parent graphs y = sin x and y = cos x have amplitude 1, period 360°, midline y = 0.",
    ideas: [
      r`$y=\sin x$ starts at $(0,0)$; $y=\cos x$ starts at its max $(0,1)$.`,
      r`Both repeat every $360^\circ$ and range from $-1$ to $1$.`,
    ],
    examples: [
      { t: "Amplitude", body: r`Amplitude of $y=3\sin x$?\soln The coefficient of sine: $|3|=3$.` },
      { t: "Period", body: r`Period of $y=\sin x$?\soln One cycle spans $360^\circ$.` },
      { t: "Start of cosine", body: r`Where does $y=\cos x$ start?\soln At its maximum $(0,1)$. Sine (blue) starts at $0$; cosine (orange) starts at the top:` + r`\splot{-1.5}{1.5}{\addplot[exblue,very thick,domain=0:360]{sin(x)};\addplot[qorange,very thick,domain=0:360]{cos(x)};}` },
      { t: "Key value", body: r`Evaluate $\sin90^\circ$.\soln The sine peak: $1$.` },
      { t: "Key value", body: r`Evaluate $\cos0^\circ$.\soln Cosine starts at its max: $1$.` },
      { t: "Zero", body: r`Evaluate $\sin180^\circ$.\soln A zero crossing: $0$.` },
      { t: "Negative", body: r`Evaluate $\cos180^\circ$.\soln Cosine's trough: $-1$.` },
      { t: "Max", body: r`Max of $y=2\sin x$?\soln Amplitude $2$, midline $0$: max $2$.` },
      { t: "Midline", body: r`Midline of $y=\cos x$?\soln $y=0$.` },
    ],
    questions: [
      { ask: r`Amplitude of $y=6\sin x$?` },
      { ask: r`Period of $y=\sin x$?` },
      { ask: r`Evaluate $\cos0^\circ$.` },
      { ask: r`Evaluate $\sin90^\circ$.` },
      { ask: r`Evaluate $\sin0^\circ$.` },
      { ask: r`Evaluate $\cos90^\circ$.` },
      { ask: r`Evaluate $\sin270^\circ$.` },
      { ask: r`State the maximum of $y=3\sin x$.` },
      { ask: r`State the minimum of $y=3\sin x$.` },
      { ask: r`Where does $\sin x=1$ in $[0^\circ,360^\circ]$?` },
      { ask: r`Where does $\cos x=0$ in $[0^\circ,360^\circ]$?` },
      { ask: r`State the midline of $y=\cos x$.` },
      { ask: r`Cosine starts at a maximum. At what angle is it first $0$?`, challenge: true, ws: "2.6cm" },
    ],
    answers: [r`$6$`, r`$360^\circ$`, r`$1$`, r`$1$`, r`$0$`, r`$0$`, r`$-1$`, r`$3$`, r`$-3$`, r`$90^\circ$`, r`$90^\circ,270^\circ$`, r`$y=0$`, r`$90^\circ$`],
  },
  {
    code: "5.3", unit: U, title: "Transformations of Sinusoidal Functions",
    intro: "For y = a sin(k(x − d)) + c: a is amplitude, period = 360°/k, c is the midline, d is the phase shift.",
    ideas: [
      r`Amplitude $=|a|$; period $=\dfrac{360^\circ}{k}$.`,
      r`Midline $y=c$; range from $c-|a|$ to $c+|a|$.`,
      r`$d$ shifts horizontally (phase shift).`,
    ],
    examples: [
      { t: "Amplitude & period", body: r`For $y=3\sin(2x)$: amplitude and period.\soln Amplitude $|3|=3$; period $\dfrac{360^\circ}{2}=180^\circ$ — two cycles in $360^\circ$:` + r`\splot{-3.5}{3.5}{\addplot[exblue,very thick,domain=0:360]{3*sin(2*x)};}` },
      { t: "Midline", body: r`Midline of $y=\sin x+4$?\soln The $+4$ raises the midline to $y=4$.` },
      { t: "Period", body: r`Period of $y=\cos(4x)$?\soln $\dfrac{360^\circ}{4}=90^\circ$.` },
      { t: "Write an equation", body: r`Sine with amplitude $2$, period $360^\circ$, midline $0$.\soln $a=2$, $k=1$, $c=0$: $y=2\sin x$.` },
      { t: "Phase shift", body: r`Phase shift of $y=\sin(x-30^\circ)$?\soln $(x-30^\circ)$ shifts the graph right $30^\circ$.` },
      { t: "Range", body: r`Range of $y=3\sin x+1$?\soln Midline $1$, amplitude $3$: from $1-3$ to $1+3$, i.e. $-2\le y\le4$.` },
      { t: "Amplitude", body: r`Amplitude of $y=5\sin x$?\soln $|5|=5$.` },
      { t: "Period", body: r`Period of $y=\sin(3x)$?\soln $\dfrac{360^\circ}{3}=120^\circ$.` },
      { t: "Midline", body: r`Midline of $y=2\cos x-5$?\soln The $-5$ gives midline $y=-5$.` },
    ],
    questions: [
      { ask: r`Amplitude of $y=4\sin x$?` },
      { ask: r`Period of $y=\sin(3x)$?` },
      { ask: r`Midline of $y=\cos x-3$?` },
      { ask: r`Phase shift of $y=\sin(x-40^\circ)$?` },
      { ask: r`Amplitude and period of $y=2\sin(4x)$?`, ws: "2.6cm" },
      { ask: r`Range of $y=3\sin x+1$?` },
      { ask: r`Midline of $y=2\cos x-5$?` },
      { ask: r`Period of $y=\cos(6x)$?` },
      { ask: r`Write a sine function: amplitude $2$, period $360^\circ$, midline $0$.` },
      { ask: r`Range of $y=5\sin x$?` },
      { ask: r`Amplitude of $y=-3\sin x$?` },
      { ask: r`Period of $y=\sin x$?` },
      { ask: r`State amplitude, period, midline, and range of $y=4\sin(2x)-1$.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$4$`, r`$120^\circ$`, r`$y=-3$`, r`right $40^\circ$`, r`amplitude $2$, period $90^\circ$`, r`$-2\le y\le4$`, r`$y=-5$`, r`$60^\circ$`, r`$y=2\sin x$`, r`$-5\le y\le5$`, r`$3$`, r`$360^\circ$`, r`amp $4$, period $180^\circ$, midline $y=-1$, range $-5\le y\le3$`],
  },
  {
    code: "5.4", unit: U, title: "Sinusoidal Applications",
    intro: "Model Ferris wheels, tides, and temperature with h = a sin(k(t − d)) + c.",
    ideas: [
      r`Amplitude $=\dfrac{\text{max}-\text{min}}{2}$; midline $=\dfrac{\text{max}+\text{min}}{2}$.`,
      r`$k=\dfrac{360^\circ}{\text{period}}$.`,
      r`Max $=$ midline $+$ amplitude; min $=$ midline $-$ amplitude.`,
    ],
    examples: [
      { t: "Amplitude", body: r`A wheel ranges $2$ m to $12$ m. Amplitude?\soln $\dfrac{12-2}{2}=5$ m.` },
      { t: "Midline", body: r`Same wheel. Midline?\soln $\dfrac{12+2}{2}=7$ m.` },
      { t: "Period to k", body: r`A tide cycle is $12$ h. Find $k$.\soln $k=\dfrac{360^\circ}{12}=30^\circ$/h.` },
      { t: "Build a model", body: r`Temperature ranges $10^\circ$ to $24^\circ$. Amplitude and midline?\soln amplitude $\dfrac{24-10}{2}=7$; midline $\dfrac{24+10}{2}=17$.` },
      { t: "Height at a time", body: r`For $h=5\sin(30t)+7$, find $h$ at $t=3$ (so $30t=90^\circ$).\soln $5\sin90^\circ+7=5(1)+7=12$ m. The model oscillates between $2$ and $12$ about the midline $7$:` + r`\splot{0}{14}{\addplot[qorange,dashed,domain=0:360]{7};\addplot[exblue,very thick,domain=0:360]{5*sin(x)+7};}` },
      { t: "Maximum", body: r`Max of $h=5\sin(30t)+7$?\soln midline $+$ amplitude $=7+5=12$ m.` },
      { t: "Minimum", body: r`Min of $h=5\sin(30t)+7$?\soln midline $-$ amplitude $=7-5=2$ m.` },
      { t: "Amplitude", body: r`A wheel ranges $1$ m to $15$ m. Amplitude?\soln $\dfrac{15-1}{2}=7$ m.` },
      { t: "Cycle to k", body: r`A cycle lasts $10$ s. Find $k$.\soln $k=\dfrac{360^\circ}{10}=36^\circ$/s.` },
    ],
    questions: [
      { ask: r`A wheel ranges $2$ m to $18$ m. Find the amplitude.` },
      { ask: r`Same wheel. Find the midline.` },
      { ask: r`A cycle lasts $8$ s. Find $k$.` },
      { ask: r`For $h=6\sin(30t)+8$, find the maximum height.` },
      { ask: r`For $h=6\sin(30t)+8$, find the minimum height.` },
      { ask: r`Temperature ranges $8^\circ$ to $22^\circ$. Find the amplitude.` },
      { ask: r`Same temperature. Find the midline.` },
      { ask: r`A tide has period $12$ h. Find $k$.` },
      { ask: r`For $h=5\sin(30t)+7$, find $h$ at $t=3$.`, ws: "2.6cm" },
      { ask: r`A wheel ranges $1$ m to $15$ m. Find the amplitude.` },
      { ask: r`State the range of $h=4\sin(30t)+10$.` },
      { ask: r`If $k=30^\circ$/h, what is the period?` },
      { ask: r`A Ferris wheel turns once in $40$ s; height ranges $1$ m to $21$ m. Find the amplitude, midline, and $k$.`, challenge: true, ws: "4cm" },
    ],
    answers: [r`$8$`, r`$10$`, r`$45^\circ$/s`, r`$14$ m`, r`$2$ m`, r`$7$`, r`$15$`, r`$30^\circ$/h`, r`$12$ m`, r`$7$`, r`$6$ to $14$`, r`$12$ h`, r`amplitude $10$, midline $11$, $k=9^\circ$/s`],
  },
];
