// MDM4U Unit 1 worksheets — Counting, Permutations & Combinations.
// Textbook-level depth: multi-step, method-contrasting, multi-part; each example
// and question a distinct idea. 9 worked examples + 13 questions + answer key each.
const r = String.raw;
const U = "1: Counting, Permutations & Combinations";

export default [
  {
    code: "1.1", unit: U, title: "The Fundamental Counting Principle",
    intro: r`Sequential (\emph{and}) choices \emph{multiply}; disjoint (\emph{or}) cases \emph{add}. Fill the most-restricted stage first, and count \emph{at least} with the complement (total $-$ unwanted).`,
    ideas: [r`Multiplicative principle: independent stages multiply.`, r`Additive principle: mutually exclusive cases add --- watch for AND nested inside OR.`, r`Restrictions first; \emph{at least one} $=$ total $-$ none.`],
    examples: [
      { t: "Product rule, with a follow-up", body: r`A diner special is 1 of 3 egg styles, 1 of 4 breads, and 1 of 5 drinks. \\ \textbf{(a)} How many specials? \\ \textbf{(b)} How many if the drink must be coffee or tea (2 of the 5)?\soln (a) $3\cdot4\cdot5=60$. (b) restrict the last stage: $3\cdot4\cdot2=24$.` },
      { t: "Repeats vs. distinct (and the ratio)", body: r`A 3-character wristband code uses letters A--Z. \\ \textbf{(a)} repeats allowed; \\ \textbf{(b)} all different; \\ \textbf{(c)} what fraction are all different?\soln (a) $26^3=17\,576$. (b) $26\cdot25\cdot24=15\,600$. (c) $\dfrac{15\,600}{17\,576}\approx0.89$.` },
      { t: "Product nested in cases (AND in OR)", body: r`A café combo is either a hot drink with a pastry ($6\times4$) or a cold drink with a cookie ($5\times3$). How many combos?\soln Multiply within each case, then add the disjoint cases: $6\cdot4+5\cdot3=24+15=39$.` },
      { t: "Most-restricted stage first", body: r`A 4-digit ID has first digit $1$--$9$, a distinct set of digits, and an even last digit. How many?\soln Split on the units. \emph{Units $=0$:} $9\cdot8\cdot7=504$. \emph{Units $\in\{2,4,6,8\}$:} first digit avoids $0$ and the units ($8$), then $8,7$: $4\cdot8\cdot8\cdot7=1792$. Total $504+1792=2296$.` },
      { t: "Complement (at least one)", body: r`A 6-question true/false quiz. How many answer keys have at least one \emph{False}?\soln Total $-$ all-True: $2^6-1=63$.` },
      { t: "Adjacency restriction", body: r`A 4-note ringtone uses 7 distinct notes; no two consecutive notes are equal. How many ringtones?\soln First note $7$; each later note only avoids the one before it ($6$): $7\cdot6\cdot6\cdot6=1512$.` },
      { t: "Ordered selection", body: r`10 sprinters race. How many gold--silver--bronze podiums are possible?\soln Ordered, no repeats: $10\cdot9\cdot8=720$.` },
      { t: "Subsets via yes/no", body: r`A frozen-yogurt bar has 8 toppings; take any subset. How many topping combinations, including none?\soln Each topping in or out: $2^8=256$.` },
      { t: "Complement in an ordered choice", body: r`A 4-leg relay order is chosen from 6 runners. In how many orders does the fastest runner, Maya, run a leg?\soln Total $-$ none: $6\cdot5\cdot4\cdot3-5\cdot4\cdot3\cdot2=360-120=240$.` },
    ],
    questions: [
      { ask: r`A build-your-own burrito offers 2 tortillas, 3 proteins, 4 salsas, and 2 cheeses. \\ \textbf{(a)} How many burritos? \\ \textbf{(b)} How many if cheese is optional (a \emph{no cheese} choice is added)?` },
      { ask: r`A 5-character Wi-Fi password uses digits $0$--$9$. \\ \textbf{(a)} How many if repeats are allowed? \\ \textbf{(b)} How many with no repeated digit?` },
      { ask: r`A 4-letter mascot name starts with a consonant (21 choices); the other 3 letters are any letters, repeats allowed. How many names?` },
      { ask: r`A lunch deal is either a wrap with a drink ($5\times4$) or a salad with a soup ($3\times3$). How many deals?` },
      { ask: r`A 5-question true/false test. How many answer keys have at least one \emph{True}?` },
      { ask: r`An ice-cream sundae takes any subset of 6 toppings. How many sundaes have at least one topping?` },
      { ask: r`9 gymnasts compete. How many gold--silver--bronze outcomes are possible?` },
      { ask: r`A 4-bead strip (in a row) is made from 5 colours; no two adjacent beads share a colour. How many strips?` },
      { ask: r`A 3-digit locker number uses digits $0$--$9$ but can't start with $0$. How many lockers?` },
      { ask: r`A 4-symbol code uses letters A--Z but can't be four identical letters. How many codes?` },
      { ask: r`From 10 photos, how many ways to arrange 3 in a row on a wall?` },
      { ask: r`A jersey shows 2 different initials (letters) then a single digit $1$--$9$. How many jerseys?` },
      { ask: r`A 4-character password has exactly 2 letters and 2 digits in some order; both may repeat. How many passwords?`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`(a) $48$; (b) $2\cdot3\cdot4\cdot3=72$`, r`(a) $10^5=100\,000$; (b) $10\cdot9\cdot8\cdot7\cdot6=30\,240$`, r`$21\cdot26^3=369\,096$`, r`$20+9=29$`, r`$2^5-1=31$`, r`$2^6-1=63$`, r`$9\cdot8\cdot7=504$`, r`$5\cdot4\cdot4\cdot4=320$`, r`$9\cdot10\cdot10=900$`, r`$26^4-26=456\,950$`, r`$10\cdot9\cdot8=720$`, r`$26\cdot25\cdot9=5850$`, r`$\dbinom{4}{2}26^2\,10^2=405\,600$`],
  },
  {
    code: "1.2", unit: U, title: "Factorials & Permutations of Distinct Objects",
    intro: r`$n!$ counts full orderings of $n$ distinct objects; $_nP_r=\dfrac{n!}{(n-r)!}$ counts \emph{ordered} selections of $r$ from $n$. Simplify factorial fractions by cancelling the common tail.`,
    ideas: [r`$n!=n(n-1)\cdots2\cdot1$, and $0!=1$.`, r`$_nP_r=\dfrac{n!}{(n-r)!}$ for ordered selections.`, r`Solve $_nP_r=k$ by expanding into a polynomial in $n$.`],
    examples: [
      { t: "Evaluate and interpret", body: r`Compute $6!$ and say what it counts.\soln $6!=720$ --- the number of orders of 6 distinct books on a shelf.` },
      { t: "Simplify a factorial fraction", body: r`Simplify $\dfrac{10!}{7!}$ without a calculator.\soln Cancel the common tail $7!$: $10\cdot9\cdot8=720$.` },
      { t: "Ordered selection in context", body: r`8 runners race for gold, silver, and bronze. How many podiums?\soln $_8P_3=8\cdot7\cdot6=336$.` },
      { t: "Order all objects", body: r`How many arrangements of the letters of MONEY?\soln All 5 distinct: $5!=120$.` },
      { t: "Solve for $n$", body: r`Solve $_nP_2=56$.\soln $n(n-1)=56\Rightarrow n^2-n-56=0\Rightarrow(n-8)(n+7)=0\Rightarrow n=8$.` },
      { t: "Algebraic simplification", body: r`Simplify $\dfrac{(n+1)!}{(n-1)!}$.\soln $(n+1)\,n=n^2+n$.` },
      { t: "Assign distinct prizes", body: r`5 different trophies are given to 8 students, at most one each. How many ways?\soln Ordered selection: $_8P_5=8\cdot7\cdot6\cdot5\cdot4=6720$.` },
      { t: "Arrangement with a fixed spot", body: r`7 people line up for a photo with one specific person in the middle (4th) position. How many line-ups?\soln Fix that person; arrange the other 6: $6!=720$.` },
      { t: "Two-part count", body: r`A gallery hangs 4 of 9 distinct paintings in a row. \\ \textbf{(a)} How many displays? \\ \textbf{(b)} How many put a specific painting first?\soln (a) $_9P_4=3024$. (b) fix it first; arrange 3 of the other 8: $_8P_3=336$.` },
    ],
    questions: [
      { ask: r`Evaluate $8!$.` },
      { ask: r`In how many orders can 7 distinct parade floats line up?` },
      { ask: r`Simplify $\dfrac{11!}{8!}$.` },
      { ask: r`A club elects a president, then a VP, then a treasurer from 12 members. How many outcomes?` },
      { ask: r`Find $_{10}P_3$.` },
      { ask: r`Solve $_nP_2=42$.` },
      { ask: r`How many arrangements of the letters of PLANET (all distinct)?` },
      { ask: r`A 4-character password uses distinct letters from $\{A,B,C,D,E,F\}$. How many?` },
      { ask: r`Simplify $\dfrac{n!}{(n-3)!}$.` },
      { ask: r`Solve $_nP_3=210$.` },
      { ask: r`In how many ways can gold and silver medals be given among 15 athletes?` },
      { ask: r`5 distinct books sit on a shelf. \\ \textbf{(a)} How many arrangements? \\ \textbf{(b)} How many with a particular book at an end?` },
      { ask: r`Simplify $\dfrac{(n+2)!}{n!}$, then solve $\dfrac{(n+2)!}{n!}=72$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$40\,320$`, r`$7!=5040$`, r`$11\cdot10\cdot9=990$`, r`$12\cdot11\cdot10=1320$`, r`$720$`, r`$n=7$`, r`$720$`, r`$_6P_4=360$`, r`$n(n-1)(n-2)$`, r`$n=7$`, r`$_{15}P_2=210$`, r`(a) $120$; (b) $2\cdot4!=48$`, r`$(n+2)(n+1)$; $=72\Rightarrow n=7$`],
  },
  {
    code: "1.3", unit: U, title: "Permutations with Identical Objects",
    intro: r`Indistinguishable objects overcount. Divide by the factorials of each repeat: $\dfrac{n!}{a!\,b!\cdots}$. Lattice paths and bit strings are the same idea in disguise.`,
    ideas: [r`Arrangements of $n$ items with repeats $a,b,\dots$: $\dfrac{n!}{a!\,b!\cdots}$.`, r`Grid path (all shortest routes): $\dfrac{(R+U)!}{R!\,U!}$.`, r`An $n$-bit string with $k$ ones: $\dfrac{n!}{k!\,(n-k)!}=\dbinom{n}{k}$.`],
    examples: [
      { t: "Word with repeats", body: r`How many arrangements of BANANA?\soln B$1$, A$3$, N$2$: $\dfrac{6!}{3!\,2!}=60$.` },
      { t: "Many repeats", body: r`Arrangements of MISSISSIPPI?\soln M$1$, I$4$, S$4$, P$2$: $\dfrac{11!}{4!\,4!\,2!}=34\,650$.` },
      { t: "A multiset of digits", body: r`How many arrangements of the digits $1,1,2,3,3,3$?\soln $\dfrac{6!}{2!\,3!}=60$.` },
      { t: "Lattice path", body: r`Shortest routes across a $4\times3$ grid (4 rights, 3 ups)? Interpret the count.\soln $\dfrac{7!}{4!\,3!}=35$ --- choosing which 4 of the 7 steps are \emph{right}.` },
      { t: "Bit string = combination", body: r`How many 8-bit binary strings contain exactly three $1$s?\soln $\dfrac{8!}{3!\,5!}=56=\dbinom{8}{3}$ --- choose the positions of the ones.` },
      { t: "Longer word", body: r`Arrangements of SUCCESS?\soln S$3$, U$1$, C$2$, E$1$: $\dfrac{7!}{3!\,2!}=420$.` },
      { t: "Path through a checkpoint", body: r`On a $4\times4$ grid, how many shortest routes pass through the centre corner $(2,2)$?\soln Multiply the two legs: $\dbinom{4}{2}\cdot\dbinom{4}{2}=6\cdot6=36$.` },
      { t: "Word with a triple", body: r`How many arrangements of CANADA?\soln 3 A's: $\dfrac{6!}{3!}=120$.` },
      { t: "Constrained arrangement", body: r`How many arrangements of TORONTO \\ \textbf{(a)} in total; \\ \textbf{(b)} beginning with T?\soln T$2$, O$3$, R$1$, N$1$. (a) $\dfrac{7!}{2!\,3!}=420$. (b) fix a T; arrange T,O,O,O,R,N: $\dfrac{6!}{3!}=120$.` },
    ],
    questions: [
      { ask: r`How many arrangements of the letters of APPLE?` },
      { ask: r`A ship signals with a vertical line of 3 red and 4 blue identical flags. How many signals?` },
      { ask: r`Shortest routes across a $3\times2$ city grid (3 east, 2 north)?` },
      { ask: r`A baker lines up 4 identical croissants and 3 identical muffins in a display row. How many arrangements?` },
      { ask: r`A student's 6 report grades are A, A, B, B, B, C. In how many orders could they have appeared?` },
      { ask: r`How many arrangements of the letters of ONTARIO?` },
      { ask: r`How many 8-bit binary strings contain exactly three $1$s?` },
      { ask: r`How many arrangements of the letters of COMMITTEE?` },
      { ask: r`On a $4\times4$ grid, how many shortest routes pass through the centre point $(2,2)$?` },
      { ask: r`A staircase is climbed using 2 single steps and 3 double steps in some order. How many step-sequences?` },
      { ask: r`Arrange 2 A's, 2 B's, and 2 C's in a row.` },
      { ask: r`How many arrangements of the letters of TENNESSEE?` },
      { ask: r`How many arrangements of MISSISSIPPI have all four S's together?`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\dfrac{5!}{2!}=60$`, r`$\dfrac{7!}{3!\,4!}=35$`, r`$\dfrac{5!}{3!\,2!}=10$`, r`$\dfrac{7!}{4!\,3!}=35$`, r`$\dfrac{6!}{2!\,3!}=60$`, r`$\dfrac{7!}{2!}=2520$`, r`$\dbinom{8}{3}=56$`, r`$\dfrac{9!}{2!\,2!\,2!}=45\,360$`, r`$\dbinom{4}{2}^2=36$`, r`$\dfrac{5!}{2!\,3!}=10$`, r`$\dfrac{6!}{2!\,2!\,2!}=90$`, r`$\dfrac{9!}{4!\,2!\,2!}=3780$`, r`block SSSS $+$ M,I,I,I,I,P,P: $\dfrac{8!}{4!\,2!}=840$`],
  },
  {
    code: "1.4", unit: U, title: "Permutations with Constraints",
    intro: r`\emph{Together}: glue the block, arrange it, then arrange inside. \emph{Apart}: seat the rest, then slot into the gaps (or use the complement). \emph{Circular}: $(n-1)!$.`,
    ideas: [r`\emph{Together} --- one block: (block \& others)! $\times$ (inside)!.`, r`\emph{Apart} --- gap method, or total $-$ together.`, r`Circular arrangements of $n$: $(n-1)!$.`],
    examples: [
      { t: "Two together (glue)", body: r`5 people in a row; two specific people sit together.\soln Glue them: $4!\cdot2!=48$.` },
      { t: "Two apart (complement)", body: r`5 people in a row; two specific people do \emph{not} sit together.\soln Total $-$ together: $5!-48=72$.` },
      { t: "Block of three", body: r`6 people in a row; a group of 3 must stay together.\soln $4!\cdot3!=144$.` },
      { t: "Circular", body: r`Seat 6 people around a round table.\soln $(6-1)!=120$.` },
      { t: "Circular with a pair", body: r`Seat 6 around a round table with two specific people together.\soln Block $\Rightarrow5$ units: $(5-1)!\cdot2!=48$.` },
      { t: "None adjacent (gap method)", body: r`4 boys and 3 girls in a row with no two girls adjacent.\soln Seat boys $4!$; gaps $=5$; place 3 girls ordered $_5P_3=60$: $4!\cdot60=1440$.` },
      { t: "Fixed ends", body: r`Arrange PENCIL with P and L at the two ends.\soln Ends $2!$, middle $4!$: $2!\cdot4!=48$.` },
      { t: "Alternating", body: r`4 boys and 4 girls in a row, seated alternately by gender.\soln Two gender patterns, each side arranged: $2\cdot4!\cdot4!=1152$.` },
      { t: "Two conditions", body: r`8 books: 3 distinct math, 5 distinct novels. \\ \textbf{(a)} all math together? \\ \textbf{(b)} math together at the far left?\soln (a) $6!\cdot3!=4320$. (b) block fixed at left, arrange 5 novels and the 3 math inside: $5!\cdot3!=720$.` },
    ],
    questions: [
      { ask: r`6 friends pose in a row for a photo; twins Amy and Ben stand together. How many photos?` },
      { ask: r`Same 6 friends, but Amy and Ben refuse to stand together. How many photos?` },
      { ask: r`Seat 5 diplomats around a round table.` },
      { ask: r`8 books on a shelf include a 3-volume trilogy that must stay together, in order or reversed. How many arrangements?` },
      { ask: r`A playlist of 5 pop and 2 jazz songs must play the 5 pop songs consecutively. How many playlists?` },
      { ask: r`4 adults and 3 children in a row; no two children are adjacent.` },
      { ask: r`Arrange the letters of NUMBER with N and R at the two ends.` },
      { ask: r`7 guests at a round table; two specific guests sit together.` },
      { ask: r`Arrange the letters of FLOWER so the word begins with a vowel.` },
      { ask: r`7 volumes on a shelf; two specific volumes must not be adjacent.` },
      { ask: r`3 couples around a round table; each couple sits together.` },
      { ask: r`6 charms arranged around a circular bracelet (use $(n-1)!$).` },
      { ask: r`4 men and 4 women stand in a row, alternating by gender.`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`$5!\cdot2!=240$`, r`$720-240=480$`, r`$4!=24$`, r`$6!\cdot2!=1440$`, r`$3!\cdot5!=720$`, r`$4!\cdot{}_5P_3=1440$`, r`$2!\cdot4!=48$`, r`$5!\cdot2!=240$`, r`$2\cdot5!=240$`, r`$7!-6!\cdot2!=3600$`, r`$(3-1)!\cdot2!^3=16$`, r`$(6-1)!=120$`, r`$2\cdot4!\cdot4!=1152$`],
  },
  {
    code: "1.5", unit: U, title: "Combinations",
    intro: r`When order does \emph{not} matter, count selections with $_nC_r=\dbinom{n}{r}=\dfrac{n!}{r!\,(n-r)!}$. Contrast with $_nP_r=r!\dbinom{n}{r}$ when order \emph{does} matter.`,
    ideas: [r`Combination $=$ unordered selection: $\dbinom{n}{r}$.`, r`Multiply the choices when selecting from several groups at once.`, r`Symmetry $\dbinom{n}{r}=\dbinom{n}{n-r}$; and $_nP_r=r!\dbinom{n}{r}$.`],
    examples: [
      { t: "Basic combination", body: r`Compute $\dbinom{8}{3}$.\soln $\dfrac{8\cdot7\cdot6}{3!}=56$.` },
      { t: "Choose a squad", body: r`Choose 5 starters from 12 players.\soln $\dbinom{12}{5}=792$.` },
      { t: "Handshakes (pairs)", body: r`How many handshakes among 8 people (each pair once)?\soln $\dbinom{8}{2}=28$ --- one per pair.` },
      { t: "Two groups at once", body: r`Choose 2 of 6 men and 3 of 5 women.\soln $\dbinom{6}{2}\dbinom{5}{3}=15\cdot10=150$.` },
      { t: "Diagonals of a polygon", body: r`How many diagonals does an octagon have?\soln $\dbinom{8}{2}-8=28-8=20$ (subtract the 8 sides).` },
      { t: "Triangles from points", body: r`From 10 points, no 3 collinear, how many triangles?\soln Each set of 3 points makes one triangle: $\dbinom{10}{3}=120$.` },
      { t: "Symmetry shortcut", body: r`Compute $\dbinom{15}{13}$.\soln $\dbinom{15}{13}=\dbinom{15}{2}=105$.` },
      { t: "Combination vs. permutation", body: r`From 9 books, \\ \textbf{(a)} choose 4 for a bag; \\ \textbf{(b)} arrange 4 on a shelf.\soln (a) $\dbinom{9}{4}=126$. (b) $_9P_4=4!\dbinom{9}{4}=3024$.` },
      { t: "Any, then a condition", body: r`A 4-person committee from 7 men and 5 women. \\ \textbf{(a)} any committee; \\ \textbf{(b)} exactly 2 women.\soln (a) $\dbinom{12}{4}=495$. (b) $\dbinom{5}{2}\dbinom{7}{2}=10\cdot21=210$.` },
    ],
    questions: [
      { ask: r`Compute $\dbinom{7}{2}$.` },
      { ask: r`Compute $\dbinom{10}{4}$.` },
      { ask: r`How many ways to choose 4 books from 9?` },
      { ask: r`How many handshakes among 12 people?` },
      { ask: r`Choose 3 of 7 boys and 2 of 5 girls.` },
      { ask: r`Compute $\dbinom{20}{18}$.` },
      { ask: r`How many diagonals does a decagon (10-gon) have?` },
      { ask: r`From 10 points, no 3 collinear, how many triangles?` },
      { ask: r`Ways to pick 6 numbers from 49 in a lottery?` },
      { ask: r`A pizza uses exactly 3 of 8 toppings. How many pizzas?` },
      { ask: r`From 10 students, \\ \textbf{(a)} choose 3 for a test; \\ \textbf{(b)} award gold, silver, bronze.` },
      { ask: r`From 15 players, how many possible starting fives?` },
      { ask: r`A team of 5 from 7 forwards and 4 defenders with exactly 3 forwards.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$21$`, r`$210$`, r`$\dbinom{9}{4}=126$`, r`$\dbinom{12}{2}=66$`, r`$35\cdot10=350$`, r`$\dbinom{20}{2}=190$`, r`$\dbinom{10}{2}-10=35$`, r`$\dbinom{10}{3}=120$`, r`$\dbinom{49}{6}=13\,983\,816$`, r`$\dbinom{8}{3}=56$`, r`(a) $\dbinom{10}{3}=120$; (b) $_{10}P_3=720$`, r`$\dbinom{15}{5}=3003$`, r`$\dbinom{7}{3}\dbinom{4}{2}=35\cdot6=210$`],
  },
  {
    code: "1.6", unit: U, title: "Combinations with Cases & the Complement",
    intro: r`Rich selection problems combine moves: split into disjoint \emph{cases} and add, or subtract the unwanted (the \emph{complement}); \emph{choose then arrange} when order matters after selecting; and fix required or forbidden members before counting.`,
    ideas: [r`Direct: break \emph{at least}/\emph{at most} into disjoint cases and add (rule of sum).`, r`Indirect: when the cases pile up, count $\text{total}-\text{unwanted}$ (the complement).`, r`Choose \emph{then} arrange: $\dbinom{n}{r}\cdot r!={}_nP_r$ pairs a selection with its orderings.`, r`Lock in required members and delete forbidden ones \emph{before} you count.`],
    examples: [
      { t: "Direct method: cases and the rule of sum", body: r`A 4-person fundraising committee is chosen from 5 seniors and 4 juniors and must include \emph{at least 2 seniors}. How many committees are possible?\soln Split into disjoint cases on the number of seniors, then add. \emph{2 seniors:} $\dbinom{5}{2}\dbinom{4}{2}=10\cdot6=60$. \emph{3 seniors:} $\dbinom{5}{3}\dbinom{4}{1}=10\cdot4=40$. \emph{4 seniors:} $\dbinom{5}{4}\dbinom{4}{0}=5$. By the rule of sum, $60+40+5=105$.` },
      { t: "Indirect method: the complement", body: r`The same committee (4 from 5 seniors, 4 juniors) must now include \emph{at least 1 senior}. Find a faster route than cases.\soln A direct count needs four cases; instead subtract the one unwanted outcome (\emph{all juniors}) from the total: $\dbinom{9}{4}-\dbinom{4}{4}=126-1=125$. \emph{When the cases pile up, the complement wins.}` },
      { t: "Choose, then arrange", body: r`A DJ builds a set from 3 of 7 pop tracks and 2 of 5 rock tracks, then plays all 5 tracks in some order. How many different sets are possible?\soln First \emph{choose} the tracks, then \emph{arrange} them: $\dbinom{7}{3}\dbinom{5}{2}\times5!=35\cdot10\cdot120=42\,000$.` },
      { t: "Combination vs. permutation", body: r`Twenty runners enter a race. In how many ways can (a) 3 be picked for a random drug test, (b) the gold, silver, and bronze medals be awarded?\soln (a) Order is irrelevant: $\dbinom{20}{3}=1140$. (b) Order matters: $_{20}P_3=6840=3!\cdot\dbinom{20}{3}$.` },
      { t: "Selecting from two groups (exactly)", body: r`A 5-person club is chosen from 8 boys and 4 girls with \emph{exactly} 3 boys. How many clubs?\soln $\dbinom{8}{3}\dbinom{4}{2}=56\cdot6=336$.` },
      { t: "Required and forbidden members", body: r`A relay squad of 4 is picked from 12 athletes, but the captain \emph{must} be included and 2 injured athletes \emph{cannot} be. How many squads?\soln Place the captain, remove the 2 injured, then choose 3 from the other 9: $\dbinom{9}{3}=84$.` },
      { t: "At least one (complement, cards)", body: r`How many 5-card hands from a standard deck contain at least one ace?\soln Total $-$ no aces: $\dbinom{52}{5}-\dbinom{48}{5}=886\,656$.` },
      { t: "Counting subsets (how many totals)", body: r`A wallet holds a \$5, a \$10, a \$20, and a \$50 bill. How many different non-zero amounts can be made by choosing some of the bills?\soln Each bill is in or out, and every subset gives a different total: $2^4-1=15$.` },
      { t: "A layered hand: exactly one pair", body: r`How many 5-card hands are exactly one pair?\soln Pair's rank $13$ and its two suits $\dbinom{4}{2}$; three other ranks $\dbinom{12}{3}$, one suit each $4^3$: $13\dbinom{4}{2}\dbinom{12}{3}4^3=1\,098\,240$.` },
    ],
    questions: [
      { ask: r`From 8 people, how many 3-person committees \emph{exclude} one particular person?` },
      { ask: r`From 7 women and 5 men, how many ways to choose 3 women and 2 men for a panel?` },
      { ask: r`A pizzeria offers 9 toppings. How many pizzas have exactly 3 toppings?` },
      { ask: r`A reading club of 5 is formed from 7 women and 4 men with at least 3 women. How many clubs?` },
      { ask: r`A coach chooses 4 of 9 sprinters and assigns them to legs 1--4 of a relay. How many line-ups? (Choose, then arrange.)` },
      { ask: r`Twenty raffle tickets are drawn for 3 prizes. How many results if the prizes are \\ \textbf{(a)} identical, \\ \textbf{(b)} a 1st, 2nd, and 3rd prize?` },
      { ask: r`A test has 12 questions; you answer exactly 8, and question 1 is compulsory. How many ways to pick your questions?` },
      { ask: r`A teacher splits 10 distinct books, giving 3 to Alia and 4 to Ben (keeping the rest). In how many ways?` },
      { ask: r`An ice-cream sundae takes at least one of 8 available toppings. How many sundaes?` },
      { ask: r`From 20 books (12 fiction, 8 non-fiction), how many ways to choose 5 with at least one non-fiction?` },
      { ask: r`12 points lie on a circle. How many \\ \textbf{(a)} chords (segments joining two points), \\ \textbf{(b)} triangles with vertices among the points can be drawn?` },
      { ask: r`How many positive divisors does $1200$ have? (Hint: $1200=2^4\cdot3\cdot5^2$.)` },
      { ask: r`From a standard 52-card deck, how many 5-card hands are exactly \emph{two pair}?`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$\dbinom{7}{3}=35$`, r`$\dbinom{7}{3}\dbinom{5}{2}=35\cdot10=350$`, r`$\dbinom{9}{3}=84$`, r`$\dbinom{7}{3}\dbinom{4}{2}+\dbinom{7}{4}\dbinom{4}{1}+\dbinom{7}{5}=210+140+21=371$`, r`$\dbinom{9}{4}\cdot4!=126\cdot24=3024$`, r`(a) $\dbinom{20}{3}=1140$; (b) $_{20}P_3=6840$`, r`$\dbinom{11}{7}=330$`, r`$\dbinom{10}{3}\dbinom{7}{4}=120\cdot35=4200$`, r`$2^8-1=255$`, r`$\dbinom{20}{5}-\dbinom{12}{5}=14\,712$`, r`(a) $\dbinom{12}{2}=66$; (b) $\dbinom{12}{3}=220$`, r`$(4{+}1)(1{+}1)(2{+}1)=30$`, r`$\dbinom{13}{2}\dbinom{4}{2}^2\cdot44=123\,552$`],
  },
  {
    code: "1.7", unit: U, title: "Pascal's Triangle & Combinatorial Identities",
    intro: r`Each entry of Pascal's triangle is $\dbinom{n}{r}$. Pascal's identity $\dbinom{n}{r}=\dbinom{n-1}{r-1}+\dbinom{n-1}{r}$ builds each from the two above; row $n$ sums to $2^n$.`,
    ideas: [r`Entry in row $n$, position $r$ (from 0) is $\dbinom{n}{r}$.`, r`Pascal's identity: $\dbinom{n}{r}=\dbinom{n-1}{r-1}+\dbinom{n-1}{r}$.`, r`Row sum $=2^n$; alternating row sum $=0$; hockey-stick along a diagonal.`],
    examples: [
      { t: "Write a row", body: r`Write row 5 of Pascal's triangle.\soln $1,\,5,\,10,\,10,\,5,\,1$ --- these are $\dbinom{5}{0}\dots\dbinom{5}{5}$.` },
      { t: "Pascal's identity", body: r`Verify $\dbinom{7}{3}=\dbinom{6}{2}+\dbinom{6}{3}$.\soln $15+20=35=\dbinom{7}{3}$.` },
      { t: "Row sum", body: r`What is the sum of the entries in row 6?\soln $2^6=64$ --- the number of subsets of a 6-set.` },
      { t: "Build a large entry", body: r`Use Pascal's identity for $\dbinom{10}{4}$.\soln $\dbinom{9}{3}+\dbinom{9}{4}=84+126=210$.` },
      { t: "Hockey-stick (diagonal sum)", body: r`Evaluate $\dbinom{2}{2}+\dbinom{3}{2}+\dbinom{4}{2}$.\soln $1+3+6=10=\dbinom{5}{3}$.` },
      { t: "Symmetry", body: r`Simplify $\dbinom{9}{7}$.\soln $\dbinom{9}{7}=\dbinom{9}{2}=36$.` },
      { t: "Alternating sum", body: r`Evaluate $\dbinom{4}{0}-\dbinom{4}{1}+\dbinom{4}{2}-\dbinom{4}{3}+\dbinom{4}{4}$.\soln $1-4+6-4+1=0$.` },
      { t: "Paths as Pascal entries", body: r`How many shortest grid routes reach the cell 3 right and 2 up?\soln $\dbinom{5}{2}=10$ --- exactly a Pascal entry.` },
      { t: "Sum of squares (Vandermonde)", body: r`Evaluate $\dbinom{4}{0}^2+\dbinom{4}{1}^2+\dbinom{4}{2}^2+\dbinom{4}{3}^2+\dbinom{4}{4}^2$.\soln $1+16+36+16+1=70=\dbinom{8}{4}$.` },
    ],
    questions: [
      { ask: r`Write row 4 of Pascal's triangle.` },
      { ask: r`Use Pascal's identity to find $\dbinom{8}{3}$ from row 7.` },
      { ask: r`What is the sum of the entries in row 7?` },
      { ask: r`Find $\dbinom{12}{5}$ using $\dbinom{11}{4}+\dbinom{11}{5}$.` },
      { ask: r`Which entry equals $\dbinom{10}{7}$?` },
      { ask: r`Evaluate the alternating sum of row 5.` },
      { ask: r`How many subsets does a 6-element set have?` },
      { ask: r`Evaluate $\dbinom{2}{2}+\dbinom{3}{2}+\dbinom{4}{2}+\dbinom{5}{2}$.` },
      { ask: r`State $\dbinom{n}{0}+\dbinom{n}{1}+\cdots+\dbinom{n}{n}$.` },
      { ask: r`Find the 3rd entry (position $r=2$) of row 9.` },
      { ask: r`How many shortest grid routes reach the cell 4 right and 3 up?` },
      { ask: r`How many subsets of size $\ge1$ does a 5-element set have?` },
      { ask: r`Evaluate $\dbinom{4}{0}^2+\dbinom{4}{1}^2+\dbinom{4}{2}^2+\dbinom{4}{3}^2+\dbinom{4}{4}^2$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$1,4,6,4,1$`, r`$\dbinom{7}{2}+\dbinom{7}{3}=21+35=56$`, r`$2^7=128$`, r`$330+462=792$`, r`$\dbinom{10}{3}=120$`, r`$0$`, r`$2^6=64$`, r`$\dbinom{6}{3}=20$`, r`$2^n$`, r`$\dbinom{9}{2}=36$`, r`$\dbinom{7}{3}=35$`, r`$2^5-1=31$`, r`$\dbinom{8}{4}=70$`],
  },
  {
    code: "1.8", unit: U, title: "The Binomial Theorem",
    intro: r`$(a+b)^n=\displaystyle\sum_{k=0}^{n}\dbinom{n}{k}a^{n-k}b^{k}$. The general term is $T_{k+1}=\dbinom{n}{k}a^{n-k}b^{k}$ --- set the exponent of $x$ to pull out any single term.`,
    ideas: [r`$(a+b)^n=\sum_{k=0}^{n}\dbinom{n}{k}a^{n-k}b^{k}$; the expansion has $n+1$ terms.`, r`General term $T_{k+1}=\dbinom{n}{k}a^{n-k}b^{k}$.`, r`For a specific power (or the constant term), solve the exponent equation for $k$; set $x=1$ for the sum of coefficients.`],
    examples: [
      { t: "Full expansion", body: r`Expand $(x+2)^4$.\soln $x^4+8x^3+24x^2+32x+16$.` },
      { t: "Specific term", body: r`Find the term in $x^2$ of $(x+3)^5$.\soln $T=\dbinom{5}{k}x^{5-k}3^{k}$; $5-k=2\Rightarrow k=3$: $\dbinom{5}{3}3^3x^2=270x^2$.` },
      { t: "Coefficient with a factor", body: r`Coefficient of $x^3$ in $(2x-1)^5$.\soln $5-k=3\Rightarrow k=2$: $\dbinom{5}{2}(2)^3(-1)^2=80$.` },
      { t: "Constant term", body: r`Constant term of $\left(x+\dfrac1x\right)^6$.\soln $\dbinom{6}{k}x^{6-2k}$; $6-2k=0\Rightarrow k=3$: $\dbinom{6}{3}=20$.` },
      { t: "Middle term", body: r`Middle term of $(a+b)^8$.\soln $k=4$: $\dbinom{8}{4}a^4b^4=70a^4b^4$.` },
      { t: "Sum of coefficients", body: r`Sum of the coefficients of $(2x+3)^4$.\soln Set $x=1$: $5^4=625$.` },
      { t: "Negative sign", body: r`Expand $(1-x)^3$.\soln $1-3x+3x^2-x^3$.` },
      { t: "Power inside", body: r`Coefficient of $x^4$ in $(x^2+2)^5$.\soln $\dbinom{5}{k}2^{k}x^{10-2k}$; $10-2k=4\Rightarrow k=3$: $\dbinom{5}{3}2^3=80$.` },
      { t: "Mixed powers", body: r`Term containing $x^5$ in $\left(x-\dfrac2x\right)^7$.\soln $\dbinom{7}{k}(-2)^{k}x^{7-2k}$; $7-2k=5\Rightarrow k=1$: $\dbinom{7}{1}(-2)x^5=-14x^5$.` },
    ],
    questions: [
      { ask: r`Expand $(x+1)^4$.` },
      { ask: r`Expand $(x-2)^3$.` },
      { ask: r`Coefficient of $x^2$ in $(x+3)^4$.` },
      { ask: r`Find the term in $x^3$ of $(2x+1)^5$.` },
      { ask: r`Constant term of $\left(x+\dfrac1x\right)^4$.` },
      { ask: r`Middle term of $(a+b)^6$.` },
      { ask: r`Sum of the coefficients of $(3x-2)^5$.` },
      { ask: r`Constant term of $\left(x^2+\dfrac1x\right)^6$.` },
      { ask: r`Coefficient of $x^4$ in $(1+x)^7$.` },
      { ask: r`Expand $(2x-1)^3$.` },
      { ask: r`How many terms are in the expansion of $(a+b)^{10}$?` },
      { ask: r`Coefficient of $x^6$ in $(x+2)^9$.` },
      { ask: r`Find the term independent of $x$ in $\left(2x-\dfrac{3}{x^2}\right)^6$.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$x^4+4x^3+6x^2+4x+1$`, r`$x^3-6x^2+12x-8$`, r`$\dbinom{4}{2}3^2=54$`, r`$\dbinom{5}{2}(2x)^3=80x^3$`, r`$\dbinom{4}{2}=6$`, r`$\dbinom{6}{3}a^3b^3=20a^3b^3$`, r`$1^5=1$`, r`$\dbinom{6}{4}=15$`, r`$\dbinom{7}{4}=35$`, r`$8x^3-12x^2+6x-1$`, r`$11$`, r`$\dbinom{9}{3}2^3=672$`, r`$\dbinom{6}{2}2^4(-3)^2=2160$`],
  },
];
