// MDM4U Unit 2 worksheets — Probability.
// Textbook-level depth: sample spaces, counting-based probability, odds/complement,
// additive & multiplicative rules, conditional probability, trees. Each example and
// question a distinct idea. 9 worked examples + 13 questions + answer key each.
const r = String.raw;
const U = "2: Probability";

export default [
  {
    code: "2.1", unit: U, title: "Introduction to Probability",
    intro: r`For equally likely outcomes, $P(A)=\dfrac{n(A)}{n(S)}$, a number in $[0,1]$. \emph{Theoretical} probability is counted, \emph{experimental} is measured from trials, and \emph{subjective} is judged.`,
    ideas: [r`Sample space $S$ lists all outcomes; an event $A$ is a subset.`, r`$P(A)=\dfrac{n(A)}{n(S)}$ (equally likely); complement $P(A')=1-P(A)$.`, r`Theoretical vs. experimental vs. subjective probability; $0\le P\le1$.`],
    examples: [
      { t: "Sample space of two dice", body: r`Two dice are rolled. Find $P(\text{sum}=7)$.\soln $n(S)=36$. Sums of 7: $(1,6),(2,5),(3,4),(4,3),(5,2),(6,1)$, so $n(A)=6$. $P=\dfrac{6}{36}=\dfrac16$.` },
      { t: "An event on one die", body: r`A die is rolled. Find $P(\text{prime})$.\soln Primes are $\{2,3,5\}$: $P=\dfrac36=\dfrac12$.` },
      { t: "A card event", body: r`One card is drawn from a standard deck. Find $P(\text{face card})$.\soln $12$ face cards: $P=\dfrac{12}{52}=\dfrac{3}{13}$.` },
      { t: "Experimental vs. theoretical", body: r`A die is rolled 200 times and shows a 3 on 44 rolls. Compare the experimental and theoretical probabilities.\soln Experimental $=\dfrac{44}{200}=0.22$; theoretical $=\dfrac16\approx0.167$. Close, as expected for many trials.` },
      { t: "Complement", body: r`Find $P(\text{not a heart})$ for one card.\soln $1-\dfrac{13}{52}=\dfrac{39}{52}=\dfrac34$.` },
      { t: "Two coins", body: r`Two coins are tossed. Find $P(\text{exactly one head})$.\soln $S=\{HH,HT,TH,TT\}$; favourable $\{HT,TH\}$: $P=\dfrac24=\dfrac12$.` },
      { t: "Unequal spinner", body: r`A spinner has 8 equal wedges: 4 red, 3 blue, 1 green. Find $P(\text{blue})$.\soln $P=\dfrac38$.` },
      { t: "Classify the probability", body: r`Classify each as theoretical, experimental, or subjective: \\ \textbf{(a)} $P(\text{ace})=\tfrac{1}{13}$; \\ \textbf{(b)} 63 of 150 tacks land point-up; \\ \textbf{(c)} a forecaster's 70\% chance of rain.\soln (a) theoretical; (b) experimental; (c) subjective.` },
      { t: "Valid probabilities", body: r`Which are valid probabilities: $-0.2,\ 0.5,\ 1.3,\ \tfrac34$?\soln Only $0.5$ and $\tfrac34$: a probability must lie in $[0,1]$.` },
    ],
    questions: [
      { ask: r`Two dice are rolled. Find $P(\text{sum}=8)$.` },
      { ask: r`A die is rolled. Find $P(\text{number}>4)$.` },
      { ask: r`One card is drawn. Find $P(\text{red king})$.` },
      { ask: r`A bag has 5 red, 3 blue, and 2 green marbles. Find $P(\text{green})$.` },
      { ask: r`Find $P(\text{not rolling a 6})$ on one die.` },
      { ask: r`Two coins are tossed. Find $P(\text{at least one tail})$.` },
      { ask: r`A spinner has 8 equal wedges, 3 marked \emph{win}. Find $P(\text{win})$.` },
      { ask: r`A thumbtack lands point-up on 63 of 150 tosses. State the experimental probability.` },
      { ask: r`Classify this statement: \emph{There is a 40\% chance our team wins tomorrow.}` },
      { ask: r`Which are valid probabilities: $-0.1,\ 0,\ 0.75,\ 1,\ 1.5$?` },
      { ask: r`One card is drawn. Find $P(\text{a heart or the ace of spades})$.` },
      { ask: r`Two dice are rolled. Find $P(\text{a double})$.` },
      { ask: r`Three coins are tossed. \\ \textbf{(a)} How many outcomes? \\ \textbf{(b)} $P(\text{exactly two heads})$; \\ \textbf{(c)} $P(\text{at least one head})$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\tfrac{5}{36}$`, r`$\tfrac26=\tfrac13$`, r`$\tfrac{2}{52}=\tfrac{1}{26}$`, r`$\tfrac{2}{10}=\tfrac15$`, r`$\tfrac56$`, r`$\tfrac34$`, r`$\tfrac38$`, r`$\tfrac{63}{150}=0.42$`, r`subjective`, r`$0,\ 0.75,\ 1$`, r`$\tfrac{14}{52}=\tfrac{7}{26}$`, r`$\tfrac{6}{36}=\tfrac16$`, r`(a) $8$; (b) $\tfrac38$; (c) $\tfrac78$`],
  },
  {
    code: "2.2", unit: U, title: "Counting & Probability",
    intro: r`For equally likely outcomes, $P(A)=\dfrac{n(A)}{n(S)}$ where \emph{both} counts come from permutations or combinations. Use the complement for \emph{at least}.`,
    ideas: [r`Unordered draws: count with $\dbinom{n}{r}$; ordered: with $_nP_r$.`, r`$P=\dfrac{\text{favourable count}}{\text{total count}}$.`, r`$P(\text{at least one})=1-P(\text{none})$.`],
    examples: [
      { t: "Choosing a committee", body: r`A committee of 3 is chosen from 5 men and 4 women. Find $P(\text{all women})$.\soln $\dfrac{\dbinom{4}{3}}{\dbinom{9}{3}}=\dfrac{4}{84}=\dfrac{1}{21}$.` },
      { t: "A card hand", body: r`Find $P(\text{a 5-card hand is all hearts})$.\soln $\dfrac{\dbinom{13}{5}}{\dbinom{52}{5}}=\dfrac{1287}{2\,598\,960}\approx0.000495$.` },
      { t: "Arrangement probability", body: r`5 people sit in a row at random. Find $P(\text{two specific people are adjacent})$.\soln $\dfrac{4!\cdot2!}{5!}=\dfrac{48}{120}=\dfrac25$.` },
      { t: "At least one (complement)", body: r`Find $P(\text{a 5-card hand has at least one ace})$.\soln $1-\dfrac{\dbinom{48}{5}}{\dbinom{52}{5}}\approx1-0.659=0.341$.` },
      { t: "Exactly $k$ of a type", body: r`Draw 4 from 8 boys and 4 girls. Find $P(\text{exactly 2 girls})$.\soln $\dfrac{\dbinom{4}{2}\dbinom{8}{2}}{\dbinom{12}{4}}=\dfrac{6\cdot28}{495}=\dfrac{168}{495}=\dfrac{56}{165}$.` },
      { t: "All distinct", body: r`Three people each pick a digit $0$--$9$ at random. Find $P(\text{all different})$.\soln $\dfrac{10\cdot9\cdot8}{10^3}=\dfrac{720}{1000}=0.72$.` },
      { t: "Lottery", body: r`In a 6/49 lottery, find $P(\text{match all 6})$ and $P(\text{match exactly 5})$.\soln $P(6)=\dfrac{1}{\dbinom{49}{6}}$; $P(5)=\dfrac{\dbinom{6}{5}\dbinom{43}{1}}{\dbinom{49}{6}}=\dfrac{258}{13\,983\,816}$.` },
      { t: "Word arrangement", body: r`The letters of BANANA are arranged at random. Find $P(\text{it starts with B})$.\soln Total $\dfrac{6!}{3!2!}=60$; starting with B: $\dfrac{5!}{3!2!}=10$; $P=\dfrac{10}{60}=\dfrac16$.` },
      { t: "Two-part committee", body: r`Choose 4 from 6 seniors and 4 juniors. \\ \textbf{(a)} $P(\text{all seniors})$; \\ \textbf{(b)} $P(\text{at least one junior})$.\soln (a) $\dfrac{\dbinom{6}{4}}{\dbinom{10}{4}}=\dfrac{15}{210}=\dfrac{1}{14}$. (b) $1-\dfrac{1}{14}=\dfrac{13}{14}$.` },
    ],
    questions: [
      { ask: r`A committee of 3 is chosen from 4 men and 5 women. Find $P(\text{all men})$.` },
      { ask: r`Find $P(\text{a 5-card hand is all spades})$.` },
      { ask: r`4 people sit in a row at random. Find $P(\text{two specific are together})$.` },
      { ask: r`Draw 3 from 7 red and 3 green marbles. Find $P(\text{exactly 1 green})$.` },
      { ask: r`Find $P(\text{a 5-card hand has at least one king})$.` },
      { ask: r`Three digits $0$--$9$ are chosen with repetition. Find $P(\text{all the same})$.` },
      { ask: r`6 finalists are randomly awarded gold, silver, bronze. Find $P(\text{a specific person wins gold})$.` },
      { ask: r`The letters of LEVEL are arranged at random. Find $P(\text{it starts with V})$.` },
      { ask: r`In a 6/49 lottery, find $P(\text{match exactly 4})$.` },
      { ask: r`Choose 4 from 5 seniors and 4 juniors. Find $P(\text{exactly 2 of each})$.` },
      { ask: r`Three people each pick a day of the week at random. Find $P(\text{all different})$.` },
      { ask: r`Find $P(\text{a 5-card hand is 3 aces and 2 kings})$.` },
      { ask: r`8 people are seated at random around a round table. Find $P(\text{two specific people sit together})$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\dfrac{\binom{4}{3}}{\binom{9}{3}}=\tfrac{4}{84}=\tfrac{1}{21}$`, r`$\dfrac{\binom{13}{5}}{\binom{52}{5}}=\tfrac{1287}{2\,598\,960}$`, r`$\tfrac{3!\,2!}{4!}=\tfrac{12}{24}=\tfrac12$`, r`$\dfrac{\binom{3}{1}\binom{7}{2}}{\binom{10}{3}}=\tfrac{63}{120}=\tfrac{21}{40}$`, r`$1-\dfrac{\binom{48}{5}}{\binom{52}{5}}\approx0.341$`, r`$\tfrac{10}{1000}=\tfrac{1}{100}$`, r`$\tfrac16$`, r`$\dfrac{4!/(2!2!)}{5!/(2!2!)}=\tfrac{6}{30}=\tfrac15$`, r`$\dfrac{\binom{6}{4}\binom{43}{2}}{\binom{49}{6}}$`, r`$\dfrac{\binom{5}{2}\binom{4}{2}}{\binom{9}{4}}=\tfrac{60}{126}=\tfrac{10}{21}$`, r`$\tfrac{7\cdot6\cdot5}{7^3}=\tfrac{210}{343}=\tfrac{30}{49}$`, r`$\dfrac{\binom{4}{3}\binom{4}{2}}{\binom{52}{5}}=\tfrac{24}{2\,598\,960}$`, r`$\dfrac{6!\cdot2!}{7!}=\tfrac{1440}{5040}=\tfrac27$`],
  },
  {
    code: "2.3", unit: U, title: "Odds & the Complement",
    intro: r`Odds in favour $a:b$ correspond to $P=\dfrac{a}{a+b}$. The complement $P(A')=1-P(A)$ turns hard \emph{at least} events into easy \emph{none} events.`,
    ideas: [r`Odds in favour $a:b\Leftrightarrow P=\dfrac{a}{a+b}$; odds against $=b:a$.`, r`$P(A')=1-P(A)$.`, r`$P(\text{at least one})=1-P(\text{none})$.`],
    examples: [
      { t: "Odds to probability", body: r`The odds in favour of an event are $3:2$. Find $P$.\soln $P=\dfrac{3}{3+2}=\dfrac35$.` },
      { t: "Probability to odds", body: r`If $P(A)=\dfrac14$, state the odds in favour and against.\soln In favour $1:3$; against $3:1$.` },
      { t: "At least one (complement)", body: r`Three coins are tossed. Find $P(\text{at least one head})$.\soln $1-P(\text{no heads})=1-\dfrac18=\dfrac78$.` },
      { t: "Odds against from a deck", body: r`State the odds against drawing a heart.\soln $P(\text{not heart}):P(\text{heart})=\dfrac34:\dfrac14=3:1$.` },
      { t: "At least one 6", body: r`Two dice are rolled. Find $P(\text{at least one 6})$.\soln $1-\left(\dfrac56\right)^2=1-\dfrac{25}{36}=\dfrac{11}{36}$.` },
      { t: "Implied probability from payout odds", body: r`A horse has odds against of $5:1$. What is the implied probability of winning?\soln $P=\dfrac{1}{5+1}=\dfrac16$.` },
      { t: "Complement with combinations", body: r`4 items are drawn from 20, of which 3 are defective. Find $P(\text{at least one defective})$.\soln $1-\dfrac{\dbinom{17}{4}}{\dbinom{20}{4}}=1-\dfrac{2380}{4845}\approx0.509$.` },
      { t: "Compare two chances", body: r`Which is more likely: odds $4:3$ in favour, or $P=0.55$?\soln $4:3\Rightarrow\dfrac47\approx0.571>0.55$, so the odds are more likely.` },
      { t: "Two-part spinner", body: r`A spinner has $P(\text{win})=0.3$. \\ \textbf{(a)} odds in favour of winning; \\ \textbf{(b)} $P(\text{win at least once in 2 spins})$.\soln (a) $3:7$. (b) $1-0.7^2=0.51$.` },
    ],
    questions: [
      { ask: r`The odds in favour are $5:3$. Find $P$.` },
      { ask: r`If $P=\dfrac29$, state the odds in favour and against.` },
      { ask: r`Four coins are tossed. Find $P(\text{at least one tail})$.` },
      { ask: r`State the odds against rolling a prime on one die.` },
      { ask: r`Two dice are rolled. Find $P(\text{at least one 5})$.` },
      { ask: r`A team's odds against winning are $7:2$. Find the implied $P(\text{win})$.` },
      { ask: r`From 20 items with 3 defective, draw 4. Find $P(\text{at least one defective})$.` },
      { ask: r`Which is more likely: odds $3:2$ in favour, or $P=0.65$?` },
      { ask: r`Three dice are rolled. Find $P(\text{no 6})$, then $P(\text{at least one 6})$.` },
      { ask: r`The odds in favour are $9:11$. Find $P$.` },
      { ask: r`If $P(\text{red})=0.4$, state the odds against red.` },
      { ask: r`Two cards are drawn without replacement. Find $P(\text{at least one ace})$ using the complement.` },
      { ask: r`Each round, the odds against winning are $7:3$ (rounds independent). Find $P(\text{win at least once in 3 rounds})$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\tfrac58$`, r`$2:7$ and $7:2$`, r`$1-\tfrac{1}{16}=\tfrac{15}{16}$`, r`$1:1$ (since $P(\text{prime})=\tfrac12$)`, r`$1-\left(\tfrac56\right)^2=\tfrac{11}{36}$`, r`$\tfrac29$`, r`$1-\dfrac{\binom{17}{4}}{\binom{20}{4}}\approx0.509$`, r`$3:2=0.6<0.65$, so $P=0.65$`, r`$\left(\tfrac56\right)^3=\tfrac{125}{216}$; then $\tfrac{91}{216}$`, r`$\tfrac{9}{20}$`, r`$6:4=3:2$`, r`$1-\tfrac{48}{52}\cdot\tfrac{47}{51}$`, r`$1-\left(\tfrac{7}{10}\right)^3=\tfrac{657}{1000}$`],
  },
  {
    code: "2.4", unit: U, title: "Mutually Exclusive Events & the Additive Rule",
    intro: r`In general $P(A\cup B)=P(A)+P(B)-P(A\cap B)$. When $A$ and $B$ are \emph{mutually exclusive} ($A\cap B=\varnothing$) the overlap term is $0$.`,
    ideas: [r`Mutually exclusive: $P(A\cup B)=P(A)+P(B)$.`, r`General additive rule: subtract the overlap $P(A\cap B)$.`, r`Venn diagrams organize overlapping counts.`],
    examples: [
      { t: "Mutually exclusive", body: r`One die. Find $P(2\text{ or }5)$.\soln Disjoint: $\dfrac16+\dfrac16=\dfrac13$.` },
      { t: "Not mutually exclusive", body: r`One card. Find $P(\text{king or heart})$.\soln $\dfrac{4}{52}+\dfrac{13}{52}-\dfrac{1}{52}=\dfrac{16}{52}=\dfrac{4}{13}$.` },
      { t: "Venn counts", body: r`In a class of 30, 18 like math, 12 like art, 6 like both. Find $P(\text{math or art})$.\soln $\dfrac{18+12-6}{30}=\dfrac{24}{30}=\dfrac45$.` },
      { t: "Complement of a union", body: r`For the class above, find $P(\text{neither})$.\soln $1-\dfrac45=\dfrac15$.` },
      { t: "Disjoint dice sums", body: r`Two dice. Find $P(\text{sum }7\text{ or }11)$.\soln Disjoint: $\dfrac{6}{36}+\dfrac{2}{36}=\dfrac{8}{36}=\dfrac29$.` },
      { t: "Card overlap", body: r`One card. Find $P(\text{face card or spade})$.\soln $\dfrac{12}{52}+\dfrac{13}{52}-\dfrac{3}{52}=\dfrac{22}{52}=\dfrac{11}{26}$.` },
      { t: "Find the overlap", body: r`Given $P(A)=0.5,\ P(B)=0.4,\ P(A\cup B)=0.7$, find $P(A\cap B)$.\soln $0.7=0.5+0.4-P(A\cap B)\Rightarrow P(A\cap B)=0.2$.` },
      { t: "Check for mutual exclusivity", body: r`Are \emph{even} and \emph{prime} mutually exclusive on a die? Find $P(\text{even or prime})$.\soln They share $2$, so \emph{not} exclusive: $\dfrac36+\dfrac36-\dfrac16=\dfrac56$.` },
      { t: "Three-part survey", body: r`Of 100 people, 55 drink coffee, 40 tea, 15 both. Find \\ \textbf{(a)} $P(\text{coffee or tea})$; \\ \textbf{(b)} $P(\text{coffee only})$; \\ \textbf{(c)} $P(\text{neither})$.\soln (a) $\dfrac{55+40-15}{100}=0.8$. (b) $\dfrac{55-15}{100}=0.4$. (c) $0.2$.` },
    ],
    questions: [
      { ask: r`One die. Find $P(1\text{ or }4)$.` },
      { ask: r`One card. Find $P(\text{queen or diamond})$.` },
      { ask: r`Two dice. Find $P(\text{sum }5\text{ or }9)$.` },
      { ask: r`In a class of 25, 14 play soccer, 10 basketball, 5 both. Find $P(\text{soccer or basketball})$.` },
      { ask: r`For that class, find $P(\text{neither})$.` },
      { ask: r`One card. Find $P(\text{red or face card})$.` },
      { ask: r`$P(A)=0.6,\ P(B)=0.3$, mutually exclusive. Find $P(A\cup B)$.` },
      { ask: r`$P(A)=0.5,\ P(B)=0.5,\ P(A\cup B)=0.8$. Find $P(A\cap B)$.` },
      { ask: r`One die. Find $P(\text{odd or greater than }4)$.` },
      { ask: r`Two dice. Find $P(\text{a double or sum }6)$.` },
      { ask: r`Of 200 people, 120 own a car, 90 a bike, 40 both. Find $P(\text{car or bike})$.` },
      { ask: r`For those 200 people, find $P(\text{car only})$.` },
      { ask: r`One card. Find $P(\text{a spade, a king, or a queen})$ using inclusion--exclusion.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\tfrac13$`, r`$\tfrac{4+13-1}{52}=\tfrac{16}{52}=\tfrac{4}{13}$`, r`$\tfrac{4+4}{36}=\tfrac29$`, r`$\tfrac{19}{25}$`, r`$\tfrac{6}{25}$`, r`$\tfrac{26+12-6}{52}=\tfrac{32}{52}=\tfrac{8}{13}$`, r`$0.9$`, r`$0.2$`, r`$\tfrac{3+2-1}{6}=\tfrac46=\tfrac23$`, r`$\tfrac{6+5-1}{36}=\tfrac{10}{36}=\tfrac{5}{18}$`, r`$\tfrac{170}{200}=\tfrac{17}{20}$`, r`$\tfrac{80}{200}=\tfrac25$`, r`$\tfrac{13+4+4-1-1-0}{52}=\tfrac{19}{52}$`],
  },
  {
    code: "2.5", unit: U, title: "Independent & Dependent Events",
    intro: r`\emph{Independent} events multiply: $P(A\cap B)=P(A)P(B)$. \emph{Dependent} events (drawing without replacement) update the counts. Independence is \emph{not} the same as mutual exclusivity.`,
    ideas: [r`Independent \emph{and}: $P(A\cap B)=P(A)P(B)$.`, r`Dependent (no replacement): adjust the pool for the next draw.`, r`$P(\text{at least one})=1-P(\text{none})$ (independent trials).`],
    examples: [
      { t: "Independent coin and die", body: r`Find $P(\text{head and a 6})$.\soln $\dfrac12\cdot\dfrac16=\dfrac{1}{12}$.` },
      { t: "Dependent draw (no replacement)", body: r`Draw 2 cards without replacement. Find $P(\text{two aces})$.\soln $\dfrac{4}{52}\cdot\dfrac{3}{51}=\dfrac{12}{2652}=\dfrac{1}{221}$.` },
      { t: "With vs. without replacement", body: r`From 5 red and 3 blue, draw 2. Find $P(\text{both red})$ \\ \textbf{(a)} with replacement; \\ \textbf{(b)} without.\soln (a) $\left(\dfrac58\right)^2=\dfrac{25}{64}$. (b) $\dfrac58\cdot\dfrac47=\dfrac{20}{56}=\dfrac{5}{14}$.` },
      { t: "Independent chain", body: r`Find $P(\text{3 heads in a row})$.\soln $\left(\dfrac12\right)^3=\dfrac18$.` },
      { t: "One of each (no replacement)", body: r`A bag has 4 red and 6 blue. Draw 2 without replacement. Find $P(\text{one of each colour})$.\soln $\dfrac{4}{10}\cdot\dfrac69+\dfrac{6}{10}\cdot\dfrac49=\dfrac{24}{90}+\dfrac{24}{90}=\dfrac{48}{90}=\dfrac{8}{15}$.` },
      { t: "Test for independence", body: r`On one die, are \emph{even} and \emph{greater than 3} independent?\soln $P(\text{even}\cap{>}3)=P(\{4,6\})=\dfrac26=\dfrac13$, but $P(\text{even})P({>}3)=\dfrac12\cdot\dfrac12=\dfrac14\ne\dfrac13$. \emph{Not} independent.` },
      { t: "At least one via complement", body: r`Find $P(\text{at least one 6 in 3 rolls})$.\soln $1-\left(\dfrac56\right)^3=1-\dfrac{125}{216}=\dfrac{91}{216}$.` },
      { t: "System reliability", body: r`Two independent components each work with $P=0.9$. Find $P(\text{both work})$ and $P(\text{at least one works})$.\soln Both: $0.81$. At least one: $1-0.1^2=0.99$.` },
      { t: "Three-part jar", body: r`A jar has 3 green and 7 yellow; draw 2 without replacement. Find \\ \textbf{(a)} $P(\text{both green})$; \\ \textbf{(b)} $P(\text{no green})$; \\ \textbf{(c)} $P(\text{at least one green})$.\soln (a) $\dfrac{3}{10}\cdot\dfrac29=\dfrac{1}{15}$. (b) $\dfrac{7}{10}\cdot\dfrac69=\dfrac{7}{15}$. (c) $1-\dfrac{7}{15}=\dfrac{8}{15}$.` },
    ],
    questions: [
      { ask: r`Find $P(\text{three heads})$ when 3 coins are tossed.` },
      { ask: r`Two dice. Find $P(\text{both show 6})$.` },
      { ask: r`Draw 2 cards without replacement. Find $P(\text{both hearts})$.` },
      { ask: r`Bag of 5 red and 5 blue; draw 2 without replacement. Find $P(\text{both red})$.` },
      { ask: r`Same bag, but with replacement. Find $P(\text{both red})$.` },
      { ask: r`Find $P(\text{a 4 then an odd number})$ on two rolls.` },
      { ask: r`A spinner has $P(\text{win})=0.2$. Find $P(\text{win twice in a row})$.` },
      { ask: r`Two independent components each fail with $P=0.1$. Find $P(\text{both work})$.` },
      { ask: r`Draw 3 cards without replacement. Find $P(\text{all aces})$.` },
      { ask: r`On one die, are \emph{prime} and \emph{odd} independent? Justify.` },
      { ask: r`A jar of 2 green and 8 red; draw 2 without replacement. Find $P(\text{at least one green})$.` },
      { ask: r`Two dice. Find $P(\text{at least one 6})$.` },
      { ask: r`A test has 3 four-option questions answered by guessing. Find \\ \textbf{(a)} $P(\text{all correct})$; \\ \textbf{(b)} $P(\text{none correct})$; \\ \textbf{(c)} $P(\text{at least one correct})$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\tfrac18$`, r`$\tfrac{1}{36}$`, r`$\tfrac{13}{52}\cdot\tfrac{12}{51}=\tfrac{1}{17}$`, r`$\tfrac{5}{10}\cdot\tfrac49=\tfrac29$`, r`$\left(\tfrac12\right)^2=\tfrac14$`, r`$\tfrac16\cdot\tfrac12=\tfrac{1}{12}$`, r`$0.04$`, r`$0.9^2=0.81$`, r`$\tfrac{4}{52}\cdot\tfrac{3}{51}\cdot\tfrac{2}{50}=\tfrac{1}{5525}$`, r`No: $P(\{3,5\})=\tfrac13\ne\tfrac12\cdot\tfrac12=\tfrac14$`, r`$1-\tfrac{8}{10}\cdot\tfrac79=\tfrac{34}{90}=\tfrac{17}{45}$`, r`$1-\left(\tfrac56\right)^2=\tfrac{11}{36}$`, r`(a) $\tfrac{1}{64}$; (b) $\tfrac{27}{64}$; (c) $\tfrac{37}{64}$`],
  },
  {
    code: "2.6", unit: U, title: "Conditional Probability",
    intro: r`$P(A\mid B)=\dfrac{P(A\cap B)}{P(B)}$ restricts to the outcomes where $B$ happened. The product rule $P(A\cap B)=P(B)\,P(A\mid B)$ and two-way tables make it concrete.`,
    ideas: [r`$P(A\mid B)=\dfrac{P(A\cap B)}{P(B)}$ --- a reduced sample space.`, r`Product rule: $P(A\cap B)=P(B)P(A\mid B)$.`, r`Read conditions directly off a two-way table.`],
    examples: [
      { t: "Reduced sample space (cards)", body: r`Find $P(\text{king}\mid\text{face card})$.\soln $\dfrac{4/52}{12/52}=\dfrac{4}{12}=\dfrac13$.` },
      { t: "Two-way table", body: r`Of 100 people, 60 are female and 36 of them own a pet. Find $P(\text{owns pet}\mid\text{female})$.\soln $\dfrac{36}{60}=0.6$.` },
      { t: "Dependent second draw", body: r`Drawing without replacement, find $P(\text{2nd is an ace}\mid\text{1st was an ace})$.\soln $\dfrac{3}{51}=\dfrac{1}{17}$.` },
      { t: "Product rule", body: r`Find $P(\text{two kings in a row})$ without replacement.\soln $P(K_1)P(K_2\mid K_1)=\dfrac{4}{52}\cdot\dfrac{3}{51}=\dfrac{1}{221}$.` },
      { t: "Condition on one die", body: r`Two dice. Find $P(\text{sum}=8\mid\text{first die}=5)$.\soln Given first $=5$, need second $=3$: $\dfrac16$.` },
      { t: "Reduced space with counting", body: r`Two dice. Find $P(\text{sum}\ge10\mid\text{at least one 6})$.\soln The event \emph{at least one 6} has 11 outcomes; those with sum $\ge10$ are $(6,4),(4,6),(6,5),(5,6),(6,6)$: $\dfrac{5}{11}$.` },
      { t: "Natural frequencies (Bayes-lite)", body: r`1\% of people have a condition. A test is 90\% sensitive with a 5\% false-positive rate. Estimate $P(\text{condition}\mid\text{positive})$.\soln Per 1000: $10$ sick $\to9$ positive; $990$ healthy $\to\approx50$ positive. $P\approx\dfrac{9}{9+50}\approx0.15$.` },
      { t: "Reverse the condition", body: r`In a survey, 60 people own a pet and 36 of them are female. Find $P(\text{female}\mid\text{owns pet})$.\soln $\dfrac{36}{60}=0.6$.` },
      { t: "The two-child subtlety", body: r`A family has two children (each B/G equally likely). Find \\ \textbf{(a)} $P(\text{both girls}\mid\text{at least one girl})$; \\ \textbf{(b)} $P(\text{both girls}\mid\text{elder is a girl})$.\soln (a) $\{BG,GB,GG\}$: $\dfrac13$. (b) $\{GB,GG\}$: $\dfrac12$.` },
    ],
    questions: [
      { ask: r`Find $P(\text{queen}\mid\text{red card})$.` },
      { ask: r`Find $P(\text{heart}\mid\text{red card})$.` },
      { ask: r`Two dice. Find $P(\text{sum}=6\mid\text{first die}=2)$.` },
      { ask: r`Draw 2 without replacement. Find $P(\text{2nd is a spade}\mid\text{1st was a spade})$.` },
      { ask: r`50 students take French; 30 take French and 12 of those also take Spanish. Find $P(\text{Spanish}\mid\text{French})$.` },
      { ask: r`A jar of 4 red and 6 blue; draw 2 without replacement. Find $P(\text{2nd red}\mid\text{1st red})$.` },
      { ask: r`Two dice. Find $P(\text{a double}\mid\text{sum is even})$.` },
      { ask: r`From 5 red and 4 green, draw 2 without replacement. Find $P(\text{both red})$ via the product rule.` },
      { ask: r`A two-child family. Find $P(\text{both boys}\mid\text{at least one boy})$.` },
      { ask: r`Of 200 people, 120 own a phone and 90 of them own a laptop. Find $P(\text{laptop}\mid\text{phone})$.` },
      { ask: r`In that group, 100 own a laptop in total; find $P(\text{phone}\mid\text{laptop})$.` },
      { ask: r`Two dice. Find $P(\text{sum}\ge10\mid\text{at least one 6})$.` },
      { ask: r`A disease affects 2\% of people. A test is 95\% sensitive with a 10\% false-positive rate. Using 1000 people, estimate $P(\text{sick}\mid\text{positive})$.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$\tfrac{2}{26}=\tfrac{1}{13}$`, r`$\tfrac{13}{26}=\tfrac12$`, r`$\tfrac16$`, r`$\tfrac{12}{51}=\tfrac{4}{17}$`, r`$\tfrac{12}{30}=\tfrac25$`, r`$\tfrac39=\tfrac13$`, r`$\tfrac{6}{18}=\tfrac13$`, r`$\tfrac59\cdot\tfrac48=\tfrac{20}{72}=\tfrac{5}{18}$`, r`$\tfrac13$`, r`$\tfrac{90}{120}=\tfrac34$`, r`$\tfrac{90}{100}=\tfrac{9}{10}$`, r`$\tfrac{5}{11}$`, r`$\approx\tfrac{19}{19+98}=\tfrac{19}{117}\approx0.16$`],
  },
  {
    code: "2.7", unit: U, title: "Tree Diagrams & Probability Tables",
    intro: r`Multiply probabilities \emph{along} the branches of a tree and add \emph{across} disjoint paths. Trees handle multi-stage experiments; two-way tables organize joint outcomes.`,
    ideas: [r`Multiply along a branch (successive stages).`, r`Add the probabilities of disjoint paths to one outcome.`, r`Total probability: $P(E)=\sum P(\text{path to }E)$; reverse with a tree for $P(\text{cause}\mid E)$.`],
    examples: [
      { t: "Two-stage tree", body: r`Flip a coin; if heads, roll a die. Find $P(\text{heads and a 6})$.\soln Along the branch: $\dfrac12\cdot\dfrac16=\dfrac{1}{12}$.` },
      { t: "Without replacement", body: r`Draw 2 from 4 red and 3 blue. Find $P(\text{RR})$ and $P(\text{one of each})$.\soln $P(RR)=\dfrac47\cdot\dfrac36=\dfrac27$; one of each $=\dfrac47\cdot\dfrac36+\dfrac37\cdot\dfrac46=\dfrac{24}{42}=\dfrac47$.` },
      { t: "Total probability", body: r`60\% of parts come from factory A (2\% defective), 40\% from B (5\% defective). Find $P(\text{defective})$.\soln $0.6(0.02)+0.4(0.05)=0.012+0.020=0.032$.` },
      { t: "Reverse the tree (Bayes)", body: r`From the factories above, find $P(\text{from A}\mid\text{defective})$.\soln $\dfrac{0.012}{0.032}=\dfrac38$.` },
      { t: "Multi-stage independent", body: r`Three traffic lights are each green with $P=0.4$. Find $P(\text{all green})$ and $P(\text{exactly one green})$.\soln All: $0.4^3=0.064$. Exactly one: $\dbinom{3}{1}(0.4)(0.6)^2=3(0.4)(0.36)=0.432$.` },
      { t: "Weighted paths", body: r`70\% of students study (90\% pass); 30\% don't (40\% pass). Find $P(\text{pass})$.\soln $0.7(0.9)+0.3(0.4)=0.63+0.12=0.75$.` },
      { t: "Reverse the condition", body: r`From that quiz model, find $P(\text{studied}\mid\text{passed})$.\soln $\dfrac{0.63}{0.75}=0.84$.` },
      { t: "Table to joint probability", body: r`Of 100 people, 40 exercise and diet, 20 exercise only, 25 diet only, 15 neither. Find $P(\text{exercise or diet})$.\soln $\dfrac{40+20+25}{100}=0.85$.` },
      { t: "Three-draw urn", body: r`An urn has 5 white and 3 black; draw 3 without replacement. Find \\ \textbf{(a)} $P(\text{WWW})$; \\ \textbf{(b)} $P(\text{exactly 2 white})$.\soln (a) $\dfrac58\cdot\dfrac47\cdot\dfrac36=\dfrac{5}{28}$. (b) $\dfrac{\dbinom{5}{2}\dbinom{3}{1}}{\dbinom{8}{3}}=\dfrac{30}{56}=\dfrac{15}{28}$.` },
    ],
    questions: [
      { ask: r`Flip a coin, then roll a die. Find $P(\text{tails and an even number})$.` },
      { ask: r`Draw 2 without replacement from 3 red and 2 green. Find $P(\text{both red})$.` },
      { ask: r`For that draw, find $P(\text{one red and one green})$.` },
      { ask: r`70\% of parts are from A (3\% defective), 30\% from B (6\% defective). Find $P(\text{defective})$.` },
      { ask: r`For those parts, find $P(\text{from B}\mid\text{defective})$.` },
      { ask: r`Three lights are each green with $P=0.5$. Find $P(\text{all green})$.` },
      { ask: r`For those lights, find $P(\text{exactly two green})$.` },
      { ask: r`60\% of students are prepared (pass 0.9); 40\% are not (pass 0.3). Find $P(\text{pass})$.` },
      { ask: r`For that model, find $P(\text{prepared}\mid\text{passed})$.` },
      { ask: r`Draw 2 without replacement from 4 white and 2 red. Find $P(\text{exactly one white})$.` },
      { ask: r`Guess 2 true/false questions. Find $P(\text{both correct})$ from a tree.` },
      { ask: r`80\% take a vaccine (5\% get sick); 20\% don't (30\% get sick). Find $P(\text{sick})$.` },
      { ask: r`An urn has 5 white and 3 black; draw 3 without replacement. Find \\ \textbf{(a)} $P(\text{all white})$; \\ \textbf{(b)} $P(\text{exactly 2 white})$; \\ \textbf{(c)} $P(\text{at least one black})$.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$\tfrac12\cdot\tfrac12=\tfrac14$`, r`$\tfrac35\cdot\tfrac24=\tfrac{6}{20}=\tfrac{3}{10}$`, r`$\tfrac35\cdot\tfrac24+\tfrac25\cdot\tfrac34=\tfrac{12}{20}=\tfrac35$`, r`$0.7(0.03)+0.3(0.06)=0.039$`, r`$\tfrac{0.018}{0.039}=\tfrac{6}{13}$`, r`$0.5^3=\tfrac18$`, r`$\dbinom{3}{2}(0.5)^3=\tfrac38$`, r`$0.6(0.9)+0.4(0.3)=0.66$`, r`$\tfrac{0.54}{0.66}=\tfrac{9}{11}$`, r`$\dfrac{\binom{4}{1}\binom{2}{1}}{\binom{6}{2}}=\tfrac{8}{15}$`, r`$\tfrac14$`, r`$0.8(0.05)+0.2(0.30)=0.10$`, r`(a) $\tfrac{5}{28}$; (b) $\tfrac{15}{28}$; (c) $\tfrac{23}{28}$`],
  },
];
