// MDM4U Unit 3 worksheets — Discrete Probability Distributions.
// Textbook-level depth: random variables, expected value, uniform, binomial,
// geometric, hypergeometric. Each example and question a distinct idea.
// 9 worked examples + 13 questions + answer key each. No backtick quotes in r`...`.
const r = String.raw;
const U = "3: Discrete Probability Distributions";

export default [
  {
    code: "3.1", unit: U, title: "Random Variables & Discrete Distributions",
    intro: r`A random variable assigns a number to each outcome. Its \emph{distribution} lists every value with its probability, and those probabilities must sum to $1$.`,
    ideas: [r`Discrete random variable $X$ takes separate values.`, r`A distribution is valid when every $P(x)\ge0$ and $\sum P(x)=1$.`, r`Cumulative events: $P(X\le k)$, $P(X\ge k)$ add the relevant rows.`],
    examples: [
      { t: "Build a distribution", body: r`Two coins are tossed; $X=$ number of heads. Give the distribution.\soln $X\in\{0,1,2\}$ with $P=\tfrac14,\tfrac12,\tfrac14$; sum $=1$. \checkmark` },
      { t: "Distribution of a dice sum", body: r`Two dice; $X=$ the sum. Find $P(X=5)$ and describe the shape.\soln $P(5)=\dfrac{4}{36}=\dfrac19$; the distribution rises to a peak at $7$, then falls (triangular).` },
      { t: "Find a missing probability", body: r`A table gives $P(0)=0.1,\ P(1)=0.3,\ P(3)=0.2$. Find $P(2)$.\soln $\sum=1\Rightarrow P(2)=1-(0.1+0.3+0.2)=0.4$.` },
      { t: "Cumulative probabilities", body: r`For $P(0)=0.1,\ P(1)=0.4,\ P(2)=0.3,\ P(3)=0.2$, find $P(X\ge2)$.\soln $0.3+0.2=0.5$.` },
      { t: "Solve for a constant", body: r`$P(x)=kx$ for $x=1,2,3,4$. Find $k$.\soln $k(1+2+3+4)=1\Rightarrow 10k=1\Rightarrow k=\tfrac{1}{10}$.` },
      { t: "An indicator variable", body: r`$X=1$ if a drawn card is a heart, else $0$. Give the distribution.\soln $P(1)=\tfrac14,\ P(0)=\tfrac34$.` },
      { t: "Distribution from a draw", body: r`From 3 red and 2 blue, draw 2 without replacement; $X=$ number of red. Give the distribution.\soln $P(0)=\dfrac{\binom{2}{2}}{\binom{5}{2}}=\tfrac{1}{10}$, $P(1)=\dfrac{\binom{3}{1}\binom{2}{1}}{10}=\tfrac{6}{10}$, $P(2)=\dfrac{\binom{3}{2}}{10}=\tfrac{3}{10}$; sum $=1$. \checkmark` },
      { t: "Read a histogram", body: r`A probability histogram has bars $P(1)=0.2,\ P(2)=0.5,\ P(3)=0.3$. Find $P(X\le2)$.\soln $0.2+0.5=0.7$.` },
      { t: "Full distribution, three parts", body: r`Roll one die; $X=$ the value. Find \\ \textbf{(a)} the distribution; \\ \textbf{(b)} $P(X>4)$; \\ \textbf{(c)} $P(X\text{ even})$.\soln (a) uniform, $\tfrac16$ each. (b) $\tfrac26=\tfrac13$. (c) $\tfrac12$.` },
    ],
    questions: [
      { ask: r`Two coins are tossed; $X=$ number of heads. Give the distribution.` },
      { ask: r`A table gives $P(0)=0.2,\ P(1)=0.5$. If these are the only other values besides $P(2)$, find $P(2)$.` },
      { ask: r`$P(x)=kx^2$ for $x=1,2,3$. Find $k$.` },
      { ask: r`For $P(0)=0.1,\ P(1)=0.4,\ P(2)=0.3,\ P(3)=0.2$, find $P(X\ge2)$.` },
      { ask: r`Two dice; $X=$ sum. Find $P(X=7)$.` },
      { ask: r`Two dice; $X=$ sum. Find $P(X\le4)$.` },
      { ask: r`From 4 red and 3 green, draw 2 without replacement; $X=$ green. Find $P(X=1)$.` },
      { ask: r`A spinner $1$--$5$ (equally likely); $X=$ value. Find $P(X\text{ prime})$.` },
      { ask: r`$X=$ number of heads in 3 coins. Find $P(X=2)$.` },
      { ask: r`$P(x)=c$ for $x=1,\dots,6$. Find $c$.` },
      { ask: r`$P(0)=0.3,\ P(1)=a,\ P(2)=2a,\ P(3)=0.1$. Find $a$.` },
      { ask: r`Two dice; $X=$ sum. Find $P(X\text{ is a multiple of }3)$.` },
      { ask: r`A bag has 2 red, 2 blue, 1 green; draw 2 without replacement, $X=$ red. Give the full distribution and verify $\sum P=1$.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$P(0)=\tfrac14,\ P(1)=\tfrac12,\ P(2)=\tfrac14$`, r`$P(2)=0.3$`, r`$k(1+4+9)=1\Rightarrow k=\tfrac{1}{14}$`, r`$0.5$`, r`$\tfrac{6}{36}=\tfrac16$`, r`$\tfrac{1+2+3}{36}=\tfrac16$`, r`$\dfrac{\binom{3}{1}\binom{4}{1}}{\binom{7}{2}}=\tfrac{12}{21}=\tfrac47$`, r`$\tfrac35$`, r`$\tfrac38$`, r`$c=\tfrac16$`, r`$3a=0.6\Rightarrow a=0.2$`, r`$\tfrac{12}{36}=\tfrac13$`, r`$P(0)=\tfrac{3}{10},\ P(1)=\tfrac{6}{10},\ P(2)=\tfrac{1}{10}$`],
  },
  {
    code: "3.2", unit: U, title: "Expected Value",
    intro: r`The expected value $E(X)=\sum x\,P(x)$ is the long-run average. A game is \emph{fair} when the expected net gain is $0$; expected value drives rational decisions.`,
    ideas: [r`$E(X)=\sum x\,P(x)$.`, r`Fair game: expected net $=0$; a fair price equals the expected winnings.`, r`Compare options by their expected values.`],
    examples: [
      { t: "Expected value of a die", body: r`Find $E(X)$ for one die.\soln $\dfrac{1+2+3+4+5+6}{6}=3.5$.` },
      { t: "Weighted average", body: r`For $P(0)=0.2,\ P(1)=0.5,\ P(2)=0.3$, find $E(X)$.\soln $0(0.2)+1(0.5)+2(0.3)=1.1$.` },
      { t: "Is the game fair?", body: r`Pay \$2 to play; win \$5 with probability $0.3$, else nothing. Find the expected net gain.\soln $E=0.3(5)-2=1.5-2=-0.50$. Not fair --- it favours the house.` },
      { t: "Lottery expected value", body: r`A \$2 ticket wins \$1000 with probability $\tfrac{1}{1000}$. Find the expected net.\soln $E=\dfrac{1000}{1000}-2=1-2=-1$ dollar.` },
      { t: "Expected count by linearity", body: r`Find the expected number of aces when 5 cards are drawn.\soln Each card is an ace with probability $\tfrac{4}{52}$; by linearity $E=5\cdot\tfrac{4}{52}=\tfrac{5}{13}\approx0.385$.` },
      { t: "Set a fair price", body: r`A game pays \$0 or \$10 with probabilities $0.9$ and $0.1$. What entry fee makes it fair?\soln $E=0.1(10)=1$, so a fair fee is \$1.` },
      { t: "Choose the better bet", body: r`Game A: win \$4 with $P=0.5$. Game B: win \$10 with $P=0.25$. Which has the higher expected payout?\soln $E_A=2.00$, $E_B=2.50$; choose B.` },
      { t: "Expected number of successes", body: r`Find the expected number of sixes in 12 rolls of a die.\soln $12\cdot\tfrac16=2$.` },
      { t: "Multi-payout spinner", body: r`A spinner pays \$1, \$4, \$10 with probabilities $\tfrac12,\tfrac13,\tfrac16$. Find \\ \textbf{(a)} $E(\text{payout})$; \\ \textbf{(b)} a fair fee.\soln (a) $\tfrac12(1)+\tfrac13(4)+\tfrac16(10)=0.5+1.333+1.667=3.50$. (b) \$3.50.` },
    ],
    questions: [
      { ask: r`A payout equals the face value of one die roll. Find $E$.` },
      { ask: r`For $P(0)=0.2,\ P(1)=0.5,\ P(2)=0.3$, find $E(X)$.` },
      { ask: r`Pay \$3 to play; win \$10 with $P=0.25$, else nothing. Find the expected net.` },
      { ask: r`A raffle sells 500 tickets at \$1; one prize is \$100. Find the expected net per ticket.` },
      { ask: r`Find the expected number of hearts when 4 cards are drawn.` },
      { ask: r`Win \$6 with $P=\tfrac13$, lose \$3 with $P=\tfrac23$. Find $E$ and state whether it is fair.` },
      { ask: r`For $x=1,2,3,4$ with $P=0.4,0.3,0.2,0.1$, find $E(X)$.` },
      { ask: r`Two dice are rolled. Find $E(\text{sum})$.` },
      { ask: r`A spinner pays \$2, \$5, \$8 with $P=0.5,0.3,0.2$. Find $E(\text{payout})$.` },
      { ask: r`A game pays \$0 or \$10 with $P=0.9,0.1$. What is a fair entry fee?` },
      { ask: r`Find the expected number of sixes in 12 rolls of a die.` },
      { ask: r`A \$5 ticket wins \$1000 with $P=\tfrac{1}{400}$ or \$50 with $P=\tfrac{1}{40}$. Find the expected net.` },
      { ask: r`Roll two dice: win \$10 on a sum of 7, \$5 on a sum of 11, else nothing. Find the fair price to play.`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`$3.5$`, r`$1.1$`, r`$0.25(10)-3=-0.50$`, r`$\tfrac{100}{500}-1=-0.80$`, r`$4\cdot\tfrac{13}{52}=1$`, r`$2-2=0$ (fair)`, r`$0.4+0.6+0.6+0.4=2.0$`, r`$7$`, r`$1+1.5+1.6=4.1$`, r`$E=1$, so \$1`, r`$12\cdot\tfrac16=2$`, r`$\tfrac{1000}{400}+\tfrac{50}{40}-5=2.5+1.25-5=-1.25$`, r`$E=10\cdot\tfrac{6}{36}+5\cdot\tfrac{2}{36}=\tfrac{70}{36}\approx1.94$`],
  },
  {
    code: "3.3", unit: U, title: "The Uniform Distribution",
    intro: r`In a discrete \emph{uniform} distribution every outcome is equally likely: $P=\tfrac1n$. For consecutive integers the mean is the middle value, $\tfrac{\text{min}+\text{max}}{2}$.`,
    ideas: [r`Uniform: $P(x)=\tfrac1n$ for each of $n$ outcomes.`, r`Mean of a uniform on consecutive integers $=\tfrac{\text{min}+\text{max}}{2}$.`, r`Equal likelihood must be a valid assumption --- e.g. a dice \emph{sum} is not uniform.`],
    examples: [
      { t: "A die is uniform", body: r`State $P$ and $E(X)$ for a fair die.\soln $P=\tfrac16$ each; $E=3.5$.` },
      { t: "Uniform on 1--10", body: r`For a random integer $1$--$10$, find $E(X)$ and $P(X>7)$.\soln $E=\tfrac{1+10}{2}=5.5$; $P(X>7)=\tfrac{3}{10}$.` },
      { t: "Divisibility", body: r`A random integer $1$--$20$. Find $P(\text{divisible by }3)$.\soln Multiples of 3 up to 20: $6$ of them: $\tfrac{6}{20}=\tfrac{3}{10}$.` },
      { t: "Uniform over card ranks", body: r`Find $P(\text{a specific rank, e.g. a 7})$ for one card.\soln $\tfrac{4}{52}=\tfrac{1}{13}$.` },
      { t: "Not everything is uniform", body: r`Explain why the sum of two dice is not uniform.\soln Sums near 7 arise from more outcomes (six ways) than sums near 2 (one way), so the probabilities differ.` },
      { t: "Spinner mean", body: r`A spinner is labelled $1$--$8$ equally. Find $E(X)$.\soln $\tfrac{1+8}{2}=4.5$.` },
      { t: "Selecting a person", body: r`Students are numbered $1$--$30$; one is chosen at random. Find $P(\text{number ends in }0)$.\soln $\{10,20,30\}$: $\tfrac{3}{30}=\tfrac{1}{10}$.` },
      { t: "Complement on a uniform", body: r`A random integer $1$--$50$. Find $P(\text{not a multiple of }5)$.\soln Multiples of 5: $10$; $1-\tfrac{10}{50}=\tfrac45$.` },
      { t: "Three parts", body: r`A random integer $1$--$12$. Find \\ \textbf{(a)} $P(\text{prime})$; \\ \textbf{(b)} $E(X)$; \\ \textbf{(c)} $P(X\ge9)$.\soln (a) primes $\{2,3,5,7,11\}$: $\tfrac{5}{12}$. (b) $6.5$. (c) $\{9,10,11,12\}$: $\tfrac{4}{12}=\tfrac13$.` },
    ],
    questions: [
      { ask: r`Find $E(X)$ for a fair die.` },
      { ask: r`Random integer $1$--$10$. Find $P(X\le3)$.` },
      { ask: r`Random integer $1$--$20$. Find $P(\text{even})$.` },
      { ask: r`Random integer $1$--$100$. Find $P(\text{multiple of }10)$.` },
      { ask: r`Find $E(X)$ for a uniform on $\{1,\dots,9\}$.` },
      { ask: r`Random integer $1$--$15$. Find $P(\text{multiple of }3)$.` },
      { ask: r`Is the sum of two dice uniform? Explain briefly.` },
      { ask: r`A spinner $1$--$8$ (equal). Find $P(X>5)$.` },
      { ask: r`One card. Find $P(\text{a specific rank})$.` },
      { ask: r`Random integer $1$--$50$. Find $P(\text{not a multiple of }5)$.` },
      { ask: r`Random integer $1$--$30$. Find $P(\text{ends in }0)$.` },
      { ask: r`A spinner labelled $0$--$9$ (equal). Find $E(X)$.` },
      { ask: r`Random integer $1$--$12$. Find \\ \textbf{(a)} $P(\text{prime})$; \\ \textbf{(b)} $E(X)$; \\ \textbf{(c)} $P(X\ge9)$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$3.5$`, r`$\tfrac{3}{10}$`, r`$\tfrac12$`, r`$\tfrac{10}{100}=\tfrac{1}{10}$`, r`$5$`, r`$\tfrac{5}{15}=\tfrac13$`, r`No --- middle sums have more outcomes`, r`$\tfrac38$`, r`$\tfrac{4}{52}=\tfrac{1}{13}$`, r`$\tfrac45$`, r`$\tfrac{3}{30}=\tfrac{1}{10}$`, r`$4.5$`, r`(a) $\tfrac{5}{12}$; (b) $6.5$; (c) $\tfrac13$`],
  },
  {
    code: "3.4", unit: U, title: "The Binomial Distribution",
    intro: r`For $n$ independent trials (BINS: Binary, Independent, fixed Number, Same $p$), $P(X=k)=\dbinom{n}{k}p^{k}q^{\,n-k}$, with mean $np$ and standard deviation $\sqrt{npq}$.`,
    ideas: [r`$P(X=k)=\dbinom{n}{k}p^{k}q^{\,n-k}$, $q=1-p$.`, r`Mean $\mu=np$; standard deviation $\sigma=\sqrt{npq}$.`, r`At least/at most: sum terms, or use the complement.`],
    examples: [
      { t: "Exactly $k$ (fair)", body: r`Find $P(\text{exactly 3 heads in 5 flips})$.\soln $\dbinom{5}{3}\left(\tfrac12\right)^5=\tfrac{10}{32}=\tfrac{5}{16}$.` },
      { t: "Exactly $k$ (unfair)", body: r`A player makes 80\% of free throws. Find $P(\text{exactly 5 of 6})$.\soln $\dbinom{6}{5}(0.8)^5(0.2)=6(0.32768)(0.2)\approx0.393$.` },
      { t: "At least one (complement)", body: r`Roll 4 dice. Find $P(\text{at least one 6})$.\soln $1-\left(\tfrac56\right)^4=1-\tfrac{625}{1296}=\tfrac{671}{1296}$.` },
      { t: "At most one", body: r`$n=10,\ p=0.3$. Find $P(X\le1)$.\soln $(0.7)^{10}+10(0.3)(0.7)^9\approx0.028+0.121=0.149$.` },
      { t: "Mean and standard deviation", body: r`$n=200,\ p=0.1$. Find $\mu$ and $\sigma$.\soln $\mu=20$; $\sigma=\sqrt{200(0.1)(0.9)}=\sqrt{18}\approx4.24$.` },
      { t: "Symmetric case", body: r`Find $P(\text{exactly 4 boys in 8 births})$, $p=0.5$.\soln $\dbinom{8}{4}\left(\tfrac12\right)^8=\tfrac{70}{256}\approx0.273$.` },
      { t: "At least one defective", body: r`20 items, each defective with $p=0.05$. Find $P(\text{at least one defective})$.\soln $1-(0.95)^{20}\approx1-0.358=0.642$.` },
      { t: "Solve for $n$", body: r`With $p=0.2$ per trial, how many trials give $P(\text{at least one success})\ge0.9$?\soln $1-(0.8)^n\ge0.9\Rightarrow(0.8)^n\le0.1\Rightarrow n\ge\tfrac{\log0.1}{\log0.8}\approx10.3$, so $n=11$.` },
      { t: "Guessing a test (three parts)", body: r`10 questions, 4 options each, all guessed ($p=0.25$). Find \\ \textbf{(a)} $E(\text{correct})$; \\ \textbf{(b)} $P(\text{exactly 3})$; \\ \textbf{(c)} $P(\text{at least 1})$.\soln (a) $2.5$. (b) $\dbinom{10}{3}(0.25)^3(0.75)^7\approx0.250$. (c) $1-(0.75)^{10}\approx0.944$.` },
    ],
    questions: [
      { ask: r`Find $P(\text{exactly 4 heads in 6 flips})$.` },
      { ask: r`A player makes 90\% of free throws. Find $P(\text{all 5 of 5})$.` },
      { ask: r`Roll 3 dice. Find $P(\text{at least one 6})$.` },
      { ask: r`$n=10,\ p=0.2$. Find $P(\text{exactly 2})$.` },
      { ask: r`$n=50,\ p=0.4$. Find $\mu$ and $\sigma$.` },
      { ask: r`7 true/false guesses ($p=0.5$). Find $P(\text{exactly 4 correct})$.` },
      { ask: r`20 seeds each germinate with $p=0.85$. Find $P(\text{all germinate})$.` },
      { ask: r`$n=12,\ p=\tfrac16$ (rolling a 6). Find $P(\text{exactly two 6s})$.` },
      { ask: r`15 items, each defective with $p=0.1$. Find $P(\text{at least one defective})$.` },
      { ask: r`8 multiple-choice questions guessed ($p=0.25$). Find $E(\text{correct})$.` },
      { ask: r`$n=100,\ p=0.5$. Find $\mu$ and $\sigma$.` },
      { ask: r`4 shots, each a hit with $p=0.7$. Find $P(\text{exactly 3 hits})$.` },
      { ask: r`A 10-question test with 5 options each, all guessed ($p=0.2$). Find \\ \textbf{(a)} $E(\text{correct})$; \\ \textbf{(b)} $P(\text{exactly 2})$; \\ \textbf{(c)} $P(\text{at least 1})$.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$\dbinom{6}{4}\left(\tfrac12\right)^6=\tfrac{15}{64}$`, r`$0.9^5\approx0.590$`, r`$1-\left(\tfrac56\right)^3=\tfrac{91}{216}$`, r`$\dbinom{10}{2}(0.2)^2(0.8)^8\approx0.302$`, r`$\mu=20,\ \sigma=\sqrt{12}\approx3.46$`, r`$\dbinom{7}{4}\left(\tfrac12\right)^7=\tfrac{35}{128}$`, r`$0.85^{20}\approx0.039$`, r`$\dbinom{12}{2}\left(\tfrac16\right)^2\left(\tfrac56\right)^{10}\approx0.296$`, r`$1-0.9^{15}\approx0.794$`, r`$\mu=2$`, r`$\mu=50,\ \sigma=5$`, r`$\dbinom{4}{3}(0.7)^3(0.3)\approx0.412$`, r`(a) $2$; (b) $\approx0.302$; (c) $1-0.8^{10}\approx0.893$`],
  },
  {
    code: "3.5", unit: U, title: "The Geometric Distribution",
    intro: r`The geometric distribution counts trials until the first success: $P(X=k)=q^{\,k-1}p$. Its mean is $E(X)=\tfrac1p$, and $P(X>k)=q^{k}$.`,
    ideas: [r`$P(X=k)=q^{\,k-1}p$ (first success on trial $k$).`, r`$E(X)=\tfrac1p$; rarer successes mean longer waits.`, r`$P(X>k)=q^{k}$ (no success in the first $k$ trials).`],
    examples: [
      { t: "First success on trial $k$", body: r`Roll a die until a 6. Find $P(\text{first 6 on the 3rd roll})$.\soln $\left(\tfrac56\right)^2\left(\tfrac16\right)=\tfrac{25}{216}$.` },
      { t: "Expected wait", body: r`Find the expected number of rolls to get a 6.\soln $E=\tfrac{1}{1/6}=6$.` },
      { t: "No success yet", body: r`Find $P(\text{no 6 in the first 4 rolls})$.\soln $\left(\tfrac56\right)^4=\tfrac{625}{1296}$.` },
      { t: "Within the first $k$", body: r`Find $P(\text{first 6 within 3 rolls})$.\soln $1-\left(\tfrac56\right)^3=\tfrac{91}{216}$.` },
      { t: "A different success event", body: r`A player makes 80\% of shots. Find $P(\text{first miss on the 4th shot})$.\soln Missing has $p=0.2$: $(0.8)^3(0.2)=0.1024$.` },
      { t: "Expected wait, high $p$", body: r`With $p=0.8$, find the expected number of shots to the first make.\soln $E=\tfrac{1}{0.8}=1.25$.` },
      { t: "First head on an even toss", body: r`Toss a fair coin. Find $P(\text{first head on an even-numbered toss})$.\soln $\tfrac12\cdot\tfrac12+\left(\tfrac12\right)^3\cdot\tfrac12+\cdots=\dfrac{qp}{1-q^2}=\dfrac{1/4}{3/4}=\tfrac13$.` },
      { t: "Long wait", body: r`With $p=0.3$, find $P(\text{more than 5 attempts needed})$.\soln $P(X>5)=(0.7)^5\approx0.168$.` },
      { t: "Three parts", body: r`A game is won with $p=0.25$ each try. Find \\ \textbf{(a)} $E(\text{tries})$; \\ \textbf{(b)} $P(\text{win on the 3rd try})$; \\ \textbf{(c)} $P(\text{win within 2 tries})$.\soln (a) $4$. (b) $(0.75)^2(0.25)\approx0.141$. (c) $1-(0.75)^2=0.4375$.` },
    ],
    questions: [
      { ask: r`Roll a die until a 6. Find $P(\text{first 6 on the 2nd roll})$.` },
      { ask: r`Find the expected number of rolls to the first 6.` },
      { ask: r`Find $P(\text{no 6 in the first 3 rolls})$.` },
      { ask: r`With $p=0.4$, find $P(\text{first success on the 4th trial})$.` },
      { ask: r`With $p=0.4$, find $E(\text{trials})$.` },
      { ask: r`A player makes 90\% of shots. Find $P(\text{first miss on the 3rd shot})$.` },
      { ask: r`Toss a coin. Find $P(\text{first head on the 3rd toss})$.` },
      { ask: r`With $p=0.2$, find $P(\text{more than 4 trials needed})$.` },
      { ask: r`Roll a die until a 6. Find $P(\text{success within 4 rolls})$.` },
      { ask: r`With $p=0.5$, find $E(\text{trials to first success})$.` },
      { ask: r`With $p=0.3$, find $P(\text{first success on the 5th trial})$.` },
      { ask: r`Toss a coin. Find $P(\text{first head on an even-numbered toss})$.` },
      { ask: r`A prize is won with $p=0.25$ each try. Find \\ \textbf{(a)} $E(\text{tries})$; \\ \textbf{(b)} $P(\text{win on 3rd try})$; \\ \textbf{(c)} $P(\text{win within 2 tries})$.`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`$\tfrac56\cdot\tfrac16=\tfrac{5}{36}$`, r`$6$`, r`$\left(\tfrac56\right)^3=\tfrac{125}{216}$`, r`$(0.6)^3(0.4)=0.0864$`, r`$2.5$`, r`$(0.9)^2(0.1)=0.081$`, r`$\left(\tfrac12\right)^3=\tfrac18$`, r`$(0.8)^4=0.4096$`, r`$1-\left(\tfrac56\right)^4=\tfrac{671}{1296}$`, r`$2$`, r`$(0.7)^4(0.3)=0.072$`, r`$\tfrac13$`, r`(a) $4$; (b) $\approx0.141$; (c) $0.4375$`],
  },
  {
    code: "3.6", unit: U, title: "The Hypergeometric Distribution",
    intro: r`When sampling \emph{without} replacement, $P(X=k)=\dfrac{\dbinom{a}{k}\dbinom{n-a}{r-k}}{\dbinom{n}{r}}$, with mean $E(X)=r\cdot\tfrac{a}{n}$. Replacement is the only difference from the binomial.`,
    ideas: [r`$P(X=k)=\dfrac{\binom{a}{k}\binom{n-a}{r-k}}{\binom{n}{r}}$ (choose successes $\times$ non-successes).`, r`Mean $E(X)=r\cdot\tfrac{a}{n}$.`, r`Binomial (with replacement / large population) vs. hypergeometric (small population, without replacement).`],
    examples: [
      { t: "Exactly $k$ of a type", body: r`10 items, 4 defective; draw 3. Find $P(\text{exactly 1 defective})$.\soln $\dfrac{\dbinom{4}{1}\dbinom{6}{2}}{\dbinom{10}{3}}=\dfrac{4\cdot15}{120}=\dfrac12$.` },
      { t: "Expected number", body: r`For that draw, find the expected number of defectives.\soln $E=3\cdot\tfrac{4}{10}=1.2$.` },
      { t: "Card hand", body: r`Find $P(\text{exactly 2 aces in a 5-card hand})$.\soln $\dfrac{\dbinom{4}{2}\dbinom{48}{3}}{\dbinom{52}{5}}$.` },
      { t: "Lottery match", body: r`In 6/49, find $P(\text{match exactly 4})$.\soln $\dfrac{\dbinom{6}{4}\dbinom{43}{2}}{\dbinom{49}{6}}$.` },
      { t: "All of one type", body: r`Draw 3 from 5 red and 5 blue. Find $P(\text{all red})$.\soln $\dfrac{\dbinom{5}{3}}{\dbinom{10}{3}}=\dfrac{10}{120}=\dfrac{1}{12}$.` },
      { t: "At least one (complement)", body: r`Draw 4 from 20 items with 3 defective. Find $P(\text{at least one defective})$.\soln $1-\dfrac{\dbinom{17}{4}}{\dbinom{20}{4}}\approx0.509$.` },
      { t: "Committee", body: r`12 people, 5 women; choose 4. Find $P(\text{exactly 2 women})$.\soln $\dfrac{\dbinom{5}{2}\dbinom{7}{2}}{\dbinom{12}{4}}=\dfrac{10\cdot21}{495}=\dfrac{14}{33}$.` },
      { t: "Binomial vs. hypergeometric", body: r`Why is drawing 5 cards hypergeometric, but 5 die-rolls binomial?\soln Cards are drawn \emph{without} replacement (the pool shrinks); die rolls are independent with a constant $p$.` },
      { t: "Three parts", body: r`A box has 6 good and 4 bad bulbs; draw 3. Find \\ \textbf{(a)} $P(\text{all good})$; \\ \textbf{(b)} $P(\text{exactly 1 bad})$; \\ \textbf{(c)} $E(\text{bad})$.\soln (a) $\dfrac{\dbinom{6}{3}}{\dbinom{10}{3}}=\dfrac{20}{120}=\dfrac16$. (b) $\dfrac{\dbinom{4}{1}\dbinom{6}{2}}{120}=\dfrac{60}{120}=\dfrac12$. (c) $3\cdot\tfrac{4}{10}=1.2$.` },
    ],
    questions: [
      { ask: r`8 items, 3 defective; draw 2. Find $P(\text{exactly 1 defective})$.` },
      { ask: r`For that draw, find the expected number of defectives.` },
      { ask: r`Find $P(\text{exactly 2 kings in a 5-card hand})$.` },
      { ask: r`Draw 3 from 6 red and 4 green. Find $P(\text{all red})$.` },
      { ask: r`In 6/49, find $P(\text{match exactly 5})$.` },
      { ask: r`12 people, 5 women; choose 4. Find $P(\text{exactly 2 women})$.` },
      { ask: r`A box has 7 good and 3 bad; draw 3. Find $P(\text{no bad})$.` },
      { ask: r`For that box, find $P(\text{at least one bad})$.` },
      { ask: r`20 items, 4 defective; draw 5. Find $E(\text{defective})$.` },
      { ask: r`Draw 4 from 5 red and 5 blue. Find $P(\text{2 red and 2 blue})$.` },
      { ask: r`Find $P(\text{exactly 3 hearts in a 5-card hand})$.` },
      { ask: r`Find $P(\text{a 5-card hand has all four aces})$.` },
      { ask: r`A box has 6 good and 4 bad bulbs; draw 3. Find \\ \textbf{(a)} $P(\text{all good})$; \\ \textbf{(b)} $P(\text{exactly 1 bad})$; \\ \textbf{(c)} $E(\text{bad})$.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$\dfrac{\binom{3}{1}\binom{5}{1}}{\binom{8}{2}}=\tfrac{15}{28}$`, r`$2\cdot\tfrac{3}{8}=0.75$`, r`$\dfrac{\binom{4}{2}\binom{48}{3}}{\binom{52}{5}}$`, r`$\dfrac{\binom{6}{3}}{\binom{10}{3}}=\tfrac{20}{120}=\tfrac16$`, r`$\dfrac{\binom{6}{5}\binom{43}{1}}{\binom{49}{6}}$`, r`$\dfrac{\binom{5}{2}\binom{7}{2}}{\binom{12}{4}}=\tfrac{14}{33}$`, r`$\dfrac{\binom{7}{3}}{\binom{10}{3}}=\tfrac{35}{120}=\tfrac{7}{24}$`, r`$1-\tfrac{7}{24}=\tfrac{17}{24}$`, r`$5\cdot\tfrac{4}{20}=1$`, r`$\dfrac{\binom{5}{2}\binom{5}{2}}{\binom{10}{4}}=\tfrac{100}{210}=\tfrac{10}{21}$`, r`$\dfrac{\binom{13}{3}\binom{39}{2}}{\binom{52}{5}}$`, r`$\dfrac{\binom{4}{4}\binom{48}{1}}{\binom{52}{5}}=\tfrac{48}{2\,598\,960}$`, r`(a) $\tfrac16$; (b) $\tfrac12$; (c) $1.2$`],
  },
];
