// MDM4U Unit 4 worksheets — Continuous & Normal Distributions.
// Textbook-level depth with shaded bell-curve figures (\ncurve{from}{to}{}).
// z-table values assumed available. Each example/question a distinct idea.
// 9 worked examples + 13 questions + answer key each. No backtick quotes in r`...`.
const r = String.raw;
const U = "4: Continuous & Normal Distributions";

export default [
  {
    code: "4.1", unit: U, title: "Continuous Random Variables",
    intro: r`A continuous random variable takes any value in an interval, so probability becomes \emph{area} under a density curve $f(x)$. The total area is $1$, and $P(X=a)=0$ for any single value.`,
    ideas: [r`Probability $=$ area under the density $f(x)$; total area $=1$.`, r`$P(X=a)=0$; only intervals carry probability.`, r`For a continuous uniform on $[a,b]$: $f=\tfrac{1}{b-a}$ and mean $\tfrac{a+b}{2}$.`],
    examples: [
      { t: "Uniform density (a rectangle)", body: r`$X$ is uniform on $[0,10]$. Find $P(X<3)$.\soln $f=\tfrac{1}{10}$; area of the rectangle: $3\cdot\tfrac{1}{10}=0.3$.` },
      { t: "Uniform interval", body: r`$X$ is uniform on $[2,6]$. Find $P(3<X<5)$.\soln $\dfrac{5-3}{6-2}=\dfrac24=0.5$.` },
      { t: "A single value has probability 0", body: r`For a continuous $X$, explain $P(X=5)$.\soln A single point has zero width, so zero area: $P(X=5)=0$.` },
      { t: "A ramp density", body: r`$f(x)=\tfrac{x}{2}$ on $[0,2]$ (area $=1$). Find $P(X<1)$.\soln Triangle with base $1$, height $f(1)=0.5$: $\tfrac12(1)(0.5)=0.25$.` },
      { t: "A decreasing density", body: r`$f(x)=\tfrac{4-x}{8}$ on $[0,4]$. Find $P(X<2)$.\soln Trapezoid from $0$ to $2$: heights $0.5$ and $0.25$, so $\tfrac{0.5+0.25}{2}\cdot2=0.75$.` },
      { t: "Complement", body: r`$X$ is uniform on $[0,10]$. Find $P(X>7)$ and $P(X<7)$.\soln $P(X>7)=0.3$; $P(X<7)=0.7$.` },
      { t: "Median splits the area", body: r`Find the median of a uniform distribution on $[0,10]$.\soln The value with half the area on each side: $5$.` },
      { t: "Mean of a uniform", body: r`Find $E(X)$ for a uniform on $[2,6]$.\soln $\dfrac{2+6}{2}=4$.` },
      { t: "Waiting time (three parts)", body: r`A wait is uniform on $[0,20]$ minutes. Find \\ \textbf{(a)} $P(\text{wait}<5)$; \\ \textbf{(b)} $P(\text{wait}>15)$; \\ \textbf{(c)} $P(5<\text{wait}<15)$.\soln (a) $\tfrac{5}{20}=0.25$. (b) $\tfrac{5}{20}=0.25$. (c) $\tfrac{10}{20}=0.5$.` },
    ],
    questions: [
      { ask: r`$X$ uniform on $[0,10]$. Find $P(X<4)$.` },
      { ask: r`$X$ uniform on $[0,10]$. Find $P(X>6)$.` },
      { ask: r`$X$ uniform on $[1,5]$. Find $P(2<X<4)$.` },
      { ask: r`For a continuous $X$, find $P(X=3)$.` },
      { ask: r`$X$ uniform on $[0,20]$. Find $P(X<5)$.` },
      { ask: r`$f(x)=\tfrac{x}{2}$ on $[0,2]$. Find $P(X<1)$.` },
      { ask: r`Find $E(X)$ for a uniform on $[4,10]$.` },
      { ask: r`Find the median of a uniform on $[0,8]$.` },
      { ask: r`$f(x)=\tfrac{4-x}{8}$ on $[0,4]$. Find $P(X<2)$.` },
      { ask: r`A bus wait is uniform on $[0,30]$ min. Find $P(\text{wait}>25)$.` },
      { ask: r`$X$ uniform on $[0,1]$. Find $P(0.2<X<0.5)$.` },
      { ask: r`What is the total area under any density curve $f(x)$?` },
      { ask: r`A wait is uniform on $[0,20]$ min. Find \\ \textbf{(a)} $P(X<5)$; \\ \textbf{(b)} $P(X>15)$; \\ \textbf{(c)} $P(5<X<15)$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$0.4$`, r`$0.4$`, r`$\tfrac24=0.5$`, r`$0$`, r`$\tfrac{5}{20}=0.25$`, r`$\tfrac12(1)(0.5)=0.25$`, r`$7$`, r`$4$`, r`$0.75$`, r`$\tfrac{5}{30}=\tfrac16$`, r`$0.3$`, r`$1$`, r`(a) $0.25$; (b) $0.25$; (c) $0.5$`],
  },
  {
    code: "4.2", unit: U, title: "The Normal Distribution & z-Scores",
    intro: r`A normal curve is symmetric about its mean $\mu$ with spread $\sigma$. The $z$-score $z=\dfrac{x-\mu}{\sigma}$ measures how many standard deviations $x$ sits from the mean. The empirical rule gives $68\%$--$95\%$--$99.7\%$ within $1,2,3\,\sigma$.`,
    ideas: [r`$z=\dfrac{x-\mu}{\sigma}$; invert with $x=\mu+z\sigma$.`, r`Empirical rule: $\approx68\%,95\%,99.7\%$ within $\pm1,\pm2,\pm3\,\sigma$.`, r`Standardizing lets you compare values from different distributions.`],
    examples: [
      { t: "Compute a z-score", body: r`$X\sim N(100,15)$. Find the $z$-score of $x=130$.\soln $z=\dfrac{130-100}{15}=2$.` },
      { t: "Empirical rule (one sigma)", body: r`$X\sim N(50,5)$. What percent lies between $45$ and $55$?\soln Within $\pm1\sigma$: about $68\%$.` },
      { t: "Empirical rule (two sigma)", body: r`$X\sim N(50,5)$. What percent lies between $40$ and $60$?\soln Within $\pm2\sigma$: about $95\%$.` + r`\ncurve{-2}{2}{}` },
      { t: "Invert a z-score", body: r`$X\sim N(200,10)$. Find $x$ when $z=-1.5$.\soln $x=\mu+z\sigma=200-15=185$.` },
      { t: "Compare with z-scores", body: r`Test A: $80$ on $N(70,5)$. Test B: $90$ on $N(80,8)$. Which is relatively better?\soln $z_A=2$, $z_B=1.25$; Test A is stronger.` },
      { t: "Empirical rule tail", body: r`$X\sim N(500,100)$. Estimate $P(X>700)$.\soln $700$ is $+2\sigma$; the upper tail beyond $+2\sigma$ is about $2.5\%$.` + r`\ncurve{2}{3.8}{}` },
      { t: "Asymmetric empirical region", body: r`Estimate $P(\mu-\sigma<X<\mu+2\sigma)$.\soln $\tfrac{68}{2}+\tfrac{95}{2}=34\%+47.5\%=81.5\%$.` },
      { t: "Find sigma from a z-score", body: r`$x=90$ has $z=1.5$ and $\mu=75$. Find $\sigma$.\soln $1.5\sigma=90-75=15\Rightarrow\sigma=10$.` },
      { t: "Heights (three parts)", body: r`Heights are $N(170,8)$ cm. Find \\ \textbf{(a)} $z$ for $186$; \\ \textbf{(b)} percent taller than $178$; \\ \textbf{(c)} the middle-$95\%$ range.\soln (a) $z=2$. (b) $178$ is $+1\sigma$; about $16\%$ are above. (c) $170\pm16=$ $154$ to $186$.` },
    ],
    questions: [
      { ask: r`$X\sim N(60,4)$. Find the $z$-score of $x=68$.` },
      { ask: r`$X\sim N(100,15)$. Find the $z$-score of $x=85$.` },
      { ask: r`$X\sim N(50,10)$. What percent lies between $40$ and $60$?` },
      { ask: r`$X\sim N(200,20)$. Find $x$ when $z=1.5$.` },
      { ask: r`$X\sim N(500,50)$. What percent lies between $400$ and $600$?` },
      { ask: r`Which is better: $85$ on $N(75,5)$ or $92$ on $N(80,10)$? Use $z$-scores.` },
      { ask: r`For a standard normal, what percent lies above $z=1$?` },
      { ask: r`$x=48$ has $z=-2$ and $\mu=60$. Find $\sigma$.` },
      { ask: r`$X\sim N(100,10)$. Estimate $P(90<X<120)$ with the empirical rule.` },
      { ask: r`$X\sim N(170,8)$. Find the $z$-score of $154$.` },
      { ask: r`$X\sim N(25,3)$. Find $x$ when $z=-1$.` },
      { ask: r`What percent of a normal distribution lies beyond $\pm3\sigma$?` },
      { ask: r`IQ scores are $N(100,15)$. Find \\ \textbf{(a)} $z$ for $130$; \\ \textbf{(b)} percent above $130$; \\ \textbf{(c)} the middle-$68\%$ range.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$2$`, r`$-1$`, r`$68\%$`, r`$230$`, r`$95\%$`, r`$z=2$ vs $1.2$; the $85$ is better`, r`$\approx16\%$`, r`$\sigma=6$`, r`$34\%+47.5\%=81.5\%$`, r`$-2$`, r`$22$`, r`$\approx0.3\%$`, r`(a) $2$; (b) $\approx2.5\%$; (c) $85$ to $115$`],
  },
  {
    code: "4.3", unit: U, title: "Normal Probabilities & Percentiles",
    intro: r`Standardize, then read the table value $\Phi(z)=P(Z<z)$. Then $P(a<X<b)=\Phi(z_b)-\Phi(z_a)$, and percentiles invert the table: $x=\mu+z\sigma$.`,
    ideas: [r`$P(X<x)=\Phi(z)$ after standardizing.`, r`$P(a<X<b)=\Phi(z_b)-\Phi(z_a)$; upper tail $=1-\Phi(z)$.`, r`Percentile $\to$ $z$ $\to$ $x=\mu+z\sigma$.`],
    examples: [
      { t: "Left area", body: r`$X\sim N(100,15)$. Find $P(X<120)$.\soln $z=\tfrac{120-100}{15}=1.33$; $\Phi(1.33)=0.9082$.` + r`\ncurve{-3.8}{1.33}{}` },
      { t: "Upper tail", body: r`$X\sim N(100,15)$. Find $P(X>85)$.\soln $z=-1$; $P=1-\Phi(-1)=\Phi(1)=0.8413$.` },
      { t: "Between two values", body: r`$X\sim N(50,5)$. Find $P(45<X<55)$.\soln $\Phi(1)-\Phi(-1)=0.8413-0.1587=0.6826$.` + r`\ncurve{-1}{1}{}` },
      { t: "Percentile to value", body: r`Find the $90$th percentile of $N(500,100)$.\soln $z=1.28$; $x=500+128=628$.` },
      { t: "Target probability to value", body: r`$X\sim N(70,10)$. Find $x$ with $P(X>x)=0.05$.\soln $z=1.645$; $x=70+16.45=86.45$.` },
      { t: "Middle 95% interval", body: r`Find the central $95\%$ interval of $N(100,15)$.\soln $z=\pm1.96$: $100\pm29.4$, i.e. $70.6$ to $129.4$.` },
      { t: "Two-tailed area", body: r`Find $P(|Z|>2)$.\soln $2\bigl(1-\Phi(2)\bigr)=2(0.0228)=0.0456$.` },
      { t: "Find sigma from a probability", body: r`$X\sim N(200,\sigma)$ with $P(X<230)=0.84$. Find $\sigma$.\soln $\Phi(1)=0.84$, so $230$ is $+1\sigma$: $\sigma=30$.` },
      { t: "Exam scores (three parts)", body: r`Scores are $N(72,12)$. Find \\ \textbf{(a)} $P(X>90)$; \\ \textbf{(b)} $P(60<X<84)$; \\ \textbf{(c)} the $95$th percentile.\soln (a) $z=1.5$, $1-\Phi(1.5)=0.0668$. (b) $\Phi(1)-\Phi(-1)=0.6826$. (c) $z=1.645$, $72+19.74=91.74$.` },
    ],
    questions: [
      { ask: r`$X\sim N(100,15)$. Find $P(X<115)$.` },
      { ask: r`$X\sim N(50,4)$. Find $P(X>58)$.` },
      { ask: r`$X\sim N(200,20)$. Find $P(180<X<220)$.` },
      { ask: r`Find the $84$th percentile of $N(60,5)$.` },
      { ask: r`$X\sim N(500,100)$. Find $x$ with $P(X>x)=0.10$.` },
      { ask: r`Find $P(-1.5<Z<1.5)$.` },
      { ask: r`$X\sim N(72,12)$. Find $P(X>96)$.` },
      { ask: r`Find the central $90\%$ interval of $N(100,10)$.` },
      { ask: r`$X\sim N(25,4)$. Find $P(X<17)$.` },
      { ask: r`Find the $99$th percentile of $N(500,100)$.` },
      { ask: r`For any normal, find $P(X<\mu)$.` },
      { ask: r`$X\sim N(160,10)$. Find $P(150<X<180)$.` },
      { ask: r`Scores are $N(72,12)$. Find \\ \textbf{(a)} $P(X>90)$; \\ \textbf{(b)} $P(60<X<84)$; \\ \textbf{(c)} the $95$th percentile.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$\Phi(1)=0.8413$`, r`$1-\Phi(2)=0.0228$`, r`$\Phi(1)-\Phi(-1)=0.6826$`, r`$z\approx1\Rightarrow65$`, r`$z=1.28\Rightarrow628$`, r`$\Phi(1.5)-\Phi(-1.5)=0.8664$`, r`$z=2\Rightarrow0.0228$`, r`$100\pm16.45=83.55$ to $116.45$`, r`$z=-2\Rightarrow0.0228$`, r`$z=2.33\Rightarrow733$`, r`$0.5$`, r`$\Phi(2)-\Phi(-1)=0.8185$`, r`(a) $0.0668$; (b) $0.6826$; (c) $\approx91.7$`],
  },
  {
    code: "4.4", unit: U, title: "The Normal Approximation to the Binomial",
    intro: r`When $n$ is large with $np\ge5$ and $nq\ge5$, a binomial is close to a normal with $\mu=np$ and $\sigma=\sqrt{npq}$. Apply a continuity correction of $\pm0.5$ when switching from a count to a continuous range.`,
    ideas: [r`Check $np\ge5$ and $nq\ge5$ before approximating.`, r`$\mu=np$, $\sigma=\sqrt{npq}$.`, r`Continuity correction: widen the interval by $0.5$ to include the boundary count.`],
    examples: [
      { t: "Check conditions; find mu, sigma", body: r`$n=50,\ p=0.4$. Can we approximate? Find $\mu$ and $\sigma$.\soln $np=20,\ nq=30$ (both $\ge5$): yes. $\mu=20$, $\sigma=\sqrt{12}\approx3.46$.` },
      { t: "At least (continuity)", body: r`With $n=50,\ p=0.4$, find $P(X\ge25)$.\soln $P(X>24.5)$: $z=\tfrac{24.5-20}{3.46}=1.30$; $1-\Phi(1.30)=0.0968$.` + r`\ncurve{1.3}{3.8}{}` },
      { t: "At most (continuity)", body: r`With $n=50,\ p=0.4$, find $P(X\le15)$.\soln $P(X<15.5)$: $z=\tfrac{15.5-20}{3.46}=-1.30$; $\Phi(-1.30)=0.0968$.` },
      { t: "Exactly $k$ (two half-steps)", body: r`With $n=50,\ p=0.4$, estimate $P(X=20)$.\soln $P(19.5<X<20.5)$: $z=\pm0.14$; $\Phi(0.14)-\Phi(-0.14)\approx0.111$.` },
      { t: "Coin tosses", body: r`$n=100,\ p=0.5$. Find $P(X\ge60)$.\soln $\mu=50,\ \sigma=5$; $P(X>59.5)$: $z=1.9$; $1-\Phi(1.9)=0.0287$.` },
      { t: "Between two counts", body: r`$n=100,\ p=0.5$. Find $P(45\le X\le55)$.\soln $P(44.5<X<55.5)$: $z=\pm1.1$; $\Phi(1.1)-\Phi(-1.1)=0.7286$.` },
      { t: "Direction of the correction", body: r`For $n=80,\ p=0.5$, which boundary do you use for $P(X<40)$ vs. $P(X\le40)$?\soln $P(X<40)\to39.5$; $P(X\le40)\to40.5$ (widen to include the boundary count).` },
      { t: "When you cannot approximate", body: r`$n=20,\ p=0.1$. Is the normal approximation valid?\soln $np=2<5$: no --- use the exact binomial.` },
      { t: "Baseball (three parts)", body: r`$n=64,\ p=0.5$. Find \\ \textbf{(a)} $\mu$ and $\sigma$; \\ \textbf{(b)} $P(X\ge40)$; \\ \textbf{(c)} which correction to use.\soln (a) $\mu=32,\ \sigma=4$. (b) $P(X>39.5)$: $z=1.88$; $1-\Phi(1.88)=0.0301$. (c) use $39.5$.` },
    ],
    questions: [
      { ask: r`$n=50,\ p=0.4$. Find $\mu$ and $\sigma$.` },
      { ask: r`$n=40,\ p=0.2$. Is the normal approximation valid? Justify.` },
      { ask: r`$n=100,\ p=0.5$. Find $P(X\ge60)$ with continuity correction.` },
      { ask: r`$n=100,\ p=0.5$. Find $P(X\le40)$.` },
      { ask: r`$n=200,\ p=0.1$. Find $\mu$ and $\sigma$.` },
      { ask: r`$n=64,\ p=0.5$. Find $P(X>40)$.` },
      { ask: r`$n=50,\ p=0.5$. Estimate $P(X=25)$ with continuity correction.` },
      { ask: r`For $P(X<30)$, which continuity boundary do you use?` },
      { ask: r`$n=15,\ p=0.1$. Can you use the normal approximation?` },
      { ask: r`$n=400,\ p=0.5$. Find $\mu$ and $\sigma$.` },
      { ask: r`$n=100,\ p=0.3$. Find $P(X\le25)$.` },
      { ask: r`$n=100,\ p=0.5$. Find $P(45\le X\le55)$.` },
      { ask: r`$n=64,\ p=0.5$. Find \\ \textbf{(a)} $\mu,\sigma$; \\ \textbf{(b)} $P(X\ge40)$; \\ \textbf{(c)} the continuity boundary for $X\ge40$.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$\mu=20,\ \sigma=\sqrt{12}\approx3.46$`, r`$np=8,\ nq=32\ge5$: yes`, r`$P(X>59.5),\ z=1.9,\ 0.0287$`, r`$P(X<40.5),\ z=-1.9,\ 0.0287$`, r`$\mu=20,\ \sigma=\sqrt{18}\approx4.24$`, r`$P(X>40.5),\ z=2.13,\ 0.0166$`, r`$P(24.5<X<25.5)\approx0.113$`, r`$29.5$`, r`$np=1.5<5$: no`, r`$\mu=200,\ \sigma=10$`, r`$P(X<25.5),\ z=-0.98,\ 0.1635$`, r`$0.7286$`, r`(a) $32,\ 4$; (b) $z=1.88,\ 0.0301$; (c) $39.5$`],
  },
];
