// MDM4U Unit 5 worksheets — One-Variable Statistics.
// Textbook-level depth: sampling & bias, central tendency, spread, quartiles &
// box plots, distributions/histograms, z-scores. Each example/question a distinct
// idea. 9 worked examples + 13 questions + answer key each. No backtick quotes.
const r = String.raw;
const U = "5: One-Variable Statistics";

export default [
  {
    code: "5.1", unit: U, title: "Sampling Techniques & Bias",
    intro: r`Conclusions about a \emph{population} rest on a representative \emph{sample}. Distinguish a \emph{parameter} (a true population value) from a \emph{statistic} (its sample estimate), and choose a method that avoids bias.`,
    ideas: [r`Population vs. sample; parameter vs. statistic.`, r`Methods: simple random, stratified (by proportional groups), systematic (every $k$th), cluster (whole groups).`, r`Biases: sampling/coverage, non-response, response (wording), measurement.`],
    examples: [
      { t: "Population vs. sample", body: r`A factory makes 10\,000 bulbs; 200 are tested. Identify the population and the sample.\soln Population $=$ all 10\,000 bulbs; sample $=$ the 200 tested.` },
      { t: "Parameter vs. statistic", body: r`Is the mean lifetime of \emph{all} bulbs a parameter or a statistic?\soln A parameter --- it describes the whole population (the sample mean would be the statistic).` },
      { t: "Stratified sample", body: r`A school has 600 grade-9 and 400 grade-10 students. Take a stratified sample of 50.\soln Proportional: $\tfrac{600}{1000}(50)=30$ grade-9 and $\tfrac{400}{1000}(50)=20$ grade-10.` },
      { t: "Systematic sample", body: r`Choose 50 people systematically from 1000. Find the interval $k$.\soln $k=\tfrac{1000}{50}=20$: pick a random start, then every $20$th person.` },
      { t: "Cluster sample", body: r`Describe a cluster sample of a school's students.\soln Split into clusters (classes), randomly select a few whole classes, and survey everyone in them.` },
      { t: "Sampling (coverage) bias", body: r`An online poll surveys only website visitors. What is the flaw?\soln Sampling/coverage bias --- non-internet users are excluded, so the sample is unrepresentative.` },
      { t: "Response (wording) bias", body: r`Critique the question: \emph{Don't you agree our excellent mayor deserves re-election?}\soln The leading wording pushes a \emph{yes}, creating response bias.` },
      { t: "Non-response bias", body: r`A mailed survey gets a 10\% reply rate. Why is this a concern?\soln The 90\% who did not reply may differ systematically --- non-response bias.` },
      { t: "Diagnose and fix (three parts)", body: r`A firm phones customers only during work hours. \\ \textbf{(a)} name the bias; \\ \textbf{(b)} suggest a fix; \\ \textbf{(c)} is the result a parameter or a statistic?\soln (a) non-response/coverage bias. (b) call at varied times and add other contact methods. (c) a statistic.` },
    ],
    questions: [
      { ask: r`A city has 40\,000 voters; 500 are polled. Identify the population and sample.` },
      { ask: r`Is \emph{52\% of all voters support the plan} a parameter or a statistic?` },
      { ask: r`From 800 women and 200 men, take a stratified sample of 50. How many of each?` },
      { ask: r`Choose 40 items systematically from 2000. Find $k$.` },
      { ask: r`Name the method: three whole classes are chosen at random and all their students surveyed.` },
      { ask: r`Name the bias: a mailed survey has only a 12\% response rate.` },
      { ask: r`Name the bias in the question: \emph{Should wasteful government spending be cut?}` },
      { ask: r`Name the bias: a survey about favourite sport is taken at a hockey game.` },
      { ask: r`From grades of 300, 200, 100 students, take a proportional sample of 60. How many from each?` },
      { ask: r`Parameter or statistic: the mean age of 500 surveyed shoppers is 34.` },
      { ask: r`Name the method: every 25th shopper entering a mall is surveyed.` },
      { ask: r`Name the method: 5 neighbourhoods are chosen at random and all residents surveyed.` },
      { ask: r`A TV show asks viewers to phone in opinions. \\ \textbf{(a)} name two biases; \\ \textbf{(b)} is it reliable; \\ \textbf{(c)} suggest a better design.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`population $=$ 40\,000 voters; sample $=$ 500 polled`, r`statistic`, r`40 women, 10 men`, r`$k=50$`, r`cluster`, r`non-response bias`, r`response (leading/wording) bias`, r`sampling/coverage bias`, r`30, 20, 10`, r`statistic`, r`systematic`, r`cluster`, r`(a) self-selection + coverage; (b) not reliable; (c) random sample of the population`],
  },
  {
    code: "5.2", unit: U, title: "Measures of Central Tendency",
    intro: r`The \emph{mean} (sum$/n$), \emph{median} (middle value), and \emph{mode} (most frequent) each summarize the centre. Outliers and skew pull the mean away from the median.`,
    ideas: [r`Mean $=\dfrac{\sum x}{n}$; weighted mean $=\dfrac{\sum w x}{\sum w}$.`, r`Median $=$ middle (average the two middle values if $n$ is even).`, r`Outliers/skew move the mean more than the median; report the median for skewed data.`],
    examples: [
      { t: "Mean, median, mode", body: r`Find all three for $\{3,7,7,9,14\}$.\soln Mean $=\tfrac{40}{5}=8$; median $=7$; mode $=7$.` },
      { t: "Median of an even set", body: r`Find the median of $\{2,5,8,11\}$.\soln Average the two middle: $\tfrac{5+8}{2}=6.5$.` },
      { t: "Weighted mean", body: r`A mark is $70,80,90$ weighted $20\%,30\%,50\%$. Find the weighted mean.\soln $0.2(70)+0.3(80)+0.5(90)=14+24+45=83$.` },
      { t: "Effect of an outlier", body: r`Compare mean and median of $\{5,6,7,8,100\}$.\soln Mean $=\tfrac{126}{5}=25.2$; median $=7$. The outlier inflates the mean --- report the median.` },
      { t: "Grouped-data mean", body: r`For $x=1,2,3$ with frequencies $4,6,10$, find the mean.\soln $\dfrac{4(1)+6(2)+10(3)}{20}=\dfrac{46}{20}=2.3$.` },
      { t: "Find a missing value", body: r`Four numbers have mean $12$; three are $8,10,15$. Find the fourth.\soln Sum $=48$; fourth $=48-33=15$.` },
      { t: "Choosing the right measure", body: r`Incomes are strongly right-skewed. Which measure best describes a typical income?\soln The median --- it resists the few very high incomes.` },
      { t: "Mode for categories", body: r`Shoe sizes sold: $7,8,8,9,8,10$. Which measure applies?\soln The mode ($8$) --- the most frequently sold size.` },
      { t: "All three (multi-part)", body: r`For $\{4,8,8,10,15,15,15,20\}$ find \\ \textbf{(a)} mean; \\ \textbf{(b)} median; \\ \textbf{(c)} mode.\soln (a) $\tfrac{95}{8}=11.875$. (b) $\tfrac{10+15}{2}=12.5$. (c) $15$.` },
    ],
    questions: [
      { ask: r`Find the mean of $\{3,7,7,9,14\}$.` },
      { ask: r`Find the median of $\{3,7,7,9,14\}$.` },
      { ask: r`Find the mode of $\{3,7,7,9,14\}$.` },
      { ask: r`Find the median of $\{2,5,8,11\}$.` },
      { ask: r`Marks $70,80,90$ have weights $20\%,30\%,50\%$. Find the weighted mean.` },
      { ask: r`For $\{5,6,7,8,100\}$, find the mean and median; which is more representative?` },
      { ask: r`For $x=1,2,3$ with frequencies $4,6,10$, find the mean.` },
      { ask: r`Four numbers have mean $12$; three are $8,10,15$. Find the fourth.` },
      { ask: r`Which measure describes the most common shoe size sold?` },
      { ask: r`Find the median of $\{12,15,18,20,22,25\}$.` },
      { ask: r`Add the outlier $200$ to $\{2,4,6\}$. Find the new mean.` },
      { ask: r`Find the mean of $\{10,20,30,40,50\}$.` },
      { ask: r`For $\{4,8,8,10,15,15,15,20\}$ find \\ \textbf{(a)} mean; \\ \textbf{(b)} median; \\ \textbf{(c)} mode; \\ \textbf{(d)} which best describes the centre?`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\tfrac{40}{5}=8$`, r`$7$`, r`$7$`, r`$6.5$`, r`$83$`, r`mean $=25.2$, median $=7$; median`, r`$\tfrac{46}{20}=2.3$`, r`$15$`, r`mode`, r`$19$`, r`$\tfrac{212}{4}=53$`, r`$30$`, r`(a) $11.875$; (b) $12.5$; (c) $15$; (d) median`],
  },
  {
    code: "5.3", unit: U, title: "Measures of Spread",
    intro: r`Two data sets can share a mean yet differ wildly. The \emph{range} ($\max-\min$), \emph{IQR} ($Q_3-Q_1$), and \emph{standard deviation} $\sigma=\sqrt{\dfrac{\sum(x-\bar x)^2}{n}}$ measure how spread out the data are.`,
    ideas: [r`Range $=\max-\min$; IQR $=Q_3-Q_1$.`, r`Variance $=$ mean of squared deviations; $\sigma=\sqrt{\text{variance}}$.`, r`Adding a constant leaves $\sigma$ unchanged; scaling by $k$ multiplies $\sigma$ by $|k|$.`],
    examples: [
      { t: "Range", body: r`Find the range of $\{5,8,12,20\}$.\soln $20-5=15$.` },
      { t: "Standard deviation", body: r`Find the (population) standard deviation of $\{2,4,6,8,10\}$.\soln $\bar x=6$; squared deviations $16,4,0,4,16$ sum to $40$; variance $=\tfrac{40}{5}=8$; $\sigma=\sqrt{8}\approx2.83$.` },
      { t: "Same mean, different spread", body: r`Sets A and B both average $50$, with $\sigma_A=2$ and $\sigma_B=10$. Which is more consistent?\soln A --- its smaller $\sigma$ means values cluster tightly.` },
      { t: "IQR", body: r`Find the IQR of $\{3,5,7,9,11,13,15\}$.\soln Median $9$; $Q_1=5$, $Q_3=13$; IQR $=8$.` },
      { t: "Add a constant", body: r`Every value gains $5$. How does $\sigma$ change?\soln Unchanged --- shifting all data does not change the spread.` },
      { t: "Scale the data", body: r`Every value is tripled. How does $\sigma$ change?\soln It triples ($\sigma\to3\sigma$).` },
      { t: "Zero spread", body: r`Find $\sigma$ for $\{10,10,10,10\}$.\soln $0$ --- all values equal the mean.` },
      { t: "Variance", body: r`Find the (population) variance of $\{1,3,5,7,9\}$.\soln $\bar x=5$; squared deviations $16,4,0,4,16$ sum to $40$; variance $=8$.` },
      { t: "Full spread (multi-part)", body: r`For $\{2,4,4,4,5,5,7,9\}$ find \\ \textbf{(a)} mean; \\ \textbf{(b)} population $\sigma$; \\ \textbf{(c)} range.\soln (a) $\tfrac{40}{8}=5$. (b) squared deviations sum to $32$, variance $4$, $\sigma=2$. (c) $9-2=7$.` },
    ],
    questions: [
      { ask: r`Find the range of $\{5,8,12,20\}$.` },
      { ask: r`Find the population $\sigma$ of $\{2,4,6,8,10\}$.` },
      { ask: r`Find the IQR of $\{3,5,7,9,11,13,15\}$.` },
      { ask: r`Two sets average $50$ with $\sigma=2$ and $\sigma=10$. Which is more consistent?` },
      { ask: r`Every value in a set gains $5$. How does $\sigma$ change?` },
      { ask: r`Every value is multiplied by $3$. How does $\sigma$ change?` },
      { ask: r`Find $\sigma$ for $\{10,10,10,10\}$.` },
      { ask: r`Test scores run from $45$ to $98$. Find the range.` },
      { ask: r`Find the population variance of $\{1,3,5,7,9\}$.` },
      { ask: r`Find the IQR of $\{2,4,6,8,10,12,14,16\}$.` },
      { ask: r`A data set has $\sigma=0$. What does that mean?` },
      { ask: r`Set A has range $20$; set B has range $5$. Which is more spread out?` },
      { ask: r`For $\{2,4,4,4,5,5,7,9\}$ find \\ \textbf{(a)} mean; \\ \textbf{(b)} population $\sigma$; \\ \textbf{(c)} range.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$15$`, r`$\sqrt{8}\approx2.83$`, r`$13-5=8$`, r`$\sigma=2$`, r`unchanged`, r`multiplied by $3$`, r`$0$`, r`$53$`, r`$8$`, r`$Q_1=5,\ Q_3=13$, IQR $=8$`, r`all values are identical`, r`set A`, r`(a) $5$; (b) $2$; (c) $7$`],
  },
  {
    code: "5.4", unit: U, title: "Quartiles, Percentiles & Box Plots",
    intro: r`Quartiles slice ordered data into quarters. The \emph{five-number summary} (min, $Q_1$, median, $Q_3$, max) drives the box plot, and the $1.5\times\text{IQR}$ test flags outliers.`,
    ideas: [r`Five-number summary: min, $Q_1$, median, $Q_3$, max.`, r`Outlier fences: below $Q_1-1.5\,\text{IQR}$ or above $Q_3+1.5\,\text{IQR}$.`, r`A box plot pictures the summary; the median's position shows skew.`],
    examples: [
      { t: "Five-number summary", body: r`Summarize $\{3,6,7,9,12,15,18\}$.\soln Min $3$, $Q_1=6$, median $9$, $Q_3=15$, max $18$.` },
      { t: "IQR", body: r`Find the IQR above.\soln $Q_3-Q_1=15-6=9$.` },
      { t: "Outlier test", body: r`With $Q_1=20$, $Q_3=40$, is $75$ an outlier?\soln IQR $=20$; upper fence $=40+1.5(20)=70$; $75>70$, so yes.` },
      { t: "Percentile meaning", body: r`Interpret the $80$th percentile.\soln $80\%$ of the data lie at or below that value.` },
      { t: "Box plot", body: r`Draw the box plot for min $1$, $Q_1=3$, median $6.5$, $Q_3=10$, max $12$.\soln The box spans $Q_1$ to $Q_3$ with the median inside; whiskers reach the extremes.` + r`\boxplot{1}{3}{6.5}{10}{12}{0}{13}` },
      { t: "Compare two box plots", body: r`Box A has a higher median and a shorter box than box B. Compare.\soln A is centred higher and is more consistent (less spread) than B.` },
      { t: "Percentile rank", body: r`Out of 20 values, 15 are below a score. Find its percentile rank.\soln $\tfrac{15}{20}=75$th percentile.` },
      { t: "Skew from a box plot", body: r`The median sits near the left of the box. What skew is indicated?\soln Right (positive) skew --- the upper quarter is stretched.` },
      { t: "Full analysis (multi-part)", body: r`For $\{4,7,8,10,12,14,15,18,21,50\}$ find \\ \textbf{(a)} the five-number summary; \\ \textbf{(b)} the IQR; \\ \textbf{(c)} whether $50$ is an outlier.\soln (a) min $4$, $Q_1=8$, median $13$, $Q_3=18$, max $50$. (b) $10$. (c) fence $=18+15=33$; $50>33$, so yes.` },
    ],
    questions: [
      { ask: r`Give the five-number summary of $\{3,6,7,9,12,15,18\}$.` },
      { ask: r`Find the IQR when $Q_1=6$ and $Q_3=15$.` },
      { ask: r`With $Q_1=20$, $Q_3=40$, is $75$ an outlier?` },
      { ask: r`What does the $90$th percentile mean?` },
      { ask: r`Find the median of $\{5,10,15,20,25,30,35,40\}$.` },
      { ask: r`Find $Q_1$ and $Q_3$ for that data.` },
      { ask: r`Find the IQR of $\{5,10,15,20,25,30,35,40\}$.` },
      { ask: r`With $Q_1=10$, $Q_3=18$, is $2$ an outlier?` },
      { ask: r`A box plot's median is near the left of the box. What skew?` },
      { ask: r`Out of 20 values, 15 are below a score. Find its percentile rank.` },
      { ask: r`Give the five-number summary of $\{2,4,4,6,8,10,12\}$.` },
      { ask: r`Which resists outliers: the range or the IQR?` },
      { ask: r`For $\{4,7,8,10,12,14,15,18,21,50\}$ find \\ \textbf{(a)} the five-number summary; \\ \textbf{(b)} the IQR; \\ \textbf{(c)} is $50$ an outlier?`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`min $3,\ Q_1=6,\ \text{med}=9,\ Q_3=15,\ \max=18$`, r`$9$`, r`fence $=70$; $75>70$, yes`, r`$90\%$ of the data lie at or below it`, r`$22.5$`, r`$Q_1=12.5,\ Q_3=32.5$`, r`$20$`, r`fence $=-2$; $2>-2$, no`, r`right (positive) skew`, r`$75$th`, r`min $2,\ Q_1=4,\ \text{med}=6,\ Q_3=10,\ \max=12$`, r`the IQR`, r`(a) $4,8,13,18,50$; (b) $10$; (c) yes ($>33$)`],
  },
  {
    code: "5.5", unit: U, title: "Displaying & Describing Distributions",
    intro: r`A histogram shows the \emph{shape} of a distribution. Describe it by symmetry (symmetric, left- or right-skewed) and by the number of peaks (unimodal, bimodal), then compare centre and spread.`,
    ideas: [r`Frequency vs. relative-frequency histograms.`, r`Shape: symmetric, right-skew (tail right), left-skew (tail left), unimodal/bimodal.`, r`Right-skew $\Rightarrow$ mean $>$ median; left-skew $\Rightarrow$ mean $<$ median.`],
    examples: [
      { t: "Build a histogram", body: r`Frequencies for classes $1$--$5$ are $4,8,10,6,2$. Sketch the histogram.\soln Bars of those heights; the tallest is at class $3$.` + r`\hist{(1,4) (2,8) (3,10) (4,6) (5,2)}{12}` },
      { t: "Relative frequency", body: r`Convert the frequency $8$ (of a total $30$) to a relative frequency.\soln $\tfrac{8}{30}\approx0.27$, or $27\%$.` },
      { t: "Symmetric shape", body: r`A histogram rises to a central peak and falls evenly. Describe it.\soln Symmetric and unimodal --- mean $\approx$ median.` },
      { t: "Right skew", body: r`Most incomes are low with a long high tail. Describe the shape and compare mean/median.\soln Right- (positively) skewed; mean $>$ median.` },
      { t: "Left skew", body: r`Test scores bunch near the top with a low tail. Describe it.\soln Left- (negatively) skewed; mean $<$ median.` },
      { t: "Bimodal", body: r`A histogram has two separate peaks. What is it called, and what might it mean?\soln Bimodal --- often two subgroups mixed together.` },
      { t: "Read a histogram", body: r`Using the frequencies $4,8,10,6,2$, how many values are in classes $3$ or higher?\soln $10+6+2=18$.` },
      { t: "Compare distributions", body: r`Two classes have the same mean, but one histogram is wider. Compare.\soln Same centre, but the wider one has greater spread (larger $\sigma$).` },
      { t: "Interpret (multi-part)", body: r`For frequencies $2,5,9,7,3$ over classes $1$--$5$, \\ \textbf{(a)} state the total; \\ \textbf{(b)} the modal class; \\ \textbf{(c)} the shape.\soln (a) $26$. (b) class $3$. (c) roughly symmetric, unimodal.` },
    ],
    questions: [
      { ask: r`Frequencies for classes $1$--$4$ are $3,7,5,1$. Which class is the mode?` },
      { ask: r`Convert a frequency of $12$ (total $40$) to a relative frequency.` },
      { ask: r`A histogram has a long right tail. Name the shape.` },
      { ask: r`For a right-skewed distribution, is the mean above or below the median?` },
      { ask: r`A histogram has two peaks. What is it called?` },
      { ask: r`Frequencies $5,8,10,4,3$: how many values are in classes $3$ or higher?` },
      { ask: r`For a left-skewed distribution, compare mean and median.` },
      { ask: r`Two histograms share a mean; one is narrower. Compare their spread.` },
      { ask: r`A symmetric, single-peaked histogram --- what can you say about mean vs. median?` },
      { ask: r`Frequencies $2,5,9,7,3$ (classes $1$--$5$): find the total.` },
      { ask: r`For those frequencies, name the modal class.` },
      { ask: r`Relative frequencies must sum to what value?` },
      { ask: r`For frequencies $1,3,8,6,2$ (classes $1$--$5$), \\ \textbf{(a)} total; \\ \textbf{(b)} modal class; \\ \textbf{(c)} describe the shape.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`class $2$`, r`$\tfrac{12}{40}=0.30$`, r`right- (positively) skewed`, r`above`, r`bimodal`, r`$10+4+3=17$`, r`mean $<$ median`, r`the narrower one has less spread`, r`mean $\approx$ median`, r`$26$`, r`class $3$`, r`$1$`, r`(a) $20$; (b) class $3$; (c) roughly symmetric, unimodal`],
  },
  {
    code: "5.6", unit: U, title: "The z-Score & Comparing Data",
    intro: r`A $z$-score, $z=\dfrac{x-\bar x}{\sigma}$, gives a value's standardized position: how many standard deviations it sits from the mean. It lets you compare values from different data sets and, for normal data, convert to a percentile.`,
    ideas: [r`$z=\dfrac{x-\bar x}{\sigma}$; invert with $x=\bar x+z\sigma$.`, r`Higher $z$ $=$ relatively higher standing; a negative $z$ is below the mean.`, r`For normal data, a $z$-score maps to a percentile.`],
    examples: [
      { t: "Compute a z-score", body: r`A score is $85$ where $\bar x=70,\ \sigma=10$. Find $z$.\soln $z=\dfrac{85-70}{10}=1.5$.` },
      { t: "Compare two data sets", body: r`Ann scores $82$ on a test with $\bar x=75,\sigma=5$; Ben scores $88$ with $\bar x=80,\sigma=8$. Who did relatively better?\soln $z_{\text{Ann}}=1.4$, $z_{\text{Ben}}=1.0$; Ann.` },
      { t: "z to percentile", body: r`For normal data, what percentile is $z=1$?\soln $\Phi(1)=0.8413$: the $84$th percentile.` },
      { t: "Value from a z-score", body: r`With $\bar x=60,\ \sigma=8$, find the value at $z=-1.25$.\soln $x=60+(-1.25)(8)=50$.` },
      { t: "Which is more extreme", body: r`Compare $z=-2.1$ and $z=1.8$.\soln $|-2.1|>|1.8|$, so $z=-2.1$ is more extreme (further from the mean).` },
      { t: "Negative z-score", body: r`A value has $z=-0.5$. Where does it lie?\soln Half a standard deviation \emph{below} the mean.` },
      { t: "Standardize a value", body: r`In a set with $\bar x=100,\ \sigma=12$, standardize $x=118$.\soln $z=\dfrac{118-100}{12}=1.5$.` },
      { t: "Percentile to value", body: r`Normal data with $\bar x=500,\ \sigma=100$: find the $90$th percentile.\soln $z=1.28$; $x=500+128=628$.` },
      { t: "Heights (multi-part)", body: r`Heights are $\bar x=165,\ \sigma=7$ (normal). Find \\ \textbf{(a)} $z$ for $179$; \\ \textbf{(b)} the percentile; \\ \textbf{(c)} the height at the $16$th percentile.\soln (a) $z=2$. (b) $\Phi(2)=0.9772$, the $\approx98$th percentile. (c) $z=-1$: $165-7=158$.` },
    ],
    questions: [
      { ask: r`A score is $92$ with $\bar x=80,\ \sigma=6$. Find $z$.` },
      { ask: r`With $\bar x=50,\ \sigma=4$, find $z$ for $x=42$.` },
      { ask: r`Who did better: $z=1.2$ or $z=0.9$?` },
      { ask: r`With $\bar x=70,\ \sigma=10$, find the value at $z=2$.` },
      { ask: r`Which is more extreme: $z=-1.9$ or $z=1.5$?` },
      { ask: r`A value has $z=-1$. Describe its position.` },
      { ask: r`For normal data, what percentile is $z=2$?` },
      { ask: r`With $\bar x=100,\ \sigma=12$, standardize $x=76$.` },
      { ask: r`Ann: $82$ on $N(75,5)$. Ben: $88$ on $N(80,8)$. Who is relatively higher?` },
      { ask: r`Normal data $\bar x=500,\ \sigma=100$: find the $84$th percentile.` },
      { ask: r`With $\bar x=25,\ \sigma=3$, find the value at $z=-1$.` },
      { ask: r`For normal data, what percentile is $z=0$?` },
      { ask: r`Heights are $N(165,7)$. Find \\ \textbf{(a)} $z$ for $179$; \\ \textbf{(b)} the percentile; \\ \textbf{(c)} the height at the $16$th percentile.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$2$`, r`$-2$`, r`$z=1.2$`, r`$90$`, r`$z=-1.9$`, r`one $\sigma$ below the mean`, r`$\approx98$th ($\Phi(2)=0.9772$)`, r`$-2$`, r`Ann ($z=1.4$ vs $1.0$)`, r`$z=1\Rightarrow600$`, r`$22$`, r`$50$th`, r`(a) $2$; (b) $\approx98$th; (c) $158$`],
  },
];
