// MDM4U Unit 6 worksheets — Two-Variable Statistics.
// In MDM4U scope: r and the line of best fit come FROM TECHNOLOGY, then are
// interpreted/used (predict, interpolate/extrapolate, r^2 = % explained, residual
// = observed - predicted, correlation vs causation). NO by-hand least-squares
// derivation. Each example/question a distinct idea. No backtick quotes in r`...`.
const r = String.raw;
const U = "6: Two-Variable Statistics";

// ── 6.1 helpers: every table, plot and quoted r below comes from these arrays ──
const W61 = {
  car: { x: [1, 2, 3, 4, 5, 6, 7, 8, 9], y: [24.1, 21.2, 19.8, 17.9, 15.3, 13.6, 11.2, 9.8, 8.1] },
  steps: { x: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12], y: [72, 76, 69, 75, 70, 73, 68, 74, 71, 69] },
  ball: { x: [0, 1, 2, 3, 4, 5, 6], y: [1, 6, 9, 10, 9, 6, 1] },
  err: { x: [3, 4, 5, 6, 7, 8, 9, 10], y: [96, 103, 110, 116, 122, 12.7, 133, 138] },
};
const G61 = {
  g2: { x: [28, 29, 30, 31, 32, 29.5, 30.5], y: [62, 70, 58, 66, 60, 64, 68] },
  g8: { x: [38, 39, 40, 41, 42, 43, 39.5, 41.5], y: [150, 142, 158, 148, 155, 146, 152, 144] },
};
const Q61 = {
  mistakes: { x: [1, 2, 3, 4, 5, 6, 7, 8], y: [14, 12, 13, 10, 9, 7, 6, 4] },
  expo: { x: [0, 1, 2, 3, 4, 5, 6], y: [1, 2, 4, 8, 16, 32, 64] },
  lemon: { x: [18, 20, 22, 24, 26, 28, 30, 32], y: [41, 49, 48, 58, 62, 66, 74, 79] },
};
const pts = (d, idx) => (idx ?? d.x.map((_, i) => i)).map((i) => `(${d.x[i]},${d.y[i]})`).join("");
const tab = (xl, yl, d) => r`\begin{center}\footnotesize\begin{tabular}{|l|*{${d.x.length}}{c|}}\hline ${xl} & ${d.x.join(" & ")} \\ \hline ${yl} & ${d.y.join(" & ")} \\ \hline\end{tabular}\end{center}`;
const sc = (x0, x1, y0, y1, xl, yl, p, o = "") => r`\scatterl{${x0}}{${x1}}{${y0}}{${y1}}{${xl}}{${yl}}{\addplot[only marks,mark=*,exblue,mark size=2pt] coordinates {${p}};${o ? r`\addplot[only marks,mark=*,red,mark size=2.8pt] coordinates {${o}};` : ""}}`;
const scgroups = () => r`\scatterl{26}{45}{40}{170}{Shoe size (EU)}{Words per minute}{\addplot[only marks,mark=*,exblue,mark size=2pt] coordinates {${pts(G61.g2)}};\addplot[only marks,mark=*,qorange,mark size=2pt] coordinates {${pts(G61.g8)}};}`;

export default [
  {
    code: "6.1", unit: U, title: "Scatter Plots & Correlation",
    intro: r`A scatter plot shows paired data as points. Describe it by \emph{direction}, \emph{form}, \emph{strength} and \emph{unusual features}, in context. The correlation coefficient $r$ (from technology) measures the strength and direction of a \emph{linear} relationship, from $-1$ to $1$. A strong correlation shows \emph{association}, not necessarily \emph{cause and effect}.`,
    ideas: [
      r`Explanatory ($x$) variable predicts; response ($y$) variable is predicted. Roles are not a claim of cause.`,
      r`Describe: direction (positive/negative), form (linear/curved), strength, unusual features (outliers, clusters).`,
      r`$-1\le r\le1$: sign $=$ direction, $|r|=$ strength, $r$ detects only \emph{linear} association, and one outlier can change it a lot.`,
      r`$r$ has no units; changing units or swapping axes keeps $r$; reversing one scale flips its sign.`,
      r`Correlation $\ne$ causation. Name the type of relationship: cause and effect, common cause, reverse cause and effect, presumed, or accidental --- and justify it with the reason for the link.`,
    ],
    examples: [
      { t: "Assign the roles", body: r`Name the explanatory and response variable. \\ \textbf{(a)} A teen's nightly sleep and next-day reaction time. \\ \textbf{(b)} A tree's age and its trunk diameter. \\ \textbf{(c)} A company's monthly advertising spending and its website visits.\soln (a) explanatory: hours of sleep; response: reaction time. (b) explanatory: age; response: trunk diameter. (c) explanatory: advertising spending; response: website visits. In each case the first variable is the one used to predict the second.` },
      { t: "Plot and describe", body: r`The age of nine used cars and their resale value are recorded. Technology gives $r=-0.998$. Describe the relationship.` + tab("Age (years)", r`Value (\$1000s)`, W61.car) + sc(0, 10, 0, 26, "Age of car (years)", r`Value (\$1000s)`, pts(W61.car)) + r`\soln The points fall steadily from upper left to lower right and hug a straight band: a \textbf{strong, negative, linear} relationship between a car's age and its resale value, with no unusual features.` },
      { t: "A weak relationship", body: r`Ten adults record their average daily steps (in thousands) and their resting heart rate. Technology gives $r=-0.37$. Describe the relationship.` + tab("Steps (1000s)", "Heart rate (bpm)", W61.steps) + sc(2, 13, 64, 80, "Daily steps (thousands)", "Resting heart rate (bpm)", pts(W61.steps)) + r`\soln There is a slight downward drift (\textbf{negative}), the points are loosely scattered about a line (\textbf{linear}, but \textbf{weak}, $|r|=0.37$): more steps goes with a slightly lower heart rate, but individual points vary widely. No outliers.` },
      { t: "A pattern that $r$ misses", body: r`A ball's height is recorded each second after it is thrown. Technology gives $r=0$. Is height unrelated to time?` + tab("Time (s)", "Height (m)", W61.ball) + sc(-0.5, 6.5, 0, 12, "Time (s)", "Height (m)", pts(W61.ball)) + r`\soln No. The points trace a clear symmetric arch, so the relationship is strong but \textbf{non-linear}: it rises, then falls, so there is no overall direction. $r=0$ only says there is no \emph{linear} trend.` },
      { t: "An outlier from a recording error", body: r`Heights of children aged 3 to 10 are entered in a spreadsheet; the age-8 height was typed as $12.7$ instead of $127$. Technology gives $r=0.12$ with the error and $r=0.998$ after correcting it.` + tab("Age (years)", "Height (cm)", W61.err) + sc(2, 11, 0, 150, "Age (years)", "Height (cm)", pts(W61.err, [0, 1, 2, 3, 4, 6, 7]), pts(W61.err, [5])) + r`\soln The point $(8,12.7)$ is a far outlier that drags $r$ from $0.998$ to $0.12$, hiding a very strong, positive, linear relationship. Because the cause is a known typing error, \emph{correct} it to $127$ (and say so); do not simply delete points to improve $r$.` },
      { t: "Rank by strength", body: r`For plants, technology gives $r$ between height after six weeks and: sunlight hours $0.88$; daily water $0.52$; soil pH $-0.12$; night temperature $-0.93$. Which has the strongest relationship, which the weakest, and which are negative?\soln Compare $|r|$: $0.93>0.88>0.52>0.12$. Strongest: night temperature ($-0.93$). Weakest: soil pH ($-0.12$). Negative: night temperature and soil pH.` },
      { t: "Units and reversed scales", body: r`Distance run $x$ (km) and calories burned $y$ have $r=0.89$. Find $r$ if \\ \textbf{(a)} distance is in miles; \\ \textbf{(b)} the axes are swapped; \\ \textbf{(c)} $y$ is replaced by $1000-y$ (calories \emph{remaining} of a 1000 kcal goal).\soln (a) $0.89$ --- units do not change $r$. (b) $0.89$ --- $r$ is symmetric in $x$ and $y$. (c) $-0.89$ --- reversing one scale flips the sign only.` },
      { t: "Two hidden groups", body: r`Shoe size and reading speed (words per minute) are recorded for Grade 2 students (blue) and Grade 8 students (orange). All 15 students give $r=0.96$; within Grade 2 alone $r=-0.18$; within Grade 8 alone $r=-0.05$.` + scgroups() + r`\soln The combined $r$ is strong only because of the \emph{gap between two clusters}. Inside each grade there is no linear pattern ($r$ near $0$). Grade level (age) is the hidden factor driving both shoe size and reading speed; do not describe the combined data as one linear trend.` },
      { t: "Name the type of relationship", body: r`Each pair is positively correlated. Name the most likely type of relationship and justify it. \\ \textbf{(a)} The number of fire trucks sent to a fire and the dollar damage. \\ \textbf{(b)} The number of snowplows a city owns and its yearly snowfall. \\ \textbf{(c)} Hours of practice and a dancer's competition score. \\ \textbf{(d)} The number of vowels in a town's name and the town's population. \\ \textbf{(e)} A person's grip strength and their running speed.\soln (a) \emph{Common cause}: the size of the fire drives both. (b) \emph{Reverse cause and effect}: heavy snowfall leads a city to buy more plows. (c) \emph{Cause and effect}: practice directly improves skill (a clear mechanism, though a sample should be large). (d) \emph{Accidental}: no logical link. (e) \emph{Presumed}: both reflect general fitness, but neither causes the other and no single third variable is obvious.` },
    ],
    questions: [
      { ask: r`Name the explanatory and response variables: a river's water level (m) and the day's rainfall (mm).`, ws: "1.6cm" },
      { ask: r`Eight musicians record weekly practice hours and the number of mistakes in a recital. Technology gives $r=-0.98$. Describe the relationship in context.` + tab("Practice (h/week)", "Mistakes", Q61.mistakes) + sc(0, 9, 0, 16, "Practice (hours/week)", "Mistakes", pts(Q61.mistakes)), recap: r`Describe the practice-vs-mistakes scatter plot ($r=-0.98$) in context.`, ws: "2.2cm" },
      { ask: r`Match each value of $r$ to a description: $0.97,\ -0.33,\ 0.62,\ -0.91$. Descriptions: strong negative, weak negative, moderate positive, strong positive.`, ws: "2.4cm" },
      { ask: r`Name the most likely type of relationship and justify it. \\ \textbf{(a)} Umbrella sales and raincoat sales in a town. \\ \textbf{(b)} The number of passengers on a bus and the bus's total fuel use. \\ \textbf{(c)} The number of letters in a student's surname and their test score. \\ \textbf{(d)} A city's number of hospitals and its number of schools.`, recap: r`Name the type of relationship (cause and effect, common cause, reverse, presumed or accidental) for four pairs.`, ws: "3.4cm" },
      { ask: r`All points lie exactly on a straight line that rises to the right. What is $r$? What is $r$ if the line falls?`, ws: "2cm" },
      { ask: r`The data below follow $y=2^{x}$ and technology gives $r=0.88$. Describe the form, and explain why \textquotedblleft{}strong linear relationship\textquotedblright{} would be a poor description.` + tab("$x$", "$y$", Q61.expo) + sc(-1, 7, 0, 70, "$x$", "$y$", pts(Q61.expo)), recap: r`Data follow $y=2^x$ ($r=0.88$): describe the form and say why \textquotedblleft{}strong linear\textquotedblright{} is a poor description.`, ws: "2.2cm" },
      { ask: r`A scatter plot has $r=-0.31$. After one far-off point is removed, $r=-0.94$. \\ \textbf{(a)} What does this show? \\ \textbf{(b)} What must you do before deleting the point?`, ws: "2.6cm" },
      { ask: r`A survey finds that adults who take a daily vitamin have lower blood pressure ($r=-0.40$). \\ \textbf{(a)} Give two explanations other than \textquotedblleft{}vitamins lower blood pressure\textquotedblright{}. \\ \textbf{(b)} Describe a study that could test whether vitamins really do lower blood pressure.`, recap: r`Vitamins and blood pressure ($r=-0.40$): two other explanations; design a study to test cause.`, ws: "3.2cm" },
      { ask: r`Countries with more televisions per person have longer life expectancy ($r=0.80$). Does owning televisions lengthen life? Name a lurking variable.`, ws: "2.4cm" },
      { ask: r`Streets with more security cameras report more break-ins ($r=0.60$). Explain how reverse cause could account for this.`, ws: "2.4cm" },
      { ask: r`Sketch a scatter plot of about eight points that is positive, linear and weak, with one outlier.`, grid: true, recap: r`Sketch a positive, linear, weak scatter with one outlier.` },
      { ask: r`A classmate says \textquotedblleft{}$r=0.92$ means 92\% of the points lie on the line.\textquotedblright{} Explain the error.`, ws: "2.4cm" },
      { ask: r`A food truck records the day's high temperature and the cups of lemonade sold. Technology gives $r=0.99$.` + tab(r`High ($^\circ$C)`, "Cups sold", Q61.lemon) + r`\par\smallskip\textbf{(a)} Name the explanatory and response variables. \\ \textbf{(b)} Describe the relationship. \\ \textbf{(c)} Find $r$ if temperature is converted to $^\circ$F. \\ \textbf{(d)} A rainy day at $24^\circ$C sells only 12 cups. How would this point appear, and what would it do to $r$? \\ \textbf{(e)} Does hot weather \emph{cause} higher sales? What would you need to be sure?`, recap: r`Lemonade truck ($r=0.99$): (a) roles; (b) describe; (c) $^\circ$F; (d) effect of a 12-cup rainy day; (e) cause and effect?`, challenge: true, ws: "6.5cm" },
    ],
    answers: [
      r`explanatory: rainfall; response: water level`,
      r`strong, negative, linear: more practice goes with fewer mistakes; no outliers`,
      r`$0.97$ strong positive; $-0.33$ weak negative; $0.62$ moderate positive; $-0.91$ strong negative`,
      r`(a) common cause (rainy weather); (b) cause and effect (more passengers weigh more, so more fuel); (c) accidental (no logical link); (d) common cause (city population)`,
      r`$r=1$ (rising line); $r=-1$ (falling line)`,
      r`curved (exponential growth) and increasing; $r$ measures only linear fit, so $0.88$ overstates a line's suitability`,
      r`(a) one outlier hid a strong negative linear pattern; (b) find out why it is unusual; correct or delete only if it is an error, otherwise keep it and report both $r$ values`,
      r`(a) common cause: people who take vitamins may exercise and eat better; reverse cause: people already watching their health are the ones who take vitamins; (b) randomly assign volunteers to a vitamin group or a placebo group, keep all else the same, and compare blood pressure`,
      r`no; lurking variable: national wealth/health care, which raises both`,
      r`crime leads residents to install cameras, so break-ins (the response) cause the cameras (the \textquotedblleft{}explanatory\textquotedblright{} variable)`,
      r`about eight points rising loosely, plus one point far from the pattern`,
      r`$r$ measures the strength of a \emph{linear} trend, not a percent of points; few points lie exactly on a line unless $|r|=1$`,
      r`(a) explanatory: temperature; response: cups sold; (b) strong, positive, linear; (c) $0.99$ (unchanged); (d) a point far below the pattern (outlier) that would lower $r$; (e) no; association only --- a randomized experiment would be needed`,
    ],
  },
  {
    code: "6.2", unit: U, title: "Correlation & Linear Regression",
    intro: r`Technology fits a \emph{line of best fit} $\hat y=ax+b$ to linear data. Its slope $a$ is the rate of change, its intercept $b$ the baseline; substitute an $x$ to \emph{predict} a $y$. The value $r$ reports how well the line fits.`,
    ideas: [r`Line of best fit $\hat y=ax+b$ (from technology).`, r`Slope $=$ rate of change; intercept $=$ value when $x=0$.`, r`Predict by substitution; $r$ measures the fit (not the steepness).`],
    examples: [
      { t: "Predict from a line", body: r`For $\hat y=2x+5$, predict $y$ at $x=10$.\soln $\hat y=2(10)+5=25$.` },
      { t: "Interpret slope and intercept", body: r`A cost model is $\hat y=0.5x+20$. Interpret its parts.\soln Each extra unit adds \$0.50 (slope); the fixed cost is \$20 (intercept).` },
      { t: "Interpolate", body: r`Data run over $x=1$ to $10$ with $\hat y=1.2x+3$. Predict at $x=6$.\soln $\hat y=1.2(6)+3=10.2$ --- an interpolation, so reliable.` },
      { t: "Read a technology result", body: r`Software reports $\hat y=1.2x+3$ with $r=0.95$. Interpret.\soln A strong positive linear fit; each unit of $x$ raises $\hat y$ by $1.2$.` },
      { t: "Predicted vs. actual (residual)", body: r`With $\hat y=2x+1$, the actual $y$ at $x=5$ is $13$. Find the residual.\soln Predicted $11$; residual $=13-11=+2$.` },
      { t: "r vs. slope", body: r`Two lines both have slope $2$, but $r=0.99$ and $r=0.6$. What differs?\soln The steepness is the same; $r$ shows the first data hug the line far more tightly.` },
      { t: "Sign agreement", body: r`If $r=-0.9$, what is the sign of the best-fit slope?\soln Negative --- $r$ and the slope always share a sign.` },
      { t: "Scatter with a fitted line", body: r`The line $\hat y=2x+1$ is fitted to the data. Predict at $x=4$.\soln $\hat y=9$.` + r`\scatter{0}{7}{0}{14}{\addplot[only marks,mark=*,exblue] coordinates {(1,3)(2,5)(3,6)(4,9)(5,11)}; \addplot[qorange,thick,domain=0:6]{2*x+1};}` },
      { t: "Full use (multi-part)", body: r`Sales follow $\hat y=3x+10$. Find \\ \textbf{(a)} the prediction at $x=8$; \\ \textbf{(b)} the meaning of the slope; \\ \textbf{(c)} the residual if the actual value at $x=8$ is $40$.\soln (a) $34$. (b) each unit of $x$ adds $3$ in sales. (c) $40-34=+6$.` },
    ],
    questions: [
      { ask: r`For $\hat y=2x+1$, predict $y$ at $x=6$.` },
      { ask: r`For $\hat y=-0.5x+20$, predict $y$ at $x=10$.` },
      { ask: r`Interpret the slope of the cost model $\hat y=4x+50$.` },
      { ask: r`Which line fits better: one with $r=0.98$ or one with $r=0.6$?` },
      { ask: r`Predicted $y=20$, actual $y=22$. Find the residual.` },
      { ask: r`For $\hat y=1.5x+2$, predict $y$ at $x=4$.` },
      { ask: r`Interpret the intercept of $\hat y=3x+12$.` },
      { ask: r`For $\hat y=0.1x+5$, predict at $x=100$. What caution applies?` },
      { ask: r`Which describes the strength of a linear relationship: $r$ or the slope?` },
      { ask: r`For $\hat y=-2x+30$, at what $x$ does $\hat y=10$?` },
      { ask: r`Predicted $y=18$, actual $y=15$. Find the residual.` },
      { ask: r`If $r=-0.9$, is the best-fit slope positive or negative?` },
      { ask: r`Sales follow $\hat y=3x+10$. Find \\ \textbf{(a)} the prediction at $x=8$; \\ \textbf{(b)} the slope's meaning; \\ \textbf{(c)} the residual if the actual is $40$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$13$`, r`$15$`, r`each unit adds $4$`, r`$r=0.98$`, r`$+2$`, r`$8$`, r`value when $x=0$ is $12$`, r`$15$ --- but this is extrapolation`, r`$r$`, r`$x=10$`, r`$-3$`, r`negative`, r`(a) $34$; (b) $+3$ per unit; (c) $+6$`],
  },
  {
    code: "6.3", unit: U, title: "The Coefficient of Determination & Prediction",
    intro: r`The coefficient of determination $r^{2}$ is the fraction of the variation in $y$ explained by the linear model. Trust \emph{interpolation} (inside the data) but be wary of \emph{extrapolation} (outside it). A residual is observed $-$ predicted.`,
    ideas: [r`$r^{2}$ $=$ proportion of variation in $y$ explained by the model.`, r`Interpolation (inside the range) is reliable; extrapolation (outside) is risky.`, r`Residual $=$ observed $-$ predicted; $0$ means the point is on the line.`],
    examples: [
      { t: "Compute r squared", body: r`If $r=0.8$, find $r^{2}$ and interpret it.\soln $r^{2}=0.64$: $64\%$ of the variation in $y$ is explained by the model.` },
      { t: "Interpret r squared", body: r`A model has $r^{2}=0.9$. What does that mean?\soln $90\%$ of the variation in $y$ is explained; $10\%$ is not.` },
      { t: "Recover r from r squared", body: r`A positive scatter has $r^{2}=0.49$. Find $r$.\soln $r=+\sqrt{0.49}=0.7$ (positive, matching the scatter).` },
      { t: "Interpolate vs. extrapolate", body: r`Data run over $x=0$ to $50$. Is a prediction at $x=20$ interpolation or extrapolation?\soln Interpolation --- $x=20$ is inside the range, so it is reliable.` },
      { t: "Find a residual", body: r`Observed $y=30$, predicted $\hat y=27$. Find the residual.\soln $30-27=+3$ --- the point sits above the line.` },
      { t: "Why extrapolation is risky", body: r`Why distrust a prediction far outside the data?\soln The pattern may not continue beyond the observed range; the model is unverified there.` },
      { t: "Weak model", body: r`A model has $r^{2}=0.25$. Comment.\soln Only $25\%$ of the variation is explained --- a weak fit; $75\%$ is unexplained.` },
      { t: "Compare two models", body: r`Model A: $r^{2}=0.92$; Model B: $r^{2}=0.55$. Which explains more?\soln Model A --- it accounts for far more of the variation.` },
      { t: "Full interpretation (multi-part)", body: r`A model has $r=0.85$. Find \\ \textbf{(a)} $r^{2}$; \\ \textbf{(b)} the percent explained; \\ \textbf{(c)} whether a prediction far outside the data is wise.\soln (a) $0.7225$. (b) about $72\%$. (c) no --- that is extrapolation.` },
    ],
    questions: [
      { ask: r`If $r=0.6$, find $r^{2}$.` },
      { ask: r`If $r^{2}=0.81$, what percent of the variation is explained?` },
      { ask: r`A positive scatter has $r^{2}=0.64$. Find $r$.` },
      { ask: r`Predicting inside the data range is called what?` },
      { ask: r`Observed $y=30$, predicted $27$. Find the residual.` },
      { ask: r`Which model is better: $r^{2}=0.9$ or $r^{2}=0.5$?` },
      { ask: r`If $r=-0.7$, find $r^{2}$.` },
      { ask: r`Is a prediction far beyond the data reliable?` },
      { ask: r`If $r^{2}=0.36$, what percent is unexplained?` },
      { ask: r`What does $r^{2}=1$ indicate?` },
      { ask: r`What does a residual of $0$ mean?` },
      { ask: r`If $r=0.5$, what percent of the variation is explained?` },
      { ask: r`A model has $r=0.85$. Find \\ \textbf{(a)} $r^{2}$; \\ \textbf{(b)} the percent explained; \\ \textbf{(c)} the reliability of a prediction far outside the data.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$0.36$`, r`$81\%$`, r`$0.8$`, r`interpolation`, r`$+3$`, r`$r^{2}=0.9$`, r`$0.49$`, r`no --- it is extrapolation`, r`$64\%$`, r`a perfect linear fit`, r`the point lies exactly on the line`, r`$25\%$`, r`(a) $0.7225$; (b) $\approx72\%$; (c) unreliable (extrapolation)`],
  },
  {
    code: "6.4", unit: U, title: "Non-Linear Regression & Modelling",
    intro: r`When a scatter curves, a line is the wrong tool. Read the pattern: constant \emph{first differences} $\Rightarrow$ linear; constant \emph{second differences} $\Rightarrow$ quadratic; constant \emph{ratios} $\Rightarrow$ exponential. Compare candidate models by $r^{2}$.`,
    ideas: [r`Constant first differences $\Rightarrow$ linear; constant second differences $\Rightarrow$ quadratic.`, r`Constant ratios $\Rightarrow$ exponential.`, r`Pick the model from the scatter's shape; confirm with $r^{2}$ and a residual check.`],
    examples: [
      { t: "Constant differences", body: r`A table has first differences $3,3,3$. Which model?\soln Linear --- a constant rate of change.` },
      { t: "Constant ratios", body: r`Successive values have ratios $2,2,2$. Which model?\soln Exponential --- multiplied by a constant factor.` },
      { t: "Second differences", body: r`First differences change but second differences are constant. Which model?\soln Quadratic.` },
      { t: "Identify from a table", body: r`For $y=1,4,9,16$, which model?\soln Perfect squares --- quadratic ($y=x^{2}$).` },
      { t: "Exponential growth", body: r`A colony doubles each hour. Which model, and what is special about it?\soln Exponential; it has a constant ratio ($2$) rather than a constant difference.` },
      { t: "Shape to model", body: r`A projectile's height rises then falls in one arch. Which model?\soln Quadratic --- a single symmetric arch.` },
      { t: "Compare by r squared", body: r`Curved data: a line gives $r^{2}=0.7$, a quadratic gives $r^{2}=0.99$. Which model?\soln The quadratic --- it explains far more of the variation.` },
      { t: "Extrapolation caution", body: r`An exponential model of growth is extended 50 years out. What is the risk?\soln Unbounded growth is unrealistic long-term; extrapolation of an exponential is especially unreliable.` },
      { t: "Doubling data (multi-part)", body: r`For $y=3,6,12,24$ at $x=1,2,3,4$, find \\ \textbf{(a)} the model type; \\ \textbf{(b)} an equation; \\ \textbf{(c)} the value at $x=5$.\soln (a) exponential (ratio $2$). (b) $y=3\cdot2^{\,x-1}$. (c) $48$.` },
    ],
    questions: [
      { ask: r`First differences $3,3,3$. Which model?` },
      { ask: r`Ratios $2,2,2$. Which model?` },
      { ask: r`Second differences are constant. Which model?` },
      { ask: r`A single-arch scatter (rise then fall). Which model?` },
      { ask: r`A population that doubles each year. Which model?` },
      { ask: r`For $y=2,4,8,16$, what is the next value?` },
      { ask: r`For $y=1,4,9,16$, which model?` },
      { ask: r`Curved data: which fits better, $r^{2}=0.99$ (quadratic) or $0.7$ (linear)?` },
      { ask: r`Constant first differences of $5$. What is the slope of the linear model?` },
      { ask: r`For $y=5,10,15,20$, state the model and the next value.` },
      { ask: r`Bacteria triple every hour. Which model?` },
      { ask: r`Is fitting a line to clearly curved data a good idea?` },
      { ask: r`For $y=3,6,12,24$ at $x=1,2,3,4$, find \\ \textbf{(a)} the model; \\ \textbf{(b)} an equation; \\ \textbf{(c)} the value at $x=5$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`linear`, r`exponential`, r`quadratic`, r`quadratic`, r`exponential`, r`$32$`, r`quadratic ($y=x^{2}$)`, r`the quadratic`, r`$5$`, r`linear; next $=25$`, r`exponential`, r`no`, r`(a) exponential; (b) $y=3\cdot2^{\,x-1}$; (c) $48$`],
  },
  {
    code: "6.5", unit: U, title: "Correlation vs Causation",
    intro: r`A strong correlation never, by itself, proves cause and effect. A hidden \emph{confounding} (lurking) variable, reverse causation, or plain coincidence can all create correlation. Only a controlled experiment can establish causation.`,
    ideas: [r`Correlation $\ne$ causation.`, r`A confounding (lurking) variable can drive both quantities.`, r`Also possible: reverse causation, common cause, or coincidence.`],
    examples: [
      { t: "The classic confounder", body: r`Ice-cream sales and drownings rise together. Does ice cream cause drownings?\soln No --- hot weather (a confounder) drives both.` },
      { t: "Reverse causation", body: r`Sick people take more medicine, yet medicine is meant to help. What is happening?\soln The direction is reversed --- illness drives medicine use, not the other way.` },
      { t: "Coincidence", body: r`Two unrelated trends happen to move together for a few years. Explain.\soln A coincidental correlation --- no real link at all.` },
      { t: "Common cause", body: r`Larger vocabulary correlates with bigger shoe size in children. Why?\soln Both grow with \emph{age} --- a common cause.` },
      { t: "Why experiment", body: r`Why is a controlled experiment needed to prove causation?\soln It randomizes and controls other variables, isolating the effect of one factor.` },
      { t: "Spot the lurking variable", body: r`Towns with more churches have more bars. What is the lurking variable?\soln Population size --- bigger towns have more of both.` },
      { t: "Observational limits", body: r`An observational study finds a correlation. What can it conclude?\soln Correlation only --- not causation.` },
      { t: "Strength is not proof", body: r`Two variables have $r=0.99$. Does that prove one causes the other?\soln No --- even a near-perfect correlation can be confounded or coincidental.` },
      { t: "Full reasoning (multi-part)", body: r`Students with more books at home score higher. \\ \textbf{(a)} Does this prove books raise scores? \\ \textbf{(b)} Name a lurking variable. \\ \textbf{(c)} How could causation be tested?\soln (a) No. (b) family income/education. (c) a controlled study that varies book access while holding other factors fixed.` },
    ],
    questions: [
      { ask: r`Does a high correlation prove causation?` },
      { ask: r`Ice-cream sales and drownings both rise. Name the lurking variable.` },
      { ask: r`What kind of link is \emph{a rooster crows, then the sun rises}?` },
      { ask: r`What is required to establish causation?` },
      { ask: r`What is a confounding variable?` },
      { ask: r`Bigger shoe size correlates with better reading in children. Lurking variable?` },
      { ask: r`What can an observational study establish?` },
      { ask: r`Coffee drinkers live longer. Does coffee cause longevity?` },
      { ask: r`Two variables both driven by a third factor illustrate what?` },
      { ask: r`A randomized experiment controls for what?` },
      { ask: r`A correlation of $0.99$ between two variables --- does it prove cause?` },
      { ask: r`Name one alternative to causation that can explain a correlation.` },
      { ask: r`Cities with more police have more crime. \\ \textbf{(a)} Does policing cause crime? \\ \textbf{(b)} Name a lurking variable. \\ \textbf{(c)} How could you test the claim?`, challenge: true, ws: "3cm" },
    ],
    answers: [r`no`, r`hot weather`, r`coincidental (and reverse) --- not causal`, r`a controlled experiment`, r`one that affects both variables`, r`age`, r`correlation, not causation`, r`not necessarily --- it may be confounded`, r`a common cause`, r`confounding variables`, r`no`, r`confounding, reverse causation, or coincidence`, r`(a) no; (b) city/population size; (c) a controlled comparison`],
  },
];
