// MDM4U Unit 6 worksheets — Two-Variable Statistics.
// In MDM4U scope: r and the line of best fit come FROM TECHNOLOGY, then are
// interpreted/used (predict, interpolate/extrapolate, r^2 = % explained, residual
// = observed - predicted, correlation vs causation). NO by-hand least-squares
// derivation. Each example/question a distinct idea. No backtick quotes in r`...`.
const r = String.raw;
const U = "6: Two-Variable Statistics";

export default [
  {
    code: "6.1", unit: U, title: "Scatter Plots & Correlation",
    intro: r`A scatter plot of paired data shows \emph{direction} (positive/negative), \emph{form} (linear/non-linear), and \emph{strength}. The correlation coefficient $r$ measures \emph{linear} strength, from $-1$ to $1$.`,
    ideas: [r`Explanatory ($x$) vs. response ($y$) variable.`, r`Describe a scatter by direction, form, and strength.`, r`$r\in[-1,1]$: the sign gives direction, $|r|$ gives strength; $r$ only measures \emph{linear} association.`],
    examples: [
      { t: "Explanatory vs. response", body: r`In the pair hours studied vs. test score, which is which?\soln Hours studied is explanatory ($x$); test score is the response ($y$).` },
      { t: "Describe a scatter", body: r`Points climb steadily along a straight band. Describe the association.\soln Positive, linear, and strong.` },
      { t: "Estimate r by eye", body: r`A tight, upward-sloping band of points. Estimate $r$.\soln Close to $+1$ (say $r\approx0.9$).` },
      { t: "Negative correlation", body: r`As outdoor temperature rises, heating cost falls. Describe $r$.\soln Negative --- $r$ is between $-1$ and $0$.` },
      { t: "No correlation", body: r`Shoe size vs. test score shows a shapeless cloud. Estimate $r$.\soln About $0$ --- no linear association.` },
      { t: "Non-linear form", body: r`Points follow a clear U-shape. Is $r$ a good summary?\soln No --- $r$ only measures \emph{linear} strength and will understate a curved relationship.` },
      { t: "Interpret a value", body: r`Interpret $r=-0.85$.\soln A strong \emph{negative} linear relationship.` },
      { t: "Read a scatter", body: r`Describe the plotted data.\soln A strong positive linear trend.` + r`\scatter{0}{7}{0}{10}{\addplot[only marks,mark=*,exblue] coordinates {(1,2)(2,3)(3,5)(4,6)(5,8)(6,9)};}` },
      { t: "Compare r values (multi-part)", body: r`Given $r=-0.2,\ 0.95,\ -0.99,\ 0.5$, find \\ \textbf{(a)} the strongest; \\ \textbf{(b)} the weakest; \\ \textbf{(c)} the negative ones.\soln (a) $-0.99$ (largest $|r|$). (b) $-0.2$. (c) $-0.2$ and $-0.99$.` },
    ],
    questions: [
      { ask: r`Which is the explanatory variable: hours of sunlight vs. plant growth?` },
      { ask: r`Describe the association when $r=0.9$.` },
      { ask: r`Describe the association when $r=-0.4$.` },
      { ask: r`Which is stronger: $r=0.8$ or $r=-0.9$?` },
      { ask: r`What does $r=0$ indicate?` },
      { ask: r`A scatter curves sharply upward. Is $r$ a good summary? Why?` },
      { ask: r`Estimate $r$ for a tight, downward-sloping line of points.` },
      { ask: r`What is the likely sign of $r$ for ice-cream sales vs. temperature?` },
      { ask: r`Rank by strength: $r=0.3,\ -0.7,\ 0.95$.` },
      { ask: r`Which is explanatory: age vs. vocabulary size?` },
      { ask: r`Interpret $r=-0.99$.` },
      { ask: r`Two unrelated variables --- what value of $r$ do you expect?` },
      { ask: r`Given $r=0.1,\ -0.6,\ 0.99,\ -0.95$, find \\ \textbf{(a)} the strongest; \\ \textbf{(b)} the weakest; \\ \textbf{(c)} the negative ones.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`hours of sunlight`, r`strong positive linear`, r`weak-to-moderate negative`, r`$r=-0.9$`, r`no linear correlation`, r`no --- the relationship is non-linear`, r`near $-1$`, r`positive`, r`$0.95>0.7>0.3$`, r`age`, r`very strong negative linear`, r`$\approx0$`, r`(a) $0.99$; (b) $0.1$; (c) $-0.6,\ -0.95$`],
  },
  {
    code: "6.2", unit: U, title: "Correlation & Linear Regression",
    intro: r`Technology fits a \emph{line of best fit} $\hat y=ax+b$ to linear data. Its slope $a$ is the rate of change, its intercept $b$ the baseline; substitute an $x$ to \emph{predict} a $y$. The value $r$ reports how well the line fits.`,
    ideas: [r`Line of best fit $\hat y=ax+b$ (from technology).`, r`Slope $=$ rate of change; intercept $=$ value when $x=0$.`, r`Predict by substitution; $r$ measures the fit (not the steepness).`],
    examples: [
      { t: "Predict from a line", body: r`For $\hat y=2x+5$, predict $y$ at $x=10$.\soln $\hat y=2(10)+5=25$.` },
      { t: "Interpret slope and intercept", body: r`A cost model is $\hat y=0.5x+20$. Interpret its parts.\soln Each extra unit adds \$0.50 (slope); the fixed cost is \$20 (intercept).` },
      { t: "Interpolate", body: r`Data run over $x=1$ to $10$ with $\hat y=1.2x+3$. Predict at $x=6$.\soln $\hat y=1.2(6)+3=10.2$ --- an interpolation, so reliable.` },
      { t: "Read a technology result", body: r`Software reports $\hat y=1.2x+3$ with $r=0.95$. Interpret.\soln A strong positive linear fit; each unit of $x$ raises $\hat y$ by $1.2$.` },
      { t: "Predicted vs. actual (residual)", body: r`With $\hat y=2x+1$, the actual $y$ at $x=5$ is $13$. Find the residual.\soln Predicted $11$; residual $=13-11=+2$.` },
      { t: "r vs. slope", body: r`Two lines both have slope $2$, but $r=0.99$ and $r=0.6$. What differs?\soln The steepness is the same; $r$ shows the first data hug the line far more tightly.` },
      { t: "Sign agreement", body: r`If $r=-0.9$, what is the sign of the best-fit slope?\soln Negative --- $r$ and the slope always share a sign.` },
      { t: "Scatter with a fitted line", body: r`The line $\hat y=2x+1$ is fitted to the data. Predict at $x=4$.\soln $\hat y=9$.` + r`\scatter{0}{7}{0}{14}{\addplot[only marks,mark=*,exblue] coordinates {(1,3)(2,5)(3,6)(4,9)(5,11)}; \addplot[qorange,thick,domain=0:6]{2*x+1};}` },
      { t: "Full use (multi-part)", body: r`Sales follow $\hat y=3x+10$. Find \\ \textbf{(a)} the prediction at $x=8$; \\ \textbf{(b)} the meaning of the slope; \\ \textbf{(c)} the residual if the actual value at $x=8$ is $40$.\soln (a) $34$. (b) each unit of $x$ adds $3$ in sales. (c) $40-34=+6$.` },
    ],
    questions: [
      { ask: r`For $\hat y=2x+1$, predict $y$ at $x=6$.` },
      { ask: r`For $\hat y=-0.5x+20$, predict $y$ at $x=10$.` },
      { ask: r`Interpret the slope of the cost model $\hat y=4x+50$.` },
      { ask: r`Which line fits better: one with $r=0.98$ or one with $r=0.6$?` },
      { ask: r`Predicted $y=20$, actual $y=22$. Find the residual.` },
      { ask: r`For $\hat y=1.5x+2$, predict $y$ at $x=4$.` },
      { ask: r`Interpret the intercept of $\hat y=3x+12$.` },
      { ask: r`For $\hat y=0.1x+5$, predict at $x=100$. What caution applies?` },
      { ask: r`Which describes the strength of a linear relationship: $r$ or the slope?` },
      { ask: r`For $\hat y=-2x+30$, at what $x$ does $\hat y=10$?` },
      { ask: r`Predicted $y=18$, actual $y=15$. Find the residual.` },
      { ask: r`If $r=-0.9$, is the best-fit slope positive or negative?` },
      { ask: r`Sales follow $\hat y=3x+10$. Find \\ \textbf{(a)} the prediction at $x=8$; \\ \textbf{(b)} the slope's meaning; \\ \textbf{(c)} the residual if the actual is $40$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$13$`, r`$15$`, r`each unit adds $4$`, r`$r=0.98$`, r`$+2$`, r`$8$`, r`value when $x=0$ is $12$`, r`$15$ --- but this is extrapolation`, r`$r$`, r`$x=10$`, r`$-3$`, r`negative`, r`(a) $34$; (b) $+3$ per unit; (c) $+6$`],
  },
  {
    code: "6.3", unit: U, title: "The Coefficient of Determination & Prediction",
    intro: r`The coefficient of determination $r^{2}$ is the fraction of the variation in $y$ explained by the linear model. Trust \emph{interpolation} (inside the data) but be wary of \emph{extrapolation} (outside it). A residual is observed $-$ predicted.`,
    ideas: [r`$r^{2}$ $=$ proportion of variation in $y$ explained by the model.`, r`Interpolation (inside the range) is reliable; extrapolation (outside) is risky.`, r`Residual $=$ observed $-$ predicted; $0$ means the point is on the line.`],
    examples: [
      { t: "Compute r squared", body: r`If $r=0.8$, find $r^{2}$ and interpret it.\soln $r^{2}=0.64$: $64\%$ of the variation in $y$ is explained by the model.` },
      { t: "Interpret r squared", body: r`A model has $r^{2}=0.9$. What does that mean?\soln $90\%$ of the variation in $y$ is explained; $10\%$ is not.` },
      { t: "Recover r from r squared", body: r`A positive scatter has $r^{2}=0.49$. Find $r$.\soln $r=+\sqrt{0.49}=0.7$ (positive, matching the scatter).` },
      { t: "Interpolate vs. extrapolate", body: r`Data run over $x=0$ to $50$. Is a prediction at $x=20$ interpolation or extrapolation?\soln Interpolation --- $x=20$ is inside the range, so it is reliable.` },
      { t: "Find a residual", body: r`Observed $y=30$, predicted $\hat y=27$. Find the residual.\soln $30-27=+3$ --- the point sits above the line.` },
      { t: "Why extrapolation is risky", body: r`Why distrust a prediction far outside the data?\soln The pattern may not continue beyond the observed range; the model is unverified there.` },
      { t: "Weak model", body: r`A model has $r^{2}=0.25$. Comment.\soln Only $25\%$ of the variation is explained --- a weak fit; $75\%$ is unexplained.` },
      { t: "Compare two models", body: r`Model A: $r^{2}=0.92$; Model B: $r^{2}=0.55$. Which explains more?\soln Model A --- it accounts for far more of the variation.` },
      { t: "Full interpretation (multi-part)", body: r`A model has $r=0.85$. Find \\ \textbf{(a)} $r^{2}$; \\ \textbf{(b)} the percent explained; \\ \textbf{(c)} whether a prediction far outside the data is wise.\soln (a) $0.7225$. (b) about $72\%$. (c) no --- that is extrapolation.` },
    ],
    questions: [
      { ask: r`If $r=0.6$, find $r^{2}$.` },
      { ask: r`If $r^{2}=0.81$, what percent of the variation is explained?` },
      { ask: r`A positive scatter has $r^{2}=0.64$. Find $r$.` },
      { ask: r`Predicting inside the data range is called what?` },
      { ask: r`Observed $y=30$, predicted $27$. Find the residual.` },
      { ask: r`Which model is better: $r^{2}=0.9$ or $r^{2}=0.5$?` },
      { ask: r`If $r=-0.7$, find $r^{2}$.` },
      { ask: r`Is a prediction far beyond the data reliable?` },
      { ask: r`If $r^{2}=0.36$, what percent is unexplained?` },
      { ask: r`What does $r^{2}=1$ indicate?` },
      { ask: r`What does a residual of $0$ mean?` },
      { ask: r`If $r=0.5$, what percent of the variation is explained?` },
      { ask: r`A model has $r=0.85$. Find \\ \textbf{(a)} $r^{2}$; \\ \textbf{(b)} the percent explained; \\ \textbf{(c)} the reliability of a prediction far outside the data.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$0.36$`, r`$81\%$`, r`$0.8$`, r`interpolation`, r`$+3$`, r`$r^{2}=0.9$`, r`$0.49$`, r`no --- it is extrapolation`, r`$64\%$`, r`a perfect linear fit`, r`the point lies exactly on the line`, r`$25\%$`, r`(a) $0.7225$; (b) $\approx72\%$; (c) unreliable (extrapolation)`],
  },
  {
    code: "6.4", unit: U, title: "Non-Linear Regression & Modelling",
    intro: r`When a scatter curves, a line is the wrong tool. Read the pattern: constant \emph{first differences} $\Rightarrow$ linear; constant \emph{second differences} $\Rightarrow$ quadratic; constant \emph{ratios} $\Rightarrow$ exponential. Compare candidate models by $r^{2}$.`,
    ideas: [r`Constant first differences $\Rightarrow$ linear; constant second differences $\Rightarrow$ quadratic.`, r`Constant ratios $\Rightarrow$ exponential.`, r`Pick the model from the scatter's shape; confirm with $r^{2}$ and a residual check.`],
    examples: [
      { t: "Constant differences", body: r`A table has first differences $3,3,3$. Which model?\soln Linear --- a constant rate of change.` },
      { t: "Constant ratios", body: r`Successive values have ratios $2,2,2$. Which model?\soln Exponential --- multiplied by a constant factor.` },
      { t: "Second differences", body: r`First differences change but second differences are constant. Which model?\soln Quadratic.` },
      { t: "Identify from a table", body: r`For $y=1,4,9,16$, which model?\soln Perfect squares --- quadratic ($y=x^{2}$).` },
      { t: "Exponential growth", body: r`A colony doubles each hour. Which model, and what is special about it?\soln Exponential; it has a constant ratio ($2$) rather than a constant difference.` },
      { t: "Shape to model", body: r`A projectile's height rises then falls in one arch. Which model?\soln Quadratic --- a single symmetric arch.` },
      { t: "Compare by r squared", body: r`Curved data: a line gives $r^{2}=0.7$, a quadratic gives $r^{2}=0.99$. Which model?\soln The quadratic --- it explains far more of the variation.` },
      { t: "Extrapolation caution", body: r`An exponential model of growth is extended 50 years out. What is the risk?\soln Unbounded growth is unrealistic long-term; extrapolation of an exponential is especially unreliable.` },
      { t: "Doubling data (multi-part)", body: r`For $y=3,6,12,24$ at $x=1,2,3,4$, find \\ \textbf{(a)} the model type; \\ \textbf{(b)} an equation; \\ \textbf{(c)} the value at $x=5$.\soln (a) exponential (ratio $2$). (b) $y=3\cdot2^{\,x-1}$. (c) $48$.` },
    ],
    questions: [
      { ask: r`First differences $3,3,3$. Which model?` },
      { ask: r`Ratios $2,2,2$. Which model?` },
      { ask: r`Second differences are constant. Which model?` },
      { ask: r`A single-arch scatter (rise then fall). Which model?` },
      { ask: r`A population that doubles each year. Which model?` },
      { ask: r`For $y=2,4,8,16$, what is the next value?` },
      { ask: r`For $y=1,4,9,16$, which model?` },
      { ask: r`Curved data: which fits better, $r^{2}=0.99$ (quadratic) or $0.7$ (linear)?` },
      { ask: r`Constant first differences of $5$. What is the slope of the linear model?` },
      { ask: r`For $y=5,10,15,20$, state the model and the next value.` },
      { ask: r`Bacteria triple every hour. Which model?` },
      { ask: r`Is fitting a line to clearly curved data a good idea?` },
      { ask: r`For $y=3,6,12,24$ at $x=1,2,3,4$, find \\ \textbf{(a)} the model; \\ \textbf{(b)} an equation; \\ \textbf{(c)} the value at $x=5$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`linear`, r`exponential`, r`quadratic`, r`quadratic`, r`exponential`, r`$32$`, r`quadratic ($y=x^{2}$)`, r`the quadratic`, r`$5$`, r`linear; next $=25$`, r`exponential`, r`no`, r`(a) exponential; (b) $y=3\cdot2^{\,x-1}$; (c) $48$`],
  },
  {
    code: "6.5", unit: U, title: "Correlation vs Causation",
    intro: r`A strong correlation never, by itself, proves cause and effect. A hidden \emph{confounding} (lurking) variable, reverse causation, or plain coincidence can all create correlation. Only a controlled experiment can establish causation.`,
    ideas: [r`Correlation $\ne$ causation.`, r`A confounding (lurking) variable can drive both quantities.`, r`Also possible: reverse causation, common cause, or coincidence.`],
    examples: [
      { t: "The classic confounder", body: r`Ice-cream sales and drownings rise together. Does ice cream cause drownings?\soln No --- hot weather (a confounder) drives both.` },
      { t: "Reverse causation", body: r`Sick people take more medicine, yet medicine is meant to help. What is happening?\soln The direction is reversed --- illness drives medicine use, not the other way.` },
      { t: "Coincidence", body: r`Two unrelated trends happen to move together for a few years. Explain.\soln A coincidental correlation --- no real link at all.` },
      { t: "Common cause", body: r`Larger vocabulary correlates with bigger shoe size in children. Why?\soln Both grow with \emph{age} --- a common cause.` },
      { t: "Why experiment", body: r`Why is a controlled experiment needed to prove causation?\soln It randomizes and controls other variables, isolating the effect of one factor.` },
      { t: "Spot the lurking variable", body: r`Towns with more churches have more bars. What is the lurking variable?\soln Population size --- bigger towns have more of both.` },
      { t: "Observational limits", body: r`An observational study finds a correlation. What can it conclude?\soln Correlation only --- not causation.` },
      { t: "Strength is not proof", body: r`Two variables have $r=0.99$. Does that prove one causes the other?\soln No --- even a near-perfect correlation can be confounded or coincidental.` },
      { t: "Full reasoning (multi-part)", body: r`Students with more books at home score higher. \\ \textbf{(a)} Does this prove books raise scores? \\ \textbf{(b)} Name a lurking variable. \\ \textbf{(c)} How could causation be tested?\soln (a) No. (b) family income/education. (c) a controlled study that varies book access while holding other factors fixed.` },
    ],
    questions: [
      { ask: r`Does a high correlation prove causation?` },
      { ask: r`Ice-cream sales and drownings both rise. Name the lurking variable.` },
      { ask: r`What kind of link is \emph{a rooster crows, then the sun rises}?` },
      { ask: r`What is required to establish causation?` },
      { ask: r`What is a confounding variable?` },
      { ask: r`Bigger shoe size correlates with better reading in children. Lurking variable?` },
      { ask: r`What can an observational study establish?` },
      { ask: r`Coffee drinkers live longer. Does coffee cause longevity?` },
      { ask: r`Two variables both driven by a third factor illustrate what?` },
      { ask: r`A randomized experiment controls for what?` },
      { ask: r`A correlation of $0.99$ between two variables --- does it prove cause?` },
      { ask: r`Name one alternative to causation that can explain a correlation.` },
      { ask: r`Cities with more police have more crime. \\ \textbf{(a)} Does policing cause crime? \\ \textbf{(b)} Name a lurking variable. \\ \textbf{(c)} How could you test the claim?`, challenge: true, ws: "3cm" },
    ],
    answers: [r`no`, r`hot weather`, r`coincidental (and reverse) --- not causal`, r`a controlled experiment`, r`one that affects both variables`, r`age`, r`correlation, not causation`, r`not necessarily --- it may be confounded`, r`a common cause`, r`confounding variables`, r`no`, r`confounding, reverse causation, or coincidence`, r`(a) no; (b) city/population size; (c) a controlled comparison`],
  },
];
