// MDM4U Unit 7 worksheets — The Culminating Investigation.
// The methodology/project unit: designing a study, collecting & managing data,
// analysing (pulling together one- and two-variable tools), and communicating.
// Each example/question a distinct idea. No backtick quotes in r`...`.
const r = String.raw;
const U = "7: The Culminating Investigation";

export default [
  {
    code: "7.1", unit: U, title: "Designing the Study",
    intro: r`A good investigation turns curiosity into a \emph{researchable question} with clearly defined variables and a hypothesis, then chooses a design --- observational or experimental --- that can actually answer it.`,
    ideas: [r`A researchable question is focused, measurable, and answerable with data.`, r`Identify the explanatory and response variables and state a hypothesis.`, r`Observational study (measures as-is) vs. experiment (imposes a treatment); only an experiment can show causation.`],
    examples: [
      { t: "Refine a vague question", body: r`Turn the vague question \emph{Is exercise good?} into a researchable one.\soln E.g. \emph{Do students who exercise at least 3 hours a week have higher fitness scores?} --- specific, measurable variables.` },
      { t: "Identify the variables", body: r`In \emph{does study time affect test scores}, name the variables.\soln Explanatory: study time; response: test score.` },
      { t: "State a hypothesis", body: r`Write a hypothesis for a sleep-and-grades study.\soln \emph{More sleep is associated with higher grades} --- a testable prediction of the relationship.` },
      { t: "Observational vs. experimental", body: r`To test whether a fertilizer increases yield, which design proves cause?\soln An experiment: randomly assign plots to fertilizer or none and compare --- only this controls confounders.` },
      { t: "Population and frame", body: r`Distinguish the target population from the sampling frame.\soln The population is everyone of interest; the frame is the list you can actually sample from (they may differ, causing coverage bias).` },
      { t: "Control a confounder", body: r`A study links coffee to poor sleep, but coffee drinkers also work late. What must the design control?\soln The confounder --- work hours --- e.g. by matching or randomizing.` },
      { t: "One- vs. two-variable question", body: r`Classify: (a) \emph{what is the average commute time?}; (b) \emph{does commute time depend on distance?}\soln (a) one-variable (a single measured quantity); (b) two-variable (a relationship).` },
      { t: "Ethics in design", body: r`Name one ethical requirement when studying people.\soln Informed consent (also privacy/anonymity and the right to withdraw).` },
      { t: "Design a study (multi-part)", body: r`For \emph{does sleep affect grades}, state \\ \textbf{(a)} the variables; \\ \textbf{(b)} a hypothesis; \\ \textbf{(c)} observational or experimental?\soln (a) sleep (explanatory), grades (response). (b) more sleep $\to$ higher grades. (c) observational (you cannot ethically force sleep amounts).` },
    ],
    questions: [
      { ask: r`Rewrite the vague question \emph{are phones bad?} as a researchable one.` },
      { ask: r`Name the explanatory and response variables in \emph{does temperature affect ice-cream sales?}` },
      { ask: r`Write a testable hypothesis about practice time and free-throw success.` },
      { ask: r`Which design can establish causation: observational or experimental?` },
      { ask: r`Classify \emph{what is the median household income?} --- one- or two-variable?` },
      { ask: r`Classify \emph{is height related to shoe size?} --- one- or two-variable?` },
      { ask: r`A study links screen time to grades, but both relate to age. Name the confounder.` },
      { ask: r`State one ethical requirement when collecting data from people.` },
      { ask: r`What is the difference between a population and a sampling frame?` },
      { ask: r`To prove a drug works, why randomly assign patients to drug vs. placebo?` },
      { ask: r`Give the response variable in \emph{does fertilizer amount change plant height?}` },
      { ask: r`Is \emph{how many hours do teens sleep?} a one- or two-variable question?` },
      { ask: r`For \emph{does music while studying affect recall}, state \\ \textbf{(a)} the variables; \\ \textbf{(b)} a hypothesis; \\ \textbf{(c)} a design that could show causation.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`e.g. do teens using phones $>4$ h/day sleep fewer hours?`, r`explanatory: temperature; response: sales`, r`e.g. more practice raises free-throw percentage`, r`experimental`, r`one-variable`, r`two-variable`, r`age`, r`informed consent (or privacy/anonymity)`, r`population $=$ all of interest; frame $=$ the list you can sample`, r`to control confounders so the groups differ only by treatment`, r`plant height`, r`one-variable`, r`(a) music (expl.), recall (resp.); (b) music lowers recall; (c) a randomized experiment`],
  },
  {
    code: "7.2", unit: U, title: "Collecting & Managing Data",
    intro: r`Data may be \emph{primary} (you collect it) or \emph{secondary} (already published). Before analysis it must be cleaned --- fixing errors, outliers, and missing values --- and handled ethically, with sources cited.`,
    ideas: [r`Primary (first-hand) vs. secondary (existing) data.`, r`Data types: categorical vs. numerical; discrete vs. continuous.`, r`Clean errors/outliers/missing values; respect privacy and cite sources.`],
    examples: [
      { t: "Primary vs. secondary", body: r`You survey classmates about sleep. Primary or secondary?\soln Primary --- you collected it first-hand.` },
      { t: "Using published data", body: r`You download census tables. Primary or secondary?\soln Secondary --- it was collected by someone else.` },
      { t: "Spot a data error", body: r`A list of ages includes $200$. What should you do?\soln Flag it as a likely entry error and correct or remove it before analysis.` },
      { t: "Missing values", body: r`Some survey rows have blank income. Name two options.\soln Exclude those rows, or impute a reasonable value --- and report what you did.` },
      { t: "Classify data types", body: r`Classify: (a) eye colour; (b) number of siblings; (c) height.\soln (a) categorical; (b) numerical discrete; (c) numerical continuous.` },
      { t: "Ethics: privacy", body: r`Why anonymize survey responses?\soln To protect participants' privacy and encourage honest answers.` },
      { t: "Cite a source", body: r`Why must a secondary source be cited?\soln To give credit, allow verification, and let readers judge the data's reliability.` },
      { t: "Consistent units", body: r`Half the heights are in cm, half in inches. What is the risk?\soln Mixed units corrupt any calculation; convert everything to one unit first.` },
      { t: "Clean a dataset (multi-part)", body: r`A downloaded table lists a person's age as $200$. \\ \textbf{(a)} primary or secondary? \\ \textbf{(b)} what is the issue? \\ \textbf{(c)} how do you handle it?\soln (a) secondary. (b) an impossible outlier (error). (c) verify, then correct or remove it and note the change.` },
    ],
    questions: [
      { ask: r`You measure plant heights yourself. Primary or secondary data?` },
      { ask: r`You use Statistics Canada tables. Primary or secondary?` },
      { ask: r`Classify: favourite colour --- categorical or numerical?` },
      { ask: r`Classify: number of pets --- discrete or continuous?` },
      { ask: r`Classify: exact weight of a package --- discrete or continuous?` },
      { ask: r`A test score of $150$ appears on a $100$-point exam. What is it?` },
      { ask: r`Name one way to handle missing values in a dataset.` },
      { ask: r`Why should survey responses be anonymized?` },
      { ask: r`Why cite a secondary data source?` },
      { ask: r`Heights are recorded in both cm and inches. What must you do first?` },
      { ask: r`Classify: brand of phone owned --- categorical or numerical?` },
      { ask: r`Give one example of primary data collection.` },
      { ask: r`A table lists an age of $200$. \\ \textbf{(a)} primary or secondary? \\ \textbf{(b)} the issue? \\ \textbf{(c)} how to handle it?`, challenge: true, ws: "3cm" },
    ],
    answers: [r`primary`, r`secondary`, r`categorical`, r`discrete`, r`continuous`, r`an error/outlier (impossible value)`, r`exclude the rows, or impute and report it`, r`to protect privacy and encourage honesty`, r`credit, verification, and reliability`, r`convert all to a single unit`, r`categorical`, r`e.g. running your own survey/experiment`, r`(a) secondary; (b) impossible outlier; (c) verify then correct/remove`],
  },
  {
    code: "7.3", unit: U, title: "Analyzing the Data",
    intro: r`Analysis puts the whole course to work: choose the right one-variable summary (centre, spread, shape) and two-variable tool ($r$, regression), while staying alert to bias and variability.`,
    ideas: [r`Pick the centre/spread that suit the shape (median \& IQR for skewed data).`, r`Two-variable: use $r$ for strength and a regression line to predict.`, r`Interpret results with an eye on sampling bias and variability.`],
    examples: [
      { t: "Choose the centre", body: r`Incomes are strongly right-skewed. Which centre?\soln The median --- it resists the high outliers.` },
      { t: "Choose the spread", body: r`For skewed data with outliers, which spread?\soln The IQR --- it is resistant, unlike the range or $\sigma$.` },
      { t: "Summarize one variable", body: r`Find the median of $\{2,3,3,4,50\}$.\soln $3$ --- and note the $50$ is an outlier inflating the mean.` },
      { t: "Two-variable strength", body: r`Technology reports $r=0.9$ for study time vs. score. Interpret.\soln A strong positive linear relationship.` },
      { t: "Predict with regression", body: r`Using $\hat y=2x+5$, predict the score at $x=10$ hours.\soln $\hat y=25$.` },
      { t: "Compare two groups", body: r`How can you compare two classes' test results?\soln Compare centres and spreads --- e.g. side-by-side box plots or means with $\sigma$.` },
      { t: "Interpret r squared", body: r`A model has $r^{2}=0.81$. What does it say?\soln $81\%$ of the variation in the response is explained by the model.` },
      { t: "Bias check", body: r`Your data came from a volunteer web poll. How does that affect analysis?\soln Self-selection bias --- results may not generalize to the whole population.` },
      { t: "Full analysis (multi-part)", body: r`For $\{4,6,6,8,11\}$, find \\ \textbf{(a)} the mean; \\ \textbf{(b)} the median; \\ \textbf{(c)} which better describes the centre.\soln (a) $7$. (b) $6$. (c) both are close --- the mean is fine (little skew).` },
    ],
    questions: [
      { ask: r`For strongly skewed data, which centre is best?` },
      { ask: r`For data with outliers, which spread is most resistant?` },
      { ask: r`Find the median of $\{2,3,3,4,50\}$.` },
      { ask: r`Technology gives $r=-0.8$. Describe the relationship.` },
      { ask: r`Using $\hat y=3x+2$, predict $y$ at $x=5$.` },
      { ask: r`A model has $r^{2}=0.64$. What percent of variation is explained?` },
      { ask: r`Name a graph for comparing two groups' distributions.` },
      { ask: r`Data came from a volunteer online poll. Name the bias.` },
      { ask: r`Find the mean of $\{4,6,6,8,11\}$.` },
      { ask: r`Would a scatter plot or a histogram show a relationship between two variables?` },
      { ask: r`$r=0.2$: is the linear relationship strong or weak?` },
      { ask: r`For symmetric data with no outliers, which centre is fine to use?` },
      { ask: r`For $\{4,6,6,8,11\}$, find \\ \textbf{(a)} the mean; \\ \textbf{(b)} the median; \\ \textbf{(c)} which better describes the centre.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`the median`, r`the IQR`, r`$3$`, r`strong negative linear`, r`$17$`, r`$64\%$`, r`side-by-side box plots`, r`self-selection (voluntary-response) bias`, r`$\tfrac{35}{5}=7$`, r`a scatter plot`, r`weak`, r`the mean`, r`(a) $7$; (b) $6$; (c) either --- little skew`],
  },
  {
    code: "7.4", unit: U, title: "Communicating Conclusions",
    intro: r`A result is only as strong as its argument: interpret in real-world context, acknowledge the limitations and assumptions, and never claim more than the data support (correlation is not causation).`,
    ideas: [r`Interpret findings in context, with appropriate units and scale.`, r`State limitations: sample size, bias, variability, and the danger of extrapolation.`, r`Match the claim to the evidence --- an observational study shows correlation, not cause.`],
    examples: [
      { t: "Interpret in context", body: r`A model gives a slope of $2$ marks per study-hour. State it in plain language.\soln Each additional hour of study is associated with about $2$ more marks.` },
      { t: "Acknowledge a limitation", body: r`A survey of 15 friends finds a trend. What limitation must you state?\soln The tiny, non-random sample --- results may not generalize.` },
      { t: "Avoid a causation overclaim", body: r`Data show a correlation between two variables. What may you \emph{not} conclude?\soln That one causes the other --- correlation alone does not prove causation.` },
      { t: "Note extrapolation", body: r`Your data cover ages $10$--$18$. Why not predict for age $40$?\soln That is extrapolation far outside the data; the pattern may not hold.` },
      { t: "Choose the right graph", body: r`You want to show one variable's shape. Which display?\soln A histogram or box plot --- not a scatter plot (that is for relationships).` },
      { t: "Report uncertainty", body: r`Why report a margin of error with a poll result?\soln It conveys the sampling variability --- the true value likely lies within that range.` },
      { t: "Address bias in the conclusion", body: r`Your sample over-represented one group. How should the conclusion reflect this?\soln State that the bias may skew results and limit how far they generalize.` },
      { t: "Practical vs. statistical", body: r`A huge study finds a real but tiny effect. What should you note?\soln It may be statistically detectable yet too small to matter practically.` },
      { t: "Critique a conclusion (multi-part)", body: r`A survey concludes \emph{video games cause better reflexes}. \\ \textbf{(a)} what is wrong? \\ \textbf{(b)} a limitation? \\ \textbf{(c)} reword it responsibly.\soln (a) it claims causation from a survey (correlation only). (b) possible confounders/self-report. (c) \emph{gaming is associated with faster reflexes in this sample}.` },
    ],
    questions: [
      { ask: r`A regression slope is $5$ dollars per item. State its meaning in words.` },
      { ask: r`A study surveys only 12 people. What limitation must be reported?` },
      { ask: r`Two variables are correlated. What conclusion is NOT justified?` },
      { ask: r`Data span years $1$--$5$. Why distrust a prediction for year $20$?` },
      { ask: r`Which display shows a single variable's shape: histogram or scatter plot?` },
      { ask: r`Why report a margin of error with a poll?` },
      { ask: r`A sample over-represents one region. How should the conclusion note this?` },
      { ask: r`A large study finds a tiny effect. What distinction should you make?` },
      { ask: r`Rewrite the claim \emph{sunscreen causes more beach trips} to avoid a false causal statement.` },
      { ask: r`Name one assumption worth stating in a conclusion.` },
      { ask: r`Which is appropriate for an observational study: \emph{linked to} or \emph{causes}?` },
      { ask: r`Why include units when reporting a mean?` },
      { ask: r`A survey concludes \emph{phones cause lower grades}. \\ \textbf{(a)} what is wrong? \\ \textbf{(b)} a limitation? \\ \textbf{(c)} reword it responsibly.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`each extra item adds \$5 on average`, r`the small, likely non-random sample`, r`that one variable causes the other`, r`it is extrapolation far outside the data`, r`histogram`, r`it shows the sampling variability/uncertainty`, r`state that the bias limits how far it generalizes`, r`statistical vs. practical significance`, r`e.g. sunscreen use is associated with more beach trips`, r`e.g. the sample is representative, or units are consistent`, r`linked to`, r`to give the numbers meaning and scale`, r`(a) causation claimed from a survey; (b) confounders/self-report; (c) phone use is associated with lower grades here`],
  },
];
