// MCT4C Unit 1 worksheets — Exponential Functions & Logarithms.
// Full \soln solutions; 9 worked examples + 13 questions + answer key each.
const r = String.raw;
const U = "1: Exponential Functions";

export default [
  {
    code: "1.1", unit: U, title: "Exponent Laws",
    intro: r`Same base: multiply $\Rightarrow$ add exponents; divide $\Rightarrow$ subtract; power of a power $\Rightarrow$ multiply. A negative exponent is a reciprocal ($a^{-n}=\tfrac{1}{a^n}$); a rational exponent is a root ($a^{m/n}=\sqrt[n]{a^m}$).`,
    ideas: [r`Product/quotient/power laws (same base only).`, r`$a^{0}=1,\ a^{-n}=\dfrac{1}{a^n}$.`, r`$a^{m/n}=\left(\sqrt[n]{a}\right)^{m}$ — take the root first.`],
    examples: [
      { t: "Multi-variable simplification", body: r`Simplify $\dfrac{(3x^2y^3)^2(2xy^4)^3}{6x^3y^5}$.\soln Numerator $=9x^4y^6\cdot8x^3y^{12}=72x^7y^{18}$; divide: $12x^4y^{13}$.` },
      { t: "Negative exponents", body: r`Simplify $(2a^{-3}b^2)^{-2}\cdot a^5b^{-1}$ with positive exponents.\soln $\tfrac14a^6b^{-4}\cdot a^5b^{-1}=\tfrac14a^{11}b^{-5}=\dfrac{a^{11}}{4b^5}$.` },
      { t: "Rational powers by hand", body: r`Evaluate $27^{2/3}$, $16^{-3/4}$, $\left(\tfrac{8}{27}\right)^{-2/3}$.\soln $(\sqrt[3]{27})^2=9$; $\tfrac{1}{2^3}=\tfrac18$; $\left(\tfrac{27}{8}\right)^{2/3}=\left(\tfrac32\right)^2=\tfrac94$.` },
      { t: "Rational exponents, variables", body: r`Simplify $\dfrac{(x^{1/2}y^{-2})^4}{x^3y^{-5}}$.\soln $\dfrac{x^2y^{-8}}{x^3y^{-5}}=x^{-1}y^{-3}=\dfrac{1}{xy^3}$.` },
      { t: "Quotient raised to a power", body: r`Simplify $\left(\dfrac{a^{2/3}b^{-1/2}}{a^{-1/3}b^{1/2}}\right)^{6}$.\soln Inside: $a^{1}b^{-1}$; to the 6th: $a^6b^{-6}=\dfrac{a^6}{b^6}$.` },
      { t: "Mixed evaluation", body: r`Evaluate $8^{2/3}\cdot 9^{-1/2}\cdot 5^{0}$.\soln $4\cdot\tfrac13\cdot1=\tfrac43$.` },
      { t: "Reciprocal of a product", body: r`Simplify $(4x^{-2}y^5)^{-1}$ with positive exponents.\soln $4^{-1}x^2y^{-5}=\dfrac{x^2}{4y^5}$.` },
      { t: "Power then product", body: r`Simplify $(2x^3)^4\cdot x^{-5}$.\soln $16x^{12}\cdot x^{-5}=16x^7$.` },
      { t: "Combine like bases", body: r`Simplify $\dfrac{a^5b^2\cdot a^2b^4}{a^3b}$.\soln $\dfrac{a^7b^6}{a^3b}=a^4b^5$.` },
    ],
    questions: [
      { ask: r`Simplify $(3x^4)^2$.` },
      { ask: r`Evaluate $25^{3/2}$.` },
      { ask: r`Simplify $\dfrac{x^7}{x^3}$.` },
      { ask: r`Simplify $(2a^2b)^3$.` },
      { ask: r`Evaluate $16^{-1/2}$.` },
      { ask: r`Simplify $(a^{-2})^{-3}$.` },
      { ask: r`Evaluate $\left(\tfrac18\right)^{-2/3}$.` },
      { ask: r`Simplify $\dfrac{6x^5y^2}{2x^2y^5}$.` },
      { ask: r`Evaluate $81^{3/4}$.` },
      { ask: r`Simplify $(x^{1/3})^6$.` },
      { ask: r`Simplify $(3x^2y)^2(2xy^3)$.` },
      { ask: r`Evaluate $32^{-2/5}$.` },
      { ask: r`Simplify $\dfrac{(2a^{1/2}b^{-1})^4}{a^{-1}b^{2}}$ with positive exponents.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$9x^8$`, r`$125$`, r`$x^4$`, r`$8a^6b^3$`, r`$\tfrac14$`, r`$a^6$`, r`$4$`, r`$\dfrac{3x^3}{y^3}$`, r`$27$`, r`$x^2$`, r`$18x^5y^5$`, r`$\tfrac14$`, r`$\dfrac{16a^3}{b^6}$`],
  },
  {
    code: "1.2", unit: U, title: "Exponential Functions & Their Graphs",
    intro: r`An exponential function $y=a\,b^{x}$ multiplies by $b$ each unit step. It has $y$-intercept $(0,a)$, horizontal asymptote $y=0$, and grows if $b>1$ or decays if $0<b<1$.`,
    ideas: [r`Form $y=a\,b^{x}$; $y$-intercept $(0,a)$.`, r`Horizontal asymptote $y=0$; range $y>0$ (for $a>0$).`, r`Base $b>1$ grows; $0<b<1$ decays.`],
    examples: [
      { t: "Read the features", body: r`For $y=3\cdot2^{x}$, give the $y$-intercept, asymptote, and behaviour.\soln $(0,3)$; asymptote $y=0$; growth.` },
      { t: "Growth vs. decay", body: r`Compare $y=2^{x}$ and $y=\left(\tfrac12\right)^{x}$.\soln Both pass $(0,1)$ with asymptote $y=0$; the second decays (mirror of the first).` },
      { t: "Table and trend", body: r`Tabulate $y=4\left(\tfrac12\right)^{x}$ at $x=0,1,2,3$.\soln $4,2,1,\tfrac12$ — halving; $y$-intercept $(0,4)$, decay.` },
      { t: "Find the equation", body: r`$y=a\,b^{x}$ has $y$-intercept $5$ and passes $(2,45)$. Find it.\soln $a=5$; $45=5b^2\Rightarrow b=3$; $y=5\cdot3^{x}$.` },
      { t: "Domain and range", body: r`State the domain, range, asymptote of $y=5\cdot3^{x}$ and find $y(-1)$.\soln Domain $\mathbb{R}$; range $y>0$; asymptote $y=0$; $y(-1)=\tfrac53$.` },
      { t: "Two points", body: r`A function passes $(1,12)$ and $(3,48)$. Find $y=a\,b^{x}$.\soln $\tfrac{48}{12}=b^2=4\Rightarrow b=2$; $12=2a\Rightarrow a=6$; $y=6\cdot2^{x}$.` },
      { t: "Evaluate", body: r`Evaluate $y=2\cdot5^{x}$ at $x=2$ and $x=-1$.\soln $50$ and $\tfrac25$.` },
      { t: "Decay factor", body: r`A quantity halves each step from $80$. Write the model and give the value after 3 steps.\soln $y=80\left(\tfrac12\right)^{x}$; at $x=3$: $10$.` },
      { t: "Compare bases", body: r`Which grows faster: $y=2^{x}$ or $y=3^{x}$? Compare at $x=3$.\soln $2^3=8$ vs. $3^3=27$; $3^x$ grows faster.` },
    ],
    questions: [
      { ask: r`State the $y$-intercept and asymptote of $y=2\cdot5^{x}$.` },
      { ask: r`Does $y=6\left(\tfrac34\right)^{x}$ grow or decay?` },
      { ask: r`Evaluate $y=4\cdot3^{x}$ at $x=2$.` },
      { ask: r`An exponential passes $(0,7)$ and $(1,21)$. Find it.` },
      { ask: r`State the range of $y=2\cdot3^{x}$.` },
      { ask: r`Evaluate $y=5\cdot2^{x}$ at $x=-2$.` },
      { ask: r`A function passes $(2,20)$ and $(4,80)$. Find $b$.` },
      { ask: r`Is $y=\left(\tfrac25\right)^{x}$ growth or decay?` },
      { ask: r`Give the asymptote of $y=7\cdot4^{x}$.` },
      { ask: r`Tabulate $y=3\cdot2^{x}$ at $x=0,1,2$.` },
      { ask: r`A quantity triples from $2$ each step. Write the model.` },
      { ask: r`Evaluate $y=6\left(\tfrac12\right)^{x}$ at $x=3$.` },
      { ask: r`A function passes $(1,6)$ and $(3,54)$. Find $y=a\,b^{x}$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$(0,2)$, $y=0$`, r`decay`, r`$36$`, r`$y=7\cdot3^{x}$`, r`$y>0$`, r`$\tfrac54$`, r`$b=2$`, r`decay`, r`$y=0$`, r`$3,6,12$`, r`$y=2\cdot3^{x}$`, r`$\tfrac34$`, r`$b^2=9\Rightarrow b=3$, $a=2$: $y=2\cdot3^{x}$`],
  },
  {
    code: "1.3", unit: U, title: "Transformations of Exponential Functions",
    intro: r`In $y=a\,b^{\,k(x-d)}+c$: $a$ stretches/reflects, $k$ stretches horizontally, $d$ shifts right, and $c$ shifts up — moving the asymptote to $y=c$.`,
    ideas: [r`$a$: vertical stretch ($a<0$ reflects).`, r`$d$: right shift; $c$: up shift (asymptote $y=c$).`, r`$y$-intercept: substitute $x=0$.`],
    examples: [
      { t: "Describe the shifts", body: r`Describe $y=2^{\,x-3}+1$.\soln Right $3$, up $1$; asymptote $y=1$.` },
      { t: "Reflection + shift", body: r`Find the $y$-intercept and asymptote of $y=-3\cdot2^{x}+4$.\soln $y(0)=-3+4=1$, so $(0,1)$; asymptote $y=4$.` },
      { t: "Graph features", body: r`For $y=2^{\,x+1}-3$, give the asymptote and $y$-intercept.\soln Asymptote $y=-3$; $y(0)=2^1-3=-1$.` },
      { t: "Write the equation", body: r`$y=3^{x}$ is stretched by $2$, reflected in the $x$-axis, shifted up $5$. Write it.\soln $y=-2\cdot3^{x}+5$; asymptote $y=5$.` },
      { t: "Range", body: r`State the range of $y=-4\cdot2^{x}+10$.\soln Asymptote $y=10$, $a<0$: $y<10$.` },
      { t: "Left shift", body: r`Describe $y=5^{\,x+2}$.\soln Left $2$; asymptote $y=0$.` },
      { t: "Down shift range", body: r`Range of $y=3\cdot2^{\,x-1}-6$.\soln Asymptote $y=-6$, $a>0$: $y>-6$.` },
      { t: "Intercept after shift", body: r`Find the $y$-intercept of $y=-2\cdot4^{x}+9$.\soln $-2+9=7$, so $(0,7)$.` },
      { t: "Combine", body: r`Describe $y=2\cdot3^{\,x-1}+4$ fully.\soln Stretch $2$, right $1$, up $4$; asymptote $y=4$.` },
    ],
    questions: [
      { ask: r`Describe the transformations in $y=2^{\,x-4}$.` },
      { ask: r`Asymptote of $y=5\cdot3^{x}-2$?` },
      { ask: r`$y$-intercept of $y=-2\cdot4^{x}+9$?` },
      { ask: r`Write $y=2^{x}$ shifted left $3$ and down $1$.` },
      { ask: r`Range of $y=3\cdot2^{\,x-1}-6$?` },
      { ask: r`Asymptote of $y=-4\cdot2^{x}+7$?` },
      { ask: r`$y$-intercept of $y=3\cdot2^{x}-1$?` },
      { ask: r`Describe $y=4^{\,x+2}+3$.` },
      { ask: r`Range of $y=-5\cdot3^{x}+2$?` },
      { ask: r`Write $y=3^{x}$ reflected in the $x$-axis and up $6$.` },
      { ask: r`Asymptote of $y=2^{\,x-5}+8$?` },
      { ask: r`$y$-intercept of $y=6\cdot2^{x}-4$?` },
      { ask: r`State the range of $y=-2\cdot5^{\,x+1}+12$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`right $4$`, r`$y=-2$`, r`$(0,7)$`, r`$y=2^{\,x+3}-1$`, r`$y>-6$`, r`$y=7$`, r`$(0,2)$`, r`left $2$, up $3$; asymptote $y=3$`, r`$y<2$`, r`$y=-3^{x}+6$`, r`$y=8$`, r`$(0,2)$`, r`$y<12$`],
  },
  {
    code: "1.4", unit: U, title: "Solving Exponential Equations by Common Bases",
    intro: r`If both sides can be written as powers of the same base, set the exponents equal. Watch for hidden powers: $4=2^2,\ 8=2^3,\ 27=3^3,\ \tfrac14=2^{-2}$.`,
    ideas: [r`Rewrite each side with a common base.`, r`Equate exponents and solve.`, r`Distribute powers over exponent expressions.`],
    examples: [
      { t: "Same base", body: r`Solve $2^{x}=32$.\soln $2^x=2^5\Rightarrow x=5$.` },
      { t: "Rewrite one side", body: r`Solve $9^{x}=27$.\soln $3^{2x}=3^3\Rightarrow x=\tfrac32$.` },
      { t: "Exponent expression", body: r`Solve $8^{\,x-1}=16$.\soln $2^{3(x-1)}=2^4\Rightarrow 3x-3=4\Rightarrow x=\tfrac73$.` },
      { t: "Fractional base", body: r`Solve $\left(\tfrac14\right)^{x}=8$.\soln $2^{-2x}=2^3\Rightarrow x=-\tfrac32$.` },
      { t: "Variable both sides", body: r`Solve $4^{\,x+1}=8^{\,x-1}$.\soln $2^{2x+2}=2^{3x-3}\Rightarrow 2x+2=3x-3\Rightarrow x=5$.` },
      { t: "Base 5", body: r`Solve $25^{x}=125$.\soln $5^{2x}=5^3\Rightarrow x=\tfrac32$.` },
      { t: "Negative solution", body: r`Solve $\left(\tfrac19\right)^{x}=27$.\soln $3^{-2x}=3^3\Rightarrow x=-\tfrac32$.` },
      { t: "Coefficient in exponent", body: r`Solve $2^{\,3x}=32$.\soln $2^{3x}=2^5\Rightarrow x=\tfrac53$.` },
      { t: "Both sides powers", body: r`Solve $27^{\,x-1}=9^{\,2x+1}$.\soln $3^{3(x-1)}=3^{2(2x+1)}\Rightarrow 3x-3=4x+2\Rightarrow x=-5$.` },
    ],
    questions: [
      { ask: r`Solve $3^{x}=81$.` },
      { ask: r`Solve $2^{x}=64$.` },
      { ask: r`Solve $9^{x}=27$.` },
      { ask: r`Solve $\left(\tfrac12\right)^{x}=16$.` },
      { ask: r`Solve $4^{\,x-1}=64$.` },
      { ask: r`Solve $25^{x}=5$.` },
      { ask: r`Solve $8^{x}=32$.` },
      { ask: r`Solve $\left(\tfrac13\right)^{x}=81$.` },
      { ask: r`Solve $2^{\,2x}=128$.` },
      { ask: r`Solve $16^{x}=8$.` },
      { ask: r`Solve $4^{\,x+1}=16^{\,x}$.` },
      { ask: r`Solve $27^{x}=9$.` },
      { ask: r`Solve $8^{\,x+1}=4^{\,2x-1}$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$x=4$`, r`$x=6$`, r`$x=\tfrac32$`, r`$x=-4$`, r`$x=4$`, r`$x=\tfrac12$`, r`$x=\tfrac53$`, r`$x=-4$`, r`$x=\tfrac72$`, r`$x=\tfrac34$`, r`$2x+2=4x\Rightarrow x=1$`, r`$x=\tfrac23$`, r`$3x+3=4x-2\Rightarrow x=5$`],
  },
  {
    code: "1.5", unit: U, title: "Introduction to Logarithms",
    intro: r`A logarithm is an exponent: $\log_b x=y$ means $b^{y}=x$ (with $b>0,b\ne1,x>0$). $\log x$ is base $10$; $\ln x$ is base $e$.`,
    ideas: [r`$\log_b x=y\iff b^{y}=x$.`, r`$\log_b 1=0$, $\log_b b=1$.`, r`Evaluate by asking "what exponent?".`],
    examples: [
      { t: "Switch forms", body: r`Rewrite $2^5=32$ in log form; $\log_3 81=4$ in exponential form.\soln $\log_2 32=5$; $3^4=81$.` },
      { t: "Evaluate several", body: r`Evaluate $\log_2 16,\ \log_5\tfrac1{25},\ \log 1000,\ \log_9 3$.\soln $4,\ -2,\ 3,\ \tfrac12$.` },
      { t: "Solve for argument", body: r`Solve $\log_2 x=5$.\soln $x=2^5=32$.` },
      { t: "Solve for base", body: r`Solve $\log_x 64=3$.\soln $x^3=64\Rightarrow x=4$.` },
      { t: "Fractional value", body: r`Evaluate $\log_4 8$.\soln $2^{2y}=2^3\Rightarrow y=\tfrac32$.` },
      { t: "Base 10", body: r`Evaluate $\log 100000$.\soln $10^5\Rightarrow 5$.` },
      { t: "Negative log", body: r`Evaluate $\log_3\tfrac{1}{27}$.\soln $3^{-3}\Rightarrow -3$.` },
      { t: "Solve for base again", body: r`Solve $\log_x 81=4$.\soln $x^4=81\Rightarrow x=3$.` },
      { t: "Root value", body: r`Evaluate $\log_8 32$.\soln $2^{3y}=2^5\Rightarrow y=\tfrac53$.` },
    ],
    questions: [
      { ask: r`Rewrite $10^4=10000$ in log form.` },
      { ask: r`Evaluate $\log_3 27$.` },
      { ask: r`Evaluate $\log_2\tfrac18$.` },
      { ask: r`Solve $\log_x 81=4$.` },
      { ask: r`Evaluate $\log_5 125$.` },
      { ask: r`Solve $\log_2 x=6$.` },
      { ask: r`Evaluate $\log 1$.` },
      { ask: r`Evaluate $\log_4 2$.` },
      { ask: r`Solve $\log_x 1000=3$.` },
      { ask: r`Evaluate $\log_2 1$.` },
      { ask: r`Evaluate $\log_6 36$.` },
      { ask: r`Evaluate $\log_{16} 4$.` },
      { ask: r`Evaluate $\log_9 27$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\log 10000=4$`, r`$3$`, r`$-3$`, r`$x=3$`, r`$3$`, r`$x=64$`, r`$0$`, r`$\tfrac12$`, r`$x=10$`, r`$0$`, r`$2$`, r`$\tfrac12$`, r`$3^{2y}=3^3\Rightarrow y=\tfrac32$`],
  },
  {
    code: "1.6", unit: U, title: "Laws of Logarithms",
    intro: r`Products become sums, quotients become differences, powers become multipliers: $\log_b(MN)=\log_b M+\log_b N$, $\log_b\tfrac{M}{N}=\log_b M-\log_b N$, $\log_b M^p=p\log_b M$. Change base with $\log_b x=\tfrac{\log x}{\log b}$.`,
    ideas: [r`Product/quotient/power laws.`, r`Expand or condense expressions.`, r`Change of base for any calculator.`],
    examples: [
      { t: "Expand", body: r`Expand $\log\!\left(\dfrac{x^2y}{z}\right)$.\soln $2\log x+\log y-\log z$.` },
      { t: "Condense", body: r`Write $2\log a+\log b-3\log c$ as one log.\soln $\log\!\left(\dfrac{a^2b}{c^3}\right)$.` },
      { t: "Evaluate a sum", body: r`Evaluate $\log_6 9+\log_6 4$.\soln $\log_6 36=2$.` },
      { t: "Power law", body: r`Evaluate $\log_2 8^4$.\soln $4\log_2 8=4\cdot3=12$.` },
      { t: "Change of base", body: r`Evaluate $\log_2 10$ to 3 decimals.\soln $\dfrac{\log 10}{\log 2}\approx3.322$.` },
      { t: "Evaluate a difference", body: r`Evaluate $\log_5 100-\log_5 4$.\soln $\log_5 25=2$.` },
      { t: "Expand a root", body: r`Expand $\log\sqrt{x}$.\soln $\tfrac12\log x$.` },
      { t: "Condense with coefficient", body: r`Write $3\log x-\log y$ as one log.\soln $\log\!\left(\dfrac{x^3}{y}\right)$.` },
      { t: "Change of base 2", body: r`Evaluate $\log_3 20$ to 3 decimals.\soln $\dfrac{\log 20}{\log 3}\approx2.727$.` },
    ],
    questions: [
      { ask: r`Expand $\log(ab^3)$.` },
      { ask: r`Condense $\log x+\log y-\log z$.` },
      { ask: r`Evaluate $\log_3 6+\log_3 \tfrac32$.` },
      { ask: r`Evaluate $\log_5 100-\log_5 4$.` },
      { ask: r`Expand $\log\!\left(\tfrac{x^3}{y^2}\right)$.` },
      { ask: r`Condense $4\log a+2\log b$.` },
      { ask: r`Evaluate $\log_2 40-\log_2 5$.` },
      { ask: r`Expand $\log(x^2\sqrt{y})$.` },
      { ask: r`Evaluate $\log_4 8+\log_4 2$.` },
      { ask: r`Condense $\tfrac12\log x+\log y$.` },
      { ask: r`Evaluate $\log_2 3+\log_2 \tfrac{16}{3}$.` },
      { ask: r`Evaluate $\log_5 100$ to 3 decimals.` },
      { ask: r`Evaluate $\log_3 50$ to 3 decimals.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\log a+3\log b$`, r`$\log\!\left(\tfrac{xy}{z}\right)$`, r`$\log_3 9=2$`, r`$\log_5 25=2$`, r`$3\log x-2\log y$`, r`$\log(a^4b^2)$`, r`$\log_2 8=3$`, r`$2\log x+\tfrac12\log y$`, r`$\log_4 16=2$`, r`$\log(y\sqrt{x})$`, r`$\log_2 16=4$`, r`$\dfrac{\log 100}{\log 5}\approx2.861$`, r`$\dfrac{\log 50}{\log 3}\approx3.561$`],
  },
  {
    code: "1.7", unit: U, title: "Solving Exponential Equations Using Logarithms",
    intro: r`When no common base works, take $\log$ of both sides and use $\log b^{x}=x\log b$: so $x=\dfrac{\log k}{\log b}$. Isolate the power first.`,
    ideas: [r`Take $\log$ (or $\ln$) of both sides.`, r`Bring the exponent down with the power law.`, r`Isolate coefficients before taking logs.`],
    examples: [
      { t: "Basic solve", body: r`Solve $3^{x}=20$ (3 decimals).\soln $x=\dfrac{\log 20}{\log 3}\approx2.727$.` },
      { t: "Shifted exponent", body: r`Solve $2^{\,x+1}=7$.\soln $x+1=\dfrac{\log 7}{\log 2}\approx2.807\Rightarrow x\approx1.807$.` },
      { t: "Isolate first", body: r`Solve $4\cdot3^{x}=100$.\soln $3^x=25$; $x=\dfrac{\log 25}{\log 3}\approx2.930$.` },
      { t: "Base $e$", body: r`Solve $e^{\,2x}=15$.\soln $2x=\ln 15\approx2.708\Rightarrow x\approx1.354$.` },
      { t: "Applied", body: r`When does $1000(1.05)^{t}=2000$?\soln $1.05^t=2$; $t=\dfrac{\log 2}{\log 1.05}\approx14.2$.` },
      { t: "Base 5", body: r`Solve $5^{x}=200$.\soln $x=\dfrac{\log 200}{\log 5}\approx3.292$.` },
      { t: "Shift both sides", body: r`Solve $3^{\,x-2}=50$.\soln $x-2=\dfrac{\log 50}{\log 3}\approx3.561\Rightarrow x\approx5.561$.` },
      { t: "Natural log", body: r`Solve $e^{x}=8$.\soln $x=\ln 8\approx2.079$.` },
      { t: "Growth to target", body: r`When does $200(1.08)^{t}=1000$?\soln $1.08^t=5$; $t=\dfrac{\log 5}{\log 1.08}\approx20.9$.` },
    ],
    questions: [
      { ask: r`Solve $2^{x}=13$ (3 decimals).` },
      { ask: r`Solve $5^{x}=100$.` },
      { ask: r`Solve $3^{x}=45$.` },
      { ask: r`Solve $e^{x}=20$.` },
      { ask: r`Solve $2\cdot3^{x}=54$.` },
      { ask: r`Solve $4^{x}=30$.` },
      { ask: r`Solve $2^{\,x-1}=15$.` },
      { ask: r`Solve $e^{\,3x}=10$.` },
      { ask: r`When does $500(1.04)^{t}=800$?` },
      { ask: r`Solve $10^{x}=250$.` },
      { ask: r`Solve $6^{x}=1000$.` },
      { ask: r`Solve $3\cdot2^{x}=96$.` },
      { ask: r`When does $2000(1.06)^{t}=5000$?`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\tfrac{\log 13}{\log 2}\approx3.700$`, r`$\tfrac{\log 100}{\log 5}\approx2.861$`, r`$\tfrac{\log 45}{\log 3}\approx3.465$`, r`$\ln 20\approx2.996$`, r`$3^x=27\Rightarrow x=3$`, r`$\tfrac{\log 30}{\log 4}\approx2.453$`, r`$x-1=\tfrac{\log 15}{\log 2}\Rightarrow x\approx4.907$`, r`$3x=\ln 10\Rightarrow x\approx0.768$`, r`$\tfrac{\log 1.6}{\log 1.04}\approx11.98$`, r`$\log 250\approx2.398$`, r`$\tfrac{\log 1000}{\log 6}\approx3.856$`, r`$2^x=32\Rightarrow x=5$`, r`$\tfrac{\log 2.5}{\log 1.06}\approx15.73$`],
  },
  {
    code: "1.8", unit: U, title: "Growth, Decay & Compound Interest",
    intro: r`Model constant-percentage change with $A=A_0\,b^{t}$: growth $b=1+r$, decay $b=1-r$. Half-life uses $\left(\tfrac12\right)^{t/h}$; compound interest is $A=P(1+i)^{n}$.`,
    ideas: [r`Growth/decay factor $b=1\pm r$.`, r`Half-life / doubling models.`, r`Compound interest $A=P(1+i)^{n}$.`],
    examples: [
      { t: "Population growth", body: r`$P=500(1.03)^{t}$; find $P$ after 10 years.\soln $500(1.03)^{10}\approx672$.` },
      { t: "Half-life", body: r`$80$ mg, half-life $6$ h. Model it; find the amount after $18$ h.\soln $A=80\left(\tfrac12\right)^{t/6}$; at $18$: $80\cdot\tfrac18=10$ mg.` },
      { t: "Compound interest", body: r`\$2000 at $4\%$/yr, compounded annually, $5$ years.\soln $2000(1.04)^{5}\approx\$2433.31$.` },
      { t: "Doubling time", body: r`At $6\%$/yr, how long to double?\soln $1.06^t=2\Rightarrow t=\dfrac{\log 2}{\log 1.06}\approx11.9$ yr.` },
      { t: "Decay to half", body: r`$A=A_0(0.95)^{t}$; when is $50\%$ left?\soln $0.95^t=0.5\Rightarrow t\approx13.5$ yr.` },
      { t: "Growth value", body: r`$800(1.02)^{t}$; find after $15$ years.\soln $\approx1077$.` },
      { t: "Half-life count", body: r`$60$ mg, half-life $4$ h; amount after $12$ h.\soln $60\left(\tfrac12\right)^{3}=7.5$ mg.` },
      { t: "Depreciation", body: r`A \$30\,000 car depreciates $12\%$/yr. When worth \$15\,000?\soln $(0.88)^t=0.5\Rightarrow t\approx5.4$ yr.` },
      { t: "Interest amount", body: r`\$1500 at $5\%$/yr, $4$ years.\soln $1500(1.05)^{4}\approx\$1823.26$.` },
    ],
    questions: [
      { ask: r`\$1000 at $5\%$/yr compounded annually for $3$ years — find the amount.` },
      { ask: r`A $40$ mg sample, half-life $5$ h — amount after $15$ h?` },
      { ask: r`A population $600(1.03)^{t}$ — find it after $10$ years.` },
      { ask: r`Money at $8\%$/yr — how long to double?` },
      { ask: r`$A=A_0(0.9)^{t}$ — when is $50\%$ left?` },
      { ask: r`\$5000 at $6\%$/yr for $2$ years — amount?` },
      { ask: r`A $100$ mg sample, half-life $3$ h — amount after $9$ h?` },
      { ask: r`A \$20\,000 car depreciates $10\%$/yr — value after $3$ years?` },
      { ask: r`A colony $50(1.1)^{t}$ — reaches what after $5$ h?` },
      { ask: r`Money at $4\%$/yr — how long to reach $1.5\times$?` },
      { ask: r`A $200$ mg dose, half-life $8$ h — amount after $24$ h?` },
      { ask: r`\$3000 at $7\%$/yr for $5$ years — amount?` },
      { ask: r`A substance decays $15\%$/yr. When is $25\%$ left?`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`$1000(1.05)^3\approx\$1157.63$`, r`$40\left(\tfrac12\right)^3=5$ mg`, r`$600(1.03)^{10}\approx807$`, r`$\tfrac{\log 2}{\log 1.08}\approx9.0$ yr`, r`$\tfrac{\log 0.5}{\log 0.9}\approx6.6$ yr`, r`$5000(1.06)^2\approx\$5618$`, r`$100\left(\tfrac12\right)^3=12.5$ mg`, r`$20000(0.9)^3\approx\$14\,580$`, r`$50(1.1)^5\approx80.5$`, r`$\tfrac{\log 1.5}{\log 1.04}\approx10.3$ yr`, r`$200\left(\tfrac12\right)^3=25$ mg`, r`$3000(1.07)^5\approx\$4207.66$`, r`$(0.85)^t=0.25\Rightarrow t=\tfrac{\log 0.25}{\log 0.85}\approx8.5$ yr`],
  },
];
