// MCT4C Unit 2 worksheets — Polynomial Functions.
// Full \soln solutions; 9 worked examples + 13 questions + answer key each.
const r = String.raw;
const U = "2: Polynomial Functions";

export default [
  {
    code: "2.1", unit: U, title: "Polynomial Expressions & Functions",
    intro: r`A polynomial has real coefficients and whole-number exponents. The \emph{degree} is the highest exponent, the \emph{leading coefficient} multiplies it, and \emph{standard form} lists terms from highest to lowest degree.`,
    ideas: [r`Whole-number exponents only (no $\sqrt{x}$, no $\tfrac1x$).`, r`Degree $=$ highest exponent; leading coefficient multiplies it.`, r`Evaluate with function notation $P(a)$.`],
    examples: [
      { t: "Identify polynomials", body: r`Which are polynomials: $x^3-5x^2+1$, $2^{x}$, $\sqrt{x}+3$, $4x^{-2}$?\soln Only $x^3-5x^2+1$ (the others have a variable, fractional, or negative exponent).` },
      { t: "Degree and leading coefficient", body: r`State the degree and leading coefficient of $-4x^5+2x^3-7$.\soln Degree $5$, leading coefficient $-4$.` },
      { t: "Evaluate", body: r`For $P(x)=2x^3-x+5$, find $P(2)$ and $P(-1)$.\soln $16-2+5=19$; $-2+1+5=4$.` },
      { t: "Standard form", body: r`Write $3x-5x^4+2-x^2$ in standard form.\soln $-5x^4-x^2+3x+2$.` },
      { t: "Classify", body: r`Classify $4x^3-2x+7$.\soln Cubic (degree 3) trinomial (3 terms).` },
      { t: "Evaluate a quartic", body: r`For $P(x)=x^4-3x^2+2x$, find $P(-2)$.\soln $16-12-4=0$.` },
      { t: "Not a polynomial", body: r`Is $3x^2-\tfrac1x$ a polynomial? Why?\soln No — $\tfrac1x=x^{-1}$ has a negative exponent.` },
      { t: "Degree of a product", body: r`What is the degree of $(x^2+1)(x^3-x)$?\soln $2+3=5$.` },
      { t: "Constant and coefficient", body: r`For $P(x)=6-2x^3+x^7$, give the degree, leading coefficient, and constant term.\soln Degree $7$, leading coefficient $1$, constant $6$.` },
    ],
    questions: [
      { ask: r`Is $3x^2-\tfrac{1}{x}$ a polynomial?` },
      { ask: r`Degree and leading coefficient of $6-2x^3+x^7$?` },
      { ask: r`For $P(x)=x^3-2x^2+4$, find $P(3)$.` },
      { ask: r`Write $2x-x^3+5$ in standard form.` },
      { ask: r`For $P(x)=x^4-3x^2+2x$, find $P(-2)$.` },
      { ask: r`Classify $5x^2-1$.` },
      { ask: r`Is $\sqrt{x}+2$ a polynomial?` },
      { ask: r`Degree of $(x^3+2)(x^2-1)$?` },
      { ask: r`For $P(x)=2x^3+x-4$, find $P(0)$.` },
      { ask: r`Leading coefficient of $7-3x^4+x$?` },
      { ask: r`For $P(x)=x^3-x$, find $P(2)$.` },
      { ask: r`Classify $x^4-2x^3+x-1$.` },
      { ask: r`For $P(x)=x^3-4x^2+x+6$, find $P(3)$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`no ($x^{-1}$)`, r`degree $7$, LC $1$`, r`$27-18+4=13$`, r`$-x^3+2x+5$`, r`$0$`, r`quadratic binomial`, r`no`, r`$5$`, r`$-4$`, r`$-3$`, r`$6$`, r`quartic (4 terms)`, r`$27-36+3+6=0$`],
  },
  {
    code: "2.2", unit: U, title: "Graphs of Polynomial Functions",
    intro: r`Degree parity and the leading coefficient's sign set the \emph{end behaviour}; a degree-$n$ polynomial has at most $n$ $x$-intercepts and $n-1$ turning points.`,
    ideas: [r`Even degree: ends match; odd degree: ends oppose.`, r`$+$ leading rises right; $-$ leading falls right.`, r`At most $n$ intercepts, $n-1$ turns.`],
    examples: [
      { t: "Odd, positive", body: r`End behaviour of $y=2x^3-5x+1$?\soln Down-left, up-right.` },
      { t: "Even, negative", body: r`End behaviour of $y=-x^4+3x^2$?\soln Down on both ends.` },
      { t: "Count features", body: r`Max $x$-intercepts and turning points of a quartic?\soln $4$ and $3$.` },
      { t: "Reason from graph", body: r`A graph rises on both ends. Degree and leading sign?\soln Even degree, positive leading coefficient.` },
      { t: "Odd, negative", body: r`End behaviour of $y=-x^5+2x^2$?\soln Up-left, down-right.` },
      { t: "Cubic ends", body: r`End behaviour of $y=x^3$?\soln Down-left, up-right.` },
      { t: "Quartic ends", body: r`End behaviour of $y=x^4$?\soln Up on both ends.` },
      { t: "Turning points", body: r`Max turning points of a degree-6 polynomial?\soln $5$.` },
      { t: "Falls both ends", body: r`A graph falls on both ends. Degree and sign?\soln Even degree, negative leading coefficient.` },
    ],
    questions: [
      { ask: r`End behaviour of $y=x^4-2x^2$?` },
      { ask: r`End behaviour of $y=-2x^3+x$?` },
      { ask: r`Max $x$-intercepts of a cubic?` },
      { ask: r`A graph falls both ends — degree and leading sign?` },
      { ask: r`Max turning points of a degree-6 polynomial?` },
      { ask: r`End behaviour of $y=3x^5$?` },
      { ask: r`End behaviour of $y=-x^6$?` },
      { ask: r`Max $x$-intercepts of a quartic?` },
      { ask: r`A graph rises both ends — degree parity?` },
      { ask: r`End behaviour of $y=-5x^3+2x^2-1$?` },
      { ask: r`Max turning points of a cubic?` },
      { ask: r`End behaviour of $y=2x^4-x$?` },
      { ask: r`A degree-5 graph with negative leading coefficient — describe its ends.`, challenge: true, ws: "2.6cm" },
    ],
    answers: [r`up both ends`, r`up-left, down-right`, r`$3$`, r`even degree, negative LC`, r`$5$`, r`down-left, up-right`, r`down both ends`, r`$4$`, r`even`, r`up-left, down-right`, r`$2$`, r`up both ends`, r`up-left, down-right`],
  },
  {
    code: "2.3", unit: U, title: "Factored Form & Zeros",
    intro: r`Each factor $(x-r)$ names a zero at $x=r$. Odd multiplicity crosses the axis; even multiplicity touches. Build an equation with one factor per zero and a leading coefficient $a$.`,
    ideas: [r`$(x-r)$ $\Rightarrow$ zero at $x=r$.`, r`Odd multiplicity crosses; even touches.`, r`Find $a$ by substituting a known point.`],
    examples: [
      { t: "Read the zeros", body: r`Zeros of $y=(x-2)(x+3)(x-1)$?\soln $x=2,-3,1$.` },
      { t: "Multiplicity", body: r`Behaviour of $y=(x-1)^2(x+2)$ at each zero.\soln $x=1$ (even): touches; $x=-2$ (odd): crosses.` },
      { t: "Build from zeros", body: r`Write a cubic with zeros $-1,2,3$.\soln $y=a(x+1)(x-2)(x-3)$.` },
      { t: "Find $a$", body: r`The cubic above passes $(0,12)$. Find $a$.\soln $12=a(1)(-2)(-3)=6a\Rightarrow a=2$.` },
      { t: "Triple root", body: r`Behaviour of $y=x(x-2)^3$ at $x=2$.\soln Multiplicity 3 (odd): crosses but flattens.` },
      { t: "Zeros with a quadratic factor", body: r`Zeros of $y=(x-4)(x+1)^2$?\soln $x=4$ and $x=-1$ (double).` },
      { t: "Quartic zeros", body: r`Zeros of $y=x^2(x-3)(x+2)$?\soln $x=0$ (double), $3,-2$.` },
      { t: "Write with a double", body: r`Write a cubic with a double zero at $2$ and a zero at $-1$.\soln $y=a(x-2)^2(x+1)$.` },
      { t: "Find $a$ from a point", body: r`A cubic with zeros $0,1,-2$ passes $(2,8)$. Find $a$.\soln $8=a(2)(1)(4)=8a\Rightarrow a=1$.` },
    ],
    questions: [
      { ask: r`Zeros of $y=(x+4)(x-5)$?` },
      { ask: r`At $x=3$, does $y=(x-3)^2(x+1)$ cross or touch?` },
      { ask: r`Write a quadratic with zeros $2$ and $-5$.` },
      { ask: r`A cubic with zeros $0,1,-2$ passes $(2,8)$. Find $a$.` },
      { ask: r`Behaviour of $y=(x+1)^4$ at $x=-1$?` },
      { ask: r`Zeros of $y=x(x-4)(x+3)$?` },
      { ask: r`At $x=-2$, does $y=(x-1)(x+2)^3$ cross or touch?` },
      { ask: r`Write a cubic with zeros $-3,0,3$.` },
      { ask: r`Zeros of $y=(x-2)^2(x+5)$?` },
      { ask: r`A quadratic with zeros $\pm4$ passes $(0,-16)$. Find $a$.` },
      { ask: r`Behaviour of $y=(x-2)^5$ at $x=2$?` },
      { ask: r`Write a cubic with a double zero at $-1$ and a zero at $4$.` },
      { ask: r`A cubic with zeros $1,-1,2$ passes $(0,4)$. Find $a$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$-4,5$`, r`touches`, r`$y=a(x-2)(x+5)$`, r`$a=1$`, r`touches (flattens)`, r`$0,4,-3$`, r`crosses (flattens)`, r`$y=a(x+3)x(x-3)$`, r`$2$ (double), $-5$`, r`$-16=a(-4)(4)=-16a\Rightarrow a=1$`, r`crosses (flattens)`, r`$y=a(x+1)^2(x-4)$`, r`$4=a(-1)(1)(-2)=2a\Rightarrow a=2$`],
  },
  {
    code: "2.4", unit: U, title: "Dividing Polynomials",
    intro: r`Division gives $P(x)=D(x)Q(x)+R$. Synthetic division (for divisor $x-a$): write coefficients (zeros for missing terms), bring down, then multiply-by-$a$ and add.`,
    ideas: [r`$P(x)=D(x)Q(x)+R$.`, r`Synthetic division for $x-a$.`, r`Insert $0$ for missing terms.`],
    examples: [
      { t: "Divide out a factor", body: r`Divide $(x^3-2x^2-5x+6)\div(x-1)$.\soln Synthetic ($a=1$): quotient $x^2-x-6$, remainder $0$.` },
      { t: "Non-zero remainder", body: r`Divide $(2x^3+3x^2-1)\div(x+2)$.\soln $a=-2$: quotient $2x^2-x+2$, remainder $-5$.` },
      { t: "Find a factor", body: r`Divide $(x^3-7x-6)\div(x+1)$.\soln $a=-1$: quotient $x^2-x-6$, remainder $0$.` },
      { t: "Difference of cubes", body: r`Divide $(x^3-1)\div(x-1)$.\soln $x^2+x+1$, remainder $0$.` },
      { t: "Higher degree", body: r`Divide $(x^4-16)\div(x-2)$.\soln $x^3+2x^2+4x+8$, remainder $0$.` },
      { t: "Quadratic dividend", body: r`Divide $(2x^2-3x+1)\div(x-2)$.\soln $2x+1$, remainder $3$.` },
      { t: "Missing term", body: r`Divide $(x^3+2x^2-3)\div(x-1)$.\soln $x^2+3x+3$, remainder $0$.` },
      { t: "Write the identity", body: r`Write $2x^3+3x^2-1$ using its division by $x+2$.\soln $(x+2)(2x^2-x+2)-5$.` },
      { t: "Simple factor", body: r`Divide $(x^2+5x+6)\div(x+2)$.\soln $x+3$, remainder $0$.` },
    ],
    questions: [
      { ask: r`Divide $(x^2+5x+6)\div(x+2)$.` },
      { ask: r`Divide $(x^3-1)\div(x-1)$.` },
      { ask: r`Divide $(x^3+2x^2-3)\div(x-1)$.` },
      { ask: r`Divide $(2x^2-3x+1)\div(x-2)$.` },
      { ask: r`Divide $(x^4-16)\div(x-2)$.` },
      { ask: r`Divide $(x^3-2x^2-5x+6)\div(x-1)$.` },
      { ask: r`Divide $(x^3-7x-6)\div(x+1)$.` },
      { ask: r`Divide $(x^2-9)\div(x-3)$.` },
      { ask: r`Divide $(x^3+8)\div(x+2)$.` },
      { ask: r`Divide $(2x^3+3x^2-1)\div(x+2)$.` },
      { ask: r`Divide $(x^3-6x^2+11x-6)\div(x-1)$.` },
      { ask: r`Divide $(x^3+x)\div(x)$.` },
      { ask: r`Divide $(x^4-3x^2+2)\div(x-1)$.`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`$x+3$, R $0$`, r`$x^2+x+1$, R $0$`, r`$x^2+3x+3$, R $0$`, r`$2x+1$, R $3$`, r`$x^3+2x^2+4x+8$, R $0$`, r`$x^2-x-6$, R $0$`, r`$x^2-x-6$, R $0$`, r`$x+3$, R $0$`, r`$x^2-2x+4$, R $0$`, r`$2x^2-x+2$, R $-5$`, r`$x^2-5x+6$, R $0$`, r`$x^2+1$, R $0$`, r`$x^3+x^2-2x-2$, R $0$`],
  },
  {
    code: "2.5", unit: U, title: "The Remainder Theorem",
    intro: r`The remainder of $P(x)\div(x-a)$ is $P(a)$ — one substitution instead of a full division. For a divisor $bx-a$, evaluate at $x=\tfrac{a}{b}$.`,
    ideas: [r`Remainder $=P(a)$.`, r`Set $P(a)$ equal to a given remainder to find an unknown.`, r`For $bx-a$, use $x=\tfrac{a}{b}$.`],
    examples: [
      { t: "By substitution", body: r`Remainder of $(x^3-4x+1)\div(x-2)$.\soln $P(2)=8-8+1=1$.` },
      { t: "Negative value", body: r`Remainder of $(x^3-4x+1)\div(x+3)$.\soln $P(-3)=-27+12+1=-14$.` },
      { t: "Find a coefficient", body: r`$P(x)=x^3+kx-6$ has remainder $4$ on $\div(x-2)$. Find $k$.\soln $8+2k-6=4\Rightarrow k=1$.` },
      { t: "Divisor $2x-1$", body: r`Remainder of $(2x^3-3x^2+1)\div(2x-1)$.\soln $P(\tfrac12)=\tfrac14-\tfrac34+1=\tfrac12$.` },
      { t: "Fast evaluation", body: r`Evaluate $P(-1)$ for $P(x)=x^3+2x^2-x+5$.\soln $-1+2+1+5=7$.` },
      { t: "Zero remainder", body: r`Remainder of $(x^3-2x+4)\div(x+2)$.\soln $P(-2)=-8+4+4=0$.` },
      { t: "Small case", body: r`Remainder of $(x^2+3x-2)\div(x-1)$.\soln $P(1)=2$.` },
      { t: "Another coefficient", body: r`$P(x)=x^3+ax+2$ has remainder $8$ on $\div(x-1)$. Find $a$.\soln $1+a+2=8\Rightarrow a=5$.` },
      { t: "Quartic remainder", body: r`Remainder of $(x^4-1)\div(x-1)$.\soln $P(1)=0$.` },
    ],
    questions: [
      { ask: r`Remainder of $(x^2+3x-2)\div(x-1)$?` },
      { ask: r`Remainder of $(x^3-2x+4)\div(x+2)$?` },
      { ask: r`$P(x)=x^3+ax+2$ leaves remainder $8$ on $\div(x-1)$. Find $a$.` },
      { ask: r`Remainder of $(x^4-1)\div(x-1)$?` },
      { ask: r`Remainder of $(x^3-4x+1)\div(x-2)$?` },
      { ask: r`Remainder of $(2x^3+x-5)\div(x-1)$?` },
      { ask: r`$P(x)=x^3+kx^2-4$ leaves remainder $0$ on $\div(x-2)$. Find $k$.` },
      { ask: r`Remainder of $(x^3-8)\div(x-2)$?` },
      { ask: r`Remainder of $(x^3+2x^2-x+5)\div(x+1)$?` },
      { ask: r`Remainder of $(x^4-3x^2+1)\div(x-1)$?` },
      { ask: r`Remainder of $(3x^2-2x+7)\div(x+2)$?` },
      { ask: r`$P(x)=2x^3-x+c$ leaves remainder $5$ on $\div(x-1)$. Find $c$.` },
      { ask: r`Remainder of $(3x^3-x+2)\div(3x-1)$?`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$2$`, r`$0$`, r`$a=5$`, r`$0$`, r`$1$`, r`$-2$`, r`$8+4k-4=0\Rightarrow k=-1$`, r`$0$`, r`$-1+2+1+5=7$`, r`$1-3+1=-1$`, r`$12+4+7=23$`, r`$2-1+c=5\Rightarrow c=4$`, r`$P(\tfrac13)=\tfrac19-\tfrac13+2=\tfrac{16}{9}$`],
  },
  {
    code: "2.6", unit: U, title: "The Factor Theorem",
    intro: r`$x-a$ is a factor of $P(x)$ exactly when $P(a)=0$. Test the factors of the constant term to find a first zero, divide it out, then factor the leftover quadratic.`,
    ideas: [r`$x-a$ a factor $\Leftrightarrow P(a)=0$.`, r`Candidate zeros are factors of the constant term.`, r`Divide, then factor completely.`],
    examples: [
      { t: "Test a factor", body: r`Is $x-2$ a factor of $x^3-3x^2+4$?\soln $P(2)=8-12+4=0$: yes.` },
      { t: "Factor completely", body: r`Factor $x^3-3x^2+4$.\soln Divide by $x-2$: $x^2-x-2=(x-2)(x+1)$; so $(x-2)^2(x+1)$.` },
      { t: "Find a zero, factor", body: r`Factor $x^3+2x^2-5x-6$.\soln $P(-1)=0$; $(x+1)(x^2+x-6)=(x+1)(x+3)(x-2)$.` },
      { t: "Candidates", body: r`Factor $x^3-4x^2+x+6$.\soln $P(-1)=0$; $(x+1)(x^2-5x+6)=(x+1)(x-2)(x-3)$.` },
      { t: "Quartic", body: r`Factor $x^4-1$.\soln $(x^2-1)(x^2+1)=(x-1)(x+1)(x^2+1)$.` },
      { t: "Common factor first", body: r`Factor $x^3-x$.\soln $x(x-1)(x+1)$.` },
      { t: "Another cubic", body: r`Factor $x^3-2x^2-x+2$.\soln $P(1)=0$; $(x-1)(x^2-x-2)=(x-1)(x-2)(x+1)$.` },
      { t: "Repeated factor", body: r`Factor $x^3+3x^2-4$.\soln $P(1)=0$; $(x-1)(x^2+4x+4)=(x-1)(x+2)^2$.` },
      { t: "Non-monic", body: r`Factor $2x^3-3x^2-11x+6$ given $x=3$ is a zero.\soln $(x-3)(2x^2+3x-2)=(x-3)(2x-1)(x+2)$.` },
    ],
    questions: [
      { ask: r`Is $x-1$ a factor of $x^3-1$?` },
      { ask: r`Factor $x^3-x$.` },
      { ask: r`Factor $x^3-2x^2-x+2$.` },
      { ask: r`Factor $x^3+3x^2-4$.` },
      { ask: r`Factor $2x^3-3x^2-11x+6$ (given $x=3$ is a zero).` },
      { ask: r`Is $x+2$ a factor of $x^3+8$?` },
      { ask: r`Factor $x^3-7x+6$.` },
      { ask: r`Factor $x^3+2x^2-5x-6$.` },
      { ask: r`Factor $x^4-16$.` },
      { ask: r`Is $x-3$ a factor of $x^3-4x^2+x+6$?` },
      { ask: r`Factor $x^3-6x^2+11x-6$.` },
      { ask: r`Factor $x^3+x^2-4x-4$.` },
      { ask: r`Factor $x^4-5x^2+4$.`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`yes`, r`$x(x-1)(x+1)$`, r`$(x-1)(x-2)(x+1)$`, r`$(x-1)(x+2)^2$`, r`$(x-3)(2x-1)(x+2)$`, r`yes`, r`$(x-1)(x-2)(x+3)$`, r`$(x+1)(x+3)(x-2)$`, r`$(x-2)(x+2)(x^2+4)$`, r`yes`, r`$(x-1)(x-2)(x-3)$`, r`$(x+1)(x-2)(x+2)$`, r`$(x-1)(x+1)(x-2)(x+2)$`],
  },
  {
    code: "2.7", unit: U, title: "Solving Polynomial Equations",
    intro: r`Set the equation to zero, factor completely, and use the zero-product property: a product is zero only when a factor is. Repeated factors give repeated roots; watch for a quadratic in $x^2$.`,
    ideas: [r`Move to one side, then factor.`, r`Zero-product property gives the roots.`, r`Quadratic-in-$x^2$ and grouping tricks.`],
    examples: [
      { t: "Repeated root", body: r`Solve $x^3-3x^2+4=0$.\soln $(x-2)^2(x+1)=0\Rightarrow x=2\ (\text{double}),\,-1$.` },
      { t: "Three roots", body: r`Solve $x^3+2x^2-5x-6=0$.\soln $(x+1)(x+3)(x-2)=0\Rightarrow x=-1,-3,2$.` },
      { t: "Quadratic in $x^2$", body: r`Solve $x^4-5x^2+4=0$.\soln $(x^2-1)(x^2-4)=0\Rightarrow x=\pm1,\pm2$.` },
      { t: "Grouping", body: r`Solve $2x^3-x^2-8x+4=0$.\soln $(2x-1)(x-2)(x+2)=0\Rightarrow x=\tfrac12,2,-2$.` },
      { t: "Common factor", body: r`Solve $x^3-4x=0$.\soln $x(x-2)(x+2)=0\Rightarrow x=0,\pm2$.` },
      { t: "Simple product", body: r`Solve $(x-3)(x+4)=0$.\soln $x=3,-4$.` },
      { t: "Cube factor", body: r`Solve $x^3-9x=0$.\soln $x(x-3)(x+3)=0\Rightarrow x=0,\pm3$.` },
      { t: "Biquadratic", body: r`Solve $x^4-13x^2+36=0$.\soln $(x^2-4)(x^2-9)=0\Rightarrow x=\pm2,\pm3$.` },
      { t: "Group and factor", body: r`Solve $x^3-x^2-4x+4=0$.\soln $(x-1)(x-2)(x+2)=0\Rightarrow x=1,2,-2$.` },
    ],
    questions: [
      { ask: r`Solve $(x-3)(x+4)=0$.` },
      { ask: r`Solve $x^3-9x=0$.` },
      { ask: r`Solve $x^3-2x^2-x+2=0$.` },
      { ask: r`Solve $x^4-13x^2+36=0$.` },
      { ask: r`Solve $x^3-x^2-4x+4=0$.` },
      { ask: r`Solve $x^3-3x^2+4=0$.` },
      { ask: r`Solve $x^4-5x^2+4=0$.` },
      { ask: r`Solve $x^3-4x=0$.` },
      { ask: r`Solve $x^3+2x^2-5x-6=0$.` },
      { ask: r`Solve $x^2(x-3)=0$.` },
      { ask: r`Solve $2x^3-x^2-8x+4=0$.` },
      { ask: r`Solve $x^3-16x=0$.` },
      { ask: r`Solve $x^4-10x^2+9=0$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$x=3,-4$`, r`$x=0,\pm3$`, r`$x=1,2,-1$`, r`$x=\pm2,\pm3$`, r`$x=1,2,-2$`, r`$x=2\,(\text{double}),-1$`, r`$x=\pm1,\pm2$`, r`$x=0,\pm2$`, r`$x=-1,-3,2$`, r`$x=0\,(\text{double}),3$`, r`$x=\tfrac12,\pm2$`, r`$x=0,\pm4$`, r`$x=\pm1,\pm3$`],
  },
  {
    code: "2.8", unit: U, title: "Applications of Polynomial Functions",
    intro: r`Model a situation with a polynomial (usually a volume or height), set the equation, solve by factoring, and keep only physically sensible roots (positive lengths).`,
    ideas: [r`Translate the context into a polynomial.`, r`Solve by factoring.`, r`Discard out-of-range roots.`],
    examples: [
      { t: "Open box", body: r`Squares of side $x$ are cut from a $12\times12$ sheet. For what $x$ is the volume $128$?\soln $V=x(12-2x)^2$; $x=2$ gives $2(8)^2=128$ ($0<x<6$).` },
      { t: "Projectile", body: r`$h(t)=-5t^2+30t$. When does it land?\soln $t(-5t+30)=0\Rightarrow t=6$ s.` },
      { t: "Volume from factors", body: r`$V=x^3+4x^2+3x$; factor and find $V$ at $x=2$.\soln $x(x+1)(x+3)$; at $2$: $2\cdot3\cdot5=30$.` },
      { t: "Break-even", body: r`Solve $x^3-7x-6=0$ for the positive root.\soln $(x-3)(x+1)(x+2)=0\Rightarrow x=3$.` },
      { t: "Beam deflection", body: r`$d(x)=x^3-12x$. Where is $d=0$?\soln $x(x^2-12)=0\Rightarrow x=0,\ 2\sqrt3$.` },
      { t: "Landing time", body: r`$h(t)=-5t^2+20t$. When does it land?\soln $t(-5t+20)=0\Rightarrow t=4$ s.` },
      { t: "Box dimensions", body: r`A box has volume $x(x-1)(x+2)$; find $V$ at $x=3$.\soln $3\cdot2\cdot5=30$.` },
      { t: "Design equation", body: r`Solve $x^3-9x=0$ for the positive length.\soln $x=3$.` },
      { t: "Profit roots", body: r`Solve $x^3-x^2-4x+4=0$; give the positive roots.\soln $x=1,2$.` },
    ],
    questions: [
      { ask: r`$h(t)=-5t^2+20t$. When does it land?` },
      { ask: r`A box $x(x-1)(x+2)$; find $V$ at $x=3$.` },
      { ask: r`Solve $x^3-9x=0$ (positive length).` },
      { ask: r`$V=x(10-2x)^2$; is $V=72$ at $x=1$?` },
      { ask: r`Solve $x^3-2x^2-5x+6=0$; positive roots?` },
      { ask: r`$h(t)=-5t^2+40t$. When does it land?` },
      { ask: r`$V=x^3+5x^2+6x$; find $V$ at $x=1$.` },
      { ask: r`Solve $x^3-16x=0$ (positive length).` },
      { ask: r`A box $x(8-2x)^2=72$; check $x=1$.` },
      { ask: r`Solve $x^3-4x=0$ (positive length).` },
      { ask: r`$d(x)=x^3-9x$; where is $d=0$ (positive)?` },
      { ask: r`$V=x(x+2)(x+4)$; find $V$ at $x=2$.` },
      { ask: r`A $16\times16$ sheet, cut $x$: is $V=x(16-2x)^2=768$ at $x=2$?`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`$t=4$ s`, r`$30$`, r`$x=3$`, r`$1(8)^2=64\ne72$: no`, r`$x=1,3$`, r`$t=8$ s`, r`$1\cdot3\cdot4=12$`, r`$x=4$`, r`$1(6)^2=36\ne72$: no`, r`$x=2$`, r`$x=3$`, r`$2\cdot4\cdot6=48$`, r`$2(12)^2=288\ne768$: no`],
  },
];
