// MCT4C Unit 3 worksheets — Trigonometric Functions (degrees throughout).
// Full \soln solutions; 9 worked examples + 13 questions + answer key each.
const r = String.raw;
const U = "3: Trigonometric Functions";

export default [
  {
    code: "3.1", unit: U, title: "Trigonometric Ratios to 360°",
    intro: r`Use \emph{CAST} for signs by quadrant and the \emph{reference angle} (the acute angle to the $x$-axis) to reduce any angle to a special-angle value. Exact values come from the $30^\circ$-$60^\circ$-$90^\circ$ and $45^\circ$-$45^\circ$-$90^\circ$ triangles.`,
    ideas: [r`CAST: which of $\sin,\cos,\tan$ is positive in each quadrant.`, r`Reference angle to the $x$-axis reduces to a special angle.`, r`Solve equations by combining reference angle with quadrants.`],
    examples: [
      { t: "Reference angles", body: r`Find the reference angle of $150^\circ$, $210^\circ$, $300^\circ$.\soln $30^\circ,\ 30^\circ,\ 60^\circ$.` },
      { t: "Signs by quadrant", body: r`In which quadrants is $\cos\theta<0$?\soln Quadrants II and III.` },
      { t: "Exact value", body: r`Find $\sin150^\circ$, $\cos150^\circ$, $\tan150^\circ$ exactly.\soln $\tfrac12,\ -\tfrac{\sqrt3}{2},\ -\tfrac{\sqrt3}{3}$.` },
      { t: "From a ratio", body: r`$\sin\theta=\tfrac35$ with $\theta$ in QII. Find $\cos\theta,\tan\theta$.\soln $\cos\theta=-\tfrac45,\ \tan\theta=-\tfrac34$.` },
      { t: "More exact values", body: r`Find $\cos225^\circ$ and $\sin300^\circ$.\soln $-\tfrac{\sqrt2}{2}$ and $-\tfrac{\sqrt3}{2}$.` },
      { t: "Solve a sine equation", body: r`Solve $\sin\theta=\tfrac12$ for $0^\circ\le\theta<360^\circ$.\soln Reference $30^\circ$; positive in QI, QII: $\theta=30^\circ,150^\circ$.` },
      { t: "Solve a cosine equation", body: r`Solve $\cos\theta=-\tfrac12$.\soln Reference $60^\circ$; negative in QII, QIII: $\theta=120^\circ,240^\circ$.` },
      { t: "Solve a tangent equation", body: r`Solve $\tan\theta=1$.\soln Reference $45^\circ$; positive in QI, QIII: $\theta=45^\circ,225^\circ$.` },
      { t: "From a ratio, QIII", body: r`$\cos\theta=-\tfrac{5}{13}$ with $\theta$ in QIII. Find $\sin\theta,\tan\theta$.\soln $\sin\theta=-\tfrac{12}{13},\ \tan\theta=\tfrac{12}{5}$.` },
    ],
    questions: [
      { ask: r`Reference angle of $200^\circ$?` },
      { ask: r`In which quadrants is $\sin\theta<0$?` },
      { ask: r`Find $\cos150^\circ$ exactly.` },
      { ask: r`Solve $\sin\theta=\tfrac12$ for $0^\circ\le\theta<360^\circ$.` },
      { ask: r`If $\cos\theta=\tfrac45$ in QIV, find $\sin\theta$.` },
      { ask: r`Reference angle of $310^\circ$?` },
      { ask: r`Find $\tan45^\circ$ exactly.` },
      { ask: r`Solve $\cos\theta=0$ for $0^\circ\le\theta<360^\circ$.` },
      { ask: r`Sign of $\tan\theta$ in QII?` },
      { ask: r`Find $\sin240^\circ$ exactly.` },
      { ask: r`Solve $\tan\theta=-1$ for $0^\circ\le\theta<360^\circ$.` },
      { ask: r`Solve $\cos\theta=-\tfrac12$ for $0^\circ\le\theta<360^\circ$.` },
      { ask: r`If $\sin\theta=-0.6$ in QIII, find $\cos\theta$ and $\tan\theta$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$20^\circ$`, r`QIII, QIV`, r`$-\tfrac{\sqrt3}{2}$`, r`$30^\circ,150^\circ$`, r`$-\tfrac35$`, r`$50^\circ$`, r`$1$`, r`$90^\circ,270^\circ$`, r`negative`, r`$-\tfrac{\sqrt3}{2}$`, r`$135^\circ,315^\circ$`, r`$120^\circ,240^\circ$`, r`$\cos\theta=-0.8,\ \tan\theta=0.75$`],
  },
  {
    code: "3.2", unit: U, title: "The Sine Law & the Ambiguous Case",
    intro: r`$\dfrac{a}{\sin A}=\dfrac{b}{\sin B}=\dfrac{c}{\sin C}$ works with any side–opposite-angle pair. Given two sides and a non-included angle (SSA), there may be \emph{two}, one, or no triangles.`,
    ideas: [r`Use a matched side/opposite-angle pair.`, r`SSA: check for a second angle ($180^\circ-B$).`, r`If $\sin B>1$, no triangle exists.`],
    examples: [
      { t: "Find a side", body: r`$A=40^\circ,B=60^\circ,a=10$. Find $b$.\soln $b=\dfrac{10\sin60^\circ}{\sin40^\circ}\approx13.5$.` },
      { t: "Find the third side", body: r`Continue: $C=80^\circ$, find $c$.\soln $c=\dfrac{10\sin80^\circ}{\sin40^\circ}\approx15.3$.` },
      { t: "Find an angle", body: r`$a=8,b=6,A=50^\circ$. Find $B$.\soln $\sin B=\dfrac{6\sin50^\circ}{8}\Rightarrow B\approx35.1^\circ$.` },
      { t: "Ambiguous — two triangles", body: r`$a=7,b=10,A=40^\circ$. Find $B$.\soln $\sin B=\dfrac{10\sin40^\circ}{7}\approx0.92\Rightarrow B\approx66.7^\circ$ or $113.3^\circ$.` },
      { t: "No triangle", body: r`$a=5,b=10,A=70^\circ$. Find $B$.\soln $\sin B=\dfrac{10\sin70^\circ}{5}\approx1.88>1$: no triangle.` },
      { t: "One triangle ($a>b$)", body: r`$a=12,b=8,A=55^\circ$. Find $B$.\soln $\sin B=\dfrac{8\sin55^\circ}{12}\Rightarrow B\approx33.1^\circ$ (only, since $a>b$).` },
      { t: "Third angle", body: r`From Example 3, find $C$.\soln $C=180^\circ-50^\circ-35.1^\circ=94.9^\circ$.` },
      { t: "Area follow-up", body: r`For Example 1's triangle, find its area ($\tfrac12ab\sin C$).\soln $\tfrac12(10)(13.5)\sin80^\circ\approx66.5$.` },
      { t: "Set up a pair", body: r`$A=25^\circ,C=100^\circ,c=15$. Find $a$.\soln $a=\dfrac{15\sin25^\circ}{\sin100^\circ}\approx6.4$.` },
    ],
    questions: [
      { ask: r`$A=35^\circ,B=85^\circ,a=12$. Find $b$.` },
      { ask: r`$a=9,b=7,A=50^\circ$. Find $B$.` },
      { ask: r`$A=25^\circ,C=100^\circ,c=15$. Find $a$.` },
      { ask: r`$a=6,b=8,A=40^\circ$. Find both possible values of $B$.` },
      { ask: r`$a=5,b=12,A=60^\circ$. How many triangles?` },
      { ask: r`$A=40^\circ,B=60^\circ,a=10$. Find $C$.` },
      { ask: r`$A=48^\circ,a=20,b=15$. Find $B$.` },
      { ask: r`$B=70^\circ,C=50^\circ,b=18$. Find $c$.` },
      { ask: r`$a=10,b=6,A=30^\circ$. Find $B$.` },
      { ask: r`In $\triangle ABC$, $A=45^\circ,a=14,b=10$. One or two triangles?` },
      { ask: r`$A=55^\circ,B=65^\circ,c=20$. Find $a$ (find $C$ first).` },
      { ask: r`$a=7,b=9,A=38^\circ$. Find both possible $B$.` },
      { ask: r`$a=8,b=11,A=44^\circ$: find $B$, then $C$, then $c$.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$\dfrac{12\sin85^\circ}{\sin35^\circ}\approx20.8$`, r`$B\approx36.6^\circ$`, r`$\approx6.4$`, r`$\sin B\approx0.86\Rightarrow B\approx59.0^\circ$ or $121.0^\circ$`, r`$\sin B\approx2.08>1$: none`, r`$80^\circ$`, r`$\sin B=\tfrac{15\sin48^\circ}{20}\Rightarrow B\approx33.8^\circ$`, r`$c=\tfrac{18\sin50^\circ}{\sin70^\circ}\approx14.7$`, r`$\sin B=\tfrac{6\sin30^\circ}{10}\Rightarrow B\approx17.5^\circ$`, r`one ($a>b$)`, r`$C=60^\circ$; $a=\tfrac{20\sin55^\circ}{\sin60^\circ}\approx18.9$`, r`$\sin B\approx0.79\Rightarrow B\approx52.3^\circ$ or $127.7^\circ$`, r`$B\approx72.8^\circ$, $C\approx63.2^\circ$, $c=\tfrac{8\sin63.2^\circ}{\sin44^\circ}\approx10.3$`],
  },
  {
    code: "3.3", unit: U, title: "The Cosine Law",
    intro: r`$a^2=b^2+c^2-2bc\cos A$ finds the third side from SAS, and rearranged, $\cos A=\dfrac{b^2+c^2-a^2}{2bc}$ finds an angle from SSS. Use it whenever the sine law's matched pair is unavailable.`,
    ideas: [r`SAS $\Rightarrow$ find the opposite side.`, r`SSS $\Rightarrow$ find any angle.`, r`Find the largest angle (opposite the longest side) first.`],
    examples: [
      { t: "SAS side", body: r`$b=7,c=9,A=60^\circ$. Find $a$.\soln $a^2=49+81-2(63)\cos60^\circ=67\Rightarrow a\approx8.2$.` },
      { t: "Another SAS", body: r`$b=5,c=8,A=40^\circ$. Find $a$.\soln $a^2=25+64-80\cos40^\circ\approx27.7\Rightarrow a\approx5.3$.` },
      { t: "SSS right check", body: r`$a=6,b=8,c=10$. Find $A$.\soln $\cos A=\dfrac{64+100-36}{160}=0.8\Rightarrow A\approx36.9^\circ$.` },
      { t: "SSS angle", body: r`$a=8,b=5,c=7$. Find $A$.\soln $\cos A=\dfrac{25+49-64}{70}=\tfrac17\Rightarrow A\approx81.8^\circ$.` },
      { t: "Largest angle", body: r`$a=5,b=6,c=7$. Find the largest angle.\soln Opposite $c$: $\cos C=\dfrac{25+36-49}{60}=0.2\Rightarrow C\approx78.5^\circ$.` },
      { t: "SAS with obtuse angle", body: r`$b=8,c=11,A=95^\circ$. Find $a$.\soln $a^2=64+121-176\cos95^\circ\approx200.3\Rightarrow a\approx14.2$.` },
      { t: "Right triangle from SSS", body: r`$a=9,b=12,c=15$. Find $C$.\soln $\cos C=\dfrac{81+144-225}{216}=0\Rightarrow C=90^\circ$.` },
      { t: "Choose the law", body: r`Which law for $b=12,c=15,A=50^\circ$?\soln Cosine law (SAS): $a=\sqrt{144+225-360\cos50^\circ}\approx11.7$.` },
      { t: "Diagonal of a parallelogram", body: r`Sides $6,10$ with a $70^\circ$ angle between. Find the shorter diagonal.\soln $d^2=36+100-120\cos70^\circ\approx95\Rightarrow d\approx9.7$.` },
    ],
    questions: [
      { ask: r`$b=12,c=15,A=50^\circ$. Find $a$.` },
      { ask: r`$a=5,b=6,c=7$. Find the largest angle.` },
      { ask: r`$b=10,c=14,A=35^\circ$. Find $a$.` },
      { ask: r`$a=9,b=12,c=15$. Find $C$.` },
      { ask: r`$b=8,c=11,A=95^\circ$. Find $a$.` },
      { ask: r`$a=6,b=8,c=10$. Find $A$.` },
      { ask: r`$a=7,b=9,C=48^\circ$. Find $c$.` },
      { ask: r`$a=4,b=5,c=6$. Find the smallest angle.` },
      { ask: r`$b=13,c=20,A=110^\circ$. Find $a$.` },
      { ask: r`Which law for SSS?` },
      { ask: r`$a=10,b=10,c=12$. Find $C$.` },
      { ask: r`Sides $6,10$, included angle $70^\circ$ — shorter diagonal?` },
      { ask: r`$a=8,b=11,c=6$: find the largest angle, then a second angle by the sine law.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$\approx11.7$`, r`$C\approx78.5^\circ$`, r`$\approx8.2$`, r`$90^\circ$`, r`$\approx14.2$`, r`$\approx36.9^\circ$`, r`$c=\sqrt{49+81-126\cos48^\circ}\approx6.7$`, r`opp $a$: $\cos A=\tfrac{25+36-16}{60}=0.75\Rightarrow41.4^\circ$`, r`$a=\sqrt{169+400-520\cos110^\circ}\approx27.3$`, r`cosine law`, r`$\cos C=\tfrac{100+100-144}{200}=0.28\Rightarrow73.7^\circ$`, r`$\approx9.7$`, r`opp $b$: $\cos B=\tfrac{64+36-121}{96}=-0.219\Rightarrow102.6^\circ$; then $\sin A=\tfrac{8\sin102.6^\circ}{11}\Rightarrow A\approx45.2^\circ$`],
  },
  {
    code: "3.4", unit: U, title: "Solving Oblique-Triangle Problems",
    intro: r`Real problems (surveying, navigation, structures) reduce to a triangle: sketch it, label the given parts, choose the sine or cosine law, then answer the question. Bearings are measured clockwise from north.`,
    ideas: [r`Sketch and label before computing.`, r`SAS/SSS $\to$ cosine law; matched pair $\to$ sine law.`, r`Convert bearings/elevations into interior angles.`],
    examples: [
      { t: "Two ships", body: r`Two ships leave port with a $60^\circ$ angle between courses, sailing $20$ km and $30$ km. How far apart?\soln $d=\sqrt{400+900-1200\cos60^\circ}=\sqrt{700}\approx26.5$ km.` },
      { t: "Survey a distance", body: r`From two points $100$ m apart, a rock is seen at $40^\circ$ and $75^\circ$. Find its distance from the first point.\soln Third angle $65^\circ$; $d=\dfrac{100\sin75^\circ}{\sin65^\circ}\approx106.6$ m.` },
      { t: "Leaning pole", body: r`A $12$ m pole leans; a $15$ m wire from its top meets the ground $9$ m from the base. Find the angle the pole makes with the ground.\soln $\cos\theta=\dfrac{12^2+9^2-15^2}{2(12)(9)}=0\Rightarrow\theta=90^\circ$.` },
      { t: "Triangular lot", body: r`A lot has sides $40$ m, $55$ m with a $80^\circ$ angle between. Find the third side.\soln $\sqrt{1600+3025-4400\cos80^\circ}\approx62.1$ m.` },
      { t: "Height by angles", body: r`Two points $50$ m apart on level ground sight a tower top at $30^\circ$ and $50^\circ$. Find the tower's slant distance from the nearer point.\soln Angle at tower $=20^\circ$; $d=\dfrac{50\sin30^\circ}{\sin20^\circ}\approx73.1$ m.` },
      { t: "Bearing problem", body: r`A plane flies $200$ km, turns through an interior angle of $110^\circ$, flies $150$ km. Distance from start?\soln $\sqrt{200^2+150^2-2(200)(150)\cos110^\circ}\approx288$ km.` },
      { t: "Area of a lot", body: r`Find the area of a triangular lot with sides $40,55$ and included $80^\circ$.\soln $\tfrac12(40)(55)\sin80^\circ\approx1083$ m$^2$.` },
      { t: "Guy wires", body: r`Two guy wires reach a tower top from points $30$ m apart, at $58^\circ$ and $49^\circ$. Find the longer wire.\soln Angle at top $=73^\circ$; longer wire opposite the larger ground angle: $\dfrac{30\sin58^\circ}{\sin73^\circ}\approx26.6$ m.` },
      { t: "Distance across a lake", body: r`From one point, two landmarks are $500$ m and $650$ m away with a $72^\circ$ angle between. Find the distance between landmarks.\soln $\sqrt{500^2+650^2-2(500)(650)\cos72^\circ}\approx686.8$ m.` },
    ],
    questions: [
      { ask: r`Two roads leave a town at $55^\circ$; cars go $80$ km and $110$ km. How far apart?` },
      { ask: r`A triangular field has sides $60$ m, $80$ m, included $65^\circ$ — find the third side.` },
      { ask: r`From two points $200$ m apart, a tower is seen at $35^\circ$ and $48^\circ$. Distance from the nearer point?` },
      { ask: r`Find the area of a lot with sides $30$ m, $45$ m and a $70^\circ$ angle between.` },
      { ask: r`Two ships leave port at a $48^\circ$ angle, sailing $15$ km and $22$ km. Distance apart?` },
      { ask: r`A $10$ m ladder and an $8$ m ladder reach the same point from $6$ m apart. Find the angle between them at the top given the base triangle has sides $10,8,6$.` },
      { ask: r`A plane flies $300$ km, turns to an interior $120^\circ$, flies $200$ km. Distance from start?` },
      { ask: r`A triangle has sides $12,15,20$ — find its largest angle.` },
      { ask: r`Two observers $400$ m apart sight a balloon at $40^\circ$ and $65^\circ$ (same side). Find the balloon's distance from the first observer.` },
      { ask: r`Find the area of a triangle with sides $9,12$ and included $50^\circ$.` },
      { ask: r`A parallelogram has sides $8,14$ with a $60^\circ$ angle — find the longer diagonal.` },
      { ask: r`Two trails diverge at $75^\circ$; hikers go $5$ km and $7$ km. How far apart?` },
      { ask: r`A surveyor at $A$ sees $B$ (250 m) and $C$ (310 m) with $\angle BAC=68^\circ$. Find $BC$, then $\angle ABC$.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$\sqrt{80^2+110^2-2(80)(110)\cos55^\circ}\approx91.7$ km`, r`$\sqrt{3600+6400-9600\cos65^\circ}\approx77.1$ m`, r`angle $97^\circ$: $\tfrac{200\sin35^\circ}{\sin97^\circ}\approx115.6$ m`, r`$\tfrac12(30)(45)\sin70^\circ\approx634$ m$^2$`, r`$\sqrt{225+484-660\cos48^\circ}\approx16.4$ km`, r`$\cos\theta=\tfrac{100+64-36}{160}=0.8\Rightarrow36.9^\circ$`, r`$\sqrt{300^2+200^2-2(300)(200)\cos120^\circ}\approx436$ km`, r`opp $20$: $\cos=\tfrac{144+225-400}{360}=-0.086\Rightarrow94.9^\circ$`, r`angle $75^\circ$: $\tfrac{400\sin40^\circ}{\sin75^\circ}\approx266.2$ m`, r`$\tfrac12(9)(12)\sin50^\circ\approx41.4$ units$^2$`, r`$\sqrt{64+196-224\cos120^\circ}\approx19.3$`, r`$\sqrt{25+49-70\cos75^\circ}\approx7.5$ km`, r`$BC=\sqrt{250^2+310^2-2(250)(310)\cos68^\circ}\approx317$ m; $\sin B=\tfrac{310\sin68^\circ}{317}\Rightarrow B\approx65.0^\circ$`],
  },
  {
    code: "3.5", unit: U, title: "Graphs of Sinusoidal Functions",
    intro: r`For $y=a\sin x+c$ (or $\cos$): amplitude $=|a|$, period $=360^\circ$, midline $y=c$, maximum $c+|a|$, minimum $c-|a|$. A coefficient $k$ on $x$ changes the period to $\dfrac{360^\circ}{|k|}$.`,
    ideas: [r`Amplitude $=|a|$; midline $y=c$.`, r`Period $=\dfrac{360^\circ}{|k|}$.`, r`Max $=c+|a|$, min $=c-|a|$.`],
    examples: [
      { t: "Basic sine", body: r`State the amplitude, period, max, min of $y=3\sin x$.\soln $3,\ 360^\circ,\ 3,\ -3$.` },
      { t: "Vertical shift", body: r`For $y=2\sin x+5$, give the midline, max, min.\soln Midline $y=5$; max $7$; min $3$.` },
      { t: "Changed period", body: r`Find the period of $y=4\cos(2x)$.\soln $\dfrac{360^\circ}{2}=180^\circ$; amplitude $4$.` },
      { t: "Small $k$", body: r`Find the period of $y=\sin(0.5x)$.\soln $\dfrac{360^\circ}{0.5}=720^\circ$.` },
      { t: "Reflection", body: r`Describe $y=-3\sin x$.\soln Amplitude $3$, reflected in the $x$-axis.` },
      { t: "Combined", body: r`For $y=5\cos x-2$, give max and min.\soln Max $3$; min $-7$.` },
      { t: "Period only", body: r`Period of $y=\cos(3x)$?\soln $120^\circ$.` },
      { t: "Read both", body: r`Amplitude and period of $y=6\sin(4x)$.\soln $6$ and $90^\circ$.` },
      { t: "Key point", body: r`For $y=2\cos x$, where is the first maximum?\soln At $x=0^\circ$, $y=2$.` },
    ],
    questions: [
      { ask: r`Amplitude and period of $y=5\sin x$?` },
      { ask: r`Midline, max, min of $y=3\sin x+4$?` },
      { ask: r`Period of $y=\cos(4x)$?` },
      { ask: r`Amplitude of $y=-7\sin x$?` },
      { ask: r`Max and min of $y=2\cos x-3$?` },
      { ask: r`Period of $y=\sin(0.25x)$?` },
      { ask: r`Amplitude and period of $y=4\cos(3x)$?` },
      { ask: r`For $y=6\sin x$, first maximum is at which $x$?` },
      { ask: r`Midline of $y=\cos x+2$?` },
      { ask: r`Period of $y=3\sin(6x)$?` },
      { ask: r`Max of $y=5\sin x-1$?` },
      { ask: r`Amplitude and period of $y=2\cos(0.5x)$?` },
      { ask: r`For $y=4\sin(2x)+1$: amplitude, period, midline, max, min.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$5$, $360^\circ$`, r`midline $4$, max $7$, min $1$`, r`$90^\circ$`, r`$7$`, r`max $-1$, min $-5$`, r`$1440^\circ$`, r`$4$, $120^\circ$`, r`$x=90^\circ$`, r`$y=2$`, r`$60^\circ$`, r`$4$`, r`$2$, $720^\circ$`, r`amp $4$, period $180^\circ$, midline $1$, max $5$, min $-3$`],
  },
  {
    code: "3.6", unit: U, title: "Transformations of Sinusoidal Functions",
    intro: r`In $y=a\sin\!\big(k(x-d)\big)+c$: $|a|$ is the amplitude, $\dfrac{360^\circ}{|k|}$ the period, $d$ the horizontal (phase) shift, and $c$ the vertical shift. Factor out $k$ before reading $d$.`,
    ideas: [r`Amplitude $|a|$, period $\tfrac{360^\circ}{|k|}$.`, r`$d$: phase shift; $c$: vertical shift.`, r`Build an equation from amplitude, period, and midline.`],
    examples: [
      { t: "Describe fully", body: r`Describe $y=2\sin(x-30^\circ)+1$.\soln Amplitude $2$, right $30^\circ$, up $1$; midline $y=1$.` },
      { t: "Factor for phase", body: r`Phase shift and period of $y=3\cos(2(x-45^\circ))$.\soln Right $45^\circ$; period $180^\circ$.` },
      { t: "Reflection + shift", body: r`Describe $y=-\sin x+4$.\soln Amplitude $1$, reflected, midline $y=4$.` },
      { t: "Everything at once", body: r`For $y=4\sin(3x)-2$: amplitude, period, midline, max, min.\soln $4;\ 120^\circ;\ y=-2;\ 2;\ -6$.` },
      { t: "Left shift", body: r`Describe $y=2\cos(x+60^\circ)$.\soln Amplitude $2$, left $60^\circ$.` },
      { t: "Max/min", body: r`Max and min of $y=-4\sin(2x)+1$.\soln Max $5$; min $-3$.` },
      { t: "Read phase from factored form", body: r`Phase shift of $y=\sin(2(x-90^\circ))$.\soln Right $90^\circ$.` },
      { t: "Build an equation", body: r`Write a sine function with amplitude $3$, period $180^\circ$, midline $y=2$.\soln $y=3\sin(2x)+2$ (since $k=\tfrac{360}{180}=2$).` },
      { t: "Range", body: r`State the range of $y=5\sin x-1$.\soln $[-6,4]$.` },
    ],
    questions: [
      { ask: r`Describe $y=3\sin(x-45^\circ)+2$.` },
      { ask: r`Period of $y=2\cos(4x)$?` },
      { ask: r`Phase shift of $y=\sin(x+30^\circ)$?` },
      { ask: r`Max and min of $y=6\sin(2x)-1$?` },
      { ask: r`Amplitude of $y=-5\cos(3x)+2$?` },
      { ask: r`Write a cosine function with amplitude $4$, period $120^\circ$, midline $y=0$.` },
      { ask: r`Range of $y=2\sin x+3$?` },
      { ask: r`Phase shift of $y=\cos(2(x-60^\circ))$?` },
      { ask: r`Midline and period of $y=\sin(0.5x)+5$?` },
      { ask: r`Max of $y=-3\cos x+4$?` },
      { ask: r`Write a sine function: amplitude $2$, period $90^\circ$, midline $y=1$.` },
      { ask: r`Describe $y=-2\sin(3(x-20^\circ))+4$.` },
      { ask: r`For $y=5\cos(2(x-30^\circ))-1$: amplitude, period, phase shift, max, min.`, challenge: true, ws: "3.2cm" },
    ],
    answers: [r`amp $3$, right $45^\circ$, up $2$`, r`$90^\circ$`, r`left $30^\circ$`, r`max $5$, min $-7$`, r`$5$`, r`$y=4\cos(3x)$`, r`$[1,5]$`, r`right $60^\circ$`, r`midline $5$, period $720^\circ$`, r`$7$`, r`$y=2\sin(4x)+1$`, r`amp $2$ (reflected), period $120^\circ$, right $20^\circ$, up $4$`, r`amp $5$, period $180^\circ$, right $30^\circ$, max $4$, min $-6$`],
  },
  {
    code: "3.7", unit: U, title: "Modelling with Sinusoidal Functions",
    intro: r`Turn repeating real data (tides, Ferris wheels, temperatures, daylight) into $y=a\sin\!\big(k(x-d)\big)+c$ or a cosine model: midline $c=\tfrac{\max+\min}{2}$, amplitude $a=\tfrac{\max-\min}{2}$, and $k=\tfrac{360^\circ}{\text{period}}$.`,
    ideas: [r`$c=\tfrac{\max+\min}{2}$, $a=\tfrac{\max-\min}{2}$.`, r`$k=\tfrac{360^\circ}{\text{period}}$ (time in the unit given).`, r`Use $-\cos$ to start at a minimum, $+\cos$ to start at a maximum.`],
    examples: [
      { t: "Ferris wheel model", body: r`A wheel of radius $10$ m has its centre $12$ m up and one turn every $60$ s, starting at the bottom. Write $h(t)$.\soln $k=\tfrac{360}{60}=6$; starts at min: $h=12-10\cos(6t)$ ($t$ in s).` },
      { t: "Value from the model", body: r`Using the model, find the height at $t=15$ s.\soln $12-10\cos(90^\circ)=12$ m.` },
      { t: "Max and min heights", body: r`Give the max and min heights of that wheel.\soln $22$ m and $2$ m.` },
      { t: "Tide amplitude/midline", body: r`High tide $8$ m, low tide $2$ m. Find the amplitude and midline.\soln Amplitude $3$; midline $5$.` },
      { t: "Tide period", body: r`A tide cycle takes $12$ h. Find $k$ (degrees per hour).\soln $k=\tfrac{360}{12}=30$.` },
      { t: "Temperature model", body: r`Daily high $25^\circ$, low $5^\circ$. Amplitude and midline?\soln Amplitude $10$; midline $15$.` },
      { t: "Write a tide model", body: r`Tide: max $8$ m, min $2$ m, period $12$ h, starting at high tide. Write $h(t)$.\soln $h=5+3\cos(30t)$.` },
      { t: "Start-at-minimum model", body: r`A quantity ranges $2$ to $8$, period $4$ s, starting at the minimum. Write it.\soln Midline $5$, amp $3$, $k=90$: $y=5-3\cos(90t)$.` },
      { t: "Interpret", body: r`For $h=5+3\cos(30t)$, when is the first low tide?\soln $\cos(30t)=-1\Rightarrow 30t=180^\circ\Rightarrow t=6$ h.` },
    ],
    questions: [
      { ask: r`High tide $10$ m, low $4$ m — amplitude and midline?` },
      { ask: r`A wheel turns once every $40$ s — find $k$ (degrees/s).` },
      { ask: r`Ferris wheel radius $8$ m, centre $9$ m up — max and min heights?` },
      { ask: r`Daily high $28^\circ$, low $12^\circ$ — amplitude and midline?` },
      { ask: r`A tide cycle is $10$ h — find $k$ (degrees/h).` },
      { ask: r`Write a Ferris-wheel model: radius $6$, centre $8$, period $30$ s, starting at bottom.` },
      { ask: r`For $h=12-10\cos(6t)$, find $h$ at $t=30$ s.` },
      { ask: r`A quantity ranges $1$ to $9$ — amplitude and midline?` },
      { ask: r`Write a tide model: max $6$, min $2$, period $12$ h, starting at high tide.` },
      { ask: r`For $h=5+3\cos(30t)$, find $h$ at $t=0$.` },
      { ask: r`A temperature model has midline $18$, amplitude $7$ — max and min?` },
      { ask: r`A wheel of radius $15$, centre $17$, starts at the bottom — lowest height?` },
      { ask: r`A tide has high $9$ m at $t=0$ and low $3$ m, period $12$ h. Write $h(t)$ and find the height at $t=3$ h.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`amp $3$, midline $7$`, r`$9$`, r`max $17$, min $1$`, r`amp $8$, midline $20$`, r`$36$`, r`$h=8-6\cos(12t)$`, r`$12-10\cos(180^\circ)=22$ m`, r`amp $4$, midline $5$`, r`$h=4+2\cos(30t)$`, r`$5+3=8$ m`, r`max $25$, min $11$`, r`$2$ m`, r`$h=6+3\cos(30t)$; at $t=3$: $6+3\cos(90^\circ)=6$ m`],
  },
];
