// MCT4C Unit 4 worksheets — Vectors & Geometry.
// Full \soln solutions; 9 worked examples + 13 questions + answer key each.
const r = String.raw;
const U = "4: Vectors & Geometry";

export default [
  {
    code: "4.1", unit: U, title: "Introduction to Vectors",
    intro: r`A vector has \emph{magnitude} and \emph{direction}. From components $(x,y)$: magnitude $=\sqrt{x^2+y^2}$ and direction is the angle to the positive $x$-axis. From a magnitude $m$ at angle $\theta$: components $(m\cos\theta,\ m\sin\theta)$.`,
    ideas: [r`Magnitude $|\vec v|=\sqrt{x^2+y^2}$.`, r`Components $(m\cos\theta,\ m\sin\theta)$.`, r`Opposite vector negates both components; a unit vector has magnitude $1$.`],
    examples: [
      { t: "Magnitude and direction", body: r`Find the magnitude and direction of $(3,4)$.\soln $\sqrt{9+16}=5$; $\theta=\tan^{-1}\tfrac43\approx53.1^\circ$.` },
      { t: "A 3-4-5 relative", body: r`Find $|(5,-12)|$.\soln $\sqrt{25+144}=13$.` },
      { t: "Resolve into components", body: r`A vector has magnitude $10$ at $30^\circ$. Find its components.\soln $(10\cos30^\circ,10\sin30^\circ)\approx(8.7,5)$.` },
      { t: "Larger magnitude", body: r`Components of magnitude $20$ at $60^\circ$?\soln $(20\cos60^\circ,20\sin60^\circ)=(10,17.3)$.` },
      { t: "Opposite vector", body: r`Write the opposite of $(2,3)$ and its magnitude.\soln $(-2,-3)$; magnitude $\sqrt{13}\approx3.6$.` },
      { t: "Scalar multiple", body: r`Find $3(2,-1)$ and its magnitude.\soln $(6,-3)$; $\sqrt{45}=3\sqrt5\approx6.7$.` },
      { t: "Unit vector", body: r`Find the unit vector in the direction of $(3,4)$.\soln $\tfrac{1}{5}(3,4)=(0.6,0.8)$.` },
      { t: "Another magnitude", body: r`Find $|(6,8)|$.\soln $10$.` },
      { t: "Direction in QII", body: r`Find the direction of $(-1,1)$.\soln Reference $45^\circ$ in QII: $135^\circ$.` },
    ],
    questions: [
      { ask: r`Find $|(8,6)|$.` },
      { ask: r`Find $|(5,12)|$.` },
      { ask: r`Components of magnitude $10$ at $30^\circ$?` },
      { ask: r`Find $|(-3,-4)|$.` },
      { ask: r`Find $2(4,-3)$ and its magnitude.` },
      { ask: r`Direction of $(1,1)$?` },
      { ask: r`Find $|(7,24)|$.` },
      { ask: r`Components of magnitude $16$ at $45^\circ$?` },
      { ask: r`Write the opposite of $(5,-2)$.` },
      { ask: r`Unit vector of $(6,8)$?` },
      { ask: r`Find $|(9,12)|$.` },
      { ask: r`Direction of $(0,5)$?` },
      { ask: r`Resolve a $25$ N force at $40^\circ$ above the horizontal into components.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$10$`, r`$13$`, r`$(8.7,5)$`, r`$5$`, r`$(8,-6)$, mag $10$`, r`$45^\circ$`, r`$25$`, r`$\approx(11.3,11.3)$`, r`$(-5,2)$`, r`$(0.6,0.8)$`, r`$15$`, r`$90^\circ$`, r`$(25\cos40^\circ,25\sin40^\circ)\approx(19.2,16.1)$ N`],
  },
  {
    code: "4.2", unit: U, title: "Adding & Subtracting Vectors",
    intro: r`Add or subtract vectors component-by-component, then take the magnitude. For two vectors with angle $\theta$ between them, the resultant magnitude is $\sqrt{a^2+b^2+2ab\cos\theta}$.`,
    ideas: [r`Add/subtract components, then find magnitude.`, r`Resultant $|\vec R|=\sqrt{a^2+b^2+2ab\cos\theta}$.`, r`Perpendicular vectors ($\theta=90^\circ$) reduce to $\sqrt{a^2+b^2}$.`],
    examples: [
      { t: "Add components", body: r`Find $(3,4)+(1,2)$ and its magnitude.\soln $(4,6)$; $\sqrt{52}\approx7.21$.` },
      { t: "Subtract components", body: r`Find $(5,2)-(1,6)$ and its magnitude.\soln $(4,-4)$; $\sqrt{32}\approx5.66$.` },
      { t: "Resultant at 60°", body: r`Two vectors, magnitudes $8$ and $5$, have $60^\circ$ between them. Find the resultant.\soln $\sqrt{64+25+2(8)(5)\cos60^\circ}=\sqrt{129}\approx11.4$.` },
      { t: "Resultant at 120°", body: r`Same magnitudes but $120^\circ$ apart.\soln $\sqrt{89+80\cos120^\circ}=\sqrt{49}=7$.` },
      { t: "Perpendicular", body: r`Resultant of magnitudes $6$ and $8$ at right angles.\soln $\sqrt{36+64}=10$.` },
      { t: "Linear combination", body: r`With $\vec u=(1,2),\vec v=(3,-1)$, find $2\vec u+\vec v$ and its magnitude.\soln $(5,3)$; $\sqrt{34}\approx5.83$.` },
      { t: "Difference vector", body: r`With $\vec u=(2,5),\vec v=(4,1)$, find $\vec u-\vec v$ and its magnitude.\soln $(-2,4)$; $\sqrt{20}\approx4.47$.` },
      { t: "Sum in different quadrants", body: r`Find $(-2,3)+(5,-1)$ and its magnitude.\soln $(3,2)$; $\sqrt{13}\approx3.61$.` },
      { t: "Equal magnitudes, right angle", body: r`Resultant of two magnitude-$10$ vectors at $90^\circ$.\soln $\sqrt{200}\approx14.1$.` },
    ],
    questions: [
      { ask: r`Find $(2,3)+(4,1)$ and its magnitude.` },
      { ask: r`Find $(7,2)-(3,5)$ and its magnitude.` },
      { ask: r`Resultant of magnitudes $6$ and $8$ at right angles?` },
      { ask: r`Resultant of magnitudes $9$ and $12$ at $90^\circ$?` },
      { ask: r`With $\vec u=(1,1),\vec v=(2,3)$, find $\vec u+\vec v$ and its magnitude.` },
      { ask: r`Find $3(2,-1)$.` },
      { ask: r`Find $(5,5)-(5,5)$.` },
      { ask: r`Resultant of magnitudes $5$ and $5$ at $60^\circ$?` },
      { ask: r`Resultant of magnitudes $7$ and $24$ at right angles?` },
      { ask: r`Find $(-3,4)+(3,-4)$.` },
      { ask: r`Find $|2\vec u|$ where $\vec u=(3,4)$.` },
      { ask: r`Resultant of magnitudes $12$ and $5$ at right angles?` },
      { ask: r`Two forces $10$ N and $14$ N have $50^\circ$ between them — find the resultant magnitude.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$(6,4)$, $\sqrt{52}\approx7.21$`, r`$(4,-3)$, $5$`, r`$10$`, r`$15$`, r`$(3,4)$, $5$`, r`$(6,-3)$`, r`$(0,0)$`, r`$\sqrt{75}\approx8.66$`, r`$25$`, r`$(0,0)$`, r`$10$`, r`$13$`, r`$\sqrt{100+196+280\cos50^\circ}\approx21.8$ N`],
  },
  {
    code: "4.3", unit: U, title: "Applications of Vectors",
    intro: r`Forces and velocities add as vectors. Resolve into components or use the resultant law; perpendicular cases (crosswinds, currents) use $\sqrt{a^2+b^2}$ with direction $\tan^{-1}\tfrac{\text{cross}}{\text{main}}$.`,
    ideas: [r`Velocities/forces combine as vectors.`, r`Crosswind/current: $\sqrt{a^2+b^2}$ and a drift angle.`, r`Two equal forces at angle $2\alpha$: resultant $=2F\cos\alpha$ along the bisector.`],
    examples: [
      { t: "Crosswind", body: r`A plane heads at $400$ km/h with a $60$ km/h perpendicular crosswind. Find the ground speed and drift.\soln $\sqrt{400^2+60^2}\approx404.5$ km/h; drift $\tan^{-1}\tfrac{60}{400}\approx8.5^\circ$.` },
      { t: "Perpendicular forces", body: r`Two forces $10$ N and $15$ N act at right angles. Find the resultant.\soln $\sqrt{100+225}\approx18.0$ N.` },
      { t: "Forces at 60°", body: r`Forces $12$ N and $18$ N have $60^\circ$ between. Resultant?\soln $\sqrt{144+324+2(12)(18)\cos60^\circ}\approx26.2$ N.` },
      { t: "River crossing", body: r`A boat rows $8$ km/h straight across; the current is $3$ km/h. Find the actual speed and angle.\soln $\sqrt{64+9}\approx8.5$ km/h; $\tan^{-1}\tfrac38\approx20.6^\circ$ downstream.` },
      { t: "Wind from the side", body: r`A plane flies $300$ km/h north into a $50$ km/h east wind. Ground speed?\soln $\sqrt{300^2+50^2}\approx304.1$ km/h.` },
      { t: "Resolve a force", body: r`Resolve a $25$ N force at $40^\circ$ into horizontal and vertical parts.\soln $(25\cos40^\circ,25\sin40^\circ)\approx(19.2,16.1)$ N.` },
      { t: "Two tugboats", body: r`Two tugboats each pull $5000$ N, at $30^\circ$ on either side of a barge's axis. Find the forward pull.\soln $2(5000)\cos30^\circ\approx8660$ N.` },
      { t: "Equilibrant", body: r`If a resultant is $18$ N at $40^\circ$, what is the equilibrant?\soln Same magnitude, opposite direction: $18$ N at $220^\circ$.` },
      { t: "Two equal forces", body: r`Two $20$ N forces have $60^\circ$ between. Resultant?\soln $2(20)\cos30^\circ\approx34.6$ N.` },
    ],
    questions: [
      { ask: r`A plane heads $500$ km/h with a $100$ km/h perpendicular crosswind — ground speed?` },
      { ask: r`Two forces $8$ N and $6$ N at right angles — resultant?` },
      { ask: r`Two forces $12$ N and $16$ N at $90^\circ$ — resultant?` },
      { ask: r`A boat crosses at $10$ km/h with a $4$ km/h current — actual speed and angle?` },
      { ask: r`A plane flies $400$ km/h north with a $30$ km/h east wind — ground speed?` },
      { ask: r`Two $20$ N forces at $60^\circ$ apart — resultant?` },
      { ask: r`Horizontal component of a $50$ N force at $30^\circ$?` },
      { ask: r`Two forces $3$ N and $4$ N at right angles — resultant?` },
      { ask: r`Two tugs pull $4000$ N each, $40^\circ$ apart — forward pull?` },
      { ask: r`A plane heads $350$ km/h with a $45$ km/h crosswind — ground speed?` },
      { ask: r`Vertical component of a $60$ N force at $25^\circ$?` },
      { ask: r`Two forces $9$ N and $40$ N at right angles — resultant?` },
      { ask: r`A swimmer crosses a $60$ m river at $2$ m/s; the current is $1.5$ m/s. Find the resultant speed and how far downstream they land.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$\sqrt{250000+10000}\approx509.9$ km/h`, r`$10$ N`, r`$20$ N`, r`$\sqrt{116}\approx10.8$ km/h, $\tan^{-1}\tfrac{4}{10}\approx21.8^\circ$`, r`$\sqrt{160000+900}\approx401.1$ km/h`, r`$2(20)\cos30^\circ\approx34.6$ N`, r`$50\cos30^\circ\approx43.3$ N`, r`$5$ N`, r`$2(4000)\cos20^\circ\approx7518$ N`, r`$\sqrt{122500+2025}\approx352.9$ km/h`, r`$60\sin25^\circ\approx25.4$ N`, r`$41$ N`, r`$\sqrt{2^2+1.5^2}=2.5$ m/s; cross time $\tfrac{60}{2}=30$ s, downstream $1.5(30)=45$ m`],
  },
  {
    code: "4.4", unit: U, title: "Composite Two-Dimensional Areas",
    intro: r`Break a composite region into rectangles, triangles, trapezoids, and circles; add the pieces, or subtract a cut-out. Key areas: rectangle $lw$, triangle $\tfrac12bh$, trapezoid $\tfrac12(a+b)h$, circle $\pi r^2$.`,
    ideas: [r`Decompose into standard shapes.`, r`Add pieces or subtract holes.`, r`Semicircle $=\tfrac12\pi r^2$; annulus $=\pi(R^2-r^2)$.`],
    examples: [
      { t: "L-shape (subtract)", body: r`A $10\times8$ rectangle with a $4\times3$ corner removed. Area?\soln $80-12=68$.` },
      { t: "Rectangle + semicircle", body: r`A $12\times7$ rectangle capped by a semicircle of diameter $7$. Area?\soln $84+\tfrac12\pi(3.5)^2\approx84+19.2=103.2$.` },
      { t: "Trapezoid", body: r`Parallel sides $8$ and $14$, height $6$. Area?\soln $\tfrac12(8+14)(6)=66$.` },
      { t: "Annulus", body: r`Region between circles of radius $6$ and $4$. Area?\soln $\pi(36-16)=20\pi\approx62.8$.` },
      { t: "Stadium (track)", body: r`A $20\times12$ rectangle with a semicircle on each short end ($r=6$). Area?\soln $240+\pi(6)^2\approx240+113.1=353.1$.` },
      { t: "Triangle", body: r`Base $10$, height $8$. Area?\soln $\tfrac12(10)(8)=40$.` },
      { t: "Two rectangles", body: r`A $6\times4$ rectangle joined to a $3\times2$ rectangle. Area?\soln $24+6=30$.` },
      { t: "Parallelogram", body: r`Base $9$, height $5$. Area?\soln $45$.` },
      { t: "Square minus circle", body: r`A square of side $10$ with an inscribed circle ($r=5$) removed. Area?\soln $100-25\pi\approx100-78.5=21.5$.` },
    ],
    questions: [
      { ask: r`Area of a $15\times9$ rectangle?` },
      { ask: r`Area of a triangle, base $12$, height $7$?` },
      { ask: r`Area of a circle, radius $8$ (leave in $\pi$)?` },
      { ask: r`Area of a trapezoid, parallel sides $5,11$, height $4$?` },
      { ask: r`L-shape: $12\times10$ with a $5\times4$ corner removed — area?` },
      { ask: r`Annulus between radii $10$ and $6$ (leave in $\pi$)?` },
      { ask: r`A $10\times6$ rectangle with a semicircle ($r=3$) on one end — area?` },
      { ask: r`Area of a parallelogram, base $8$, height $6$?` },
      { ask: r`A square of side $7$ with an inscribed circle removed — area?` },
      { ask: r`Composite: an $8\times5$ rectangle with a triangle (base $8$, height $4$) on top — area?` },
      { ask: r`Area of a circle, radius $5$ (to 1 decimal)?` },
      { ask: r`Area of a trapezoid, parallel sides $6,10$, height $5$?` },
      { ask: r`A running track: a $40\times20$ rectangle with a semicircular end on each short side ($r=10$). Find the total area.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$135$`, r`$42$`, r`$64\pi$`, r`$32$`, r`$120-20=100$`, r`$64\pi\approx201.1$`, r`$60+\tfrac12\pi(9)\approx74.1$`, r`$48$`, r`$49-12.25\pi\approx10.5$`, r`$40+16=56$`, r`$\approx78.5$`, r`$40$`, r`$800+\pi(10)^2\approx1114.2$`],
  },
  {
    code: "4.5", unit: U, title: "Properties of Circles",
    intro: r`For a central angle $\theta$ (degrees): arc length $=\tfrac{\theta}{360}\,2\pi r$ and sector area $=\tfrac{\theta}{360}\,\pi r^2$. An inscribed angle is half the central angle on the same arc.`,
    ideas: [r`Arc $=\tfrac{\theta}{360}(2\pi r)$.`, r`Sector area $=\tfrac{\theta}{360}(\pi r^2)$.`, r`Inscribed angle $=\tfrac12\times$ central angle.`],
    examples: [
      { t: "Arc length", body: r`Arc of a $72^\circ$ sector, radius $10$.\soln $\tfrac{72}{360}(2\pi\cdot10)=4\pi\approx12.57$.` },
      { t: "Sector area", body: r`Area of that $72^\circ$ sector.\soln $\tfrac{72}{360}(\pi\cdot100)=20\pi\approx62.83$.` },
      { t: "Bigger angle", body: r`Arc of a $120^\circ$ sector, radius $6$.\soln $\tfrac13(2\pi\cdot6)=4\pi\approx12.57$.` },
      { t: "Small sector", body: r`Area of a $45^\circ$ sector, radius $8$.\soln $\tfrac18(\pi\cdot64)=8\pi\approx25.13$.` },
      { t: "Whole circle", body: r`Circumference and area for radius $7$.\soln $14\pi\approx43.98$; $49\pi\approx153.94$.` },
      { t: "Quarter arc", body: r`Arc of a $90^\circ$ sector, radius $12$.\soln $6\pi\approx18.85$.` },
      { t: "Reflex sector", body: r`Area of a $216^\circ$ sector, radius $5$.\soln $\tfrac{216}{360}(25\pi)=15\pi\approx47.12$.` },
      { t: "Inscribed angle", body: r`A central angle is $80^\circ$; find the inscribed angle on the same arc.\soln $40^\circ$.` },
      { t: "From inscribed to central", body: r`An inscribed angle is $35^\circ$; find the central angle.\soln $70^\circ$.` },
    ],
    questions: [
      { ask: r`Circumference of a circle, radius $5$ (in $\pi$)?` },
      { ask: r`Area of a circle, radius $9$ (in $\pi$)?` },
      { ask: r`Arc of a $90^\circ$ sector, radius $10$ (in $\pi$)?` },
      { ask: r`Area of a $60^\circ$ sector, radius $6$ (in $\pi$)?` },
      { ask: r`Arc of a $180^\circ$ sector, radius $4$ (in $\pi$)?` },
      { ask: r`Area of a $36^\circ$ sector, radius $10$ (in $\pi$)?` },
      { ask: r`Inscribed angle if the central angle is $80^\circ$?` },
      { ask: r`Arc of a $120^\circ$ sector, radius $15$ (in $\pi$)?` },
      { ask: r`Area of a $30^\circ$ sector, radius $12$ (in $\pi$)?` },
      { ask: r`Area of a semicircle, radius $8$ (in $\pi$)?` },
      { ask: r`Arc of a $240^\circ$ sector, radius $9$ (in $\pi$)?` },
      { ask: r`Central angle if the inscribed angle is $25^\circ$?` },
      { ask: r`A sector of radius $12$ has arc length $8\pi$. Find its central angle and area.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$10\pi$`, r`$81\pi$`, r`$5\pi$`, r`$6\pi$`, r`$4\pi$`, r`$10\pi$`, r`$40^\circ$`, r`$10\pi$`, r`$12\pi$`, r`$32\pi$`, r`$12\pi$`, r`$50^\circ$`, r`$\theta=120^\circ$; area $48\pi\approx150.8$`],
  },
  {
    code: "4.6", unit: U, title: "Surface Area & Volume",
    intro: r`Prism/cylinder volume $=(\text{base area})\times h$; pyramid/cone $=\tfrac13(\text{base area})h$; sphere $=\tfrac43\pi r^3$. Cylinder $SA=2\pi r^2+2\pi rh$, cone $SA=\pi r^2+\pi r\ell$, sphere $SA=4\pi r^2$.`,
    ideas: [r`Prisms/cylinders: base $\times h$; cones/pyramids: $\tfrac13$ of that.`, r`Sphere $V=\tfrac43\pi r^3$, $SA=4\pi r^2$.`, r`Cone slant $\ell=\sqrt{r^2+h^2}$.`],
    examples: [
      { t: "Cylinder", body: r`Radius $5$, height $10$: volume and surface area.\soln $V=250\pi\approx785.4$; $SA=50\pi+100\pi=150\pi\approx471.2$.` },
      { t: "Cone", body: r`Radius $3$, height $4$ (slant $5$): volume and surface area.\soln $V=12\pi\approx37.7$; $SA=9\pi+15\pi=24\pi\approx75.4$.` },
      { t: "Sphere", body: r`Radius $6$: volume and surface area.\soln $V=288\pi\approx904.8$; $SA=144\pi\approx452.4$.` },
      { t: "Rectangular prism", body: r`$4\times5\times6$: volume and surface area.\soln $V=120$; $SA=2(20+24+30)=148$.` },
      { t: "Square pyramid", body: r`Base $6$, height $4$, slant height $5$: volume and surface area.\soln $V=\tfrac13(36)(4)=48$; $SA=36+4(\tfrac12\cdot6\cdot5)=96$.` },
      { t: "Cylinder volume", body: r`Radius $4$, height $9$: volume.\soln $144\pi\approx452.4$.` },
      { t: "Larger cone", body: r`Radius $6$, height $8$ (slant $10$): volume and surface area.\soln $V=96\pi\approx301.6$; $SA=36\pi+60\pi=96\pi\approx301.6$.` },
      { t: "Small sphere", body: r`Radius $3$: volume and surface area.\soln $V=36\pi\approx113.1$; $SA=36\pi\approx113.1$.` },
      { t: "Find slant first", body: r`A cone has radius $9$, height $12$. Find slant height.\soln $\sqrt{81+144}=15$.` },
    ],
    questions: [
      { ask: r`Volume of a cylinder, radius $3$, height $7$ (in $\pi$)?` },
      { ask: r`Volume of a sphere, radius $5$ (in $\pi$)?` },
      { ask: r`Volume of a cone, radius $4$, height $9$ (in $\pi$)?` },
      { ask: r`Surface area of a cube, side $5$?` },
      { ask: r`Volume of a $3\times4\times10$ prism?` },
      { ask: r`Surface area of a sphere, radius $7$ (in $\pi$)?` },
      { ask: r`Volume of a cylinder, radius $6$, height $10$ (in $\pi$)?` },
      { ask: r`Surface area of a closed cylinder, radius $5$, height $8$ (in $\pi$)?` },
      { ask: r`Volume of a square pyramid, base $8$, height $9$?` },
      { ask: r`Volume of a cone, radius $5$, height $12$ (in $\pi$)?` },
      { ask: r`Surface area of a cone, radius $6$, slant $10$ (in $\pi$)?` },
      { ask: r`Volume of a hemisphere, radius $6$ (in $\pi$)?` },
      { ask: r`A cone has radius $9$ and height $12$. Find slant height, volume, and total surface area.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$63\pi$`, r`$\tfrac{500}{3}\pi$`, r`$48\pi$`, r`$150$`, r`$120$`, r`$196\pi$`, r`$360\pi$`, r`$130\pi$`, r`$192$`, r`$100\pi$`, r`$96\pi$`, r`$144\pi$`, r`$\ell=15$; $V=324\pi\approx1017.9$; $SA=216\pi\approx678.6$`],
  },
  {
    code: "4.7", unit: U, title: "Composite Three-Dimensional Figures",
    intro: r`Split a solid into standard pieces, compute each volume, and add — or subtract a hole. Common combos: cylinder $+$ hemisphere (silo/capsule), cone $+$ cylinder, or a prism with a drilled hole.`,
    ideas: [r`Add the piece volumes (or subtract a hole).`, r`Hemisphere $V=\tfrac23\pi r^3$.`, r`Drilled hole subtracts a cylinder $\pi r^2 h$.`],
    examples: [
      { t: "Cylinder + hemisphere", body: r`A cylinder ($r=3,h=10$) topped by a hemisphere ($r=3$). Volume?\soln $90\pi+18\pi=108\pi\approx339.3$.` },
      { t: "Cone on a cylinder", body: r`A cone ($r=3,h=4$) on a cylinder ($r=3,h=6$). Volume?\soln $12\pi+54\pi=66\pi\approx207.3$.` },
      { t: "Drilled block", body: r`A $10\times8\times6$ box with a cylindrical hole ($r=2$) drilled through the height $6$. Volume?\soln $480-24\pi\approx404.6$.` },
      { t: "Dome on a cylinder", body: r`A hemisphere ($r=6$) on a cylinder ($r=6,h=10$). Volume?\soln $360\pi+144\pi=504\pi\approx1583.4$.` },
      { t: "Capsule", body: r`A cylinder ($r=2,h=10$) with a hemisphere on each end. Volume?\soln $40\pi+\tfrac43\pi(8)=40\pi+\tfrac{32}{3}\pi\approx159.2$.` },
      { t: "Two prisms", body: r`A $5\times4\times3$ box stacked on a $5\times4\times2$ box. Volume?\soln $60+40=100$.` },
      { t: "Ice-cream cone", body: r`A cone ($r=3,h=8$) filled and topped by a hemisphere ($r=3$). Volume?\soln $24\pi+18\pi=42\pi\approx131.9$.` },
      { t: "Block with a bore", body: r`A $12\times10\times8$ box with a cylindrical hole ($r=3$) through the height $8$. Volume?\soln $960-72\pi\approx733.8$.` },
      { t: "Silo", body: r`A grain silo: cylinder ($r=4,h=15$) with a hemispherical top ($r=4$). Volume?\soln $240\pi+\tfrac23\pi(64)=240\pi+\tfrac{128}{3}\pi\approx888.0$.` },
    ],
    questions: [
      { ask: r`A cylinder ($r=2,h=5$) with a cone ($r=2,h=3$) on top — volume (in $\pi$)?` },
      { ask: r`A hemisphere ($r=3$) on a cylinder ($r=3,h=8$) — volume (in $\pi$)?` },
      { ask: r`A $6\times4\times5$ box with a cylindrical hole ($r=1$) through height $5$ — volume?` },
      { ask: r`A cone ($r=6,h=8$) on a cylinder ($r=6,h=10$) — volume (in $\pi$)?` },
      { ask: r`Two boxes: $5\times4\times3$ and $5\times4\times2$ stacked — volume?` },
      { ask: r`A capsule: cylinder ($r=2,h=10$) with a hemisphere each end — volume (decimal)?` },
      { ask: r`A cone ($r=3,h=8$) topped by a hemisphere ($r=3$) — volume (in $\pi$)?` },
      { ask: r`A cylinder ($r=5,h=12$) with a hemispherical cap ($r=5$) — volume (in $\pi$)?` },
      { ask: r`A $10\times10\times4$ slab with a cylindrical hole ($r=2$) through height $4$ — volume (decimal)?` },
      { ask: r`A hemisphere ($r=6$) on a cylinder ($r=6,h=10$) — volume (in $\pi$)?` },
      { ask: r`A $12\times10\times8$ box with a hole ($r=3$) drilled through height $8$ — volume (decimal)?` },
      { ask: r`A cone ($r=3,h=4$) on a cylinder ($r=3,h=6$) — volume (in $\pi$)?` },
      { ask: r`A silo is a cylinder ($r=4,h=12$) with a hemispherical top ($r=4$). Find its total volume.`, challenge: true, ws: "3.4cm" },
    ],
    answers: [r`$20\pi+4\pi=24\pi$`, r`$72\pi+18\pi=90\pi$`, r`$120-5\pi\approx104.3$`, r`$96\pi+360\pi=456\pi$`, r`$100$`, r`$40\pi+\tfrac{32}{3}\pi\approx159.2$`, r`$24\pi+18\pi=42\pi$`, r`$300\pi+\tfrac{250}{3}\pi\approx1204.3$`, r`$400-16\pi\approx349.7$`, r`$360\pi+144\pi=504\pi$`, r`$960-72\pi\approx733.8$`, r`$12\pi+54\pi=66\pi$`, r`$192\pi+\tfrac{128}{3}\pi\approx737.2$`],
  },
];
