// MHF4U Unit 1 — Polynomial Functions: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 1.1 Power Functions & End Behaviour ──────────────────────
function g11() {
  const q = [];
  q.push(mc("easy", "End behaviour of $f(x)=x^3$:", ["down–up", "up–up", "down–down", "up–down"], 0));
  q.push(mc("easy", "End behaviour of $f(x)=x^4$:", ["up–up", "down–up", "down–down", "up–down"], 0));
  q.push(mc("easy", "End behaviour of $f(x)=-x^4$:", ["down–down", "up–up", "down–up", "up–down"], 0));
  q.push(mc("easy", "End behaviour of $f(x)=-x^3$:", ["up–down", "down–up", "up–up", "down–down"], 0));
  q.push(mc("easy", "Even degree means both ends go:", ["the same direction", "opposite directions", "always up", "always down"], 0));
  q.push(mc("easy", "A negative leading coefficient:", ["flips the ends", "never matters", "sets the degree", "sets the zeros"], 0));
  q.push(ms("easy", "End behaviour depends on:", ["the degree's parity", "the sign of the leading coefficient", "the leading term", "the constant term"], [0, 1, 2]));
  q.push(ms("easy", "Even degree:", ["both ends the same", "up–up if $a>0$", "down–down if $a<0$", "ends opposite"], [0, 1, 2]));
  q.push(ms("easy", "Odd degree:", ["ends opposite", "down–up if $a>0$", "up–down if $a<0$", "both the same"], [0, 1, 2]));
  q.push(ms("easy", "For large $|x|$:", ["the leading term dominates", "other terms are negligible", "it controls the ends", "the constant dominates"], [0, 1, 2]));
  q.push(tf("easy", "$x^4$ has both ends up.", true));
  q.push(tf("easy", "$x^3$ has both ends up.", false));
  q.push(tf("easy", "A negative leading coefficient flips the end behaviour.", true));
  q.push(fill("easy", "End behaviour of $x^5$ (like down-up).", ["down-up", "down–up"]));
  q.push(fill("easy", "End behaviour of $-x^2$.", ["down-down", "down–down"]));
  q.push(fill("easy", "End behaviour of $x^6$.", ["up-up", "up–up"]));
  q.push(num("easy", "Degree of $x^5$.", 5, 0));
  q.push(num("easy", "Degree of $-3x^4$.", 4, 0));
  q.push(num("easy", "The smallest even degree greater than 0.", 2, 0));
  q.push(match("easy", "Match each to its end behaviour.", ["$x^3$", "$x^4$", "$-x^4$"], ["down–up", "up–up", "down–down"], [0, 1, 2]));
  q.push(mc("medium", "End behaviour of $-2x^3$:", ["up–down", "down–up", "up–up", "down–down"], 0));
  q.push(mc("medium", "End behaviour of $3x^6$:", ["up–up", "down–up", "down–down", "up–down"], 0));
  q.push(mc("medium", "A graph falls left, rises right:", ["odd degree, $a>0$", "even, $a>0$", "odd, $a<0$", "even, $a<0$"], 0));
  q.push(mc("medium", "A graph rises on both ends:", ["even, $a>0$", "odd, $a>0$", "even, $a<0$", "odd, $a<0$"], 0));
  q.push(mc("medium", "End behaviour of $2x^5-x^3+4$:", ["down–up", "up–down", "up–up", "down–down"], 0));
  q.push(mc("medium", "End behaviour of $-x^6+2x^2$:", ["down–down", "up–up", "down–up", "up–down"], 0));
  q.push(ms("medium", "$-2x^3$:", ["odd degree", "$a<0$", "up–down", "down–up"], [0, 1, 2]));
  q.push(ms("medium", "Reading a graph:", ["check both ends", "opposite → odd", "same → even", "ignore the ends"], [0, 1, 2]));
  q.push(ms("medium", "Leading term of $2x^5-x^3+4$:", ["$2x^5$", "degree 5", "sets the end behaviour", "$-x^3$"], [0, 1, 2]));
  q.push(ms("medium", "Rising on both ends:", ["even degree", "$a>0$", "like a parabola", "odd degree"], [0, 1, 2]));
  q.push(tf("medium", "$-2x^3$ has end behaviour up–down.", true));
  q.push(tf("medium", "$3x^6$ has both ends up.", true));
  q.push(tf("medium", "$2x^5-x^3+4$ has both ends up.", false));
  q.push(fill("medium", "End behaviour of $-4x^3$.", ["up-down", "up–down"]));
  q.push(fill("medium", "End behaviour of $5x^4$.", ["up-up", "up–up"]));
  q.push(fill("medium", "End behaviour of $-x^5+3x^2$.", ["up-down", "up–down"]));
  q.push(num("medium", "Degree with leading term $7x^8$.", 8, 0));
  q.push(num("medium", "Minimum degree of an odd polynomial crossing the x-axis 3 times.", 3, 0));
  q.push(num("medium", "Sign of $a$ (enter -1) that makes $x^4$ open down.", -1, 0));
  q.push(match("medium", "Match each to its end behaviour.", ["$-2x^3$", "$3x^6$", "$2x^5$"], ["up–down", "up–up", "down–up"], [0, 1, 2]));
  q.push(mc("hard", "End behaviour of $f(x)=-x^7+5x^2$:", ["up–down", "down–up", "up–up", "down–down"], 0));
  q.push(mc("hard", "A degree-4 polynomial with $a<0$ has ends:", ["down–down", "up–up", "down–up", "up–down"], 0));
  q.push(mc("hard", "Which has the same end behaviour as $x^3$?", ["$5x^3-2x$", "$-x^3$", "$x^2$", "$-x^5$"], 0));
  q.push(mc("hard", "A polynomial crosses the x-axis 5 times with ends down–up. Minimum degree:", ["5", "4", "6", "3"], 0));
  q.push(mc("hard", "As $x\\to-\\infty$, $-3x^4+x\\to$", ["$-\\infty$", "$+\\infty$", "0", "3"], 0));
  q.push(ms("hard", "$f(x)=-x^7+5x^2$:", ["odd degree 7", "$a=-1<0$", "up–down", "down–up"], [0, 1, 2]));
  q.push(ms("hard", "Same end behaviour as $x^3$:", ["positive odd leading term", "$5x^3-2x$ qualifies", "down–up", "$-x^3$ qualifies"], [0, 1, 2]));
  q.push(ms("hard", "Minimum degree from crossings & ends:", ["at least the number of crossings", "odd ends → odd degree", "5 crossings → degree $\\ge5$", "degree 4"], [0, 1, 2]));
  q.push(ms("hard", "Evaluating end limits:", ["consider large $|x|$", "the leading term wins", "sign from $a$ and parity", "the constant wins"], [0, 1, 2]));
  q.push(tf("hard", "$-x^7+5x^2$ has end behaviour up–down.", true));
  q.push(tf("hard", "$5x^3-2x$ has the same end behaviour as $x^3$.", true));
  q.push(tf("hard", "$-3x^4+x\\to+\\infty$ as $x\\to-\\infty$.", false));
  q.push(fill("hard", "End behaviour of $-x^7+5x^2$.", ["up-down", "up–down"]));
  q.push(fill("hard", "As $x\\to-\\infty$, $-3x^4\\to$ ?", ["-∞", "-infinity", "negative infinity"]));
  q.push(fill("hard", "Minimum degree: 5 x-intercepts, ends down–up.", ["5"]));
  q.push(num("hard", "Minimum degree with 5 x-intercepts.", 5, 0));
  q.push(num("hard", "Degree of the leading term $-x^7$.", 7, 0));
  q.push(num("hard", "As $x\\to+\\infty$, $y=x^3$: enter 1 for $+\\infty$.", 1, 0));
  q.push(order("hard", "Order the steps to find the end behaviour of $-2x^5+x^2$.", ["Find the leading term $-2x^5$", "Degree 5 is odd → ends opposite", "$a=-2<0$", "Ends: up–down"]));
  q.push(match("hard", "Match each to its end behaviour.", ["$-x^7$", "$-3x^4$", "$5x^3$"], ["up–down", "down–down", "down–up"], [0, 1, 2]));
  return q;
}

// ── 1.2 Characteristics of Polynomial Functions ──────────────
function g12() {
  const q = [];
  q.push(mc("easy", "Max turning points of a degree-5 polynomial:", ["4", "5", "3", "6"], 0));
  q.push(mc("easy", "Max x-intercepts of a degree-4 polynomial:", ["4", "3", "5", "2"], 0));
  q.push(mc("easy", "If the 3rd differences are constant, the degree is:", ["3", "2", "4", "1"], 0));
  q.push(mc("easy", "An even function is symmetric about:", ["the y-axis", "the origin", "the x-axis", "nothing"], 0));
  q.push(mc("easy", "An odd function is symmetric about:", ["the origin", "the y-axis", "the x-axis", "nothing"], 0));
  q.push(mc("easy", "$f(x)=x^4$ is:", ["even", "odd", "neither", "linear"], 0));
  q.push(ms("easy", "For degree $n$:", ["at most $n$ zeros", "at most $n-1$ turning points", "it sets end behaviour", "at most $n$ turning points"], [0, 1, 2]));
  q.push(ms("easy", "Finite differences:", ["$n$-th differences constant for degree $n$", "computed from a table", "reveal the degree", "1st is always constant"], [0, 1, 2]));
  q.push(ms("easy", "Even function:", ["$f(-x)=f(x)$", "only even powers", "y-axis symmetry", "origin symmetry"], [0, 1, 2]));
  q.push(ms("easy", "Odd function:", ["$f(-x)=-f(x)$", "only odd powers", "origin symmetry", "y-axis symmetry"], [0, 1, 2]));
  q.push(tf("easy", "A degree-4 polynomial has at most 3 turning points.", true));
  q.push(tf("easy", "An even function is symmetric about the origin.", false));
  q.push(tf("easy", "The 2nd differences are constant for a quadratic.", true));
  q.push(fill("easy", "Max turning points of a degree-6 polynomial.", ["5"]));
  q.push(fill("easy", "Max x-intercepts of a degree-5 polynomial.", ["5"]));
  q.push(fill("easy", "Degree if the 4th differences are constant.", ["4"]));
  q.push(num("easy", "Max turning points of a degree-7 polynomial.", 6, 0));
  q.push(num("easy", "Max x-intercepts of a degree-3 polynomial.", 3, 0));
  q.push(num("easy", "Degree if the 2nd differences are constant.", 2, 0));
  q.push(match("easy", "Match each function to its type.", ["$x^4-1$", "$x^3-x$", "$x^3+x^2$"], ["even", "odd", "neither"], [0, 1, 2]));
  q.push(mc("medium", "Classify $f(x)=x^4-3x^2+1$:", ["even", "odd", "neither", "linear"], 0));
  q.push(mc("medium", "Classify $f(x)=x^3-4x$:", ["odd", "even", "neither", "linear"], 0));
  q.push(mc("medium", "A polynomial with 4 turning points has minimum degree:", ["5", "4", "6", "3"], 0));
  q.push(mc("medium", "A degree-4 polynomial has at most how many zeros?", ["4", "3", "5", "8"], 0));
  q.push(mc("medium", "Classify $f(x)=x^5+x^2$:", ["neither", "even", "odd", "linear"], 0));
  q.push(mc("medium", "A cubic has at most how many turning points?", ["2", "3", "1", "4"], 0));
  q.push(ms("medium", "$x^4-3x^2+1$:", ["only even powers", "$f(-x)=f(x)$", "even", "odd"], [0, 1, 2]));
  q.push(ms("medium", "Minimum degree from turning points:", ["turning pts $\\le n-1$", "4 turning pts → $n\\ge5$", "so degree 5", "degree 4"], [0, 1, 2]));
  q.push(ms("medium", "$x^3-4x$:", ["only odd powers", "$f(-x)=-f(x)$", "odd", "even"], [0, 1, 2]));
  q.push(ms("medium", "Neither even nor odd:", ["mixed power parities", "e.g. $x^3+x^2$", "fails both tests", "is even"], [0, 1, 2]));
  q.push(tf("medium", "$x^4-3x^2+1$ is even.", true));
  q.push(tf("medium", "A polynomial with 4 turning points can be degree 4.", false));
  q.push(tf("medium", "$x^3-4x$ is odd.", true));
  q.push(fill("medium", "Type of $x^6-x^2$ (even/odd/neither).", ["even"]));
  q.push(fill("medium", "Minimum degree with 5 turning points.", ["6"]));
  q.push(fill("medium", "Type of $x^5-x$ (even/odd/neither).", ["odd"]));
  q.push(num("medium", "Minimum degree with 4 turning points.", 5, 0));
  q.push(num("medium", "Max turning points of a degree-6 polynomial.", 5, 0));
  q.push(num("medium", "Degree if the 5th differences are constant.", 5, 0));
  q.push(match("medium", "Match each.", ["degree 5: max turning pts", "degree 4: max zeros", "3rd diff constant: degree"], ["4", "4", "3"], [0, 1, 2]));
  q.push(mc("hard", "A degree-6 even polynomial is symmetric about:", ["the y-axis", "the origin", "the x-axis", "$y=x$"], 0));
  q.push(mc("hard", "A degree-3 polynomial with 3 distinct zeros has how many turning points?", ["2", "3", "1", "0"], 0));
  q.push(mc("hard", "The 4th differences are constant and nonzero. Degree:", ["4", "3", "5", "2"], 0));
  q.push(mc("hard", "$f(x)=x^5-x^3$ is:", ["odd", "even", "neither", "linear"], 0));
  q.push(mc("hard", "A degree-4 polynomial has at most how many real zeros?", ["4", "3", "5", "2"], 0));
  q.push(ms("hard", "Even-degree symmetry:", ["an even function → y-axis", "not all even-degree are even functions", "need only even powers", "always y-axis"], [0, 1, 2]));
  q.push(ms("hard", "Turning points of a cubic with 3 distinct zeros:", ["2 turning points", "one local max, one local min", "$\\le n-1=2$", "3"], [0, 1, 2]));
  q.push(ms("hard", "Reading finite differences:", ["$n$-th constant → degree $n$", "build a difference table", "stop when constant", "1st constant → degree 2"], [0, 1, 2]));
  q.push(ms("hard", "Classifying $x^5-x^3$:", ["all odd powers", "$f(-x)=-f(x)$", "odd", "even"], [0, 1, 2]));
  q.push(tf("hard", "A degree-3 polynomial with 3 distinct real zeros has 2 turning points.", true));
  q.push(tf("hard", "$x^5-x^3$ is an odd function.", true));
  q.push(tf("hard", "Every even-degree polynomial is an even function.", false));
  q.push(fill("hard", "Symmetry of an even function.", ["y-axis"]));
  q.push(fill("hard", "Turning points of a cubic with 3 distinct zeros.", ["2"]));
  q.push(fill("hard", "Type of $x^5-x^3$ (even/odd/neither).", ["odd"]));
  q.push(num("hard", "Max real zeros of a degree-4 polynomial.", 4, 0));
  q.push(num("hard", "Turning points of a degree-3 polynomial with 3 distinct zeros.", 2, 0));
  q.push(num("hard", "Degree if the 4th differences are constant.", 4, 0));
  q.push(order("hard", "Order the steps to find a polynomial's degree from a table.", ["Build the difference table", "Compute successive differences", "Find where the differences become constant", "That level $n$ is the degree"]));
  q.push(match("hard", "Match each to its value.", ["max turning pts, degree 7", "max zeros, degree 5", "degree if 6th diff constant"], ["6", "5", "6"], [0, 1, 2]));
  return q;
}

// ── 1.3 Equations & Graphs of Polynomial Functions ───────────
function g13() {
  const q = [];
  q.push(mc("easy", "Zeros of $(x-3)(x+1)$:", ["$3,-1$", "$-3,1$", "$3,1$", "$-3,-1$"], 0));
  q.push(mc("easy", "Zero of $(x-5)$:", ["$5$", "$-5$", "$0$", "$\\tfrac15$"], 0));
  q.push(mc("easy", "At a zero of even multiplicity the graph:", ["touches", "crosses", "disappears", "is vertical"], 0));
  q.push(mc("easy", "At a zero of odd multiplicity the graph:", ["crosses", "touches", "disappears", "is vertical"], 0));
  q.push(mc("easy", "The y-intercept is found by:", ["setting $x=0$", "setting $y=0$", "factoring", "the degree"], 0));
  q.push(mc("easy", "Zeros of $x(x-2)(x+4)$:", ["$0,2,-4$", "$0,-2,4$", "$2,4$", "$0$"], 0));
  q.push(ms("easy", "Factored form gives:", ["zeros from the factors", "multiplicity from the exponents", "$a$ from a point", "the degree from the constant"], [0, 1, 2]));
  q.push(ms("easy", "Multiplicity:", ["odd → cross", "even → touch", "is the factor's exponent", "always cross"], [0, 1, 2]));
  q.push(ms("easy", "y-intercept:", ["set $x=0$", "evaluate $f(0)$", "multiply the constants", "set $y=0$"], [0, 1, 2]));
  q.push(ms("easy", "Building an equation:", ["use the zeros as factors", "$y=a(x-r_1)(x-r_2)\\cdots$", "find $a$ from a point", "ignore $a$"], [0, 1, 2]));
  q.push(tf("easy", "$(x-2)^2$ touches the x-axis at 2.", true));
  q.push(tf("easy", "$(x-2)^3$ touches (does not cross) at 2.", false));
  q.push(tf("easy", "The y-intercept of $(x-1)(x+1)$ is $-1$.", true));
  q.push(fill("easy", "Zeros of $(x-4)(x+2)$.", ["4,-2", "-2,4"]));
  q.push(fill("easy", "y-intercept of $(x-2)(x+3)$.", ["-6"]));
  q.push(fill("easy", "Write a polynomial with zeros 1 and $-3$.", ["a(x-1)(x+3)", "(x-1)(x+3)"]));
  q.push(num("easy", "y-intercept of $(x-1)(x-2)(x-3)$.", -6, 0));
  q.push(num("easy", "Number of distinct zeros of $(x-1)(x+1)(x-2)$.", 3, 0));
  q.push(num("easy", "Larger zero of $(x-5)(x+2)$.", 5, 0));
  q.push(match("easy", "Match each to its zeros.", ["$(x-3)(x+1)$", "$x(x-2)$", "$(x+4)(x-1)$"], ["$3,-1$", "$0,2$", "$-4,1$"], [0, 1, 2]));
  q.push(mc("medium", "Behaviour at $x=2$ of $(x-2)^2(x+1)$:", ["touch", "cross", "both", "vertical"], 0));
  q.push(mc("medium", "y-intercept of $(x-1)(x+2)(x-3)$:", ["6", "-6", "1", "-1"], 0));
  q.push(mc("medium", "A cubic with zeros $1,2,3$ through $(0,12)$: $a=$", ["-2", "2", "6", "-6"], 0));
  q.push(mc("medium", "Zeros & behaviour of $(x-4)(x+2)^2$:", ["4 cross, $-2$ touch", "both cross", "both touch", "4 touch"], 0));
  q.push(mc("medium", "A cubic with zeros $-1,0,2$:", ["$x(x+1)(x-2)$", "$x(x-1)(x+2)$", "$(x+1)(x-2)$", "$x(x+1)(x+2)$"], 0));
  q.push(mc("medium", "At $x=-1$ of $(x+1)^3$:", ["crosses (flat)", "touches", "vertical", "jumps"], 0));
  q.push(ms("medium", "$(x-2)^2(x+1)$:", ["$x=2$ mult 2 → touch", "$x=-1$ mult 1 → cross", "degree 3", "$x=2$ cross"], [0, 1, 2]));
  q.push(ms("medium", "Finding $a$:", ["substitute the point", "solve for $a$", "$a=-2$ here", "$a=1$ always"], [0, 1, 2]));
  q.push(ms("medium", "y-intercept:", ["$f(0)$", "$(-1)(2)(-3)=6$", "product of the constants", "$=0$"], [0, 1, 2]));
  q.push(ms("medium", "Multiplicity 3:", ["odd → crosses", "with a flat inflection", "locally like $x^3$", "touches"], [0, 1, 2]));
  q.push(tf("medium", "$(x-2)^2(x+1)$ touches at $x=2$.", true));
  q.push(tf("medium", "A cubic with zeros $1,2,3$ through $(0,12)$ has $a=-2$.", true));
  q.push(tf("medium", "$(x+1)^3$ touches (does not cross) at $-1$.", false));
  q.push(fill("medium", "Behaviour at $x=3$ of $(x-3)^2(x+1)$.", ["touch", "touches"]));
  q.push(fill("medium", "y-intercept of $(x-1)(x+2)(x-3)$.", ["6"]));
  q.push(fill("medium", "$a$ for a cubic with zeros $1,2,3$ through $(0,12)$.", ["-2"]));
  q.push(num("medium", "y-intercept of $(x-2)(x+1)(x-4)$.", 8, 0));
  q.push(num("medium", "$a$ for a quadratic with zeros $1,5$ through $(0,10)$.", 2, 0));
  q.push(num("medium", "Number of distinct zeros of $(x-1)^2(x+3)$.", 2, 0));
  q.push(match("medium", "Match each behaviour at the zero.", ["$(x-2)^2$", "$(x-2)^3$", "$(x-2)$"], ["touch", "cross (flat)", "cross"], [0, 1, 2]));
  q.push(mc("hard", "A quartic with zeros $-2$ (double), $1$, $3$ through $(0,12)$: $a=$", ["1", "2", "-1", "12"], 0));
  q.push(mc("hard", "Touch at $x=1$, cross at $x=-2$ and $x=3$ — minimum form:", ["$a(x-1)^2(x+2)(x-3)$", "$a(x-1)(x+2)(x-3)$", "$a(x-1)^2(x+2)^2$", "$a(x-1)(x+2)^2$"], 0));
  q.push(mc("hard", "Sign of $(x-1)(x+2)(x-3)$ for $x>3$:", ["positive", "negative", "zero", "undefined"], 0));
  q.push(mc("hard", "End behaviour of $(x+1)^2(x-2)$:", ["down–up", "up–up", "down–down", "up–down"], 0));
  q.push(mc("hard", "Zeros (with multiplicity) of $(x-1)^2(x+2)^3$ total:", ["5", "2", "3", "4"], 0));
  q.push(ms("hard", "Quartic from zeros & a point:", ["write factors with multiplicities", "substitute $(0,12)$", "solve for $a$", "$a=1$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Touch vs cross when building:", ["touch → even multiplicity", "cross → odd multiplicity", "$(x-1)^2$ for a touch", "$(x-1)$ for a touch"], [0, 1, 2]));
  q.push(ms("hard", "Sign analysis:", ["test a point in each interval", "for $x>3$ all factors positive", "$f>0$ there", "$f<0$ there"], [0, 1, 2]));
  q.push(ms("hard", "End behaviour of a product:", ["multiply the leading terms", "$(x+1)^2(x-2)\\to x^3$", "degree 3, $a>0$ → down–up", "degree 4"], [0, 1, 2]));
  q.push(tf("hard", "$(x+1)^2(x-2)$ has end behaviour down–up.", true));
  q.push(tf("hard", "To make the graph touch at $x=1$, use $(x-1)^2$.", true));
  q.push(tf("hard", "$(x-1)(x+2)(x-3)$ is negative for $x>3$.", false));
  q.push(fill("hard", "$a$ for $(x+2)^2(x-1)(x-3)$ through $(0,12)$.", ["1"]));
  q.push(fill("hard", "Multiplicity needed at $x=1$ to touch.", ["2", "even"]));
  q.push(fill("hard", "End behaviour of $(x+1)^2(x-2)$.", ["down-up", "down–up"]));
  q.push(num("hard", "$a$ for $(x+2)^2(x-1)(x-3)$ through $(0,12)$.", 1, 0));
  q.push(num("hard", "Total zeros (with multiplicity) of $(x-1)^2(x+2)^3$.", 5, 0));
  q.push(num("hard", "Degree of $(x+1)^2(x-2)$.", 3, 0));
  q.push(order("hard", "Order the steps to build a quartic with zeros $-2$ (double), $1$, $3$ through $(0,12)$.", ["Write $a(x+2)^2(x-1)(x-3)$", "Substitute $(0,12)$: $a(4)(-1)(-3)=12$", "$12a=12$", "$a=1$"]));
  q.push(match("hard", "Match each to its behaviour at the zero.", ["$(x-1)^2$", "$(x-1)^3$", "$(x-1)$"], ["touch", "cross with flat", "cross"], [0, 1, 2]));
  return q;
}

// ── 1.4 Transformations of Functions ─────────────────────────
function g14() {
  const q = [];
  q.push(mc("easy", "$y=x^3+3$ shifts:", ["up 3", "down 3", "right 3", "left 3"], 0));
  q.push(mc("easy", "$y=(x-2)^3$ shifts:", ["right 2", "left 2", "up 2", "down 2"], 0));
  q.push(mc("easy", "$y=-x^3$ is:", ["a reflection in the x-axis", "a shift up", "a stretch", "a shift right"], 0));
  q.push(mc("easy", "$y=2x^3$ is:", ["a vertical stretch by 2", "a shift up 2", "a reflection", "a shift right"], 0));
  q.push(mc("easy", "In $a(x-d)^n+c$, $c$ is the:", ["vertical shift", "horizontal shift", "stretch", "reflection"], 0));
  q.push(mc("easy", "$y=(x+4)^3$ shifts:", ["left 4", "right 4", "up 4", "down 4"], 0));
  q.push(ms("easy", "The parameters:", ["$a$ stretch/reflect", "$d$ horizontal", "$c$ vertical", "$a$ horizontal"], [0, 1, 2]));
  q.push(ms("easy", "$y=-2(x-1)^3$:", ["reflect", "stretch by 2", "right 1", "left 1"], [0, 1, 2]));
  q.push(ms("easy", "Vertical shift:", ["$+c$ up", "$-c$ down", "changes $y$", "changes $x$"], [0, 1, 2]));
  q.push(ms("easy", "Reflections:", ["$a<0$ over the x-axis", "$k<0$ over the y-axis", "flip the graph", "shift it"], [0, 1, 2]));
  q.push(tf("easy", "$y=x^3+3$ shifts up 3.", true));
  q.push(tf("easy", "$y=(x-2)^3$ shifts left 2.", false));
  q.push(tf("easy", "$y=-x^4$ opens down.", true));
  q.push(fill("easy", "Describe the shift in $y=(x-5)^3$.", ["right 5"]));
  q.push(fill("easy", "Describe the shift in $y=x^4+2$.", ["up 2"]));
  q.push(fill("easy", "What does $a=-1$ do?", ["reflect in x-axis", "reflection"]));
  q.push(num("easy", "Vertical shift $c$ in $y=x^3-7$.", -7, 0));
  q.push(num("easy", "Horizontal shift in $y=(x-6)^3$ (right is +).", 6, 0));
  q.push(num("easy", "Stretch factor in $y=5x^3$.", 5, 0));
  q.push(match("easy", "Match each parameter.", ["$a$", "$d$", "$c$"], ["stretch/reflect", "horizontal shift", "vertical shift"], [0, 1, 2]));
  q.push(mc("medium", "Describe $y=2(x-1)^3+3$:", ["stretch 2, right 1, up 3", "stretch 2, left 1, up 3", "reflect, right 1, up 3", "stretch 2, right 1, down 3"], 0));
  q.push(mc("medium", "Describe $y=-x^4$:", ["reflect in the x-axis", "shift up", "stretch", "shift right"], 0));
  q.push(mc("medium", "$(1,1)$ on $y=x^3$ maps under $y=(x-2)^3+4$ to:", ["$(3,5)$", "$(-1,5)$", "$(3,-3)$", "$(-1,-3)$"], 0));
  q.push(mc("medium", "Write $y=x^3$ right 4, up 1:", ["$(x-4)^3+1$", "$(x+4)^3+1$", "$(x-4)^3-1$", "$x^3+5$"], 0));
  q.push(mc("medium", "Describe $y=-3x^4+2$:", ["reflect, stretch 3, up 2", "stretch 3, up 2", "reflect, up 2", "reflect, stretch 3, down 2"], 0));
  q.push(mc("medium", "$k=2$ in $y=(2x)^3$ gives:", ["horizontal compression by $\\tfrac12$", "stretch by 2", "shift right 2", "reflection"], 0));
  q.push(ms("medium", "$y=2(x-1)^3+3$:", ["$a=2$", "right 1", "up 3", "left 1"], [0, 1, 2]));
  q.push(ms("medium", "Mapping a point:", ["apply each transformation", "$(1,1)\\to(3,5)$", "$x+2,\\ y+4$", "ignore the shifts"], [0, 1, 2]));
  q.push(ms("medium", "Writing from a description:", ["$d$ for horizontal", "$c$ for vertical", "$a$ for stretch", "ignore $a$"], [0, 1, 2]));
  q.push(ms("medium", "Reflection & stretch:", ["$a=-3$ reflects", "and stretches by 3", "over the x-axis", "over the y-axis"], [0, 1, 2]));
  q.push(tf("medium", "$y=2(x-1)^3+3$ is centred at $(1,3)$.", true));
  q.push(tf("medium", "$(1,1)$ on $y=x^3$ maps to $(3,5)$ under $y=(x-2)^3+4$.", true));
  q.push(tf("medium", "$y=(2x)^3$ stretches horizontally by 2.", false));
  q.push(fill("medium", "Centre of $y=(x-5)^3+2$.", ["(5,2)", "5,2"]));
  q.push(fill("medium", "Image of $(1,1)$ under $y=(x-2)^3+4$.", ["(3,5)", "3,5"]));
  q.push(fill("medium", "Equation: $x^4$ reflected, left 1, down 2.", ["-(x+1)^4-2"]));
  q.push(num("medium", "New $x$ of $(1,1)$ under $y=(x-3)^3$.", 4, 0));
  q.push(num("medium", "Vertical shift of $y=2(x-1)^3+3$.", 3, 0));
  q.push(num("medium", "Stretch factor of $y=-3x^4+2$.", 3, 0));
  q.push(match("medium", "Match each to its description.", ["$2(x-1)^3+3$", "$-x^4$", "$(x+3)^3-1$"], ["stretch 2, right 1, up 3", "reflect in x-axis", "left 3, down 1"], [0, 1, 2]));
  q.push(mc("hard", "Fully describe $y=-2(x+1)^3-3$:", ["reflect, stretch 2, left 1, down 3", "stretch 2, left 1, down 3", "reflect, stretch 2, right 1, down 3", "reflect, left 1, up 3"], 0));
  q.push(mc("hard", "$(2,8)$ on $y=x^3$ maps under $y=-x^3$ to:", ["$(2,-8)$", "$(-2,8)$", "$(2,8)$", "$(-2,-8)$"], 0));
  q.push(mc("hard", "Minimum point of $y=(x-1)^4+2$:", ["$(1,2)$", "$(1,-2)$", "$(-1,2)$", "$(2,1)$"], 0));
  q.push(mc("hard", "$y=x^3$ stretched by 3 and down 4:", ["$3x^3-4$", "$3(x-4)^3$", "$3x^3+4$", "$x^3-12$"], 0));
  q.push(mc("hard", "$y=f(-x)$ reflects $y=f(x)$ in:", ["the y-axis", "the x-axis", "$y=x$", "the origin"], 0));
  q.push(ms("hard", "$y=-2(x+1)^3-3$:", ["$a=-2$ reflect & stretch", "$d=-1$ left 1", "$c=-3$ down 3", "right 1"], [0, 1, 2]));
  q.push(ms("hard", "$(2,8)$ under $y=-x^3$:", ["$y\\to-y$", "$(2,-8)$", "reflect in the x-axis", "$(-2,8)$"], [0, 1, 2]));
  q.push(ms("hard", "Minimum of $(x-1)^4+2$:", ["even power → minimum at the vertex", "at $x=1$", "value 2", "at $x=-1$"], [0, 1, 2]));
  q.push(ms("hard", "Building from a description:", ["apply $a$ first", "then the shifts", "$y=3x^3-4$ for stretch 3, down 4", "ignore order"], [0, 1, 2]));
  q.push(tf("hard", "$y=-2(x+1)^3-3$ is reflected, stretched by 2, left 1, down 3.", true));
  q.push(tf("hard", "$(2,8)$ on $y=x^3$ maps to $(2,-8)$ on $y=-x^3$.", true));
  q.push(tf("hard", "$y=(x-1)^4+2$ has a maximum at $(1,2)$.", false));
  q.push(fill("hard", "Image of $(2,8)$ under $y=-x^3$.", ["(2,-8)", "2,-8"]));
  q.push(fill("hard", "Minimum point of $y=(x-1)^4+2$.", ["(1,2)", "1,2"]));
  q.push(fill("hard", "Equation: $x^3$ stretched by 3, down 4.", ["3x^3-4"]));
  q.push(num("hard", "$y$-value of the minimum of $y=(x-1)^4+2$.", 2, 0));
  q.push(num("hard", "$y$ of the image of $(2,8)$ under $y=-x^3$.", -8, 0));
  q.push(num("hard", "Vertical stretch factor of $y=-2(x+1)^3-3$.", 2, 0));
  q.push(order("hard", "Order the transformations to graph $y=-2(x+1)^3-3$.", ["Stretch vertically by 2", "Reflect in the x-axis", "Shift left 1", "Shift down 3"]));
  q.push(match("hard", "Match each to its result.", ["min of $(x-1)^4+2$", "image of $(2,8)$ under $-x^3$", "centre of $(x+1)^3-3$"], ["$(1,2)$", "$(2,-8)$", "$(-1,-3)$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "1.1", gen: g11 },
  { code: "1.2", gen: g12 },
  { code: "1.3", gen: g13 },
  { code: "1.4", gen: g14 },
];
