// MHF4U Unit 2 — Polynomial Equations & Inequalities: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 2.1 Dividing Polynomials ─────────────────────────────────
function g21() {
  const q = [];
  q.push(mc("easy", "$(x^2+5x+6)\\div(x+2)$ gives quotient:", ["$x+3$", "$x+2$", "$x+6$", "$x-3$"], 0));
  q.push(mc("easy", "$(x^2+7x+10)\\div(x+5)$ gives quotient:", ["$x+2$", "$x+5$", "$x+7$", "$x-2$"], 0));
  q.push(mc("easy", "Synthetic division can be used when the divisor is:", ["linear, $x-a$", "quadratic", "any polynomial", "a constant"], 0));
  q.push(mc("easy", "A remainder of 0 means the divisor is:", ["a factor", "the quotient", "linear", "negative"], 0));
  q.push(mc("easy", "The division statement is:", ["$P=DQ+R$", "$P=D+Q+R$", "$P=DQR$", "$P=Q-R$"], 0));
  q.push(mc("easy", "The remainder's degree must be:", ["less than the divisor's", "equal to the divisor's", "more than the divisor's", "zero"], 0));
  q.push(ms("easy", "Long division steps:", ["divide leading terms", "multiply back", "subtract", "always stop after one step"], [0, 1, 2]));
  q.push(ms("easy", "Synthetic division (by $x-a$):", ["list the coefficients", "bring down the first", "multiply by $a$ and add", "use the constant only"], [0, 1, 2]));
  q.push(ms("easy", "The division statement $P=DQ+R$:", ["$D$ is the divisor", "$Q$ is the quotient", "$R$ is the remainder", "$R$ is the divisor"], [0, 1, 2]));
  q.push(ms("easy", "If $R=0$:", ["$D$ is a factor", "$P=DQ$", "the division is exact", "$R$ is the quotient"], [0, 1, 2]));
  q.push(tf("easy", "If a division has remainder 0, the divisor is a factor.", true));
  q.push(tf("easy", "Synthetic division works for any divisor.", false));
  q.push(tf("easy", "The remainder can have higher degree than the divisor.", false));
  q.push(fill("easy", "Quotient of $(x^2+6x+8)\\div(x+2)$.", ["x+4"]));
  q.push(fill("easy", "Quotient of $(x^2+x-6)\\div(x-2)$.", ["x+3"]));
  q.push(fill("easy", "Remainder of $(x^2+5x+6)\\div(x+2)$.", ["0"]));
  q.push(num("easy", "Remainder of $(x^2+5x+6)\\div(x+2)$.", 0, 0));
  q.push(num("easy", "Remainder of $(x^2+4x+1)\\div(x+1)$.", -2, 0));
  q.push(num("easy", "Degree of the quotient of a cubic divided by a linear.", 2, 0));
  q.push(match("easy", "Match each to its quotient.", ["$(x^2+5x+6)\\div(x+2)$", "$(x^2+7x+10)\\div(x+5)$", "$(x^2+x-6)\\div(x-2)$"], ["$x+3$", "$x+2$", "$x+3$"], [0, 1, 2]));
  q.push(mc("medium", "$(x^3-1)\\div(x-1)$ gives quotient:", ["$x^2+x+1$", "$x^2-x+1$", "$x^2+1$", "$x^2-1$"], 0));
  q.push(mc("medium", "$(x^3-4x^2+x+6)\\div(x-2)$ gives quotient:", ["$x^2-2x-3$", "$x^2-2x+3$", "$x^2+2x-3$", "$x^2-6x$"], 0));
  q.push(mc("medium", "$(x^2+4x+1)\\div(x+1)$ gives remainder:", ["$-2$", "$0$", "$2$", "$1$"], 0));
  q.push(mc("medium", "$(x^3-8)\\div(x-2)$ gives quotient:", ["$x^2+2x+4$", "$x^2-2x+4$", "$x^2+4$", "$x^2-4$"], 0));
  q.push(mc("medium", "Division statement for $(x^2+3x+5)\\div(x+1)$:", ["$(x+1)(x+2)+3$", "$(x+1)(x+2)$", "$(x+1)(x+3)+2$", "$(x+1)(x+2)-3$"], 0));
  q.push(mc("medium", "$(2x^2+7x+3)\\div(x+3)$ gives quotient:", ["$2x+1$", "$2x+3$", "$x+1$", "$2x-1$"], 0));
  q.push(ms("medium", "$(x^3-1)\\div(x-1)$:", ["coefficients $1,0,0,-1$", "root $1$", "quotient $x^2+x+1$", "remainder $-1$"], [0, 1, 2]));
  q.push(ms("medium", "Checking $(x^2+3x+5)\\div(x+1)$:", ["quotient $x+2$", "remainder $3$", "$(x+1)(x+2)+3$", "remainder $0$"], [0, 1, 2]));
  q.push(ms("medium", "Reading a synthetic-division row:", ["last number is the remainder", "others are quotient coefficients", "degree drops by 1", "first is the remainder"], [0, 1, 2]));
  q.push(ms("medium", "$(x^3-8)\\div(x-2)$:", ["root $2$", "quotient $x^2+2x+4$", "remainder $0$", "remainder $8$"], [0, 1, 2]));
  q.push(tf("medium", "$(x^3-1)\\div(x-1)=x^2+x+1$ with remainder 0.", true));
  q.push(tf("medium", "$(x^2+4x+1)\\div(x+1)$ has remainder $-2$.", true));
  q.push(tf("medium", "$(x^3-8)\\div(x-2)$ has remainder $8$.", false));
  q.push(fill("medium", "Quotient of $(x^3-1)\\div(x-1)$.", ["x^2+x+1"]));
  q.push(fill("medium", "Remainder of $(x^2+4x+1)\\div(x+1)$.", ["-2"]));
  q.push(fill("medium", "Quotient of $(x^3-8)\\div(x-2)$.", ["x^2+2x+4"]));
  q.push(num("medium", "Remainder of $(x^3-1)\\div(x-1)$.", 0, 0));
  q.push(num("medium", "Remainder of $(x^2+1)\\div(x+1)$.", 2, 0));
  q.push(num("medium", "Remainder of $(x^3+2x^2-5)\\div(x-1)$.", -2, 0));
  q.push(match("medium", "Match each to its remainder.", ["$(x^2+5x+6)\\div(x+2)$", "$(x^2+4x+1)\\div(x+1)$", "$(x^2+1)\\div(x+1)$"], ["$0$", "$-2$", "$2$"], [0, 1, 2]));
  q.push(mc("hard", "$(x^3-2x^2-5x+6)\\div(x-1)$ gives quotient:", ["$x^2-x-6$", "$x^2-x+6$", "$x^2+x-6$", "$x^2-6$"], 0));
  q.push(mc("hard", "$(x^3+2x^2-5)\\div(x-1)$ gives:", ["$x^2+3x+3$, R $-2$", "$x^2+3x+3$, R $0$", "$x^2+2x$, R $-5$", "$x^2+3x$, R $-5$"], 0));
  q.push(mc("hard", "If $(x^3+kx-2)\\div(x-1)$ has remainder 0, then $k=$", ["1", "2", "-1", "0"], 0));
  q.push(mc("hard", "$(x^4-1)\\div(x-1)$ gives quotient:", ["$x^3+x^2+x+1$", "$x^3-x^2+x-1$", "$x^3+1$", "$x^3-1$"], 0));
  q.push(mc("hard", "Dividing a degree-4 by a degree-2 gives a quotient of degree:", ["2", "1", "3", "4"], 0));
  q.push(ms("hard", "$(x^3-2x^2-5x+6)\\div(x-1)$:", ["root $1$", "coefficients $1,-2,-5,6$", "quotient $x^2-x-6$", "remainder $6$"], [0, 1, 2]));
  q.push(ms("hard", "Remainder 0 from division:", ["the divisor is a factor", "links to the Factor Theorem", "$P(a)=0$ for divisor $x-a$", "the quotient is 0"], [0, 1, 2]));
  q.push(ms("hard", "$(x^3+2x^2-5)\\div(x-1)$:", ["use $0$ for the missing $x$ term", "coefficients $1,2,0,-5$", "remainder $-2$", "coefficients $1,2,-5$"], [0, 1, 2]));
  q.push(ms("hard", "Degree bookkeeping:", ["quotient degree = dividend − divisor", "remainder degree < divisor", "cubic ÷ linear → quadratic", "cubic ÷ linear → cubic"], [0, 1, 2]));
  q.push(tf("hard", "$(x^3-2x^2-5x+6)\\div(x-1)$ has remainder 0.", true));
  q.push(tf("hard", "Missing terms are entered as 0 coefficients in synthetic division.", true));
  q.push(tf("hard", "$(x^4-1)\\div(x-1)$ has a nonzero remainder.", false));
  q.push(fill("hard", "Quotient of $(x^3-2x^2-5x+6)\\div(x-1)$.", ["x^2-x-6"]));
  q.push(fill("hard", "$k$ so $(x^3+kx-2)\\div(x-1)$ has remainder 0.", ["1"]));
  q.push(fill("hard", "Quotient of $(x^4-1)\\div(x-1)$.", ["x^3+x^2+x+1"]));
  q.push(num("hard", "Remainder of $(x^3-2x^2-5x+6)\\div(x-1)$.", 0, 0));
  q.push(num("hard", "Remainder of $(x^4-1)\\div(x-1)$.", 0, 0));
  q.push(num("hard", "Degree of the quotient of a degree-4 ÷ degree-2.", 2, 0));
  q.push(order("hard", "Order the synthetic-division steps for $(x^3-4x^2+x+6)\\div(x-2)$.", ["Write coefficients $1,-4,1,6$ and root $2$", "Bring down $1$", "Multiply by 2 and add down the row", "Read quotient $x^2-2x-3$, R $0$"]));
  q.push(match("hard", "Match each division to its quotient.", ["$(x^3-1)\\div(x-1)$", "$(x^3-8)\\div(x-2)$", "$(x^4-1)\\div(x-1)$"], ["$x^2+x+1$", "$x^2+2x+4$", "$x^3+x^2+x+1$"], [0, 1, 2]));
  return q;
}

// ── 2.2 Remainder & Factor Theorems ──────────────────────────
function g22() {
  const q = [];
  q.push(mc("easy", "The remainder of $P(x)\\div(x-a)$ is:", ["$P(a)$", "$P(0)$", "$P(-a)$", "$a$"], 0));
  q.push(mc("easy", "$x-a$ is a factor of $P(x)$ when:", ["$P(a)=0$", "$P(0)=0$", "$P(a)=1$", "$a=0$"], 0));
  q.push(mc("easy", "Remainder of $x^3-2x+1$ divided by $x-2$:", ["5", "0", "1", "7"], 0));
  q.push(mc("easy", "Is $x-1$ a factor of $x^3-1$?", ["yes", "no", "only if $x>0$", "cannot tell"], 0));
  q.push(mc("easy", "$P(1)=0$ means:", ["$x-1$ is a factor", "$x+1$ is a factor", "$P$ has no zeros", "$P(0)=1$"], 0));
  q.push(mc("easy", "To use the Remainder Theorem you compute:", ["$P(a)$", "$P'(a)$", "the quotient", "the leading term"], 0));
  q.push(ms("easy", "Remainder Theorem:", ["remainder $=P(a)$", "for divisor $x-a$", "no full division needed", "remainder $=P(0)$"], [0, 1, 2]));
  q.push(ms("easy", "Factor Theorem:", ["$x-a$ factor $\\iff P(a)=0$", "tests divisibility", "a special case of the Remainder Theorem", "needs long division"], [0, 1, 2]));
  q.push(ms("easy", "Rational Root Theorem:", ["candidate zeros $\\tfrac{p}{q}$", "$p\\mid$ constant", "$q\\mid$ leading coefficient", "only integer zeros"], [0, 1, 2]));
  q.push(ms("easy", "Testing factors:", ["evaluate $P(a)$", "$=0$ → factor", "$\\ne0$ → not a factor", "always a factor"], [0, 1, 2]));
  q.push(tf("easy", "The remainder of $P(x)\\div(x-a)$ equals $P(a)$.", true));
  q.push(tf("easy", "$x-a$ is a factor exactly when $P(a)=0$.", true));
  q.push(tf("easy", "$P(1)=0$ means $x+1$ is a factor.", false));
  q.push(fill("easy", "Remainder of $x^3-2x+1$ divided by $x-2$.", ["5"]));
  q.push(fill("easy", "Is $x-1$ a factor of $x^3-1$? (yes/no)", ["yes"]));
  q.push(fill("easy", "Is $x+2$ a factor of $x^3+8$? (yes/no)", ["yes"]));
  q.push(num("easy", "Remainder of $x^3-2x+1$ divided by $x-2$.", 5, 0));
  q.push(num("easy", "Remainder of $x^3+1$ divided by $x-1$.", 2, 0));
  q.push(num("easy", "$P(1)$ for $P(x)=x^3-1$.", 0, 0));
  q.push(match("easy", "Match each to its remainder (divide by $x-1$).", ["$x^3-1$", "$x^3+1$", "$x^3-2x+1$"], ["$0$", "$2$", "$0$"], [0, 1, 2]));
  q.push(mc("medium", "Remainder of $x^3+1$ divided by $x-1$:", ["2", "0", "1", "-1"], 0));
  q.push(mc("medium", "Is $x+1$ a factor of $x^3+x^2-x-1$?", ["yes", "no", "only if $x<0$", "cannot tell"], 0));
  q.push(mc("medium", "$k$ so $x-1$ is a factor of $x^3+kx-2$:", ["1", "2", "-1", "0"], 0));
  q.push(mc("medium", "$k$ so $x+1$ is a factor of $x^3+kx+4$:", ["3", "-3", "4", "-4"], 0));
  q.push(mc("medium", "A rational zero of $x^3-2x^2-x+2$:", ["1", "3", "4", "-3"], 0));
  q.push(mc("medium", "Remainder of $2x^3-x+5$ divided by $x+1$:", ["4", "6", "2", "-4"], 0));
  q.push(ms("medium", "Finding $k$ for a factor:", ["set $P(\\text{root})=0$", "solve for $k$", "use the Factor Theorem", "use the quotient"], [0, 1, 2]));
  q.push(ms("medium", "Is $x+1$ a factor of $x^3+x^2-x-1$:", ["compute $P(-1)$", "$P(-1)=0$", "so yes", "compute $P(1)$"], [0, 1, 2]));
  q.push(ms("medium", "Rational-root candidates of $x^3-2x^2-x+2$:", ["$\\pm1$", "$\\pm2$", "divisors of 2", "$\\pm3$"], [0, 1, 2]));
  q.push(ms("medium", "Remainder Theorem in practice:", ["faster than dividing", "just one evaluation", "gives remainder directly", "needs the quotient"], [0, 1, 2]));
  q.push(tf("medium", "$x-1$ is a factor of $x^3+kx-2$ when $k=1$.", true));
  q.push(tf("medium", "A rational zero of $x^3-2x^2-x+2$ is $x=1$.", true));
  q.push(tf("medium", "The remainder of $2x^3-x+5$ divided by $x+1$ is $6$.", false));
  q.push(fill("medium", "$k$ so $x+1$ is a factor of $x^3+kx+4$.", ["3"]));
  q.push(fill("medium", "A rational zero of $x^3-x^2-4x+4$.", ["1"]));
  q.push(fill("medium", "Remainder of $2x^3-x+5$ divided by $x+1$.", ["4"]));
  q.push(num("medium", "$k$ so $x-1$ is a factor of $x^3+kx-2$.", 1, 0));
  q.push(num("medium", "$k$ so $x+1$ is a factor of $x^3+kx+4$.", 3, 0));
  q.push(num("medium", "Remainder of $2x^3-x+5$ divided by $x+1$.", 4, 0));
  q.push(match("medium", "Match each to its $k$ (named factor).", ["$x-1\\mid x^3+kx-2$", "$x+1\\mid x^3+kx+4$", "$x-2\\mid x^3-kx+2$"], ["$1$", "$3$", "$5$"], [0, 1, 2]));
  q.push(mc("hard", "$k$ so $x-2$ is a factor of $x^3-kx+2$:", ["5", "3", "-5", "4"], 0));
  q.push(mc("hard", "List the rational-root candidates of $x^3-2x^2-5x+6$:", ["$\\pm1,\\pm2,\\pm3,\\pm6$", "$\\pm1,\\pm2$", "$\\pm1,\\pm6$", "$\\pm2,\\pm3$"], 0));
  q.push(mc("hard", "If $P(x)=x^3+bx+c$ and $P(1)=0,\\ P(-1)=0$, then $b=$", ["$-1$", "$1$", "$0$", "$2$"], 0));
  q.push(mc("hard", "Remainder of $x^4-3x^2+2$ divided by $x-1$:", ["0", "2", "1", "-1"], 0));
  q.push(mc("hard", "After showing $x-1\\mid x^3-2x^2-x+2$, another factor is:", ["$x-2$", "$x-3$", "$x+3$", "$x-4$"], 0));
  q.push(ms("hard", "Finding $k$ for $x-2\\mid x^3-kx+2$:", ["$P(2)=8-2k+2=0$", "$10=2k$", "$k=5$", "$k=3$"], [0, 1, 2]));
  q.push(ms("hard", "Two known zeros $1$ and $-1$:", ["$P(1)=0$ and $P(-1)=0$", "gives two equations", "solve for the unknowns", "needs the quotient only"], [0, 1, 2]));
  q.push(ms("hard", "Full factoring with the theorems:", ["find one zero", "divide it out", "factor the quotient", "skip the division"], [0, 1, 2]));
  q.push(ms("hard", "Rational Root Theorem details:", ["$p\\mid$ constant term", "$q\\mid$ leading coefficient", "candidates are $\\pm\\tfrac{p}{q}$", "only $q=1$"], [0, 1, 2]));
  q.push(tf("hard", "$x-2$ is a factor of $x^3-kx+2$ when $k=5$.", true));
  q.push(tf("hard", "The remainder of $x^4-3x^2+2$ divided by $x-1$ is 0.", true));
  q.push(tf("hard", "$x-1$ and $x-2$ are both factors of $x^3-2x^2-x+2$.", true));
  q.push(fill("hard", "$k$ so $x-2$ is a factor of $x^3-kx+2$.", ["5"]));
  q.push(fill("hard", "Remainder of $x^4-3x^2+2$ divided by $x-1$.", ["0"]));
  q.push(fill("hard", "After $x-1$, a second factor of $x^3-2x^2-x+2$.", ["x-2", "x+1"]));
  q.push(num("hard", "$k$ so $x-2$ is a factor of $x^3-kx+2$.", 5, 0));
  q.push(num("hard", "Remainder of $x^4-3x^2+2$ divided by $x-1$.", 0, 0));
  q.push(num("hard", "Number of rational-root candidates (counting signs) for $x^3+\\,$const $6$, leading $1$.", 8, 0));
  q.push(order("hard", "Order the steps to factor $x^3-2x^2-x+2$ fully.", ["List candidates $\\pm1,\\pm2$", "Find $P(1)=0$", "Divide out $(x-1)$ → $x^2-x-2$", "Factor → $(x-1)(x-2)(x+1)$"]));
  q.push(match("hard", "Match each to its remainder when divided by $x-1$.", ["$x^4-3x^2+2$", "$x^3+1$", "$x^3-2x+1$"], ["$0$", "$2$", "$0$"], [0, 1, 2]));
  return q;
}

// ── 2.3 Solving Polynomial Equations ─────────────────────────
function g23() {
  const q = [];
  q.push(mc("easy", "Solve $x^3-4x=0$:", ["$0,2,-2$", "$0,4,-4$", "$2,-2$", "$0,2$"], 0));
  q.push(mc("easy", "Solve $x(x-3)=0$:", ["$0,3$", "$3$", "$0,-3$", "$-3$"], 0));
  q.push(mc("easy", "First step in solving a polynomial equation:", ["take out a common factor", "graph it", "divide by $x$", "add 1"], 0));
  q.push(mc("easy", "Solve $x^2-9=0$:", ["$3,-3$", "$9,-9$", "$3$", "$0,9$"], 0));
  q.push(mc("easy", "A degree-3 polynomial has how many roots in total?", ["3", "2", "1", "4"], 0));
  q.push(mc("easy", "Solve $x^3=0$:", ["$0$ (triple)", "$0,1$", "no solution", "$1$"], 0));
  q.push(ms("easy", "Strategy:", ["common factor first", "then factor further", "set each factor to 0", "expand everything"], [0, 1, 2]));
  q.push(ms("easy", "Zero product property:", ["if $ab=0$ then $a=0$ or $b=0$", "solve each factor", "gives the roots", "needs the graph"], [0, 1, 2]));
  q.push(ms("easy", "Counting roots:", ["degree $n$ → $n$ roots", "counting multiplicity", "may include complex roots", "always $n-1$"], [0, 1, 2]));
  q.push(ms("easy", "Common factoring:", ["$x^3-4x=x(x^2-4)$", "then $x(x-2)(x+2)$", "roots $0,2,-2$", "roots $2,-2$ only"], [0, 1, 2]));
  q.push(tf("easy", "The first step is usually to remove a common factor.", true));
  q.push(tf("easy", "A degree-3 polynomial has at most 3 roots.", true));
  q.push(tf("easy", "$x^3-4x=0$ has only the roots $2$ and $-2$.", false));
  q.push(fill("easy", "Solve $x^3-4x=0$ (list roots).", ["0,2,-2", "0,-2,2"]));
  q.push(fill("easy", "Solve $x^2-9=0$.", ["3,-3", "-3,3"]));
  q.push(fill("easy", "Solve $x(x-5)=0$.", ["0,5"]));
  q.push(num("easy", "Number of roots of a degree-4 polynomial (with multiplicity).", 4, 0));
  q.push(num("easy", "Largest root of $x^3-4x=0$.", 2, 0));
  q.push(num("easy", "Smallest root of $x^3-4x=0$.", -2, 0));
  q.push(match("easy", "Match each to its roots.", ["$x^3-4x=0$", "$x^2-9=0$", "$x(x-3)=0$"], ["$0,2,-2$", "$3,-3$", "$0,3$"], [0, 1, 2]));
  q.push(mc("medium", "Solve $x^3-2x^2-3x=0$:", ["$0,3,-1$", "$0,-3,1$", "$3,-1$", "$0,3$"], 0));
  q.push(mc("medium", "Solve $x^3+2x^2-x-2=0$ (grouping):", ["$-2,1,-1$", "$2,1,-1$", "$-2,-1$", "$2,-1,1$"], 0));
  q.push(mc("medium", "Solve $x^4-5x^2+4=0$:", ["$\\pm1,\\pm2$", "$\\pm1,\\pm4$", "$1,2$", "$\\pm2$"], 0));
  q.push(mc("medium", "Solve $x^3-7x-6=0$ (with $x=-1$):", ["$-1,3,-2$", "$1,3,2$", "$-1,3,2$", "$-1,-3,2$"], 0));
  q.push(mc("medium", "Solve $x^3-9x=0$:", ["$0,3,-3$", "$0,9,-9$", "$3,-3$", "$0,3$"], 0));
  q.push(mc("medium", "Solve $x^3-x^2-2x=0$:", ["$0,2,-1$", "$0,-2,1$", "$2,-1$", "$0,2$"], 0));
  q.push(ms("medium", "$x^3-2x^2-3x=0$:", ["factor out $x$", "$x(x-3)(x+1)$", "roots $0,3,-1$", "roots $3,-1$ only"], [0, 1, 2]));
  q.push(ms("medium", "Grouping $x^3+2x^2-x-2$:", ["$x^2(x+2)-(x+2)$", "$(x+2)(x^2-1)$", "$(x+2)(x-1)(x+1)$", "$(x+2)(x^2+1)$"], [0, 1, 2]));
  q.push(ms("medium", "$x^4-5x^2+4$:", ["let $u=x^2$", "$(x^2-1)(x^2-4)$", "roots $\\pm1,\\pm2$", "roots $\\pm1$ only"], [0, 1, 2]));
  q.push(ms("medium", "Using a hint zero:", ["confirm $P(\\text{hint})=0$", "divide it out", "factor the quotient", "ignore the hint"], [0, 1, 2]));
  q.push(tf("medium", "$x^3-2x^2-3x=0$ has roots $0,3,-1$.", true));
  q.push(tf("medium", "$x^4-5x^2+4=0$ has roots $\\pm1,\\pm2$.", true));
  q.push(tf("medium", "$x^3+2x^2-x-2=0$ has roots $2,1,-1$.", false));
  q.push(fill("medium", "Solve $x^3-2x^2-3x=0$.", ["0,3,-1"]));
  q.push(fill("medium", "Solve $x^3+3x^2-x-3=0$.", ["-3,1,-1", "1,-1,-3"]));
  q.push(fill("medium", "Solve $x^3-x=0$.", ["0,1,-1"]));
  q.push(num("medium", "Largest root of $x^3-7x-6=0$.", 3, 0));
  q.push(num("medium", "Number of distinct real roots of $x^4-5x^2+4=0$.", 4, 0));
  q.push(num("medium", "Smallest root of $x^3-2x^2-3x=0$.", -1, 0));
  q.push(match("medium", "Match each to its roots.", ["$x^3-2x^2-3x=0$", "$x^4-5x^2+4=0$", "$x^3+2x^2-x-2=0$"], ["$0,3,-1$", "$\\pm1,\\pm2$", "$-2,1,-1$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $x^3-4x^2+x+6=0$ (with $x=-1$):", ["$-1,2,3$", "$1,2,3$", "$-1,-2,3$", "$-1,2,-3$"], 0));
  q.push(mc("hard", "Solve $x^3-2x^2-5x+6=0$ (with $x=1$):", ["$1,3,-2$", "$1,-3,2$", "$1,3,2$", "$-1,3,-2$"], 0));
  q.push(mc("hard", "Solve $x^3-6x^2+11x-6=0$:", ["$1,2,3$", "$1,2,-3$", "$-1,2,3$", "$1,-2,3$"], 0));
  q.push(mc("hard", "Solve $x^4-13x^2+36=0$:", ["$\\pm2,\\pm3$", "$\\pm1,\\pm6$", "$\\pm4,\\pm9$", "$2,3$"], 0));
  q.push(mc("hard", "Solve $x^3+x^2-9x-9=0$ (grouping):", ["$-1,3,-3$", "$1,3,-3$", "$-1,-3,3$", "$1,-3,3$"], 0));
  q.push(ms("hard", "$x^3-6x^2+11x-6$:", ["$P(1)=0$", "divide → $x^2-5x+6$", "$(x-1)(x-2)(x-3)$", "roots $1,2,-3$"], [0, 1, 2]));
  q.push(ms("hard", "$x^4-13x^2+36$:", ["let $u=x^2$", "$(x^2-4)(x^2-9)$", "roots $\\pm2,\\pm3$", "roots $\\pm4,\\pm9$"], [0, 1, 2]));
  q.push(ms("hard", "Grouping $x^3+x^2-9x-9$:", ["$x^2(x+1)-9(x+1)$", "$(x+1)(x^2-9)$", "$(x+1)(x-3)(x+3)$", "$(x+1)(x^2+9)$"], [0, 1, 2]));
  q.push(ms("hard", "When no rational root exists:", ["the quadratic formula on the quotient", "may give irrational roots", "or complex roots", "always rational"], [0, 1, 2]));
  q.push(tf("hard", "$x^3-6x^2+11x-6=0$ has roots $1,2,3$.", true));
  q.push(tf("hard", "$x^4-13x^2+36=0$ has roots $\\pm2,\\pm3$.", true));
  q.push(tf("hard", "$x^3-2x^2-5x+6=0$ has roots $1,-3,2$.", false));
  q.push(fill("hard", "Solve $x^3-6x^2+11x-6=0$.", ["1,2,3"]));
  q.push(fill("hard", "Solve $x^4-13x^2+36=0$.", ["2,-2,3,-3", "\\pm2,\\pm3"]));
  q.push(fill("hard", "Solve $x^3-2x^2-5x+6=0$.", ["1,3,-2"]));
  q.push(num("hard", "Largest root of $x^3-6x^2+11x-6=0$.", 3, 0));
  q.push(num("hard", "Largest root of $x^4-13x^2+36=0$.", 3, 0));
  q.push(num("hard", "Sum of the roots of $x^3-6x^2+11x-6=0$.", 6, 0));
  q.push(order("hard", "Order the steps to solve $x^3-4x^2+x+6=0$.", ["Test candidates; find $P(-1)=0$", "Divide out $(x+1)$ → $x^2-5x+6$", "Factor → $(x-2)(x-3)$", "Roots: $-1,2,3$"]));
  q.push(match("hard", "Match each equation to its roots.", ["$x^3-6x^2+11x-6=0$", "$x^4-13x^2+36=0$", "$x^3+x^2-9x-9=0$"], ["$1,2,3$", "$\\pm2,\\pm3$", "$-1,3,-3$"], [0, 1, 2]));
  return q;
}

// ── 2.4 Polynomial Inequalities ──────────────────────────────
function g24() {
  const q = [];
  q.push(mc("easy", "Solve $(x-1)(x+2)>0$:", ["$x<-2$ or $x>1$", "$-2<x<1$", "$x>1$", "$x<-2$"], 0));
  q.push(mc("easy", "Solve $(x-1)(x+2)<0$:", ["$-2<x<1$", "$x<-2$ or $x>1$", "$x>1$", "$x<1$"], 0));
  q.push(mc("easy", "The zeros of a polynomial split the number line into:", ["intervals of constant sign", "two halves", "the domain", "turning points"], 0));
  q.push(mc("easy", "To find the sign on an interval you:", ["test a point", "factor again", "differentiate", "take the average"], 0));
  q.push(mc("easy", "Endpoints are included for:", ["$\\ge$ or $\\le$", "$>$ or $<$", "never", "always"], 0));
  q.push(mc("easy", "Solve $x^2-4<0$:", ["$-2<x<2$", "$x<-2$ or $x>2$", "$x>2$", "$x<2$"], 0));
  q.push(ms("easy", "The method:", ["factor to find zeros", "test a point per interval", "pick matching intervals", "expand everything"], [0, 1, 2]));
  q.push(ms("easy", "Sign chart:", ["mark the zeros", "label each interval's sign", "read off the solution", "ignore the zeros"], [0, 1, 2]));
  q.push(ms("easy", "$(x-1)(x+2)>0$:", ["zeros $1,-2$", "positive outside", "$x<-2$ or $x>1$", "negative outside"], [0, 1, 2]));
  q.push(ms("easy", "Including endpoints:", ["$\\ge$ includes them", "$\\le$ includes them", "strict $>$ excludes them", "$>$ includes them"], [0, 1, 2]));
  q.push(tf("easy", "$(x-1)(x+2)<0$ on the interval $-2<x<1$.", true));
  q.push(tf("easy", "For $>$ (strict), endpoints are included.", false));
  q.push(tf("easy", "$x^2-4<0$ gives $-2<x<2$.", true));
  q.push(fill("easy", "Solve $(x-1)(x+2)<0$.", ["-2<x<1"]));
  q.push(fill("easy", "Solve $x^2-4<0$.", ["-2<x<2"]));
  q.push(fill("easy", "Zeros of $(x-3)(x+1)$.", ["3,-1", "-1,3"]));
  q.push(num("easy", "Left zero of $(x-1)(x+2)$.", -2, 0));
  q.push(num("easy", "Right zero of $(x-1)(x+2)$.", 1, 0));
  q.push(num("easy", "Number of intervals created by 2 distinct zeros.", 3, 0));
  q.push(match("easy", "Match each to its solution.", ["$(x-1)(x+2)>0$", "$(x-1)(x+2)<0$", "$x^2-4<0$"], ["$x<-2$ or $x>1$", "$-2<x<1$", "$-2<x<2$"], [0, 1, 2]));
  q.push(mc("medium", "Solve $x^2-x-6>0$:", ["$x<-2$ or $x>3$", "$-2<x<3$", "$x>3$", "$x<-2$"], 0));
  q.push(mc("medium", "Solve $x(x-2)(x+1)<0$:", ["$x<-1$ or $0<x<2$", "$-1<x<0$ or $x>2$", "$x>2$", "$-1<x<2$"], 0));
  q.push(mc("medium", "Solve $x^2-2x-3\\ge0$:", ["$x\\le-1$ or $x\\ge3$", "$-1\\le x\\le3$", "$x\\ge3$", "$x\\le-1$"], 0));
  q.push(mc("medium", "Solve $(x+1)(x-4)<0$:", ["$-1<x<4$", "$x<-1$ or $x>4$", "$x>4$", "$x<-1$"], 0));
  q.push(mc("medium", "Solve $x^2-9>0$:", ["$x<-3$ or $x>3$", "$-3<x<3$", "$x>3$", "$x<-3$"], 0));
  q.push(mc("medium", "Solve $x^2-5x+6\\le0$:", ["$2\\le x\\le3$", "$x\\le2$ or $x\\ge3$", "$x\\ge3$", "$2<x<3$"], 0));
  q.push(ms("medium", "$x^2-x-6>0$:", ["$(x-3)(x+2)$", "zeros $3,-2$", "$x<-2$ or $x>3$", "$-2<x<3$"], [0, 1, 2]));
  q.push(ms("medium", "$x(x-2)(x+1)<0$:", ["zeros $-1,0,2$", "signs $-,+,-,+$", "$x<-1$ or $0<x<2$", "$-1<x<2$"], [0, 1, 2]));
  q.push(ms("medium", "$x^2-2x-3\\ge0$:", ["$(x-3)(x+1)$", "$\\ge$ includes endpoints", "$x\\le-1$ or $x\\ge3$", "$-1\\le x\\le3$"], [0, 1, 2]));
  q.push(ms("medium", "Three-factor sign chart:", ["3 zeros → 4 intervals", "alternate signs if all simple", "test one point per interval", "all same sign"], [0, 1, 2]));
  q.push(tf("medium", "$x^2-x-6>0$ gives $x<-2$ or $x>3$.", true));
  q.push(tf("medium", "$x^2-5x+6\\le0$ gives $2\\le x\\le3$.", true));
  q.push(tf("medium", "$(x+1)(x-4)<0$ gives $x<-1$ or $x>4$.", false));
  q.push(fill("medium", "Solve $x^2-x-6>0$.", ["x<-2 or x>3"]));
  q.push(fill("medium", "Solve $x^2-5x+6\\le0$.", ["2<=x<=3", "2≤x≤3"]));
  q.push(fill("medium", "Solve $(x+1)(x-4)<0$.", ["-1<x<4"]));
  q.push(num("medium", "Number of intervals from 3 distinct zeros.", 4, 0));
  q.push(num("medium", "Left endpoint of the solution to $x^2-5x+6\\le0$.", 2, 0));
  q.push(num("medium", "Right endpoint of the solution to $x^2-5x+6\\le0$.", 3, 0));
  q.push(match("medium", "Match each to its solution.", ["$x^2-x-6>0$", "$x^2-5x+6\\le0$", "$(x+1)(x-4)<0$"], ["$x<-2$ or $x>3$", "$2\\le x\\le3$", "$-1<x<4$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $(x-1)^2(x+3)>0$:", ["$x>-3,\\ x\\ne1$", "$x>-3$", "$x<-3$", "all $x$"], 0));
  q.push(mc("hard", "Solve $x^3-x<0$:", ["$x<-1$ or $0<x<1$", "$-1<x<0$ or $x>1$", "$x>1$", "$-1<x<1$"], 0));
  q.push(mc("hard", "Solve $x(x-1)(x-2)(x+1)>0$:", ["$x<-1$ or $0<x<1$ or $x>2$", "$-1<x<0$ or $1<x<2$", "$x>2$", "$-1<x<2$"], 0));
  q.push(mc("hard", "At a zero of even multiplicity the sign:", ["does not change", "always changes", "becomes 0 forever", "flips twice"], 0));
  q.push(mc("hard", "Solve $(x-2)^2(x+1)>0$:", ["$x>-1,\\ x\\ne2$", "$x>-1$", "$x<-1$", "all $x$"], 0));
  q.push(ms("hard", "$(x-1)^2(x+3)>0$:", ["$(x-1)^2\\ge0$ always", "sign from $x+3$", "exclude $x=1$", "$x>-3,\\ x\\ne1$"], [0, 1, 2, 3]));
  q.push(ms("hard", "$x^3-x<0$:", ["$x(x-1)(x+1)$", "zeros $-1,0,1$", "signs $-,+,-,+$", "$x<-1$ or $0<x<1$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Four-factor sign chart:", ["4 zeros → 5 intervals", "signs alternate if all simple", "test a point per interval", "all positive"], [0, 1, 2]));
  q.push(ms("hard", "Even multiplicity:", ["the factor is a square", "stays $\\ge0$", "no sign change there", "always negative"], [0, 1, 2]));
  q.push(tf("hard", "$(x-1)^2(x+3)>0$ excludes $x=1$.", true));
  q.push(tf("hard", "$x^3-x<0$ gives $x<-1$ or $0<x<1$.", true));
  q.push(tf("hard", "At an even-multiplicity zero the sign changes.", false));
  q.push(fill("hard", "Solve $(x-1)^2(x+3)>0$.", ["x>-3, x≠1", "x>-3 and x≠1"]));
  q.push(fill("hard", "Solve $x^3-x<0$.", ["x<-1 or 0<x<1"]));
  q.push(fill("hard", "Sign change happens only at ___ multiplicity zeros.", ["odd"]));
  q.push(num("hard", "Number of intervals from 4 distinct zeros.", 5, 0));
  q.push(num("hard", "The excluded value in the solution of $(x-1)^2(x+3)>0$.", 1, 0));
  q.push(num("hard", "The excluded value in the solution of $(x-2)^2(x+1)>0$.", 2, 0));
  q.push(order("hard", "Order the steps to solve $x(x-2)(x+1)<0$.", ["Zeros: $-1,0,2$", "Build a sign chart with 4 intervals", "Test a point in each: $-,+,-,+$", "Pick negatives: $x<-1$ or $0<x<2$"]));
  q.push(match("hard", "Match each to its solution.", ["$(x-1)^2(x+3)>0$", "$x^3-x<0$", "$(x-2)^2(x+1)>0$"], ["$x>-3,\\ x\\ne1$", "$x<-1$ or $0<x<1$", "$x>-1,\\ x\\ne2$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "2.1", gen: g21 },
  { code: "2.2", gen: g22 },
  { code: "2.3", gen: g23 },
  { code: "2.4", gen: g24 },
];
