// MHF4U Unit 3 — Rational Functions: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 3.1 Reciprocal & Rational Functions ──────────────────────
function g31() {
  const q = [];
  q.push(mc("easy", "Vertical asymptote of $y=\\dfrac{1}{x-3}$:", ["$x=3$", "$x=-3$", "$y=3$", "$x=0$"], 0));
  q.push(mc("easy", "Horizontal asymptote of $y=\\dfrac{1}{x-3}$:", ["$y=0$", "$y=3$", "$x=0$", "$y=1$"], 0));
  q.push(mc("easy", "Domain of $y=\\dfrac{1}{x+2}$:", ["$x\\ne-2$", "$x\\ne2$", "all $x$", "$x>0$"], 0));
  q.push(mc("easy", "A rational function is:", ["a ratio of polynomials", "always linear", "never undefined", "a power function"], 0));
  q.push(mc("easy", "Vertical asymptotes occur where:", ["the denominator is 0", "the numerator is 0", "$x=0$", "$y=0$"], 0));
  q.push(mc("easy", "The reciprocal function is:", ["$y=\\tfrac1x$", "$y=x$", "$y=x^2$", "$y=\\sqrt x$"], 0));
  q.push(ms("easy", "Key features of a rational function:", ["vertical asymptotes", "a horizontal asymptote", "possibly a hole", "always a maximum"], [0, 1, 2]));
  q.push(ms("easy", "The domain:", ["excludes zeros of the denominator", "is everything else", "found by setting $q(x)=0$", "is all reals always"], [0, 1, 2]));
  q.push(ms("easy", "Horizontal asymptote rule:", ["lower top → $y=0$", "equal degrees → ratio of leading coefficients", "compare degrees", "always $y=1$"], [0, 1, 2]));
  q.push(ms("easy", "A hole:", ["from a cancelling factor", "in both top and bottom", "a single missing point", "a vertical asymptote"], [0, 1, 2]));
  q.push(tf("easy", "The vertical asymptote of $y=\\tfrac1x$ is $x=0$.", true));
  q.push(tf("easy", "The horizontal asymptote of $y=\\tfrac1x$ is $y=1$.", false));
  q.push(tf("easy", "The domain of $y=\\dfrac{1}{x-4}$ excludes $x=4$.", true));
  q.push(fill("easy", "Vertical asymptote of $y=\\dfrac{1}{x-5}$.", ["x=5"]));
  q.push(fill("easy", "Horizontal asymptote of $y=\\dfrac{3}{x+1}$.", ["y=0"]));
  q.push(fill("easy", "Domain of $y=\\dfrac{x}{x-4}$.", ["x≠4", "x!=4"]));
  q.push(num("easy", "The $x$-value of the vertical asymptote of $y=\\dfrac{1}{x-6}$.", 6, 0));
  q.push(num("easy", "The $y$-value of the horizontal asymptote of $y=\\dfrac{1}{x-3}$.", 0, 0));
  q.push(num("easy", "Excluded value of $y=\\dfrac{1}{x+2}$.", -2, 0));
  q.push(match("easy", "Match each to its vertical asymptote.", ["$\\dfrac{1}{x-3}$", "$\\dfrac{1}{x+2}$", "$\\dfrac{1}{x-5}$"], ["$x=3$", "$x=-2$", "$x=5$"], [0, 1, 2]));
  q.push(mc("medium", "Horizontal asymptote of $y=\\dfrac{2x}{x-1}$:", ["$y=2$", "$y=0$", "$y=1$", "$x=1$"], 0));
  q.push(mc("medium", "Describe $y=\\dfrac{x^2-1}{x-1}$:", ["$y=x+1$ with a hole at $x=1$", "$y=x-1$", "VA at $x=1$", "no domain restriction"], 0));
  q.push(mc("medium", "Horizontal asymptote of $y=\\dfrac{5x}{x+2}$:", ["$y=5$", "$y=0$", "$y=2$", "$x=-2$"], 0));
  q.push(mc("medium", "Where is the hole in $y=\\dfrac{x^2-4}{x-2}$?", ["$x=2$", "$x=-2$", "$x=4$", "no hole"], 0));
  q.push(mc("medium", "Horizontal asymptote of $y=\\dfrac{3x}{2x-1}$:", ["$y=\\tfrac32$", "$y=3$", "$y=0$", "$y=2$"], 0));
  q.push(mc("medium", "Vertical asymptote of $y=\\dfrac{x+1}{x-6}$:", ["$x=6$", "$x=-1$", "$x=-6$", "$y=1$"], 0));
  q.push(ms("medium", "$y=\\dfrac{2x}{x-1}$:", ["equal degrees", "HA $y=2$", "VA $x=1$", "HA $y=0$"], [0, 1, 2]));
  q.push(ms("medium", "$y=\\dfrac{x^2-1}{x-1}$:", ["factors to $\\dfrac{(x-1)(x+1)}{x-1}$", "simplifies to $x+1$", "hole at $x=1$", "VA at $x=1$"], [0, 1, 2]));
  q.push(ms("medium", "Finding the HA by degrees:", ["compare top and bottom degree", "equal → ratio of leading coeffs", "lower top → $y=0$", "always the constant term"], [0, 1, 2]));
  q.push(ms("medium", "Hole vs asymptote:", ["a hole comes from a cancelling factor", "a VA from a non-cancelling zero", "both restrict the domain", "they are the same"], [0, 1, 2]));
  q.push(tf("medium", "$y=\\dfrac{2x}{x-1}$ has horizontal asymptote $y=2$.", true));
  q.push(tf("medium", "$y=\\dfrac{x^2-1}{x-1}$ has a hole at $x=1$.", true));
  q.push(tf("medium", "$y=\\dfrac{5x}{x+2}$ has horizontal asymptote $y=0$.", false));
  q.push(fill("medium", "Horizontal asymptote of $y=\\dfrac{2x}{x-1}$.", ["y=2"]));
  q.push(fill("medium", "Hole location of $y=\\dfrac{x^2-4}{x-2}$.", ["x=2"]));
  q.push(fill("medium", "Horizontal asymptote of $y=\\dfrac{3x}{2x-1}$.", ["y=3/2", "y=1.5"]));
  q.push(num("medium", "HA $y$-value of $y=\\dfrac{5x}{x+2}$.", 5, 0));
  q.push(num("medium", "Hole $x$-value of $y=\\dfrac{x^2-9}{x+3}$.", -3, 0));
  q.push(num("medium", "VA $x$-value of $y=\\dfrac{x+1}{x-6}$.", 6, 0));
  q.push(match("medium", "Match each to its horizontal asymptote.", ["$\\dfrac{2x}{x-1}$", "$\\dfrac{1}{x-3}$", "$\\dfrac{3x}{2x-1}$"], ["$y=2$", "$y=0$", "$y=\\tfrac32$"], [0, 1, 2]));
  q.push(mc("hard", "Horizontal asymptote of $y=\\dfrac{x^2+1}{x^2-4}$:", ["$y=1$", "$y=0$", "$y=-4$", "none"], 0));
  q.push(mc("hard", "Vertical asymptotes of $y=\\dfrac{1}{x^2-9}$:", ["$x=3$ and $x=-3$", "$x=9$", "$x=3$ only", "none"], 0));
  q.push(mc("hard", "$y=\\dfrac{(x-2)(x+1)}{(x-2)(x-3)}$ has:", ["a hole at $x=2$, VA $x=3$", "VAs at $x=2,3$", "no hole", "HA $y=2$"], 0));
  q.push(mc("hard", "Horizontal asymptote of $y=\\dfrac{x}{x^2+1}$:", ["$y=0$", "$y=1$", "none", "$y=x$"], 0));
  q.push(mc("hard", "Domain of $y=\\dfrac{x+1}{x^2-x-6}$:", ["$x\\ne3,\\ x\\ne-2$", "$x\\ne-1$", "$x\\ne6$", "all $x$"], 0));
  q.push(ms("hard", "$y=\\dfrac{x^2+1}{x^2-4}$:", ["equal degrees", "HA $y=1$", "VAs $x=\\pm2$", "HA $y=0$"], [0, 1, 2]));
  q.push(ms("hard", "$y=\\dfrac{(x-2)(x+1)}{(x-2)(x-3)}$:", ["$(x-2)$ cancels", "hole at $x=2$", "VA at $x=3$", "VA at $x=2$"], [0, 1, 2]));
  q.push(ms("hard", "Factoring the denominator $x^2-x-6$:", ["$(x-3)(x+2)$", "zeros $3,-2$", "VAs there (if no cancel)", "zeros $6,-1$"], [0, 1, 2]));
  q.push(ms("hard", "Lower-degree top:", ["top degree < bottom", "HA is $y=0$", "e.g. $\\dfrac{x}{x^2+1}$", "HA is the ratio of leading coeffs"], [0, 1, 2]));
  q.push(tf("hard", "$y=\\dfrac{1}{x^2-9}$ has two vertical asymptotes.", true));
  q.push(tf("hard", "$y=\\dfrac{x^2+1}{x^2-4}$ has horizontal asymptote $y=1$.", true));
  q.push(tf("hard", "$y=\\dfrac{x}{x^2+1}$ has a vertical asymptote.", false));
  q.push(fill("hard", "HA of $y=\\dfrac{x^2+1}{x^2-4}$.", ["y=1"]));
  q.push(fill("hard", "VAs of $y=\\dfrac{1}{x^2-9}$.", ["x=3, x=-3", "x=±3", "x=3 and x=-3"]));
  q.push(fill("hard", "Hole location of $y=\\dfrac{(x-2)(x+1)}{(x-2)(x-3)}$.", ["x=2"]));
  q.push(num("hard", "Number of vertical asymptotes of $y=\\dfrac{1}{x^2-9}$.", 2, 0));
  q.push(num("hard", "HA $y$-value of $y=\\dfrac{x^2+1}{x^2-4}$.", 1, 0));
  q.push(num("hard", "Number of excluded $x$-values for $y=\\dfrac{x+1}{x^2-x-6}$.", 2, 0));
  q.push(order("hard", "Order the steps to analyse $y=\\dfrac{x^2-1}{x^2-x-2}$.", ["Factor: $\\dfrac{(x-1)(x+1)}{(x-2)(x+1)}$", "Cancel $(x+1)$ → hole at $x=-1$", "VA at $x=2$", "HA $y=1$ (equal degrees)"]));
  q.push(match("hard", "Match each to its key feature.", ["$\\dfrac{1}{x^2-9}$", "$\\dfrac{x^2+1}{x^2-4}$", "$\\dfrac{(x-2)(x+1)}{(x-2)(x-3)}$"], ["VAs $x=\\pm3$", "HA $y=1$", "hole at $x=2$"], [0, 1, 2]));
  return q;
}

// ── 3.2 Graphs of Rational Functions ─────────────────────────
function g32() {
  const q = [];
  q.push(mc("easy", "The x-intercept of a rational function comes from:", ["the numerator = 0", "the denominator = 0", "$f(0)$", "the asymptote"], 0));
  q.push(mc("easy", "The y-intercept comes from:", ["$f(0)$", "the numerator = 0", "the VA", "the HA"], 0));
  q.push(mc("easy", "VA and HA of $y=\\dfrac{1}{x-4}$:", ["VA $x=4$, HA $y=0$", "VA $x=0$, HA $y=4$", "VA $x=-4$, HA $y=0$", "no asymptotes"], 0));
  q.push(mc("easy", "x-intercept of $y=\\dfrac{x-5}{x+2}$:", ["$(5,0)$", "$(-2,0)$", "$(0,5)$", "$(2,0)$"], 0));
  q.push(mc("easy", "Near a vertical asymptote the curve:", ["rushes to $\\pm\\infty$", "is flat", "crosses the axis", "is zero"], 0));
  q.push(mc("easy", "Far from the origin the curve approaches:", ["the horizontal asymptote", "the y-axis", "the vertical asymptote", "the origin"], 0));
  q.push(ms("easy", "Sketching checklist:", ["intercepts", "asymptotes", "behaviour near a VA", "ignore the asymptotes"], [0, 1, 2]));
  q.push(ms("easy", "Intercepts:", ["x-int from numerator", "y-int from $f(0)$", "set each appropriately to 0", "both from the denominator"], [0, 1, 2]));
  q.push(ms("easy", "Asymptotes:", ["VA from denominator", "HA from degrees", "guide the sketch", "VA from numerator"], [0, 1, 2]));
  q.push(ms("easy", "Behaviour near a VA:", ["check both sides", "the curve → $\\pm\\infty$", "use a test point", "the curve is flat"], [0, 1, 2]));
  q.push(tf("easy", "The x-intercept comes from the numerator being zero.", true));
  q.push(tf("easy", "The y-intercept is found by setting the denominator to zero.", false));
  q.push(tf("easy", "Far from the origin the graph approaches the horizontal asymptote.", true));
  q.push(fill("easy", "VA of $y=\\dfrac{1}{x-4}$.", ["x=4"]));
  q.push(fill("easy", "x-intercept of $y=\\dfrac{x-5}{x+2}$ (x-value).", ["5"]));
  q.push(fill("easy", "HA of $y=\\dfrac{1}{x-4}$.", ["y=0"]));
  q.push(num("easy", "x-intercept value of $y=\\dfrac{x-5}{x+2}$.", 5, 0));
  q.push(num("easy", "y-intercept value of $y=\\dfrac{x+4}{x-2}$.", -2, 0));
  q.push(num("easy", "VA x-value of $y=\\dfrac{1}{x-4}$.", 4, 0));
  q.push(match("easy", "Match each to its x-intercept.", ["$\\dfrac{x-5}{x+2}$", "$\\dfrac{x+3}{x-1}$", "$\\dfrac{2x-6}{x+4}$"], ["$5$", "$-3$", "$3$"], [0, 1, 2]));
  q.push(mc("medium", "y-intercept of $y=\\dfrac{x+3}{x-1}$:", ["$(0,-3)$", "$(0,3)$", "$(3,0)$", "$(-3,0)$"], 0));
  q.push(mc("medium", "As $x\\to\\infty$, $y=\\dfrac{2x+1}{x-3}\\to$", ["$2$", "$0$", "$1$", "$\\infty$"], 0));
  q.push(mc("medium", "x-intercept of $y=\\dfrac{2x-6}{x+4}$:", ["$(3,0)$", "$(-4,0)$", "$(0,3)$", "$(6,0)$"], 0));
  q.push(mc("medium", "HA of $y=\\dfrac{3x}{x+5}$:", ["$y=3$", "$y=0$", "$y=5$", "$x=-5$"], 0));
  q.push(mc("medium", "For $y=\\dfrac{x-2}{x+1}$: VA, HA?", ["VA $x=-1$, HA $y=1$", "VA $x=1$, HA $y=0$", "VA $x=-1$, HA $y=0$", "VA $x=2$, HA $y=1$"], 0));
  q.push(mc("medium", "As $x\\to\\infty$, $y=\\dfrac{x+1}{2x-1}\\to$", ["$\\tfrac12$", "$1$", "$2$", "$0$"], 0));
  q.push(ms("medium", "$y=\\dfrac{x-2}{x+1}$:", ["x-int $(2,0)$", "y-int $(0,-2)$", "VA $x=-1$", "HA $y=2$"], [0, 1, 2]));
  q.push(ms("medium", "End behaviour of $\\dfrac{2x+1}{x-3}$:", ["equal degrees", "ratio $\\tfrac21$", "$y\\to2$", "$y\\to0$"], [0, 1, 2]));
  q.push(ms("medium", "y-intercept of $\\dfrac{x+3}{x-1}$:", ["$f(0)=\\dfrac{3}{-1}$", "$=-3$", "point $(0,-3)$", "$=3$"], [0, 1, 2]));
  q.push(ms("medium", "Reading the sketch:", ["the curve approaches HA far out", "blows up near a VA", "crosses at the x-intercept", "touches the VA"], [0, 1, 2]));
  q.push(tf("medium", "$y=\\dfrac{x+3}{x-1}$ has y-intercept $(0,-3)$.", true));
  q.push(tf("medium", "As $x\\to\\infty$, $y=\\dfrac{2x+1}{x-3}\\to2$.", true));
  q.push(tf("medium", "$y=\\dfrac{x-2}{x+1}$ has VA $x=1$.", false));
  q.push(fill("medium", "y-intercept of $y=\\dfrac{x+3}{x-1}$ (y-value).", ["-3"]));
  q.push(fill("medium", "Limit of $\\dfrac{2x+1}{x-3}$ as $x\\to\\infty$.", ["2"]));
  q.push(fill("medium", "VA of $y=\\dfrac{x-2}{x+1}$.", ["x=-1"]));
  q.push(num("medium", "y-intercept value of $y=\\dfrac{x+3}{x-1}$.", -3, 0));
  q.push(num("medium", "x-intercept value of $y=\\dfrac{2x-6}{x+4}$.", 3, 0));
  q.push(num("medium", "HA y-value of $y=\\dfrac{3x}{x+5}$.", 3, 0));
  q.push(match("medium", "Match each to its horizontal asymptote.", ["$\\dfrac{2x+1}{x-3}$", "$\\dfrac{x+1}{2x-1}$", "$\\dfrac{3x}{x+5}$"], ["$y=2$", "$y=\\tfrac12$", "$y=3$"], [0, 1, 2]));
  q.push(mc("hard", "Where does $y=\\dfrac{1}{x-2}$ go just left of $x=2$?", ["$-\\infty$", "$+\\infty$", "$0$", "$2$"], 0));
  q.push(mc("hard", "Intercepts and asymptotes of $y=\\dfrac{x-1}{x+2}$:", ["x-int $1$, y-int $-\\tfrac12$, VA $-2$, HA $1$", "x-int $-2$, VA $1$", "no intercepts", "HA $y=0$"], 0));
  q.push(mc("hard", "$y=\\dfrac{x}{x^2-1}$ has horizontal asymptote:", ["$y=0$", "$y=1$", "none", "$y=x$"], 0));
  q.push(mc("hard", "The graph of $y=\\dfrac{x-2}{x+1}$ crosses its HA:", ["never", "at $x=2$", "at $x=0$", "at $x=-1$"], 0));
  q.push(mc("hard", "$y=\\dfrac{(x-1)(x+2)}{x-3}$ has x-intercepts:", ["$1$ and $-2$", "$3$", "$-1$ and $2$", "none"], 0));
  q.push(ms("hard", "$y=\\dfrac{x-1}{x+2}$ full sketch:", ["x-int $(1,0)$", "y-int $(0,-\\tfrac12)$", "VA $x=-2$, HA $y=1$", "VA $x=1$"], [0, 1, 2]));
  q.push(ms("hard", "Behaviour near $x=2$ for $\\dfrac{1}{x-2}$:", ["left → $-\\infty$", "right → $+\\infty$", "test each side", "both → $+\\infty$"], [0, 1, 2]));
  q.push(ms("hard", "$y=\\dfrac{x}{x^2-1}$:", ["top degree < bottom", "HA $y=0$", "VAs $x=\\pm1$", "HA $y=1$"], [0, 1, 2]));
  q.push(ms("hard", "Multiple x-intercepts:", ["set numerator $=0$", "factor it", "$\\dfrac{(x-1)(x+2)}{x-3}$ → $1,-2$", "from the denominator"], [0, 1, 2]));
  q.push(tf("hard", "$y=\\dfrac{1}{x-2}\\to-\\infty$ just left of $x=2$.", true));
  q.push(tf("hard", "$y=\\dfrac{x}{x^2-1}$ has horizontal asymptote $y=0$.", true));
  q.push(tf("hard", "$y=\\dfrac{(x-1)(x+2)}{x-3}$ has x-intercepts at $1$ and $-2$.", true));
  q.push(fill("hard", "Behaviour of $\\dfrac{1}{x-2}$ just left of $x=2$.", ["-∞", "-infinity", "negative infinity"]));
  q.push(fill("hard", "HA of $y=\\dfrac{x}{x^2-1}$.", ["y=0"]));
  q.push(fill("hard", "x-intercepts of $y=\\dfrac{(x-1)(x+2)}{x-3}$.", ["1,-2", "1 and -2", "-2,1"]));
  q.push(num("hard", "Number of x-intercepts of $y=\\dfrac{(x-1)(x+2)}{x-3}$.", 2, 0));
  q.push(num("hard", "Number of vertical asymptotes of $y=\\dfrac{x}{x^2-1}$.", 2, 0));
  q.push(num("hard", "y-intercept value of $y=\\dfrac{x-1}{x+2}$ (as a fraction, enter $-0.5$).", -0.5, 0.01));
  q.push(order("hard", "Order the steps to sketch $y=\\dfrac{x-2}{x+1}$.", ["x-int: numerator 0 → $(2,0)$", "y-int: $f(0)=-2$", "VA $x=-1$, HA $y=1$", "Test each side of the VA and draw"]));
  q.push(match("hard", "Match each to its behaviour just left of its VA.", ["$\\dfrac{1}{x-2}$", "$\\dfrac{1}{2-x}$", "$\\dfrac{-1}{x-2}$"], ["$-\\infty$", "$+\\infty$", "$+\\infty$"], [0, 1, 2]));
  return q;
}

// ── 3.3 Solving Rational Equations & Inequalities ────────────
function g33() {
  const q = [];
  q.push(mc("easy", "Solve $\\dfrac1x=2$:", ["$x=\\tfrac12$", "$x=2$", "$x=-2$", "$x=1$"], 0));
  q.push(mc("easy", "To solve a rational equation, first:", ["multiply by the LCD", "add 1", "square it", "differentiate"], 0));
  q.push(mc("easy", "Solve $\\dfrac3x=6$:", ["$x=\\tfrac12$", "$x=2$", "$x=18$", "$x=-2$"], 0));
  q.push(mc("easy", "An extraneous root is one that:", ["makes a denominator 0", "is negative", "is a fraction", "is the largest"], 0));
  q.push(mc("easy", "In an inequality, the denominator's zeros are:", ["always excluded", "always included", "the solution", "ignored"], 0));
  q.push(mc("easy", "Solve $\\dfrac1x=5$:", ["$x=\\tfrac15$", "$x=5$", "$x=-5$", "$x=1$"], 0));
  q.push(ms("easy", "Solving an equation:", ["multiply by the LCD", "solve the result", "check restrictions", "skip checking"], [0, 1, 2]));
  q.push(ms("easy", "Solving an inequality:", ["get 0 on one side", "find critical values", "test each interval", "ignore the denominator"], [0, 1, 2]));
  q.push(ms("easy", "Critical values:", ["zeros of the numerator", "zeros of the denominator", "split the number line", "only the numerator"], [0, 1, 2]));
  q.push(ms("easy", "Restrictions:", ["values making a denominator 0", "must be rejected as solutions", "excluded from the domain", "always included"], [0, 1, 2]));
  q.push(tf("easy", "Solving $\\dfrac1x=2$ gives $x=\\tfrac12$.", true));
  q.push(tf("easy", "An extraneous root makes an original denominator zero.", true));
  q.push(tf("easy", "Denominator zeros are included in an inequality's solution.", false));
  q.push(fill("easy", "Solve $\\dfrac1x=2$.", ["1/2", "0.5"]));
  q.push(fill("easy", "Solve $\\dfrac3x=6$.", ["1/2", "0.5"]));
  q.push(fill("easy", "Solve $\\dfrac5x=10$.", ["1/2", "0.5"]));
  q.push(num("easy", "Solve $\\dfrac2x=4$ (decimal).", 0.5, 0.01));
  q.push(num("easy", "Solve $\\dfrac6x=2$.", 3, 0));
  q.push(num("easy", "Solve $\\dfrac{10}{x}=5$.", 2, 0));
  q.push(match("easy", "Match each to its solution.", ["$\\dfrac1x=2$", "$\\dfrac6x=2$", "$\\dfrac{10}{x}=5$"], ["$\\tfrac12$", "$3$", "$2$"], [0, 1, 2]));
  q.push(mc("medium", "Solve $\\dfrac{x+1}{x-2}=3$:", ["$x=\\tfrac72$", "$x=2$", "$x=-1$", "$x=7$"], 0));
  q.push(mc("medium", "Solve $\\dfrac2x+1=3$:", ["$x=1$", "$x=2$", "$x=\\tfrac12$", "$x=-1$"], 0));
  q.push(mc("medium", "Solve $\\dfrac{x}{x-1}>0$:", ["$x<0$ or $x>1$", "$0<x<1$", "$x>1$", "$x<0$"], 0));
  q.push(mc("medium", "Solve $\\dfrac{1}{x-2}<0$:", ["$x<2$", "$x>2$", "all $x$", "$x<0$"], 0));
  q.push(mc("medium", "Solve $\\dfrac{x-1}{x+2}=2$:", ["$x=-5$", "$x=5$", "$x=-1$", "$x=2$"], 0));
  q.push(mc("medium", "Solve $\\dfrac4x-1=1$:", ["$x=2$", "$x=4$", "$x=\\tfrac12$", "$x=-2$"], 0));
  q.push(ms("medium", "$\\dfrac{x+1}{x-2}=3$:", ["cross-multiply", "$x+1=3x-6$", "$x=\\tfrac72$", "$x=2$"], [0, 1, 2]));
  q.push(ms("medium", "$\\dfrac{x}{x-1}>0$:", ["critical values $0,1$", "signs $+,-,+$", "$x<0$ or $x>1$", "$0<x<1$"], [0, 1, 2]));
  q.push(ms("medium", "$\\dfrac2x+1=3$:", ["$\\dfrac2x=2$", "$2=2x$", "$x=1$", "$x=2$"], [0, 1, 2]));
  q.push(ms("medium", "Checking solutions:", ["reject values making a denominator 0", "keep the rest", "$x=\\tfrac72\\ne2$ so valid", "always accept all"], [0, 1, 2]));
  q.push(tf("medium", "$\\dfrac{x+1}{x-2}=3$ gives $x=\\tfrac72$.", true));
  q.push(tf("medium", "$\\dfrac{x}{x-1}>0$ on $x<0$ or $x>1$.", true));
  q.push(tf("medium", "$\\dfrac{1}{x-2}<0$ gives $x>2$.", false));
  q.push(fill("medium", "Solve $\\dfrac{x-1}{x+2}=2$.", ["-5"]));
  q.push(fill("medium", "Solve $\\dfrac4x-1=1$.", ["2"]));
  q.push(fill("medium", "Solve $\\dfrac{1}{x-2}<0$.", ["x<2"]));
  q.push(num("medium", "Solve $\\dfrac{x-1}{x+2}=2$.", -5, 0));
  q.push(num("medium", "Solve $\\dfrac6x+2=5$.", 2, 0));
  q.push(num("medium", "Solve $\\dfrac{x+2}{x-1}=3$.", 2.5, 0.01));
  q.push(match("medium", "Match each to its solution.", ["$\\dfrac{x+1}{x-2}=3$", "$\\dfrac{x-1}{x+2}=2$", "$\\dfrac2x+1=3$"], ["$\\tfrac72$", "$-5$", "$1$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $\\dfrac{x}{x+2}>0$:", ["$x<-2$ or $x>0$", "$-2<x<0$", "$x>0$", "$x<-2$"], 0));
  q.push(mc("hard", "Solve $\\dfrac{2}{x}=\\dfrac{1}{x-1}$:", ["$x=2$", "$x=1$", "$x=-2$", "$x=\\tfrac12$"], 0));
  q.push(mc("hard", "Solve $\\dfrac{x-2}{x+1}\\ge0$:", ["$x\\le-1$ or $x\\ge2$", "$-1\\le x\\le2$", "$x\\ge2$", "$x<-1$ or $x\\ge2$"], 3));
  q.push(mc("hard", "Solve $\\dfrac{x}{x-3}<0$:", ["$0<x<3$", "$x<0$ or $x>3$", "$x>3$", "$x<0$"], 0));
  q.push(mc("hard", "Solve $\\dfrac{1}{x}+\\dfrac{1}{x-1}=\\dfrac{3}{x(x-1)}$ → $x=$", ["$2$", "$1$", "$0$", "$3$"], 0));
  q.push(ms("hard", "$\\dfrac{x-2}{x+1}\\ge0$:", ["critical values $2,-1$", "exclude $x=-1$", "include $x=2$ (numerator)", "include $x=-1$"], [0, 1, 2]));
  q.push(ms("hard", "$\\dfrac{2}{x}=\\dfrac{1}{x-1}$:", ["cross-multiply", "$2(x-1)=x$", "$x=2$", "$x=1$"], [0, 1, 2]));
  q.push(ms("hard", "Combining fractions:", ["use a common denominator", "$\\dfrac1x+\\dfrac1{x-1}=\\dfrac{2x-1}{x(x-1)}$", "set numerators equal", "add numerators directly"], [0, 1, 2]));
  q.push(ms("hard", "Sign chart for $\\dfrac{x}{x-3}$:", ["critical values $0,3$", "open circle at $3$", "negative on $0<x<3$", "$x=3$ included"], [0, 1, 2]));
  q.push(tf("hard", "$\\dfrac{x}{x+2}>0$ on $x<-2$ or $x>0$.", true));
  q.push(tf("hard", "$\\dfrac{2}{x}=\\dfrac{1}{x-1}$ gives $x=2$.", true));
  q.push(tf("hard", "$\\dfrac{x}{x-3}<0$ on $x<0$ or $x>3$.", false));
  q.push(fill("hard", "Solve $\\dfrac{x}{x-3}<0$.", ["0<x<3"]));
  q.push(fill("hard", "Solve $\\dfrac{2}{x}=\\dfrac{1}{x-1}$.", ["2"]));
  q.push(fill("hard", "Solve $\\dfrac{x-2}{x+1}\\ge0$.", ["x<-1 or x>=2", "x<-1 or x≥2"]));
  q.push(num("hard", "Solve $\\dfrac{2}{x}=\\dfrac{1}{x-1}$.", 2, 0));
  q.push(num("hard", "Left critical value of $\\dfrac{x}{x+2}>0$.", -2, 0));
  q.push(num("hard", "Right critical value of $\\dfrac{x}{x-3}<0$.", 3, 0));
  q.push(order("hard", "Order the steps to solve $\\dfrac{x}{x-1}>0$.", ["Critical values: $0$ (top), $1$ (bottom)", "Sign chart on the 3 intervals", "Signs: $+,-,+$", "Solution: $x<0$ or $x>1$"]));
  q.push(match("hard", "Match each inequality to its solution.", ["$\\dfrac{x}{x+2}>0$", "$\\dfrac{x}{x-3}<0$", "$\\dfrac{1}{x-2}<0$"], ["$x<-2$ or $x>0$", "$0<x<3$", "$x<2$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "3.1", gen: g31 },
  { code: "3.2", gen: g32 },
  { code: "3.3", gen: g33 },
];
