// MHF4U Unit 4 — Exponential & Logarithmic Functions: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 4.1 Logarithms & the Laws of Logarithms ──────────────────
function g41() {
  const q = [];
  q.push(mc("easy", "$\\log_2 8=$", ["3", "2", "4", "8"], 0));
  q.push(mc("easy", "$\\log_5 25=$", ["2", "5", "3", "25"], 0));
  q.push(mc("easy", "$\\log 100=$", ["2", "10", "100", "1"], 0));
  q.push(mc("easy", "$\\log_b x=y$ is equivalent to:", ["$b^y=x$", "$b^x=y$", "$x^y=b$", "$y^b=x$"], 0));
  q.push(mc("easy", "$\\log_3 27=$", ["3", "9", "27", "2"], 0));
  q.push(mc("easy", "A logarithm represents:", ["an exponent", "a product", "a base", "a root"], 0));
  q.push(ms("easy", "The laws of logarithms:", ["product → sum", "quotient → difference", "power → multiple", "sum → product"], [0, 1, 2]));
  q.push(ms("easy", "$\\log_b x=y\\iff b^y=x$:", ["the log is the inverse exponent", "needs $b>0,\\ b\\ne1$", "needs $x>0$", "needs $x<0$"], [0, 1, 2]));
  q.push(ms("easy", "Evaluating $\\log_2 8$:", ["ask $2^?=8$", "$2^3=8$", "answer 3", "answer 8"], [0, 1, 2]));
  q.push(ms("easy", "Change of base:", ["$\\log_b x=\\dfrac{\\log x}{\\log b}$", "lets a calculator help", "any base works", "only base 10"], [0, 1, 2]));
  q.push(tf("easy", "$\\log_2 8=3$.", true));
  q.push(tf("easy", "$\\log_b 1=1$.", false));
  q.push(tf("easy", "A logarithm is the inverse of an exponential.", true));
  q.push(fill("easy", "$\\log_2 16=$", ["4"]));
  q.push(fill("easy", "$\\log 1000=$", ["3"]));
  q.push(fill("easy", "$\\log_2 1=$", ["0"]));
  q.push(num("easy", "$\\log_2 8$.", 3, 0));
  q.push(num("easy", "$\\log_5 25$.", 2, 0));
  q.push(num("easy", "$\\log 100$.", 2, 0));
  q.push(match("easy", "Match each log to its value.", ["$\\log_2 8$", "$\\log_5 25$", "$\\log 100$"], ["$3$", "$2$", "$2$"], [0, 1, 2]));
  q.push(mc("medium", "$\\log_2(4\\cdot8)=$", ["5", "32", "6", "12"], 0));
  q.push(mc("medium", "$\\log_2(8^2)=$", ["6", "16", "3", "9"], 0));
  q.push(mc("medium", "$\\log_2\\dfrac{32}{4}=$", ["3", "8", "5", "28"], 0));
  q.push(mc("medium", "$\\log_4 64=$", ["3", "4", "16", "2"], 0));
  q.push(mc("medium", "$\\log_b b^7=$", ["7", "1", "$b$", "0"], 0));
  q.push(mc("medium", "$\\log 0.01=$", ["$-2$", "$2$", "$-1$", "$0.01$"], 0));
  q.push(ms("medium", "$\\log_2(4\\cdot8)$:", ["product law", "$=\\log_2 4+\\log_2 8$", "$=2+3=5$", "$=2\\cdot3$"], [0, 1, 2]));
  q.push(ms("medium", "$\\log_2(8^2)$:", ["power law", "$=2\\log_2 8$", "$=2\\cdot3=6$", "$=\\log_2 16$"], [0, 1, 2]));
  q.push(ms("medium", "$\\log_2\\dfrac{32}{4}$:", ["quotient law", "$=\\log_2 32-\\log_2 4$", "$=5-2=3$", "$=5+2$"], [0, 1, 2]));
  q.push(ms("medium", "$\\log_b b^n=n$:", ["base and argument share the base", "the exponent is the answer", "$\\log_b b=1$", "$=b$"], [0, 1, 2]));
  q.push(tf("medium", "$\\log_2(4\\cdot8)=5$.", true));
  q.push(tf("medium", "$\\log_2(8^2)=6$.", true));
  q.push(tf("medium", "$\\log_2\\dfrac{32}{4}=8$.", false));
  q.push(fill("medium", "$\\log_3(9\\cdot27)=$", ["5"]));
  q.push(fill("medium", "$\\log_5(25^3)=$", ["6"]));
  q.push(fill("medium", "$\\log_b b^7=$", ["7"]));
  q.push(num("medium", "$\\log_2(4\\cdot8)$.", 5, 0));
  q.push(num("medium", "$\\log_2(8^2)$.", 6, 0));
  q.push(num("medium", "$\\log_4 64$.", 3, 0));
  q.push(match("medium", "Match each to its value.", ["$\\log_2(4\\cdot8)$", "$\\log_2(8^2)$", "$\\log_2\\tfrac{32}{4}$"], ["$5$", "$6$", "$3$"], [0, 1, 2]));
  q.push(mc("hard", "$\\log_2 10$ equals (change of base):", ["$\\dfrac{\\log10}{\\log2}$", "$\\dfrac{\\log2}{\\log10}$", "$10\\log 2$", "$\\log 5$"], 0));
  q.push(mc("hard", "Write $\\log_2 40$ using $40=2^3\\cdot5$:", ["$3+\\log_2 5$", "$3\\log_2 5$", "$\\log_2 5-3$", "$3-\\log_2 5$"], 0));
  q.push(mc("hard", "$2\\log x+\\log y$ as one log:", ["$\\log(x^2 y)$", "$\\log(2xy)$", "$\\log(x^2+y)$", "$\\log\\tfrac{x^2}{y}$"], 0));
  q.push(mc("hard", "$\\log 50+\\log 2=$", ["2", "100", "1", "$\\log 52$"], 0));
  q.push(mc("hard", "$\\log_3 81-\\log_3 3=$", ["3", "4", "1", "27"], 0));
  q.push(ms("hard", "Combining $2\\log x+\\log y$:", ["power law on the first", "$\\log x^2+\\log y$", "$\\log(x^2 y)$", "$\\log(2xy)$"], [0, 1, 2]));
  q.push(ms("hard", "$\\log 50+\\log 2$:", ["product law", "$\\log(100)$", "$=2$", "$\\log 52$"], [0, 1, 2]));
  q.push(ms("hard", "$\\log_2 40$ with $40=2^3\\cdot5$:", ["$\\log_2 2^3+\\log_2 5$", "$3+\\log_2 5$", "uses product & power laws", "$3\\log_2 5$"], [0, 1, 2]));
  q.push(ms("hard", "Expanding $\\log\\dfrac{x^3}{y}$:", ["$3\\log x-\\log y$", "quotient then power", "two terms", "$3\\log x+\\log y$"], [0, 1, 2]));
  q.push(tf("hard", "$\\log 50+\\log 2=2$.", true));
  q.push(tf("hard", "$2\\log x+\\log y=\\log(x^2 y)$.", true));
  q.push(tf("hard", "$\\log_2 40=3\\log_2 5$.", false));
  q.push(fill("hard", "$\\log 50+\\log 2=$", ["2"]));
  q.push(fill("hard", "$\\log_3 81-\\log_3 3=$", ["3"]));
  q.push(fill("hard", "Combine $2\\log x+\\log y$.", ["log(x^2y)", "log(x^2 y)"]));
  q.push(num("hard", "$\\log 50+\\log 2$.", 2, 0));
  q.push(num("hard", "$\\log_3 81-\\log_3 3$.", 3, 0));
  q.push(num("hard", "$\\log_2 40-\\log_2 5$.", 3, 0));
  q.push(order("hard", "Order the steps to expand $\\log\\dfrac{x^3}{y}$.", ["Quotient law: $\\log x^3-\\log y$", "Power law on the first term", "$3\\log x-\\log y$", "Final expanded form"]));
  q.push(match("hard", "Match each to its simplified value.", ["$\\log 50+\\log 2$", "$\\log_3 81-\\log_3 3$", "$\\log_2 40-\\log_2 5$"], ["$2$", "$3$", "$3$"], [0, 1, 2]));
  return q;
}

// ── 4.2 Graphs of Logarithmic Functions ──────────────────────
function g42() {
  const q = [];
  q.push(mc("easy", "Domain of $y=\\log x$:", ["$x>0$", "$x<0$", "all $x$", "$x\\ne0$"], 0));
  q.push(mc("easy", "Vertical asymptote of $y=\\log x$:", ["$x=0$", "$y=0$", "$x=1$", "none"], 0));
  q.push(mc("easy", "Every $y=\\log_b x$ passes through:", ["$(1,0)$", "$(0,1)$", "$(0,0)$", "$(1,1)$"], 0));
  q.push(mc("easy", "Range of $y=\\log x$:", ["all reals", "$y>0$", "$y<0$", "$y\\ge0$"], 0));
  q.push(mc("easy", "$y=\\log_b x$ is the inverse of:", ["$y=b^x$", "$y=x^b$", "$y=bx$", "$y=\\tfrac1x$"], 0));
  q.push(mc("easy", "For $b>1$, $y=\\log_b x$ is:", ["increasing", "decreasing", "constant", "undefined"], 0));
  q.push(ms("easy", "Features of $y=\\log_b x$:", ["VA $x=0$", "domain $x>0$", "range all reals", "VA $y=0$"], [0, 1, 2]));
  q.push(ms("easy", "Log vs exponential:", ["inverses", "reflections in $y=x$", "domain/range swap", "the same graph"], [0, 1, 2]));
  q.push(ms("easy", "Key point and shape:", ["passes $(1,0)$", "increasing if $b>1$", "no maximum", "passes $(0,1)$"], [0, 1, 2]));
  q.push(ms("easy", "The vertical asymptote:", ["at $x=0$ for $y=\\log x$", "from the domain restriction", "argument must be $>0$", "at $y=0$"], [0, 1, 2]));
  q.push(tf("easy", "The domain of $y=\\log x$ is $x>0$.", true));
  q.push(tf("easy", "$y=\\log x$ has a horizontal asymptote.", false));
  q.push(tf("easy", "$y=\\log_b x$ passes through $(1,0)$.", true));
  q.push(fill("easy", "Domain of $y=\\log_2 x$.", ["x>0"]));
  q.push(fill("easy", "VA of $y=\\log x$.", ["x=0"]));
  q.push(fill("easy", "$\\log_b 1=$", ["0"]));
  q.push(num("easy", "The y-coordinate where $y=\\log_b x$ meets the x-axis input $x=1$.", 0, 0));
  q.push(num("easy", "The x-value of the vertical asymptote of $y=\\log x$.", 0, 0));
  q.push(num("easy", "Value of $\\log_b b$.", 1, 0));
  q.push(match("easy", "Match each feature of $y=\\log x$.", ["domain", "VA", "key point"], ["$x>0$", "$x=0$", "$(1,0)$"], [0, 1, 2]));
  q.push(mc("medium", "VA of $y=\\log(x-2)$:", ["$x=2$", "$x=-2$", "$x=0$", "$y=2$"], 0));
  q.push(mc("medium", "VA of $y=\\log(x+3)$:", ["$x=-3$", "$x=3$", "$x=0$", "$y=3$"], 0));
  q.push(mc("medium", "Inverse of $y=3^x$:", ["$y=\\log_3 x$", "$y=3x$", "$y=x^3$", "$y=\\log x$"], 0));
  q.push(mc("medium", "Domain of $y=\\log(x-1)$:", ["$x>1$", "$x>-1$", "$x>0$", "all $x$"], 0));
  q.push(mc("medium", "As $x\\to0^+$, $y=\\log x\\to$", ["$-\\infty$", "$+\\infty$", "$0$", "$1$"], 0));
  q.push(mc("medium", "$y=\\log x+4$ shifts the graph:", ["up 4", "down 4", "right 4", "left 4"], 0));
  q.push(ms("medium", "$y=\\log(x-2)$:", ["argument $x-2>0$", "domain $x>2$", "VA $x=2$", "VA $x=-2$"], [0, 1, 2]));
  q.push(ms("medium", "Inverse relationship:", ["$3^x$ and $\\log_3 x$", "swap $x$ and $y$", "reflect in $y=x$", "same function"], [0, 1, 2]));
  q.push(ms("medium", "Translations of $y=\\log x$:", ["$\\log(x-d)$ → VA $x=d$", "$+c$ → up $c$", "domain shifts with $d$", "$+c$ changes the VA"], [0, 1, 2]));
  q.push(ms("medium", "Behaviour near the VA:", ["$x\\to0^+\\Rightarrow y\\to-\\infty$", "the curve hugs the y-axis", "never crosses $x=0$", "$y\\to+\\infty$"], [0, 1, 2]));
  q.push(tf("medium", "$y=\\log(x-2)$ has VA $x=2$.", true));
  q.push(tf("medium", "The inverse of $y=3^x$ is $y=\\log_3 x$.", true));
  q.push(tf("medium", "$y=\\log(x+3)$ has VA $x=3$.", false));
  q.push(fill("medium", "VA of $y=\\log(x-5)$.", ["x=5"]));
  q.push(fill("medium", "Domain of $y=\\log(x-1)$.", ["x>1"]));
  q.push(fill("medium", "Inverse of $y=10^x$.", ["y=log x", "log x", "y=log(x)"]));
  q.push(num("medium", "VA x-value of $y=\\log(x-2)$.", 2, 0));
  q.push(num("medium", "VA x-value of $y=\\log(x+3)$.", -3, 0));
  q.push(num("medium", "Smallest integer in the domain of $y=\\log(x-1)$ is just above this value.", 1, 0));
  q.push(match("medium", "Match each to its vertical asymptote.", ["$\\log(x-2)$", "$\\log(x+3)$", "$\\log(x-5)$"], ["$x=2$", "$x=-3$", "$x=5$"], [0, 1, 2]));
  q.push(mc("hard", "Domain of $y=\\log(2x-6)$:", ["$x>3$", "$x>6$", "$x>-3$", "all $x$"], 0));
  q.push(mc("hard", "VA of $y=\\log(3-x)$:", ["$x=3$", "$x=-3$", "$x=0$", "none"], 0));
  q.push(mc("hard", "$y=2\\log x$ compared to $y=\\log x$:", ["vertical stretch by 2", "shifted up 2", "shifted right 2", "reflected"], 0));
  q.push(mc("hard", "$y=-\\log x$ is $y=\\log x$:", ["reflected in the x-axis", "reflected in the y-axis", "shifted down", "stretched"], 0));
  q.push(mc("hard", "$y=\\log(x-1)+2$ passes through:", ["$(2,2)$", "$(1,2)$", "$(2,0)$", "$(0,2)$"], 0));
  q.push(ms("hard", "Domain of $y=\\log(2x-6)$:", ["$2x-6>0$", "$x>3$", "argument positive", "$x>6$"], [0, 1, 2]));
  q.push(ms("hard", "$y=\\log(3-x)$:", ["argument $3-x>0$", "$x<3$", "VA $x=3$", "domain $x>3$"], [0, 1, 2]));
  q.push(ms("hard", "Transformations:", ["$2\\log x$ stretches vertically", "$-\\log x$ reflects in x-axis", "$\\log(x-1)+2$ shifts right 1 up 2", "$2\\log x$ shifts up"], [0, 1, 2]));
  q.push(ms("hard", "Checking a point on $y=\\log(x-1)+2$:", ["at $x=2$, $\\log1=0$", "so $y=0+2=2$", "point $(2,2)$", "point $(1,2)$"], [0, 1, 2]));
  q.push(tf("hard", "$y=\\log(2x-6)$ has domain $x>3$.", true));
  q.push(tf("hard", "$y=\\log(3-x)$ has VA $x=3$.", true));
  q.push(tf("hard", "$y=2\\log x$ is a vertical shift of $y=\\log x$.", false));
  q.push(fill("hard", "Domain of $y=\\log(2x-6)$.", ["x>3"]));
  q.push(fill("hard", "VA of $y=\\log(3-x)$.", ["x=3"]));
  q.push(fill("hard", "A point on $y=\\log(x-1)+2$.", ["(2,2)", "2,2"]));
  q.push(num("hard", "VA x-value of $y=\\log(2x-6)$.", 3, 0));
  q.push(num("hard", "VA x-value of $y=\\log(3-x)$.", 3, 0));
  q.push(num("hard", "$y$ on $y=\\log(x-1)+2$ at $x=2$.", 2, 0));
  q.push(order("hard", "Order the steps to find the domain of $y=\\log(2x-6)$.", ["Set the argument $>0$", "$2x-6>0$", "$2x>6$", "$x>3$"]));
  q.push(match("hard", "Match each transformation of $y=\\log x$.", ["$2\\log x$", "$-\\log x$", "$\\log x+3$"], ["vertical stretch 2", "reflect in x-axis", "up 3"], [0, 1, 2]));
  return q;
}

// ── 4.3 Solving Exponential & Logarithmic Equations ──────────
function g43() {
  const q = [];
  q.push(mc("easy", "Solve $2^x=8$:", ["3", "4", "2", "6"], 0));
  q.push(mc("easy", "Solve $3^x=81$:", ["4", "3", "27", "9"], 0));
  q.push(mc("easy", "Solve $\\log_2 x=5$:", ["32", "10", "25", "7"], 0));
  q.push(mc("easy", "Solve $5^x=125$:", ["3", "5", "25", "4"], 0));
  q.push(mc("easy", "To solve $b^{f}=b^{g}$:", ["set $f=g$", "set $f=0$", "multiply", "take roots"], 0));
  q.push(mc("easy", "Solve $\\log_3 x=2$:", ["9", "6", "8", "3"], 0));
  q.push(ms("easy", "Solving methods:", ["match the base", "take logs", "rewrite log → exponential", "always guess"], [0, 1, 2]));
  q.push(ms("easy", "Same base:", ["$b^{f}=b^{g}$", "$\\Rightarrow f=g$", "e.g. $2^x=2^3$", "$\\Rightarrow f=0$"], [0, 1, 2]));
  q.push(ms("easy", "$\\log_b x=k$:", ["rewrite as $x=b^k$", "exponential form", "check $x>0$", "$x=k^b$"], [0, 1, 2]));
  q.push(ms("easy", "$2^x=8$:", ["$2^x=2^3$", "$x=3$", "same base", "$x=8$"], [0, 1, 2]));
  q.push(tf("easy", "$2^x=8$ gives $x=3$.", true));
  q.push(tf("easy", "$\\log_2 x=5$ gives $x=10$.", false));
  q.push(tf("easy", "If $b^f=b^g$ then $f=g$.", true));
  q.push(fill("easy", "Solve $2^x=16$.", ["4"]));
  q.push(fill("easy", "Solve $5^x=125$.", ["3"]));
  q.push(fill("easy", "Solve $\\log_3 x=4$.", ["81"]));
  q.push(num("easy", "Solve $2^x=8$.", 3, 0));
  q.push(num("easy", "Solve $\\log_2 x=5$.", 32, 0));
  q.push(num("easy", "Solve $4^x=64$.", 3, 0));
  q.push(match("easy", "Match each equation to its solution.", ["$2^x=8$", "$3^x=81$", "$\\log_2 x=5$"], ["$3$", "$4$", "$32$"], [0, 1, 2]));
  q.push(mc("medium", "Solve $2^x=10$ (2 d.p.):", ["3.32", "5.00", "2.30", "1.00"], 0));
  q.push(mc("medium", "Solve $\\log(x-1)=1$:", ["11", "10", "2", "1"], 0));
  q.push(mc("medium", "Solve $2^{x+1}=16$:", ["3", "4", "15", "8"], 0));
  q.push(mc("medium", "Solve $3^x=20$ (2 d.p.):", ["2.73", "6.67", "1.30", "3.00"], 0));
  q.push(mc("medium", "Solve $\\log(x+2)=1$:", ["8", "10", "12", "3"], 0));
  q.push(mc("medium", "Solve $2^{x-1}=32$:", ["6", "5", "16", "4"], 0));
  q.push(ms("medium", "$2^x=10$:", ["take logs", "$x=\\dfrac{\\log10}{\\log2}$", "$\\approx3.32$", "$x=5$"], [0, 1, 2]));
  q.push(ms("medium", "$\\log(x-1)=1$:", ["$x-1=10^1$", "$x=11$", "check $x-1>0$", "$x=10$"], [0, 1, 2]));
  q.push(ms("medium", "$2^{x+1}=16$:", ["$2^{x+1}=2^4$", "$x+1=4$", "$x=3$", "$x=4$"], [0, 1, 2]));
  q.push(ms("medium", "Checking log solutions:", ["arguments must be positive", "reject the rest", "substitute back", "accept all"], [0, 1, 2]));
  q.push(tf("medium", "$2^x=10$ gives $x\\approx3.32$.", true));
  q.push(tf("medium", "$\\log(x-1)=1$ gives $x=11$.", true));
  q.push(tf("medium", "$2^{x+1}=16$ gives $x=4$.", false));
  q.push(fill("medium", "Solve $\\log(x+2)=1$.", ["8"]));
  q.push(fill("medium", "Solve $2^{x-1}=32$.", ["6"]));
  q.push(fill("medium", "Solve $3^{2x}=81$.", ["2"]));
  q.push(num("medium", "Solve $\\log(x-4)=2$.", 104, 0));
  q.push(num("medium", "Solve $2^{x+1}=16$.", 3, 0));
  q.push(num("medium", "Solve $\\log_5 x=2$.", 25, 0));
  q.push(match("medium", "Match each equation to its solution.", ["$2^{x+1}=16$", "$\\log(x-1)=1$", "$\\log(x+2)=1$"], ["$3$", "$11$", "$8$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $2^x=50$ (2 d.p.):", ["5.64", "25.00", "4.64", "6.64"], 0));
  q.push(mc("hard", "Solve $\\log_2 x+\\log_2(x-2)=3$:", ["4", "2", "8", "6"], 0));
  q.push(mc("hard", "Solve $4^x=8$:", ["1.5", "2", "0.5", "3"], 0));
  q.push(mc("hard", "Solve $\\log(x)+\\log(x-3)=1$:", ["5", "10", "13", "2"], 0));
  q.push(mc("hard", "Solve $3^{2x}=3^{x+1}$:", ["1", "2", "3", "0"], 0));
  q.push(ms("hard", "$\\log_2 x+\\log_2(x-2)=3$:", ["combine: $\\log_2 x(x-2)=3$", "$x(x-2)=8$", "$x=4$ (reject $-2$)", "$x=8$"], [0, 1, 2]));
  q.push(ms("hard", "$2^x=50$:", ["take logs", "$x=\\dfrac{\\log50}{\\log2}$", "$\\approx5.64$", "$x=25$"], [0, 1, 2]));
  q.push(ms("hard", "$4^x=8$ via base 2:", ["$2^{2x}=2^3$", "$2x=3$", "$x=1.5$", "$x=2$"], [0, 1, 2]));
  q.push(ms("hard", "Rejecting roots:", ["$\\log(x)+\\log(x-3)=1$ → $x(x-3)=10$", "$x^2-3x-10=0$", "$x=5$ (reject $-2$)", "$x=-2$ valid"], [0, 1, 2]));
  q.push(tf("hard", "$\\log_2 x+\\log_2(x-2)=3$ gives $x=4$.", true));
  q.push(tf("hard", "$4^x=8$ gives $x=1.5$.", true));
  q.push(tf("hard", "$\\log(x)+\\log(x-3)=1$ gives $x=-2$.", false));
  q.push(fill("hard", "Solve $4^x=8$ (decimal).", ["1.5", "3/2"]));
  q.push(fill("hard", "Solve $\\log_2 x+\\log_2(x-2)=3$.", ["4"]));
  q.push(fill("hard", "Solve $\\log(x)+\\log(x-3)=1$.", ["5"]));
  q.push(num("hard", "Solve $4^x=8$.", 1.5, 0.01));
  q.push(num("hard", "Solve $\\log(x)+\\log(x-3)=1$.", 5, 0));
  q.push(num("hard", "Solve $3^{2x}=3^{x+1}$.", 1, 0));
  q.push(order("hard", "Order the steps to solve $\\log_2 x+\\log_2(x-2)=3$.", ["Combine: $\\log_2 x(x-2)=3$", "Rewrite: $x(x-2)=8$", "Solve $x^2-2x-8=0$ → $x=4,-2$", "Reject $-2$; $x=4$"]));
  q.push(match("hard", "Match each equation to its solution.", ["$2^x=50$", "$4^x=8$", "$\\log_2 x+\\log_2(x-2)=3$"], ["$\\approx5.64$", "$1.5$", "$4$"], [0, 1, 2]));
  return q;
}

// ── 4.4 Applications of Exponential & Log Models ──────────────
function g44() {
  const q = [];
  q.push(mc("easy", "$P=100\\cdot2^{t/5}$ at $t=10$:", ["400", "200", "800", "100"], 0));
  q.push(mc("easy", "$A=80(\\tfrac12)^{t/3}$ at $t=6$:", ["20", "40", "10", "80"], 0));
  q.push(mc("easy", "pH if $[\\text{H}^+]=10^{-4}$:", ["4", "$-4$", "10", "40"], 0));
  q.push(mc("easy", "In $A=A_0 b^{t/p}$, growth needs:", ["$b>1$", "$b<1$", "$b=0$", "$b=1$"], 0));
  q.push(mc("easy", "In $A=A_0 b^{t/p}$, decay needs:", ["$0<b<1$", "$b>1$", "$b=1$", "$b<0$"], 0));
  q.push(mc("easy", "$\\text{pH}=$", ["$-\\log[\\text{H}^+]$", "$\\log[\\text{H}^+]$", "$[\\text{H}^+]$", "$10^{[\\text{H}^+]}$"], 0));
  q.push(ms("easy", "The model $A=A_0 b^{t/p}$:", ["$A_0$ is the start", "$p$ is doubling/half-life", "$b>1$ grows", "$p$ is the amount"], [0, 1, 2]));
  q.push(ms("easy", "Log scales:", ["pH", "decibels", "Richter", "Celsius"], [0, 1, 2]));
  q.push(ms("easy", "Half-life:", ["use $b=\\tfrac12$", "$p$ is the half-life", "amount halves each $p$", "amount doubles each $p$"], [0, 1, 2]));
  q.push(ms("easy", "Doubling:", ["use $b=2$", "$p$ is the doubling time", "amount doubles each $p$", "amount halves"], [0, 1, 2]));
  q.push(tf("easy", "$P=100\\cdot2^{t/5}$ equals 400 at $t=10$.", true));
  q.push(tf("easy", "pH $=-\\log[\\text{H}^+]$.", true));
  q.push(tf("easy", "Decay requires $b>1$.", false));
  q.push(fill("easy", "$P=200\\cdot2^{t/4}$ at $t=8$.", ["800"]));
  q.push(fill("easy", "$A=160(\\tfrac12)^{t/5}$ at $t=10$.", ["40"]));
  q.push(fill("easy", "pH if $[\\text{H}^+]=10^{-7}$.", ["7"]));
  q.push(num("easy", "$P=100\\cdot2^{t/5}$ at $t=10$.", 400, 0));
  q.push(num("easy", "$A=80(\\tfrac12)^{t/3}$ at $t=6$.", 20, 0));
  q.push(num("easy", "pH if $[\\text{H}^+]=10^{-4}$.", 4, 0));
  q.push(match("easy", "Match each to its value.", ["$100\\cdot2^{10/5}$", "$80(\\tfrac12)^{6/3}$", "pH of $10^{-4}$"], ["$400$", "$20$", "$4$"], [0, 1, 2]));
  q.push(mc("medium", "How much stronger is magnitude 7 than 5?", ["$100\\times$", "$2\\times$", "$10\\times$", "$1000\\times$"], 0));
  q.push(mc("medium", "Double at 5\\%/yr takes about:", ["14.2 yr", "5 yr", "20 yr", "7 yr"], 0));
  q.push(mc("medium", "$P=200\\cdot2^{t/4}$ at $t=8$:", ["800", "400", "1600", "200"], 0));
  q.push(mc("medium", "Double at 10\\%/yr takes about:", ["7.3 yr", "10 yr", "14 yr", "3 yr"], 0));
  q.push(mc("medium", "$A=64(\\tfrac12)^{t/2}$ at $t=6$:", ["8", "16", "4", "32"], 0));
  q.push(mc("medium", "Magnitude 6 vs magnitude 3 is:", ["$1000\\times$", "$100\\times$", "$3\\times$", "$30\\times$"], 0));
  q.push(ms("medium", "Doubling time at rate $r$:", ["solve $2=(1+r)^t$", "$t=\\dfrac{\\log2}{\\log(1+r)}$", "use logs", "$t=2r$"], [0, 1, 2]));
  q.push(ms("medium", "Richter difference of 2:", ["$10^2$", "$=100\\times$", "each step $\\times10$", "$=2\\times$"], [0, 1, 2]));
  q.push(ms("medium", "$A=64(\\tfrac12)^{t/2}$ at $t=6$:", ["$t/2=3$", "$(\\tfrac12)^3=\\tfrac18$", "$64\\cdot\\tfrac18=8$", "$=16$"], [0, 1, 2]));
  q.push(ms("medium", "Reading a half-life model:", ["$b=\\tfrac12$", "exponent $t/p$", "decreases over time", "increases over time"], [0, 1, 2]));
  q.push(tf("medium", "Magnitude 7 is 100 times stronger than magnitude 5.", true));
  q.push(tf("medium", "Doubling at 5\\%/yr takes about 14.2 years.", true));
  q.push(tf("medium", "$A=64(\\tfrac12)^{t/2}$ equals 16 at $t=6$.", false));
  q.push(fill("medium", "Magnitude difference giving $1000\\times$.", ["3"]));
  q.push(fill("medium", "$P=100\\cdot2^{t/10}$ at $t=20$.", ["400"]));
  q.push(fill("medium", "$A=64(\\tfrac12)^{t/2}$ at $t=6$.", ["8"]));
  q.push(num("medium", "$P=200\\cdot2^{t/4}$ at $t=8$.", 800, 0));
  q.push(num("medium", "How many times stronger is magnitude 6 than 3?", 1000, 0));
  q.push(num("medium", "$A=64(\\tfrac12)^{t/2}$ at $t=6$.", 8, 0));
  q.push(match("medium", "Match each to its value.", ["mag 7 vs 5", "mag 6 vs 3", "$200\\cdot2^{8/4}$"], ["$100\\times$", "$1000\\times$", "$800$"], [0, 1, 2]));
  q.push(mc("hard", "Time to triple at 5\\%/yr (2 d.p.):", ["22.52 yr", "14.21 yr", "20.00 yr", "9.01 yr"], 0));
  q.push(mc("hard", "Time to double at 8\\%/yr (2 d.p.):", ["9.01 yr", "8.66 yr", "12.50 yr", "7.27 yr"], 0));
  q.push(mc("hard", "A quake $10^4$ times stronger is how many magnitudes higher?", ["4", "10", "2", "104"], 0));
  q.push(mc("hard", "$P=50\\cdot3^{t/5}$ at $t=5$:", ["150", "100", "250", "50"], 0));
  q.push(mc("hard", "Reach 1.5× at 5\\%/yr (2 d.p.):", ["8.31 yr", "14.21 yr", "10.00 yr", "5.00 yr"], 0));
  q.push(ms("hard", "Tripling time at 5\\%:", ["$3=1.05^t$", "$t=\\dfrac{\\log3}{\\log1.05}$", "$\\approx22.52$ yr", "$\\approx14.2$ yr"], [0, 1, 2]));
  q.push(ms("hard", "$10^4$ amplitude factor:", ["each magnitude $=\\times10$", "$10^4$ → 4 magnitudes", "log scale", "→ 10 magnitudes"], [0, 1, 2]));
  q.push(ms("hard", "$P=50\\cdot3^{t/5}$ at $t=5$:", ["$t/5=1$", "$3^1=3$", "$50\\cdot3=150$", "$=100$"], [0, 1, 2]));
  q.push(ms("hard", "Solving for time generally:", ["isolate the power", "take logs of both sides", "divide by $\\log$ base", "guess and check only"], [0, 1, 2]));
  q.push(tf("hard", "Tripling at 5\\%/yr takes about 22.52 years.", true));
  q.push(tf("hard", "A $10^4$-times-stronger quake is 4 magnitudes higher.", true));
  q.push(tf("hard", "$P=50\\cdot3^{t/5}$ equals 100 at $t=5$.", false));
  q.push(fill("hard", "Magnitudes higher for a $10^4$ factor.", ["4"]));
  q.push(fill("hard", "$P=50\\cdot3^{t/5}$ at $t=5$.", ["150"]));
  q.push(fill("hard", "Tripling time at 5\\%/yr (2 d.p.).", ["22.52"]));
  q.push(num("hard", "$P=50\\cdot3^{t/5}$ at $t=5$.", 150, 0));
  q.push(num("hard", "Magnitudes higher for a $10^4$ amplitude factor.", 4, 0));
  q.push(num("hard", "$P=500\\cdot2^{t/3}$ at $t=9$.", 4000, 0));
  q.push(order("hard", "Order the steps to find the doubling time at 5\\%/yr.", ["Set $2=1.05^t$", "Take logs: $\\log2=t\\log1.05$", "$t=\\dfrac{\\log2}{\\log1.05}$", "$t\\approx14.2$ yr"]));
  q.push(match("hard", "Match each to its result.", ["double at 8\\%", "triple at 5\\%", "$500\\cdot2^{9/3}$"], ["$\\approx9.01$ yr", "$\\approx22.52$ yr", "$4000$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "4.1", gen: g41 },
  { code: "4.2", gen: g42 },
  { code: "4.3", gen: g43 },
  { code: "4.4", gen: g44 },
];
