// MHF4U Unit 5 — Trigonometric Functions (radians): question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 5.1 Radian Measure ───────────────────────────────────────
function g51() {
  const q = [];
  q.push(mc("easy", "$180^\\circ$ in radians:", ["$\\pi$", "$2\\pi$", "$\\tfrac{\\pi}{2}$", "$\\tfrac{\\pi}{3}$"], 0));
  q.push(mc("easy", "$90^\\circ$ in radians:", ["$\\tfrac{\\pi}{2}$", "$\\pi$", "$\\tfrac{\\pi}{4}$", "$\\tfrac{\\pi}{3}$"], 0));
  q.push(mc("easy", "$\\tfrac{\\pi}{3}$ in degrees:", ["$60^\\circ$", "$30^\\circ$", "$45^\\circ$", "$90^\\circ$"], 0));
  q.push(mc("easy", "A full circle in radians:", ["$2\\pi$", "$\\pi$", "$360$", "$4\\pi$"], 0));
  q.push(mc("easy", "To convert degrees to radians, multiply by:", ["$\\tfrac{\\pi}{180}$", "$\\tfrac{180}{\\pi}$", "$\\pi$", "$180$"], 0));
  q.push(mc("easy", "The arc-length formula is:", ["$s=r\\theta$", "$s=\\tfrac{r}{\\theta}$", "$s=r+\\theta$", "$s=r^2\\theta$"], 0));
  q.push(ms("easy", "Radian facts:", ["full circle $=2\\pi$", "arc $=$ radius for 1 rad", "natural unit for trig", "full circle $=\\pi$"], [0, 1, 2]));
  q.push(ms("easy", "Conversions:", ["deg→rad $\\times\\tfrac{\\pi}{180}$", "rad→deg $\\times\\tfrac{180}{\\pi}$", "$180^\\circ=\\pi$", "deg→rad $\\times180$"], [0, 1, 2]));
  q.push(ms("easy", "Special angles:", ["$30^\\circ=\\tfrac{\\pi}{6}$", "$45^\\circ=\\tfrac{\\pi}{4}$", "$60^\\circ=\\tfrac{\\pi}{3}$", "$30^\\circ=\\tfrac{\\pi}{3}$"], [0, 1, 2]));
  q.push(ms("easy", "Arc length $s=r\\theta$:", ["$\\theta$ in radians", "grows with radius", "grows with angle", "$\\theta$ in degrees"], [0, 1, 2]));
  q.push(tf("easy", "$180^\\circ=\\pi$ radians.", true));
  q.push(tf("easy", "A full circle is $\\pi$ radians.", false));
  q.push(tf("easy", "Arc length is $s=r\\theta$ with $\\theta$ in radians.", true));
  q.push(fill("easy", "$90^\\circ$ in radians.", ["pi/2", "π/2"]));
  q.push(fill("easy", "$\\tfrac{\\pi}{6}$ in degrees.", ["30"]));
  q.push(fill("easy", "$60^\\circ$ in radians.", ["pi/3", "π/3"]));
  q.push(num("easy", "$\\tfrac{\\pi}{3}$ in degrees.", 60, 0));
  q.push(num("easy", "$2\\pi$ in degrees.", 360, 0));
  q.push(num("easy", "Arc length for $r=6,\\ \\theta=\\tfrac{\\pi}{2}$ as a multiple of $\\pi$ (enter the coefficient).", 3, 0));
  q.push(match("easy", "Match each degree measure to radians.", ["$180^\\circ$", "$90^\\circ$", "$60^\\circ$"], ["$\\pi$", "$\\tfrac{\\pi}{2}$", "$\\tfrac{\\pi}{3}$"], [0, 1, 2]));
  q.push(mc("medium", "$\\tfrac{3\\pi}{2}$ in degrees:", ["$270^\\circ$", "$135^\\circ$", "$90^\\circ$", "$240^\\circ$"], 0));
  q.push(mc("medium", "$120^\\circ$ in radians:", ["$\\tfrac{2\\pi}{3}$", "$\\tfrac{\\pi}{3}$", "$\\tfrac{3\\pi}{4}$", "$\\tfrac{5\\pi}{6}$"], 0));
  q.push(mc("medium", "$\\tfrac{3\\pi}{4}$ in degrees:", ["$135^\\circ$", "$120^\\circ$", "$150^\\circ$", "$45^\\circ$"], 0));
  q.push(mc("medium", "Arc length for $r=4,\\ \\theta=\\tfrac{\\pi}{3}$:", ["$\\tfrac{4\\pi}{3}$", "$\\tfrac{4\\pi}{6}$", "$4\\pi$", "$\\tfrac{\\pi}{3}$"], 0));
  q.push(mc("medium", "$225^\\circ$ in radians:", ["$\\tfrac{5\\pi}{4}$", "$\\tfrac{3\\pi}{4}$", "$\\tfrac{7\\pi}{4}$", "$\\tfrac{5\\pi}{6}$"], 0));
  q.push(mc("medium", "$\\tfrac{5\\pi}{6}$ in degrees:", ["$150^\\circ$", "$120^\\circ$", "$135^\\circ$", "$165^\\circ$"], 0));
  q.push(ms("medium", "Converting $120^\\circ$:", ["$\\times\\tfrac{\\pi}{180}$", "$=\\tfrac{120\\pi}{180}$", "$=\\tfrac{2\\pi}{3}$", "$=\\tfrac{\\pi}{3}$"], [0, 1, 2]));
  q.push(ms("medium", "Arc length $r=4,\\ \\theta=\\tfrac{\\pi}{3}$:", ["$s=r\\theta$", "$=4\\cdot\\tfrac{\\pi}{3}$", "$=\\tfrac{4\\pi}{3}$", "$=\\tfrac{\\pi}{3}$"], [0, 1, 2]));
  q.push(ms("medium", "Converting radians to degrees:", ["$\\times\\tfrac{180}{\\pi}$", "$\\tfrac{3\\pi}{2}\\to270^\\circ$", "$\\pi\\to180^\\circ$", "$\\times\\tfrac{\\pi}{180}$"], [0, 1, 2]));
  q.push(ms("medium", "Coterminal & quadrants:", ["$\\tfrac{3\\pi}{2}$ is on the negative y-axis", "$=270^\\circ$", "between QIII and QIV", "$=90^\\circ$"], [0, 1, 2]));
  q.push(tf("medium", "$120^\\circ=\\tfrac{2\\pi}{3}$.", true));
  q.push(tf("medium", "Arc length for $r=4,\\ \\theta=\\tfrac{\\pi}{3}$ is $\\tfrac{4\\pi}{3}$.", true));
  q.push(tf("medium", "$\\tfrac{3\\pi}{4}=120^\\circ$.", false));
  q.push(fill("medium", "$120^\\circ$ in radians.", ["2pi/3", "2π/3"]));
  q.push(fill("medium", "$\\tfrac{3\\pi}{2}$ in degrees.", ["270"]));
  q.push(fill("medium", "$225^\\circ$ in radians.", ["5pi/4", "5π/4"]));
  q.push(num("medium", "$\\tfrac{3\\pi}{4}$ in degrees.", 135, 0));
  q.push(num("medium", "$\\tfrac{5\\pi}{6}$ in degrees.", 150, 0));
  q.push(num("medium", "Arc length for $r=10,\\ \\theta=\\tfrac{\\pi}{5}$ as a multiple of $\\pi$ (coefficient).", 2, 0));
  q.push(match("medium", "Match each to its degree measure.", ["$\\tfrac{2\\pi}{3}$", "$\\tfrac{3\\pi}{4}$", "$\\tfrac{5\\pi}{6}$"], ["$120^\\circ$", "$135^\\circ$", "$150^\\circ$"], [0, 1, 2]));
  q.push(mc("hard", "$\\tfrac{7\\pi}{6}$ in degrees:", ["$210^\\circ$", "$240^\\circ$", "$150^\\circ$", "$330^\\circ$"], 0));
  q.push(mc("hard", "$300^\\circ$ in radians:", ["$\\tfrac{5\\pi}{3}$", "$\\tfrac{4\\pi}{3}$", "$\\tfrac{5\\pi}{6}$", "$\\tfrac{7\\pi}{6}$"], 0));
  q.push(mc("hard", "A sector of radius 8 has arc length $4\\pi$. Its central angle is:", ["$\\tfrac{\\pi}{2}$", "$\\pi$", "$\\tfrac{\\pi}{4}$", "$2\\pi$"], 0));
  q.push(mc("hard", "Through how many radians does the minute hand turn in 15 min?", ["$\\tfrac{\\pi}{2}$", "$\\pi$", "$\\tfrac{\\pi}{4}$", "$2\\pi$"], 0));
  q.push(mc("hard", "$1$ radian is approximately:", ["$57.3^\\circ$", "$45^\\circ$", "$60^\\circ$", "$30^\\circ$"], 0));
  q.push(ms("hard", "Finding $\\theta$ from $s=r\\theta$:", ["$\\theta=\\tfrac{s}{r}$", "for $s=4\\pi,\\ r=8$", "$\\theta=\\tfrac{\\pi}{2}$", "$\\theta=2\\pi$"], [0, 1, 2]));
  q.push(ms("hard", "Clock angles:", ["full turn $=2\\pi$", "15 min $=\\tfrac14$ turn", "$=\\tfrac{\\pi}{2}$", "$=\\pi$"], [0, 1, 2]));
  q.push(ms("hard", "$\\tfrac{7\\pi}{6}$:", ["$=210^\\circ$", "in QIII", "$\\pi+\\tfrac{\\pi}{6}$", "in QII"], [0, 1, 2]));
  q.push(ms("hard", "$1$ radian:", ["$=\\tfrac{180}{\\pi}{}^\\circ$", "$\\approx57.3^\\circ$", "more than $45^\\circ$", "$=60^\\circ$ exactly"], [0, 1, 2]));
  q.push(tf("hard", "A sector with $r=8,\\ s=4\\pi$ has central angle $\\tfrac{\\pi}{2}$.", true));
  q.push(tf("hard", "$\\tfrac{7\\pi}{6}=210^\\circ$.", true));
  q.push(tf("hard", "1 radian is exactly $60^\\circ$.", false));
  q.push(fill("hard", "$\\tfrac{7\\pi}{6}$ in degrees.", ["210"]));
  q.push(fill("hard", "$300^\\circ$ in radians.", ["5pi/3", "5π/3"]));
  q.push(fill("hard", "Central angle if $r=8,\\ s=4\\pi$.", ["pi/2", "π/2"]));
  q.push(num("hard", "$\\tfrac{7\\pi}{6}$ in degrees.", 210, 0));
  q.push(num("hard", "Radius if $s=4\\pi$ and $\\theta=\\tfrac{\\pi}{2}$.", 8, 0));
  q.push(num("hard", "$1$ radian in degrees, to the nearest degree.", 57, 1));
  q.push(order("hard", "Order the steps to find the angle of a sector with $r=8,\\ s=4\\pi$.", ["Use $s=r\\theta$", "$4\\pi=8\\theta$", "$\\theta=\\tfrac{4\\pi}{8}$", "$\\theta=\\tfrac{\\pi}{2}$"]));
  q.push(match("hard", "Match each to its radian measure.", ["$210^\\circ$", "$300^\\circ$", "$240^\\circ$"], ["$\\tfrac{7\\pi}{6}$", "$\\tfrac{5\\pi}{3}$", "$\\tfrac{4\\pi}{3}$"], [0, 1, 2]));
  return q;
}

// ── 5.2 Trigonometric Ratios & the Unit Circle ───────────────
function g52() {
  const q = [];
  q.push(mc("easy", "$\\sin\\tfrac{\\pi}{6}=$", ["$\\tfrac12$", "$\\tfrac{\\sqrt3}{2}$", "$1$", "$\\tfrac{\\sqrt2}{2}$"], 0));
  q.push(mc("easy", "$\\cos\\tfrac{\\pi}{3}=$", ["$\\tfrac12$", "$\\tfrac{\\sqrt3}{2}$", "$0$", "$1$"], 0));
  q.push(mc("easy", "$\\sin\\tfrac{\\pi}{2}=$", ["$1$", "$0$", "$\\tfrac12$", "$-1$"], 0));
  q.push(mc("easy", "$\\cos\\pi=$", ["$-1$", "$0$", "$1$", "$\\tfrac12$"], 0));
  q.push(mc("easy", "$\\tan\\tfrac{\\pi}{4}=$", ["$1$", "$0$", "$\\sqrt3$", "undefined"], 0));
  q.push(mc("easy", "The unit-circle point at $\\theta$ is:", ["$(\\cos\\theta,\\sin\\theta)$", "$(\\sin\\theta,\\cos\\theta)$", "$(\\tan\\theta,1)$", "$(\\theta,\\theta)$"], 0));
  q.push(ms("easy", "Unit circle:", ["radius 1", "point $(\\cos\\theta,\\sin\\theta)$", "$\\tan\\theta=\\tfrac{\\sin\\theta}{\\cos\\theta}$", "radius $2\\pi$"], [0, 1, 2]));
  q.push(ms("easy", "Special values:", ["$\\sin\\tfrac{\\pi}{6}=\\tfrac12$", "$\\cos\\tfrac{\\pi}{3}=\\tfrac12$", "$\\tan\\tfrac{\\pi}{4}=1$", "$\\sin\\tfrac{\\pi}{2}=0$"], [0, 1, 2]));
  q.push(ms("easy", "Quadrantal angles:", ["$\\sin\\tfrac{\\pi}{2}=1$", "$\\cos\\tfrac{\\pi}{2}=0$", "$\\cos\\pi=-1$", "$\\sin\\tfrac{\\pi}{2}=0$"], [0, 1, 2]));
  q.push(ms("easy", "Tangent:", ["$=\\tfrac{\\sin}{\\cos}$", "$\\tan\\tfrac{\\pi}{4}=1$", "undefined where $\\cos=0$", "$=\\tfrac{\\cos}{\\sin}$"], [0, 1, 2]));
  q.push(tf("easy", "$\\sin\\tfrac{\\pi}{6}=\\tfrac12$.", true));
  q.push(tf("easy", "$\\cos\\pi=1$.", false));
  q.push(tf("easy", "$\\tan\\tfrac{\\pi}{4}=1$.", true));
  q.push(fill("easy", "$\\cos\\tfrac{\\pi}{3}=$", ["1/2", "0.5"]));
  q.push(fill("easy", "$\\sin\\tfrac{\\pi}{2}=$", ["1"]));
  q.push(fill("easy", "$\\cos\\pi=$", ["-1"]));
  q.push(num("easy", "$\\sin\\tfrac{\\pi}{2}$.", 1, 0));
  q.push(num("easy", "$\\cos\\pi$.", -1, 0));
  q.push(num("easy", "$\\tan\\tfrac{\\pi}{4}$.", 1, 0));
  q.push(match("easy", "Match each to its value.", ["$\\sin\\tfrac{\\pi}{6}$", "$\\cos\\pi$", "$\\sin\\tfrac{\\pi}{2}$"], ["$\\tfrac12$", "$-1$", "$1$"], [0, 1, 2]));
  q.push(mc("medium", "$\\cos\\tfrac{\\pi}{6}=$", ["$\\tfrac{\\sqrt3}{2}$", "$\\tfrac12$", "$1$", "$0$"], 0));
  q.push(mc("medium", "$\\sin\\tfrac{\\pi}{3}=$", ["$\\tfrac{\\sqrt3}{2}$", "$\\tfrac12$", "$1$", "$0$"], 0));
  q.push(mc("medium", "$\\cos\\tfrac{\\pi}{2}=$", ["$0$", "$1$", "$-1$", "$\\tfrac12$"], 0));
  q.push(mc("medium", "$\\sin\\pi=$", ["$0$", "$1$", "$-1$", "$\\tfrac12$"], 0));
  q.push(mc("medium", "In QII, which is positive?", ["$\\sin\\theta$", "$\\cos\\theta$", "$\\tan\\theta$", "all"], 0));
  q.push(mc("medium", "$\\cos 0=$", ["$1$", "$0$", "$-1$", "$\\tfrac12$"], 0));
  q.push(ms("medium", "$\\sin\\tfrac{\\pi}{4}=\\cos\\tfrac{\\pi}{4}$:", ["both $\\tfrac{\\sqrt2}{2}$", "from a $45^\\circ$ triangle", "equal", "both $1$"], [0, 1, 2]));
  q.push(ms("medium", "CAST in QII:", ["only sine positive", "cosine negative", "tangent negative", "all positive"], [0, 1, 2]));
  q.push(ms("medium", "Quadrantal values:", ["$\\cos\\tfrac{\\pi}{2}=0$", "$\\sin\\pi=0$", "$\\cos 0=1$", "$\\sin\\pi=1$"], [0, 1, 2]));
  q.push(ms("medium", "$\\sin\\tfrac{\\pi}{3}$ vs $\\cos\\tfrac{\\pi}{6}$:", ["both $\\tfrac{\\sqrt3}{2}$", "cofunction relationship", "equal", "both $\\tfrac12$"], [0, 1, 2]));
  q.push(tf("medium", "$\\cos\\tfrac{\\pi}{6}=\\tfrac{\\sqrt3}{2}$.", true));
  q.push(tf("medium", "In QII, $\\cos\\theta>0$.", false));
  q.push(tf("medium", "$\\sin\\pi=0$.", true));
  q.push(fill("medium", "$\\sin\\tfrac{\\pi}{3}=$", ["sqrt3/2", "√3/2"]));
  q.push(fill("medium", "$\\cos\\tfrac{\\pi}{2}=$", ["0"]));
  q.push(fill("medium", "Quadrant with $\\sin>0,\\ \\cos<0$.", ["II", "2"]));
  q.push(num("medium", "$\\cos\\tfrac{\\pi}{2}$.", 0, 0));
  q.push(num("medium", "$\\sin\\pi$.", 0, 0));
  q.push(num("medium", "$\\cos 0$.", 1, 0));
  q.push(match("medium", "Match each to its value.", ["$\\cos\\tfrac{\\pi}{6}$", "$\\sin\\tfrac{\\pi}{3}$", "$\\cos\\tfrac{\\pi}{2}$"], ["$\\tfrac{\\sqrt3}{2}$", "$\\tfrac{\\sqrt3}{2}$", "$0$"], [0, 1, 2]));
  q.push(mc("hard", "$\\sin\\tfrac{2\\pi}{3}=$", ["$\\tfrac{\\sqrt3}{2}$", "$-\\tfrac{\\sqrt3}{2}$", "$\\tfrac12$", "$-\\tfrac12$"], 0));
  q.push(mc("hard", "$\\cos\\tfrac{2\\pi}{3}=$", ["$-\\tfrac12$", "$\\tfrac12$", "$\\tfrac{\\sqrt3}{2}$", "$-\\tfrac{\\sqrt3}{2}$"], 0));
  q.push(mc("hard", "$\\tan\\tfrac{\\pi}{3}=$", ["$\\sqrt3$", "$\\tfrac1{\\sqrt3}$", "$1$", "$\\tfrac{\\sqrt3}{2}$"], 0));
  q.push(mc("hard", "$\\sin\\tfrac{7\\pi}{6}=$", ["$-\\tfrac12$", "$\\tfrac12$", "$-\\tfrac{\\sqrt3}{2}$", "$\\tfrac{\\sqrt3}{2}$"], 0));
  q.push(mc("hard", "Solve $\\sin\\theta=\\tfrac12$ on $[0,2\\pi)$:", ["$\\tfrac{\\pi}{6},\\tfrac{5\\pi}{6}$", "$\\tfrac{\\pi}{6}$", "$\\tfrac{\\pi}{3},\\tfrac{2\\pi}{3}$", "$\\tfrac{\\pi}{6},\\tfrac{7\\pi}{6}$"], 0));
  q.push(ms("hard", "$\\sin\\tfrac{2\\pi}{3}$:", ["reference angle $\\tfrac{\\pi}{3}$", "QII → sine positive", "$=\\tfrac{\\sqrt3}{2}$", "$=-\\tfrac{\\sqrt3}{2}$"], [0, 1, 2]));
  q.push(ms("hard", "$\\cos\\tfrac{2\\pi}{3}$:", ["reference angle $\\tfrac{\\pi}{3}$", "QII → cosine negative", "$=-\\tfrac12$", "$=\\tfrac12$"], [0, 1, 2]));
  q.push(ms("hard", "Solving $\\sin\\theta=\\tfrac12$:", ["base angle $\\tfrac{\\pi}{6}$", "sine positive in QI, QII", "$\\theta=\\tfrac{\\pi}{6},\\tfrac{5\\pi}{6}$", "only $\\tfrac{\\pi}{6}$"], [0, 1, 2]));
  q.push(ms("hard", "$\\sin\\tfrac{7\\pi}{6}$:", ["reference angle $\\tfrac{\\pi}{6}$", "QIII → sine negative", "$=-\\tfrac12$", "$=\\tfrac12$"], [0, 1, 2]));
  q.push(tf("hard", "$\\sin\\tfrac{2\\pi}{3}=\\tfrac{\\sqrt3}{2}$.", true));
  q.push(tf("hard", "$\\cos\\tfrac{2\\pi}{3}=-\\tfrac12$.", true));
  q.push(tf("hard", "$\\sin\\theta=\\tfrac12$ has only one solution on $[0,2\\pi)$.", false));
  q.push(fill("hard", "$\\sin\\tfrac{2\\pi}{3}=$", ["sqrt3/2", "√3/2"]));
  q.push(fill("hard", "$\\cos\\tfrac{2\\pi}{3}=$", ["-1/2", "-0.5"]));
  q.push(fill("hard", "Solutions of $\\sin\\theta=\\tfrac12$ on $[0,2\\pi)$.", ["pi/6, 5pi/6", "π/6, 5π/6"]));
  q.push(num("hard", "$\\tan\\tfrac{\\pi}{4}$.", 1, 0));
  q.push(num("hard", "Number of solutions of $\\sin\\theta=\\tfrac12$ on $[0,2\\pi)$.", 2, 0));
  q.push(num("hard", "Number of solutions of $\\cos\\theta=0$ on $[0,2\\pi)$.", 2, 0));
  q.push(order("hard", "Order the steps to evaluate $\\sin\\tfrac{2\\pi}{3}$.", ["Find the reference angle $\\tfrac{\\pi}{3}$", "$\\tfrac{2\\pi}{3}$ is in QII", "Sine is positive in QII", "$=\\tfrac{\\sqrt3}{2}$"]));
  q.push(match("hard", "Match each to its value.", ["$\\sin\\tfrac{2\\pi}{3}$", "$\\cos\\tfrac{2\\pi}{3}$", "$\\tan\\tfrac{\\pi}{3}$"], ["$\\tfrac{\\sqrt3}{2}$", "$-\\tfrac12$", "$\\sqrt3$"], [0, 1, 2]));
  return q;
}

// ── 5.3 Graphs of Sinusoidal Functions ───────────────────────
function g53() {
  const q = [];
  q.push(mc("easy", "Amplitude of $y=3\\sin x$:", ["3", "1", "6", "$\\tfrac13$"], 0));
  q.push(mc("easy", "Period of $y=\\sin x$:", ["$2\\pi$", "$\\pi$", "$1$", "$\\tfrac{\\pi}{2}$"], 0));
  q.push(mc("easy", "Midline of $y=\\sin x+2$:", ["$y=2$", "$y=0$", "$y=-2$", "$x=2$"], 0));
  q.push(mc("easy", "Amplitude of $y=5\\sin x$:", ["5", "1", "10", "$\\tfrac15$"], 0));
  q.push(mc("easy", "The period formula is:", ["$\\tfrac{2\\pi}{k}$", "$2\\pi k$", "$\\tfrac{k}{2\\pi}$", "$\\tfrac{\\pi}{k}$"], 0));
  q.push(mc("easy", "Amplitude is:", ["$|a|$", "$k$", "$c$", "$d$"], 0));
  q.push(ms("easy", "In $y=a\\sin(k(x-d))+c$:", ["amplitude $|a|$", "period $\\tfrac{2\\pi}{k}$", "midline $y=c$", "amplitude $k$"], [0, 1, 2]));
  q.push(ms("easy", "Amplitude:", ["height above midline", "$=|a|$", "from the coefficient of sin", "$=c$"], [0, 1, 2]));
  q.push(ms("easy", "Midline:", ["$y=c$", "vertical centre", "from the $+c$ term", "$=|a|$"], [0, 1, 2]));
  q.push(ms("easy", "Period:", ["$\\tfrac{2\\pi}{k}$", "length of one cycle", "shorter for large $k$", "$=|a|$"], [0, 1, 2]));
  q.push(tf("easy", "Amplitude of $y=3\\sin x$ is 3.", true));
  q.push(tf("easy", "The period of $y=\\sin x$ is $\\pi$.", false));
  q.push(tf("easy", "Midline of $y=\\sin x+2$ is $y=2$.", true));
  q.push(fill("easy", "Amplitude of $y=5\\sin x$.", ["5"]));
  q.push(fill("easy", "Period of $y=\\sin x$.", ["2pi", "2π"]));
  q.push(fill("easy", "Midline of $y=\\cos x-3$.", ["y=-3"]));
  q.push(num("easy", "Amplitude of $y=3\\sin x$.", 3, 0));
  q.push(num("easy", "Amplitude of $y=7\\cos x$.", 7, 0));
  q.push(num("easy", "Midline $y$-value of $y=\\sin x+5$.", 5, 0));
  q.push(match("easy", "Match each to its amplitude.", ["$3\\sin x$", "$5\\sin x$", "$\\tfrac12\\sin x$"], ["$3$", "$5$", "$\\tfrac12$"], [0, 1, 2]));
  q.push(mc("medium", "Period of $y=\\sin(2x)$:", ["$\\pi$", "$2\\pi$", "$4\\pi$", "$\\tfrac{\\pi}{2}$"], 0));
  q.push(mc("medium", "Period of $y=\\cos(\\tfrac{x}{2})$:", ["$4\\pi$", "$2\\pi$", "$\\pi$", "$\\tfrac{\\pi}{2}$"], 0));
  q.push(mc("medium", "Amplitude and period of $y=2\\sin(3x)$:", ["amp 2, period $\\tfrac{2\\pi}{3}$", "amp 3, period 2", "amp 2, period $\\pi$", "amp 6, period $2\\pi$"], 0));
  q.push(mc("medium", "Period of $y=\\sin(4x)$:", ["$\\tfrac{\\pi}{2}$", "$\\pi$", "$2\\pi$", "$4\\pi$"], 0));
  q.push(mc("medium", "Amplitude and period of $y=4\\cos(2x)$:", ["amp 4, period $\\pi$", "amp 2, period 4", "amp 4, period $2\\pi$", "amp 8, period $\\pi$"], 0));
  q.push(mc("medium", "Period of $y=\\sin(\\tfrac{x}{3})$:", ["$6\\pi$", "$3\\pi$", "$\\tfrac{2\\pi}{3}$", "$2\\pi$"], 0));
  q.push(ms("medium", "Period of $y=\\sin(2x)$:", ["$\\tfrac{2\\pi}{k}$", "$k=2$", "$=\\pi$", "$=2\\pi$"], [0, 1, 2]));
  q.push(ms("medium", "$y=2\\sin(3x)$:", ["amp 2", "$k=3$", "period $\\tfrac{2\\pi}{3}$", "period $3$"], [0, 1, 2]));
  q.push(ms("medium", "Longer periods:", ["small $k$ → long period", "$\\cos(\\tfrac{x}{2})$ → $4\\pi$", "$\\sin(\\tfrac{x}{3})$ → $6\\pi$", "small $k$ → short period"], [0, 1, 2]));
  q.push(ms("medium", "Reading $y=4\\cos(2x)$:", ["amp $=4$", "$k=2$", "period $\\pi$", "midline $y=4$"], [0, 1, 2]));
  q.push(tf("medium", "The period of $y=\\sin(2x)$ is $\\pi$.", true));
  q.push(tf("medium", "$y=2\\sin(3x)$ has period $\\tfrac{2\\pi}{3}$.", true));
  q.push(tf("medium", "$y=\\cos(\\tfrac{x}{2})$ has period $\\pi$.", false));
  q.push(fill("medium", "Period of $y=\\sin(4x)$.", ["pi/2", "π/2"]));
  q.push(fill("medium", "Period of $y=\\cos(\\tfrac{x}{2})$.", ["4pi", "4π"]));
  q.push(fill("medium", "Amplitude of $y=4\\cos(2x)$.", ["4"]));
  q.push(num("medium", "Period of $y=\\sin(2x)$ as a multiple of $\\pi$ (coefficient).", 1, 0));
  q.push(num("medium", "Period of $y=\\sin(\\tfrac{x}{3})$ as a multiple of $\\pi$ (coefficient).", 6, 0));
  q.push(num("medium", "Amplitude of $y=2\\sin(3x)$.", 2, 0));
  q.push(match("medium", "Match each to its period.", ["$\\sin(2x)$", "$\\cos(\\tfrac{x}{2})$", "$\\sin(4x)$"], ["$\\pi$", "$4\\pi$", "$\\tfrac{\\pi}{2}$"], [0, 1, 2]));
  q.push(mc("hard", "Amplitude, period, midline of $y=3\\sin(2x)+1$:", ["3, $\\pi$, $y=1$", "2, $\\pi$, $y=3$", "3, $2\\pi$, $y=1$", "1, $\\pi$, $y=3$"], 0));
  q.push(mc("hard", "$y=2\\cos(\\tfrac{x}{2})-1$ has range:", ["$[-3,1]$", "$[-1,3]$", "$[-2,2]$", "$[0,2]$"], 0));
  q.push(mc("hard", "The max of $y=4\\sin x+2$ is:", ["6", "4", "2", "8"], 0));
  q.push(mc("hard", "Phase shift of $y=\\sin(x-\\tfrac{\\pi}{3})$:", ["$\\tfrac{\\pi}{3}$ right", "$\\tfrac{\\pi}{3}$ left", "up $\\tfrac{\\pi}{3}$", "none"], 0));
  q.push(mc("hard", "A wave with period $\\pi$ has $k=$", ["2", "1", "$\\tfrac12$", "$\\pi$"], 0));
  q.push(ms("hard", "$y=3\\sin(2x)+1$:", ["amp 3", "period $\\pi$", "midline $y=1$", "amp 1"], [0, 1, 2]));
  q.push(ms("hard", "Range of $y=2\\cos(\\tfrac{x}{2})-1$:", ["amp 2, midline $-1$", "max $1$", "min $-3$", "range $[-3,1]$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Max/min from amp & midline:", ["max $=c+|a|$", "min $=c-|a|$", "for $4\\sin x+2$: max 6", "max $=c$"], [0, 1, 2]));
  q.push(ms("hard", "Finding $k$ from a period:", ["$k=\\tfrac{2\\pi}{\\text{period}}$", "period $\\pi$ → $k=2$", "shorter period → larger $k$", "$k=$ period"], [0, 1, 2]));
  q.push(tf("hard", "$y=3\\sin(2x)+1$ has amplitude 3, period $\\pi$, midline $y=1$.", true));
  q.push(tf("hard", "$y=2\\cos(\\tfrac{x}{2})-1$ has range $[-3,1]$.", true));
  q.push(tf("hard", "The maximum of $y=4\\sin x+2$ is 4.", false));
  q.push(fill("hard", "Maximum of $y=4\\sin x+2$.", ["6"]));
  q.push(fill("hard", "Range of $y=2\\cos(\\tfrac{x}{2})-1$.", ["[-3,1]"]));
  q.push(fill("hard", "$k$ for a wave of period $\\pi$.", ["2"]));
  q.push(num("hard", "Maximum of $y=4\\sin x+2$.", 6, 0));
  q.push(num("hard", "Minimum of $y=2\\cos(\\tfrac{x}{2})-1$.", -3, 0));
  q.push(num("hard", "$k$ for period $\\pi$.", 2, 0));
  q.push(order("hard", "Order the steps to find the range of $y=2\\cos(\\tfrac{x}{2})-1$.", ["Amplitude 2, midline $y=-1$", "Max $=-1+2=1$", "Min $=-1-2=-3$", "Range $[-3,1]$"]));
  q.push(match("hard", "Match each to its period.", ["$3\\sin(2x)+1$", "$2\\cos(\\tfrac{x}{2})$", "$\\sin(4x)$"], ["$\\pi$", "$4\\pi$", "$\\tfrac{\\pi}{2}$"], [0, 1, 2]));
  return q;
}

// ── 5.4 Reciprocal Trigonometric Functions ───────────────────
function g54() {
  const q = [];
  q.push(mc("easy", "$\\csc\\theta=$", ["$\\tfrac1{\\sin\\theta}$", "$\\tfrac1{\\cos\\theta}$", "$\\tfrac{\\cos\\theta}{\\sin\\theta}$", "$\\sin\\theta$"], 0));
  q.push(mc("easy", "$\\sec\\theta=$", ["$\\tfrac1{\\cos\\theta}$", "$\\tfrac1{\\sin\\theta}$", "$\\tan\\theta$", "$\\cos\\theta$"], 0));
  q.push(mc("easy", "$\\cot\\theta=$", ["$\\tfrac{\\cos\\theta}{\\sin\\theta}$", "$\\tfrac{\\sin\\theta}{\\cos\\theta}$", "$\\tfrac1{\\cos\\theta}$", "$\\tan\\theta$"], 0));
  q.push(mc("easy", "$\\csc\\tfrac{\\pi}{2}=$", ["1", "0", "2", "$\\tfrac12$"], 0));
  q.push(mc("easy", "$\\sec 0=$", ["1", "0", "$-1$", "undefined"], 0));
  q.push(mc("easy", "$\\cot\\tfrac{\\pi}{4}=$", ["1", "0", "$\\sqrt3$", "undefined"], 0));
  q.push(ms("easy", "The reciprocal ratios:", ["$\\csc=\\tfrac1{\\sin}$", "$\\sec=\\tfrac1{\\cos}$", "$\\cot=\\tfrac{\\cos}{\\sin}$", "$\\csc=\\tfrac1{\\cos}$"], [0, 1, 2]));
  q.push(ms("easy", "Evaluating:", ["find the base ratio first", "then reciprocate", "$\\csc\\tfrac{\\pi}{2}=\\tfrac11=1$", "square it"], [0, 1, 2]));
  q.push(ms("easy", "Asymptotes:", ["$\\csc$ where $\\sin=0$", "$\\sec$ where $\\cos=0$", "from division by zero", "$\\csc$ where $\\cos=0$"], [0, 1, 2]));
  q.push(ms("easy", "Reciprocal of a small value:", ["is large", "$\\csc\\tfrac{\\pi}{6}=2$", "since $\\sin\\tfrac{\\pi}{6}=\\tfrac12$", "is small"], [0, 1, 2]));
  q.push(tf("easy", "$\\csc\\theta=\\tfrac1{\\sin\\theta}$.", true));
  q.push(tf("easy", "$\\sec\\theta=\\tfrac1{\\sin\\theta}$.", false));
  q.push(tf("easy", "$\\cot\\tfrac{\\pi}{4}=1$.", true));
  q.push(fill("easy", "$\\csc\\tfrac{\\pi}{2}=$", ["1"]));
  q.push(fill("easy", "$\\sec 0=$", ["1"]));
  q.push(fill("easy", "$\\cot\\tfrac{\\pi}{4}=$", ["1"]));
  q.push(num("easy", "$\\csc\\tfrac{\\pi}{2}$.", 1, 0));
  q.push(num("easy", "$\\sec 0$.", 1, 0));
  q.push(num("easy", "$\\cot\\tfrac{\\pi}{4}$.", 1, 0));
  q.push(match("easy", "Match each reciprocal function.", ["$\\csc$", "$\\sec$", "$\\cot$"], ["$\\tfrac1{\\sin}$", "$\\tfrac1{\\cos}$", "$\\tfrac{\\cos}{\\sin}$"], [0, 1, 2]));
  q.push(mc("medium", "$\\csc\\tfrac{\\pi}{6}=$", ["2", "$\\tfrac12$", "1", "$\\sqrt3$"], 0));
  q.push(mc("medium", "$\\sec\\tfrac{\\pi}{3}=$", ["2", "$\\tfrac12$", "1", "$\\sqrt3$"], 0));
  q.push(mc("medium", "$\\sec\\pi=$", ["$-1$", "1", "0", "undefined"], 0));
  q.push(mc("medium", "$\\cot\\tfrac{\\pi}{2}=$", ["0", "1", "undefined", "$-1$"], 0));
  q.push(mc("medium", "$\\csc\\tfrac{3\\pi}{2}=$", ["$-1$", "1", "0", "undefined"], 0));
  q.push(mc("medium", "$\\csc\\theta$ has asymptotes where:", ["$\\sin\\theta=0$", "$\\cos\\theta=0$", "$\\tan\\theta=0$", "$\\theta=0$ only"], 0));
  q.push(ms("medium", "$\\csc\\tfrac{\\pi}{6}$:", ["$\\sin\\tfrac{\\pi}{6}=\\tfrac12$", "reciprocal $=2$", "since $\\tfrac1{1/2}=2$", "$=\\tfrac12$"], [0, 1, 2]));
  q.push(ms("medium", "$\\sec\\pi$:", ["$\\cos\\pi=-1$", "$\\sec=\\tfrac1{-1}$", "$=-1$", "$=1$"], [0, 1, 2]));
  q.push(ms("medium", "$\\cot\\tfrac{\\pi}{2}$:", ["$\\cos\\tfrac{\\pi}{2}=0$", "$\\sin\\tfrac{\\pi}{2}=1$", "$\\tfrac01=0$", "undefined"], [0, 1, 2]));
  q.push(ms("medium", "Asymptotes of $\\sec$:", ["where $\\cos=0$", "$\\theta=\\tfrac{\\pi}{2},\\tfrac{3\\pi}{2}$", "division by zero", "where $\\sin=0$"], [0, 1, 2]));
  q.push(tf("medium", "$\\csc\\tfrac{\\pi}{6}=2$.", true));
  q.push(tf("medium", "$\\sec\\pi=-1$.", true));
  q.push(tf("medium", "$\\cot\\tfrac{\\pi}{2}=1$.", false));
  q.push(fill("medium", "$\\csc\\tfrac{\\pi}{6}=$", ["2"]));
  q.push(fill("medium", "$\\sec\\tfrac{\\pi}{3}=$", ["2"]));
  q.push(fill("medium", "$\\cot\\tfrac{\\pi}{2}=$", ["0"]));
  q.push(num("medium", "$\\csc\\tfrac{\\pi}{6}$.", 2, 0));
  q.push(num("medium", "$\\sec\\tfrac{\\pi}{3}$.", 2, 0));
  q.push(num("medium", "$\\sec\\pi$.", -1, 0));
  q.push(match("medium", "Match each to its value.", ["$\\csc\\tfrac{\\pi}{6}$", "$\\sec\\pi$", "$\\cot\\tfrac{\\pi}{2}$"], ["$2$", "$-1$", "$0$"], [0, 1, 2]));
  q.push(mc("hard", "$\\sec\\tfrac{\\pi}{6}=$", ["$\\tfrac{2}{\\sqrt3}$", "$\\tfrac{\\sqrt3}{2}$", "2", "$\\tfrac12$"], 0));
  q.push(mc("hard", "$\\cot\\tfrac{\\pi}{3}=$", ["$\\tfrac1{\\sqrt3}$", "$\\sqrt3$", "1", "$\\tfrac{\\sqrt3}{2}$"], 0));
  q.push(mc("hard", "$\\csc\\pi$ is:", ["undefined", "0", "1", "$-1$"], 0));
  q.push(mc("hard", "$\\csc\\tfrac{2\\pi}{3}=$", ["$\\tfrac{2}{\\sqrt3}$", "$-\\tfrac{2}{\\sqrt3}$", "2", "$-2$"], 0));
  q.push(mc("hard", "$\\sec\\tfrac{2\\pi}{3}=$", ["$-2$", "2", "$\\tfrac12$", "$-\\tfrac12$"], 0));
  q.push(ms("hard", "$\\sec\\tfrac{\\pi}{6}$:", ["$\\cos\\tfrac{\\pi}{6}=\\tfrac{\\sqrt3}{2}$", "reciprocal $\\tfrac{2}{\\sqrt3}$", "rationalize to $\\tfrac{2\\sqrt3}{3}$", "$=2$"], [0, 1, 2]));
  q.push(ms("hard", "$\\csc\\pi$:", ["$\\sin\\pi=0$", "division by 0", "undefined", "$=0$"], [0, 1, 2]));
  q.push(ms("hard", "$\\sec\\tfrac{2\\pi}{3}$:", ["$\\cos\\tfrac{2\\pi}{3}=-\\tfrac12$", "reciprocal $-2$", "QII → cosine negative", "$=2$"], [0, 1, 2]));
  q.push(ms("hard", "$\\cot\\tfrac{\\pi}{3}$:", ["$\\tan\\tfrac{\\pi}{3}=\\sqrt3$", "$\\cot=\\tfrac1{\\sqrt3}$", "$=\\tfrac{\\sqrt3}{3}$", "$=\\sqrt3$"], [0, 1, 2]));
  q.push(tf("hard", "$\\csc\\pi$ is undefined.", true));
  q.push(tf("hard", "$\\sec\\tfrac{2\\pi}{3}=-2$.", true));
  q.push(tf("hard", "$\\cot\\tfrac{\\pi}{3}=\\sqrt3$.", false));
  q.push(fill("hard", "$\\sec\\tfrac{\\pi}{6}=$", ["2/sqrt3", "2/√3", "2√3/3"]));
  q.push(fill("hard", "$\\cot\\tfrac{\\pi}{3}=$", ["1/sqrt3", "1/√3", "√3/3"]));
  q.push(fill("hard", "$\\csc\\pi$ (state if undefined).", ["undefined"]));
  q.push(num("hard", "$\\sec\\tfrac{2\\pi}{3}$.", -2, 0));
  q.push(num("hard", "$\\csc\\tfrac{3\\pi}{2}$.", -1, 0));
  q.push(num("hard", "$\\sec 2\\pi$.", 1, 0));
  q.push(order("hard", "Order the steps to evaluate $\\sec\\tfrac{2\\pi}{3}$.", ["Reference angle $\\tfrac{\\pi}{3}$", "QII → cosine negative: $\\cos\\tfrac{2\\pi}{3}=-\\tfrac12$", "$\\sec=\\tfrac1{\\cos}$", "$=-2$"]));
  q.push(match("hard", "Match each to its value.", ["$\\sec\\tfrac{2\\pi}{3}$", "$\\csc\\tfrac{3\\pi}{2}$", "$\\sec 2\\pi$"], ["$-2$", "$-1$", "$1$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "5.1", gen: g51 },
  { code: "5.2", gen: g52 },
  { code: "5.3", gen: g53 },
  { code: "5.4", gen: g54 },
];
