// MHF4U Unit 6 — Trigonometric Identities & Equations: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 6.1 Compound Angle Formulas ──────────────────────────────
function g61() {
  const q = [];
  q.push(mc("easy", "$\\sin(A+B)=$", ["$\\sin A\\cos B+\\cos A\\sin B$", "$\\sin A\\cos B-\\cos A\\sin B$", "$\\cos A\\cos B-\\sin A\\sin B$", "$\\sin A+\\sin B$"], 0));
  q.push(mc("easy", "$\\cos(A-B)=$", ["$\\cos A\\cos B+\\sin A\\sin B$", "$\\cos A\\cos B-\\sin A\\sin B$", "$\\sin A\\cos B-\\cos A\\sin B$", "$\\cos A-\\cos B$"], 0));
  q.push(mc("easy", "$\\sin(A-B)=$", ["$\\sin A\\cos B-\\cos A\\sin B$", "$\\sin A\\cos B+\\cos A\\sin B$", "$\\cos A\\cos B+\\sin A\\sin B$", "$\\sin A-\\sin B$"], 0));
  q.push(mc("easy", "$\\cos(A+B)=$", ["$\\cos A\\cos B-\\sin A\\sin B$", "$\\cos A\\cos B+\\sin A\\sin B$", "$\\sin A\\cos B+\\cos A\\sin B$", "$\\cos A+\\cos B$"], 0));
  q.push(mc("easy", "$15^\\circ$ can be written as:", ["$45^\\circ-30^\\circ$", "$45^\\circ+30^\\circ$", "$60^\\circ-30^\\circ$", "$90^\\circ-30^\\circ$"], 0));
  q.push(mc("easy", "$\\cos x\\cos y+\\sin x\\sin y=$", ["$\\cos(x-y)$", "$\\cos(x+y)$", "$\\sin(x-y)$", "$\\sin(x+y)$"], 0));
  q.push(ms("easy", "Compound angle formulas:", ["$\\sin(A+B)=\\sin A\\cos B+\\cos A\\sin B$", "$\\cos(A+B)=\\cos A\\cos B-\\sin A\\sin B$", "give exact values for new angles", "$\\sin(A+B)=\\sin A+\\sin B$"], [0, 1, 2]));
  q.push(ms("easy", "To find $\\sin 75^\\circ$:", ["write $75=45+30$", "use $\\sin(A+B)$", "substitute special values", "use $\\sin 75=\\sin 45+\\sin 30$"], [0, 1, 2]));
  q.push(ms("easy", "Recognizing patterns:", ["$\\sin A\\cos B+\\cos A\\sin B=\\sin(A+B)$", "$\\cos A\\cos B+\\sin A\\sin B=\\cos(A-B)$", "reverse the formulas", "always equal $\\sin(A+B)$"], [0, 1, 2]));
  q.push(ms("easy", "Sign care:", ["cosine flips the sign", "$\\cos(A+B)$ uses minus", "$\\cos(A-B)$ uses plus", "cosine keeps the same sign"], [0, 1, 2]));
  q.push(tf("easy", "$\\sin(A+B)=\\sin A\\cos B+\\cos A\\sin B$.", true));
  q.push(tf("easy", "$\\cos(A+B)=\\cos A\\cos B+\\sin A\\sin B$.", false));
  q.push(tf("easy", "$15^\\circ=45^\\circ-30^\\circ$.", true));
  q.push(fill("easy", "$\\cos x\\cos y+\\sin x\\sin y=$", ["cos(x-y)"]));
  q.push(fill("easy", "$\\sin x\\cos y+\\cos x\\sin y=$", ["sin(x+y)"]));
  q.push(fill("easy", "Write $75^\\circ$ as a sum of special angles.", ["45+30", "30+45"]));
  q.push(num("easy", "If $75=45+B$, then $B=$ (degrees).", 30, 0));
  q.push(num("easy", "If $15=45-B$, then $B=$ (degrees).", 30, 0));
  q.push(num("easy", "$105=60+B$, then $B=$ (degrees).", 45, 0));
  q.push(match("easy", "Match each to its identity.", ["$\\sin A\\cos B+\\cos A\\sin B$", "$\\cos A\\cos B-\\sin A\\sin B$", "$\\cos A\\cos B+\\sin A\\sin B$"], ["$\\sin(A+B)$", "$\\cos(A+B)$", "$\\cos(A-B)$"], [0, 1, 2]));
  q.push(mc("medium", "$\\sin 75^\\circ=$", ["$\\tfrac{\\sqrt6+\\sqrt2}{4}$", "$\\tfrac{\\sqrt6-\\sqrt2}{4}$", "$\\tfrac{\\sqrt3+1}{2}$", "$\\tfrac12$"], 0));
  q.push(mc("medium", "$\\cos 75^\\circ=$", ["$\\tfrac{\\sqrt6-\\sqrt2}{4}$", "$\\tfrac{\\sqrt6+\\sqrt2}{4}$", "$\\tfrac12$", "$\\tfrac{\\sqrt3}{2}$"], 0));
  q.push(mc("medium", "$\\sin 15^\\circ=$", ["$\\tfrac{\\sqrt6-\\sqrt2}{4}$", "$\\tfrac{\\sqrt6+\\sqrt2}{4}$", "$\\tfrac12$", "$\\tfrac{\\sqrt2}{2}$"], 0));
  q.push(mc("medium", "With $\\sin A=\\tfrac35,\\cos A=\\tfrac45,\\sin B=\\tfrac5{13},\\cos B=\\tfrac{12}{13}$, $\\sin(A+B)=$", ["$\\tfrac{56}{65}$", "$\\tfrac{33}{65}$", "$\\tfrac{16}{65}$", "$\\tfrac{63}{65}$"], 0));
  q.push(mc("medium", "Same values: $\\cos(A+B)=$", ["$\\tfrac{33}{65}$", "$\\tfrac{56}{65}$", "$\\tfrac{16}{65}$", "$-\\tfrac{33}{65}$"], 0));
  q.push(mc("medium", "$\\cos 15^\\circ=$", ["$\\tfrac{\\sqrt6+\\sqrt2}{4}$", "$\\tfrac{\\sqrt6-\\sqrt2}{4}$", "$\\tfrac12$", "$\\tfrac{\\sqrt3}{2}$"], 0));
  q.push(ms("medium", "Computing $\\sin 75^\\circ$:", ["$\\sin45\\cos30+\\cos45\\sin30$", "$\\tfrac{\\sqrt6}{4}+\\tfrac{\\sqrt2}{4}$", "$\\tfrac{\\sqrt6+\\sqrt2}{4}$", "$\\tfrac12$"], [0, 1, 2]));
  q.push(ms("medium", "Computing $\\sin(A+B)$ with values:", ["$\\sin A\\cos B+\\cos A\\sin B$", "$\\tfrac35\\cdot\\tfrac{12}{13}+\\tfrac45\\cdot\\tfrac5{13}$", "$\\tfrac{56}{65}$", "$\\tfrac{33}{65}$"], [0, 1, 2]));
  q.push(ms("medium", "$\\sin 15^\\circ$ via difference:", ["$\\sin(45-30)$", "$\\sin45\\cos30-\\cos45\\sin30$", "$\\tfrac{\\sqrt6-\\sqrt2}{4}$", "$\\tfrac{\\sqrt6+\\sqrt2}{4}$"], [0, 1, 2]));
  q.push(ms("medium", "$\\cos(A+B)$ with values:", ["$\\cos A\\cos B-\\sin A\\sin B$", "$\\tfrac45\\cdot\\tfrac{12}{13}-\\tfrac35\\cdot\\tfrac5{13}$", "$\\tfrac{33}{65}$", "$\\tfrac{56}{65}$"], [0, 1, 2]));
  q.push(tf("medium", "$\\sin 75^\\circ=\\tfrac{\\sqrt6+\\sqrt2}{4}$.", true));
  q.push(tf("medium", "$\\sin(A+B)=\\tfrac{56}{65}$ for the given values.", true));
  q.push(tf("medium", "$\\cos 75^\\circ=\\tfrac{\\sqrt6+\\sqrt2}{4}$.", false));
  q.push(fill("medium", "$\\sin 75^\\circ$.", ["(sqrt6+sqrt2)/4", "(√6+√2)/4"]));
  q.push(fill("medium", "$\\cos 75^\\circ$.", ["(sqrt6-sqrt2)/4", "(√6-√2)/4"]));
  q.push(fill("medium", "$\\sin(A+B)$ for the given values.", ["56/65"]));
  q.push(num("medium", "$\\sin(A+B)$ numerator (over 65) for the given values.", 56, 0));
  q.push(num("medium", "$\\cos(A+B)$ numerator (over 65) for the given values.", 33, 0));
  q.push(num("medium", "Numerator of $\\sin 75^\\circ$ written as $\\tfrac{\\sqrt6+\\sqrt2}{n}$, the $n$.", 4, 0));
  q.push(match("medium", "Match each to its value.", ["$\\sin 75^\\circ$", "$\\cos 75^\\circ$", "$\\sin 15^\\circ$"], ["$\\tfrac{\\sqrt6+\\sqrt2}{4}$", "$\\tfrac{\\sqrt6-\\sqrt2}{4}$", "$\\tfrac{\\sqrt6-\\sqrt2}{4}$"], [0, 1, 2]));
  q.push(mc("hard", "Same values: $\\sin(A-B)=$", ["$\\tfrac{16}{65}$", "$\\tfrac{56}{65}$", "$\\tfrac{33}{65}$", "$\\tfrac{63}{65}$"], 0));
  q.push(mc("hard", "$\\tan(A+B)=$", ["$\\tfrac{\\tan A+\\tan B}{1-\\tan A\\tan B}$", "$\\tan A+\\tan B$", "$\\tfrac{\\tan A-\\tan B}{1+\\tan A\\tan B}$", "$\\tan A\\tan B$"], 0));
  q.push(mc("hard", "$\\cos 105^\\circ=$", ["$\\tfrac{\\sqrt2-\\sqrt6}{4}$", "$\\tfrac{\\sqrt6+\\sqrt2}{4}$", "$\\tfrac{\\sqrt6-\\sqrt2}{4}$", "$\\tfrac12$"], 0));
  q.push(mc("hard", "$\\sin A\\cos B-\\cos A\\sin B=$", ["$\\sin(A-B)$", "$\\sin(A+B)$", "$\\cos(A-B)$", "$\\cos(A+B)$"], 0));
  q.push(mc("hard", "$\\sin 105^\\circ=$", ["$\\tfrac{\\sqrt6+\\sqrt2}{4}$", "$\\tfrac{\\sqrt6-\\sqrt2}{4}$", "$\\tfrac12$", "$\\tfrac{\\sqrt3}{2}$"], 0));
  q.push(ms("hard", "$\\sin(A-B)$ with values:", ["$\\sin A\\cos B-\\cos A\\sin B$", "$\\tfrac35\\cdot\\tfrac{12}{13}-\\tfrac45\\cdot\\tfrac5{13}$", "$\\tfrac{16}{65}$", "$\\tfrac{56}{65}$"], [0, 1, 2]));
  q.push(ms("hard", "$\\cos 105^\\circ=\\cos(60+45)$:", ["$\\cos60\\cos45-\\sin60\\sin45$", "$\\tfrac{\\sqrt2}{4}-\\tfrac{\\sqrt6}{4}$", "$\\tfrac{\\sqrt2-\\sqrt6}{4}$", "$\\tfrac{\\sqrt6+\\sqrt2}{4}$"], [0, 1, 2]));
  q.push(ms("hard", "$\\tan(A+B)$:", ["$\\tfrac{\\tan A+\\tan B}{1-\\tan A\\tan B}$", "from $\\sin/\\cos$ of the sum", "denominator has $1-\\tan A\\tan B$", "numerator $\\tan A\\tan B$"], [0, 1, 2]));
  q.push(ms("hard", "$\\sin 105^\\circ$:", ["$\\sin(60+45)$", "$\\sin60\\cos45+\\cos60\\sin45$", "$\\tfrac{\\sqrt6+\\sqrt2}{4}$", "$\\tfrac{\\sqrt6-\\sqrt2}{4}$"], [0, 1, 2]));
  q.push(tf("hard", "$\\sin(A-B)=\\tfrac{16}{65}$ for the given values.", true));
  q.push(tf("hard", "$\\cos 105^\\circ=\\tfrac{\\sqrt2-\\sqrt6}{4}$.", true));
  q.push(tf("hard", "$\\tan(A+B)=\\tan A+\\tan B$.", false));
  q.push(fill("hard", "$\\sin(A-B)$ for the given values.", ["16/65"]));
  q.push(fill("hard", "$\\sin 105^\\circ$.", ["(sqrt6+sqrt2)/4", "(√6+√2)/4"]));
  q.push(fill("hard", "$\\cos 105^\\circ$.", ["(sqrt2-sqrt6)/4", "(√2-√6)/4"]));
  q.push(num("hard", "$\\sin(A-B)$ numerator (over 65) for the given values.", 16, 0));
  q.push(num("hard", "$\\cos(A-B)$ numerator (over 65) for the given values.", 63, 0));
  q.push(num("hard", "In $\\tan(A+B)$, the denominator is $1-\\tan A\\tan B$; for $\\tan A=\\tan B=1$ this equals.", 0, 0));
  q.push(order("hard", "Order the steps to find $\\sin 75^\\circ$.", ["Write $75=45+30$", "$\\sin45\\cos30+\\cos45\\sin30$", "$\\tfrac{\\sqrt6}{4}+\\tfrac{\\sqrt2}{4}$", "$\\tfrac{\\sqrt6+\\sqrt2}{4}$"]));
  q.push(match("hard", "Match each to its value (given the standard values).", ["$\\sin(A+B)$", "$\\cos(A+B)$", "$\\sin(A-B)$"], ["$\\tfrac{56}{65}$", "$\\tfrac{33}{65}$", "$\\tfrac{16}{65}$"], [0, 1, 2]));
  return q;
}

// ── 6.2 Double Angle Formulas ────────────────────────────────
function g62() {
  const q = [];
  q.push(mc("easy", "$\\sin 2\\theta=$", ["$2\\sin\\theta\\cos\\theta$", "$2\\sin\\theta$", "$\\sin^2\\theta$", "$\\cos^2\\theta-\\sin^2\\theta$"], 0));
  q.push(mc("easy", "$2\\sin x\\cos x=$", ["$\\sin 2x$", "$\\cos 2x$", "$\\sin x$", "$2\\sin x$"], 0));
  q.push(mc("easy", "$\\cos 2\\theta=$", ["$\\cos^2\\theta-\\sin^2\\theta$", "$2\\cos\\theta$", "$2\\sin\\theta\\cos\\theta$", "$1+2\\sin^2\\theta$"], 0));
  q.push(mc("easy", "$1-2\\sin^2 x=$", ["$\\cos 2x$", "$\\sin 2x$", "$\\cos x$", "$1$"], 0));
  q.push(mc("easy", "$2\\cos^2 x-1=$", ["$\\cos 2x$", "$\\sin 2x$", "$\\cos x$", "$-1$"], 0));
  q.push(mc("easy", "The double angle formulas come from:", ["compound angles with $B=A$", "the quotient identity", "the Pythagorean identity", "a calculator"], 0));
  q.push(ms("easy", "Double angle formulas:", ["$\\sin2\\theta=2\\sin\\theta\\cos\\theta$", "$\\cos2\\theta=\\cos^2\\theta-\\sin^2\\theta$", "$\\cos2\\theta=1-2\\sin^2\\theta$", "$\\sin2\\theta=2\\sin\\theta$"], [0, 1, 2]));
  q.push(ms("easy", "Forms of $\\cos2\\theta$:", ["$\\cos^2\\theta-\\sin^2\\theta$", "$1-2\\sin^2\\theta$", "$2\\cos^2\\theta-1$", "$2\\sin\\theta\\cos\\theta$"], [0, 1, 2]));
  q.push(ms("easy", "Recognizing:", ["$2\\sin x\\cos x=\\sin2x$", "$1-2\\sin^2 x=\\cos2x$", "$2\\cos^2 x-1=\\cos2x$", "$2\\sin x\\cos x=\\cos2x$"], [0, 1, 2]));
  q.push(ms("easy", "Origin:", ["set $B=A$ in $\\sin(A+B)$", "gives $\\sin2A$", "similarly for cosine", "unrelated to compound angles"], [0, 1, 2]));
  q.push(tf("easy", "$\\sin2\\theta=2\\sin\\theta\\cos\\theta$.", true));
  q.push(tf("easy", "$2\\sin x\\cos x=\\cos 2x$.", false));
  q.push(tf("easy", "$2\\cos^2 x-1=\\cos 2x$.", true));
  q.push(fill("easy", "$2\\sin x\\cos x=$", ["sin2x", "sin(2x)"]));
  q.push(fill("easy", "$1-2\\sin^2 x=$", ["cos2x", "cos(2x)"]));
  q.push(fill("easy", "$\\cos^2 x-\\sin^2 x=$", ["cos2x", "cos(2x)"]));
  q.push(num("easy", "If $\\sin\\theta=\\tfrac35,\\cos\\theta=\\tfrac45$, $\\sin2\\theta=\\tfrac{n}{25}$; the $n$.", 24, 0));
  q.push(num("easy", "Number of equivalent forms of $\\cos2\\theta$ shown.", 3, 0));
  q.push(num("easy", "If $\\sin\\theta=\\tfrac35$, $\\cos2\\theta=\\tfrac{n}{25}$; the $n$.", 7, 0));
  q.push(match("easy", "Match each to its simplified form.", ["$2\\sin x\\cos x$", "$1-2\\sin^2 x$", "$2\\cos^2 x-1$"], ["$\\sin2x$", "$\\cos2x$", "$\\cos2x$"], [0, 1, 2]));
  q.push(mc("medium", "If $\\sin\\theta=\\tfrac35,\\cos\\theta=\\tfrac45$, $\\sin2\\theta=$", ["$\\tfrac{24}{25}$", "$\\tfrac7{25}$", "$\\tfrac{12}{25}$", "$\\tfrac{6}{5}$"], 0));
  q.push(mc("medium", "If $\\sin\\theta=\\tfrac35$, $\\cos2\\theta=$", ["$\\tfrac7{25}$", "$-\\tfrac7{25}$", "$\\tfrac{24}{25}$", "$\\tfrac{18}{25}$"], 0));
  q.push(mc("medium", "If $\\sin\\theta=\\tfrac5{13},\\cos\\theta=\\tfrac{12}{13}$, $\\sin2\\theta=$", ["$\\tfrac{120}{169}$", "$\\tfrac{119}{169}$", "$\\tfrac{60}{169}$", "$\\tfrac{10}{13}$"], 0));
  q.push(mc("medium", "If $\\cos\\theta=\\tfrac35$, $\\cos2\\theta=$", ["$-\\tfrac7{25}$", "$\\tfrac7{25}$", "$\\tfrac{24}{25}$", "$\\tfrac{18}{25}$"], 0));
  q.push(mc("medium", "$\\dfrac{\\sin 2x}{2\\cos x}=$", ["$\\sin x$", "$\\cos x$", "$\\tan x$", "$2\\sin x$"], 0));
  q.push(mc("medium", "$\\dfrac{2\\tan x}{1-\\tan^2 x}=$", ["$\\tan 2x$", "$\\sin 2x$", "$\\cos 2x$", "$2\\tan x$"], 0));
  q.push(ms("medium", "$\\sin2\\theta$ from values:", ["$2\\sin\\theta\\cos\\theta$", "$2\\cdot\\tfrac35\\cdot\\tfrac45$", "$\\tfrac{24}{25}$", "$\\tfrac7{25}$"], [0, 1, 2]));
  q.push(ms("medium", "$\\cos2\\theta$ from $\\sin\\theta=\\tfrac35$:", ["$1-2\\sin^2\\theta$", "$1-\\tfrac{18}{25}$", "$\\tfrac7{25}$", "$-\\tfrac7{25}$"], [0, 1, 2]));
  q.push(ms("medium", "Simplifying $\\tfrac{\\sin2x}{2\\cos x}$:", ["expand $\\sin2x=2\\sin x\\cos x$", "cancel $2\\cos x$", "$=\\sin x$", "$=\\cos x$"], [0, 1, 2]));
  q.push(ms("medium", "$\\cos2\\theta$ from $\\cos\\theta=\\tfrac35$:", ["$2\\cos^2\\theta-1$", "$2\\cdot\\tfrac9{25}-1$", "$-\\tfrac7{25}$", "$\\tfrac7{25}$"], [0, 1, 2]));
  q.push(tf("medium", "$\\sin2\\theta=\\tfrac{24}{25}$ when $\\sin\\theta=\\tfrac35,\\cos\\theta=\\tfrac45$.", true));
  q.push(tf("medium", "$\\dfrac{\\sin2x}{2\\cos x}=\\sin x$.", true));
  q.push(tf("medium", "If $\\cos\\theta=\\tfrac35$, $\\cos2\\theta=\\tfrac7{25}$.", false));
  q.push(fill("medium", "$\\sin2\\theta$ if $\\sin\\theta=\\tfrac35,\\cos\\theta=\\tfrac45$.", ["24/25"]));
  q.push(fill("medium", "$\\cos2\\theta$ if $\\sin\\theta=\\tfrac35$.", ["7/25"]));
  q.push(fill("medium", "$\\dfrac{\\sin2x}{2\\cos x}$.", ["sin x", "sinx"]));
  q.push(num("medium", "$\\sin2\\theta$ numerator (over 169) if $\\sin\\theta=\\tfrac5{13},\\cos\\theta=\\tfrac{12}{13}$.", 120, 0));
  q.push(num("medium", "$\\cos2\\theta$ numerator (over 25, signed) if $\\cos\\theta=\\tfrac35$.", -7, 0));
  q.push(num("medium", "$\\sin2\\theta$ numerator (over 25) if $\\sin\\theta=\\tfrac35,\\cos\\theta=\\tfrac45$.", 24, 0));
  q.push(match("medium", "Match each simplification.", ["$\\tfrac{\\sin2x}{2\\cos x}$", "$\\tfrac{2\\tan x}{1-\\tan^2 x}$", "$\\cos^2 x-\\sin^2 x$"], ["$\\sin x$", "$\\tan 2x$", "$\\cos 2x$"], [0, 1, 2]));
  q.push(mc("hard", "If $\\sin\\theta=\\tfrac35$ ($\\theta$ in QI), $\\cos2\\theta=$", ["$\\tfrac7{25}$", "$-\\tfrac7{25}$", "$\\tfrac{24}{25}$", "$\\tfrac{18}{25}$"], 0));
  q.push(mc("hard", "If $\\cos\\theta=-\\tfrac35$ ($\\theta$ in QII), $\\sin2\\theta=$", ["$-\\tfrac{24}{25}$", "$\\tfrac{24}{25}$", "$\\tfrac7{25}$", "$-\\tfrac7{25}$"], 0));
  q.push(mc("hard", "$1+\\cos 2x=$", ["$2\\cos^2 x$", "$2\\sin^2 x$", "$\\cos^2 x$", "$1$"], 0));
  q.push(mc("hard", "$1-\\cos 2x=$", ["$2\\sin^2 x$", "$2\\cos^2 x$", "$\\sin^2 x$", "$1$"], 0));
  q.push(mc("hard", "$\\sin 2x=\\tfrac12$ has how many solutions on $[0,2\\pi)$?", ["4", "2", "1", "3"], 0));
  q.push(ms("hard", "$\\sin2\\theta$ in QII ($\\cos\\theta=-\\tfrac35,\\sin\\theta=\\tfrac45$):", ["$2\\sin\\theta\\cos\\theta$", "$2\\cdot\\tfrac45\\cdot(-\\tfrac35)$", "$-\\tfrac{24}{25}$", "$\\tfrac{24}{25}$"], [0, 1, 2]));
  q.push(ms("hard", "$1+\\cos 2x$:", ["use $\\cos2x=2\\cos^2 x-1$", "$1+2\\cos^2 x-1$", "$=2\\cos^2 x$", "$=2\\sin^2 x$"], [0, 1, 2]));
  q.push(ms("hard", "$1-\\cos 2x$:", ["use $\\cos2x=1-2\\sin^2 x$", "$1-(1-2\\sin^2 x)$", "$=2\\sin^2 x$", "$=2\\cos^2 x$"], [0, 1, 2]));
  q.push(ms("hard", "$\\sin 2x=\\tfrac12$ on $[0,2\\pi)$:", ["let $u=2x\\in[0,4\\pi)$", "$\\sin u=\\tfrac12$ four times", "4 solutions for $x$", "only 2 solutions"], [0, 1, 2]));
  q.push(tf("hard", "$1+\\cos 2x=2\\cos^2 x$.", true));
  q.push(tf("hard", "If $\\cos\\theta=-\\tfrac35,\\sin\\theta=\\tfrac45$, $\\sin2\\theta=-\\tfrac{24}{25}$.", true));
  q.push(tf("hard", "$\\sin 2x=\\tfrac12$ has 2 solutions on $[0,2\\pi)$.", false));
  q.push(fill("hard", "$1+\\cos 2x=$", ["2cos^2 x", "2(cos x)^2"]));
  q.push(fill("hard", "$1-\\cos 2x=$", ["2sin^2 x", "2(sin x)^2"]));
  q.push(fill("hard", "$\\sin2\\theta$ if $\\cos\\theta=-\\tfrac35,\\sin\\theta=\\tfrac45$.", ["-24/25"]));
  q.push(num("hard", "Number of solutions of $\\sin 2x=\\tfrac12$ on $[0,2\\pi)$.", 4, 0));
  q.push(num("hard", "$\\sin2\\theta$ numerator (over 25, signed) if $\\cos\\theta=-\\tfrac35,\\sin\\theta=\\tfrac45$.", -24, 0));
  q.push(num("hard", "$\\cos2\\theta$ numerator (over 25) if $\\sin\\theta=\\tfrac35$ in QI.", 7, 0));
  q.push(order("hard", "Order the steps to find $\\cos2\\theta$ given $\\sin\\theta=\\tfrac35$.", ["Choose $\\cos2\\theta=1-2\\sin^2\\theta$", "Substitute $\\sin\\theta=\\tfrac35$", "$1-2\\cdot\\tfrac9{25}$", "$=\\tfrac7{25}$"]));
  q.push(match("hard", "Match each to its simplified form.", ["$1+\\cos2x$", "$1-\\cos2x$", "$2\\sin x\\cos x$"], ["$2\\cos^2 x$", "$2\\sin^2 x$", "$\\sin2x$"], [0, 1, 2]));
  return q;
}

// ── 6.3 Proving Trigonometric Identities ─────────────────────
function g63() {
  const q = [];
  q.push(mc("easy", "$\\sin^2\\theta+\\cos^2\\theta=$", ["1", "0", "$2$", "$\\tan\\theta$"], 0));
  q.push(mc("easy", "$\\tan\\theta=$", ["$\\tfrac{\\sin\\theta}{\\cos\\theta}$", "$\\tfrac{\\cos\\theta}{\\sin\\theta}$", "$\\tfrac1{\\sin\\theta}$", "$\\sin\\theta\\cos\\theta$"], 0));
  q.push(mc("easy", "$1-\\cos^2 x=$", ["$\\sin^2 x$", "$\\cos^2 x$", "$\\tan^2 x$", "$1$"], 0));
  q.push(mc("easy", "To prove an identity you:", ["transform one side", "move terms across $=$", "add to both sides", "plug in one value"], 0));
  q.push(mc("easy", "$\\tan x\\cos x=$", ["$\\sin x$", "$\\cos x$", "$1$", "$\\sec x$"], 0));
  q.push(mc("easy", "$1+\\tan^2\\theta=$", ["$\\sec^2\\theta$", "$\\csc^2\\theta$", "$1$", "$\\cot^2\\theta$"], 0));
  q.push(ms("easy", "Core identities:", ["$\\sin^2+\\cos^2=1$", "$1+\\tan^2=\\sec^2$", "$1+\\cot^2=\\csc^2$", "$\\sin^2-\\cos^2=1$"], [0, 1, 2]));
  q.push(ms("easy", "Quotient identities:", ["$\\tan=\\tfrac{\\sin}{\\cos}$", "$\\cot=\\tfrac{\\cos}{\\sin}$", "useful in proofs", "$\\tan=\\tfrac{\\cos}{\\sin}$"], [0, 1, 2]));
  q.push(ms("easy", "Proof strategy:", ["work one side only", "rewrite in sin and cos", "start with the harder side", "rearrange across $=$"], [0, 1, 2]));
  q.push(ms("easy", "$\\tan x\\cos x$:", ["$=\\tfrac{\\sin x}{\\cos x}\\cos x$", "cancel $\\cos x$", "$=\\sin x$", "$=\\cos x$"], [0, 1, 2]));
  q.push(tf("easy", "$\\sin^2\\theta+\\cos^2\\theta=1$.", true));
  q.push(tf("easy", "You may move terms across the equals sign when proving an identity.", false));
  q.push(tf("easy", "$\\tan x\\cos x=\\sin x$.", true));
  q.push(fill("easy", "$1-\\cos^2 x=$", ["sin^2 x", "(sin x)^2"]));
  q.push(fill("easy", "$\\tan\\theta=\\dfrac{?}{\\cos\\theta}$", ["sin theta", "sinθ", "sin θ"]));
  q.push(fill("easy", "$\\sin^2\\theta+\\cos^2\\theta=$", ["1"]));
  q.push(num("easy", "Value of $\\sin^2\\theta+\\cos^2\\theta$.", 1, 0));
  q.push(num("easy", "Value of $\\tan x\\cos x\\div\\sin x$ (when defined).", 1, 0));
  q.push(num("easy", "Value of $(1-\\cos^2 x)\\div\\sin^2 x$ (when defined).", 1, 0));
  q.push(match("easy", "Match each identity.", ["$\\sin^2+\\cos^2$", "$1+\\tan^2$", "$1+\\cot^2$"], ["$1$", "$\\sec^2$", "$\\csc^2$"], [0, 1, 2]));
  q.push(mc("medium", "$\\dfrac{\\sec x}{\\csc x}=$", ["$\\tan x$", "$\\cot x$", "$1$", "$\\sin x$"], 0));
  q.push(mc("medium", "$\\csc x\\tan x=$", ["$\\sec x$", "$\\csc x$", "$\\cot x$", "$1$"], 0));
  q.push(mc("medium", "$1+\\cot^2 x=$", ["$\\csc^2 x$", "$\\sec^2 x$", "$\\tan^2 x$", "$1$"], 0));
  q.push(mc("medium", "$\\cot x\\sin x=$", ["$\\cos x$", "$\\sin x$", "$1$", "$\\tan x$"], 0));
  q.push(mc("medium", "$\\sin x\\sec x=$", ["$\\tan x$", "$\\cot x$", "$1$", "$\\cos x$"], 0));
  q.push(mc("medium", "$\\dfrac{1-\\cos^2 x}{\\sin x}=$", ["$\\sin x$", "$\\cos x$", "$\\tan x$", "$1$"], 0));
  q.push(ms("medium", "$\\dfrac{\\sec x}{\\csc x}$:", ["$\\tfrac{1/\\cos x}{1/\\sin x}$", "$=\\tfrac{\\sin x}{\\cos x}$", "$=\\tan x$", "$=\\cot x$"], [0, 1, 2]));
  q.push(ms("medium", "$\\csc x\\tan x$:", ["$\\tfrac1{\\sin x}\\cdot\\tfrac{\\sin x}{\\cos x}$", "cancel $\\sin x$", "$=\\sec x$", "$=\\csc x$"], [0, 1, 2]));
  q.push(ms("medium", "$1+\\cot^2 x=\\csc^2 x$:", ["divide $\\sin^2+\\cos^2=1$ by $\\sin^2 x$", "$1+\\cot^2 x$", "$=\\csc^2 x$", "by $\\cos^2 x$"], [0, 1, 2]));
  q.push(ms("medium", "$\\dfrac{1-\\cos^2 x}{\\sin x}$:", ["$1-\\cos^2 x=\\sin^2 x$", "$\\tfrac{\\sin^2 x}{\\sin x}$", "$=\\sin x$", "$=\\cos x$"], [0, 1, 2]));
  q.push(tf("medium", "$\\dfrac{\\sec x}{\\csc x}=\\tan x$.", true));
  q.push(tf("medium", "$\\cot x\\sin x=\\cos x$.", true));
  q.push(tf("medium", "$\\csc x\\tan x=\\csc x$.", false));
  q.push(fill("medium", "$\\dfrac{\\sec x}{\\csc x}=$", ["tan x", "tanx"]));
  q.push(fill("medium", "$\\csc x\\tan x=$", ["sec x", "secx"]));
  q.push(fill("medium", "$\\cot x\\sin x=$", ["cos x", "cosx"]));
  q.push(num("medium", "$(\\csc x\\tan x)\\div\\sec x$ (when defined).", 1, 0));
  q.push(num("medium", "$(\\cot x\\sin x)\\div\\cos x$ (when defined).", 1, 0));
  q.push(num("medium", "$(\\sin x\\sec x)\\div\\tan x$ (when defined).", 1, 0));
  q.push(match("medium", "Match each to its result.", ["$\\sec x\\cot x$", "$\\csc x\\tan x$", "$\\sin x\\sec x$"], ["$\\csc x$", "$\\sec x$", "$\\tan x$"], [0, 1, 2]));
  q.push(mc("hard", "$\\dfrac{1}{1-\\sin x}+\\dfrac{1}{1+\\sin x}=$", ["$2\\sec^2 x$", "$\\sec^2 x$", "$2\\csc^2 x$", "$2$"], 0));
  q.push(mc("hard", "$(1+\\tan^2 x)\\cos^2 x=$", ["$1$", "$\\sin^2 x$", "$\\sec^2 x$", "$\\cos^2 x$"], 0));
  q.push(mc("hard", "$\\dfrac{\\sin x}{1+\\cos x}+\\dfrac{1+\\cos x}{\\sin x}=$", ["$2\\csc x$", "$2\\sec x$", "$\\csc x$", "$2$"], 0));
  q.push(mc("hard", "$\\sec^2 x-\\tan^2 x=$", ["$1$", "$0$", "$\\sec^2 x$", "$2$"], 0));
  q.push(mc("hard", "$\\dfrac{\\cos x}{1-\\sin x}=$", ["$\\dfrac{1+\\sin x}{\\cos x}$", "$\\sec x$", "$\\tan x$", "$1$"], 0));
  q.push(ms("hard", "$\\dfrac{1}{1-\\sin x}+\\dfrac{1}{1+\\sin x}$:", ["common denominator $1-\\sin^2 x$", "$=\\tfrac{2}{\\cos^2 x}$", "$=2\\sec^2 x$", "$=\\sec^2 x$"], [0, 1, 2]));
  q.push(ms("hard", "$(1+\\tan^2 x)\\cos^2 x$:", ["$\\sec^2 x\\cdot\\cos^2 x$", "$=\\tfrac1{\\cos^2 x}\\cdot\\cos^2 x$", "$=1$", "$=\\sin^2 x$"], [0, 1, 2]));
  q.push(ms("hard", "$\\dfrac{\\sin x}{1+\\cos x}+\\dfrac{1+\\cos x}{\\sin x}$:", ["common denom $\\sin x(1+\\cos x)$", "numerator $\\sin^2 x+(1+\\cos x)^2$", "simplifies using $\\sin^2+\\cos^2=1$", "$=2\\csc x$"], [0, 1, 2, 3]));
  q.push(ms("hard", "$\\sec^2 x-\\tan^2 x$:", ["from $1+\\tan^2 x=\\sec^2 x$", "$\\sec^2 x-\\tan^2 x=1$", "always 1", "$=0$"], [0, 1, 2]));
  q.push(tf("hard", "$(1+\\tan^2 x)\\cos^2 x=1$.", true));
  q.push(tf("hard", "$\\sec^2 x-\\tan^2 x=1$.", true));
  q.push(tf("hard", "$\\dfrac{1}{1-\\sin x}+\\dfrac{1}{1+\\sin x}=\\sec^2 x$.", false));
  q.push(fill("hard", "$\\dfrac{1}{1-\\sin x}+\\dfrac{1}{1+\\sin x}=$", ["2sec^2 x", "2/(cos x)^2"]));
  q.push(fill("hard", "$(1+\\tan^2 x)\\cos^2 x=$", ["1"]));
  q.push(fill("hard", "$\\sec^2 x-\\tan^2 x=$", ["1"]));
  q.push(num("hard", "Value of $(1+\\tan^2 x)\\cos^2 x$.", 1, 0));
  q.push(num("hard", "Value of $\\sec^2 x-\\tan^2 x$.", 1, 0));
  q.push(num("hard", "Coefficient of $\\sec^2 x$ in $\\tfrac1{1-\\sin x}+\\tfrac1{1+\\sin x}$.", 2, 0));
  q.push(order("hard", "Order the steps to prove $\\tfrac1{1-\\sin x}+\\tfrac1{1+\\sin x}=2\\sec^2 x$.", ["Common denominator $1-\\sin^2 x$", "Numerator $(1+\\sin x)+(1-\\sin x)=2$", "$\\tfrac{2}{1-\\sin^2 x}=\\tfrac{2}{\\cos^2 x}$", "$=2\\sec^2 x$"]));
  q.push(match("hard", "Match each to its simplified value.", ["$(1+\\tan^2 x)\\cos^2 x$", "$\\sec^2 x-\\tan^2 x$", "$\\tfrac1{1-\\sin x}+\\tfrac1{1+\\sin x}$"], ["$1$", "$1$", "$2\\sec^2 x$"], [0, 1, 2]));
  return q;
}

// ── 6.4 Solving Trigonometric Equations ──────────────────────
function g64() {
  const q = [];
  q.push(mc("easy", "Solve $\\sin\\theta=\\tfrac12$ on $[0,2\\pi)$:", ["$\\tfrac{\\pi}{6},\\tfrac{5\\pi}{6}$", "$\\tfrac{\\pi}{6}$", "$\\tfrac{\\pi}{3},\\tfrac{2\\pi}{3}$", "$\\tfrac{\\pi}{6},\\tfrac{7\\pi}{6}$"], 0));
  q.push(mc("easy", "Solve $\\cos\\theta=0$ on $[0,2\\pi)$:", ["$\\tfrac{\\pi}{2},\\tfrac{3\\pi}{2}$", "$0,\\pi$", "$\\tfrac{\\pi}{2}$", "$\\pi$"], 0));
  q.push(mc("easy", "Solve $\\sin\\theta=0$ on $[0,2\\pi)$:", ["$0,\\pi$", "$\\tfrac{\\pi}{2},\\tfrac{3\\pi}{2}$", "$0$", "$\\pi,2\\pi$"], 0));
  q.push(mc("easy", "First step in solving:", ["isolate the trig ratio", "graph it", "square both sides", "differentiate"], 0));
  q.push(mc("easy", "Solve $\\tan\\theta=1$ on $[0,2\\pi)$:", ["$\\tfrac{\\pi}{4},\\tfrac{5\\pi}{4}$", "$\\tfrac{\\pi}{4}$", "$\\tfrac{\\pi}{4},\\tfrac{3\\pi}{4}$", "$\\tfrac{3\\pi}{4},\\tfrac{7\\pi}{4}$"], 0));
  q.push(mc("easy", "$\\sin\\theta=\\tfrac12$ is positive in quadrants:", ["I and II", "I and IV", "III and IV", "II and III"], 0));
  q.push(ms("easy", "Solving method:", ["isolate the ratio", "find the related angle", "use CAST for quadrants", "use only QI"], [0, 1, 2]));
  q.push(ms("easy", "$\\sin\\theta=\\tfrac12$:", ["related angle $\\tfrac{\\pi}{6}$", "sine $+$ in QI, QII", "$\\theta=\\tfrac{\\pi}{6},\\tfrac{5\\pi}{6}$", "only $\\tfrac{\\pi}{6}$"], [0, 1, 2]));
  q.push(ms("easy", "Number of solutions:", ["usually two per period", "one per quadrant with the right sign", "quadrantal cases differ", "always one"], [0, 1, 2]));
  q.push(ms("easy", "$\\cos\\theta=0$:", ["on the y-axis", "$\\theta=\\tfrac{\\pi}{2},\\tfrac{3\\pi}{2}$", "two solutions", "$\\theta=0,\\pi$"], [0, 1, 2]));
  q.push(tf("easy", "$\\sin\\theta=\\tfrac12$ has solutions $\\tfrac{\\pi}{6},\\tfrac{5\\pi}{6}$.", true));
  q.push(tf("easy", "$\\cos\\theta=0$ at $\\theta=0,\\pi$.", false));
  q.push(tf("easy", "The first step is to isolate the trig ratio.", true));
  q.push(fill("easy", "Solve $\\sin\\theta=\\tfrac12$ on $[0,2\\pi)$.", ["pi/6, 5pi/6", "π/6, 5π/6"]));
  q.push(fill("easy", "Solve $\\cos\\theta=0$ on $[0,2\\pi)$.", ["pi/2, 3pi/2", "π/2, 3π/2"]));
  q.push(fill("easy", "Solve $\\sin\\theta=0$ on $[0,2\\pi)$.", ["0, pi", "0, π"]));
  q.push(num("easy", "Number of solutions of $\\sin\\theta=\\tfrac12$ on $[0,2\\pi)$.", 2, 0));
  q.push(num("easy", "Number of solutions of $\\cos\\theta=0$ on $[0,2\\pi)$.", 2, 0));
  q.push(num("easy", "Number of solutions of $\\sin\\theta=1$ on $[0,2\\pi)$.", 1, 0));
  q.push(match("easy", "Match each equation to its solutions.", ["$\\sin\\theta=\\tfrac12$", "$\\cos\\theta=0$", "$\\sin\\theta=0$"], ["$\\tfrac{\\pi}{6},\\tfrac{5\\pi}{6}$", "$\\tfrac{\\pi}{2},\\tfrac{3\\pi}{2}$", "$0,\\pi$"], [0, 1, 2]));
  q.push(mc("medium", "Solve $2\\cos\\theta-1=0$ on $[0,2\\pi)$:", ["$\\tfrac{\\pi}{3},\\tfrac{5\\pi}{3}$", "$\\tfrac{\\pi}{3},\\tfrac{2\\pi}{3}$", "$\\tfrac{\\pi}{6},\\tfrac{11\\pi}{6}$", "$\\tfrac{\\pi}{3}$"], 0));
  q.push(mc("medium", "Solve $2\\sin\\theta+1=0$ on $[0,2\\pi)$:", ["$\\tfrac{7\\pi}{6},\\tfrac{11\\pi}{6}$", "$\\tfrac{\\pi}{6},\\tfrac{5\\pi}{6}$", "$\\tfrac{5\\pi}{6},\\tfrac{7\\pi}{6}$", "$\\tfrac{\\pi}{6}$"], 0));
  q.push(mc("medium", "Solve $\\tan\\theta=-1$ on $[0,2\\pi)$:", ["$\\tfrac{3\\pi}{4},\\tfrac{7\\pi}{4}$", "$\\tfrac{\\pi}{4},\\tfrac{5\\pi}{4}$", "$\\tfrac{3\\pi}{4},\\tfrac{5\\pi}{4}$", "$\\tfrac{\\pi}{4}$"], 0));
  q.push(mc("medium", "Solve $\\cos\\theta=\\tfrac12$ on $[0,2\\pi)$:", ["$\\tfrac{\\pi}{3},\\tfrac{5\\pi}{3}$", "$\\tfrac{\\pi}{3},\\tfrac{2\\pi}{3}$", "$\\tfrac{\\pi}{6},\\tfrac{11\\pi}{6}$", "$\\tfrac{\\pi}{3}$"], 0));
  q.push(mc("medium", "Solve $\\sin\\theta(\\sin\\theta-1)=0$ on $[0,2\\pi)$:", ["$0,\\pi,\\tfrac{\\pi}{2}$", "$0,\\pi$", "$\\tfrac{\\pi}{2}$", "$0,\\tfrac{\\pi}{2},\\pi,\\tfrac{3\\pi}{2}$"], 0));
  q.push(mc("medium", "Solve $\\cos\\theta=-1$ on $[0,2\\pi)$:", ["$\\pi$", "$0$", "$\\tfrac{\\pi}{2}$", "$0,\\pi$"], 0));
  q.push(ms("medium", "$2\\cos\\theta-1=0$:", ["$\\cos\\theta=\\tfrac12$", "related angle $\\tfrac{\\pi}{3}$", "$+$ in QI, QIV", "$\\theta=\\tfrac{\\pi}{3},\\tfrac{5\\pi}{3}$"], [0, 1, 2, 3]));
  q.push(ms("medium", "$2\\sin\\theta+1=0$:", ["$\\sin\\theta=-\\tfrac12$", "negative in QIII, QIV", "$\\theta=\\tfrac{7\\pi}{6},\\tfrac{11\\pi}{6}$", "$\\theta=\\tfrac{\\pi}{6},\\tfrac{5\\pi}{6}$"], [0, 1, 2]));
  q.push(ms("medium", "Factored equation $\\sin\\theta(\\sin\\theta-1)=0$:", ["$\\sin\\theta=0\\Rightarrow0,\\pi$", "$\\sin\\theta=1\\Rightarrow\\tfrac{\\pi}{2}$", "combine all", "only $\\tfrac{\\pi}{2}$"], [0, 1, 2]));
  q.push(ms("medium", "$\\tan\\theta=-1$:", ["related angle $\\tfrac{\\pi}{4}$", "negative in QII, QIV", "$\\theta=\\tfrac{3\\pi}{4},\\tfrac{7\\pi}{4}$", "$\\theta=\\tfrac{\\pi}{4},\\tfrac{5\\pi}{4}$"], [0, 1, 2]));
  q.push(tf("medium", "$2\\cos\\theta-1=0$ gives $\\theta=\\tfrac{\\pi}{3},\\tfrac{5\\pi}{3}$.", true));
  q.push(tf("medium", "$2\\sin\\theta+1=0$ gives $\\theta=\\tfrac{7\\pi}{6},\\tfrac{11\\pi}{6}$.", true));
  q.push(tf("medium", "$\\tan\\theta=-1$ gives $\\theta=\\tfrac{\\pi}{4},\\tfrac{5\\pi}{4}$.", false));
  q.push(fill("medium", "Solve $2\\cos\\theta-1=0$ on $[0,2\\pi)$.", ["pi/3, 5pi/3", "π/3, 5π/3"]));
  q.push(fill("medium", "Solve $2\\sin\\theta+1=0$ on $[0,2\\pi)$.", ["7pi/6, 11pi/6", "7π/6, 11π/6"]));
  q.push(fill("medium", "Solve $\\tan\\theta=-1$ on $[0,2\\pi)$.", ["3pi/4, 7pi/4", "3π/4, 7π/4"]));
  q.push(num("medium", "Number of solutions of $\\sin\\theta(\\sin\\theta-1)=0$ on $[0,2\\pi)$.", 3, 0));
  q.push(num("medium", "Number of solutions of $\\cos\\theta=-1$ on $[0,2\\pi)$.", 1, 0));
  q.push(num("medium", "Number of solutions of $2\\cos\\theta-1=0$ on $[0,2\\pi)$.", 2, 0));
  q.push(match("medium", "Match each equation to its solutions.", ["$2\\cos\\theta-1=0$", "$2\\sin\\theta+1=0$", "$\\tan\\theta=-1$"], ["$\\tfrac{\\pi}{3},\\tfrac{5\\pi}{3}$", "$\\tfrac{7\\pi}{6},\\tfrac{11\\pi}{6}$", "$\\tfrac{3\\pi}{4},\\tfrac{7\\pi}{4}$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $2\\sin^2\\theta-1=0$ on $[0,2\\pi)$:", ["$\\tfrac{\\pi}{4},\\tfrac{3\\pi}{4},\\tfrac{5\\pi}{4},\\tfrac{7\\pi}{4}$", "$\\tfrac{\\pi}{4},\\tfrac{3\\pi}{4}$", "$\\tfrac{\\pi}{4}$", "$\\tfrac{\\pi}{2},\\tfrac{3\\pi}{2}$"], 0));
  q.push(mc("hard", "Solve $2\\cos^2\\theta-\\cos\\theta=0$ on $[0,2\\pi)$:", ["$\\tfrac{\\pi}{2},\\tfrac{3\\pi}{2},\\tfrac{\\pi}{3},\\tfrac{5\\pi}{3}$", "$\\tfrac{\\pi}{3},\\tfrac{5\\pi}{3}$", "$\\tfrac{\\pi}{2},\\tfrac{3\\pi}{2}$", "$0,\\pi$"], 0));
  q.push(mc("hard", "Solve $2\\sin^2\\theta+\\sin\\theta-1=0$ on $[0,2\\pi)$:", ["$\\tfrac{\\pi}{6},\\tfrac{5\\pi}{6},\\tfrac{3\\pi}{2}$", "$\\tfrac{\\pi}{6},\\tfrac{5\\pi}{6}$", "$\\tfrac{3\\pi}{2}$", "$\\tfrac{\\pi}{2}$"], 0));
  q.push(mc("hard", "Solve $\\sin 2\\theta=0$ on $[0,2\\pi)$:", ["$0,\\tfrac{\\pi}{2},\\pi,\\tfrac{3\\pi}{2}$", "$0,\\pi$", "$\\tfrac{\\pi}{2},\\tfrac{3\\pi}{2}$", "$0,\\tfrac{\\pi}{2}$"], 0));
  q.push(mc("hard", "Solve $\\cos^2\\theta=\\tfrac14$ on $[0,2\\pi)$:", ["$\\tfrac{\\pi}{3},\\tfrac{2\\pi}{3},\\tfrac{4\\pi}{3},\\tfrac{5\\pi}{3}$", "$\\tfrac{\\pi}{3},\\tfrac{5\\pi}{3}$", "$\\tfrac{\\pi}{6}$", "$\\tfrac{\\pi}{3},\\tfrac{2\\pi}{3}$"], 0));
  q.push(ms("hard", "$2\\sin^2\\theta-1=0$:", ["$\\sin\\theta=\\pm\\tfrac{\\sqrt2}{2}$", "related angle $\\tfrac{\\pi}{4}$", "all four quadrants", "only QI"], [0, 1, 2]));
  q.push(ms("hard", "$2\\cos^2\\theta-\\cos\\theta=0$:", ["factor $\\cos\\theta(2\\cos\\theta-1)$", "$\\cos\\theta=0\\Rightarrow\\tfrac{\\pi}{2},\\tfrac{3\\pi}{2}$", "$\\cos\\theta=\\tfrac12\\Rightarrow\\tfrac{\\pi}{3},\\tfrac{5\\pi}{3}$", "expand fully"], [0, 1, 2]));
  q.push(ms("hard", "$2\\sin^2\\theta+\\sin\\theta-1=0$:", ["factor $(2\\sin\\theta-1)(\\sin\\theta+1)$", "$\\sin\\theta=\\tfrac12\\Rightarrow\\tfrac{\\pi}{6},\\tfrac{5\\pi}{6}$", "$\\sin\\theta=-1\\Rightarrow\\tfrac{3\\pi}{2}$", "$\\sin\\theta=1$"], [0, 1, 2]));
  q.push(ms("hard", "$\\sin 2\\theta=0$:", ["$2\\theta=0,\\pi,2\\pi,3\\pi$", "$\\theta=0,\\tfrac{\\pi}{2},\\pi,\\tfrac{3\\pi}{2}$", "double angle doubles solutions", "only $0,\\pi$"], [0, 1, 2]));
  q.push(tf("hard", "$2\\sin^2\\theta-1=0$ has four solutions on $[0,2\\pi)$.", true));
  q.push(tf("hard", "$2\\cos^2\\theta-\\cos\\theta=0$ factors as $\\cos\\theta(2\\cos\\theta-1)$.", true));
  q.push(tf("hard", "$\\sin 2\\theta=0$ has only two solutions on $[0,2\\pi)$.", false));
  q.push(fill("hard", "Number of solutions of $2\\sin^2\\theta-1=0$ on $[0,2\\pi)$.", ["4"]));
  q.push(fill("hard", "Factor $2\\cos^2\\theta-\\cos\\theta$.", ["cos theta(2cos theta-1)", "cosθ(2cosθ-1)"]));
  q.push(fill("hard", "Solve $2\\sin^2\\theta+\\sin\\theta-1=0$ on $[0,2\\pi)$.", ["pi/6, 5pi/6, 3pi/2", "π/6, 5π/6, 3π/2"]));
  q.push(num("hard", "Number of solutions of $2\\sin^2\\theta-1=0$ on $[0,2\\pi)$.", 4, 0));
  q.push(num("hard", "Number of solutions of $\\sin 2\\theta=0$ on $[0,2\\pi)$.", 4, 0));
  q.push(num("hard", "Number of solutions of $2\\cos^2\\theta-\\cos\\theta=0$ on $[0,2\\pi)$.", 4, 0));
  q.push(order("hard", "Order the steps to solve $2\\cos^2\\theta-\\cos\\theta=0$.", ["Factor: $\\cos\\theta(2\\cos\\theta-1)=0$", "$\\cos\\theta=0\\Rightarrow\\tfrac{\\pi}{2},\\tfrac{3\\pi}{2}$", "$\\cos\\theta=\\tfrac12\\Rightarrow\\tfrac{\\pi}{3},\\tfrac{5\\pi}{3}$", "Combine all four"]));
  q.push(match("hard", "Match each equation to its number of solutions on $[0,2\\pi)$.", ["$2\\sin^2\\theta-1=0$", "$\\sin\\theta=1$", "$\\sin 2\\theta=0$"], ["$4$", "$1$", "$4$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "6.1", gen: g61 },
  { code: "6.2", gen: g62 },
  { code: "6.3", gen: g63 },
  { code: "6.4", gen: g64 },
];
