// MHF4U Unit 7 — Rates of Change & Combining Functions: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 7.1 Average & Instantaneous Rate of Change ───────────────
function g71() {
  const q = [];
  q.push(mc("easy", "Average rate of change of $f$ on $[a,b]$:", ["$\\dfrac{f(b)-f(a)}{b-a}$", "$f(b)-f(a)$", "$\\dfrac{b-a}{f(b)-f(a)}$", "$f'(a)$"], 0));
  q.push(mc("easy", "The average rate of change is the slope of the:", ["secant line", "tangent line", "x-axis", "asymptote"], 0));
  q.push(mc("easy", "The instantaneous rate of change is the slope of the:", ["tangent line", "secant line", "y-axis", "midline"], 0));
  q.push(mc("easy", "Average rate of $f(x)=x^2$ on $[1,3]$:", ["4", "8", "2", "9"], 0));
  q.push(mc("easy", "A line's rate of change is:", ["constant", "increasing", "zero", "undefined"], 0));
  q.push(mc("easy", "To estimate an instantaneous rate, use:", ["a very small interval", "the whole domain", "two distant points", "the y-intercept"], 0));
  q.push(ms("easy", "Average rate of change:", ["secant slope", "$\\dfrac{f(b)-f(a)}{b-a}$", "over an interval", "tangent slope"], [0, 1, 2]));
  q.push(ms("easy", "Instantaneous rate:", ["tangent slope", "at a single point", "limit of average rates", "secant slope"], [0, 1, 2]));
  q.push(ms("easy", "Estimating:", ["use a tiny interval", "like $[a,a+0.1]$", "approaches the tangent slope", "use the whole domain"], [0, 1, 2]));
  q.push(ms("easy", "For a linear function:", ["rate is constant", "same on every interval", "equals the slope", "changes each point"], [0, 1, 2]));
  q.push(tf("easy", "The average rate of change is a secant slope.", true));
  q.push(tf("easy", "The instantaneous rate of change is a secant slope.", false));
  q.push(tf("easy", "A line has a constant rate of change.", true));
  q.push(fill("easy", "Average rate of $f(x)=x^2$ on $[1,3]$.", ["4"]));
  q.push(fill("easy", "Average rate of $f(x)=x^2$ on $[2,4]$.", ["6"]));
  q.push(fill("easy", "The tangent slope measures the ___ rate of change.", ["instantaneous"]));
  q.push(num("easy", "Average rate of $f(x)=x^2$ on $[1,3]$.", 4, 0));
  q.push(num("easy", "Average rate of $f(x)=x^2$ on $[2,4]$.", 6, 0));
  q.push(num("easy", "Average rate of $f(x)=2x+1$ on $[0,5]$.", 2, 0));
  q.push(match("easy", "Match each to its average rate.", ["$x^2$ on $[1,3]$", "$x^2$ on $[2,4]$", "$2x+1$ on $[0,5]$"], ["$4$", "$6$", "$2$"], [0, 1, 2]));
  q.push(mc("medium", "Average rate of $f(x)=x^2$ on $[0,4]$:", ["4", "8", "16", "2"], 0));
  q.push(mc("medium", "Average rate of $f(x)=x^3$ on $[1,2]$:", ["7", "8", "1", "9"], 0));
  q.push(mc("medium", "Estimate the instantaneous rate of $f(x)=x^2$ at $x=2$ via $[2,2.1]$:", ["4.1", "4.0", "2.1", "8.4"], 0));
  q.push(mc("medium", "Average rate of $f(x)=5x-2$ on $[1,4]$:", ["5", "3", "13", "15"], 0));
  q.push(mc("medium", "Average rate of $f(x)=-x^2$ on $[1,3]$:", ["$-4$", "$4$", "$-8$", "$-2$"], 0));
  q.push(mc("medium", "Average rate of $f(x)=x^2+1$ on $[0,3]$:", ["3", "4", "9", "10"], 0));
  q.push(ms("medium", "$f(x)=x^2$ on $[0,4]$:", ["$\\dfrac{16-0}{4}$", "$=4$", "secant slope", "$=16$"], [0, 1, 2]));
  q.push(ms("medium", "Estimating at $x=2$:", ["use $[2,2.1]$", "$\\dfrac{4.41-4}{0.1}$", "$=4.1$", "$=2.1$"], [0, 1, 2]));
  q.push(ms("medium", "$f(x)=x^3$ on $[1,2]$:", ["$\\dfrac{8-1}{1}$", "$=7$", "secant slope", "$=8$"], [0, 1, 2]));
  q.push(ms("medium", "Interpreting position $d(t)$:", ["AROC $=$ average speed", "$\\dfrac{d(b)-d(a)}{b-a}$", "distance over time", "tangent gives instantaneous speed"], [0, 1, 2, 3]));
  q.push(tf("medium", "Average rate of $f(x)=x^3$ on $[1,2]$ is 7.", true));
  q.push(tf("medium", "The estimate at $x=2$ using $[2,2.1]$ gives 4.1.", true));
  q.push(tf("medium", "Average rate of $f(x)=-x^2$ on $[1,3]$ is 4.", false));
  q.push(fill("medium", "Average rate of $f(x)=x^3$ on $[1,2]$.", ["7"]));
  q.push(fill("medium", "Estimate of the rate of $x^2$ at $x=2$ via $[2,2.1]$.", ["4.1"]));
  q.push(fill("medium", "Average rate of $f(x)=-x^2$ on $[1,3]$.", ["-4"]));
  q.push(num("medium", "Average rate of $f(x)=x^2$ on $[0,4]$.", 4, 0));
  q.push(num("medium", "Average rate of $f(x)=x^3$ on $[1,2]$.", 7, 0));
  q.push(num("medium", "Average rate of $f(x)=x^2+1$ on $[0,3]$.", 3, 0));
  q.push(match("medium", "Match each to its average rate.", ["$x^3$ on $[1,2]$", "$-x^2$ on $[1,3]$", "$x^2$ on $[0,4]$"], ["$7$", "$-4$", "$4$"], [0, 1, 2]));
  q.push(mc("hard", "As the interval shrinks to a point, the average rate approaches the:", ["instantaneous rate", "y-intercept", "average value", "maximum"], 0));
  q.push(mc("hard", "Estimate the instantaneous rate of $f(x)=x^2$ at $x=3$ via $[3,3.01]$:", ["6.01", "6.1", "9", "3.01"], 0));
  q.push(mc("hard", "For $P(t)=100+t^2$, average growth on $[0,5]$:", ["5", "25", "10", "1"], 0));
  q.push(mc("hard", "The instantaneous rate of $f(x)=x^2$ at $x=2$ (exact) is:", ["4", "4.1", "2", "8"], 0));
  q.push(mc("hard", "Average rate of $f(x)=\\tfrac1x$ on $[1,2]$:", ["$-\\tfrac12$", "$\\tfrac12$", "$-1$", "$1$"], 0));
  q.push(ms("hard", "Shrinking intervals:", ["secant → tangent", "average → instantaneous", "smaller interval is more accurate", "interval should be large"], [0, 1, 2]));
  q.push(ms("hard", "$P(t)=100+t^2$ on $[0,5]$:", ["$\\dfrac{125-100}{5}$", "$=5$", "average rate of growth", "$=25$"], [0, 1, 2]));
  q.push(ms("hard", "$f(x)=\\tfrac1x$ on $[1,2]$:", ["$\\dfrac{1/2-1}{2-1}$", "$=-\\tfrac12$", "negative (decreasing)", "$=\\tfrac12$"], [0, 1, 2]));
  q.push(ms("hard", "Accuracy of estimates:", ["$[3,3.01]$ beats $[3,3.1]$", "closer to the tangent slope", "true rate at $x=3$ is 6", "true rate is 6.1"], [0, 1, 2]));
  q.push(tf("hard", "Average rate of $f(x)=\\tfrac1x$ on $[1,2]$ is $-\\tfrac12$.", true));
  q.push(tf("hard", "$P(t)=100+t^2$ has average growth 5 on $[0,5]$.", true));
  q.push(tf("hard", "The exact instantaneous rate of $x^2$ at $x=2$ is 4.1.", false));
  q.push(fill("hard", "Average rate of $f(x)=\\tfrac1x$ on $[1,2]$.", ["-1/2", "-0.5"]));
  q.push(fill("hard", "Average growth of $P(t)=100+t^2$ on $[0,5]$.", ["5"]));
  q.push(fill("hard", "Exact instantaneous rate of $x^2$ at $x=2$.", ["4"]));
  q.push(num("hard", "Average growth of $P(t)=100+t^2$ on $[0,5]$.", 5, 0));
  q.push(num("hard", "Estimate of the rate of $x^2$ at $x=3$ via $[3,3.01]$.", 6.01, 0.01));
  q.push(num("hard", "Exact instantaneous rate of $f(x)=x^2$ at $x=2$.", 4, 0));
  q.push(order("hard", "Order the steps to estimate the instantaneous rate of $f(x)=x^2$ at $x=2$.", ["Choose a small interval $[2,2.1]$", "Compute $f(2.1)=4.41$ and $f(2)=4$", "$\\dfrac{4.41-4}{0.1}=4.1$", "Estimate $\\approx4$"]));
  q.push(match("hard", "Match each to its average rate.", ["$\\tfrac1x$ on $[1,2]$", "$100+t^2$ on $[0,5]$", "$x^2$ on $[0,4]$"], ["$-\\tfrac12$", "$5$", "$4$"], [0, 1, 2]));
  return q;
}

// ── 7.2 Combining Functions ──────────────────────────────────
function g72() {
  const q = [];
  q.push(mc("easy", "$(f+g)(x)=$", ["$f(x)+g(x)$", "$f(g(x))$", "$f(x)g(x)$", "$f(x)-g(x)$"], 0));
  q.push(mc("easy", "With $f=x^2,g=x$, $(f+g)(x)=$", ["$x^2+x$", "$x^3$", "$x^2-x$", "$2x$"], 0));
  q.push(mc("easy", "With $f=x^2,g=x$, $(fg)(x)=$", ["$x^3$", "$x^2+x$", "$x$", "$x^2$"], 0));
  q.push(mc("easy", "The domain of a combined function is:", ["the intersection of domains", "the union", "all reals", "empty"], 0));
  q.push(mc("easy", "With $f=x^2,g=x$, $(f-g)(x)=$", ["$x^2-x$", "$x^2+x$", "$x$", "$x^3$"], 0));
  q.push(mc("easy", "For $\\tfrac fg$ you must exclude:", ["where $g(x)=0$", "where $f(x)=0$", "$x=1$", "nothing"], 0));
  q.push(ms("easy", "Combining operations:", ["$(f\\pm g)(x)=f(x)\\pm g(x)$", "$(fg)(x)=f(x)g(x)$", "$(\\tfrac fg)(x)=\\tfrac{f(x)}{g(x)}$", "$(f+g)(x)=f(g(x))$"], [0, 1, 2]));
  q.push(ms("easy", "Domain of a combination:", ["intersection of domains", "where both defined", "exclude $g=0$ for $\\tfrac fg$", "the union of domains"], [0, 1, 2]));
  q.push(ms("easy", "With $f=x^2,g=x$:", ["$(f+g)=x^2+x$", "$(fg)=x^3$", "$(f-g)=x^2-x$", "$(f+g)=x^3$"], [0, 1, 2]));
  q.push(ms("easy", "Evaluating combinations:", ["$(f+g)(a)=f(a)+g(a)$", "$(fg)(a)=f(a)g(a)$", "plug in then combine", "$(f+g)(a)=f(g(a))$"], [0, 1, 2]));
  q.push(tf("easy", "$(f+g)(x)=f(x)+g(x)$.", true));
  q.push(tf("easy", "$(fg)(x)=f(g(x))$.", false));
  q.push(tf("easy", "The domain of $\\tfrac fg$ excludes where $g(x)=0$.", true));
  q.push(fill("easy", "With $f=x^2,g=x$, $(f+g)(x)=$", ["x^2+x"]));
  q.push(fill("easy", "With $f=x^2,g=x$, $(fg)(x)=$", ["x^3"]));
  q.push(fill("easy", "With $f=x^2,g=x$, $(f-g)(x)=$", ["x^2-x"]));
  q.push(num("easy", "With $f=x^2,g=x$, $(f+g)(2)$.", 6, 0));
  q.push(num("easy", "With $f=x^2,g=x$, $(fg)(2)$.", 8, 0));
  q.push(num("easy", "With $f=x^2,g=x$, $(f-g)(3)$.", 6, 0));
  q.push(match("easy", "Match each combination (with $f=x^2,g=x$).", ["$(f+g)(x)$", "$(fg)(x)$", "$(f-g)(x)$"], ["$x^2+x$", "$x^3$", "$x^2-x$"], [0, 1, 2]));
  q.push(mc("medium", "$f=x+1,g=x-1$. $(f+g)(x)=$", ["$2x$", "$2$", "$x^2-1$", "$x$"], 0));
  q.push(mc("medium", "$f=x+1,g=x-1$. $(fg)(x)=$", ["$x^2-1$", "$2x$", "$x^2+1$", "$x^2-2x-1$"], 0));
  q.push(mc("medium", "$f=x^2,g=3$. $(f-g)(x)=$", ["$x^2-3$", "$x^2+3$", "$3x^2$", "$3-x^2$"], 0));
  q.push(mc("medium", "$f=x,g=x+2$. $(f+g)(3)=$", ["8", "5", "6", "3"], 0));
  q.push(mc("medium", "$f=x^2,g=x$. Domain of $\\tfrac fg$:", ["$x\\ne0$", "$x\\ne1$", "all $x$", "$x>0$"], 0));
  q.push(mc("medium", "$f=2x,g=x^2$. $(f+g)(x)=$", ["$x^2+2x$", "$2x^3$", "$2x^2$", "$x^2-2x$"], 0));
  q.push(ms("medium", "$f=x+1,g=x-1$:", ["$(f+g)=2x$", "$(fg)=x^2-1$", "$(f-g)=2$", "$(f+g)=2$"], [0, 1, 2]));
  q.push(ms("medium", "$\\tfrac fg$ with $f=x^2,g=x$:", ["$=x$", "$x\\ne0$", "simplify then restrict", "$=x^3$"], [0, 1, 2]));
  q.push(ms("medium", "Evaluating $(f+g)(3)$ with $f=x,g=x+2$:", ["$f(3)+g(3)$", "$3+5$", "$=8$", "$=6$"], [0, 1, 2]));
  q.push(ms("medium", "$(fg)(x)$ with $f=x+3,g=x-3$:", ["difference of squares", "$(x+3)(x-3)$", "$=x^2-9$", "$=x^2+9$"], [0, 1, 2]));
  q.push(tf("medium", "With $f=x+1,g=x-1$, $(fg)(x)=x^2-1$.", true));
  q.push(tf("medium", "With $f=x^2,g=x$, the domain of $\\tfrac fg$ is $x\\ne0$.", true));
  q.push(tf("medium", "With $f=x,g=x+2$, $(f+g)(3)=6$.", false));
  q.push(fill("medium", "$f=x+1,g=x-1$: $(f+g)(x)=$", ["2x"]));
  q.push(fill("medium", "$f=x+1,g=x-1$: $(fg)(x)=$", ["x^2-1"]));
  q.push(fill("medium", "$f=x,g=x+2$: $(f+g)(3)=$", ["8"]));
  q.push(num("medium", "$f=x+3,g=x-3$: $(fg)(0)$.", -9, 0));
  q.push(num("medium", "$f=2x,g=x^2$: $(f+g)(2)$.", 8, 0));
  q.push(num("medium", "$f=x^2,g=x+1$: $(f+g)(1)$.", 3, 0));
  q.push(match("medium", "Match each (with $f=x+1,g=x-1$).", ["$(f+g)(x)$", "$(fg)(x)$", "$(f-g)(x)$"], ["$2x$", "$x^2-1$", "$2$"], [0, 1, 2]));
  q.push(mc("hard", "$f=x^2-1,g=x+1$. $\\left(\\tfrac fg\\right)(x)=$", ["$x-1,\\ x\\ne-1$", "$x+1$", "$x-1$", "$x^2$"], 0));
  q.push(mc("hard", "$f=x^2,g=x-2$. Domain of $\\tfrac fg$:", ["$x\\ne2$", "$x\\ne0$", "all $x$", "$x\\ne-2$"], 0));
  q.push(mc("hard", "$f=\\sqrt x,g=x$. Domain of $(f+g)$:", ["$x\\ge0$", "all $x$", "$x>0$", "$x\\ne0$"], 0));
  q.push(mc("hard", "$f=x^2-4,g=x-2$. $\\left(\\tfrac fg\\right)(x)=$", ["$x+2,\\ x\\ne2$", "$x-2$", "$x+2$", "$x^2$"], 0));
  q.push(mc("hard", "$f=x,g=\\tfrac1x$. $(fg)(x)=$", ["$1,\\ x\\ne0$", "$x^2$", "$\\tfrac1{x^2}$", "$x$"], 0));
  q.push(ms("hard", "$\\tfrac{x^2-1}{x+1}$:", ["factor $\\tfrac{(x-1)(x+1)}{x+1}$", "$=x-1$", "$x\\ne-1$", "$=x+1$"], [0, 1, 2]));
  q.push(ms("hard", "Domain of $(f+g)$ with $f=\\sqrt x$:", ["$\\sqrt x$ needs $x\\ge0$", "intersect with $g$'s domain", "$x\\ge0$", "all reals"], [0, 1, 2]));
  q.push(ms("hard", "$\\tfrac{x^2-4}{x-2}$:", ["$\\tfrac{(x-2)(x+2)}{x-2}$", "$=x+2$", "$x\\ne2$", "$=x-2$"], [0, 1, 2]));
  q.push(ms("hard", "$(fg)$ with $f=x,g=\\tfrac1x$:", ["$x\\cdot\\tfrac1x$", "$=1$", "$x\\ne0$", "$=x^2$"], [0, 1, 2]));
  q.push(tf("hard", "$\\tfrac{x^2-1}{x+1}=x-1$ with $x\\ne-1$.", true));
  q.push(tf("hard", "$f=x,g=\\tfrac1x$ gives $(fg)(x)=1$ with $x\\ne0$.", true));
  q.push(tf("hard", "$\\tfrac{x^2-4}{x-2}=x-2$.", false));
  q.push(fill("hard", "$\\left(\\tfrac fg\\right)(x)$ for $f=x^2-1,g=x+1$ (with restriction).", ["x-1, x≠-1", "x-1 (x≠-1)"]));
  q.push(fill("hard", "$\\left(\\tfrac fg\\right)(x)$ for $f=x^2-4,g=x-2$.", ["x+2, x≠2", "x+2 (x≠2)"]));
  q.push(fill("hard", "Domain of $(f+g)$ for $f=\\sqrt x,g=x$.", ["x>=0", "x≥0"]));
  q.push(num("hard", "$f=x,g=\\tfrac1x$: $(fg)(5)$.", 1, 0));
  q.push(num("hard", "$f=x^2-1,g=x+1$: $\\left(\\tfrac fg\\right)(3)$.", 2, 0));
  q.push(num("hard", "$f=x^2-4,g=x-2$: $\\left(\\tfrac fg\\right)(0)$.", 2, 0));
  q.push(order("hard", "Order the steps to simplify $\\left(\\tfrac fg\\right)(x)$ for $f=x^2-1,g=x+1$.", ["Write $\\tfrac{x^2-1}{x+1}$", "Factor $\\tfrac{(x-1)(x+1)}{x+1}$", "Cancel $(x+1)$", "$x-1$, with $x\\ne-1$"]));
  q.push(match("hard", "Match each quotient to its simplest form.", ["$\\tfrac{x^2-1}{x+1}$", "$\\tfrac{x^2-4}{x-2}$", "$x\\cdot\\tfrac1x$"], ["$x-1$", "$x+2$", "$1$"], [0, 1, 2]));
  return q;
}

// ── 7.3 Composition of Functions ─────────────────────────────
function g73() {
  const q = [];
  q.push(mc("easy", "$(f\\circ g)(x)=$", ["$f(g(x))$", "$f(x)g(x)$", "$f(x)+g(x)$", "$g(f(x))$"], 0));
  q.push(mc("easy", "In $f(g(x))$ you apply:", ["$g$ first, then $f$", "$f$ first, then $g$", "both at once", "neither"], 0));
  q.push(mc("easy", "$f=x^2,g=x+1$. $f(g(x))=$", ["$(x+1)^2$", "$x^2+1$", "$x^2+x$", "$x+1$"], 0));
  q.push(mc("easy", "$f=x^2,g=x+1$. $g(f(x))=$", ["$x^2+1$", "$(x+1)^2$", "$x^2$", "$x+1$"], 0));
  q.push(mc("easy", "Is $f\\circ g$ usually equal to $g\\circ f$?", ["no", "yes", "always", "only for lines"], 0));
  q.push(mc("easy", "$f=x^2,g=x+1$. $f(g(2))=$", ["9", "5", "4", "3"], 0));
  q.push(ms("easy", "Composition:", ["$(f\\circ g)(x)=f(g(x))$", "inner first", "order matters", "$=f(x)g(x)$"], [0, 1, 2]));
  q.push(ms("easy", "Evaluating $f(g(2))$:", ["find $g(2)$ first", "then apply $f$", "two steps", "apply $f$ first"], [0, 1, 2]));
  q.push(ms("easy", "$f=x^2,g=x+1$:", ["$f(g(x))=(x+1)^2$", "$g(f(x))=x^2+1$", "they differ", "they are equal"], [0, 1, 2]));
  q.push(ms("easy", "Decomposition:", ["split into outer and inner", "$(x+1)^2$: outer $x^2$, inner $x+1$", "reverse of composing", "always one function"], [0, 1, 2]));
  q.push(tf("easy", "$(f\\circ g)(x)=f(g(x))$.", true));
  q.push(tf("easy", "$f\\circ g$ always equals $g\\circ f$.", false));
  q.push(tf("easy", "For $f=x^2,g=x+1$, $f(g(x))=(x+1)^2$.", true));
  q.push(fill("easy", "$f=x^2,g=x+1$: $f(g(x))=$", ["(x+1)^2"]));
  q.push(fill("easy", "$f=x^2,g=x+1$: $g(f(x))=$", ["x^2+1"]));
  q.push(fill("easy", "$f=x^2,g=x+1$: $f(g(2))=$", ["9"]));
  q.push(num("easy", "$f=x^2,g=x+1$: $f(g(2))$.", 9, 0));
  q.push(num("easy", "$f=x^2,g=x+1$: $g(f(2))$.", 5, 0));
  q.push(num("easy", "$f=2x,g=x+3$: $f(g(1))$.", 8, 0));
  q.push(match("easy", "Match each (with $f=x^2,g=x+1$).", ["$f(g(x))$", "$g(f(x))$", "$f(g(2))$"], ["$(x+1)^2$", "$x^2+1$", "$9$"], [0, 1, 2]));
  q.push(mc("medium", "$f=x^2,g=x-2$. $f(g(x))=$", ["$(x-2)^2$", "$x^2-2$", "$x^2+2$", "$x-2$"], 0));
  q.push(mc("medium", "$f=x^2,g=x-2$. $g(f(x))=$", ["$x^2-2$", "$(x-2)^2$", "$x^2$", "$x-2$"], 0));
  q.push(mc("medium", "$f=2x,g=x+3$. $f(g(1))=$", ["8", "5", "4", "6"], 0));
  q.push(mc("medium", "Decompose $h(x)=\\sqrt{x+5}$:", ["$f=\\sqrt x,g=x+5$", "$f=x+5,g=\\sqrt x$", "$f=\\sqrt x,g=x$", "$f=x,g=\\sqrt{x+5}$"], 0));
  q.push(mc("medium", "$f=\\sqrt x,g=x-1$. Domain of $f(g(x))$:", ["$x\\ge1$", "$x\\ge0$", "$x\\ge-1$", "all $x$"], 0));
  q.push(mc("medium", "$f=x+1,g=x^2$. $f(g(x))=$", ["$x^2+1$", "$(x+1)^2$", "$x^2$", "$x+1$"], 0));
  q.push(ms("medium", "$f=x^2,g=x-2$:", ["$f(g(x))=(x-2)^2$", "$g(f(x))=x^2-2$", "different results", "same result"], [0, 1, 2]));
  q.push(ms("medium", "Decomposing $\\sqrt{x+5}$:", ["outer $\\sqrt x$", "inner $x+5$", "$f(g(x))$ with these", "outer $x+5$"], [0, 1, 2]));
  q.push(ms("medium", "Domain of $f(g(x))$ for $f=\\sqrt x,g=x-1$:", ["need $g(x)\\ge0$", "$x-1\\ge0$", "$x\\ge1$", "$x\\ge0$"], [0, 1, 2]));
  q.push(ms("medium", "Evaluating $f(g(1))$ for $f=2x,g=x+3$:", ["$g(1)=4$", "$f(4)=8$", "two steps", "$f(1)=2$ first"], [0, 1, 2]));
  q.push(tf("medium", "$f=x^2,g=x-2$ gives $f(g(x))=(x-2)^2$.", true));
  q.push(tf("medium", "$h(x)=\\sqrt{x+5}$ decomposes as $f=\\sqrt x,g=x+5$.", true));
  q.push(tf("medium", "$f=\\sqrt x,g=x-1$ gives domain $x\\ge0$ for $f(g(x))$.", false));
  q.push(fill("medium", "$f=x^2,g=x-2$: $f(g(x))=$", ["(x-2)^2"]));
  q.push(fill("medium", "Domain of $f(g(x))$ for $f=\\sqrt x,g=x-1$.", ["x>=1", "x≥1"]));
  q.push(fill("medium", "$f=x+1,g=x^2$: $f(g(x))=$", ["x^2+1"]));
  q.push(num("medium", "$f=2x,g=x+3$: $f(g(1))$.", 8, 0));
  q.push(num("medium", "$f=x^2,g=x+4$: $f(g(0))$.", 16, 0));
  q.push(num("medium", "$f=3x,g=x-1$: $f(g(2))$.", 3, 0));
  q.push(match("medium", "Match each (with $f=x^2,g=x-2$).", ["$f(g(x))$", "$g(f(x))$", "$f(g(3))$"], ["$(x-2)^2$", "$x^2-2$", "$1$"], [0, 1, 2]));
  q.push(mc("hard", "$f=\\tfrac1x,g=x-2$. $f(g(x))=$", ["$\\tfrac1{x-2},\\ x\\ne2$", "$\\tfrac1x-2$", "$\\tfrac1{x}-2$", "$x-2$"], 0));
  q.push(mc("hard", "$f=x^2,g=\\sqrt x$. $f(g(x))=$ (with domain)", ["$x,\\ x\\ge0$", "$x^2$", "$\\sqrt{x^2}$", "$x,\\ $all reals"], 0));
  q.push(mc("hard", "Decompose $h(x)=(2x-1)^2$:", ["$f=x^2,g=2x-1$", "$f=2x-1,g=x^2$", "$f=x^2,g=2x$", "$f=2x,g=x^2$"], 0));
  q.push(mc("hard", "$f=\\sqrt x,g=x^2-4$. Domain of $f(g(x))$:", ["$x\\le-2$ or $x\\ge2$", "$x\\ge2$", "all $x$", "$-2\\le x\\le2$"], 0));
  q.push(mc("hard", "$f=x^2,g=x+1$. $f(g(x))-g(f(x))=$", ["$2x$", "$0$", "$2x^2$", "$2$"], 0));
  q.push(ms("hard", "$f=\\tfrac1x,g=x-2$:", ["$f(g(x))=\\tfrac1{x-2}$", "restriction $x\\ne2$", "compose inner first", "$=\\tfrac1x-2$"], [0, 1, 2]));
  q.push(ms("hard", "$f=x^2,g=\\sqrt x$:", ["$f(g(x))=(\\sqrt x)^2=x$", "need $x\\ge0$ for $\\sqrt x$", "domain $x\\ge0$", "domain all reals"], [0, 1, 2]));
  q.push(ms("hard", "Domain of $\\sqrt{x^2-4}$:", ["need $x^2-4\\ge0$", "$x^2\\ge4$", "$x\\le-2$ or $x\\ge2$", "$-2\\le x\\le2$"], [0, 1, 2]));
  q.push(ms("hard", "$f(g(x))-g(f(x))$ for $f=x^2,g=x+1$:", ["$(x+1)^2-(x^2+1)$", "$x^2+2x+1-x^2-1$", "$=2x$", "$=0$"], [0, 1, 2]));
  q.push(tf("hard", "$f=x^2,g=\\sqrt x$ gives $f(g(x))=x$ with domain $x\\ge0$.", true));
  q.push(tf("hard", "$\\sqrt{x^2-4}$ has domain $x\\le-2$ or $x\\ge2$.", true));
  q.push(tf("hard", "For $f=x^2,g=x+1$, $f(g(x))=g(f(x))$.", false));
  q.push(fill("hard", "$f=\\tfrac1x,g=x-2$: $f(g(x))=$ (with restriction).", ["1/(x-2), x≠2", "1/(x-2) (x≠2)"]));
  q.push(fill("hard", "Decompose $(2x-1)^2$.", ["f=x^2, g=2x-1", "outer x^2, inner 2x-1"]));
  q.push(fill("hard", "Domain of $\\sqrt{x^2-4}$.", ["x<=-2 or x>=2", "x≤-2 or x≥2"]));
  q.push(num("hard", "$f=x^2,g=\\sqrt x$: $f(g(9))$.", 9, 0));
  q.push(num("hard", "$f=\\tfrac1x,g=x-2$: $f(g(4))$.", 0.5, 0.01));
  q.push(num("hard", "$f=x^2,g=x+1$: $f(g(3))-g(f(3))$.", 6, 0));
  q.push(order("hard", "Order the steps to find the domain of $f(g(x))$ for $f=\\sqrt x,g=x-3$.", ["Compose: $\\sqrt{x-3}$", "Require the radicand $\\ge0$", "$x-3\\ge0$", "$x\\ge3$"]));
  q.push(match("hard", "Match each composite to its form.", ["$f=\\tfrac1x,g=x-2$", "$f=x^2,g=\\sqrt x$", "$f=\\sqrt x,g=x-3$"], ["$\\tfrac1{x-2}$", "$x$", "$\\sqrt{x-3}$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "7.1", gen: g71 },
  { code: "7.2", gen: g72 },
  { code: "7.3", gen: g73 },
];
