-- ============================================================
-- Chapter tests: a chapter test is just a quiz (see 2026-06-15_question_bank.sql —
-- "Teachers pick from it to build class quizzes"), generated by random sampling
-- across a whole chapter instead of manual picking, optionally as several
-- non-identical forms (Form A/B/C) so a teacher can hand out different versions
-- or use one as a retest.
--
-- test_group_id ties sibling forms of the SAME generated test together (not a
-- foreign key — just a shared tag) so the UI can list/delete "this test" as one
-- unit without parsing titles. A single-form test still gets a group id, for
-- consistency.
--
-- Run once in the Supabase SQL Editor. Idempotent.
-- ============================================================

alter table quizzes add column if not exists test_group_id uuid;

create index if not exists quizzes_test_group_idx on quizzes (test_group_id) where test_group_id is not null;

notify pgrst, 'reload schema';
