// MCV4U Unit 1 — Rates of Change & Limits: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 1.1 Average & Instantaneous Rate of Change ───────────────
function g11() {
  const q = [];
  q.push(mc("easy", "The average rate of change over $[a,b]$ is:", ["$\\dfrac{f(b)-f(a)}{b-a}$", "$f(b)-f(a)$", "$f'(a)$", "$\\dfrac{b-a}{f(b)-f(a)}$"], 0));
  q.push(mc("easy", "The average rate of change is the slope of the:", ["secant", "tangent", "axis", "asymptote"], 0));
  q.push(mc("easy", "The instantaneous rate of change is the slope of the:", ["tangent", "secant", "x-axis", "midline"], 0));
  q.push(mc("easy", "Average rate of change of $f(x)=x^2$ on $[1,3]$:", ["4", "8", "2", "9"], 0));
  q.push(mc("easy", "The difference quotient is:", ["$\\dfrac{f(x+h)-f(x)}{h}$", "$f(x+h)-f(x)$", "$\\dfrac{f(x)}{h}$", "$f(x)\\cdot h$"], 0));
  q.push(mc("easy", "To get the instantaneous rate you let:", ["$h\\to0$", "$h\\to\\infty$", "$x\\to0$", "$h=1$"], 0));
  q.push(ms("easy", "Rates of change:", ["average = secant slope", "instantaneous = tangent slope", "difference quotient → tangent", "average = tangent slope"], [0, 1, 2]));
  q.push(ms("easy", "The difference quotient:", ["$\\dfrac{f(x+h)-f(x)}{h}$", "is a secant slope", "→ derivative as $h\\to0$", "needs $h=0$ directly"], [0, 1, 2]));
  q.push(ms("easy", "Average rate over $[a,b]$:", ["$\\dfrac{f(b)-f(a)}{b-a}$", "change in $y$ over change in $x$", "a secant slope", "the tangent slope"], [0, 1, 2]));
  q.push(ms("easy", "Instantaneous rate:", ["a tangent slope", "a limit of secant slopes", "at a single point", "an interval average"], [0, 1, 2]));
  q.push(tf("easy", "The average rate of change is a secant slope.", true));
  q.push(tf("easy", "The instantaneous rate of change is a secant slope.", false));
  q.push(tf("easy", "Letting $h\\to0$ turns the secant slope into the tangent slope.", true));
  q.push(fill("easy", "Average rate of change of $f(x)=x^2$ on $[1,3]$.", ["4"]));
  q.push(fill("easy", "Average rate of change of $f(x)=x^2$ on $[2,4]$.", ["6"]));
  q.push(fill("easy", "The tangent slope is the ___ rate of change.", ["instantaneous"]));
  q.push(num("easy", "Average rate of change of $f(x)=x^2$ on $[1,3]$.", 4, 0));
  q.push(num("easy", "Average rate of change of $f(x)=x^2$ on $[0,4]$.", 4, 0));
  q.push(num("easy", "Average rate of change of $f(x)=3x+1$ on $[2,5]$.", 3, 0));
  q.push(match("easy", "Match each to its average rate.", ["$x^2$ on $[1,3]$", "$x^2$ on $[2,4]$", "$3x+1$ on $[2,5]$"], ["$4$", "$6$", "$3$"], [0, 1, 2]));
  q.push(mc("medium", "Simplify the difference quotient of $f(x)=x^2$:", ["$2x+h$", "$2x$", "$x+h$", "$2xh$"], 0));
  q.push(mc("medium", "Instantaneous rate of $f(x)=x^2$ at $x=2$:", ["4", "5", "2", "8"], 0));
  q.push(mc("medium", "Instantaneous rate of $f(x)=3x^2$ at $x=2$:", ["12", "6", "9", "18"], 0));
  q.push(mc("medium", "For $s(t)=t^2$, the instantaneous velocity at $t=4$:", ["8", "16", "4", "2"], 0));
  q.push(mc("medium", "Average rate of change of $f(x)=x^3$ on $[1,2]$:", ["7", "8", "1", "9"], 0));
  q.push(mc("medium", "The difference quotient of $f(x)=2x^2$ simplifies to:", ["$4x+2h$", "$2x+h$", "$4x$", "$2x+2h$"], 0));
  q.push(ms("medium", "$\\dfrac{(x+h)^2-x^2}{h}$:", ["$=\\dfrac{2xh+h^2}{h}$", "$=2x+h$", "limit $2x$", "$=2x+h^2$"], [0, 1, 2]));
  q.push(ms("medium", "Instantaneous rate of $x^2$ at $x=2$:", ["$\\lim_{h\\to0}(4+h)$", "$=4$", "the tangent slope", "$=5$"], [0, 1, 2]));
  q.push(ms("medium", "Velocity from position:", ["instantaneous rate of $s$", "$v=\\lim\\frac{\\Delta s}{\\Delta t}$", "tangent to the $s$–$t$ graph", "the average over all time"], [0, 1, 2]));
  q.push(ms("medium", "For $f(x)=x^2$ the slope function is:", ["$2x$", "the derivative", "the slider's limit", "$x^2$"], [0, 1, 2]));
  q.push(tf("medium", "The difference quotient of $f(x)=x^2$ is $2x+h$.", true));
  q.push(tf("medium", "The instantaneous rate of $x^2$ at $x=2$ is $4$.", true));
  q.push(tf("medium", "The instantaneous rate of $3x^2$ at $x=2$ is $6$.", false));
  q.push(fill("medium", "Difference quotient of $f(x)=x^2$ (simplified).", ["2x+h"]));
  q.push(fill("medium", "Instantaneous rate of $f(x)=x^2$ at $x=5$.", ["10"]));
  q.push(fill("medium", "Instantaneous velocity of $s(t)=t^2$ at $t=4$.", ["8"]));
  q.push(num("medium", "Instantaneous rate of $f(x)=x^2$ at $x=5$.", 10, 0));
  q.push(num("medium", "Instantaneous rate of $f(x)=3x^2$ at $x=2$.", 12, 0));
  q.push(num("medium", "Average rate of change of $f(x)=x^3$ on $[1,2]$.", 7, 0));
  q.push(match("medium", "Match each to its instantaneous rate.", ["$x^2$ at $x=5$", "$3x^2$ at $x=2$", "$t^2$ at $t=4$"], ["$10$", "$12$", "$8$"], [0, 1, 2]));
  q.push(mc("hard", "Instantaneous rate of $f(x)=x^2$ at a general $x$:", ["$2x$", "$2x+h$", "$x^2$", "$x$"], 0));
  q.push(mc("hard", "A ball's height is $h(t)=20t-5t^2$; its velocity at $t=1$:", ["10", "15", "20", "0"], 0));
  q.push(mc("hard", "$h(t)=20t-5t^2$; average velocity on $[1,3]$:", ["0", "10", "5", "−10"], 0));
  q.push(mc("hard", "Simplify $\\dfrac{(x+h)^3-x^3}{h}$:", ["$3x^2+3xh+h^2$", "$3x^2$", "$x^2+h$", "$3x^2+h$"], 0));
  q.push(mc("hard", "So the instantaneous rate of $f(x)=x^3$ is:", ["$3x^2$", "$3x$", "$x^2$", "$2x$"], 0));
  q.push(ms("hard", "$h(t)=20t-5t^2$ at $t=1$:", ["$\\lim_{h\\to0}(10-5h)$", "$=10$ m/s", "instantaneous velocity", "$=0$"], [0, 1, 2]));
  q.push(ms("hard", "Average vs instantaneous for the ball:", ["average on $[1,3]$ is $0$", "up then back to the same height", "instantaneous at $t=1$ is $10$", "they are equal"], [0, 1, 2]));
  q.push(ms("hard", "$\\dfrac{(x+h)^3-x^3}{h}$:", ["expand $(x+h)^3$", "$=3x^2+3xh+h^2$", "limit $3x^2$", "$=3x^2+h$"], [0, 1, 2]));
  q.push(ms("hard", "Generalizing $f(x)=x^2$:", ["secant slope $2x+h$", "limit gives $2x$", "valid for every $x$", "only at $x=2$"], [0, 1, 2]));
  q.push(tf("hard", "The instantaneous rate of $x^3$ at a general $x$ is $3x^2$.", true));
  q.push(tf("hard", "For $h(t)=20t-5t^2$, the average velocity on $[1,3]$ is $0$.", true));
  q.push(tf("hard", "The difference quotient of $x^3$ is $3x^2$ (no $h$ terms).", false));
  q.push(fill("hard", "Instantaneous rate of $f(x)=x^2$ at a general $x$.", ["2x"]));
  q.push(fill("hard", "Simplified difference quotient of $f(x)=x^3$.", ["3x^2+3xh+h^2"]));
  q.push(fill("hard", "Velocity of $h(t)=20t-5t^2$ at $t=1$.", ["10"]));
  q.push(num("hard", "Velocity of $h(t)=20t-5t^2$ at $t=1$.", 10, 0));
  q.push(num("hard", "Average velocity of $h(t)=20t-5t^2$ on $[1,3]$.", 0, 0));
  q.push(num("hard", "Instantaneous rate of $f(x)=x^3$ at $x=2$ (uses $3x^2$).", 12, 0));
  q.push(order("hard", "Order the steps to find the instantaneous rate of $f(x)=x^2$ at $x=2$.", ["Form $\\dfrac{(2+h)^2-4}{h}$", "Expand: $\\dfrac{4h+h^2}{h}$", "Cancel $h$: $4+h$", "Let $h\\to0$: $4$"]));
  q.push(match("hard", "Match each to its instantaneous-rate function.", ["$x^2$", "$x^3$", "$3x^2$"], ["$2x$", "$3x^2$", "$6x$"], [0, 1, 2]));
  return q;
}

// ── 1.2 The Limit of a Function ──────────────────────────────
function g12() {
  const q = [];
  q.push(mc("easy", "$\\displaystyle\\lim_{x\\to3}(2x+1)=$", ["7", "6", "3", "1"], 0));
  q.push(mc("easy", "To evaluate a limit where $f$ is continuous, you:", ["substitute", "factor first", "rationalize", "graph it"], 0));
  q.push(mc("easy", "$\\tfrac00$ is:", ["indeterminate", "equal to 0", "equal to 1", "undefined and final"], 0));
  q.push(mc("easy", "$\\displaystyle\\lim_{x\\to4}(x^2-1)=$", ["15", "16", "3", "7"], 0));
  q.push(mc("easy", "A two-sided limit exists only if:", ["the one-sided limits agree", "$f(a)$ exists", "the function is a polynomial", "$x=a$"], 0));
  q.push(mc("easy", "Does the limit need $f(a)$ to be defined?", ["no", "yes", "only for polynomials", "only at infinity"], 0));
  q.push(ms("easy", "Evaluating limits:", ["substitute if continuous", "factor/rationalize for $\\tfrac00$", "check one-sided limits", "always plug in $0$"], [0, 1, 2]));
  q.push(ms("easy", "The indeterminate $\\tfrac00$:", ["needs more work", "factor and cancel", "or rationalize", "is the final answer"], [0, 1, 2]));
  q.push(ms("easy", "One-sided limits:", ["$\\lim_{x\\to a^-}$ from the left", "$\\lim_{x\\to a^+}$ from the right", "must agree for the limit to exist", "are always equal"], [0, 1, 2]));
  q.push(ms("easy", "Limits at infinity:", ["divide by the highest power", "small terms vanish", "ratio of leading coefficients", "always 0"], [0, 1, 2]));
  q.push(tf("easy", "$\\displaystyle\\lim_{x\\to3}(2x+1)=7$.", true));
  q.push(tf("easy", "$\\tfrac00$ means the limit is 0.", false));
  q.push(tf("easy", "A limit can exist even if $f(a)$ is undefined.", true));
  q.push(fill("easy", "$\\displaystyle\\lim_{x\\to3}(2x+1)$.", ["7"]));
  q.push(fill("easy", "$\\displaystyle\\lim_{x\\to4}(x^2-1)$.", ["15"]));
  q.push(fill("easy", "$\\displaystyle\\lim_{x\\to0}(x^2+5)$.", ["5"]));
  q.push(num("easy", "$\\displaystyle\\lim_{x\\to3}(2x+1)$.", 7, 0));
  q.push(num("easy", "$\\displaystyle\\lim_{x\\to4}(x^2-1)$.", 15, 0));
  q.push(num("easy", "$\\displaystyle\\lim_{x\\to2}(5x)$.", 10, 0));
  q.push(match("easy", "Match each limit to its value.", ["$\\lim_{x\\to3}(2x+1)$", "$\\lim_{x\\to4}(x^2-1)$", "$\\lim_{x\\to2}(5x)$"], ["$7$", "$15$", "$10$"], [0, 1, 2]));
  q.push(mc("medium", "$\\displaystyle\\lim_{x\\to2}\\dfrac{x^2-4}{x-2}=$", ["4", "0", "2", "DNE"], 0));
  q.push(mc("medium", "$\\displaystyle\\lim_{x\\to3}\\dfrac{x^2-9}{x-3}=$", ["6", "0", "3", "DNE"], 0));
  q.push(mc("medium", "$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{5x-2}{x+1}=$", ["5", "0", "$\\infty$", "1"], 0));
  q.push(mc("medium", "$\\displaystyle\\lim_{x\\to1}\\dfrac{x^2+x-2}{x-1}=$", ["3", "0", "1", "DNE"], 0));
  q.push(mc("medium", "$\\displaystyle\\lim_{x\\to0}\\dfrac{|x|}{x}$:", ["DNE", "0", "1", "−1"], 0));
  q.push(mc("medium", "$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{3x^2-x}{x^2+5}=$", ["3", "0", "$\\infty$", "1"], 0));
  q.push(ms("medium", "$\\dfrac{x^2-4}{x-2}$ at $x=2$:", ["$\\tfrac00$", "factor $(x-2)(x+2)$", "cancel → $x+2$", "substitute directly"], [0, 1, 2]));
  q.push(ms("medium", "$\\lim_{x\\to0}\\tfrac{|x|}{x}$:", ["right limit $1$", "left limit $-1$", "they differ → DNE", "equals $0$"], [0, 1, 2]));
  q.push(ms("medium", "Limit at infinity of a rational:", ["compare degrees", "equal degrees → leading-coefficient ratio", "divide by highest power", "always $0$"], [0, 1, 2]));
  q.push(ms("medium", "$\\dfrac{x^2+x-2}{x-1}$ at $x=1$:", ["$\\tfrac00$", "$(x+2)(x-1)$ on top", "cancel → $x+2$", "limit $4$"], [0, 1, 2]));
  q.push(tf("medium", "$\\displaystyle\\lim_{x\\to2}\\dfrac{x^2-4}{x-2}=4$.", true));
  q.push(tf("medium", "$\\displaystyle\\lim_{x\\to0}\\dfrac{|x|}{x}$ exists.", false));
  q.push(tf("medium", "$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{5x-2}{x+1}=5$.", true));
  q.push(fill("medium", "$\\displaystyle\\lim_{x\\to2}\\dfrac{x^2-4}{x-2}$.", ["4"]));
  q.push(fill("medium", "$\\displaystyle\\lim_{x\\to3}\\dfrac{x^2-9}{x-3}$.", ["6"]));
  q.push(fill("medium", "$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{3x^2-x}{x^2+5}$.", ["3"]));
  q.push(num("medium", "$\\displaystyle\\lim_{x\\to2}\\dfrac{x^2-4}{x-2}$.", 4, 0));
  q.push(num("medium", "$\\displaystyle\\lim_{x\\to1}\\dfrac{x^2+x-2}{x-1}$.", 3, 0));
  q.push(num("medium", "$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{5x-2}{x+1}$.", 5, 0));
  q.push(match("medium", "Match each limit to its value.", ["$\\lim_{x\\to2}\\tfrac{x^2-4}{x-2}$", "$\\lim_{x\\to3}\\tfrac{x^2-9}{x-3}$", "$\\lim_{x\\to\\infty}\\tfrac{5x-2}{x+1}$"], ["$4$", "$6$", "$5$"], [0, 1, 2]));
  q.push(mc("hard", "$\\displaystyle\\lim_{x\\to0}\\dfrac{\\sqrt{x+9}-3}{x}=$", ["$\\tfrac16$", "$0$", "$\\tfrac13$", "DNE"], 0));
  q.push(mc("hard", "$\\displaystyle\\lim_{x\\to0}\\dfrac{\\sqrt{x+4}-2}{x}=$", ["$\\tfrac14$", "$\\tfrac12$", "$0$", "DNE"], 0));
  q.push(mc("hard", "$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{2x^2+1}{x^2-3}=$", ["2", "0", "$\\infty$", "1"], 0));
  q.push(mc("hard", "$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{x+5}{x^2+1}=$", ["0", "1", "$\\infty$", "5"], 0));
  q.push(mc("hard", "$\\displaystyle\\lim_{x\\to-2}\\dfrac{x^2-4}{x+2}=$", ["−4", "4", "0", "DNE"], 0));
  q.push(ms("hard", "Rationalizing $\\tfrac{\\sqrt{x+9}-3}{x}$:", ["multiply by the conjugate", "numerator becomes $x$", "cancel $x$", "leave the root on top"], [0, 1, 2]));
  q.push(ms("hard", "$\\lim_{x\\to\\infty}\\tfrac{x+5}{x^2+1}$:", ["bottom degree higher", "→ $0$", "divide by $x^2$", "→ $1$"], [0, 1, 2]));
  q.push(ms("hard", "$\\lim_{x\\to-2}\\tfrac{x^2-4}{x+2}$:", ["$\\tfrac00$ at $-2$", "factor $(x-2)(x+2)$", "cancel → $x-2$", "limit $4$"], [0, 1, 2]));
  q.push(ms("hard", "Degree comparison at infinity:", ["top<bottom → $0$", "top=bottom → ratio", "top>bottom → $\\pm\\infty$", "always finite"], [0, 1, 2]));
  q.push(tf("hard", "$\\displaystyle\\lim_{x\\to0}\\dfrac{\\sqrt{x+9}-3}{x}=\\tfrac16$.", true));
  q.push(tf("hard", "$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{x+5}{x^2+1}=0$.", true));
  q.push(tf("hard", "$\\displaystyle\\lim_{x\\to-2}\\dfrac{x^2-4}{x+2}=4$.", false));
  q.push(fill("hard", "$\\displaystyle\\lim_{x\\to0}\\dfrac{\\sqrt{x+9}-3}{x}$.", ["1/6"]));
  q.push(fill("hard", "$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{2x^2+1}{x^2-3}$.", ["2"]));
  q.push(fill("hard", "$\\displaystyle\\lim_{x\\to-2}\\dfrac{x^2-4}{x+2}$.", ["-4"]));
  q.push(num("hard", "$\\displaystyle\\lim_{x\\to0}\\dfrac{\\sqrt{x+4}-2}{x}$ (decimal).", 0.25, 0.01));
  q.push(num("hard", "$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{2x^2+1}{x^2-3}$.", 2, 0));
  q.push(num("hard", "$\\displaystyle\\lim_{x\\to-2}\\dfrac{x^2-4}{x+2}$.", -4, 0));
  q.push(order("hard", "Order the steps to evaluate $\\displaystyle\\lim_{x\\to0}\\dfrac{\\sqrt{x+9}-3}{x}$.", ["Multiply by the conjugate $\\sqrt{x+9}+3$", "Numerator becomes $x$", "Cancel: $\\dfrac1{\\sqrt{x+9}+3}$", "Substitute: $\\tfrac16$"]));
  q.push(match("hard", "Match each limit to its value.", ["$\\lim_{x\\to0}\\tfrac{\\sqrt{x+9}-3}{x}$", "$\\lim_{x\\to\\infty}\\tfrac{x+5}{x^2+1}$", "$\\lim_{x\\to-2}\\tfrac{x^2-4}{x+2}$"], ["$\\tfrac16$", "$0$", "$-4$"], [0, 1, 2]));
  return q;
}

// ── 1.3 Continuity & Limit Laws ──────────────────────────────
function g13() {
  const q = [];
  q.push(mc("easy", "A function is continuous at $a$ if $f(a)$ is defined, the limit exists, and:", ["they are equal", "$f(a)=0$", "$a=0$", "$f$ is linear"], 0));
  q.push(mc("easy", "A hole in a graph is a:", ["removable discontinuity", "jump", "infinite discontinuity", "continuity"], 0));
  q.push(mc("easy", "A vertical asymptote gives a:", ["infinite discontinuity", "removable discontinuity", "jump", "hole"], 0));
  q.push(mc("easy", "Is $f(x)=x^2+1$ continuous at $x=2$?", ["yes", "no", "only from the left", "undefined"], 0));
  q.push(mc("easy", "A jump discontinuity occurs when:", ["the one-sided limits differ", "$f(a)$ is defined", "the graph is smooth", "$x=0$"], 0));
  q.push(mc("easy", "$\\displaystyle\\lim_{x\\to2}(3x^2-x)=$", ["10", "12", "5", "11"], 0));
  q.push(ms("easy", "Continuity at $a$ needs:", ["$f(a)$ defined", "the limit to exist", "$\\lim=f(a)$", "$f(a)=0$"], [0, 1, 2]));
  q.push(ms("easy", "Types of discontinuity:", ["removable (hole)", "jump", "infinite (asymptote)", "smooth"], [0, 1, 2]));
  q.push(ms("easy", "Limit laws split:", ["sums", "products", "quotients (nonzero denom)", "nothing"], [0, 1, 2]));
  q.push(ms("easy", "A removable discontinuity:", ["is a single hole", "the limit exists", "could be 'filled in'", "is an asymptote"], [0, 1, 2]));
  q.push(tf("easy", "A removable discontinuity is a hole.", true));
  q.push(tf("easy", "A vertical asymptote is a removable discontinuity.", false));
  q.push(tf("easy", "Continuity requires $\\lim_{x\\to a}f(x)=f(a)$.", true));
  q.push(fill("easy", "A hole is a ___ discontinuity.", ["removable"]));
  q.push(fill("easy", "$\\displaystyle\\lim_{x\\to2}(3x^2-x)$.", ["10"]));
  q.push(fill("easy", "A vertical asymptote is an ___ discontinuity.", ["infinite"]));
  q.push(num("easy", "$\\displaystyle\\lim_{x\\to2}(3x^2-x)$.", 10, 0));
  q.push(num("easy", "$\\displaystyle\\lim_{x\\to1}(4x^2+2x)$.", 6, 0));
  q.push(num("easy", "Number of conditions for continuity at a point.", 3, 0));
  q.push(match("easy", "Match each break to its type.", ["a single hole", "a sudden step", "a vertical asymptote"], ["removable", "jump", "infinite"], [0, 1, 2]));
  q.push(mc("medium", "Classify the discontinuity of $\\dfrac{x^2-4}{x-2}$ at $x=2$:", ["removable", "jump", "infinite", "none"], 0));
  q.push(mc("medium", "Classify the discontinuity of $\\dfrac1{x-3}$ at $x=3$:", ["infinite", "removable", "jump", "none"], 0));
  q.push(mc("medium", "Find $k$ so $\\begin{cases}x^2,&x\\le2\\\\kx,&x>2\\end{cases}$ is continuous at $2$:", ["2", "4", "1", "0"], 0));
  q.push(mc("medium", "Where is $\\dfrac1{x^2-9}$ discontinuous?", ["$x=\\pm3$", "$x=9$", "$x=3$", "nowhere"], 0));
  q.push(mc("medium", "Classify $\\dfrac{x^2-1}{x-1}$ at $x=1$:", ["removable", "jump", "infinite", "none"], 0));
  q.push(mc("medium", "For $\\begin{cases}x,&x<1\\\\x+2,&x\\ge1\\end{cases}$ at $x=1$:", ["jump", "removable", "infinite", "continuous"], 0));
  q.push(ms("medium", "$\\dfrac{x^2-4}{x-2}$ at $x=2$:", ["$f(2)$ undefined", "limit $=4$ exists", "removable", "infinite"], [0, 1, 2]));
  q.push(ms("medium", "Making a piecewise function continuous:", ["set the pieces equal at the boundary", "solve for the constant", "$2^2=2k\\Rightarrow k=2$", "ignore the boundary"], [0, 1, 2]));
  q.push(ms("medium", "$\\dfrac1{x-3}$ at $x=3$:", ["denominator $0$", "one-sided limits $\\pm\\infty$", "infinite discontinuity", "removable"], [0, 1, 2]));
  q.push(ms("medium", "Discontinuities of a rational function:", ["where the denominator is $0$", "removable if it cancels", "infinite if it doesn't", "never occur"], [0, 1, 2]));
  q.push(tf("medium", "$\\dfrac{x^2-4}{x-2}$ has a removable discontinuity at $x=2$.", true));
  q.push(tf("medium", "$\\begin{cases}x^2,&x\\le2\\\\kx,&x>2\\end{cases}$ is continuous at $2$ when $k=2$.", true));
  q.push(tf("medium", "$\\dfrac1{x-3}$ has a removable discontinuity at $x=3$.", false));
  q.push(fill("medium", "Type of discontinuity of $\\dfrac{x^2-4}{x-2}$ at $x=2$.", ["removable"]));
  q.push(fill("medium", "$k$ making $\\begin{cases}x^2,&x\\le2\\\\kx,&x>2\\end{cases}$ continuous at $2$.", ["2"]));
  q.push(fill("medium", "Discontinuities of $\\dfrac1{x^2-9}$.", ["x=3, x=-3", "x=±3", "3,-3"]));
  q.push(num("medium", "$k$ so $\\begin{cases}3x,&x<1\\\\x+k,&x\\ge1\\end{cases}$ is continuous at $1$.", 2, 0));
  q.push(num("medium", "Number of points where $\\dfrac1{x^2-9}$ is discontinuous.", 2, 0));
  q.push(num("medium", "$\\displaystyle\\lim_{x\\to2}(3x^2-x)$.", 10, 0));
  q.push(match("medium", "Match each to its discontinuity type.", ["$\\tfrac{x^2-4}{x-2}$ at $2$", "$\\tfrac1{x-3}$ at $3$", "step at $x=1$"], ["removable", "infinite", "jump"], [0, 1, 2]));
  q.push(mc("hard", "Find $a$ so $\\begin{cases}x^2+1,&x<2\\\\ax+1,&x\\ge2\\end{cases}$ is continuous at $2$:", ["2", "5", "4", "3"], 0));
  q.push(mc("hard", "Where is $\\dfrac{x}{x^2-x}$ discontinuous?", ["$x=0$ and $x=1$", "$x=1$", "$x=0$", "nowhere"], 0));
  q.push(mc("hard", "$\\dfrac{x}{x^2-x}$ simplifies to $\\dfrac1{x-1}$; the break at $x=0$ is:", ["removable", "infinite", "jump", "none"], 0));
  q.push(mc("hard", "For continuity of $\\begin{cases}ax+1,&x\\le1\\\\x^2+b,&x>1\\end{cases}$ at $1$, you need:", ["$a+1=1+b$", "$a=b$", "$a=1$", "$b=0$"], 0));
  q.push(mc("hard", "$\\dfrac{\\sin x}{x}$ at $x=0$ has what kind of discontinuity?", ["removable", "infinite", "jump", "none"], 0));
  q.push(ms("hard", "$\\begin{cases}x^2+1,&x<2\\\\ax+1,&x\\ge2\\end{cases}$ at $2$:", ["left value $5$", "right value $2a+1$", "$5=2a+1\\Rightarrow a=2$", "$a=4$"], [0, 1, 2]));
  q.push(ms("hard", "$\\dfrac{x}{x^2-x}$:", ["$=\\dfrac{x}{x(x-1)}$", "cancels to $\\dfrac1{x-1}$", "hole at $x=0$, asymptote at $x=1$", "continuous everywhere"], [0, 1, 2]));
  q.push(ms("hard", "Removable vs infinite:", ["removable: factor cancels", "infinite: it doesn't", "check after simplifying", "always infinite"], [0, 1, 2]));
  q.push(ms("hard", "$\\dfrac{\\sin x}{x}$ at $0$:", ["$\\tfrac00$ form", "limit $=1$", "removable", "infinite"], [0, 1, 2]));
  q.push(tf("hard", "$\\dfrac{x}{x^2-x}$ has a removable discontinuity at $x=0$.", true));
  q.push(tf("hard", "$\\begin{cases}x^2+1,&x<2\\\\ax+1,&x\\ge2\\end{cases}$ is continuous at $2$ when $a=2$.", true));
  q.push(tf("hard", "$\\dfrac{\\sin x}{x}$ has an infinite discontinuity at $0$.", false));
  q.push(fill("hard", "$a$ for $\\begin{cases}x^2+1,&x<2\\\\ax+1,&x\\ge2\\end{cases}$ continuous at $2$.", ["2"]));
  q.push(fill("hard", "Discontinuities of $\\dfrac{x}{x^2-x}$.", ["x=0, x=1", "0,1"]));
  q.push(fill("hard", "Type of break of $\\dfrac{\\sin x}{x}$ at $0$.", ["removable"]));
  q.push(num("hard", "$a$ making $\\begin{cases}x^2+1,&x<2\\\\ax+1,&x\\ge2\\end{cases}$ continuous at $2$.", 2, 0));
  q.push(num("hard", "Number of discontinuities of $\\dfrac{x}{x^2-x}$.", 2, 0));
  q.push(num("hard", "$\\displaystyle\\lim_{x\\to0}\\dfrac{\\sin x}{x}$.", 1, 0));
  q.push(order("hard", "Order the steps to make $\\begin{cases}x^2,&x\\le2\\\\kx,&x>2\\end{cases}$ continuous at $2$.", ["Match the pieces at $x=2$", "$2^2=k\\cdot2$", "$4=2k$", "$k=2$"]));
  q.push(match("hard", "Match each to its break at the stated point.", ["$\\tfrac{x}{x^2-x}$ at $0$", "$\\tfrac{x}{x^2-x}$ at $1$", "$\\tfrac{\\sin x}{x}$ at $0$"], ["removable", "infinite", "removable"], [0, 1, 2]));
  return q;
}

// ── 1.4 The Derivative from First Principles ─────────────────
function g14() {
  const q = [];
  q.push(mc("easy", "The derivative is defined as:", ["$\\lim_{h\\to0}\\dfrac{f(x+h)-f(x)}{h}$", "$\\dfrac{f(b)-f(a)}{b-a}$", "$f(x+h)-f(x)$", "$\\dfrac{f(x)}{x}$"], 0));
  q.push(mc("easy", "$f'(x)$ gives the slope of the:", ["tangent", "secant", "x-axis", "asymptote"], 0));
  q.push(mc("easy", "From first principles, $\\dfrac{d}{dx}x^2=$", ["$2x$", "$x$", "$2$", "$x^2$"], 0));
  q.push(mc("easy", "The first step in first principles is to form:", ["$\\dfrac{f(x+h)-f(x)}{h}$", "$f'(x)$", "$f(0)$", "the tangent line"], 0));
  q.push(mc("easy", "After simplifying, you let:", ["$h\\to0$", "$x\\to0$", "$h\\to\\infty$", "$h=1$"], 0));
  q.push(mc("easy", "From first principles, $\\dfrac{d}{dx}(5x)=$", ["5", "$5x$", "0", "1"], 0));
  q.push(ms("easy", "The derivative:", ["a limit of difference quotients", "the tangent slope", "a new function $f'(x)$", "the secant slope"], [0, 1, 2]));
  q.push(ms("easy", "First-principles routine:", ["form the difference quotient", "simplify to cancel $h$", "let $h\\to0$", "set $h=0$ first"], [0, 1, 2]));
  q.push(ms("easy", "Tangent line at $a$:", ["$y-f(a)=f'(a)(x-a)$", "needs $f'(a)$", "needs the point $(a,f(a))$", "$y=f'(a)$"], [0, 1, 2]));
  q.push(ms("easy", "Why first principles matters:", ["it's the definition", "the rules are built on it", "no shortcuts assumed", "it only works for lines"], [0, 1, 2]));
  q.push(tf("easy", "The derivative is the slope of the tangent line.", true));
  q.push(tf("easy", "You set $h=0$ at the very first step.", false));
  q.push(tf("easy", "From first principles, the derivative of $x^2$ is $2x$.", true));
  q.push(fill("easy", "From first principles, $\\dfrac{d}{dx}x^2$.", ["2x"]));
  q.push(fill("easy", "From first principles, $\\dfrac{d}{dx}(5x)$.", ["5"]));
  q.push(fill("easy", "The slope of the tangent is the value of ___.", ["f'(x)", "the derivative"]));
  q.push(num("easy", "$\\dfrac{d}{dx}x^2$ at $x=3$.", 6, 0));
  q.push(num("easy", "$\\dfrac{d}{dx}(5x)$ (constant).", 5, 0));
  q.push(num("easy", "$\\dfrac{d}{dx}(7)$.", 0, 0));
  q.push(match("easy", "Match each to its derivative.", ["$x^2$", "$5x$", "$7$"], ["$2x$", "$5$", "$0$"], [0, 1, 2]));
  q.push(mc("medium", "From first principles, $\\dfrac{d}{dx}(3x^2-x)=$", ["$6x-1$", "$6x$", "$3x-1$", "$6x-x$"], 0));
  q.push(mc("medium", "From first principles, $\\dfrac{d}{dx}(x^2+5x)=$", ["$2x+5$", "$2x$", "$x+5$", "$2x+5h$"], 0));
  q.push(mc("medium", "From first principles, $\\dfrac{d}{dx}(2x^2)=$", ["$4x$", "$2x$", "$4x+2h$", "$x^2$"], 0));
  q.push(mc("medium", "The tangent to $y=x^2$ at $x=3$:", ["$y=6x-9$", "$y=6x+9$", "$y=3x-9$", "$y=2x-9$"], 0));
  q.push(mc("medium", "The tangent to $y=x^2$ at $x=1$:", ["$y=2x-1$", "$y=2x+1$", "$y=x-1$", "$y=2x$"], 0));
  q.push(mc("medium", "From first principles, $\\dfrac{d}{dx}(x^2-3x)=$", ["$2x-3$", "$2x$", "$x-3$", "$2x-3h$"], 0));
  q.push(ms("medium", "Differentiating $3x^2-x$:", ["numerator $6xh+3h^2-h$", "divide by $h$: $6x+3h-1$", "$h\\to0$: $6x-1$", "$=3x-1$"], [0, 1, 2]));
  q.push(ms("medium", "Tangent line at $x=3$ for $y=x^2$:", ["$f'(3)=6$", "point $(3,9)$", "$y=6x-9$", "$y=6x$"], [0, 1, 2]));
  q.push(ms("medium", "Differentiating $x^2+5x$:", ["expand $(x+h)^2+5(x+h)$", "quotient $2x+5+h$", "$h\\to0$: $2x+5$", "$=x+5$"], [0, 1, 2]));
  q.push(ms("medium", "Linear functions:", ["constant slope", "$\\dfrac{d}{dx}(5x-3)=5$", "no $x$ in the derivative", "slope changes"], [0, 1, 2]));
  q.push(tf("medium", "From first principles $\\dfrac{d}{dx}(3x^2-x)=6x-1$.", true));
  q.push(tf("medium", "The tangent to $y=x^2$ at $x=3$ is $y=6x-9$.", true));
  q.push(tf("medium", "From first principles $\\dfrac{d}{dx}(2x^2)=2x$.", false));
  q.push(fill("medium", "From first principles, $\\dfrac{d}{dx}(3x^2-x)$.", ["6x-1"]));
  q.push(fill("medium", "Tangent to $y=x^2$ at $x=3$.", ["y=6x-9"]));
  q.push(fill("medium", "From first principles, $\\dfrac{d}{dx}(2x^2)$.", ["4x"]));
  q.push(num("medium", "$\\dfrac{d}{dx}(3x^2-x)$ at $x=2$.", 11, 0));
  q.push(num("medium", "Slope of the tangent to $y=x^2$ at $x=3$.", 6, 0));
  q.push(num("medium", "$\\dfrac{d}{dx}(x^2+5x)$ at $x=0$.", 5, 0));
  q.push(match("medium", "Match each to its derivative.", ["$3x^2-x$", "$x^2+5x$", "$2x^2$"], ["$6x-1$", "$2x+5$", "$4x$"], [0, 1, 2]));
  q.push(mc("hard", "From first principles, $\\dfrac{d}{dx}\\dfrac1x=$", ["$-\\dfrac1{x^2}$", "$\\dfrac1{x^2}$", "$-\\dfrac1x$", "$\\dfrac1x$"], 0));
  q.push(mc("hard", "From first principles, $\\dfrac{d}{dx}\\sqrt{x}=$", ["$\\dfrac1{2\\sqrt{x}}$", "$\\dfrac1{\\sqrt{x}}$", "$2\\sqrt{x}$", "$\\sqrt{x}$"], 0));
  q.push(mc("hard", "$\\dfrac{\\frac1{x+h}-\\frac1x}{h}$ simplifies to:", ["$\\dfrac{-1}{x(x+h)}$", "$\\dfrac{1}{x(x+h)}$", "$\\dfrac{-1}{x^2}$", "$\\dfrac{-h}{x}$"], 0));
  q.push(mc("hard", "To differentiate $\\sqrt{x}$ from first principles you:", ["rationalize the numerator", "factor", "expand a square", "substitute $h=0$ first"], 0));
  q.push(mc("hard", "The tangent to $y=\\dfrac1x$ at $x=1$ has slope:", ["−1", "1", "−2", "$-\\tfrac12$"], 0));
  q.push(ms("hard", "Differentiating $\\dfrac1x$:", ["combine fractions", "$\\dfrac{-h}{x(x+h)h}$", "cancel $h$ → $\\dfrac{-1}{x(x+h)}$", "limit $-\\dfrac1{x^2}$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Differentiating $\\sqrt{x}$:", ["multiply by conjugate", "numerator becomes $h$", "cancel $h$", "limit $\\dfrac1{2\\sqrt{x}}$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Tangent to $y=\\tfrac1x$ at $x=1$:", ["$f'(x)=-\\tfrac1{x^2}$", "$f'(1)=-1$", "point $(1,1)$", "slope $1$"], [0, 1, 2]));
  q.push(ms("hard", "Why these need a trick:", ["$\\tfrac00$ after substitution", "must cancel the $h$", "fractions/roots block direct sub", "no trick needed"], [0, 1, 2]));
  q.push(tf("hard", "From first principles $\\dfrac{d}{dx}\\dfrac1x=-\\dfrac1{x^2}$.", true));
  q.push(tf("hard", "From first principles $\\dfrac{d}{dx}\\sqrt{x}=\\dfrac1{2\\sqrt{x}}$.", true));
  q.push(tf("hard", "The tangent to $y=\\tfrac1x$ at $x=1$ has slope $1$.", false));
  q.push(fill("hard", "From first principles, $\\dfrac{d}{dx}\\dfrac1x$.", ["-1/x^2"]));
  q.push(fill("hard", "From first principles, $\\dfrac{d}{dx}\\sqrt{x}$.", ["1/(2sqrt(x))", "1/(2√x)"]));
  q.push(fill("hard", "Slope of the tangent to $y=\\tfrac1x$ at $x=1$.", ["-1"]));
  q.push(num("hard", "Slope of the tangent to $y=\\tfrac1x$ at $x=1$.", -1, 0));
  q.push(num("hard", "$\\dfrac{d}{dx}\\sqrt{x}$ at $x=4$ (decimal).", 0.25, 0.01));
  q.push(num("hard", "$\\dfrac{d}{dx}\\dfrac1x$ at $x=2$ (decimal).", -0.25, 0.01));
  q.push(order("hard", "Order the steps to differentiate $f(x)=\\dfrac1x$ from first principles.", ["Form $\\dfrac{\\frac1{x+h}-\\frac1x}{h}$", "Combine: $\\dfrac{-h}{x(x+h)h}$", "Cancel $h$: $\\dfrac{-1}{x(x+h)}$", "Let $h\\to0$: $-\\dfrac1{x^2}$"]));
  q.push(match("hard", "Match each to its derivative.", ["$\\dfrac1x$", "$\\sqrt{x}$", "$x^2$"], ["$-\\dfrac1{x^2}$", "$\\dfrac1{2\\sqrt{x}}$", "$2x$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "1.1", gen: g11 },
  { code: "1.2", gen: g12 },
  { code: "1.3", gen: g13 },
  { code: "1.4", gen: g14 },
];
