// MCV4U Unit 2 — Derivative Rules: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 2.1 Power, Constant & Sum Rules ──────────────────────────
function g21() {
  const q = [];
  q.push(mc("easy", "$\\dfrac{d}{dx}x^n=$", ["$nx^{n-1}$", "$x^{n-1}$", "$nx^n$", "$nx^{n+1}$"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}x^5=$", ["$5x^4$", "$5x^5$", "$x^4$", "$4x^5$"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}(7)=$", ["0", "7", "1", "$7x$"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}(3x^2)=$", ["$6x$", "$3x$", "$6x^2$", "$x$"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}(x^2+x)=$", ["$2x+1$", "$2x$", "$x+1$", "$2x+x$"], 0));
  q.push(mc("easy", "To differentiate $\\sqrt{x}$ you first write it as:", ["$x^{1/2}$", "$x^2$", "$x^{-1}$", "$2x$"], 0));
  q.push(ms("easy", "The basic rules:", ["power rule $nx^{n-1}$", "constant → 0", "sum/difference splits", "product of derivatives"], [0, 1, 2]));
  q.push(ms("easy", "Differentiating a polynomial:", ["term by term", "power rule on each", "constants vanish", "all at once with one power"], [0, 1, 2]));
  q.push(ms("easy", "Rewriting before differentiating:", ["$\\sqrt{x}=x^{1/2}$", "$\\tfrac1{x^k}=x^{-k}$", "then use the power rule", "leave as a root"], [0, 1, 2]));
  q.push(ms("easy", "$\\dfrac{d}{dx}(cf)$:", ["$=cf'$", "the constant stays", "constant-multiple rule", "$=c$"], [0, 1, 2]));
  q.push(tf("easy", "$\\dfrac{d}{dx}x^5=5x^4$.", true));
  q.push(tf("easy", "The derivative of a constant is the constant.", false));
  q.push(tf("easy", "$\\sqrt{x}=x^{1/2}$.", true));
  q.push(fill("easy", "$\\dfrac{d}{dx}x^7$.", ["7x^6"]));
  q.push(fill("easy", "$\\dfrac{d}{dx}(3x^4-2x^2+7)$.", ["12x^3-4x"]));
  q.push(fill("easy", "$\\dfrac{d}{dx}(9)$.", ["0"]));
  q.push(num("easy", "$\\dfrac{d}{dx}x^5$ at $x=1$.", 5, 0));
  q.push(num("easy", "$\\dfrac{d}{dx}(x^2)$ at $x=3$.", 6, 0));
  q.push(num("easy", "$\\dfrac{d}{dx}(4x)$.", 4, 0));
  q.push(match("easy", "Match each to its derivative.", ["$x^5$", "$3x^2$", "$7$"], ["$5x^4$", "$6x$", "$0$"], [0, 1, 2]));
  q.push(mc("medium", "$\\dfrac{d}{dx}(3x^4-2x^2+7)=$", ["$12x^3-4x$", "$12x^3-4x+7$", "$3x^3-2x$", "$12x^3-2x$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\dfrac1{x^3}=$", ["$-\\dfrac3{x^4}$", "$\\dfrac3{x^4}$", "$-\\dfrac1{x^4}$", "$-3x^2$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\sqrt{x}=$", ["$\\dfrac1{2\\sqrt{x}}$", "$\\dfrac1{\\sqrt{x}}$", "$2\\sqrt{x}$", "$\\sqrt{x}$"], 0));
  q.push(mc("medium", "For $f(x)=x^3-3x$, $f'(2)=$", ["9", "6", "3", "12"], 0));
  q.push(mc("medium", "$f(x)=x^2-4x$ has a horizontal tangent at:", ["$x=2$", "$x=4$", "$x=0$", "$x=-2$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}(x^{1/3})=$", ["$\\tfrac13x^{-2/3}$", "$\\tfrac13x^{2/3}$", "$3x^{-2/3}$", "$x^{-2/3}$"], 0));
  q.push(ms("medium", "$\\dfrac1{x^3}$:", ["rewrite $x^{-3}$", "power rule $-3x^{-4}$", "$=-\\tfrac3{x^4}$", "$=\\tfrac3{x^4}$"], [0, 1, 2]));
  q.push(ms("medium", "$f'(2)$ for $x^3-3x$:", ["$f'(x)=3x^2-3$", "$f'(2)=12-3$", "$=9$", "$=6$"], [0, 1, 2]));
  q.push(ms("medium", "Horizontal tangents:", ["solve $f'(x)=0$", "turning points", "$x^2-4x\\Rightarrow 2x-4=0$", "$x=4$"], [0, 1, 2]));
  q.push(ms("medium", "Fractional exponents:", ["$\\sqrt[3]{x}=x^{1/3}$", "power rule applies", "$\\tfrac13x^{-2/3}$", "no rule for these"], [0, 1, 2]));
  q.push(tf("medium", "$\\dfrac{d}{dx}\\dfrac1{x^3}=-\\dfrac3{x^4}$.", true));
  q.push(tf("medium", "$f(x)=x^3-3x$ has $f'(2)=9$.", true));
  q.push(tf("medium", "$f(x)=x^2-4x$ has a horizontal tangent at $x=4$.", false));
  q.push(fill("medium", "$\\dfrac{d}{dx}\\dfrac1{x^3}$.", ["-3/x^4"]));
  q.push(fill("medium", "$f'(2)$ for $f(x)=x^3-3x$.", ["9"]));
  q.push(fill("medium", "Horizontal tangent of $f(x)=x^2-4x$.", ["x=2"]));
  q.push(num("medium", "$f'(2)$ for $f(x)=x^3-3x$.", 9, 0));
  q.push(num("medium", "$x$-value of the horizontal tangent of $f(x)=x^2-6x$.", 3, 0));
  q.push(num("medium", "$f'(1)$ for $f(x)=x^4-2x$.", 2, 0));
  q.push(match("medium", "Match each to its derivative.", ["$\\tfrac1{x^3}$", "$\\sqrt{x}$", "$x^{1/3}$"], ["$-\\tfrac3{x^4}$", "$\\tfrac1{2\\sqrt{x}}$", "$\\tfrac13x^{-2/3}$"], [0, 1, 2]));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\left(\\sqrt{x}+\\dfrac1{x^2}\\right)=$", ["$\\dfrac1{2\\sqrt{x}}-\\dfrac2{x^3}$", "$\\dfrac1{2\\sqrt{x}}+\\dfrac2{x^3}$", "$2\\sqrt{x}-2x^3$", "$\\dfrac1{\\sqrt{x}}-\\dfrac2{x^3}$"], 0));
  q.push(mc("hard", "The tangent to $f(x)=x^2-2x$ at $x=3$ is:", ["$y=4x-9$", "$y=4x-3$", "$y=2x-9$", "$y=4x+3$"], 0));
  q.push(mc("hard", "$f(x)=x^3-12x$ has horizontal tangents at:", ["$x=\\pm2$", "$x=\\pm4$", "$x=0$", "$x=\\pm12$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\left(\\dfrac{x^2+1}{x}\\right)$ (split first):", ["$1-\\dfrac1{x^2}$", "$2x$", "$1+\\dfrac1{x^2}$", "$\\dfrac1{x^2}$"], 0));
  q.push(mc("hard", "If $f'(x)=3x^2-12$, where is $f$ increasing?", ["$|x|>2$", "$|x|<2$", "$x>0$", "all $x$"], 0));
  q.push(ms("hard", "$\\sqrt{x}+\\tfrac1{x^2}$:", ["$x^{1/2}+x^{-2}$", "$\\tfrac12x^{-1/2}-2x^{-3}$", "$=\\tfrac1{2\\sqrt{x}}-\\tfrac2{x^3}$", "constant"], [0, 1, 2]));
  q.push(ms("hard", "Tangent line at $x=3$ for $x^2-2x$:", ["$f'(3)=4$", "$f(3)=3$", "$y-3=4(x-3)$", "$y=4x-9$"], [0, 1, 2, 3]));
  q.push(ms("hard", "$\\dfrac{x^2+1}{x}$ split:", ["$x+\\tfrac1x$", "$=x+x^{-1}$", "derivative $1-x^{-2}$", "use the quotient rule only"], [0, 1, 2]));
  q.push(ms("hard", "Increasing where $f'>0$:", ["$3x^2-12>0$", "$x^2>4$", "$|x|>2$", "$|x|<2$"], [0, 1, 2]));
  q.push(tf("hard", "$\\dfrac{d}{dx}\\left(\\sqrt{x}+\\tfrac1{x^2}\\right)=\\tfrac1{2\\sqrt{x}}-\\tfrac2{x^3}$.", true));
  q.push(tf("hard", "The tangent to $x^2-2x$ at $x=3$ is $y=4x-9$.", true));
  q.push(tf("hard", "$x^3-12x$ has horizontal tangents at $x=\\pm4$.", false));
  q.push(fill("hard", "Tangent to $f(x)=x^2-2x$ at $x=3$.", ["y=4x-9"]));
  q.push(fill("hard", "Horizontal tangents of $f(x)=x^3-12x$.", ["x=±2", "x=2, x=-2", "2,-2"]));
  q.push(fill("hard", "$\\dfrac{d}{dx}\\left(\\dfrac{x^2+1}{x}\\right)$.", ["1-1/x^2"]));
  q.push(num("hard", "Slope of the tangent to $x^2-2x$ at $x=3$.", 4, 0));
  q.push(num("hard", "Positive $x$ where $x^3-12x$ has a horizontal tangent.", 2, 0));
  q.push(num("hard", "$f'(4)$ for $f(x)=\\sqrt{x}$ (decimal).", 0.25, 0.01));
  q.push(order("hard", "Order the steps to find the tangent to $f(x)=x^2-2x$ at $x=3$.", ["$f'(x)=2x-2$", "$f'(3)=4$", "$f(3)=3$ → point $(3,3)$", "$y=4x-9$"]));
  q.push(match("hard", "Match each to its result.", ["tangent of $x^2-2x$ at 3", "horiz. tangents of $x^3-12x$", "$f'(4)$ of $\\sqrt{x}$"], ["$y=4x-9$", "$x=\\pm2$", "$\\tfrac14$"], [0, 1, 2]));
  return q;
}

// ── 2.2 Product & Quotient Rules ─────────────────────────────
function g22() {
  const q = [];
  q.push(mc("easy", "The product rule is:", ["$f'g+fg'$", "$f'g'$", "$f'g-fg'$", "$fg'$"], 0));
  q.push(mc("easy", "The quotient rule is:", ["$\\dfrac{f'g-fg'}{g^2}$", "$\\dfrac{f'g+fg'}{g^2}$", "$\\dfrac{f'}{g'}$", "$\\dfrac{fg'-f'g}{g^2}$"], 0));
  q.push(mc("easy", "$(fg)'$ equals:", ["$f'g+fg'$", "$f'g'$", "$fg$", "$f+g$"], 0));
  q.push(mc("easy", "Is $(fg)'=f'g'$?", ["no", "yes", "only for polynomials", "only at 0"], 0));
  q.push(mc("easy", "In the quotient rule the bottom becomes:", ["$g^2$", "$g$", "$2g$", "$g'$"], 0));
  q.push(mc("easy", "Sometimes instead of the product rule you can:", ["expand", "ignore it", "use the chain rule", "set it to 0"], 0));
  q.push(ms("easy", "Product rule:", ["$(fg)'=f'g+fg'$", "both terms", "not $f'g'$", "$=f'g'$"], [0, 1, 2]));
  q.push(ms("easy", "Quotient rule:", ["$\\dfrac{f'g-fg'}{g^2}$", "top derivative first", "square the bottom", "add the terms"], [0, 1, 2]));
  q.push(ms("easy", "When to expand instead:", ["if the product is simple", "e.g. $x^2(x+1)$", "then power rule", "always use the rule"], [0, 1, 2]));
  q.push(ms("easy", "Order in the quotient rule:", ["$f'g$ comes first", "then $-fg'$", "the minus sign matters", "order is irrelevant"], [0, 1, 2]));
  q.push(tf("easy", "$(fg)'=f'g+fg'$.", true));
  q.push(tf("easy", "$(fg)'=f'g'$.", false));
  q.push(tf("easy", "The quotient rule squares the denominator.", true));
  q.push(fill("easy", "The product rule: $(fg)'=$", ["f'g+fg'"]));
  q.push(fill("easy", "$\\dfrac{d}{dx}[x^2(x+1)]$ (simplified).", ["3x^2+2x"]));
  q.push(fill("easy", "The denominator in the quotient rule is ___.", ["g^2"]));
  q.push(num("easy", "$\\dfrac{d}{dx}[x^2(x+1)]$ at $x=1$.", 5, 0));
  q.push(num("easy", "Given $f'=2,g=3,f=1,g'=4$: $(fg)'$.", 10, 0));
  q.push(num("easy", "$\\dfrac{d}{dx}[x\\cdot x]$ at $x=3$.", 6, 0));
  q.push(match("easy", "Match each rule.", ["product", "quotient", "expand-first"], ["$f'g+fg'$", "$\\tfrac{f'g-fg'}{g^2}$", "for simple products"], [0, 1, 2]));
  q.push(mc("medium", "$\\dfrac{d}{dx}[x^2(x+1)]=$", ["$3x^2+2x$", "$2x$", "$3x^2$", "$2x^2+x$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}[(2x+1)(x^2-3)]=$", ["$6x^2+2x-6$", "$4x$", "$6x^2-6$", "$2x^2-6$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\dfrac{x+1}{x-1}=$", ["$\\dfrac{-2}{(x-1)^2}$", "$\\dfrac{2}{(x-1)^2}$", "$1$", "$\\dfrac{-2}{x-1}$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\dfrac{x^2}{x+1}=$", ["$\\dfrac{x^2+2x}{(x+1)^2}$", "$\\dfrac{2x}{x+1}$", "$\\dfrac{x^2-2x}{(x+1)^2}$", "$2x$"], 0));
  q.push(mc("medium", "Given $f(2)=3,f'(2)=1,g(2)=4,g'(2)=-2$: $(fg)'(2)=$", ["−2", "2", "−6", "10"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\dfrac{x}{x+2}=$", ["$\\dfrac{2}{(x+2)^2}$", "$\\dfrac{-2}{(x+2)^2}$", "$1$", "$\\dfrac{1}{x+2}$"], 0));
  q.push(ms("medium", "$x^2(x+1)$:", ["$2x(x+1)+x^2$", "$=3x^2+2x$", "or expand to $x^3+x^2$", "$=2x$"], [0, 1, 2]));
  q.push(ms("medium", "$\\dfrac{x+1}{x-1}$:", ["$\\dfrac{(x-1)-(x+1)}{(x-1)^2}$", "numerator $-2$", "$=\\dfrac{-2}{(x-1)^2}$", "$=\\dfrac{2}{(x-1)^2}$"], [0, 1, 2]));
  q.push(ms("medium", "$(fg)'(2)$ from data:", ["$f'g+fg'$", "$(1)(4)+(3)(-2)$", "$=-2$", "$=10$"], [0, 1, 2]));
  q.push(ms("medium", "$\\dfrac{x^2}{x+1}$:", ["$\\dfrac{2x(x+1)-x^2}{(x+1)^2}$", "numerator $x^2+2x$", "result $\\dfrac{x^2+2x}{(x+1)^2}$", "$=2x$"], [0, 1, 2]));
  q.push(tf("medium", "$\\dfrac{d}{dx}[x^2(x+1)]=3x^2+2x$.", true));
  q.push(tf("medium", "$\\dfrac{d}{dx}\\dfrac{x+1}{x-1}=\\dfrac{-2}{(x-1)^2}$.", true));
  q.push(tf("medium", "$(fg)'(2)=10$ for the data $f(2)=3,f'(2)=1,g(2)=4,g'(2)=-2$.", false));
  q.push(fill("medium", "$\\dfrac{d}{dx}[(2x+1)(x^2-3)]$.", ["6x^2+2x-6"]));
  q.push(fill("medium", "$\\dfrac{d}{dx}\\dfrac{x+1}{x-1}$.", ["-2/(x-1)^2"]));
  q.push(fill("medium", "$(fg)'(2)$ for the given data.", ["-2"]));
  q.push(num("medium", "$(fg)'(2)$ for $f(2)=3,f'(2)=1,g(2)=4,g'(2)=-2$.", -2, 0));
  q.push(num("medium", "$(fg)'(1)$ for $f(1)=2,f'(1)=3,g(1)=5,g'(1)=-1$.", 13, 0));
  q.push(num("medium", "$\\dfrac{d}{dx}[x^3(x-2)]$ at $x=1$ (it's $4x^3-6x^2$).", -2, 0));
  q.push(match("medium", "Match each to its derivative.", ["$\\tfrac{x+1}{x-1}$", "$\\tfrac{x}{x+2}$", "$x^2(x+1)$"], ["$\\tfrac{-2}{(x-1)^2}$", "$\\tfrac{2}{(x+2)^2}$", "$3x^2+2x$"], [0, 1, 2]));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\dfrac{x^2-1}{x^2+1}=$", ["$\\dfrac{4x}{(x^2+1)^2}$", "$\\dfrac{-4x}{(x^2+1)^2}$", "$\\dfrac{2x}{x^2+1}$", "$1$"], 0));
  q.push(mc("hard", "Given $f(0)=1,f'(0)=2,g(0)=3,g'(0)=4$: $\\left(\\tfrac fg\\right)'(0)=$", ["$\\tfrac29$", "$\\tfrac{2}{3}$", "$-\\tfrac29$", "$\\tfrac{10}{9}$"], 0));
  q.push(mc("hard", "The tangent to $f(x)=\\dfrac{x}{x+1}$ at $x=1$ has slope:", ["$\\tfrac14$", "$\\tfrac12$", "$1$", "$-\\tfrac14$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\big[(x^2+1)(x^3-x)\\big]$ at $x=1$:", ["8", "4", "6", "2"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\dfrac{\\sqrt{x}}{x+1}$ uses:", ["quotient + power rule", "product rule only", "chain rule only", "no rule"], 0));
  q.push(ms("hard", "$\\dfrac{x^2-1}{x^2+1}$:", ["$\\dfrac{2x(x^2+1)-(x^2-1)2x}{(x^2+1)^2}$", "numerator $4x$", "$=\\dfrac{4x}{(x^2+1)^2}$", "$=\\dfrac{-4x}{(x^2+1)^2}$"], [0, 1, 2]));
  q.push(ms("hard", "$\\left(\\tfrac fg\\right)'(0)$ from data:", ["$\\dfrac{f'g-fg'}{g^2}$", "$\\dfrac{(2)(3)-(1)(4)}{9}$", "$=\\tfrac29$", "$=\\tfrac{10}9$"], [0, 1, 2]));
  q.push(ms("hard", "Tangent to $\\tfrac{x}{x+1}$ at 1:", ["$f'(x)=\\dfrac1{(x+1)^2}$", "$f'(1)=\\tfrac14$", "point $(1,\\tfrac12)$", "slope $1$"], [0, 1, 2]));
  q.push(ms("hard", "Combining rules:", ["$(x^2+1)(x^3-x)$ → product rule", "$\\tfrac{\\sqrt x}{x+1}$ → quotient + power", "pick by structure", "always quotient"], [0, 1, 2]));
  q.push(tf("hard", "$\\dfrac{d}{dx}\\dfrac{x^2-1}{x^2+1}=\\dfrac{4x}{(x^2+1)^2}$.", true));
  q.push(tf("hard", "$\\left(\\tfrac fg\\right)'(0)=\\tfrac29$ for $f(0)=1,f'(0)=2,g(0)=3,g'(0)=4$.", true));
  q.push(tf("hard", "The tangent to $\\tfrac{x}{x+1}$ at $x=1$ has slope $1$.", false));
  q.push(fill("hard", "$\\dfrac{d}{dx}\\dfrac{x^2-1}{x^2+1}$.", ["4x/(x^2+1)^2"]));
  q.push(fill("hard", "$\\left(\\tfrac fg\\right)'(0)$ for the given data.", ["2/9"]));
  q.push(fill("hard", "Slope of the tangent to $\\tfrac{x}{x+1}$ at $x=1$.", ["1/4"]));
  q.push(num("hard", "$\\left(\\tfrac fg\\right)'(0)$ as a decimal for the given data.", 0.222, 0.01));
  q.push(num("hard", "$\\dfrac{d}{dx}\\big[(x^2+1)(x^3-x)\\big]$ at $x=1$.", 8, 0));
  q.push(num("hard", "Slope of the tangent to $\\tfrac{x}{x+1}$ at $x=1$ (decimal).", 0.25, 0.01));
  q.push(order("hard", "Order the steps to differentiate $\\dfrac{x+1}{x-1}$.", ["Quotient rule: $\\dfrac{(1)(x-1)-(x+1)(1)}{(x-1)^2}$", "Numerator: $x-1-x-1$", "$=-2$", "Result $\\dfrac{-2}{(x-1)^2}$"]));
  q.push(match("hard", "Match each to its derivative.", ["$\\tfrac{x^2-1}{x^2+1}$", "$\\tfrac{x}{x+1}$", "$x^2(x+1)$"], ["$\\tfrac{4x}{(x^2+1)^2}$", "$\\tfrac1{(x+1)^2}$", "$3x^2+2x$"], [0, 1, 2]));
  return q;
}

// ── 2.3 The Chain Rule ───────────────────────────────────────
function g23() {
  const q = [];
  q.push(mc("easy", "The chain rule is:", ["$f'(g(x))\\cdot g'(x)$", "$f'(x)g'(x)$", "$f'(g(x))$", "$f(g'(x))$"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}(x^2+1)^3=$", ["$6x(x^2+1)^2$", "$3(x^2+1)^2$", "$6x$", "$3(x^2+1)^2\\cdot x$"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}[g(x)]^n=$", ["$n[g(x)]^{n-1}g'(x)$", "$n[g(x)]^{n-1}$", "$[g(x)]^{n-1}$", "$ng'(x)$"], 0));
  q.push(mc("easy", "The most-forgotten part of the chain rule is:", ["the inner derivative", "the power", "the constant", "the sign"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}(3x)^2=$", ["$18x$", "$6x$", "$9x$", "$3x$"], 0));
  q.push(mc("easy", "A composite function is:", ["a function inside a function", "a product", "a sum", "a quotient"], 0));
  q.push(ms("easy", "Chain rule:", ["outer derivative", "× inner derivative", "$f'(g)\\cdot g'$", "just the outer"], [0, 1, 2]));
  q.push(ms("easy", "Power of a function:", ["$n[g]^{n-1}g'$", "bring down the power", "times the inner derivative", "ignore the inside"], [0, 1, 2]));
  q.push(ms("easy", "Spotting a composite:", ["something inside a power/root", "e.g. $(x^2+1)^3$", "or $\\sqrt{x^2+1}$", "a plain polynomial"], [0, 1, 2]));
  q.push(ms("easy", "Why $g'(x)$ matters:", ["it's the inner rate", "forgetting it is the top error", "needed for correctness", "it's optional"], [0, 1, 2]));
  q.push(tf("easy", "The chain rule multiplies by the inner derivative.", true));
  q.push(tf("easy", "$\\dfrac{d}{dx}(x^2+1)^3=3(x^2+1)^2$ (no inner derivative).", false));
  q.push(tf("easy", "$(x^2+1)^3$ is a composite function.", true));
  q.push(fill("easy", "$\\dfrac{d}{dx}(x^2+1)^3$.", ["6x(x^2+1)^2"]));
  q.push(fill("easy", "$\\dfrac{d}{dx}(3x-2)^5$.", ["15(3x-2)^4"]));
  q.push(fill("easy", "The chain rule: $\\dfrac{d}{dx}f(g(x))=$", ["f'(g(x))g'(x)", "f'(g(x))·g'(x)"]));
  q.push(num("easy", "$\\dfrac{d}{dx}(x^2+1)^3$ at $x=1$ (it's $6x(x^2+1)^2$).", 24, 0));
  q.push(num("easy", "Inner derivative of $(3x-2)^5$.", 3, 0));
  q.push(num("easy", "$\\dfrac{d}{dx}(2x)^3$ at $x=1$ (it's $24x^2$).", 24, 0));
  q.push(match("easy", "Match each to its derivative.", ["$(x^2+1)^3$", "$(3x-2)^5$", "$(5x+1)^4$"], ["$6x(x^2+1)^2$", "$15(3x-2)^4$", "$20(5x+1)^3$"], [0, 1, 2]));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\sqrt{x^2+1}=$", ["$\\dfrac{x}{\\sqrt{x^2+1}}$", "$\\dfrac1{2\\sqrt{x^2+1}}$", "$2x$", "$\\dfrac{2x}{\\sqrt{x^2+1}}$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}(3x-2)^5=$", ["$15(3x-2)^4$", "$5(3x-2)^4$", "$3(3x-2)^4$", "$15(3x-2)^5$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}(x^3+x)^4=$", ["$4(x^3+x)^3(3x^2+1)$", "$4(x^3+x)^3$", "$(3x^2+1)^4$", "$4(3x^2+1)^3$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\dfrac1{(x+1)^2}=$", ["$\\dfrac{-2}{(x+1)^3}$", "$\\dfrac{2}{(x+1)^3}$", "$\\dfrac{-1}{(x+1)^3}$", "$\\dfrac{-2}{(x+1)^2}$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}(x^2+3x)^5=$", ["$5(x^2+3x)^4(2x+3)$", "$5(x^2+3x)^4$", "$(2x+3)^5$", "$5(2x+3)^4$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\sqrt{2x+1}=$", ["$\\dfrac1{\\sqrt{2x+1}}$", "$\\dfrac1{2\\sqrt{2x+1}}$", "$\\dfrac2{\\sqrt{2x+1}}$", "$\\sqrt{2x+1}$"], 0));
  q.push(ms("medium", "$\\sqrt{x^2+1}$:", ["$(x^2+1)^{1/2}$", "$\\tfrac12(x^2+1)^{-1/2}\\cdot2x$", "$=\\dfrac{x}{\\sqrt{x^2+1}}$", "$=2x$"], [0, 1, 2]));
  q.push(ms("medium", "$(3x-2)^5$:", ["outer $5(3x-2)^4$", "inner derivative $3$", "$=15(3x-2)^4$", "$=5(3x-2)^4$"], [0, 1, 2]));
  q.push(ms("medium", "$\\dfrac1{(x+1)^2}$:", ["$(x+1)^{-2}$", "$-2(x+1)^{-3}$", "$=\\dfrac{-2}{(x+1)^3}$", "inner derivative $1$"], [0, 1, 2, 3]));
  q.push(ms("medium", "$(x^3+x)^4$:", ["$4(x^3+x)^3$", "× $(3x^2+1)$", "the inner derivative", "ignore the inside"], [0, 1, 2]));
  q.push(tf("medium", "$\\dfrac{d}{dx}\\sqrt{x^2+1}=\\dfrac{x}{\\sqrt{x^2+1}}$.", true));
  q.push(tf("medium", "$\\dfrac{d}{dx}(3x-2)^5=15(3x-2)^4$.", true));
  q.push(tf("medium", "$\\dfrac{d}{dx}(x^3+x)^4=4(x^3+x)^3$.", false));
  q.push(fill("medium", "$\\dfrac{d}{dx}\\sqrt{x^2+1}$.", ["x/sqrt(x^2+1)", "x/√(x^2+1)"]));
  q.push(fill("medium", "$\\dfrac{d}{dx}(x^3+x)^4$.", ["4(x^3+x)^3(3x^2+1)"]));
  q.push(fill("medium", "$\\dfrac{d}{dx}\\dfrac1{(x+1)^2}$.", ["-2/(x+1)^3"]));
  q.push(num("medium", "$\\dfrac{d}{dx}\\sqrt{2x+1}$ at $x=4$ (it's $1/\\sqrt{2x+1}$).", 0.333, 0.02));
  q.push(num("medium", "$\\dfrac{d}{dx}(x^2-4)^3$ at $x=0$ (it's $6x(x^2-4)^2$).", 0, 0));
  q.push(num("medium", "Inner derivative used for $(x^2+3x)^5$ at $x=1$.", 5, 0));
  q.push(match("medium", "Match each to its derivative.", ["$\\sqrt{x^2+1}$", "$(x^3+x)^4$", "$\\tfrac1{(x+1)^2}$"], ["$\\tfrac{x}{\\sqrt{x^2+1}}$", "$4(x^3+x)^3(3x^2+1)$", "$\\tfrac{-2}{(x+1)^3}$"], [0, 1, 2]));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\big[x(2x+1)^3\\big]=$", ["$(2x+1)^2(8x+1)$", "$3(2x+1)^2$", "$(2x+1)^3$", "$6x(2x+1)^2$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\big[x^2(x+1)^3\\big]=$", ["$2x(x+1)^3+3x^2(x+1)^2$", "$6x(x+1)^2$", "$2x(x+1)^3$", "$5x(x+1)^2$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\sqrt{x^2+x+1}$ at $x=1$ is (using $\\dfrac{2x+1}{2\\sqrt{x^2+x+1}}$):", ["$\\dfrac{3}{2\\sqrt3}$", "$\\dfrac1{2\\sqrt3}$", "$\\sqrt3$", "$3$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}(x^2+1)^{1/2}=$", ["$\\dfrac{x}{\\sqrt{x^2+1}}$", "$\\dfrac1{2\\sqrt{x^2+1}}$", "$2x$", "$\\dfrac{2x}{\\sqrt{x^2+1}}$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\big[(x-1)^2(x+1)^3\\big]$ uses:", ["product + chain on each factor", "chain only", "quotient", "power rule only"], 0));
  q.push(ms("hard", "$x(2x+1)^3$:", ["product rule", "$(2x+1)^3+x\\cdot3(2x+1)^2\\cdot2$", "factor $(2x+1)^2$", "$=(2x+1)^2(8x+1)$"], [0, 1, 2, 3]));
  q.push(ms("hard", "$x^2(x+1)^3$:", ["product rule", "$2x(x+1)^3$", "$+\\,3x^2(x+1)^2$", "no chain needed"], [0, 1, 2]));
  q.push(ms("hard", "Mixing rules:", ["identify the structure", "product on the outside", "chain on composites", "use one rule only"], [0, 1, 2]));
  q.push(ms("hard", "$\\sqrt{x^2+x+1}$:", ["$(x^2+x+1)^{1/2}$", "$\\tfrac12(\\cdots)^{-1/2}(2x+1)$", "$=\\dfrac{2x+1}{2\\sqrt{x^2+x+1}}$", "$=2x+1$"], [0, 1, 2]));
  q.push(tf("hard", "$\\dfrac{d}{dx}[x(2x+1)^3]=(2x+1)^2(8x+1)$.", true));
  q.push(tf("hard", "$\\dfrac{d}{dx}[x^2(x+1)^3]=2x(x+1)^3+3x^2(x+1)^2$.", true));
  q.push(tf("hard", "$\\dfrac{d}{dx}(x^2+1)^{1/2}=\\dfrac{2x}{\\sqrt{x^2+1}}$.", false));
  q.push(fill("hard", "$\\dfrac{d}{dx}[x(2x+1)^3]$ (factored).", ["(2x+1)^2(8x+1)"]));
  q.push(fill("hard", "$\\dfrac{d}{dx}\\sqrt{x^2+x+1}$.", ["(2x+1)/(2sqrt(x^2+x+1))", "(2x+1)/(2√(x^2+x+1))"]));
  q.push(fill("hard", "$\\dfrac{d}{dx}(x^2+1)^{1/2}$.", ["x/sqrt(x^2+1)", "x/√(x^2+1)"]));
  q.push(num("hard", "$\\dfrac{d}{dx}[x(2x+1)^3]$ at $x=0$ (it's $(2x+1)^2(8x+1)$).", 1, 0));
  q.push(num("hard", "$\\dfrac{d}{dx}(x^2-4)^3$ at $x=1$ (it's $6x(x^2-4)^2$).", 54, 0));
  q.push(num("hard", "$\\dfrac{d}{dx}\\sqrt{2x+1}$ at $x=0$ (it's $1/\\sqrt{2x+1}$).", 1, 0));
  q.push(order("hard", "Order the steps to differentiate $x(2x+1)^3$.", ["Product rule", "$(2x+1)^3+x\\cdot3(2x+1)^2\\cdot2$", "Factor $(2x+1)^2$", "$(2x+1)^2(8x+1)$"]));
  q.push(match("hard", "Match each to its derivative.", ["$x(2x+1)^3$", "$\\sqrt{x^2+1}$", "$(3x-2)^5$"], ["$(2x+1)^2(8x+1)$", "$\\tfrac{x}{\\sqrt{x^2+1}}$", "$15(3x-2)^4$"], [0, 1, 2]));
  return q;
}

// ── 2.4 Rational, Radical & Higher-Order Derivatives ─────────
function g24() {
  const q = [];
  q.push(mc("easy", "$\\dfrac{d}{dx}\\dfrac1{x^2}=$", ["$-\\dfrac2{x^3}$", "$\\dfrac2{x^3}$", "$-\\dfrac1{x^3}$", "$-2x$"], 0));
  q.push(mc("easy", "$\\dfrac1{x^k}$ rewritten is:", ["$x^{-k}$", "$x^k$", "$kx$", "$x^{1/k}$"], 0));
  q.push(mc("easy", "The second derivative is:", ["$(f')'$", "$f'$", "$2f$", "$f^2$"], 0));
  q.push(mc("easy", "For $f(x)=x^4$, $f''(x)=$", ["$12x^2$", "$4x^3$", "$24x$", "$x^2$"], 0));
  q.push(mc("easy", "$\\sqrt[3]{x^2}$ rewritten is:", ["$x^{2/3}$", "$x^{3/2}$", "$x^{-2/3}$", "$x^6$"], 0));
  q.push(mc("easy", "Implicit differentiation attaches ___ to every $y$.", ["$\\tfrac{dy}{dx}$", "$x$", "$y^2$", "nothing"], 0));
  q.push(ms("easy", "Rewriting tricks:", ["$\\tfrac1{x^k}=x^{-k}$", "$\\sqrt[n]{x^m}=x^{m/n}$", "then power rule", "leave as roots"], [0, 1, 2]));
  q.push(ms("easy", "Second derivative:", ["differentiate twice", "$f''=(f')'$", "measures concavity", "$=f^2$"], [0, 1, 2]));
  q.push(ms("easy", "Implicit differentiation:", ["differentiate both sides", "treat $y$ as a function of $x$", "every $y$ gets $\\tfrac{dy}{dx}$", "solve for $y$ first"], [0, 1, 2]));
  q.push(ms("easy", "Higher-order:", ["$f'$ then $f''$ then $f'''$", "each is the slope of the last", "polynomials eventually reach 0", "they never end"], [0, 1, 2]));
  q.push(tf("easy", "$\\dfrac{d}{dx}\\dfrac1{x^2}=-\\dfrac2{x^3}$.", true));
  q.push(tf("easy", "The second derivative of $x^4$ is $4x^3$.", false));
  q.push(tf("easy", "$\\sqrt[3]{x^2}=x^{2/3}$.", true));
  q.push(fill("easy", "$\\dfrac{d}{dx}\\dfrac1{x^2}$.", ["-2/x^3"]));
  q.push(fill("easy", "$f''(x)$ for $f(x)=x^4$.", ["12x^2"]));
  q.push(fill("easy", "Rewrite $\\sqrt[3]{x^2}$ as a power.", ["x^(2/3)", "x^{2/3}"]));
  q.push(num("easy", "$f''(x)$ for $f(x)=x^4$ at $x=1$.", 12, 0));
  q.push(num("easy", "$f''(x)$ for $f(x)=x^3$ at $x=1$.", 6, 0));
  q.push(num("easy", "$\\dfrac{d}{dx}\\dfrac1{x^2}$ at $x=1$.", -2, 0));
  q.push(match("easy", "Match each to its second derivative.", ["$x^4$", "$x^3$", "$x^2$"], ["$12x^2$", "$6x$", "$2$"], [0, 1, 2]));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\sqrt[3]{x^2}=$", ["$\\tfrac23x^{-1/3}$", "$\\tfrac23x^{1/3}$", "$\\tfrac32x^{1/2}$", "$x^{-1/3}$"], 0));
  q.push(mc("medium", "For $f(x)=x^3-3x$, $f''(x)=$", ["$6x$", "$3x^2-3$", "$6$", "$6x-3$"], 0));
  q.push(mc("medium", "For $x^2+y^2=25$, $\\dfrac{dy}{dx}=$", ["$-\\dfrac xy$", "$\\dfrac xy$", "$-\\dfrac yx$", "$-x$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\dfrac1{x^4}=$", ["$-\\dfrac4{x^5}$", "$\\dfrac4{x^5}$", "$-\\dfrac1{x^5}$", "$-4x^3$"], 0));
  q.push(mc("medium", "For $f(x)=x^5$, $f''(x)=$", ["$20x^3$", "$5x^4$", "$60x^2$", "$x^3$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}x^{3/2}=$", ["$\\tfrac32x^{1/2}$", "$\\tfrac32x^{-1/2}$", "$\\tfrac23x^{1/2}$", "$x^{1/2}$"], 0));
  q.push(ms("medium", "$f''$ for $x^3-3x$:", ["$f'=3x^2-3$", "$f''=6x$", "$f''(1)=6$", "$f''=6$"], [0, 1, 2]));
  q.push(ms("medium", "Implicit on $x^2+y^2=25$:", ["$2x+2yy'=0$", "solve for $y'$", "$y'=-\\dfrac xy$", "$y'=-x$"], [0, 1, 2]));
  q.push(ms("medium", "$\\dfrac1{x^4}$:", ["$x^{-4}$", "$-4x^{-5}$", "$=-\\dfrac4{x^5}$", "$=\\dfrac4{x^5}$"], [0, 1, 2]));
  q.push(ms("medium", "$x^{3/2}$:", ["power rule", "$\\tfrac32x^{1/2}$", "$=\\tfrac32\\sqrt{x}$", "$=\\tfrac23x^{1/2}$"], [0, 1, 2]));
  q.push(tf("medium", "For $f(x)=x^3-3x$, $f''(x)=6x$.", true));
  q.push(tf("medium", "For $x^2+y^2=25$, $\\dfrac{dy}{dx}=-\\dfrac xy$.", true));
  q.push(tf("medium", "For $f(x)=x^5$, $f''(x)=5x^4$.", false));
  q.push(fill("medium", "$f''(x)$ for $f(x)=x^3-3x$.", ["6x"]));
  q.push(fill("medium", "$\\dfrac{dy}{dx}$ for $x^2+y^2=25$.", ["-x/y"]));
  q.push(fill("medium", "$\\dfrac{d}{dx}\\dfrac1{x^4}$.", ["-4/x^5"]));
  q.push(num("medium", "$f''(1)$ for $f(x)=x^3-3x$.", 6, 0));
  q.push(num("medium", "$f''(x)$ for $f(x)=x^5$ at $x=1$.", 20, 0));
  q.push(num("medium", "Slope $\\tfrac{dy}{dx}$ of $x^2+y^2=25$ at $(3,4)$ (decimal).", -0.75, 0.01));
  q.push(match("medium", "Match each to its result.", ["$f''$ of $x^3-3x$", "$\\tfrac{dy}{dx}$ of $x^2+y^2=25$", "$\\tfrac{d}{dx}\\tfrac1{x^4}$"], ["$6x$", "$-\\tfrac xy$", "$-\\tfrac4{x^5}$"], [0, 1, 2]));
  q.push(mc("hard", "For $xy=4$, $\\dfrac{dy}{dx}=$", ["$-\\dfrac yx$", "$\\dfrac yx$", "$-\\dfrac4{x^2}$", "$-x$"], 0));
  q.push(mc("hard", "For $x^2+xy+y^2=7$, $\\dfrac{dy}{dx}=$", ["$-\\dfrac{2x+y}{x+2y}$", "$-\\dfrac{x+y}{x+y}$", "$\\dfrac{2x+y}{x+2y}$", "$-\\dfrac{2x}{2y}$"], 0));
  q.push(mc("hard", "For $f(x)=x^4-2x^2$, $f''(x)=$", ["$12x^2-4$", "$4x^3-4x$", "$12x^2$", "$12x-4$"], 0));
  q.push(mc("hard", "The third derivative of $x^4$ is:", ["$24x$", "$12x^2$", "$24$", "$4x^3$"], 0));
  q.push(mc("hard", "For $x^2-y^2=1$, $\\dfrac{dy}{dx}=$", ["$\\dfrac xy$", "$-\\dfrac xy$", "$\\dfrac yx$", "$-\\dfrac yx$"], 0));
  q.push(ms("hard", "Implicit on $xy=4$:", ["product rule on $xy$", "$y+xy'=0$", "$y'=-\\dfrac yx$", "$y'=-x$"], [0, 1, 2]));
  q.push(ms("hard", "Implicit on $x^2+xy+y^2=7$:", ["$2x+(y+xy')+2yy'=0$", "group the $y'$ terms", "$y'=-\\dfrac{2x+y}{x+2y}$", "$y'=-x$"], [0, 1, 2]));
  q.push(ms("hard", "Higher-order of $x^4$:", ["$4x^3$", "$12x^2$", "$24x$", "stops being $0$"], [0, 1, 2]));
  q.push(ms("hard", "$x^2-y^2=1$:", ["$2x-2yy'=0$", "$y'=\\dfrac xy$", "differentiate implicitly", "$y'=-\\dfrac xy$"], [0, 1, 2]));
  q.push(tf("hard", "For $xy=4$, $\\dfrac{dy}{dx}=-\\dfrac yx$.", true));
  q.push(tf("hard", "For $x^2-y^2=1$, $\\dfrac{dy}{dx}=\\dfrac xy$.", true));
  q.push(tf("hard", "The third derivative of $x^4$ is $12x^2$.", false));
  q.push(fill("hard", "$\\dfrac{dy}{dx}$ for $xy=4$.", ["-y/x"]));
  q.push(fill("hard", "$\\dfrac{dy}{dx}$ for $x^2+xy+y^2=7$.", ["-(2x+y)/(x+2y)"]));
  q.push(fill("hard", "Third derivative of $x^4$.", ["24x"]));
  q.push(num("hard", "$f''(x)$ for $f(x)=x^4-2x^2$ at $x=1$.", 8, 0));
  q.push(num("hard", "Third derivative of $x^4$ at $x=1$.", 24, 0));
  q.push(num("hard", "$\\dfrac{dy}{dx}$ of $xy=4$ at $(2,2)$.", -1, 0));
  q.push(order("hard", "Order the steps to find $\\dfrac{dy}{dx}$ for $x^2+y^2=25$.", ["Differentiate both sides w.r.t. $x$", "$2x+2y\\dfrac{dy}{dx}=0$", "Isolate $\\dfrac{dy}{dx}$", "$\\dfrac{dy}{dx}=-\\dfrac xy$"]));
  q.push(match("hard", "Match each to its $\\tfrac{dy}{dx}$.", ["$x^2+y^2=25$", "$xy=4$", "$x^2-y^2=1$"], ["$-\\tfrac xy$", "$-\\tfrac yx$", "$\\tfrac xy$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "2.1", gen: g21 },
  { code: "2.2", gen: g22 },
  { code: "2.3", gen: g23 },
  { code: "2.4", gen: g24 },
];
