// MCV4U Unit 3 — Derivatives of Transcendental Functions: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 3.1 Derivatives of Sinusoidal Functions ──────────────────
function g31() {
  const q = [];
  q.push(mc("easy", "$\\dfrac{d}{dx}\\sin x=$", ["$\\cos x$", "$-\\cos x$", "$-\\sin x$", "$\\sin x$"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}\\cos x=$", ["$-\\sin x$", "$\\sin x$", "$\\cos x$", "$-\\cos x$"], 0));
  q.push(mc("easy", "These rules require angles in:", ["radians", "degrees", "either", "gradians"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}(3\\sin x)=$", ["$3\\cos x$", "$3\\sin x$", "$\\cos x$", "$-3\\sin x$"], 0));
  q.push(mc("easy", "The slope of $y=\\sin x$ at $x=0$ is:", ["1", "0", "−1", "$\\pi$"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}\\sin(3x)=$", ["$3\\cos(3x)$", "$\\cos(3x)$", "$3\\sin(3x)$", "$\\cos x$"], 0));
  q.push(ms("easy", "The trig rules:", ["$\\dfrac{d}{dx}\\sin x=\\cos x$", "$\\dfrac{d}{dx}\\cos x=-\\sin x$", "need radians", "$\\dfrac{d}{dx}\\sin x=-\\cos x$"], [0, 1, 2]));
  q.push(ms("easy", "With the chain rule:", ["$\\dfrac{d}{dx}\\sin(g)=\\cos(g)g'$", "multiply by the inner derivative", "e.g. $\\sin(3x)\\to3\\cos(3x)$", "ignore the inside"], [0, 1, 2]));
  q.push(ms("easy", "Graphically:", ["$\\cos x$ is the slope of $\\sin x$", "$\\sin$ peaks where $\\cos=0$", "$\\cos$ is max where $\\sin$ is steepest", "they are unrelated"], [0, 1, 2]));
  q.push(ms("easy", "Cosine's derivative:", ["$-\\sin x$", "carries a minus", "easy to forget the sign", "$+\\sin x$"], [0, 1, 2]));
  q.push(tf("easy", "$\\dfrac{d}{dx}\\sin x=\\cos x$.", true));
  q.push(tf("easy", "$\\dfrac{d}{dx}\\cos x=\\sin x$.", false));
  q.push(tf("easy", "These derivative rules need radians.", true));
  q.push(fill("easy", "$\\dfrac{d}{dx}\\sin x$.", ["cos x", "cosx"]));
  q.push(fill("easy", "$\\dfrac{d}{dx}\\cos x$.", ["-sin x", "-sinx"]));
  q.push(fill("easy", "$\\dfrac{d}{dx}\\sin(3x)$.", ["3cos(3x)", "3cos 3x"]));
  q.push(num("easy", "Slope of $y=\\sin x$ at $x=0$.", 1, 0));
  q.push(num("easy", "Slope of $y=\\cos x$ at $x=0$ (it's $-\\sin 0$).", 0, 0));
  q.push(num("easy", "Coefficient in $\\dfrac{d}{dx}\\sin(5x)=k\\cos(5x)$.", 5, 0));
  q.push(match("easy", "Match each to its derivative.", ["$\\sin x$", "$\\cos x$", "$\\sin(3x)$"], ["$\\cos x$", "$-\\sin x$", "$3\\cos(3x)$"], [0, 1, 2]));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\cos(2x)=$", ["$-2\\sin(2x)$", "$2\\sin(2x)$", "$-\\sin(2x)$", "$-2\\cos(2x)$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}(x\\sin x)=$", ["$\\sin x+x\\cos x$", "$\\cos x$", "$x\\cos x$", "$\\sin x-x\\cos x$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\sin^2 x=$", ["$2\\sin x\\cos x$", "$2\\sin x$", "$\\cos^2 x$", "$2\\cos x$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\sin(x^2)=$", ["$2x\\cos(x^2)$", "$\\cos(x^2)$", "$2x\\sin(x^2)$", "$\\cos(2x)$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}(x^2\\cos x)=$", ["$2x\\cos x-x^2\\sin x$", "$2x\\sin x$", "$-2x\\sin x$", "$2x\\cos x+x^2\\sin x$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\sin(5x)=$", ["$5\\cos(5x)$", "$\\cos(5x)$", "$5\\sin(5x)$", "$-5\\cos(5x)$"], 0));
  q.push(ms("medium", "$x\\sin x$:", ["product rule", "$(1)\\sin x+x\\cos x$", "$=\\sin x+x\\cos x$", "$=x\\cos x$"], [0, 1, 2]));
  q.push(ms("medium", "$\\sin^2 x$:", ["$(\\sin x)^2$", "chain rule $2\\sin x\\cos x$", "$=\\sin 2x$", "$=2\\cos x$"], [0, 1, 2]));
  q.push(ms("medium", "$\\cos(2x)$:", ["chain rule", "$-\\sin(2x)\\cdot2$", "$=-2\\sin(2x)$", "$=2\\sin(2x)$"], [0, 1, 2]));
  q.push(ms("medium", "$\\sin(x^2)$:", ["chain rule", "$\\cos(x^2)\\cdot2x$", "$=2x\\cos(x^2)$", "$=\\cos(2x)$"], [0, 1, 2]));
  q.push(tf("medium", "$\\dfrac{d}{dx}\\cos(2x)=-2\\sin(2x)$.", true));
  q.push(tf("medium", "$\\dfrac{d}{dx}(x\\sin x)=\\sin x+x\\cos x$.", true));
  q.push(tf("medium", "$\\dfrac{d}{dx}\\sin^2 x=2\\cos x$.", false));
  q.push(fill("medium", "$\\dfrac{d}{dx}\\cos(2x)$.", ["-2sin(2x)", "-2sin 2x"]));
  q.push(fill("medium", "$\\dfrac{d}{dx}(x\\sin x)$.", ["sin x+x cos x", "sinx+xcosx"]));
  q.push(fill("medium", "$\\dfrac{d}{dx}\\sin(x^2)$.", ["2x cos(x^2)", "2xcos(x^2)"]));
  q.push(num("medium", "Coefficient in $\\dfrac{d}{dx}\\cos(4x)=k\\sin(4x)$ (signed).", -4, 0));
  q.push(num("medium", "$\\dfrac{d}{dx}(x\\sin x)$ at $x=0$.", 0, 0));
  q.push(num("medium", "Slope of $y=\\sin(2x)$ at $x=0$ (it's $2\\cos(2x)$).", 2, 0));
  q.push(match("medium", "Match each to its derivative.", ["$\\cos(2x)$", "$x\\sin x$", "$\\sin^2 x$"], ["$-2\\sin(2x)$", "$\\sin x+x\\cos x$", "$\\sin 2x$"], [0, 1, 2]));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\dfrac{\\sin x}{x}=$", ["$\\dfrac{x\\cos x-\\sin x}{x^2}$", "$\\dfrac{\\cos x}{1}$", "$\\dfrac{x\\cos x+\\sin x}{x^2}$", "$\\cos x$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\sin(\\cos x)=$", ["$-\\sin x\\cos(\\cos x)$", "$\\cos(\\cos x)$", "$\\cos x\\cos(\\cos x)$", "$-\\cos(\\cos x)$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\cos^3 x=$", ["$-3\\cos^2 x\\sin x$", "$3\\cos^2 x$", "$-3\\sin^2 x$", "$3\\cos^2 x\\sin x$"], 0));
  q.push(mc("hard", "The slope of $y=\\cos x$ at $x=\\tfrac{\\pi}{2}$:", ["−1", "0", "1", "$-\\tfrac{\\pi}{2}$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}(e^x\\sin x)=$", ["$e^x(\\sin x+\\cos x)$", "$e^x\\cos x$", "$e^x\\sin x$", "$e^x(\\cos x-\\sin x)$"], 0));
  q.push(ms("hard", "$\\dfrac{\\sin x}{x}$:", ["quotient rule", "$\\dfrac{x\\cos x-\\sin x}{x^2}$", "top derivative $\\cos x$", "$=\\cos x$"], [0, 1, 2]));
  q.push(ms("hard", "$\\sin(\\cos x)$:", ["chain rule", "outer $\\cos(\\cos x)$", "inner $-\\sin x$", "$=\\cos(\\cos x)$"], [0, 1, 2]));
  q.push(ms("hard", "$\\cos^3 x$:", ["$(\\cos x)^3$", "$3\\cos^2 x\\cdot(-\\sin x)$", "$=-3\\cos^2 x\\sin x$", "$=3\\cos^2 x$"], [0, 1, 2]));
  q.push(ms("hard", "$e^x\\sin x$:", ["product rule", "$e^x\\sin x+e^x\\cos x$", "$=e^x(\\sin x+\\cos x)$", "$=e^x\\cos x$"], [0, 1, 2]));
  q.push(tf("hard", "$\\dfrac{d}{dx}\\dfrac{\\sin x}{x}=\\dfrac{x\\cos x-\\sin x}{x^2}$.", true));
  q.push(tf("hard", "$\\dfrac{d}{dx}\\cos^3 x=-3\\cos^2 x\\sin x$.", true));
  q.push(tf("hard", "The slope of $\\cos x$ at $x=\\tfrac{\\pi}{2}$ is $1$.", false));
  q.push(fill("hard", "$\\dfrac{d}{dx}\\dfrac{\\sin x}{x}$.", ["(x cos x - sin x)/x^2"]));
  q.push(fill("hard", "$\\dfrac{d}{dx}(e^x\\sin x)$.", ["e^x(sin x+cos x)"]));
  q.push(fill("hard", "$\\dfrac{d}{dx}\\cos^3 x$.", ["-3cos^2 x sin x"]));
  q.push(num("hard", "Slope of $y=\\cos x$ at $x=\\tfrac{\\pi}{2}$.", -1, 0));
  q.push(num("hard", "Slope of $y=\\sin x$ at $x=\\tfrac{\\pi}{2}$ (it's $\\cos\\tfrac{\\pi}{2}$).", 0, 0));
  q.push(num("hard", "$\\dfrac{d}{dx}(e^x\\sin x)$ at $x=0$ (it's $e^x(\\sin x+\\cos x)$).", 1, 0));
  q.push(order("hard", "Order the steps to differentiate $\\dfrac{\\sin x}{x}$.", ["Quotient rule", "$\\dfrac{(\\cos x)(x)-(\\sin x)(1)}{x^2}$", "$=\\dfrac{x\\cos x-\\sin x}{x^2}$", "Done"]));
  q.push(match("hard", "Match each to its derivative.", ["$\\cos^3 x$", "$e^x\\sin x$", "$\\sin(\\cos x)$"], ["$-3\\cos^2 x\\sin x$", "$e^x(\\sin x+\\cos x)$", "$-\\sin x\\cos(\\cos x)$"], [0, 1, 2]));
  return q;
}

// ── 3.2 Derivatives of Exponential Functions ─────────────────
function g32() {
  const q = [];
  q.push(mc("easy", "$\\dfrac{d}{dx}e^x=$", ["$e^x$", "$xe^{x-1}$", "$e^{x-1}$", "$1$"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}b^x=$", ["$b^x\\ln b$", "$b^x$", "$xb^{x-1}$", "$b\\ln x$"], 0));
  q.push(mc("easy", "$e^x$ is special because it is:", ["its own derivative", "a polynomial", "negative", "constant"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}(4e^x)=$", ["$4e^x$", "$e^x$", "$4xe^{x}$", "$4$"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}e^{3x}=$", ["$3e^{3x}$", "$e^{3x}$", "$3e^x$", "$e^{3}$"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}2^x=$", ["$2^x\\ln 2$", "$2^x$", "$x2^{x-1}$", "$2\\ln x$"], 0));
  q.push(ms("easy", "Exponential rules:", ["$\\dfrac{d}{dx}e^x=e^x$", "$\\dfrac{d}{dx}b^x=b^x\\ln b$", "$\\dfrac{d}{dx}e^{g}=e^{g}g'$", "$\\dfrac{d}{dx}e^x=xe^{x-1}$"], [0, 1, 2]));
  q.push(ms("easy", "Why $e$ is special:", ["its own derivative", "growth rate = current value", "slope = height", "it is a polynomial"], [0, 1, 2]));
  q.push(ms("easy", "Chain with exponentials:", ["$e^{g}\\cdot g'$", "exponential carries along", "times the inner derivative", "drop the exponential"], [0, 1, 2]));
  q.push(ms("easy", "Other bases:", ["$b^x\\ln b$", "extra factor $\\ln b$", "$\\ln 2$ for base 2", "no $\\ln$ factor"], [0, 1, 2]));
  q.push(tf("easy", "$\\dfrac{d}{dx}e^x=e^x$.", true));
  q.push(tf("easy", "$\\dfrac{d}{dx}2^x=2^x$.", false));
  q.push(tf("easy", "$\\dfrac{d}{dx}b^x=b^x\\ln b$.", true));
  q.push(fill("easy", "$\\dfrac{d}{dx}e^x$.", ["e^x"]));
  q.push(fill("easy", "$\\dfrac{d}{dx}e^{3x}$.", ["3e^{3x}", "3e^3x"]));
  q.push(fill("easy", "$\\dfrac{d}{dx}2^x$.", ["2^x ln 2", "2^x ln2"]));
  q.push(num("easy", "Slope of $y=e^x$ at $x=0$.", 1, 0));
  q.push(num("easy", "Coefficient in $\\dfrac{d}{dx}e^{3x}=k e^{3x}$.", 3, 0));
  q.push(num("easy", "Coefficient in $\\dfrac{d}{dx}e^{5x}=k e^{5x}$.", 5, 0));
  q.push(match("easy", "Match each to its derivative.", ["$e^x$", "$e^{3x}$", "$2^x$"], ["$e^x$", "$3e^{3x}$", "$2^x\\ln 2$"], [0, 1, 2]));
  q.push(mc("medium", "$\\dfrac{d}{dx}(x e^x)=$", ["$e^x(1+x)$", "$e^x$", "$x e^x$", "$e^x(x-1)$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}e^{x^2}=$", ["$2x e^{x^2}$", "$e^{x^2}$", "$2x e^{2x}$", "$x^2 e^{x^2}$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}e^{-x}=$", ["$-e^{-x}$", "$e^{-x}$", "$-e^{x}$", "$xe^{-x}$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}3^x=$", ["$3^x\\ln 3$", "$3^x$", "$x3^{x-1}$", "$3\\ln 3$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}(x^2 e^x)=$", ["$e^x(x^2+2x)$", "$2x e^x$", "$x^2 e^x$", "$e^x(x^2-2x)$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}e^{x^3+1}=$", ["$3x^2 e^{x^3+1}$", "$e^{x^3+1}$", "$3x^2 e^{x^2}$", "$(x^3+1)e^{x^3}$"], 0));
  q.push(ms("medium", "$x e^x$:", ["product rule", "$e^x+x e^x$", "$=e^x(1+x)$", "$=x e^x$"], [0, 1, 2]));
  q.push(ms("medium", "$e^{x^2}$:", ["chain rule", "$e^{x^2}\\cdot2x$", "$=2x e^{x^2}$", "$=e^{2x}$"], [0, 1, 2]));
  q.push(ms("medium", "$e^{-x}$:", ["chain rule", "inner derivative $-1$", "$=-e^{-x}$", "$=e^{-x}$"], [0, 1, 2]));
  q.push(ms("medium", "$x^2 e^x$:", ["product rule", "$2x e^x+x^2 e^x$", "$=e^x(x^2+2x)$", "$=2x e^x$"], [0, 1, 2]));
  q.push(tf("medium", "$\\dfrac{d}{dx}(x e^x)=e^x(1+x)$.", true));
  q.push(tf("medium", "$\\dfrac{d}{dx}e^{x^2}=2x e^{x^2}$.", true));
  q.push(tf("medium", "$\\dfrac{d}{dx}e^{-x}=e^{-x}$.", false));
  q.push(fill("medium", "$\\dfrac{d}{dx}(x e^x)$.", ["e^x(1+x)", "e^x+xe^x"]));
  q.push(fill("medium", "$\\dfrac{d}{dx}e^{x^2}$.", ["2x e^{x^2}", "2xe^{x^2}"]));
  q.push(fill("medium", "$\\dfrac{d}{dx}e^{-x}$.", ["-e^{-x}", "-e^-x"]));
  q.push(num("medium", "$\\dfrac{d}{dx}(x e^x)$ at $x=0$.", 1, 0));
  q.push(num("medium", "$\\dfrac{d}{dx}e^{x^2}$ at $x=0$.", 0, 0));
  q.push(num("medium", "Coefficient in $\\dfrac{d}{dx}e^{-3x}=k e^{-3x}$ (signed).", -3, 0));
  q.push(match("medium", "Match each to its derivative.", ["$x e^x$", "$e^{x^2}$", "$e^{-x}$"], ["$e^x(1+x)$", "$2x e^{x^2}$", "$-e^{-x}$"], [0, 1, 2]));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\dfrac{e^x}{x}=$", ["$\\dfrac{e^x(x-1)}{x^2}$", "$\\dfrac{e^x}{x^2}$", "$\\dfrac{e^x(x+1)}{x^2}$", "$e^x$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}(x e^{2x})=$", ["$e^{2x}(1+2x)$", "$2e^{2x}$", "$e^{2x}$", "$2x e^{2x}$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}e^{\\sin x}=$", ["$\\cos x\\,e^{\\sin x}$", "$e^{\\sin x}$", "$\\cos x$", "$\\sin x\\,e^{\\sin x}$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}(e^x\\cos x)=$", ["$e^x(\\cos x-\\sin x)$", "$e^x\\cos x$", "$-e^x\\sin x$", "$e^x(\\cos x+\\sin x)$"], 0));
  q.push(mc("hard", "The tangent to $y=e^x$ at $x=0$ is:", ["$y=x+1$", "$y=x$", "$y=e x$", "$y=1$"], 0));
  q.push(ms("hard", "$\\dfrac{e^x}{x}$:", ["quotient rule", "$\\dfrac{e^x\\cdot x-e^x}{x^2}$", "$=\\dfrac{e^x(x-1)}{x^2}$", "$=\\dfrac{e^x}{x^2}$"], [0, 1, 2]));
  q.push(ms("hard", "$x e^{2x}$:", ["product + chain", "$e^{2x}+x\\cdot2e^{2x}$", "$=e^{2x}(1+2x)$", "$=2x e^{2x}$"], [0, 1, 2]));
  q.push(ms("hard", "$e^{\\sin x}$:", ["chain rule", "outer $e^{\\sin x}$", "inner $\\cos x$", "$=\\cos x\\,e^{\\sin x}$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Tangent to $e^x$ at 0:", ["$f'(0)=e^0=1$", "point $(0,1)$", "$y=x+1$", "slope $0$"], [0, 1, 2]));
  q.push(tf("hard", "$\\dfrac{d}{dx}\\dfrac{e^x}{x}=\\dfrac{e^x(x-1)}{x^2}$.", true));
  q.push(tf("hard", "$\\dfrac{d}{dx}e^{\\sin x}=\\cos x\\,e^{\\sin x}$.", true));
  q.push(tf("hard", "The tangent to $y=e^x$ at $x=0$ is $y=x$.", false));
  q.push(fill("hard", "$\\dfrac{d}{dx}\\dfrac{e^x}{x}$.", ["e^x(x-1)/x^2"]));
  q.push(fill("hard", "$\\dfrac{d}{dx}e^{\\sin x}$.", ["cos x e^{sin x}", "cosx e^{sinx}"]));
  q.push(fill("hard", "Tangent to $y=e^x$ at $x=0$.", ["y=x+1"]));
  q.push(num("hard", "Slope of $y=e^x$ at $x=0$.", 1, 0));
  q.push(num("hard", "$\\dfrac{d}{dx}(x e^{2x})$ at $x=0$ (it's $e^{2x}(1+2x)$).", 1, 0));
  q.push(num("hard", "$\\dfrac{d}{dx}(e^x\\cos x)$ at $x=0$ (it's $e^x(\\cos x-\\sin x)$).", 1, 0));
  q.push(order("hard", "Order the steps to differentiate $\\dfrac{e^x}{x}$.", ["Quotient rule", "$\\dfrac{e^x\\cdot x-e^x\\cdot1}{x^2}$", "Factor $e^x$", "$\\dfrac{e^x(x-1)}{x^2}$"]));
  q.push(match("hard", "Match each to its derivative.", ["$\\tfrac{e^x}{x}$", "$x e^{2x}$", "$e^{\\sin x}$"], ["$\\tfrac{e^x(x-1)}{x^2}$", "$e^{2x}(1+2x)$", "$\\cos x\\,e^{\\sin x}$"], [0, 1, 2]));
  return q;
}

// ── 3.3 Derivatives of Logarithmic Functions ─────────────────
function g33() {
  const q = [];
  q.push(mc("easy", "$\\dfrac{d}{dx}\\ln x=$", ["$\\dfrac1x$", "$\\ln x$", "$x$", "$-\\dfrac1x$"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}\\ln(g(x))=$", ["$\\dfrac{g'(x)}{g(x)}$", "$\\dfrac1{g(x)}$", "$g'(x)$", "$\\ln g'(x)$"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}\\log_b x=$", ["$\\dfrac1{x\\ln b}$", "$\\dfrac1x$", "$\\dfrac{\\ln b}{x}$", "$\\dfrac1{\\ln b}$"], 0));
  q.push(mc("easy", "The slope of $y=\\ln x$ at $x=2$ is:", ["$\\tfrac12$", "$2$", "$\\ln 2$", "$1$"], 0));
  q.push(mc("easy", "$\\dfrac{d}{dx}\\ln(3x)=$", ["$\\dfrac1x$", "$\\dfrac3x$", "$\\dfrac1{3x}$", "$3$"], 0));
  q.push(mc("easy", "The derivative of $\\ln x$ is the curve:", ["$\\dfrac1x$", "$x$", "$e^x$", "$\\ln x$"], 0));
  q.push(ms("easy", "Log rules:", ["$\\dfrac{d}{dx}\\ln x=\\dfrac1x$", "$\\dfrac{d}{dx}\\ln(g)=\\dfrac{g'}{g}$", "$\\dfrac{d}{dx}\\log_b x=\\dfrac1{x\\ln b}$", "$\\dfrac{d}{dx}\\ln x=x$"], [0, 1, 2]));
  q.push(ms("easy", "The chain form:", ["$\\dfrac{g'(x)}{g(x)}$", "inner derivative over the inside", "e.g. $\\ln(x^2+1)\\to\\dfrac{2x}{x^2+1}$", "ignore the inside"], [0, 1, 2]));
  q.push(ms("easy", "Graph of $\\ln x$ vs $1/x$:", ["$1/x$ is the slope of $\\ln x$", "slope large near 0", "slope shrinks as $x$ grows", "they are equal"], [0, 1, 2]));
  q.push(ms("easy", "Other-base logs:", ["$\\dfrac1{x\\ln b}$", "extra $\\ln b$ in the denominator", "$\\ln 2$ for base 2", "no $\\ln b$"], [0, 1, 2]));
  q.push(tf("easy", "$\\dfrac{d}{dx}\\ln x=\\dfrac1x$.", true));
  q.push(tf("easy", "$\\dfrac{d}{dx}\\ln x=\\ln x$.", false));
  q.push(tf("easy", "$\\dfrac{d}{dx}\\log_b x=\\dfrac1{x\\ln b}$.", true));
  q.push(fill("easy", "$\\dfrac{d}{dx}\\ln x$.", ["1/x"]));
  q.push(fill("easy", "$\\dfrac{d}{dx}\\ln(3x)$.", ["1/x"]));
  q.push(fill("easy", "$\\dfrac{d}{dx}\\log_2 x$.", ["1/(x ln 2)", "1/(x ln2)"]));
  q.push(num("easy", "Slope of $y=\\ln x$ at $x=2$ (decimal).", 0.5, 0.01));
  q.push(num("easy", "Slope of $y=\\ln x$ at $x=1$.", 1, 0));
  q.push(num("easy", "Slope of $y=\\ln x$ at $x=4$ (decimal).", 0.25, 0.01));
  q.push(match("easy", "Match each to its derivative.", ["$\\ln x$", "$\\ln(x^2+1)$", "$\\log_2 x$"], ["$\\tfrac1x$", "$\\tfrac{2x}{x^2+1}$", "$\\tfrac1{x\\ln 2}$"], [0, 1, 2]));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\ln(x^2+1)=$", ["$\\dfrac{2x}{x^2+1}$", "$\\dfrac1{x^2+1}$", "$2x$", "$\\dfrac{2x}{x^2}$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}(x\\ln x)=$", ["$\\ln x+1$", "$\\ln x$", "$1$", "$\\dfrac1x$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\ln(x^3)=$", ["$\\dfrac3x$", "$\\dfrac1{x^3}$", "$3x^2$", "$\\dfrac{3}{x^3}$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\ln(\\cos x)=$", ["$-\\tan x$", "$\\tan x$", "$\\dfrac1{\\cos x}$", "$-\\sin x$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}(x^2\\ln x)=$", ["$2x\\ln x+x$", "$2x\\ln x$", "$x$", "$2x+x$"], 0));
  q.push(mc("medium", "$\\dfrac{d}{dx}\\ln(5x-1)=$", ["$\\dfrac5{5x-1}$", "$\\dfrac1{5x-1}$", "$5$", "$\\dfrac{5x}{5x-1}$"], 0));
  q.push(ms("medium", "$\\ln(x^2+1)$:", ["chain $\\dfrac{g'}{g}$", "$g'=2x$", "$=\\dfrac{2x}{x^2+1}$", "$=\\dfrac1{x^2+1}$"], [0, 1, 2]));
  q.push(ms("medium", "$x\\ln x$:", ["product rule", "$\\ln x+x\\cdot\\dfrac1x$", "$=\\ln x+1$", "$=\\ln x$"], [0, 1, 2]));
  q.push(ms("medium", "$\\ln(\\cos x)$:", ["chain $\\dfrac{g'}{g}$", "$\\dfrac{-\\sin x}{\\cos x}$", "$=-\\tan x$", "$=\\tan x$"], [0, 1, 2]));
  q.push(ms("medium", "$\\ln(x^3)$:", ["$=3\\ln x$ first", "or chain $\\dfrac{3x^2}{x^3}$", "$=\\dfrac3x$", "$=\\dfrac1{x^3}$"], [0, 1, 2]));
  q.push(tf("medium", "$\\dfrac{d}{dx}(x\\ln x)=\\ln x+1$.", true));
  q.push(tf("medium", "$\\dfrac{d}{dx}\\ln(\\cos x)=-\\tan x$.", true));
  q.push(tf("medium", "$\\dfrac{d}{dx}\\ln(x^2+1)=\\dfrac1{x^2+1}$.", false));
  q.push(fill("medium", "$\\dfrac{d}{dx}\\ln(x^2+1)$.", ["2x/(x^2+1)"]));
  q.push(fill("medium", "$\\dfrac{d}{dx}(x\\ln x)$.", ["ln x+1", "lnx+1"]));
  q.push(fill("medium", "$\\dfrac{d}{dx}\\ln(\\cos x)$.", ["-tan x", "-tanx"]));
  q.push(num("medium", "$\\dfrac{d}{dx}(x\\ln x)$ at $x=1$ (it's $\\ln x+1$).", 1, 0));
  q.push(num("medium", "$\\dfrac{d}{dx}\\ln(x^3)$ at $x=1$ (it's $3/x$).", 3, 0));
  q.push(num("medium", "$\\dfrac{d}{dx}\\ln(x^2+1)$ at $x=0$.", 0, 0));
  q.push(match("medium", "Match each to its derivative.", ["$x\\ln x$", "$\\ln(\\cos x)$", "$\\ln(x^3)$"], ["$\\ln x+1$", "$-\\tan x$", "$\\tfrac3x$"], [0, 1, 2]));
  q.push(mc("hard", "By logarithmic differentiation, $\\dfrac{d}{dx}x^x=$", ["$x^x(\\ln x+1)$", "$x\\cdot x^{x-1}$", "$x^x\\ln x$", "$x^x$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\dfrac{\\ln x}{x}=$", ["$\\dfrac{1-\\ln x}{x^2}$", "$\\dfrac{\\ln x}{x^2}$", "$\\dfrac1{x^2}$", "$\\dfrac{1+\\ln x}{x^2}$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}x^{2x}=$", ["$x^{2x}(2\\ln x+2)$", "$2x\\cdot x^{2x-1}$", "$x^{2x}\\ln x$", "$2x^{2x}$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}(\\ln x)^2=$", ["$\\dfrac{2\\ln x}{x}$", "$\\dfrac2x$", "$2\\ln x$", "$\\dfrac{2}{x^2}$"], 0));
  q.push(mc("hard", "$\\dfrac{d}{dx}\\ln(x e^x)=$", ["$\\dfrac1x+1$", "$\\dfrac1x$", "$1+e^x$", "$\\dfrac1{xe^x}$"], 0));
  q.push(ms("hard", "Logarithmic differentiation of $x^x$:", ["$\\ln y=x\\ln x$", "$\\dfrac{y'}{y}=\\ln x+1$", "$y'=x^x(\\ln x+1)$", "$y'=x\\cdot x^{x-1}$"], [0, 1, 2]));
  q.push(ms("hard", "$\\dfrac{\\ln x}{x}$:", ["quotient rule", "$\\dfrac{\\frac1x\\cdot x-\\ln x}{x^2}$", "$=\\dfrac{1-\\ln x}{x^2}$", "$=\\dfrac{\\ln x}{x^2}$"], [0, 1, 2]));
  q.push(ms("hard", "$(\\ln x)^2$:", ["chain rule", "$2\\ln x\\cdot\\dfrac1x$", "$=\\dfrac{2\\ln x}{x}$", "$=\\dfrac2x$"], [0, 1, 2]));
  q.push(ms("hard", "$\\ln(x e^x)$:", ["$=\\ln x+x$ first", "derivative $\\dfrac1x+1$", "log laws simplify it", "needs the quotient rule"], [0, 1, 2]));
  q.push(tf("hard", "$\\dfrac{d}{dx}x^x=x^x(\\ln x+1)$.", true));
  q.push(tf("hard", "$\\dfrac{d}{dx}\\dfrac{\\ln x}{x}=\\dfrac{1-\\ln x}{x^2}$.", true));
  q.push(tf("hard", "$\\dfrac{d}{dx}x^x=x\\cdot x^{x-1}$.", false));
  q.push(fill("hard", "$\\dfrac{d}{dx}x^x$.", ["x^x(ln x+1)", "x^x(lnx+1)"]));
  q.push(fill("hard", "$\\dfrac{d}{dx}\\dfrac{\\ln x}{x}$.", ["(1-ln x)/x^2"]));
  q.push(fill("hard", "$\\dfrac{d}{dx}(\\ln x)^2$.", ["2 ln x/x", "(2lnx)/x"]));
  q.push(num("hard", "$\\dfrac{d}{dx}x^x$ at $x=1$ (it's $x^x(\\ln x+1)$).", 1, 0));
  q.push(num("hard", "$\\dfrac{d}{dx}\\dfrac{\\ln x}{x}$ at $x=1$ (it's $(1-\\ln x)/x^2$).", 1, 0));
  q.push(num("hard", "$\\dfrac{d}{dx}\\ln(x e^x)$ at $x=1$ (it's $1/x+1$).", 2, 0));
  q.push(order("hard", "Order the steps to differentiate $y=x^x$.", ["Take $\\ln$: $\\ln y=x\\ln x$", "Differentiate: $\\dfrac{y'}{y}=\\ln x+1$", "Multiply by $y$", "$y'=x^x(\\ln x+1)$"]));
  q.push(match("hard", "Match each to its derivative.", ["$x^x$", "$\\tfrac{\\ln x}{x}$", "$(\\ln x)^2$"], ["$x^x(\\ln x+1)$", "$\\tfrac{1-\\ln x}{x^2}$", "$\\tfrac{2\\ln x}{x}$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "3.1", gen: g31 },
  { code: "3.2", gen: g32 },
  { code: "3.3", gen: g33 },
];
