// MCV4U Unit 4 — Curve Sketching: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 4.1 Increasing/Decreasing & the First Derivative Test ────
function g41() {
  const q = [];
  q.push(mc("easy", "$f$ is increasing where:", ["$f'>0$", "$f'<0$", "$f'=0$", "$f''>0$"], 0));
  q.push(mc("easy", "$f$ is decreasing where:", ["$f'<0$", "$f'>0$", "$f''<0$", "$f=0$"], 0));
  q.push(mc("easy", "A critical number is where:", ["$f'=0$ or undefined", "$f=0$", "$f''=0$", "$x=0$"], 0));
  q.push(mc("easy", "If $f'$ goes $+\\to-$, the point is a:", ["local max", "local min", "inflection", "asymptote"], 0));
  q.push(mc("easy", "If $f'$ goes $-\\to+$, the point is a:", ["local min", "local max", "inflection", "hole"], 0));
  q.push(mc("easy", "Critical numbers of $f(x)=x^2-4x$ (from $f'=2x-4$):", ["$x=2$", "$x=4$", "$x=0$", "$x=-2$"], 0));
  q.push(ms("easy", "Using $f'$:", ["$f'>0$ → increasing", "$f'<0$ → decreasing", "$f'=0$ → critical number", "$f'=0$ → always a max"], [0, 1, 2]));
  q.push(ms("easy", "First derivative test:", ["$+\\to-$ max", "$-\\to+$ min", "no change → neither", "$+\\to-$ min"], [0, 1, 2]));
  q.push(ms("easy", "Critical numbers:", ["where $f'=0$", "or $f'$ undefined", "candidates for extrema", "where $f=0$"], [0, 1, 2]));
  q.push(ms("easy", "Not every critical number is an extremum:", ["$x^3$ at $0$", "$f'$ doesn't change sign", "it's an inflection", "always a max"], [0, 1, 2]));
  q.push(tf("easy", "$f$ increases where $f'>0$.", true));
  q.push(tf("easy", "Every critical number is a local extremum.", false));
  q.push(tf("easy", "$f'$ changing $+\\to-$ gives a local max.", true));
  q.push(fill("easy", "$f$ is increasing where $f'$ is ___.", ["positive", ">0"]));
  q.push(fill("easy", "Critical number of $f(x)=x^2-4x$.", ["2", "x=2"]));
  q.push(fill("easy", "$f'$ goes $-\\to+$: the point is a local ___.", ["min", "minimum"]));
  q.push(num("easy", "Critical number of $f(x)=x^2-6x$.", 3, 0));
  q.push(num("easy", "Number of critical numbers of $f(x)=x^3-3x$.", 2, 0));
  q.push(num("easy", "Critical number of $f(x)=x^2+8x$.", -4, 0));
  q.push(match("easy", "Match each $f'$ behaviour to the result.", ["$+\\to-$", "$-\\to+$", "no change"], ["local max", "local min", "neither"], [0, 1, 2]));
  q.push(mc("medium", "Where is $f(x)=x^2-4x$ decreasing?", ["$x<2$", "$x>2$", "all $x$", "$x<0$"], 0));
  q.push(mc("medium", "Critical numbers of $f(x)=x^3-3x$:", ["$\\pm1$", "$\\pm3$", "$0$", "$\\pm\\sqrt3$"], 0));
  q.push(mc("medium", "Local max of $f(x)=x^3-3x$ is at:", ["$x=-1$", "$x=1$", "$x=0$", "$x=3$"], 0));
  q.push(mc("medium", "$f(x)=x^3$ at its critical number is:", ["neither", "a max", "a min", "an asymptote"], 0));
  q.push(mc("medium", "Critical numbers of $f(x)=x^4-2x^2$:", ["$0,\\pm1$", "$\\pm1$", "$0$", "$\\pm2$"], 0));
  q.push(mc("medium", "Is $f(x)=x^3+x$ ever decreasing?", ["no", "yes", "only $x<0$", "only $x>0$"], 0));
  q.push(ms("medium", "$f(x)=x^3-3x$:", ["$f'=3x^2-3$", "critical $\\pm1$", "max $(-1,2)$, min $(1,-2)$", "max at $1$"], [0, 1, 2]));
  q.push(ms("medium", "$f(x)=x^4-2x^2$:", ["$f'=4x(x-1)(x+1)$", "critical $0,\\pm1$", "min at $\\pm1$, max at $0$", "max at $\\pm1$"], [0, 1, 2]));
  q.push(ms("medium", "Always increasing:", ["$f'>0$ for all $x$", "$x^3+x$ qualifies", "$f'=3x^2+1$", "has a max"], [0, 1, 2]));
  q.push(ms("medium", "$f(x)=x^2-4x$:", ["$f'=2x-4$", "decreasing $x<2$", "increasing $x>2$", "min at $x=2$"], [0, 1, 2, 3]));
  q.push(tf("medium", "$f(x)=x^3-3x$ has a local max at $x=-1$.", true));
  q.push(tf("medium", "$f(x)=x^3+x$ is never decreasing.", true));
  q.push(tf("medium", "$f(x)=x^3$ has a local min at $x=0$.", false));
  q.push(fill("medium", "Local-max $x$-value of $f(x)=x^3-3x$.", ["-1"]));
  q.push(fill("medium", "Critical numbers of $f(x)=x^4-2x^2$.", ["0, 1, -1", "0,±1"]));
  q.push(fill("medium", "Where $f(x)=x^2-4x$ is increasing.", ["x>2"]));
  q.push(num("medium", "Local-min $x$-value of $f(x)=x^3-3x$.", 1, 0));
  q.push(num("medium", "Number of critical numbers of $f(x)=x^4-2x^2$.", 3, 0));
  q.push(num("medium", "Local-max value of $f(x)=x^3-3x$.", 2, 0));
  q.push(match("medium", "Match each function to its critical numbers.", ["$x^2-4x$", "$x^3-3x$", "$x^4-2x^2$"], ["$2$", "$\\pm1$", "$0,\\pm1$"], [0, 1, 2]));
  q.push(mc("hard", "$f(x)=x^3-6x^2+9x$ has critical numbers:", ["$x=1,3$", "$x=0,3$", "$x=3$", "$x=\\pm3$"], 0));
  q.push(mc("hard", "For that $f$, $x=1$ is a:", ["local max", "local min", "inflection", "neither"], 0));
  q.push(mc("hard", "$f(x)=\\dfrac1x$ has critical numbers:", ["none ($f'$ never 0)", "$x=0$", "$x=1$", "$x=\\pm1$"], 0));
  q.push(mc("hard", "$f(x)=x+\\dfrac1x$ has critical numbers:", ["$x=\\pm1$", "$x=0$", "$x=1$", "none"], 0));
  q.push(mc("hard", "Where is $f(x)=x^3-3x^2$ increasing?", ["$x<0$ or $x>2$", "$0<x<2$", "$x>0$", "all $x$"], 0));
  q.push(ms("hard", "$f(x)=x^3-6x^2+9x$:", ["$f'=3x^2-12x+9$", "$=3(x-1)(x-3)$", "max $(1,4)$, min $(3,0)$", "max $(3,0)$"], [0, 1, 2]));
  q.push(ms("hard", "$f(x)=x+\\tfrac1x$:", ["$f'=1-\\tfrac1{x^2}$", "$=0$ at $x=\\pm1$", "min at $1$, max at $-1$", "min at $-1$"], [0, 1, 2]));
  q.push(ms("hard", "Reading intervals from $f'$:", ["test a point in each interval", "sign gives increase/decrease", "switches mark extrema", "ignore the sign"], [0, 1, 2]));
  q.push(ms("hard", "Critical numbers from undefined $f'$:", ["e.g. $\\sqrt{x}$ at $0$", "or rationals where denom $=0$", "include in the analysis", "only $f'=0$ counts"], [0, 1, 2]));
  q.push(tf("hard", "$f(x)=x^3-6x^2+9x$ has a local max at $x=1$.", true));
  q.push(tf("hard", "$f(x)=x+\\tfrac1x$ has a local min at $x=1$.", true));
  q.push(tf("hard", "$f(x)=\\tfrac1x$ has a critical number at $x=0$.", false));
  q.push(fill("hard", "Critical numbers of $f(x)=x^3-6x^2+9x$.", ["1, 3", "1 and 3"]));
  q.push(fill("hard", "Critical numbers of $f(x)=x+\\tfrac1x$.", ["±1", "1, -1"]));
  q.push(fill("hard", "Where $f(x)=x^3-3x^2$ is increasing.", ["x<0 or x>2"]));
  q.push(num("hard", "Local-max value of $f(x)=x^3-6x^2+9x$ (at $x=1$).", 4, 0));
  q.push(num("hard", "Local-min value of $f(x)=x^3-6x^2+9x$ (at $x=3$).", 0, 0));
  q.push(num("hard", "Local-min value of $f(x)=x+\\tfrac1x$ (at $x=1$).", 2, 0));
  q.push(order("hard", "Order the first-derivative-test steps for $f(x)=x^3-3x$.", ["$f'=3x^2-3$", "Critical numbers $x=\\pm1$", "Sign of $f'$: $+,-,+$", "Max $(-1,2)$, min $(1,-2)$"]));
  q.push(match("hard", "Match each to its classification at the stated point.", ["$x^3-6x^2+9x$ at $1$", "$x^3-6x^2+9x$ at $3$", "$x^3$ at $0$"], ["local max", "local min", "neither"], [0, 1, 2]));
  return q;
}

// ── 4.2 Concavity & the Second Derivative ────────────────────
function g42() {
  const q = [];
  q.push(mc("easy", "$f$ is concave up where:", ["$f''>0$", "$f''<0$", "$f'>0$", "$f=0$"], 0));
  q.push(mc("easy", "$f$ is concave down where:", ["$f''<0$", "$f''>0$", "$f'<0$", "$f=0$"], 0));
  q.push(mc("easy", "An inflection point is where:", ["$f''$ changes sign", "$f'=0$", "$f=0$", "$x=0$"], 0));
  q.push(mc("easy", "Concavity of $f(x)=x^2$:", ["up everywhere", "down everywhere", "switches", "none"], 0));
  q.push(mc("easy", "2nd-derivative test: $f'(c)=0,\\ f''(c)>0$ gives a:", ["local min", "local max", "inflection", "asymptote"], 0));
  q.push(mc("easy", "2nd-derivative test: $f''(c)<0$ gives a:", ["local max", "local min", "inflection", "hole"], 0));
  q.push(ms("easy", "Concavity:", ["$f''>0$ up", "$f''<0$ down", "inflection where it switches", "$f'>0$ up"], [0, 1, 2]));
  q.push(ms("easy", "2nd-derivative test:", ["needs $f'(c)=0$", "$f''(c)>0$ → min", "$f''(c)<0$ → max", "$f''(c)=0$ → max"], [0, 1, 2]));
  q.push(ms("easy", "Inflection points:", ["concavity changes", "$f''$ changes sign", "the curve switches bending", "where $f=0$"], [0, 1, 2]));
  q.push(ms("easy", "$f(x)=x^3$:", ["$f''=6x$", "down for $x<0$", "up for $x>0$", "concave up everywhere"], [0, 1, 2]));
  q.push(tf("easy", "$f''>0$ means concave up.", true));
  q.push(tf("easy", "An inflection point is where $f'=0$.", false));
  q.push(tf("easy", "$f(x)=x^2$ is concave up everywhere.", true));
  q.push(fill("easy", "$f$ is concave up where $f''$ is ___.", ["positive", ">0"]));
  q.push(fill("easy", "Inflection: where $f''$ ___ sign.", ["changes"]));
  q.push(fill("easy", "2nd-derivative test with $f''(c)<0$ gives a local ___.", ["max", "maximum"]));
  q.push(num("easy", "$f''$ for $f(x)=x^2$.", 2, 0));
  q.push(num("easy", "$x$-value of the inflection point of $f(x)=x^3$.", 0, 0));
  q.push(num("easy", "$f''(0)$ for $f(x)=x^3$.", 0, 0));
  q.push(match("easy", "Match each sign of $f''$ to concavity.", ["$f''>0$", "$f''<0$", "$f''$ switches"], ["up", "down", "inflection"], [0, 1, 2]));
  q.push(mc("medium", "Where is $f(x)=x^3$ concave up?", ["$x>0$", "$x<0$", "all $x$", "nowhere"], 0));
  q.push(mc("medium", "Inflection point of $f(x)=x^3-3x^2$:", ["$(1,-2)$", "$(0,0)$", "$(2,-4)$", "$(1,0)$"], 0));
  q.push(mc("medium", "Classify $x=2$ for $f(x)=x^2-4x$ with $f''$:", ["local min", "local max", "inflection", "neither"], 0));
  q.push(mc("medium", "For $f(x)=x^4-2x^2$, $x=0$ is a:", ["local max", "local min", "inflection", "neither"], 0));
  q.push(mc("medium", "For $f(x)=x^4-2x^2$, $x=\\pm1$ are:", ["local minima", "local maxima", "inflections", "neither"], 0));
  q.push(mc("medium", "Inflection point of $f(x)=x^3-6x^2$:", ["$(2,-16)$", "$(0,0)$", "$(4,-32)$", "$(2,0)$"], 0));
  q.push(ms("medium", "$f(x)=x^3-3x^2$:", ["$f''=6x-6$", "inflection at $x=1$", "$f(1)=-2$", "inflection at $x=0$"], [0, 1, 2]));
  q.push(ms("medium", "$f(x)=x^4-2x^2$:", ["$f''=12x^2-4$", "$f''(0)<0$ → max", "$f''(\\pm1)>0$ → min", "$f''(0)>0$"], [0, 1, 2]));
  q.push(ms("medium", "2nd-derivative test on $x^2-4x$:", ["$f'=2x-4=0$ at $2$", "$f''=2>0$", "local min", "local max"], [0, 1, 2]));
  q.push(ms("medium", "Inflection of $x^3-6x^2$:", ["$f''=6x-12$", "$=0$ at $x=2$", "$(2,-16)$", "$(0,0)$"], [0, 1, 2]));
  q.push(tf("medium", "The inflection point of $x^3-3x^2$ is $(1,-2)$.", true));
  q.push(tf("medium", "For $x^4-2x^2$, $x=0$ is a local max.", true));
  q.push(tf("medium", "For $x^2-4x$, the 2nd-derivative test gives a local max at $x=2$.", false));
  q.push(fill("medium", "Inflection point of $f(x)=x^3-3x^2$.", ["(1,-2)"]));
  q.push(fill("medium", "Classification of $x=0$ for $f(x)=x^4-2x^2$.", ["max", "local max"]));
  q.push(fill("medium", "Where $f(x)=x^3$ is concave up.", ["x>0"]));
  q.push(num("medium", "$x$-value of the inflection of $f(x)=x^3-3x^2$.", 1, 0));
  q.push(num("medium", "$x$-value of the inflection of $f(x)=x^3-6x^2$.", 2, 0));
  q.push(num("medium", "$f''(-3)$ for $f(x)=x^2+6x$ (it's $2$).", 2, 0));
  q.push(match("medium", "Match each to its inflection point.", ["$x^3-3x^2$", "$x^3-6x^2$", "$x^3$"], ["$(1,-2)$", "$(2,-16)$", "$(0,0)$"], [0, 1, 2]));
  q.push(mc("hard", "Intervals of concavity of $f(x)=x^3-3x^2+1$:", ["down $x<1$, up $x>1$", "up everywhere", "down everywhere", "up $x<1$, down $x>1$"], 0));
  q.push(mc("hard", "$f(x)=x^4$ at $x=0$ ($f''(0)=0$): the 2nd-derivative test is:", ["inconclusive", "a max", "a min", "an inflection"], 0));
  q.push(mc("hard", "(For $x^4$, the 1st-derivative test shows $x=0$ is a:)", ["local min", "local max", "inflection", "neither"], 0));
  q.push(mc("hard", "Inflection points of $f(x)=x^4-6x^2$ ($f''=12x^2-12$):", ["$x=\\pm1$", "$x=0$", "$x=\\pm\\sqrt6$", "none"], 0));
  q.push(mc("hard", "If $f''(c)=0$ but $f''$ does NOT change sign at $c$:", ["no inflection", "always an inflection", "a max", "a min"], 0));
  q.push(ms("hard", "$x^3-3x^2+1$ concavity:", ["$f''=6x-6$", "$<0$ for $x<1$ (down)", "$>0$ for $x>1$ (up)", "up everywhere"], [0, 1, 2]));
  q.push(ms("hard", "$x^4$ at $0$:", ["$f''(0)=0$ inconclusive", "use the 1st-derivative test", "$f'$ goes $-\\to+$ → min", "it's a max"], [0, 1, 2]));
  q.push(ms("hard", "$x^4-6x^2$ inflection:", ["$f''=12x^2-12$", "$=0$ at $x=\\pm1$", "sign change at each", "no inflection"], [0, 1, 2]));
  q.push(ms("hard", "When $f''(c)=0$:", ["check whether $f''$ changes sign", "sign change → inflection", "no change → no inflection", "always an inflection"], [0, 1, 2]));
  q.push(tf("hard", "$f(x)=x^3-3x^2+1$ is concave up for $x>1$.", true));
  q.push(tf("hard", "For $f(x)=x^4$ at $x=0$ the 2nd-derivative test is inconclusive.", true));
  q.push(tf("hard", "$f''(c)=0$ always means an inflection point.", false));
  q.push(fill("hard", "Concavity of $x^3-3x^2+1$ for $x<1$.", ["down", "concave down"]));
  q.push(fill("hard", "Inflection $x$-values of $f(x)=x^4-6x^2$.", ["±1", "1, -1"]));
  q.push(fill("hard", "The 2nd-derivative test is ___ when $f''(c)=0$.", ["inconclusive"]));
  q.push(num("hard", "$x$-value of the inflection of $f(x)=x^3-3x^2+1$.", 1, 0));
  q.push(num("hard", "Number of inflection points of $f(x)=x^4-6x^2$.", 2, 0));
  q.push(num("hard", "$f''(1)$ for $f(x)=x^4-6x^2$ (it's $12x^2-12$).", 0, 0));
  q.push(order("hard", "Order the steps to find the concavity of $f(x)=x^3-3x^2+1$.", ["$f''=6x-6$", "Set $f''=0$: $x=1$", "Test signs: $-$ then $+$", "Down on $x<1$, up on $x>1$"]));
  q.push(match("hard", "Match each to its 2nd-derivative-test result.", ["$x^2-4x$ at $2$", "$x^4-2x^2$ at $0$", "$x^4$ at $0$"], ["min", "max", "inconclusive"], [0, 1, 2]));
  return q;
}

// ── 4.3 Critical, Inflection & End Behaviour ─────────────────
function g43() {
  const q = [];
  q.push(mc("easy", "From $f'$ you read:", ["increase/decrease & extrema", "concavity", "intercepts", "asymptotes"], 0));
  q.push(mc("easy", "From $f''$ you read:", ["concavity & inflection", "intercepts", "extrema", "the domain"], 0));
  q.push(mc("easy", "A vertical asymptote of $\\dfrac1{x-3}$ is at:", ["$x=3$", "$x=-3$", "$y=3$", "$x=0$"], 0));
  q.push(mc("easy", "If $f'(3)=0$ and $f''(3)>0$, then $x=3$ is a:", ["local min", "local max", "inflection", "asymptote"], 0));
  q.push(mc("easy", "Critical numbers of $f(x)=x^3-3x^2$:", ["$0,2$", "$0,3$", "$1$", "$\\pm1$"], 0));
  q.push(mc("easy", "End behaviour of $f(x)=-x^3+2x$:", ["up–down", "down–up", "up–up", "down–down"], 0));
  q.push(ms("easy", "The feature checklist:", ["domain & intercepts", "asymptotes", "$f'$ and $f''$ info", "ignore end behaviour"], [0, 1, 2]));
  q.push(ms("easy", "$f'$ gives:", ["intervals of increase/decrease", "local extrema", "critical numbers", "concavity"], [0, 1, 2]));
  q.push(ms("easy", "$f''$ gives:", ["concavity", "inflection points", "the bending", "the intercepts"], [0, 1, 2]));
  q.push(ms("easy", "Rational asymptotes guide:", ["the sketch", "VA from the denominator", "HA from the degrees", "the intercepts only"], [0, 1, 2]));
  q.push(tf("easy", "From $f'$ you find the extrema.", true));
  q.push(tf("easy", "From $f''$ you find the intercepts.", false));
  q.push(tf("easy", "$\\dfrac1{x-3}$ has a vertical asymptote at $x=3$.", true));
  q.push(fill("easy", "$f'$ tells you increase/decrease and ___.", ["extrema"]));
  q.push(fill("easy", "$f''$ tells you concavity and ___.", ["inflection", "inflection points"]));
  q.push(fill("easy", "VA of $f(x)=\\dfrac1{x-3}$.", ["x=3"]));
  q.push(num("easy", "Number of critical numbers of $f(x)=x^3-3x^2$.", 2, 0));
  q.push(num("easy", "VA $x$-value of $f(x)=\\dfrac1{x-3}$.", 3, 0));
  q.push(num("easy", "HA $y$-value of $f(x)=\\dfrac1{x-3}$.", 0, 0));
  q.push(match("easy", "Match each tool to what it gives.", ["$f'$", "$f''$", "$f$"], ["extrema", "inflection", "intercepts"], [0, 1, 2]));
  q.push(mc("medium", "If $f'(2)=0$ and $f''(2)=-3$, then $x=2$ is a:", ["local max", "local min", "inflection", "hole"], 0));
  q.push(mc("medium", "Asymptotes of $f(x)=\\dfrac{x}{x-2}$:", ["VA $x=2$, HA $y=1$", "VA $x=0$, HA $y=2$", "VA $x=2$, HA $y=0$", "none"], 0));
  q.push(mc("medium", "Inflection point of $f(x)=x^3-3x^2$:", ["$(1,-2)$", "$(0,0)$", "$(2,-4)$", "$(3,0)$"], 0));
  q.push(mc("medium", "Local extrema of $f(x)=x^3-3x$:", ["max $(-1,2)$, min $(1,-2)$", "max $(1,-2)$", "min $(-1,2)$", "none"], 0));
  q.push(mc("medium", "$f(x)=x^3+1$ has at $x=0$:", ["an inflection (no extremum)", "a local max", "a local min", "an asymptote"], 0));
  q.push(mc("medium", "End behaviour of $f(x)=x^4-1$:", ["up–up", "down–down", "down–up", "up–down"], 0));
  q.push(ms("medium", "$f'(2)=0,\\ f''(2)<0$:", ["critical point", "concave down", "local max", "local min"], [0, 1, 2]));
  q.push(ms("medium", "$\\dfrac{x}{x-2}$:", ["VA $x=2$", "equal degrees", "HA $y=1$", "HA $y=0$"], [0, 1, 2]));
  q.push(ms("medium", "$x^3+1$ at $0$:", ["$f''=6x=0$", "sign change → inflection", "$f'=3x^2\\ge0$ → no extremum", "a local max"], [0, 1, 2]));
  q.push(ms("medium", "Features of $x^3-3x$:", ["max $(-1,2)$", "min $(1,-2)$", "inflection $(0,0)$", "VA at $x=0$"], [0, 1, 2]));
  q.push(tf("medium", "If $f'(2)=0$ and $f''(2)<0$, then $x=2$ is a local max.", true));
  q.push(tf("medium", "$\\dfrac{x}{x-2}$ has HA $y=1$.", true));
  q.push(tf("medium", "$x^3+1$ has a local min at $x=0$.", false));
  q.push(fill("medium", "Classification when $f'(c)=0,\\ f''(c)<0$.", ["local max", "max"]));
  q.push(fill("medium", "HA of $f(x)=\\dfrac{x}{x-2}$.", ["y=1"]));
  q.push(fill("medium", "Inflection point of $f(x)=x^3-3x^2$.", ["(1,-2)"]));
  q.push(num("medium", "Local-max value of $f(x)=x^3-3x$.", 2, 0));
  q.push(num("medium", "VA $x$-value of $f(x)=\\dfrac{x}{x-2}$.", 2, 0));
  q.push(num("medium", "Number of local extrema of $f(x)=x^3-3x$.", 2, 0));
  q.push(match("medium", "Match each to its feature.", ["$x^3-3x$ extrema", "$\\tfrac{x}{x-2}$ HA", "$x^3-3x^2$ inflection"], ["max $(-1,2)$, min $(1,-2)$", "$y=1$", "$(1,-2)$"], [0, 1, 2]));
  q.push(mc("hard", "$f(x)=\\dfrac{x^2}{x^2-1}$ has vertical asymptotes at:", ["$x=\\pm1$", "$x=1$", "$x=0$", "none"], 0));
  q.push(mc("hard", "$f(x)=\\dfrac{x^2}{x^2-1}$ has horizontal asymptote:", ["$y=1$", "$y=0$", "none", "$y=-1$"], 0));
  q.push(mc("hard", "If $f''>0$ on all of $(a,b)$, then on $(a,b)$ the graph is:", ["concave up", "concave down", "linear", "decreasing"], 0));
  q.push(mc("hard", "A function with $f'>0$ and $f''<0$ on an interval is:", ["increasing & concave down", "increasing & concave up", "decreasing & concave down", "constant"], 0));
  q.push(mc("hard", "Critical numbers of $f(x)=\\dfrac{x}{x^2+1}$ ($f'=\\dfrac{1-x^2}{(x^2+1)^2}$):", ["$x=\\pm1$", "$x=0$", "none", "$x=1$"], 0));
  q.push(ms("hard", "$\\dfrac{x^2}{x^2-1}$:", ["VAs at $x=\\pm1$", "equal degrees", "HA $y=1$", "HA $y=0$"], [0, 1, 2]));
  q.push(ms("hard", "Increasing & concave down:", ["$f'>0$", "$f''<0$", "rising but bending down", "a falling curve"], [0, 1, 2]));
  q.push(ms("hard", "$\\dfrac{x}{x^2+1}$:", ["$f'=\\dfrac{1-x^2}{(x^2+1)^2}$", "$=0$ at $x=\\pm1$", "max at $1$, min at $-1$", "no critical numbers"], [0, 1, 2]));
  q.push(ms("hard", "Combining $f'$ and $f''$ signs:", ["four shape types", "↑ up, ↑ down, ↓ up, ↓ down", "describe the bend & slope", "only the slope matters"], [0, 1, 2]));
  q.push(tf("hard", "$\\dfrac{x^2}{x^2-1}$ has vertical asymptotes at $x=\\pm1$.", true));
  q.push(tf("hard", "$f'>0,\\ f''<0$ means increasing and concave down.", true));
  q.push(tf("hard", "$\\dfrac{x}{x^2+1}$ has no critical numbers.", false));
  q.push(fill("hard", "VAs of $f(x)=\\dfrac{x^2}{x^2-1}$.", ["±1", "1, -1"]));
  q.push(fill("hard", "HA of $f(x)=\\dfrac{x^2}{x^2-1}$.", ["y=1"]));
  q.push(fill("hard", "Critical numbers of $f(x)=\\dfrac{x}{x^2+1}$.", ["±1", "1, -1"]));
  q.push(num("hard", "Number of vertical asymptotes of $f(x)=\\dfrac{x^2}{x^2-1}$.", 2, 0));
  q.push(num("hard", "Number of critical numbers of $f(x)=\\dfrac{x}{x^2+1}$.", 2, 0));
  q.push(num("hard", "HA $y$-value of $f(x)=\\dfrac{x^2}{x^2-1}$.", 1, 0));
  q.push(order("hard", "Order the steps to find the features of $f(x)=\\dfrac{x}{x-2}$.", ["Domain: $x\\ne2$", "VA $x=2$", "Equal degrees → HA $y=1$", "Sketch with the asymptotes"]));
  q.push(match("hard", "Match each function to a key feature.", ["$\\tfrac{x^2}{x^2-1}$", "$\\tfrac{x}{x^2+1}$", "$x^3+1$"], ["VAs $x=\\pm1$", "max/min at $\\pm1$", "inflection $(0,1)$"], [0, 1, 2]));
  return q;
}

// ── 4.4 Full Curve Sketching ─────────────────────────────────
function g44() {
  const q = [];
  q.push(mc("easy", "The first step of a full sketch is:", ["domain & intercepts", "the second derivative", "end behaviour", "asymptotes"], 0));
  q.push(mc("easy", "x-intercepts of $f(x)=x^3-3x$:", ["$0,\\pm\\sqrt3$", "$\\pm1$", "$0,3$", "$\\pm3$"], 0));
  q.push(mc("easy", "Local extrema of $f(x)=x^3-3x^2$:", ["max $(0,0)$, min $(2,-4)$", "max $(2,-4)$", "min $(0,0)$", "none"], 0));
  q.push(mc("easy", "Inflection of $f(x)=x^3-3x$:", ["$(0,0)$", "$(1,-2)$", "$(-1,2)$", "$(2,-4)$"], 0));
  q.push(mc("easy", "$f(x)=x^4-2x^2$ is:", ["even", "odd", "neither", "linear"], 0));
  q.push(mc("easy", "If $f'>0$ everywhere, the graph is:", ["always increasing", "always decreasing", "constant", "concave up"], 0));
  q.push(ms("easy", "Full-sketch checklist:", ["domain/symmetry/intercepts", "$f'$ for extrema", "$f''$ for concavity", "guess the shape"], [0, 1, 2]));
  q.push(ms("easy", "Even/odd helps:", ["even → y-axis symmetry", "odd → origin symmetry", "halves the work", "always neither"], [0, 1, 2]));
  q.push(ms("easy", "Finishing a sketch:", ["use end behaviour", "place extrema & inflections", "respect asymptotes", "ignore concavity"], [0, 1, 2]));
  q.push(ms("easy", "$f(x)=x^3-3x$:", ["x-ints $0,\\pm\\sqrt3$", "max $(-1,2)$, min $(1,-2)$", "inflection $(0,0)$", "even function"], [0, 1, 2]));
  q.push(tf("easy", "The first step of a full sketch is domain and intercepts.", true));
  q.push(tf("easy", "$f(x)=x^4-2x^2$ is odd.", false));
  q.push(tf("easy", "If $f'>0$ everywhere, the graph always increases.", true));
  q.push(fill("easy", "x-intercepts of $f(x)=x^3-3x$.", ["0, ±√3", "0, sqrt3, -sqrt3"]));
  q.push(fill("easy", "Inflection point of $f(x)=x^3-3x$.", ["(0,0)"]));
  q.push(fill("easy", "Symmetry type of $f(x)=x^4-2x^2$.", ["even"]));
  q.push(num("easy", "Number of x-intercepts of $f(x)=x^3-3x$.", 3, 0));
  q.push(num("easy", "y-intercept of $f(x)=x^3-3x+2$.", 2, 0));
  q.push(num("easy", "Number of local extrema of $f(x)=x^3-3x^2$.", 2, 0));
  q.push(match("easy", "Match each tool to its job.", ["domain/intercepts", "$f'$", "$f''$"], ["start", "extrema", "concavity"], [0, 1, 2]));
  q.push(mc("medium", "Local extrema of $f(x)=x^4-2x^2$:", ["max $(0,0)$, min $(\\pm1,-1)$", "max $(\\pm1,-1)$", "min $(0,0)$", "none"], 0));
  q.push(mc("medium", "End behaviour of $f(x)=x^4-2x^2$:", ["up–up", "down–down", "down–up", "up–down"], 0));
  q.push(mc("medium", "x-intercepts of $f(x)=x^4-2x^2$:", ["$0,\\pm\\sqrt2$", "$\\pm1$", "$0,2$", "$\\pm2$"], 0));
  q.push(mc("medium", "If $f$ has a max at $-1$ and a min at $1$, $f'$ is:", ["an upward parabola with roots $\\pm1$", "a line", "always positive", "a downward parabola"], 0));
  q.push(mc("medium", "$f(x)=x^3-3x^2$ inflection:", ["$(1,-2)$", "$(0,0)$", "$(2,-4)$", "$(3,0)$"], 0));
  q.push(mc("medium", "If $f'<0$ everywhere, the graph is:", ["always decreasing", "always increasing", "constant", "concave down"], 0));
  q.push(ms("medium", "$f(x)=x^4-2x^2$:", ["even (W-shape)", "max $(0,0)$", "mins $(\\pm1,-1)$", "max $(\\pm1,-1)$"], [0, 1, 2]));
  q.push(ms("medium", "$f$ max at $-1$, min at $1$:", ["$f'=0$ at $\\pm1$", "$f'>0$ outside", "$f'<0$ inside", "$f'<0$ outside"], [0, 1, 2]));
  q.push(ms("medium", "Cubic $x^3-3x^2$:", ["x-ints $0,3$", "max $(0,0)$, min $(2,-4)$", "inflection $(1,-2)$", "even"], [0, 1, 2]));
  q.push(ms("medium", "Using symmetry:", ["even → reflect over y-axis", "odd → rotate about origin", "saves analysis", "always neither"], [0, 1, 2]));
  q.push(tf("medium", "$f(x)=x^4-2x^2$ has minima at $(\\pm1,-1)$.", true));
  q.push(tf("medium", "$f(x)=x^4-2x^2$ has end behaviour up–up.", true));
  q.push(tf("medium", "$f(x)=x^3-3x^2$ has its inflection at $(0,0)$.", false));
  q.push(fill("medium", "x-intercepts of $f(x)=x^4-2x^2$.", ["0, ±√2"]));
  q.push(fill("medium", "Local extrema of $f(x)=x^4-2x^2$.", ["max (0,0), min (±1,-1)"]));
  q.push(fill("medium", "End behaviour of $f(x)=x^4-2x^2$.", ["up-up", "up–up"]));
  q.push(num("medium", "Number of x-intercepts of $f(x)=x^4-2x^2$.", 3, 0));
  q.push(num("medium", "Number of local minima of $f(x)=x^4-2x^2$.", 2, 0));
  q.push(num("medium", "Min value of $f(x)=x^4-2x^2$.", -1, 0));
  q.push(match("medium", "Match each function to its shape.", ["$x^3-3x$", "$x^4-2x^2$", "$x^2$"], ["S-curve, down–up", "W, up–up", "U, up–up"], [0, 1, 2]));
  q.push(mc("hard", "Full analysis of $f(x)=x^3-3x^2$: the local min is at:", ["$(2,-4)$", "$(0,0)$", "$(1,-2)$", "$(3,0)$"], 0));
  q.push(mc("hard", "For $f(x)=\\dfrac{x^2}{x-1}$, the vertical asymptote is:", ["$x=1$", "$x=0$", "$x=-1$", "none"], 0));
  q.push(mc("hard", "A function increasing on $(-\\infty,1)$, decreasing on $(1,\\infty)$, concave down throughout has:", ["a max at $1$", "a min at $1$", "an inflection at $1$", "an asymptote"], 0));
  q.push(mc("hard", "x-intercepts of $f(x)=x^3-x$:", ["$0,\\pm1$", "$\\pm1$", "$0$", "$\\pm\\sqrt2$"], 0));
  q.push(mc("hard", "$f(x)=x^3-3x^2$ is increasing on:", ["$x<0$ or $x>2$", "$0<x<2$", "all $x$", "$x>1$"], 0));
  q.push(ms("hard", "Full sketch of $x^3-3x^2$:", ["x-ints $0,3$", "max $(0,0)$, min $(2,-4)$", "inflection $(1,-2)$", "max $(2,-4)$"], [0, 1, 2]));
  q.push(ms("hard", "$\\dfrac{x^2}{x-1}$ features:", ["VA $x=1$", "oblique asymptote (deg top > bottom)", "no horizontal asymptote", "HA $y=0$"], [0, 1, 2]));
  q.push(ms("hard", "Reading combined signs:", ["increasing + concave down", "rises while bending over", "→ a local max ahead", "→ a local min"], [0, 1, 2]));
  q.push(ms("hard", "$x^3-x$:", ["odd function", "x-ints $0,\\pm1$", "origin symmetry", "even function"], [0, 1, 2]));
  q.push(tf("hard", "$f(x)=x^3-3x^2$ has its local min at $(2,-4)$.", true));
  q.push(tf("hard", "$f(x)=\\dfrac{x^2}{x-1}$ has a vertical asymptote at $x=1$.", true));
  q.push(tf("hard", "$f(x)=x^3-3x^2$ is increasing on $0<x<2$.", false));
  q.push(fill("hard", "Local min of $f(x)=x^3-3x^2$.", ["(2,-4)"]));
  q.push(fill("hard", "VA of $f(x)=\\dfrac{x^2}{x-1}$.", ["x=1"]));
  q.push(fill("hard", "x-intercepts of $f(x)=x^3-x$.", ["0, ±1"]));
  q.push(num("hard", "Local-min value of $f(x)=x^3-3x^2$.", -4, 0));
  q.push(num("hard", "Number of x-intercepts of $f(x)=x^3-x$.", 3, 0));
  q.push(num("hard", "y-intercept of $f(x)=x^3-3x^2$.", 0, 0));
  q.push(order("hard", "Order a full sketch of $f(x)=x^3-3x^2$.", ["Intercepts: $0,3$", "$f'=3x^2-6x$: max $(0,0)$, min $(2,-4)$", "$f''=6x-6$: inflection $(1,-2)$", "Ends down–up; draw"]));
  q.push(match("hard", "Match each to its full-sketch fact.", ["$x^3-3x^2$ min", "$x^3-3x^2$ inflection", "$x^3-3x^2$ x-ints"], ["$(2,-4)$", "$(1,-2)$", "$0,3$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "4.1", gen: g41 },
  { code: "4.2", gen: g42 },
  { code: "4.3", gen: g43 },
  { code: "4.4", gen: g44 },
];
