// MCV4U Unit 5 — Applications of Derivatives: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 5.1 Optimization ─────────────────────────────────────────
function g51() {
  const q = [];
  q.push(mc("easy", "The first step in optimization is:", ["write the quantity to optimize", "differentiate twice", "guess", "draw axes"], 0));
  q.push(mc("easy", "To find candidates you solve:", ["$Q'=0$", "$Q=0$", "$Q''=0$", "$Q'=1$"], 0));
  q.push(mc("easy", "The most area for a fixed perimeter is a:", ["square", "long rectangle", "circle", "triangle"], 0));
  q.push(mc("easy", "Two numbers sum to 12; max product is at:", ["6 and 6", "1 and 11", "0 and 12", "5 and 7"], 0));
  q.push(mc("easy", "After $Q'=0$, to confirm a max you can use:", ["$Q''<0$", "$Q''>0$", "$Q=0$", "$Q'=1$"], 0));
  q.push(mc("easy", "Optimization reduces $Q$ to how many variables?", ["one", "two", "three", "zero"], 0));
  q.push(ms("easy", "The recipe:", ["write $Q$", "reduce to one variable", "solve $Q'=0$ and verify", "skip the constraint"], [0, 1, 2]));
  q.push(ms("easy", "Verifying the optimum:", ["second derivative test", "sign of $Q'$", "check endpoints", "ignore it"], [0, 1, 2]));
  q.push(ms("easy", "Using the constraint:", ["solve for one variable", "substitute into $Q$", "get one-variable $Q$", "leave two variables"], [0, 1, 2]));
  q.push(ms("easy", "Domain matters because:", ["lengths are positive", "endpoints can be optima", "limits the variable", "it never matters"], [0, 1, 2]));
  q.push(tf("easy", "A square maximizes area for a fixed perimeter.", true));
  q.push(tf("easy", "You optimize by setting $Q=0$.", false));
  q.push(tf("easy", "$Q''<0$ at a critical point confirms a maximum.", true));
  q.push(fill("easy", "To find candidates, set $Q'$ equal to ___.", ["0", "zero"]));
  q.push(fill("easy", "Two numbers summing to 12 with max product: ___ and ___.", ["6 and 6", "6, 6"]));
  q.push(fill("easy", "Shape with the most area for fixed perimeter.", ["square"]));
  q.push(num("easy", "Max product of two positive numbers summing to 10.", 25, 0));
  q.push(num("easy", "Side of the max-area square with 40 m of fence.", 10, 0));
  q.push(num("easy", "Max product of two positive numbers summing to 8.", 16, 0));
  q.push(match("easy", "Match each step to its order.", ["write $Q$", "one variable", "solve $Q'=0$"], ["1st", "2nd", "3rd"], [0, 1, 2]));
  q.push(mc("medium", "A pen uses 40 m of fence; the max area is:", ["100 m²", "200 m²", "80 m²", "400 m²"], 0));
  q.push(mc("medium", "3-sided pen, 20 m of fence; max area is:", ["50 m²", "100 m²", "25 m²", "40 m²"], 0));
  q.push(mc("medium", "For $x>0$, $f(x)=x+\\dfrac{16}{x}$ has minimum value:", ["8", "16", "4", "2"], 0));
  q.push(mc("medium", "Open box from a $12\\times12$ sheet: the best cut is $x=$", ["2", "3", "6", "1"], 0));
  q.push(mc("medium", "$P(x)=-2x^2+40x-100$ is maximized at $x=$", ["10", "20", "5", "40"], 0));
  q.push(mc("medium", "Max area of a rectangle with 60 m of fence:", ["225 m²", "200 m²", "100 m²", "400 m²"], 0));
  q.push(ms("medium", "Fixed-perimeter pen (40 m):", ["$A=x(20-x)$", "$A'=20-2x=0$", "$x=10$, area 100", "$x=20$"], [0, 1, 2]));
  q.push(ms("medium", "$f(x)=x+\\tfrac{16}{x}$:", ["$f'=1-\\tfrac{16}{x^2}$", "$x=4$", "$f''>0$ (min)", "min value 8"], [0, 1, 2, 3]));
  q.push(ms("medium", "Open-box volume:", ["$V=x(12-2x)^2$", "$V'=(12-2x)(12-6x)$", "$x=2$ (valid)", "$x=6$"], [0, 1, 2]));
  q.push(ms("medium", "Max profit:", ["$P'=0$", "$-4x+40=0$", "$x=10$, $P=100$", "$x=40$"], [0, 1, 2]));
  q.push(tf("medium", "A 40 m fence pen has maximum area 100 m².", true));
  q.push(tf("medium", "$f(x)=x+\\tfrac{16}{x}$ has minimum value 8 for $x>0$.", true));
  q.push(tf("medium", "The open box from a $12\\times12$ sheet is best at $x=6$.", false));
  q.push(fill("medium", "Max area with 40 m of fence.", ["100"]));
  q.push(fill("medium", "Minimum of $f(x)=x+\\tfrac{16}{x}$.", ["8"]));
  q.push(fill("medium", "Best corner cut for an open box from $12\\times12$.", ["2", "x=2"]));
  q.push(num("medium", "Max area (m²) with 40 m of fence.", 100, 0));
  q.push(num("medium", "Minimum value of $f(x)=x+\\tfrac{16}{x}$, $x>0$.", 8, 0));
  q.push(num("medium", "Output maximizing $P(x)=-2x^2+40x-100$.", 10, 0));
  q.push(match("medium", "Match each to its optimum.", ["40 m pen area", "$x+\\tfrac{16}{x}$ min", "$-2x^2+40x-100$ max output"], ["100", "8", "10"], [0, 1, 2]));
  q.push(mc("hard", "For $x>0$, $f(x)=x+\\dfrac{c}{x}$ has its minimum at $x=$", ["$\\sqrt{c}$", "$c$", "$\\tfrac c2$", "$c^2$"], 0));
  q.push(mc("hard", "Open box from $6\\times6$ sheet: best cut $x=$", ["1", "2", "3", "0.5"], 0));
  q.push(mc("hard", "Two adjacent identical pens, 240 m of fence (3 widths): max total area:", ["2400 m²", "3600 m²", "1200 m²", "4800 m²"], 0));
  q.push(mc("hard", "A box with square base and fixed volume has least surface area when it is:", ["a cube", "very tall", "very flat", "a sphere"], 0));
  q.push(mc("hard", "Minimum value of $f(x)=x+\\dfrac{9}{x}$ for $x>0$:", ["6", "3", "9", "18"], 0));
  q.push(ms("hard", "$x+\\tfrac cx$ minimum:", ["$f'=1-\\tfrac c{x^2}$", "$x=\\sqrt c$", "min value $2\\sqrt c$", "$x=c$"], [0, 1, 2]));
  q.push(ms("hard", "Two adjacent pens:", ["$3x+2L=240$", "$A=x\\cdot\\tfrac{240-3x}{2}$", "$x=40$, area 2400", "$x=60$"], [0, 1, 2]));
  q.push(ms("hard", "$6\\times6$ open box:", ["$V=x(6-2x)^2$", "$V'=(6-2x)(6-6x)$", "$x=1$ (valid)", "$x=3$"], [0, 1, 2]));
  q.push(ms("hard", "General optimization care:", ["check the domain", "test endpoints too", "verify max vs min", "skip verification"], [0, 1, 2]));
  q.push(tf("hard", "For $f(x)=x+\\tfrac cx$, the minimum is at $x=\\sqrt c$.", true));
  q.push(tf("hard", "Two adjacent pens with 240 m of fence give 2400 m².", true));
  q.push(tf("hard", "The $6\\times6$ open box is best at $x=3$.", false));
  q.push(fill("hard", "$x$ minimizing $f(x)=x+\\tfrac cx$.", ["sqrt(c)", "√c"]));
  q.push(fill("hard", "Best corner cut for a $6\\times6$ open box.", ["1", "x=1"]));
  q.push(fill("hard", "Max total area of two adjacent pens with 240 m fence.", ["2400"]));
  q.push(num("hard", "Minimum of $f(x)=x+\\tfrac{9}{x}$ ($x>0$).", 6, 0));
  q.push(num("hard", "$x$ minimizing $x+\\tfrac{36}{x}$.", 6, 0));
  q.push(num("hard", "Best corner cut for a $6\\times6$ open box.", 1, 0));
  q.push(order("hard", "Order the optimization of a 40 m pen's area.", ["Let sides $x$ and $20-x$", "$A=x(20-x)$", "$A'=20-2x=0\\Rightarrow x=10$", "Area $=100$ m²"]));
  q.push(match("hard", "Match each to its optimum value.", ["$x+\\tfrac9x$ min", "$6\\times6$ box cut", "240 m two-pen area"], ["6", "1", "2400"], [0, 1, 2]));
  return q;
}

// ── 5.2 Related Rates ────────────────────────────────────────
function g52() {
  const q = [];
  q.push(mc("easy", "Related rates link quantities that change with:", ["time", "space", "mass", "colour"], 0));
  q.push(mc("easy", "The key first move is to:", ["relate the quantities with an equation", "guess the answer", "integrate", "draw a graph"], 0));
  q.push(mc("easy", "Differentiating w.r.t. $t$ uses the:", ["chain rule", "power rule only", "quotient rule only", "no rule"], 0));
  q.push(mc("easy", "For $A=\\pi r^2$, $\\dfrac{dA}{dt}=$", ["$2\\pi r\\dfrac{dr}{dt}$", "$2\\pi r$", "$\\pi r^2\\dfrac{dr}{dt}$", "$2\\pi\\dfrac{dr}{dt}$"], 0));
  q.push(mc("easy", "A negative rate means the quantity is:", ["decreasing", "increasing", "constant", "zero"], 0));
  q.push(mc("easy", "You substitute the instant's numbers:", ["after differentiating", "before differentiating", "never", "instead of differentiating"], 0));
  q.push(ms("easy", "Related-rates recipe:", ["relate quantities", "differentiate w.r.t. $t$", "substitute the instant", "substitute first"], [0, 1, 2]));
  q.push(ms("easy", "Chain rule in $t$:", ["every variable gets $\\tfrac{d}{dt}$", "$\\tfrac{d}{dt}r^2=2r\\tfrac{dr}{dt}$", "rates multiply in", "ignore inner rates"], [0, 1, 2]));
  q.push(ms("easy", "Reading the answer:", ["units are per second", "negative = decreasing", "positive = increasing", "sign is meaningless"], [0, 1, 2]));
  q.push(ms("easy", "Setting up:", ["identify known rates", "identify the unknown rate", "find a relating equation", "skip the equation"], [0, 1, 2]));
  q.push(tf("easy", "You differentiate before substituting numbers.", true));
  q.push(tf("easy", "$\\dfrac{d}{dt}r^2=2r$.", false));
  q.push(tf("easy", "A negative rate means a decreasing quantity.", true));
  q.push(fill("easy", "$\\dfrac{d}{dt}(\\pi r^2)=$", ["2pi r dr/dt", "2πr dr/dt"]));
  q.push(fill("easy", "Differentiating in $t$ uses the ___ rule.", ["chain"]));
  q.push(fill("easy", "A negative rate means the quantity is ___.", ["decreasing"]));
  q.push(num("easy", "For a circle with $\\tfrac{dr}{dt}=2$, $\\tfrac{dA}{dt}$ at $r=5$ as a multiple of $\\pi$.", 20, 0));
  q.push(num("easy", "For a square with $\\tfrac{ds}{dt}=3$, $\\tfrac{dA}{dt}$ at $s=10$.", 60, 0));
  q.push(num("easy", "For a circle with $\\tfrac{dr}{dt}=1$, $\\tfrac{dA}{dt}$ at $r=4$ (multiple of $\\pi$).", 8, 0));
  q.push(match("easy", "Match each quantity to its rate equation.", ["$A=\\pi r^2$", "$A=s^2$", "$V=\\tfrac43\\pi r^3$"], ["$2\\pi r\\,r'$", "$2s\\,s'$", "$4\\pi r^2\\,r'$"], [0, 1, 2]));
  q.push(mc("medium", "$\\tfrac{dr}{dt}=2$ cm/s; $\\tfrac{dA}{dt}$ at $r=5$:", ["$20\\pi$", "$10\\pi$", "$25\\pi$", "$4\\pi$"], 0));
  q.push(mc("medium", "A 13 m ladder, base out at 2 m/s; the top's rate at base $=5$:", ["$-\\tfrac56$ m/s", "$-\\tfrac65$ m/s", "$-2$ m/s", "$\\tfrac56$ m/s"], 0));
  q.push(mc("medium", "Balloon $\\tfrac{dV}{dt}=100$ cm³/s; $\\tfrac{dr}{dt}$ at $r=5$:", ["$\\tfrac1\\pi$", "$\\pi$", "$\\tfrac1{4\\pi}$", "$\\tfrac{100}\\pi$"], 0));
  q.push(mc("medium", "Square, side at 3 cm/s; $\\tfrac{dA}{dt}$ at $s=10$:", ["60", "30", "90", "20"], 0));
  q.push(mc("medium", "Two cars N 60, E 80 km/h; distance rate after 1 h:", ["100 km/h", "140 km/h", "80 km/h", "70 km/h"], 0));
  q.push(mc("medium", "For the ladder, $\\tfrac{dy}{dt}=-\\tfrac xy\\tfrac{dx}{dt}$ comes from:", ["differentiating $x^2+y^2=169$", "the product rule", "the quotient rule", "guessing"], 0));
  q.push(ms("medium", "Expanding circle:", ["$A=\\pi r^2$", "$\\tfrac{dA}{dt}=2\\pi r\\tfrac{dr}{dt}$", "$=2\\pi(5)(2)=20\\pi$", "$=10\\pi$"], [0, 1, 2]));
  q.push(ms("medium", "Sliding ladder:", ["$x^2+y^2=169$", "$y=12$ when $x=5$", "$y'=-\\tfrac{5(2)}{12}=-\\tfrac56$", "$y'=+\\tfrac56$"], [0, 1, 2]));
  q.push(ms("medium", "Balloon:", ["$V=\\tfrac43\\pi r^3$", "$\\tfrac{dV}{dt}=4\\pi r^2\\tfrac{dr}{dt}$", "$\\tfrac{dr}{dt}=\\tfrac{100}{4\\pi(25)}=\\tfrac1\\pi$", "$=\\pi$"], [0, 1, 2]));
  q.push(ms("medium", "Two cars:", ["$D^2=a^2+b^2$", "$2DD'=2aa'+2bb'$", "$D'=\\tfrac{60^2+80^2}{100}=100$", "$D'=140$"], [0, 1, 2]));
  q.push(tf("medium", "Expanding circle: $\\tfrac{dA}{dt}=20\\pi$ when $r=5,\\ \\tfrac{dr}{dt}=2$.", true));
  q.push(tf("medium", "The ladder top descends at $\\tfrac56$ m/s.", true));
  q.push(tf("medium", "The two cars separate at 140 km/h after 1 h.", false));
  q.push(fill("medium", "$\\tfrac{dA}{dt}$ for the expanding circle ($r=5$, $\\tfrac{dr}{dt}=2$), as a multiple of $\\pi$.", ["20"]));
  q.push(fill("medium", "The ladder top's rate (signed) at base 5 m.", ["-5/6"]));
  q.push(fill("medium", "$\\tfrac{dr}{dt}$ for the balloon ($\\tfrac{dV}{dt}=100$, $r=5$).", ["1/pi", "1/π"]));
  q.push(num("medium", "Two cars (N 60, E 80): separation rate after 1 h (km/h).", 100, 0));
  q.push(num("medium", "$\\tfrac{dA}{dt}$ (mult. of $\\pi$) for circle $r=5$, $\\tfrac{dr}{dt}=2$.", 20, 0));
  q.push(num("medium", "$\\tfrac{dA}{dt}$ for square $s=10$, $\\tfrac{ds}{dt}=3$.", 60, 0));
  q.push(match("medium", "Match each scenario to its answer.", ["circle $r=5$, $r'=2$", "ladder top at base 5", "balloon $V'=100$, $r=5$"], ["$20\\pi$", "$-\\tfrac56$", "$\\tfrac1\\pi$"], [0, 1, 2]));
  q.push(mc("hard", "A 25 m ladder, base out 3 m/s; top's rate at base 7 m:", ["$-\\tfrac78$ m/s", "$-\\tfrac87$ m/s", "$-3$ m/s", "$-\\tfrac38$ m/s"], 0));
  q.push(mc("hard", "Cylinder ($r=3$) fills at $\\tfrac{dV}{dt}=18\\pi$; $\\tfrac{dh}{dt}=$", ["2 cm/s", "1 cm/s", "$\\tfrac1\\pi$", "6 cm/s"], 0));
  q.push(mc("hard", "Conical pile: $V=\\tfrac13\\pi r^2 h$ with $h=r$; this becomes:", ["$V=\\tfrac13\\pi r^3$", "$V=\\tfrac43\\pi r^3$", "$V=\\pi r^2$", "$V=\\tfrac12\\pi r^2$"], 0));
  q.push(mc("hard", "If $\\tfrac{dA}{dt}=20\\pi$ for a circle at $r=5$, then $\\tfrac{dr}{dt}=$", ["2", "4", "1", "$\\tfrac1\\pi$"], 0));
  q.push(mc("hard", "Two cars N 30, E 40 km/h; separation rate after 1 h:", ["50 km/h", "70 km/h", "10 km/h", "35 km/h"], 0));
  q.push(ms("hard", "25 m ladder:", ["$x^2+y^2=625$", "$y=24$ at $x=7$", "$y'=-\\tfrac{7(3)}{24}=-\\tfrac78$", "$y'=-3$"], [0, 1, 2]));
  q.push(ms("hard", "Cylinder height rate:", ["$V=\\pi r^2 h$ with $r=3$", "$\\tfrac{dV}{dt}=9\\pi\\tfrac{dh}{dt}$", "$18\\pi=9\\pi\\tfrac{dh}{dt}\\Rightarrow2$", "$=1$"], [0, 1, 2]));
  q.push(ms("hard", "Reverse problem (find $r'$):", ["$\\tfrac{dA}{dt}=2\\pi r\\tfrac{dr}{dt}$", "solve for $\\tfrac{dr}{dt}$", "$20\\pi=2\\pi(5)r'\\Rightarrow r'=2$", "$r'=4$"], [0, 1, 2]));
  q.push(ms("hard", "Substituting a constraint ($h=r$):", ["reduces variables", "before differentiating if always true", "simplifies $V$", "never allowed"], [0, 1, 2]));
  q.push(tf("hard", "A 25 m ladder's top descends at $\\tfrac78$ m/s when the base is 7 m out.", true));
  q.push(tf("hard", "A cylinder ($r=3$) with $\\tfrac{dV}{dt}=18\\pi$ has $\\tfrac{dh}{dt}=2$ cm/s.", true));
  q.push(tf("hard", "Two cars at 30 and 40 km/h separate at 70 km/h after 1 h.", false));
  q.push(fill("hard", "Top's rate (signed) of a 25 m ladder at base 7 m.", ["-7/8"]));
  q.push(fill("hard", "$\\tfrac{dh}{dt}$ for the cylinder ($r=3$, $V'=18\\pi$).", ["2"]));
  q.push(fill("hard", "Separation rate of two cars (N 30, E 40) after 1 h.", ["50"]));
  q.push(num("hard", "$\\tfrac{dh}{dt}$ (cm/s) for cylinder $r=3$, $\\tfrac{dV}{dt}=18\\pi$.", 2, 0));
  q.push(num("hard", "Separation rate (km/h) of cars N 30, E 40 after 1 h.", 50, 0));
  q.push(num("hard", "Top speed (magnitude) of a 25 m ladder at base 7 m, base rate 3 (as a fraction $7/8$ → decimal).", 0.875, 0.01));
  q.push(order("hard", "Order the steps for the sliding-ladder problem.", ["Write $x^2+y^2=169$", "Differentiate: $2xx'+2yy'=0$", "Substitute $x=5,y=12,x'=2$", "Solve $y'=-\\tfrac56$"]));
  q.push(match("hard", "Match each to its rate.", ["25 m ladder top", "cylinder height", "cars N30/E40"], ["$-\\tfrac78$", "$2$", "$50$"], [0, 1, 2]));
  return q;
}

// ── 5.3 Kinematics: Velocity & Acceleration ──────────────────
function g53() {
  const q = [];
  q.push(mc("easy", "Velocity is:", ["$v=s'$", "$v=s''$", "$v=s$", "$v=\\int s$"], 0));
  q.push(mc("easy", "Acceleration is:", ["$a=v'=s''$", "$a=s'$", "$a=v$", "$a=s$"], 0));
  q.push(mc("easy", "The object is at rest when:", ["$v=0$", "$a=0$", "$s=0$", "$v>0$"], 0));
  q.push(mc("easy", "Speed is:", ["$|v|$", "$v^2$", "$a$", "$s$"], 0));
  q.push(mc("easy", "For $s(t)=t^2-4t$, $v(t)=$", ["$2t-4$", "$2t$", "$t^2$", "$2$"], 0));
  q.push(mc("easy", "Direction of motion is given by the sign of:", ["$v$", "$a$", "$s$", "$t$"], 0));
  q.push(ms("easy", "Kinematics chain:", ["$v=s'$", "$a=v'$", "$a=s''$", "$a=s'$"], [0, 1, 2]));
  q.push(ms("easy", "At rest:", ["$v=0$", "velocity is zero", "a turning point of $s$", "$a=0$"], [0, 1, 2]));
  q.push(ms("easy", "Speed vs velocity:", ["speed $=|v|$", "velocity has direction", "speed is non-negative", "they are identical"], [0, 1, 2]));
  q.push(ms("easy", "Speeding up / slowing down:", ["same sign $v,a$ → speeding up", "opposite signs → slowing down", "compare the signs", "depends only on $v$"], [0, 1, 2]));
  q.push(tf("easy", "$v=s'$ and $a=s''$.", true));
  q.push(tf("easy", "The object is at rest when $a=0$.", false));
  q.push(tf("easy", "Speed is $|v|$.", true));
  q.push(fill("easy", "For $s(t)=t^2-4t$, $v(t)=$", ["2t-4"]));
  q.push(fill("easy", "The object is at rest when $v=$ ___.", ["0"]));
  q.push(fill("easy", "Acceleration is the derivative of ___.", ["velocity", "v"]));
  q.push(num("easy", "For $s(t)=t^2-4t$, the time at rest.", 2, 0));
  q.push(num("easy", "For $s(t)=t^2-4t$, $a(t)$ (constant).", 2, 0));
  q.push(num("easy", "For $s(t)=t^2-6t$, the time at rest.", 3, 0));
  q.push(match("easy", "Match each to its meaning.", ["$s'$", "$s''$", "$|v|$"], ["velocity", "acceleration", "speed"], [0, 1, 2]));
  q.push(mc("medium", "For $s(t)=t^3-6t^2+9t$, at rest at:", ["$t=1,3$", "$t=0,3$", "$t=3$", "$t=1$"], 0));
  q.push(mc("medium", "For $s(t)=t^3-3t^2$, $a(t)=$", ["$6t-6$", "$3t^2-6t$", "$6t$", "$3t-6$"], 0));
  q.push(mc("medium", "A projectile $h(t)=-5t^2+20t$ is highest at:", ["$t=2$", "$t=4$", "$t=1$", "$t=20$"], 0));
  q.push(mc("medium", "If $v>0$ and $a<0$, the object is:", ["slowing down", "speeding up", "at rest", "accelerating"], 0));
  q.push(mc("medium", "For $s(t)=t^3-6t^2+9t$, at $t=0$ it moves:", ["right ($v=9>0$)", "left", "is at rest", "backward"], 0));
  q.push(mc("medium", "For $s(t)=t^3-6t^2+9t$, at $t=4$ it is:", ["speeding up", "slowing down", "at rest", "stopped"], 0));
  q.push(ms("medium", "$s=t^3-6t^2+9t$:", ["$v=3t^2-12t+9$", "$=3(t-1)(t-3)$", "rest at $t=1,3$", "rest at $t=2$"], [0, 1, 2]));
  q.push(ms("medium", "At $t=0$ for that $s$:", ["$v(0)=9>0$ (right)", "$a=6t-12$", "$a(0)=-12<0$", "speeding up"], [0, 1, 2]));
  q.push(ms("medium", "At $t=4$ for that $s$:", ["$v(4)=9>0$", "$a(4)=12>0$", "same sign → speeding up", "opposite signs"], [0, 1, 2]));
  q.push(ms("medium", "Projectile max height:", ["$v=0$", "$-10t+20=0$", "$t=2$", "$t=4$"], [0, 1, 2]));
  q.push(tf("medium", "For $s(t)=t^3-6t^2+9t$, the object is at rest at $t=1$ and $t=3$.", true));
  q.push(tf("medium", "A projectile $h(t)=-5t^2+20t$ peaks at $t=2$.", true));
  q.push(tf("medium", "If $v>0$ and $a<0$, the object is speeding up.", false));
  q.push(fill("medium", "Rest times of $s(t)=t^3-6t^2+9t$.", ["1, 3", "t=1, t=3"]));
  q.push(fill("medium", "$a(t)$ for $s(t)=t^3-3t^2$.", ["6t-6"]));
  q.push(fill("medium", "Peak time of $h(t)=-5t^2+20t$.", ["2"]));
  q.push(num("medium", "Larger rest time of $s(t)=t^3-6t^2+9t$.", 3, 0));
  q.push(num("medium", "Peak time of $h(t)=-5t^2+30t$.", 3, 0));
  q.push(num("medium", "$v(0)$ for $s(t)=t^3-6t^2+9t$.", 9, 0));
  q.push(match("medium", "Match each to its value (for $s=t^3-6t^2+9t$).", ["rest times", "$v(0)$", "$a(0)$"], ["$1,3$", "$9$", "$-12$"], [0, 1, 2]));
  q.push(mc("hard", "For $s(t)=t^3-6t^2+9t$, total distance vs displacement on $[0,3]$ differ because:", ["it changes direction", "it speeds up", "it's linear", "they're equal"], 0));
  q.push(mc("hard", "For $s(t)=t^3-6t^2+9t$, the object moves left on:", ["$1<t<3$", "$t<1$", "$t>3$", "never"], 0));
  q.push(mc("hard", "Maximum height of $h(t)=-5t^2+20t$:", ["20 m", "40 m", "10 m", "15 m"], 0));
  q.push(mc("hard", "When $a>0$ throughout, the velocity graph is:", ["increasing", "decreasing", "constant", "zero"], 0));
  q.push(mc("hard", "For $s(t)=t^3-6t^2+9t$, at $t=2$: $v(2)=-3$, $a(2)=0$, so it is:", ["momentarily neither (a=0)", "speeding up", "slowing down", "at rest"], 0));
  q.push(ms("hard", "Direction changes:", ["where $v$ changes sign", "at rest points", "$t=1$ and $t=3$ here", "never"], [0, 1, 2]));
  q.push(ms("hard", "Max height:", ["set $v=0$", "$t=2$", "$h(2)=-20+40=20$", "$h=40$"], [0, 1, 2]));
  q.push(ms("hard", "Moving left:", ["$v<0$", "$3(t-1)(t-3)<0$", "on $1<t<3$", "on $t>3$"], [0, 1, 2]));
  q.push(ms("hard", "Speeding up regions:", ["$v$ and $a$ same sign", "check each interval", "near $t=4$ here both $+$", "always"], [0, 1, 2]));
  q.push(tf("hard", "For $s(t)=t^3-6t^2+9t$, the object moves left on $1<t<3$.", true));
  q.push(tf("hard", "The max height of $h(t)=-5t^2+20t$ is 20 m.", true));
  q.push(tf("hard", "When $a>0$ throughout, velocity is decreasing.", false));
  q.push(fill("hard", "Interval where $s(t)=t^3-6t^2+9t$ moves left.", ["1<t<3"]));
  q.push(fill("hard", "Max height of $h(t)=-5t^2+20t$.", ["20", "20 m"]));
  q.push(fill("hard", "$v$ and $a$ same sign means ___.", ["speeding up"]));
  q.push(num("hard", "Max height (m) of $h(t)=-5t^2+20t$.", 20, 0));
  q.push(num("hard", "$v(2)$ for $s(t)=t^3-6t^2+9t$.", -3, 0));
  q.push(num("hard", "$a(1)$ for $s(t)=t^3-6t^2+9t$ (it's $6t-12$).", -6, 0));
  q.push(order("hard", "Order the steps to find a projectile's max height for $h(t)=-5t^2+20t$.", ["$v=h'=-10t+20$", "Set $v=0$: $t=2$", "$h(2)=-20+40$", "Max height $20$ m"]));
  q.push(match("hard", "Match each to its value (for $s=t^3-6t^2+9t$).", ["moves left on", "$v(2)$", "$a(1)$"], ["$1<t<3$", "$-3$", "$-6$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "5.1", gen: g51 },
  { code: "5.2", gen: g52 },
  { code: "5.3", gen: g53 },
];
