// MCV4U Unit 6 — Geometry & Algebra of Vectors: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 6.1 Introduction to Vectors ──────────────────────────────
function g61() {
  const q = [];
  q.push(mc("easy", "A vector has:", ["magnitude and direction", "magnitude only", "direction only", "neither"], 0));
  q.push(mc("easy", "A scalar has:", ["magnitude only", "magnitude and direction", "direction only", "neither"], 0));
  q.push(mc("easy", "Velocity is a:", ["vector", "scalar", "neither", "constant"], 0));
  q.push(mc("easy", "Speed is a:", ["scalar", "vector", "neither", "bearing"], 0));
  q.push(mc("easy", "$-\\vec v$ has:", ["same magnitude, opposite direction", "opposite magnitude", "the same direction", "zero magnitude"], 0));
  q.push(mc("easy", "Two vectors are equal when they share:", ["magnitude and direction", "position", "magnitude only", "a starting point"], 0));
  q.push(ms("easy", "Vectors:", ["have magnitude", "have direction", "e.g. velocity, force", "e.g. temperature"], [0, 1, 2]));
  q.push(ms("easy", "Scalars:", ["magnitude only", "e.g. speed", "e.g. mass", "have direction"], [0, 1, 2]));
  q.push(ms("easy", "Equal vectors:", ["same magnitude", "same direction", "position doesn't matter", "must start at the origin"], [0, 1, 2]));
  q.push(ms("easy", "Opposite vector $-\\vec v$:", ["same length", "reversed direction", "$|-\\vec v|=|\\vec v|$", "longer"], [0, 1, 2]));
  q.push(tf("easy", "A vector has both magnitude and direction.", true));
  q.push(tf("easy", "Speed is a vector.", false));
  q.push(tf("easy", "$-\\vec v$ has the same magnitude as $\\vec v$.", true));
  q.push(fill("easy", "Velocity is a ___.", ["vector"]));
  q.push(fill("easy", "Temperature is a ___.", ["scalar"]));
  q.push(fill("easy", "$N40^\\circ E$ as a true bearing.", ["040", "040°"]));
  q.push(num("easy", "$N75^\\circ E$ as a true bearing (degrees).", 75, 0));
  q.push(num("easy", "$N20^\\circ E$ as a true bearing (degrees).", 20, 0));
  q.push(num("easy", "Magnitude of a 500-km displacement.", 500, 0));
  q.push(match("easy", "Classify each quantity.", ["velocity", "speed", "force"], ["vector", "scalar", "vector"], [0, 1, 2]));
  q.push(mc("medium", "Force is a:", ["vector", "scalar", "neither", "bearing"], 0));
  q.push(mc("medium", "Mass is a:", ["scalar", "vector", "neither", "displacement"], 0));
  q.push(mc("medium", "If $\\vec v$ is 8 m/s east, $-\\vec v$ is:", ["8 m/s west", "8 m/s east", "−8 m/s", "0"], 0));
  q.push(mc("medium", "Two vectors equal in magnitude but opposite in direction are:", ["opposites", "equal", "perpendicular", "parallel & equal"], 0));
  q.push(mc("medium", "$N50^\\circ E$ as a true bearing:", ["$050^\\circ$", "$130^\\circ$", "$040^\\circ$", "$310^\\circ$"], 0));
  q.push(mc("medium", "Acceleration is a:", ["vector", "scalar", "neither", "bearing"], 0));
  q.push(ms("medium", "Classifying:", ["force → vector", "energy → scalar", "displacement → vector", "displacement → scalar"], [0, 1, 2]));
  q.push(ms("medium", "Opposite vectors:", ["equal magnitude", "opposite direction", "not equal vectors", "are equal"], [0, 1, 2]));
  q.push(ms("medium", "Bearings:", ["measured clockwise from north", "$N40^\\circ E=040^\\circ$", "give direction", "measured from east"], [0, 1, 2]));
  q.push(ms("medium", "Position-independence:", ["a vector can be drawn anywhere", "only magnitude & direction matter", "equal if those match", "must share a location"], [0, 1, 2]));
  q.push(tf("medium", "Force is a vector.", true));
  q.push(tf("medium", "Opposite vectors are equal vectors.", false));
  q.push(tf("medium", "$N50^\\circ E$ is the bearing $050^\\circ$.", true));
  q.push(fill("medium", "Acceleration is a ___.", ["vector"]));
  q.push(fill("medium", "$-\\vec v$ if $\\vec v$ is 10 N north.", ["10 N south", "10N south"]));
  q.push(fill("medium", "Energy is a ___.", ["scalar"]));
  q.push(num("medium", "$N50^\\circ E$ as a true bearing (degrees).", 50, 0));
  q.push(num("medium", "$N15^\\circ E$ as a true bearing (degrees).", 15, 0));
  q.push(num("medium", "$N90^\\circ E$ (due east) as a true bearing (degrees).", 90, 0));
  q.push(match("medium", "Classify each quantity.", ["acceleration", "mass", "displacement"], ["vector", "scalar", "vector"], [0, 1, 2]));
  q.push(mc("hard", "A bearing of $120^\\circ$ in N–E/S–E form is:", ["$S60^\\circ E$", "$N60^\\circ E$", "$S30^\\circ E$", "$N30^\\circ E$"], 0));
  q.push(mc("hard", "A bearing of $225^\\circ$ is:", ["$S45^\\circ W$", "$S45^\\circ E$", "$N45^\\circ W$", "$N45^\\circ E$"], 0));
  q.push(mc("hard", "Which is a scalar?", ["work", "displacement", "momentum", "force"], 0));
  q.push(mc("hard", "$\\vec{AB}=-\\vec{BA}$ because:", ["they reverse direction", "they have different magnitude", "they are equal", "$A=B$"], 0));
  q.push(mc("hard", "Two parallel vectors of equal length pointing the same way are:", ["equal", "opposite", "perpendicular", "zero"], 0));
  q.push(ms("hard", "Bearing conversions:", ["$120^\\circ=S60^\\circ E$", "$225^\\circ=S45^\\circ W$", "measured clockwise from N", "$120^\\circ=N60^\\circ E$"], [0, 1, 2]));
  q.push(ms("hard", "$\\vec{AB}$ vs $\\vec{BA}$:", ["same magnitude", "opposite direction", "$\\vec{AB}=-\\vec{BA}$", "they're equal"], [0, 1, 2]));
  q.push(ms("hard", "Scalar vs vector quantities:", ["work is scalar", "force is vector", "momentum is vector", "work is vector"], [0, 1, 2]));
  q.push(ms("hard", "Equal vectors test:", ["compare magnitude", "compare direction", "ignore position", "compare position"], [0, 1, 2]));
  q.push(tf("hard", "A bearing of $120^\\circ$ equals $S60^\\circ E$.", true));
  q.push(tf("hard", "$\\vec{AB}=-\\vec{BA}$.", true));
  q.push(tf("hard", "Work is a vector quantity.", false));
  q.push(fill("hard", "Bearing $120^\\circ$ in N–E/S–E form.", ["S60°E", "S60E"]));
  q.push(fill("hard", "Bearing $225^\\circ$ in compass form.", ["S45°W", "S45W"]));
  q.push(fill("hard", "$\\vec{AB}$ in terms of $\\vec{BA}$.", ["-BA", "-\\vec{BA}"]));
  q.push(num("hard", "$S60^\\circ E$ as a true bearing (degrees).", 120, 0));
  q.push(num("hard", "$S45^\\circ W$ as a true bearing (degrees).", 225, 0));
  q.push(num("hard", "Due west as a true bearing (degrees).", 270, 0));
  q.push(order("hard", "Order the steps to decide if two vectors are equal.", ["Find each magnitude", "Find each direction", "Compare both (ignore position)", "Equal iff both match"]));
  q.push(match("hard", "Match each bearing to compass form.", ["$120^\\circ$", "$225^\\circ$", "$315^\\circ$"], ["$S60^\\circ E$", "$S45^\\circ W$", "$N45^\\circ W$"], [0, 1, 2]));
  return q;
}

// ── 6.2 Vector Operations (Geometric) ────────────────────────
function g62() {
  const q = [];
  q.push(mc("easy", "Vectors add:", ["tip-to-tail", "tail-to-tail only", "by magnitude only", "they don't add"], 0));
  q.push(mc("easy", "$\\vec a-\\vec b$ equals:", ["$\\vec a+(-\\vec b)$", "$\\vec b-\\vec a$", "$-\\vec a+\\vec b$", "$\\vec a+\\vec b$"], 0));
  q.push(mc("easy", "$k\\vec v$ with $k<0$:", ["reverses direction", "keeps direction", "becomes zero", "rotates 90°"], 0));
  q.push(mc("easy", "Resultant magnitude of 3 east, 4 north:", ["5", "7", "12", "1"], 0));
  q.push(mc("easy", "The triangle law gives the:", ["resultant", "difference only", "magnitude only", "angle only"], 0));
  q.push(mc("easy", "$3\\vec v$ is:", ["3× as long, same direction", "3× as long, opposite", "1/3 as long", "perpendicular"], 0));
  q.push(ms("easy", "Vector addition:", ["tip-to-tail", "resultant spans start to finish", "triangle/parallelogram law", "add magnitudes only"], [0, 1, 2]));
  q.push(ms("easy", "Scalar multiplication:", ["scales length by $|k|$", "flips if $k<0$", "keeps direction if $k>0$", "always flips"], [0, 1, 2]));
  q.push(ms("easy", "Subtraction:", ["$\\vec a-\\vec b=\\vec a+(-\\vec b)$", "add the opposite", "tip-to-tail", "$\\vec b-\\vec a$"], [0, 1, 2]));
  q.push(ms("easy", "Perpendicular resultant:", ["use Pythagoras", "$\\sqrt{a^2+b^2}$", "direction via $\\tan^{-1}$", "add lengths"], [0, 1, 2]));
  q.push(tf("easy", "Vectors add tip-to-tail.", true));
  q.push(tf("easy", "$\\vec a-\\vec b=\\vec b-\\vec a$.", false));
  q.push(tf("easy", "The resultant of 3 east and 4 north has magnitude 5.", true));
  q.push(fill("easy", "Resultant magnitude of 3 east, 4 north.", ["5"]));
  q.push(fill("easy", "$\\vec a-\\vec b$ as an addition.", ["a+(-b)", "\\vec a+(-\\vec b)"]));
  q.push(fill("easy", "Describe $4\\vec v$.", ["4x length same direction", "4 times, same direction"]));
  q.push(num("easy", "Resultant magnitude of 3 east, 4 north.", 5, 0));
  q.push(num("easy", "Resultant magnitude of 6 east, 8 north.", 10, 0));
  q.push(num("easy", "Length of $5\\vec v$ if $|\\vec v|=2$.", 10, 0));
  q.push(match("easy", "Match each to its description.", ["$2\\vec v$", "$-\\vec v$", "$-3\\vec v$"], ["2× same dir", "1× opposite", "3× opposite"], [0, 1, 2]));
  q.push(mc("medium", "Resultant magnitude of 5 east, 12 north:", ["13", "17", "7", "60"], 0));
  q.push(mc("medium", "Resultant of 6 N east, 8 N north:", ["10 N at ≈53° N of E", "14 N", "2 N", "48 N"], 0));
  q.push(mc("medium", "Describe $-2\\vec v$:", ["2× as long, opposite", "2× same direction", "1/2 length", "perpendicular"], 0));
  q.push(mc("medium", "Resultant magnitude of 9 east, 12 north:", ["15", "21", "3", "108"], 0));
  q.push(mc("medium", "Direction of the resultant of 3 east, 4 north:", ["≈53° N of E", "≈37° N of E", "45°", "90°"], 0));
  q.push(mc("medium", "Resultant magnitude of 8 east, 15 north:", ["17", "23", "7", "120"], 0));
  q.push(ms("medium", "Perpendicular resultant (3,4):", ["magnitude 5", "Pythagoras", "$\\tan^{-1}\\tfrac43\\approx53^\\circ$", "magnitude 7"], [0, 1, 2]));
  q.push(ms("medium", "Resultant force (6,8):", ["$\\sqrt{36+64}=10$", "angle $\\tan^{-1}\\tfrac86$", "$\\approx53^\\circ$ N of E", "magnitude 14"], [0, 1, 2]));
  q.push(ms("medium", "$-2\\vec v$:", ["length $2|\\vec v|$", "opposite direction", "$k=-2$", "same direction"], [0, 1, 2]));
  q.push(ms("medium", "Reading a resultant:", ["from first tail to last tip", "triangle law", "magnitude by Pythagoras (if ⊥)", "sum of magnitudes always"], [0, 1, 2]));
  q.push(tf("medium", "The resultant of 5 east and 12 north has magnitude 13.", true));
  q.push(tf("medium", "$-2\\vec v$ is twice as long and opposite in direction.", true));
  q.push(tf("medium", "The resultant of 9 east and 12 north has magnitude 21.", false));
  q.push(fill("medium", "Resultant magnitude of 5 east, 12 north.", ["13"]));
  q.push(fill("medium", "Resultant magnitude of 6 N east, 8 N north.", ["10", "10 N"]));
  q.push(fill("medium", "Direction of resultant of 5 east, 5 north (N of E).", ["45", "45°"]));
  q.push(num("medium", "Resultant magnitude of 8 east, 15 north.", 17, 0));
  q.push(num("medium", "Resultant magnitude of 7 east, 24 north.", 25, 0));
  q.push(num("medium", "Resultant magnitude of 9 east, 40 north.", 41, 0));
  q.push(match("medium", "Match each pair to the resultant magnitude.", ["3 E, 4 N", "5 E, 12 N", "8 E, 15 N"], ["5", "13", "17"], [0, 1, 2]));
  q.push(mc("hard", "Two forces 10 N east, 24 N north: resultant magnitude:", ["26 N", "34 N", "14 N", "240 N"], 0));
  q.push(mc("hard", "Direction of that resultant:", ["≈67° N of E", "≈23° N of E", "45°", "≈53° N of E"], 0));
  q.push(mc("hard", "Vectors at 60° apart, each length 10: resultant magnitude:", ["≈17.3", "20", "10", "14.1"], 0));
  q.push(mc("hard", "If $\\vec a+\\vec b=\\vec 0$, then $\\vec b=$", ["$-\\vec a$", "$\\vec a$", "$2\\vec a$", "$\\vec 0$"], 0));
  q.push(mc("hard", "Resultant of equal & opposite vectors:", ["$\\vec 0$", "double", "perpendicular", "unchanged"], 0));
  q.push(ms("hard", "Resultant (10,24):", ["$\\sqrt{100+576}=26$", "angle $\\tan^{-1}\\tfrac{24}{10}$", "$\\approx67^\\circ$ N of E", "magnitude 34"], [0, 1, 2]));
  q.push(ms("hard", "Non-perpendicular addition:", ["use the cosine law", "or components", "$|\\vec R|^2=a^2+b^2+2ab\\cos\\theta$ form", "Pythagoras always works"], [0, 1, 2]));
  q.push(ms("hard", "Zero resultant:", ["$\\vec a+\\vec b=\\vec 0$", "$\\vec b=-\\vec a$", "equal & opposite", "$\\vec b=\\vec a$"], [0, 1, 2]));
  q.push(ms("hard", "Choosing a method:", ["⊥ → Pythagoras", "general → components or cosine law", "direction via $\\tan^{-1}$", "always add magnitudes"], [0, 1, 2]));
  q.push(tf("hard", "Forces 10 N east and 24 N north give a resultant of 26 N.", true));
  q.push(tf("hard", "If $\\vec a+\\vec b=\\vec 0$ then $\\vec b=-\\vec a$.", true));
  q.push(tf("hard", "Two perpendicular forces always add by simple addition of magnitudes.", false));
  q.push(fill("hard", "Resultant magnitude of 10 N east, 24 N north.", ["26", "26 N"]));
  q.push(fill("hard", "$\\vec b$ if $\\vec a+\\vec b=\\vec 0$.", ["-a", "-\\vec a"]));
  q.push(fill("hard", "Direction of the (10,24) resultant (N of E, nearest degree).", ["67", "67°"]));
  q.push(num("hard", "Resultant magnitude of 10 N east, 24 N north.", 26, 0));
  q.push(num("hard", "Resultant magnitude of 20 east, 21 north.", 29, 0));
  q.push(num("hard", "Resultant magnitude of 12 east, 35 north.", 37, 0));
  q.push(order("hard", "Order the steps to add 6 N east and 8 N north.", ["Perpendicular → Pythagoras", "$\\sqrt{6^2+8^2}=10$", "Angle $\\tan^{-1}\\tfrac86$", "$\\approx53^\\circ$ N of E"]));
  q.push(match("hard", "Match each pair to the resultant magnitude.", ["10 E, 24 N", "20 E, 21 N", "12 E, 35 N"], ["26", "29", "37"], [0, 1, 2]));
  return q;
}

// ── 6.3 Cartesian Vectors in 2-D & 3-D ───────────────────────
function g63() {
  const q = [];
  q.push(mc("easy", "$|(a,b)|=$", ["$\\sqrt{a^2+b^2}$", "$a+b$", "$a^2+b^2$", "$|a|+|b|$"], 0));
  q.push(mc("easy", "$|(3,4)|=$", ["5", "7", "12", "25"], 0));
  q.push(mc("easy", "$(2,3)+(1,-1)=$", ["$(3,2)$", "$(1,4)$", "$(3,4)$", "$(2,-3)$"], 0));
  q.push(mc("easy", "$3(2,-1)=$", ["$(6,-3)$", "$(5,2)$", "$(6,-1)$", "$(2,-3)$"], 0));
  q.push(mc("easy", "$\\vec{AB}=$", ["$B-A$", "$A-B$", "$A+B$", "$\\tfrac{A+B}2$"], 0));
  q.push(mc("easy", "A unit vector has length:", ["1", "0", "the magnitude", "2"], 0));
  q.push(ms("easy", "Magnitude:", ["$\\sqrt{a^2+b^2}$ in 2-D", "add $+c^2$ in 3-D", "always non-negative", "$a+b$"], [0, 1, 2]));
  q.push(ms("easy", "Componentwise:", ["add components", "subtract components", "scale each component", "mix components"], [0, 1, 2]));
  q.push(ms("easy", "$\\vec{AB}$:", ["$B-A$", "head minus tail", "components of the displacement", "$A-B$"], [0, 1, 2]));
  q.push(ms("easy", "Unit vector:", ["$\\vec v/|\\vec v|$", "length 1", "same direction", "length $|\\vec v|$"], [0, 1, 2]));
  q.push(tf("easy", "$|(3,4)|=5$.", true));
  q.push(tf("easy", "$\\vec{AB}=A-B$.", false));
  q.push(tf("easy", "A unit vector has length 1.", true));
  q.push(fill("easy", "$|(3,4)|$.", ["5"]));
  q.push(fill("easy", "$(2,3)+(1,-1)$.", ["(3,2)"]));
  q.push(fill("easy", "$3(2,-1)$.", ["(6,-3)"]));
  q.push(num("easy", "$|(3,4)|$.", 5, 0));
  q.push(num("easy", "$|(6,8)|$.", 10, 0));
  q.push(num("easy", "$|(5,12)|$.", 13, 0));
  q.push(match("easy", "Match each to its magnitude.", ["$(3,4)$", "$(6,8)$", "$(5,12)$"], ["5", "10", "13"], [0, 1, 2]));
  q.push(mc("medium", "$|(1,2,2)|=$", ["3", "5", "9", "7"], 0));
  q.push(mc("medium", "$|(2,3,6)|=$", ["7", "11", "5", "41"], 0));
  q.push(mc("medium", "$(5,1)-(2,4)=$", ["$(3,-3)$", "$(7,5)$", "$(3,3)$", "$(-3,3)$"], 0));
  q.push(mc("medium", "$\\vec{AB}$ for $A(1,2),B(4,6)$:", ["$(3,4)$", "$(5,8)$", "$(-3,-4)$", "$(3,8)$"], 0));
  q.push(mc("medium", "Unit vector of $(3,4)$:", ["$(\\tfrac35,\\tfrac45)$", "$(3,4)$", "$(\\tfrac15,\\tfrac15)$", "$(\\tfrac45,\\tfrac35)$"], 0));
  q.push(mc("medium", "$|(0,5)|=$", ["5", "0", "25", "$\\sqrt5$"], 0));
  q.push(ms("medium", "$|(1,2,2)|$:", ["$\\sqrt{1+4+4}$", "$=\\sqrt9$", "$=3$", "$=5$"], [0, 1, 2]));
  q.push(ms("medium", "$\\vec{AB}$ for $A(1,2),B(4,6)$:", ["$(3,4)$", "$B-A$", "magnitude 5", "magnitude 3"], [0, 1, 2]));
  q.push(ms("medium", "Unit vector of $(3,4)$:", ["divide by 5", "$(\\tfrac35,\\tfrac45)$", "length 1", "$(3,4)$"], [0, 1, 2]));
  q.push(ms("medium", "Subtraction:", ["$(5,1)-(2,4)$", "$=(3,-3)$", "componentwise", "$=(7,5)$"], [0, 1, 2]));
  q.push(tf("medium", "$|(1,2,2)|=3$.", true));
  q.push(tf("medium", "$\\vec{AB}=(3,4)$ for $A(1,2),B(4,6)$.", true));
  q.push(tf("medium", "The unit vector of $(3,4)$ is $(3,4)$.", false));
  q.push(fill("medium", "$|(2,3,6)|$.", ["7"]));
  q.push(fill("medium", "$\\vec{AB}$ for $A(2,1),B(5,5)$.", ["(3,4)"]));
  q.push(fill("medium", "Unit vector of $(6,8)$.", ["(3/5,4/5)", "(0.6,0.8)"]));
  q.push(num("medium", "$|(1,2,2)|$.", 3, 0));
  q.push(num("medium", "$|(2,3,6)|$.", 7, 0));
  q.push(num("medium", "$|\\vec{AB}|$ for $A(0,0),B(8,6)$.", 10, 0));
  q.push(match("medium", "Match each to its magnitude.", ["$(1,2,2)$", "$(2,3,6)$", "$(1,4,8)$"], ["3", "7", "9"], [0, 1, 2]));
  q.push(mc("hard", "$|(1,4,8)|=$", ["9", "13", "11", "81"], 0));
  q.push(mc("hard", "$\\vec{AB}$ and $|\\vec{AB}|$ for $A(1,2,3),B(4,6,15)$:", ["$(3,4,12),\\ 13$", "$(3,4,12),\\ 19$", "$(5,8,18),\\ 13$", "$(3,4,12),\\ 12$"], 0));
  q.push(mc("hard", "Unit vector of $(0,3,4)$:", ["$(0,\\tfrac35,\\tfrac45)$", "$(0,3,4)$", "$(\\tfrac35,\\tfrac45,0)$", "$(0,\\tfrac15,\\tfrac15)$"], 0));
  q.push(mc("hard", "A vector with magnitude 10 in the direction of $(3,4)$:", ["$(6,8)$", "$(3,4)$", "$(30,40)$", "$(\\tfrac35,\\tfrac45)$"], 0));
  q.push(mc("hard", "$2(1,2,3)-(0,1,4)=$", ["$(2,3,2)$", "$(2,5,10)$", "$(2,3,10)$", "$(1,3,2)$"], 0));
  q.push(ms("hard", "$\\vec{AB}$ for 3-D points:", ["$B-A$ componentwise", "$(3,4,12)$", "$|\\vec{AB}|=\\sqrt{9+16+144}=13$", "$=19$"], [0, 1, 2]));
  q.push(ms("hard", "Scaling to a given magnitude:", ["find the unit vector", "multiply by the desired length", "$10\\cdot(\\tfrac35,\\tfrac45)=(6,8)$", "just double"], [0, 1, 2]));
  q.push(ms("hard", "$|(1,4,8)|$:", ["$\\sqrt{1+16+64}$", "$=\\sqrt{81}$", "$=9$", "$=13$"], [0, 1, 2]));
  q.push(ms("hard", "Combined operations:", ["scale then subtract", "$2(1,2,3)=(2,4,6)$", "$-(0,1,4)\\Rightarrow(2,3,2)$", "$(2,5,10)$"], [0, 1, 2]));
  q.push(tf("hard", "$|(1,4,8)|=9$.", true));
  q.push(tf("hard", "A magnitude-10 vector along $(3,4)$ is $(6,8)$.", true));
  q.push(tf("hard", "$\\vec{AB}=(3,4,12)$ has magnitude 19 for $A(1,2,3),B(4,6,15)$.", false));
  q.push(fill("hard", "$|(1,4,8)|$.", ["9"]));
  q.push(fill("hard", "$|\\vec{AB}|$ for $A(1,2,3),B(4,6,15)$.", ["13"]));
  q.push(fill("hard", "Magnitude-10 vector along $(3,4)$.", ["(6,8)"]));
  q.push(num("hard", "$|(1,4,8)|$.", 9, 0));
  q.push(num("hard", "$|\\vec{AB}|$ for $A(1,2,3),B(4,6,15)$.", 13, 0));
  q.push(num("hard", "$|(2,10,11)|$.", 15, 0));
  q.push(order("hard", "Order the steps to find a unit vector of $(3,4)$.", ["Find the magnitude $5$", "Divide each component by 5", "$(\\tfrac35,\\tfrac45)$", "Confirm length 1"]));
  q.push(match("hard", "Match each to its magnitude.", ["$(1,4,8)$", "$(2,10,11)$", "$(2,3,6)$"], ["9", "15", "7"], [0, 1, 2]));
  return q;
}

// ── 6.4 The Dot Product ──────────────────────────────────────
function g64() {
  const q = [];
  q.push(mc("easy", "$\\vec a\\cdot\\vec b$ (2-D) $=$", ["$a_1b_1+a_2b_2$", "$a_1b_2+a_2b_1$", "$a_1b_1-a_2b_2$", "$(a_1+b_1)(a_2+b_2)$"], 0));
  q.push(mc("easy", "The dot product produces a:", ["scalar", "vector", "matrix", "bearing"], 0));
  q.push(mc("easy", "$(2,3)\\cdot(4,-1)=$", ["5", "11", "8", "−3"], 0));
  q.push(mc("easy", "$\\vec a\\cdot\\vec b=0$ means:", ["perpendicular", "parallel", "equal", "opposite"], 0));
  q.push(mc("easy", "$(1,0)\\cdot(0,1)=$", ["0", "1", "−1", "2"], 0));
  q.push(mc("easy", "Work equals:", ["$\\vec F\\cdot\\vec d$", "$\\vec F\\times\\vec d$", "$|\\vec F||\\vec d|$", "$\\vec F+\\vec d$"], 0));
  q.push(ms("easy", "The dot product:", ["$a_1b_1+a_2b_2$", "a scalar", "$=|\\vec a||\\vec b|\\cos\\theta$", "a vector"], [0, 1, 2]));
  q.push(ms("easy", "Uses of the dot product:", ["angle between vectors", "test perpendicularity", "work", "area of a triangle"], [0, 1, 2]));
  q.push(ms("easy", "Perpendicular:", ["$\\vec a\\cdot\\vec b=0$", "$\\cos\\theta=0$", "$\\theta=90^\\circ$", "$\\vec a\\cdot\\vec b=1$"], [0, 1, 2]));
  q.push(ms("easy", "Angle formula:", ["$\\cos\\theta=\\tfrac{\\vec a\\cdot\\vec b}{|\\vec a||\\vec b|}$", "needs the dot product", "and the magnitudes", "needs the cross product"], [0, 1, 2]));
  q.push(tf("easy", "The dot product is a scalar.", true));
  q.push(tf("easy", "$\\vec a\\cdot\\vec b=0$ means the vectors are parallel.", false));
  q.push(tf("easy", "$(2,3)\\cdot(4,-1)=5$.", true));
  q.push(fill("easy", "$(2,3)\\cdot(4,-1)$.", ["5"]));
  q.push(fill("easy", "$(1,0)\\cdot(0,1)$.", ["0"]));
  q.push(fill("easy", "Work $=\\vec F\\cdot$ ___.", ["d", "\\vec d"]));
  q.push(num("easy", "$(2,3)\\cdot(4,-1)$.", 5, 0));
  q.push(num("easy", "$(1,2)\\cdot(3,4)$.", 11, 0));
  q.push(num("easy", "$(1,0)\\cdot(0,1)$.", 0, 0));
  q.push(match("easy", "Match each to its dot product.", ["$(2,3)\\cdot(4,-1)$", "$(1,2)\\cdot(3,4)$", "$(1,0)\\cdot(0,1)$"], ["5", "11", "0"], [0, 1, 2]));
  q.push(mc("medium", "$(1,2,3)\\cdot(2,0,-1)=$", ["−1", "1", "5", "0"], 0));
  q.push(mc("medium", "Angle between $(1,0)$ and $(1,1)$:", ["45°", "30°", "60°", "90°"], 0));
  q.push(mc("medium", "Are $(2,3)$ and $(3,-2)$ perpendicular?", ["yes", "no", "only in 3-D", "cannot tell"], 0));
  q.push(mc("medium", "Work of $\\vec F=(3,4)$ along $\\vec d=(2,0)$:", ["6", "10", "12", "0"], 0));
  q.push(mc("medium", "$(2,-1,3)\\cdot(1,4,2)=$", ["4", "6", "−2", "0"], 0));
  q.push(mc("medium", "Angle between $(1,0)$ and $(0,1)$:", ["90°", "45°", "0°", "180°"], 0));
  q.push(ms("medium", "$(1,2,3)\\cdot(2,0,-1)$:", ["$2+0-3$", "$=-1$", "componentwise", "$=5$"], [0, 1, 2]));
  q.push(ms("medium", "Angle of $(1,0),(1,1)$:", ["$\\cos\\theta=\\tfrac1{\\sqrt2}$", "$\\theta=45^\\circ$", "uses the dot product", "$\\theta=90^\\circ$"], [0, 1, 2]));
  q.push(ms("medium", "Perpendicularity of $(2,3),(3,-2)$:", ["$6-6=0$", "dot product zero", "perpendicular", "parallel"], [0, 1, 2]));
  q.push(ms("medium", "Work:", ["$\\vec F\\cdot\\vec d$", "$(3)(2)+(4)(0)$", "$=6$ J", "$=12$"], [0, 1, 2]));
  q.push(tf("medium", "$(1,2,3)\\cdot(2,0,-1)=-1$.", true));
  q.push(tf("medium", "$(2,3)$ and $(3,-2)$ are perpendicular.", true));
  q.push(tf("medium", "The angle between $(1,0)$ and $(1,1)$ is 30°.", false));
  q.push(fill("medium", "$(1,2,3)\\cdot(2,0,-1)$.", ["-1"]));
  q.push(fill("medium", "Angle between $(1,0)$ and $(1,1)$ (degrees).", ["45", "45°"]));
  q.push(fill("medium", "Work of $\\vec F=(3,4)$ along $\\vec d=(2,0)$.", ["6", "6 J"]));
  q.push(num("medium", "$(2,-1,3)\\cdot(1,4,2)$.", 4, 0));
  q.push(num("medium", "Angle between $(1,0)$ and $(1,1)$ (degrees).", 45, 0));
  q.push(num("medium", "Work of $\\vec F=(5,0)$ along $\\vec d=(3,4)$.", 15, 0));
  q.push(match("medium", "Match each to its value.", ["$(1,2,3)\\cdot(2,0,-1)$", "angle of $(1,0),(1,1)$", "work $(3,4)\\cdot(2,0)$"], ["$-1$", "$45^\\circ$", "$6$"], [0, 1, 2]));
  q.push(mc("hard", "Angle between $(3,4)$ and $(4,3)$ (nearest degree):", ["16°", "30°", "45°", "53°"], 0));
  q.push(mc("hard", "For which $k$ are $(2,k)$ and $(3,-1)$ perpendicular?", ["6", "−6", "2", "3"], 0));
  q.push(mc("hard", "$(1,1,1)\\cdot(2,3,4)=$", ["9", "24", "6", "0"], 0));
  q.push(mc("hard", "If $\\vec a\\cdot\\vec a=25$, then $|\\vec a|=$", ["5", "25", "$\\sqrt5$", "12.5"], 0));
  q.push(mc("hard", "Angle between $(1,0)$ and $(-1,0)$:", ["180°", "0°", "90°", "45°"], 0));
  q.push(ms("hard", "Angle of $(3,4),(4,3)$:", ["$\\vec a\\cdot\\vec b=24$", "$|\\vec a||\\vec b|=25$", "$\\cos\\theta=\\tfrac{24}{25}$", "$\\theta\\approx16^\\circ$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Finding $k$ for perpendicularity:", ["set the dot product to 0", "$(2)(3)+(k)(-1)=0$", "$6-k=0\\Rightarrow k=6$", "$k=-6$"], [0, 1, 2]));
  q.push(ms("hard", "$\\vec a\\cdot\\vec a$:", ["$=|\\vec a|^2$", "always $\\ge0$", "$|\\vec a|=\\sqrt{\\vec a\\cdot\\vec a}$", "can be negative"], [0, 1, 2]));
  q.push(ms("hard", "Opposite vectors:", ["$\\theta=180^\\circ$", "$\\cos\\theta=-1$", "$\\vec a\\cdot\\vec b=-|\\vec a||\\vec b|$", "$\\vec a\\cdot\\vec b=0$"], [0, 1, 2]));
  q.push(tf("hard", "$(2,6)$ and $(3,-1)$ are perpendicular.", true));
  q.push(tf("hard", "If $\\vec a\\cdot\\vec a=25$ then $|\\vec a|=5$.", true));
  q.push(tf("hard", "The angle between $(3,4)$ and $(4,3)$ is 45°.", false));
  q.push(fill("hard", "$k$ making $(2,k)$ and $(3,-1)$ perpendicular.", ["6"]));
  q.push(fill("hard", "$|\\vec a|$ if $\\vec a\\cdot\\vec a=25$.", ["5"]));
  q.push(fill("hard", "Angle between $(3,4)$ and $(4,3)$ (nearest degree).", ["16", "16°"]));
  q.push(num("hard", "$k$ making $(2,k)$ and $(3,-1)$ perpendicular.", 6, 0));
  q.push(num("hard", "$|\\vec a|$ if $\\vec a\\cdot\\vec a=49$.", 7, 0));
  q.push(num("hard", "Angle (degrees) between $(1,0)$ and $(-1,0)$.", 180, 0));
  q.push(order("hard", "Order the steps to find the angle between $(3,4)$ and $(4,3)$.", ["Dot product $=24$", "$|\\vec a||\\vec b|=25$", "$\\cos\\theta=\\tfrac{24}{25}$", "$\\theta\\approx16^\\circ$"]));
  q.push(match("hard", "Match each to its value.", ["$(1,1,1)\\cdot(2,3,4)$", "$|\\vec a|$ if $\\vec a\\cdot\\vec a=25$", "angle of $(1,0),(-1,0)$"], ["9", "5", "180°"], [0, 1, 2]));
  return q;
}

// ── 6.5 The Cross Product ────────────────────────────────────
function g65() {
  const q = [];
  q.push(mc("easy", "The cross product produces a:", ["vector", "scalar", "matrix", "number"], 0));
  q.push(mc("easy", "$\\vec a\\times\\vec b$ is ___ to both $\\vec a$ and $\\vec b$:", ["perpendicular", "parallel", "equal", "opposite"], 0));
  q.push(mc("easy", "The cross product exists in:", ["3-D", "2-D only", "1-D", "any dimension"], 0));
  q.push(mc("easy", "$(1,0,0)\\times(0,1,0)=$", ["$(0,0,1)$", "$(1,0,0)$", "$(0,1,0)$", "$(0,0,0)$"], 0));
  q.push(mc("easy", "$|\\vec a\\times\\vec b|$ equals the:", ["parallelogram area", "dot product", "sum", "perimeter"], 0));
  q.push(mc("easy", "Triangle area $=$", ["$\\tfrac12|\\vec a\\times\\vec b|$", "$|\\vec a\\times\\vec b|$", "$\\vec a\\cdot\\vec b$", "$2|\\vec a\\times\\vec b|$"], 0));
  q.push(ms("easy", "The cross product:", ["a vector", "perpendicular to both", "3-D only", "a scalar"], [0, 1, 2]));
  q.push(ms("easy", "Magnitude:", ["$|\\vec a||\\vec b|\\sin\\theta$", "the parallelogram area", "$0$ if parallel", "the dot product"], [0, 1, 2]));
  q.push(ms("easy", "Direction:", ["perpendicular to both", "right-hand rule", "out of the plane", "along $\\vec a$"], [0, 1, 2]));
  q.push(ms("easy", "Area uses:", ["parallelogram $=|\\vec a\\times\\vec b|$", "triangle $=\\tfrac12|\\vec a\\times\\vec b|$", "the cross product", "the dot product"], [0, 1, 2]));
  q.push(tf("easy", "The cross product is a vector.", true));
  q.push(tf("easy", "The cross product is defined in 2-D.", false));
  q.push(tf("easy", "$\\vec a\\times\\vec b$ is perpendicular to both inputs.", true));
  q.push(fill("easy", "$(1,0,0)\\times(0,1,0)$.", ["(0,0,1)"]));
  q.push(fill("easy", "Triangle area in terms of the cross product.", ["1/2|a×b|", "(1/2)|axb|"]));
  q.push(fill("easy", "$\\vec a\\times\\vec b$ is ___ to both vectors.", ["perpendicular"]));
  q.push(num("easy", "Magnitude of $(0,0,1)$ (from $(1,0,0)\\times(0,1,0)$).", 1, 0));
  q.push(num("easy", "Parallelogram area from $(2,0,0)$ and $(0,3,0)$.", 6, 0));
  q.push(num("easy", "Parallelogram area from $(1,0,0)$ and $(0,2,0)$.", 2, 0));
  q.push(match("easy", "Match each cross product.", ["$(1,0,0)\\times(0,1,0)$", "$(0,1,0)\\times(0,0,1)$", "$(0,0,1)\\times(1,0,0)$"], ["$(0,0,1)$", "$(1,0,0)$", "$(0,1,0)$"], [0, 1, 2]));
  q.push(mc("medium", "$(1,2,3)\\times(4,5,6)=$", ["$(-3,6,-3)$", "$(3,-6,3)$", "$(0,0,0)$", "$(-3,-6,-3)$"], 0));
  q.push(mc("medium", "$(2,0,0)\\times(0,3,0)=$", ["$(0,0,6)$", "$(6,0,0)$", "$(0,6,0)$", "$(0,0,0)$"], 0));
  q.push(mc("medium", "$(1,1,0)\\times(0,1,1)=$", ["$(1,-1,1)$", "$(1,1,1)$", "$(-1,1,-1)$", "$(0,0,0)$"], 0));
  q.push(mc("medium", "Area of the parallelogram from $(3,0,0),(0,4,0)$:", ["12", "7", "5", "24"], 0));
  q.push(mc("medium", "$(0,1,0)\\times(0,0,1)=$", ["$(1,0,0)$", "$(0,0,1)$", "$(0,-1,0)$", "$(0,0,0)$"], 0));
  q.push(mc("medium", "Triangle area from $(2,0,0),(0,2,0)$:", ["2", "4", "1", "8"], 0));
  q.push(ms("medium", "$(1,2,3)\\times(4,5,6)$:", ["$(2\\cdot6-3\\cdot5,\\dots)$", "$=(-3,6,-3)$", "perpendicular to both", "$=(3,6,3)$"], [0, 1, 2]));
  q.push(ms("medium", "Parallelogram area from $(3,0,0),(0,4,0)$:", ["cross $=(0,0,12)$", "magnitude 12", "area 12", "area 7"], [0, 1, 2]));
  q.push(ms("medium", "$(1,1,0)\\times(0,1,1)$:", ["$(1\\cdot1-0\\cdot1,\\,0\\cdot0-1\\cdot1,\\,1\\cdot1-1\\cdot0)$", "$=(1,-1,1)$", "perpendicular to both", "$=(1,1,1)$"], [0, 1, 2]));
  q.push(ms("medium", "Triangle area:", ["$\\tfrac12|\\vec a\\times\\vec b|$", "half the parallelogram", "$\\tfrac12(4)=2$ here", "equals the parallelogram"], [0, 1, 2]));
  q.push(tf("medium", "$(1,2,3)\\times(4,5,6)=(-3,6,-3)$.", true));
  q.push(tf("medium", "The parallelogram from $(3,0,0),(0,4,0)$ has area 12.", true));
  q.push(tf("medium", "$(2,0,0)\\times(0,3,0)=(6,0,0)$.", false));
  q.push(fill("medium", "$(1,2,3)\\times(4,5,6)$.", ["(-3,6,-3)"]));
  q.push(fill("medium", "$(1,1,0)\\times(0,1,1)$.", ["(1,-1,1)"]));
  q.push(fill("medium", "Parallelogram area from $(3,0,0),(0,4,0)$.", ["12"]));
  q.push(num("medium", "Parallelogram area from $(3,0,0),(0,4,0)$.", 12, 0));
  q.push(num("medium", "Triangle area from $(2,0,0),(0,2,0)$.", 2, 0));
  q.push(num("medium", "$z$-component of $(1,2,3)\\times(4,5,6)$.", -3, 0));
  q.push(match("medium", "Match each cross product.", ["$(1,2,3)\\times(4,5,6)$", "$(2,0,0)\\times(0,3,0)$", "$(1,1,0)\\times(0,1,1)$"], ["$(-3,6,-3)$", "$(0,0,6)$", "$(1,-1,1)$"], [0, 1, 2]));
  q.push(mc("hard", "$(1,2,3)\\times(2,4,6)=$", ["$(0,0,0)$", "$(-3,6,-3)$", "$(1,1,1)$", "$(2,4,6)$"], 0));
  q.push(mc("hard", "Why is $(1,2,3)\\times(2,4,6)=\\vec0$?", ["the vectors are parallel", "they are equal", "$\\theta=90^\\circ$", "they are unit vectors"], 0));
  q.push(mc("hard", "Is $(-3,6,-3)$ perpendicular to $(4,5,6)$?", ["yes ($-12+30-18=0$)", "no", "only to $(1,2,3)$", "cannot tell"], 0));
  q.push(mc("hard", "Triangle with $A(0,0,0),B(1,0,0),C(0,2,3)$: area:", ["$\\tfrac12\\sqrt{13}$", "$\\sqrt{13}$", "$\\tfrac12\\sqrt5$", "$3$"], 0));
  q.push(mc("hard", "$\\vec a\\times\\vec b=-(\\vec b\\times\\vec a)$ because the cross product is:", ["anti-commutative", "commutative", "associative", "scalar"], 0));
  q.push(ms("hard", "Parallel vectors:", ["cross product $=\\vec0$", "$\\sin\\theta=0$", "$(1,2,3),(2,4,6)$ parallel", "perpendicular"], [0, 1, 2]));
  q.push(ms("hard", "Triangle area via cross product:", ["$\\vec{AB}\\times\\vec{AC}$", "take half the magnitude", "$(1,0,0)\\times(0,2,3)=(0,-3,2)$", "use the dot product"], [0, 1, 2]));
  q.push(ms("hard", "Anti-commutativity:", ["$\\vec a\\times\\vec b=-\\vec b\\times\\vec a$", "order flips the sign", "direction reverses", "order doesn't matter"], [0, 1, 2]));
  q.push(ms("hard", "Perpendicularity check:", ["dot the result with an input", "should be 0", "$(-3,6,-3)\\cdot(4,5,6)=0$", "should be 1"], [0, 1, 2]));
  q.push(tf("hard", "$(1,2,3)\\times(2,4,6)=\\vec0$ because the vectors are parallel.", true));
  q.push(tf("hard", "The cross product is anti-commutative.", true));
  q.push(tf("hard", "$(1,2,3)\\times(4,5,6)$ is parallel to $(4,5,6)$.", false));
  q.push(fill("hard", "$(1,2,3)\\times(2,4,6)$.", ["(0,0,0)", "0"]));
  q.push(fill("hard", "Area of triangle $A(0,0,0),B(1,0,0),C(0,2,3)$.", ["(1/2)sqrt(13)", "√13/2"]));
  q.push(fill("hard", "$\\vec a\\times\\vec b$ in terms of $\\vec b\\times\\vec a$.", ["-(b×a)", "-\\vec b×\\vec a"]));
  q.push(num("hard", "$(-3,6,-3)\\cdot(4,5,6)$ (perpendicularity check).", 0, 0));
  q.push(num("hard", "$(1,2,3)\\times(2,4,6)$ — its magnitude.", 0, 0));
  q.push(num("hard", "Parallelogram area from $A(0,0,0)$ via $(1,0,0)$ and $(0,2,3)$ ($=|(0,-3,2)|=\\sqrt{13}$); enter $13$ for the radicand.", 13, 0));
  q.push(order("hard", "Order the steps to find a triangle's area from two edge vectors.", ["Compute $\\vec a\\times\\vec b$", "Take its magnitude", "Halve it", "That is the triangle's area"]));
  q.push(match("hard", "Match each fact.", ["$(1,2,3)\\times(2,4,6)$", "cross-product order", "perpendicular check"], ["$\\vec0$ (parallel)", "anti-commutative", "dot $=0$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "6.1", gen: g61 },
  { code: "6.2", gen: g62 },
  { code: "6.3", gen: g63 },
  { code: "6.4", gen: g64 },
  { code: "6.5", gen: g65 },
];
