// MCV4U Unit 7 — Lines & Planes: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 7.1 Equations of Lines ───────────────────────────────────
function g71() {
  const q = [];
  q.push(mc("easy", "A line is fixed by:", ["a point and a direction vector", "two normals", "one point only", "a magnitude"], 0));
  q.push(mc("easy", "The vector equation of a line is:", ["$\\vec r=\\vec r_0+t\\vec d$", "$\\vec r=t\\vec d$", "$\\vec r=\\vec r_0$", "$Ax+By=C$"], 0));
  q.push(mc("easy", "A direction vector through $A,B$ is:", ["$B-A$", "$A+B$", "$\\tfrac{A+B}2$", "$AB$"], 0));
  q.push(mc("easy", "Parametric form of $\\vec r=(1,2)+t(3,4)$:", ["$x=1+3t,\\ y=2+4t$", "$x=3+t,\\ y=4+2t$", "$x=1+4t,\\ y=2+3t$", "$x=t,\\ y=t$"], 0));
  q.push(mc("easy", "The symmetric form solves each parametric equation for:", ["$t$", "$x$", "$y$", "$\\vec d$"], 0));
  q.push(mc("easy", "Direction vector through $A(1,0,2),B(4,6,8)$:", ["$(3,6,6)$", "$(5,6,10)$", "$(3,6,10)$", "$(1,0,2)$"], 0));
  q.push(ms("easy", "Forms of a line:", ["vector $\\vec r=\\vec r_0+t\\vec d$", "parametric", "symmetric", "scalar $Ax+By+Cz=D$"], [0, 1, 2]));
  q.push(ms("easy", "Direction vectors:", ["$\\vec d=B-A$ through two points", "any nonzero multiple works", "set the line's direction", "must be a unit vector"], [0, 1, 2]));
  q.push(ms("easy", "Vector form:", ["$\\vec r=\\vec r_0+t\\vec d$", "$\\vec r_0$ is a point", "$\\vec d$ is a direction", "$t$ is fixed"], [0, 1, 2]));
  q.push(ms("easy", "Checking a point on a line:", ["solve one component for $t$", "verify the others", "consistent ⇒ on the line", "any $t$ works"], [0, 1, 2]));
  q.push(tf("easy", "A line needs a point and a direction vector.", true));
  q.push(tf("easy", "A direction vector through $A,B$ is $A-B$ only.", false));
  q.push(tf("easy", "Parametric form of $\\vec r=(1,2)+t(3,4)$ is $x=1+3t,\\ y=2+4t$.", true));
  q.push(fill("easy", "The vector equation of a line.", ["r=r0+td", "\\vec r=\\vec r_0+t\\vec d"]));
  q.push(fill("easy", "Direction vector through $A(1,0,2),B(4,6,8)$.", ["(3,6,6)"]));
  q.push(fill("easy", "Parametric form of $\\vec r=(3,-1)+t(1,2)$.", ["x=3+t, y=-1+2t"]));
  q.push(num("easy", "First component of the direction $B-A$ for $A(1,0,2),B(4,6,8)$.", 3, 0));
  q.push(num("easy", "The $t$-value where $(4,6)$ sits on $\\vec r=(1,2)+t(3,4)$.", 1, 0));
  q.push(num("easy", "Number of points needed (besides a direction) to fix a line.", 1, 0));
  q.push(match("easy", "Match each form to its name.", ["$\\vec r=\\vec r_0+t\\vec d$", "$x=x_0+ta$", "$\\tfrac{x-x_0}{a}=\\tfrac{y-y_0}{b}$"], ["vector", "parametric", "symmetric"], [0, 1, 2]));
  q.push(mc("medium", "Vector equation through $(0,1)$ with direction $(2,5)$:", ["$\\vec r=(0,1)+t(2,5)$", "$\\vec r=(2,5)+t(0,1)$", "$\\vec r=(0,1)$", "$2x+5y=1$"], 0));
  q.push(mc("medium", "Is $(4,6)$ on $\\vec r=(1,2)+t(3,4)$?", ["yes ($t=1$)", "no", "only $x$ matches", "yes ($t=2$)"], 0));
  q.push(mc("medium", "Symmetric equation through $(1,2)$ with direction $(3,4)$:", ["$\\tfrac{x-1}{3}=\\tfrac{y-2}{4}$", "$\\tfrac{x-3}{1}=\\tfrac{y-4}{2}$", "$3x+4y=11$", "$\\tfrac{x}{3}=\\tfrac{y}{4}$"], 0));
  q.push(mc("medium", "Vector equation through $A(1,0,2),B(4,6,8)$:", ["$(1,0,2)+t(3,6,6)$", "$(4,6,8)+t(1,0,2)$", "$(3,6,6)+t(1,0,2)$", "$(1,0,2)+t(5,6,10)$"], 0));
  q.push(mc("medium", "Is $(7,11)$ on $\\vec r=(1,2)+t(3,3)$?", ["no", "yes ($t=2$)", "yes ($t=3$)", "only $y$ matches"], 0));
  q.push(mc("medium", "Direction vector through $A(2,1,0),B(5,7,6)$:", ["$(3,6,6)$", "$(7,8,6)$", "$(3,6,0)$", "$(5,7,6)$"], 0));
  q.push(ms("medium", "Line through two points:", ["$\\vec d=B-A$", "use either point as $\\vec r_0$", "$\\vec r=A+t(B-A)$", "$\\vec d=A+B$"], [0, 1, 2]));
  q.push(ms("medium", "$(4,6)$ on $\\vec r=(1,2)+t(3,4)$:", ["$4=1+3t\\Rightarrow t=1$", "check $y$: $2+4=6$ ✓", "on the line", "not on the line"], [0, 1, 2]));
  q.push(ms("medium", "Symmetric form:", ["solve each parametric eqn for $t$", "equate the expressions", "$\\tfrac{x-x_0}{a}=\\tfrac{y-y_0}{b}$", "$Ax+By=D$"], [0, 1, 2]));
  q.push(ms("medium", "Equivalent lines:", ["same line, different $\\vec r_0$ allowed", "direction can be scaled", "many vector equations", "only one equation"], [0, 1, 2]));
  q.push(tf("medium", "$(4,6)$ lies on $\\vec r=(1,2)+t(3,4)$.", true));
  q.push(tf("medium", "$(7,11)$ lies on $\\vec r=(1,2)+t(3,3)$.", false));
  q.push(tf("medium", "Any nonzero scalar multiple of a direction vector gives the same line's direction.", true));
  q.push(fill("medium", "Symmetric eqn through $(1,2)$, direction $(3,4)$.", ["(x-1)/3=(y-2)/4"]));
  q.push(fill("medium", "$t$ where $(4,6)$ is on $\\vec r=(1,2)+t(3,4)$.", ["1"]));
  q.push(fill("medium", "Vector equation through $A(1,0,2),B(4,6,8)$.", ["(1,0,2)+t(3,6,6)"]));
  q.push(num("medium", "$t$ where $(4,6)$ lies on $\\vec r=(1,2)+t(3,4)$.", 1, 0));
  q.push(num("medium", "Third component of the direction through $A(2,1,0),B(5,7,6)$.", 6, 0));
  q.push(num("medium", "$y$-value at $t=2$ on $\\vec r=(3,-1)+t(1,2)$.", 3, 0));
  q.push(match("medium", "Match each line to its direction vector.", ["through $A(1,0,2),B(4,6,8)$", "$\\vec r=(0,1)+t(2,5)$", "$x=3+t,y=-1+2t$"], ["$(3,6,6)$", "$(2,5)$", "$(1,2)$"], [0, 1, 2]));
  q.push(mc("hard", "Lines $\\vec r=(0,0)+t(2,4)$ and $\\vec r=(1,1)+s(1,2)$ are:", ["parallel", "intersecting", "perpendicular", "the same line"], 0));
  q.push(mc("hard", "Is $(2,4,6)$ on $\\vec r=(0,0,0)+t(1,2,3)$?", ["yes ($t=2$)", "no", "only $x$ matches", "yes ($t=3$)"], 0));
  q.push(mc("hard", "A line parallel to $(3,6,6)$ could have direction:", ["$(1,2,2)$", "$(3,6,5)$", "$(1,2,3)$", "$(6,6,3)$"], 0));
  q.push(mc("hard", "The $x$-axis has vector equation:", ["$\\vec r=(0,0,0)+t(1,0,0)$", "$\\vec r=(0,0,0)+t(0,1,0)$", "$x=0$", "$\\vec r=(1,0,0)$"], 0));
  q.push(mc("hard", "Two lines with directions $(1,2)$ and $(2,1)$ are:", ["not parallel", "parallel", "the same", "perpendicular"], 0));
  q.push(ms("hard", "Parallel lines:", ["directions are scalar multiples", "$(2,4)=2(1,2)$", "same direction", "directions $(1,2),(2,1)$ are parallel"], [0, 1, 2]));
  q.push(ms("hard", "$(2,4,6)$ on $\\vec r=t(1,2,3)$:", ["$2=t,\\ 4=2t,\\ 6=3t$", "all give $t=2$", "consistent ⇒ on the line", "inconsistent"], [0, 1, 2]));
  q.push(ms("hard", "Scaling directions:", ["$(1,2,2)\\parallel(3,6,6)$", "since $(3,6,6)=3(1,2,2)$", "same line direction", "they're perpendicular"], [0, 1, 2]));
  q.push(ms("hard", "Building a line from two points:", ["$\\vec d=B-A$", "$\\vec r=A+t\\vec d$", "parametric splits the components", "needs a normal"], [0, 1, 2]));
  q.push(tf("hard", "$\\vec r=(0,0)+t(2,4)$ and $\\vec r=(1,1)+s(1,2)$ are parallel.", true));
  q.push(tf("hard", "$(2,4,6)$ lies on $\\vec r=t(1,2,3)$.", true));
  q.push(tf("hard", "Directions $(1,2)$ and $(2,1)$ are parallel.", false));
  q.push(fill("hard", "Relationship of $\\vec r=(0,0)+t(2,4)$ and $\\vec r=(1,1)+s(1,2)$.", ["parallel"]));
  q.push(fill("hard", "Vector equation of the $x$-axis.", ["r=(0,0,0)+t(1,0,0)", "(0,0,0)+t(1,0,0)"]));
  q.push(fill("hard", "A direction parallel to $(3,6,6)$ (simplest).", ["(1,2,2)"]));
  q.push(num("hard", "$t$ where $(2,4,6)$ lies on $\\vec r=t(1,2,3)$.", 2, 0));
  q.push(num("hard", "Scalar $k$ with $(2,4)=k(1,2)$.", 2, 0));
  q.push(num("hard", "Number of solutions for two parallel, distinct lines' intersection.", 0, 0));
  q.push(order("hard", "Order the steps to check $(4,6)$ is on $\\vec r=(1,2)+t(3,4)$.", ["$4=1+3t$", "$t=1$", "Check $y$: $2+4(1)=6$", "Consistent ⇒ on the line"]));
  q.push(match("hard", "Match each pair of directions to their relationship.", ["$(2,4),(1,2)$", "$(1,2),(2,1)$", "$(3,6,6),(1,2,2)$"], ["parallel", "not parallel", "parallel"], [0, 1, 2]));
  return q;
}

// ── 7.2 Equations of Planes ──────────────────────────────────
function g72() {
  const q = [];
  q.push(mc("easy", "A plane is fixed by:", ["a point and a normal vector", "two points", "a direction vector only", "a magnitude"], 0));
  q.push(mc("easy", "The normal of $2x+y-z=5$ is:", ["$(2,1,-1)$", "$(2,1,5)$", "$(5,1,-1)$", "$(1,1,1)$"], 0));
  q.push(mc("easy", "The scalar equation of a plane is:", ["$Ax+By+Cz=D$", "$\\vec r=\\vec r_0+t\\vec d$", "$Ax+By=C$", "$x=a$"], 0));
  q.push(mc("easy", "The normal of a plane is ___ to it:", ["perpendicular", "parallel", "tangent", "inside"], 0));
  q.push(mc("easy", "Is $(1,1,1)$ on $2x+y-z=2$?", ["yes", "no", "only if $z=0$", "cannot tell"], 0));
  q.push(mc("easy", "A normal from two in-plane directions comes from the:", ["cross product", "dot product", "sum", "difference"], 0));
  q.push(ms("easy", "Plane essentials:", ["a point", "a normal", "scalar eqn $Ax+By+Cz=D$", "two normals"], [0, 1, 2]));
  q.push(ms("easy", "Reading the normal:", ["it's $(A,B,C)$", "the coefficients", "from $Ax+By+Cz=D$", "from $D$"], [0, 1, 2]));
  q.push(ms("easy", "Building the scalar equation:", ["$A(x-x_0)+B(y-y_0)+C(z-z_0)=0$", "uses a point", "uses the normal", "uses two points only"], [0, 1, 2]));
  q.push(ms("easy", "Normal from directions:", ["$\\vec n=\\vec u\\times\\vec v$", "perpendicular to both", "use the cross product", "use the dot product"], [0, 1, 2]));
  q.push(tf("easy", "A plane needs a point and a normal vector.", true));
  q.push(tf("easy", "The normal of $2x+y-z=5$ is $(2,1,5)$.", false));
  q.push(tf("easy", "$(1,1,1)$ is on $2x+y-z=2$.", true));
  q.push(fill("easy", "Normal vector of $2x+y-z=5$.", ["(2,1,-1)"]));
  q.push(fill("easy", "Scalar equation through $(0,0,0)$ with normal $(1,2,3)$.", ["x+2y+3z=0"]));
  q.push(fill("easy", "How to get a normal from two directions.", ["cross product", "u×v"]));
  q.push(num("easy", "First component of the normal of $3x-y+4z=7$.", 3, 0));
  q.push(num("easy", "Value of $D$ for the plane $x+2y+3z=0$.", 0, 0));
  q.push(num("easy", "Number of points needed (besides a normal) to fix a plane.", 1, 0));
  q.push(match("easy", "Match each plane to its normal.", ["$2x+y-z=5$", "$x+2y+3z=0$", "$z=4$"], ["$(2,1,-1)$", "$(1,2,3)$", "$(0,0,1)$"], [0, 1, 2]));
  q.push(mc("medium", "Scalar equation through $(1,2,3)$ with normal $(2,1,-1)$:", ["$2x+y-z=1$", "$2x+y-z=5$", "$2x+y-z=0$", "$x+y+z=6$"], 0));
  q.push(mc("medium", "Normal of $3x-y+4z=7$:", ["$(3,-1,4)$", "$(3,1,4)$", "$(7,-1,4)$", "$(3,-1,7)$"], 0));
  q.push(mc("medium", "Is $(2,0,1)$ on $x+y+z=3$?", ["yes", "no", "only if $y=1$", "cannot tell"], 0));
  q.push(mc("medium", "Normal from $\\vec u=(1,0,0),\\vec v=(0,1,0)$:", ["$(0,0,1)$", "$(1,1,0)$", "$(0,0,0)$", "$(1,0,0)$"], 0));
  q.push(mc("medium", "Plane through $A(0,0,0),B(1,0,0),C(0,1,0)$:", ["$z=0$", "$x=0$", "$y=0$", "$x+y=0$"], 0));
  q.push(mc("medium", "Scalar equation through $(2,0,0)$ with normal $(1,0,0)$:", ["$x=2$", "$x=0$", "$y=2$", "$x+y+z=2$"], 0));
  q.push(ms("medium", "Plane from point & normal:", ["$2(x-1)+(y-2)-(z-3)=0$", "expand", "$2x+y-z=1$", "$=5$"], [0, 1, 2]));
  q.push(ms("medium", "Plane through 3 points:", ["two direction vectors", "$\\vec n=\\vec{AB}\\times\\vec{AC}$", "then a scalar equation", "needs only one point"], [0, 1, 2]));
  q.push(ms("medium", "Checking a point:", ["substitute into $Ax+By+Cz$", "compare with $D$", "equal ⇒ on the plane", "any value works"], [0, 1, 2]));
  q.push(ms("medium", "Special planes:", ["$z=k$ has normal $(0,0,1)$", "$x=k$ has normal $(1,0,0)$", "axis-aligned", "$z=k$ has normal $(1,0,0)$"], [0, 1, 2]));
  q.push(tf("medium", "The plane through $(1,2,3)$ with normal $(2,1,-1)$ is $2x+y-z=1$.", true));
  q.push(tf("medium", "$(2,0,1)$ is on $x+y+z=3$.", true));
  q.push(tf("medium", "$(1,0,0)\\times(0,1,0)=(0,0,1)$ is a valid plane normal.", true));
  q.push(fill("medium", "Scalar equation through $(1,2,3)$ with normal $(2,1,-1)$.", ["2x+y-z=1"]));
  q.push(fill("medium", "Plane through $A(0,0,0),B(1,0,0),C(0,1,0)$.", ["z=0"]));
  q.push(fill("medium", "Scalar equation through $(2,0,0)$ with normal $(1,0,0)$.", ["x=2"]));
  q.push(num("medium", "$D$ for the plane through $(1,2,3)$, normal $(2,1,-1)$ (in $2x+y-z=D$).", 1, 0));
  q.push(num("medium", "$z$-component of $(1,0,0)\\times(0,1,0)$.", 1, 0));
  q.push(num("medium", "$D$ for $x+y+z=D$ through $(2,0,1)$.", 3, 0));
  q.push(match("medium", "Match each to its plane.", ["pt $(1,2,3)$, $\\vec n=(2,1,-1)$", "$A,B,C$ in $xy$-plane", "pt $(2,0,0)$, $\\vec n=(1,0,0)$"], ["$2x+y-z=1$", "$z=0$", "$x=2$"], [0, 1, 2]));
  q.push(mc("hard", "Plane through $A(1,0,0),B(0,1,0),C(0,0,1)$:", ["$x+y+z=1$", "$x+y+z=0$", "$x+y+z=3$", "$xyz=1$"], 0));
  q.push(mc("hard", "Normal of the plane through $A(0,0,0),B(2,0,0),C(0,3,0)$:", ["$(0,0,6)$", "$(2,3,0)$", "$(6,0,0)$", "$(0,0,1)$"], 0));
  q.push(mc("hard", "Are $x+y+z=1$ and $2x+2y+2z=5$ the same plane?", ["no (parallel & distinct)", "yes", "they intersect in a line", "perpendicular"], 0));
  q.push(mc("hard", "A plane with normal $(0,0,1)$ through $(5,7,3)$:", ["$z=3$", "$z=5$", "$x=5$", "$z=0$"], 0));
  q.push(mc("hard", "If a plane contains the origin, then $D=$", ["0", "1", "the normal", "undefined"], 0));
  q.push(ms("hard", "Plane through 3 points $A,B,C$:", ["$\\vec{AB}\\times\\vec{AC}$ for the normal", "use any point for $\\vec r_0$", "form $Ax+By+Cz=D$", "uses the dot product"], [0, 1, 2]));
  q.push(ms("hard", "Same vs parallel planes:", ["proportional normals → parallel", "proportional whole equations → same", "$x+y+z=1$ vs $2x+2y+2z=5$ are distinct", "they're identical"], [0, 1, 2]));
  q.push(ms("hard", "Origin on a plane:", ["substitute $(0,0,0)$", "gives $D=0$", "the plane passes through O", "$D=1$"], [0, 1, 2]));
  q.push(ms("hard", "Intercept plane:", ["$A(1,0,0),B(0,1,0),C(0,0,1)$", "normal $(1,1,1)$", "$x+y+z=1$", "$x+y+z=0$"], [0, 1, 2]));
  q.push(tf("hard", "The plane through $(1,0,0),(0,1,0),(0,0,1)$ is $x+y+z=1$.", true));
  q.push(tf("hard", "$x+y+z=1$ and $2x+2y+2z=5$ are parallel and distinct.", true));
  q.push(tf("hard", "$x+y+z=1$ and $2x+2y+2z=2$ are different planes.", false));
  q.push(fill("hard", "Plane through $(1,0,0),(0,1,0),(0,0,1)$.", ["x+y+z=1"]));
  q.push(fill("hard", "Normal of the plane through $A(0,0,0),B(2,0,0),C(0,3,0)$.", ["(0,0,6)", "(0,0,1)"]));
  q.push(fill("hard", "$D$ when a plane passes through the origin.", ["0"]));
  q.push(num("hard", "$D$ for $x+y+z=D$ through $(1,0,0),(0,1,0),(0,0,1)$.", 1, 0));
  q.push(num("hard", "$z$-component of $\\vec{AB}\\times\\vec{AC}$ for $A(0,0,0),B(2,0,0),C(0,3,0)$.", 6, 0));
  q.push(num("hard", "$D$ for a plane $z=D$ through $(5,7,3)$.", 3, 0));
  q.push(order("hard", "Order the steps to find the plane through $A(1,0,0),B(0,1,0),C(0,0,1)$.", ["$\\vec{AB}=(-1,1,0),\\ \\vec{AC}=(-1,0,1)$", "$\\vec n=\\vec{AB}\\times\\vec{AC}=(1,1,1)$", "Use point $A$: $1(x-1)+y+z=0$", "$x+y+z=1$"]));
  q.push(match("hard", "Match each plane to a fact.", ["through O", "$x+y+z=1$ vs $2x+2y+2z=5$", "normal $(0,0,1)$ at $(5,7,3)$"], ["$D=0$", "parallel & distinct", "$z=3$"], [0, 1, 2]));
  return q;
}

// ── 7.3 Intersections of Lines & Planes ──────────────────────
function g73() {
  const q = [];
  q.push(mc("easy", "To find a line–plane intersection you:", ["substitute the line into the plane", "add the equations", "take a cross product", "guess"], 0));
  q.push(mc("easy", "A line is parallel to a plane when:", ["$\\vec d\\cdot\\vec n=0$", "$\\vec d\\cdot\\vec n=1$", "$\\vec d=\\vec n$", "$\\vec d\\times\\vec n=0$"], 0));
  q.push(mc("easy", "Two planes are parallel when their normals are:", ["parallel", "perpendicular", "zero", "equal in length"], 0));
  q.push(mc("easy", "Where does $\\vec r=(1,0,0)+t(0,0,1)$ meet $z=5$?", ["$(1,0,5)$", "$(1,0,0)$", "$(5,0,0)$", "$(0,0,5)$"], 0));
  q.push(mc("easy", "Two lines are parallel when their directions are:", ["scalar multiples", "perpendicular", "different lengths", "both zero"], 0));
  q.push(mc("easy", "Where does $x=t,y=t,z=t$ meet $x+y+z=6$?", ["$(2,2,2)$", "$(6,6,6)$", "$(1,1,1)$", "$(3,3,3)$"], 0));
  q.push(ms("easy", "Line–plane intersection:", ["substitute the line", "solve for $t$", "back-substitute for the point", "add normals"], [0, 1, 2]));
  q.push(ms("easy", "Parallel relationships:", ["line ∥ plane: $\\vec d\\cdot\\vec n=0$", "planes ∥: normals parallel", "lines ∥: directions parallel", "always intersect"], [0, 1, 2]));
  q.push(ms("easy", "Possible line–plane outcomes:", ["one point", "no intersection (parallel)", "the whole line (contained)", "two points"], [0, 1, 2]));
  q.push(ms("easy", "Substitution method:", ["use the parametric line", "plug $x,y,z$ into the plane", "solve the resulting equation", "ignore $t$"], [0, 1, 2]));
  q.push(tf("easy", "A line ∥ plane when $\\vec d\\cdot\\vec n=0$.", true));
  q.push(tf("easy", "Two planes are parallel when their normals are perpendicular.", false));
  q.push(tf("easy", "$\\vec r=(1,0,0)+t(0,0,1)$ meets $z=5$ at $(1,0,5)$.", true));
  q.push(fill("easy", "Condition for a line to be parallel to a plane.", ["d·n=0", "\\vec d\\cdot\\vec n=0"]));
  q.push(fill("easy", "Intersection of $x=t,y=t,z=t$ and $x+y+z=6$.", ["(2,2,2)"]));
  q.push(fill("easy", "Two planes are parallel when their ___ are parallel.", ["normals"]));
  q.push(num("easy", "$t$ where $x=t,y=t,z=t$ meets $x+y+z=6$.", 2, 0));
  q.push(num("easy", "$z$ where $\\vec r=(1,0,0)+t(0,0,1)$ meets $z=5$.", 5, 0));
  q.push(num("easy", "$\\vec d\\cdot\\vec n$ for a line parallel to a plane.", 0, 0));
  q.push(match("easy", "Match each relationship to its test.", ["line ∥ plane", "planes ∥", "lines ∥"], ["$\\vec d\\cdot\\vec n=0$", "normals parallel", "directions parallel"], [0, 1, 2]));
  q.push(mc("medium", "Where does $x=t,y=t,z=t$ meet $x+y+z=9$?", ["$(3,3,3)$", "$(9,9,9)$", "$(2,2,2)$", "$(1,1,1)$"], 0));
  q.push(mc("medium", "Are $x+y+z=1$ and $2x+2y+2z=5$ parallel?", ["yes (distinct)", "no", "they coincide", "they intersect in a line"], 0));
  q.push(mc("medium", "Is direction $(1,1,1)$ parallel to $x+y+z=4$?", ["no ($\\vec d\\cdot\\vec n=3$)", "yes", "only if it passes through O", "cannot tell"], 0));
  q.push(mc("medium", "Where does $\\vec r=(0,0,0)+t(1,0,0)$ meet $x=4$?", ["$(4,0,0)$", "$(0,4,0)$", "$(4,4,4)$", "$(0,0,4)$"], 0));
  q.push(mc("medium", "Are $\\vec r=(0,0)+t(2,4)$ and $\\vec r=(1,1)+s(1,2)$ parallel?", ["yes", "no", "perpendicular", "the same line"], 0));
  q.push(mc("medium", "Where does $x=2t,y=t,z=t$ meet $x+y+z=8$?", ["$(4,2,2)$", "$(8,4,4)$", "$(2,1,1)$", "$(4,4,4)$"], 0));
  q.push(ms("medium", "Substitute & solve:", ["$x=t,y=t,z=t$ into $x+y+z=9$", "$3t=9$", "$t=3$", "$t=9$"], [0, 1, 2]));
  q.push(ms("medium", "Line parallel to plane:", ["$\\vec d\\cdot\\vec n=0$", "and the point is not on the plane", "no intersection", "always intersects"], [0, 1, 2]));
  q.push(ms("medium", "Parallel planes:", ["normals are scalar multiples", "equations not proportional ⇒ distinct", "$x+y+z=1$ vs $=5$ scaled", "they intersect"], [0, 1, 2]));
  q.push(ms("medium", "Parallel lines:", ["$(2,4)=2(1,2)$", "directions scalar multiples", "no unique intersection", "perpendicular"], [0, 1, 2]));
  q.push(tf("medium", "$x=t,y=t,z=t$ meets $x+y+z=9$ at $(3,3,3)$.", true));
  q.push(tf("medium", "Direction $(1,1,1)$ is parallel to $x+y+z=4$.", false));
  q.push(tf("medium", "$\\vec r=(0,0)+t(2,4)$ and $\\vec r=(1,1)+s(1,2)$ are parallel.", true));
  q.push(fill("medium", "Intersection of $x=t,y=t,z=t$ and $x+y+z=9$.", ["(3,3,3)"]));
  q.push(fill("medium", "Intersection of $\\vec r=(0,0,0)+t(1,0,0)$ and $x=4$.", ["(4,0,0)"]));
  q.push(fill("medium", "$\\vec d\\cdot\\vec n$ for direction $(1,1,1)$ and plane $x+y+z=4$.", ["3"]));
  q.push(num("medium", "$t$ where $x=t,y=t,z=t$ meets $x+y+z=9$.", 3, 0));
  q.push(num("medium", "$t$ where $x=2t,y=t,z=t$ meets $x+y+z=8$.", 2, 0));
  q.push(num("medium", "$x$ where $\\vec r=(0,0,0)+t(1,0,0)$ meets $x=7$.", 7, 0));
  q.push(match("medium", "Match each to its result.", ["$x=t,y=t,z=t$ & $x+y+z=9$", "dir $(1,1,1)$ & $x+y+z=4$", "$x+y+z=1$ & $2x+2y+2z=5$"], ["$(3,3,3)$", "crosses", "parallel & distinct"], [0, 1, 2]));
  q.push(mc("hard", "Where does $x=1+t,y=2+t,z=3+t$ meet $x+y+z=12$?", ["$(3,4,5)$", "$(4,5,6)$", "$(2,3,4)$", "$(1,2,3)$"], 0));
  q.push(mc("hard", "Two planes with normals $(1,2,3)$ and $(2,4,6)$ are:", ["parallel", "perpendicular", "intersecting in a line", "skew"], 0));
  q.push(mc("hard", "A line lies in a plane when:", ["$\\vec d\\cdot\\vec n=0$ and a point is on the plane", "$\\vec d\\cdot\\vec n\\ne0$", "$\\vec d=\\vec n$", "never"], 0));
  q.push(mc("hard", "Lines that are not parallel and don't intersect (in 3-D) are:", ["skew", "parallel", "coincident", "perpendicular"], 0));
  q.push(mc("hard", "$x=t,y=2t,z=0$ and the plane $z=0$:", ["the line lies in the plane", "meet at one point", "are parallel & distinct", "are skew"], 0));
  q.push(ms("hard", "$x=1+t,y=2+t,z=3+t$ into $x+y+z=12$:", ["$6+3t=12$", "$t=2$", "$(3,4,5)$", "$t=12$"], [0, 1, 2]));
  q.push(ms("hard", "Line contained in a plane:", ["$\\vec d\\cdot\\vec n=0$", "a point of the line satisfies the plane", "infinitely many intersection points", "no points"], [0, 1, 2]));
  q.push(ms("hard", "Skew lines:", ["not parallel", "don't intersect", "only in 3-D", "always in 2-D"], [0, 1, 2]));
  q.push(ms("hard", "Parallel planes detail:", ["normals proportional", "$(1,2,3),(2,4,6)$ proportional", "no intersection if distinct", "they always meet"], [0, 1, 2]));
  q.push(tf("hard", "$x=1+t,y=2+t,z=3+t$ meets $x+y+z=12$ at $(3,4,5)$.", true));
  q.push(tf("hard", "Planes with normals $(1,2,3)$ and $(2,4,6)$ are parallel.", true));
  q.push(tf("hard", "Two lines that are not parallel always intersect in 3-D.", false));
  q.push(fill("hard", "Intersection of $x=1+t,y=2+t,z=3+t$ and $x+y+z=12$.", ["(3,4,5)"]));
  q.push(fill("hard", "Lines that are neither parallel nor intersecting (3-D).", ["skew"]));
  q.push(fill("hard", "$x=t,y=2t,z=0$ relative to $z=0$.", ["lies in the plane", "contained"]));
  q.push(num("hard", "$t$ where $x=1+t,y=2+t,z=3+t$ meets $x+y+z=12$.", 2, 0));
  q.push(num("hard", "Number of intersection points of a line lying in a plane.", 0, 0));
  q.push(num("hard", "$\\vec d\\cdot\\vec n$ for a line contained in (or parallel to) a plane.", 0, 0));
  q.push(order("hard", "Order the steps to intersect $x=1+t,y=2+t,z=3+t$ with $x+y+z=12$.", ["Substitute: $(1+t)+(2+t)+(3+t)=12$", "$6+3t=12$", "$t=2$", "Point $(3,4,5)$"]));
  q.push(match("hard", "Match each pair to its relationship.", ["normals $(1,2,3),(2,4,6)$", "not-parallel, non-meeting lines", "$\\vec d\\cdot\\vec n=0$, point on plane"], ["parallel planes", "skew", "line in plane"], [0, 1, 2]));
  return q;
}

export default [
  { code: "7.1", gen: g71 },
  { code: "7.2", gen: g72 },
  { code: "7.3", gen: g73 },
];
