// MCF3M Unit 1 — Quadratic Expressions & Equations: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 1.1 Expanding & Simplifying Quadratic Expressions ────────
function g11() {
  const q = [];
  q.push(mc("easy", "$3(x+4)$ =", ["$3x+12$", "$3x+4$", "$x+12$", "$3x+7$"], 0));
  q.push(mc("easy", "$2x(x-5)$ =", ["$2x^2-10x$", "$2x^2-5$", "$2x-10$", "$2x^2-10$"], 0));
  q.push(mc("easy", "$(x+2)(x+3)$ =", ["$x^2+5x+6$", "$x^2+6x+5$", "$x^2+6$", "$x^2+5$"], 0));
  q.push(mc("easy", "$(x+5)^2$ =", ["$x^2+10x+25$", "$x^2+25$", "$x^2+5x+25$", "$x^2+10x+5$"], 0));
  q.push(mc("easy", "$(x-4)(x+4)$ =", ["$x^2-16$", "$x^2+16$", "$x^2-8x-16$", "$x^2-8$"], 0));
  q.push(mc("easy", "$5(x-2)$ =", ["$5x-10$", "$5x-2$", "$5x+10$", "$x-10$"], 0));
  q.push(ms("easy", "Expanding tools:", ["distribute", "FOIL", "collect like terms", "add exponents"], [0, 1, 2]));
  q.push(ms("easy", "Special products:", ["$(a+b)^2=a^2+2ab+b^2$", "$(a-b)(a+b)=a^2-b^2$", "the middle term matters", "$(a+b)^2=a^2+b^2$"], [0, 1, 2]));
  q.push(ms("easy", "$(x+2)(x+3)$:", ["$x^2$", "$+5x$", "$+6$", "$+6x$"], [0, 1, 2]));
  q.push(ms("easy", "Standard form:", ["$ax^2+bx+c$", "descending degree", "collected terms", "factored"], [0, 1, 2]));
  q.push(tf("easy", "$(x+2)(x+3)=x^2+5x+6$.", true));
  q.push(tf("easy", "$(x+5)^2=x^2+25$.", false));
  q.push(tf("easy", "$(x-4)(x+4)=x^2-16$.", true));
  q.push(fill("easy", "Expand $(x+1)(x+4)$.", ["x^2+5x+4", "x²+5x+4"]));
  q.push(fill("easy", "Expand $3(2x-5)$.", ["6x-15"]));
  q.push(fill("easy", "Expand $(x-3)^2$.", ["x^2-6x+9", "x²-6x+9"]));
  q.push(num("easy", "Coefficient of $x$ in $(x+2)(x+3)$.", 5, 0));
  q.push(num("easy", "Constant in $(x+5)(x-2)$.", -10, 0));
  q.push(num("easy", "Coefficient of $x$ in $(x+3)^2$.", 6, 0));
  q.push(match("easy", "Match each expansion.", ["$(x+3)^2$", "$(x-4)(x+4)$", "$(x+5)(x-2)$"], ["$x^2+6x+9$", "$x^2-16$", "$x^2+3x-10$"], [0, 1, 2]));
  q.push(mc("medium", "$(2x-3)(x+5)$ =", ["$2x^2+7x-15$", "$2x^2-7x-15$", "$2x^2+13x-15$", "$2x^2+7x+15$"], 0));
  q.push(mc("medium", "$(3x+2)^2$ =", ["$9x^2+12x+4$", "$9x^2+4$", "$9x^2+6x+4$", "$6x^2+12x+4$"], 0));
  q.push(mc("medium", "$2x(x+1)+x(x-3)$ =", ["$3x^2-x$", "$3x^2+x$", "$2x^2-x$", "$3x^2-3x$"], 0));
  q.push(mc("medium", "$(x-6)(x+2)$ =", ["$x^2-4x-12$", "$x^2+4x-12$", "$x^2-4x+12$", "$x^2-8x-12$"], 0));
  q.push(mc("medium", "$(2x-1)(2x+1)$ =", ["$4x^2-1$", "$4x^2+1$", "$2x^2-1$", "$4x^2-4x-1$"], 0));
  q.push(mc("medium", "$-2(x^2-3x+1)$ =", ["$-2x^2+6x-2$", "$-2x^2-6x-2$", "$-2x^2+6x+2$", "$-2x^2-3x+1$"], 0));
  q.push(ms("medium", "$(2x-3)(x+5)$:", ["$2x^2$", "$10x-3x=7x$", "$-15$", "$2x^2+7x-15$"], [0, 1, 2, 3]));
  q.push(ms("medium", "$(3x+2)^2$:", ["$9x^2$", "$+12x$", "$+4$", "$9x^2+4$"], [0, 1, 2]));
  q.push(ms("medium", "Simplifying after expanding:", ["combine like terms", "watch signs", "collect by degree", "add exponents"], [0, 1, 2]));
  q.push(ms("medium", "Distributing a negative:", ["each term's sign flips", "$-2(x^2-3x+1)=-2x^2+6x-2$", "be careful with signs", "only the first term"], [0, 1, 2]));
  q.push(tf("medium", "$(3x+2)^2=9x^2+12x+4$.", true));
  q.push(tf("medium", "$(2x-1)(2x+1)=4x^2-1$.", true));
  q.push(tf("medium", "$(x-6)(x+2)=x^2+4x-12$.", false));
  q.push(fill("medium", "Expand $(2x-3)(x+5)$.", ["2x^2+7x-15", "2x²+7x-15"]));
  q.push(fill("medium", "Expand $(3x-2)^2$.", ["9x^2-12x+4", "9x²-12x+4"]));
  q.push(fill("medium", "Simplify $2x(x+1)+x(x-3)$.", ["3x^2-x", "3x²-x"]));
  q.push(num("medium", "Coefficient of $x$ in $(2x-3)(x+5)$.", 7, 0));
  q.push(num("medium", "Constant in $(2x-3)(x+5)$.", -15, 0));
  q.push(num("medium", "Coefficient of $x$ in $(3x+2)^2$.", 12, 0));
  q.push(match("medium", "Match each expansion.", ["$(2x-3)(x+5)$", "$(3x+2)^2$", "$(2x-1)(2x+1)$"], ["$2x^2+7x-15$", "$9x^2+12x+4$", "$4x^2-1$"], [0, 1, 2]));
  q.push(mc("hard", "$(x+2)(x^2-3x+1)$ =", ["$x^3-x^2-5x+2$", "$x^3-x^2+5x+2$", "$x^3+x^2-5x+2$", "$x^3-5x+2$"], 0));
  q.push(mc("hard", "$(2x-1)^2-(x+3)^2$ =", ["$3x^2-10x-8$", "$3x^2+10x-8$", "$3x^2-8$", "$5x^2-10x-8$"], 0));
  q.push(mc("hard", "$(x+2)(x+3)-(x+1)(x-1)$ =", ["$5x+7$", "$5x+5$", "$x^2+5x+7$", "$5x-7$"], 0));
  q.push(mc("hard", "$3(x-2)^2$ =", ["$3x^2-12x+12$", "$3x^2-4x+4$", "$3x^2-12x+4$", "$3x^2-6x+12$"], 0));
  q.push(mc("hard", "$(x+1)^3$ =", ["$x^3+3x^2+3x+1$", "$x^3+1$", "$x^3+3x+1$", "$x^3+x^2+x+1$"], 0));
  q.push(ms("hard", "$(2x-1)^2$:", ["$4x^2$", "$-4x$", "$+1$", "$4x^2-4x+1$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Subtracting expansions:", ["expand both", "distribute the minus", "combine like terms", "ignore signs"], [0, 1, 2]));
  q.push(ms("hard", "$(x+2)(x^2-3x+1)$:", ["multiply term by term", "collect like terms", "$x^3-x^2-5x+2$", "$x^3-5x+2$"], [0, 1, 2]));
  q.push(ms("hard", "$3(x-2)^2$:", ["square first", "$x^2-4x+4$", "then times 3", "$3x^2-12x+12$"], [0, 1, 2, 3]));
  q.push(tf("hard", "$(x+2)(x+3)-(x+1)(x-1)=5x+7$.", true));
  q.push(tf("hard", "$3(x-2)^2=3x^2-12x+12$.", true));
  q.push(tf("hard", "$(2x-1)^2-(x+3)^2=3x^2-8$.", false));
  q.push(fill("hard", "Expand $(x+2)(x^2-3x+1)$.", ["x^3-x^2-5x+2"]));
  q.push(fill("hard", "Simplify $(x+2)(x+3)-(x+1)(x-1)$.", ["5x+7"]));
  q.push(fill("hard", "Expand $3(x-2)^2$.", ["3x^2-12x+12", "3x²-12x+12"]));
  q.push(num("hard", "Coefficient of $x^2$ in $(x+2)(x^2-3x+1)$.", -1, 0));
  q.push(num("hard", "Value of $(x+2)(x+3)-(x+1)(x-1)$ at $x=3$.", 22, 0));
  q.push(num("hard", "Coefficient of $x$ in $(2x-1)^2$.", -4, 0));
  q.push(order("hard", "Order the steps to expand $3(x-2)^2$.", ["Square: $(x-2)^2=x^2-4x+4$", "Multiply by 3", "$3x^2-12x+12$", "State the result"]));
  q.push(match("hard", "Match each expansion.", ["$(2x-1)^2$", "$3(x-2)^2$", "$(x+1)^3$"], ["$4x^2-4x+1$", "$3x^2-12x+12$", "$x^3+3x^2+3x+1$"], [0, 1, 2]));
  return q;
}

// ── 1.2 Factoring Quadratic Expressions ──────────────────────
function g12() {
  const q = [];
  q.push(mc("easy", "Factor $x^2+5x+6$.", ["$(x+2)(x+3)$", "$(x+1)(x+6)$", "$(x-2)(x-3)$", "$(x+5)(x+6)$"], 0));
  q.push(mc("easy", "Factor $x^2-9$.", ["$(x-3)(x+3)$", "$(x-9)(x+1)$", "$(x-3)^2$", "$(x+3)^2$"], 0));
  q.push(mc("easy", "Common factor of $4x+8$.", ["$4$", "$2$", "$x$", "$8$"], 0));
  q.push(mc("easy", "Factor $x^2-x-6$.", ["$(x-3)(x+2)$", "$(x+3)(x-2)$", "$(x-6)(x+1)$", "$(x-3)(x-2)$"], 0));
  q.push(mc("easy", "Factor $6x^2+9x$.", ["$3x(2x+3)$", "$3(2x^2+3x)$", "$3x(2x+9)$", "$x(6x+9)$"], 0));
  q.push(mc("easy", "Factor $x^2+7x+12$.", ["$(x+3)(x+4)$", "$(x+2)(x+6)$", "$(x+1)(x+12)$", "$(x+3)(x+5)$"], 0));
  q.push(ms("easy", "To factor $x^2+5x+6$:", ["two numbers with product 6", "and sum 5", "$2$ and $3$", "product 5"], [0, 1, 2]));
  q.push(ms("easy", "Difference of squares:", ["$a^2-b^2=(a-b)(a+b)$", "$x^2-9=(x-3)(x+3)$", "two terms", "$a^2+b^2$"], [0, 1, 2]));
  q.push(ms("easy", "Common factoring:", ["take out the GCF", "$4x+8=4(x+2)$", "reverse distribution", "add terms"], [0, 1, 2]));
  q.push(ms("easy", "Which factor over the integers?", ["$x^2-9$", "$x^2+5x+6$", "$x^2-x-6$", "$x^2+1$"], [0, 1, 2]));
  q.push(tf("easy", "$x^2-9=(x-3)(x+3)$.", true));
  q.push(tf("easy", "$x^2+9=(x+3)^2$.", false));
  q.push(tf("easy", "$6x^2+9x=3x(2x+3)$.", true));
  q.push(fill("easy", "Factor $x^2+8x+15$.", ["(x+3)(x+5)", "(x+5)(x+3)"]));
  q.push(fill("easy", "Factor $x^2-16$.", ["(x-4)(x+4)", "(x+4)(x-4)"]));
  q.push(fill("easy", "Factor $5x+10$.", ["5(x+2)"]));
  q.push(num("easy", "In $x^2+5x+6=(x+a)(x+b)$, the value $a+b$.", 5, 0));
  q.push(num("easy", "In $x^2-9=(x-a)(x+a)$, the value $a$.", 3, 0));
  q.push(num("easy", "GCF of $6x+9$.", 3, 0));
  q.push(match("easy", "Match each to its factors.", ["$x^2-9$", "$x^2+5x+6$", "$x^2-x-6$"], ["$(x-3)(x+3)$", "$(x+2)(x+3)$", "$(x-3)(x+2)$"], [0, 1, 2]));
  q.push(mc("medium", "Factor $2x^2+7x+3$.", ["$(2x+1)(x+3)$", "$(2x+3)(x+1)$", "$(2x+1)(x-3)$", "$(x+1)(x+3)$"], 0));
  q.push(mc("medium", "Factor $x^2-10x+25$.", ["$(x-5)^2$", "$(x+5)^2$", "$(x-5)(x+5)$", "$(x-25)(x-1)$"], 0));
  q.push(mc("medium", "Factor $3x^2+13x-10$.", ["$(3x-2)(x+5)$", "$(3x+2)(x-5)$", "$(3x-5)(x+2)$", "$(3x-10)(x+1)$"], 0));
  q.push(mc("medium", "Factor $4x^2-9$.", ["$(2x-3)(2x+3)$", "$(4x-3)(x+3)$", "$(2x-9)(2x+1)$", "$(2x-3)^2$"], 0));
  q.push(mc("medium", "Factor $x^2-2x-15$.", ["$(x-5)(x+3)$", "$(x+5)(x-3)$", "$(x-15)(x+1)$", "$(x-5)(x-3)$"], 0));
  q.push(mc("medium", "Factor $5x^2-20$.", ["$5(x-2)(x+2)$", "$5(x^2-4)$", "$(5x-4)(x+5)$", "$5(x-4)(x+1)$"], 0));
  q.push(ms("medium", "Factoring $2x^2+7x+3$:", ["$ac=6$", "split $7x=6x+x$", "group", "$(2x+1)(x+3)$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Perfect-square trinomial:", ["$x^2-10x+25=(x-5)^2$", "first & last are squares", "middle $=2ab$", "$x^2+25$"], [0, 1, 2]));
  q.push(ms("medium", "Factor out the GCF first:", ["$5x^2-20=5(x^2-4)$", "then difference of squares", "$5(x-2)(x+2)$", "cannot factor"], [0, 1, 2]));
  q.push(ms("medium", "Decomposition for $ax^2+bx+c$:", ["find numbers with product $ac$", "and sum $b$", "then group", "ignore $a$"], [0, 1, 2]));
  q.push(tf("medium", "$x^2-10x+25=(x-5)^2$.", true));
  q.push(tf("medium", "$5x^2-20=5(x-2)(x+2)$.", true));
  q.push(tf("medium", "$4x^2-9=(2x-3)^2$.", false));
  q.push(fill("medium", "Factor $2x^2+7x+3$.", ["(2x+1)(x+3)", "(x+3)(2x+1)"]));
  q.push(fill("medium", "Factor $x^2-10x+25$.", ["(x-5)^2", "(x-5)(x-5)"]));
  q.push(fill("medium", "Factor $4x^2-9$.", ["(2x-3)(2x+3)", "(2x+3)(2x-3)"]));
  q.push(num("medium", "In $2x^2+7x+3$, the product $ac$.", 6, 0));
  q.push(num("medium", "GCF to remove from $5x^2-20$.", 5, 0));
  q.push(num("medium", "Repeated root of $(x-5)^2$.", 5, 0));
  q.push(match("medium", "Match each to its factors.", ["$x^2-10x+25$", "$4x^2-9$", "$2x^2+7x+3$"], ["$(x-5)^2$", "$(2x-3)(2x+3)$", "$(2x+1)(x+3)$"], [0, 1, 2]));
  q.push(mc("hard", "Factor $6x^2+x-2$.", ["$(3x+2)(2x-1)$", "$(3x-2)(2x+1)$", "$(6x-1)(x+2)$", "$(3x-1)(2x+2)$"], 0));
  q.push(mc("hard", "Factor $6x^2+11x-10$.", ["$(3x-2)(2x+5)$", "$(3x+2)(2x-5)$", "$(6x-5)(x+2)$", "$(2x-2)(3x+5)$"], 0));
  q.push(mc("hard", "Factor fully $2x^2-18$.", ["$2(x-3)(x+3)$", "$(2x-3)(x+6)$", "$2(x^2-9)$", "$(x-3)(2x+6)$"], 0));
  q.push(mc("hard", "Factor $3x^2-10x+3$.", ["$(3x-1)(x-3)$", "$(3x-3)(x-1)$", "$(3x+1)(x-3)$", "$(x-3)(3x+1)$"], 0));
  q.push(mc("hard", "Factor fully $x^3-4x$.", ["$x(x-2)(x+2)$", "$x(x^2-4)$", "$x^2(x-4)$", "$(x-2)(x+2)$"], 0));
  q.push(ms("hard", "Factoring $6x^2+x-2$:", ["$ac=-12$", "$4$ and $-3$", "group", "$(3x+2)(2x-1)$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Factor fully means:", ["until no further factoring", "check for a GCF", "then patterns", "stop at first step"], [0, 1, 2]));
  q.push(ms("hard", "$2x^2-18$:", ["common factor 2", "$2(x^2-9)$", "$2(x-3)(x+3)$", "cannot factor"], [0, 1, 2]));
  q.push(ms("hard", "$x^3-4x$:", ["common factor $x$", "$x(x^2-4)$", "$x(x-2)(x+2)$", "$x^2(x-4)$"], [0, 1, 2]));
  q.push(tf("hard", "$6x^2+x-2=(3x+2)(2x-1)$.", true));
  q.push(tf("hard", "$2x^2-18$ factors fully to $2(x-3)(x+3)$.", true));
  q.push(tf("hard", "$x^3-4x=x(x^2-4)$ is fully factored.", false));
  q.push(fill("hard", "Factor $6x^2+x-2$.", ["(3x+2)(2x-1)", "(2x-1)(3x+2)"]));
  q.push(fill("hard", "Factor fully $2x^2-18$.", ["2(x-3)(x+3)", "2(x+3)(x-3)"]));
  q.push(fill("hard", "Factor fully $x^3-4x$.", ["x(x-2)(x+2)", "x(x+2)(x-2)"]));
  q.push(num("hard", "In $6x^2+x-2$, the product $ac$.", -12, 0));
  q.push(num("hard", "GCF removed from $2x^2-18$.", 2, 0));
  q.push(num("hard", "Number of linear factors of $x^3-4x$.", 3, 0));
  q.push(order("hard", "Order the steps to factor fully $2x^2-18$.", ["Common factor: $2(x^2-9)$", "Recognize a difference of squares", "$2(x-3)(x+3)$", "State fully factored"]));
  q.push(match("hard", "Match each to its factored form.", ["$6x^2+x-2$", "$2x^2-18$", "$x^3-4x$"], ["$(3x+2)(2x-1)$", "$2(x-3)(x+3)$", "$x(x-2)(x+2)$"], [0, 1, 2]));
  return q;
}

// ── 1.3 Solving Quadratic Equations by Factoring ─────────────
function g13() {
  const q = [];
  q.push(mc("easy", "Solve $x^2-5x+6=0$.", ["$2,3$", "$-2,-3$", "$1,6$", "$5,6$"], 0));
  q.push(mc("easy", "Solve $x^2-9=0$.", ["$\\pm3$", "$\\pm9$", "$3$", "$9$"], 0));
  q.push(mc("easy", "Solve $(x-4)(x+1)=0$.", ["$4,-1$", "$-4,1$", "$4,1$", "$-4,-1$"], 0));
  q.push(mc("easy", "Solve $x^2+2x-8=0$.", ["$2,-4$", "$-2,4$", "$2,4$", "$-2,-4$"], 0));
  q.push(mc("easy", "Solve $x^2-6x=0$.", ["$0,6$", "$6$", "$-6$", "$0,-6$"], 0));
  q.push(mc("easy", "The zero product property:", ["if $AB=0$ then $A=0$ or $B=0$", "always $A=0$", "$A+B=0$", "$AB=1$"], 0));
  q.push(ms("easy", "Solving $x^2-5x+6=0$:", ["factor $(x-2)(x-3)$", "set each $=0$", "$x=2,3$", "$x=5,6$"], [0, 1, 2]));
  q.push(ms("easy", "Steps:", ["rearrange to $=0$", "factor", "each factor $=0$", "add factors"], [0, 1, 2]));
  q.push(ms("easy", "$x^2-9=0$:", ["$(x-3)(x+3)=0$", "$x=\\pm3$", "two solutions", "$x=9$"], [0, 1, 2]));
  q.push(ms("easy", "Solutions mean:", ["x-intercepts", "where $y=0$", "the roots", "y-intercepts"], [0, 1, 2]));
  q.push(tf("easy", "$x^2-5x+6=0$ has solutions $2,3$.", true));
  q.push(tf("easy", "A quadratic must equal 0 before factoring to solve.", true));
  q.push(tf("easy", "$x^2-9=0$ has only $x=3$.", false));
  q.push(fill("easy", "Solve $x^2-7x+10=0$.", ["2,5", "5,2"]));
  q.push(fill("easy", "Solve $x^2-16=0$.", ["±4", "4,-4", "-4,4"]));
  q.push(fill("easy", "Solve $x^2+x-6=0$.", ["2,-3", "-3,2"]));
  q.push(num("easy", "Larger solution of $x^2-5x+6=0$.", 3, 0));
  q.push(num("easy", "Positive solution of $x^2-49=0$.", 7, 0));
  q.push(num("easy", "Larger solution of $x^2+2x-8=0$.", 2, 0));
  q.push(match("easy", "Match each equation to its solutions.", ["$x^2-9=0$", "$x^2-5x+6=0$", "$(x-4)(x+1)=0$"], ["$\\pm3$", "$2,3$", "$4,-1$"], [0, 1, 2]));
  q.push(mc("medium", "Solve $2x^2-7x+3=0$.", ["$\\tfrac12,3$", "$-\\tfrac12,-3$", "$3,2$", "$\\tfrac13,2$"], 0));
  q.push(mc("medium", "Solve $3x^2-5x-2=0$.", ["$2,-\\tfrac13$", "$-2,\\tfrac13$", "$2,\\tfrac13$", "$-2,-\\tfrac13$"], 0));
  q.push(mc("medium", "Solve $x^2+7x+10=0$.", ["$-2,-5$", "$2,5$", "$-2,5$", "$2,-5$"], 0));
  q.push(mc("medium", "Solve $x^2-x-12=0$.", ["$4,-3$", "$-4,3$", "$4,3$", "$-4,-3$"], 0));
  q.push(mc("medium", "Solve $x^2-8x=0$.", ["$0,8$", "$8$", "$-8$", "$0,-8$"], 0));
  q.push(mc("medium", "Solve $4x^2-9=0$.", ["$\\pm\\tfrac32$", "$\\pm3$", "$\\pm\\tfrac23$", "$\\pm9$"], 0));
  q.push(ms("medium", "Solving $2x^2-7x+3=0$:", ["$(2x-1)(x-3)=0$", "$x=\\tfrac12$", "$x=3$", "$x=2$"], [0, 1, 2]));
  q.push(ms("medium", "Solving $x^2-8x=0$:", ["common factor $x$", "$x(x-8)=0$", "$x=0,8$", "$x=8$ only"], [0, 1, 2]));
  q.push(ms("medium", "$4x^2-9=0$:", ["difference of squares", "$(2x-3)(2x+3)=0$", "$x=\\pm\\tfrac32$", "$x=\\pm3$"], [0, 1, 2]));
  q.push(ms("medium", "Checking solutions:", ["substitute back", "both should give 0", "verify", "skip checking"], [0, 1, 2]));
  q.push(tf("medium", "$2x^2-7x+3=0$ gives $x=\\tfrac12,3$.", true));
  q.push(tf("medium", "$x^2-8x=0$ gives $x=0,8$.", true));
  q.push(tf("medium", "$4x^2-9=0$ gives $x=\\pm3$.", false));
  q.push(fill("medium", "Solve $3x^2-5x-2=0$.", ["2,-1/3", "2,-0.333"]));
  q.push(fill("medium", "Solve $x^2+7x+10=0$.", ["-2,-5", "-5,-2"]));
  q.push(fill("medium", "Solve $x^2-8x=0$.", ["0,8", "8,0"]));
  q.push(num("medium", "Larger solution of $2x^2-7x+3=0$.", 3, 0));
  q.push(num("medium", "Larger solution of $3x^2-5x-2=0$.", 2, 0));
  q.push(num("medium", "Nonzero solution of $x^2-8x=0$.", 8, 0));
  q.push(match("medium", "Match each to its solutions.", ["$2x^2-7x+3=0$", "$x^2-8x=0$", "$4x^2-9=0$"], ["$\\tfrac12,3$", "$0,8$", "$\\pm\\tfrac32$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $2x^2-x-6=0$.", ["$2,-\\tfrac32$", "$-2,\\tfrac32$", "$2,\\tfrac32$", "$-2,-\\tfrac32$"], 0));
  q.push(mc("hard", "Solve $6x^2+x-2=0$.", ["$\\tfrac12,-\\tfrac23$", "$-\\tfrac12,\\tfrac23$", "$2,-3$", "$\\tfrac23,-\\tfrac12$"], 0));
  q.push(mc("hard", "A rectangle satisfies $x^2+5x=24$. Find the positive $x$.", ["$3$", "$8$", "$4$", "$24$"], 0));
  q.push(mc("hard", "Solve $x^2=6x-9$.", ["$3$", "$\\pm3$", "$3,6$", "$9$"], 0));
  q.push(mc("hard", "Solve $(x-2)(x+5)=8$.", ["$3,-6$", "$2,-5$", "$8,1$", "$-3,6$"], 0));
  q.push(ms("hard", "Solving $2x^2-x-6=0$:", ["$(2x+3)(x-2)=0$", "$x=2$", "$x=-\\tfrac32$", "$x=3$"], [0, 1, 2]));
  q.push(ms("hard", "Equations not set to 0:", ["rearrange first", "$x^2=6x-9\\to x^2-6x+9=0$", "then factor", "factor as is"], [0, 1, 2]));
  q.push(ms("hard", "$(x-2)(x+5)=8$:", ["expand first", "$x^2+3x-10=8$", "$x^2+3x-18=0$", "set each factor to 8"], [0, 1, 2]));
  q.push(ms("hard", "Word problems:", ["set up the equation", "move all to one side", "factor & solve", "reject invalid roots"], [0, 1, 2]));
  q.push(tf("hard", "$2x^2-x-6=0$ gives $x=2,-\\tfrac32$.", true));
  q.push(tf("hard", "$x^2=6x-9$ has the double root $x=3$.", true));
  q.push(tf("hard", "You can solve $(x-2)(x+5)=8$ by $x-2=8$ or $x+5=8$.", false));
  q.push(fill("hard", "Solve $2x^2-x-6=0$.", ["2,-3/2", "2,-1.5"]));
  q.push(fill("hard", "Solve $x^2=6x-9$.", ["3"]));
  q.push(fill("hard", "Solve $(x-2)(x+5)=8$.", ["3,-6", "-6,3"]));
  q.push(num("hard", "Positive solution of $2x^2-x-6=0$.", 2, 0));
  q.push(num("hard", "Double root of $x^2-6x+9=0$.", 3, 0));
  q.push(num("hard", "Positive solution of $x^2+5x-24=0$.", 3, 0));
  q.push(order("hard", "Order the steps to solve $x^2=6x-9$.", ["Rearrange: $x^2-6x+9=0$", "Factor: $(x-3)^2=0$", "Set $x-3=0$", "$x=3$"]));
  q.push(match("hard", "Match each equation to its solutions.", ["$2x^2-x-6=0$", "$x^2=6x-9$", "$(x-2)(x+5)=8$"], ["$2,-\\tfrac32$", "$3$", "$3,-6$"], [0, 1, 2]));
  return q;
}

// ── 1.4 The Quadratic Formula & the Discriminant ─────────────
function g14() {
  const q = [];
  q.push(mc("easy", "The quadratic formula is $x=$", ["$\\dfrac{-b\\pm\\sqrt{b^2-4ac}}{2a}$", "$\\dfrac{b\\pm\\sqrt{b^2-4ac}}{2a}$", "$\\dfrac{-b\\pm\\sqrt{b^2+4ac}}{2a}$", "$-\\dfrac{b}{2a}$"], 0));
  q.push(mc("easy", "The discriminant is:", ["$b^2-4ac$", "$b^2+4ac$", "$-b/2a$", "$\\sqrt{b^2-4ac}$"], 0));
  q.push(mc("easy", "In $x^2-4x+1$, $a,b,c=$", ["$1,-4,1$", "$1,4,1$", "$0,-4,1$", "$1,-4,0$"], 0));
  q.push(mc("easy", "If $D>0$, the number of real roots is:", ["$2$", "$1$", "$0$", "$3$"], 0));
  q.push(mc("easy", "If $D=0$, the number of real roots is:", ["$1$", "$2$", "$0$", "$3$"], 0));
  q.push(mc("easy", "If $D<0$, the number of real roots is:", ["$0$", "$1$", "$2$", "$3$"], 0));
  q.push(ms("easy", "The quadratic formula:", ["solves any quadratic", "needs $a,b,c$", "$\\dfrac{-b\\pm\\sqrt{b^2-4ac}}{2a}$", "needs only $b$"], [0, 1, 2]));
  q.push(ms("easy", "Discriminant $b^2-4ac$:", ["$>0$ two roots", "$=0$ one", "$<0$ none", "always positive"], [0, 1, 2]));
  q.push(ms("easy", "Identifying $a,b,c$:", ["from $ax^2+bx+c$", "include signs", "$x^2-4x+1$: $1,-4,1$", "ignore signs"], [0, 1, 2]));
  q.push(ms("easy", "When to use the formula:", ["when factoring fails", "it always works", "for any quadratic", "never"], [0, 1, 2]));
  q.push(tf("easy", "The discriminant is $b^2-4ac$.", true));
  q.push(tf("easy", "$D<0$ means two real roots.", false));
  q.push(tf("easy", "The quadratic formula solves any quadratic.", true));
  q.push(fill("easy", "Discriminant of $x^2-4x+4$.", ["0"]));
  q.push(fill("easy", "Discriminant of $x^2+x+1$.", ["-3"]));
  q.push(fill("easy", "Number of real roots if $D=25$.", ["2"]));
  q.push(num("easy", "Discriminant of $x^2-6x+9$.", 0, 0));
  q.push(num("easy", "Discriminant of $x^2-5x+6$.", 1, 0));
  q.push(num("easy", "Discriminant of $x^2+2x+5$.", -16, 0));
  q.push(match("easy", "Match each discriminant to the number of roots.", ["$D>0$", "$D=0$", "$D<0$"], ["two", "one", "none"], [0, 1, 2]));
  q.push(mc("medium", "Solve $x^2-4x+1=0$.", ["$2\\pm\\sqrt3$", "$2\\pm\\sqrt5$", "$4\\pm\\sqrt3$", "$1\\pm\\sqrt3$"], 0));
  q.push(mc("medium", "Solve $2x^2+3x-2=0$.", ["$\\tfrac12,-2$", "$-\\tfrac12,2$", "$2,-3$", "$\\tfrac13,-2$"], 0));
  q.push(mc("medium", "Solve $x^2+x-1=0$.", ["$\\dfrac{-1\\pm\\sqrt5}{2}$", "$\\dfrac{1\\pm\\sqrt5}{2}$", "$-1\\pm\\sqrt5$", "$\\dfrac{-1\\pm\\sqrt3}{2}$"], 0));
  q.push(mc("medium", "How many real roots has $x^2+2x+5=0$?", ["$0$", "$1$", "$2$", "$3$"], 0));
  q.push(mc("medium", "How many real roots has $x^2-6x+9=0$?", ["$1$", "$2$", "$0$", "$3$"], 0));
  q.push(mc("medium", "Solve $x^2-2x-1=0$.", ["$1\\pm\\sqrt2$", "$1\\pm\\sqrt3$", "$-1\\pm\\sqrt2$", "$2\\pm\\sqrt2$"], 0));
  q.push(ms("medium", "Quadratic formula on $x^2-4x+1$:", ["$a=1,b=-4,c=1$", "$D=12$", "$x=\\dfrac{4\\pm\\sqrt{12}}2$", "$x=2\\pm\\sqrt3$"], [0, 1, 2, 3]));
  q.push(ms("medium", "No real roots:", ["$D<0$", "$x^2+2x+5$: $D=-16$", "graph misses the x-axis", "one root"], [0, 1, 2]));
  q.push(ms("medium", "One root:", ["$D=0$", "a double root", "$x^2-6x+9$", "two roots"], [0, 1, 2]));
  q.push(ms("medium", "Simplifying $\\sqrt{12}$:", ["$=2\\sqrt3$", "factor out a square", "$\\sqrt{4\\cdot3}$", "$=12$"], [0, 1, 2]));
  q.push(tf("medium", "$x^2-4x+1=0$ gives $x=2\\pm\\sqrt3$.", true));
  q.push(tf("medium", "$x^2+2x+5=0$ has no real roots.", true));
  q.push(tf("medium", "$x^2-6x+9=0$ has two distinct roots.", false));
  q.push(fill("medium", "Solve $x^2-4x+1=0$.", ["2±√3", "2+√3,2-√3"]));
  q.push(fill("medium", "Solve $x^2-2x-1=0$.", ["1±√2", "1+√2,1-√2"]));
  q.push(fill("medium", "Number of real roots of $x^2+2x+5$.", ["0"]));
  q.push(num("medium", "Discriminant of $2x^2+3x-2$.", 25, 0));
  q.push(num("medium", "Larger solution of $2x^2+3x-2=0$ (decimal).", 0.5, 0.01));
  q.push(num("medium", "Discriminant of $x^2-2x-1$.", 8, 0));
  q.push(match("medium", "Match each equation to its solutions.", ["$x^2-4x+1=0$", "$x^2-2x-1=0$", "$2x^2+3x-2=0$"], ["$2\\pm\\sqrt3$", "$1\\pm\\sqrt2$", "$\\tfrac12,-2$"], [0, 1, 2]));
  q.push(mc("hard", "Solve $2x^2-3x-1=0$.", ["$\\dfrac{3\\pm\\sqrt{17}}{4}$", "$\\dfrac{-3\\pm\\sqrt{17}}{4}$", "$\\dfrac{3\\pm\\sqrt5}{4}$", "$\\dfrac{3\\pm17}{4}$"], 0));
  q.push(mc("hard", "Solve $x^2-8x+13=0$.", ["$4\\pm\\sqrt3$", "$4\\pm\\sqrt5$", "$8\\pm\\sqrt3$", "$4\\pm3$"], 0));
  q.push(mc("hard", "For what $k$ does $x^2-6x+k=0$ have one root?", ["$9$", "$6$", "$3$", "$36$"], 0));
  q.push(mc("hard", "For what $k$ does $x^2+kx+9=0$ have one root?", ["$\\pm6$", "$6$", "$9$", "$\\pm3$"], 0));
  q.push(mc("hard", "$x^2-kx+4=0$ has two distinct roots when:", ["$k^2>16$", "$k^2<16$", "$k=4$", "$k>4$"], 0));
  q.push(ms("hard", "Solving $2x^2-3x-1=0$:", ["$a=2,b=-3,c=-1$", "$D=17$", "$x=\\dfrac{3\\pm\\sqrt{17}}{4}$", "$x=\\dfrac{-3\\pm\\sqrt{17}}{4}$"], [0, 1, 2]));
  q.push(ms("hard", "One-root condition:", ["$D=0$", "$x^2-6x+k$: $36-4k=0$", "$k=9$", "$k=6$"], [0, 1, 2]));
  q.push(ms("hard", "$x^2+kx+9=0$ has one root:", ["$k^2-36=0$", "$k=\\pm6$", "two values", "$k=9$"], [0, 1, 2]));
  q.push(ms("hard", "Two distinct roots:", ["$D>0$", "$x^2-kx+4$: $k^2-16>0$", "$k^2>16$", "$k^2<16$"], [0, 1, 2]));
  q.push(tf("hard", "$x^2-8x+13=0$ gives $x=4\\pm\\sqrt3$.", true));
  q.push(tf("hard", "$x^2-6x+k=0$ has one root when $k=9$.", true));
  q.push(tf("hard", "$x^2+kx+9=0$ has one root only when $k=6$.", false));
  q.push(fill("hard", "Solve $x^2-8x+13=0$.", ["4±√3", "4+√3,4-√3"]));
  q.push(fill("hard", "$k$ for one root of $x^2-6x+k=0$.", ["9"]));
  q.push(fill("hard", "Values of $k$ for one root of $x^2+kx+9=0$.", ["±6", "6,-6", "-6,6"]));
  q.push(num("hard", "Discriminant of $2x^2-3x-1$.", 17, 0));
  q.push(num("hard", "$k$ for one root of $x^2-6x+k=0$.", 9, 0));
  q.push(num("hard", "Positive $k$ for one root of $x^2+kx+9=0$.", 6, 0));
  q.push(order("hard", "Order the steps to solve $2x^2-3x-1=0$.", ["Identify $a=2,b=-3,c=-1$", "$D=9+8=17$", "$x=\\dfrac{3\\pm\\sqrt{17}}{4}$", "State both roots"]));
  q.push(match("hard", "Match each to its value.", ["$D$ of $2x^2-3x-1$", "$k$ for one root of $x^2-6x+k$", "$D$ of $x^2-8x+13$"], ["$17$", "$9$", "$12$"], [0, 1, 2]));
  return q;
}

// ── 1.5 Roots and x-Intercepts ───────────────────────────────
function g15() {
  const q = [];
  q.push(mc("easy", "The real roots of $ax^2+bx+c=0$ are the:", ["x-intercepts", "y-intercepts", "vertex", "slope"], 0));
  q.push(mc("easy", "x-intercepts of $y=(x-2)(x+5)$:", ["$2,-5$", "$-2,5$", "$2,5$", "$-2,-5$"], 0));
  q.push(mc("easy", "x-intercepts of $y=x^2-9$:", ["$\\pm3$", "$\\pm9$", "$3$", "$0$"], 0));
  q.push(mc("easy", "If $D<0$, the parabola:", ["does not cross the x-axis", "crosses twice", "touches once", "is a line"], 0));
  q.push(mc("easy", "x-intercept(s) of $y=(x-3)^2$:", ["$3$", "$\\pm3$", "$9$", "none"], 0));
  q.push(mc("easy", "A double root means the parabola:", ["touches the x-axis", "crosses twice", "misses it", "is linear"], 0));
  q.push(ms("easy", "Roots and intercepts:", ["real roots = x-intercepts", "both where $y=0$", "found by factoring or graphing", "y-intercepts"], [0, 1, 2]));
  q.push(ms("easy", "Number of x-intercepts:", ["$D>0$ two", "$D=0$ one", "$D<0$ none", "always two"], [0, 1, 2]));
  q.push(ms("easy", "$y=x^2-9$:", ["$(x-3)(x+3)$", "x-intercepts $\\pm3$", "crosses twice", "one intercept"], [0, 1, 2]));
  q.push(ms("easy", "A double root:", ["$D=0$", "vertex on the x-axis", "just touches", "crosses twice"], [0, 1, 2]));
  q.push(tf("easy", "Real roots are the x-intercepts of the parabola.", true));
  q.push(tf("easy", "If $D<0$ the graph crosses the x-axis twice.", false));
  q.push(tf("easy", "$y=(x-3)^2$ has one x-intercept.", true));
  q.push(fill("easy", "x-intercepts of $y=(x-4)(x+1)$.", ["4,-1", "-1,4"]));
  q.push(fill("easy", "x-intercepts of $y=x^2-25$.", ["±5", "5,-5", "-5,5"]));
  q.push(fill("easy", "Number of x-intercepts if $D=0$.", ["1", "one"]));
  q.push(num("easy", "Larger x-intercept of $y=x^2-9$.", 3, 0));
  q.push(num("easy", "Number of x-intercepts of $y=x^2+1$.", 0, 0));
  q.push(num("easy", "The single x-intercept of $y=(x-7)^2$.", 7, 0));
  q.push(match("easy", "Match each to its number of x-intercepts.", ["$y=x^2-9$", "$y=x^2+1$", "$y=(x-3)^2$"], ["two", "none", "one"], [0, 1, 2]));
  q.push(mc("medium", "x-intercepts of $y=x^2-4x+3$:", ["$1,3$", "$-1,-3$", "$2,3$", "$0,3$"], 0));
  q.push(mc("medium", "How many x-intercepts has $y=x^2-2x+5$?", ["$0$", "$1$", "$2$", "$3$"], 0));
  q.push(mc("medium", "How many x-intercepts has $y=4x^2-12x+9$?", ["$1$", "$2$", "$0$", "$3$"], 0));
  q.push(mc("medium", "x-intercepts of $y=x^2+x-12$:", ["$3,-4$", "$-3,4$", "$3,4$", "$-3,-4$"], 0));
  q.push(mc("medium", "How many x-intercepts has $y=2x^2-3x-5$?", ["$2$", "$1$", "$0$", "$3$"], 0));
  q.push(mc("medium", "x-intercepts of $y=2x^2-5x-3$:", ["$3,-\\tfrac12$", "$-3,\\tfrac12$", "$3,\\tfrac12$", "$-3,-\\tfrac12$"], 0));
  q.push(ms("medium", "Finding x-intercepts of $y=x^2-4x+3$:", ["set $y=0$", "factor $(x-1)(x-3)$", "$x=1,3$", "$x=4,3$"], [0, 1, 2]));
  q.push(ms("medium", "Counting via $D$:", ["$D=b^2-4ac$", "$>0$ two", "$=0$ one", "$<0$ none"], [0, 1, 2, 3]));
  q.push(ms("medium", "$y=4x^2-12x+9$:", ["$(2x-3)^2$", "$D=0$", "one x-intercept", "two"], [0, 1, 2]));
  q.push(ms("medium", "No x-intercepts:", ["$D<0$", "$y=x^2-2x+5$", "graph above the axis", "crosses twice"], [0, 1, 2]));
  q.push(tf("medium", "$y=x^2-4x+3$ has x-intercepts 1 and 3.", true));
  q.push(tf("medium", "$y=4x^2-12x+9$ has one x-intercept.", true));
  q.push(tf("medium", "$y=x^2-2x+5$ has two x-intercepts.", false));
  q.push(fill("medium", "x-intercepts of $y=x^2-4x+3$.", ["1,3", "3,1"]));
  q.push(fill("medium", "Number of x-intercepts of $y=x^2-2x+5$.", ["0"]));
  q.push(fill("medium", "x-intercepts of $y=x^2+x-12$.", ["3,-4", "-4,3"]));
  q.push(num("medium", "Number of x-intercepts of $y=2x^2-3x-5$.", 2, 0));
  q.push(num("medium", "Larger x-intercept of $y=x^2-4x+3$.", 3, 0));
  q.push(num("medium", "Discriminant of $y=4x^2-12x+9$.", 0, 0));
  q.push(match("medium", "Match each to its number of x-intercepts.", ["$x^2-4x+3$", "$x^2-2x+5$", "$4x^2-12x+9$"], ["two", "none", "one"], [0, 1, 2]));
  q.push(mc("hard", "Profit $P=-5x^2+550x-5000$. For what $x$ is $P=0$?", ["$10$ or $100$", "$5$ or $50$", "$10$ only", "$50$ or $100$"], 0));
  q.push(mc("hard", "A ball's height $h=-5t^2+20t$. When is $h=0$?", ["$t=0$ or $4$", "$t=4$", "$t=2$", "$t=20$"], 0));
  q.push(mc("hard", "$y=x^2-6x+k$ touches the x-axis when $k=$", ["$9$", "$6$", "$3$", "$36$"], 0));
  q.push(mc("hard", "A parabola has x-intercepts $2$ and $-3$. A possible equation is:", ["$y=(x-2)(x+3)$", "$y=(x+2)(x-3)$", "$y=(x-2)(x-3)$", "$y=x^2+6$"], 0));
  q.push(mc("hard", "$y=x^2+bx+9$ touches the x-axis. Then $b=$", ["$\\pm6$", "$6$", "$9$", "$\\pm3$"], 0));
  q.push(ms("hard", "Profit $P=-5x^2+550x-5000=0$:", ["factor $-5(x-10)(x-100)$", "$x=10$ or $100$", "both make profit 0", "$x=550$"], [0, 1, 2]));
  q.push(ms("hard", "Ball height $h=-5t^2+20t$:", ["factor $-5t(t-4)$", "$t=0$ (start)", "$t=4$ (lands)", "$t=20$"], [0, 1, 2]));
  q.push(ms("hard", "Touching the x-axis:", ["$D=0$", "one x-intercept", "a double root", "two intercepts"], [0, 1, 2]));
  q.push(ms("hard", "Building from intercepts:", ["$y=a(x-r)(x-s)$", "$r,s$ are the roots", "$y=(x-2)(x+3)$ for $2,-3$", "add the roots"], [0, 1, 2]));
  q.push(tf("hard", "$P=-5x^2+550x-5000=0$ at $x=10$ and $x=100$.", true));
  q.push(tf("hard", "$y=x^2-6x+k$ touches the x-axis when $k=9$.", true));
  q.push(tf("hard", "A parabola with x-intercepts $2,-3$ is $y=(x-2)(x-3)$.", false));
  q.push(fill("hard", "Advertising values ($x$) giving $P=0$ for $P=-5x^2+550x-5000$.", ["10,100", "100,10"]));
  q.push(fill("hard", "Times the ball $h=-5t^2+20t$ is on the ground.", ["0,4", "4,0"]));
  q.push(fill("hard", "$k$ for which $y=x^2-6x+k$ touches the x-axis.", ["9"]));
  q.push(num("hard", "Larger advertising value giving $P=0$ ($P=-5x^2+550x-5000$).", 100, 0));
  q.push(num("hard", "Time the ball $h=-5t^2+20t$ lands ($t>0$).", 4, 0));
  q.push(num("hard", "$k$ for which $y=x^2-6x+k$ touches the x-axis.", 9, 0));
  q.push(order("hard", "Order the steps to find where $P=-5x^2+550x-5000=0$.", ["Factor out $-5$: $-5(x^2-110x+1000)$", "Factor: $-5(x-10)(x-100)$", "Set each factor to 0", "$x=10$ or $x=100$"]));
  q.push(match("hard", "Match each to its zeros.", ["$P=-5x^2+550x-5000$", "$h=-5t^2+20t$", "$y=x^2-6x+9$"], ["$10,100$", "$0,4$", "$3$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "1.1", gen: g11 },
  { code: "1.2", gen: g12 },
  { code: "1.3", gen: g13 },
  { code: "1.4", gen: g14 },
  { code: "1.5", gen: g15 },
];
