// MCF3M Unit 2 — Quadratic Functions: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 2.1 Functions, Function Notation, Domain & Range ─────────
function g21() {
  const q = [];
  q.push(mc("easy", "$f(x)=2x+3$ at $x=4$.", ["$11$", "$14$", "$10$", "$7$"], 0));
  q.push(mc("easy", "$f(x)=x^2-1$ at $x=3$.", ["$8$", "$5$", "$9$", "$10$"], 0));
  q.push(mc("easy", "Is $\\{(1,2),(2,4),(3,6)\\}$ a function?", ["yes", "no", "sometimes", "cannot tell"], 0));
  q.push(mc("easy", "$f(x)$ means:", ["the output at $x$", "$f$ times $x$", "the input", "the slope"], 0));
  q.push(mc("easy", "The domain of a quadratic is:", ["all real numbers", "$x\\ge0$", "$x\\ne0$", "$x>0$"], 0));
  q.push(mc("easy", "$f(x)=x^2$ at $x=-3$.", ["$9$", "$-9$", "$6$", "$-6$"], 0));
  q.push(ms("easy", "Functions:", ["each input one output", "pass the vertical-line test", "one-to-one or many-to-one", "one-to-many"], [0, 1, 2]));
  q.push(ms("easy", "For $f(x)=x^2-4$:", ["$f(2)=0$", "$f(0)=-4$", "$f(3)=5$", "$f(1)=4$"], [0, 1, 2]));
  q.push(ms("easy", "Domain & range of a quadratic:", ["domain all reals", "range from the vertex", "range is bounded", "range all reals"], [0, 1, 2]));
  q.push(ms("easy", "Function notation:", ["$f(x)$ is the output", "substitute for $x$", "not multiplication", "means $f\\cdot x$"], [0, 1, 2]));
  q.push(tf("easy", "$f(x)=x^2+1$ has domain all reals.", true));
  q.push(tf("easy", "$x=y^2$ is a function.", false));
  q.push(tf("easy", "$f(3)=4$ for $f(x)=x+1$.", true));
  q.push(fill("easy", "$f(x)=3x-2$ at $x=5$.", ["13"]));
  q.push(fill("easy", "$f(x)=x^2+1$ at $x=4$.", ["17"]));
  q.push(fill("easy", "Range of $y=x^2-3$ (write like y>=-3).", ["y>=-3", "y \\ge -3", "y≥-3"]));
  q.push(num("easy", "$f(x)=2x^2$ at $x=3$.", 18, 0));
  q.push(num("easy", "$f(x)=4x-7$ at $x=2$.", 1, 0));
  q.push(num("easy", "$f(x)=x^2-2x$ at $x=5$.", 15, 0));
  q.push(match("easy", "Match each $f$ to $f(2)$.", ["$f(x)=x+3$", "$f(x)=2x$", "$f(x)=x^2$"], ["$5$", "$4$", "$4$"], [0, 1, 2]));
  q.push(mc("medium", "$f(x)=2x^2+3x-1$ at $x=2$.", ["$13$", "$9$", "$7$", "$15$"], 0));
  q.push(mc("medium", "$f(x)=2x^2+3x-1$ at $x=-1$.", ["$-2$", "$0$", "$4$", "$-4$"], 0));
  q.push(mc("medium", "Range of $y=-x^2+5$.", ["$y\\le5$", "$y\\ge5$", "$y\\le0$", "all reals"], 0));
  q.push(mc("medium", "Range of $y=(x-2)^2+1$.", ["$y\\ge1$", "$y\\ge2$", "$y\\ge0$", "$y\\le1$"], 0));
  q.push(mc("medium", "$r(s)=-10s^2+1500s$; $r(60)=$", ["$54000$", "$45000$", "$36000$", "$90000$"], 0));
  q.push(mc("medium", "For $f(x)=5-2x$, solve $f(x)=1$.", ["$2$", "$3$", "$-2$", "$\\tfrac12$"], 0));
  q.push(ms("medium", "For $f(x)=2x+1$:", ["$f(0)=1$", "$f(3)=7$", "$f(-1)=-1$", "$f(2)=6$"], [0, 1, 2]));
  q.push(ms("medium", "Range from the vertex:", ["minimum if $a>0$", "maximum if $a<0$", "$y\\ge k$ or $y\\le k$", "range all reals"], [0, 1, 2]));
  q.push(ms("medium", "Evaluating $r(60)$ for $-10s^2+1500s$:", ["$-10(3600)$", "$+90000$", "$=54000$", "$=45000$"], [0, 1, 2]));
  q.push(ms("medium", "A relation is a function if:", ["each input maps to one output", "it passes the vertical-line test", "it is not one-to-many", "it is one-to-many"], [0, 1, 2]));
  q.push(tf("medium", "$f(-1)=-2$ for $f(x)=2x^2+3x-1$.", true));
  q.push(tf("medium", "$y=(x-2)^2+1$ has range $y\\ge1$.", true));
  q.push(tf("medium", "$y=-x^2+5$ has range $y\\ge5$.", false));
  q.push(fill("medium", "$f(x)=2x^2+3x-1$ at $x=2$.", ["13"]));
  q.push(fill("medium", "Range of $y=-x^2+5$ (write like y<=5).", ["y<=5", "y \\le 5", "y≤5"]));
  q.push(fill("medium", "$f(x)=x^2-5x$ at $x=-2$.", ["14"]));
  q.push(num("medium", "$f(x)=2x^2+3x-1$ at $x=-1$.", -2, 0));
  q.push(num("medium", "$r(75)$ for $r(s)=-10s^2+1500s$.", 56250, 0));
  q.push(num("medium", "Solve $2x-6=0$.", 3, 0));
  q.push(match("medium", "Match each to its range.", ["$x^2+1$", "$-x^2+5$", "$(x-2)^2$"], ["$y\\ge1$", "$y\\le5$", "$y\\ge0$"], [0, 1, 2]));
  q.push(mc("hard", "$f(x)=x^2-3x$; $f(a+1)=$", ["$a^2-a-2$", "$a^2-3a$", "$a^2+a$", "$a^2-2$"], 0));
  q.push(mc("hard", "Range of $f(x)=x^2-6x+5$.", ["$y\\ge-4$", "$y\\ge5$", "$y\\le-4$", "all reals"], 0));
  q.push(mc("hard", "$r(s)=-10s^2+1500s$ is maximized at $s=$", ["$75$", "$60$", "$150$", "$1500$"], 0));
  q.push(mc("hard", "$f(x)=x^2$; for what $x$ is $f(x)=49$?", ["$\\pm7$", "$7$", "$24.5$", "$\\pm49$"], 0));
  q.push(mc("hard", "If $f(2)=7$ and $f(x)=ax^2-1$, then $a=$", ["$2$", "$3$", "$4$", "$1$"], 0));
  q.push(ms("hard", "For $f(x)=x^2-3x$:", ["$f(0)=0$", "$f(3)=0$", "$f(1)=-2$", "$f(2)=2$"], [0, 1, 2]));
  q.push(ms("hard", "Range of $x^2-6x+5$:", ["vertex $(3,-4)$", "opens up", "$y\\ge-4$", "$y\\le-4$"], [0, 1, 2]));
  q.push(ms("hard", "Max revenue of $-10s^2+1500s$:", ["at $s=-\\tfrac{b}{2a}$", "$s=75$", "then compute $r(75)$", "$s=1500$"], [0, 1, 2]));
  q.push(ms("hard", "Domain/range in context:", ["physical limits apply", "e.g. time $\\ge0$", "the range may be restricted", "no limits"], [0, 1, 2]));
  q.push(tf("hard", "$f(x)=x^2-3x$ gives $f(a+1)=a^2-a-2$.", true));
  q.push(tf("hard", "The range of $x^2-6x+5$ is $y\\ge-4$.", true));
  q.push(tf("hard", "$-10s^2+1500s$ is maximized at $s=150$.", false));
  q.push(fill("hard", "$f(x)=x^2-3x$; $f(4)=$", ["4"]));
  q.push(fill("hard", "Range of $y=x^2-6x+5$ (write like y>=-4).", ["y>=-4", "y \\ge -4", "y≥-4"]));
  q.push(fill("hard", "$s$ that maximizes $r(s)=-10s^2+1500s$.", ["75"]));
  q.push(num("hard", "$f(x)=x^2-3x$ at $x=5$.", 10, 0));
  q.push(num("hard", "$s$ maximizing $-10s^2+1500s$.", 75, 0));
  q.push(num("hard", "$a$ if $f(2)=7$, $f(x)=ax^2-1$.", 2, 0));
  q.push(order("hard", "Order the steps to find the range of $y=x^2-6x+5$.", ["Find the vertex $x=3$", "$y=9-18+5=-4$", "Vertex $(3,-4)$, opens up", "Range $y\\ge-4$"]));
  q.push(match("hard", "Match each to its value ($f(x)=x^2-3x$).", ["$f(0)$", "$f(3)$", "$f(4)$"], ["$0$", "$0$", "$4$"], [0, 1, 2]));
  return q;
}

// ── 2.2 Transformations & Vertex Form ────────────────────────
function g22() {
  const q = [];
  q.push(mc("easy", "Vertex of $y=(x-3)^2+2$.", ["$(3,2)$", "$(-3,2)$", "$(3,-2)$", "$(2,3)$"], 0));
  q.push(mc("easy", "$y=x^2+4$ shifts:", ["up 4", "down 4", "right 4", "left 4"], 0));
  q.push(mc("easy", "$y=-x^2$ is:", ["a reflection in the $x$-axis", "a shift up", "a stretch", "a shift right"], 0));
  q.push(mc("easy", "$y=2x^2$ is:", ["a vertical stretch by 2", "a shift up 2", "a reflection", "a shift right"], 0));
  q.push(mc("easy", "Vertex of $y=(x+1)^2-5$.", ["$(-1,-5)$", "$(1,-5)$", "$(-1,5)$", "$(5,-1)$"], 0));
  q.push(mc("easy", "$y=(x-2)^2$ shifts:", ["right 2", "left 2", "up 2", "down 2"], 0));
  q.push(ms("easy", "In $a(x-h)^2+k$:", ["$a$ stretch/reflect", "$h$ horizontal", "$k$ vertical", "$a$ horizontal"], [0, 1, 2]));
  q.push(ms("easy", "$y=-2(x-3)^2+1$:", ["reflect", "stretch by 2", "right 3, up 1", "left 3"], [0, 1, 2]));
  q.push(ms("easy", "Vertex form:", ["vertex $(h,k)$", "$a<0$ opens down", "$k$ is the max/min", "vertex $(-h,k)$"], [0, 1, 2]));
  q.push(ms("easy", "Reflections:", ["$a<0$ over the $x$-axis", "flips the graph", "opens down", "shifts up"], [0, 1, 2]));
  q.push(tf("easy", "$y=(x-3)^2+2$ has vertex $(3,2)$.", true));
  q.push(tf("easy", "$y=x^2-5$ shifts up 5.", false));
  q.push(tf("easy", "$y=-x^2$ opens down.", true));
  q.push(fill("easy", "Vertex of $y=(x-4)^2+2$.", ["(4,2)", "4,2"]));
  q.push(fill("easy", "Vertex of $y=(x+1)^2-3$.", ["(-1,-3)", "-1,-3"]));
  q.push(fill("easy", "$y=(x+6)^2$ shifts (direction & amount).", ["left 6", "left6"]));
  q.push(num("easy", "$x$-coordinate of the vertex of $y=(x-7)^2+1$.", 7, 0));
  q.push(num("easy", "$y$-coordinate of the vertex of $y=x^2+9$.", 9, 0));
  q.push(num("easy", "Stretch factor in $y=5(x-1)^2$.", 5, 0));
  q.push(match("easy", "Match each to its vertex.", ["$(x-2)^2+3$", "$(x+1)^2-5$", "$x^2+4$"], ["$(2,3)$", "$(-1,-5)$", "$(0,4)$"], [0, 1, 2]));
  q.push(mc("medium", "Vertex of $y=-2(x+1)^2+5$.", ["$(-1,5)$", "$(1,5)$", "$(-1,-5)$", "$(5,-1)$"], 0));
  q.push(mc("medium", "Describe $y=3(x-2)^2$ from $y=x^2$.", ["stretch 3, right 2", "stretch 3, left 2", "reflect, right 2", "compress, right 2"], 0));
  q.push(mc("medium", "Max value of $y=-(x-2)^2+3$.", ["$3$", "$2$", "$-3$", "$0$"], 0));
  q.push(mc("medium", "Write $y=x^2$ shifted right 5 and down 4.", ["$y=(x-5)^2-4$", "$y=(x+5)^2-4$", "$y=(x-5)^2+4$", "$y=(x-4)^2-5$"], 0));
  q.push(mc("medium", "Vertex of $y=(x+4)^2-2$.", ["$(-4,-2)$", "$(4,-2)$", "$(-4,2)$", "$(4,2)$"], 0));
  q.push(mc("medium", "Which opens down?", ["$y=-3(x-1)^2$", "$y=3(x-1)^2$", "$y=(x-1)^2+2$", "$y=x^2$"], 0));
  q.push(ms("medium", "For $y=-2(x+1)^2+5$:", ["reflect", "stretch by 2", "left 1", "up 5"], [0, 1, 2, 3]));
  q.push(ms("medium", "Reading $a(x-h)^2+k$:", ["vertex $(h,k)$", "$a<0$ opens down", "$k$ is the max/min", "vertex $(h,-k)$"], [0, 1, 2]));
  q.push(ms("medium", "Writing from a description:", ["$h$ for horizontal", "$k$ for vertical", "$a$ for stretch/reflect", "ignore $a$"], [0, 1, 2]));
  q.push(ms("medium", "Max vs min from $a$:", ["$a>0$ minimum", "$a<0$ maximum", "at the vertex", "always minimum"], [0, 1, 2]));
  q.push(tf("medium", "$y=-2(x+1)^2+5$ has vertex $(-1,5)$.", true));
  q.push(tf("medium", "$y=(x-4)^2+6$ has minimum 6.", true));
  q.push(tf("medium", "$y=3(x-2)^2$ shifts left 2.", false));
  q.push(fill("medium", "Vertex of $y=-2(x+1)^2+5$.", ["(-1,5)", "-1,5"]));
  q.push(fill("medium", "Max value of $y=-(x-2)^2+3$.", ["3"]));
  q.push(fill("medium", "Vertex of $y=(x+4)^2-2$.", ["(-4,-2)", "-4,-2"]));
  q.push(num("medium", "$y$-coordinate of the vertex of $y=(x-1)^2-7$.", -7, 0));
  q.push(num("medium", "$x$-coordinate of the vertex of $y=3(x-5)^2+2$.", 5, 0));
  q.push(num("medium", "Max value of $y=-(x+1)^2+10$.", 10, 0));
  q.push(match("medium", "Match each to its vertex.", ["$-2(x+1)^2+5$", "$(x+4)^2-2$", "$3(x-5)^2+2$"], ["$(-1,5)$", "$(-4,-2)$", "$(5,2)$"], [0, 1, 2]));
  q.push(mc("hard", "A parabola has vertex $(2,-3)$ and passes $(0,5)$. Its $a=$", ["$2$", "$1$", "$-2$", "$4$"], 0));
  q.push(mc("hard", "$(1,1)$ on $y=x^2$ maps to which point on $y=(x-3)^2$?", ["$(4,1)$", "$(-2,1)$", "$(1,4)$", "$(4,-1)$"], 0));
  q.push(mc("hard", "$y=x^2$ stretched by 3 then down 4:", ["$y=3x^2-4$", "$y=3(x-4)^2$", "$y=3x^2+4$", "$y=x^2-12$"], 0));
  q.push(mc("hard", "Vertex and max of $y=-2(x-3)^2+8$:", ["$(3,8)$, max 8", "$(3,8)$, min 8", "$(-3,8)$, max 8", "$(3,-8)$, max -8"], 0));
  q.push(mc("hard", "Which has vertex $(-2,5)$ and opens down?", ["$y=-(x+2)^2+5$", "$y=-(x-2)^2+5$", "$y=(x+2)^2+5$", "$y=-(x+2)^2-5$"], 0));
  q.push(ms("hard", "Finding $a$ from vertex $(2,-3)$, point $(0,5)$:", ["$y=a(x-2)^2-3$", "$5=4a-3$", "$a=2$", "$a=1$"], [0, 1, 2]));
  q.push(ms("hard", "Mapping a point under $y=(x-3)^2$:", ["$x$ shifts $+3$", "$(1,1)\\to(4,1)$", "horizontal shift right", "$y$ changes"], [0, 1, 2]));
  q.push(ms("hard", "Building an equation:", ["vertex gives $h,k$", "$a$ from another point", "$y=a(x-h)^2+k$", "ignore $a$"], [0, 1, 2]));
  q.push(ms("hard", "For $y=-2(x-3)^2+8$:", ["vertex $(3,8)$", "opens down", "max 8", "min 8"], [0, 1, 2]));
  q.push(tf("hard", "A parabola with vertex $(2,-3)$ through $(0,5)$ has $a=2$.", true));
  q.push(tf("hard", "$y=-(x+2)^2+5$ has vertex $(-2,5)$ and opens down.", true));
  q.push(tf("hard", "$(1,1)$ on $y=x^2$ maps to $(1,4)$ on $y=(x-3)^2$.", false));
  q.push(fill("hard", "$a$ for vertex $(2,-3)$ through $(0,5)$.", ["2"]));
  q.push(fill("hard", "New $x$ of $(1,1)$ under $y=(x-3)^2$.", ["4"]));
  q.push(fill("hard", "Equation with vertex $(-2,5)$ opening down.", ["-(x+2)^2+5", "y=-(x+2)^2+5"]));
  q.push(num("hard", "$a$ for vertex $(2,-3)$ through $(0,5)$.", 2, 0));
  q.push(num("hard", "Max value of $y=-2(x-3)^2+8$.", 8, 0));
  q.push(num("hard", "New $x$-coordinate of $(1,1)$ under $y=(x-3)^2$.", 4, 0));
  q.push(order("hard", "Order the steps to find $a$ for a parabola with vertex $(2,-3)$ through $(0,5)$.", ["Write $y=a(x-2)^2-3$", "Substitute $(0,5)$: $5=4a-3$", "$4a=8$", "$a=2$"]));
  q.push(match("hard", "Match each parabola to its vertex.", ["$-2(x-3)^2+8$", "$(x+4)^2-2$", "$-(x+2)^2+5$"], ["$(3,8)$", "$(-4,-2)$", "$(-2,5)$"], [0, 1, 2]));
  return q;
}

// ── 2.3 Completing the Square ────────────────────────────────
function g23() {
  const q = [];
  q.push(mc("easy", "$x^2+6x+5$ =", ["$(x+3)^2-4$", "$(x+3)^2+4$", "$(x-3)^2-4$", "$(x+6)^2+5$"], 0));
  q.push(mc("easy", "$x^2-4x+1$ =", ["$(x-2)^2-3$", "$(x-2)^2+3$", "$(x+2)^2-3$", "$(x-4)^2+1$"], 0));
  q.push(mc("easy", "To complete $x^2+bx$, add:", ["$(b/2)^2$", "$b/2$", "$b^2$", "$2b$"], 0));
  q.push(mc("easy", "Vertex of $(x-3)^2-4$.", ["$(3,-4)$", "$(-3,-4)$", "$(3,4)$", "$(4,3)$"], 0));
  q.push(mc("easy", "$x^2+8x+10$ =", ["$(x+4)^2-6$", "$(x+4)^2+6$", "$(x-4)^2-6$", "$(x+8)^2+10$"], 0));
  q.push(mc("easy", "Completing the square gives:", ["vertex form", "factored form", "standard form", "slope form"], 0));
  q.push(ms("easy", "Method:", ["half the $x$-coefficient", "square it", "add & subtract", "double it"], [0, 1, 2]));
  q.push(ms("easy", "From $x^2+6x+5$:", ["half of 6 is 3", "$(x+3)^2$", "$-9+5=-4$", "$(x+3)^2-4$"], [0, 1, 2, 3]));
  q.push(ms("easy", "Completing the square reveals:", ["the vertex", "the max/min", "vertex form", "the slope"], [0, 1, 2]));
  q.push(ms("easy", "Perfect square:", ["$(x+3)^2=x^2+6x+9$", "first & last are squares", "middle $2ab$", "$(x+3)^2=x^2+9$"], [0, 1, 2]));
  q.push(tf("easy", "$x^2+6x+5=(x+3)^2-4$.", true));
  q.push(tf("easy", "To complete $x^2+bx$ you add $b$.", false));
  q.push(tf("easy", "$x^2-4x+1=(x-2)^2-3$.", true));
  q.push(fill("easy", "Complete the square: $x^2+2x-3$.", ["(x+1)^2-4"]));
  q.push(fill("easy", "Complete the square: $x^2-10x$.", ["(x-5)^2-25"]));
  q.push(fill("easy", "Complete the square: $x^2+8x+10$.", ["(x+4)^2-6"]));
  q.push(num("easy", "Number added to complete $x^2+6x$.", 9, 0));
  q.push(num("easy", "Vertex $x$ of $y=x^2-6x+5$.", 3, 0));
  q.push(num("easy", "Vertex $y$ of $y=x^2-6x+5$.", -4, 0));
  q.push(match("easy", "Match each to vertex form.", ["$x^2+6x+5$", "$x^2-4x+1$", "$x^2+8x+10$"], ["$(x+3)^2-4$", "$(x-2)^2-3$", "$(x+4)^2-6$"], [0, 1, 2]));
  q.push(mc("medium", "Vertex of $y=x^2-6x+5$.", ["$(3,-4)$", "$(-3,-4)$", "$(3,4)$", "$(6,5)$"], 0));
  q.push(mc("medium", "$2x^2-12x+5$ =", ["$2(x-3)^2-13$", "$2(x-3)^2+13$", "$2(x-6)^2-13$", "$(x-3)^2-13$"], 0));
  q.push(mc("medium", "Standard form of $(x-1)^2+4$.", ["$x^2-2x+5$", "$x^2-2x+4$", "$x^2+2x+5$", "$x^2-1+4$"], 0));
  q.push(mc("medium", "Vertex of $y=x^2+4x+1$.", ["$(-2,-3)$", "$(2,-3)$", "$(-2,3)$", "$(4,1)$"], 0));
  q.push(mc("medium", "$2x^2+8x+3$ =", ["$2(x+2)^2-5$", "$2(x+2)^2+5$", "$2(x+4)^2-5$", "$(x+2)^2-5$"], 0));
  q.push(mc("medium", "Min of $y=x^2-6x+5$.", ["$-4$", "$5$", "$3$", "$-9$"], 0));
  q.push(ms("medium", "Completing $2x^2-12x+5$:", ["factor 2 from the $x$-terms", "$2(x^2-6x)+5$", "$2((x-3)^2-9)+5$", "$2(x-3)^2-13$"], [0, 1, 2, 3]));
  q.push(ms("medium", "Vertex from vertex form:", ["$a(x-h)^2+k$", "vertex $(h,k)$", "$k$ is min/max", "vertex $(-h,k)$"], [0, 1, 2]));
  q.push(ms("medium", "Expanding back:", ["check your work", "$(x-1)^2+4=x^2-2x+5$", "matches standard form", "always different"], [0, 1, 2]));
  q.push(ms("medium", "Leading coefficient:", ["factor $a$ first", "from the $x^2$ and $x$ terms", "not the constant", "factor everything"], [0, 1, 2]));
  q.push(tf("medium", "$2x^2-12x+5=2(x-3)^2-13$.", true));
  q.push(tf("medium", "$(x-1)^2+4$ expands to $x^2-2x+5$.", true));
  q.push(tf("medium", "$y=x^2+4x+1$ has vertex $(2,-3)$.", false));
  q.push(fill("medium", "Vertex of $y=x^2-6x+5$.", ["(3,-4)", "3,-4"]));
  q.push(fill("medium", "Complete the square: $2x^2-8x+3$.", ["2(x-2)^2-5"]));
  q.push(fill("medium", "Standard form of $(x+3)^2-2$.", ["x^2+6x+7", "x²+6x+7"]));
  q.push(num("medium", "Vertex $x$ of $y=2x^2-12x+5$.", 3, 0));
  q.push(num("medium", "Vertex $y$ of $y=2x^2-12x+5$.", -13, 0));
  q.push(num("medium", "Min of $y=x^2+4x+1$.", -3, 0));
  q.push(match("medium", "Match each to its vertex.", ["$x^2-6x+5$", "$x^2+4x+1$", "$2x^2-12x+5$"], ["$(3,-4)$", "$(-2,-3)$", "$(3,-13)$"], [0, 1, 2]));
  q.push(mc("hard", "Complete the square: $-x^2+4x+1$.", ["$-(x-2)^2+5$", "$-(x-2)^2-5$", "$-(x+2)^2+5$", "$(x-2)^2+5$"], 0));
  q.push(mc("hard", "Vertex of $y=3x^2-12x+1$.", ["$(2,-11)$", "$(2,11)$", "$(-2,-11)$", "$(2,-13)$"], 0));
  q.push(mc("hard", "Min value of $y=2x^2+4x-3$.", ["$-5$", "$-3$", "$-1$", "$1$"], 0));
  q.push(mc("hard", "Min value of $y=x^2-6x+11$.", ["$2$", "$11$", "$-2$", "$3$"], 0));
  q.push(mc("hard", "For $y=ax^2+bx+c$, the vertex $x$ is:", ["$-\\dfrac{b}{2a}$", "$\\dfrac{b}{2a}$", "$-\\dfrac{b}{a}$", "$\\dfrac{c}{a}$"], 0));
  q.push(ms("hard", "Completing $-x^2+4x+1$:", ["factor $-1$: $-(x^2-4x)+1$", "$-((x-2)^2-4)+1$", "$-(x-2)^2+5$", "vertex $(2,5)$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Vertex of $3x^2-12x+1$:", ["$x=-\\tfrac{b}{2a}=2$", "$y=3(4)-24+1=-11$", "vertex $(2,-11)$", "$x=-2$"], [0, 1, 2]));
  q.push(ms("hard", "Negative leading coefficient:", ["opens down", "has a maximum", "factor $-1$ carefully", "has a minimum"], [0, 1, 2]));
  q.push(ms("hard", "Quick vertex $x$:", ["$x=-\\tfrac{b}{2a}$", "then substitute", "gives the vertex", "not needed"], [0, 1, 2]));
  q.push(tf("hard", "$-x^2+4x+1=-(x-2)^2+5$.", true));
  q.push(tf("hard", "$y=x^2-6x+11$ has minimum value 2.", true));
  q.push(tf("hard", "The vertex $x$ of $y=ax^2+bx+c$ is $\\tfrac{b}{2a}$.", false));
  q.push(fill("hard", "Complete the square: $-x^2+4x+1$.", ["-(x-2)^2+5"]));
  q.push(fill("hard", "Vertex of $y=3x^2-12x+1$.", ["(2,-11)", "2,-11"]));
  q.push(fill("hard", "Min value of $y=2x^2+4x-3$.", ["-5"]));
  q.push(num("hard", "Vertex $x$ of $y=3x^2-12x+1$.", 2, 0));
  q.push(num("hard", "Min value of $y=x^2-6x+11$.", 2, 0));
  q.push(num("hard", "Min value of $y=2x^2+4x-3$.", -5, 0));
  q.push(order("hard", "Order the steps to complete the square for $-x^2+4x+1$.", ["Factor $-1$: $-(x^2-4x)+1$", "$-((x-2)^2-4)+1$", "Distribute: $-(x-2)^2+4+1$", "$-(x-2)^2+5$"]));
  q.push(match("hard", "Match each to its vertex.", ["$3x^2-12x+1$", "$2x^2+4x-3$", "$x^2-6x+11$"], ["$(2,-11)$", "$(-1,-5)$", "$(3,2)$"], [0, 1, 2]));
  return q;
}

// ── 2.4 Factored Form & Graphing ─────────────────────────────
function g24() {
  const q = [];
  q.push(mc("easy", "x-intercepts of $(x-1)(x-5)$.", ["$1,5$", "$-1,-5$", "$1,-5$", "$5$"], 0));
  q.push(mc("easy", "x-intercepts of $(x+2)(x-6)$.", ["$-2,6$", "$2,-6$", "$2,6$", "$-2,-6$"], 0));
  q.push(mc("easy", "Axis of symmetry of $y=(x-1)(x-5)$.", ["$x=3$", "$x=2$", "$x=6$", "$x=0$"], 0));
  q.push(mc("easy", "y-intercept of $y=(x-1)(x-5)$.", ["$5$", "$-5$", "$1$", "$6$"], 0));
  q.push(mc("easy", "To find x-intercepts, set:", ["each factor to 0", "$y$ to 1", "$x$ to 0", "$a$ to 0"], 0));
  q.push(mc("easy", "x-intercepts of $(x-4)(x+1)$.", ["$4,-1$", "$-4,1$", "$4,1$", "$-4,-1$"], 0));
  q.push(ms("easy", "From factored form:", ["x-intercepts from factors", "axis midway", "vertex on the axis", "y-int at $x=0$"], [0, 1, 2, 3]));
  q.push(ms("easy", "Axis of symmetry:", ["$x=\\tfrac{r+s}{2}$", "midway between intercepts", "through the vertex", "at $x=0$ always"], [0, 1, 2]));
  q.push(ms("easy", "y-intercept:", ["set $x=0$", "multiply the constants", "$(x-1)(x-5)\\to5$", "set $y=0$"], [0, 1, 2]));
  q.push(ms("easy", "Graphing:", ["plot the x-intercepts", "find the vertex", "sketch the parabola", "plot randomly"], [0, 1, 2]));
  q.push(tf("easy", "The x-intercepts of $(x-1)(x-5)$ are 1 and 5.", true));
  q.push(tf("easy", "The axis of symmetry of $(x-1)(x-5)$ is $x=2$.", false));
  q.push(tf("easy", "The y-intercept of $(x-1)(x-5)$ is 5.", true));
  q.push(fill("easy", "x-intercepts of $(x-2)(x-6)$.", ["2,6", "6,2"]));
  q.push(fill("easy", "Axis of symmetry of $(x-2)(x-6)$.", ["x=4", "4"]));
  q.push(fill("easy", "y-intercept of $(x+1)(x-5)$.", ["-5"]));
  q.push(num("easy", "Axis of symmetry $x=$ of $y=(x-2)(x-6)$.", 4, 0));
  q.push(num("easy", "y-intercept of $y=(x-3)(x+4)$.", -12, 0));
  q.push(num("easy", "Larger x-intercept of $(x+2)(x-6)$.", 6, 0));
  q.push(match("easy", "Match each to its x-intercepts.", ["$(x-1)(x-5)$", "$(x+2)(x-6)$", "$(x-4)(x+1)$"], ["$1,5$", "$-2,6$", "$4,-1$"], [0, 1, 2]));
  q.push(mc("medium", "Vertex of $y=(x-1)(x-5)$.", ["$(3,-4)$", "$(3,4)$", "$(-3,-4)$", "$(2,-4)$"], 0));
  q.push(mc("medium", "x-intercepts of $y=x^2-2x-3$.", ["$3,-1$", "$-3,1$", "$3,1$", "$-3,-1$"], 0));
  q.push(mc("medium", "Vertex of $y=2(x+2)(x-4)$.", ["$(1,-18)$", "$(1,18)$", "$(-1,-18)$", "$(1,-9)$"], 0));
  q.push(mc("medium", "Vertex of $y=(x-2)(x-8)$.", ["$(5,-9)$", "$(5,9)$", "$(-5,-9)$", "$(5,-3)$"], 0));
  q.push(mc("medium", "Axis of symmetry of $y=x^2+x-12$.", ["$x=-\\tfrac12$", "$x=\\tfrac12$", "$x=1$", "$x=-1$"], 0));
  q.push(mc("medium", "x-intercepts of $y=3(x-1)(x+3)$.", ["$1,-3$", "$-1,3$", "$3,-1$", "$1,3$"], 0));
  q.push(ms("medium", "Finding the vertex from factored form:", ["axis $x=\\tfrac{r+s}{2}$", "substitute back", "gives the vertex", "use the y-int"], [0, 1, 2]));
  q.push(ms("medium", "$y=2(x+2)(x-4)$:", ["intercepts $-2,4$", "axis $x=1$", "$y=2(3)(-3)=-18$", "vertex $(1,18)$"], [0, 1, 2]));
  q.push(ms("medium", "Factor then read:", ["$x^2-2x-3=(x-3)(x+1)$", "intercepts $3,-1$", "axis $x=1$", "intercepts $-3,1$"], [0, 1, 2]));
  q.push(ms("medium", "Building a sketch:", ["x-intercepts", "vertex", "y-intercept", "random points"], [0, 1, 2]));
  q.push(tf("medium", "The vertex of $y=(x-1)(x-5)$ is $(3,-4)$.", true));
  q.push(tf("medium", "The vertex of $y=(x-2)(x-8)$ is $(5,-9)$.", true));
  q.push(tf("medium", "The axis of symmetry of $y=x^2+x-12$ is $x=1$.", false));
  q.push(fill("medium", "Vertex of $y=(x-1)(x-5)$.", ["(3,-4)", "3,-4"]));
  q.push(fill("medium", "x-intercepts of $y=x^2-2x-3$.", ["3,-1", "-1,3"]));
  q.push(fill("medium", "Axis of symmetry of $y=x^2+x-12$.", ["x=-1/2", "-1/2", "-0.5"]));
  q.push(num("medium", "Vertex $y$ of $y=(x-2)(x-8)$.", -9, 0));
  q.push(num("medium", "y-intercept of $y=2(x-1)(x-3)$.", 6, 0));
  q.push(num("medium", "Vertex $y$ of $y=(x+1)(x-7)$.", -16, 0));
  q.push(match("medium", "Match each to its vertex.", ["$(x-1)(x-5)$", "$(x-2)(x-8)$", "$2(x+2)(x-4)$"], ["$(3,-4)$", "$(5,-9)$", "$(1,-18)$"], [0, 1, 2]));
  q.push(mc("hard", "A parabola has x-intercepts 2, 6 and passes $(4,-8)$. Then $a=$", ["$2$", "$1$", "$-2$", "$4$"], 0));
  q.push(mc("hard", "Factored form of $y=x^2-7x+10$.", ["$(x-2)(x-5)$", "$(x+2)(x+5)$", "$(x-2)(x+5)$", "$(x-10)(x-1)$"], 0));
  q.push(mc("hard", "A quadratic with x-intercepts $-3,4$ and y-intercept $-12$ has $a=$", ["$1$", "$2$", "$-1$", "$12$"], 0));
  q.push(mc("hard", "Vertex of $y=x^2-7x+10$.", ["$(3.5,-2.25)$", "$(3.5,2.25)$", "$(3,-2)$", "$(7,10)$"], 0));
  q.push(mc("hard", "Minimum of $y=(x-2)(x-8)$.", ["$-9$", "$-4$", "$5$", "$9$"], 0));
  q.push(ms("hard", "Finding $a$ from intercepts & a point:", ["$y=a(x-r)(x-s)$", "substitute the point", "solve for $a$", "$a=1$ always"], [0, 1, 2]));
  q.push(ms("hard", "$y=x^2-7x+10$:", ["factor $(x-2)(x-5)$", "intercepts $2,5$", "axis $x=3.5$", "intercepts $-2,-5$"], [0, 1, 2]));
  q.push(ms("hard", "Vertex from factored:", ["axis = midpoint of roots", "substitute back", "that $y$ is the min/max", "use the y-int"], [0, 1, 2]));
  q.push(ms("hard", "From x-intercepts to an equation:", ["$y=a(x-r)(x-s)$", "need one more point for $a$", "then expand if needed", "$a$ is free"], [0, 1, 2]));
  q.push(tf("hard", "A parabola with x-intercepts 2, 6 through $(4,-8)$ has $a=2$.", true));
  q.push(tf("hard", "$y=x^2-7x+10$ factors to $(x-2)(x-5)$.", true));
  q.push(tf("hard", "A quadratic with x-intercepts $-3,4$ and y-intercept $-12$ has $a=2$.", false));
  q.push(fill("hard", "$a$ for x-intercepts 2, 6 through $(4,-8)$.", ["2"]));
  q.push(fill("hard", "Factored form of $y=x^2-7x+10$.", ["(x-2)(x-5)", "(x-5)(x-2)"]));
  q.push(fill("hard", "Vertex of $y=x^2-7x+10$.", ["(3.5,-2.25)", "3.5,-2.25"]));
  q.push(num("hard", "$a$ for x-intercepts 2, 6 through $(4,-8)$.", 2, 0));
  q.push(num("hard", "Min value of $y=(x-2)(x-8)$.", -9, 0));
  q.push(num("hard", "$a$ for x-intercepts $-3,4$ and y-intercept $-12$.", 1, 0));
  q.push(order("hard", "Order the steps to find $a$ for x-intercepts 2, 6 through $(4,-8)$.", ["Write $y=a(x-2)(x-6)$", "Substitute $(4,-8)$: $-8=a(2)(-2)$", "$-8=-4a$", "$a=2$"]));
  q.push(match("hard", "Match each quadratic to its factored form.", ["$x^2-7x+10$", "$x^2-2x-3$", "$x^2-16$"], ["$(x-2)(x-5)$", "$(x-3)(x+1)$", "$(x-4)(x+4)$"], [0, 1, 2]));
  return q;
}

// ── 2.5 Maximum/Minimum Problems & Applications ──────────────
function g25() {
  const q = [];
  q.push(mc("easy", "The max/min of a parabola is at the:", ["vertex", "y-intercept", "x-intercept", "axis only"], 0));
  q.push(mc("easy", "If $a>0$, the parabola has a:", ["minimum", "maximum", "neither", "both"], 0));
  q.push(mc("easy", "If $a<0$, the parabola has a:", ["maximum", "minimum", "neither", "both"], 0));
  q.push(mc("easy", "Max of $y=-(x-3)^2+9$.", ["$9$", "$3$", "$-9$", "$0$"], 0));
  q.push(mc("easy", "Min of $y=(x-2)^2+5$.", ["$5$", "$2$", "$-5$", "$0$"], 0));
  q.push(mc("easy", "The vertex $x$ of $y=ax^2+bx+c$ is:", ["$-\\dfrac{b}{2a}$", "$\\dfrac{b}{2a}$", "$\\dfrac{c}{a}$", "$-\\dfrac{c}{b}$"], 0));
  q.push(ms("easy", "Max/min:", ["at the vertex", "$a>0$ minimum", "$a<0$ maximum", "at the x-intercept"], [0, 1, 2]));
  q.push(ms("easy", "Finding it:", ["$x=-\\tfrac{b}{2a}$", "substitute back", "gives the value", "random"], [0, 1, 2]));
  q.push(ms("easy", "Applications:", ["height", "profit", "area", "slope"], [0, 1, 2]));
  q.push(ms("easy", "Reading vertex form:", ["$a(x-h)^2+k$", "max/min is $k$", "at $x=h$", "$k$ is the slope"], [0, 1, 2]));
  q.push(tf("easy", "The maximum or minimum is at the vertex.", true));
  q.push(tf("easy", "If $a>0$ the parabola has a maximum.", false));
  q.push(tf("easy", "Max of $y=-(x-3)^2+9$ is 9.", true));
  q.push(fill("easy", "Max of $y=-(x-2)^2+7$.", ["7"]));
  q.push(fill("easy", "Min of $y=(x-4)^2+6$.", ["6"]));
  q.push(fill("easy", "Does $y=2x^2-3$ have a max or min?", ["min", "minimum"]));
  q.push(num("easy", "Max value of $y=-(x-1)^2+4$.", 4, 0));
  q.push(num("easy", "Min value of $y=(x-5)^2+2$.", 2, 0));
  q.push(num("easy", "Vertex $x$ of $y=x^2-6x+5$.", 3, 0));
  q.push(match("easy", "Match each to its max/min.", ["$-(x-3)^2+9$", "$(x-2)^2+5$", "$-(x+1)^2$"], ["max 9", "min 5", "max 0"], [0, 1, 2]));
  q.push(mc("medium", "Min of $y=x^2-6x+5$.", ["$-4$", "$5$", "$3$", "$-9$"], 0));
  q.push(mc("medium", "Ball $h=-5t^2+20t$; max height.", ["$20$", "$40$", "$10$", "$4$"], 0));
  q.push(mc("medium", "Profit $P=-2x^2+12x-10$; max profit.", ["$8$", "$12$", "$3$", "$10$"], 0));
  q.push(mc("medium", "Rectangle, perimeter 20; max area.", ["$25$", "$20$", "$100$", "$10$"], 0));
  q.push(mc("medium", "Min of $y=2x^2-8x+1$.", ["$-7$", "$1$", "$-8$", "$2$"], 0));
  q.push(mc("medium", "$h=-5t^2+20t$ reaches max height at $t=$", ["$2$", "$4$", "$20$", "$5$"], 0));
  q.push(ms("medium", "Max height of $h=-5t^2+20t$:", ["$t=-\\tfrac{b}{2a}=2$", "$h=-20+40=20$", "20 m", "$t=4$"], [0, 1, 2]));
  q.push(ms("medium", "Max profit $P=-2x^2+12x-10$:", ["$x=3$", "$P=8$", "at the vertex", "$x=12$"], [0, 1, 2]));
  q.push(ms("medium", "Max area, perimeter 20:", ["$w(10-w)$", "vertex $w=5$", "$5\\times5=25$", "$w=10$"], [0, 1, 2]));
  q.push(ms("medium", "Setting up:", ["define a variable", "write a quadratic", "find the vertex", "guess"], [0, 1, 2]));
  q.push(tf("medium", "The ball $h=-5t^2+20t$ has max height 20 m.", true));
  q.push(tf("medium", "A rectangle with perimeter 20 has max area when $5\\times5$.", true));
  q.push(tf("medium", "$P=-2x^2+12x-10$ has its maximum at $x=12$.", false));
  q.push(fill("medium", "Max height of $h=-5t^2+20t$.", ["20"]));
  q.push(fill("medium", "Max profit of $P=-2x^2+12x-10$.", ["8"]));
  q.push(fill("medium", "Min of $y=x^2-6x+5$.", ["-4"]));
  q.push(num("medium", "Max height (m) of $h=-5t^2+30t$.", 45, 0));
  q.push(num("medium", "Min of $y=2x^2-8x+1$.", -7, 0));
  q.push(num("medium", "Max area of a rectangle with perimeter 24.", 36, 0));
  q.push(match("medium", "Match each model to its optimum.", ["$h=-5t^2+20t$", "$P=-2x^2+12x-10$", "$y=x^2-6x+5$"], ["max 20", "max 8", "min -4"], [0, 1, 2]));
  q.push(mc("hard", "A pen against a wall, 60 m of fencing on 3 sides; max area.", ["$450$", "$900$", "$225$", "$400$"], 0));
  q.push(mc("hard", "Ball $h=-5t^2+40t$; max height.", ["$80$", "$40$", "$160$", "$8$"], 0));
  q.push(mc("hard", "Two numbers sum to 12; max product.", ["$36$", "$12$", "$24$", "$72$"], 0));
  q.push(mc("hard", "Rectangle, perimeter 100 m; max area.", ["$625$", "$2500$", "$100$", "$50$"], 0));
  q.push(mc("hard", "Revenue $r(s)=-10s^2+1500s$; max revenue.", ["$56250$", "$75$", "$112500$", "$54000$"], 0));
  q.push(ms("hard", "Pen with 60 m on 3 sides:", ["$A=w(60-2w)$", "vertex $w=15$", "length 30", "area 450"], [0, 1, 2, 3]));
  q.push(ms("hard", "Two numbers summing to 12:", ["product $x(12-x)$", "vertex $x=6$", "max 36", "max 12"], [0, 1, 2]));
  q.push(ms("hard", "Max revenue $-10s^2+1500s$:", ["$s=-\\tfrac{b}{2a}=75$", "$r(75)=56250$", "at the vertex", "$s=150$"], [0, 1, 2]));
  q.push(ms("hard", "Optimization steps:", ["model the quantity", "find the vertex", "interpret in context", "ignore units"], [0, 1, 2]));
  q.push(tf("hard", "A 3-sided pen with 60 m of fencing has max area 450 m².", true));
  q.push(tf("hard", "Two numbers summing to 12 have max product 36.", true));
  q.push(tf("hard", "$r(s)=-10s^2+1500s$ is maximized at $s=150$.", false));
  q.push(fill("hard", "Max area of a 3-sided pen with 60 m of fencing.", ["450"]));
  q.push(fill("hard", "Max product of two numbers summing to 12.", ["36"]));
  q.push(fill("hard", "$s$ that maximizes $r(s)=-10s^2+1500s$.", ["75"]));
  q.push(num("hard", "Max area (m²) of a 3-sided pen with 60 m of fencing.", 450, 0));
  q.push(num("hard", "Max height (m) of $h=-5t^2+40t$.", 80, 0));
  q.push(num("hard", "Max revenue of $r(s)=-10s^2+1500s$.", 56250, 0));
  q.push(order("hard", "Order the steps to maximize the area of a 3-sided pen with 60 m of fencing.", ["Let width $w$, length $60-2w$", "Area $A=w(60-2w)=60w-2w^2$", "Vertex at $w=15$, length 30", "Max area 450 m²"]));
  q.push(match("hard", "Match each to its maximum.", ["3-sided pen, 60 m", "numbers summing to 12", "$r=-10s^2+1500s$"], ["$450$", "$36$", "$56250$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "2.1", gen: g21 },
  { code: "2.2", gen: g22 },
  { code: "2.3", gen: g23 },
  { code: "2.4", gen: g24 },
  { code: "2.5", gen: g25 },
];
