// MCF3M Unit 5 — Trigonometry: question bank (60 per topic).
import { mc, ms, tf, num, fill, order, match } from "../bank-mpm2d/helpers.mjs";

// ── 5.1 Primary Trigonometric Ratios & Right Triangles ───────
function g51() {
  const q = [];
  q.push(mc("easy", "$\\sin\\theta=$", ["$\\dfrac{\\text{opp}}{\\text{hyp}}$", "$\\dfrac{\\text{adj}}{\\text{hyp}}$", "$\\dfrac{\\text{opp}}{\\text{adj}}$", "$\\dfrac{\\text{hyp}}{\\text{opp}}$"], 0));
  q.push(mc("easy", "$\\cos\\theta=$", ["$\\dfrac{\\text{adj}}{\\text{hyp}}$", "$\\dfrac{\\text{opp}}{\\text{hyp}}$", "$\\dfrac{\\text{opp}}{\\text{adj}}$", "$\\dfrac{\\text{hyp}}{\\text{adj}}$"], 0));
  q.push(mc("easy", "$\\tan\\theta=$", ["$\\dfrac{\\text{opp}}{\\text{adj}}$", "$\\dfrac{\\text{adj}}{\\text{opp}}$", "$\\dfrac{\\text{opp}}{\\text{hyp}}$", "$\\dfrac{\\text{hyp}}{\\text{adj}}$"], 0));
  q.push(mc("easy", "opp $=3$, hyp $=5$: $\\sin\\theta=$", ["$0.6$", "$0.8$", "$0.75$", "$1.67$"], 0));
  q.push(mc("easy", "The hypotenuse is opposite the:", ["right angle", "smallest angle", "given angle", "largest side"], 0));
  q.push(mc("easy", "To find an angle from two sides, use:", ["inverse trig", "multiplication", "Pythagoras only", "addition"], 0));
  q.push(ms("easy", "SOH CAH TOA:", ["$\\sin=$ opp/hyp", "$\\cos=$ adj/hyp", "$\\tan=$ opp/adj", "$\\sin=$ adj/hyp"], [0, 1, 2]));
  q.push(ms("easy", "Finding a side:", ["choose a ratio", "multiply", "e.g. opp $=$ hyp $\\cdot\\sin\\theta$", "use an inverse"], [0, 1, 2]));
  q.push(ms("easy", "Finding an angle:", ["use inverse trig", "$\\theta=\\tan^{-1}(\\text{opp/adj})$", "need two sides", "just multiply"], [0, 1, 2]));
  q.push(ms("easy", "The hypotenuse:", ["is the longest side", "is opposite the right angle", "appears in sin & cos", "is opposite the given angle"], [0, 1, 2]));
  q.push(tf("easy", "$\\sin\\theta=\\text{opp/hyp}$.", true));
  q.push(tf("easy", "To find an angle you multiply the two sides.", false));
  q.push(tf("easy", "The hypotenuse is the longest side.", true));
  q.push(fill("easy", "$\\sin\\theta$ if opp $=4$, hyp $=5$.", ["0.8", "4/5"]));
  q.push(fill("easy", "Opposite side if hyp $=10$, angle $30°$ (use sine).", ["5"]));
  q.push(fill("easy", "$\\cos\\theta$ if adj $=3$, hyp $=5$.", ["0.6", "3/5"]));
  q.push(num("easy", "$\\sin\\theta$ (decimal) if opp $=3$, hyp $=5$.", 0.6, 0.01));
  q.push(num("easy", "Opposite side if hyp $=20$, angle $30°$.", 10, 0));
  q.push(num("easy", "$\\theta$ (degrees) if $\\sin\\theta=0.5$.", 30, 0));
  q.push(match("easy", "Match each ratio.", ["$\\sin\\theta$", "$\\cos\\theta$", "$\\tan\\theta$"], ["opp/hyp", "adj/hyp", "opp/adj"], [0, 1, 2]));
  q.push(mc("medium", "Opposite side: adj $=8$, angle $40°$.", ["$\\approx6.71$", "$\\approx6.13$", "$\\approx10.4$", "$\\approx5.14$"], 0));
  q.push(mc("medium", "$\\theta$ if opp $=3$, adj $=4$.", ["$\\approx36.9°$", "$\\approx53.1°$", "$\\approx48.6°$", "$\\approx41.4°$"], 0));
  q.push(mc("medium", "A 10 m ladder at $60°$ reaches a height of:", ["$\\approx8.66$", "$\\approx5$", "$\\approx10$", "$\\approx7.07$"], 0));
  q.push(mc("medium", "Opposite side: hyp $=12$, angle $30°$.", ["$6$", "$10.4$", "$12$", "$3$"], 0));
  q.push(mc("medium", "$\\theta$ if opp $=7$, hyp $=10$.", ["$\\approx44.4°$", "$\\approx45.6°$", "$\\approx35.5°$", "$\\approx54.5°$"], 0));
  q.push(mc("medium", "Adjacent side: hyp $=10$, angle $40°$.", ["$\\approx7.66$", "$\\approx6.43$", "$\\approx8.39$", "$\\approx12.2$"], 0));
  q.push(ms("medium", "Finding opp from adj & angle:", ["$\\tan=$ opp/adj", "opp $=$ adj $\\cdot\\tan\\theta$", "need the angle", "opp $=$ adj $\\cdot\\sin\\theta$"], [0, 1, 2]));
  q.push(ms("medium", "Finding an angle:", ["two sides known", "use the matching inverse", "$\\tan^{-1}(\\text{opp/adj})$", "$\\sin^{-1}(\\text{adj/hyp})$"], [0, 1, 2]));
  q.push(ms("medium", "Ladder problem:", ["height $=$ length $\\cdot\\sin\\theta$", "a right triangle", "$10\\sin60°\\approx8.66$", "$10\\cos60°$"], [0, 1, 2]));
  q.push(ms("medium", "Choosing the ratio:", ["match known & wanted sides", "opp & hyp $\\to\\sin$", "adj & hyp $\\to\\cos$", "always tan"], [0, 1, 2]));
  q.push(tf("medium", "With adj $=8$, angle $40°$, opp $\\approx6.71$.", true));
  q.push(tf("medium", "With hyp $=12$, angle $30°$, opp $=6$.", true));
  q.push(tf("medium", "With opp $=3$, adj $=4$, $\\theta\\approx53.1°$.", false));
  q.push(fill("medium", "Opposite side if adj $=8$, angle $40°$ (2 dp).", ["6.71"]));
  q.push(fill("medium", "$\\theta$ (deg, 1 dp) if opp $=3$, adj $=4$.", ["36.9"]));
  q.push(fill("medium", "Height of a 10 m ladder at $60°$ (2 dp).", ["8.66"]));
  q.push(num("medium", "Opposite side if adj $=8$, angle $40°$ (2 dp).", 6.71, 0.05));
  q.push(num("medium", "$\\theta$ (deg) if opp $=3$, adj $=4$.", 36.9, 0.2));
  q.push(num("medium", "Height of a 10 m ladder at $60°$ (2 dp).", 8.66, 0.05));
  q.push(match("medium", "Match each to its value.", ["opp: hyp 10, $30°$", "$\\theta$: opp 3, adj 4", "$\\theta$: opp 7, hyp 10"], ["$5$", "$\\approx36.9°$", "$\\approx44.4°$"], [0, 1, 2]));
  q.push(mc("hard", "A 50 m kite string at $65°$ to the ground: the kite's height is:", ["$\\approx45.3$", "$\\approx21.1$", "$\\approx55.2$", "$\\approx42.3$"], 0));
  q.push(mc("hard", "A ramp rises 2 m over a 10 m run. Its angle is:", ["$\\approx11.3°$", "$\\approx78.7°$", "$\\approx11.5°$", "$\\approx20°$"], 0));
  q.push(mc("hard", "A wire from a 12 m pole meets the ground at $50°$. Its length is:", ["$\\approx15.66$", "$\\approx9.19$", "$\\approx18.67$", "$\\approx14.3$"], 0));
  q.push(mc("hard", "A 20 m guy wire reaches 16 m up a tower. Its angle with the ground is:", ["$\\approx53.1°$", "$\\approx36.9°$", "$\\approx51.3°$", "$\\approx38.7°$"], 0));
  q.push(mc("hard", "A road rises at $8°$. The vertical rise over 500 m of road is:", ["$\\approx69.6$", "$\\approx70.3$", "$\\approx495$", "$\\approx62.5$"], 0));
  q.push(ms("hard", "Kite at $65°$, 50 m string:", ["height $=50\\sin65°$", "$\\approx45.3$ m", "a right triangle", "$50\\cos65°$"], [0, 1, 2]));
  q.push(ms("hard", "Ramp angle from rise & run:", ["$\\tan\\theta=$ rise/run", "$\\theta=\\tan^{-1}(2/10)$", "$\\approx11.3°$", "$\\sin^{-1}$"], [0, 1, 2]));
  q.push(ms("hard", "Wire length (hyp) from height & angle:", ["$\\sin\\theta=$ height/hyp", "hyp $=$ height $\\div\\sin\\theta$", "$12/\\sin50°\\approx15.66$", "hyp $=12\\sin50°$"], [0, 1, 2]));
  q.push(ms("hard", "Real problems:", ["draw & label", "pick the ratio", "solve & check units", "skip the diagram"], [0, 1, 2]));
  q.push(tf("hard", "A 50 m string at $65°$ reaches $\\approx45.3$ m high.", true));
  q.push(tf("hard", "A ramp rising 2 m over 10 m makes $\\approx11.3°$ with the ground.", true));
  q.push(tf("hard", "A 20 m wire to a point 16 m up makes $\\approx36.9°$ with the ground.", false));
  q.push(fill("hard", "Height of a 50 m kite string at $65°$ (1 dp).", ["45.3"]));
  q.push(fill("hard", "Ramp angle for rise 2, run 10 (deg, 1 dp).", ["11.3"]));
  q.push(fill("hard", "Wire length from a 12 m pole at $50°$ (2 dp).", ["15.66"]));
  q.push(num("hard", "Height of a 50 m string at $65°$ (1 dp).", 45.3, 0.2));
  q.push(num("hard", "Vertical rise over 500 m of road at $8°$ (1 dp).", 69.6, 0.3));
  q.push(num("hard", "Angle of a 20 m wire reaching 16 m up (deg).", 53.1, 0.2));
  q.push(order("hard", "Order the steps to find the height a 50 m kite string at $65°$ reaches.", ["Identify hyp $=50$, angle $=65°$", "Use $\\sin65°=$ height $\\div50$", "height $=50\\sin65°$", "$\\approx45.3$ m"]));
  q.push(match("hard", "Match each to its value.", ["50 m string at $65°$", "ramp rise 2, run 10", "wire: 12 m pole at $50°$"], ["$\\approx45.3$ m", "$\\approx11.3°$", "$\\approx15.66$ m"], [0, 1, 2]));
  return q;
}

// ── 5.2 Two Right Triangles in 2-D ───────────────────────────
function g52() {
  const q = [];
  q.push(mc("easy", "An angle of elevation is measured:", ["up from the horizontal", "down from the horizontal", "from the vertical", "along the ground"], 0));
  q.push(mc("easy", "An angle of depression is measured:", ["down from the horizontal", "up from the horizontal", "from the vertical", "along the ground"], 0));
  q.push(mc("easy", "The two right triangles usually share:", ["a side", "nothing", "only a vertex", "a curve"], 0));
  q.push(mc("easy", "From 40 m, elevation $35°$ to a roof: height $=$", ["$40\\tan35°$", "$40\\sin35°$", "$40\\cos35°$", "$40\\div\\tan35°$"], 0));
  q.push(mc("easy", "Elevation and depression across parallels are:", ["equal", "complementary", "supplementary", "unrelated"], 0));
  q.push(mc("easy", "The first step in a two-triangle problem:", ["draw and label", "guess", "use the sine law", "ignore the figure"], 0));
  q.push(ms("easy", "Strategy:", ["draw the figure", "mark the shared side", "one equation per triangle", "skip the diagram"], [0, 1, 2]));
  q.push(ms("easy", "Elevation vs depression:", ["elevation looks up", "depression looks down", "equal across parallels", "both from the vertical"], [0, 1, 2]));
  q.push(ms("easy", "Tools:", ["SOH CAH TOA", "two equations", "combine them", "sine law only"], [0, 1, 2]));
  q.push(ms("easy", "Common setups:", ["a height from two distances", "two objects from one point", "a shared height or base", "unrelated triangles"], [0, 1, 2]));
  q.push(tf("easy", "An angle of elevation is measured up from the horizontal.", true));
  q.push(tf("easy", "Elevation and depression across parallels are supplementary.", false));
  q.push(tf("easy", "The two triangles usually share a side.", true));
  q.push(fill("easy", "Height of a roof from 40 m at $35°$ (expression).", ["40tan35°", "40\\tan35°"]));
  q.push(fill("easy", "Distance to a boat from a 60 m cliff at depression $25°$ (expression).", ["60/tan25°", "\\frac{60}{\\tan25°}"]));
  q.push(fill("easy", "Are elevation & depression across parallels equal?", ["equal", "yes"]));
  q.push(num("easy", "Height of a roof from 40 m at $35°$ (1 dp).", 28.0, 0.3));
  q.push(num("easy", "Distance to a boat from a 60 m cliff, depression $25°$ (nearest m).", 128.7, 1.5));
  q.push(num("easy", "Number of right triangles in these problems.", 2, 0));
  q.push(match("easy", "Match each term.", ["elevation", "depression", "first step"], ["look up", "look down", "draw & label"], [0, 1, 2]));
  q.push(mc("medium", "Helicopter 500 m up, depressions $60°$ & $20°$: trucks are apart by", ["$\\approx1085$", "$\\approx288.7$", "$\\approx1373.7$", "$\\approx500$"], 0));
  q.push(mc("medium", "Pole on a building, 50 m away, $30°$ & $40°$: pole height", ["$\\approx13.1$", "$\\approx41.95$", "$\\approx28.87$", "$\\approx70.8$"], 0));
  q.push(mc("medium", "Two buoys from a 40 m cliff, $50°$ & $30°$: apart by", ["$\\approx35.7$", "$\\approx33.56$", "$\\approx69.28$", "$\\approx40$"], 0));
  q.push(mc("medium", "From a 300 m helicopter, depressions $45°$ & $30°$: trucks apart by", ["$\\approx219.6$", "$\\approx300$", "$\\approx519.6$", "$\\approx173.2$"], 0));
  q.push(mc("medium", "From 60 m, elevations $28°$ & $38°$ to a flagpole's base & top: pole height", ["$\\approx15.0$", "$\\approx46.9$", "$\\approx31.9$", "$\\approx12.5$"], 0));
  q.push(mc("medium", "From a 60 m cliff, depression $25°$ to a boat: distance", ["$\\approx128.7$", "$\\approx27.96$", "$\\approx132.4$", "$\\approx141.4$"], 0));
  q.push(ms("medium", "Helicopter & trucks:", ["far distance $=500/\\tan20°$", "near distance $=500/\\tan60°$", "apart $=$ far $-$ near", "add them"], [0, 1, 2]));
  q.push(ms("medium", "Pole on a building:", ["top height $=50\\tan40°$", "base height $=50\\tan30°$", "pole $=$ difference", "pole $=$ sum"], [0, 1, 2]));
  q.push(ms("medium", "Walking closer (hill):", ["$h/\\tan\\theta_1-h/\\tan\\theta_2=$ distance", "two equations", "solve for $h$", "one equation"], [0, 1, 2]));
  q.push(ms("medium", "Setting up:", ["label the shared height", "write each triangle", "subtract the distances", "ignore one triangle"], [0, 1, 2]));
  q.push(tf("medium", "A 500 m helicopter (depressions $60°,20°$) sees trucks $\\approx1085$ m apart.", true));
  q.push(tf("medium", "A rooftop pole (50 m away, $30°$ & $40°$) is $\\approx13.1$ m.", true));
  q.push(tf("medium", "Two trucks from a 300 m helicopter at $45°$ & $30°$ are $\\approx519.6$ m apart.", false));
  q.push(fill("medium", "Trucks apart: 500 m heli, depressions $60°$ & $20°$ (nearest m).", ["1085"]));
  q.push(fill("medium", "Pole height: 50 m away, $30°$ & $40°$ (1 dp).", ["13.1"]));
  q.push(fill("medium", "Buoys apart: 40 m cliff, $50°$ & $30°$ (1 dp).", ["35.7"]));
  q.push(num("medium", "Trucks apart: 500 m heli, $60°$ & $20°$ (nearest 5 m).", 1085, 6));
  q.push(num("medium", "Pole height: 50 m away, $30°$ & $40°$ (1 dp).", 13.1, 0.3));
  q.push(num("medium", "Trucks apart: 300 m heli, $45°$ & $30°$ (1 dp).", 219.6, 1.5));
  q.push(match("medium", "Match each to its value.", ["heli 500 m, $60°$&$20°$", "pole 50 m, $30°$&$40°$", "buoys 40 m, $50°$&$30°$"], ["$\\approx1085$ m", "$\\approx13.1$ m", "$\\approx35.7$ m"], [0, 1, 2]));
  q.push(mc("hard", "Hill: $20°$ from A, $35°$ from 100 m closer: height", ["$\\approx75.8$", "$\\approx68.3$", "$\\approx47.3$", "$\\approx100$"], 0));
  q.push(mc("hard", "Tower: $45°$, then $60°$ from 20 m closer: height", ["$\\approx47.3$", "$\\approx27.3$", "$\\approx20$", "$\\approx34.6$"], 0));
  q.push(mc("hard", "Hill: $25°$ from A, $40°$ from 60 m closer: height", ["$\\approx63.0$", "$\\approx68.3$", "$\\approx40$", "$\\approx52$"], 0));
  q.push(mc("hard", "Tower: $30°$, then $45°$ from 50 m closer: height", ["$\\approx68.3$", "$\\approx50$", "$\\approx75.8$", "$\\approx35.4$"], 0));
  q.push(mc("hard", "Helicopter 400 m up, cars at $50°$ & $25°$: apart by", ["$\\approx522.2$", "$\\approx335.6$", "$\\approx857.8$", "$\\approx400$"], 0));
  q.push(ms("hard", "Hill, walking closer:", ["$h(\\cot\\theta_1-\\cot\\theta_2)=$ distance", "$\\cot20°-\\cot35°$", "$=100\\div$ that", "$h\\approx75.8$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Tower $45°$ then $60°$:", ["$h(\\cot45°-\\cot60°)=20$", "$\\cot45°=1,\\ \\cot60°\\approx0.577$", "$h\\approx47.3$", "$h=20$"], [0, 1, 2]));
  q.push(ms("hard", "General method:", ["each triangle: distance $=h\\cot\\theta$", "subtract the two", "solve for $h$", "add them"], [0, 1, 2]));
  q.push(ms("hard", "Why it works:", ["the same height $h$ in both", "two distances differ by the walk", "one unknown $h$", "two unknowns"], [0, 1, 2]));
  q.push(tf("hard", "Hill $20°\\to35°$ over 100 m gives a height $\\approx75.8$ m.", true));
  q.push(tf("hard", "Tower $45°\\to60°$ over 20 m gives a height $\\approx47.3$ m.", true));
  q.push(tf("hard", "Hill $30°\\to45°$ over 50 m gives a height $\\approx50$ m.", false));
  q.push(fill("hard", "Hill height: $20°$ then $35°$, 100 m closer (1 dp).", ["75.8"]));
  q.push(fill("hard", "Tower height: $45°$ then $60°$, 20 m closer (1 dp).", ["47.3"]));
  q.push(fill("hard", "Hill height: $25°$ then $40°$, 60 m closer (1 dp).", ["63.0", "63"]));
  q.push(num("hard", "Hill height: $20°\\to35°$, 100 m (1 dp).", 75.8, 0.6));
  q.push(num("hard", "Tower height: $45°\\to60°$, 20 m (1 dp).", 47.3, 0.6));
  q.push(num("hard", "Cars apart: 400 m heli, $50°$ & $25°$ (nearest m).", 522.2, 3));
  q.push(order("hard", "Order the steps to find a hill's height ($20°$ from A, $35°$ after 100 m closer).", ["Each triangle: distance $=h\\cot\\theta$", "$h\\cot20°-h\\cot35°=100$", "$h(2.747-1.428)=100$", "$h\\approx75.8$ m"]));
  q.push(match("hard", "Match each to its value.", ["hill $20°\\to35°$, 100 m", "tower $45°\\to60°$, 20 m", "cars: 400 m heli, $50°$&$25°$"], ["$\\approx75.8$ m", "$\\approx47.3$ m", "$\\approx522.2$ m"], [0, 1, 2]));
  return q;
}

// ── 5.3 The Sine Law ─────────────────────────────────────────
function g53() {
  const q = [];
  q.push(mc("easy", "The sine law:", ["$\\dfrac{a}{\\sin A}=\\dfrac{b}{\\sin B}$", "$a^2=b^2+c^2$", "$c^2=a^2+b^2-2ab\\cos C$", "$a=b+c$"], 0));
  q.push(mc("easy", "Use the sine law when you have:", ["a side and its opposite angle", "three sides", "two sides & the included angle", "nothing"], 0));
  q.push(mc("easy", "Triangle angles sum to:", ["$180°$", "$360°$", "$90°$", "$270°$"], 0));
  q.push(mc("easy", "The largest side is opposite the:", ["largest angle", "smallest angle", "right angle", "first angle"], 0));
  q.push(mc("easy", "If $A=40°$ and $B=75°$, then $C=$", ["$65°$", "$115°$", "$75°$", "$45°$"], 0));
  q.push(mc("easy", "In the sine law each side pairs with:", ["its opposite angle", "an adjacent angle", "any angle", "the largest angle"], 0));
  q.push(ms("easy", "Sine law:", ["$\\dfrac a{\\sin A}=\\dfrac b{\\sin B}=\\dfrac c{\\sin C}$", "side ↔ opposite angle", "needs a matched pair", "$a^2+b^2=c^2$"], [0, 1, 2]));
  q.push(ms("easy", "When to use:", ["a side & its opposite angle", "plus one more piece", "AAS / ASA / SSA", "SSS only"], [0, 1, 2]));
  q.push(ms("easy", "Angle sum:", ["$A+B+C=180°$", "find the third angle", "useful before the sine law", "$=360°$"], [0, 1, 2]));
  q.push(ms("easy", "Finding an angle:", ["cross-multiply", "$\\sin B=b\\sin A\\div a$", "then $\\sin^{-1}$", "then add"], [0, 1, 2]));
  q.push(tf("easy", "The sine law pairs each side with its opposite angle.", true));
  q.push(tf("easy", "Triangle angles sum to $360°$.", false));
  q.push(tf("easy", "If $A=40°$ and $B=75°$, then $C=65°$.", true));
  q.push(fill("easy", "Third angle if $A=50°$, $B=60°$.", ["70°", "70"]));
  q.push(fill("easy", "Setup for $b$: $A=40°$, $a=10$, $B=60°$.", ["10sin60°/sin40°", "\\frac{10\\sin60°}{\\sin40°}"]));
  q.push(fill("easy", "The sine law is for a side and its ___ angle.", ["opposite"]));
  q.push(num("easy", "Third angle (deg) if $A=40°$, $B=75°$.", 65, 0));
  q.push(num("easy", "$b$ (1 dp) if $A=40°$, $a=10$, $B=60°$.", 13.5, 0.2));
  q.push(num("easy", "Sum of triangle angles (deg).", 180, 0));
  q.push(match("easy", "Match each.", ["sine law", "when to use", "angle sum"], ["$\\dfrac a{\\sin A}=\\dfrac b{\\sin B}$", "side & opposite angle", "$180°$"], [0, 1, 2]));
  q.push(mc("medium", "$b$ if $A=40°$, $a=10$, $B=60°$.", ["$\\approx13.5$", "$\\approx7.4$", "$\\approx11.3$", "$\\approx15.6$"], 0));
  q.push(mc("medium", "$b$ if $A=50°$, $B=70°$, $a=8$.", ["$\\approx9.81$", "$\\approx6.5$", "$\\approx8.7$", "$\\approx10.4$"], 0));
  q.push(mc("medium", "$B$ if $a=8$, $A=50°$, $b=6$.", ["$\\approx35.1°$", "$\\approx40°$", "$\\approx44.9°$", "$\\approx50°$"], 0));
  q.push(mc("medium", "$c$ if $A=45°$, $B=60°$, $a=12$.", ["$\\approx16.4$", "$\\approx14.7$", "$\\approx12$", "$\\approx10.4$"], 0));
  q.push(mc("medium", "$b$ if $A=30°$, $a=5$, $B=80°$.", ["$\\approx9.85$", "$\\approx2.5$", "$\\approx5$", "$\\approx7.7$"], 0));
  q.push(mc("medium", "$b$ if $A=60°$, $a=10$, $B=40°$.", ["$\\approx7.42$", "$\\approx13.5$", "$\\approx8.5$", "$\\approx6.4$"], 0));
  q.push(ms("medium", "$b$ for $A=40°$, $a=10$, $B=60°$:", ["$b=a\\sin B\\div\\sin A$", "$=10\\sin60°/\\sin40°$", "$\\approx13.5$", "$=10\\sin40°/\\sin60°$"], [0, 1, 2]));
  q.push(ms("medium", "Finding $B$ ($a=8$, $A=50°$, $b=6$):", ["$\\sin B=b\\sin A\\div a$", "$=6\\sin50°/8$", "$B\\approx35.1°$", "$B\\approx50°$"], [0, 1, 2]));
  q.push(ms("medium", "Two angles given:", ["find the third", "then a side", "$C=180°-A-B$", "skip the third"], [0, 1, 2]));
  q.push(ms("medium", "Setting up:", ["match a side & opposite angle", "cross-multiply", "solve", "add the sides"], [0, 1, 2]));
  q.push(tf("medium", "$b\\approx13.5$ for $A=40°$, $a=10$, $B=60°$.", true));
  q.push(tf("medium", "$B\\approx35.1°$ for $a=8$, $A=50°$, $b=6$.", true));
  q.push(tf("medium", "$c\\approx12$ for $A=45°$, $B=60°$, $a=12$.", false));
  q.push(fill("medium", "$b$ (1 dp) if $A=40°$, $a=10$, $B=60°$.", ["13.5"]));
  q.push(fill("medium", "$B$ (deg, 1 dp) if $a=8$, $A=50°$, $b=6$.", ["35.1"]));
  q.push(fill("medium", "$c$ (1 dp) if $A=45°$, $B=60°$, $a=12$.", ["16.4"]));
  q.push(num("medium", "$b$ (1 dp) if $A=50°$, $B=70°$, $a=8$.", 9.81, 0.15));
  q.push(num("medium", "$B$ (deg, 1 dp) if $a=10$, $A=70°$, $b=8$.", 48.8, 0.3));
  q.push(num("medium", "$b$ (1 dp) if $A=60°$, $a=10$, $B=40°$.", 7.42, 0.15));
  q.push(match("medium", "Match each to its value.", ["$b$: $A40°,a10,B60°$", "$B$: $a8,A50°,b6$", "$c$: $A45°,B60°,a12$"], ["$\\approx13.5$", "$\\approx35.1°$", "$\\approx16.4$"], [0, 1, 2]));
  q.push(mc("hard", "$b$ if $A=55°$, $a=14$, $B=65°$.", ["$\\approx15.5$", "$\\approx13.0$", "$\\approx12.6$", "$\\approx16.9$"], 0));
  q.push(mc("hard", "$B$ if $a=12$, $A=80°$, $b=9$.", ["$\\approx47.6°$", "$\\approx42.4°$", "$\\approx52.3°$", "$\\approx38.1°$"], 0));
  q.push(mc("hard", "$B$ if $A=35°$, $a=9$, $b=7$.", ["$\\approx26.5°$", "$\\approx30°$", "$\\approx33.5°$", "$\\approx40°$"], 0));
  q.push(mc("hard", "$a$ if $A=50°$, $C=60°$, $b=10$.", ["$\\approx8.15$", "$\\approx9.2$", "$\\approx10$", "$\\approx7.4$"], 0));
  q.push(mc("hard", "$c$ if $B=40°$, $b=9$, $C=75°$.", ["$\\approx13.5$", "$\\approx11.4$", "$\\approx9$", "$\\approx7.1$"], 0));
  q.push(ms("hard", "$b$ for $A=55°$, $a=14$, $B=65°$:", ["$b=14\\sin65°/\\sin55°$", "$\\approx15.5$", "a matched pair", "$b=14\\sin55°/\\sin65°$"], [0, 1, 2]));
  q.push(ms("hard", "Finding $a$ ($A=50°$, $C=60°$, $b=10$):", ["$B=70°$", "$a=b\\sin A\\div\\sin B$", "$=10\\sin50°/\\sin70°\\approx8.15$", "$a=10$"], [0, 1, 2]));
  q.push(ms("hard", "Finding $B$ ($A=35°$, $a=9$, $b=7$):", ["$\\sin B=7\\sin35°/9$", "$\\approx0.446$", "$B\\approx26.5°$", "$B\\approx40°$"], [0, 1, 2]));
  q.push(ms("hard", "General sine-law solving:", ["identify a matched pair", "use the angle sum if needed", "solve for the unknown", "guess"], [0, 1, 2]));
  q.push(tf("hard", "$b\\approx15.5$ for $A=55°$, $a=14$, $B=65°$.", true));
  q.push(tf("hard", "$B\\approx26.5°$ for $A=35°$, $a=9$, $b=7$.", true));
  q.push(tf("hard", "$B\\approx52°$ for $a=12$, $A=80°$, $b=9$.", false));
  q.push(fill("hard", "$b$ (1 dp) if $A=55°$, $a=14$, $B=65°$.", ["15.5"]));
  q.push(fill("hard", "$B$ (deg, 1 dp) if $a=12$, $A=80°$, $b=9$.", ["47.6"]));
  q.push(fill("hard", "$B$ (deg, 1 dp) if $A=35°$, $a=9$, $b=7$.", ["26.5"]));
  q.push(num("hard", "$b$ (1 dp) if $A=55°$, $a=14$, $B=65°$.", 15.5, 0.2));
  q.push(num("hard", "$a$ (2 dp) if $A=50°$, $C=60°$, $b=10$.", 8.15, 0.15));
  q.push(num("hard", "$B$ (deg, 1 dp) if $A=35°$, $a=9$, $b=7$.", 26.5, 0.3));
  q.push(order("hard", "Order the steps to find $a$, given $A=50°$, $C=60°$, $b=10$.", ["Third angle $B=180°-50°-60°=70°$", "$a/\\sin A=b/\\sin B$", "$a=10\\sin50°/\\sin70°$", "$a\\approx8.15$"]));
  q.push(match("hard", "Match each to its value.", ["$b$: $A55°,a14,B65°$", "$B$: $a12,A80°,b9$", "$B$: $A35°,a9,b7$"], ["$\\approx15.5$", "$\\approx47.6°$", "$\\approx26.5°$"], [0, 1, 2]));
  return q;
}

// ── 5.4 The Cosine Law ───────────────────────────────────────
function g54() {
  const q = [];
  q.push(mc("easy", "The cosine law (find a side):", ["$c^2=a^2+b^2-2ab\\cos C$", "$c^2=a^2+b^2$", "$\\dfrac a{\\sin A}=\\dfrac b{\\sin B}$", "$c=a+b$"], 0));
  q.push(mc("easy", "Use the cosine law for:", ["SAS or SSS", "a side & its opposite angle", "two angles", "nothing"], 0));
  q.push(mc("easy", "When $C=90°$, $\\cos C=$", ["$0$", "$1$", "$-1$", "$0.5$"], 0));
  q.push(mc("easy", "The cosine law generalizes:", ["the Pythagorean theorem", "the sine law", "SOH CAH TOA", "the angle sum"], 0));
  q.push(mc("easy", "To find an angle from three sides, use:", ["the cosine law", "the sine law", "Pythagoras", "the angle sum"], 0));
  q.push(mc("easy", "The largest angle is opposite the:", ["longest side", "shortest side", "first side", "hypotenuse"], 0));
  q.push(ms("easy", "Cosine law:", ["$c^2=a^2+b^2-2ab\\cos C$", "for SAS", "for SSS (rearranged)", "only right triangles"], [0, 1, 2]));
  q.push(ms("easy", "Find an angle (SSS):", ["$\\cos C=\\dfrac{a^2+b^2-c^2}{2ab}$", "then $\\cos^{-1}$", "need three sides", "need an angle"], [0, 1, 2]));
  q.push(ms("easy", "Connection to Pythagoras:", ["$C=90°\\Rightarrow\\cos C=0$", "then $c^2=a^2+b^2$", "the extra term vanishes", "no connection"], [0, 1, 2]));
  q.push(ms("easy", "Choosing a law:", ["SAS → cosine", "SSS → cosine", "matched pair → sine", "always sine"], [0, 1, 2]));
  q.push(tf("easy", "The cosine law generalizes the Pythagorean theorem.", true));
  q.push(tf("easy", "The cosine law needs a side and its opposite angle.", false));
  q.push(tf("easy", "To find an angle from three sides, use the cosine law.", true));
  q.push(fill("easy", "$\\cos C$ when $C=90°$.", ["0"]));
  q.push(fill("easy", "Law for three sides (find an angle).", ["cosine", "cosine law"]));
  q.push(fill("easy", "$c^2$ for $a=5$, $b=7$, $C=60°$.", ["39"]));
  q.push(num("easy", "$c^2$ for $a=5$, $b=7$, $C=60°$.", 39, 0));
  q.push(num("easy", "$c$ for $a=8$, $b=6$, $C=90°$.", 10, 0));
  q.push(num("easy", "$\\cos C$ for sides $6,8,10$ (opposite 10).", 0, 0.001));
  q.push(match("easy", "Match each case to a law.", ["SAS", "SSS", "matched pair"], ["cosine law", "cosine law", "sine law"], [0, 1, 2]));
  q.push(mc("medium", "$c$ if $a=5$, $b=7$, $C=60°$.", ["$\\approx6.24$", "$\\approx12$", "$\\approx8.6$", "$\\approx39$"], 0));
  q.push(mc("medium", "$c$ if $a=8$, $b=6$, $C=90°$.", ["$10$", "$14$", "$2$", "$\\sqrt{28}$"], 0));
  q.push(mc("medium", "Largest angle of sides $6,8,10$.", ["$90°$", "$53.1°$", "$36.9°$", "$60°$"], 0));
  q.push(mc("medium", "$c$ if $a=7$, $b=9$, $C=50°$.", ["$\\approx7.0$", "$\\approx11.4$", "$\\approx5.7$", "$\\approx9.0$"], 0));
  q.push(mc("medium", "Largest angle of sides $5,6,7$.", ["$\\approx78.5°$", "$\\approx57.1°$", "$\\approx44.4°$", "$\\approx90°$"], 0));
  q.push(mc("medium", "$c$ if $a=4$, $b=5$, $C=90°$.", ["$\\approx6.40$", "$\\approx3$", "$\\approx9$", "$\\approx5.7$"], 0));
  q.push(ms("medium", "Computing $c$ ($a=5$, $b=7$, $C=60°$):", ["$c^2=25+49-70\\cos60°$", "$=74-35=39$", "$c\\approx6.24$", "$c=39$"], [0, 1, 2]));
  q.push(ms("medium", "Finding an angle ($6,8,10$):", ["$\\cos C=(36+64-100)\\div96$", "$=0$", "$C=90°$", "$C=60°$"], [0, 1, 2]));
  q.push(ms("medium", "Largest angle:", ["opposite the longest side", "use the cosine law", "$\\cos^{-1}$", "opposite the shortest"], [0, 1, 2]));
  q.push(ms("medium", "SAS vs SSS:", ["SAS finds a side", "SSS finds an angle", "both use the cosine law", "both use the sine law"], [0, 1, 2]));
  q.push(tf("medium", "$c\\approx6.24$ for $a=5$, $b=7$, $C=60°$.", true));
  q.push(tf("medium", "The largest angle of a $6,8,10$ triangle is $90°$.", true));
  q.push(tf("medium", "The largest angle of a $5,6,7$ triangle is $90°$.", false));
  q.push(fill("medium", "$c$ (2 dp) for $a=5$, $b=7$, $C=60°$.", ["6.24"]));
  q.push(fill("medium", "Largest angle (deg) of $6,8,10$.", ["90", "90°"]));
  q.push(fill("medium", "$c$ for $a=8$, $b=6$, $C=90°$.", ["10"]));
  q.push(num("medium", "$c$ (2 dp) for $a=5$, $b=7$, $C=60°$.", 6.24, 0.05));
  q.push(num("medium", "Largest angle (deg) of $5,6,7$.", 78.5, 0.5));
  q.push(num("medium", "$c$ (1 dp) for $a=9$, $b=12$, $C=80°$.", 13.7, 0.2));
  q.push(match("medium", "Match each to its value.", ["$c$: $a5,b7,C60°$", "largest ∠ of $6,8,10$", "largest ∠ of $5,6,7$"], ["$\\approx6.24$", "$90°$", "$\\approx78.5°$"], [0, 1, 2]));
  q.push(mc("hard", "$c$ if $a=9$, $b=12$, $C=80°$.", ["$\\approx13.7$", "$\\approx10.6$", "$\\approx15.0$", "$\\approx21$"], 0));
  q.push(mc("hard", "Angle opposite 9 in a $7,8,9$ triangle.", ["$\\approx73.4°$", "$\\approx48.2°$", "$\\approx58.4°$", "$\\approx90°$"], 0));
  q.push(mc("hard", "$c$ if $a=10$, $b=7$, $C=55°$.", ["$\\approx8.29$", "$\\approx6.4$", "$\\approx11.7$", "$\\approx9.0$"], 0));
  q.push(mc("hard", "Largest angle of a $9,10,11$ triangle.", ["$\\approx70.5°$", "$\\approx60°$", "$\\approx82.8°$", "$\\approx49.5°$"], 0));
  q.push(mc("hard", "$c$ if $a=8$, $b=8$, $C=60°$.", ["$8$", "$\\approx13.9$", "$\\approx11.3$", "$\\approx6.9$"], 0));
  q.push(ms("hard", "Computing $c$ ($a=9$, $b=12$, $C=80°$):", ["$c^2=81+144-216\\cos80°$", "$\\approx225-37.5=187.5$", "$c\\approx13.7$", "$c=187.5$"], [0, 1, 2]));
  q.push(ms("hard", "Angle opposite 9 ($7,8,9$):", ["$\\cos C=(49+64-81)\\div112$", "$\\approx0.286$", "$C\\approx73.4°$", "$C\\approx90°$"], [0, 1, 2]));
  q.push(ms("hard", "Largest angle of $9,10,11$:", ["opposite 11", "$\\cos C=(81+100-121)\\div180$", "$=0.333$", "$C\\approx70.5°$"], [0, 1, 2, 3]));
  q.push(ms("hard", "Solving fully:", ["use the cosine law first for SAS/SSS", "then the sine law", "angle sum to finish", "guess"], [0, 1, 2]));
  q.push(tf("hard", "$c\\approx13.7$ for $a=9$, $b=12$, $C=80°$.", true));
  q.push(tf("hard", "The angle opposite 9 in a $7,8,9$ triangle is $\\approx73.4°$.", true));
  q.push(tf("hard", "An $8,8$ triangle with $C=60°$ gives $c\\approx11.3$.", false));
  q.push(fill("hard", "$c$ (1 dp) for $a=9$, $b=12$, $C=80°$.", ["13.7"]));
  q.push(fill("hard", "Angle opposite 9 in $7,8,9$ (deg, 1 dp).", ["73.4"]));
  q.push(fill("hard", "Largest angle of $9,10,11$ (deg, 1 dp).", ["70.5"]));
  q.push(num("hard", "$c$ (1 dp) for $a=9$, $b=12$, $C=80°$.", 13.7, 0.2));
  q.push(num("hard", "Angle opposite 9 in $7,8,9$ (deg).", 73.4, 0.3));
  q.push(num("hard", "Largest angle of $9,10,11$ (deg).", 70.5, 0.3));
  q.push(order("hard", "Order the steps to find the largest angle of a $9,10,11$ triangle.", ["The largest angle is opposite 11", "$\\cos C=(81+100-121)\\div(2\\cdot9\\cdot10)$", "$=60/180=0.333$", "$C\\approx70.5°$"]));
  q.push(match("hard", "Match each to its value.", ["$c$: $a9,b12,C80°$", "∠ opp 9 in $7,8,9$", "largest ∠ of $9,10,11$"], ["$\\approx13.7$", "$\\approx73.4°$", "$\\approx70.5°$"], [0, 1, 2]));
  return q;
}

export default [
  { code: "5.1", gen: g51 },
  { code: "5.2", gen: g52 },
  { code: "5.3", gen: g53 },
  { code: "5.4", gen: g54 },
];
