// MHF4U Unit 1 worksheets — Polynomial Functions.
// Examples: full step-by-step solutions with TikZ polynomial graphs (\eplot).
const r = String.raw;
const U = "1: Polynomial Functions";

export default [
  {
    code: "1.1", unit: U, title: "Power Functions & End Behaviour",
    intro: r`Every polynomial behaves like its leading term at the ends. Degree parity and the sign of $a$ decide the end behaviour.`,
    ideas: [r`Even degree: both ends the same (up–up if $a>0$, down–down if $a<0$).`, r`Odd degree: ends opposite (down–up if $a>0$, up–down if $a<0$).`, r`Write it with limits, e.g. as $x\to+\infty,\ y\to+\infty$.`],
    examples: [
      { t: "Odd, positive", body: r`End behaviour of $f(x)=x^3$?\soln Odd degree, $a>0$: as $x\to-\infty,\ y\to-\infty$; as $x\to+\infty,\ y\to+\infty$ (down–up):` + r`\eplot{-3}{3}{-9}{9}{\addplot[exblue,very thick,domain=-2.1:2.1]{x^3};}` },
      { t: "Even, positive", body: r`End behaviour of $f(x)=x^4$?\soln Even degree, $a>0$: both ends $y\to+\infty$ (up–up):` + r`\eplot{-2}{2}{-1}{9}{\addplot[exblue,very thick,domain=-1.7:1.7]{x^4};}` },
      { t: "Odd, negative", body: r`End behaviour of $f(x)=-2x^3$?\soln Odd, $a<0$ flips it: as $x\to-\infty,\ y\to+\infty$; as $x\to+\infty,\ y\to-\infty$ (up–down).` },
      { t: "Even, negative", body: r`End behaviour of $f(x)=-x^4$?\soln Even, $a<0$: both ends $y\to-\infty$ (down–down).` },
      { t: "Read a graph", body: r`A graph falls on the left and rises on the right.\soln Opposite ends ⇒ odd degree; rising on the right ⇒ $a>0$.` },
      { t: "Odd, positive", body: r`End behaviour of $f(x)=x^5$?\soln Down–up (odd, $a>0$).` },
      { t: "Even, negative", body: r`End behaviour of $f(x)=-x^2$?\soln Down–down (even, $a<0$).` },
      { t: "Even, positive", body: r`End behaviour of $f(x)=3x^6$?\soln Up–up (even, $a>0$).` },
      { t: "Compare shapes", body: r`How do $y=x^2$ and $y=x^4$ compare?\soln Both up–up; $x^4$ is flatter near 0 and steeper outside $[-1,1]$:` + r`\eplot{-2}{2}{-1}{9}{\addplot[exblue,very thick,domain=-2.9:2.9]{x^2};\addplot[qorange,very thick,domain=-1.7:1.7]{x^4};}` },
    ],
    questions: [
      { ask: r`End behaviour of $f(x)=x^7$?` },
      { ask: r`End behaviour of $f(x)=-x^6$?` },
      { ask: r`End behaviour of $f(x)=2x^4$?` },
      { ask: r`End behaviour of $f(x)=-5x^3$?` },
      { ask: r`A graph rises on both ends. Even or odd degree?` },
      { ask: r`End behaviour of $f(x)=x^3$?` },
      { ask: r`End behaviour of $f(x)=-x^5$?` },
      { ask: r`End behaviour of $f(x)=4x^2$?` },
      { ask: r`A graph falls on both ends. Sign of $a$?` },
      { ask: r`End behaviour of $f(x)=-2x^6$?` },
      { ask: r`Does $f(x)=x^4$ open up or down?` },
      { ask: r`A cubic with $a<0$: describe its ends.` },
      { ask: r`A polynomial has ends up–down. State the degree parity and sign of $a$.`, challenge: true, ws: "2.6cm" },
    ],
    answers: [r`down–up`, r`down–down`, r`up–up`, r`up–down`, r`even`, r`down–up`, r`up–down`, r`up–up`, r`$a<0$`, r`down–down`, r`up`, r`up–down`, r`odd, $a<0$`],
  },
  {
    code: "1.2", unit: U, title: "Characteristics of Polynomial Functions",
    intro: r`Degree $n$ limits the graph: at most $n$ zeros and $n-1$ turning points; the $n$-th finite differences are constant.`,
    ideas: [r`At most $n$ x-intercepts and $n-1$ turning points.`, r`The $n$-th differences of a degree-$n$ polynomial are constant.`, r`Even: $f(-x)=f(x)$ (y-axis). Odd: $f(-x)=-f(x)$ (origin).`],
    examples: [
      { t: "Turning points", body: r`Max turning points of a degree-5 polynomial?\soln $n-1=5-1=4$.` },
      { t: "x-intercepts", body: r`Max x-intercepts of a degree-4 polynomial?\soln At most $n=4$.` },
      { t: "Degree from differences", body: r`The 3rd finite differences are constant. Degree?\soln $n$-th differences constant ⇒ degree $n$, so $3$.` },
      { t: "Even function", body: r`Classify $f(x)=x^4-3x^2+1$.\soln Only even powers ⇒ $f(-x)=f(x)$: even (y-axis symmetry).` },
      { t: "Odd function", body: r`Classify $f(x)=x^3-4x$.\soln Only odd powers ⇒ $f(-x)=-f(x)$: odd (origin symmetry).` },
      { t: "A cubic's graph", body: r`A cubic $y=x^3-3x$ has how many turning points and zeros?\soln 2 turning points (at $x=\pm1$) and 3 zeros — the maxima for degree 3:` + r`\eplot{-3}{3}{-4}{4}{\addplot[exblue,very thick,domain=-2.1:2.1]{x^3-3*x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-1,2) (1,-2)};}` },
      { t: "Minimum degree", body: r`A polynomial has 4 turning points. Minimum degree?\soln Turning points $\le n-1$, so $n\ge5$.` },
      { t: "Degree from differences", body: r`The 2nd differences are constant. Degree?\soln $2$.` },
      { t: "Neither", body: r`Classify $f(x)=x^3+x^2$.\soln Mixed even and odd powers ⇒ neither.` },
    ],
    questions: [
      { ask: r`Max turning points of a degree-4 polynomial?` },
      { ask: r`Max x-intercepts of a degree-6 polynomial?` },
      { ask: r`The 4th differences are constant. Degree?` },
      { ask: r`Is $f(x)=x^6-x^2$ even, odd, or neither?` },
      { ask: r`Is $f(x)=x^5-x^3$ even, odd, or neither?` },
      { ask: r`Max turning points of a degree-7 polynomial?` },
      { ask: r`A polynomial has 5 turning points. Minimum degree?` },
      { ask: r`The 1st differences are constant. Degree?` },
      { ask: r`Is $f(x)=x^4+x$ even, odd, or neither?` },
      { ask: r`Max x-intercepts of a degree-3 polynomial?` },
      { ask: r`Symmetry of an even function?` },
      { ask: r`Symmetry of an odd function?` },
      { ask: r`A degree-4 polynomial has exactly 1 turning point — is that possible? Explain.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`3`, r`6`, r`4`, r`even`, r`odd`, r`6`, r`6`, r`1`, r`neither`, r`3`, r`y-axis`, r`origin`, r`yes (it need not reach the maximum of 3)`],
  },
  {
    code: "1.3", unit: U, title: "Equations & Graphs of Polynomial Functions",
    intro: r`In factored form $f(x)=a(x-r_1)^{m_1}\cdots$, the zeros are $r_i$ and the multiplicities $m_i$ control how the graph meets the x-axis.`,
    ideas: [r`Zeros: set each factor to $0$.`, r`Odd multiplicity crosses; even multiplicity touches and turns.`, r`y-intercept $=f(0)$; find $a$ from one extra point.`],
    examples: [
      { t: "Zeros", body: r`Zeros of $f(x)=(x-3)(x+1)(x-2)$?\soln Set each factor to 0: $x=3,-1,2$.` },
      { t: "Multiplicity", body: r`How does $f(x)=(x+2)(x-1)^2$ meet the x-axis?\soln At $x=-2$ (mult 1) it crosses; at $x=1$ (mult 2) it touches:` + r`\eplot{-4}{3}{-6}{6}{\addplot[exblue,very thick,domain=-2.4:1.9]{(x+2)*(x-1)^2};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-2,0) (1,0)};}` },
      { t: "y-intercept", body: r`y-intercept of $f(x)=(x-1)(x+2)(x-3)$?\soln $f(0)=(-1)(2)(-3)=6$, so $(0,6)$.` },
      { t: "Build an equation", body: r`Write a cubic with zeros $-1,0,2$.\soln $f(x)=a\,x(x+1)(x-2)$; e.g. $y=x(x+1)(x-2)$.` },
      { t: "Find a", body: r`A cubic has zeros $1,2,3$ and passes through $(0,12)$. Find $a$.\soln $12=a(0-1)(0-2)(0-3)=a(-6)\Rightarrow a=-2$.` },
      { t: "Zeros with multiplicity", body: r`Zeros of $f(x)=(x-4)(x+2)^2$ and behaviour?\soln $x=4$ (cross), $x=-2$ (touch).` },
      { t: "Cross or touch", body: r`At $x=3$ in $(x-3)^2(x+1)$?\soln Even multiplicity (2): touches.` },
      { t: "y-intercept", body: r`y-intercept of $(x-2)(x+1)(x-4)$?\soln $(-2)(1)(-4)=8$.` },
      { t: "Build an equation", body: r`Write a polynomial with zeros $-3$ and $2$.\soln $y=a(x+3)(x-2)$.` },
    ],
    questions: [
      { ask: r`Zeros of $f(x)=(x-4)(x+2)(x-1)$?` },
      { ask: r`At $x=3$ in $(x-3)^2(x+1)$, cross or touch?` },
      { ask: r`y-intercept of $(x-2)(x+1)(x-4)$?` },
      { ask: r`Write a polynomial with zeros $-3$ and $2$.` },
      { ask: r`A quadratic has zeros $1,5$ and passes through $(0,10)$. Find $a$.` },
      { ask: r`Zeros of $f(x)=x(x-3)(x+5)$?` },
      { ask: r`At $x=-2$ in $(x+2)^3$, cross or touch?` },
      { ask: r`y-intercept of $(x+1)(x-2)(x+3)$?` },
      { ask: r`Write a cubic with zeros $0,2,-2$.` },
      { ask: r`A cubic has zeros $-1,1,2$ and passes through $(0,4)$. Find $a$.` },
      { ask: r`Zeros of $f(x)=(x-5)^2(x+1)$ and their behaviour?` },
      { ask: r`y-intercept of $x(x-1)(x+4)$?` },
      { ask: r`Sketch the sign of $(x+1)(x-2)^2$ across the number line.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$4,-2,1$`, r`touch`, r`$8$`, r`$y=a(x+3)(x-2)$`, r`$a=2$`, r`$0,3,-5$`, r`cross (odd mult 3)`, r`$(0,6)$`, r`$y=ax(x-2)(x+2)$`, r`$a=-2$`, r`$5$ (touch), $-1$ (cross)`, r`$0$`, r`neg, then pos for $x>-1$ (touches at 2)`],
  },
  {
    code: "1.4", unit: U, title: "Transformations of Functions",
    intro: r`Apply $g(x)=a\,f\big(k(x-d)\big)+c$ to the parent $f(x)=x^n$.`,
    ideas: [r`$a$: vertical stretch/reflection. $k$: horizontal stretch/reflection.`, r`$d$: horizontal shift (opposite to the sign). $c$: vertical shift.`, r`Stretches/reflections first, then translations.`],
    examples: [
      { t: "Describe", body: r`Describe $y=2(x-1)^3+3$ from $y=x^3$.\soln $a=2$ stretch; $d=1$ right; $c=3$ up — centred at $(1,3)$:` + r`\eplot{-2}{4}{-6}{12}{\addplot[exblue,very thick,domain=-0.4:2.4]{2*(x-1)^3+3};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(1,3)};}` },
      { t: "Reflection", body: r`Describe $y=-x^4$.\soln $a=-1$: reflection in the x-axis (opens down).` },
      { t: "Horizontal stretch", body: r`What does $k=2$ do in $y=(2x)^3$?\soln Horizontal compression by $\tfrac12$ (squeezed toward the y-axis).` },
      { t: "Map a point", body: r`$(1,1)$ on $y=x^3$ maps where on $y=(x-2)^3+4$?\soln Right 2, up 4: $(3,5)$.` },
      { t: "Write the equation", body: r`Write $y=x^4$ reflected, left 1, down 2.\soln $a=-1,\ d=-1,\ c=-2$: $y=-(x+1)^4-2$.` },
      { t: "Describe", body: r`Describe $y=(x+3)^3-1$.\soln Left 3, down 1.` },
      { t: "Map a point", body: r`$(1,1)$ on $y=x^3$ maps where on $y=x^3-5$?\soln $(1,-4)$.` },
      { t: "Stretch & reflect", body: r`Describe $y=-3x^4+2$.\soln Reflect, stretch by 3, up 2.` },
      { t: "Write the equation", body: r`Write $y=x^3$ shifted right 4 and up 1.\soln $y=(x-4)^3+1$.` },
    ],
    questions: [
      { ask: r`Describe $y=(x+3)^3-1$ from $y=x^3$.` },
      { ask: r`What does $a=-2$ do?` },
      { ask: r`Where does $(1,1)$ on $y=x^3$ map under $y=x^3-5$?` },
      { ask: r`Write $y=x^3$ shifted right 4 and up 1.` },
      { ask: r`Describe $y=-3x^4+2$.` },
      { ask: r`Write $y=x^4$ reflected, left 1 and down 2.` },
      { ask: r`Where does $(1,1)$ on $y=x^3$ map under $y=(x-2)^3+4$?` },
      { ask: r`What does $k=3$ do?` },
      { ask: r`Describe $y=2(x+1)^4$ from $y=x^4$.` },
      { ask: r`Write $y=x^3$ reflected in the x-axis.` },
      { ask: r`State the vertex-like centre of $y=(x-5)^3+2$.` },
      { ask: r`Describe $y=\tfrac12 x^3$.` },
      { ask: r`Fully describe $y=-2(x+1)^3-3$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`left 3, down 1`, r`reflect and stretch by 2`, r`$(1,-4)$`, r`$y=(x-4)^3+1$`, r`reflect, stretch 3, up 2`, r`$y=-(x+1)^4-2$`, r`$(3,5)$`, r`horizontal compression by $\tfrac13$`, r`stretch 2, left 1`, r`$y=-x^3$`, r`$(5,2)$`, r`vertical compression by $\tfrac12$`, r`reflect, stretch 2, left 1, down 3`],
  },
];
