// MHF4U Unit 2 worksheets — Polynomial Equations & Inequalities.
const r = String.raw;
const U = "2: Polynomial Equations and Inequalities";

export default [
  {
    code: "2.1", unit: U, title: "Dividing Polynomials",
    intro: r`Long division always works; synthetic division is a shortcut for dividing by $x-a$. Every result is a division statement $P(x)=D(x)Q(x)+R(x)$.`,
    ideas: [r`Long division: divide, multiply, subtract, bring down.`, r`Synthetic (by $x-a$): bring down, multiply by $a$, add.`, r`$\deg R<\deg D$; remainder $0$ means $D$ is a factor.`],
    examples: [
      { t: "Exact long division", body: r`$(x^2+5x+6)\div(x+2)$.\soln $x^2\div x=x$; subtract $x^2+2x$ → $3x+6$; $3x\div x=3$; subtract → $0$. Quotient $x+3$, R $0$. The graph confirms a zero at $x=-2$:` + r`\eplot{-5}{1}{-1}{8}{\addplot[exblue,very thick,domain=-4.6:0.6]{x^2+5*x+6};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-2,0) (-3,0)};}` },
      { t: "Exact long division", body: r`$(x^2+7x+10)\div(x+5)$.\soln Quotient $x+2$, R $0$, so $x^2+7x+10=(x+5)(x+2)$.` },
      { t: "Synthetic division", body: r`$(x^3-4x^2+x+6)\div(x-2)$.\soln Coefficients $1,-4,1,6$, root $2$: bring down $1$; $1{\cdot}2=2,\ -4{+}2=-2$; $-2{\cdot}2=-4,\ 1{-}4=-3$; $-3{\cdot}2=-6,\ 6{-}6=0$. Quotient $x^2-2x-3$, R $0$.` },
      { t: "Division statement", body: r`Write the statement for $(x^2+5x+6)\div(x+2)$.\soln $x^2+5x+6=(x+2)(x+3)+0$.` },
      { t: "Nonzero remainder", body: r`$(x^2+3x+5)\div(x+1)$.\soln Quotient $x+2$; $(x+1)(x+2)=x^2+3x+2$; subtract → $3$. So $x^2+3x+5=(x+1)(x+2)+3$.` },
      { t: "Synthetic", body: r`$(x^3-1)\div(x-1)$.\soln Coefficients $1,0,0,-1$, root $1$: $1,1,1,0$. Quotient $x^2+x+1$, R $0$.` },
      { t: "Linear over linear", body: r`$(x^2+x-6)\div(x-2)$.\soln Quotient $x+3$, R $0$, so $(x-2)(x+3)$.` },
      { t: "Remainder", body: r`$(x^2+4x+1)\div(x+1)$.\soln Quotient $x+3$, remainder $-2$: $x^2+4x+1=(x+1)(x+3)-2$.` },
      { t: "Cubic remainder", body: r`$(x^3+2x^2-5)\div(x-1)$.\soln Synthetic with root $1$ on $1,2,0,-5$: $1,3,3,-2$. Quotient $x^2+3x+3$, R $-2$.` },
    ],
    questions: [
      { ask: r`$(x^2+6x+8)\div(x+2)$?` },
      { ask: r`$(x^2+x-6)\div(x-2)$?` },
      { ask: r`Synthetic: $(x^3-1)\div(x-1)$?` },
      { ask: r`$(x^2+4x+1)\div(x+1)$, with remainder?` },
      { ask: r`Write the division statement for $(x^2+4x+1)\div(x+1)$.` },
      { ask: r`$(x^2+9x+20)\div(x+4)$?` },
      { ask: r`$(x^3-8)\div(x-2)$?` },
      { ask: r`$(x^2-5x+6)\div(x-3)$?` },
      { ask: r`$(x^3+2x^2-5)\div(x-1)$, quotient and remainder?` },
      { ask: r`Is $x+3$ a factor of $x^2+5x+6$? (use the remainder)` },
      { ask: r`$(2x^2+7x+3)\div(x+3)$?` },
      { ask: r`$(x^2+1)\div(x+1)$, remainder?` },
      { ask: r`Divide $(x^3-2x^2-5x+6)\div(x-1)$ and state quotient and remainder.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$x+4$, R 0`, r`$x+3$, R 0`, r`$x^2+x+1$, R 0`, r`$x+3$, R $-2$`, r`$(x+1)(x+3)-2$`, r`$x+5$, R 0`, r`$x^2+2x+4$, R 0`, r`$x-2$, R 0`, r`$x^2+3x+3$, R $-2$`, r`yes (R 0)`, r`$2x+1$, R 0`, r`$x-1$, R 2`, r`$x^2-x-6$, R 0`],
  },
  {
    code: "2.2", unit: U, title: "Remainder & Factor Theorems",
    intro: r`The remainder of $P(x)\div(x-a)$ is $P(a)$; and $x-a$ is a factor exactly when $P(a)=0$.`,
    ideas: [r`Remainder Theorem: remainder $=P(a)$.`, r`Factor Theorem: $x-a$ is a factor $\iff P(a)=0$.`, r`Rational Root Theorem: $\tfrac{p}{q}$ with $p\mid$ constant, $q\mid$ leading coeff.`],
    examples: [
      { t: "Find a remainder", body: r`Remainder of $P(x)=x^3-2x+1$ divided by $x-2$.\soln $P(2)=8-4+1=5$.` },
      { t: "Test a factor", body: r`Is $x-1$ a factor of $x^3-1$?\soln $P(1)=1-1=0$: yes. The graph crosses at $x=1$:` + r`\eplot{-2}{2}{-4}{4}{\addplot[exblue,very thick,domain=-1.6:1.6]{x^3-1};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(1,0)};}` },
      { t: "Sum of cubes", body: r`Is $x+2$ a factor of $x^3+8$?\soln $P(-2)=-8+8=0$: yes.` },
      { t: "Solve for k", body: r`Find $k$ so $x-1$ is a factor of $x^3+kx-2$.\soln $P(1)=1+k-2=0\Rightarrow k=1$.` },
      { t: "Find a zero", body: r`A rational zero of $P(x)=x^3-2x^2-x+2$?\soln Candidates $\pm1,\pm2$. $P(1)=1-2-1+2=0$, so $x=1$.` },
      { t: "Remainder", body: r`Remainder of $x^3+1$ divided by $x-1$.\soln $P(1)=2$.` },
      { t: "Difference of cubes", body: r`Is $x-2$ a factor of $x^3-8$?\soln $P(2)=8-8=0$: yes.` },
      { t: "Solve for k", body: r`Find $k$ so $x+1$ is a factor of $x^3+kx+4$.\soln $P(-1)=-1-k+4=0\Rightarrow k=3$.` },
      { t: "Find a zero", body: r`A rational zero of $x^3-x^2-4x+4$?\soln $P(1)=1-1-4+4=0$, so $x=1$.` },
    ],
    questions: [
      { ask: r`Remainder of $x^3+1$ divided by $x-1$?` },
      { ask: r`Is $x-2$ a factor of $x^3-8$?` },
      { ask: r`Is $x+1$ a factor of $x^3+x^2-x-1$?` },
      { ask: r`Find $k$ so $x+1$ is a factor of $x^3+kx+4$.` },
      { ask: r`A rational zero of $x^3-x^2-4x+4$?` },
      { ask: r`Remainder of $x^3-3x+2$ divided by $x-1$?` },
      { ask: r`Is $x-3$ a factor of $x^3-27$?` },
      { ask: r`Find $k$ so $x-2$ is a factor of $x^3-kx+2$.` },
      { ask: r`Remainder of $2x^3-x+5$ divided by $x+1$?` },
      { ask: r`Is $x+3$ a factor of $x^3+27$?` },
      { ask: r`List the rational-root candidates for $x^3-2x^2-5x+6$.` },
      { ask: r`Remainder of $x^4-1$ divided by $x-1$?` },
      { ask: r`Show that $x-1$ is a factor of $x^3-2x^2-x+2$, then state another factor.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$2$`, r`yes`, r`yes`, r`$k=3$`, r`$x=1$`, r`$0$`, r`yes`, r`$k=5$`, r`$4$`, r`yes`, r`$\pm1,\pm2,\pm3,\pm6$`, r`$0$`, r`$P(1)=0$; e.g. $(x-2)$ or $(x+1)$`],
  },
  {
    code: "2.3", unit: U, title: "Solving Polynomial Equations",
    intro: r`Factor fully — common factor, grouping, or the factor theorem — then set each factor to zero.`,
    ideas: [r`Take out the common factor first.`, r`Try grouping, or the factor theorem + division.`, r`A degree-$n$ polynomial has $n$ roots (with multiplicity).`],
    examples: [
      { t: "Common factor", body: r`Solve $x^3-4x=0$.\soln $x(x-2)(x+2)=0\Rightarrow x=0,2,-2$. The graph crosses at all three:` + r`\eplot{-3}{3}{-4}{4}{\addplot[exblue,very thick,domain=-2.4:2.4]{x^3-4*x};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-2,0) (0,0) (2,0)};}` },
      { t: "Factor a trinomial", body: r`Solve $x^3-2x^2-3x=0$.\soln $x(x-3)(x+1)=0\Rightarrow x=0,3,-1$.` },
      { t: "Grouping", body: r`Solve $x^3+2x^2-x-2=0$.\soln $x^2(x+2)-(x+2)=(x+2)(x-1)(x+1)=0\Rightarrow x=-2,1,-1$.` },
      { t: "Factor theorem", body: r`Solve $x^3-7x-6=0$.\soln $P(-1)=0$; divide → $(x+1)(x-3)(x+2)=0\Rightarrow x=-1,3,-2$.` },
      { t: "Quadratic in $x^2$", body: r`Solve $x^4-5x^2+4=0$.\soln $(x^2-1)(x^2-4)=0\Rightarrow x=\pm1,\pm2$.` },
      { t: "Common factor", body: r`Solve $x^3-9x=0$.\soln $x(x-3)(x+3)=0\Rightarrow x=0,3,-3$.` },
      { t: "Trinomial", body: r`Solve $x^3-x^2-2x=0$.\soln $x(x-2)(x+1)=0\Rightarrow x=0,2,-1$.` },
      { t: "Grouping", body: r`Solve $x^3+3x^2-x-3=0$.\soln $(x+3)(x-1)(x+1)=0\Rightarrow x=-3,1,-1$.` },
      { t: "Factor theorem", body: r`Solve $x^3-4x^2+x+6=0$ (hint $x=-1$).\soln $(x+1)(x-2)(x-3)=0\Rightarrow x=-1,2,3$.` },
    ],
    questions: [
      { ask: r`Solve $x^3-9x=0$.` },
      { ask: r`Solve $x^3-x^2-2x=0$.` },
      { ask: r`Solve $x^3+3x^2-x-3=0$ by grouping.` },
      { ask: r`Solve $x^3-4x^2+x+6=0$ (hint $x=-1$).` },
      { ask: r`Solve $x^4-5x^2+4=0$.` },
      { ask: r`Solve $x^3-16x=0$.` },
      { ask: r`Solve $x^3-3x^2-4x=0$.` },
      { ask: r`Solve $x^3-x=0$.` },
      { ask: r`Solve $x^4-13x^2+36=0$.` },
      { ask: r`Solve $x^3+x^2-9x-9=0$ by grouping.` },
      { ask: r`Solve $x^3-2x^2-5x+6=0$ (hint $x=1$).` },
      { ask: r`Solve $2x^3-8x=0$.` },
      { ask: r`Solve $x^3-6x^2+11x-6=0$ (hint: try $x=1$).`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$0,3,-3$`, r`$0,2,-1$`, r`$-3,1,-1$`, r`$-1,2,3$`, r`$\pm1,\pm2$`, r`$0,4,-4$`, r`$0,4,-1$`, r`$0,1,-1$`, r`$\pm2,\pm3$`, r`$-1,3,-3$`, r`$1,3,-2$`, r`$0,2,-2$`, r`$1,2,3$`],
  },
  {
    code: "2.4", unit: U, title: "Polynomial Inequalities",
    intro: r`Find the zeros, then test a point on each interval. The sign flips at odd multiplicity but not at even multiplicity.`,
    ideas: [r`Move to one side, factor, find the zeros.`, r`Test a point in each interval for the sign.`, r`Include endpoints for $\ge$ or $\le$.`],
    examples: [
      { t: "Product positive", body: r`Solve $(x-1)(x+2)>0$.\soln Zeros $1,-2$; positive outside $[-2,1]$. So $x<-2$ or $x>1$. The graph is above the axis there:` + r`\eplot{-4}{3}{-3}{6}{\addplot[exblue,very thick,domain=-3.4:2.4]{(x-1)*(x+2)};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(-2,0) (1,0)};}` },
      { t: "Product negative", body: r`Solve $(x-1)(x+2)<0$.\soln Negative on the middle interval: $-2<x<1$.` },
      { t: "Factor first", body: r`Solve $x^2-x-6>0$.\soln $(x-3)(x+2)>0$; zeros $3,-2$: $x<-2$ or $x>3$.` },
      { t: "Three factors", body: r`Solve $x(x-2)(x+1)<0$.\soln Zeros $-1,0,2$; signs $-,+,-,+$. So $x<-1$ or $0<x<2$.` },
      { t: "Even multiplicity", body: r`Solve $(x-1)^2(x+3)>0$.\soln $(x-1)^2\ge0$; sign from $x+3$ (and $x\ne1$): $x>-3,\ x\ne1$.` },
      { t: "Difference of squares", body: r`Solve $x^2-4<0$.\soln $(x-2)(x+2)<0\Rightarrow-2<x<2$.` },
      { t: "With equality", body: r`Solve $x^2-2x-3\ge0$.\soln $(x-3)(x+1)\ge0\Rightarrow x\le-1$ or $x\ge3$.` },
      { t: "Three factors", body: r`Solve $x(x-1)(x+2)>0$.\soln Zeros $-2,0,1$; signs $-,+,-,+$. So $-2<x<0$ or $x>1$.` },
      { t: "Cubic", body: r`Solve $x^3-x<0$.\soln $x(x-1)(x+1)<0$; signs $-,+,-,+$. So $x<-1$ or $0<x<1$.` },
    ],
    questions: [
      { ask: r`Solve $(x-3)(x+1)>0$.` },
      { ask: r`Solve $(x-3)(x+1)<0$.` },
      { ask: r`Solve $x^2-4<0$.` },
      { ask: r`Solve $x(x-2)(x+1)>0$.` },
      { ask: r`Solve $x^2-2x-3\ge0$.` },
      { ask: r`Solve $x^2-9>0$.` },
      { ask: r`Solve $(x+1)(x-4)<0$.` },
      { ask: r`Solve $x^3-x<0$.` },
      { ask: r`Solve $(x-2)^2(x+1)>0$.` },
      { ask: r`Solve $x^2-5x+6\le0$.` },
      { ask: r`Solve $x(x-3)(x+2)<0$.` },
      { ask: r`Solve $x^2+x-6\ge0$.` },
      { ask: r`Solve $x(x-1)(x-2)(x+1)>0$ using a sign chart.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$x<-1$ or $x>3$`, r`$-1<x<3$`, r`$-2<x<2$`, r`$-1<x<0$ or $x>2$`, r`$x\le-1$ or $x\ge3$`, r`$x<-3$ or $x>3$`, r`$-1<x<4$`, r`$x<-1$ or $0<x<1$`, r`$x>-1,\ x\ne2$`, r`$2\le x\le3$`, r`$x<-2$ or $0<x<3$`, r`$x\le-3$ or $x\ge2$`, r`$x<-1$ or $0<x<1$ or $x>2$`],
  },
];
