// MHF4U Unit 4 worksheets — Exponential & Logarithmic Functions.
const r = String.raw;
const U = "4: Exponential and Logarithmic Functions";

// pgfplots: log base b is ln(x)/ln(b). Exponential 2^x, 0.5^x render directly.
const expPlot = r`\eplot{-3}{3}{-1}{9}{\addplot[exblue,very thick,domain=-3:3.1,samples=80]{2^x};}`;
const logPlot = r`\eplot{0}{8}{-4}{4}{\addplot[exblue,very thick,domain=0.08:8,samples=140]{ln(x)/ln(2)};}`;
const invPlot = r`\eplot{-4}{8}{-4}{8}{\addplot[exblue,very thick,domain=-4:3,samples=80]{2^x};\addplot[qorange,very thick,domain=0.08:8,samples=140]{ln(x)/ln(2)};\addplot[gray,dashed,domain=-4:8]{x};}`;
const gdPlot = r`\eplot{-3}{3}{-1}{9}{\addplot[exblue,very thick,domain=-3:3.1,samples=80]{2^x};\addplot[qorange,very thick,domain=-3.1:3,samples=80]{0.5^x};}`;

export default [
  {
    code: "4.1", unit: U, title: "Logarithms & the Laws of Logarithms",
    intro: r`A logarithm answers "what exponent?": $\log_b x=y\iff b^y=x$. The laws turn products, quotients and powers into sums, differences and multiples.`,
    ideas: [r`$\log_b x=y\iff b^y=x$.`, r`Product $\log_b(xy)=\log_b x+\log_b y$; Quotient subtracts; Power $\log_b(x^n)=n\log_b x$.`, r`Change of base: $\log_b x=\dfrac{\log x}{\log b}$.`],
    examples: [
      { t: "Evaluate", body: r`Find $\log_2 8$.\soln $2^3=8$, so $\log_2 8=3$. The exponential $y=2^x$ is the inverse:` + expPlot },
      { t: "Convert to log form", body: r`Write $10^3=1000$ in logarithmic form.\soln Base 10, exponent 3: $\log 1000=3$.` },
      { t: "Evaluate", body: r`Find $\log_5 25$.\soln $5^2=25$, so $2$.` },
      { t: "Product law", body: r`Simplify $\log_2(4\cdot8)$.\soln $\log_2 4+\log_2 8=2+3=5$.` },
      { t: "Power law", body: r`Simplify $\log_2(8^2)$.\soln $2\log_2 8=2\cdot3=6$.` },
      { t: "Evaluate", body: r`Find $\log_3 27$.\soln $3^3=27$, so $3$.` },
      { t: "Base 10", body: r`Find $\log 100$.\soln $10^2=100$, so $2$.` },
      { t: "Quotient law", body: r`Simplify $\log_2\dfrac{32}{4}$.\soln $\log_2 32-\log_2 4=5-2=3$.` },
      { t: "Change of base", body: r`Express $\log_2 10$ with base-10 logs.\soln $\log_2 10=\dfrac{\log 10}{\log 2}\approx3.32$.` },
    ],
    questions: [
      { ask: r`Evaluate $\log_2 16$.` },
      { ask: r`Write $2^5=32$ in log form.` },
      { ask: r`Evaluate $\log 1000$.` },
      { ask: r`Simplify $\log_3(9\cdot27)$.` },
      { ask: r`Simplify $\log_5(25^3)$.` },
      { ask: r`Evaluate $\log_4 64$.` },
      { ask: r`Simplify $\log_2\dfrac{64}{8}$.` },
      { ask: r`Evaluate $\log_2 1$.` },
      { ask: r`Express $\log_3 20$ with base-10 logs.` },
      { ask: r`Simplify $\log_b b^7$.` },
      { ask: r`Evaluate $\log_{10} 0.01$.` },
      { ask: r`Simplify $\log 2+\log 5$.` },
      { ask: r`Write $\log_2 40$ as a sum/difference of $\log_2 2,\log_2 5$ (note $40=2^3\cdot5$).`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$4$`, r`$\log_2 32=5$`, r`$3$`, r`$2+3=5$`, r`$3\cdot2=6$`, r`$3$`, r`$6-3=3$`, r`$0$`, r`$\dfrac{\log20}{\log3}$`, r`$7$`, r`$-2$`, r`$\log10=1$`, r`$3+\log_2 5$`],
  },
  {
    code: "4.2", unit: U, title: "Graphs of Logarithmic Functions",
    intro: r`$y=\log_b x$ is the reflection of $y=b^x$ in $y=x$: vertical asymptote $x=0$, domain $x>0$, range all reals, through $(1,0)$.`,
    ideas: [r`VA at $x=0$; domain $x>0$; range all reals.`, r`Passes through $(1,0)$; increasing for $b>1$.`, r`$y=\log_b(x-d)$ shifts the VA to $x=d$.`],
    examples: [
      { t: "The log graph", body: r`Sketch $y=\log_2 x$.\soln VA $x=0$, through $(1,0)$, increasing:` + logPlot },
      { t: "Domain", body: r`Domain of $y=\log x$?\soln Argument $>0$: $x>0$.` },
      { t: "Inverse pair", body: r`How are $y=2^x$ and $y=\log_2 x$ related?\soln They are inverses — mirror images across $y=x$:` + invPlot },
      { t: "Vertical asymptote", body: r`VA of $y=\log x$?\soln As $x\to0^+,\ y\to-\infty$: $x=0$.` },
      { t: "Key point", body: r`What point is on every $y=\log_b x$?\soln $\log_b 1=0$, so $(1,0)$.` },
      { t: "Transformation", body: r`VA of $y=\log(x-2)$?\soln $x-2>0\Rightarrow x>2$, so VA $x=2$.` },
      { t: "Range", body: r`Range of $y=\log x$?\soln All real numbers.` },
      { t: "Inverse", body: r`Inverse of $y=3^x$?\soln $y=\log_3 x$.` },
      { t: "Transformation", body: r`VA of $y=\log(x+3)$?\soln $x>-3$, so VA $x=-3$.` },
    ],
    questions: [
      { ask: r`Domain of $y=\log_2 x$?` },
      { ask: r`VA of $y=\log(x+3)$?` },
      { ask: r`What is $\log_b 1$?` },
      { ask: r`Is $y=\log_2 x$ increasing or decreasing?` },
      { ask: r`Inverse of $y=3^x$?` },
      { ask: r`Range of $y=\log x$?` },
      { ask: r`VA of $y=\log(x-5)$?` },
      { ask: r`Domain of $y=\log(x-1)$?` },
      { ask: r`Through which point does $y=\log_5 x$ pass on the x-axis?` },
      { ask: r`Inverse of $y=10^x$?` },
      { ask: r`VA of $y=\log(x)+4$?` },
      { ask: r`As $x\to0^+$, what does $y=\log x$ do?` },
      { ask: r`State the domain, range, VA and a key point of $y=\log_2(x-1)$.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$x>0$`, r`$x=-3$`, r`$0$`, r`increasing`, r`$y=\log_3 x$`, r`all reals`, r`$x=5$`, r`$x>1$`, r`$(1,0)$`, r`$y=\log x$`, r`$x=0$`, r`$\to-\infty$`, r`domain $x>1$, range all reals, VA $x=1$, point $(2,0)$`],
  },
  {
    code: "4.3", unit: U, title: "Solving Exponential & Logarithmic Equations",
    intro: r`Match bases and set exponents equal, or take logs of both sides; for log equations rewrite in exponential form and check the argument is positive.`,
    ideas: [r`Same base: $b^{f}=b^{g}\Rightarrow f=g$.`, r`Different bases: $b^x=c\Rightarrow x=\dfrac{\log c}{\log b}$.`, r`$\log_b x=k\Rightarrow x=b^k$; reject non-positive arguments.`],
    examples: [
      { t: "Same base", body: r`Solve $2^x=8$.\soln $2^x=2^3\Rightarrow x=3$. Read across $y=2^x$ at height 8:` + expPlot },
      { t: "Same base", body: r`Solve $3^x=81$.\soln $3^x=3^4\Rightarrow x=4$.` },
      { t: "Take logs", body: r`Solve $2^x=10$.\soln $x=\dfrac{\log10}{\log2}\approx3.32$.` },
      { t: "Log equation", body: r`Solve $\log_2 x=5$.\soln $x=2^5=32$.` },
      { t: "Log equation", body: r`Solve $\log(x-1)=1$.\soln $x-1=10^1\Rightarrow x=11$ (valid).` },
      { t: "Same base", body: r`Solve $5^x=125$.\soln $5^x=5^3\Rightarrow x=3$.` },
      { t: "Log equation", body: r`Solve $\log_3 x=4$.\soln $x=3^4=81$.` },
      { t: "Rewrite first", body: r`Solve $2^{x+1}=16$.\soln $2^{x+1}=2^4\Rightarrow x+1=4\Rightarrow x=3$.` },
      { t: "Take logs", body: r`Solve $3^x=20$.\soln $x=\dfrac{\log20}{\log3}\approx2.73$.` },
    ],
    questions: [
      { ask: r`Solve $2^x=16$.` },
      { ask: r`Solve $5^x=125$.` },
      { ask: r`Solve $3^x=20$ (2 d.p.).` },
      { ask: r`Solve $\log_3 x=4$.` },
      { ask: r`Solve $\log(x+2)=1$.` },
      { ask: r`Solve $4^x=64$.` },
      { ask: r`Solve $2^{x-1}=32$.` },
      { ask: r`Solve $\log_2 x=6$.` },
      { ask: r`Solve $10^x=500$ (2 d.p.).` },
      { ask: r`Solve $\log(x-4)=2$.` },
      { ask: r`Solve $3^{2x}=81$.` },
      { ask: r`Solve $\log_5 x=2$.` },
      { ask: r`Solve $2^{x}=50$ to two decimal places, showing the log step.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$x=4$`, r`$x=3$`, r`$x\approx2.73$`, r`$x=81$`, r`$x=8$`, r`$x=3$`, r`$x=6$`, r`$x=64$`, r`$x\approx2.70$`, r`$x=104$`, r`$x=2$`, r`$x=25$`, r`$x=\tfrac{\log50}{\log2}\approx5.64$`],
  },
  {
    code: "4.4", unit: U, title: "Applications of Exponential & Log Models",
    intro: r`Model with $A=A_0\,b^{t/p}$ (growth $b>1$, decay $0<b<1$); use logs for doubling time and half-life; log scales (pH, dB, Richter) step by factors of ten.`,
    ideas: [r`$A=A_0\,b^{t/p}$, where $p$ is the doubling time or half-life.`, r`Doubling time $=\dfrac{\log2}{\log(\text{growth factor})}$.`, r`$\text{pH}=-\log[\text{H}^+]$; each Richter step is $\times10$.`],
    examples: [
      { t: "Growth", body: r`$P=100\cdot2^{t/5}$. Find $P$ at $t=10$.\soln $P=100\cdot2^{2}=400$. Growth $2^x$ vs decay $0.5^x$:` + gdPlot },
      { t: "Half-life", body: r`$A=80(\tfrac12)^{t/3}$. Find $A$ at $t=6$.\soln $A=80\cdot(\tfrac12)^2=80\cdot\tfrac14=20$ mg.` },
      { t: "Doubling time", body: r`How long to double at 5\% /yr?\soln $2=1.05^t\Rightarrow t=\dfrac{\log2}{\log1.05}\approx14.2$ yr.` },
      { t: "pH scale", body: r`Find the pH if $[\text{H}^+]=10^{-4}$.\soln $\text{pH}=-\log(10^{-4})=4$.` },
      { t: "Richter scale", body: r`How much stronger is magnitude 7 than magnitude 5?\soln Difference $2\Rightarrow10^2=100\times$.` },
      { t: "Growth", body: r`$P=200\cdot2^{t/4}$. Find $P$ at $t=8$.\soln $200\cdot2^2=800$.` },
      { t: "Half-life", body: r`$A=160(\tfrac12)^{t/5}$. Find $A$ at $t=10$.\soln $160\cdot\tfrac14=40$.` },
      { t: "Doubling time", body: r`How long to double at 10\% /yr?\soln $\dfrac{\log2}{\log1.1}\approx7.3$ yr.` },
      { t: "pH scale", body: r`Find the pH if $[\text{H}^+]=10^{-7}$.\soln pH $=7$.` },
    ],
    questions: [
      { ask: r`$P=300\cdot2^{t/6}$. Find $P$ at $t=12$.` },
      { ask: r`$A=240(\tfrac12)^{t/4}$. Find $A$ at $t=8$.` },
      { ask: r`How long to double at 8\% /yr (2 d.p.)?` },
      { ask: r`pH if $[\text{H}^+]=10^{-3}$?` },
      { ask: r`How much stronger is magnitude 6 than magnitude 3?` },
      { ask: r`$P=100\cdot2^{t/10}$. Find $P$ at $t=20$.` },
      { ask: r`$A=64(\tfrac12)^{t/2}$. Find $A$ at $t=6$.` },
      { ask: r`How long to triple at 5\% /yr (2 d.p.)?` },
      { ask: r`pH if $[\text{H}^+]=10^{-9}$?` },
      { ask: r`A quake is $10^4$ times stronger than another. What is the magnitude difference?` },
      { ask: r`$P=50\cdot3^{t/5}$. Find $P$ at $t=5$.` },
      { ask: r`How long for 5\% /yr growth to reach 1.5 times the start (2 d.p.)?` },
      { ask: r`Bacteria double every 3 h from 500. Write the model and find the count at $t=9$ h.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$1200$`, r`$60$`, r`$\tfrac{\log2}{\log1.08}\approx9.01$ yr`, r`$3$`, r`$1000\times$`, r`$400$`, r`$8$`, r`$\tfrac{\log3}{\log1.05}\approx22.52$ yr`, r`$9$`, r`$4$`, r`$150$`, r`$\tfrac{\log1.5}{\log1.05}\approx8.31$ yr`, r`$P=500\cdot2^{t/3}$, $P(9)=4000$`],
  },
];
