// MHF4U Unit 6 worksheets — Trigonometric Identities & Equations.
const r = String.raw;
const U = "6: Trigonometric Identities and Equations";

const trig = (body, ymin = -1.6, ymax = 1.6) =>
  `\\begin{center}\\begin{tikzpicture}\\begin{axis}[width=9.2cm,height=4.6cm,axis lines=middle,xlabel={\\small$x$},ylabel={\\small$y$},xmin=-0.4,xmax=6.9,ymin=${ymin},ymax=${ymax},samples=220,xtick={1.5708,3.1416,4.7124,6.2832},xticklabels={$\\frac{\\pi}{2}$,$\\pi$,$\\frac{3\\pi}{2}$,$2\\pi$}]${body}\\end{axis}\\end{tikzpicture}\\end{center}`;
const sin2Plot = trig(r`\addplot[exblue,very thick,domain=0:6.4]{sin(deg(2*x))};`);
const pythPlot = trig(r`\addplot[exblue,very thick,domain=0:6.4]{(sin(deg(x)))^2+(cos(deg(x)))^2};`, -0.4, 2);
const solvePlot = trig(r`\addplot[exblue,very thick,domain=0:6.4]{sin(deg(x))};\addplot[qorange,dashed,thick,domain=0:6.4]{0.5};`);

export default [
  {
    code: "6.1", unit: U, title: "Compound Angle Formulas",
    intro: r`$\sin(A\pm B)=\sin A\cos B\pm\cos A\sin B$ and $\cos(A\pm B)=\cos A\cos B\mp\sin A\sin B$ give exact values for new angles.`,
    ideas: [r`$\sin(A\pm B)=\sin A\cos B\pm\cos A\sin B$.`, r`$\cos(A\pm B)=\cos A\cos B\mp\sin A\sin B$.`, r`Write $15^\circ,75^\circ,\dots$ as sums/differences of special angles.`],
    examples: [
      { t: "Sine of a sum", body: r`Find $\sin 75^\circ=\sin(45^\circ+30^\circ)$.\soln $\sin45\cos30+\cos45\sin30=\tfrac{\sqrt6}{4}+\tfrac{\sqrt2}{4}=\dfrac{\sqrt6+\sqrt2}{4}$. Recall cos is sin shifted by $\tfrac{\pi}{2}$:` + trig(r`\addplot[exblue,very thick,domain=0:6.4]{sin(deg(x))};\addplot[qorange,very thick,domain=0:6.4]{cos(deg(x))};`) },
      { t: "Cosine of a sum", body: r`Find $\cos 75^\circ$.\soln $\cos45\cos30-\sin45\sin30=\dfrac{\sqrt6-\sqrt2}{4}$.` },
      { t: "Difference", body: r`Find $\sin 15^\circ=\sin(45^\circ-30^\circ)$.\soln $\sin45\cos30-\cos45\sin30=\dfrac{\sqrt6-\sqrt2}{4}$.` },
      { t: "Recognize the pattern", body: r`Simplify $\cos x\cos y+\sin x\sin y$.\soln This is $\cos(x-y)$.` },
      { t: "Use given values", body: r`$\sin A=\tfrac35,\cos A=\tfrac45,\sin B=\tfrac5{13},\cos B=\tfrac{12}{13}$. Find $\sin(A+B)$.\soln $\tfrac35\cdot\tfrac{12}{13}+\tfrac45\cdot\tfrac5{13}=\tfrac{36+20}{65}=\dfrac{56}{65}$.` },
      { t: "Cosine difference", body: r`Find $\cos 15^\circ$.\soln $\cos45\cos30+\sin45\sin30=\dfrac{\sqrt6+\sqrt2}{4}$.` },
      { t: "Recognize", body: r`Simplify $\sin x\cos y+\cos x\sin y$.\soln $\sin(x+y)$.` },
      { t: "Recognize", body: r`Simplify $\cos x\cos y-\sin x\sin y$.\soln $\cos(x+y)$.` },
      { t: "Use given values", body: r`With the Example-5 values, find $\cos(A+B)$.\soln $\tfrac45\cdot\tfrac{12}{13}-\tfrac35\cdot\tfrac5{13}=\dfrac{33}{65}$.` },
    ],
    questions: [
      { ask: r`Find $\cos 15^\circ$.` },
      { ask: r`Simplify $\sin x\cos y+\cos x\sin y$.` },
      { ask: r`Simplify $\cos x\cos y-\sin x\sin y$.` },
      { ask: r`Find $\sin 105^\circ=\sin(60^\circ+45^\circ)$.` },
      { ask: r`With Example-5 values, find $\cos(A+B)$.` },
      { ask: r`Find $\cos 105^\circ=\cos(60^\circ+45^\circ)$.` },
      { ask: r`Simplify $\cos x\cos y+\sin x\sin y$.` },
      { ask: r`State the formula for $\sin(A-B)$.` },
      { ask: r`Find $\sin 75^\circ$.` },
      { ask: r`State the formula for $\cos(A+B)$.` },
      { ask: r`Simplify $\sin x\cos y-\cos x\sin y$.` },
      { ask: r`Find $\tan(A+B)$ given $\tan A=1,\tan B=\tfrac1{\sqrt3}$ (formula form).` },
      { ask: r`Use $\sin A=\tfrac35,\cos A=\tfrac45,\sin B=\tfrac5{13},\cos B=\tfrac{12}{13}$ to find $\sin(A-B)$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\tfrac{\sqrt6+\sqrt2}{4}$`, r`$\sin(x+y)$`, r`$\cos(x+y)$`, r`$\tfrac{\sqrt6+\sqrt2}{4}$`, r`$\tfrac{33}{65}$`, r`$\tfrac{\sqrt2-\sqrt6}{4}$`, r`$\cos(x-y)$`, r`$\sin A\cos B-\cos A\sin B$`, r`$\tfrac{\sqrt6+\sqrt2}{4}$`, r`$\cos A\cos B-\sin A\sin B$`, r`$\sin(x-y)$`, r`$\tfrac{1+1/\sqrt3}{1-1/\sqrt3}$`, r`$\tfrac35\cdot\tfrac{12}{13}-\tfrac45\cdot\tfrac5{13}=\tfrac{16}{65}$`],
  },
  {
    code: "6.2", unit: U, title: "Double Angle Formulas",
    intro: r`Setting $B=A$: $\sin2\theta=2\sin\theta\cos\theta$ and $\cos2\theta=\cos^2\theta-\sin^2\theta=1-2\sin^2\theta=2\cos^2\theta-1$.`,
    ideas: [r`$\sin2\theta=2\sin\theta\cos\theta$.`, r`$\cos2\theta=1-2\sin^2\theta=2\cos^2\theta-1$.`, r`$\tan2\theta=\tfrac{2\tan\theta}{1-\tan^2\theta}$.`],
    examples: [
      { t: "Sine double angle", body: r`$\sin\theta=\tfrac35,\cos\theta=\tfrac45$. Find $\sin2\theta$.\soln $2\cdot\tfrac35\cdot\tfrac45=\dfrac{24}{25}$. The graph $y=\sin2x$ completes two cycles in $2\pi$:` + sin2Plot },
      { t: "Cosine double angle", body: r`With $\sin\theta=\tfrac35$, find $\cos2\theta$.\soln $1-2\sin^2\theta=1-\tfrac{18}{25}=\dfrac7{25}$.` },
      { t: "Recognize", body: r`Simplify $2\sin x\cos x$.\soln $\sin2x$.` },
      { t: "Cosine form", body: r`Write $\cos2\theta$ using only $\cos\theta$.\soln $2\cos^2\theta-1$.` },
      { t: "Recognize", body: r`Simplify $1-2\sin^2 x$.\soln $\cos2x$.` },
      { t: "Sine double angle", body: r`$\sin\theta=\tfrac5{13},\cos\theta=\tfrac{12}{13}$. Find $\sin2\theta$.\soln $2\cdot\tfrac5{13}\cdot\tfrac{12}{13}=\dfrac{120}{169}$.` },
      { t: "Recognize", body: r`Simplify $2\cos^2 x-1$.\soln $\cos2x$.` },
      { t: "Cosine double angle", body: r`With $\cos\theta=\tfrac35$, find $\cos2\theta$.\soln $2\cdot\tfrac9{25}-1=-\dfrac7{25}$.` },
      { t: "Simplify", body: r`Simplify $\dfrac{\sin2x}{2\cos x}$.\soln $\dfrac{2\sin x\cos x}{2\cos x}=\sin x$.` },
    ],
    questions: [
      { ask: r`$\sin\theta=\tfrac5{13},\cos\theta=\tfrac{12}{13}$. Find $\sin2\theta$.` },
      { ask: r`Simplify $2\cos^2 x-1$.` },
      { ask: r`With $\cos\theta=\tfrac35$, find $\cos2\theta$.` },
      { ask: r`Simplify $\dfrac{\sin2x}{2\cos x}$.` },
      { ask: r`Simplify $\cos^2 x-\sin^2 x$.` },
      { ask: r`State $\sin2\theta$.` },
      { ask: r`Simplify $2\sin x\cos x$.` },
      { ask: r`With $\sin\theta=\tfrac45$, find $\cos2\theta$ (use $1-2\sin^2\theta$).` },
      { ask: r`Simplify $1-2\sin^2 x$.` },
      { ask: r`State the three forms of $\cos2\theta$.` },
      { ask: r`With $\sin\theta=\tfrac35,\cos\theta=\tfrac45$, find $\sin2\theta$.` },
      { ask: r`Simplify $\dfrac{2\tan x}{1-\tan^2 x}$.` },
      { ask: r`Given $\sin\theta=\tfrac35$ ($\theta$ in QI), find both $\sin2\theta$ and $\cos2\theta$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\tfrac{120}{169}$`, r`$\cos2x$`, r`$-\tfrac7{25}$`, r`$\sin x$`, r`$\cos2x$`, r`$2\sin\theta\cos\theta$`, r`$\sin2x$`, r`$-\tfrac7{25}$`, r`$\cos2x$`, r`$\cos^2\theta-\sin^2\theta=1-2\sin^2\theta=2\cos^2\theta-1$`, r`$\tfrac{24}{25}$`, r`$\tan2x$`, r`$\sin2\theta=\tfrac{24}{25},\ \cos2\theta=\tfrac7{25}$`],
  },
  {
    code: "6.3", unit: U, title: "Proving Trigonometric Identities",
    intro: r`Transform one side using the Pythagorean, quotient, and reciprocal identities until it matches the other.`,
    ideas: [r`$\sin^2\theta+\cos^2\theta=1$; $1+\tan^2\theta=\sec^2\theta$; $1+\cot^2\theta=\csc^2\theta$.`, r`$\tan\theta=\tfrac{\sin\theta}{\cos\theta}$, $\cot\theta=\tfrac{\cos\theta}{\sin\theta}$.`, r`Start with the harder side; rewrite in sines and cosines.`],
    examples: [
      { t: "Pythagorean", body: r`Prove $1-\cos^2 x=\sin^2 x$.\soln From $\sin^2 x+\cos^2 x=1$, subtract $\cos^2 x$. The sum is always $1$:` + pythPlot },
      { t: "Quotient", body: r`Prove $\tan x\cos x=\sin x$.\soln $\dfrac{\sin x}{\cos x}\cdot\cos x=\sin x$. $\checkmark$` },
      { t: "Reciprocal ratios", body: r`Prove $\dfrac{\sec x}{\csc x}=\tan x$.\soln $\dfrac{1/\cos x}{1/\sin x}=\dfrac{\sin x}{\cos x}=\tan x$. $\checkmark$` },
      { t: "Build to a known one", body: r`Prove $\csc x\tan x=\sec x$.\soln $\dfrac1{\sin x}\cdot\dfrac{\sin x}{\cos x}=\dfrac1{\cos x}=\sec x$. $\checkmark$` },
      { t: "Pythagorean form", body: r`Prove $1+\tan^2 x=\sec^2 x$.\soln Divide $\sin^2 x+\cos^2 x=1$ by $\cos^2 x$. $\checkmark$` },
      { t: "Pythagorean", body: r`Prove $1-\sin^2 x=\cos^2 x$.\soln From $\sin^2 x+\cos^2 x=1$. $\checkmark$` },
      { t: "Quotient", body: r`Prove $\cot x\sin x=\cos x$.\soln $\dfrac{\cos x}{\sin x}\cdot\sin x=\cos x$. $\checkmark$` },
      { t: "Reciprocal ratios", body: r`Prove $\dfrac{\csc x}{\sec x}=\cot x$.\soln $\dfrac{1/\sin x}{1/\cos x}=\dfrac{\cos x}{\sin x}=\cot x$. $\checkmark$` },
      { t: "Build", body: r`Prove $\sec x\cot x=\csc x$.\soln $\dfrac1{\cos x}\cdot\dfrac{\cos x}{\sin x}=\dfrac1{\sin x}=\csc x$. $\checkmark$` },
    ],
    questions: [
      { ask: r`Prove $1-\sin^2 x=\cos^2 x$.` },
      { ask: r`Prove $\cot x\sin x=\cos x$.` },
      { ask: r`Prove $\dfrac{\csc x}{\sec x}=\cot x$.` },
      { ask: r`Prove $\sec x\cot x=\csc x$.` },
      { ask: r`Prove $1+\cot^2 x=\csc^2 x$.` },
      { ask: r`Prove $\tan x\cos x=\sin x$.` },
      { ask: r`Prove $\dfrac{\sec x}{\csc x}=\tan x$.` },
      { ask: r`Prove $\sin x\sec x=\tan x$.` },
      { ask: r`Prove $\cos x\csc x=\cot x$.` },
      { ask: r`Prove $1+\tan^2 x=\sec^2 x$.` },
      { ask: r`Prove $\dfrac{1-\cos^2 x}{\sin x}=\sin x$.` },
      { ask: r`Prove $\csc x\tan x=\sec x$.` },
      { ask: r`Prove $\dfrac{\sin x}{1+\cos x}+\dfrac{1+\cos x}{\sin x}=\dfrac{2}{\sin x}$.`, challenge: true, ws: "4cm" },
    ],
    answers: [r`from $\sin^2+\cos^2=1$`, r`$\tfrac{\cos x}{\sin x}\sin x=\cos x$`, r`$\tfrac{1/\sin x}{1/\cos x}=\cot x$`, r`$\tfrac1{\cos x}\tfrac{\cos x}{\sin x}=\csc x$`, r`divide identity by $\sin^2 x$`, r`$\tfrac{\sin x}{\cos x}\cos x=\sin x$`, r`$\tfrac{1/\cos x}{1/\sin x}=\tan x$`, r`$\sin x\cdot\tfrac1{\cos x}=\tan x$`, r`$\cos x\cdot\tfrac1{\sin x}=\cot x$`, r`divide identity by $\cos^2 x$`, r`$\tfrac{\sin^2 x}{\sin x}=\sin x$`, r`$\tfrac1{\sin x}\tfrac{\sin x}{\cos x}=\sec x$`, r`common denom $\to\tfrac{\sin^2 x+(1+\cos x)^2}{\sin x(1+\cos x)}=\tfrac{2}{\sin x}$`],
  },
  {
    code: "6.4", unit: U, title: "Solving Trigonometric Equations",
    intro: r`Find all solutions on $[0,2\pi)$: isolate the ratio, find the related angle, then use CAST for each quadrant.`,
    ideas: [r`Isolate the ratio; find the related angle from a special value.`, r`Use CAST to place every solution.`, r`Quadratics: factor first; mixed: use an identity.`],
    examples: [
      { t: "Basic sine", body: r`Solve $\sin\theta=\tfrac12$ on $[0,2\pi)$.\soln Related angle $\tfrac{\pi}{6}$; sine $+$ in QI, QII: $\theta=\tfrac{\pi}{6},\tfrac{5\pi}{6}$. The wave reaches $\tfrac12$ twice:` + solvePlot },
      { t: "Cosine zero", body: r`Solve $\cos\theta=0$ on $[0,2\pi)$.\soln $\theta=\tfrac{\pi}{2},\tfrac{3\pi}{2}$.` },
      { t: "Isolate first", body: r`Solve $2\cos\theta-1=0$ on $[0,2\pi)$.\soln $\cos\theta=\tfrac12$; related $\tfrac{\pi}{3}$, $+$ in QI, QIV: $\theta=\tfrac{\pi}{3},\tfrac{5\pi}{3}$.` },
      { t: "Tangent", body: r`Solve $\tan\theta=1$ on $[0,2\pi)$.\soln Related $\tfrac{\pi}{4}$, $+$ in QI, QIII: $\theta=\tfrac{\pi}{4},\tfrac{5\pi}{4}$.` },
      { t: "Quadratic type", body: r`Solve $2\sin^2\theta-1=0$ on $[0,2\pi)$.\soln $\sin\theta=\pm\tfrac{\sqrt2}{2}$; all four quadrants: $\theta=\tfrac{\pi}{4},\tfrac{3\pi}{4},\tfrac{5\pi}{4},\tfrac{7\pi}{4}$.` },
      { t: "Basic cosine", body: r`Solve $\cos\theta=\tfrac12$ on $[0,2\pi)$.\soln $\theta=\tfrac{\pi}{3},\tfrac{5\pi}{3}$.` },
      { t: "Basic sine", body: r`Solve $\sin\theta=0$ on $[0,2\pi)$.\soln $\theta=0,\pi$.` },
      { t: "Negative value", body: r`Solve $2\sin\theta+1=0$ on $[0,2\pi)$.\soln $\sin\theta=-\tfrac12$; QIII, QIV: $\theta=\tfrac{7\pi}{6},\tfrac{11\pi}{6}$.` },
      { t: "Factor", body: r`Solve $\sin\theta(\sin\theta-1)=0$ on $[0,2\pi)$.\soln $\sin\theta=0\Rightarrow0,\pi$; $\sin\theta=1\Rightarrow\tfrac{\pi}{2}$.` },
    ],
    questions: [
      { ask: r`Solve $\cos\theta=\tfrac12$ on $[0,2\pi)$.` },
      { ask: r`Solve $\sin\theta=0$ on $[0,2\pi)$.` },
      { ask: r`Solve $2\sin\theta+1=0$ on $[0,2\pi)$.` },
      { ask: r`Solve $\tan\theta=-1$ on $[0,2\pi)$.` },
      { ask: r`Solve $\sin\theta(\sin\theta-1)=0$ on $[0,2\pi)$.` },
      { ask: r`Solve $\sin\theta=\tfrac12$ on $[0,2\pi)$.` },
      { ask: r`Solve $\cos\theta=0$ on $[0,2\pi)$.` },
      { ask: r`Solve $2\cos\theta-1=0$ on $[0,2\pi)$.` },
      { ask: r`Solve $\tan\theta=1$ on $[0,2\pi)$.` },
      { ask: r`Solve $\cos\theta=-1$ on $[0,2\pi)$.` },
      { ask: r`Solve $2\sin^2\theta-1=0$ on $[0,2\pi)$.` },
      { ask: r`Solve $\sin\theta=1$ on $[0,2\pi)$.` },
      { ask: r`Solve $2\cos^2\theta-\cos\theta=0$ on $[0,2\pi)$ by factoring.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$\tfrac{\pi}{3},\tfrac{5\pi}{3}$`, r`$0,\pi$`, r`$\tfrac{7\pi}{6},\tfrac{11\pi}{6}$`, r`$\tfrac{3\pi}{4},\tfrac{7\pi}{4}$`, r`$0,\pi,\tfrac{\pi}{2}$`, r`$\tfrac{\pi}{6},\tfrac{5\pi}{6}$`, r`$\tfrac{\pi}{2},\tfrac{3\pi}{2}$`, r`$\tfrac{\pi}{3},\tfrac{5\pi}{3}$`, r`$\tfrac{\pi}{4},\tfrac{5\pi}{4}$`, r`$\pi$`, r`$\tfrac{\pi}{4},\tfrac{3\pi}{4},\tfrac{5\pi}{4},\tfrac{7\pi}{4}$`, r`$\tfrac{\pi}{2}$`, r`$\cos\theta(2\cos\theta-1)=0\Rightarrow\tfrac{\pi}{2},\tfrac{3\pi}{2},\tfrac{\pi}{3},\tfrac{5\pi}{3}$`],
  },
];
