// MHF4U Unit 6 worksheets — Trigonometric Identities & Equations.
const r = String.raw;
const U = "6: Trigonometric Identities and Equations";

const trig = (body, ymin = -1.6, ymax = 1.6) =>
  `\\begin{center}\\begin{tikzpicture}\\begin{axis}[width=9.2cm,height=4.6cm,axis lines=middle,xlabel={\\small$x$},ylabel={\\small$y$},xmin=-0.4,xmax=6.9,ymin=${ymin},ymax=${ymax},samples=220,xtick={1.5708,3.1416,4.7124,6.2832},xticklabels={$\\frac{\\pi}{2}$,$\\pi$,$\\frac{3\\pi}{2}$,$2\\pi$}]${body}\\end{axis}\\end{tikzpicture}\\end{center}`;
const sin2Plot = trig(r`\addplot[exblue,very thick,domain=0:6.4]{sin(deg(2*x))};`);
const pythPlot = trig(r`\addplot[exblue,very thick,domain=0:6.4]{(sin(deg(x)))^2+(cos(deg(x)))^2};`, -0.4, 2);
const solvePlot = trig(r`\addplot[exblue,very thick,domain=0:6.4]{sin(deg(x))};\addplot[qorange,dashed,thick,domain=0:6.4]{0.5};`);

export default [
  {
    code: "6.1", unit: U, title: "Compound Angle Formulas",
    intro: r`$\sin(A\pm B)=\sin A\cos B\pm\cos A\sin B$ and $\cos(A\pm B)=\cos A\cos B\mp\sin A\sin B$ give exact values for new angles.`,
    ideas: [r`$\sin(A\pm B)=\sin A\cos B\pm\cos A\sin B$.`, r`$\cos(A\pm B)=\cos A\cos B\mp\sin A\sin B$.`, r`Write $15^\circ,75^\circ,\dots$ as sums/differences of special angles.`],
    examples: [
      { t: "Cosine of a sum", body: r`Find $\cos 345^\circ=\cos(300^\circ+45^\circ)$.\soln $\cos300\cos45-\sin300\sin45=\tfrac12\cdot\tfrac{\sqrt2}{2}+\tfrac{\sqrt3}{2}\cdot\tfrac{\sqrt2}{2}=\dfrac{\sqrt2+\sqrt6}{4}$. Recall cos is sin shifted by $\tfrac{\pi}{2}$:` + trig(r`\addplot[exblue,very thick,domain=0:6.4]{sin(deg(x))};\addplot[qorange,very thick,domain=0:6.4]{cos(deg(x))};`) },
      { t: "Sine of a sum", body: r`Find $\sin 285^\circ=\sin(240^\circ+45^\circ)$.\soln $\sin240\cos45+\cos240\sin45=-\tfrac{\sqrt3}{2}\cdot\tfrac{\sqrt2}{2}-\tfrac12\cdot\tfrac{\sqrt2}{2}=-\dfrac{\sqrt6+\sqrt2}{4}$.` },
      { t: "Difference", body: r`Find $\sin 15^\circ=\sin(45^\circ-30^\circ)$.\soln $\sin45\cos30-\cos45\sin30=\dfrac{\sqrt6-\sqrt2}{4}$.` },
      { t: "Recognize the pattern", body: r`Simplify $\cos x\cos y+\sin x\sin y$.\soln This is $\cos(x-y)$.` },
      { t: "Use given values", body: r`$\sin A=\tfrac8{17},\cos A=\tfrac{15}{17},\sin B=\tfrac45,\cos B=\tfrac35$. Find $\sin(A+B)$.\soln $\tfrac8{17}\cdot\tfrac35+\tfrac{15}{17}\cdot\tfrac45=\tfrac{24+60}{85}=\dfrac{84}{85}$.` },
      { t: "Tangent difference", body: r`Find $\tan 15^\circ=\tan(45^\circ-30^\circ)$.\soln $\dfrac{\tan45-\tan30}{1+\tan45\tan30}=\dfrac{1-1/\sqrt3}{1+1/\sqrt3}=\dfrac{\sqrt3-1}{\sqrt3+1}=2-\sqrt3$.` },
      { t: "Recognize", body: r`Simplify $\sin x\cos y+\cos x\sin y$.\soln $\sin(x+y)$.` },
      { t: "Recognize", body: r`Simplify $\cos x\cos y-\sin x\sin y$.\soln $\cos(x+y)$.` },
      { t: "Use given values", body: r`With the Example-5 values, find $\cos(A+B)$.\soln $\tfrac{15}{17}\cdot\tfrac35-\tfrac8{17}\cdot\tfrac45=\tfrac{45-32}{85}=\dfrac{13}{85}$.` },
    ],
    questions: [
      { ask: r`Find $\sin 345^\circ$.` },
      { ask: r`Simplify $\sin 3x\cos x+\cos 3x\sin x$.` },
      { ask: r`Simplify $\cos 5x\cos 2x-\sin 5x\sin 2x$.` },
      { ask: r`Find $\cos 285^\circ=\cos(240^\circ+45^\circ)$.` },
      { ask: r`With Example-5 values, find $\sin(A-B)$.` },
      { ask: r`Find $\cos 105^\circ=\cos(60^\circ+45^\circ)$.` },
      { ask: r`Simplify $\cos40^\circ\cos10^\circ+\sin40^\circ\sin10^\circ$.` },
      { ask: r`State the formula for $\sin(A-B)$.` },
      { ask: r`Find $\tan 75^\circ=\tan(45^\circ+30^\circ)$.` },
      { ask: r`State the formula for $\cos(A+B)$.` },
      { ask: r`Simplify $\sin80^\circ\cos20^\circ-\cos80^\circ\sin20^\circ$.` },
      { ask: r`Find $\tan(A-B)$ given $\tan A=3,\tan B=2$.` },
      { ask: r`Use $\sin A=\tfrac7{25},\cos A=\tfrac{24}{25},\sin B=\tfrac{12}{13},\cos B=\tfrac5{13}$ to find $\sin(A-B)$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\tfrac{\sqrt2-\sqrt6}{4}$`, r`$\sin4x$`, r`$\cos7x$`, r`$\tfrac{\sqrt6-\sqrt2}{4}$`, r`$-\tfrac{36}{85}$`, r`$\tfrac{\sqrt2-\sqrt6}{4}$`, r`$\cos30^\circ=\tfrac{\sqrt3}{2}$`, r`$\sin A\cos B-\cos A\sin B$`, r`$2+\sqrt3$`, r`$\cos A\cos B-\sin A\sin B$`, r`$\sin60^\circ=\tfrac{\sqrt3}{2}$`, r`$\tfrac{3-2}{1+6}=\tfrac17$`, r`$\tfrac{35-288}{325}=-\tfrac{253}{325}$`],
  },
  {
    code: "6.2", unit: U, title: "Double Angle Formulas",
    intro: r`Setting $B=A$: $\sin2\theta=2\sin\theta\cos\theta$ and $\cos2\theta=\cos^2\theta-\sin^2\theta=1-2\sin^2\theta=2\cos^2\theta-1$.`,
    ideas: [r`$\sin2\theta=2\sin\theta\cos\theta$.`, r`$\cos2\theta=1-2\sin^2\theta=2\cos^2\theta-1$.`, r`$\tan2\theta=\tfrac{2\tan\theta}{1-\tan^2\theta}$.`],
    examples: [
      { t: "Sine double angle", body: r`$\sin\theta=\tfrac8{17},\cos\theta=\tfrac{15}{17}$. Find $\sin2\theta$.\soln $2\cdot\tfrac8{17}\cdot\tfrac{15}{17}=\dfrac{240}{289}$. The graph $y=\sin2x$ completes two cycles in $2\pi$:` + sin2Plot },
      { t: "Cosine double angle", body: r`With $\sin\theta=\tfrac23$, find $\cos2\theta$.\soln $1-2\sin^2\theta=1-\tfrac89=\dfrac19$.` },
      { t: "Recognize", body: r`Simplify $2\sin 3x\cos 3x$.\soln $\sin6x$.` },
      { t: "Cosine form", body: r`Write $\cos2\theta$ using only $\sin\theta$.\soln $1-2\sin^2\theta$.` },
      { t: "Recognize", body: r`Simplify $1-2\sin^2 4x$.\soln $\cos8x$.` },
      { t: "Sine double angle", body: r`$\sin\theta=\tfrac7{25},\cos\theta=\tfrac{24}{25}$. Find $\sin2\theta$.\soln $2\cdot\tfrac7{25}\cdot\tfrac{24}{25}=\dfrac{336}{625}$.` },
      { t: "Recognize", body: r`Simplify $2\cos^2 5x-1$.\soln $\cos10x$.` },
      { t: "Cosine double angle", body: r`With $\cos\theta=\tfrac5{13}$, find $\cos2\theta$.\soln $2\cdot\tfrac{25}{169}-1=-\dfrac{119}{169}$.` },
      { t: "Simplify", body: r`Simplify $\dfrac{\sin2x}{2\sin x}$.\soln $\dfrac{2\sin x\cos x}{2\sin x}=\cos x$.` },
    ],
    questions: [
      { ask: r`$\sin\theta=\tfrac9{41},\cos\theta=\tfrac{40}{41}$. Find $\sin2\theta$.` },
      { ask: r`Simplify $2\cos^2\tfrac{x}{2}-1$.` },
      { ask: r`With $\cos\theta=\tfrac{12}{13}$, find $\cos2\theta$.` },
      { ask: r`Simplify $\dfrac{\sin2x}{\sin x}$.` },
      { ask: r`Simplify $\cos^2 3x-\sin^2 3x$.` },
      { ask: r`State $\sin2\theta$.` },
      { ask: r`Simplify $2\sin\tfrac{x}{2}\cos\tfrac{x}{2}$.` },
      { ask: r`With $\sin\theta=\tfrac34$, find $\cos2\theta$ (use $1-2\sin^2\theta$).` },
      { ask: r`Evaluate $1-2\sin^2 15^\circ$ exactly.` },
      { ask: r`State the three forms of $\cos2\theta$.` },
      { ask: r`With $\sin\theta=\tfrac{20}{29},\cos\theta=\tfrac{21}{29}$, find $\sin2\theta$.` },
      { ask: r`Simplify $\dfrac{2\tan x}{1-\tan^2 x}$.` },
      { ask: r`Given $\cos\theta=\tfrac{35}{37}$ ($\theta$ in QI), find both $\sin2\theta$ and $\cos2\theta$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$\tfrac{720}{1681}$`, r`$\cos x$`, r`$\tfrac{119}{169}$`, r`$2\cos x$`, r`$\cos6x$`, r`$2\sin\theta\cos\theta$`, r`$\sin x$`, r`$-\tfrac18$`, r`$\cos30^\circ=\tfrac{\sqrt3}{2}$`, r`$\cos^2\theta-\sin^2\theta=1-2\sin^2\theta=2\cos^2\theta-1$`, r`$\tfrac{840}{841}$`, r`$\tan2x$`, r`$\sin2\theta=\tfrac{840}{1369},\ \cos2\theta=\tfrac{1081}{1369}$`],
  },
  {
    code: "6.3", unit: U, title: "Proving Trigonometric Identities",
    intro: r`Transform one side using the Pythagorean, quotient, and reciprocal identities until it matches the other.`,
    ideas: [r`$\sin^2\theta+\cos^2\theta=1$; $1+\tan^2\theta=\sec^2\theta$; $1+\cot^2\theta=\csc^2\theta$.`, r`$\tan\theta=\tfrac{\sin\theta}{\cos\theta}$, $\cot\theta=\tfrac{\cos\theta}{\sin\theta}$.`, r`Start with the harder side; rewrite in sines and cosines.`],
    examples: [
      { t: "Pythagorean", body: r`Prove $\dfrac{\sin^2 x}{1-\cos x}=1+\cos x$.\soln $\sin^2 x=1-\cos^2 x$ (the sum below is always $1$): $\dfrac{(1-\cos x)(1+\cos x)}{1-\cos x}=1+\cos x$. $\checkmark$` + pythPlot },
      { t: "Quotient", body: r`Prove $\tan x\cos x=\sin x$.\soln $\dfrac{\sin x}{\cos x}\cdot\cos x=\sin x$. $\checkmark$` },
      { t: "Reciprocal ratios", body: r`Prove $\dfrac{\tan x}{\sin x}=\sec x$.\soln $\dfrac{\sin x/\cos x}{\sin x}=\dfrac1{\cos x}=\sec x$. $\checkmark$` },
      { t: "Build to a known one", body: r`Prove $\cot x\sec x=\csc x$.\soln $\dfrac{\cos x}{\sin x}\cdot\dfrac1{\cos x}=\dfrac1{\sin x}=\csc x$. $\checkmark$` },
      { t: "Pythagorean form", body: r`Prove $\cos^2 x\,(1+\tan^2 x)=1$.\soln $1+\tan^2 x=\sec^2 x$, so $\cos^2 x\cdot\dfrac1{\cos^2 x}=1$. $\checkmark$` },
      { t: "Difference of squares", body: r`Prove $(1-\sin x)(1+\sin x)=\cos^2 x$.\soln $1-\sin^2 x=\cos^2 x$. $\checkmark$` },
      { t: "Quotient", body: r`Prove $\cot x\sin x=\cos x$.\soln $\dfrac{\cos x}{\sin x}\cdot\sin x=\cos x$. $\checkmark$` },
      { t: "Quotient", body: r`Prove $\dfrac{\cos x}{\cot x}=\sin x$.\soln $\cos x\cdot\dfrac{\sin x}{\cos x}=\sin x$. $\checkmark$` },
      { t: "Combine", body: r`Prove $\sec x-\cos x=\sin x\tan x$.\soln $\dfrac1{\cos x}-\cos x=\dfrac{1-\cos^2 x}{\cos x}=\dfrac{\sin^2 x}{\cos x}=\sin x\cdot\dfrac{\sin x}{\cos x}$. $\checkmark$` },
    ],
    questions: [
      { ask: r`Prove $\cos^2 x-1=-\sin^2 x$.` },
      { ask: r`Prove $\cot x\tan x=1$.` },
      { ask: r`Prove $\dfrac{\cot x}{\csc x}=\cos x$.` },
      { ask: r`Prove $\dfrac{\sec x}{\tan x}=\csc x$.` },
      { ask: r`Prove $\sin^2 x\,(1+\cot^2 x)=1$.` },
      { ask: r`Prove $\dfrac{\sin x}{\tan x}=\cos x$.` },
      { ask: r`Prove $\dfrac{\csc x}{\cot x}=\sec x$.` },
      { ask: r`Prove $\sin x\sec x=\tan x$.` },
      { ask: r`Prove $\cos x\csc x=\cot x$.` },
      { ask: r`Prove $\sec^2 x-\tan^2 x=1$.` },
      { ask: r`Prove $\dfrac{1-\cos^2 x}{\sin x}=\sin x$.` },
      { ask: r`Prove $\dfrac{\cos x}{1-\sin^2 x}=\sec x$.` },
      { ask: r`Prove $\dfrac{\sin x}{1+\cos x}+\dfrac{1+\cos x}{\sin x}=\dfrac{2}{\sin x}$.`, challenge: true, ws: "4cm" },
    ],
    answers: [r`$-(1-\cos^2 x)=-\sin^2 x$`, r`$\tfrac{\cos x}{\sin x}\cdot\tfrac{\sin x}{\cos x}=1$`, r`$\tfrac{\cos x/\sin x}{1/\sin x}=\cos x$`, r`$\tfrac{1/\cos x}{\sin x/\cos x}=\tfrac1{\sin x}$`, r`$\sin^2 x\csc^2 x=1$`, r`$\sin x\cdot\tfrac{\cos x}{\sin x}=\cos x$`, r`$\tfrac{1/\sin x}{\cos x/\sin x}=\tfrac1{\cos x}$`, r`$\sin x\cdot\tfrac1{\cos x}=\tan x$`, r`$\cos x\cdot\tfrac1{\sin x}=\cot x$`, r`from $1+\tan^2 x=\sec^2 x$`, r`$\tfrac{\sin^2 x}{\sin x}=\sin x$`, r`$\tfrac{\cos x}{\cos^2 x}=\tfrac1{\cos x}$`, r`common denom $\to\tfrac{\sin^2 x+(1+\cos x)^2}{\sin x(1+\cos x)}=\tfrac{2}{\sin x}$`],
  },
  {
    code: "6.4", unit: U, title: "Solving Trigonometric Equations",
    intro: r`Find all solutions on $[0,2\pi)$: isolate the ratio, find the related angle, then use CAST for each quadrant.`,
    ideas: [r`Isolate the ratio; find the related angle from a special value.`, r`Use CAST to place every solution.`, r`Quadratics: factor first; mixed: use an identity.`],
    examples: [
      { t: "Basic sine", body: r`Solve $\sin\theta=\tfrac{\sqrt3}{2}$ on $[0,2\pi)$.\soln Related angle $\tfrac{\pi}{3}$; sine $+$ in QI, QII: $\theta=\tfrac{\pi}{3},\tfrac{2\pi}{3}$. The wave reaches $\tfrac{\sqrt3}{2}\approx0.87$ twice:` + trig(r`\addplot[exblue,very thick,domain=0:6.4]{sin(deg(x))};\addplot[qorange,dashed,thick,domain=0:6.4]{0.866};`) },
      { t: "Cosine one", body: r`Solve $\cos\theta=1$ on $[0,2\pi)$.\soln $\theta=0$ (the value $2\pi$ is excluded).` },
      { t: "Isolate first", body: r`Solve $2\cos\theta+\sqrt2=0$ on $[0,2\pi)$.\soln $\cos\theta=-\tfrac{\sqrt2}{2}$; related $\tfrac{\pi}{4}$, $-$ in QII, QIII: $\theta=\tfrac{3\pi}{4},\tfrac{5\pi}{4}$.` },
      { t: "Tangent", body: r`Solve $\tan\theta=\sqrt3$ on $[0,2\pi)$.\soln Related $\tfrac{\pi}{3}$, $+$ in QI, QIII: $\theta=\tfrac{\pi}{3},\tfrac{4\pi}{3}$.` },
      { t: "Quadratic type", body: r`Solve $4\cos^2\theta-3=0$ on $[0,2\pi)$.\soln $\cos\theta=\pm\tfrac{\sqrt3}{2}$; all four quadrants: $\theta=\tfrac{\pi}{6},\tfrac{5\pi}{6},\tfrac{7\pi}{6},\tfrac{11\pi}{6}$.` },
      { t: "Basic cosine", body: r`Solve $\cos\theta=-\tfrac12$ on $[0,2\pi)$.\soln $\theta=\tfrac{2\pi}{3},\tfrac{4\pi}{3}$.` },
      { t: "Basic tangent", body: r`Solve $\tan\theta=0$ on $[0,2\pi)$.\soln $\theta=0,\pi$.` },
      { t: "Isolate first", body: r`Solve $\sqrt2\sin\theta-1=0$ on $[0,2\pi)$.\soln $\sin\theta=\tfrac{\sqrt2}{2}$; QI, QII: $\theta=\tfrac{\pi}{4},\tfrac{3\pi}{4}$.` },
      { t: "Factor", body: r`Solve $(2\sin\theta-1)(\sin\theta+1)=0$ on $[0,2\pi)$.\soln $\sin\theta=\tfrac12\Rightarrow\tfrac{\pi}{6},\tfrac{5\pi}{6}$; $\sin\theta=-1\Rightarrow\tfrac{3\pi}{2}$.` },
    ],
    questions: [
      { ask: r`Solve $\cos\theta=\tfrac{\sqrt3}{2}$ on $[0,2\pi)$.` },
      { ask: r`Solve $\cos\theta=\tfrac{\sqrt2}{2}$ on $[0,2\pi)$.` },
      { ask: r`Solve $\sqrt3\tan\theta+1=0$ on $[0,2\pi)$.` },
      { ask: r`Solve $\tan\theta=-\sqrt3$ on $[0,2\pi)$.` },
      { ask: r`Solve $\cos\theta(2\cos\theta+1)=0$ on $[0,2\pi)$.` },
      { ask: r`Solve $\sin\theta=-1$ on $[0,2\pi)$.` },
      { ask: r`Solve $\tan\theta=\tfrac{1}{\sqrt3}$ on $[0,2\pi)$.` },
      { ask: r`Solve $2\sin\theta+\sqrt2=0$ on $[0,2\pi)$.` },
      { ask: r`Solve $4\sin^2\theta-1=0$ on $[0,2\pi)$.` },
      { ask: r`Solve $\cos\theta=-1$ on $[0,2\pi)$.` },
      { ask: r`Solve $\tan^2\theta=1$ on $[0,2\pi)$.` },
      { ask: r`Solve $\sin\theta=1$ on $[0,2\pi)$.` },
      { ask: r`Solve $2\cos^2\theta+\cos\theta-1=0$ on $[0,2\pi)$ by factoring.`, challenge: true, ws: "3.5cm" },
    ],
    answers: [r`$\tfrac{\pi}{6},\tfrac{11\pi}{6}$`, r`$\tfrac{\pi}{4},\tfrac{7\pi}{4}$`, r`$\tfrac{5\pi}{6},\tfrac{11\pi}{6}$`, r`$\tfrac{2\pi}{3},\tfrac{5\pi}{3}$`, r`$\tfrac{\pi}{2},\tfrac{3\pi}{2},\tfrac{2\pi}{3},\tfrac{4\pi}{3}$`, r`$\tfrac{3\pi}{2}$`, r`$\tfrac{\pi}{6},\tfrac{7\pi}{6}$`, r`$\tfrac{5\pi}{4},\tfrac{7\pi}{4}$`, r`$\tfrac{\pi}{6},\tfrac{5\pi}{6},\tfrac{7\pi}{6},\tfrac{11\pi}{6}$`, r`$\pi$`, r`$\tfrac{\pi}{4},\tfrac{3\pi}{4},\tfrac{5\pi}{4},\tfrac{7\pi}{4}$`, r`$\tfrac{\pi}{2}$`, r`$\tfrac{\pi}{3},\pi,\tfrac{5\pi}{3}$`],
  },
];
