// MHF4U Unit 7 worksheets — Rates of Change & Combining Functions.
const r = String.raw;
const U = "7: Rates of Change and Combining Functions";

export default [
  {
    code: "7.1", unit: U, title: "Average & Instantaneous Rate of Change",
    intro: r`The average rate of change over $[a,b]$ is the secant slope $\dfrac{f(b)-f(a)}{b-a}$; the instantaneous rate at a point is the tangent slope, estimated over a tiny interval.`,
    ideas: [r`Average rate $=\dfrac{f(b)-f(a)}{b-a}$ (secant slope).`, r`Instantaneous rate $=$ tangent slope at a point.`, r`Estimate it with a small interval like $[a,a+0.1]$.`],
    examples: [
      { t: "Average rate", body: r`Average rate of change of $f(x)=x^2$ on $[1,3]$.\soln $\dfrac{f(3)-f(1)}{3-1}=\dfrac{9-1}{2}=4$. The secant slope approaches the tangent as the interval shrinks:` + r`\eplot{-3}{3}{-1}{9}{\addplot[exblue,very thick,domain=-2.9:2.9]{x^2};\addplot[red,thick] coordinates {(1,1) (3,9)};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(1,1) (3,9)};}` },
      { t: "Average rate", body: r`Average rate of change of $f(x)=x^2$ on $[2,4]$.\soln $\dfrac{16-4}{2}=6$.` },
      { t: "Estimate instantaneous", body: r`Estimate the instantaneous rate of $f(x)=x^2$ at $x=2$ using $[2,2.1]$.\soln $\dfrac{2.1^2-2^2}{0.1}=\dfrac{4.41-4}{0.1}=4.1$ (true value $4$).` },
      { t: "Linear rate", body: r`Average rate of change of $f(x)=2x+1$ on $[0,5]$.\soln $\dfrac{11-1}{5}=2$ — constant for a line.` },
      { t: "Interpret", body: r`A car's position is $d(t)$. What is $\dfrac{d(5)-d(2)}{5-2}$?\soln The average speed over $[2,5]$.` },
      { t: "Average rate", body: r`Average rate of $f(x)=x^2$ on $[0,4]$.\soln $\dfrac{16-0}{4}=4$.` },
      { t: "Cubic", body: r`Average rate of $f(x)=x^3$ on $[1,2]$.\soln $\dfrac{8-1}{1}=7$.` },
      { t: "Estimate instantaneous", body: r`Estimate the instantaneous rate of $f(x)=x^2$ at $x=3$ using $[3,3.1]$.\soln $\dfrac{9.61-9}{0.1}=6.1\approx6$.` },
      { t: "Tangent meaning", body: r`What does a tangent line's slope measure?\soln The instantaneous rate of change at that point.` },
    ],
    questions: [
      { ask: r`Average rate of $f(x)=x^2$ on $[0,4]$?` },
      { ask: r`Average rate of $f(x)=x^3$ on $[1,2]$?` },
      { ask: r`Estimate the instantaneous rate of $f(x)=x^2$ at $x=3$ using $[3,3.1]$.` },
      { ask: r`Average rate of $f(x)=5x-2$ on $[1,4]$?` },
      { ask: r`What does the slope of a tangent line measure?` },
      { ask: r`Average rate of $f(x)=x^2$ on $[1,5]$?` },
      { ask: r`Average rate of $f(x)=x^2+1$ on $[0,3]$?` },
      { ask: r`Average rate of $f(x)=3x$ on $[2,6]$?` },
      { ask: r`Estimate the instantaneous rate of $f(x)=x^2$ at $x=1$ using $[1,1.1]$.` },
      { ask: r`Average rate of $f(x)=x^3$ on $[0,2]$?` },
      { ask: r`Does a line have a changing instantaneous rate?` },
      { ask: r`Average rate of $f(x)=-x^2$ on $[1,3]$?` },
      { ask: r`A population is $P(t)=100+t^2$. Find its average rate of growth on $[0,5]$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$4$`, r`$7$`, r`$6.1\approx6$`, r`$5$`, r`instantaneous rate of change`, r`$6$`, r`$3$`, r`$3$`, r`$2.1\approx2$`, r`$4$`, r`no (constant)`, r`$-4$`, r`$\dfrac{125-100}{5}=5$`],
  },
  {
    code: "7.2", unit: U, title: "Combining Functions",
    intro: r`Combine functions point by point: $(f\pm g)(x)=f(x)\pm g(x)$, $(fg)(x)=f(x)g(x)$, $\left(\tfrac fg\right)(x)=\dfrac{f(x)}{g(x)}$ (with $g\ne0$).`,
    ideas: [r`$(f\pm g)(x)=f(x)\pm g(x)$; $(fg)(x)=f(x)g(x)$.`, r`Domain $=$ intersection of the two domains.`, r`For $\tfrac fg$, also exclude $g(x)=0$.`],
    examples: [
      { t: "Sum", body: r`$f=x^2,\ g=x$. Find $(f+g)(x)$.\soln $x^2+x$. Graphs add point by point:` + r`\eplot{-4}{3}{-3}{9}{\addplot[gray,thick,domain=-3:3]{x^2};\addplot[gray,thick,domain=-3:3]{x};\addplot[exblue,very thick,domain=-3.5:2.6]{x^2+x};}` },
      { t: "Difference", body: r`Find $(f-g)(x)$.\soln $x^2-x$.` },
      { t: "Product", body: r`Find $(fg)(x)$.\soln $x^2\cdot x=x^3$.` },
      { t: "Quotient", body: r`Find $\left(\tfrac fg\right)(x)$ and its domain.\soln $\dfrac{x^2}{x}=x$, with $x\ne0$.` },
      { t: "Evaluate", body: r`Find $(f+g)(2)$.\soln $f(2)+g(2)=4+2=6$.` },
      { t: "Sum", body: r`$f=x+1,\ g=x-1$. Find $(f+g)(x)$.\soln $2x$.` },
      { t: "Product", body: r`Same $f,g$: find $(fg)(x)$.\soln $(x+1)(x-1)=x^2-1$.` },
      { t: "Difference", body: r`$f=x^2,\ g=3$. Find $(f-g)(x)$.\soln $x^2-3$.` },
      { t: "Evaluate", body: r`$f=x,\ g=x+2$. Find $(f+g)(3)$.\soln $3+5=8$.` },
    ],
    questions: [
      { ask: r`$f=x+1,\ g=x-1$. Find $(f+g)(x)$.` },
      { ask: r`Same $f,g$: find $(fg)(x)$.` },
      { ask: r`$f=x^2,\ g=3$. Find $(f-g)(x)$.` },
      { ask: r`$f=x,\ g=x+2$. Find $(f+g)(3)$.` },
      { ask: r`$f=x^2,\ g=x$. Find the domain of $\tfrac fg$.` },
      { ask: r`$f=2x,\ g=x^2$. Find $(f+g)(x)$.` },
      { ask: r`$f=x^2,\ g=x$. Find $(fg)(x)$.` },
      { ask: r`$f=x+3,\ g=x-3$. Find $(fg)(x)$.` },
      { ask: r`$f=x^2,\ g=x+1$. Find $(f+g)(1)$.` },
      { ask: r`$f=5,\ g=x$. Find $(f-g)(x)$.` },
      { ask: r`$f=x^3,\ g=x$. Find $\left(\tfrac fg\right)(x)$ (and restriction).` },
      { ask: r`$f=x,\ g=x$. Find $(fg)(x)$.` },
      { ask: r`$f=x^2-1,\ g=x+1$. Find $\left(\tfrac fg\right)(x)$ and state the restriction.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$2x$`, r`$x^2-1$`, r`$x^2-3$`, r`$8$`, r`$x\ne0$`, r`$x^2+2x$`, r`$x^3$`, r`$x^2-9$`, r`$3$`, r`$5-x$`, r`$x^2$, $x\ne0$`, r`$x^2$`, r`$x-1$, $x\ne-1$`],
  },
  {
    code: "7.3", unit: U, title: "Composition of Functions",
    intro: r`A composition feeds one function into another: $(f\circ g)(x)=f(g(x))$ — inner first, then outer. Order matters, and you can also decompose.`,
    ideas: [r`$(f\circ g)(x)=f(g(x))$: apply $g$ first, then $f$.`, r`Domain: $x$ in $g$'s domain and $g(x)$ in $f$'s domain.`, r`Decompose: split into an outer and inner function.`],
    examples: [
      { t: "Compose", body: r`$f=x^2,\ g=x+1$. Find $f(g(x))$.\soln Replace $f$'s input with $g(x)$: $(x+1)^2$. This is the parabola shifted left 1:` + r`\eplot{-4}{2}{-1}{9}{\addplot[exblue,very thick,domain=-4:1.9]{(x+1)^2};}` },
      { t: "Reverse order", body: r`Find $g(f(x))$.\soln $g(x^2)=x^2+1$ (different from $f(g(x))$).` },
      { t: "Evaluate", body: r`Find $f(g(2))$.\soln $g(2)=3$, then $f(3)=9$.` },
      { t: "Decompose", body: r`Write $h(x)=(x+1)^2$ as $f(g(x))$.\soln Inner $g(x)=x+1$, outer $f(x)=x^2$.` },
      { t: "Domain of a composite", body: r`$f=\sqrt x,\ g=x-3$. Find $f(g(x))$ and its domain.\soln $\sqrt{x-3}$; need $x-3\ge0$, so $x\ge3$.` },
      { t: "Compose", body: r`$f=x^2,\ g=x-2$. Find $f(g(x))$.\soln $(x-2)^2$.` },
      { t: "Reverse order", body: r`Same $f,g$: find $g(f(x))$.\soln $x^2-2$.` },
      { t: "Evaluate", body: r`$f=2x,\ g=x+3$. Find $f(g(1))$.\soln $g(1)=4,\ f(4)=8$.` },
      { t: "Decompose", body: r`Decompose $h(x)=\sqrt{x+5}$.\soln $f(x)=\sqrt x,\ g(x)=x+5$.` },
    ],
    questions: [
      { ask: r`$f=x^2,\ g=x-2$. Find $f(g(x))$.` },
      { ask: r`Same $f,g$: find $g(f(x))$.` },
      { ask: r`$f=2x,\ g=x+3$. Find $f(g(1))$.` },
      { ask: r`Decompose $h(x)=\sqrt{x+5}$.` },
      { ask: r`$f=\sqrt x,\ g=x-1$. Domain of $f(g(x))$?` },
      { ask: r`$f=x+1,\ g=x^2$. Find $f(g(x))$.` },
      { ask: r`Same $f,g$: find $g(f(x))$.` },
      { ask: r`$f=3x,\ g=x-1$. Find $f(g(2))$.` },
      { ask: r`Decompose $h(x)=(2x-1)^2$.` },
      { ask: r`$f=x^2,\ g=x+4$. Find $f(g(0))$.` },
      { ask: r`Is $f(g(x))$ usually equal to $g(f(x))$?` },
      { ask: r`$f=\tfrac1x,\ g=x-2$. Find $f(g(x))$ and the restriction.` },
      { ask: r`$f=x^2,\ g=\sqrt x$. Find $f(g(x))$ and state its domain.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$(x-2)^2$`, r`$x^2-2$`, r`$8$`, r`$f=\sqrt x,\ g=x+5$`, r`$x\ge1$`, r`$x^2+1$`, r`$(x+1)^2$`, r`$3$`, r`$f=x^2,\ g=2x-1$`, r`$16$`, r`no`, r`$\dfrac{1}{x-2}$, $x\ne2$`, r`$x$, domain $x\ge0$`],
  },
];
