// MHF4U Unit 7 worksheets — Rates of Change & Combining Functions.
const r = String.raw;
const U = "7: Rates of Change and Combining Functions";

export default [
  {
    code: "7.1", unit: U, title: "Average & Instantaneous Rate of Change",
    intro: r`The average rate of change over $[a,b]$ is the secant slope $\dfrac{f(b)-f(a)}{b-a}$; the instantaneous rate at a point is the tangent slope, estimated over a tiny interval.`,
    ideas: [r`Average rate $=\dfrac{f(b)-f(a)}{b-a}$ (secant slope).`, r`Instantaneous rate $=$ tangent slope at a point.`, r`Estimate it with a small interval like $[a,a+0.1]$.`],
    examples: [
      { t: "Average rate", body: r`Average rate of change of $f(x)=x^2-4$ on $[0,3]$.\soln $\dfrac{f(3)-f(0)}{3-0}=\dfrac{5-(-4)}{3}=3$. The secant slope approaches the tangent as the interval shrinks:\eplot{-3}{4}{-5}{7}{\addplot[exblue,very thick,domain=-2.8:3.2]{x^2-4};\addplot[red,thick] coordinates {(0,-4) (3,5)};\addplot[red,only marks,mark=*,mark size=1.6pt] coordinates {(0,-4) (3,5)};}` },
      { t: "Average rate", body: r`Average rate of change of $f(x)=3x^2$ on $[1,3]$.\soln $\dfrac{27-3}{2}=12$.` },
      { t: "Estimate instantaneous", body: r`Estimate the instantaneous rate of $f(x)=x^2$ at $x=4$ using $[4,4.1]$.\soln $\dfrac{4.1^2-4^2}{0.1}=\dfrac{16.81-16}{0.1}=8.1$ (true value $8$).` },
      { t: "Linear rate", body: r`Average rate of change of $f(x)=4x-3$ on $[1,6]$.\soln $\dfrac{21-1}{5}=4$ — constant for a line.` },
      { t: "Interpret", body: r`A car's position is $d(t)$. What is $\dfrac{d(9)-d(3)}{9-3}$?\soln The average speed over $[3,9]$.` },
      { t: "Average rate", body: r`Average rate of $f(x)=x^2$ on $[3,7]$.\soln $\dfrac{49-9}{4}=10$.` },
      { t: "Cubic", body: r`Average rate of $f(x)=x^3$ on $[2,3]$.\soln $\dfrac{27-8}{1}=19$.` },
      { t: "Estimate instantaneous", body: r`Estimate the instantaneous rate of $f(x)=x^3$ at $x=1$ using $[1,1.1]$.\soln $\dfrac{1.331-1}{0.1}=3.31\approx3$.` },
      { t: "Tangent meaning", body: r`What does a tangent line's slope measure?\soln The instantaneous rate of change at that point.` },
    ],
    questions: [
      { ask: r`Average rate of $f(x)=x^2-4x$ on $[1,5]$?` },
      { ask: r`Average rate of $f(x)=2x^3$ on $[1,2]$?` },
      { ask: r`Estimate the instantaneous rate of $f(x)=x^2$ at $x=5$ using $[5,5.1]$.` },
      { ask: r`Average rate of $f(x)=7x+1$ on $[2,5]$?` },
      { ask: r`What does the slope of a tangent line measure?` },
      { ask: r`Average rate of $f(x)=x^2$ on $[2,8]$?` },
      { ask: r`Average rate of $f(x)=x^2+1$ on $[0,3]$?` },
      { ask: r`Average rate of $f(x)=3x$ on $[2,6]$?` },
      { ask: r`Estimate the instantaneous rate of $f(x)=x^2$ at $x=6$ using $[6,6.1]$.` },
      { ask: r`Average rate of $f(x)=x^3$ on $[0,2]$?` },
      { ask: r`Does a line have a changing instantaneous rate?` },
      { ask: r`Average rate of $f(x)=-x^2$ on $[1,3]$?` },
      { ask: r`A population is $P(t)=100+t^2$. Find its average rate of growth on $[0,5]$.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$2$`, r`$14$`, r`$10.1\approx10$`, r`$7$`, r`instantaneous rate of change`, r`$10$`, r`$3$`, r`$3$`, r`$12.1\approx12$`, r`$4$`, r`no (constant)`, r`$-4$`, r`$\dfrac{125-100}{5}=5$`],
  },
  {
    code: "7.2", unit: U, title: "Combining Functions",
    intro: r`Combine functions point by point: $(f\pm g)(x)=f(x)\pm g(x)$, $(fg)(x)=f(x)g(x)$, $\left(\tfrac fg\right)(x)=\dfrac{f(x)}{g(x)}$ (with $g\ne0$).`,
    ideas: [r`$(f\pm g)(x)=f(x)\pm g(x)$; $(fg)(x)=f(x)g(x)$.`, r`Domain $=$ intersection of the two domains.`, r`For $\tfrac fg$, also exclude $g(x)=0$.`],
    examples: [
      { t: "Sum", body: r`$f=x^2,\ g=2x$. Find $(f+g)(x)$.\soln $x^2+2x$. Graphs add point by point:\eplot{-4}{3}{-3}{12}{\addplot[gray,thick,domain=-3:3]{x^2};\addplot[gray,thick,domain=-3:3]{2*x};\addplot[exblue,very thick,domain=-3.5:2.6]{x^2+2*x};}` },
      { t: "Difference", body: r`Find $(f-g)(x)$.\soln $x^2-2x$.` },
      { t: "Product", body: r`Find $(fg)(x)$.\soln $x^2\cdot2x=2x^3$.` },
      { t: "Quotient", body: r`Find $\left(\tfrac fg\right)(x)$ and its domain.\soln $\dfrac{x^2}{2x}=\dfrac x2$, with $x\ne0$.` },
      { t: "Evaluate", body: r`Find $(f+g)(2)$.\soln $f(2)+g(2)=4+4=8$.` },
      { t: "Sum", body: r`$f=x+4,\ g=x-4$. Find $(f+g)(x)$.\soln $2x$.` },
      { t: "Product", body: r`Same $f,g$: find $(fg)(x)$.\soln $(x+4)(x-4)=x^2-16$.` },
      { t: "Difference", body: r`$f=x^2,\ g=5$. Find $(f-g)(x)$.\soln $x^2-5$.` },
      { t: "Evaluate", body: r`$f=2x,\ g=x-1$. Find $(f+g)(4)$.\soln $8+3=11$.` },
    ],
    questions: [
      { ask: r`$f=x+6,\ g=x-2$. Find $(f+g)(x)$.` },
      { ask: r`Same $f,g$: find $(fg)(x)$.` },
      { ask: r`$f=x^2,\ g=7$. Find $(f-g)(x)$.` },
      { ask: r`$f=3x,\ g=x+1$. Find $(f+g)(2)$.` },
      { ask: r`$f=x^3,\ g=x-2$. Find the domain of $\tfrac fg$.` },
      { ask: r`$f=3x,\ g=x^2$. Find $(f+g)(x)$.` },
      { ask: r`$f=x^2,\ g=x+1$. Find $(fg)(x)$.` },
      { ask: r`$f=x+3,\ g=x-3$. Find $(fg)(x)$.` },
      { ask: r`$f=x^2,\ g=x+1$. Find $(f+g)(1)$.` },
      { ask: r`$f=5,\ g=x$. Find $(f-g)(x)$.` },
      { ask: r`$f=x^3,\ g=x$. Find $\left(\tfrac fg\right)(x)$ (and restriction).` },
      { ask: r`$f=x,\ g=x$. Find $(fg)(x)$.` },
      { ask: r`$f=x^2-1,\ g=x+1$. Find $\left(\tfrac fg\right)(x)$ and state the restriction.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$2x+4$`, r`$x^2+4x-12$`, r`$x^2-7$`, r`$9$`, r`$x\ne2$`, r`$x^2+3x$`, r`$x^3+x^2$`, r`$x^2-9$`, r`$3$`, r`$5-x$`, r`$x^2$, $x\ne0$`, r`$x^2$`, r`$x-1$, $x\ne-1$`],
  },
  {
    code: "7.3", unit: U, title: "Composition of Functions",
    intro: r`A composition feeds one function into another: $(f\circ g)(x)=f(g(x))$ — inner first, then outer. Order matters, and you can also decompose.`,
    ideas: [r`$(f\circ g)(x)=f(g(x))$: apply $g$ first, then $f$.`, r`Domain: $x$ in $g$'s domain and $g(x)$ in $f$'s domain.`, r`Decompose: split into an outer and inner function.`],
    examples: [
      { t: "Compose", body: r`$f=x^2,\ g=x+3$. Find $f(g(x))$.\soln Replace $f$'s input with $g(x)$: $(x+3)^2$. This is the parabola shifted left 3:\eplot{-6}{1}{-1}{16}{\addplot[exblue,very thick,domain=-5.9:0.9]{(x+3)^2};}` },
      { t: "Reverse order", body: r`Find $g(f(x))$.\soln $g(x^2)=x^2+3$ (different from $f(g(x))$).` },
      { t: "Evaluate", body: r`Find $f(g(2))$.\soln $g(2)=5$, then $f(5)=25$.` },
      { t: "Decompose", body: r`Write $h(x)=(x-5)^3$ as $f(g(x))$.\soln Inner $g(x)=x-5$, outer $f(x)=x^3$.` },
      { t: "Domain of a composite", body: r`$f=\sqrt x,\ g=2x-4$. Find $f(g(x))$ and its domain.\soln $\sqrt{2x-4}$; need $2x-4\ge0$, so $x\ge2$.` },
      { t: "Compose", body: r`$f=x^3,\ g=x+1$. Find $f(g(x))$.\soln $(x+1)^3$.` },
      { t: "Reverse order", body: r`Same $f,g$: find $g(f(x))$.\soln $x^3+1$.` },
      { t: "Evaluate", body: r`$f=5x,\ g=x-2$. Find $f(g(6))$.\soln $g(6)=4,\ f(4)=20$.` },
      { t: "Decompose", body: r`Decompose $h(x)=\sqrt{3x-1}$.\soln $f(x)=\sqrt x,\ g(x)=3x-1$.` },
    ],
    questions: [
      { ask: r`$f=x^2,\ g=x+5$. Find $f(g(x))$.` },
      { ask: r`Same $f,g$: find $g(f(x))$.` },
      { ask: r`$f=4x,\ g=x+2$. Find $f(g(2))$.` },
      { ask: r`Decompose $h(x)=\sqrt{x-8}$.` },
      { ask: r`$f=\sqrt x,\ g=x+7$. Domain of $f(g(x))$?` },
      { ask: r`$f=x-3,\ g=x^2$. Find $f(g(x))$.` },
      { ask: r`Same $f,g$: find $g(f(x))$.` },
      { ask: r`$f=3x,\ g=x-1$. Find $f(g(2))$.` },
      { ask: r`Decompose $h(x)=(2x-1)^2$.` },
      { ask: r`$f=x^2,\ g=x+4$. Find $f(g(0))$.` },
      { ask: r`Is $f(g(x))$ usually equal to $g(f(x))$?` },
      { ask: r`$f=\tfrac1x,\ g=x-2$. Find $f(g(x))$ and the restriction.` },
      { ask: r`$f=x^2,\ g=\sqrt x$. Find $f(g(x))$ and state its domain.`, challenge: true, ws: "3cm" },
    ],
    answers: [r`$(x+5)^2$`, r`$x^2+5$`, r`$16$`, r`$f=\sqrt x,\ g=x-8$`, r`$x\ge-7$`, r`$x^2-3$`, r`$(x-3)^2$`, r`$3$`, r`$f=x^2,\ g=2x-1$`, r`$16$`, r`no`, r`$\dfrac{1}{x-2}$, $x\ne2$`, r`$x$, domain $x\ge0$`],
  },
];
